### PR TITLE
Split Plugin Manager into Plugin Manager and Update Center

### PR DESCRIPTION
**Pull request by daniel-beck**
**Request for comments**: Is this even a good idea? Hence draft pull request status. Plus this probably shouldn't slip into the upcoming LTS baseline without proving itself in weeklies first.

----

This splits the functionality currently under "Plugin Manager":

* Former tabs "Updates" and "Available" are moved to "Update Center" (which previously only really had the UI for installation progress).
* Former tabs "Installed" and "Advanced" remain in "Plugin Manager".
* Tabs are converted to sidepanel items.

This isn't the end however, future planned enhancements:

* Split up the "Advanced" tab: Proxy configuration belongs in "Configure System", update site configuration belongs in a new page below "Update Center"

Ultimately this would open up the way towards an independent future for "manage the current setup" and "get new stuff". Recent enhancements to the latter showed how weird the current implementation is, something more "App Store" like seems like a reasonable enhancement, but this requires making the UI independent of the existing tab + table constraints.

I'm not _quite_ sure whether "Updates" should be in "Update Center" with "Browse Plugins", but I think this split makes the most sense, both in terms of current terminology used, as well as implementation wise. Mac OS and iOS have App Store for both updates and new stuff, while management of installed apps is elsewhere.

<details>
<summary>Screenshots</summary>

Screenshot 2020-04-19 at 19 50 59
Screenshot 2020-04-19 at 19 51 22
Screenshot 2020-04-19 at 19 51 35
Screenshot 2020-04-19 at 19 51 42

</details>

### Proposed changelog entries

* Move UI for applying updates and discovering new plugins into new Update Center.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by StefanSpieker** [comment]
I like the idea to split this up a little. I really would like to see the proxy configuration moved somewhere else. This is currently a very unexpected place for this configuration.

**Comment by daniel-beck** [comment]
> I really would like to see the proxy configuration moved somewhere else.

Definitely. This needs to move, perhaps here, perhaps in a different PR. (And with this PR as is, the location of the update site URL makes absolutely no sense anymore too.)

I'm still waiting for more feedback on the overall approach before I spend more time in this area.

**Comment by timja** [comment]
Idea is good, and completely agree with proxy, I’ll try check this out locally tomorrow and see how it feels

**Comment by daniel-beck** [comment]
FWIW there's also a potential "minimal" implementation of this that doesn't change 4000 lines but just replaces tabs with sidepanels. Resulting URLs would not change, unlike here, just their presentation.

**Comment by fqueiruga** [comment]
I believe separating the updates and installed tabs from would introduce lots of confusion on users, I'd keep them on the same page. I don't have an opinion regarding the proxy configuration.

TBH I also think tabs are far better than sidebar links. They are more visible and discoverable. Why do you see a problem with them?

This is a critical area of the Jenkins experience, I'd be very careful before changing anything, especially without actual UX data.

**Pull request closed without merging**
