### PR TITLE
[JENKINS-67858] Icons are placed higher than the text

### PR DESCRIPTION
**Pull request by Langer0416**
See [JENKINS-67858](https://issues.jenkins-ci.org/browse/JENKINS-67858).

The original span class `icon-lg` will let the new icons in the wrong position , so I create a new span class `icon-lg1`
let the new icons in the correct position . I also create the new span class `jenkins-icon-header-adjacent` to make the text
in the correct position.
 
Screenshot from 2022-02-23 07-23-05

Screenshot from 2022-02-23 07-23-30

### Proposed changelog entries

* Fix the position of icons which are at the header .

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] (If applicable) Jira issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [X] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by NotMyFault — COMMENTED** [review]
I don't think creating a new icon size class is the right approach to address this issue 🤔 

Likely, ionicons and text need a better treatment overall. I assume, the text/icon height difference applies to other occasions and plugins as well, at least in a foreseeable future, if more icons are overriden, therefore the change proposed doesn't address the underlaying issue without migrating to your new class addition.

**Review by timja — CHANGES_REQUESTED** [review]
this needs to be solved with css / markup changes not by introducing a new class in this way

**Comment by Langer0416** [comment]
I added `flex` style on h1 and `margin-right` to add space between text and icon.

**Comment by daniel-beck** [comment]
Don't we have a new tag dedicated to showing the page title? Should that be used here?

**Comment by timja** [comment]
not sure, cc @janfaracik

**Comment by janfaracik** [comment]
We do have an 'app-bar' now, pretty much a combination of a title with controls to the right of it but I haven't tried it with icons.

```
<div class="jenkins-app-bar">
  <div class="jenkins-app-bar__content">
    <img src="img" alt="alt" />
    <h1>Title</h1>
  </div>
</div>
```

I'd like to move away from icons next to titles ideally unless they convey helpful information (eg like the build status ball) otherwise they just steal focus for little benefit.

**Comment by daniel-beck** [comment]
> I'd like to move away from icons next to titles ideally unless they convey helpful information (eg like the build status ball) otherwise they just steal focus for little benefit.

Will take a long time to get there across plugins, so the CSS should account for the presence of icons without customization as in this PR.

**Comment by NotMyFault** [comment]
> > I'd like to move away from icons next to titles ideally unless they convey helpful information (eg like the build status ball) otherwise they just steal focus for little benefit.
> 
> Will take a long time to get there across plugins, so the CSS should account for the presence of icons without customization as in this PR.

Based on a quick though, couldn't it suffice to apply a vertical alignment to the newly added svg icon classes?
Considering this is a regression of the PR updating the "Manage Jenkins" icons, tango icons in core and third party icons would be unaffected by it while squashing all occasions under one hood 🤔

**Pull request closed without merging**
