### PR TITLE
Bump crypto-util from 1.1 to 1.5

### PR DESCRIPTION
**Pull request by timja**
https://github.com/jenkinsci/lib-crypto-util/releases/tag/crypto-util-1.5

full diff:
https://github.com/jenkinsci/lib-crypto-util/compare/crypto-util-1.1...crypto-util-1.5

### Proposed changelog entries

* Entry 1: Bug: Update crypto-util from 1.1 to 1.5 to fix the license link in Jenkins Web UI
  * Full changelog: https://github.com/jenkinsci/lib-crypto-util/releases 
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

### CODE REVIEW

**Review by res0nance — COMMENTED** [review]
Looks ok, is there any particular reason we want this?

**Comment by timja** [comment]
@res0nance fix license url https://github.com/jenkinsci/lib-crypto-util/pull/4

**Review by res0nance — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
I reviewed the commit history in https://github.com/jenkinsci/lib-crypto-util/compare/crypto-util-1.1...crypto-util-1.4 , and it looks OK: no breaking changes, no changes in existing methods. So it should be safe enough. Thanks @timja for stewarding the patch!

**Comment by oleg-nenashev** [comment]
@timja @darxriggs Should we just put a "" to the changelog for https://github.com/jenkinsci/lib-crypto-util/pull/4?

E.g.: 

```
Bug: Update crypto-util from 1.1 to 1.5 to fix the license link in Jenkins Web UI
  * Full changelog: https://github.com/jenkinsci/lib-crypto-util/releases 
```

**Review by darxriggs — APPROVED** [review]

**Comment by darxriggs** [comment]
I am ok with and also without an entry in the changelog.
It depends on if every change is listed there or not.

**Comment by timja** [comment]
Let’s merge this tomorrow if there’s no negative feedback

**Comment by oleg-nenashev** [comment]
@timja PTAL https://github.com/jenkinsci/jenkins/pull/4631#issuecomment-610222714

**Comment by timja** [comment]
> @timja PTAL [#4631 (comment)](https://github.com/jenkinsci/jenkins/pull/4631#issuecomment-610222714)

done

**Pull request merged**
