### PR TITLE
Fix Java11 telemetry test broken after end of its sendings (MissingClassTelemetryTest)

### PR DESCRIPTION
**Pull request by MRamonLeon**
This fixes the test error because of Java11 telemetry has reached its end, so the sendings don't take place anynmore. The test was not taking this into account, now it is.

### Proposed changelog entries

No entry required

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by alecharp — COMMENTED** [review]
We could also extend https://github.com/jenkinsci/jenkins/blob/c4e0291c502bff9c70e81d0bcf6f66c381f84546/core/src/main/java/jenkins/telemetry/impl/java11/MissingClassTelemetry.java#L72 or more drastically remove the telemetry for missing classes.

In the end, we could have a telemetry entry to see which version of the JVM is used rather than that.

**Comment by MRamonLeon** [comment]
> We could also extend
> 
> https://github.com/jenkinsci/jenkins/blob/c4e0291c502bff9c70e81d0bcf6f66c381f84546/core/src/main/java/jenkins/telemetry/impl/java11/MissingClassTelemetry.java#L72
> 
> or more drastically remove the telemetry for missing classes.
> In the end, we could have a telemetry entry to see which version of the JVM is used rather than that.

We already check if the JVM is Java11. If it's not the case, the sending doesn't take place. 

I think it's not worth it to extend it because we're not actively looking into these metrics. The PR is to unblock all PRs which are failing because of this test.

I would like to keep the discussion about to extend the sending or remove it apart.

**Review by oleg-nenashev — APPROVED** [review]
Thanks for the fix! Will merge once CI passes

**Comment by daniel-beck** [comment]
> Thanks for the fix! Will merge once CI passes

Please don't.

**Review by daniel-beck — APPROVED** [review]
Looks reasonable.

**Review by res0nance — APPROVED** [review]

**Comment by MarkEWaite** [comment]
@daniel-beck are we ready to merge this once CI passes?

**Comment by oleg-nenashev** [comment]
```
Error
Unable to obtain ChronoLocalDate from TemporalAccessor: class java.time.Instant
Stacktrace
java.time.DateTimeException: Unable to obtain ChronoLocalDate from TemporalAccessor: class java.time.Instant
	at java.base/java.time.chrono.ChronoLocalDate.from(ChronoLocalDate.java:294)
	at jenkins.telemetry.MissingClassTelemetryTest.telemetrySentWorks(MissingClassTelemetryTest.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

**Comment by MRamonLeon** [comment]
I'm getting a non-related error in MacOS BigSur with 11.0.10.j9-adpt:

```
[ERROR] Failures: 
[ERROR]   FunctionsTest.printThrowable:526->assertPrintThrowable:561 
Expected: is "p.Exc1\n\tat p.C.method1(C.java:17)\nCaused by: p.Exc2\n\tat p.C.method2(C.java:27)\nCaused by: [CIRCULAR REFERENCE: p.Exc1]\n"
     but: was "p.Exc1\n\tat p.C.method1(C.java:17)\nCaused by: p.Exc2\n\tat p.C.method2(C.java:27)\n\t[CIRCULAR REFERENCE:p.Exc1]\n"
```

Missing: `Caused by: `

Maybe because of J9 JVM?

**Comment by MarkEWaite** [comment]
> I'm getting a non-related error in MacOS BigSur with 11.0.10.j9-adpt:
> 
> ```
> [ERROR] Failures: 
> [ERROR]   FunctionsTest.printThrowable:526->assertPrintThrowable:561 
> Expected: is "p.Exc1\n\tat p.C.method1(C.java:17)\nCaused by: p.Exc2\n\tat p.C.method2(C.java:27)\nCaused by: [CIRCULAR REFERENCE: p.Exc1]\n"
>      but: was "p.Exc1\n\tat p.C.method1(C.java:17)\nCaused by: p.Exc2\n\tat p.C.method2(C.java:27)\n\t[CIRCULAR REFERENCE:p.Exc1]\n"
> ```
> 
> Missing: `Caused by: `
> 
> Maybe because of J9 JVM? Testing with `11.0.10.hs-adpt`...

We like to know that Jenkins runs with the OpenJ9 VM, but I'm not aware of anyone that is compiling or unit/integration testing Jenkins with OpenJ9.

**Comment by MRamonLeon** [comment]
It seems this time will pass:
```
[2021-04-08T17:31:43.971Z] [WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 10.86 s - in jenkins.telemetry.MissingClassTelemetryTest
```

**Pull request merged**
