### PR TITLE
[JENKINS-61455] "About Jenkins" accessible with Jenkins.MANAGE

### PR DESCRIPTION
**Pull request by amuniz**
See [JENKINS-61455](https://issues.jenkins-ci.org/browse/JENKINS-61455).

### Proposed changelog entries

* _About Jenkins_ management link is now accessible to users with
`Jenkins.MANAGE` or `Jenkins.SYSTEM_READ` (as well as the usual
`Jenkins.ADMINISTRATOR`)

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

Anyone.

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
Sounds about right

**Comment by daniel-beck** [comment]
Legitimate test failure: `hudson.AboutJenkinsTest#onlyAdminCanReadAbout` (the name explains why).

**Review by daniel-beck — CHANGES_REQUESTED** [review]
The changes to `…/thirdPartyLicenses` and `PluginWrapper#getApi` from the original PR are missing, links to plugin licenses on this page result in Access Denied.

**Comment by amuniz** [comment]
Ok, so something weird is going on here.

`permissions="${app.MANAGE_AND_SYSTEM_READ}"` seems to have no effect at all. I've run this under a debugger and it seems that the [`checkAnyPermission`](https://github.com/jenkinsci/jenkins/blob/56bce19cd6e26a4e122f761cb6fd3baf47a870e1/core/src/main/resources/lib/layout/layout.jelly#L100) call is done *before* the jelly expression (`"${app.MANAGE_AND_SYSTEM_READ}"`) is evaluated (I checked this by making it call a method instead of accessing a static field and setting a breakpoint inside that method and also in [`checkAnyPermission`](https://github.com/jenkinsci/jenkins/blob/9537ee51549dc944db687a5d3e99a0860a6bc786/core/src/main/java/hudson/Functions.java#L1167).

Does someone have any idea of what's going on here?

**Comment by amuniz** [comment]
And BTW, that test should not be failing, it is checking that `Jenkins.READ` does not have access to the About page, which is right.

**Comment by amuniz** [comment]
Requires https://github.com/jenkinsci/jenkins/pull/4573

**Comment by amuniz** [comment]
@daniel-beck care to re-review please?

**Review by varyvol — APPROVED** [review]

**Review by fcojfernandez — APPROVED** [review]

**Review by EstherAF — APPROVED** [review]

**Review by daniel-beck — APPROVED** [review]

**Pull request merged**
