### PR TITLE
[JENKINS-67198] Increase width of forms

### PR DESCRIPTION
**Pull request by janfaracik**
See [JENKINS-67198](https://issues.jenkins.io/browse/JENKINS-67198)

<details>
<summary>Screenshots</summary>

**Before at 1080p**
Screenshot 2022-01-09 at 15 43 51

**After at 1080p**
Screenshot 2022-01-09 at 15 44 01

</details>

This is a small snippet from #5923 simply to increase the max width of forms. The new max width has been updated from **650px** to **60% of screen width** _or_ **1400px**, whatever is smaller.

There will be future PRs in the coming month or so to update certain pages further to take advantage of horizontal space, an example of this is the updated job config page as shown in the November UX Sig.
<details>
<summary>Screenshot</summary>

image

</details>

There's still plenty more to do on the forms works for Jenkins so any and all feedback is appreciated :)

### Testing

    docker run --rm -ti -p 8080:8080 -e ID=6172 -e MERGE_WITH=master jenkins/core-pr-tester

### Proposed changelog entries

* Increase width of job configuration form on wide screens.

### Proposed upgrade guidelines

@timja @daniel-beck 

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by daniel-beck** [comment]
Thanks! To clarify, this is the [JENKINS-67198](https://issues.jenkins.io/browse/JENKINS-67198) regression fix as a standalone change?

**Comment by janfaracik** [comment]
> Thanks! To clarify, this is the [JENKINS-67198](https://issues.jenkins.io/browse/JENKINS-67198) regression fix as a standalone change?

If those that reported the issue are happy - yes :) I recognise the forms don't fill the page width 100% but I'm hoping they're now large enough to no longer cause people issues.

**Comment by daniel-beck** [comment]
I think there are two distinct issues here:

* The form fields are narrower than the frame around them in Jenkins 2.0+ style job config forms specifically.
* The form fields are narrow, making it difficult to work with complex inline scripts, unnecessarily so on wide screens.

As long as this addresses the former, I think we have a reasonable regression fix. People complaining about the latter have a point too though.

That said, job config forms still look weird even with this PR:


**Before in job configs**
Screenshot 2022-01-09 at 17 04 20

**After in job configs**
Screenshot 2022-01-09 at 17 03 05

**Review by oleg-nenashev — APPROVED** [review]
LGTM 👍

**Comment by janfaracik** [comment]
> I think there are two distinct issues here:
> 
> * The form fields are narrower than the frame around them in Jenkins 2.0+ style job config forms specifically.
> * The form fields are narrow, making it difficult to work with complex inline scripts, unnecessarily so on wide screens.
> 
> As long as this addresses the former, I think we have a reasonable _regression_ fix. People complaining about the latter have a point too though.
> 
> That said, job config forms still look weird even with this PR:
> 
> **Before in job configs** Screenshot 2022-01-09 at 17 04 20
> 
> **After in job configs** Screenshot 2022-01-09 at 17 03 05

I've updated the frame to be the same width as the form fields and increased the width of the form fields too a touch 👍 

image

**Review by timja — APPROVED** [review]
LGTM

**Review by daniel-beck — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by daeho-ro** [comment]
This is good.

For my case, I am using the custom script as follows:
```
.jenkins-form-item {
  max-width: 100%!important
}
```

**Pull request merged**
