### PR TITLE
Switch to building/testing with JDK8.

### PR DESCRIPTION
**Pull request by abayer**
Memory issues (suspected) are causing hanging test execution when
building/testing with JDK7u80, so at Daniel Beck's suggestion, let's
move to JDK8.

cc @reviewbybees

### CODE REVIEW

**Comment by daniel-beck** [comment]
CC @amuniz who investigated this for a while and found no evidence locally.

**Comment by jtnord** [comment]
update 51?  is there nothing more recent on the system with a huge amount of bug fixes?

reluctant :bee:

**Comment by abayer** [comment]
That's the most recent currently there - I could add a newer one if you'd like.

**Comment by jglick** [comment]
:bee:

**Pull request merged**
