### PR TITLE
[JENKINS-58520] - Make new Jenkins version notification noticeable in administrative monitors

### PR DESCRIPTION
**Pull request by jsoref**
See [JENKINS-58520](https://issues.jenkins-ci.org/browse/JENKINS-58520).

### Proposed changelog entries

* rfe, Make new Jenkins version notification noticeable in administrative monitors

### Submitter checklist

- [x] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
weak +1, IMHO was visible enough before this change

**Comment by daniel-beck** [comment]
Could we get before/after screenshots?

**Comment by jsoref** [comment]
Is there an easy way for me to trigger this using a local test instance of jenkins? Would I just patch an older version of jenkins and then its update check would trigger?

**Comment by zbynek** [comment]
One can easily change the DOM in dev tools, I think that's good enough emulation of the change:
Before:
warnings-before
After:
warnings-after

**Comment by oleg-nenashev** [comment]
Indeed it looks better after the change. Would appreciate some review votes ;)

**Review by fcojfernandez — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Will merge tomorrow if no negative feedback

**Pull request merged**
