### PR TITLE
[JENKINS-23378] Servlet 3.1

### PR DESCRIPTION
**Pull request by kohsuke**
As the last step of the work, make Jenkins servlet 3.1 app

### CODE REVIEW

**Comment by kohsuke** [comment]
Currently blocked by #2067

**Comment by kohsuke** [comment]
By merging the master, this pulled in all the changes and commit comments, so now the comment line is a mess.

**Comment by kohsuke** [comment]
@reviewbybees

This change is ready.

**Comment by stephenc** [comment]
:bee: (though it would have been better to isolate this from the master merge to give a cleaner diff)

**Pull request merged**
