### PR TITLE
Unify labels in plugin manager

### PR DESCRIPTION
**Pull request by zbynek**
* Both "api-plugin" and "library" labels were at some point used to mark plugins that do not have any user-facing functionality.  The api-plugin label is used more (69 vs 17 usages) and AFAIK is the suggested one, even though only "library" has a localized description. 
* Plugins for agent management are labeled either "slaves" (obsolete but localized) or "agent"

EDIT: My original approach was to change which labels are localized and ask plugin maintainers to update the metadata, but as Daniel pointed out, that results in compatibility issues. The current proposal is a bit more complicated, but does not require changes in plugin metadata. Canonical labels are listed in a text file that can be consumed by both Jenkins and the plugin website (plugin website pulls the detached plugin list in the same way).

### Proposed changelog entries

* Unify labels in plugin manager.  Remove deprecated terminology labels from the Plugin Manager.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [n/a] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [n/a] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@timja @daniel-beck @oleg-nenashev 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by daniel-beck** [comment]
IIUC, `library` has been the default for many years, and only got superseded by `api-plugin` with the latter's usage in SCM API, Branch API, etc. and got more popular through that usage. I would expect that older plugins tend to use the former label.

It's unclear to me why this removes support for the existing label. Why not support both, noting that one (debatable which) is only supported for compatibility, but should not be used?

**Comment by zbynek** [comment]
@daniel-beck thanks for the feedback. I pushed a new implementation that can unify the labels.
@oleg-nenashev this somehow relates to the "engine for label aliases" you proposed in https://github.com/jenkins-infra/update-center2/pull/353#issuecomment-633991973 -- the difference is that here the list of aliases is in Jenkins codebase and your proposal was to do it in UC. If we do label normalization in UC, we can get better backward/forward compatibility, but without changing Jenkins code that would mean the "official" (=used in json) label for agent management would be "slaves" forever.

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
checkstyle issue

**Review by oleg-nenashev — APPROVED** [review]
I suggest explicitly saying "Remove deprecated terminology labels from the Plugin Manager" in the changelog

We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Comment by zbynek** [comment]
@oleg-nenashev thanks for the feedback. Regarding the changelog entry, for the user the result is realy just unification (before "slaves" was displayed as "Agent management", now both "slaves" and "agent" are displayed this way)

**Comment by oleg-nenashev** [comment]
I will initiate the ready-for-merge process so that we could get it in the weekly

We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Comment by timja** [comment]
> I will initiate the ready-for-merge process so that we could get it in the weekly
> 
> We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

Next release is a security release so no rush on anything it won’t be in the release next week

**Comment by daniel-beck** [comment]
In fact, holding off merges will make the merge back of the security release easier. Probably irrelevant here, but static analysis stuff can be really annoying.

**Pull request merged**
