### PR TITLE
Update the Log Recorders interface

### PR DESCRIPTION
**Pull request by janfaracik**
This PR updates the Log Recorders interface - 

* Drops the side panel from all pages, moves actions to the app bar following https://weekly.ci.jenkins.io/design-library/Layouts/
* Moves the 'Configure' button to the right of the table item (consistent with other pages)
* Moves the 'Clear log' and RSS buttons to the top of the page for easy access
* Uses the bottom app bar for the Configure page's submit controls

**Before**
image

image

image

**After**
image

image

image

### Testing done

* Log Recorders works as before
  * Can create new log recorders, configure them, RSS works as before, clearing works 

### Proposed changelog entries

- Update the Log Recorders interface

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.

### Desired reviewers

@jenkinsci/sig-ux 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/8087"></a>

### CODE REVIEW

**Review by uhafner — APPROVED** [review]
Looks good! 

One thing that should be changed as well: please shorten the name of the add button. Use "New Recorder" (as done in the nodes section) or "Add Recorder". Long names in buttons do not look good in general and "Add new log recorder" seems to be too long. 

Maybe we should add a note in the design library button section as well that describes what text should be typically used in buttons.

**Review by timja — APPROVED** [review]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by basil** [comment]
@janfaracik @NotMyFault @timja Breaks `hudson.plugins.throttleconcurrents.ThrottleQueueTaskDispatcherTest#testShouldConsiderTaskAsBlockableStillUponMatchingLabelPairWithLowestMax`. In the absence of a fix for the test, I intend to revert this PR.

**Comment by NotMyFault** [comment]
> @janfaracik @NotMyFault @timja Breaks `hudson.plugins.throttleconcurrents.ThrottleQueueTaskDispatcherTest#testShouldConsiderTaskAsBlockableStillUponMatchingLabelPairWithLowestMax`. In the absence of a fix for the test, I intend to revert this PR.

There's no such test case in this repository.

**Comment by timja** [comment]
Basil's comment could have been clearer but it's here:
https://github.com/jenkinsci/throttle-concurrent-builds-plugin/blob/3b9867b417ae7bfee26526ed31e098819228c11f/src/test/java/hudson/plugins/throttleconcurrents/ThrottleQueueTaskDispatcherTest.java#L112

**Comment by timja** [comment]
👉 https://github.com/jenkinsci/throttle-concurrent-builds-plugin/pull/233

**Pull request merged**
