### PR TITLE
[JENKINS-48957] Prevent wildfly to deliver old jackson for blue ocean and other plugins

### PR DESCRIPTION
**Pull request by ManuelB**
See [JENKINS-48957](https://issues.jenkins-ci.org/browse/JENKINS-48957).

This change has no test cases because it is a system issue and it would require to have test cases for every application server jenkins is running on.

### Proposed changelog entries

* JENKINS-48957 isolated Jenkins from JAX-RS classes shipped with wildfly (former JBoss) implementation to make blue ocean works (Jackson 2.7 vs 2.8) 

### Submitter checklist

- [X] JIRA issue is well described
- [X] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change).
- [X] Appropriate autotests or explanation to why this change has no tests
- [X] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@michaelneale

### CODE REVIEW

**Comment by michaelneale** [comment]
I think this LGTM - I can't see how this would cause problems for the common use cases, as it is an addition of a config file for WF specifically

**Comment by oleg-nenashev** [comment]
IIUC this is generally a defect in BlueOcean which uses newer versions of libs instead of ones included into the core. Right @michaelneale ?

**Comment by ManuelB** [comment]
@oleg-nenashev here is a list of all plugins that contain the name *jackson* on our installation:

```
cd /mnt/.jenkins/plugins
$ find . -name "*jackson-core*"
./jackson2-api/WEB-INF/lib/jackson-core-2.8.10.jar
./github/WEB-INF/lib/jackson-core-2.6.0.jar
./pipeline-model-api/WEB-INF/lib/jackson-core-2.2.2.jar
./pipeline-model-definition/WEB-INF/lib/jackson-core-2.7.3.jar
./cucumber-reports/WEB-INF/lib/jackson-core-2.8.6.jar
./cloudbees-bitbucket-branch-source/WEB-INF/lib/jackson-core-asl-1.9.13.jar
./blueocean-rest-impl/WEB-INF/lib/jackson-core-2.8.9.jar
./jira/WEB-INF/lib/jackson-core-2.8.9.jar
./jira/WEB-INF/lib/jackson-core-asl-1.5.5.jar
./jenkins-jira-plugin/WEB-INF/lib/jackson-core-asl-1.9.1.jar
./blueocean-commons/WEB-INF/lib/jackson-core-2.8.9.jar
```

As you can see most of your mobiles are bring your own library but this is not the problem.

The problem lies in the classloading policy of wildfly. 
https://docs.jboss.org/author/display/WFLY10/Class+Loading+in+WildFly

The policy is the following:

In order of highest priority to lowest priority

1. System Dependencies - These are dependencies that are added to the module automatically by the container, including the Java EE api's.
2. User Dependencies - These are dependencies that are added through jboss-deployment-structure.xml or through the Dependencies: manifest entry.
3. Local Resource - Class files packaged up inside the deployment itself, e.g. class files from WEB-INF/classes or WEB-INF/lib of a war.
4. Inter deployment dependencies - These are dependencies on other deployments in an ear deployment. This can include classes in an ear's lib directory, or classes defined in other ejb jars. 

With my addition I explicitly excluded the system dependency to the wildfly jax rs module.

/Manuel

**Comment by ManuelB** [comment]
As a none native english speaker I had to lookup the abbreviations:

LGTM - Looks good to me
IICU - If I understand correctly

**Comment by ManuelB** [comment]
Just for completeness this issue fixes the following stacktrace that happens when running jenkins, blue ocean on wildfly 10:

```
java.lang.NoSuchMethodError: com.fasterxml.jackson.core.io.JsonStringEncoder.quoteAsString(Ljava/lang/CharSequence;Ljava/lang/StringBuilder;)V
	at io.jenkins.blueocean.commons.stapler.export.JSONDataWriter.value(JSONDataWriter.java:112)
	at io.jenkins.blueocean.commons.stapler.export.JSONDataWriter.startObject(JSONDataWriter.java:154)
	at io.jenkins.blueocean.commons.stapler.export.Model.writeTo(Model.java:198)
	at io.jenkins.blueocean.commons.stapler.Export.writeOne(Export.java:148)
	at io.jenkins.blueocean.commons.stapler.Export.serveExposedBean(Export.java:139)
	at io.jenkins.blueocean.commons.stapler.Export.doJson(Export.java:79)
	at io.jenkins.blueocean.commons.stapler.TreeResponse$Processor$1.generateResponse(TreeResponse.java:48)
	at org.kohsuke.stapler.HttpResponseRenderer$Default.handleHttpResponse(HttpResponseRenderer.java:124)
	at org.kohsuke.stapler.HttpResponseRenderer$Default.generateResponse(HttpResponseRenderer.java:69)
	at org.kohsuke.stapler.Function.renderResponse(Function.java:136)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:119)
	at org.kohsuke.stapler.IndexDispatcher.dispatch(IndexDispatcher.java:26)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
	at org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:374)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
	at org.kohsuke.stapler.MetaClass$3.doDispatch(MetaClass.java:209)
```

**Review by oleg-nenashev — APPROVED** [review]
The proposed fix for not impact non-JBoss platforms, so I think it's fine to merge it. Thanks for the behavior clarification, @ManuelB 

P.S: I will try to use less abbreviations in PR reviews

**Pull request merged**
