### PR TITLE
Remove RSS links from the History Widget

### PR DESCRIPTION
**Pull request by kevinburke**

### CODE REVIEW

**Comment by jglick** [comment]
Cf. [JENKINS-26468](https://issues.jenkins-ci.org/browse/JENKINS-26468).

**Comment by oleg-nenashev** [comment]
Any plans to finish this PR?

**Comment by kevinburke** [comment]
hey... sorry, got too busy, would love if you want to follow up on it.


--
Kevin Burke
phone: 925.271.7005 | twentymilliseconds.com

**Comment by daniel-beck** [comment]
PR has been abandoned years ago (and Blue Ocean is becoming a formidable UI replacement), so closing this PR. Please rebase onto current Jenkins, address any review feedback, and submit a new PR if you're still interested in this.

**Pull request closed without merging**
