### PR TITLE
[JENKINS-24064] No more war-for-test

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-24064](https://issues.jenkins-ci.org/browse/JENKINS-24064)

Requires some follow-up PRs for use from plugins.

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
```
rememberMeAutoLoginFailure(hudson.security.TokenBasedRememberMeServices2Test)  Time elapsed: 10.271 sec  <<< FAILURE!
Assertion failed: 

assert logs.find { it.message.contains("contained username 'alice' but was not found")}!=null
       |    |                                                                          |
       []   null                                                                       false
```

**Comment by rsandell** [comment]
:bee:

**Comment by daniel-beck** [comment]
Will this new dependency be newly added to plugin class paths?

**Comment by jglick** [comment]
> Will this new dependency be newly added to plugin class paths?

Yes, see https://github.com/jenkinsci/jenkins-test-harness/issues/43 and https://github.com/jenkinsci/plugin-pom/issues/40.

**Comment by jglick** [comment]
Random-looking failure in `Security232Test.commonsCollections1` on one system only.

**Comment by jglick** [comment]
The main problem is that it is tricky to track which runtime dependencies are actually also needed by functional tests. Perhaps there needs to be another module in this repository which has `jar` packaging, no sources, and merely serves to depend on `jenkins-core` plus all the various modules, assets, and runtime libraries. Then `jenkins-war` would depend on this (dumping all those dependencies in `WEB-INF/lib/*.jar`, I hope), and tests would depend on it as well, giving effectively the same behavior as a `war-for-test` dep.

**Comment by daniel-beck** [comment]
Given the fun we already have with core dependencies exposed to plugins, I'm not sure we want to do more of that if we have an alternative.

**Comment by jglick** [comment]
> another module in this repository

Scratch that idea—it would not allow the plugin parent POM to pick a dependency on core in a way that would work for existing releases. We would need some Gradle-like

```groovy
if (new VersionNumber(props['jenkins.version']) >= new VersionNumber('2.34')) {
  test "org.jenkins-ci.main:jenkins-war-deps:${props['jenkins.version']}"
} else {
  test "org.jenkins-ci.main:jenkins-war:war-for-test:${props['jenkins.version']}"
}
```

> Given the fun we already have with core dependencies exposed to plugins, I'm not sure we want to do more of that if we have an alternative.

Not sure what you are getting at. Plugins _already_ pick up transitive dependencies from `jenkins-war`. The current PR actually removes some of those.

Anyway I think the “fun” you refer to involves runtime dependencies. Here we are only talking about test-scoped dependencies.

**Review by stephenc — COMMENTED** [review]
First round of review looks ok

**Comment by daniel-beck** [comment]
> Not sure what you are getting at. Plugins already pick up transitive dependencies from jenkins-war. The current PR actually removes some of those. … Here we are only talking about test-scoped dependencies.

How will this impact the JTH (not ATH)? Do we need guidance for plugin developers for when they upgrade the Jenkins version they develop against, e.g. will they need to add some test dependencies explicitly, or will things break in other ways?

**Comment by jglick** [comment]
> How will this impact the JTH (not ATH)? Do we need guidance for plugin developers for when they upgrade the Jenkins version they develop against

They just need to use a parent POM including https://github.com/jenkinsci/plugin-pom/pull/40; and either specify no particular `jenkins-test-harness.version`, or specify one which includes https://github.com/jenkinsci/jenkins-test-harness/pull/43.

**Comment by jglick** [comment]
@stephenc suggested an alternative approach in https://github.com/jenkinsci/plugin-pom/pull/40, TBD.

**Comment by jglick** [comment]
Not using this approach.

**Pull request closed without merging**
