### PR TITLE
JENKINS-73355 Removal of commons-compress from core

### PR DESCRIPTION
**Pull request by jonesbusy**
See JENKINS-73355

Not sure if it's premature for the removal, but most common plugins (with 3000 installation) have been adapted. I volunteer to also update other plugins from the list https://docs.google.com/spreadsheets/d/1WaWStSxgx8kLf2GhT5CwR7kwQ9DZa50wdKkOgZtl0_U/edit if needed

Since we move to new LTS baseline recently it would be nice that the removal lands in some next weekly release.

Also I'm maintainer of the `jobcacher` plugin that now rely on https://plugins.jenkins.io/commons-compress-api/ and would like at some point that the commons-compress gets updated 

### Testing done

Only rely on automated tests

### Proposed changelog entries

- Developer: The `commons-compress` library is no longer provided by Jenkins itself, use the [commons-compress API plugin](https://plugins.jenkins.io/commons-compress-api/) instead

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [x] The Jira issue, if it exists, is well-described.
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [x] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@basil 

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Comment by timja** [comment]
I would prefer if the saucelabs plugin could be merged and released first, good apart from that from my PoV

**Comment by jonesbusy** [comment]
Thanks. I will also update the `checkmarx-ast-scanner` plugin. It has ~400 installation and very recent release (actually yesterday). So definitely active

**Comment by jonesbusy** [comment]
The sauce on demand plugin was released (the google docs is also updated): https://github.com/jenkinsci/sauce-ondemand-plugin/releases/tag/sauce-ondemand-1.215

I will let core maintainers decide if we wait for the `checkmarx-ast-scanner` (PR is done, waiting for maintainer answer). I tried to check installation stats on https://old.stats.jenkins.io/pluginversions/checkmarx-ast-scanner.html but doesn't give relevant results to know if plugin user follow weekly or LTS upgrades

`aws-codepipeline-plugin` was also raised but the service is deprecated on AWS so I don't think we need to wait for it

Regards,

**Comment by timja** [comment]
Can you run bom and ATH tests to be safe please?

**Comment by jonesbusy** [comment]
Sure will open a test PR on the bom

**Review by timja — APPROVED** [review]

**Comment by jonesbusy** [comment]
`checkmarx-ast-scanner` was merged and released, will update the branch and hopefully we can move on this PR

**Review by NotMyFault — APPROVED** [review]

**Comment by timja** [comment]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by timja** [comment]
Causing ATH failures: 

```
master1264775610|java.lang.ClassNotFoundException: org.apache.commons.compress.compressors.bzip2.BZip2CompressorInputStream
```

See https://github.com/jenkinsci/acceptance-test-harness/pull/1860

**Comment by timja** [comment]
I see Mark has raised a PR: https://github.com/jenkinsci/compress-artifacts-plugin/pull/30

**Comment by jonesbusy** [comment]
Caused https://github.com/jenkinsci/blackduck-coverity-on-polaris-plugin/issues/4

**Pull request merged**
