### PR TITLE
[FIX JENKINS-36044]: Added default locale to XMLUtilsTest so that it …

### PR DESCRIPTION
**Pull request by ghost**
…runs independent from the host OS locale.

https://issues.jenkins-ci.org/browse/JENKINS-36044

### CODE REVIEW

**Comment by daniel-beck** [comment]
Why not make the tests locale independent, or at least limit the locale definition to the bits that really need to be English? I expect this could hide other (legitimate) test failures.

**Comment by oleg-nenashev** [comment]
Same comment as in #2650

**Comment by oleg-nenashev** [comment]
Still not good for parallel testing, but weak 👍 since we use similar approaches in test suites. Maybe deserves a TODO comment

**Comment by andrealaura** [comment]
Thanks @oleg-nenashev and @daniel-beck for your comments, I think I have a better solution now, by not checking the exception for english text but for the XSD location.

**Review by oleg-nenashev — APPROVED** [review]
The proposed change LGTM if it works :+1:

**Pull request merged**
