### PR TITLE
[JENKINS-73114] avoid conflicts with css classes from bootstrap

### PR DESCRIPTION
**Pull request by mawinter69**
jenkins and bootstrap both have definitions for `alert` and `alert-warning`, `alert-info` and `alert-danger`. Bootstrap css definitions are included when e.g. the warning-ng plugin is installed and a job is configured to scan for warnings. The css classes from bootstrap are then chosen instead of the ones for Jenkins for things like the admin monitors. To make things unambiguous, add additional classes prefixed with `jenkins-` and make use of them in code. Keep the old definitions for backward compatibility with plugins.
Follow-up changes are needed in plugins (Mostly those that define admin monitors) and the design-library

After:
for a plugin message:
image

for a core message:
image

See [JENKINS-73114](https://issues.jenkins.io/browse/JENKINS-73114).

Originally reported as https://github.com/jenkinsci/customizable-header-plugin/issues/99

### Testing done

Manual testing
1. Create new Jenkins instance, it should have some executors for built-in, this will trigger the corresponding monitor
2. Visit page `/manage/` -> monitors are displayed properly
3. install warnings-ng plugin
4. create freestyle job and configure post build action to scan for e.g. stylellint.
5. run the job once
6. In the header click on the warning shield -> monitor is displayed properly (If there are monitors from plugins they might not be properly styled here)

### Proposed changelog entries

- Add new CSS classes to avoid conflicts with CSS classes from bootstrap.

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Review by janfaracik — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]
Thanks!

---

/label ready-for-merge

---

This PR is now ready for merge. We will merge it after ~24 hours if there is no negative feedback.
Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process.
Thanks!

**Comment by timja** [comment]
Can you create a PR for the design library to adapt to this please?

**Comment by mawinter69** [comment]
> Can you create a PR for the design library to adapt to this please?

done

**Comment by MarkEWaite** [comment]
@mawinter69 can you also identify the plugins that need to be updated to use the new CSS classes?  I think it is better to complete the migration from the old CSS classes to the new CSS classes in the most popular plugins.

**Comment by mawinter69** [comment]
Should this maybe downported to LTS 2.452.2? Otherwise it will take quite a while until it arrives in an LTS. Plugins would otherwise need to use weekly 2.459. Specifying both the old and new classes doesn't help when bootstrap loaded so it can't really be made forward compatible

**Comment by mawinter69** [comment]
I Identified following plugins making use of the any of the alert-* classes. That doesn't necessarily mean they need to be adjusted, e.g. pipeline-stage-view seems to have a bootstrap3 included and relies on the definitions there.

configuration-as-code
github
ec2
xcode
sysdig-secure
role-strategy
gitlab-branch-source
copyartifact
opentelemetry
matrix-auth
alauda-devopy-synvc
pipeline-input-step
atlassian-bitbucket-server-integration
dimensionsscm
azure-ad
artifact-manager-s3
jenkinslint
active-directory
branch-api
dependency-track
cloudbees-jenkins-advisor
pipeline-maven
spotinst
pull-request-monitoring
localization-support
pipeline-stage-view
ssh-agents
blue-ocean
audit-trail
sysdig-secure
customizable-header
gradle
azure-vm-agents
miniorange-two-factor
miniorange-saml-sp
collabnet
performance-signature-dynatrace

**Comment by mawinter69** [comment]
> Thanks @mawinter69 ! Is it valid CSS to refer to a CSS class that does not exist? 

That would be valid (Jenkins is using all over the place classes without a corresponding css definition to be able to select things in queries). Though only by removing `alert` and `alert-warning` there is no interference with bootstrap. And for not breaking plugins that don't have the new classes, the old definitions are still there.

> <div class="alert alert-warning" role="alert">

that should become `<div class="alert jenkins-alert alert-warning jenkins-alert-warning" role="alert">`

**Pull request merged**
