### PR TITLE
[JENKINS-67155] New jenkins-tooltip class does not work in title attributes

### PR DESCRIPTION
**Pull request by jamesD33064**
See [JENKINS-67155](https://issues.jenkins-ci.org/browse/JENKINS-67155).
截圖 2021-11-27 下午11 28 24

### Proposed changelog entries

* Show the new style tooltip.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] (If applicable) Jira issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by Wadeck** [comment]
I haven't checked the details, but my spider sense was in alert mode with this PR. IIRC the `applyTooltip` "executes" the HTML, and thus will create tons of XSS.
_(to be confirmed it's not the case before merging this PR)_

**Review by Wadeck — CHANGES_REQUESTED** [review]
Hello @jamesD33064, we spent some times with @alecharp to check my previous comment and yes this is problematic.

The problem is that with your PR, you are transforming title attribute into tooltip, by interpreting the content as HTML, meaning with some payload, you can trigger XSSs.
Example, with the offline cause for an agent, the user can store the XSS and then any victim who is hovering the icon in the left widget will trigger the XSS.

<details>

<summary>XSS proof</summary>

#### Config

pr_5976_xss_config


#### Trigger

pr_5976_xss_trigger


</details>

So, in the current situation I can only refuse your PR.

💡 Now, as a proposal, you can hook with a more specific attribute (both for the behavior and the getAttribute), like `data-jenkins-html-title`, which will not impact the whole ecosystem and explicit the fact that the attribute will be executed.

**Comment by alecharp** [comment]
@jamesD33064 were you able to review the comment from @Wadeck about what we found with this changes?

**Comment by basil** [comment]
There hasn't been a response from the original author since this PR was opened 5 months ago, so I am labeling this PR as `stalled`. In the absence of a response I plan to transition it to `proposed-for-close` in approximately one month and close it approximately one week after that.

**Comment by janfaracik** [comment]
> Hello @jamesD33064, we spent some times with @alecharp to check my previous comment and yes this is problematic.
> 
> The problem is that with your PR, you are transforming title attribute into tooltip, by interpreting the content as HTML, meaning with some payload, you can trigger XSSs. Example, with the offline cause for an agent, the user can store the XSS and then any victim who is hovering the icon in the left widget will trigger the XSS.
> 
> XSS proof
> So, in the current situation I can only refuse your PR.
> 
> 💡 Now, as a proposal, you can hook with a more specific attribute (both for the behavior and the getAttribute), like `data-jenkins-html-title`, which will not impact the whole ecosystem and explicit the fact that the attribute will be executed.

With the tooltip overhaul (#6408) we'll have two attributes `tooltip="..."` (XSS safe) and `html-tooltip="..."` (not XSS safe) which should satisfy this.

**Comment by basil** [comment]
Since the review feedback has not yet been addressed and over five months have elapsed, including a week with no response after applying the `proposed-for-close` label, I am closing this PR. On behalf of the core team, I would like to thank you for your contribution. Even though this PR did not make it across the finish line, it was a promising start! I continue to encourage you (or anyone else who is interested!) to pick up this effort and drive it to completion. Thanks!

**Pull request closed without merging**
