### PR TITLE
JENKINS-28601: Correct sort order

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
I doubt it's a right approach, because changes in many dependent plugins may be required.
I'd better revert https://github.com/jenkinsci/jenkins/pull/1708 and somehow document the behavior

**Comment by daniel-beck** [comment]
Grepping my slightly older copy of `all.git` reveals 26 affected plugins. This appears to be manageable.

**Comment by oleg-nenashev** [comment]
> Of course it'd be easier to revert the change and live with this odd behavior.

I would vote for this approach. If nobody goes forward and fixes plugins, I'll submit a revert PR by the weekend and fix JENKINS-17290 in another way.

Probably, we could change the appearance of arrows and make the UI better by totally obfuscating the code

**Comment by daniel-beck** [comment]
@oleg-nenashev 

> I would vote for this approach. If nobody goes forward and fixes plugins, I'll submit a revert PR by the weekend

Agreed, this would be the best solution for now.

**Comment by jglick** [comment]
So :-1: on this in favor of #1737.

**Comment by oleg-nenashev** [comment]
Are we going to make an additional fix attempt?
I suppose a rework of the code is not a right idea due to the huge impact on plugins, so we need another solution

**Comment by daniel-beck** [comment]
@oleg-nenashev I think I'm missing something here. Because when I follow the instructions on [JENKINS-17290](https://issues.jenkins-ci.org/browse/JENKINS-17290), I don't even see the column headers anymore. Did you reproduce the issue when you proposed #1708?

**Comment by oleg-nenashev** [comment]
The issue still can be reproduced on other tables using sortable. You may see that the direction of sorting differs from the arrow icon direction

**Comment by daniel-beck** [comment]
@oleg-nenashev That's not what JENKINS-17290 is about however.

**Comment by oleg-nenashev** [comment]
#1708 has been reverted && there is no progress in this PR, hence I propose to close it

**Comment by oleg-nenashev** [comment]
Closing since nobody disagrees

**Pull request closed without merging**
