### PR TITLE
Update the bundled version of cvs plugin to 2.17

### PR DESCRIPTION
**Pull request by daniel-beck**
See https://www.jenkins.io/security/advisory/2020-12-03/?#SECURITY-2146

Untested.

### Proposed changelog entries

too minor?

* Update bundled CVS Plugin to 2.17

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [x] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by jvz — APPROVED** [review]
Whoa, the bundled version was pretty old!

**Review by MarkEWaite — APPROVED** [review]

**Comment by MarkEWaite** [comment]
I labeled as `bug` but was not sure if it should be labeled as `dependency` rather than `bug`.

**Comment by daniel-beck** [comment]
All previous such PRs were labeled `rfe`, so for consistency…

**Review by res0nance — APPROVED** [review]

**Comment by daniel-beck** [comment]
Needs to add jsch to the test dependencies.

**Comment by daniel-beck** [comment]
I like #5102 better.

**Pull request closed without merging**
