### PR TITLE
[FIX JENKINS-34857] Don't throw Exception when Jenkins.getInstance() yields null

### PR DESCRIPTION
**Pull request by batmat**
Alternative approach to fixing JENKINS-34857. 

Could be preferred to #2354 

@stephenc WDYT?

### CODE REVIEW

**Comment by stephenc** [comment]
Fine by me... As long as we move towards the eventual goal

**Comment by oleg-nenashev** [comment]
I think this one is better. I think a compatibility issue is not a big deal since it's a critical regression

**Comment by batmat** [comment]
OK, thanks for your feedback. 
Gonna wait a bit more for additional feedback, and if nobody objects will merge this PR and close #2354.

**Comment by batmat** [comment]
Let's go. @kohsuke is ready to make a bugfix release. That'll prevent that issue to become too widespread and give us time to analyse if only the subversion plugin is affected or if there are more.

**Comment by oleg-nenashev** [comment]
@batmat @kohsuke Seems we were using different IRC chats, but 👍 for going forward

**Pull request merged**
