### PR TITLE
[JENKINS-33396] System/Job Config page scrollspy tab overflow

### PR DESCRIPTION
**Pull request by tfennelly**
Rerun of https://github.com/jenkinsci/jenkins/pull/2210, this time with 2.0 on master.

[JENKINS-33396](https://issues.jenkins-ci.org/browse/JENKINS-33396)

Today, config page scrollspy is kinda horrible if used on the system config with lots of plugins installed. It results in tab overflow where there can be 5+ rows of tabs. Looks a bit silly + is eating up a lot of space.

These changes introduce a dropdown box for when tabs overflow.

VIDEO: https://youtu.be/h25-8Hu1VLs (shows the current state at the start, followed by how things would look with these changes) 

@jenkinsci/code-reviewers 

**TODO**
- [ ] Unit tests. Prob 1 days work, +/- a few hours.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
CC @samatdav . Seems it is related to one of items in your GSoC project

**Comment by oleg-nenashev** [comment]
@tfennelly please create a JIRA issue for it. Seems it may need a backporting to the new LTS baseline

**Comment by daniel-beck** [comment]
Minor issue: Tab labels don't appear for items to the right of the current item when scrolling down, even when there's enough space for them. Only when scrolling further do these items appear.

> screen shot 2016-05-23 at 16 43 37

After scrolling down a bit further:

>  screen shot 2016-05-23 at 16 43 45

Sample items are from installing all suggested plugins in the PR build, then going to *Configure System*.

---

Otherwise, seems fine. :+1: Looks mergeable.

Would be great if this could be extended to the *Global Tools Configuration* as well.

**Comment by oleg-nenashev** [comment]
@tfennelly Are you still working on it? I mean the "WiP" status

**Comment by daniel-beck** [comment]
@oleg-nenashev The reason this is WIP is that UI tests are missing, and Tom doesn't have time to add these right now.

**Comment by oleg-nenashev** [comment]
@tfennelly Is the work done? It's marked as WiP now, and I am not sure whether it's ready for another iteration

**Comment by daniel-beck** [comment]
AFAIR Tom has no current plans to finish this, and I've unsuccessfully tried months ago to get this in the queue of @michaelneale and @i386.

**Comment by slide** [comment]
Not sure why I was notified on this, but definitely a :+1: from me. Looks great :-)

**Comment by michaelneale** [comment]
@daniel-beck last touched 26 march 2016 - by the time it was on our radar it was already ancient, if it still works, why not, it seems like a good change as long as not way out of date.

**Comment by oleg-nenashev** [comment]
@michaelneale Well, it requires some work to get it over the fence. I will assign it to you so that you can decide how to proceed

**Comment by michaelneale** [comment]
@oleg-nenashev yeah this hasn't gone anywhere, I don't think @tfennelly will have time, so can close this for now (if no one has picked it up) - his branch remains, can be re-opened in future if people pipe up

**Pull request closed without merging**
