### PR TITLE
[JENKINS-38711, JENKINS-47132] - Update Remoting to 3.13

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Changelog: https://github.com/jenkinsci/remoting/blob/master/CHANGELOG.md#313
Full Diff: https://github.com/jenkinsci/remoting/compare/remoting-3.12...remoting-3.13

### Proposed changelog entries

* RFE: Upgrade Remoting from 3.12 to 3.13
  * Changelog: https://github.com/jenkinsci/remoting/blob/master/CHANGELOG.md#313
  * Linked issues: [JENKINS-47132](https://issues.jenkins-ci.org/browse/JENKINS-47132), [JENKINS-38711](https://issues.jenkins-ci.org/browse/JENKINS-38711)
* RFE: [JENKINS-38711](https://issues.jenkins-ci.org/browse/JENKINS-38711) - Add uncaught exception handling logic to Agent connection threads in the Core and Remoting.
  * Comment: It needs to be a separate entry, because it also involves patches on the core side

@reviewbybees @rysteboe

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@jenkinsci/hacktoberfest just to test my dashboard

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers ?

**Comment by daniel-beck** [comment]
What is the relation between this and #3017? Are the "core changes" the proposed changelog above refers to over there? Why are these independent PRs?

**Comment by oleg-nenashev** [comment]
@daniel-beck Both pull requests address the same improvement: [JENKINS-38711](https://issues.jenkins-ci.org/browse/JENKINS-38711) (uncaught exception handlers). The patches are independent though there is one issue ID for them. That's why I cross-reference them.

Merging two pull requests into a single release would simplify the things, but it's not really mandatory.

**Review by jglick — APPROVED** [review]
OK I suppose!

**Comment by oleg-nenashev** [comment]
So the target is 2.85 (next Sunday)

**Pull request merged**
