### PR TITLE
[JENKINS-52019] - Update Groovy from 2.4.11 to 2.4.12 to pick up fixes towards Java 11 support

### PR DESCRIPTION
**Pull request by oleg-nenashev**
See [JENKINS-52019](https://issues.jenkins-ci.org/browse/JENKINS-52019), it is a core counterpart for https://github.com/jenkinsci/workflow-support-plugin/pull/68. Requires sign-off from @svanoort before going forward

Testing:

* Spot-check during the Java 10+ hackathon (on Java 8, 10, 11)
* Soak testing on @oleg-nenashev's environment (~2 weeks, Java 8)
* Testing for memory leaks by @svanoort . Originally we suspected a memory leak, but according to tests there is no evidence of that which would block the change upstreaming

foo

### Proposed changelog entries

* RFE Update Groovy from 2.4.11 to 2.4.12 to pick up fixes towards Java 11 support
  * http://groovy-lang.org/changelogs/changelog-2.4.12.html

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@jenkinsci/sig-platform @svanoort

### CODE REVIEW

**Review by daniel-beck — APPROVED** [review]
🎉

**Review by svanoort — APPROVED** [review]
I'm approving, but we should watch feedback on the weekly carefully just in case (we cannot readily cover every possible Groovy failure mode

**Review by MarkEWaite — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
>  we should watch feedback on the weekly carefully just in case (we cannot readily cover every possible Groovy failure mode

for sure

**Comment by oleg-nenashev** [comment]
Merging. It has been soak tested for long, and it makes sense to proceed so we have more time for evaluation before LTS

**Pull request merged**
