### PR TITLE
[JENKINS-71087] Nicer 404 error pages

### PR DESCRIPTION
**Pull request by daniel-beck**
Resurrects #5527, replaces #7865. Collaboration with @mawinter69.

See [JENKINS-71087](https://issues.jenkins.io/browse/JENKINS-71087).

<details>
<summary>Screenshots</summary>

resource
security-anon

security-auth

no-security

</details>

TODOs not otherwise noted in the code:

- [x] Prevent the "REST API" link from showing up in the footer, or ensure it links to the correct URL
- [ ] [Figure out favicon issues on resource domain](https://github.com/jenkinsci/jenkins/pull/8250#discussion_r1261010569)

### Testing done

See screenshots above.

For manual tests in `mvn -pl war jetty:run`, run `org.kohsuke.stapler.Dispatcher.TRACE = false` beforehand in the script console.

Expected behaviors (most asserted in autotests):

* 404 error page on the regular domain
  - looks nice
  - correctly reflects the current user (top right)
  - if a login link is shown, it links to `login?from=/` (both with and without context path)
  - if "security" (security realm and authorization strategy) is configured, show "you may not have access", otherwise "this does not exist"
  - If it's inside `static-files/` (`ResourceDomainRootAction`), do not have a note that the file may or may not exist
* 404 error page on the resource domain
  - looks slightly less nice
  - links to actual Jenkins
  - Serves all included resources…
  - …but no resources/URLs that don't appear on the page

### Proposed changelog entries

- Add a nicer 404 error page.

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [x] The Jira issue, if it exists, is well-described.
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [x] There is automated testing or an explanation as to why this change has no tests.
- [x] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/8250"></a>

### CODE REVIEW

**Comment by daniel-beck** [comment]
@mawinter69 Could you clarify what `jenkins.security.ResourceDomainRootAction.error` is for? Development feftover from before you went with `ResourceDomainConfiguration#isResourceRequest`?

**Comment by mawinter69** [comment]
In the PR to your branch I wrote this
`Do not show the hint about not found or permission when accessing the static-files url from the regular domain.` 
I think it doesn't make sense to tell the user that the page doesn't exist when he accessed a static-file url that is not meant to be used like this. I would not expect that people will ever access such urls, but one never knows.

**Comment by daniel-beck** [comment]
> In the PR to your branch I wrote this

Ah, I missed that, thanks! Now it's clear.

**Review by yaroslavafenkin — COMMENTED** [review]
Seems OK from security PoV

**Review by timja — APPROVED** [review]
LGTM

**Comment by NotMyFault** [comment]
Oh, the screenshots look great. Thanks so much to you too for carrying this forward 🚀 

There are test failures in the ATH: https://github.com/jenkinsci/acceptance-test-harness/pull/1342

**Comment by daniel-beck** [comment]
ATH failure is probably caused by https://github.com/jenkinsci/acceptance-test-harness/pull/1324 given this is missing https://github.com/jenkinsci/jenkins/pull/8365.

**Comment by NotMyFault** [comment]
> ATH failure is probably caused by [jenkinsci/acceptance-test-harness#1324](https://github.com/jenkinsci/acceptance-test-harness/pull/1324) given this is missing #8365.

Indeed, false alarm from my side.

**Review by NotMyFault — APPROVED** [review]
Huge thanks to both of you for driving this effort, the new pages are a massive improvement over the old ones 🚀

**Comment by timja** [comment]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by basil** [comment]
Has caused a number of new PCT failures: https://github.com/jenkinsci/bom/pull/2407/checks?check_run_id=16152161796

If all PCT failures caused by this change are not addressed by next Monday I intend to revert this change

**Pull request merged**
