### PR TITLE
[JENKINS-61521] Ignore RemoteClassLoader$ClassLoaderProxy#fetch3 on telemetry

### PR DESCRIPTION
**Pull request by MRamonLeon**
See [JENKINS-61521](https://issues.jenkins-ci.org/browse/JENKINS-61521).
Tests are not needed. Well known addition without implications.

### Proposed changelog entries

* N/A

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] JIRA issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [X] Appropriate autotests or explanation to why this change has no tests
- [N/A] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers
@jenkinsci/core-pr-reviewers 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [x] There are at least 2 approvals for the pull request and no outstanding requests for change
- [x] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [x] Proper changelog labels are set so that the changelog can be generated automatically
- [x] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [x] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

### CODE REVIEW

**Review by varyvol — APPROVED** [review]

**Review by rsandell — APPROVED** [review]

**Review by timja — APPROVED** [review]

**Review by res0nance — APPROVED** [review]

**Comment by MRamonLeon** [comment]
Filed an issue on infra: https://issues.jenkins-ci.org/browse/INFRA-2543

**Comment by timja** [comment]
> Filed an issue on infra: [issues.jenkins-ci.org/browse/INFRA-2543](https://issues.jenkins-ci.org/browse/INFRA-2543)

I've pinged on IRC, olbak is aware

**Comment by oleg-nenashev** [comment]
Looks like a minor bug to me

**Comment by MRamonLeon** [comment]
Well, these messages were expected, to review all places where a CNFE due to Java 11 missed classes is triggered. We have to review one by one each reported place to assess it's expected or, in the other hand, some part of Jenkins core or a plugin won't work well on Java 11. This case it doesn't mean Jenkins won't run fine on this branch of code on Java 11, so just to ignore the place. That's why I marked it as just an improvement. Anyway, not a big deal.

**Pull request merged**
