### PR TITLE
[FIXED JENKINS-35641] - Always send usage statistics over HTTPs to the new usage.jenkins.io hostname

### PR DESCRIPTION
**Pull request by rtyler**
References [INFRA-559](https://issues.jenkins-ci.org/browse/INFRA-559)

https://issues.jenkins-ci.org/browse/JENKINS-35641

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
👍

**Comment by oleg-nenashev** [comment]
@rtyler Is it an improvement or a security hardening fix? In the second case it may be backported into 2.7.x (ideally needs a JIRA issue then)

**Comment by oleg-nenashev** [comment]
Created JENKINS-35641

**Comment by batmat** [comment]
+1 for 2.7.1 backport if deemed OK.

**Pull request merged**
