### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by edwardpro**
Add Script:
COPY test-pom/ /jenkins/src/test-pom/
COPY test-jdk8/ /jenkins/src/test-jdk8/

For can't use docker build.

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

### Proposed changelog entries

* Entry 1: Issue, Human-readable Text
* ...

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### CODE REVIEW

**Comment by daniel-beck** [comment]
Originally added in https://github.com/jenkinsci/jenkins/pull/3670 (early October 2018).
IIUC, broken by https://github.com/jenkinsci/jenkins/pull/3759(mid November 2018).
Now it's 5 months later.

Why would we want to keep the Dockerfile around when it's not being used?

@oleg-nenashev ?

**Comment by batmat** [comment]
Yeah, I would rather just delete this file, given I understand the intent here is probably fulfilled by https://hub.docker.com/r/jenkins/core-pr-tester.

How about either this PR is repurposed for this, or we close this and I can propose a PR to delete the `Dockerfile` and add a blurb in the https://github.com/jenkinsci/jenkins/blob/master/CONTRIBUTING.md for instance?

**Comment by oleg-nenashev** [comment]
@batmat @daniel-beck the Dockerfile is used for continuous delivery of Jenkins master builds to https://hub.docker.com/r/jenkins/jenkins-experimental . But the flow is dead now. I can recover it, but generally we should adopt [JEP-217](https://github.com/jenkinsci/jep/tree/master/jep/217)

**Review by oleg-nenashev — APPROVED** [review]
Merging since it will not hurt

**Comment by oleg-nenashev** [comment]
And not waiting for extra reviews, this is not a production code

**Pull request merged**
