### PR TITLE
MessageFormat treats ' as a special character

### PR DESCRIPTION
**Pull request by jsoref**
https://docs.oracle.com/javase/8/docs/api/java/text/MessageFormat.html

Test case is jenkins/computer/node/configure
 Help for "Launch method"

Without this fix, you will see:
Launch agent via Java Web Start
... By default, the JNLP agent will launch a GUI, but its also possible to run a JNLP agent without a GUI, e.g. as a Window service.

You should see:
... By default, the JNLP agent will launch a GUI, but it's also possible to run a JNLP agent without a GUI, e.g. as a Window service.

### Submitter checklist

- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)

### Desired reviewers

### CODE REVIEW

**Comment by daniel-beck** [comment]
I think @jglick had somewhat strong feelings that these should just be typographic quotes instead.

**Comment by jsoref** [comment]
From my perspective, there are potentially two bugs here:
1. your single quotes need to be doubled to be seen -- my patch does this. This is a strict improvement over what is currently present.
1. you may want to replace single quotes w/ typographic quotes. @jglick may want that.

At the expense of repo churn, I'd rather get my change in and have someone else consider a more global typographic quotes commit.

**Comment by jglick** [comment]
You definitely need to double up `'` when there is actually a message format: `{0}`, etc. But if there are no parameters, as in the example shown, there is no reason to process anything using `MessageFormat` to begin with—it should have just been treated as a literal string. So I wonder if there is a bug in `stapler-jelly` at the root of this.

**Comment by jsoref** [comment]
My guess is that there's only one path, it's designed for localization and is consistent and agnostic.

**Review by daniel-beck — APPROVED** [review]
seems reasonable, assuming it was tested.

**Comment by jglick** [comment]
Indeed [this code](https://github.com/stapler/stapler/blob/4b96ce1f9a18673f223cb6ebf977e1daaaf947d1/jelly/src/main/java/org/kohsuke/stapler/jelly/InternationalizedStringExpression.java#L68-L73) shows that Stapler applies `MessageFormat` even when there are no arguments to format, which is surprising and undesirable, but presumably too late to fix now—if anyone is already using `''` inside a zero-argument string, we must continue to render it as `'`.

**Review by jglick — APPROVED** [review]
Generally prefer use of `’` (or, for matched pairs, `‘`…`’` or `“`…`”` or even in some cases `` ` ``…`` ` ``), or spelling out contractions (s/`doesn't`/`does not`/), but this is fine for now.

**Review by oleg-nenashev — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Thanks @jsoref !

**Comment by recena** [comment]
@jsoref I found a regression [JENKINS-49634](https://issues.jenkins-ci.org/browse/JENKINS-49634)

/cc @daniel-beck @jglick

**Pull request merged**
