### PR TITLE
Add a full stop to the end of the Manage Users button description in the Manage Jenkins page

### PR DESCRIPTION
**Pull request by tullydwyer**
Hi there, thanks for this awesome project.

This is a tiny PR to add a full stop to the end of the Manage Users button description in the Manage Jenkins page, as it is the only description on the page without a full stop.

Before:
Screen Shot 2022-02-18 at 10 02 41 am

After:
image

### Proposed changelog entries

Not needed or

* Add a full stop to the end of the Manage Users button description in the Manage Jenkins page.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- ~~(If applicable) Jira issue is well described~~
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- ~~Appropriate autotests or explanation to why this change has no tests~~
- ~~New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate.~~
- ~~For dependency updates: links to external changelogs and, if possible, full diffs~~

### Desired reviewers

anyone

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [x] There are at least 2 approvals for the pull request and no outstanding requests for change
- [x] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [x] Proper changelog labels are set so that the changelog can be generated automatically
- ~~If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))~~
- ~~If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).~~

### CODE REVIEW

**Review by NotMyFault — COMMENTED** [review]
Looks like all section items end with a full stop but this one. 
I'd suggest to apply this change to the translation files too.

**Comment by tullydwyer** [comment]
Hi NotMyFault,

I only know english, and from my understanding I don't believe all languages use full stops. So I think it could break a proper translation to add full stops to the end of all translations.

image

https://en.wikipedia.org/wiki/Full_stop#Full_stops_in_other_scripts

**Review by daniel-beck — APPROVED** [review]
Good catch 👍 I don't think we need localizations to be updated for the reason given. It's also not severe enough to delete them to force a re-translation.

Next step: Fix every single plugin 😭

Screenshot 2022-02-18 at 10 03 07

**Review by NotMyFault — APPROVED** [review]

**Comment by MarkEWaite** [comment]
This PR is now ready for merge.  We will merge it after approximately 24 hours if there is no negative feedback.

**Comment by daniel-beck** [comment]
@tullydwyer Just in case, there's no expectation that you fix up all of the plugins 😉 It's just something I noticed when I looked at the manage page.

**Pull request merged**
