### PR TITLE
More memory for test execution

### PR DESCRIPTION
**Pull request by daniel-beck**
https://ci.jenkins-ci.org/job/jenkins_2.0/ looks like it runs out of memory while executing tests.

@abayer WDYT?

@reviewbybees

### CODE REVIEW

**Comment by abayer** [comment]
:bee: MOAR MOAR MOAR memory gooood.

**Comment by jtnord** [comment]
You should look at why this is leaking memory rather than just pushing more and more to it.
if we need that much to run tests then it smells like a memory leak somewhere.

master is using 256MB and this is the second time you have bumped memory on 2.0 branch - so I really doubt you have added that much to 2.0 that this points to some buggy code in 2.0 that needs to be fixed.

So really you have a :bug: in your tests or production code that must be fixed.

**Comment by jtnord** [comment]
You should look at why this is leaking memory rather than just pushing more and more to it.
if we need that much to run tests then it smells like a memory leak somewhere.

[master](https://github.com/jenkinsci/jenkins/blob/master/test/pom.xml#L205) is using [256MB](https://github.com/jenkinsci/jenkins/blob/573d0920dbaa4b2b48d839b865141a097c3b87fd/test/pom.xml#L205) so I really doubt you have added that much to 2.0 that this points to some buggy code in 2.0 that needs to be fixed and is the [second time](https://github.com/jenkinsci/jenkins/commit/32d65cc6782ec3e4898d6f0163d2e4d9d4017e98#diff-9271d1e8533e20df7fd09db69d1ad683) that memory issues are just being swept under the carpet.

**Comment by aheritier** [comment]
I agree with @jtnord It is a too easy short term fix. It smells bad for the product...

**Pull request closed without merging**
