### PR TITLE
[JENKINS-68941] Make -Dtest=... work again

### PR DESCRIPTION
**Pull request by daniel-beck**
See [JENKINS-68941](https://issues.jenkins.io/browse/JENKINS-68941). Amends #6652.

When running `mvn clean install -Dspotbugs.skip -Dfindbugs.skip -Dcheckstyle.skip -Dspotless.check.skip -Dtest=PluginManagerTest`, the `cli` module build fails without this, but passes with this change.

### Proposed changelog entries

(Internal/developer only)

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")` if applicable.
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

### CODE REVIEW

**Review by basil — COMMENTED** [review]
The same is the case for plugins with a Maven multi-module build (e.g., `pipeline-model-definition`) and other core components with a Maven multi-module build (e.g., `lib-access-modifier`). I think this is a good idea but I think the right place to fix this is in `plugin-pom` and `pom` (the fact that both exist and are largely duplicates of each other is a pre-existing issue, but I try to keep them in sync as much as possible). That way, the fix would apply to the whole organization rather than just this repository. Not against applying it to this repository alone, but I view that as more of a hotfix than a long-term fix. Similar situation with the change James wanted to make recently about redirecting test output to a file: we ended up putting that in place in `pom` and `plugin-pom` rather than in core.

**Comment by daniel-beck** [comment]
Note that I am simply fixing what was broken by the update: The profile for this purpose exists and sets a (now apparently no longer correct) property. I would consider the migration of this behavior upstream a good idea, but out of scope of this PR.

**Comment by basil** [comment]
And I would consider short-term fixes like this acceptable, but not desirable.

**Comment by daniel-beck** [comment]
I guess superseded by https://github.com/jenkinsci/pom/pull/274 and https://github.com/jenkinsci/jenkins/pull/6793

**Pull request closed without merging**
