### PR TITLE
Fix missing icons

### PR DESCRIPTION
**Pull request by janfaracik**
## Before

130775101-d4459d3b-f34a-4ebc-be94-caa60f5637f1

## After

image

### Proposed changelog entries

* Fix missing settings/cog icon in Plugin Manager
* Fix incorrect folder icon showing in projects

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@timja 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by daniel-beck** [comment]
Does this mean that plugins using the same icon will now show missing images? E.g. https://github.com/jenkinsci/workflow-cps-plugin/blob/f522e783e917bc0aa0513a29684285b710163905/src/main/java/org/jenkinsci/plugins/workflow/cps/SnippetizerLink.java#L138

**Comment by timja** [comment]
> Does this mean that plugins using the same icon will now show missing images? E.g. [jenkinsci/workflow-cps-plugin@`f522e78`/src/main/java/org/jenkinsci/plugins/workflow/cps/SnippetizerLink.java#L138](https://github.com/jenkinsci/workflow-cps-plugin/blob/f522e783e917bc0aa0513a29684285b710163905/src/main/java/org/jenkinsci/plugins/workflow/cps/SnippetizerLink.java#L138)

yes it does:

image

Can you re-add compatibility for that icon please?

**Comment by janfaracik** [comment]
> > Does this mean that plugins using the same icon will now show missing images? E.g. [jenkinsci/workflow-cps-plugin@`f522e78`/src/main/java/org/jenkinsci/plugins/workflow/cps/SnippetizerLink.java#L138](https://github.com/jenkinsci/workflow-cps-plugin/blob/f522e783e917bc0aa0513a29684285b710163905/src/main/java/org/jenkinsci/plugins/workflow/cps/SnippetizerLink.java#L138)
> 
> yes it does:
> 
> image
> 
> Can you re-add compatibility for that icon please?

I've duplicated the gear.svg icon as gear2.svg, it's a rather hacky fix

**Review by timja — APPROVED** [review]
it works, could introduce alias functionality in the icons list, but probably not worth it for one icon.

**Review by basil — APPROVED** [review]
This PR is now ready for merge. We will merge it after approximately 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process. Thanks!

**Review by res0nance — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]

**Pull request merged**
