### PR TITLE
[JENKINS-48614] Ensure optional dependencies of bundled and detached plugins are upgraded if necessary

### PR DESCRIPTION
**Pull request by dwnusbaum**
See [JENKINS-48614](https://issues.jenkins-ci.org/browse/JENKINS-48614).

Discovered in #3201.

### Proposed changelog entries

* Upgrade optional dependencies of bundled and detached plugins if the installed version of the dependency is older than the requested version.

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@reviewbybees

### CODE REVIEW

**Comment by dwnusbaum** [comment]
This PR is based on #3201 since it requires those changes.

**Comment by jglick** [comment]
@jenkinsci/code-reviewers also

**Comment by dwnusbaum** [comment]
Needs a test to confirm the problem before and after the proposed fix.

**Comment by oleg-nenashev** [comment]
Please request my review again when you finish it

**Review by jglick — COMMENTED** [review]
Still in progress?

**Comment by dwnusbaum** [comment]
@jglick No. It needs to be merged with master and a test should be created. I think this case is rare enough that it doesn't matter in practice. Will try to take finish it up if I have time on a weekend.

**Pull request closed without merging**
