### PR TITLE
Override more Tango icons with symbols

### PR DESCRIPTION
**Pull request by NotMyFault**
The change proposed overrides Tango icons with Jenkins symbols, which are not overridden yet, and removes a few dead icon references.

### Proposed changelog entries

* Override more Tango icons with Jenkins symbols

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

### CODE REVIEW

**Comment by janfaracik** [comment]
Looks great to me :)

**Review by janfaracik — APPROVED** [review]

**Comment by NotMyFault** [comment]
One of the icon overrides surprisingly causes a test failure, I'm not sure if I've located that right, running this specific test fails on master for me too 🤔

**Comment by timja** [comment]
> One of the icon overrides surprisingly causes a test failure, I'm not sure if I've located that right, running this specific test fails on master for me too 🤔

make sure you're running from maven command line and not via IntelliJ, as quite a lot of tests fail in intellij for some reason

**Comment by timja** [comment]
reminder @NotMyFault  in case you've forgotten about this

**Comment by NotMyFault** [comment]
> reminder @NotMyFault in case you've forgotten about this

Yeah, am aware. Just a bit busy atm, I'll try to pick it up next week.

**Comment by alecharp** [comment]
@NotMyFault do you still have this on your todo-list?

**Comment by NotMyFault** [comment]
> @NotMyFault do you still have this on your todo-list?

I'm looking forward to pick it up soonish again with a larger approach, no worries 👍🏻

**Pull request closed without merging**
