### PR TITLE
[JENKINS-63828] It is legal to have a CloudProvisioningListener not implementing `canProvision`

### PR DESCRIPTION
**Pull request by Vlatombe**
Follow-up of #4922, #4955

I got confused in https://github.com/jenkinsci/jenkins/commit/3992a30efb1abf697cae8e02f9e81dd04b92b135 by `Cloud#canProvision` which was abstract vs. `CloudProvisioningListener#canProvision` which wasn't and was returning `null`.

See [JENKINS-63828](https://issues.jenkins-ci.org/browse/JENKINS-63828).

### Proposed changelog entries

* Fix docker build agent provisioning (regression in 2.259-260) (take 2).

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by MRamonLeon — APPROVED** [review]

**Review by timja — APPROVED** [review]
lgtm would be good to get confirmation from users that are affected

**Review by oleg-nenashev — APPROVED** [review]
Looks fine from what I remember about Cloud API. Note that it still remains a high risk change, but at least it moves us forward towards a fix.

We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

@jenkinsci/core do we want to expedite it into the weekly?

**Comment by timja** [comment]
Yeah I think we should get it in to the weekly

**Comment by oleg-nenashev** [comment]
Will merge it taking the feedback above

**Comment by MarkEWaite** [comment]
Added to the 2.261 changelog in https://github.com/jenkins-infra/jenkins.io/pull/3861

**Pull request merged**
