### PR TITLE
Update availability_fr.html to remove esclave

### PR DESCRIPTION
**Pull request by clywyk**
Replace esclave with agent.

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

### Proposed changelog entries

* Entry 1: Issue, Human-readable Text
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by daniel-beck** [comment]
FYI there's a few more occurrences, but not too many: https://github.com/jenkinsci/jenkins/search?q=esclave&unscoped_q=esclave

**Comment by clywyk** [comment]
> FYI there's a few more occurrences, but not too many, in case you want to complete the task: https://github.com/jenkinsci/jenkins/search?q=esclave&unscoped_q=esclave

Thanks. I have PRs ready for all of them, but I'm new to this and wanted to make sure I was doing everything correctly. I'm waiting on a response from Marky, but if you can confimr, I'll submit all the PRs.

**Review by markjacksonfishing — APPROVED** [review]

**Comment by daniel-beck** [comment]
@clywyk It's probably easier to review and manage if you change all the French language files in one PR. Ideally you'd do this via a local checkout resulting in one larger commit for all the files, but even individual commits in the same PR, each changing a single file, something you can do from the GH UI, would be fine. A dozen or more different PRs is a bit much.

**Comment by clywyk** [comment]
Thanks, @daniel-beck . Not sure why I didn't think of that in the first place. Doing it now.

**Comment by clywyk** [comment]
Okay, @daniel-beck , it's done. 
https://github.com/jenkinsci/jenkins/pull/4801
@markyjackson-taulia

**Pull request closed without merging**
