### PR TITLE
WIP [JENKINS-54333] Try to prevent bubbling

### PR DESCRIPTION
**Pull request by scherler**
See [JENKINS-54333](https://issues.jenkins-ci.org/browse/JENKINS-54333) and maybe [JENKINS-54261](https://issues.jenkins-ci.org/browse/JENKINS-54261)

Prevent event bubbling and in case of IE11 explicitly do not submit the form and rely on the second "phantom" event to trigger the submit. 

...The problem is YUI lib and what I am doing is hacks-over-hacks because the real solution would be to drop YUI lib.

### CODE REVIEW

**Comment by daniel-beck** [comment]
Several legitimate looking UI test failures.

**Comment by scherler** [comment]
@daniel-beck 
```
expected:<... Yellow Banana split[]]> but was:<... Yellow Banana split[, Apple with 0 seeds , Apple with 0 seeds ]]> at junit.framework.Assert.assertEquals(Assert.java:100) at junit.framework.TestCase.assertEquals(TestCase.java:261) at lib.form.RepeatableTest.testDropdownList(RepeatableTest.java:357) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at junit.framework.TestCase.runTest(TestCase.java:176) at org.jvnet.hudson.test.HudsonTestCase.runTest(HudsonTestCase.java:444) at junit.framework.TestCase.runBare(TestCase.java:141) at org.jvnet.hudson.test.HudsonTestCase.runBare(HudsonTestCase.java:278) at junit.framework.TestResult$1.protect(TestResult.java:122) at junit.framework.TestResult.runProtected(TestResult.java:142) at junit.framework.TestResult.run(TestResult.java:125) at junit.framework.TestCase.run(TestCase.java:129) at junit.framework.TestSuite.runTest(TestSuite.java:252) at junit.framework.TestSuite.run(TestSuite.java:247) at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86) at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365) at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272) at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236) at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159) at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386) at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323) at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
```
Hmm not sure how that is related :(

**Comment by daniel-beck** [comment]
`RepeatableTest#testSimple` fails with:

> `expected:<[{"bool":false,"txt":"value one"},{"bool":false,"txt":"value two"},{"bool":true,"txt":"value three"}]> but was:<[{"txt":"value one","bool":false},{"txt":"value two","bool":false},{"txt":"value three","bool":true},{"txt":"","bool":false},{"txt":"","bool":false},{"txt":"","bool":false}]>`

IOW, instead of three elements, there are six.

Looking at https://github.com/jenkinsci/jenkins/blob/6baaf7d9b918d6afebbe0f0fa82b4aeb3a6626f7/test/src/test/java/lib/form/RepeatableTest.java#L69...L88, button clicks are involved. The view for it, https://github.com/jenkinsci/jenkins/blob/master/test/src/test/resources/lib/form/RepeatableTest/testSimple.jelly, looks pretty straightforward as well.

I wouldn't be surprised if the other test cases are just more complex variants of this one.

**Comment by scherler** [comment]
hmm, ok that maybe allows to track it further

**Comment by daniel-beck** [comment]
Superseded by https://github.com/jenkinsci/jenkins/pull/3761

**Pull request closed without merging**
