### PR TITLE
Remove Arabic and Portuguese translations

### PR DESCRIPTION
**Pull request by daniel-beck**
Per `translation-tool.pl`, both Arabic and Portuguese are just over 5% completed in terms of `.properties` files, and have no translated help files.

```
AR: Keys: 2015 Done: 116(5.76%) Missing: 1881(93.35%) Orphan: 18(0.89%) Empty: 0(0.00%) Same: 0(0.00%)
PT: Keys: 2015 Done: 127(6.30%) Missing: 1871(92.85%) Orphan: 7(0.35%) Empty: 4(0.20%) Same: 6(0.30%)
```

With these numbers, they escaped #2813, but spot-checking the files being removed here, the last contributions were more than 7 years ago, and nothing since.

I don't think it makes sense to keep these files around; anyone wanting to restart the translation effort can resurrect these files, or just start over.

FTR, the next least complete translations are 22% (Turkish) and 29% (Dutch), which is quite a bit better than these.

### Proposed changelog entries

* Remove partial (~6% complete) Arabic and Portuguese translations.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
What about making a public call for translation contributions @daniel-beck ? Just as an experiment

**Comment by daniel-beck** [comment]
Out of scope.

> anyone wanting to restart the translation effort can resurrect these files, or just start over

**Review by timja — APPROVED** [review]

**Review by basil — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
https://twitter.com/oleg_nenashev/status/1398259066955304969 for the last ditch attempt

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Review by oleg-nenashev — APPROVED** [review]
Approving it. No traction from the social media outreach. Should have tried LinkedIn, but uh oh. I will think about Arabic localization. It looks quite important for the user outreach taking wide usage of the language. Indeed it would need a few native speakers as maintainers, especially taking the potential UX obstacles due to right to left writing.

**Pull request merged**
