### PR TITLE
Begin migration to Jakarta Annotations

### PR DESCRIPTION
**Pull request by basil**
Downstream of jenkinsci/stapler#320.

### Problem

Core ships the Java EE annotation API, which is consumed both in core itself and in Stapler (a core dependency). Specifically, we consume `javax.annotation.PostConstruct`. `configuration-as-code`, `coverity`, `datetime-constraint`, `opentelemetry`, and `strict-crumb-issuer` consume `javax.annotation.PostConstruct` from core. `coverity`, `jira`, and `opentelemetry` consume `javax.annotation.PreDestroy` from core. `gitlab-plugin` consumes `javax.annotation.Priority` from core. All of these are subject to Jakarta package renames. This means we need to come up with a migration plan.

### Solution

This PR begins a migration by shipping both the old `javax.annotation` classes and the new `jakarta.annotation` classes, adjusting Stapler to check both `jakarta.annotation.PostConstruct` and `javax.annotation.PostConstruct` for backward compatibility. Stapler itself is migrated to `jakarta.annotation`, and when jenkinsci/stapler#320 is merged and released and core upgrades to it in this PR, then core can also switch to `jakarta.annotation`. This just leaves the plugins mentioned above. As each plugin upgrades its core baseline to one that includes a Stapler release with this PR, the plugin can migrate from `javax.annotation` to `jakarta.annotation`. Once each of the above plugins has done so and the PRs have been merged and released, `usage-in-plugins` should show no usages for `javax.annotation` in the ecosystem. At that point, the `javax.annotation:javax.annotation-api` dependency can be removed and the migration will be considered complete.

### Proposed changelog entries

Developer: The `javax.annotation.Generated`, `javax.annotation.ManagedBean`, `javax.annotation.PostConstruct`, `javax.annotation.PreDestroy`, `javax.annotation.Priority`, `javax.annotation.Resource`, `javax.annotation.Resources`, `javax.annotation.security.DeclareRoles`, `javax.annotation.security.DenyAll`, `javax.annotation.security.PermitAll`, `javax.annotation.security.RolesAllowed`, `javax.annotation.security.RunAs`, `javax.annotation.sql.DataSourceDefinition`, and `javax.annotation.sql.DataSourceDefinitions` annotations have been deprecated in favor of the equivalent classes in the `jakarta.annotation` package. Plugin developers should migrate to the Jakarta Annotations version of each of the above annotations.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by jtnord** [comment]
(How) does this affect plugins using guice for wiring.
Does guice recognise the new annotations or will some resources not be correctly wired in plugins using guice injection?

**Comment by basil** [comment]
> does this affect plugins using guice for wiring.

No. Guice 5.0.1 contains no references to `javax.annotation` other than `javax.annotation.Nullable` and `javax.annotation.concurrent.NotThreadSafe` (which are not relevant to the question).

> Does guice recognise the new annotations or will some resources not be correctly wired in plugins using guice injection?

Guice recognizes neither the old nor the new annotations and is unaffected by this PR.

**Comment by basil** [comment]
This PR is now ready for merge. We will merge it after approximately 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process. Thanks!

**Review by oleg-nenashev — APPROVED** [review]

**Comment by jtnord** [comment]
> > does this affect plugins using guice for wiring.
> 
> No. Guice 5.0.1 contains no references to `javax.annotation` other than `javax.annotation.Nullable` and `javax.annotation.concurrent.NotThreadSafe` (which are not relevant to the question).
> 
> > Does guice recognise the new annotations or will some resources not be correctly wired in plugins using guice injection?
> 
> Guice recognizes neither the old nor the new annotations and is unaffected by this PR.

s/guice/sezpoz.
IIUC any Extension using `javax.annotation.PostConstruct` will no longer be called as the `ExtensionFinder` (ref)[https://github.com/jenkinsci/jenkins/blob/df901a6b4eca73a361a7bdb8d0dc8fa97c6d7ccc/core/src/main/java/hudson/ExtensionFinder.java#L567-L597] is now ignoring these will now no longer work as I understand it as the `ExtensionFinder` will not call them?

**Review by jtnord — CHANGES_REQUESTED** [review]
I do not beleive that this works for existing plugins using Extension Lifecycle managent.

**Comment by basil** [comment]
Ah yes, we do need to check for both the old `PostConstruct` and the new `PostConstruct` annotations. I already did that in Stapler in `org.kohsuke.stapler.MetaClass` but neglected to do it in SezPoz. Simple fix.

**Review by jtnord — APPROVED** [review]

**Pull request merged**
