### PR TITLE
Upgrade jQuery to 3.5.x

### PR DESCRIPTION
**Pull request by fqueiruga**
This PR bumps the jQuery version from 2.1.4 to 3.5.x. 
I have created the PR in order to properly test it with a CI build.

JS changes:
- Remove uses of the .size() and .load() methods
- Remove the unit tests on the maven test command because they have not been ported

Testing command:
- `docker run --rm -it -p 8080:8080 -e ID=4929 jenkins/core-pr-tester`

### Proposed changelog entries

* TBD

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@uhafner
@Wadeck 
@timja 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by fqueiruga — COMMENTED** [review]
Taking this one out of WIP status as the proper work is done but there are some discussions and some work left.

Most of the JS unit tests do not work with this PR. These tests are very difficult to migrate and offer little value, as most of the use-cases they cover are also covered by JTH and ATH suites. Any thoughts on this?

**Review by timja — COMMENTED** [review]
are you running ATH over this? (more than just the default smoke tests that run on CI)

> Most of the JS unit tests do not work with this PR. These tests are very difficult to migrate and offer little value, as most of the use-cases they cover are also covered by JTH and ATH suites. Any thoughts on this?

Can probably remove.

**Comment by fqueiruga** [comment]
I'll get back to you with a full ATH run hopefully tomorrow

**Comment by fqueiruga** [comment]
I have verified that there are no ATH errors that happen in other PRs.

**Review by timja — APPROVED** [review]

**Review by Wadeck — APPROVED** [review]
Random manual testing (like monkey typing on keyboards), looking for console errors. Core (without plugins) was working fine, testing with multiple pages.

**Review by uhafner — APPROVED** [review]
Nice! This PR makes my jQuery plugin obsolete (if this PR is part of an LTS). Is jQuery 3.x then available as `$` in views or do we still need workarounds? (How does this change relate to https://github.com/jenkinsci/jquery-plugin? Is this plugin then obsolete as well?)

**Review by romenrg — APPROVED** [review]
Just ran some manual smoke tests, clicking random stuff and checking both behavior and the inspect console, as Wadeck did; and everything looks good to me.

**Comment by fqueiruga** [comment]
> Nice! This PR makes my jQuery plugin obsolete (if this PR is part of an LTS). Is jQuery 3.x then available as `$` in views or do we still need workarounds? (How does this change relate to https://github.com/jenkinsci/jquery-plugin? Is this plugin then obsolete as well?)

It does not. The jQuery version is contained to the bundles generated by webpack and not exposed to the `window` namespace. It should have no effect in any plugin (except those that hook up to the setup wizard).

**Comment by fqueiruga** [comment]
For context, `$` in vanilla jenkins (no plugins) corresponds to the prototype object, not jquery

**Comment by fqueiruga** [comment]
I have run a comprehensive PCT suite and have found some errors that I need to go through. I suspect is due to outdated POMs but still, I'd like to have the PR marked as _on hold_ maybe after the LTS selection.

**Comment by timja** [comment]
> I have run a comprehensive PCT suite and have found some errors that I need to go through. I suspect is due to outdated POMs but still, I'd like to have the PR marked as _on hold_ maybe after the LTS selection.

@fqueiruga should unhold be removed now?

**Comment by fqueiruga** [comment]
TBH I would like to give it a few weeklies of margin, maybe get it in 2.266 or 2.267. The reason is that I don't want the bug reports arising from tables-to-divs to be muddied by this PR, if that makes sense.

**Review by res0nance — APPROVED** [review]

**Comment by timja** [comment]
thoughts on shipping in 2.266?

**Comment by MarkEWaite** [comment]
> thoughts on shipping in 2.266?

I've mentioned that this change is coming in a [proposed blog post](https://github.com/jenkins-infra/jenkins.io/pull/3943) inviting users and administrators to assist with testing Jenkins weekly releases.  I think that including it in Jenkins 2.266 does not complicate bug triage any more than it is already.

**Comment by fqueiruga** [comment]
Let's go then!

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Review by oleg-nenashev — APPROVED** [review]
It is a bit YOLO, but we should merge it sooner or later. I vote for merging sooner, we have only 1 month before the Christmas break so extra week is a good addition for user feedback

**Comment by liuweiGL** [comment]
I think this is a break change? My plugin  stopped working.

link: https://github.com/jenkinsci/dingtalk-plugin/blob/ca8695a276d3e2258b363f6f35a48573e3e6db14/src/main/webapp/scripts/customValidate.js#L9

**Comment by fqueiruga** [comment]
@liuweiGL can you comment this on the issue? From what I see, your plugin is no loading jQuery in package.json, or in POM.xml. This change was also scoped to just Jenkinsci and should have no sideffects on other plugins.

From what I see, that $ variable may be referring to the prototypejs instance that Jenkins provides. jQuery does not provide a `.up()` method, but prototype does http://api.prototypejs.org/dom/Element/up/

**Comment by fqueiruga** [comment]
@liuweiGL I think your plugin may have broken on the tables-to-divs release on Jenkins 2.264, given that the change is to DOM transversal on a form function. You could report the issue on the appropiate epic https://issues.jenkins.io/browse/JENKINS-62437 and tag the issue with the label `tables-to-divs-regression`. More information on how to fix the plugin on https://www.jenkins.io/blog/2020/11/10/major-changes-in-weekly-releases/#plugin-developers

**Comment by liuweiGL** [comment]
Thank you very much.

**Pull request merged**
