### PR TITLE
Added New Document 

### PR DESCRIPTION
**Pull request by 555vedant**
See [JENKINS-XXXXX](https://issues.jenkins.io/browse/JENKINS-XXXXX).

### Proposed changelog entries

- JENKINS-XXXXX, human-readable text

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Comment by NotMyFault** [comment]
Please refrain from opening PRs of this kind. We're not interested in that.
In your previous pr I left you a link to the resources how to contribute properly.

If you continue to spam these kind of PRs, we will restrict your access to the organization.

**Comment by 555vedant** [comment]
Apologies, Sir. This is my first time contributing to such a large organization, and I'm still in the learning process. Please cooperate with me as I work to improve. I assure you, I am not a spammer, and I am committed to giving my best effort from now on.

**Comment by 555vedant** [comment]
I have added a new template in README.md. Should I create a pull request for it?

**Comment by MarkEWaite** [comment]
@555vedant I agree with @NotMyFault that open source projects like Jenkins are not the place for practice pull requests that do not provide real value and are immediately followed by requests to help you refine the pull request.  Create your own repository on GitHub and use it to submit practice pull requests.

When you created this pull request and the previous pull request, the pull request template was provided to you with many items to be completed.  You did not complete those items.  You left them with their default values.

It is very important that you read, understand, and complete the tasks from the pull  request template and from other written forms like the pull request template.  When you don't read, understand, and complete the tasks from the pull  request template, you waste the time of maintainers while they are trying to decide if your submission is worth reviewing.

The same advice applies when submitting a bug report.  A bug report is much less valuable if it does not provide enough information so that others can duplicate it.

**Comment by 555vedant** [comment]
@MarkEWaite thanks sir for you great advice i will take care onwards

**Comment by 555vedant** [comment]
Screenshot 2024-02-16 195916

**Pull request closed without merging**
