### PR TITLE
[JENKINS-72956] Skip Spotless in `quick-build` profile

### PR DESCRIPTION
**Pull request by daniel-beck**
See [JENKINS-72956](https://issues.jenkins.io/browse/JENKINS-72956). Amends https://github.com/jenkinsci/jenkins/pull/7863.

### Testing done

Added a new unused import in a file in `cli/src/main/`. `-Pquick-build` failed before this change, passes after.

Renamed this profile `quick-build2` and set only that. Tests etc. were then executed due to lack of ID overlap, but no Spotless.

Explicitly set `spotbugs.skip` to `false` in this `quick-build` profile and observed Spotbugs to be running.

### Proposed changelog entries

N/A

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [x] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Review by basil — COMMENTED** [review]
While this does solve the problem, it's a solution that I wouldn't feel comfortable adopting more broadly (i.e., in other core components, or in Jenkins plugins), as it involves copying and pasting this snippet into all of them to apply the solution there.

So the question becomes whether we should adopt a one-off solution to the problem only in Jenkins core, or whether we should make Jenkins core consistent with plugins and other core components by changing the documentation and requiring users to pass both `-Pquick-build` and `-Dspotless.check.skip`.

I have a slight preference for the latter to create consistency, but I wouldn't block the former in this one case. I would be against the idea of adding this snippet to every single core component and plugin, though.

**Comment by daniel-beck** [comment]
@basil You're making a reasonable argument. Ultimately I'd like for `-Pquick-build` to skip Spotless though.

Would the following change to the parent pom be acceptable to you? A quick local check seems to produce the desired outcome.

```diff
diff --git a/pom.xml b/pom.xml
index 7be0740..a38919c 100644
--- a/pom.xml
+++ b/pom.xml
@@ -1010,6 +1010,7 @@
         <!-- we can not use maven.test.skip because we may be producing a test jar -->
         <skipTests>true</skipTests>
         <spotbugs.skip>true</spotbugs.skip>
+        <spotless.skip>true</spotless.skip>
         <enforcer.skip>true</enforcer.skip>
         <access-modifier-checker.skip>true</access-modifier-checker.skip>
         <invoker.skip>true</invoker.skip>
```

**Comment by basil** [comment]
I'm a bit confused as to the meaning of `spotless.skip`. https://github.com/diffplug/spotless/blob/1ad019da39f8994d5b7ccd86a536678cb38fbdea/plugin-maven/README.md says the property is named `spotless.check.skip` and that's what I'm using in `plugin-pom`.

If you meant `spotless.check.skip`, then that would be essentially a revert of https://github.com/jenkinsci/pom/pull/427 which would reintroduce https://github.com/jenkinsci/pom/issues/425. Or am I missing some subtlety between `spotless.check.skip` and (an undocumented?) `spotless.skip`?

**Comment by daniel-beck** [comment]
I basically guessed the name when I wrote this and it changed behavior 🤷 

Looking at upstream, there is https://github.com/diffplug/spotless/blob/1ad019da39f8994d5b7ccd86a536678cb38fbdea/plugin-maven/src/main/java/com/diffplug/spotless/maven/AbstractSpotlessMojo.java#L105-L106 and https://github.com/diffplug/spotless/blob/1ad019da39f8994d5b7ccd86a536678cb38fbdea/plugin-maven/src/main/java/com/diffplug/spotless/maven/AbstractSpotlessMojo.java#L244-L259, so it looks like `.skip` takes precedence, which also means no unexpected interactions with the otherwise set `.check.skip`.

**Comment by basil** [comment]
That's brilliant. So by stumbling upon this poorly documented property, we seem to have found a solution to the general problem that can be applied to both `pom` and `plugin-pom`. That sounds great to me!

**Comment by daniel-beck** [comment]
Superseded by https://github.com/jenkinsci/pom/pull/537

**Pull request closed without merging**
