### PR TITLE
[JENKINS-26147] New home for BUILD_NOW_TEXT

### PR DESCRIPTION
**Pull request by jglick**
@reviewbybees

### CODE REVIEW

**Comment by jtnord** [comment]
:bee:

**Comment by recena** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
Falling back to such default value resolves all my previous concerns.
BTW I still don't like the usage of <code> ParameterizedJobMixIn</code>, because the "Build now" customization should be also applicable for non-parameterizable Job types.

**Comment by jglick** [comment]
> the "Build now" customization should be also applicable for non-parameterizable Job types

The only usage is from a method called only on a `ParameterizedJob`, which also handles _Build with Parameters_ (not currently customizable). In principle another `Job` type could come along which supports triggering builds, but not parameters, and to reuse existing code would require some other refactorings.

**Comment by jglick** [comment]
`CommandLauncherTest.commandSuceedsWithoutChannel` failure looks unrelated.

**Pull request merged**
