### PR TITLE
[FIX JENKINS-30565] Ask for confirmation before canceling/aborting

### PR DESCRIPTION
**Pull request by daniel-beck**

### CODE REVIEW

**Comment by KostyaSha** [comment]
How disable this super feature? I don't want pressing additional confirmations like in windows

**Comment by daniel-beck** [comment]
> Never had problems with 'rm' command in linux and abort in jenkins.

One is a command you need to type and confirm rather than a single button you may accidentally click while moving the mouse around. And then there's the issue of clicking the wrong abort-button because you aimed just before the AJAX refresh.

UIs even on Linux either ask for confirmation, have a trash can or similar feature (making any actions easily reversible), or do both. Jenkins currently has neither, making every accidental click final.

> How disable this super feature?

IMO this can always be added later when it appears there is actual demand for it. If such an option were implemented, doing it site-wide would be the wrong way to go. Maybe do it as a `UserProperty`, similar to case sensitive search?

**Comment by KostyaSha** [comment]
Advanced mode in user profile?

**Comment by oleg-nenashev** [comment]
I have no strong opinion. "fast clicking" is unreliable.

> Side effect is that if i mistakenly run build i want abort it very fast. And now i can do it.

A better way would be to ask for the confirmation for starting the build

**Comment by KostyaSha** [comment]
> A better way would be to ask for the confirmation for starting the build

I think usually people starting more right builds rather than canceling wrong. 
What about allowing skipping without confirmation for admins?)

**Comment by daniel-beck** [comment]
> "Advanced" mode checkbox in user profile?

@KostyaSha Yes, something like that is what I've been proposing in the comment before yours.

I think this change would improve user experience by preventing accidental aborts despite being a minor nuisance. Options can always be added later if there's notable demand for it.

**Comment by oleg-nenashev** [comment]
Cannot be merged now (after the pagination PR?)

**Comment by KostyaSha** [comment]
> oleg-nenashev added the needs-fix label 7 days ago

Bad label

**Comment by daniel-beck** [comment]
@oleg-nenashev Updated PR.

**Comment by oleg-nenashev** [comment]
👍 It makes sense to have it as a default behavior.
I agree with @KostyaSha that the original behavior may be useful in some cases. The fix cannot be quickly delivered into LTS, so I think it would be great to support the original behavior before merging

**Comment by batmat** [comment]
:+1: makes sense. It's not like you abort builds every minute, hence having a confirmation doesn't hurt.

**Comment by KostyaSha** [comment]
> makes sense. It's not like you abort builds every minute, hence having a confirmation doesn't hurt.

Then why not add confirmation before running the build? Image that this is the production not parametrized deployment.

**Comment by batmat** [comment]
Yes. Why not. Feel free to file the associated PR indeed. 

In my case, I actually rarely click on the start button for builds explicitly. 99% of the time, it's starting alone after a code checkin or something. Also, the main difference is: there's no start button in the queue or in the running builds on the left panel. And that is those button that may be moving too fast and make you effin' click on the wrong one. So that usability glitch would be fixed here.

**Comment by batmat** [comment]
For those wanting to try it out:
`docker run -ti -p 8080:8080 -e ID=1835 batmat/jenkins-pr-tester`
Then open your browser on [http://localhost:8080](http://localhost:8080)

**Comment by daniel-beck** [comment]
> Then why not add confirmation before running the build? Imagine this is the production not parametrized deployment.

Typically, an accidentally started build can be aborted immediately without adverse side effects.

A build that has been running for several hours cannot easily be "un-aborted", however.

**Comment by oleg-nenashev** [comment]
@daniel-beck So, do we want to go forward according to the voting results? I mean merge

**Comment by daniel-beck** [comment]
@oleg-nenashev Thanks for the reminder.

**Pull request merged**
