### PR TITLE
Make env-vars.html nicer and actually localizable

### PR DESCRIPTION
**Pull request by daniel-beck**
A minor improvement to https://ci.jenkins.io/env-vars.html/

* Use the regular Jenkins layout in "one-column" mode. Still not great for what's essentially a popup, but better than we have now.
* Make the introductory line actually localizable. [It never was](https://github.com/jenkinsci/jenkins/commit/72fbaba27538e9bb0c66b1759435dfaff8c4efb0#diff-c6c354c97ef2b3f67805445d53e806f692dff9b25c297adb885ca7ae4ebddd1bR11), we just had unused localizations for it.
* Since the introductory line changed a bit, also remove those unused localizations.

### Proposed changelog entries

* Improve visualization of the Environment Variables page

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by timja — APPROVED** [review]
should probably set an h1 on the page as well but looks good apart from that, it's an improvement anyway so approving

image

**Review by oleg-nenashev — APPROVED** [review]
LGTM though I would rather put it to the changelog as RFE

**Comment by oleg-nenashev** [comment]
We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Comment by oleg-nenashev** [comment]
@daniel-beck FYI I added a changelog suggestion

**Pull request merged**
