### PR TITLE
JENKINS-64049 Replace whitespaces in BUILD_TAG

### PR DESCRIPTION
**Pull request by 95jonpet**
See [JENKINS-64049](https://issues.jenkins-ci.org/browse/JENKINS-64049).

Replaces whitespaces in `BUILD_TAG` with dashes to improve tag portability.
This change should make it easier to use the generated `BUILD_TAG` in other systems where whitespaces are not allowed.

### Proposed changelog entries

* JENKINS-64049: Replace whitespaces with dashes in generated `BUILD_TAG`.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by res0nance** [comment]
This sounds like changing this might be an issue for people who rely on the whitespace

**Comment by 95jonpet** [comment]
> This sounds like changing this might be an issue for people who rely on the whitespace

It cannot be controlled directly. I don't imagine people relying on having spaces in their job names so that their build tags will contain spaces and so that they may carry a meaning. 

Jenkins and many of its plugins are terrible at dealing with special characters such as whitespacing and non-latin language related characters.

**Review by MRamonLeon — APPROVED** [review]
Seems reasonable to me, don't know too much about possible implications, though

**Comment by daniel-beck** [comment]
> I don't imagine people relying on having spaces in their job names so that their build tags will contain spaces and so that they may carry a meaning.

While technically a potentially breaking change, this is different from doing something similar to `JOB_NAME`, as the upgrade will happen while most builds are not running, so one build will have spaces, the next one won't. Upgrade scenarios involving running pipelines using `BUILD_TAG` are possible but likely rare.

That said, a lot more problematic characters than just whitespace would potentially be part of build tags, such as CJK characters. If we want the `BUILD_TAG` to be universally safe to use (assuming that's the goal here?), any other characters legal in a job name but potentially problematic as a path should be considered as well.

Replacing any of a larger set of characters with the same `-` also increases the likelihood of tag collisions.

**Comment by jglick** [comment]
Is this really necessary? If you run into problems with the value of `$BUILD_TAG`, you can

* Replace it at point of consumption with something more tailored to your needs, using shell scripting or whatever. As in https://github.com/jenkinsci/jenkins/pull/5036#issuecomment-723486752, there are lots of different systems with lots of different requirements (metacharacters, case sensitivity, length): `docker tag` values, Kubernetes identifiers, etc.
* Pick a more reasonable job name to begin with, and edit the display name as desired. Which you should do for lots of reasons anyway.

**Comment by jtnord** [comment]
Given the comment from @jglick and @daniel-beck I think this is "propose for close".

BuildTag is documented as to what it does and changing this behaviour seems not the best, and if you need to remove spaces it can be done using shell/bat as suggested above.

**Pull request closed without merging**
