### PR TITLE
[JENKINS-30742] Fixed possible NPE in AbstractProject.resolveForCLI()

### PR DESCRIPTION
**Pull request by pjanouse**
Please review, thx.

### CODE REVIEW

**Comment by KostyaSha** [comment]
Wasn't it already merged?

**Comment by oleg-nenashev** [comment]
https://github.com/jenkinsci/jenkins/pull/1841
seems so

**Comment by oleg-nenashev** [comment]
However, it's a different issue in another class
:+1:

**Comment by KostyaSha** [comment]
Could it have any test case?

**Comment by pjanouse** [comment]
Sure, test added...

**Comment by pjanouse** [comment]
Fail isn't related to this PR.

**Comment by KostyaSha** [comment]
@daniel-beck

**Comment by oleg-nenashev** [comment]
re :+1: 
The test should be investigated separately, it's not related

**Comment by pjanouse** [comment]
So should I remove the test from this PR and create a new one?

**Comment by oleg-nenashev** [comment]
@pjanouse 
My comment was related to the PR builder failure, which is unrelated to your PR. The proposed test is here, everything is fine IMO.

:+1:

**Pull request merged**
