### PR TITLE
Noarchiveonsuccess

### PR DESCRIPTION
**Pull request by ScoobyChris**
Add option to only archive when the build is not successful.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
I would rather add "successfull" and "unsuccessfull" wildcards.
It would make the behavior more flexible, but probably it's too late.

**Comment by ScoobyChris** [comment]
Hi Oleg,

I'd considered this approach but didn't want to change the interface too
much and break existing configurations.

Would certainly be a cleaner and more flexible solution and I'd be happy to
implement if there was support for it.

Chris

**Comment by oleg-nenashev** [comment]
@ScoobyChris 
After some investigation I think there is no need to implement much advanced options, because a Jenkins user can always wrap ArchiveArtifacts by Flexible Publish plugin with its Run conditions.

Regarding this PR, I'm :+1: for it as it goes to advanced configs. User of advanced configs should be ready to the undefined behavior if he checks <code>onlyIfSuccessful</code> and <code>onlyIfNotSuccessful</code> at the same time

**Comment by daniel-beck** [comment]
:-1: Should be implemented as a selection of statuses for when to archive, or a dropdown (Always, When Successful, When Unsuccessful), rather than just another top-level checkbox, given that it results in the weirdness mentioned by @oleg-nenashev .

FWIW it would be interesting to know what the use case for this is.

**Comment by ScoobyChris** [comment]
The use case is for test jobs which store system/product logs.  We don't
care about them for successful builds and they take up a lot of disk
space.  For failed builds they are useful to identify problems and we want
to keep them.

I'll look at deprecating the existing "only on success" checkbox and add a
new parameter which allows selectable filtering for build results.

Chris

**Comment by daniel-beck** [comment]
Looks more like a job for a custom build discarder/log rotator.

**Comment by jtnord** [comment]
@daniel-beck why would you want to archive stuff (could be talking about 2GB or more!)  if you know you are going to throw it away - it's slow and wasteful.

But can probably be acheived with the [Flexible Publish Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Flexible+Publish+Plugin) if people are worried about configuration issues in a core feature.

**Comment by KostyaSha** [comment]
@ScoobyChris sounds like better architecture would be to store logs in some binary storage (i..e artifactory) and use flexible-publish (or workflow?) to make decision about executing log upload step.

The real question will be whether you want automatically remove logs from this binary storage with build deletion.

**Pull request closed without merging**
