### PR TITLE
[JENKINS-59679] Use plugin URL from the update site rather than the manifest

### PR DESCRIPTION
**Pull request by zbynek**
See [JENKINS-59679](https://issues.jenkins-ci.org/browse/JENKINS-59679).

### Proposed changelog entries

* Plugin description links always point to the plugin site instead of the Jenkins wiki.

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [N/A] For dependency updates: links to external changelogs and, if possible, full diffs

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
JIRA ticket does not look to be a correct one

**Comment by zbynek** [comment]
> JIRA ticket does not look to be a correct one
Thanks, fixed.

**Review by jvz — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
Works as expected in the Core PR tester. Maybe it makes sense to consider it as bug and to backport it into the current LTS baseline. No strong opinion.

It might be also nice to do something about PluginWrapper API so that we can test such cases without mocking

**Comment by zbynek** [comment]
@oleg-nenashev good point, I removed the usage of Mockito where it made no sense.

**Review by oleg-nenashev — APPROVED** [review]

**Review by alecharp — APPROVED** [review]

**Comment by daniel-beck** [comment]
Do we recognize private builds of existing plugins (`git-3.10.1-acme-1`) that are _not_ distributed through additional private update sites to be a valid use case? I will probably link to `wiki.acme.org` in my private build.

Notably, even the way `#getInfo` handles the "closest match" search will not help when Git Plugin is on 3.12.x in updates.jenkins.io, but only on 3.10.1-acme-1 with a configured update site.

(There's a reason I didn't change this when I changed the URLs.)

**Comment by zbynek** [comment]
@daniel-beck should I change to code to check that the site has the _precise_ version that we have installed and if yes, use that for URL?

**Comment by daniel-beck** [comment]
> version that we have installed and if yes, use that for URL

Outdated plugins will then link to the wiki/GitHub, which will look pretty much random to admins. I do not think this is a good option.

**Comment by daniel-beck** [comment]
(To clarify, if consensus is that what I'm bringing up is not a use case we support, then I guess that's fine too. But it simply hasn't been mentioned before.)

**Comment by oleg-nenashev** [comment]
Looks like it needs more discussion

**Comment by zbynek** [comment]
@daniel-beck would the following be acceptable:
* get info from all plugin sites
* if they all refer to the same nonempty URL, use it
* fallback to old behavior (manifest URL if nonempty, first applicable plugin site otherwise)
In case there is just one plugin site, this behaves like my original PR.

**Comment by daniel-beck** [comment]
@zbynek That makes sense.

FWIW I may still have an unfinished improvement around that would add a standalone page for plugin metadata so we don't have to put everything we want to show into the table. In that approach, the plugin name in the table links to that page instead. This would also allow us to link to multiple URLs (the built-in one from the plugin, any URLs from update sites). WDYT is that a useful addition?

**Comment by zbynek** [comment]
@daniel-beck I added support for multiple update sites.

> standalone page for plugin metadata

Sounds cool. Maybe the detail page could be similar to the page on the plugin site (+an install button), removing the need to navigate away.

**Review by rsandell — APPROVED** [review]

**Review by fcojfernandez — APPROVED** [review]

**Comment by rsandell** [comment]
@daniel-beck Are your concerns addressed? is this ready for merge?

**Review by daniel-beck — APPROVED** [review]
Thanks for the enhancement!

Haven't tested this, but the code and tests look reasonable.

**Comment by fcojfernandez** [comment]
Marking the PR as `ready-fo-merge`

**Pull request merged**
