### PR TITLE
[JENKINS-67742] Replace computer-flash gif

### PR DESCRIPTION
**Pull request by NotMyFault**
Fixes [JENKINS-67742](https://issues.jenkins.io/browse/JENKINS-67742)

The change proposed utilizes the hourglass icon, which already is used for launching executors.

### Proposed changelog entries

* Replace the computer-flash GIF icon with the hourglass icon.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@timja 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by timja — APPROVED** [review]
I think this is fine any other thoughts?

image

image

**Review by uhafner — APPROVED** [review]
I think it is better than a blinking computer, so I am fine with that change. 

But in general I think it is not necessary to show a different icon here. 

- build executor status: The hourglass is already shown in the brackets. So I would show the normal agent icon here. (Which should be something like https://fontawesome.com/v5.15/icons/server?style=solid in the future, a fitting ionicon seems to be not available). 
- agent details view: Here we should show the solid agent icon as well and maybe add our progress animation on the right side.

**Comment by timja** [comment]
What did you think about making Ulli's suggested changes?

**Review by uhafner — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Pull request merged**
