### PR TITLE
Refactoring CLIRegisterer

### PR DESCRIPTION
**Pull request by T45K**
In #4641, a method named `logAndPrintError` was extracted (refactored), but its similar class, `CLIRegisterer` was not modified.
I refactored the class to make consistent and reduce duplicated code.

This PR is for minor changes without a JIRA ticket.

### Proposed changelog entries

N/A

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- The refactoring done should not change the behaviour of existing code, so the tests should not need to be changed.
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

N/A

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by daniel-beck — COMMENTED** [review]
Interesting suggestion, thanks for your submission.

I'm unsure whether it is worth it yet. For one thing, the new method has more arguments than lines of code to make it work, effectively reducing readability through an additional level of indirection. Perhaps if it was extended to all error messages rather than two out of seven or so it could be worth it? Log related arguments could be optional, or a new method `printError` be created that does only this.

**Comment by T45K** [comment]
@daniel-beck Thank you for your comment.

Your recommendation sounds very good. I'll add `printError` method, which extracted from all error messages.

**Comment by T45K** [comment]
@daniel-beck 

I've done the modification. Would you check it again?

**Review by MRamonLeon — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Looks good in the current state.  We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Review by daniel-beck — APPROVED** [review]
Much nicer, thanks.

**Review by stellargo — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Thanks for your contribution @T45K ! Just in case you are interested to submit more patches, the Jenkins project participates in Hacktoberfest this year. https://www.jenkins.io/events/hacktoberfest/

**Pull request merged**
