### PR TITLE
Bump parent pom to 1.55

### PR DESCRIPTION
**Pull request by timja**
Release notes: https://github.com/jenkinsci/pom/releases/tag/jenkins-1.55
most notable change is introducing findsecbugs

### Proposed changelog entries

* Entry 1: None needed
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@StefanSpieker 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by timja** [comment]
not really sure if it needs a changelog entry or not

**Comment by jeffret-b** [comment]
@timja, we also need to take out the local customization to add findsecbugs into this pom at [lines 414-420](https://github.com/jenkinsci/jenkins/blob/8c1799de8c7f6e0589ae6420d32520e4fab764db/pom.xml#L414). And do a double to make sure findsecbugs is getting inherited properly. I can help out with that if you want.

**Comment by jeffret-b** [comment]
This shouldn't need a changelog entry. It doesn't change the behavior, just where it gets it from.

**Comment by timja** [comment]
> @timja, we also need to take out the local customization to add findsecbugs into this pom at [lines 414-420](https://github.com/jenkinsci/jenkins/blob/8c1799de8c7f6e0589ae6420d32520e4fab764db/pom.xml#L414). And do a double check to make sure findsecbugs is getting inherited properly. I can help out with that if you want.

sure go for it

**Comment by jeffret-b** [comment]
I don't know the best way to propose a change to you, but if you remove the findsecbugs plugin inclusion ([lines 414-420](https://github.com/jenkinsci/jenkins/blob/8c1799de8c7f6e0589ae6420d32520e4fab764db/pom.xml#L414)), the inheritance will all work and we're good to go.

**Comment by timja** [comment]
> I don't know the best way to propose a change to you, but if you remove the findsecbugs plugin inclusion ([lines 414-420](https://github.com/jenkinsci/jenkins/blob/8c1799de8c7f6e0589ae6420d32520e4fab764db/pom.xml#L414)), the inheritance will all work and we're good to go.

You can either send a PR to my fork, or I think you should have direct push access as well, I've pushed a commit anyway but feel free to push a follow up

**Review by jeffret-b — APPROVED** [review]
This is good. I've tested out the findsecbugs behavior with this change. It now inherits the findsecbugs inclusion from the parent and still does the same spotbugs and findsecbugs checks as before.

**Review by res0nance — APPROVED** [review]

**Comment by timja** [comment]
@jeffret-b you know anything about this?
```

[2020-04-16T20:21:11.925Z] [INFO] --- spotbugs-maven-plugin:4.0.0:spotbugs (spotbugs) @ jenkins-core ---

[2020-04-16T20:21:12.869Z] [INFO] Fork Value is true

[2020-04-16T20:27:19.564Z]      [java] The following classes needed for analysis were missing:

[2020-04-16T20:27:19.564Z]      [java]   test

[2020-04-16T20:27:19.564Z]      [java]   apply

[2020-04-16T20:27:19.564Z]      [java]   get

[2020-04-16T20:27:19.564Z]      [java]   call

[2020-04-16T20:27:19.564Z]      [java]   accept

[2020-04-16T20:27:19.564Z]      [java]   check

[2020-04-16T20:27:19.564Z]      [java]   getString

[2020-04-16T20:27:19.564Z]      [java]   visit

[2020-04-16T20:27:19.564Z]      [java]   compare

[2020-04-16T20:27:19.564Z]      [java]   run

[2020-04-16T20:27:19.564Z]      [java]   convert

[2020-04-16T20:27:19.564Z]      [java]   generateResponse

[2020-04-16T20:27:19.564Z]      [java]   invoke

[2020-04-16T20:27:19.564Z]      [java]   reportException

[2020-04-16T20:27:19.564Z]      [java]   shouldRetry

[2020-04-16T20:27:19.564Z]      [java]   uncaughtException
```

https://ci.jenkins.io/blue/organizations/jenkins/Core%2Fjenkins/detail/PR-4661/2/pipeline

**Comment by jeffret-b** [comment]
I'm quite familiar with it. It can be safely ignored. It's a spotbugs issue where they raise "stupid warnings". They're leaking too much internal logging through to users, where it's just confusing to users. It would be nice if they could get this fixed. See spotbugs/spotbugs#527 . It shows up under some configurations, but not all and there doesn't seem to be anything that we, as spotbugs users, can do to influence it.

**Comment by jeffret-b** [comment]
Oh, I just checked the build. This is causing build failures?! I'll look more.

**Comment by jeffret-b** [comment]
I found the problem and submitted a fix for it. You were a little aggressive in what you removed and I didn't review carefully enough to catch it. I expect it to work now.

**Comment by timja** [comment]
Let’s merge this tomorrow if no negative feedback

**Review by oleg-nenashev — APPROVED** [review]
Less code is good

**Pull request merged**
