### PR TITLE
Add plugin index page with technical information

### PR DESCRIPTION
**Pull request by daniel-beck**
Builds on top of https://github.com/jenkinsci/jenkins/pull/4687 with an application for that change.

Thoughts? Implementation is a bit rough, can be cleaned up if the idea is sound. Also no permission checks yet.

URLs are currently unlinked, but would be:

JENKINS/pluginManager/plugin/ID/
JENKINS/plugin/ID/wrapper/

#### Structs (mostly empty)

> 

#### Matrix Auth (some stuff)

> 

#### Credentials (very long list)

> 

### Proposed changelog entries

* Add pages showing internal diagnostic information for each installed plugin

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by jvz** [comment]
Ooh, this looks pretty sweet so far!

**Comment by res0nance** [comment]
Looks nice, some questions
- Who is this for?
- Given we know who this is for, what information do we want to ensure is accessible?

Might give a good idea of how to organize all this information

**Comment by oleg-nenashev** [comment]
I am not against it, but IMHO it should be rather integrated into the plugin site

**Comment by daniel-beck** [comment]
> IMHO it should be rather integrated into the plugin site

Between proprietary plugins/plugins not hosted on our update sites, and releases older than the latest, that would be completely useless for people wanting to figure out what's going on on their instance.

**Comment by MRamonLeon** [comment]
Nice initiative!!. Although not sure whether it may fit better on a plugin or the support-core plugin as an extra information. Not sure about the use case to consume this data, apart from Jenkins Develop Community.

**Comment by oleg-nenashev** [comment]
> Between proprietary plugins/plugins not hosted on our update sites, and releases older than the latest, that would be completely useless for people wanting to figure out what's going on on their instance.

Agreed. Maybe we should introduce a "Jenkins Developer Tools" plugin or so for such purpose. I do not mind including it into the core directly if there is such preference, but I doubt there would be many users using it. So I am fine either way

**Comment by daniel-beck** [comment]
IIRC one of the Stapler security fixes has killed off the ability to contribute views to objects from other plugins, so this needs to be in core, or would necessarily be clunky.

This URL is currently not linked from anywhere (it 404s) so it's not like we're exposing scary internals to users who aren't editing URLs manually. It can also be moved to a separate (non-index) view once we need this for something more generally useful.

**Pull request closed without merging**
