### PR TITLE
Include `shortName` in relevant `PluginWrapper.dependencyErrors`

### PR DESCRIPTION
**Pull request by jglick**
Longstanding irritation that messages about missing/obsolete/disabled dependencies on other plugins only printed the display name, even in logs, and it is sometimes not obvious what the plugin short name would be, which you often need to know in this circumstance. (If you only ever use the GUI to manage plugins, you are unlikely to get these errors to begin with!)

Amends some wording last modified in #3904. Removed a redundant `disabledAndObsolete` key. Renamed all modified keys since the number of message format parameters has changed and translations would otherwise have serious problems.

### Proposed changelog entries

* Noting plugin short names in some error messages.

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
I'm fine with that though it might leave a lot of localizations behind.

**Comment by daniel-beck** [comment]
Could you delete the now unused localizations from core? (Renaming still seems fine given we have https://plugins.jenkins.io/localization-zh-cn/ )

**Comment by jglick** [comment]
> delete the now unused localizations from core

Tried that initially, and wound up getting a lot of modifications to otherwise untouched lines due to the complications of various native file encodings as well as different case conventions for Unicode escapes, and gave up. At least pending UTF-8 property files, I think we should leave it to translators to use appropriate tooling to search for outdated locations, and preferably just move it all to separate plugins as was done for Simplified Chinese.

Note that a bunch of the translations were already out of date as of #3904.

BTW for NetBeans I wrote a little annotation processor that lets you define the English version of a message in Java sources right next to the usage site, which is easier for developers to maintain. Apache-licensed so should be easy enough to port to Jenkins if anyone if interested.

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Review by res0nance — APPROVED** [review]

**Pull request merged**
