### PR TITLE
[JENKINS-57412] Should always keep install wizard localization files in the core

### PR DESCRIPTION
**Pull request by LinuxSuRen**
### Proposed changelog entries

* Entry 1: Issue, restore installation wizard Chinese localization files
* ...

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@daniel-beck

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@linuxsuren 2.176 was selected as the new LTS baseline. You will need  a JIRA ticket to get it backported

**Review by oleg-nenashev — APPROVED** [review]
LGTM anyway

**Comment by LinuxSuRen** [comment]
@oleg-nenashev Added the ticket.

**Comment by oleg-nenashev** [comment]
@LinuxSuRen https://issues.jenkins-ci.org/browse/JENKINS-20620 , really? Something is wrong in the ID

**Comment by LinuxSuRen** [comment]
@oleg-nenashev Changed the title. Thanks for reminding.

**Pull request merged**
