### PR TITLE
Add @since for User.getById

### PR DESCRIPTION
**Pull request by Wadeck**
- to ease the maintenance of plugins (avoid searching for first version providing it)

### Desired reviewers

@reviewbybees @jtnord

### CODE REVIEW

**Review by jtnord — APPROVED** [review]
I'm not sure on the convention when we add things from security.  It may be we only add the mainline rather than the security (I don't know) // cc @daniel-beck 

However looks good to me

**Comment by Wadeck** [comment]
@jtnord Not sure at all :) I found some examples of two versions used in `@since` so I follow those.

**Comment by daniel-beck** [comment]
> I'm not sure on the convention when we add things from security. It may be we only add the mainline rather than the security (I don't know)

If it was usable in LTS (which it typically should not be, i.e.  `@Restricted`), adding it to `@since` makes sense to document as such.

**Review by oleg-nenashev — APPROVED** [review]
:bee: and @reviewbybees done
We have no standards about it, so 🚢 🇮🇹

**Pull request merged**
