### PR TITLE
[JENKINS-65113] Add issue tracker metadata support

### PR DESCRIPTION
**Pull request by daniel-beck**
See [JENKINS-65113](https://issues.jenkins-ci.org/browse/JENKINS-65113).

The UI is very basic (it may be time to look at separate plugin pages again, I'm sure I had an experiment somewhere), but it should get the job done. As always, suggestions welcome.

> Screenshot 2021-12-15 at 15 50 35

Almost all plugins provide this metadata, backfilled using https://github.com/jenkins-infra/repository-permissions-updater/pull/1884, and this is also what drives links in the sidebar of plugins.jenkins.io. This downgrades gracefully, the displayed link is simply missing from plugins that don't have an issue tracker reference.

### Proposed changelog entries

* Add "Report an issue" link to plugins in the plugin manager.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [n/a] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by oleg-nenashev — COMMENTED** [review]
Having API is definitely useful, but I am not sure it is good to put the link to the updates manager.   First of all, not everyone has access there. Secondly, the place is not very intuitive. Thirdly, it may be an issue for vendors who do not override up[date centers and expect users to contact their support.

What if we introduce a new pluggable "Report an Issue" view which is accessible from a menu. This view could offer a dropdown where a user can select a component, with linking to the '_unsorted' label by default. Vendors can replace that if they want via extension point. Might be too complex. 

image

**Comment by daniel-beck** [comment]
>  First of all, not everyone has access there.

Only admins can provide logs etc.; bug reports by users are usually a mess of lacking information and delays while they try to get answers (and the answers aren't seldom "oh an admin configured it to work this way"). I do not feel that we should support those.

Also we don't allow access to `/about` to regular users, which is basically just a list of installed plugins and their versions.

> Thirdly, it may be an issue for vendors who do not override up[date centers and expect users to contact their support.

For those who provide custom update sites, there's probably a URL to a helpdesk or "Contact Us" page that can be used. And as I wrote, this degrades nicely.

Besides that, we expect that everything distributed by the Jenkins project is hosted here, and track issues here. While some do this differently, I see no reason for us to provide infra support for those who attempt to circumvent this, similar to how we do not advertise SCM locations outside `github.com/jenkinsci`, or render documentation outside wiki or `github.com/jenkinsci` on the plugin site.

> Secondly, the place is not very intuitive. … What if we introduce a new pluggable "Report an Issue" view which is accessible from a menu.

Perhaps, if there's a reasonable location (the user menu doesn't seem to be it). The header is already pretty busy as well. I didn't want to further clutter the default sidepanel with a link that's (hopefully) rarely needed. The footer might work, but I would expect some pushback given how we've simplified that recently. `/about` isn't any more discoverable.

IMO the current location makes sense, even if it's quite a few clicks down, and could always be iterated on.

**Review by oleg-nenashev — APPROVED** [review]
I am approving it, because the UX can be improved later.
The code itself is good

**Review by timja — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Comment by daniel-beck** [comment]
On-holding this for a week or so to have an opportunity to get further with the issue tracker metadata backfilling, so limit conflicts when maintainers start filling in their data themselves.

**Comment by daniel-beck** [comment]
Un-on-holding, the large upstream change is now merged and this can proceed.

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Review by jvz — APPROVED** [review]

**Comment by daniel-beck** [comment]
On-holding again given the metadata size increase, I'll check with infra whether this is OK.

**Comment by daniel-beck** [comment]
@janfaracik Could you look at how I adapted this to the new UI, does that look reasonable?

**Comment by daniel-beck** [comment]
Un-on-holding based on @dduportal's feedback.

**Comment by janfaracik** [comment]
> @janfaracik Could you look at how I adapted this to the new UI, does that look reasonable?

Looks good to me :) 

I'm working on another update to the Plugin Manager to update the UI further - I might convert this link into a button on the right in the future if that's okay?

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by daniel-beck** [comment]
@janfaracik Sure, go for it, I disclaimed the UI part in the PR comment :-)

**Pull request merged**
