### PR TITLE
Add `Appearance` system configuration page

### PR DESCRIPTION
**Pull request by timja**
This adds a new system configuration page 'Appearance' for configuring the look and feel of Jenkins.
It moves a bit of config out of the main System page into a more appropriate place.

<details>
<summary>Screenshots</summary>

image

image

image

image

</details>

It implements the design from https://jenkins-redesign.vercel.app/settings/appearance

It complements https://github.com/jenkinsci/jenkins/pull/8379 but doesn't require it

I've gone through a number of plugins that contribute UI and have sent pull requests for:

```[tasklist]
### TODO
- [ ] https://github.com/jenkinsci/simple-theme-plugin/pull/156
- [ ] https://github.com/jenkinsci/theme-manager-plugin/pull/210
- [ ] https://github.com/jenkinsci/customizable-header-plugin/pull/15
- [ ] https://github.com/jenkinsci/prism-api-plugin/pull/109
```

I have gone for ones that directly affect the look and feel of Jenkins rather than ones that affect builds like ansicolor.
Any other suggestions?

After https://github.com/jenkinsci/jenkins/pull/7268 is in the user profile page can be updated to match.

Could possibly move the Display notification URL provider to appearance too? (the thing that selects Classic, Blue Ocean or Pipeline Graph View)

### Testing done

Started Jenkins with no plugins contributing to the appearance category, the page doesn't show.

Installed https://github.com/jenkinsci/theme-manager-plugin/pull/210, the page shows up and theme manager is on the appearance page and not on the system configuration page.

Unit test wise I don't think there's much value for it will something in core uses it, although happy to add something if its thought to be needed

### Proposed changelog entries

- Add appearance system configuration page

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/8403"></a>

### CODE REVIEW

**Comment by TobiX** [comment]
Nice. https://plugins.jenkins.io/test-results-analyzer/ looks like an additional candidate, but mixes appearance settings with other settings...

**Comment by Kevin-CB** [comment]
From a security perspective, I see no blockers!

**Comment by timja** [comment]
> Nice. [plugins.jenkins.io/test-results-analyzer](https://plugins.jenkins.io/test-results-analyzer/) looks like an additional candidate, but mixes appearance settings with other settings...

I've had a look but I don't think it fits with the page as well.
I'm trying to have it be more for things that affect look and feel as a whole rather than some niche plugin config

**Comment by janfaracik** [comment]
I think this is great! LGTM.

Would be good to see something similar in https://github.com/jenkinsci/jenkins/pull/7268 if it's going forward.

**Review by janfaracik — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]
That's awesome!

**Comment by timja** [comment]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by daniel-beck** [comment]
>  It moves a bit of config out of the main System page into a more appropriate place.

Previously, creation of new config categories were motivated by overcrowding on the global configuration (Tools, Clouds, possibly Security as well – matrix-auth gets huge quickly). This doesn't seem to be the case here. What motivates this change, what's special about this config page that does not apply to tons of other potential categories?

**Comment by timja** [comment]
> Previously, creation of new config categories were motivated by overcrowding on the global configuration (Tools, Clouds, possibly Security as well – matrix-auth gets huge quickly). This doesn't seem to be the case here. What motivates this change, what's special about this config page that does not apply to tons of other potential categories?


This groups related elements together, originally I had started https://github.com/jenkinsci/theme-manager-plugin/pull/105 but that would've been a breaking change at configuration level. This pull request https://github.com/jenkinsci/jenkins/pull/8379 then reminded of the design https://jenkins-redesign.vercel.app/settings/appearance. Which seemed like a much cleaner approach to solve the problem.

It means that you can configure the look and feel of Jenkins from one place without having to scroll all over the place to find it.

> what's special about this config page that does not apply to tons of other potential categories

Other sensible categories could likely be added if there are enough sensible elements that would go there? e.g. possibly notifications?

> Also, we should better define what goes here so plugin maintainers know what's appropriate to put there. The discussion about some plugins above indicates this isn't the case.

[`22b858b` (#8403)](https://github.com/jenkinsci/jenkins/pull/8403/commits/22b858b560d26dce4d3fd911abbf0bfb75311a88)

**Comment by daniel-beck** [comment]
> Other sensible categories could likely be added if there are enough sensible elements that would go there? e.g. possibly notifications?

That makes sense if we move from "this is unwieldy, split it up" to "categories are based on loosely coupled semantic relationships between elements". That seems like a JEP-level change though given the downstream impact.

**Comment by jonesbusy** [comment]
Looks login-theme-plugin was forgotten. 

I've open a PR here : https://github.com/jenkinsci/login-theme-plugin/pull/37

Regards,

**Comment by uhafner** [comment]
> * "Prism Syntax Highlighting Configuration" ([Prism API plugin](https://plugins.jenkins.io/prism-api/)): Didn't find an existing issue for this.

https://github.com/jenkinsci/prism-api-plugin/releases/tag/v1.29.0-9

**Comment by timja** [comment]
> > "Additional Sidebar Links" ([Sidebar Link plugin](https://plugins.jenkins.io/sidebar-link/)): Didn't find an existing issue for this.
> 
> As a user of `sidebar-link` I think it should be moved to appearance as well. But you should check with maintainer. Not sure if there is "guidelines" of what is appearance and what is not

Yeah it makes sense for that to go there, https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/jenkins/appearance/AppearanceCategory.java#L30-L41

**Comment by alexsch01** [comment]
@timja 
I'm running **Jenkins 2.426.3** but I don't see `Appearance` in `Manage Jenkins`
image

**Pull request merged**
