### PR TITLE
JENKINS-25205: "Slaves in label" produces wrong results

### PR DESCRIPTION
**Pull request by arcivanov**
Changes "Slaves in label: N" to "Label is serviced by N node(s) and M cloud(s)".
Portugese translation reset.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
LGTM. @daniel-beck , WDYT?

**Comment by daniel-beck** [comment]
@oleg-nenashev Agreed.

**Comment by KostyaSha** [comment]
@arcivanov please squash commits in one and place `[FIXED JENKINS-25205]` in comment tail or header.

**Comment by arcivanov** [comment]
@KostyaSha done

**Comment by KostyaSha** [comment]
:+1:

**Pull request merged**
