### PR TITLE
Make Jenkins compile in Eclipse out of the box

### PR DESCRIPTION
**Pull request by Bananeweizen**
When importing the Jenkins sources in Eclipse there are some compiler errors that cannot easily be fixed by changing preferences:
* There are 2 ambigious method call overloads, which need an additional type cast to compile in ECJ.
* All generated lexer and parser classes are missing. This is because the antlr generated code is found automatically in the maven compilation, but not in m2e (the eclipse maven integration), unless the generated source path is mentioned explicitly.

### Testing done

There are no functional changes (the Java code change is only an explicit type cast).
Compiles in Eclipse and Maven now.

It might be useful to have someone using Netbeans or IntelliJ check whether that causes bad side effects on their side (and whether some SuppressWarning or similar is needed in the modified Java class).

### Submitter checklist

- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7993"></a>

### CODE REVIEW

**Comment by NotMyFault** [comment]
Can you link the issue tracking this bug on Eclipse's end, please?
Once fixed, we can restore the original behavior.

**Comment by Bananeweizen** [comment]
@timja There is no bug in Eclipse to be tracked. There are differences between ECJ and javac that are caused by missing behaviour in the Java specs. This is such a case AFAIK. Other compilers probably default to a certain type for method references that can be either Callable or Runnable. ECJ generally produces better warnings/errors for potential programming bugs and this is one of the cases. Admittedly, both Executor methods will do the same in the end when being called, but that _semantic_ knowledge is not available to the compiler seeing 2 matching methods, and it has to decide for one of them.

For the maven related part: That's something were the maven compiler plugin seems to add the generated antlr source path to the list of available source paths lazily at maven runtime. That's bad because any explicit .classpath file generated from the _declared_ maven model then misses this. This will therefore fail for any kind of tooling that does not participate in the maven lifecycle itself (and can therefore access the modified maven model).

**Review by timja — APPROVED** [review]
LGTM, running tests in intellij is just as broken as before as far as I can tell thought I would give it a go though ^.^

**Review by NotMyFault — APPROVED** [review]
/label ready-for-merge

---

This PR is now ready for merge. We will merge it after ~24 hours if there is no negative feedback.
Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process.
Thanks!

**Pull request merged**
