### PR TITLE
[JENKINS-66446] Adjust class loading behavior of `JnlpSlaveRestarterInstaller`

### PR DESCRIPTION
**Pull request by jglick**
See [JENKINS-66446](https://issues.jenkins-ci.org/browse/JENKINS-66446).

Amendment to #3333 complementing https://github.com/jenkinsci/remoting/pull/514.

### Proposed changelog entries

* Ensure inbound agent restart logic is applied.

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by jglick** [comment]
@timja if you have the reproduction environment set up, would you mind checking whether this helps?

I am not sure how to verify that `SlaveRestarter` actually works properly. On Unix there would be an `execv` from the agent process, which somehow result in a fresh JVM being created. Maybe you could check `System.nanoTime()` in the agent’s script console? Hypothesis: without this fix, but on TCP agents or agents running Java 8 or WS agents running Java 11 after https://github.com/jenkinsci/remoting/pull/514, `nanoTime` would continue to grow after restarting the controller and reconnecting the agent (same JVM, different `Channel`); whereas with this fix, `nanoTime` would reset (same Unix process, different `JVM`). I suppose you could also use something like `System.setProperty` to mark a JVM.

**Comment by jglick** [comment]
(Arguably should be kept in draft until I think of a way to verify the fix in a functional test. I do not suppose this change could _harm_ anything but it might not help.)

**Comment by timja** [comment]
> @timja if you have the reproduction environment set up, would you mind checking whether this helps?

Yep can do in a few hours

**Comment by timja** [comment]
This is actually worse than before.

If I stop the controller the agent doesn't log anything at all.

```
Mar 01, 2022 7:58:46 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: WebSocket connection open
Mar 01, 2022 7:58:46 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connected
```

If I start the controller back up, it doesn't log anything

If I check the agent status, it's disconnected:
image

I'll adjust log levels and take a look at the threads to see if I can get any better info

**Review by timja — APPROVED** [review]
I've ran quite a few tests with:

```
➜  jenkins git:(JnlpSlaveRestarterInstaller-JENKINS-66446) java -version
openjdk version "11.0.13" 2021-10-19 LTS
OpenJDK Runtime Environment Zulu11.52+13-CA (build 11.0.13+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.52+13-CA (build 11.0.13+8-LTS, mixed mode)
```
The first couple of times it didn't work, not sure what happened there.

last 10 or so worked fine.

Was able to restart during a pipeline and have it resume just fine.

**Review by res0nance — APPROVED** [review]
Not tested manually but code is functionally no different

**Comment by jglick** [comment]
For background, `JnlpSlaveRestarterInstaller` is pretty much a hack, as you can see by the JNA-based Unix impl. Basically what it does is let `java -jar agent.jar` restart itself when reconnecting an agent, so that a new connection has a fresh JVM and thus can newly load native libraries, etc. A properly set up agent would be using an operating system service that waits for the Java process to exit and then relaunches it, which would not need this. Could be considered for deprecation alongside agent installers (https://github.com/jenkinsci/remoting/pull/507#issuecomment-1030341067) though this is not limited to agents launched via Java Web Start—would apply to any agent launching technique that assumes it can run Java once and not in a loop. If we get rid of native library usage from agents then the value is less I suppose.

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by jglick** [comment]
Thanks @basil! I am going to spend a bit of time seeing if I can use the system property trick to verify this in a test.

**Comment by jglick** [comment]
OK I think I got it.

* With `core/src/main/` reverted:
  * Java 8: both pass
  * Java 11:
    * WS: timeout after NCDFE
    * TCP: error logged; expected 1 but was 2
* As patched:
  * Java 8: both pass
  * Java 11: both pass

**Review by basil — APPROVED** [review]
Very nice! I know you don't like when others push to your PR branches, but in the interest of saving time and getting this merged I've pushed commit 7c661ff9d8 to fix some Checkstyle errors.

**Comment by jglick** [comment]
Right, thank you, I never remember to do that.

**Comment by basil** [comment]
The new test is [consistently failing on Windows](https://ci.jenkins.io/job/Core/job/jenkins/job/PR-6315/6/testReport/).

**Comment by jglick** [comment]
Got an hour or two into trying to reproduce the Windows failure locally before

> Your PC will restart several times.

never mind.

**Review by timja — APPROVED** [review]
nice

**Comment by jglick** [comment]
Note that CI currently runs Windows tests only on Java 11, not 8, so https://ci.jenkins.io/job/Core/job/jenkins/job/PR-6315/8/testReport/jenkins.slaves.restarter/JnlpSlaveRestarterInstallerTest/ was not full coverage.

**Comment by felipecrs** [comment]
Any chance this can get cherry-picked to `stable-2.332`?

**Comment by basil** [comment]
> Any chance this can get cherry-picked to `stable-2.332`?

@felipecrs Please see the [Backporting Process](https://www.jenkins.io/download/lts/#backporting-process) page:

> Any user can propose that a issue is backported to LTS by labeling with [lts-candidate](https://issues.jenkins.io/secure/IssueNavigator.jspa?reset=true&jqlQuery=labels+%3D+lts-candidate).

In general, the more confident we are in a fix, the more likely it is to be backported to the LTS line. So if you can verify that the issue is resolved in the latest weekly release, that would give us additional confidence to accept the backport request.

**Comment by felipecrs** [comment]
Verified with:

```console
$ kind create cluster

$ helm repo add jenkins https://charts.jenkins.io

$ helm repo update

$ helm upgrade jenkins jenkins/jenkins --install --wait --debug -f- <<'EOF'
controller:
  tag: 2.339-jdk11
  adminPassword: admin
  agentListenerEnabled: false
  # specifying plugins without version makes sure to use the latest
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - job-dsl
    - saferestart
  JCasC:
    configScripts:
      my-jobs: |
        jobs:
          - script: |
              pipelineJob('testjob') {
                definition {
                  cps {
                    script("""\
                      pipeline {
                        agent any
                        stages {
                          stage ('test') {
                            steps {
                              sleep 1000
                            }
                          }
                        }
                      }""".stripIndent())
                    sandbox()
                  }
                }
              }
agent:
  websocket: true
  tag: 4.13-1
EOF

$ echo http://127.0.0.1:8080 && kubectl --namespace default port-forward svc/jenkins 8080:8080
```

Then:

1. Go to the Jenkins UI at http://127.0.0.1:8080/
2. Login with "admin" as user and password
3. Trigger a build of "testjob"
4. Wait for a pod to be assigned to the build and the sleep command to start running
5. Start following the pod logs with kubectl logs -f <name-of-pod>
6. Go to Jenkins home page and click in Restart Safely and confirm
7. Watch the pod logs, it detect that Jenkins is down and also will not exit as it was doing before.

```console
$ kubectl logs default-jdwxv --follow
[...]
Mar 16, 2022 12:45:38 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: http://jenkins.default.svc.cluster.local:8080/login is not ready: 503
Mar 16, 2022 12:45:48 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Performing onReconnect operation.
Mar 16, 2022 12:45:48 AM jenkins.slaves.restarter.JnlpSlaveRestarterInstaller$EngineListenerAdapterImpl onReconnect
INFO: Restarting agent via jenkins.slaves.restarter.UnixSlaveRestarter@22aac3e7
Mar 16, 2022 12:45:50 AM hudson.remoting.jnlp.Main createEngine
INFO: Setting up agent: default-jdwxv
Mar 16, 2022 12:45:50 AM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
Mar 16, 2022 12:45:50 AM hudson.remoting.Engine startEngine
INFO: Using Remoting version: 4.13
[...]
```

As mentioned in https://issues.jenkins.io/browse/JENKINS-67062, the exact same procedure were able to reproduce the error.

**Comment by basil** [comment]
Thanks for confirming! I have added the `lts-candidate` label to [JENKINS-66446](https://issues.jenkins.io/browse/JENKINS-66446?focusedCommentId=423079&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-423079).

**Comment by felipecrs** [comment]
Thanks a lot!

**Pull request merged**
