### PR TITLE
[JENKINS-68196] "Preview button" and "Hide Preview button" will show at the same time

### PR DESCRIPTION
**Pull request by frankie139506**
See [JENKINS-68196](https://issues.jenkins-ci.org/browse/JENKINS-68196).
gif1

### Proposed changelog entries

* fix `Preview button` and `Hide Preview button` will show at the same time

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] (If applicable) Jira issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [X] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by NotMyFault — COMMENTED** [review]
It doesn't seem to be covered well in your preview gif, but there's an nbsp as delimiter between `Preview` and `Hide preview` in the associated jelly file:
https://github.com/jenkinsci/jenkins/blob/0d4d7bdc025147f9ab70b24789ad8ce971d6f944/core/src/main/resources/lib/form/textarea.jelly#L113-L115
It would make sense to remove it here then, to not show two spaces, if we want to only show one, though does that make sense in the first place?

**Review by daniel-beck — CHANGES_REQUESTED** [review]
"Preview" shows (or updates) the preview. "Hide" hides it. Both are useful "next" actions while an older preview is visible.

**Comment by NotMyFault** [comment]
> though does that make sense in the first place?

> "Preview" shows (or updates) the preview. "Hide" hides it. Both are useful "next" actions while an older preview is visible.

Yeah, the current proposal strips functionality for no good. The "Preview" surface could be turned into an "Update Preview" depending whether you're editing existing text or not, fwiw.
But I'm -1 for the current proposal.

**Comment by timja** [comment]
Another option would be to automatically update it while the preview box is open.

**Review by basil — COMMENTED** [review]
+1 for Tim's idea for automatic updating while the preview box is open. I concur with Daniel and Alex that in the absence of such automatic updating this PR removes existing functionality and is therefore not ready for merge.

**Comment by basil** [comment]
This PR has been stalled for the past month for no response. I have added the `proposed-for-closed` label and plan to close it in approximately one week if there is no response.

**Pull request closed without merging**
