### PR TITLE
[JENKINS-73047] Fix weather icons 

### PR DESCRIPTION
**Pull request by SNanda8895**
See [JENKINS-73047](https://issues.jenkins.io/browse/JENKINS-73047).

### Testing done

I tested it locally ,everything worked fine. 

Screenshot 2024-05-24 at 5 01 40 PM
Screenshot 2024-05-24 at 5 01 58 PM
Screenshot 2024-05-24 at 4 57 05 PM
Screenshot 2024-05-24 at 4 57 40 PM
Screenshot 2024-05-24 at 5 16 29 PM
Screenshot 2024-05-24 at 5 17 45 PM

### Proposed changelog entries

- Fix stoke width of weather icons in Safari.

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [x] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@Kevin-CB 
@daniel-beck 

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Comment by Luckybangar** [comment]
ok

**Review by daniel-beck — COMMENTED** [review]
The code change looks good as far as I understand it.

@SNanda8895 Could you confirm testing in all supported browsers looked OK with and without zoom applied (ideally by providing screenshots for each combination)? Given this issue occurred only in one browser and with zoom applied, we'd like to prevent causing regressions in other browsers. [These are the supported browsers](https://www.jenkins.io/doc/book/platform-information/support-policy-web-browsers/).

Additionally, please provide a suggested changelog entry. See [the changelog styleguide](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/_STYLEGUIDE.adoc) for guidance and [previous entries](https://www.jenkins.io/changelog/) for examples.

**Review by daniel-beck — APPROVED** [review]
Thanks for the screenshots.

**Review by timja — APPROVED** [review]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Pull request merged**
