### PR TITLE
[JENKINS-59167] Correction of rootUrl in RSS/Atom feeds

### PR DESCRIPTION
**Pull request by Wadeck**
See [JENKINS-59167](https://issues.jenkins-ci.org/browse/JENKINS-59167).

Regression introduced in [JENKINS-58595](https://issues.jenkins-ci.org/browse/JENKINS-58595) (released as 2.190).

The variable `rootURL` is first defined in [RSS:80](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/RSS.java#L80) but then overriden in [Functions.initPageVariables](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/Functions.java#L244-L247) that's call by the new `l:view` tag introduced.

To solve the problem, I am just using the existing `app.rootUrl` which corresponds to `Jenkins.getRoolUrl()`.

For sample files, please refer to the Jira ticket.

**Edit:** The test covers especially the regression part and only this one in order to be "quickly backported". A [followup ticket](https://issues.jenkins-ci.org/browse/JENKINS-59231) was created to improve the test coverage in general in the RSS area. This is not the focus of this ticket.

### Proposed changelog entries

* Correction of the missing absolute URL in the RSS / Atom feeds

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [n/a] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@jvz

### CODE REVIEW

**Comment by daniel-beck** [comment]
This only impacts views that were not `l:layout` before, right? It's not like this will have a bunch of unexpected further occurrences? Have we looked for any?

**Comment by Wadeck** [comment]
@daniel-beck This only impact the two views related to feeds because they received their own `rootURL` from RSS.java, compared to all the rest of the view that are either using `app.rootUrl` or the standard `rootURL`.

**Review by rsandell — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
We hit this issue too often in plugins and the core :(

**Review by daniel-beck — APPROVED** [review]

**Review by jvz — APPROVED** [review]
Changes look good to me. The unit test demonstrates beyond a doubt that this feature works as expected, so I'm not trying it out manually.

**Review by oleg-nenashev — APPROVED** [review]
Will merge tomorrow if no negative feedback

**Comment by hossman** [comment]
As someone with no knowledge of jenkins internals, and no prior experience reviewing jenkins tests, please take this feedback with a grain of salt...

The one thing that jumps out at me about the new RSSTest.java  is that (IIUC) it only tests the "top level" feed (eg: `/rssAll`) but not any other feed variants, ie: "view" specific feeds (eg: `/view/Lucene-Solr/rssAll`)

It also only seems to only check that the entry links "contain" the `j.getURL()` value -- which I gather is the root url of the test server? --  w/o actually verifying that the links are valid or unique.

so (again, IIUC) there are a few classes of bugs that that might exist (now or in the future) even w/this patch, but would allow this test to pass:

* if `j.getURL()` is (somehow) the empty string in the test setup (and the test method names -- `...evenWithoutRootUrlSetup` -- imply that it is by default?), then the `containsString()` asserts won't care if the `href` values in feed are just relative paths, even though the test method names imply that they are checking for absolute URLs
* if `${h.encode(adapter.getEntryUrl(e))}` is broken in some way and evaluates to the empty string for every `e` entry, then the tests will still happily pass as long as the `href` values all contain `j.getURL()` -- even if every `href` is *exactly* the value of `j.getURL()` w/o actually being a URL that corresponds with the build numbers.
* if `${rootURL}` is something like `http://example.com` (ie: doesn't end in a slash) and `${h.encode(adapter.getEntryUrl(e))}` is something like `job/FOO/42` (ie: doesn't start with a slash) then the resulting `href` would be `http://example.comjob/FOO/42` and this test would pass (because the `href` contains the root url) even though it would still be a broken url

**Comment by Wadeck** [comment]
@hossman Thank you for the comment. I will try to explain point by point :)

---

> only tests the "top level" 

Actually, the RSS class is responsible for "all" the top level *and* the other level of feeds. When you are on a Job for example, it will call [Job.doRssAll](https://github.com/jenkinsci/jenkins/blob/0e62b68012282648377cfac4fe6d01956d7c1f11/core/src/main/java/hudson/model/Job.java#L1583) (or related) which then call [Job.rss](https://github.com/jenkinsci/jenkins/blob/0e62b68012282648377cfac4fe6d01956d7c1f11/core/src/main/java/hudson/model/Job.java#L1593) which finally call [RSS.forwardToRs](https://github.com/jenkinsci/jenkins/blob/0e62b68012282648377cfac4fe6d01956d7c1f11/core/src/main/java/hudson/model/RSS.java#L75). IOW covering the top level also cover the rest of the feeds.

> the root url of the test server?

The absolute URL of the server, including the contextPath, e.g. `http://localhost:8080/jenkins` or `https://ci.jenkins.io`.

> links are valid or unique

Not the scope of this test. I keep the focus on the regression here to have it delivered ASAP to be backported to LTS. We have created an internal ticket to add more tests on that specific area due to the number of regressions we got recently. It was not tested at all before the security correction (SECURITY-534) and that resulted in 2 regressions in the following weeks/month.

> ...evenWithoutRootUrlSetup 

The j.getURL() is either using the RootUrl configured or the request URI, so it's never empty. Due to that, the `containsString` will always check for absolute URLs.

> `${h.encode(adapter.getEntryUrl(e))}` is broken

That was exactly the problem of the previous regression. The non-regression for that will be included in a followup PR.

> if `${rootURL}` [...] doesn't end in a slash

Actually it cannot due to [ensureEndsWith](https://github.com/jenkinsci/jenkins/blob/0c2d194f0d933fdba8f5a9a1fda8adc8826981c0/core/src/main/java/jenkins/model/Jenkins.java#L2311) call inside the `Jenkins.getRootUrl()`.

---

All your points are perfectly valid, please continue to provide such elaborated feedback, that really helps because when we reply to such questions/comments, we need to ensure everything is correct. Yes you're missing the Jenkins specifics, but that's also a very good way to receive feedback from people without the "Jenkins biais" ;)

**Comment by Wadeck** [comment]
@oleg-nenashev I would like to have at least one approver having manually tested the change. It will have a good chance to be backported and thus I do want to reduce as much as possible the risk of regression inside regression.
But of course, if there are no manual testing but the deadline is reached for the next weekly, just merge it anyway.

**Comment by oleg-nenashev** [comment]
Put it on hold till Friday EoD. 
If someone does more testing, it will be much appreciated

**Comment by oleg-nenashev** [comment]
There is https://github.com/jenkinsci/core-pr-tester which helps to quickly spin up the test instance

**Comment by jvz** [comment]
Thanks for the pointer, Oleg! My team is meeting today to learn how to use that from the veterans.

**Comment by Wadeck** [comment]
@oleg-nenashev we tested as a team during a KT about the core-pr-tester, so it's fine :)

**Comment by hossman** [comment]
@Wadeck appreciate your response...

> Not the scope of this test. I keep the focus on the regression here to have it delivered ASAP to be backported to LTS. We have created an internal ticket to add more tests on that specific area due to the number of regressions we got recently.

...that's the main piece of info i was missing, I didn't realize this test was deliberately kept focused on the regression for fast backporting, and that an additional issue was opened to track additional testing. (nor that that's the general "flow" of how issues are tackled in jenins)

FWIW: If a link to that additional issue had existed either here or JENKINS-59167, thatwould have pre-empted my comment and i would have instead focused on commenting in *that* issue with suggesions for how to make hte test more robust against future regressions :)

**Comment by Wadeck** [comment]
@hossman 

> FWIW: If a link to that additional issue had existed [...]

That's a nice feedback. As it was "just" an internal ticket (internal to CloudBees, not Jenkins), more as a reminder that we should work on that, there was no sign for the community to know about that. Next time I will try to highlight that we plan to work on other part if something "obvious" was missing.
In the meantime, I created a Jenkins ticket for the followup: https://issues.jenkins-ci.org/browse/JENKINS-59231 and will modify the initial PR comment.

**Review by jeffret-b — CHANGES_REQUESTED** [review]
The code looks good. We did some manual testing in an online team meeting today and the behavior all made sense. (We used core-pr-tester and it was very easy to get a Jenkins instance with the changes to test.)
However, one of the new tests is failing on the CI machine. I haven't had a chance to run it locally and try to figure out what's going on.
Once the tests pass my concerns are removed and I would approve.

**Comment by Wadeck** [comment]
I tested locally the RSSTest with Windows and Linux, both are passing, so re-triggering the CI, seems weird.
The XML provided by the feeds does have a `<link xxx=... yyy=... />` but the SAX parser expects to have `<link>...</link>` (but only in the CI machine)

**Comment by Wadeck** [comment]
Ignoring the new tests for the moment, they will be fixed when we'll work on JENKINS-59231.

**Review by jeffret-b — APPROVED** [review]

**Pull request merged**
