### PR TITLE
[JENKINS-33828] - setup wizard was modifying the recommended plugin list

### PR DESCRIPTION
**Pull request by kzantow**
The setup wizard was returning a reference to the recommended plugin array as the selected plugins, allowing it to be modified and resulting in unexpected behavior in certain cases.

This addresses: https://issues.jenkins-ci.org/browse/JENKINS-33828

@reviewbybees esp. @daniel-beck

### CODE REVIEW

**Comment by jglick** [comment]
:bee:

**Comment by gusreiber** [comment]
@kzantow After running this guy [ https://github.com/kzantow/jenkins/tree/JENKINS-33828-recommended-plugin-list-modifiable ] I am still seeing the same blank grid of plugins being installed. This is on Chrome OSX Version 49.0.2623.87 (64-bit)
:bug:

**Comment by kzantow** [comment]
@gusreiber what set of steps did you use to reproduce this?

**Comment by gusreiber** [comment]
seeing the following in the console after entering initial pass-code:
pluginSetupWizard.js:1020 
Jenkins global module 'pluginSetupWizard' already registered.
(anonymous function) @ pluginSetupWizard.js:1020
exports.onReady @ pluginSetupWizard.js:1175
exports.export @ pluginSetupWizard.js:993
(anonymous function) @ pluginSetupWizard.js:2254
doFulfill @ pluginSetupWizard.js:807
onFulfilled @ pluginSetupWizard.js:81918
../pluginSetupWizardGui @ pluginSetupWizard.js:2236
s @ pluginSetupWizard.js:1
e @ pluginSetupWizard.js:1
(anonymous function) @ pluginSetupWizard.js:1

**Comment by daniel-beck** [comment]
> I am still seeing the same blank grid of plugins being installed

The joys of two bugs in one issue :frowning:

**Comment by daniel-beck** [comment]
:+1: as this fixes the issues observed with plugin selection. The "second half" of JENKINS-33828 should be done in a separate PR, possibly even tracked independently.

**Comment by daniel-beck** [comment]
When I select "None", then return ("Back" button) and select "Install recommended plugins", it installs a bunch of stuff, but all of them are considered dependencies (`**`). It's not a presentation issue (besides the fact that maybe dependencies should get a box as well, but whatever), but a data issue.

The other part -- "Recommended" not working properly -- is now resolved.

**Comment by gusreiber** [comment]
@kzantow @daniel-beck let me know if you want me to record a second issue. As far as I could understand it, I am still seeing exactly the same behavior described in 33828, with the same repro steps. Is that not what you are seeing, Daniel?

**Comment by kzantow** [comment]
@gusreiber please try this again, that was an embarrassing omission (could have sworn I tested that multiple times)

**Comment by gusreiber** [comment]
:bee: yup, that did it.

**Comment by jglick** [comment]
:bee:

**Comment by daniel-beck** [comment]
:bee:

**Pull request merged**
