### PR TITLE
[JENKINS-55582] Handle nonstandard $JENKINS_HOME/plugins/$shortName.hpi and warn about $shortName-$version.hpi

### PR DESCRIPTION
**Pull request by jglick**
Amends #4000 to more gracefully handle the case that a nonstandard packaging script has copied plugin archives under an improper naming scheme. (Jenkins itself always creates `$shortName.jpi` when downloading from the update center or `install-plugin` CLI, as does `jenkinsci/docker/install-plugins.sh`.)

### Proposed changelog entries

* Detached plugin handling in 2.178 could cause problems for some custom `$JENKINS_HOME` packaging schemes that used improper filenames. These cases are now at least warned about, and in some cases transparently handled.

### Desired reviewers

@jenkinsci/code-reviewers

### CODE REVIEW

**Review by nrayapati — APPROVED** [review]

**Comment by jglick** [comment]
@nrayapati assuming the build here passes, it should produce & deploy a `jenkins.war`. It would be great if you could download that and confirm that it improves behavior in your case.

**Review by oleg-nenashev — APPROVED** [review]
This double naming still produces a lot of pain and unexpected regressions :(

**Comment by oleg-nenashev** [comment]
Test failure is unrelated

**Comment by oleg-nenashev** [comment]
Test failure is unrelated

**Review by Wadeck — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Will merge it tomorrow if no negative feedback

**Comment by nrayapati** [comment]
Thank @jglick @oleg-nenashev I didn't get time to test this locally but as I mentioned in the JIRA it did work when I changed extension to .jpi.

**Pull request merged**
