### PR TITLE
Upgrade to 3.30 version of Remoting.

### PR DESCRIPTION
**Pull request by jeffret-b**
See [JENKINS-51004](https://issues.jenkins-ci.org/browse/JENKINS-51004), [JENKINS-57107](https://issues.jenkins-ci.org/browse/JENKINS-57107), and [JENKINS-46515](https://issues.jenkins-ci.org/browse/JENKINS-46515)

Upgrade to the 3.30 version of Remoting, which contains a few minor fixes. 

See the [Remoting Changelog](https://github.com/jenkinsci/remoting/blob/master/CHANGELOG.md#330).

### Proposed changelog entries
* Update Remoting from 3.29 to 3.30 to fix a few minor issues. ([Full changelog](https://github.com/jenkinsci/remoting/blob/master/CHANGELOG.md#330), [issue 51004](https://issues.jenkins-ci.org/browse/JENKINS-51004), [issue 57107](https://issues.jenkins-ci.org/browse/JENKINS-57107), [issue 46515](https://issues.jenkins-ci.org/browse/JENKINS-46515))

### Submitter checklist

- [x] JIRA issue is well described
        * Issue is sufficiently well described for the minor fix.
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
          * No tests necessary or useful for adding this logging call that was already intended.
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@jvz @oleg-nenashev

### CODE REVIEW

**Review by jglick — APPROVED** [review]
@dependabot it

**Review by basil — APPROVED** [review]
FYI, I have an open PR to update the Swarm client at jenkinsci/swarm-plugin#78.

**Review by oleg-nenashev — APPROVED** [review]

**Review by Wadeck — APPROVED** [review]

**Review by jvz — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
CI failure looks to be an INFRA issue:

```
GitHub has been notified of this commit’s build result



java.nio.channels.ClosedChannelException

Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 52.167.58.247/52.167.58.247:49188

		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)

		at hudson.remoting.Request.call(Request.java:202)

		at hudson.remoting.Channel.call(Channel.java:956)

		at hudson.FilePath.act(FilePath.java:1069)

		at hudson.FilePath.act(FilePath.java:1058)

		at hudson.FilePath.exists(FilePath.java:1555)

		at jenkins.branch.WorkspaceLocatorImpl.load(WorkspaceLocatorImpl.java:218)

		at jenkins.branch.WorkspaceLocatorImpl.locate(WorkspaceLocatorImpl.java:159)

		at jenkins.branch.WorkspaceLocatorImpl.locate(WorkspaceLocatorImpl.java:129)

		at jenkins.branch.WorkspaceLocatorImpl.locate(WorkspaceLocatorImpl.java:125)

		at hudson.model.Slave.getWorkspaceFor(Slave.java:335)

		at org.jenkinsci.plugins.workflow.support.steps.ExecutorStepExecution$PlaceholderTask$PlaceholderExecutable.run(ExecutorStepExecution.java:771)

		at hudson.model.ResourceController.execute(ResourceController.java:97)

		at hudson.model.Executor.run(Executor.java:429)

Also:   hudson.model.Computer$TerminationRequest: Termination requested at Tue Apr 30 20:59:00 GMT 2019 by Thread[Ping thread for channel hudson.remoting.Channel@51fb573:JNLP4-connect connection from 52.167.58.247/52.167.58.247:49188,5,main] [id=18536]

		at hudson.model.Computer.recordTermination(Computer.java:226)

		at hudson.model.Computer.disconnect(Computer.java:489)

		at hudson.slaves.SlaveComputer.disconnect(SlaveComputer.java:735)

		at hudson.slaves.ChannelPinger$1.onDead(ChannelPinger.java:197)

		at hudson.remoting.PingThread.ping(PingThread.java:134)

		at hudson.remoting.PingThread.run(PingThread.java:90)

Caused: hudson.remoting.RequestAbortedException

	at hudson.remoting.Request.abort(Request.java:340)

```

**Comment by oleg-nenashev** [comment]
Will merge it into the next weekly if there is no negative feedback

**Pull request merged**
