### PR TITLE
Stable 2.249.1

### PR DESCRIPTION
**Pull request by olivergondza**
Please have look at the changes proposed, so we have a consensus of what goes in. I suggest to backport all the candidates.

Fixed
-----
````
JENKINS-63462		Blocker
	Jenkins 2.252 security fixes need to be in 2.249.1
	https://issues.jenkins-ci.org/browse/JENKINS-63462
- SECURITY-1955 Stored XSS vulnerability in help icons
- SECURITY-1960 Stored XSS vulnerability in 'Trigger builds remotely' 
- SECURITY-1957 Stored XSS vulnerability in project naming strategy

JENKINS-63285		Minor     		2.251
	Fix colour inconsistencies
	https://issues.jenkins-ci.org/browse/JENKINS-63285

JENKINS-63276		Minor     		2.251
	No plugins text unreadable
	regression
	https://issues.jenkins-ci.org/browse/JENKINS-63276

JENKINS-63232		Major     		2.251
	Build Time Trend Page fails to Display Build Time History
	regression
	https://issues.jenkins-ci.org/browse/JENKINS-63232

JENKINS-63180		Minor     		2.251
	Correct style for Tabs with long names and many tabs
	regression
	https://issues.jenkins-ci.org/browse/JENKINS-63180

JENKINS-63166		Minor     		2.251
	Jenkins core: Cleanup slave references in the Japanese localization
	https://issues.jenkins-ci.org/browse/JENKINS-63166

### CODE REVIEW

**Comment by daniel-beck** [comment]
We probably need https://github.com/jenkinsci/jenkins/pull/4915 here as well.

**Review by daniel-beck — APPROVED** [review]
Looks reasonable. Security fixes are correctly backported.

**Review by amuniz — APPROVED** [review]

**Comment by fcojfernandez** [comment]
What about https://github.com/jenkinsci/jenkins/pull/4896? Its JIRA ticket (https://issues.jenkins-ci.org/browse/JENKINS-63308) was labeled as lts-candidate and without that fix the UI is broken for the `doCheck` methods. 
CC @timja

**Comment by timja** [comment]
Also https://github.com/jenkinsci/jenkins/pull/4912 should be included

**Comment by olivergondza** [comment]
@fcojfernandez, the JIRA is still marked In Review and as such is not considered for backporting. Looks like an omission.

@timja, #4912 is something to consider now when it is merged.

**Comment by jglick** [comment]
If backporting #4912, it may be helpful to first backport #4886 (which was also post-2.249) to avoid merge conflicts, even though #4912 is just deleting the whole block that #4886 edited.

**Review by res0nance — APPROVED** [review]

**Comment by fcojfernandez** [comment]
@olivergondza, @timja has marked https://issues.jenkins-ci.org/browse/JENKINS-63308 as resolved

**Comment by olivergondza** [comment]
I have updated the PR will the additional backports.

Postponed
---------

JENKINS-63330		Minor     		2.253
	Alert popup colour's inconsistent with Manage Jenkins
	https://issues.jenkins-ci.org/browse/JENKINS-63330

JENKINS-63331		Minor     		2.253
	Unavailable plugin background is not themeable
	https://issues.jenkins-ci.org/browse/JENKINS-63331

Fixed
-----

JENKINS-63462		Blocker   		
	Jenkins 2.252 security fixes need to be in 2.249.1
	https://issues.jenkins-ci.org/browse/JENKINS-63462

JENKINS-63458		Blocker   		2.254
	Agent deadlock associated with SlaveInitializer, part III
	regression
	https://issues.jenkins-ci.org/browse/JENKINS-63458

JENKINS-63342		Minor     		2.253
	Some keyboard inputs broken in Script Console on a Mac
	regression
	https://issues.jenkins-ci.org/browse/JENKINS-63342

JENKINS-63308		Minor     		2.253
	Regexp Validator location incorrect since 2.244
	https://issues.jenkins-ci.org/browse/JENKINS-63308

JENKINS-63285		Minor     		2.251
	Fix colour inconsistencies
	https://issues.jenkins-ci.org/browse/JENKINS-63285

JENKINS-63276		Minor     		2.251
	No plugins text unreadable
	regression
	https://issues.jenkins-ci.org/browse/JENKINS-63276

JENKINS-63274		Minor     		2.253
	Copy to clipboard doesn't work for api tokens
	https://issues.jenkins-ci.org/browse/JENKINS-63274

JENKINS-63232		Major     		2.251
	Build Time Trend Page fails to Display Build Time History
	regression
	https://issues.jenkins-ci.org/browse/JENKINS-63232

JENKINS-63180		Minor     		2.251
	Correct style for Tabs with long names and many tabs
	regression
	https://issues.jenkins-ci.org/browse/JENKINS-63180

JENKINS-63166		Minor     		2.251
	Jenkins core: Cleanup slave references in the Japanese localization
	https://issues.jenkins-ci.org/browse/JENKINS-63166

JENKINS-61687		Minor     		2.253
	Exceptions due to race condition during build deletion
	https://issues.jenkins-ci.org/browse/JENKINS-61687

INFRA-266		Major     		
	Jenkins and jenkins plugins not available for download via HTTPS
	https://issues.jenkins-ci.org/browse/INFRA-266

**Comment by olivergondza** [comment]
Merging, thank you folks for review

**Pull request merged**
