### PR TITLE
Backporting for LTS 2.440.2

### PR DESCRIPTION
**Pull request by krisstern**
```shell
Latest core version: jenkins-2.448

Postponed
---------

JENKINS-72799           Minor                   Tue, 5 Mar 2024 13:24:45 +0000
        ConsoleLogFilter is not applied to all SlaveComputer logging
        https://issues.jenkins.io/browse/JENKINS-72799

Fixed
-----

JENKINS-72775           Minor                   2.444
        Update Winstone to 6.18 to get Jetty 10.0.20
        https://issues.jenkins.io/browse/JENKINS-72775

JENKINS-72711           Minor                   2.446
        Build History page no longer uses animated icons for builds in progress (regression in 2.434)
        regression
        https://issues.jenkins.io/browse/JENKINS-72711

JENKINS-72407           Major                   <a href="https://www.jenkins.io/changelog/?query#v2.443">https://www.jenkins.io/changelog/?query#v2.443</a>
        Build status icon missing for multibranch pipeline
        https://issues.jenkins.io/browse/JENKINS-72407

JENKINS-71148           Trivial                 2.447
        Do not display empty tooltips
        https://issues.jenkins.io/browse/JENKINS-71148
```

```[tasklist]
### Submitter checklist
- [x] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

N/A

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Comment by kmartens27** [comment]
@krisstern can you confirm whether
```
 JENKINS-72407           Major                   <a href="https://www.jenkins.io/changelog/?query#v2.443">https://www.jenkins.io/changelog/?query#v2.443</a>
        Build status icon missing for multibranch pipeline
        https://issues.jenkins.io/browse/JENKINS-72407
```
is the same as what's mentioned in the 2.440.1 backporting? I ask because the empty folder icons were included in the last LTS changelog.

Screenshot 2024-03-05 at 10 54 04 AM

I just want to make sure that it is included in the correct changelog, so if it did not get released as part of .1, then I need to adjust everything accordingly.

**Comment by krisstern** [comment]
@kmartens27 Yes, the commit referring to in
```shell
JENKINS-72407           Major                   <a href="https://www.jenkins.io/changelog/?query#v2.443">https://www.jenkins.io/changelog/?query#v2.443</a>
        Build status icon missing for multibranch pipeline
        https://issues.jenkins.io/browse/JENKINS-72407
```
is an empty commit. Should be okay codewise. However, I am not sure if this is needed. I am including this resolved commit again for completeness' sake, so that we can close the JIRA issue for it.

**Review by basil — APPROVED** [review]
The fix for JENKINS-72407 was already backported to `stable-2.440` in #8945. I do not see a need for an empty commit, as this feels like process for its own sake rather than for the sake of achieving any specific goal. But I do not feel strongly either way.

**Comment by daniel-beck** [comment]
I changed the Jira labels from `2.440.2-fixed` to `2.440.1-fixed` to reflect reality. CC @NotMyFault who switched it back from `2.440.1-fixed` to `lts-candidate` in case I'm missing something.

**Comment by krisstern** [comment]
I have removed the commit for:
```shell
JENKINS-72407           Major                   <a href="https://www.jenkins.io/changelog/?query#v2.443">https://www.jenkins.io/changelog/?query#v2.443</a>
        Build status icon missing for multibranch pipeline
        https://issues.jenkins.io/browse/JENKINS-72407
```

**Pull request merged**
