### PR TITLE
Upgrade to Groovy 2.4.11

### PR DESCRIPTION
**Pull request by kamilszymanski**
Fixes few subtle Groovy issues
[Groovy 2.4.9 release notes](http://groovy-lang.org/changelogs/changelog-2.4.9.html)
[Groovy 2.4.10 release notes](http://groovy-lang.org/changelogs/changelog-2.4.10.html)
[Groovy 2.4.11 release notes](http://groovy-lang.org/changelogs/changelog-2.4.11.html)

### Changelog

* Update Groovy from 2.4.8 to 2.4.11 (+ Links to the release notes)

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
It also picks 2.4.9: http://groovy-lang.org/changelogs/changelog-2.4.9.html

**Comment by oleg-nenashev** [comment]
Summon @jenkinsci/code-reviewer, @daspilker and @jglick

**Comment by jglick** [comment]
Code review is useless here; need someone to do exhaustive testing of all affected plugins.

**Comment by daniel-beck** [comment]
> need someone to do exhaustive testing of all affected plugins

This. What effectively amounts to regressions due to 2.4.8 already was the major factor in deciding not to go with 2.48 for the next LTS baseline.

**Comment by oleg-nenashev** [comment]
The next LTS baseline is pretty far from here, so maybe we could do that. But I agree we need somebody to test it

**Comment by daniel-beck** [comment]
The label doesn't work exactly, but it's the closest we have.

**Review by abayer — CHANGES_REQUESTED** [review]
If we're going to bump Groovy, we should bump it to 2.4.11, which has a fix for https://issues.apache.org/jira/browse/GROOVY-8140, which I found in `groovy-cps` work.

**Comment by daspilker** [comment]
👍 for going directly to 2.4.11.

I tested Job DSL with 2.4.11 and core @ https://github.com/jenkinsci/jenkins/commit/b5ee2a0750a242e6160641670330768a9c20cd4f. Since Job DSL still targets Groovy 1.8.9 and core 1.651, I get compile and test errors. But those are the same as with 2.4.8, so updating to 2.4.11 should be no problem for Job DSL.

**Comment by oleg-nenashev** [comment]
If we want to upgrade, probably it is a good time to do so if we want to use 2.57 as LTS. If not, maybe we want to postpone such change a bit

**Comment by oleg-nenashev** [comment]
I will create new PR for 2.4.11

**Comment by kamilszymanski** [comment]
@oleg-nenashev I can update this PR

**Comment by oleg-nenashev** [comment]
@kamilszymanski fine for me

**Review by oleg-nenashev — APPROVED** [review]
👍 from me since @daspilker tested it with JobDSL. Would be nice to get feedback from @jglick regarding Pipeline

**Comment by oleg-nenashev** [comment]
@jglick @abayer ping. If there is no response from Pipeline devs, we may probably merge it towards 2.60 according to the feedback from @daspilker

**Review by abayer — APPROVED** [review]
Yup, I've tested 2.4.11 pretty thoroughly with Pipeline and it looks good.

**Comment by oleg-nenashev** [comment]
Merging according to the feedback

**Pull request merged**
