### PR TITLE
Backporting for LTS 2.332.3

### PR DESCRIPTION
**Pull request by NotMyFault**
```
Latest core version: jenkins-2.343

Fixed
-----

JENKINS-68254           Major                   2.343
        Jenkins build queue is cleared after restart (regression in 2.333)
        regression
        https://issues.jenkins.io/browse/JENKINS-68254

JENKINS-68122           Major                   2.343
        Agent connection broken (randomly) with error java.util.concurrent.TimeoutException (regression in 2.325)
        regression
        https://issues.jenkins.io/browse/JENKINS-68122

JENKINS-68056           Trivial                 2.340
        Bad character encoding in the Security Warning box (French)
        https://issues.jenkins.io/browse/JENKINS-68056

JENKINS-68055           Minor                   2.343
        load statistics not working for label expressions (regression in 2.289)
        regression
        https://issues.jenkins.io/browse/JENKINS-68055

JENKINS-67967           Minor                   2.341
        "View build information" is not readonly
        https://issues.jenkins.io/browse/JENKINS-67967

JENKINS-67742           Minor                   2.335
        Agent launching gif has white background
        https://issues.jenkins.io/browse/JENKINS-67742

JENKINS-68057           Minor                   2.338
        java.lang.NullPointerException in system logs
        https://issues.jenkins.io/browse/JENKINS-68057

JENKINS-68276           Minor                   2.344
        bump jackson2-api plugin
        https://issues.jenkins.io/browse/JENKINS-68276

JENKINS-68260           Minor                   2.344
        Cannot filter updates by plugin ID anymore (regression in 2.321)
        https://issues.jenkins.io/browse/JENKINS-68260
```

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Review by timja — APPROVED** [review]

**Review by res0nance — APPROVED** [review]

**Review by basil — APPROVED** [review]

**Comment by MarkEWaite** [comment]
@NotMyFault thanks very much!

As far as I can tell, 

> JENKINS-68149           Major                   2.332.2
>         2.332.1 upgrade changes JENKINS_WAR default location but doesn't apply it in the configuration
>         https://issues.jenkins.io/browse/JENKINS-68149

was included in 2.332.2.  Are you OK if I remove it from the PR description so that we don't incorrectly include it in the changelog?

**Comment by NotMyFault** [comment]
Yeah, basil closed the packaging PR, because all changes already included in .2.

**Comment by jglick** [comment]
https://github.com/jenkinsci/jenkins/pull/6472/commits/64cd8ca0e64597bef8c747f79a069ff78df21eca OK

**Comment by basil** [comment]
Has JENKINS-68260 (i.e. commit b7366fce5d6ea3871904d8b39dd04fb4b54cef5b) been verified yet? This fix has not yet shipped in a weekly, and I looked in Jira and in the pull request but I did not see that anyone has verified the fix yet.

**Comment by NotMyFault** [comment]
> Has JENKINS-68260 (i.e. commit [b7366fc](https://github.com/jenkinsci/jenkins/commit/b7366fce5d6ea3871904d8b39dd04fb4b54cef5b)) been verified yet? This fix has not yet shipped in a weekly, and I looked in Jira and in the pull request but I did not see that anyone has verified the fix yet.

Yeah, there's been no testing of this in a weekly yet outside of the reviewers of the PR.

**Comment by basil** [comment]
> Yeah, there's been no testing of this in a weekly yet outside of the people reviewing the PR.

OK, so then I think it is premature to backport the fix. We should not be backporting fixes that have not yet been verified. If the fix gets verified then I think it is fine to backport it.

**Comment by timja** [comment]
>  but I did not see that anyone has verified the fix yet

I verified the fix when reviewing it, normally we would release in a weekly first, although in this case it's a very small change

**Comment by basil** [comment]
> I verified the fix when reviewing it

Excellent! Would be great if you could update the verified status in Jira by moving the bug from Resolved to Closed then.

**Review by zbynek — APPROVED** [review]

**Comment by NotMyFault** [comment]
Heyo @MarkEWaite, did you have a chance to look over this PR and the changes proposed yet?
I'm heading forward to publish the RC tomorrow.

**Review by MarkEWaite — APPROVED** [review]

**Pull request merged**
