### PR TITLE
Custom workspace tr zh replace slave on agent

### PR DESCRIPTION
**Pull request by Fargk**
See [JENKINS-42816](https://issues.jenkins-ci.org/browse/JENKINS-42816).

It is a small part of that issue. But it looks like this is the last patch for slave word in war/src/main/webapp/help/project-config/custom-workspace_.*.html files.

In TR and ZH localizations replaced slave on agent and slaves on agents.

### CODE REVIEW

**Comment by MarkEWaite** [comment]
> See [JENKINS-42816](https://issues.jenkins-ci.org/browse/JENKINS-42816).
> 
> It is a small part of that issue. But it looks like this is the last patch for slave word in war/src/main/webapp/help/project-config/custom-workspace_.*.html files.
> 
> In TR and ZH localizations replaced slave on agent and slaves on agents.

Are you fluent in both those languages?  We've had issues in the past where a non-native speaker provided a translation that was worse than the original flawed terminology.  We like to ask the submitter if they are confident that the replacement is correct.

@LinuxSuRen can you review the Chinese translation?

**Review by LinuxSuRen — APPROVED** [review]
I'm not quite familiar with TW. But it looks like no changes with the sentence. The only change is switching `Slave` to `Agent`.

LGTM

**Comment by Fargk** [comment]
so?

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Pull request merged**
