### PR TITLE
[JENKINS-30745] - Revert trigger optimisation

### PR DESCRIPTION
**Pull request by KostyaSha**
I don't want (and have no time) continue fixing this crappy APIs. 

My result:
- i fixed some existed possible NPEs in plugins and core for Triggers API
- added tests
- users are not happy https://issues.jenkins-ci.org/browse/JENKINS-30745 as it exposed bad job API
- filled https://issues.jenkins-ci.org/browse/JENKINS-30802
- revert same as in LTS (make @olivergondza happy)

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
:+1:

**Comment by oleg-nenashev** [comment]
Personally I don't think the revert is really required.
It may break particular use-case, but IMO they were invalid according to the "copy jobs" concept. Or not?

**Comment by KostyaSha** [comment]
Yes, as i described in https://issues.jenkins-ci.org/browse/JENKINS-30802 job state has no clear API and confuses everybody. Trigger optimisation just unmasked bad trigger/job API. And frankly speaking i don't want deal with enhancements while jenkins 2.0 will be "break everything only for cosmetic/marketing needs".

**Comment by oleg-nenashev** [comment]
We missed the previous release in any case, so now we have several days for the discussion. Feedback from others would be appreciated.

**Comment by oleg-nenashev** [comment]
I'll merge the PR on Saturday if nobody responds

**Comment by oleg-nenashev** [comment]
Ok, going forward

**Comment by oleg-nenashev** [comment]
@olivergondza Your action with LTS branch is required

**Comment by KostyaSha** [comment]
not required

**Pull request merged**
