### PR TITLE
[JENKINS-39414] Integrating Stapler 1.248

### PR DESCRIPTION
**Pull request by jglick**
[Changes](https://github.com/stapler/stapler/compare/stapler-parent-1.247...stapler-parent-1.248) are just https://github.com/stapler/stapler/pull/88.

@reviewbybees esp. @oleg-nenashev

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
🐝 as an author of https://github.com/stapler/stapler/pull/88
We should finally start doing changelogs in Stapler...

**Comment by daniel-beck** [comment]
Diff: https://github.com/stapler/stapler/compare/stapler-parent-1.247...stapler-parent-1.248

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers It would be great to get the review. We want to merge it into the tomorrow's out-of-order release ([discussion](https://groups.google.com/forum/#!topic/jenkinsci-dev/kceM9T8NEdg))

**Comment by abayer** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Comment by christ66** [comment]
:bee:

**Pull request merged**
