### PR TITLE
JENKINS-29180 Add a direct sidebar link "Manage Nodes"

### PR DESCRIPTION
**Pull request by Austry**
See [JENKINS-29180](https://issues.jenkins-ci.org/browse/JENKINS-29180).

### Proposed changelog entries
 Add a direct sidebar link "Manage Nodes"

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). 
- [x] Appropriate autotests or explanation to why this change has no tests

No tests because of minor UI improvement

### CODE REVIEW

**Comment by daniel-beck** [comment]
Thanks for tackling this!

FWIW I don't think it's _this_ straightforward to solve this adequately:

* It's a link labeled "Manage" appearing for all users, even those lacking any permissions other than Overall/Read. At this point, you're only viewing nodes/listing nodes/go to nodes/similar.
* It's redundant as the link exists in the build executors widget (and perhaps should be removed from there?), and in Manage Jenkins for those with access to it (same?).

On top of that I am not sure about the benefit of adding redundant links on parts of the UI that tend to be filled to overflowing with plugin contributed items.

Personally I wonder whether a better solution would instead be to make _Manage Jenkins_ available to users without the _Jenkins/Administer_ permission, instead checking whether any item therein would be accessible, and if so, making the link (and list) visible. This would integrate nicely with some ideas around a "lesser" permission than _Jenkins/Administer_. That's a larger change though (but ultimately, IMO, nicer).

**Comment by alecharp** [comment]
I agree with @daniel-beck on this, adding this link would be redundant.

**Comment by Austry** [comment]
@daniel-beck I think your proposal is much better that current realisation. 
How should we proceed? Close this PR, close [JENKINS-29180](https://issues.jenkins-ci.org/browse/JENKINS-29180 ) and create a new ticket with your proposal?

**Comment by daniel-beck** [comment]
@Austry Probably depends on whether you want to finish up this proposal or go for the other one? FTR, I'm unable to dedicate much, if any, time to helping with that.

**Comment by Austry** [comment]
Not ready to implement your proposal, @daniel-beck

**Pull request closed without merging**
