### PR TITLE
JENKINS-63798 Fix admin monitor JS showing in footer

### PR DESCRIPTION
**Pull request by timja**
See [JENKINS-63798](https://issues.jenkins-ci.org/browse/JENKINS-63798).

Caused by https://github.com/jenkinsci/jenkins/pull/4949

image

Classed as major bug as it looks really bad imo, although it doesn't impact functionality

and TIL script tag can be styled and is hidden by default in browsers, https://stackoverflow.com/a/38147398/4951015

### Proposed changelog entries

* Entry 1: JENKINS-63798, Stop showing JavaScript in the footer
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]

**Comment by mmh891113** [comment]
I also found this issue yesterday. Thank you very much.

**Comment by timja** [comment]
I think this is the simplest fix, we never want JavaScript to show on a page so excluding it from the * rule is very safe unless someone knows of a reason why this isn’t a good idea

**Comment by mmh891113** [comment]
yeah,I agree . at present, your fix should be the simplest and perfect.

**Review by res0nance — APPROVED** [review]

**Review by fqueiruga — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Review by yJunS — APPROVED** [review]
Sorry, I did not notice this part, and thank you for your fix it

**Comment by oleg-nenashev** [comment]
I suggest expedited merge so that we release it along with #4999

**Comment by oleg-nenashev** [comment]
@jenkinsci/core @timja @MarkEWaite I suggest merging it without timeout so that we ship an out-of-order release

**Comment by oleg-nenashev** [comment]
Will go ahead and merge it based on approval by @MarkEWaite in the chat

**Comment by mmh891113** [comment]
This PR is not just a fix for "admin monitor footer",  but also fix other plugin JS showing in footer , 
like translation-plugin/src/main/resources/hudson/plugins/translation/L10nDecorator/footer.jelly  and so on .

**Pull request merged**
