### PR TITLE
Ignore copyToWithPermissionSpecialPermissions test when running on os/x

### PR DESCRIPTION
**Pull request by mikecirioli**
Mac seems to drop setuid bits, ignore this test if running under os/x:

> java.lang.AssertionError: Special permissions should be copied on the same machine 
> Expected :1535
> Actual   :511

This pr replaces #4521 

### Proposed changelog entries

N/A

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

### CODE REVIEW

**Comment by mikecirioli** [comment]
FYI @zbynek

**Review by MarkEWaite — APPROVED** [review]

**Review by timja — APPROVED** [review]

**Review by zbynek — APPROVED** [review]

**Review by res0nance — APPROVED** [review]

**Comment by res0nance** [comment]
Merging in 24 hours if no negative feedback

**Review by daniel-beck — CHANGES_REQUESTED** [review]
Could we get a 'light' variant of this test so we ensure no Mac regressions for the stuff that's supposed to work?

**Comment by oleg-nenashev** [comment]
@mikecirioli hi, are you still interested in it?

**Comment by alecharp** [comment]
@mikecirioli could you have a look at Daniel's comment and add a test? Thanks.

**Comment by varyvol** [comment]
Closing given there's been no activity or answer. Please let us know in case you want to work on this again.

**Pull request closed without merging**
