### PR TITLE
[JENKINS-4610] - Remove historical CVS code

### PR DESCRIPTION
**Pull request by slide**
In JENKINS-4610 [1] it is recommended that the historical CVS code be removed from AbstractBuild, this PR removes that code.

1 - https://issues.jenkins-ci.org/browse/JENKINS-4610

### CODE REVIEW

**Comment by daniel-beck** [comment]
:+1:

**Comment by oleg-nenashev** [comment]
:+1: for the change
@daniel-beck It seems to be a really valid change of the documented behavior. Maybe makes sense to explicitly declare that such "minor breaking" changes may happen till 2.x

**Comment by kzantow** [comment]
👍 but - is there anything that needs to be done in the CVS plugin to account for this?

**Comment by oleg-nenashev** [comment]
Needs some compatibility notice in the documentation

**Comment by slide** [comment]
It says this branch cannot be built, but clicking "Details" takes me to a bad page.

**Comment by daniel-beck** [comment]
@slide PR is too old. I'll close and reopen for a new build.

**Comment by slide** [comment]
@kzantow I didn't see anything in the CVS plugin that would need attention.

**Comment by kzantow** [comment]
👍 @slide but agree with @oleg-nenashev , please add a note about the compatibility

**Comment by slide** [comment]
Added note to changelog.html

**Comment by oleg-nenashev** [comment]
Changelog needs manual re-merge since there were releases since this PR

**Comment by daniel-beck** [comment]
Best to leave out changelog changes for this reason.

**Comment by oleg-nenashev** [comment]
yep.

**Comment by slide** [comment]
What was the request for a note about compatibility for? Just in the code?

**Comment by oleg-nenashev** [comment]
@slide IMHO noting in the changelogs is a right way, but it needs to be done after the merge. Currently we have no engine, which would allow automating the process

**Comment by slide** [comment]
@oleg-nenashev  Ok, I'll remove that commit and force push. I was just going by yours and @kzantow's request for documentation

**Comment by oleg-nenashev** [comment]
@slide Yes, I should describe the proposed way with more details :( Sorry for making you do an extra work

**Comment by slide** [comment]
@oleg-nenashev It was no extra work, good to learn the processes better.

**Comment by oleg-nenashev** [comment]
re- 👍 Other votes are still actual, so I'm going to merge it

**Comment by jglick** [comment]
So is JENKINS-4610 still supposed to be open?

**Pull request merged**
