### PR TITLE
[FIXED JENKINS-25220] - Handle legacy use of iconSize as a variable

### PR DESCRIPTION
**Pull request by michmerr**
When iconSize was set as a jelly variable, not passed as an attribute,
the value was not being normalized to an IconSizeClass. Fixes
JENKINS-25220.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
It will cause regressions to new usages since https://github.com/jenkinsci/jenkins/commit/c7e98823415f3619e7a43d3f99b7f627b873fd5c

It makes sense to handle both attribute-based and variable-based specifications of <code>iconSize</code>, so the PR should not delete @kohsuke's code IMO.

**Comment by michmerr** [comment]
I'm pretty sure that when I tested this change, iconSize evaluated to the value of attr.iconSize if the attribute was set and the variable was not. So, it covers both cases, but it's probably better to explicitly check the values rather than count on this behavior.

**Comment by oleg-nenashev** [comment]
The old use-case is even more legacy now, but the change stills actual. Needs review

**Comment by daniel-beck** [comment]
Seems safe enough. @oleg-nenashev WDYT?

Also pinging @tfennelly in case he remembers what he did here.

**Comment by oleg-nenashev** [comment]
👍

**Pull request merged**
