### PR TITLE
Clean up formatting

### PR DESCRIPTION
**Pull request by jvz**
This file always annoys me whenever I come across it.

### Proposed changelog entries

* None

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

Whoever.

### CODE REVIEW

**Review by varyvol — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
It is still not an expected codestyle (we use the Oracle one), but it is definitely better than the original ones

**Comment by jvz** [comment]
Do we use inline annotations or not? I prefer the more common style of annotations on their own lines (except for method/constructor parameters), though I was simply trying to get this file to look the way it used to before the security patch that reformatted it.

**Comment by oleg-nenashev** [comment]
> Do we use inline annotations or not? I prefer the more common style of annotations on their own lines (except for method/constructor parameters)

Depends on whom you ask. The https://wiki.jenkins.io/display/JENKINS/Beginners+Guide+to+Contributing#BeginnersGuidetoContributing-CodeStyle explicitly refers the Oracle codestyle where annotations go to a separate line. But historically @jglick and few other contributors were using a different codestyle, hence there are different approaches. While doing reviews, I accept any codestyle in PRs as long as it is easily readable

**Comment by jglick** [comment]
I think you are mixing up two different things.

I personally recommend a non-Oracle styling (immediately preceding modifiers on same line) for a single determinative annotation (`@Override`, `@Extension`, `@Test`, `@Rule`, etc.) which gives the reason for the _existence_ of a member; and Oracle styling (preceding lines) for descriptive annotations (`@GuardedBy`, `@Deprecated`, `@Restricted`, `@Symbol`, `@RequirePOST`, etc.) which modify the meaning or behavior but without which the member might still make sense. (There is some grey area for example with `@Exported`: would this method ever be called by Java code, or is it there solely for the RESTish API?)

Then there are annotations originating in JSR 305 and Find/SpotBugs like `@NonNull` or `@Nonnull`. Some are applied to method parameters, in which case they immediately precede the parameter type in standard style; fine. The confusion is over usages which are marked as `@Target({ElementType.METHOD, …})` and so are technically parsed as method-level annotations, yet the intended meaning (and interpretation by checkers) is an annotation on the return type, which could be indicated only in a Java 8+ annotation library via `ElementType.TYPE_USE`. While the legalistic interpretation of the grammar would put them on the preceding line, it seems more intuitive and legible to have them inline preceding the return type, just like `PARAMETER` uses.

Anyway, I doubt anyone much cares so long as the result looks reasonable, as @oleg-nenashev said.

**Comment by jvz** [comment]
That's the gist of the style I had adopted here: annotations that logically apply to the return type go on the type, and annotations that logically apply to the method itself go on its own line (like `@Test`, `@Override`, etc)

**Review by jeffret-b — APPROVED** [review]

**Pull request merged**
