### PR TITLE
[FIXED JENKINS-26240] Use backwards compatible gzip compression

### PR DESCRIPTION
**Pull request by daniel-beck**
Untested change, but according to

http://man.he.net/man1/debuild
&rarr; http://man.he.net/man1/dpkg-buildpackage
 &rarr; http://man.he.net/man1/dpkg-source

this should work. @kohsuke please review.

### CODE REVIEW

**Comment by daniel-beck** [comment]
I used the Github UI to create this PR, and the branch was unexpectedly created in the `jenkinsci` repo. Sorry about that.

**Comment by dblock** [comment]
This seems to be https://issues.jenkins-ci.org/browse/JENKINS-26240, but the instructions in there to do the ugprade aren't working :( Can we get this merged and maybe provide a workaround until a new release?

**Comment by daniel-beck** [comment]
The script is moving to https://github.com/jenkinsci/packaging so this PR is obsolete. Will recreate over there if necessary.

**Comment by daniel-beck** [comment]
Superseded by https://github.com/jenkinsci/packaging/pull/1

**Pull request closed without merging**
