### PR TITLE
Make text gender neutral

### PR DESCRIPTION
**Pull request by bwalding**

### CODE REVIEW

**Comment by batmat** [comment]
:+1:

**Comment by oleg-nenashev** [comment]
🐛 Then s/user/users/

**Comment by slide** [comment]
:+1:

**Comment by bwalding** [comment]
@oleg-nenashev 
The other strategies (patternJobNaming) use the singular "user" - so I'll leave this one as user for consistency.

**Comment by oleg-nenashev** [comment]
OK

**Comment by KostyaSha** [comment]
@oleg-nenashev delete source branch because it mass used upstream?

**Comment by oleg-nenashev** [comment]
deleted

**Comment by KostyaSha** [comment]
thanks!

**Pull request merged**
