### PR TITLE
Removed html.jelly since it was deprecated as of 2.53

### PR DESCRIPTION
**Pull request by recena**
# Description

Technically, this PR is a follow up of https://github.com/jenkinsci/jenkins/pull/2445 according to the @oleg-nenashev's [suggestion](https://github.com/jenkinsci/jenkins/pull/2445#issuecomment-287009716).

### Changelog entries

Proposed changelog entries:

* The `HTML` Jelly tag has been removed. Deprecated since `2.53`, use `<l:layout />` tag instead defined on `layout.jelly`.

### Desired reviewers

@jenkinsci/code-reviewers
@reviewbybees

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
IMHO this PR cannot be merged until we have API deprecation policy

**Comment by recena** [comment]
@oleg-nenashev What is the proper way to move forward the API deprecation policy discussion? /cc @kohsuke @daniel-beck @jglick

**Comment by jglick** [comment]
It is already deprecated; why not just leave it there? Or are we confident that this tag has not been used in plugins?

**Comment by recena** [comment]
@jglick 

>  why not just leave it there?

I did never like the idea of keeping code no used. Noise, confusions, doubts, ....

> Or are we confident that this tag has not been used in plugins?

* Taking into account that `html.jelly` was exclusively introduced on Jenkins 2 for implementing the full screen layout on the Setup Wizard...
* I did some findings on GitHub...

**Comment by oleg-nenashev** [comment]
> @oleg-nenashev What is the proper way to move forward the API deprecation policy discussion? /cc 

No good answer. We have a kind of "idea" for Jenkins 2, but AFAIK it has been never detalized. I would start from writing a design proposal for it and sending it to the community review

**Comment by recena** [comment]
@oleg-nenashev You replied my question perfectly, hence, the question was correct 😄 

Now we have a policy. Nothing can be moved.

**Comment by daniel-beck** [comment]
Are we in agreement then that this should just be closed?

**Comment by recena** [comment]
@daniel-beck No, I disagree. Please, do not close this PR.

**Comment by daniel-beck** [comment]
@recena Please explain why we should remove public API for no actual reason than "never like the idea of keeping code no used". We've never done this, and Jenkins still contains code deprecated *ten years ago* (just look for "deprecated since" in the core codebase). There's a decade of precedence for us not arbitrarily introducing breaking changes, Jelly tags are considered API, and unless you have a strong reason for this change justifying plugins, even private ones, possibly breaking, it doesn't make sense to implement this.

This should not be a surprise to you. I wrote in https://github.com/jenkinsci/jenkins/pull/2445#issuecomment-234670204:

> In fact, it may be not possible to remove it, as it's effectively part of Jenkins' public plugin API now.

Later in https://github.com/jenkinsci/jenkins/pull/2445#issuecomment-239616175:

> Once we add something, we cannot easily remove it anymore, so we should make sure we're adding the right thing, in the right way.

@oleg-nenashev wrote in https://github.com/jenkinsci/jenkins/pull/2445#pullrequestreview-27060680 in the same PR:

> Even if it does not make sense for other usages (proof?), it was a part of the Jenkins API for Jelly, which is documented in Jenkins TagLib documentation. … IMHO it is not safe to just remove it.

**Comment by recena** [comment]
Maybe it is good moment for changing the some things, no? Keep deprecated indefinitely is not a good practice. At least, IMHO.

**Comment by daniel-beck** [comment]
> Maybe it is good moment for changing the some things, no? Keep deprecated indefinitely is not a good practice. At least, IMHO.

Perhaps, but the place to introduce a major shift in policy is not a "cleanup" PR. It needs to be considered carefully, weighing pros and cons, widely discussed and announced, and plugin developers need to be given plenty of time to adapt. If you want to take that on, go ahead. We have some tooling already for Java APIs in https://github.com/jenkins-infra/deprecated-usage-in-plugins that you may be able to use.

**Comment by recena** [comment]
@daniel-beck Obviously, each change in the API should be considered and analyzed. If you try to compare `Hudson` or its `getInstance()` with `html.jelly`, we are talking on different levels.

By the way, this PR was filed for two main reasons:

1. It was a @oleg-nenashev's suggestion
1. Record my intention of cleaning up. This PR can be referenced in the future if needed.

**Comment by daniel-beck** [comment]
> we are talking on different levels.

Right, this one might well be safe, but just starting to do this with anything is still a major policy shift we need to make people aware of. The pitfalls of being the first to do something ;-)

> It was a @oleg-nenashev's suggestion

I think the idea was to decouple this discussion from the main part of the other PR – otherwise that would have been stalled as I expect this to be.

**Comment by jglick** [comment]
FWIW I am +0 on this if someone has looked and there are no known usages. It is unlikely to have been used from even private plugins due to the nature of the API.

**Comment by recena** [comment]
A `+0` by @jglick on this conversation is great.

**Comment by oleg-nenashev** [comment]
> I think the idea was to decouple this discussion from the main part of the other PR – otherwise that would have been stalled as I expect this to be.

Yes, I had no intention to vote for such change before we have clear API deprecation policy.

> Record my intention of cleaning up. This PR can be referenced in the future if needed.

I would propose to create a "Deprecated API cleanup" EPIC and start adding improvement tickets to it. There is a bunch of API methods and resources we may want to kill

**Comment by daniel-beck** [comment]
@recena Do you plan to propose a more aggressive deprecation/API removal policy? Otherwise I think this should be closed.

**Comment by recena** [comment]
IMHO we could merge this PR.

**Comment by recena** [comment]
IMHO we could merge this PR.

**Comment by daniel-beck** [comment]
Reading through the thread above, I disagree. Both @oleg-nenashev and I disagree with merging this PR (and have explained extensively why), and @jglick is neutral.

**Review by daniel-beck — CHANGES_REQUESTED** [review]
The concerns from early 2017 have not been addressed, so this should not be merged.

**Comment by recena** [comment]
How I could get this PR merged?

**Comment by daniel-beck** [comment]
We have no process for removing deprecated API, as previously discussed in this thread (and you have acknowledged in https://github.com/jenkinsci/jenkins/pull/2852#issuecomment-296230224). If you want to define such a process, the best way would be to go through a JEP.

**Comment by recena** [comment]
@daniel-beck Then, It seems to be that we can only close this PR 😄

**Pull request closed without merging**
