### PR TITLE
[JENKINS-63937, JENKINS-63933] - Revert "Omit stacktraces on ClassNotFoundException in PluginStrategy classloading"

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Reverts jenkinsci/jenkins#4957 to fix https://issues.jenkins-ci.org/browse/JENKINS-63937 . To be merged if I have no better fix (or edge case confirmation) by tomorrow.

### Proposed changelog entries

* Disable omitting ClassNotFoundException stacktraces in AntClassLoader and ClassicPluginStrategy due to the regressions for some agent types.

### Proposed upgrade guidelines

N/A

### CODE REVIEW

**Review by timja — APPROVED** [review]
not ideal, but if we have to

**Review by jglick — APPROVED** [review]
Good enough for a hotfix.

**Review by res0nance — APPROVED** [review]

**Comment by alecharp** [comment]
Marking this as ready-for-merge, unless you have a better fix @oleg-nenashev. If not, then we should merge this one. Thanks

**Comment by oleg-nenashev** [comment]
I think we need https://issues.jenkins-ci.org/browse/JENKINS-63933 before cutting an out of order release. Taking the LTS selection deadline, I am inclined to recommend merging this fix as the safest option. I will keep it here for now, but I will focus on the Warnings NG issue

**Comment by oleg-nenashev** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-63933 was also caused by that patch.
@jenkinsci/core I suggest out of order release

**Comment by oleg-nenashev** [comment]
Merging as an expedited fix

**Pull request merged**
