### PR TITLE
FIX:[JENKINS-35499]Review and document all remaining uses of the term 'slave' in core

### PR DESCRIPTION
**Pull request by Vandit1604**
See [JENKINS-35499](https://issues.jenkins.io/browse/JENKINS-35499).
as suggested by @daniel-beck in discussions of #7410  I've created a smaller PR

Some of the occurences of slave cant be changed as they are used in Messages.java and it is regenerated everytime we build the project 
All The Classes containing the term 'slave 'That Inherit Slave.java can't be changed as Slave.java is used in Jenkins.java and it is not editable
### Testing done

i ran these tests `mvn -Dtests=LogRecorderManagerTest test`      

### Proposed changelog entries

Rename getSlaveLogRecords to getAgentLogRecords in package hudson.logging in files LogRecorder and LogRecorderManagerTest

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.

### Desired reviewers

@daniel-beck

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7418"></a>

### CODE REVIEW

**Review by MarkEWaite — CHANGES_REQUESTED** [review]
This change would break tests for at least one public plugin.  https://plugins.jenkins.io/github-branch-source/ refers to this method in [GithubAppCredentialsTest](https://github.com/jenkinsci/github-branch-source-plugin/blob/3a7603564d04ec5b89e9b24e05858a587d863ba2/src/test/java/org/jenkinsci/plugins/github_branch_source/GithubAppCredentialsTest.java#L572).  That plugin is installed on more than 240000 Jenkins controllers .

As far as I can tell, renaming public methods in Jenkins core is a much more challenging verification task than is covered by compiling and running tests with Jenkins core.

**Comment by Vandit1604** [comment]
How can i check the compatiblity of the code change with all the plugins ? Is there a way to do so ?

**Comment by daniel-beck** [comment]
> See [JENKINS-35499](https://issues.jenkins.io/browse/JENKINS-35499).

That issue looks unrelated.

> How can i check the compatiblity of the code change with all the plugins ? Is there a way to do so ?

GitHub code search for the method name (and class name if knowable) would be a start. More comprehensive coverage would be use of https://github.com/jenkins-infra/usage-in-plugins with a custom control file specifying the method you're changing. Even then, many organizations maintain private-source plugins, so we usually weigh the benefits of the API change against the impact of (unknowable) breaking changes.

For cases like this, removal of the existing method is likely the wrong approach. Consider creating a new method that you move the method body into, then deprecating the old one and changing it to call the new one. Any callers can adapt to the change over time, so we may be able to remove the deprecated method later. An example of that is in `AgentComputerUtil`.

While we welcome contributions to this effort, please also note that you're starting work on this topic a long time after regular contributors have taken care of most of the "easy" stuff. What's left is either an oversight (possible) or cumbersome to do well (likely). I would not expect "quick wins" in this topic, at least not in this repo. This might be a topic that's easier to get started with in plugins.

**Comment by Vandit1604** [comment]
> 
> For cases like this, removal of the existing method is likely the wrong approach. Consider creating a new method that you move the method body into, then deprecating the old one and changing it to call the new one. Any callers can adapt to the change over time, so we may be able to remove the deprecated method later. An example of that is in `AgentComputerUtil`.
> 
correct me if i understood this wrong but so i can just copy the method body with method name replacing slave with agent right ?

**Comment by daniel-beck** [comment]
> correct me if i understood this wrong so you mean i can just copy the method below our method and change its method name not changing anything in the original method and same goes for classes i can create a new class in the same location that can be used later right?

Do not duplicate code. Moving is better. Hence

> new method that you move the method body into, then deprecating the old one and changing it to call the new one

Renaming classes is much more difficult because they may be used by plugins, and because of XStream serialization. The way `Hudson` and `Jenkins` relate realistically is the best we can hope for unless we start rewriting plugin bytecode on the fly, and even that wouldn't be as straightforeard for types instantiated by outside callers. I do not recommend you attempt this.

**Comment by Vandit1604** [comment]
i looked at [AgentComputerUtil](https://github.com/jenkinsci/jenkins/blob/3658c628e1edac3587ee75f9040f83f32a6a85af/core/src/main/java/jenkins/agents/AgentComputerUtil.java#L67) in which [getChannelToMaster](https://github.com/jenkinsci/jenkins/blob/3658c628e1edac3587ee75f9040f83f32a6a85af/core/src/main/java/jenkins/agents/AgentComputerUtil.java#L67) is calling another method [getChannelToController](https://github.com/jenkinsci/jenkins/blob/3658c628e1edac3587ee75f9040f83f32a6a85af/core/src/main/java/jenkins/agents/AgentComputerUtil.java#L68) so this method can be used for non-public classes but for cases like Public Class [Slave](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Slave.java) what will be the correct approach.

**Comment by Vandit1604** [comment]
```java
 /**
     * @deprecated as the term "slave" is replaced with term "agent"
     * Use {{@link #getAgentLogRecords()}}.
     */
    @Deprecated
    public Map<Computer, List<LogRecord>> getSlaveLogRecords() {
        return getAgentLogRecords();
    }

    /**
     * Gets a view of log records per agent matching this recorder.
     *
     * @return a map (sorted by display name) from computer to (nonempty) list of log records
     * @since 1.519
     */
    public Map<Computer, List<LogRecord>> getAgentLogRecords() {
        Map<Computer, List<LogRecord>> result = new TreeMap<>(new Comparator<>() {
            final Collator COLL = Collator.getInstance();

            @Override
            public int compare(Computer c1, Computer c2) {
                return COLL.compare(c1.getDisplayName(), c2.getDisplayName());
            }
        });
        for (Computer c : Jenkins.get().getComputers()) {
            if (c.getName().length() == 0) {
                continue; // master
            }
            List<LogRecord> recs = new ArrayList<>();
            try {
                for (LogRecord rec : c.getLogRecords()) {
                    for (Target t : loggers) {
                        if (t.includes(rec)) {
                            recs.add(rec);
                            break;
                        }
                    }
                }
            } catch (IOException | InterruptedException x) {
                continue;
            }
            if (!recs.isEmpty()) {
                result.put(c, recs);
            }
        }
        return result;
    }
```
is this what you meant ?
i'll be making a PR if this seems right to you

**Review by NotMyFault — CHANGES_REQUESTED** [review]
Hey,

While I honor your attempt to replace deprecated terms, I don't believe, that deprecating existing methods and introducing the same methods delegating to the deprecated methods is a great idea.
In fact, I believe that increasing the maintenance burden of deprecated methods is an undesired outcome of this transition.
I think we're on a good way, sticking to our current policy, to use matching terms when introducing new things, rather of relying on deprecated terms.
However, if you find deprecated terms in (java)docs, tests or other sorts of documentation, I'm more than happy to review a pull request updating these :)

**Comment by Vandit1604** [comment]
Thanks @NotMyFault for the clarification. I'll close this PR as suggested and check the docs for the term 'slave' if there is any use of that term i'll submit a PR.

**Pull request closed without merging**
