### PR TITLE
Re-enable installer tests

### PR DESCRIPTION
**Pull request by abayer**
Now that we're using sh2ju for installer tests and not failing the
build for test failures, instead going unstable, let's re-enable
installer tests for 2.0.

cc @reviewbybees

### CODE REVIEW

**Comment by abayer** [comment]
Closing/reopening as I play with getting PR builds working right at https://ci.jenkins-ci.org/job/jenkins_2.0_pipeline/

**Comment by abayer** [comment]
ping @reviewbybees - especially @svanoort and @daniel-beck

**Comment by jtnord** [comment]
:bee:

**Comment by svanoort** [comment]
:bee:

**Pull request merged**
