### PR TITLE
[JENKINS-65237] Bump Groovy from 2.4.12 to 2.4.21

### LINKED ISSUE #1703: Accessing CASC static methods on Jenkins LTS 2.303.1 with JDK11 fails
### Your checklist for this issue

- [X] Jenkins version:  2.303.1
- [X] Plugin version: 1.52
- [X] OS: Docker (on UNIX)

### Description

Hello,
Thanks to the new Jenkins LTS bumped to JDK11, we can't use current classes in our scripts.

When we try to access static method, it fails as such:

```
import io.jenkins.plugins.casc.RootElementConfigurator
def test = RootElementConfigurator.all()
```
Results in:

```
java.lang.IncompatibleClassChangeError: Method 'java.util.List io.jenkins.plugins.casc.RootElementConfigurator.all()' must be InterfaceMethodref constant
	at io.jenkins.plugins.casc.RootElementConfigurator$all.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at Script1.run(Script1.groovy:3)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:585)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:623)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:594)
	at hudson.util.RemotingDiagnostics$Script.call(RemotingDiagnostics.java:146)
	at hudson.util.RemotingDiagnostics$Script.call(RemotingDiagnostics.java:116)
	at hudson.remoting.LocalChannel.call(LocalChannel.java:46)
	at hudson.util.RemotingDiagnostics.executeGroovy(RemotingDiagnostics.java:113)
	at jenkins.model.Jenkins._doScript(Jenkins.java:4638)
	at jenkins.model.Jenkins.doScript(Jenkins.java:4609)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:393)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:405)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:208)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:141)
	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:536)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:694)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:240)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:157)
	at org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:248)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at jenkins.security.ResourceDomainFilter.doFilter(ResourceDomainFilter.java:81)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at hudson.plugins.audit_trail.AuditTrailFilter.doFilter(AuditTrailFilter.java:112)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:129)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at io.jenkins.blueocean.auth.jwt.impl.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:60)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at com.cloudbees.jenkins.support.slowrequest.SlowRequestFilter.doFilter(SlowRequestFilter.java:37)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at com.smartcodeltd.jenkinsci.plugin.assetbundler.filters.LessCSS.doFilter(LessCSS.java:47)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:160)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:155)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:93)
	at jenkins.security.AcegiSecurityExceptionFilter.doFilter(AcegiSecurityExceptionFilter.java:52)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:98)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:53)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:98)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:121)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:98)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:98)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:101)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:92)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:98)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:218)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:98)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:96)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:98)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:62)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:98)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:110)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:170)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:51)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:85)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:36)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I have similar issues with `ConfiguratorRegistry.get()` and so on.

I believe it is because the plugin is built with a JDK8 flavor and that could cause issue because of JDK9+ being more strict with some validation ?

Kind regards,
/lenaing

### PR DESCRIPTION
**Pull request by basil**
See [JENKINS-65237](https://issues.jenkins.io/browse/JENKINS-65237) and [jenkinsci/jenkins#5116 (comment)](https://github.com/jenkinsci/jenkins/pull/5116#issuecomment-744526638). Upgrades Groovy from 2.4.12 to 2.4.21. Changelogs:

- [Groovy 2.4.13](http://groovy-lang.org/changelogs/changelog-2.4.13.html)
- [Groovy 2.4.14](http://groovy-lang.org/changelogs/changelog-2.4.14.html)
- [Groovy 2.4.15](http://groovy-lang.org/changelogs/changelog-2.4.15.html)
- [Groovy 2.4.16](http://groovy-lang.org/changelogs/changelog-2.4.16.html)
- [Groovy 2.4.17](http://groovy-lang.org/changelogs/changelog-2.4.17.html)
- [Groovy 2.4.18](http://groovy-lang.org/changelogs/changelog-2.4.18.html)
- [Groovy 2.4.19](http://groovy-lang.org/changelogs/changelog-2.4.19.html)
- [Groovy 2.4.20](http://groovy-lang.org/changelogs/changelog-2.4.20.html)
- [Groovy 2.4.21](http://groovy-lang.org/changelogs/changelog-2.4.21.html)

The changelogs and https://github.com/apache/groovy/compare/GROOVY_2_4_12...GROOVY_2_4_21 did not appear to contain anything frightening.

### Testing done

- [BOM tests pass](https://ci.jenkins.io/job/Tools/job/bom/job/PR-728/1/)
- [`groovy-sandbox` tests pass](https://github.com/jenkinsci/groovy-sandbox/pull/73)
- [`groovy-cps` tests pass](https://github.com/cloudbees/groovy-cps/pull/115) (ran locally)
- Verified that a Pipeline job started before this PR resumes correctly after this PR

Fixes https://github.com/jenkinsci/configuration-as-code-plugin/issues/1703

### Proposed changelog entries

Upgrade [Groovy](https://groovy-lang.org/) from [2.4.12](http://groovy-lang.org/changelogs/changelog-2.4.12.html) (released on June 21, 2017) to [2.4.21](http://groovy-lang.org/changelogs/changelog-2.4.21.html) (released on November 29, 2020).

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by jglick — APPROVED** [review]
I…guess this is OK. I looked over the changelogs and did not see anything alarming. I scanned through the aggregate diff looking at source files which would be relevant to `groovy-sandbox` and did not see anything alarming there either, though of course there were a lot of detailed changes that I could not follow. @dwnusbaum is probably in the best position to review this.

**Comment by car-roll** [comment]
I was looking into this bump a while back and this is what I had found going through the changelogs. Nothing earth shattering, of course this was just changelogs, not actual code changes.
https://issues.jenkins.io/browse/JENKINS-65237

**Review by dwnusbaum — COMMENTED** [review]
> @dwnusbaum is probably in the best position to review this.

🤷‍♂️ I looked through the changes and everything is probably harmless, but I don't know for sure. There are some bug fixes and subtle changes to method/property selection-related code like https://github.com/apache/groovy/commit/cf51a3fcfc82a38ea7534e950094a13d62f330bd where I think it is pretty hard to tell at a glance whether the issue being fixed is relevant to us without a more detailed investigation, i.e. do `groovy-sandbox` and `groovy-cps` intercept the right thing after the fix, or do they at least behave the same way with both versions of Groovy? In general I am not concerned about functional regressions, but about potential security issues due to behavior changes in things that could not have been tested because they did not work previously.

[GROOVY-8539](https://issues.apache.org/jira/browse/GROOVY-8539) is slightly interesting in that no one could have ever used compound assignment syntax for boolean arrays before the fix, so it has never been tested in `groovy-sandbox` or `groovy-cps`, but I did a quick test locally and everything seems to be intercepted as expected with 2.4.21.

[GROOVY-8428](https://issues.apache.org/jira/browse/GROOVY-8428) appears to be the only new APIs that could be relevant to Jenkins users. I think it would make sense to add them to `generic-whitelist` in `script-security` when `groovy-sandbox` is updated assuming the Jenkins baseline in the plugin is updated as well.

**Comment by basil** [comment]
> do `groovy-sandbox` and `groovy-cps` intercept the right thing after the fix, or do they at least behave the same way with both versions of Groovy?

I ran each test case from apache/groovy@cf51a3f through `org.kohsuke.groovy.sandbox.TheTest#assertIntercept` and `com.cloudbees.groovy.cps.sandbox.SandboxInvokerTest#{evalCpsSandbox,assertIntercept}` and verified that the return values were the same for both versions of Groovy (modulo the bug fix) and that the intercepted calls were the same for both versions of Groovy.

**Comment by basil** [comment]
> I am not blocking this, all I mean is that I cannot give a meaningfully more detailed review beyond what you and Jesse have already done by looking at the commits and changelogs without spending significantly more time looking through everything and doing some exploratory testing. If everyone thinks that we need a detailed review like that, I can ask my employer whether I can spend a couple of days really looking into this, but otherwise all I can say is that the update seems like it would probably be fine but I'm not completely sure.

Thanks for the quick reply! I appreciate the concerns that have been raised, but is it possible we might be [overthinking](https://en.wikipedia.org/wiki/Analysis_paralysis) this? If there are any issues with this upgrade between now and the next LTS, we can always simply revert this PR. We are at the beginning of a new LTS cycle, so my vote would be to merge this PR and monitor Jira for reported regressions. If issues are discovered, we can revert this PR and then go through the detailed process you are describing. What do you think?

**Comment by dwnusbaum** [comment]
> If there are any issues with this upgrade between now and the next LTS, we can always simply revert this PR

Yeah, I am not really worried functional regressions, since I think our test coverage is decent for most typical use cases, if some obscure case breaks there's a decent chance that it's something we don't really want people to be doing anyway, and if some common scenario breaks then reverting is no big deal like you said.

My concern is pretty much solely in relation to introducing potential security vulnerabilities, since I think these are extremely unlikely to affect regular usage and so will go unnoticed unless someone is actively looking for them. I don't see anything obviously concerning here, unlike say a 3.x upgrade where there is lots of new syntax that would obviously need to be tested, but the sandbox escapes we have seen can be pretty subtle, so I just want to make sure that I do not imply that I have thoroughly reviewed every single change in the update looking for sandbox-related issues.

**Review by timja — APPROVED** [review]

**Comment by daniel-beck** [comment]
> the sandbox escapes we have seen can be pretty subtle

I think https://www.jenkins.io/security/advisory/2019-11-21/#SECURITY-1658 or https://www.jenkins.io/security/advisory/2019-09-12/#SECURITY-1538 are examples of that?

**Comment by daniel-beck** [comment]
2.4.14 adds `StringGroovyMethods#startsWithAny` and `StringGroovyMethods#endsWithAny`, do we need to adapt `groovy-cps`?

**Comment by timja** [comment]
> 2.4.14 adds `StringGroovyMethods#startsWithAny` and `StringGroovyMethods#endsWithAny`, do we need to adapt `groovy-cps`?

https://github.com/jenkinsci/jenkins/pull/5939#pullrequestreview-818391176 says that we can add those to the allow list when bumping the version there but it doesn’t block this

**Comment by jglick** [comment]
> we can add those to the allow list

Well, not just the sandbox whitelist, but the list of DGM methods to process—if anyone ever cares. https://github.com/cloudbees/groovy-cps/pull/115#issuecomment-975897086

**Comment by dwnusbaum** [comment]
The new methods don’t have a Closure parameter, so I don’t think there is
any reason to translate them.

**Review by oleg-nenashev — APPROVED** [review]
There is still some risk of setting Pipeline and Script Security on fire again, but the best possible effort was done to prevent regressions. Based on that, I am +1 for merging. Taking lack of blocking negative feedback, I will mark it as ready for merge

We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Pull request merged**
