### PR TITLE
[JENKINS-61441] Move buttons to bottom in a p

### PR DESCRIPTION
**Pull request by jsoref**
See [JENKINS-61441](https://issues.jenkins-ci.org/browse/JENKINS-61441).

### Before
image

### After
image

### Proposed changelog entries

* UpdateSiteWarningsMonitor buttons are moved to bottom of block

### Submitter checklist

- [x] JIRA issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

### CODE REVIEW

**Comment by daniel-beck** [comment]
Could we get before/after screenshots for this UI change? Thanks!

**Comment by jsoref** [comment]
@daniel-beck: done.

**Comment by daniel-beck** [comment]
@jsoref Thanks.

Could you try getting the buttons in the "After" screenshot to be inside the box? It looks weird that they're half outside.

**Comment by jsoref** [comment]
It's a little weird, but I don't really want to spend a lot of time on it.

There is a style (admittedly not the Jenkins style) which includes buttons hanging through the edge of a box. I'd rather someone who cares iterate on it later.

The problem is:
https://github.com/jenkinsci/jenkins/blob/23ab517cb4de3edd80e07b77d332d47eb9049276/core/src/main/resources/jenkins/management/AdministrativeMonitorsDecorator/resources.css#L74
```css
#visible-am-container .am-message .alert form {
    position: relative;
    /* float: right; */
    margin: -6px 0 0 0 !important;
}
```

I can't simply remove that rule because it's being used by:
image

Without that rule, it's rendered as:
image

Note: the logical fix to this is to just move the buttons to the bottom of that thing (where they belong!)

If I make the same changes to that alert as I did to this one, then I can delete the entire rule block and it renders like this:
image
And the UpdateSiteWarningsMonitor renders like this:
image

I'm not sure how to center align the buttons (which would be the naive choice for them).
I'm also not really sure how to right align them (which would match their current behavior).

If you're ok w/ left aligned buttons, I could make the change to the other widget and remove the CSS. But...

**Comment by daniel-beck** [comment]
That's annoying 😦 Thanks for the explanation. Seems like there's just no good solution then without more substantial rework.

Personally I don't think this is a net positive change. The new UI just looks broken to me. I'm not blocking this PR: If others like it, please go ahead and merge.

**Comment by jsoref** [comment]
IMO the current ui looks worse than my fix, the buttons overhang the text whereas normally they appear to expect to have the conceptual equivalent of `vertical-align:middle` -- i.e. the middle of the text should match up w/ the middle of the text in the buttons.

FWIW, in some ways, the GitHub comment UI that I'm using right now is close to what this change does.
image

I could probably add lots of classes and styles to specifically override things for just this one case... but yuck. I'd hope people would be ok w/ this as is, and then someone who really likes Jenkins CSS could iterate over the styling.

**Comment by daniel-beck** [comment]
Trying this PR indicates that the "p" wrapper doesn't actually work. These are siblings in the web inspector.

**Comment by daniel-beck** [comment]
Screenshots from running the PR build; moving the form elements to the old location to get exactly corresponding (in content) "before" screenshots:

### Popup after

Screenshot 2020-03-13 at 01 09 26

### Popup before

Screenshot 2020-03-13 at 01 12 56

### Manage (wide) after

Screenshot 2020-03-13 at 01 13 08

### Manage (wide) before

Screenshot 2020-03-13 at 01 13 27

### Manage (narrow) after

Screenshot 2020-03-13 at 01 15 31

### Manage (narrow) before

Screenshot 2020-03-13 at 01 15 18

**Comment by fqueiruga** [comment]
I have tried to fix the button overflow locally using a clearfix technique but it makes other warnings look weird:

Captura de pantalla 2020-04-02 a las 16 07 49

TBH I don't think there's much we can do here other than "rewrite" the alerts to have a proper place for actions that doesn't involve  using a floating form.

**Comment by alecharp** [comment]
@jsoref should we close this PR or can you work a bit on it to have it merged? Thanks.

**Comment by jsoref** [comment]
@alecharp: I understand it isn't perfect, but I think it's a bit better than what we have today. I'm happy to resolve conflicts, but as @fqueiruga noted, anything else would require quite a bit more work than we have time for.

**Comment by varyvol** [comment]
@timja @uhafner given you usually participate in other UI related PRs/initiatives, could you maybe provide your opinion here? Thanks!

**Comment by uhafner** [comment]
I'm not a fan of changing something from 90% broken to 50% broken. But since we already spent a lot of time in this PR I think we should simply merge it and add this topic to the UI improvements backlog where we can try to find a better solution for such messages.

**Comment by timja** [comment]
Looking at Daniels screenshots from 6 months ago the old versions look better to me

**Comment by alecharp** [comment]
Do we have a plan to fix this PR if we got it merged? I'm afraid that it might end-up in an LTS..

**Comment by alecharp** [comment]
I've added the label because this PR had no activities in a very long time without having a consensus on its content.

**Comment by basil** [comment]
I am closing this PR due to the lack of consensus regarding the proposed solution and due to inactivity. On behalf of the core team, I would like to thank you for your contribution. Even though this PR did not make it across the finish line, it was a promising start! I continue to encourage you (or anyone else who is interested!) to pick up this effort and drive it to completion. Thanks!

**Pull request closed without merging**
