### PR TITLE
Use cards for upstream/downstream projects and permalinks

### PR DESCRIPTION
**Pull request by janfaracik**
This PR is a small design change for upstream/downstream projects and permalinks on jobs. They now use a new `Card` component (see https://jenkins-redesign.vercel.app/project for the inspiration). The intention is to use the card component for all widgets, this is just a start.

**Before**
image

**After**
image

### Testing done

* Upstream/downstream projects and permalinks works as before

### Proposed changelog entries

- Use cards for upstream/downstream projects and permalinks

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@jenkinsci/sig-ux 

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/8305"></a>

### CODE REVIEW

**Comment by uhafner** [comment]
This looks much better as the current "design"! This is a similar approach that we used in the [pull-request-monitoring plugin](https://plugins.jenkins.io/pull-request-monitoring/). We utilized Bootstrap cards though rather than to reinvent the wheel ;-) 

I'm not sure if we should start such a transition yet before we know where to go finally? Wouldn't it make more sense to discuss some requirements or wishes before, like:

- should the widgets be of fixed size or do we have a grid where a widget can fill 1x1, 2x1, or whatever number of cells?
- can we rearrange the widgets?
- can we customize the appearance (order, visibility, size, color)?
- does the layout adapt to different screen sizes automatically

Otherwise we might notice during the transition that it does not work with all those widgets we currently have.

**Comment by janfaracik** [comment]
> This looks much better as the current "design"! This is a similar approach that we used in the [pull-request-monitoring plugin](https://plugins.jenkins.io/pull-request-monitoring/). We utilized Bootstrap cards though rather than to reinvent the wheel ;-)

Thanks!

> I'm not sure if we should start such a transition yet before we know where to go finally? Wouldn't it make more sense to discuss some requirements or wishes before, like:
> 
> ...
>
> Otherwise we might notice during the transition that it does not work with all those widgets we currently have.

Absolutely. There definitely needs to be a discussion around adopting cards for Jenkins, especially identifying edge cases and plugins that haven't been mocked up in the [prototype](https://jenkins-redesign.vercel.app/project/build/375). I think for this PR the cards work better than the existing implementation (the large, blocky titles) and fit in better with the ongoing design work, so I think it'd be good to get this in.

> * should the widgets be of fixed size or do we have a grid where a widget can fill 1x1, 2x1, or whatever number of cells?
> * can we rearrange the widgets?

Widgets should be able to be resized into different configurations. Current thinking is that users will be able to rearrange/show/hide widgets, how granular that may be I'm not sure (e.g. on a system wide level or a project wide level).

> * can we customize the appearance (order, visibility, size, color)?

I think it'd make sense for plugin developers to be able to customise their widgets where necessary, e.g. the console in the prototype uses a black design rather than the default card colour. It'd be nice to have some reusable blocks for developers so that widgets have consistent design/behaviours.

> * does the layout adapt to different screen sizes automatically?

Ideally, although that does introduce a lot of complexity.

**Comment by uhafner** [comment]
If you have only those two cards, it looks good! But for my jobs it looks like:

Bildschirmfoto 2023-08-02 um 14 01 45

Even the width does not match the width of the existing widgets.

I'm not sure if we should start the transition right now without having a plan how to adapt this for all other plugins.

**Review by daniel-beck — CHANGES_REQUESTED** [review]
> The intention is to use the card component for all widgets, this is just a start.

Something like that is never a "small design change" (and I wonder whether needing to update _many_ plugins, probably with core version switch, for something this small).

Pre-emptive review to prevent premature merge with unaddressed feedback.

**Comment by janfaracik** [comment]
Closing, will have a forum post up eventually detailing cards.

**Pull request closed without merging**
