### PR TITLE
Backporting bundled script-security and junit plugin versions for 2.375.1 (#7385)

### PR DESCRIPTION
**Pull request by NotMyFault**
```
Latest core version: jenkins-2.378

Fixed
-----

JENKINS-70083          Minor                   2.379
        Update bundled script-security and junit plugins
        https://issues.jenkins.io/browse/JENKINS-70083
```

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7386"></a>

### CODE REVIEW

**Review by daniel-beck — APPROVED** [review]
Seems a bit premature, but if there's negative feedback on the updates, we can always back this out before release.

**Comment by NotMyFault** [comment]
> we can always back this out before release.

Exactly my thoughts. I'd like to include it to be tested through the RC phase. If there's something wrong, we can always drop this one before the final release.

**Review by basil — COMMENTED** [review]
Have you tested this following the procedure outlined in the *Testing done* section of the original pull request?

**Comment by NotMyFault** [comment]
> Have you tested this following the procedure outlined in the _Testing done_ section of the original pull request?

Yes, thanks to Daniel's step, I could verify the commit too.

**Review by basil — CHANGES_REQUESTED** [review]
Breaks `jenkins.install.LoadDetachedPluginsTest#upgradeFromJenkins1`.

**Comment by NotMyFault** [comment]
Right, I was on the wrong branch.

**Pull request closed without merging**
