### PR TITLE
Replaced own implementation with standard Java function (String.CASE_INSENSITIVE_ORDER)

### PR DESCRIPTION
**Pull request by StefanSpieker**
Replaced own implementation with standard Java function (`String.CASE_INSENSITIVE_ORDER`)
Since the comparator is [widely used](https://github.com/search?p=1&q=org%3Ajenkinsci+CaseInsensitiveComparator&type=Code) I did not touch him. Maybe I'm missing something here, so let's see what the CI has to say ...

### Proposed changelog entries

N/A

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by basil — COMMENTED** [review]
Can we mark `hudson.util.CaseInsensitiveComparator` with `@Deprecated` and add a Javadoc to refer consumers to use `String.CASE_INSENSITIVE_ORDER`? That way, plugins still using this core API will start getting warnings and should hopefully start migrating away. I opened PRs to migrate the open source plugins, but there are also usages in [Operations Center Cluster Operations](https://docs.cloudbees.com/docs/release-notes/latest/plugins/operations-center-clusterops-plugin/) and [Operations Center Context](https://docs.cloudbees.com/docs/release-notes/latest/plugins/operations-center-context-plugin/). Once all usages have been updated, we can then restrict the class. Unfortunately, we can't ever remove it, because it looks like references to it might exist in persistent serialized XML files.

**Comment by daniel-beck** [comment]
> Once all usages have been updated, we can then restrict the class.

We could do so now, restrictions apply at build time, not run time.

**Comment by basil** [comment]
> We could do both at the same time, restrictions apply at build time (and only with a core dependency that has them), not run time.

Indeed, but that means whoever next bumps the core version for Operations Center Cluster Operations and Operations Center Context would be forced to deal with the migration right then and there rather than at their leisure. Call me polite, but I prefer not to put people in that position if I don't have to.

**Comment by StefanSpieker** [comment]
I deprecated the class. I think the Restrictions can be applied after some plugins start to use the java function later on.

**Review by basil — APPROVED** [review]

**Comment by StefanSpieker** [comment]
Fixed the merge conflict.

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Review by johnou — APPROVED** [review]

**Pull request merged**
