### PR TITLE
remove obsolete error message about SECURITY-144

### PR DESCRIPTION
**Pull request by drts01**
JEP-235 removed the ability to whitelist rules in Jenkins 2.326.

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7009"></a>

### CODE REVIEW

**Review by timja — DISMISSED** [review]

**Review by timja — COMMENTED** [review]
probably no harm in leaving this though, reading the content, it explains more details about it, even if you can't disable it anymore

**Comment by daniel-beck** [comment]
While it's true that "SECURITY-144" is no longer a good label, having a URL through which we can provide additional information for an error if needed is generally useful. In this case, docs are useful for anyone upgrading from before 2.326, as well as anyone who encounters this error for the first time.

For that reason, -1 to this change.

**Comment by xsc27** [comment]
Then perhaps a better user experience is to include the pertinent information in the error message, i.e.
> The Agent → Controller Access Control system is always enabled since Jenkins 2.326 as part of JEP-235.

Then the user can look up JEP-235 if so desired.

**Comment by daniel-beck** [comment]
We generally prefer URLs over lots of inline details so we can update the content later. The note on being able to remove a2c access control will be gone soon enough from the site, once the versions are old enough. Note that the docs link to https://www.jenkins.io/doc/book/security/controller-isolation/jep-235/ which provides useful information for anyone encountering this after upgrading.

**Comment by xsc27** [comment]
Having a link makes sense. Also, not having the relevant information up from and digging around in docs to learn what was happening was not a great user experience.

**Comment by daniel-beck** [comment]
Could you provide a suggestion what it would take to address

> not having the relevant information up from and digging around in docs to learn what was happening was not a great user experience

?

I assume you needed to know something that's not on the linked web page? What is missing there? Or is it something else entirely?

This PR only removes a reference to more information, so it's not like it currently addresses the concern you bring up.

**Comment by basil** [comment]
@xsc27 do you have any concrete ideas on how to improve the documentation to address your concerns? If not, I plan to close this PR in about a week.

**Comment by basil** [comment]
> @xsc27 do you have any concrete ideas on how to improve the documentation to address your concerns? If not, I plan to close this PR in about a week.

Closing as promised. @xsc27 Thanks for your contribution, and let us know if you have any further suggestions about how to improve the documentation around this subsystem.

**Pull request closed without merging**
