### PR TITLE
[FIXED JENKINS-28419] - JenkinsLocationConfiguration::adminAddress can be reset

### PR DESCRIPTION
**Pull request by oleg-nenashev**
https://issues.jenkins-ci.org/browse/JENKINS-28419

This pull request resolves a potential NPE, which may happen when a user tries to reset the admin e-mail. Changes:
- Annotation of <code>JenkinsLocationConfiguration</code> methods
- Some unit tests
- Fix of <code> setAdminAddress()</code> behavior

### CODE REVIEW

**Comment by tfennelly** [comment]
@oleg-nenashev my understanding/assumption is that wrapping the email address in quotes allows the use of spaces (and or some other illegal chars). Wtf would someone do that... no idea. If that's the case, and we remove them, then how are we guaranteeing that our use of that address in future is not going to be broken? Maybe we can't really guarantee it and this is the lesser of two evils?

**Comment by oleg-nenashev** [comment]
@tfennelly 
In Jenkins code we commonly do not validate e-mails completely (even it's being passed without quotes). The only approach would be to use an external lib. http://en.wikipedia.org/wiki/Email_address provides many corner-cases, which I would not like to handle on my own. E.g. <code>" "@foo.bar</code> is a valid one.

Anyway, I think it's out of the scope of this PR (no logic changes in trimming).

**Comment by jtnord** [comment]
:+1: - although I generally would have preferred the unrelated `CheckForNull` annotations to be in a separate commit

**Comment by oleg-nenashev** [comment]
@jtnord 
Annotations come in a different commit: https://github.com/oleg-nenashev/jenkins/commit/1cd30ac665013418fb580652e773ff1dd2ddb745 (even without the issue reference)

**Comment by jtnord** [comment]
@oleg-nenashev s/commit/PR/

**Comment by oleg-nenashev** [comment]
OK, I'll try to submit different PRs next time.
Got an additional +1 from @jhoblitt => merging the PR

**Comment by jhoblitt** [comment]
:+1: I've bumped into the NPE working on puppet automation.  Major bonus points IMHO for adding test coverage for a class which had none -- something else I discovered when looking at fixing this myself.

**Comment by oleg-nenashev** [comment]
@jhoblitt Yes, at Jenkins we have some technical debt in the scope of unit/integration tests and docs. We commonly require the good implementation in the new functionality, but the legacy code stills legacy. It is being slowly updated when we experience issues in it.

**Pull request merged**
