### PR TITLE
[FIXED JENKINS-36775] - No longer hard-code the icon for the executor panel

### PR DESCRIPTION
**Pull request by SebastienGllmt**
[JENKINS-36775](https://issues.jenkins-ci.org/browse/JENKINS-36775)

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Looks reasonable :+1: 
Maybe https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Computer.java#L730 needs some Javadoc, which would help API users to implement a proper online/offline behavior in their plugins

**Comment by SebastienGllmt** [comment]
@oleg-nenashev Does this look good for documentation?

**Comment by oleg-nenashev** [comment]
@SebastienGllmt Thanks for adding Javadoc! The current text looks good to me. Would be useful to explicitly say that methods provide different icons of online and offline states, and that it's recommended to follow such approach in all implementations.

**Comment by oleg-nenashev** [comment]
re-:+1:
I'll merge it once the build passes

**Comment by SebastienGllmt** [comment]
Do you think it's worth mentioning the naming convention of these icons in the Javadocs for these? I noticed that:
for getIcon, the name should end with _anime if it is an animated gif 
for getIconClassName the name is dash-separated, the class name should start with icon- and it should end with -anime if it is an animated gif
As far as I can tell, the only place this is partially documented is in the static block inside IconSet. Maybe this should be put elsewhere such as the constructor to Icon? It doesn't feel write adding it to the comment block in Computer since these conventions hold for all icons.

**Comment by oleg-nenashev** [comment]
@SebastienGllmt Yes, such additional information would be very useful (CC @tfennelly, who was working with icon engine last time). I'm not exactly sure what is the current naming convention, but any streamlining in this and other areas would be appreciated.

I consider improvement of Icon classes as a change, which can be done in a separate pull request. IMHO JENKINS-36775 is ready do be merged. @SebastienGllmt do you agree?

**Comment by daniel-beck** [comment]
:+1:

**Comment by SebastienGllmt** [comment]
:+1: for merging this. Any change in the documentation for the Icon naming convention should be made in a different pull request as the issue associated with this pull request is fixed by the associated commits

**Comment by oleg-nenashev** [comment]
@SebastienGllmt Thanks! Merging the PR

**Pull request merged**
