### PR TITLE
Remove bundled cvs plugin

### PR DESCRIPTION
**Pull request by daniel-beck**
Similar to #4242 this will remove `cvs` plugin from the list of bundled plugins.

This PR is an alternative to #5096. In trying to fix the test failure I found I needed to start bundling `jsch`, `ssh-credentials`, `credentials`, which seemed a bit much. So I explored this alternative.

Different from #4242, we currently publish plugins with implied dependencies on `cvs`:

* https://plugins.jenkins.io/googleanalytics/ depends on 1.323
* https://plugins.jenkins.io/SSSCM/ depends on 1.323
* https://plugins.jenkins.io/script-realm/ depends on 1.330

None of them were released in the last 8 years, and installs are in the low 100s. None of them appear to use CVS plugin functionality.

If plugins depending on Hudson 1.340 or earlier are installed through the plugin manager, the newest version of `cvs` will be downloaded and installed (plus its dependencies). With manually managed  plugins, Jenkins will simply not install a bundled `cvs` on startup if one of these plugins is installed; users will need to install it themselves.

### Proposed changelog entries

* Stop bundling CVS plugin. Jenkins will no longer automatically install CVS plugin on startup if a plugin depending on Jenkins (then Hudson) 1.340 or earlier is discovered. If you use such a plugin that also relies on the functionality provided by CVS plugin and manage plugins outside Jenkins' plugin manager, you will now need to ensure yourself that a recent release of CVS plugin is installed. Jenkins will attempt to load such plugins but may fail at any time during startup or afterwards with `ClassNotFoundException` or similar.

### Proposed upgrade guidelines

See above.

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [x] There are at least 2 approvals for the pull request and no outstanding requests for change
- [x] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [x] Proper changelog labels are set so that the changelog can be generated automatically
- [x] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by StefanSpieker — APPROVED** [review]

**Review by jvz — APPROVED** [review]

**Review by MarkEWaite — APPROVED** [review]

**Comment by MarkEWaite** [comment]
I ran the war file generated by the CI job, confirmed that it did not include the CVS plugin initially, did not install the CVS plugin through the "recommended plugins", and did not install the CVS plugin when I used the plugin manager to install Blue Ocean.

**Comment by daniel-beck** [comment]
@MarkEWaite The interesting use case is shut Jenkins down after going through setup without installing anything, put `SSSCM.hpi` in `$JENKINS_HOME/plugins/`, then start Jenkins.

Before: CVS gets installed.
After: CVS does not get installed.

I thought this was clear from the changelog instructions, please update so it makes sense to you.

**Comment by MarkEWaite** [comment]
@daniel-beck I was less concerned about the cases that you specifically cited than about confirming the more trivial but widespread cases.  Your description is excellent and will be great in the changelog.

**Review by oleg-nenashev — APPROVED** [review]
> In trying to fix the test failure I found I needed to start bundling jsch, ssh-credentials, credentials, which seemed a bit much

TBH I would not mind if these plugins were bundled, but removal of CVS looks totally reasonable. I double-checked the dependency analysis, and it looks good.

**Comment by MarkEWaite** [comment]
This PR is now ready for merge.  We will merge it after approximately 24 hours if there is no negative feedback.

Based on the testing performed by different reviewers, we may want to consider merging before the 24 hour period has elapsed so that it can be included in Jenkins 2.270 that will release in about 12 hours.

**Review by timja — APPROVED** [review]

**Review by res0nance — APPROVED** [review]

**Comment by jglick** [comment]
Did you intentionally leave https://github.com/jenkinsci/jenkins/blob/ec51284c2c0fa032c7f54565b3ff47c178df0de9/core/src/main/resources/jenkins/split-plugins.txt#L11?

**Comment by daniel-beck** [comment]
@jglick Isn't that what puts the plugin on the classpath as an implied dependency? Removing that line would then mean dependent plugins break even if `cvs` is installed.

**Comment by jglick** [comment]
OK, just checking that this was deliberate.

**Pull request merged**
