### PR TITLE
Remove useless reflection and generally clean up in createSymlinkJava7()

### PR DESCRIPTION
**Pull request by maxdietrich**

### CODE REVIEW

**Comment by dietmax** [comment]
Seeing that checks failed, was that whole reflection in place to secure downward support for Java 5?

**Comment by Vlatombe** [comment]
I guess the animal sniffer check for java 6 can now be removed, now that core is targetting officially java 7

**Comment by KostyaSha** [comment]
@Vlatombe please follow discussions. Jenkins code level is keeping on java6 level for some time.

**Comment by jglick** [comment]
Right, until otherwise announced we are retaining compatibility with the Java 6 Platform APIs, to make it easy to revert the decision to require Java 7 if there is significant pushback. Assuming there is not, this could be reopened in the future (and there is plenty of other code which could use `java.nio.file` as well).

**Pull request closed without merging**
