### PR TITLE
[JENKINS-69145] bouncing build number element on mouse hover

### PR DESCRIPTION
**Pull request by frankie139506**
See [JENKINS-69145](https://issues.jenkins.io/browse/JENKINS-69145).

### Proposed changelog entries

* Fix bouncing build number element on mouse hover.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] (If applicable) Jira issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [X] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")` if applicable.
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/6928"></a>

### CODE REVIEW

**Comment by daniel-beck** [comment]
Would this also take care of [JENKINS-68160](https://issues.jenkins.io/browse/JENKINS-68160)?

**Comment by NotMyFault** [comment]
> Would this also take care of [JENKINS-68160](https://issues.jenkins.io/browse/JENKINS-68160)?

Looks like it, left is weekly.ci, right is this PR build:

https://user-images.githubusercontent.com/13383509/181840862-3b8540b4-413e-4436-8573-cdf1ff8d518d.mp4

But it also looks like James' issue is a duplicate of yours 🤔

**Comment by frankie139506** [comment]
> Would this also take care of [JENKINS-68160](https://issues.jenkins.io/browse/JENKINS-68160)?

Yes, it also fix JENKINS-68160's problem.

**Review by daniel-beck — DISMISSED** [review]
With this change it is no longer possible to access the context menu dropdown of model-links. The hover state collapses before I can move the pointer to the chevron.

https://user-images.githubusercontent.com/1831569/181893979-8dc0e055-e135-43fd-8fd0-a08f928cfc83.mov

**Comment by frankie139506** [comment]
> With this change it is no longer possible to access the context menu dropdown of model-links. The hover state collapses before I can move the pointer to the chevron.
> 
>  Screen.Recording.2022-07-30.at.10.18.27.mov

@daniel-beck In my test, it is normal, This is my demo.
gif2

**Comment by daniel-beck** [comment]
Move your mouse pointer more slowly. I found it sometimes works when moving the pointer fairly quickly.

**Comment by frankie139506** [comment]
> Move your mouse pointer more slowly. I found it sometimes works when moving the pointer fairly quickly.
> 
> Otherwise, I used Firefox 103 and most pages have some level of zoom >100%, probably was the case here too.

Thanks for your suggestion. I have make some change, please take a look.
gif2

**Comment by daniel-beck** [comment]
The latest state of this no longer causes the issue when slowly moving the mouse pointer 👍 

Not approving as of now as I've only inconsistently been able to reproduce JENKINS-68160. Requesting @jtnord as the reporter of JENKINS-69145.

**Comment by jtnord** [comment]
Can not build locally, `master` is fine... 

```
[INFO] Running 'yarn lint:ci' in C:\workarea\source\github\jenkinsci\jenkins\war
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Jenkins main module 2.362-SNAPSHOT:
[INFO]
[INFO] Jenkins main module ................................ SUCCESS [ 34.097 s]
[INFO] Jenkins BOM ........................................ SUCCESS [  0.168 s]
[INFO] Internal SPI for WebSocket ......................... SUCCESS [  9.220 s]
[INFO] Jetty 9 implementation for WebSocket ............... SUCCESS [  5.306 s]
[INFO] Jenkins cli ........................................ SUCCESS [ 21.373 s]
[INFO] Jenkins core ....................................... SUCCESS [02:11 min]
[INFO] Jenkins war ........................................ FAILURE [01:07 min]
[INFO] Tests for Jenkins core ............................. SKIPPED
[INFO] Jenkins coverage ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:47 min
[INFO] Finished at: 2022-08-01T11:57:18+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:yarn (yarn lint) on project jenkins-war: Failed to run task: 'yarn lint:ci' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :jenkins-war
```

**Comment by jtnord** [comment]
I can verify that JENKINS-69145 is indeed fixed.

**Review by jtnord — APPROVED** [review]

**Comment by frankie139506** [comment]
Could I get a reviewer for this PR?

**Review by daniel-beck — COMMENTED** [review]
I was able to reproduce the problem in JENKINS-69145 on weekly.ci.j.io and this PR appears to address it.

Ideally @janfaracik could tell us what the purpose of `pointer-events: all` was here.

**Review by daniel-beck — APPROVED** [review]
(Misclicked in the previous review.)

**Review by NotMyFault — APPROVED** [review]

**Comment by NotMyFault** [comment]
@janfaracik Do you mind taking a look and could clarify Daniel's open concerns?

**Review by basil — APPROVED** [review]
This PR is now ready for merge. We will merge it after approximately 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process. Thanks!

**Comment by basil** [comment]
Manually verified as of commit 93f69b292e

**Pull request merged**
