### PR TITLE
WIP [JENKINS-32503] Update commons-beanutils to 1.9.3

### PR DESCRIPTION
**Pull request by KostyaSha**
Testing PR build, seems it will fail because of stapler
https://issues.jenkins-ci.org/browse/JENKINS-32503
https://github.com/stapler/stapler/pull/81

---

This change is [Reviewable](https://reviewable.io/reviews/jenkinsci/jenkins/2588)

### CODE REVIEW

**Comment by KostyaSha** [comment]
@abayer why you aborted my PR build?

**Comment by KostyaSha** [comment]
@kzantow what your PR status mean?

**Comment by oleg-nenashev** [comment]
Retriggering the build.
@kzantow's status only means that his instance continues polluting the Jenkins github repo :(

**Comment by KostyaSha** [comment]
@oleg-nenashev build is ok with new version, real changes need to be done on stapler side that has already failing test with version used in core.

**Comment by oleg-nenashev** [comment]
```
12:09:59 Flaked tests: 
12:09:59 jenkins.model.StartupTest.noWarnings(jenkins.model.StartupTest)
12:09:59   Run 1: StartupTest.noWarnings:45 expected:<[]> but was:<[Failed Loading plugin Maven Integration plugin v2.14 (maven-plugin)]>
12:09:59   Run 2: PASS
12:09:59 
12:09:59 
```

Seems we still have an issue with the master branch

This PR is unlikely related, 👍

**Comment by oleg-nenashev** [comment]
Ready to merge since nobody votes against

**Comment by oleg-nenashev** [comment]
From what I see there is no need in merge before Stapler patch gets integrated, right? CC @KostyaSha

**Comment by daniel-beck** [comment]
What's the nature of Work In Progress here? Is this actually supposed to get merged?

**Comment by oleg-nenashev** [comment]
Retriggering the build

**Comment by daniel-beck** [comment]
AFAIR @KostyaSha explained to me this is not supposed to get merged, at least for now. Please correct me if I got this wrong.

**Comment by KostyaSha** [comment]
wtf is this this PR builders?

**Comment by KostyaSha** [comment]
@stephenc how trigger PR build?

**Comment by stephenc** [comment]
@KostyaSha you just have to be patient, the rate limit means that it can take a minute or two to see the close and re-open, but it *will* see the close and reopen

**Comment by daniel-beck** [comment]
@KostyaSha Could you please respond to my previous comments? It's unclear to me whether this is supposed to be merged ever.

**Comment by alecharp** [comment]
I've been trying to upgrade the library in Jenkins today. A brilliant failure. The project, for its `2.0.0` changed its GAV and reflected the ArtifactId change to the packages of the classes, moving from `org.apache.commons.beanutils.*` to `org.apache.commons.beanutils2`. I'm all for not sticking to very old version, but this change in commons-beanutils project will provide us a lot of work. I stopped trying to use the new details after checkouting stapler/stapler project and it was not the end of it..

**Comment by alecharp** [comment]
@KostyaSha would you like to continue investigating on this topic or should we close this PR?

**Pull request closed without merging**
