### PR TITLE
Update manage_da.properties, fix typo

### PR DESCRIPTION
**Pull request by RandomSort**
There was a simple typo. Andministrer is not a word in danish, while administrer is.

### Proposed changelog entries

* Entry 1: Typo, fix in Danish localization

### CODE REVIEW

**Review by daniel-beck — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]

**Comment by daniel-beck** [comment]
No need to changelog something this simple.

**Comment by daniel-beck** [comment]
@RandomSort Thanks for the fix! Not sure what the current state of the Danish translation is, but I'd be happy to show you our tooling if you're interested in improving it.

**Comment by RandomSort** [comment]
Hi @daniel-beck. 
The danish translation is quite poor. I'm not sure whether it is a bootstrap problem.
ie. it is bad because no one uses it, or no one uses it because it is bad.
I don't know if we have usage statistics most Jenkins using danes that I know switches to english as fast as possible.
Are there any usage statistics?

Either I'd be happy to check out the tooling to see if I can improve it a bit :)

**Comment by daniel-beck** [comment]
@RandomSort To clarify, the tooling is functional, I meant improving the Danish translation -- I did a major update for German (https://github.com/jenkinsci/jenkins/pull/2777) several months back, but that's the only language I speak.

Feel free to poke me on IRC (danielbeck in #jenkins) and I'll explain how everything works.

**Pull request merged**
