### PR TITLE
 [JENKINS-66658] Fix french encoding (Hacktoberfest)

### PR DESCRIPTION
**Pull request by alauregaillard**
See [JENKINS-66658](https://issues.jenkins-ci.org/browse/JENKINS-66658).

Character encoding for French accents has to be html.

FixAccents

### Proposed changelog entries

* Entry 1: Fix character encoding for French accents.
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [X] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by aHenryJard — APPROVED** [review]
Thank you very much for this one, well spotted ! I have opened the current inline help in French it's not readable oO

**Review by Vlatombe — APPROVED** [review]

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Review by Wadeck — APPROVED** [review]
Thanks for the changes :) 

💡 If you look at the `_de`, `_it`, you will tons of accents, directly in text. There is no need to encode them in HTML, it's just the Unicode that is not supported.

**Comment by Wadeck** [comment]
<details>

<summary>"Proof" 💡 </summary>

Screenshot_2021-10-13_114103_001

</details>

**Review by oleg-nenashev — COMMENTED** [review]
LGTM, thank you!

**Pull request merged**
