### PR TITLE
CommandLauncherTest is flaky

### PR DESCRIPTION
**Pull request by jglick**
Originated in #1688. Frequent source of CI test failures.

@reviewbybees and @olivergondza

### CODE REVIEW

**Comment by recena** [comment]
:bee: and :+1:

**Comment by oleg-nenashev** [comment]
:bee:

**Comment by jglick** [comment]
@reviewbybees done

**Comment by KostyaSha** [comment]
:+1:

**Comment by olivergondza** [comment]
I do not understand the cause causing the flakiness but do not object against this.

**Comment by jglick** [comment]
Could be backported to `stable-1.625` if this failure is seen there.

**Pull request merged**
