### PR TITLE
[JENKINS-70805] Remove `!important` from styles in `<pre>`

### PR DESCRIPTION
**Pull request by uhafner**
Jenkins should allow plugins to change the fonts in themes or plugins that render pre-formatted text. I'm not sure why the `important!` suffix has been added here but the console view still renders fine when this suffix will be removed.

For more details please see [JENKINS-70805](https://issues.jenkins.io/browse/JENKINS-70805).

Console View Before (Left), After (Right) [Both are identical]:

Bildschirmfoto 2023-04-12 um 20 34 02

Source Code View with Prism Plugin Before (Left), After (Right) [Right is fixed, left is broken]:

Bildschirmfoto 2023-04-12 um 20 33 44

### Testing done

Manual testing by inspecting the console log view and the source code view of the warnings plugin.

### Proposed changelog entries

- Align source code text and line numbers in views that render source code with the Prism plugin.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] The Jira issue, if it exists, is well-described.
- [X] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [X] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.

### Desired reviewers

@timja 
@janfaracik 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7836"></a>

### CODE REVIEW

**Comment by daniel-beck** [comment]
Originally added in @janfaracik's https://github.com/jenkinsci/jenkins/pull/6259 without explanation.

**Comment by janfaracik** [comment]
Looking good. Only regression that I've found is the CodeMirror textarea on Script Console no longer has the correct font.

**Before this change**
image

**After this change**
image

I haven't tried but looks like that could be fixed by applying the properties to `.cm-variable` in `codemirror.less`, e.g. 

```
  .cm-variable {
    color: var(--pre-color);
    font-family: var(--font-family-mono);
    font-weight: 500;
    line-height: 1.66;
  }
```

**Review by NotMyFault — APPROVED** [review]
Thanks!

**Review by timja — APPROVED** [review]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Pull request merged**
