### PR TITLE
[JENKINS-71890] Model links in build history views and administrative monitors no longer work

### PR DESCRIPTION
**Pull request by benebsiny**
See [JENKINS-71890](https://issues.jenkins.io/browse/JENKINS-71890).

I followed [here](https://github.com/jenkinsci/jenkins/blob/74610e024a6b8fd8feccdc51b8f7741aa6c30e3b/war/src/main/js/components/dropdowns/jumplists.js#L15) to make changes.

screen

### Proposed changelog entries

- Restore context menus of model links in build history views and in administrative monitors. (regression in 2.402).

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [X] The Jira issue, if it exists, is well-described.
- [X] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/8485"></a>

### CODE REVIEW

**Review by mawinter69 — CHANGES_REQUESTED** [review]
I'm wondering why it is necessary to repeat the code from jumplists.js.
I think the problem is that the jumplist is applied after the page was loaded, but the table is generated with javascript after jumplist#generateJumplistAccessors was called.
It is probably better to modify the jumplists.js to use a behaviorShim#specify instead of a queryselector. After the rows are created the behaviour is already applied.

PS: a similar change would be required the links created in lines 28 and 46

**Comment by mawinter69** [comment]
This does the same with just changing a single line and it fixes all potential places where a model link is created after the page was loaded.
```
--- a/war/src/main/js/components/dropdowns/jumplists.js
+++ b/war/src/main/js/components/dropdowns/jumplists.js
@@ -11,7 +11,7 @@ function init() {
  * Appends a ⌄ button at the end of links which support jump lists
  */
 function generateJumplistAccessors() {
-  document.querySelectorAll("A.model-link").forEach((link) => {
+  behaviorShim.specify("A.model-link", "-jumplist-", 999, (link) => {
     const isFirefox = navigator.userAgent.indexOf("Firefox") !== -1;
     // Firefox adds unwanted lines when copying buttons in text, so use a span instead
     const dropdownChevron = document.createElement(

```

**Comment by benebsiny** [comment]
@mawinter69 yes, this looks more reasonable, thanks for your feedback!

**Comment by mawinter69** [comment]
looks good, fixes the model links in Build history of views and also the links on the trend page of jobs

**Review by mawinter69 — APPROVED** [review]

**Comment by mawinter69** [comment]
This also fixes [JENKINS-72052](https://issues.jenkins.io/browse/JENKINS-72052)

**Review by timja — APPROVED** [review]
nice

**Comment by timja** [comment]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Review by daniel-beck — APPROVED** [review]

**Pull request merged**
