### PR TITLE
JENKINS-67953 Unavailable plugin label is not themeable

### PR DESCRIPTION
**Pull request by strangelookingnerd**
See [JENKINS-67953](https://issues.jenkins.io/browse/JENKINS-67953).

For some reason the theming was removed. This PR reintroduces it and is required for https://github.com/jenkinsci/dark-theme-plugin/issues/168

### Proposed changelog entries

Make "Unavailable" label in plugin manager theme-able

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by daniel-beck** [comment]
> theming was removed

To clarify, this worked before? When did it work, and when did it stop working?

**Comment by strangelookingnerd** [comment]
> > theming was removed
> 
> To clarify, this worked before? When did it work, and when did it stop working?

Partially, yes.
First only the "background" was made themeable (https://github.com/jenkinsci/jenkins/pull/4899)
After that the rework of the Plugin Manager UI happened (I think in https://github.com/jenkinsci/jenkins/pull/45916 - not sure tho) This removed the CSS definitions required for the themes to work.
Now the background and the color of the label can be themed (this PR)

**Comment by timja** [comment]
Can you please include screenshots for any UI changes?

Before / after.

With both light and dark theme.

**Comment by strangelookingnerd** [comment]
See comparison:

* Before 
before_light
before_dark

* After
after_light
after_dark

**Review by alecharp — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Pull request merged**
