### PR TITLE
Remove `sorcerer`

### PR DESCRIPTION
**Pull request by basil**
Whatever this thing is or was, I doubt we need it anymore.

### Proposed changelog entries

N/A

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]
Was a source code navigation tool of some sort.

https://github.com/kohsuke/sorcerer

**Review by StefanSpieker — APPROVED** [review]

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by daniel-beck** [comment]
@jglick recently mentioned it would be nice to resurrect sorcerer.

**Comment by basil** [comment]
> @jglick recently mentioned it would be nice to resurrect sorcerer. (Nonblocking, just pinging for awareness.)

Probably better off using [OpenGrok](https://github.com/oracle/opengrok) at this point.

**Comment by jglick** [comment]
> Probably better off using [OpenGrok](https://github.com/oracle/opengrok) at this point.

No. OpenGrok is basically text search AFAIK. While it may use a Java _lexer_, it has no idea what the symbols mean. Sorcerer actually embeds javac, so if it comes across a call to a `reset` method on some object, it actually knows which of the 500 methods with that name is being called. Something critically important when it comes to a huge source base like Jenkins.

Anyway, this PR is probably fine; I doubt Sorcerer still works.

**Comment by jglick** [comment]
https://github.com/github/feedback/discussions/8593

**Pull request merged**
