### PR TITLE
[JENKINS-62347] Agent2Master Security localization files contain "slave" references

### PR DESCRIPTION
**Pull request by benebsiny**
See [JENKINS-62347](https://issues.jenkins-ci.org/browse/JENKINS-62347).

Replace "slave" in nl, pt_BR, ru, tr, zh_TW languages.

* **nl** (Netherlands)
  * `slaafnode` -> `agent node`
* **pt_BR** (Brazil)
  * `slave` -> `agent`
* **ru** (Russia)
  * `подчиненном узле` -> `узлов агента`
* **tr** (Turkey)
  * `slave` -> `agent`
* **zh_TW** (Taiwan)
  * `slave` -> `agent`

### Proposed changelog entries

* Entry 1: Replace texts that references to "slave" with "agent" for nl, pt_BR, ru, tr, zh_TW

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] (If applicable) Jira issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [X] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
Please avoid doing changes for languages you are not familiar with. At least changes in Russian are not correct

**Comment by MarkEWaite** [comment]
We generally have preferred that the localizations be reviewed by a fluent speaker of the language in order to have the best chances of correct modifications to localization.  Can you share the list of those languages where you are fluent?

@getJv may be willing to review the Brazilian Portugese translation.  I believe that @aytuncbeken may be fluent in Turkish.  

Since @oleg-nenashev has reviewed the Russian and noted that they are incorrect, it may be best to restart the pull request to contain only those languages you speak fluently.

**Comment by benebsiny** [comment]
@MarkEWaite I understood, I'll try to restart a new one.

**Comment by getJv** [comment]
Yes count with me, agent in Pt-BR is agente.

**Comment by MarkEWaite** [comment]
Thanks @getJv .  Would you be willing to submit a separate pull request that corrects the Brazilian Portugese translations to use `agente` instead of the current word for `slave`?

**Comment by MarkEWaite** [comment]
Closing this pull request since @benebsiny has provided #4984 for the Traditional Chinese translation.

**Comment by aytuncbeken** [comment]
Hi @MarkEWaite I can help for Turkish language.

**Comment by MarkEWaite** [comment]
Thanks @aytuncbeken !  We'd love to have a separate pull request to update the Turkish translation with the preferred terminology.

**Pull request closed without merging**
