### PR TITLE
[JENKINS-67063] `readFromTar` to use `getCanonicalFile` only inside controller

### PR DESCRIPTION
**Pull request by jglick**
See [JENKINS-67063](https://issues.jenkins-ci.org/browse/JENKINS-67063).

Clumsy, and needs a regression test, but seems to work at least in the scenario provided in Jira (which I further simplified for local testing). Reverting https://github.com/jenkins-infra/pipeline-library/pull/237 would let us verify in context.

Reverts a small piece of https://github.com/jenkinsci/jenkins/pull/5880/commits/63cde2daadc705edf086f2213b48c8c547f98358 when running inside an agent JVM, where we do not care about this protection.

### Proposed changelog entries

* https://www.jenkins.io/security/advisory/2021-11-04/ includes a change hardening symlink handling for agent-to-controller file operations. This inadvertently broke certain usage patterns, such as `unstash` of symlinks into a workspace.

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by timja — COMMENTED** [review]
I've tested this locally and can't reproduce the issue anymore, thanks!

2 questions:
1. Do you plan to add a test for this here?
2. Should we cut a new LTS version with this?

**Comment by jglick** [comment]
> Do you plan to add a test for this here?

I think @daniel-beck is trying to come up with one.

> Should we cut a new LTS version with this?

Probably.

**Comment by timja** [comment]
> Probably. I marked it an lts-candidate.

That could also be for the next LTS line which this will need back porting into.

**Comment by jglick** [comment]
Can probably be closed in favor of #5900 @daniel-beck?

**Comment by daniel-beck** [comment]
If we like that one better, sure.

**Pull request closed without merging**
