### PR TITLE
Fix tests on Windows

### PR DESCRIPTION
**Pull request by daniel-beck**
Re-run of #2745 from a committer in the hopes that this PR picks up the Windows test in the Jenkinsfile.

### CODE REVIEW

**Comment by daniel-beck** [comment]
Looks like I'm trusted, so this can be merged. Notably, should not be squashed despite the bloated history, otherwise I think @slide is no longer attributed.

**Review by oleg-nenashev — APPROVED** [review]
:shipit:

**Comment by slide** [comment]
I'm not worried about being attributed. Feel free to squash.

**Comment by jglick** [comment]
@slide seems like this caused a test regression in `master`

```
java.io.IOException: Unable to delete file: C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.8\Downloads\0\workspace\Core_jenkins_master-CZB5BLBJFXZE2BKR63DSXQKXRZJAOWBX73QP55GU5KMX7AHAF6CQ\core\target\junit5522992408021127005\dir\x.log
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2279)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
	at hudson.util.io.RewindableRotatingFileOutputStreamTest.deletedFolder(RewindableRotatingFileOutputStreamTest.java:52)
```

**Comment by slide** [comment]
@jglick the test is invalid on windows, I am created #2774

**Pull request merged**
