### PR TITLE
Fix minor issues in localization files (escaping, incomplete entries, etc.)

### PR DESCRIPTION
**Pull request by darxriggs**
Multiple small issues have been fixed - mainly:
- trailing spaces ` ` after backslash `\` for multi-line entries
- missing backslash `\` for multi-line entries
- missing escaping of the key/value separator colon `:` when used literally
- missing key/value separator `=`
- duplicate entries
- extra content without a key

### CODE REVIEW

**Review by jvz — APPROVED** [review]

**Comment by halkeye** [comment]
What happened to the pull reqest template? Can you populate it again?

https://github.com/jenkinsci/jenkins/blob/master/.github/PULL_REQUEST_TEMPLATE.md

Mostly so the changelog entry exists

**Comment by oleg-nenashev** [comment]
> What happened to the pull reqest template? Can you populate it again? Mostly so the changelog entry exists

Good pull request title should be enough in this case FYI. https://github.com/jenkinsci/jenkins-core-changelog-generator includes both PR title and suggested changelog entries. 

If we classify it as a bug, we need a user-friendly changelog entry tho

**Comment by halkeye** [comment]
yea, i was debating between bug and internal/no changelog
but since it does update a few translations, it would be user facing would it?

**Review by res0nance — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
> but since it does update a few translations, it would be user facing would it?

It is fine with me, it just needs a user-friendly changelog then

**Review by oleg-nenashev — APPROVED** [review]
I tried to write something for the changelog, please review @jsoref 
I plan to merge it tomorrow if no negative feedback

**Comment by jsoref** [comment]
@oleg-nenashev: I suspect:

> trailing spaces ` `after backslash `\` for multi-line entries

should be:
> trailing spaces (` `) after backslash (`\`) for multi-line entries

Beyond that, don't you want a `l10n:` or similar prefix so that the right audience is able to read/skip?

**Pull request merged**
