### PR TITLE
Add @Deprecated annotations to things documented as @deprecated.

### PR DESCRIPTION
**Pull request by deadmoose**

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
It's a good change. It's not necessary, because modern IDEs and static code analyzers easily handle Javadoc notations as well. BTW, we could merge this PR to follow standards and address other use-cases (e.g. runtime).

**Comment by jtnord** [comment]
it reduces a massive amount of lint warnings, so even if not necessary "it's a good thing"<sup>:tm:</sup>

**Comment by deadmoose** [comment]
In particular, I ran http://errorprone.info and hit this and two other things (one PR sent, another on my list), so really cleaning this up opens the door for protecting against a bunch of other pitfalls by turning on that suite of static analyzers. `</pie in the sky>`

**Comment by oleg-nenashev** [comment]
Lets give some time to respond.

**Comment by jglick** [comment]
I wonder if we could pass `-Werror -Xlint:<something>` to javac so that we enforce this fix.

**Pull request merged**
