### PR TITLE
Adds Polish translations

### PR DESCRIPTION
**Pull request by damianszczepanik**
No JIRA, not deemed needed.

### Proposed changelog entries

* SetupWizard translation: polish translation was improved. 
* Error Panel: Developers can now also internationalize the title in the "error panel"  

### Submitter checklist

- ~JIRA issue is well described~
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers
@batmat

### CODE REVIEW

**Comment by batmat** [comment]
Given Damian's track record (https://github.com/jenkinsci/jenkins/pulls?q=is%3Apr+author%3Adamianszczepanik+is%3Aclosed), I think we can consider merging this soon even without review. (even if obviously better), hence I'll merge this PR likely later this week if nobody objects, or does it before :-).

@damianszczepanik note that I think it would be good if you do not blank out the PR template next time. Here, I think we should put a changelog entry about your improvement, can you please hence restore the template and fill the right fields?

Thanks!

**Review by batmat — APPROVED** [review]

**Comment by damianszczepanik** [comment]
Thanks.

Template restored
https://patch-diff.githubusercontent.com/raw/jenkinsci/jenkins/pull/3826.patch

**Comment by batmat** [comment]
@damianszczepanik thanks for acting on my comment, but I'm sorry, I was unclear I think. I was not asking you to modify the content of the commits itself, but just the description of this PR above. I believe @daniel-beck has tooling to generate changelog, so anything that does not follow means more manual work.

I'm going to copy the content you put there in the description. Please review it (and check boxes or cross the right lines). Thanks!

**Comment by batmat** [comment]
Planning to merge this after upcoming release tomorrow or Monday. Please still review the changelog, even if merged. Thanks

**Pull request merged**
