### PR TITLE
JENKINS-26544 "Select All" icon in configuration page looks "image not found" icon

### PR DESCRIPTION
**Pull request by chynten-zz**
Modified icon

### CODE REVIEW

**Comment by daniel-beck** [comment]
* Commit message should be according to https://wiki.jenkins-ci.org/display/JENKINS/contributing#contributing-CommitMessages
* Is this 100% your own work, from scratch?

**Comment by pactel** [comment]
Yes 100% my work and will take care for commit message.
Thank you.

**Comment by daniel-beck** [comment]
To clarify, you drew every single pixel of that image yourself? Because it looks identical to the previous image, aside from the checkmark icon.

**Comment by pactel** [comment]
No, I modified the image using the last image and one image which was in your comment in case. I don't know all about licensing but the license file is already there at jenkins/war/src/main/webapp/images.
 It is Attribution-ShareAlike 3.0 Unported:
You are free to:
    Share — copy and redistribute the material in any medium or format
    Adapt — remix, transform, and build upon the material
    for any purpose, even commercially. 
The licensor cannot revoke these freedoms as long as you follow the license terms.
So, what another license do I need to put?

**Comment by daniel-beck** [comment]
The checkmark in my comment is part of Jira and is probably not covered by any free license, likely making this a copyright violation. Hence my question.

The RRZE icon set we already use and have attribution for has two icons that may work as well:

https://github.com/RRZE-PP/rrze-icon-set/blob/master/tango/16x16/documents/approval.png
https://github.com/RRZE-PP/rrze-icon-set/blob/master/tango/16x16/documents/document-passed.png

**Pull request closed without merging**
