### PR TITLE
Update Readme banner to be more reactive on different themes

### PR DESCRIPTION
**Pull request by NotMyFault**
The change proposed utilizes a new GH feature to display SVGs based on the browser theme of the GH user:

<details>
<summary>Current layout - light theme</summary>

Bildschirmfoto 2022-05-29 um 15 22 54

</details>

<details>
<summary>Current layout - dark theme</summary>

Bildschirmfoto 2022-05-29 um 15 23 07

</details>

<details>
<summary>Proposed change - light theme</summary>

Bildschirmfoto 2022-05-29 um 15 22 20

</details>

<details>
<summary>Proposed change - dark theme</summary>

Bildschirmfoto 2022-05-29 um 15 22 04

</details>

Additionally, the banner is now much more readable in darkmode.

### Proposed changelog entries

* N/A, skip changelog

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]

**Comment by NotMyFault** [comment]
This PR is now ready for merge. We will merge it after ~24 hours if there is no negative feedback.
Thanks!

**Review by timja — APPROVED** [review]
better, a bit jarring on GitHub though as the white is quite strong especially against the font color GitHub uses.

image

**Comment by daniel-beck** [comment]
Screenshot 2022-07-04 at 12 52 26

Anyone else experiencing problems like this?

The image URL is https://camo.githubusercontent.com/7ce6d4521e84c41b8edc0a78ae193d9ce019934c7936924fd2e74543e876704d/68747470733a2f2f7777772e6a656e6b696e732e696f2f696d616765732f6a656e6b696e732d6c6f676f2d7469746c652e737667

**Comment by timja** [comment]
Looks good to me:

image

**Comment by NotMyFault** [comment]
No issues either:

Screenshot 2022-07-04 at 12 54 39

**Comment by NotMyFault** [comment]
Out of curiosity, how does the [design library](https://github.com/jenkinsci/design-library-plugin/) readme look for you? We use the same logic there.

**Comment by daniel-beck** [comment]
Looks reasonable.

Does the linked camo image URL look correct for you, or is it the same image I'm seeing on the page? That would indicate that GitHub cache might be broken for me.

**Comment by NotMyFault** [comment]
> Does the linked camo image URL look correct for you, or is it the same image I'm seeing on the page? That would indicate that GitHub cache might be broken for me.

I get the same weirdly shaped one with the small text, but if I download it as .svg and open it, it results in the intended layout, like you can see on our screenshots above.

I guess GH is acting up for you/us.

**Pull request merged**
