### PR TITLE
Refactor `translation-tool.pl`

### PR DESCRIPTION
**Pull request by glasswalk3r**
No Jira related issue.

Refactor the `translation-tool.pl` Perl script command line parameters parsing and handling.

### Proposed changelog entries

* Developer: Add a `--debug` option to the translation tool to help in troubleshooting. Improve the readability of the translation tool command-line interface (CLI).

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by basil** [comment]
I think including both functional changes and formatting changes in the same PR makes this more difficult to review. I think this would be easier to review if it were split into two PRs: one with functional changes, and the other with purely stylistic formatting changes.

**Comment by glasswalk3r** [comment]
> I think including both functional changes and formatting changes in the same PR makes this more difficult to review. I think this would be easier to review if it were split into two PRs: one with functional changes, and the other with purely stylistic formatting changes.

Agreed. On the other hand, the stylistic changes were not very large considering that we already merged a previous introduction of perltidy and shouldn't happen anymore as long as the configuration for it is used in the future.
The changes that really requires a review are from line 1 to 96, 282 to 346 and 413 to 491. Everything else no logic changes.
On top of that, there is still a lot more to work on that script, including minor bugs.

**Comment by basil** [comment]
> The changes that really requires a review are from line 1 to 96, 282 to 346 and 413 to 491.

Sure, though there are still stylistic changes mixed with logic changes in the above ranges of lines. Your work is highly appreciated, but I think you are going to have an easier time getting PRs merged if you make them reviewer-friendly. We are all trying to make Jenkins better and doing the best we can with what we have. The current core maintainers are not the original authors of the code, so it can take some effort to read and understand the existing code in order to evaluate pull requests. Making that process easier for us, while not required, is certainly appreciated as well.

**Comment by glasswalk3r** [comment]
> Sure, though there are still stylistic changes mixed with logic changes in the above ranges of lines. Your work is highly appreciated, but I think you are going to have an easier time getting PRs merged if you make them reviewer-friendly. We are all trying to make Jenkins better and doing the best we can with what we have. The current core maintainers are not the original authors of the code, so it can take some effort to read and understand the existing code in order to evaluate pull requests. Making that process easier for us, while not required, is certainly appreciated as well.

Thank you and I understand. I will break down the changes to make easier for everybody to review in the future. I also saw that you created a new PR aiming that, so I'll wait for it's completion before going forward with this one.

I found out other issues with `translation_tool.pl` and my conclusion is that we need a better strategy to handle those issues/refactoring, which goes down to two options:

1. Create a sub directory inside the project and start migrating the program functions to modules.
2. Create a separated project to maintain the tool, with it's own source code repository. This would also make it easier to handle issues/PR separated from Jenkins project and also make the tool available at CPAN (although this last feature could also be possible with option 1).

In both cases, we would start migrating a function to a Perl module (as-is), write unit tests, and change the script to import those functions from the modules. From there we would be able to gradually refactor those functions with more guarantees that the refactoring would not brake anything.

As said before, I'm spotting bugs from `translation_tool.pl` while making the Brazilian Portuguese translations. [This is one](https://issues.jenkins.io/browse/JENKINS-67892) and we might also get something from #6328 .

**Review by basil — APPROVED** [review]

**Review by timja — APPROVED** [review]

**Comment by basil** [comment]
This PR is now ready for merge. We will merge it after approximately 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process. Thanks!

**Comment by basil** [comment]
> I found out other issues with translation_tool.pl and my conclusion is that we need a better strategy to handle those issues/refactoring, which goes down to two options

@glasswalk3r Allow me to suggest a third option: rewrite the script from scratch in Python. Perl has declined greatly in popularity since this script was written in 2010. A Python version would be accessible to more people and could be implemented more cleanly with XML parsing libraries rather than relying on regular expressions. Obviously, this would be a much bigger undertaking, but I think the end result would be more maintainable.

I applied an automated conversion tool to the script, which resulted in mostly useless results, some of which I polished up a little. I posted it [here](https://gist.github.com/basil/309c721bb3a24ffe313dff60c84fcb35). This isn't close to being usable yet, but if you're interested in rewriting the script in Python perhaps it would be a good place to start.

**Comment by glasswalk3r** [comment]
> @glasswalk3r Allow me to suggest a third option: rewrite the script from scratch in Python. Perl has declined greatly in popularity since this script was written in 2010. A Python version would be accessible to more people and could be implemented more cleanly with XML parsing libraries rather than relying on regular expressions. Obviously, this would be a much bigger undertaking, but I think the end result would be more maintainable.

Well, it's a shame, but I got your point (and probably that is still open for discussion about the reasons for that) . But there is no denying or arguments about it, it is just a fact.

But truth to be told, I need to stand up for the fact that - written in 2010 or not - this script is really an outdated way to write Perl code: does not follow [perlstyle](https://perldoc.perl.org/perlstyle) neither [Perl Best Practices](https://www.youtube.com/watch?v=dJEkyUyepgw) (released in 2009, with so much coverage after it by the community).

Don't get me wrong, a contribution is always welcome, but it's clear that this script could be improved in a lot of ways.

For any person reasonable experienced in both Java and Perl, it is clearly written by someone with Java (or .Net) background. It **does** get the job done (well, almost, but every written software has bugs), but it is not idiomatic Perl: [here](https://www.youtube.com/watch?v=OSGv2VnC0go) is an excellent example of what I'm talking about, but related to Python.

The exaggerated usage of regular expressions was a design decision, not a limitation of the programming language. Just take a stroll at [meta::cpan](https://metacpan.org/) to see XML parsers and [much else](https://metacpan.org/pod/Config::Properties).

> I applied an automated conversion tool to the script, which resulted in mostly useless results, some of which I polished up a little. I posted it [here](https://gist.github.com/basil/309c721bb3a24ffe313dff60c84fcb35). This isn't close to being usable yet, but if you're interested in rewriting the script in Python perhaps it would be a good place to start.

I can do that, but I got ask first: why not Groovy or even Golang?

**Comment by basil** [comment]
> I can do that, but I got ask first: why not Groovy or even Golang?

I used Python as an example because it is one of the most popular scripting languages today, but rewriting the script in any of those languages (following sound engineering principles) would be an improvement over the status quo.

**Pull request merged**
