### PR TITLE
Fix for wrong build result after reload build.xml

### PR DESCRIPTION
**Pull request by fischaxe**
While running repository scans old builds not stored in memory are loaded from disk. Before deserialization is executed the result of the build is set to [Failure](https://github.com/jenkinsci/jenkins/blob/ebc0d5e785643d0df2689acb7b8daa9608b061bb/core/src/main/java/hudson/model/Run.java#L368). When deserialization hits [setResult](https://github.com/jenkinsci/jenkins/blob/ebc0d5e785643d0df2689acb7b8daa9608b061bb/core/src/main/java/hudson/model/Run.java#L503) the condition [isWorseThan](https://github.com/jenkinsci/jenkins/blob/ebc0d5e785643d0df2689acb7b8daa9608b061bb/core/src/main/java/hudson/model/Run.java#L509) never gets true caused by the pre-population and result stays with Failure.

This causes every component uses this state afterwards to report wrong results (e.g. GitHub checks)

See [JENKINS-70459](https://issues.jenkins.io/browse/JENKINS-70459)
See [JENKINS-64808](https://issues.jenkins.io/browse/JENKINS-64808) (Partial)

### Proposed changelog entries

- Stating correct build result after loading build.xml from disk

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7886"></a>

### CODE REVIEW

**Comment by fischaxe** [comment]
Hi guys,

since I can't take a look behind the scene but being interested in getting a LTS fix soon, how will you proceed with this?

Regards,
Axel

**Comment by NotMyFault** [comment]
> since I can't take a look behind the scene but being interested in getting a LTS fix soon, how will you proceed with this?

The backporting process is publicly documented on [jenkins.io](https://www.jenkins.io/download/lts/#backporting-process), but a couple of (or more) maintainers have to approve and merge this PR first, to be delivered in a weekly.

**Comment by fischaxe** [comment]
Is this PR under review or is additional information required since nobody commented so far?

**Comment by NotMyFault** [comment]
@fischaxe Would you mind addressing the feedback proposed by Mark?

**Comment by NotMyFault** [comment]
Hey @fischaxe,

thanks for the PR. I'll go ahead and close it for now, until the changes requested by Mark have been addressed.
You're welcome to reopen the PR, once it's in a state for a review.

Thanks!

**Pull request closed without merging**
