### PR TITLE
JENKINS-59505 - Fix typo in plugin setup wizard

### PR DESCRIPTION
**Pull request by agmt5989**
Minor typo fix on line `93|94` [JENKINS-59505](https://issues.jenkins-ci.org/browse/JENKINS-59505)

### Proposed changelog entries

* None

### Description

The pluginSetupWizard.properties file says on line `93|94`,

"Some plugins failed to install properly, you may retry installing them or continue with the failed plugins."

I think that should instead have been

"Some plugins failed to install properly, you may retry installing them or continue without the failed plugins"

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@timja 

This change has no autotests because none is necessary.

### CODE REVIEW

**Comment by timja** [comment]
Can you update the PR title to reflect the change, 
I would also copy the description from the ticket into the PR as that would have saved me having to click on it.

Change itself looks good

**Review by oleg-nenashev — APPROVED** [review]
thanks!

**Comment by agmt5989** [comment]
Done @timja. I hope it isn't too long

**Comment by timja** [comment]
How about:
> Fix typo in plugin setup wizard

**Review by timja — APPROVED** [review]

**Comment by agmt5989** [comment]
Done

**Review by res0nance — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
If you want this fix to be backported into LTS, we will also need a JIRA ticket for it. Otherwise, it is good to go IMHO

**Comment by timja** [comment]
It has a jira JENKINS-59505
Linked in the description, not in the regular format though

**Comment by agmt5989** [comment]
@oleg-nenashev, should I convert the JIRA issue to a ticket then?

**Comment by timja** [comment]
> @oleg-nenashev, should I convert the JIRA issue to a ticket then?

Just rename the title to include: `JENKINS-59505 -`
and ideally update your description to link like [JENKINS-59505](https://issues.jenkins-ci.org/browse/JENKINS-59505) not #59505

**Comment by agmt5989** [comment]
> 
> 
> > @oleg-nenashev, should I convert the JIRA issue to a ticket then?
> 
> Just rename the title to include: `JENKINS-59505 -`
> and ideally update your description to link like [JENKINS-59505](https://issues.jenkins-ci.org/browse/JENKINS-59505) not #59505

Done

**Comment by oleg-nenashev** [comment]
Thanks for the fix!

**Comment by agmt5989** [comment]
Pleasure's all mine.

**Pull request merged**
