### PR TITLE
Removed an extra comma

### PR DESCRIPTION
**Pull request by akashfoss**
Can anybody add me to this organization  ? Thanks for reviewing this PR.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
AFAIK it's a perfectly correct English. The only issue is that nobody uses this approach AFAIK. See http://www.getitwriteonline.com/archive/020204whencommabfand.htm . So I see no need in the change

> Can anybody add me to this organization ? 

What exactly do you want to do?

**Review by KostyaSha — CHANGES_REQUESTED** [review]
initial variant looks right

**Comment by daniel-beck** [comment]
AFAICT Jenkins documentation is predominantly American English. And in AE, most style guides, including Strunk & White and the Chicago Manual of Style mandate the use of a serial comma. Even in British English, the Oxford Style Manual requires it. So this is by no means wrong.

I think we'll pass.

**Comment by akashfoss** [comment]
Thanks guys for sharing this knowledge, I will take care of these things before creating a pull request.

**Pull request closed without merging**
