### PR TITLE
[FIXED JENKINS-18884] Access check to jobs in People pages.

### PR DESCRIPTION
**Pull request by ikedam**
People page displays users extracted from change logs of jobs belonging to that view.
And People page of All view also displays all users registered in Jenkins.

They do no permission check.

This patch does followings:
- Adds permission check to jobs to extract users (now requires Read permission).
- People page of All view no longer display all users registered in Jenkins. It works same as those of other views:
  - There is no reason for People page of All page to work different from those of other views.
  - Displaying all users in Jenkins should be handled by security realms (like [`HudsonPrivateSecurityRealm.ManageUserLinks`](http://javadoc.jenkins-ci.org/hudson/security/HudsonPrivateSecurityRealm.ManageUserLinks.html)). If needed, I would implement a default user listing page for administrators.

This is another approach of #1094 .
First I planned to add a new permission to restrict access to People page in All view, but I get to think that the root problem is the difference of behaviors of People pages between All view and other views.

### CODE REVIEW

**Comment by jglick** [comment]
My alternate recommendation now filed as [JENKINS-26469](https://issues.jenkins-ci.org/browse/JENKINS-26469).

**Comment by oleg-nenashev** [comment]
I'd rather agree with @jglick , but IMO it makes sense even in the current state
So :+1: if the merge conflict gets fixed

**Comment by dasJ** [comment]
What about the conflict @ikedam

**Comment by ikedam** [comment]
I don't plan to work for this issue anymore.
I'll abondon this request.
Thanks for the reviews.

**Comment by hypery2k** [comment]
Give new PR a try: https://github.com/jenkinsci/jenkins/pull/9052

**Pull request closed without merging**
