### PR TITLE
[JENKINS-48773] - Limit which section headers are added to the breadcrumb config outline

### PR DESCRIPTION
**Pull request by daniel-beck**
See [JENKINS-48773](https://issues.jenkins-ci.org/browse/JENKINS-48773).

This implements two independent changes:

* Do not add section headers inside `f:repeatable` elements to the outline, as that'll just make a mess of things (see Jira issue).
* Do not add section headers that are invisible (such as "Strategy" in the global config, when there's no job naming strategy selected) to the outline.

The second one has the problem that we do not check for DOM changes, so once a section header becomes visible, it still won't show in the outline. I still consider not showing initially invisible section headers preferable to showing them. My JS-fu isn't sufficient to figure out how to edit (probably) `lib/form/breadcrumb-config-outline/init.js` to do that (perhaps @kzantow knows?).

An argument could be made that any section headers that aren't on the top level shouldn't be included anyway, given that this is supposed to be a tree, and `init.js` only looks at children of the root. But I didn't bother to figure out how to determine whether a section is at the top level or not, and don't plan to.

### Proposed changelog entries

* RFE: Limit which section headers are added to the breadcrumb config outline

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [n/a] Appropriate autotests or explanation to why this change has no tests
- [n/a] For dependency updates: links to external changelogs and, if possible, full diffs

FYI @rtyler (and @abayer who edited the issue)

### CODE REVIEW

**Comment by daniel-beck** [comment]
Test failures appear to be (sort of) real.

**Review by oleg-nenashev — APPROVED** [review]
👍 AFAICT.

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers @rtyler @abayer  I tested it manually and it looks good to me. Any concerns about merging towards this weekly?

**Comment by oleg-nenashev** [comment]
I am going to merge it towards the next weekly

**Pull request merged**
