### PR TITLE
Remove HTTP response headers for the remoting-based CLI

### PR DESCRIPTION
**Pull request by daniel-beck**
Related to #2795, #3838, #4350, and aebb3b235bec7b052841da2d4ed8265f27ea2adc.

Untested; PR build and @jglick will be able to tell us whether this is correct. I think these headers are unused now; I couldn't find a reference here or in Remoting at least.

`CLI_HOST_NAME` is still advertised as `X-Jenkins-JNLP-Host`, the port as `X-Jenkins-JNLP-Port`.

Unsure whether to leave https://github.com/jenkinsci/jenkins/blob/95e85495ca6b26ba61ff4a1bf18d181d5e218bc9/test/src/test/java/hudson/cli/CLITest.java#L179 in. (Edited to add: Now removed in https://github.com/jenkinsci/jenkins/pull/5452/commits/4bd10a4c48f1e10efd8d4ddb120e4991b82346da)

### Proposed changelog entries

* Stop sending HTTP response headers related to the remoting-based CLI (removed in 2.165).

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by basil — APPROVED** [review]
Looks good to me, but might also want to get rid of the now-dangling reference to `X-Jenkins-CLI-Port` in `test/src/test/java/hudson/cli/CLITest.java`.

**Review by jglick — APPROVED** [review]
Yes I think this is safe. (Came up sometime recently but I forget where.)

**Review by jglick — APPROVED** [review]

**Review by res0nance — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
I referenced the advertiseHeaders() method in the FLoC thread, likely this is where @jglick saw it I'd guess. Thanks for the cleanup @daniel-beck !

I see reliance on these headers in https://github.com/jenkinsci/master-to-master-api-plugin/blob/bb48f24779f4873877bbf6500621377e077ffda3/src/main/java/org/jenkinsci/plugins/mastertomasterapi/simple/SIMClient.java  . I'd guess we do not care too much about this plugin in the current state (not published in the UC)

We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Comment by jglick** [comment]
> I referenced the advertiseHeaders() method in the FLoC thread, likely this is where @jglick saw it I'd guess.

Somewhere else I think. Does not matter now.

**Comment by jtnord** [comment]
@daniel-beck what is the correct web header now in order to locate the (sic) JNLP port for remoting connections?

(basically breaks quite a pretty important CloudBees specific feature :) )

**Pull request merged**
