### PR TITLE
[JENKINS-46603] Bump to latest parent 1.39

### PR DESCRIPTION
**Pull request by batmat**
Updating to latest release, including https://github.com/jenkinsci/pom/pull/15 and https://github.com/jenkinsci/pom/pull/16.

See [JENKINS-46603](https://issues.jenkins-ci.org/browse/JENKINS-46603).

### Proposed changelog entries

Please refer to https://github.com/jenkinsci/pom/blob/master/CHANGELOG.md#139

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@reviewbybees

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Parent has been already updated in https://github.com/jenkinsci/jenkins/pull/2995 , but this PR still makes sense. Retriggering the CI

**Comment by oleg-nenashev** [comment]
@batmat needs re-merge with the master branch from what I see

**Comment by batmat** [comment]
@oleg-nenashev Daniel is right to add `needs-fix`, I needed more time to investigate the failure since removing the `maven-assembly-override` shows the `attached` goal, deprecated since long, is now gone. So I need apparently to use `single` instead. Will do.

**Comment by batmat** [comment]
Fixed, let's see what the PR builder says. At least now `mvn clean verify -DskipTests` succeeds locally.

**Comment by oleg-nenashev** [comment]
PR builder is fine. Likely it will get into the next weekly. No rush anyway

**Comment by batmat** [comment]
@oleg-nenashev so per your last comment, I understand you're _approving_ this PR?

**Review by oleg-nenashev — APPROVED** [review]
Yes, 🐝

**Comment by batmat** [comment]
@daniel-beck I'm considering to merge for the upcoming release, WDYT?

I've built and tested the WAR locally for a quick dry-run test and nothing wrong surfaced.

**Comment by batmat** [comment]
Got an ack from Daniel on IRC, merging.

**Pull request merged**
