### PR TITLE
[JENKINS-63166 ] - Replace text references of slave with agent in Japanese documentation

### PR DESCRIPTION
**Pull request by takashiharano**
See [JENKINS-42816](https://issues.jenkins-ci.org/browse/JENKINS-42816).

Replaced slave with agent in Japanese documentation and messages.
No other changes (grammatical or otherwise) have been made.

The original text has three patterns:
- "スレーブ" (slave)
- "スレーブエージェント" (slave agent)
- "スレーブのエージェント" (agent of slave)

These were replaced to "エージェント" (agent).

Also, unicode escape sequences were replaced as follows:
スレーブ (slave) \u30b9\u30ec\u30fc\u30d6 to エージェント (agent) \u30a8\u30fc\u30b8\u30a7\u30f3\u30c8

### Proposed changelog entries

* Entry 1: Replace text references to slave with agent in Japanese documentation and messages

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Based on the Governance meeting agreements, I will categorize the obsolete terminology as defect so that we can cleanup it and backport the fix. https://issues.jenkins-ci.org/browse/JENKINS-63166 as a placeholder issue for the backporting process

**Comment by takashiharano** [comment]
Added one missing file.
core/src/main/resources/hudson/model/AbstractItem/help-slaveAffinity_ja.html

**Review by ikedam — APPROVED** [review]
Looks good to me.

* All replacements are valid.
* No Japanese text for slave is left.

**Review by oleg-nenashev — APPROVED** [review]
Thanks a lot for the patch to @takashiharano and for the review to @ikedam ! +1 from me as well.

We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Review by MarkEWaite — APPROVED** [review]

**Pull request merged**
