### PR TITLE
Replace "slave" reference in Traditional Chinese document

### PR DESCRIPTION
**Pull request by benebsiny**
### Proposed changelog entries

* Entry 1: Replace "slave" reference with "agent" in Traditional Chinese translation

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [X] Appropriate autotests or explanation to why this change has no tests

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [x] There are at least 2 approvals for the pull request and no outstanding requests for change
- [x] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [x] Proper changelog labels are set so that the changelog can be generated automatically

### CODE REVIEW

**Comment by daniel-beck** [comment]
@benebsiny Thanks for your submission!

Just to be safe, do you speak (well, read/write) Chinese? I am asking because we've had similar localization contributions in the past that ended up messing up the grammar.

**Comment by benebsiny** [comment]
@daniel-beck Yes, I surely speak Chinese.

**Review by MarkEWaite — APPROVED** [review]

**Review by markjacksonfishing — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
It is not 100% clear why these localizations are in the core codebase at the moment. But changes look fine. 
We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Review by res0nance — APPROVED** [review]

**Comment by daniel-beck** [comment]
@oleg-nenashev 

> It is not 100% clear why these localizations are in the core codebase at the moment.

IIRC the `localization-zh-cn` plugin at first did not support webapp resource localization; that's also something I added fairly late to `localization-support`.

**Pull request merged**
