### PR TITLE
Remove WebSocket support for Jetty 9

### PR DESCRIPTION
**Pull request by jglick**
Cleans up after #6801. Retaining support temporarily for Jetty 9 seems like a sensible conservative decision but I do not think we wish to maintain this code indefinitely.

### Proposed changelog entries

- Remove support for WebSocket agents when running inside Jetty 9.

### Proposed upgrade guidelines

If you are using WebSocket agents and were manually embedding Jenkins in a Jetty 9 servlet container, you should either upgrade the container to Jetty 10, or simply use the built-in container (`java -jar jenkins.war`).

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7101"></a>

### CODE REVIEW

**Review by basil — COMMENTED** [review]
Seems a bit aggressive to me so long as current versions of `JenkinsRule` are still based on Jetty 9. `org.csanchez.jenkins.plugins.kubernetes.pipeline.WebSocketTest` seems likely to break.

**Comment by jglick** [comment]
True, this should wait for https://github.com/jenkinsci/jenkins-test-harness/pull/453.

**Comment by basil** [comment]
> True, this should wait for https://github.com/jenkinsci/jenkins-test-harness/pull/453.

I concur, and that in turn needs to wait for the test harness to require Java 11, which in turn needs to wait for the test harness to require a baseline of 2.357 or later. Since that baseline just came out in LTS form this month, I think it is a bit aggressive to start requiring it from the plugin POM and test infrastructure, but in a few more months (when more plugins have moved their baseline to 2.361.1 or later) the time could be right.

**Comment by jglick** [comment]
Since https://github.com/jenkinsci/jenkins-test-harness/pull/453 has long since been widely adopted, I believe this is now safe from a toolchain perspective.

**Review by basil — COMMENTED** [review]
Are all the plugins in BOM using a sufficiently new test harness with https://github.com/jenkinsci/jenkins-test-harness/pull/453? If not, this might have to wait until https://github.com/jenkinsci/plugin-compat-tester/pull/489.

**Comment by jglick** [comment]
I suspect it suffices for all plugins which test WebSocket agents to use the new harness. Can check an incremental build.

**Comment by jglick** [comment]
Indeed, `bom` passes against this change.

**Review by basil — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]
Thanks!

**Comment by NotMyFault** [comment]
/label ready-for-merge

---

This PR is now ready for merge. We will merge it after ~24 hours if there is no negative feedback.
Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process.
Thanks!

**Pull request merged**
