### PR TITLE
[WiP] Add timestamp when the slave is online, and when it has been terminated

### PR DESCRIPTION
**Pull request by christ66**
It is useful to know when the time that the slave node has been terminated and when it is connected and online.

@reviewbybees

### CODE REVIEW

**Comment by stephenc** [comment]
:+1:

**Comment by daniel-beck** [comment]
Wouldn't it be better to have e.g. the `TaskListener` do that automatically whenever you add something?

**Comment by olivergondza** [comment]
I agree that decorated `TaskListener` is a better way to go. This feature naturally belongs to [Timestamper](https://wiki.jenkins-ci.org/display/JENKINS/Timestamper), though.

**Comment by jglick** [comment]
> This feature naturally belongs to Timestamper, though.

Perhaps but that plugin only handles build logs. There is no extension point for decorating slave logs that I know of.

**Comment by daniel-beck** [comment]
For slave logs this can be in core IMO.

**Comment by jglick** [comment]
:+1:

**Comment by oleg-nenashev** [comment]
I would also vote for an implementation based on an extension point, but it will require much efforts.

@christ66 
I propose to just create a new <code>TaskListener</code> implementation, because all your calls use the manually created <code>final TaskListener taskListener = new StreamTaskListener(launchLog);</code>. It will simplify the code and allow to use such listener in other similar cases (e.g. Script consoles).

**Comment by oleg-nenashev** [comment]
Marked as WiP (hopefully we'll have labels soon)

**Comment by daniel-beck** [comment]
@christ66 Are you planning to finish this?

**Comment by oleg-nenashev** [comment]
Merge conflict, no response from @christ66 .
@aheritier @recampbell are you still interested in it? If no, I suggest closing it

**Comment by aheritier** [comment]
let's close :-/

**Comment by christ66** [comment]
Probably will implement in future. Not today though. Closing.

**Pull request closed without merging**
