### PR TITLE
[JENKINS-68788] Update center checkboxes keep focus state post-click

### PR DESCRIPTION
**Pull request by 1weiho**
See [JENKINS-68788](https://issues.jenkins.io/browse/JENKINS-68788).

Before:
螢幕錄製_2022-06-23_上午2_57_42_AdobeExpress
After:
螢幕錄製_2022-06-23_上午2_58_20_AdobeExpress

### Proposed changelog entries

* Update center checkboxes keep focus state after they have been clicked.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/6680"></a>

### CODE REVIEW

**Review by NotMyFault — COMMENTED** [review]
As seen on the "After" GIF, the animation isn't cleared properly on the initial selection either, that should be addressed too.

**Comment by davidho0403** [comment]
Like this?
螢幕錄製_2022-06-23_下午7_36_11_AdobeExpress

**Comment by NotMyFault** [comment]
> Like this? 螢幕錄製_2022-06-23_下午7_36_11_AdobeExpress [ ](https://user-images.githubusercontent.com/75478661/175290027-a3f24812-e47e-4964-8120-63267e704bd1.gif) 螢幕錄製_2022-06-23_下午7_36_11_AdobeExpress [ ](https://user-images.githubusercontent.com/75478661/175290027-a3f24812-e47e-4964-8120-63267e704bd1.gif)

No, that drops the emphasizing animation at all. See `jenkinsUrl/configure` -> "Usage Statistics" ' checkbox for a proper example showing how the animation flow has to look like.

**Comment by davidho0403** [comment]
I have seen the "Usage Statistics", I can't find the difference between them (maybe I misunderstand your word?)
螢幕錄製_2022-06-23_下午8_15_17_AdobeExpress

**Comment by NotMyFault** [comment]
> I have seen the "Usage Statistics", I can't find the difference between them (maybe I misunderstand your word?) !

Take a close look at the frame and animation, it persists until you click again, as opposed to other checkboxes:
https://user-images.githubusercontent.com/13383509/175300594-9b0f8515-d28a-460b-bff6-59c6450b2fa5.mp4

**Comment by davidho0403** [comment]
I understand what you mean, I commit it, thanks~
Below is the result after my changes:
螢幕錄製_2022-06-24_上午1_05_28_AdobeExpress

**Review by NotMyFault — APPROVED** [review]
Looks promising so far.

**Comment by NotMyFault** [comment]
Can I convince someone from @jenkinsci/sig-ux to take a look? Minor issue, but it would be nice to see it resolved before the next LTS baseline selection starts.

**Comment by janfaracik** [comment]
Working well on my end 👍 I've tested the disabled state too and all seems good there too.

**Review by janfaracik — APPROVED** [review]

**Comment by timja** [comment]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Pull request merged**
