### PR TITLE
 JENKINS-61660 - Fix spacing between error messages in Setup Wizard (regression in 2.217)

### PR DESCRIPTION
**Pull request by sladyn98**
See [JENKINS-61660](https://issues.jenkins-ci.org/browse/JENKINS-61660).

**Before** 
Before Image 2020-03-23 a las 11 10 50 (1)

**After**
Screenshot from 2020-04-07 13-04-47

### Proposed changelog entries

* Fix spacing between error messages in Setup Wizard (regression in 2.217)

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests

### Desired reviewers

@fqueiruga 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [x] There are at least 2 approvals for the pull request and no outstanding requests for change
- [x] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [x] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [x] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

### CODE REVIEW

**Review by fqueiruga — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
I think this is an improvement, not a bug. Thanks anyway @sladyn98 !

**Comment by fqueiruga** [comment]
It's a regression introduced on 2.217+

**Comment by varyvol** [comment]
@sladyn98 I think screenshots for the before and after would be very useful.

**Comment by oleg-nenashev** [comment]
I plan to merge it tomorrow if no negative feedback

**Review by timja — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Thanks @sladyn98 !

**Comment by sladyn98** [comment]
@oleg-nenashev My pleasure

**Pull request merged**
