### PR TITLE
[JENKINS-69214] Radio buttons appear selected, when navigating with tab

### PR DESCRIPTION
**Pull request by ridemountainpig**
See [JENKINS-69214](https://issues.jenkins.io/browse/JENKINS-69214).
image

### Proposed changelog entries

* Show separate focus and active state for radio buttons when unselected

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")` if applicable.
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/6958"></a>

### CODE REVIEW

**Comment by daniel-beck** [comment]
Thanks for taking care of this!

Could you provide before/after screenshots right here in the PR? To be honest I do not see what was changed with your screenshot.

**Comment by ridemountainpig** [comment]
Before
image
After
image

**Comment by daniel-beck** [comment]
The problem I was reporting is that the "focused but unselected" state looks very similar to "selected", which is confusing: It looks like an element would be selected, even though it is only focused.

With this change they look identical, which is the opposite of what I was asking for.

**Comment by ridemountainpig** [comment]
Before

https://user-images.githubusercontent.com/92412722/182483422-4b0cb6b3-70a5-4d98-90a4-6926b55b5971.mov


After

https://user-images.githubusercontent.com/92412722/182483004-2c36f9cc-fec8-40ce-9380-1400344730b8.mov

**Comment by daniel-beck** [comment]
@ridemountainpig That looks very clearly different! Thank you!

@janfaracik or @jenkinsci/sig-ux does that look OK to you? Any consistency issues with other elements perhaps?

**Review by NotMyFault — COMMENTED** [review]
> Any consistency issues with other elements perhaps?

Right as you mentioned it, the change proposed gets a rid of the smooth selection transition:

<details>
<summary>This PR</summary>

https://user-images.githubusercontent.com/13383509/182708056-0ffe43bc-932d-4ce2-bae7-10ccbbac182f.mp4

</details>

<details>
<summary>2.361</summary>

https://user-images.githubusercontent.com/13383509/182708190-c1b454f4-6f57-4904-8641-efe0a9234b7e.mp4

</details>

**Comment by ridemountainpig** [comment]
> Right as you mentioned it, the change proposed gets a rid of the smooth selection transition:

Is this mean I need to made it become more smooth ?

**Comment by ridemountainpig** [comment]
> Right as you mentioned it, the change proposed gets a rid of the smooth selection transition:

I have made selection transition become more smooth

https://user-images.githubusercontent.com/92412722/182767810-59af6217-53b7-4f8f-90d5-26ad9c135d4c.mov

**Comment by NotMyFault** [comment]
> I have let selection transition become more smooth

This is still different to what it looked like before, and I don't think there's a need to change the existing animation in order to address the issue 🤔

**Comment by ridemountainpig** [comment]
> This is still different to what it looked like before, and I don't think there's a need to change the existing animation in order to address the issue 🤔

So we have to remove the transition-duration from commit ?
By the way, do you have any better way to resolve it ? 
Because now I have no better idea to resolve this question.

Thanks~

**Comment by ridemountainpig** [comment]
> This is still different to what it looked like before, and I don't think there's a need to change the existing animation in order to address the issue 🤔

I think it look a same with 2.361.

https://user-images.githubusercontent.com/92412722/183548492-72fee849-091e-43fb-ad39-d671926cfc89.mov

**Comment by ridemountainpig** [comment]
> I think it look a same with 2.361.
When selecting the middle will be white, is because the inset box-shadow had been remove, to avoid it's only focused, not selected.

@NotMyFault , @janfaracik , how do you feel ?

**Comment by janfaracik** [comment]
Hey there, thanks for taking on the bug! I've been away (and still am somewhat) for a while so apologies for my late response - 

I've given it a quick demo on Safari/macOS and the animations seems a little buggy:

https://user-images.githubusercontent.com/43062514/183758170-9003cc1f-6919-4d01-af95-1d2eac318fd3.mov

Unrelated: The focus states for the inputs across the board could do with some love really, the updated sidebar items/buttons handle focus a lot nicer than my current implementation, it would be neat to see the inputs adopt something similar.

Screenshot 2022-08-09 at 21 51 35

**Comment by ridemountainpig** [comment]
@janfaracik It seem look more better like this.

https://user-images.githubusercontent.com/92412722/183797237-e8eebd3d-d91d-4d4e-b201-44afdccca88c.mov

Thanks for review~

**Comment by ridemountainpig** [comment]
> @NotMyFault , @janfaracik It seem look more better like this.
> 
>  2022-08-10.10.27.18.mov 
> 
> Thanks for review~

Can someone give some comment for this fix ?
Thanks~

**Review by NotMyFault — APPROVED** [review]

**Comment by ridemountainpig** [comment]
Sorry, could I get a review from @jenkinsci/sig-ux and @janfaracik ? Thx~

**Review by timja — APPROVED** [review]
Tested and is fine, FYI I reported https://issues.jenkins.io/browse/JENKINS-69398 which I thought was caused by this but I can reproduce on https://weekly.ci.jenkins.io (latest weekly)

**Comment by timja** [comment]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by timja** [comment]
We have an alternative PR here https://github.com/jenkinsci/jenkins/pull/7017 which fixes both JENKINS-69398 and JENKINS-69214

**Comment by ridemountainpig** [comment]
> We have an alternative PR here https://github.com/jenkinsci/jenkins/pull/7017 which fixes both JENKINS-69398 and JENKINS-69214

I think https://github.com/jenkinsci/jenkins/pull/7017 is just look same that what I do ... ?

**Comment by ridemountainpig** [comment]
>> We have an alternative PR here https://github.com/jenkinsci/jenkins/pull/7017 which fixes both JENKINS-69398 and JENKINS-69214
> 
>I think https://github.com/jenkinsci/jenkins/pull/7017 is just look same that what I do ... ?

So if this issue have been fix in https://github.com/jenkinsci/jenkins/pull/7017 then this PR should be closed ???

**Comment by ridemountainpig** [comment]
> We have an alternative PR here https://github.com/jenkinsci/jenkins/pull/7017 which fixes both JENKINS-69398 and JENKINS-69214

@timja  I think https://github.com/jenkinsci/jenkins/pull/7017 is base on my revise to add some new things to fix this issue, so I think both PR have attribute to this issue, and both can be merge.

**Comment by timja** [comment]
> > We have an alternative PR here #7017 which fixes both JENKINS-69398 and JENKINS-69214
> 
> @timja I think #7017 is base on my revise to add some new things to fix this issue, so I think both PR have contribute to this issue, and both can be merge.

They aren't the same fix and won't apply cleanly, given the other PR fixes both issues I prefer that one but huge thanks for looking into this and your contributions are really appreciated!

**Comment by ridemountainpig** [comment]
> They aren't the same fix and won't apply cleanly, given the other PR fixes both issues I prefer that one but huge thanks for looking into this and your contributions are really appreciated!

Thanks for review!

**Pull request closed without merging**
