### PR TITLE
[JENKINS-69245] Weird spacing for dropdown in nested/combined model links

### PR DESCRIPTION
**Pull request by frankie139506**
See [JENKINS-69245](https://issues.jenkins.io/browse/JENKINS-69245).

image

### Proposed changelog entries

* fix oddly space in model links.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] (If applicable) Jira issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [X] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")` if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content-Security-Policy directives (see [documentation on jenkins.io](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/6968"></a>

### CODE REVIEW

**Comment by daniel-beck** [comment]
Would be interesting to know why this space was added in the first place. @janfaracik do you remember its purpose? MY guess is content like UpstreamBuildCause and model-link HyperLinkNotes in build logs, but those are basically taken care of with the wide solid color background?

Screenshot 2022-08-05 at 07 41 52

Screenshot 2022-08-05 at 07 41 59

**Review by NotMyFault — DISMISSED** [review]
The change as-is undoes https://github.com/jenkinsci/jenkins/pull/6481 reintroducing a couple of issues considered as blocker.

**Comment by frankie139506** [comment]
> The change as-is undoes #6481 reintroducing a couple of issues considered as blocker.

Thanks for this comment, but I didn't find the other change if I remove `margin-right`.

**Comment by frankie139506** [comment]
> The change as-is undoes #6481 reintroducing a couple of issues considered as blocker.

@NotMyFault I have made some change and I move `margin-right: 40px !important;` from `breadcrumbs.less` to `table.less`, I think it remaining https://github.com/jenkinsci/jenkins/pull/6481 's change and solve this issue problem.

**Comment by NotMyFault** [comment]
It appears that the current proposal warrants the underlaying fix still:

But some more feedback would be appreciated.

**Comment by frankie139506** [comment]
> It appears that the current proposal warrants the underlaying fix still:  But some more feedback would be appreciated.

@NotMyFault Apologize, Can you reproduce this problem? I can't find where the problem is.

**Comment by NotMyFault** [comment]
> @NotMyFault Apologize, Can you reproduce this problem? I can't find where the problem is.

There's no issue.

**Comment by frankie139506** [comment]
> > @NotMyFault Apologize, Can you reproduce this problem? I can't find where the problem is.
> 
> There's no issue.

Thanks for your reply, I have done some simple checks and I will still fix it if there is any problem.

**Comment by NotMyFault** [comment]
> > > @NotMyFault Apologize, Can you reproduce this problem? I can't find where the problem is.
> > 
> > 
> > There's no issue.
> 
> Thanks for your reply, I have done some simple checks and I will still fix it if there is any problem.

Bear in mind that "No issues" refers to the underlaying fix I mentioned before. Modifying the overall table style still has a negative impact on all tables. Apologizes if I didn't make that obvious before.

**Comment by frankie139506** [comment]
> > > > @NotMyFault Apologize, Can you reproduce this problem? I can't find where the problem is.
> > > 
> > > 
> > > There's no issue.
> > 
> > 
> > Thanks for your reply, I have done some simple checks and I will still fix it if there is any problem.
> 
> Bear in mind that "No issues" refers to the underlaying fix I mentioned before. Modifying the overall table style still has a negative impact on all tables. Apologizes if I didn't make that obvious before.

Apologize, I don't know what I need to change to. If I remove the space the dropdown button will be overwritten.

**Comment by basil** [comment]
> Apologize, I don't know what I need to change to.

I, too, share this contributor's confusion about what the action items are in order to move forward with this PR.

**Comment by daniel-beck** [comment]
It is unclear to me whether the issues referenced by @NotMyFault are still applying, but the current state modifies too many links. Comparing the current weekly and the PR build's About Jenkins pages to illustrate; it's likely other views in Jenkins are similarly impacted.

### Before

> Screenshot 2022-08-31 at 23 21 18

### After

> Screenshot 2022-08-31 at 23 21 14

**Comment by NotMyFault** [comment]
Daniel, you were faster, but yeah, some work is needed still.

In case my previous concerns got lost, the change as-is modifies two components, breadcrumbs and tables, impacting the latter in a bad way, see the now broken project overview header (misaligned of the status 'S'):
Screenshot 2022-08-31 at 23 17 17

**Comment by NotMyFault** [comment]
Hey @frankie139506,

thanks for your contribution. I'll go ahead and close this PR for now. Your changes are not lost, you are welcome to reopen it, once you have addressed the feedback given and your solution proposed is well tested, to ensure it doesn't introduce regressions in existing tables.

Thanks!

**Pull request closed without merging**
