### PR TITLE
JENKINS-17459: Clicking red/yellow/green icons link to the build Console

### PR DESCRIPTION
**Pull request by rcsalome**
Clicking on the build status icon in a job's "Build Time Trend" will now
take you to that build's console. This is the same behavior a user
expects when clicking on the build status icon in a job's "Build
History" widget.

See [JENKINS-17459](https://issues.jenkins-ci.org/browse/JENKINS-17459).

### Proposed changelog entries

* Add link to build's console page when clicking on build status in Build Time Trend

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### CODE REVIEW

**Review by oleg-nenashev — COMMENTED** [review]
It is nice to link somewhere, but maybe it should be the built root URL

**Comment by rcsalome** [comment]
Thanks for taking a look at this! Here is some more information:
1. I did not create https://issues.jenkins-ci.org/browse/JENKINS-17459, so I'm ok with another solution.
2. However, I do agree that from a UX standpoint, it is confusing that clicking on the status ball does not go to the same place.

image

In the screenshot above,
- If you click on the "blue ball" next to a build under the "Build History", then the link will take you to the console for that build.
- If you click on the "blue ball" next to a build under the "Build Time Trend", then nothing will happen.

The Reporter of JENKINS-17459 expected to be able to navigate to the console by click it.

In both "Build History" and "Build Time Trend", clicking on the "#X" number will take you to the build root URL.

**Comment by rcsalome** [comment]
I have attached an annotated screenshot. Not sure if my previous comment was clear.

image

This PR makes it so that clicking on both status balls goes to the "<buildNumber/console>"

**Review by oleg-nenashev — APPROVED** [review]
Thanks for the clarification! I am fine with the change then

**Review by daniel-beck — APPROVED** [review]
This view definitely needs the love, thanks!

**Review by res0nance — APPROVED** [review]

**Review by fcojfernandez — APPROVED** [review]

**Review by alecharp — APPROVED** [review]
Thanks for improving this!

**Comment by oleg-nenashev** [comment]
I plan to merge it tomorrow if no negative feedback. CI was green, I will make sure to take screenshots next time.

@rcsalome Is it a Hacktoberfest pull request just in case? Just to label it properly on our side. See [Hacktoberfest in Jenkins](https://jenkins.io/events/hacktoberfest). If you do not participate in it, please consider doing so. Your pull requests are much appreciated 👍

**Comment by rcsalome** [comment]
@oleg-nenashev , Thanks for the feedback! And yes, this was for Hacktoberfest. You can add the label.

**Comment by oleg-nenashev** [comment]
Thanks! And sorry for the delay due to Infra issues

**Pull request merged**
