### PR TITLE
[JENKINS-26278] Let a combobox display its drop-down when focused

### PR DESCRIPTION
**Pull request by ikedam**
[JENKINS-26278](https://issues.jenkins-ci.org/browse/JENKINS-26278)

A combobox displays its drop-down when its value is updated.
That is, a user needs to input a letter to see its candidate values. It isn't easy to use as the user have to know the first letter of the value he or she wants to use.

This change adds "displayonfocus" attribute to comboboxes, and a combobox displays its drop-down immediately when a user selects it if "displayonfocus" is set to true.

### CODE REVIEW

**Comment by jglick** [comment]
Why make it an option—when would you want this behavior disabled?

**Comment by ikedam** [comment]
> Why make it an option

I agree that it would be useful without an option.
I'll update the commit.

I worried that there are comboboxes displaying too large drop-downs without filters.
But I found that plugins can use auto-completion for those cases.

**Comment by jglick** [comment]
Seems to be a failure in `BuildListTableTest.linksFromFolders`?

**Comment by ikedam** [comment]
I don't know why `BuildListTableTest.linksFromFolders` fails.
My last commit should never affect the behavior as long as "displayonfocus" isn't specified...
I couldn't reproduce the failure in my environment.

I updated the commit that makes this behavior not optional and want to see whether the failure reproduces.

**Comment by ikedam** [comment]
Hmm...the test passed.
I'm not sure why the test for my last commit failed.

**Comment by daniel-beck** [comment]
Does this lead to more false positives in the detection of modified form elements?

**Comment by ikedam** [comment]
@daniel-beck 
Do you mean there's a known problem?
You may describe more details or point a related JIRA issue.

**Comment by daniel-beck** [comment]
@ikedam Most forms in Jenkins implement a check for user modifications so a popup can ask for confirmation before the user navigates away. If a form was not modified in any way, the popup should not show. This mostly works (except for AJAX-filled dropdown selections which I haven't been able to figure out).

So my question was whether this change will result in additional false positive form modification detections.

**Comment by ikedam** [comment]
@daniel-beck No, this doesn't activate the confirmation dialog, at least as far as I tested with Jenkins-1.595 on Firefox.
The confirmation dialog is activated when `input`, `select` or `textare` fields are changed. Dropdowns for comboboxes are implemented with`div` boxes.

**Comment by daniel-beck** [comment]
In that case :+1:

**Comment by oleg-nenashev** [comment]
:+1: from what I see

**Comment by oleg-nenashev** [comment]
Merged manually as https://github.com/jenkinsci/jenkins/commit/deecdb38d08e7e5f16fd9fd8ba161f020d26f047

**Pull request closed without merging**
