### PR TITLE
Hacktoberfest [JENKINS-66730] Un-inlining AsynchPeople/index.jelly

### PR DESCRIPTION
**Pull request by P4uline**
See [JENKINS-66730](https://issues.jenkins-ci.org/browse/JENKINS-66730).

### Proposed changelog entries

* Entry 1: Issue, Human-readable Text
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [n/a] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [n/a] Appropriate autotests or explanation to why this change has no tests
- [n/a] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by Wadeck — CHANGES_REQUESTED** [review]
Just to be sure this PR is not merged as is, the variables are not replaced as expected.

💡 I updated the "submitter" checklist, it's expected to be filled by the author ;)

**Comment by P4uline** [comment]
Thank you for you feedbacks. I just pushed some changes.
Screenshot 2021-10-30 at 21 33 45

**Review by Wadeck — CHANGES_REQUESTED** [review]
Unfortunately your screenshot does not include the "full page" and thus, does not show that the "blurb" was duplicated with the latest change.

🎉 The good news: the variables are working correctly 👍 

<details>

<summary>Screenshot</summary>



Screenshot_2021-11-01_091141_001
</details>

I tested locally, if you apply my proposed changes (both!) your PR will be working fine :)

**Review by oleg-nenashev — APPROVED** [review]
The new version looks mfine

**Review by Wadeck — APPROVED** [review]
Not manually re-tested but the change is what I expected, thanks for the changes! 🚀

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

----

Will merge in time for weekly if no objections

**Pull request merged**
