### PR TITLE
[JENKINS-62347](Hacktoberfest) Replace slave references from Non-English localization files

### PR DESCRIPTION
**Pull request by ShreyanBudhouliya**
##[JENKINS-62347](https://issues.jenkins-ci.org/browse/JENKINS-62347) Replace slave references from Non-English localization files

Non-English localization files include many 'slave' references which have been
replaced by the right term 'agent'.

### Proposed changelog entries

* Entry 1: Replace 'slave' with 'agent'

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@oleg-nenashev 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
Thanks for the pull request! According to to Google Translate, it should be "agente" in Portuguese

**Review by daniel-beck — CHANGES_REQUESTED** [review]
Please only submit changes for languages you actually speak. Text search & replace is not helpful.

**Comment by ShreyanBudhouliya** [comment]
@oleg-nenashev @daniel-beck I only have proficiency in English, sorry to attempt fixing the agent term for other languages. There's a bit confusion in some localized files where both  'slave' and non-english term for 'slave' have been used. 

I can close this PR if this is unnecessary.

**Comment by daniel-beck** [comment]
While we want to get rid of the term, we've had bad experiences in the past with low quality translations. I think it's more useful to keep this as a clear indicator these translations need updating than to mechanically replace them.

If we need to be rid of the term, as a workaround, we could always decide to remove old translations with this term altogether (and English will be used as fallback).

Please don't let this discourage you from contributing. Jenkins documentation (inside and outside the software) is great place to get started, and you can find some additional suggestions on https://www.jenkins.io/events/hacktoberfest/

**Comment by oleg-nenashev** [comment]
While we are here, I could get someone to verify the Portuguese localization. If other items are removed, this pull request could be landed as Portuguese-only localization

- I see the remaining "slave" references in the Turkish localization, so it is not ready.  I would recommend to revert it,
- Same for Chinese. Maybe this file is not actual anyway, actual localization is in https://github.com/jenkinsci/localization-zh-cn-plugin by @LinuxSuRen

**Comment by daniel-beck** [comment]
>  If other items are removed, this pull request could be landed as Portuguese-only localization

Do you speak Portuguese? I don't. @ShreyanBudhouliya doesn't. While we can look up words that doesn't help making the sentences grammatically correct.

**Comment by ShreyanBudhouliya** [comment]
@oleg-nenashev @daniel-beck I have removed every non-english `slave` term replacement except for Portuguese. 
Thanks.

**Comment by daniel-beck** [comment]
@ShreyanBudhouliya I thought you didn't speak Portuguese? How do you know the grammar is correct?

**Comment by ShreyanBudhouliya** [comment]
@daniel-beck I don't know the grammar, I just replaced the term with the google translated form.
I'll close this PR for a better translated replacement in future.

**Pull request closed without merging**
