### PR TITLE
JEP-224 GA system read permission

### PR DESCRIPTION
**Pull request by timja**
See [JEP-224](https://www.jenkins.io/jep/224).

See https://github.com/jenkinsci/jep/pull/297

See https://groups.google.com/g/jenkinsci-dev/c/qCJ7Qkn_D2s/m/2dXdE_LJAgAJ

### Proposed changelog entries

* Entry 1: JEP-224, Graduate Overall/SystemRead to GA status.
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [x] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [x] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by daniel-beck — CHANGES_REQUESTED** [review]
It is unclear what the benefit of enabling these by default is.

For me, "GA" and "enabled by default" are two different states, and while one is very likely to require the other, it's not the direction that this PR seems to imply.

Given how painful permissions management in Jenkins already is, adding to the permissions matrix should be carefully considered instead of making it a necessary part of declaring a feature GA. And in this case, we're not adding just one, but three permissions.

**Review by oleg-nenashev — COMMENTED** [review]
I have a weak preference towards enabling the permissions by default. At the same time, I agree with @daniel-beck that it is not required for making JEP-224 a GA. API cleanup is enough.

For permissions, I suggest to create a a separate PR for JEP-224 GA and to use this one for a wider discussion about permission defaults with the @jenkinsci/core team.

**Review by oleg-nenashev — APPROVED** [review]
👍 🥇

**Review by daniel-beck — APPROVED** [review]

**Review by res0nance — APPROVED** [review]

**Review by MarkEWaite — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Pull request merged**
