### PR TITLE
Fix proxy server name documentation

### PR DESCRIPTION
**Pull request by olivierdagenais**
# Background

(Skip to the next section if you don't enjoy seeing a mystery being unraveled. **SPOILER**: the butler did it!) 

I'm nearing the end of verifying proxy support for the [Jenkins TFS plugin](https://github.com/jenkinsci/tfs-plugin) and I thought I would update the [proxy documentation in the Jenkins wiki](https://wiki.jenkins-ci.org/display/JENKINS/JenkinsBehindProxy), so I could point my users to it.  As I started updating the page, I decided to look up what Jenkins itself had to say about this and here's what I found:

proxyservername-before

The above screenshot contains the following text:

> If your Jenkins server sits behind a firewall and does not have the direct access to the internet, and if your server JVM is not configured appropriately ([See JDK networking properties for more details](http://download.oracle.com/javase/6/docs/technotes/guides/net/properties.html)) to enable internet connection, you can specify the HTTP proxy server name in this field to allow Jenkins to install plugins on behalf of you. Note that Jenkins uses HTTPS to communicate with the update center to download plugins.
> 
> The value you submit here will be set as `http.proxyHost` system property. Leaving this field empty causes this property to be unset, which means Jenkins will try to connect to the host directly.
> 
> If you are unsure about the value, check the browser proxy configuration.

...so, naturally, I got curious about having overlooked this property during my testing and I can't find where Jenkins actually sets that property. (the only hits for `http.proxyHost` are in the documentation)

It looks like the file was originally added at r9915 on June 6th 2008, a.k.a. commit 7003cd8e0cb416c9d28f7e7c2dccfbe3bd48a93c, and, at the time, there was indeed code that did this in `PluginManager.java`:

``` java
    public void doProxyConfigure(@QueryParameter("proxy.server") String server, @QueryParameter("proxy.port") String port, StaplerResponse rsp) throws IOException {
        System.setProperty("http.proxyHost",Util.fixEmptyAndTrim(server));
        System.setProperty("http.proxyPort",Util.fixEmptyAndTrim(port));
        rsp.sendRedirect("./advanced");
    }
```

...but a week later came r10078 (commit 0543909074fe2fb2749cf40acc21721ea371e1e3) that fixed HUDSON-1841 by no longer setting properties and instead setting the `proxy` field (of type `ProxyConfiguration`), which is still around.
## Why bother?

The Jenkins Git plugin uses the `Jenkins.proxy` field to configure Git to use a proxy server (and has been doing so [for at least two years](https://github.com/jenkinsci/git-client-plugin/pull/116)) and soon the Jenkins TFS plugin will also do this; it would be nice to provide accurate guidance on configuring Jenkins and its plugins ONCE how to connect to a proxy server.
# The actual pull request

This pull request aims to correct the documentation for the proxy server in all the cultures that reference the `http.proxyHost` property, so I'm going to need some help from fluent speakers/writers for those I wasn't able to do (I'm fluently French and the Turkish one was almost identical to the English version):
- [x] default
- [ ] de
- [x] fr
- [ ] ja
- [ ] nl
- [ ] pt_BR
- [x] tr
- [ ] zh_TW
## Should we go further?

The first paragraph of the proxy server name documentation still talks about "JDK networking properties".  It seems to me we should at least deprecate that guidance.  It's possible that setting those properties is still the only way to get some of the plugins to make use of the proxy server, so we may not be able to remove that guidance entirely.

### CODE REVIEW

**Comment by olivierdagenais** [comment]
It looks like build 4019 failed due to `hudson.model.AbstractProjectTest.testConfiguringBlockBuildWhenUpstreamBuildingRoundtrip` receiving `java.net.SocketTimeoutException: Read timed out` while attempting to verify a page with HtmlUnit.

A cursory look at the other thread stacktraces and this test failure appears to be due to a race condition and I didn't touch any code anywhere near there, anyway.

So, what should I do?  Queuing another build feels like sweeping the issue under the carpet.

**Comment by daniel-beck** [comment]
@olivierdagenais We don't particularly care about flaky test failures clearly unrelated to the PR, so there's no problem here.

Thanks for the doc fix!

**Comment by daniel-beck** [comment]
I suspect there's something wrong with the "localized" file for the Turkish locale, so it should probably be deleted altogether.

**Comment by olivierdagenais** [comment]
> I suspect there's something wrong with the "localized" file for the Turkish locale, so it should probably be deleted altogether.

I replaced commit f673a3b with 82ea4f9.

**Comment by olivierdagenais** [comment]
Thank you for merging!  As for the remaining cultures, I have traced each file's addition to determine the original author.

**If you see your name here**, would you mind updating `core/src/main/resources/hudson/ProxyConfiguration/help-name_{culture}.html` to remove mentions of the `http.proxyHost` property, just like I did in the English version with this pull request?

- [ ] de (@swiest)
- [ ] ja (@ssogabe)
- [ ] nl (@sorokh)
- [ ] pt_BR (@russinholi)
- [ ] zh_TW (@tan9)

And just in case: @jenkinsci/translators 

Thanks!
\- Oli

**Comment by batmat** [comment]
Ping @damianszczepanik for the polish one. Thanks!

**Pull request merged**
