### PR TITLE
[FIXED JENKINS-38650] - Cleanup spelling in CLi commands + Javadoc updates

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Also adds some javadoc and since definitions.

https://issues.jenkins-ci.org/browse/JENKINS-38650

@jenkinsci/code-reviewers @pjanouse

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
The PR builder was screwed up somehow

**Comment by oleg-nenashev** [comment]
Well, that issue comes back :(

```
13:01:52 [INFO] Finished at: 2016-10-02T13:01:52-04:00
13:01:53 [INFO] Final Memory: 73M/763M
13:01:53 [INFO] ------------------------------------------------------------------------
13:01:53 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce (default) on project jenkins-war: Execution default of goal org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce failed: For artifact {null:null:null:jar}: The groupId cannot be empty. -> [Help 1]
13:01:53 [ERROR] 
13:01:53 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
13:01:53 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
13:01:53 [ERROR] 
13:01:53 [ERROR] For more information about the errors and possible solutions, please read the following articles:
13:01:53 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
13:01:53 [ERROR] 
13:01:53 [ERROR] After correcting the problems, you can resume the build with the command
13:01:53 [ERROR]   mvn <goals> -rf :jenkins-war
13:01:53 Build step 'Invoke top-level Maven targets' marked build as failure
```

**Comment by oleg-nenashev** [comment]
@daniel-beck @rtyler It seems that the VM provisioning at J-on-J is dead

**Review by olivergondza — APPROVED** [review]

**Comment by rtyler** [comment]
@oleg-nenashev infra@lists.jenkins-ci.org or INFRA in JIRA are the appropriate places to report issues with infrastructure. Fortunately I opened this email which I don't always do with PR mail

**Comment by oleg-nenashev** [comment]
Well, another CI fun: 

```
SEVERE: Unable to launch the agent for aNode
java.io.IOException: Node aNode has been deleted during the channel setup
	at hudson.slaves.SlaveComputer.setChannel(SlaveComputer.java:527)
	at hudson.slaves.SlaveComputer.setChannel(SlaveComputer.java:390)
	at hudson.slaves.CommandLauncher.launch(CommandLauncher.java:131)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:262)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by oleg-nenashev** [comment]
Or not... If somebody explains how my changes manage to cause such errors, I owe you a beer

**Comment by rtyler** [comment]
@oleg-nenashev I'm also confused. I retriggered the build on ci.jenkins.io as an experiment and we'll see what happens.

Perhaps the machine sizes are too small and Jenkins tests are just taking more resources now?

**Comment by daniel-beck** [comment]
Is this going to get merged any time soon? I don't want to have to rework #2578 (the PR that actually mentions `@since` fixes in the title :frowning_face:) twice.

**Comment by daniel-beck** [comment]
@oleg-nenashev ping

**Comment by oleg-nenashev** [comment]
@daniel-beck Sorry, I'm blocked by tests. Feel free to merge your PRs if the tests pass there. I will just re-merge it with master.

**Comment by oleg-nenashev** [comment]
BTW, I've referenced the merge conflict on the day you've created a PR ;)

**Comment by oleg-nenashev** [comment]
Just retriggered the CI instance. I'm feeling lucky

**Comment by oleg-nenashev** [comment]
Well, tests REALLY fail after this change.
Because Tests check the string.

**Comment by pjanouse** [comment]
@oleg-nenashev 
Can I help you to fix the tests?

**Comment by oleg-nenashev** [comment]
@pjanouse working on it

**Comment by oleg-nenashev** [comment]
Test failure on https://ci.jenkins.io is unrelated

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers Fixed the tests. A re-review is required

**Pull request merged**
