### PR TITLE
[JENKINS-19142] Prompt user whether to add the job to the current view

### PR DESCRIPTION
**Pull request by Vlatombe**
https://issues.jenkins-ci.org/browse/JENKINS-19142

@jenkinsci/code-reviewers 

This adds a checkbox in the new job screen, allowing the user to control whether the job will be added to the current view.

jenkins-37857

### CODE REVIEW

**Comment by jtnord** [comment]
what if the current view is based on a regex filter?

**Comment by Vlatombe** [comment]
If a regex is set then the checkbox will be unticked by default (see `isAddToCurrentView` method)

**Comment by daniel-beck** [comment]
PR build on Firefox 48:

screen shot 2016-09-01 at 10 03 47

**Comment by daniel-beck** [comment]
Naming of the file is inconsistent with the vast majority of existing Jelly files.

~1/6 have dashes, about half of them to separate a prefix (`config-`) from the rest. Almost all others are lowercase or camelCase. Underscores are only used as prefix (e.g. `_api.jelly`).

I therefore recommend something like `newJobButtonBar` or `newJob-buttonBar`.

**Comment by Vlatombe** [comment]
@daniel-beck Both fixed

**Comment by prashanth-sams** [comment]
Can anyone please me on this? 
http://stackoverflow.com/questions/39287316/how-to-launch-jenkins-as-an-admin

**Comment by batmat** [comment]
:+1: 

I'm not sure I find the rule of checking/unchecking by default is definitely the right ones, but as I can't come up with a better proposal, I'm fine with it. If someone finds a better way, it'll be quite easy to adjust as Vincent isolated that well in a small decision method.

**Comment by daniel-beck** [comment]
I think the defaults here are sensible. It's definitely a major improvement over the current situation.

Since the UI glitch has been resolved :+1:

**Comment by oleg-nenashev** [comment]
👍

**Pull request merged**
