### PR TITLE
Add the 'alt' attribute to the logo in the README.md

### PR DESCRIPTION
**Pull request by abhishekmaity**
missing 'alt' added to  at README.md

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/8497"></a>

### CODE REVIEW

**Review by NotMyFault — APPROVED** [review]
Thanks!

**Comment by abhishekmaity** [comment]
@NotMyFault Thank you

**Comment by MarkEWaite** [comment]
@abhishekmaity we prefer that the pull request description should match the content of the pull request and that the pull request should be submitted from a branch that is not the "master" branch.  You can learn more about that process in the ["Improve a plugin" tutorial](https://www.jenkins.io/doc/developer/tutorial-improve/).

We also prefer that the pull request checklist be completed and included in the pull request rather than being deleted.  Since this pull request was a minor change to documentation, I didn't worry about requiring that you insert the full pull request template.  Now that you've added significant changes and potentially incompatible changes, this pull request either needs to have those changes removed or it needs to be updated to use the pull request template

**Review by MarkEWaite — CHANGES_REQUESTED** [review]
Changes are much broader than expected for the pull request description.

I've cleared the approval from @NotMyFault because the changes require a complete new review.

**Review by NotMyFault — CHANGES_REQUESTED** [review]
> I've cleared the approval from @NotMyFault because the changes require a complete new review.

Thanks for the PR, but as Mark mentioned, you will want to work with branches which aren't the master branch to create individual sets of PRs.

Additionally, this PR cannot be reviewed or merged in its current state. It appears you replaced all occurrences of `new URL...` with `new URI...` which doesn't work. While every `URL` can also be an `URI`, not every `URI` is an `URL`.
To address the issue, an understanding of URIs and URLs is needed.

**Comment by abhishekmaity** [comment]
@NotMyFault @MarkEWaite actually I have already reverted my last commit regarding `URL` thing as I discovered I was going totally wrong. I therefore re-request review the change now.

**Comment by abhishekmaity** [comment]
> @abhishekmaity we prefer that the pull request description should match the content of the pull request and that the pull request should be submitted from a branch that is not the "master" branch. You can learn more about that process in the ["Improve a plugin" tutorial](https://www.jenkins.io/doc/developer/tutorial-improve/).
> 
> We also prefer that the pull request checklist be completed and included in the pull request rather than being deleted. Since this pull request was a minor change to documentation, I didn't worry about requiring that you insert the full pull request template. Now that you've added significant changes and potentially incompatible changes, this pull request either needs to have those changes removed or it needs to be updated to use the pull request template

@jenkinsci/core-pr-reviewers I hope I have addressed the concerns raised by reviewers. I have already removed the significant and incompatible changes and I'm once again sorry for the mess I did to simple PR

**Review by NotMyFault — APPROVED** [review]

**Review by MarkEWaite — APPROVED** [review]
Thanks!

**Pull request merged**
