### PR TITLE
[JENKINS-36923] Give ownership of bcpkix dependency to bouncycastle-apl plugin

### PR DESCRIPTION
**Pull request by stephenc**
See [JENKINS-36923](https://issues.jenkins-ci.org/browse/JENKINS-36923) follow-up to #2474 

@jenkinsci/code-reviewers @reviewbybees

Also matching PR to be made against bouncycastle-api plugin

### CODE REVIEW

**Comment by stephenc** [comment]
FYI PR builder will fail until we are ready to cut the coordinated releases

**Comment by andresrc** [comment]
:bee:

**Comment by alvarolobato** [comment]
:bee:

**Comment by jglick** [comment]
:bug:

```
org.junit.ComparisonFailure: expected:<...n":"1.1"}, {"name":"[]credentials","versio...> but was:<...n":"1.1"}, {"name":"[bouncycastle-api","version":"2.16.0-SNAPSHOT (private-a4b13398-stephenc)"}, {"name":"]credentials","versio...>
	at hudson.model.UsageStatisticsTest.compareWithFile(UsageStatisticsTest.java:155)
	at hudson.model.UsageStatisticsTest.roundtrip(UsageStatisticsTest.java:99)
```

**Comment by stephenc** [comment]
@jglick so I have to release https://github.com/jenkinsci/bouncycastle-api-plugin/issues/14 before I can fix that test... are you good to go once I have that fix as once I pull the trigger on https://github.com/jenkinsci/bouncycastle-api-plugin/issues/14 there is no going back, this will need to be merged for the 2.16 release

**Comment by stephenc** [comment]
```
diff --git a/test/src/test/resources/hudson/model/UsageStatisticsTest/plugins.json b/test/src/test/resources/hudson/model/UsageStatisticsTest/plugins.json
index 020d22d..31634e1 100644
--- a/test/src/test/resources/hudson/model/UsageStatisticsTest/plugins.json
+++ b/test/src/test/resources/hudson/model/UsageStatisticsTest/plugins.json
@@ -1 +1 @@
-[{"name":"ant","version":"1.2"}, {"name":"antisamy-markup-formatter","version":"1.1"}, {"name":"credentials","version":"1.18"}, {"name":"cvs","version":"2.11"}, {"name":"external-monitor-job","version":"1.4"}, {"name":"javadoc","version":"1.1"}, {"name":"junit","version":"1.2-beta-4"}, {"name":"ldap","version":"1.11"}, {"name":"mailer","version":"1.11"}, {"name":"matrix-auth","version":"1.1"}, {"name":"matrix-project","version":"1.4.1"}, {"name":"maven-plugin","version":"2.7.1"}, {"name":"pam-auth","version":"1.1"}, {"name":"script-security","version":"1.13"}, {"name":"ssh-credentials","version":"1.10"}, {"name":"ssh-slaves","version":"1.9"}, {"name":"subversion","version":"1.54"}, {"name":"translation","version":"1.10"}, {"name":"windows-slaves","version":"1.0"}]
\ No newline at end of file
+[{"name":"ant","version":"1.2"}, {"name":"antisamy-markup-formatter","version":"1.1"}, {"name":"bouncycastle-api","version":"2.16.0"}, {"name":"credentials","version":"1.18"}, {"name":"cvs","version":"2.11"}, {"name":"external-monitor-job","version":"1.4"}, {"name":"javadoc","version":"1.1"}, {"name":"junit","version":"1.2-beta-4"}, {"name":"ldap","version":"1.11"}, {"name":"mailer","version":"1.11"}, {"name":"matrix-auth","version":"1.1"}, {"name":"matrix-project","version":"1.4.1"}, {"name":"maven-plugin","version":"2.7.1"}, {"name":"pam-auth","version":"1.1"}, {"name":"script-security","version":"1.13"}, {"name":"ssh-credentials","version":"1.10"}, {"name":"ssh-slaves","version":"1.9"}, {"name":"subversion","version":"1.54"}, {"name":"translation","version":"1.10"}, {"name":"windows-slaves","version":"1.0"}]
```

is the remaining hunk of changes FTR

**Comment by jglick** [comment]
Can you just amend the test the mask out volatile details before comparing to the expected value? At least plugin versions. Probably it should just check syntax and look for one representative plugin.

**Comment by jglick** [comment]
:bee: (PR builder seems to be timing out)

**Comment by stephenc** [comment]
OK [let's close this out](https://github.com/jenkinsci/bouncycastle-api-plugin/pull/14#issuecomment-235517586)

**Pull request merged**
