### PR TITLE
Fix ProcessTreeKillerTest#doNotKillProcessWithCookie to work on Windows

### PR DESCRIPTION
**Pull request by slonopotamus**
### Proposed changelog entries

None

### CODE REVIEW

**Comment by slonopotamus** [comment]
I know that your Windows CI doesn't work since August but [failed to understand why it isn't fixed yet](https://github.com/jenkinsci/jenkins/pull/4155#issuecomment-534166988).

**Comment by oleg-nenashev** [comment]
> but failed to understand why it isn't fixed yet.

A part of my hall of shame

**Review by oleg-nenashev — APPROVED** [review]
LGTM. Since it is not covered by CI now, I will likely need to fix the PR builder first

**Review by res0nance — APPROVED** [review]
Looks alright, labeling on-hold till Windows CI works

**Review by oleg-nenashev — APPROVED** [review]
I confirmed manually that it work on my Windows 10 machine.
Probably it is enough to unblock it and to get it merged

**Review by timja — APPROVED** [review]

**Pull request merged**
