### PR TITLE
[JENKINS-25734] - Prevent NPE in Executor/causeOfDeath page on "expected thread death"

### PR DESCRIPTION
**Pull request by oleg-nenashev**
http://issues.jenkins-ci.org/browse/JENKINS-25734

The change does not fix the issue, but it suppresses NPE at least.

Signed-off-by: Oleg Nenashev o.v.nenashev@gmail.com

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
up. Any review to merge & forget?

**Comment by olivergondza** [comment]
I do not quite like the working of the message in case of `null` as it might be confusing when shown in a lot of different contexts. Should the argument really be `@CheckForNull` (it used to throw NPE before if I a not mistaken)?

**Comment by oleg-nenashev** [comment]
@olivergondza 
The issue has been caused by http://issues.jenkins-ci.org/browse/JENKINS-25734 , when <code>printThrowable()</code> is being called from <code>.../core/src/main/resources/hudson/model/Executor/causeOfDeath.jelly</code>. I could workaround this particular case, but I see plenty of other calls on UI with a potentially null parameter

**Comment by oleg-nenashev** [comment]
BTW, a message text could be changed to something like "No info about the exception" or something like that

**Comment by olivergondza** [comment]
The fact is that delegating `null` handling to clients would make the helper function less useful. I agree with "No exception details"/"No info about the exception".

**Comment by oleg-nenashev** [comment]
Updated the pull-request according to the discussion

**Comment by olivergondza** [comment]
LGTM

**Comment by jglick** [comment]
I would suggest just deleting this whole system of dead executors. It is obsolete as of (IIRC) 1.536, since each scheduled task now gets its own `Executor`. If there is an exception, send it to the log like anything else, and move on.

**Comment by oleg-nenashev** [comment]
> I would suggest just deleting this whole system of dead executors. 
It's definitely out of the scope of this change :)
BTW I'm :+1: for such change

**Comment by olivergondza** [comment]
I agree we should deliver this fix and address [JENKINS-28818](https://issues.jenkins-ci.org/browse/JENKINS-28818) later.

**Comment by daniel-beck** [comment]
:+1:

**Comment by jglick** [comment]
:+1:

**Pull request merged**
