### PR TITLE
[JENKINS-50504] WorkspaceList.inUse should be keyed by String not FilePath so leases survive agent reconnections

### PR DESCRIPTION
**Pull request by jglick**
See [JENKINS-50504](https://issues.jenkins-ci.org/browse/JENKINS-50504). Complements https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/101.

### Proposed changelog entries

* Do not offer a workspace lease to a new build if it is already in use by a (Pipeline) build running across an agent reconnection.

### CODE REVIEW

**Comment by jvz** [comment]
Looks logical, though I'm not familiar enough in this area to give a proper review.

**Review by daniel-beck — APPROVED** [review]

**Comment by jglick** [comment]
Would like to wait for the current build to pass, so it can be picked up in the downstream PR and we can make sure that passes.

**Review by abayer — APPROVED** [review]

**Comment by batmat** [comment]
Given approvals, I think we can merge it later today or so, if nobody objects in the meantime.

**Review by dwnusbaum — APPROVED** [review]

**Comment by daniel-beck** [comment]
@jglick Could you clarify whether we're waiting for an updated downstream PR?

**Comment by jglick** [comment]
@daniel-beck not any longer, it went green with a deployment from this PR.

**Pull request merged**
