### PR TITLE
Adapt to jenkinsci/remoting#490

### PR DESCRIPTION
**Pull request by daniel-beck**
See https://github.com/jenkinsci/remoting/pull/490

### Proposed changelog entries

* Remove support for `RoleChecker#check(RoleSensitive)` calls which were added again in Jenkins 2.319. All remoting `Callable` implementations need to perform an actual role check as documented at https://www.jenkins.io/doc/developer/security/remoting-callables/

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Still on hold?

**Comment by basil** [comment]
> Still on hold?

I believe so, as jenkinsci/remoting#490 has not yet been released.

**Comment by jglick** [comment]
@jeffret-b?

(We could set up CD for `remoting` except for the JAR signature aspect.)

**Comment by oleg-nenashev** [comment]
> (We could set up CD for remoting except for the JAR signature aspect.)

Remoting is released from the Jenkins Release Infra. Any Jenkins Core maintainer should be theoretically able to trigger the release now. CC @dduportal

**Review by oleg-nenashev — APPROVED** [review]
Approving since the upstream PR is merged anyway. Will assign to myself just in case I have some time for Jenkins during the Xmas break. No guarantees

**Comment by daniel-beck** [comment]
> Remoting is released from the Jenkins Release Infra. Any Jenkins Core maintainer should be theoretically able to trigger the release now. CC @dduportal

Having permissions to do so and the confidence I'm not about to do something foolish are two very different things 😉

**Comment by basil** [comment]
> Having permissions to do so and the confidence I'm not about to do something foolish are two very different things :wink:

There's nothing that builds confidence like getting a bug report that you've introduced a regression. :smile:

**Review by timja — APPROVED** [review]
Ready to go @daniel-beck ?

**Comment by daniel-beck** [comment]
@timja Works for me. Looks like we're just waiting for CI?

**Comment by timja** [comment]
> @timja Works for me. Looks like we're just waiting for CI?

created https://github.com/jenkins-infra/helpdesk/issues/2780

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Pull request merged**
