### PR TITLE
JENKINS-61806 Remove timestamp from page footer

### PR DESCRIPTION
**Pull request by 95jonpet**
See [JENKINS-61806](https://issues.jenkins-ci.org/browse/JENKINS-61806).

Removes the "Page generated" timestamp from the page footer.

There is no styling associated with the CSS class `page-footer__timestamp`, so there is no CSS to clean up.
The `getCurrentTime()` method is also used by `/core/src/main/resources/lib/layout/tabBar.jelly`, so it cannot be safely removed.
There are no other usages of the localized key `Page generated`. Thus, the translations can be deleted.

jenkins-no-timestamp-in-footer

### Proposed changelog entries

* Remove footer timestamp.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@fqueiruga 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by res0nance** [comment]
I recall this being somewhat controversial #4620

**Comment by 95jonpet** [comment]
I completely missed that PR as there is no mention of it in [JENKINS-61806](https://issues.jenkins-ci.org/browse/JENKINS-61806).

**Comment by oleg-nenashev** [comment]
CCed reviewers of the previous PR to restart the discussion

**Review by oleg-nenashev — APPROVED** [review]
After some testing on my local instance, I do not think we need this page any longer. Many pages already include non-static content (e.g. history and status widgets, logs, expandable forms, etc.), and this timestamp does not make much sense for them. We could return the timestamp as HTTP header, but I see no much value in keeping it in UI for common users

**Review by timja — APPROVED** [review]

**Review by jeffret-b — APPROVED** [review]

**Review by rsandell — APPROVED** [review]

**Comment by rsandell** [comment]
Though I still think some motivation should be explained in the ticket.

**Comment by oleg-nenashev** [comment]
@Wadeck @daniel-beck @fqueiruga Did your opinion change after the previous pull request? If not, there are 5 +1 and 2 -1s from what I can tell

**Comment by daniel-beck** [comment]
> there are 5 +1 and 2 -1s from what I can tell

We saw how well that approach worked in #4209.

I don't see anywhere discussing the specific feedback from either of the earlier PRs. Nothing has changed. Are we just considering the same change over and over until people are tired of voicing the same objections again?

**Comment by jglick** [comment]
Not sure I follow https://github.com/jenkinsci/jenkins/pull/4599#issuecomment-604929503 exactly but seems like this could be addressed simply by adding `FormValidation.ok(String)` to **User Defined Time Zone** indicating the current time in both the server TZ and the proposed user TZ?

As to https://github.com/jenkinsci/jenkins/pull/4599#issuecomment-603820574, we cannot just stuff every potentially useful bit of system information into every screen in Jenkins on the chance that some user will happen to encounter a bug, take a screenshot of the whole window (not just the region affected by the problem!), and attach it to a bug report, _and_ that this information will happen to be critical to diagnosis yet the user will neglect to mention it.

**Comment by res0nance** [comment]
> Not sure I follow [#4599 (comment)](https://github.com/jenkinsci/jenkins/pull/4599#issuecomment-604929503) exactly but seems like this could be addressed simply by adding `FormValidation.ok(String)` to **User Defined Time Zone** indicating the current time in both the server TZ and the proposed user TZ?

The `FormValidation` sounds like an elegant solution to the problem of being unable to see the time, which I would say is my biggest gripe about removing this

**Review by res0nance — APPROVED** [review]

**Review by fqueiruga — APPROVED** [review]
Can you clean up the CSS code? Thanks!

**Comment by 95jonpet** [comment]
> Can you clean up the CSS code? Thanks!

Sure thing.
Will look at this after work.

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
@daniel-beck  / @Wadeck the timezone property change was merged:

https://github.com/jenkinsci/jenkins/pull/4841

any remaining objections?

**Comment by Wadeck** [comment]
> any remaining objections?

The case where I used this information does not change, but **it's not blocking**. 

I still do not understand why we want to remove such information and there is no explanation of the reasoning in any of the related PR / tickets.

**Comment by timja** [comment]
For me it just looks really weird.

Nothing else I'm aware of adds information like that to the footer.

**Comment by jeffret-b** [comment]
The timestamp clutters the UI. It's always there for everyone but provides little value or gain. As mentioned, in some rare circumstances it has been useful. The timestamp footer isn't the right solution to that problem, though. It's better to remove it and clean things up.

**Comment by fqueiruga** [comment]
> I still do not understand why we want to remove such information and there is no explanation of the reasoning in any of the related PR / tickets.

The main reasoning is trimming the UI. Unnecessary clutter contributes to a bad user experience. If a piece of UI is really low value it should be considered for removal. Whether this is low value that's up for discussion.

**Comment by timja** [comment]
Thanks everyone for all the feedback and reviews across the 3 PRs this has existed in.

I think we're in a better place now with adding the current time to the timezone form validation, which was one of the main issues with the removal.

We have a large amount of positive feedback and no blockers,

Please feel free to speak up if you think there is a reason we shouldn't continue and we're happy to discuss it.

With that said, I'm marking this as ready for merge and we'll merge it after ~24 hours if there's no blocking feedback.

**Comment by oleg-nenashev** [comment]
To address comment from @Wadeck 

> I still do not understand why we want to remove such information

https://github.com/jenkinsci/jenkins/pull/4748#pullrequestreview-438616963 . Apart from cluttering of the UI, it becomes less and less relevant with dynamic content we gradually adopt in the Jenkins project (widjets, various AJAX stuff and so on). Personally I just see no much value in keeping it, and hence my approval

**Review by stellargo — APPROVED** [review]

**Pull request merged**
