### PR TITLE
[JENKINS-18032] Fix Delete Project from context menu when using CSRF defense

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-18032](https://issues.jenkins-ci.org/browse/JENKINS-18032)

Amends #798.

@reviewbybees

### CODE REVIEW

**Comment by kzantow** [comment]
:bee:

**Comment by jglick** [comment]
@rtyler I also tried `cherry-pick`ing this to the `2.0` branch, starting Jenkins on a fresh user dir, accepting the default security settings, no plugins, creating a freestyle project, and deleting it both from the sidebar link and the context menu—no problems.

(@daniel-beck BTW I was unable to `merge` due to conflicts. Should we not be routinely merging `master` into `2.0` to pick up trunk fixes? You know—_continuous integration?_)

**Comment by rtyler** [comment]
yey

**Comment by daniel-beck** [comment]
@jglick Merging master into 2.0 is in progress.

**Pull request merged**
