### PR TITLE
Backporting for LTS 2.277.4

### PR DESCRIPTION
**Pull request by bmunozm**
```
Fixed
-----

JENKINS-65336           Minor                   2.288 - Apr 13, 2021
        Load statistics timespan does not affect image
        regression
        https://issues.jenkins.io/browse/JENKINS-65336

JENKINS-65281           Minor                   2.285
        Update to xstream 1.4.16 to avoid security scanner complaints
        https://issues.jenkins.io/browse/JENKINS-65281

JENKINS-65021           Minor                   2.286 released on 30 Mar 2021
        Disabled dropdown items no longer look disabled
        regression
        https://issues.jenkins.io/browse/JENKINS-65021

JENKINS-56934           Minor                   2.288 - Apr 13, 2021
        Side panel "new View" link is no longer relative to the current folder
        https://issues.jenkins.io/browse/JENKINS-56934
```

### CODE REVIEW

**Comment by daniel-beck** [comment]
Please `cherry-pick -x` and provide a summary in the required format as documented in https://github.com/jenkins-infra/release/blob/master/.github/ISSUE_TEMPLATE/1-lts-release-checklist.md

**Comment by bmunozm** [comment]
> Please `cherry-pick -x` and provide a summary in the required format as documented in https://github.com/jenkins-infra/release/blob/master/.github/ISSUE_TEMPLATE/1-lts-release-checklist.md

Thanks @daniel-beck for pointing me to the documentation.

**Review by daniel-beck — CHANGES_REQUESTED** [review]
JENKINS-65327 has no reason to be here as it is a regression in 2.277.x (labeled because the next baseline is still undecided).

**Comment by jtnord** [comment]
unclear why we have some (the last 3) backports that are using the merge commit (and referencing the PR) whereas others are using individual commits.

**Comment by bmunozm** [comment]
@daniel-beck I updated the branch using `git cherry-pick -x`  please review again, so are yu suggesting to remove changes from JENKINS-65327 ? Do we need someone else "approval"?

@jtnord cherry-picks are different because there are some PRs merged and other ones squashed and merged. Any suggestion about how to manage it?

**Comment by daniel-beck** [comment]
> so are yu suggesting to remove changes from JENKINS-65327 ?

Yes, because the issue is not present in 2.277.x.

**Comment by bmunozm** [comment]
> JENKINS-65327

Removed!

**Comment by MarkEWaite** [comment]
I had to dig to remind myself how to generate the list of lts-candidate fixes in the expected format.  Steps that I took were:

1. Label the selected `lts-candidate` issues with the new label `2.277.4-fixed`
2. Run the lts-candidate-stats script from the root of the jenkins core repo
```
~/hub/release/backend-commit-history-parser/bin/lts-candidate-stats 2.277.4
```

That generated the following output:
```
Fixed
-----

JENKINS-65336           Minor                   2.288 - Apr 13, 2021
        Load statistics timespan does not affect image
        regression
        https://issues.jenkins.io/browse/JENKINS-65336

JENKINS-65308           Major                   2.288 - Apr 13, 2021, 2.289 - Apr 20, 2021
        Jenkins.trimLabels gets increasingly slower as number of nodes and labels increase
        https://issues.jenkins.io/browse/JENKINS-65308

JENKINS-65281           Minor                   2.285
        Update to xstream 1.4.16 to avoid security scanner complaints
        https://issues.jenkins.io/browse/JENKINS-65281

JENKINS-65021           Minor                   2.286 released on 30 Mar 2021
        Disabled dropdown items no longer look disabled
        regression
        https://issues.jenkins.io/browse/JENKINS-65021

JENKINS-56934           Minor                   2.288 - Apr 13, 2021
        Side panel "new View" link is no longer relative to the current folder
        https://issues.jenkins.io/browse/JENKINS-56934

```

**Review by MarkEWaite — APPROVED** [review]
Reviewed the changes and they look good to me.  Included in https://github.com/jenkins-infra/jenkins.io/pull/4280

**Review by olamy — APPROVED** [review]

**Review by MRamonLeon — APPROVED** [review]
LGTM

**Review by jtnord — APPROVED** [review]

**Comment by daniel-beck** [comment]
I'm not very confident about JENKINS-65308; as what's backported was replaced immediately in the weekly afterwards, meaning the backported code does not continue to soak and only users on exactly 2.288 would report issues with it.

**Comment by timja** [comment]
> I'm not very confident about JENKINS-65308; as what's backported is just two days old and therefore not usually eligible for backporting. (And the previous change for the issue was replaced immediately in the weekly afterwards, meaning it does not continue to soak and only users on exactly 2.288 would report issues with it.)

sure we can back it out, I can't see any reason to rush it in, unless @res0nance wants to weigh in?

**Comment by res0nance** [comment]
> > I'm not very confident about JENKINS-65308; as what's backported is just two days old and therefore not usually eligible for backporting. (And the previous change for the issue was replaced immediately in the weekly afterwards, meaning it does not continue to soak and only users on exactly 2.288 would report issues with it.)
> 
> sure we can back it out, I can't see any reason to rush it in, unless @res0nance wants to weigh in?

I'm fine with backing it out, I labelled it as lts-candidate at the request of a user. Not sure how many users this issue affects but doesn't seem large enough to warrant the risk.

**Comment by MarkEWaite** [comment]
+1 from me for backing out JENKINS-65308.  I've removed it from the [changelog pull request](https://github.com/jenkins-infra/jenkins.io/pull/4280) on the assumption that it will be removed here.

**Comment by daniel-beck** [comment]
Conditional approval: Without JENKINS-65308 this looks great.

**Comment by MarkEWaite** [comment]
> Conditional approval: Without JENKINS-65308 this looks great.

I've removed the `2.277.4-fixed` label from [JENKINS-65308](https://issues.jenkins.io/browse/JENKINS-65308) so that it is ready for @bmunozm to run the `lts-candidate-stats` script again and to rebase the commits to remove JENKINS-65308.

**Comment by v1v** [comment]
Sorry about the noise, but If it helps regarding [JENKINS-65308](https://issues.jenkins.io/browse/JENKINS-65308), we have recently upgraded our production Jenkins instances and so far so good, we are planing to increase the number of concurrent workers to see if the performance improvement keeps behaving as right now, which it's awesome. So far the 350 concurrent workers are doing great. 

So I wonder if the decision about this particular issue can be amended and added to the list of potential issues for this LTS change

**Comment by daniel-beck** [comment]
@v1v To clarify, is JENKINS-65308 a regression? If it is, that changes things for me. Right now it's just some random performance enhancement.

**Comment by res0nance** [comment]
> @v1v To clarify, is JENKINS-65308 a regression? If it is, that changes things for me. Right now it's just some random performance enhancement.

Its not a regression, it is a long standing issue with scalability with large numbers of labels and frequent additions and removal of nodes (so clouds or swarm). trimLabels itself has not been touched in 10 years.

> Sorry about the noise, but If it helps regarding [JENKINS-65308](https://issues.jenkins.io/browse/JENKINS-65308), we have recently upgraded our production Jenkins instances and so far so good, we are planing to increase the number of concurrent workers to see if the performance improvement keeps behaving as right now, which it's awesome. So far the 350 concurrent workers are doing great.
> 
> So I wonder if the decision about this particular issue can be amended and added to the list of potential issues for this LTS change

I'm +0 to backporting it for the reasons that this has not been in weeklies for long which introduces risk and yes though this may be a large performance benefit for some, the LTS line is meant to be a stable line so stability is more important here.

For users who this change is absolutely critical to their work, they may deploy 2.289 which has the change and likely the next LTS baseline will be 2.289.

**Comment by daniel-beck** [comment]
> Its not a regression, it is a long standing issue with scalability with large numbers of labels

Thanks for clarifying. In that case I'm tentatively against its inclusion (non-blocking vote) as before; especially since we're discussing whether to deliver the improvement into LTS in early May or early June.

**Comment by bmunozm** [comment]
I removed https://issues.jenkins.io/browse/JENKINS-65308 from this PR. Can you please review it again?

**Review by daniel-beck — APPROVED** [review]

**Review by res0nance — APPROVED** [review]

**Review by jtnord — APPROVED** [review]

**Review by MRamonLeon — APPROVED** [review]

**Review by MarkEWaite — APPROVED** [review]

**Pull request merged**
