### PR TITLE
[JENKINS-62661] Fix status filter migration

### PR DESCRIPTION
**Pull request by res0nance**
See [JENKINS-62661](https://issues.jenkins-ci.org/browse/JENKINS-62661).

Fix to a bug caused in #4466 

### Proposed changelog entries

* Entry 1: JENKINS-62661, Fix migration of status filter when coming from an older version of Jenkins

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@MarkEWaite @daniel-beck @TobiX 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by daniel-beck — APPROVED** [review]
Short term seems reasonable, long term I wonder whether this changes the result. Some filters add new entries to the list that weren't in the initial selection.

**Review by MRamonLeon — APPROVED** [review]

**Review by TobiX — APPROVED** [review]
Looks okay to me - if we want to preserve the original intent (insert at the start of the filter list), wouldn't it be "better" in the long term to add the `add(int, T)` method to the underlying List class?

**Review by alecharp — APPROVED** [review]

**Comment by res0nance** [comment]
> Looks okay to me - if we want to preserve the original intent (insert at the start of the filter list), wouldn't it be "better" in the long term to add the `add(int, T)` method to the underlying List class?

It currently throws an exception, I'm guessing there is a good reason as to why its not implemented.

**Comment by TobiX** [comment]
> It currently throws an exception, I'm guessing there is a good reason as to why its not implemented.

Probably more an artifact of the way "optional" features in Java's Collection API works...

But adding that is less of a minimal change, I think one has to enhance at least
https://github.com/jenkinsci/jenkins/blob/c431ccc9b4af2a7fdfe5979f9913df07f04906e0/core/src/main/java/hudson/util/CopyOnWriteList.java#L69-L73
and
https://github.com/jenkinsci/jenkins/blob/c431ccc9b4af2a7fdfe5979f9913df07f04906e0/core/src/main/java/hudson/util/PersistedList.java#L69-L74
and make sure that nothing breaks... (The latter has some fancy bridge-method-voodoo I'm unfamiliar with)

**Comment by res0nance** [comment]
> > It currently throws an exception, I'm guessing there is a good reason as to why its not implemented.
> 
> Probably more an artifact of the way "optional" features in Java's Collection API works...
> 
> But adding that is less of a minimal change, I think one has to enhance at least
> https://github.com/jenkinsci/jenkins/blob/c431ccc9b4af2a7fdfe5979f9913df07f04906e0/core/src/main/java/hudson/util/CopyOnWriteList.java#L69-L73
> 
> 
> and
> https://github.com/jenkinsci/jenkins/blob/c431ccc9b4af2a7fdfe5979f9913df07f04906e0/core/src/main/java/hudson/util/PersistedList.java#L69-L74
> 
> 
> and make sure that nothing breaks... (The latter has some fancy bridge-method-voodoo I'm unfamiliar with)

I had a separate implementation that recreates the DescribableList but it attempts to persist to disk which changes the config.xml before jenkins is fully loaded which will throw an exception. Implementing and using this feature might trigger the same behaviour but I'm uncertain as I'm not clear of how this bit of jenkins works exactly

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by daniel-beck** [comment]
@timja Could we merge this towards tomorrow's weekly, with a resulting chance it would be accepted by @olivergondza into the Wednesday RC? This fixes a data loss issue in 2.249.1 after all.

**Comment by MarkEWaite** [comment]
> @timja Could we merge this towards tomorrow's weekly, with a resulting chance it would be accepted by @olivergondza into the Wednesday RC? This fixes a data loss issue in 2.249.1 after all.

+1 from me to merge it into tomorrow's weekly in hopes of including it in Jenkins 2.249.1.  There are several reports of the problem from different paths and it would be much better to resolve them in 2.249.2 than to wait for 2.249.3.

**Comment by timja** [comment]
Yes let's do that.

**Comment by pjwiseman** [comment]
Doesn't work for me.  I tested an upgrade from 2.238 to 2.258.
* Install vanilla 2.238 (no plugins)
* Add a view with status filter
* Upgrade to 2.258.

**Comment by MarkEWaite** [comment]
@pjwiseman I took the steps that you described and saw that the views were preserved in Jenkins 2.258 and were not preserved in Jenkins 2.257.  I've placed more details at [JENKINS-62661](https://issues.jenkins-ci.org/browse/JENKINS-62661) and have placed a backup of the test Jenkins home directory on a [public web server](https://home.markwaite.net/~mwaite/jenkins-2.238.zip).

**Comment by pjwiseman** [comment]
My test was invalid.  I've re-tested and all is good now.  See [JENKINS-62661](https://issues.jenkins-ci.org/browse/JENKINS-62661) for details of my mistake.

**Pull request merged**
