### PR TITLE
[JENKINS-63562] Fix rare NPE

### PR DESCRIPTION
**Pull request by MRamonLeon**
See [JENKINS-63562](https://issues.jenkins-ci.org/browse/JENKINS-63562).

This is to put the fix to the NPE to the 2.249 LTS. It's a cherry-pick from 3ea9dc6b3ad4e158b19060f7f0f969577b5a22cf

### Proposed changelog entries

* Bug Fix. Fix NullPointerException pollution on logs if PluginDeprecationMonitor is enabled and some conditions are met

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@daniel-beck @batmat 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by daniel-beck** [comment]
> (Too minor)

If it's too minor we don't need it to be backported. This needs a changelog entry if there's going to be a backport.

**Comment by MRamonLeon** [comment]
> > (Too minor)
> 
> If it's too minor we don't need it to be backported. This needs a changelog entry if there's going to be a backport.

Right, I just used the text from the previous PR

**Review by daniel-beck — CHANGES_REQUESTED** [review]
This patch is a lot larger than what we need or want to have in LTS.

Cherry-picking ae9df1883e5736ce3057103e8bed3df178035eeb seems like a better idea.

**Comment by daniel-beck** [comment]
Removed author credit 👎

**Comment by batmat** [comment]
@MRamonLeon seems the commits don't look exactly the same as in the original PR, can you use `git cherry-pick -x` so we keep a log in the commit log of what the actual/original commits were please?

**Review by daniel-beck — APPROVED** [review]

**Review by batmat — APPROVED** [review]

**Review by varyvol — APPROVED** [review]

**Review by bmunozm — APPROVED** [review]

**Comment by olivergondza** [comment]
Thanks! This will be merged after 2.249.1 is released next Wednesday.

**Review by olivergondza — APPROVED** [review]

**Comment by MRamonLeon** [comment]
> Thanks! This will be merged after 2.249.1 is released next Wednesday.

Our aim was to get it merged in 2.249.1, to fix the regression. Is it still possible @olivergondza?

**Comment by batmat** [comment]
@olivergondza not sure what you mean: are you saying this fix is not eligible to 2.249.1, and will make it in 2.249.2 only? 
If so, should you mark [JENKINS-63563](https://issues.jenkins-ci.org/browse/JENKINS-63563) as `lts-rejected`?

**Comment by olivergondza** [comment]
Well, it is being discussed right now, and yes, I suggest rejecting this. We make such exceptions for impactful fixes, which is not the case.

Btw, where is the fix backported from? https://github.com/jenkinsci/jenkins/commit/ae9df1883e5736ce3057103e8bed3df178035eeb is not in master ad github says "This commit does not belong to any branch on this repository."? Also, the fix does not seem related to declared JENKINS-63563, not anything like this is part of its (unmerged) PR.

**Comment by daniel-beck** [comment]
> Btw, where is the fix backported from? ae9df18 is not in master

@olivergondza See PR description, it's the second commit of the squashed PR https://github.com/jenkinsci/jenkins/pull/4881/commits. I specifically requested this be reduced in scope and only backport the trivial NPE fix rather than the full PR.

**Comment by olivergondza** [comment]
Thanks, Daniel. Updating references to point to JENKINS-63562/#4881.

---

I am not convinced that Minor issue impacting a plugin test (with potential production impact with no reports) justifies backporting out of backporting window and cutting a second RC to retest. So yes, I pretty much suggest postponing this to .2.

**Comment by daniel-beck** [comment]
> I am not convinced that Minor issue … justifies backporting out of backporting window and cutting a second RC to retest

Given how trivial the fix is, would propose to include without second RC if this would make the cut in general. Unsure whether we do that though.

Impact is uncertain; while I believe it's limited to exceptions being logged when some pages are accessed while there's no UC data loaded (which is how I discovered this), I am not confident about it.

**Comment by MRamonLeon** [comment]
I think I can close it, right @olivergondza ?

**Comment by olivergondza** [comment]
@MRamonLeon, we are in a .2 backporting window right now and I still intend to include this. Unless you tell me otherwise.

**Comment by olivergondza** [comment]
Closing as this is part of https://github.com/jenkinsci/jenkins/pull/4946

**Pull request closed without merging**
