### PR TITLE
[JENKINS-68055] retain label expressions when trimming labels

### PR DESCRIPTION
**Pull request by res0nance**
See [JENKINS-68055](https://issues.jenkins-ci.org/browse/JENKINS-68055).

### Proposed changelog entries

* Preserve load statistics data for label expressions.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [x] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [x] Proper changelog labels are set so that the changelog can be generated automatically
- [x] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [x] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by basil — APPROVED** [review]

**Comment by MarkEWaite** [comment]
I ran interactive tests with this change and compared Jenkins 2.332.2 with a build including this pull request.  The change looks good.  Steps I took to exercise the change:

1. Define at least two agents with distinct labels (like `a` and `b` or `FreeBSD` and `OpenBSD`)
2. Define jobs that would keep those agents busy (`sleep 600` shell step)
3. Run those jobs
4. Watch the load statistics on the labeled graph for 10 minutes (since the reset happens at 5 minutes)
    * http://mark-pc2.markwaite.net:8080/label/FreeBSD%7C%7COpenBSD/load-statistics on 2.332.2 resets every 5 minutes
    * http://rhel-8-a.markwaite.net:8080/label/b%7C%7Ca/load-statistics on 2.343-snapshot with this change shows the graph without reset

My interactive testing of the [JENKINS-68055](https://issues.jenkins.io/browse/JENKINS-68055) indicates that this change fixes the reported problem.

I'll rely on others to review the implementation, especially with regard to performance.

**Comment by basil** [comment]
> I'll rely on others to review the implementation, especially with regard to performance.

I reviewed the implementation in my review, and it looks good to me. So can we get a second approval so I can start the merge timer?

**Review by MarkEWaite — APPROVED** [review]
> I reviewed the implementation in my review, and it looks good to me. So can we get a second approval so I can start the merge timer?

Approved.  Interactive testing looks good.

**Review by NotMyFault — APPROVED** [review]
Can confirm, working nicely.

**Comment by basil** [comment]
This PR is now ready for merge. We will merge it after approximately 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process. Thanks!

**Pull request merged**
