### PR TITLE
Update bundled JUnit Plugin (+ tons more) after security advisory

### PR DESCRIPTION
**Pull request by daniel-beck**
https://www.jenkins.io/security/advisory/2022-06-22/#SECURITY-2760

Presumably thanks to pointless BOM updates, this is a cascading mess of required updates.

Minimal testing -- I think @basil previously identified when I had screwed this up before? I don't remember how though.

### Proposed changelog entries

* Update bundled JUnit plugin from 1.47 to 1119.1121.vc43d0fc45561 for [security advisory](https://www.jenkins.io/security/advisory/2022-06-22/#SECURITY-2760).
* Update bundled Display URL API plugin from 2.3.5 to 2.3.6
* Update bundled Pipeline API plugin from 2.42 to 1144.v61c3180fa_03f
* Update bundled Plugin Utilities API plugin from 1.5.0 to 2.16.0
* Update bundled Checks API plugin from 1.1.1 to 1.7.4
* Update bundled ECharts API plugin from 4.9.0-2 to 5.3.2-1
* Update bundled SnakeYAML API plugin from 1.27.0 to 1.29.1
* Update bundled JQuery3 API plugin from 3.5.1-2 to 3.6.0-2
* Update bundled Font Awesome API plugin from 5.15.1-1 to 6.0.0-1
* Update bundled SCM API plugin from 2.6.5 to 602.v6a_81757a_31d2
* Update bundled Structs plugin from 1.23 to 308.v852b473a2b8c
* Replace bundled Bootstrap 4 API plugin 4.5.3-1 with Bootstrap 5 API plugin 5.1.3-6
* Replace bundled Popper.js API plugin 1.16.0-7 with Popper.js 2 API plugin 2.11.2-1
* Add bundled Pipeline Supporting APIs plugin 813.vb_d7c3d2984a_0

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/6678"></a>

### CODE REVIEW

**Review by basil — APPROVED** [review]

**Comment by basil** [comment]
#6180, #6480, and #6582 had changelog entries, so shouldn't this as well?

**Review by NotMyFault — APPROVED** [review]

**Comment by daniel-beck** [comment]
> If those were what you were referring to not pointless.

See the first commit for numerous minor/patch version updates.

**Comment by MarkEWaite** [comment]
> #6180, #6480, and #6582 had changelog entries, so shouldn't this as well?

Thanks for the reminder!  I've added proposed changelog entries for the updated components.

**Comment by basil** [comment]
> Thanks for the reminder! I've added proposed changelog entries for the updated components.

Thanks for adding proposed changelog entries, but the reminder was addressed to the submitter of this PR, who (per the [pull request template](https://github.com/jenkinsci/jenkins/blob/02f6f2dfcdec8b0c22e123a77845fd63737f5863/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L34-L35=)) is obligated to ensure that "changelog entries and upgrade guidelines are appropriate for the audience affected by the change […] and are in the imperative mood." While it is understandable that new contributors may not perfectly fulfill these obligations, I think we should expect regular contributors and especially core maintainers to fulfill these obligations.

---

The test history for this PR demonstrates just how unstable trunk has become, without a single green build so far after 14 test runs, but [PR build 13](https://ci.jenkins.io/job/Core/job/jenkins/job/PR-6678/13/) was successful other than a flake in `hudson.security.HudsonPrivateSecurityRealmSEC2566Test#noTimingDifferenceForInternalSecurityRealm`, and we know that is a flake because the Windows branch of testing passed in [PR build 3](https://ci.jenkins.io/job/Core/job/jenkins/job/PR-6678/3). In other words, between multiple test runs, all branches of the test suite have passed.

---

This PR is now ready for merge. We will merge it after approximately 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process. Thanks!

**Comment by daniel-beck** [comment]
> https://github.com/jenkinsci/jenkins/pull/6180, https://github.com/jenkinsci/jenkins/pull/6480, and https://github.com/jenkinsci/jenkins/pull/6582 had changelog entries, so shouldn't this as well?

FWIW I held off writing the changelog because I expected failures and the need to amend this.

**Pull request merged**
