### PR TITLE
Replace hetero-list YUI button and menu with new style button and tippy.js menu

### PR DESCRIPTION
**Pull request by mawinter69**
use new button style
replace the YUI menu with a tippy menu

Following plugins use the hetero-list-container and input button at some places without using the hetero-list.jelly. The input button is replaced by a jenkins button in javascript.
- dingtalk
- envinject
- branch-api
- scm-api
- multiple-scms
- pipeline-model-definition

#### Some Notes
- The tippy menu is inserted directly after the button for easier navigation for keyboard users.
- When using the "Tab" key to go through the page, once this selects a menu entry, this will become the selected entry. When you now use the "ArrowUp" or "ArrowDown" keys, focus will follow the selected entry.
- menualign attribute is now ignored (not sure what it was doing at all)

Before:
image
image

After:
image
image

### Testing done

Freestyle jobs
- Create freestyle project and goto configure
- Add post build step -> Corresponding form it inserted
- Add another post build step (previously inserted step is disabled)

Pipeline jpbs
- create a pipeline job
- go to "Pipeline Syntax" -> "Declarative Directive Generator"
- Select "options: Options" 
- Click "Add" -> "Timestamps" -> Corresponding form is inserted.
- Click "Generate Declarative Directive" -> Snippet is properly generated
- Select "tools: Tools" (This is not using the hetero-list.jelly but directly refers to relevant classes)
- New button/menu is used
- Click "Add" -> "Git"
- Click "Generate Declarative Directive" -> Snippet is properly generated

### Proposed changelog entries

- Replace hetero list YUI button and menu with new style button and tippy menu.

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/8340"></a>

### CODE REVIEW

**Review by yaroslavafenkin — COMMENTED** [review]
Looks OK security wise

**Comment by mawinter69** [comment]
> Looking good! I was working on something similar a while back but didn't get as far with it.
> 
> Few things -
> 
> It'd be nicer if the filter bar was more integrated with the menu, it's looking quite heavy at the moment. 

done
> 
> I haven't had a chance to run it yet but from the screenshots it looks like the menus width will change when you filter, it'd be nicer if the menu width was fixed so it won't change when the items change.

The Width changes with applied filters, but this was also the case before. Seems it is not possible with pure CSS to prevent this.

> 
> I think changing the item height to be smaller makes the usability harder, it'd be harder to click and for users will accessibility needs.

My intention was as there are no icons involved and the number of entries easily get over 20 (with flexible publish and any step plugins, I have here 23 entries in the menu) so I wanted it to be more compact. I increased the min-height now to 30px

**Review by timja — APPROVED** [review]
Really nice, love it

**Review by NotMyFault — APPROVED** [review]

**Comment by timja** [comment]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by basil** [comment]
This broke `org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SecureGroovyScriptTest` and `hudson.plugins.textfinder.TextFinderPublisherFreestyleTest#createTextFinderViaWebClient`

Reverted in #8412

Try again in the next weekly after ensuring that you are not breaking PCT

**Comment by daniel-beck** [comment]
> Try again in the next weekly after ensuring that you are not breaking PCT

If you're this strict about changes causing PCT regressions, this needs to be documented in https://github.com/jenkinsci/jenkins/blob/master/CONTRIBUTING.md and https://github.com/jenkinsci/jenkins/blob/master/.github/PULL_REQUEST_TEMPLATE.md.

**Pull request merged**
