### PR TITLE
Use `f:dropdownDescriptorSelector` for agent launcher

### PR DESCRIPTION
**Pull request by mawinter69**
avoid having a single help area describing all available launchers

### Proposed changelog entries

* Improve the display of help text for agent launch methods.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@jenkinsci/sig-ux 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by basil — APPROVED** [review]
Very nice!

**Review by NotMyFault — APPROVED** [review]
Really handy and improves readability a lot.

**Comment by basil** [comment]
This PR is now ready for merge. We will merge it after approximately 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process. Thanks!

**Comment by timja** [comment]
this broke the credentials pop up dialog in ssh credentials, https://github.com/jenkinsci/acceptance-test-harness/pull/763#issuecomment-1104127636

likely the javascript in credentials plugin is too fragile to markup.

**Comment by basil** [comment]
@mawinter69 Would you be able to address this in the SSH Credentials plugin? If not I will probably revert this in the next week or so.

**Comment by timja** [comment]
FWIW it's the credentials plugin that's broken but demonstrated by ssh build agents plugin, clarified above comment

(although possible the fix could be in ssh build agents)

**Pull request merged**
