### PR TITLE
[JENKINS-38812] - Support insensitive autocompletion for item selection

### PR DESCRIPTION
**Pull request by oleg-nenashev**
This is a restored version of #2587 from @DavidRutqvist. I somehow managed to close the PR by pushing to his branch, so I am recovering it here. Last state: I processed @daniel-beck's comments about toLowerCase() conversion without locale specification, but I have a concern about the comparison logic for German language:

> @daniel-beck I started implementing your comment, but then I realized we may have a problem with German language here: needle.length()>hay.length(). When the logic calls toLowerCase(), it may convert ß to ss, so that the string length may change in such operation, right?

See [JENKINS-38812](https://issues.jenkins-ci.org/browse/JENKINS-38812).

### Proposed changelog entries

* RFE: Use case-insensitive autocompletion for item selection dialogs if user profile requires case-insensitive search
* ...

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers

**Comment by daniel-beck** [comment]
@oleg-nenashev 

> When the logic calls toLowerCase(), it may convert ß to ss, so that the string length may change in such operation, right?

As to the specific example, ß is already lowercase as it only appears in the middle or end of words, SS is its uppercase form: http://www.fileformat.info/info/unicode/char/00DF/index.htm

At least until last year apparently, based on https://en.wikipedia.org/wiki/Capital_%C3%9F#Current_situation

As to similar constructs that get weird when lowercased, I don't know whether they exist.

**Comment by oleg-nenashev** [comment]
@daniel-beck thanks for feedback! In the worst case we will just get an improperly sorted list for case-insensitive mode. It's probably better than having a case-sensitive output anyway, so IMHO it can be merged even if there is such lowercase magic somewhere

**Comment by daniel-beck** [comment]
While we're at it, nobody in their right mind uses ß in item _names_ due to file system path problems with tools. (This is not the display name!)

**Review by Wadeck — APPROVED** [review]
:bee: LGTM

**Pull request merged**
