### PR TITLE
Submit button localization

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Maybe "Submit" by default? In such case we could cleanup Default usages in  code and move localizations from https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/hudson/model/AbstractModelObject/descriptionForm.jelly (12 languages)

Lame attempt to find buttons with "Submit" text: https://github.com/jenkinsci/jenkins/search?utf8=%E2%9C%93&q=%22f%3Asubmit+value%3DSubmit%22&type=

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers

**Comment by LinuxSuRen** [comment]
Maybe 'Submit' is better, already changed. @oleg-nenashev

**Comment by oleg-nenashev** [comment]
@LinuxSuRen would you like to move localizations from hudson/model/AbstractModelObject/descriptionForm.jelly and cleanup default as I proposed above? If no, I will create a follow-up ticket for that

**Comment by LinuxSuRen** [comment]
I'd love to do that. @oleg-nenashev

**Comment by LinuxSuRen** [comment]
@oleg-nenashev What's your suggest?

**Review by daniel-beck — APPROVED** [review]

**Comment by daniel-beck** [comment]
@LinuxSuRen Oleg is saying that `descriptionForm.jelly` overrode the label in a localizable manner, and its dozen or so resources files like `descriptionForm_*.properties` contain translations for this label already. Copying these contents into corresponding `submit_*.properties` will make all translations already apply this change.

**Comment by LinuxSuRen** [comment]
I know that mean, I just don't know other language. I can valid them through google translate.
@daniel-beck

**Comment by daniel-beck** [comment]
> I know that mean, I just don't know other language. I can valid them through google translate.

Well, if it's the same English text (Submit in both cases), it's likely to be correct, or at least close enough: Danish is 'Save', German is 'Apply', French, Spanish and Italian all seem to be 'Submit'. I think it's close enough to reuse it for this. IMO reuse of the equivalent translations for another UI element would still be a massive step forward, and a native speaker can always clean up the details.

> But I pretty sure zh_TW's translate is not mean 'Submit'.

送出 is 'Send' according to translate.google.com, which seems to be close enough (at least to the level we review it here). The site won't let me distinguish between traditional and simplified Chinese in the source language though, don't know whether that's a problem. Translating it to either simplified or traditional only results in a minor change (AFAICT) in the left character.

**Comment by daniel-beck** [comment]
To clarify, I think (and @oleg-nenashev seems to agree) that it would be nice if you could include it, but we're not requiring it. If you're uncomfortable with providing translations for languages you don't know, just tell us you'd rather not to this here and we'll do it in a separate followup PR.

**Comment by LinuxSuRen** [comment]
I’d love do that. I appreciate your patient. But that traditional Chinese translate is not suitable. Maybe that because of the original author using google site. I will modify it.

**Comment by daniel-beck** [comment]
@LinuxSuRen That was @tan9 in https://github.com/jenkinsci/jenkins/pull/716. Perhaps it's just a confusion about the context of the label? Then again, the same translation for Submit occurs in a bunch of different files.

**Comment by LinuxSuRen** [comment]
Oh, I see.

**Comment by daniel-beck** [comment]
> Then again, the same translation for Submit occurs in a bunch of different files.

To clarify, all of these translations contributed by the same author, so context doesn't seem to be the cause. Haven't checked beyond that PR.

**Comment by daniel-beck** [comment]
Now `descriptionForm.jelly` just needs to stop providing a custom label for `f:submit` and we should be good. 👍

**Review by oleg-nenashev — APPROVED** [review]
The button localization looks good to me. There are also other default value usages which could be cleaned up though: https://github.com/jenkinsci/jenkins/search?utf8=%E2%9C%93&q=submit+value%3D%22%24%7B%25Submit%7D%22&type=

**Comment by LinuxSuRen** [comment]
Most of them already be remoted. @oleg-nenashev

**Review by oleg-nenashev — APPROVED** [review]
LGTM assuming that we are fine with change of case in localizations. This part of localizations by editors is not clear to me, we are flip-flowing from "\u044f" to \u044F" and vice versa. But I cannot offer a good solution for that

**Comment by tan9** [comment]
@daniel-beck , @LinuxSuRen __Submit__ be translated to __送出__ is well-accepted in Taiwan, you can refer to [Microsoft Terminology collection](https://www.microsoft.com/en-us/language/Search?&searchTerm=submit&langID=Chinese%20Trad.%20(Taiwan)&Source=true&productid=All_Products) and find:

image

However, __提交__ is also acceptable.

**Comment by LinuxSuRen** [comment]
Ok, I get it.

**Comment by LinuxSuRen** [comment]
Any more suggestion? @oleg-nenashev

**Comment by oleg-nenashev** [comment]
I think it's ready to go according to @tan9's comment. Since the most of commits are atomic, merging without squash

**Pull request merged**
