### PR TITLE
Update node, npm, download-maven-plugin, & frontend-maven-plugin

### PR DESCRIPTION
**Pull request by jglick**
# Description

[Core build #324 failed](https://ci.jenkins.io/job/Core/job/jenkins/job/master/324/execution/node/47/log/?consoleFull) and I am not sure why—possibly a network problem?

@cliffmeyers suggested updating npm, and I am throwing in an update of node, and adaptations of https://github.com/jenkinsci/plugin-pom/pull/48, https://github.com/jenkinsci/plugin-pom/pull/50, and https://github.com/jenkinsci/plugin-pom/pull/53, just in case.

Tested a clean build of the `war` on a new user dir and all the setup wizard, new item, and stage view UI stuff seems fine.

### Changelog entries

None required.

### Desired reviewers

@jenkinsci/code-reviewers & @reviewbybees

### CODE REVIEW

**Comment by paladox** [comment]
This https://github.com/nodejs/nodejs.org/issues/1191 may be related to the network problem your describing.

**Review by kzantow — APPROVED** [review]
👍

**Comment by jglick** [comment]
@paladox thanks for link.

[INFRA-1139](https://issues.jenkins-ci.org/browse/INFRA-1139) got filed for the underlying problem.

**Comment by paladox** [comment]
Your welcome.

**Pull request merged**
