### PR TITLE
Remove partial (less than 5% complete) translations

### PR DESCRIPTION
**Pull request by daniel-beck**
### Proposed changelog entry:

> * Removed localizations with very low coverage: Albanian, Basque, Belarusian, Bengali, Esperanto, Galician, Georgian, Gujarati, Hindi, Icelandic, Indonesian, Irish, Kannada, Macedonian, Marathi, Mongolian, Occitan, Punjabi, Sinhala, Tamil, Telugu, Thai

---

Remove the following translations:

* Belarusian
* Bengali (India)
* Mongolian
* Occitan
* Punjabi (India)
* Shqip (Albanian)
* Esperanto
* Basque
* Irish (Ireland)
* Galician
* Gujarati (India)
* Hindi (India)
* Indonesian
* Icelandic
* Georgian
* Kannada
* Macedonian
* Marathi
* Sinhala
* Tamil
* Telugu
* Thai

All of these localizations have less than 100 keys translated (the best translated of these is Indonesian with 73 keys, or 4.17%), and no localized HTML help files.

Don't get me wrong -- It would be great if Jenkins were translated into these languages, but the current state of these localizations is just not useful to anyone: Users don't have enough to allow them to use even the common functionality of Jenkins in their own language, and anyone wishing to translate into these languages gets unnecessarily constrained by previous decisions without a substantial part of the work already done.

And it's not like they're in progress either: All of these translations have been contributed in 2013 or earlier, with the exception of @erral's #2731. (@erral If you decide to do some more work on this localization I'd be happy to restore these, and explain our tooling to get you started.) Otherwise, the few changes since then were some cleanup by @albers in 2014, and adaptations to changed code structure.

I don't think 100 keys/5% is the threshold after which a localization suddenly becomes useful, but this at least gets rid of the translations that never even tried to have reasonable coverage, often probably one person translating just a single screen (at most) via Translation Assistance.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
CC @KostyaSha regarding Belarusian. Maybe there are people who want to contribute to this area

**Review by oleg-nenashev — APPROVED** [review]
I would say the usefulness threshold is rather close to 50% than to 5%, but I agree with deletion of the translations. Alternative option would be to just comment the entries and then let translation contributors uncomment them if they feel the strings are useful

**Comment by daniel-beck** [comment]
I agree, but I think this should be a fairly uncontroversial change. And in some of the ~20-30% translations may be enough to make it reasonable to continue working on.

FTR, localizations by % done right now:

	sl - Done: 109(6.23%) Missing: 1620(92.52%) Orphan: 22(1.26%) Empty: 0(0.00%) Same: 0(0.00%) NoJenkins: 0(0.00%)
	el - Done: 112(6.40%) Missing: 1626(92.86%) Orphan: 12(0.69%) Empty: 0(0.00%) Same: 1(0.06%) NoJenkins: 0(0.00%)
	ro - Done: 123(7.02%) Missing: 1600(91.38%) Orphan: 28(1.60%) Empty: 0(0.00%) Same: 0(0.00%) NoJenkins: 0(0.00%)
	ar - Done: 130(7.42%) Missing: 1606(91.72%) Orphan: 15(0.86%) Empty: 0(0.00%) Same: 0(0.00%) NoJenkins: 0(0.00%)
	et - Done: 138(7.88%) Missing: 1582(90.35%) Orphan: 31(1.77%) Empty: 0(0.00%) Same: 0(0.00%) NoJenkins: 0(0.00%)
	pt - Done: 143(8.17%) Missing: 1591(90.86%) Orphan: 5(0.29%) Empty: 4(0.23%) Same: 8(0.46%) NoJenkins: 0(0.00%)
	ca - Done: 160(9.14%) Missing: 1555(88.81%) Orphan: 36(2.06%) Empty: 0(0.00%) Same: 0(0.00%) NoJenkins: 0(0.00%)
	he - Done: 190(10.85%) Missing: 1529(87.32%) Orphan: 32(1.83%) Empty: 0(0.00%) Same: 0(0.00%) NoJenkins: 0(0.00%)
	uk - Done: 245(13.99%) Missing: 1466(83.72%) Orphan: 40(2.28%) Empty: 0(0.00%) Same: 0(0.00%) NoJenkins: 0(0.00%)
	pt_PT - Done: 259(14.79%) Missing: 1467(83.78%) Orphan: 24(1.37%) Empty: 1(0.06%) Same: 0(0.00%) NoJenkins: 0(0.00%)
	nb_NO - Done: 270(15.42%) Missing: 1448(82.70%) Orphan: 32(1.83%) Empty: 1(0.06%) Same: 0(0.00%) NoJenkins: 0(0.00%)
	cs - Done: 264(15.08%) Missing: 1446(82.58%) Orphan: 38(2.17%) Empty: 1(0.06%) Same: 2(0.11%) NoJenkins: 0(0.00%)
	hu - Done: 286(16.33%) Missing: 1426(81.44%) Orphan: 39(2.23%) Empty: 0(0.00%) Same: 0(0.00%) NoJenkins: 0(0.00%)
	fi - Done: 294(16.79%) Missing: 1415(80.81%) Orphan: 40(2.28%) Empty: 2(0.11%) Same: 0(0.00%) NoJenkins: 0(0.00%)
	sk - Done: 319(18.22%) Missing: 1406(80.30%) Orphan: 25(1.43%) Empty: 0(0.00%) Same: 1(0.06%) NoJenkins: 0(0.00%)
	ko - Done: 345(19.70%) Missing: 1347(76.93%) Orphan: 56(3.20%) Empty: 2(0.11%) Same: 1(0.06%) NoJenkins: 0(0.00%)
	sv_SE - Done: 397(22.67%) Missing: 1302(74.36%) Orphan: 50(2.86%) Empty: 1(0.06%) Same: 1(0.06%) NoJenkins: 0(0.00%)
	lv - Done: 421(24.04%) Missing: 1300(74.24%) Orphan: 29(1.66%) Empty: 0(0.00%) Same: 1(0.06%) NoJenkins: 0(0.00%)
	it - Done: 434(24.79%) Missing: 1252(71.50%) Orphan: 46(2.63%) Empty: 1(0.06%) Same: 18(1.03%) NoJenkins: 0(0.00%)
	tr - Done: 459(26.21%) Missing: 1219(69.62%) Orphan: 55(3.14%) Empty: 6(0.34%) Same: 12(0.69%) NoJenkins: 0(0.00%)
	zh_CN - Done: 534(30.50%) Missing: 1169(66.76%) Orphan: 43(2.46%) Empty: 1(0.06%) Same: 4(0.23%) NoJenkins: 0(0.00%)
	nl - Done: 631(36.04%) Missing: 1019(58.20%) Orphan: 82(4.68%) Empty: 4(0.23%) Same: 15(0.86%) NoJenkins: 0(0.00%)
	ru - Done: 691(39.46%) Missing: 975(55.68%) Orphan: 78(4.45%) Empty: 0(0.00%) Same: 7(0.40%) NoJenkins: 0(0.00%)
	pl - Done: 736(42.03%) Missing: 1005(57.40%) Orphan: 1(0.06%) Empty: 1(0.06%) Same: 8(0.46%) NoJenkins: 0(0.00%)
	lt - Done: 748(42.72%) Missing: 962(54.94%) Orphan: 28(1.60%) Empty: 2(0.11%) Same: 11(0.63%) NoJenkins: 0(0.00%)
	fr - Done: 975(55.68%) Missing: 671(38.32%) Orphan: 75(4.28%) Empty: 12(0.69%) Same: 18(1.03%) NoJenkins: 0(0.00%)
	da - Done: 1082(61.79%) Missing: 593(33.87%) Orphan: 46(2.63%) Empty: 4(0.23%) Same: 25(1.43%) NoJenkins: 1(0.06%)
	de - Done: 1200(68.53%) Missing: 469(26.78%) Orphan: 56(3.20%) Empty: 3(0.17%) Same: 22(1.26%) NoJenkins: 1(0.06%)
	bg - Done: 1203(68.70%) Missing: 508(29.01%) Orphan: 40(2.28%) Empty: 0(0.00%) Same: 0(0.00%) NoJenkins: 0(0.00%)
	es - Done: 1279(73.04%) Missing: 409(23.36%) Orphan: 49(2.80%) Empty: 3(0.17%) Same: 11(0.63%) NoJenkins: 0(0.00%)
	zh_TW - Done: 1286(73.44%) Missing: 396(22.62%) Orphan: 48(2.74%) Empty: 0(0.00%) Same: 21(1.20%) NoJenkins: 0(0.00%)
	ja - Done: 1402(80.07%) Missing: 294(16.79%) Orphan: 21(1.20%) Empty: 4(0.23%) Same: 29(1.66%) NoJenkins: 1(0.06%)
	pt_BR - Done: 1425(81.38%) Missing: 263(15.02%) Orphan: 28(1.60%) Empty: 10(0.57%) Same: 25(1.43%) NoJenkins: 0(0.00%)
	sr - Done: 1478(84.41%) Missing: 69(3.94%) Orphan: 171(9.77%) Empty: 21(1.20%) Same: 12(0.69%) NoJenkins: 0(0.00%)

**Review by batmat — APPROVED** [review]
Agreed.

**Comment by KostyaSha** [comment]
> CC @KostyaSha regarding Belarusian. Maybe there are people who want to contribute to this area

No-no-no)

**Comment by erral** [comment]
It's ok on my side. 

I sent the pull-request to remove wrong translations, otherwise the Jenkins interface was completely useless in basque. So if you completely remove the basque translation it's OK. I have no plans to maintain the basque translation.

**Comment by albers** [comment]
I'm also fine with deleting these localizations.
They are not helpful and just bloat the sources.

**Comment by oleg-nenashev** [comment]
Ready to go then

**Comment by daniel-beck** [comment]
Merged master in after conflicts due to merging #2812.

**Comment by daniel-beck** [comment]
https://ci.jenkins.io/job/Core/job/jenkins/job/PR-2813/2/console

> GitHub has been notified of this commit’s build result

GHBS seems to be lying. The build is stable.

**Pull request merged**
