### PR TITLE
[JENKINS-27392] SimpleBuildWrapper.createLoggerDecorator

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-27392](https://issues.jenkins-ci.org/browse/JENKINS-27392)

Allows the Workflow `wrap` step to honor console decoration.

@reviewbybees

Snapshot information @ 804588a81ae7c87b2b0230018a58f00cac50a2f8:

```
main/pom/1.608-SNAPSHOT/pom-1.608-20150331.155129-2.pom
main/cli/1.608-SNAPSHOT/cli-1.608-20150331.155137-2.jar
main/cli/1.608-SNAPSHOT/cli-1.608-20150331.155137-2.pom
main/cli/1.608-SNAPSHOT/cli-1.608-20150331.155137-2-jar-with-dependencies.jar
main/jenkins-core/1.608-SNAPSHOT/jenkins-core-1.608-20150331.155258-2.jar
main/jenkins-core/1.608-SNAPSHOT/jenkins-core-1.608-20150331.155258-2.pom
main/jenkins-war/1.608-SNAPSHOT/jenkins-war-1.608-20150331.155326-2.war
main/jenkins-war/1.608-SNAPSHOT/jenkins-war-1.608-20150331.155326-2.pom
main/jenkins-war/1.608-SNAPSHOT/jenkins-war-1.608-20150331.155326-2.license.xml
main/jenkins-war/1.608-SNAPSHOT/jenkins-war-1.608-20150331.155326-2.license.html
main/jenkins-war/1.608-SNAPSHOT/jenkins-war-1.608-20150331.155326-2-war-for-test.jar
main/jenkins-test-harness/1.608-SNAPSHOT/jenkins-test-harness-1.608-20150331.155711-2.jar
main/jenkins-test-harness/1.608-SNAPSHOT/jenkins-test-harness-1.608-20150331.155711-2.pom
plugins/plugin/1.608-SNAPSHOT/plugin-1.608-20150331.155737-2.pom
```

### CODE REVIEW

**Comment by tfennelly** [comment]
:+1:

**Comment by stephenc** [comment]
:+1:

**Comment by tfennelly** [comment]
:+1: (just looking at the last commit)

**Comment by kohsuke** [comment]
:+1:

**Pull request merged**
