### PR TITLE
[JENKINS-34448] Fixed offlineCause race condition

### PR DESCRIPTION
**Pull request by pjanouse**
Please review, Pavel

### CODE REVIEW

**Comment by daniel-beck** [comment]
Issue has a full description: https://issues.jenkins-ci.org/browse/JENKINS-34448

**Comment by KostyaSha** [comment]
@stephenc cc

**Comment by stephenc** [comment]
:+1: AIUI

**Comment by KostyaSha** [comment]
i also faced weirdness of offline causes, but don't remember details, maybe it would solve it :) 👍

**Pull request merged**
