### PR TITLE
[JENKINS-63548] - Hacktoberfest: scroll bump css fix

### PR DESCRIPTION
**Pull request by naveennvrgup**
See [JENKINS-63548](https://issues.jenkins-ci.org/browse/JENKINS-63548).

### Proposed changelog entries

* Fixed the width of **body** tag to 100vw. This fixes the jerk in UI caused by switching to scroll mode. (ie., due to scroll bar getting displayed)  
* This UI change doesn't demand writing a test case
* Tested in both chrome and firefox

### before fix
before-fix-scroll

### after fix
after-fix-scroll

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@romenrg

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by romenrg — APPROVED** [review]
Just tested this locally and it seems to work fine.
Thanks @naveennvrgup !!

CC'ing @fqueiruga and @timja in case they also want to take a look at this proposed solution.

**Review by daniel-beck — CHANGES_REQUESTED** [review]
Based on the gifs this comes with a significant downside: As soon as there's a vertical scroll bar, there's also a horizontal scrollbar.

This seems like too big of a price to pay for not having a slight layout bump when resizing the window, as it would also manifest outside the resizing action.

**Comment by naveennvrgup** [comment]
@daniel-beck  Agreed. I considered a few options (mentioned below) each comes with a cost of their own. 

- padding a few pixels to the left + remove the padding when the scrollbar is visible
- or removing overflow-x when the scrollbar is visible

both of them will not work for the below scenario
hori-scroll

**Comment by naveennvrgup** [comment]
@romenrg Any ideas? I think the cons outweigh the pros.

**Review by fqueiruga — CHANGES_REQUESTED** [review]
I don't think setting the width to 100vw is a good idea, because it will never account for the scrollbar and will bring new weird scrolling issues across different browsers. FWIW I have never been a successful use of 100vw.

I'm more than open to experiment other approaches though.

**Comment by romenrg** [comment]
@daniel-beck well noted! I had missed that!
I have re-tested and it seems that the horizontal scrollbar does not appear when using Chrome, but it does on Firefox.

I've also been doing some more testing and I'm failing to reproduce the "bump" I had originally reported. It might be that the new layout of the jobs fixed that already?

If other can reproduce the bump and we consider this is still something to be solved, regarding alternative solutions, in the past something I've used `overflow-y: scroll;` to make the vertical scrollbar always visible (even when not needed) to prevent the "bump" caused when it appears

**Review by romenrg — CHANGES_REQUESTED** [review]
@daniel-beck well noted! I had missed that!
I have re-tested and it seems that the horizontal scrollbar does not appear when using Chrome, but it does on Firefox.

I've also been doing some more testing and I'm failing to reproduce the "bump" I had originally reported. It might be that the new layout of the jobs fixed that already?

If others can still reproduce the bump and we consider this is still something to be solved, then regarding alternative solutions, in the past something I've used for similar cases has been `overflow-y: scroll;`. Adding that to the HTML tag (or the body) would make the vertical scrollbar always visible (even when not needed) to prevent the "bump" caused when it appears; IIRC.

**Comment by naveennvrgup** [comment]
>  in the past something I've used for similar cases has been `overflow-y: scroll;`. Adding that to the HTML tag (or the body) would make the vertical scrollbar always visible (even when not needed) to prevent the "bump" caused when it appears; IIRC.

This seems like a good solution. I would like to know what others think of it

**Comment by fqueiruga** [comment]
I don't think this approach should go through. The current behaviour is standard IMO so there's no need to fix it. Always showing a scrollbar is a degradation I think.

**Comment by oleg-nenashev** [comment]
It is a valid Hacktoberfest PR even if the suggested approach does not get merged

**Comment by naveennvrgup** [comment]
> It is a valid Hacktoberfest PR even if the suggested approach does not get merged

So kind of you @oleg-nenashev . I will try to make some good contributions soon. Currently learning spring and how to create jenkins plugins .

**Pull request closed without merging**
