### PR TITLE
Avoid scrollbar in dropdown popups (page footer, log recorder)

### PR DESCRIPTION
**Pull request by zbynek**
Adds a wrapping `<div>` to have consistent paddingwith other dropdowns (e.g. the ones in sidebar) -- that avoids extra scrollbar  when a separator is present. The diff makes more sense [without whitespace changes](https://github.com/jenkinsci/jenkins/pull/8704/files?w=1).

<details><summary>Before:</summary>

image
image
image

</details>

<details><summary>After:</summary>

image
image
image

</details>

Footer popup introduced in this PR: https://github.com/jenkinsci/jenkins/pull/7989

### Testing done

Screenshot above.

### Proposed changelog entries

Avoid scrollbar in the version popup (page footer)

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [x] Explanation as to why this change has no tests: visual improvement only
```

### Desired reviewers

@janfaracik 

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Comment by zbynek** [comment]
Obviously it's OK to not have this in the changelog as it doesn't affect functionality, I filled the "proposed changelog" entry just in case.

**Review by MarkEWaite — APPROVED** [review]

**Comment by mawinter69** [comment]
The same problem can be seen in the menu of log recorders:
image
I think the root cause is that the [jenkins-dropdown__separator](https://github.com/jenkinsci/jenkins/blob/742e95d735ab4b4d56b829bfd2007126e8a266f2/war/src/main/scss/components/_dropdowns.scss#L76) has a negative margin for left and right. When setting the margin to 0 the problem disappears.
But maybe there was a reason for that margin value. If so then the logrecorder index.jelly should be fixed as well

**Comment by mawinter69** [comment]
I think the reason for the negative margin is to extend the separator to the edges when it is wrapped in a <div class="jenkins-dropdown">. The div adds some padding  so that highlighted rows (hovering with the mouse over a row) have some gap. So the div should be added to the log recorder as well

**Comment by zbynek** [comment]
@mawinter69 thanks, I changed the code to use the same wrapping div in all usages of `overflowButton`, even those without separator, to have consistent look. My conclusion was the same as yours -- the negative margin compensates for the outer div padding.

**Review by NotMyFault — APPROVED** [review]

**Review by timja — APPROVED** [review]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Pull request merged**
