### PR TITLE
[FIXED JENKINS-24783] add new jelly to render action floatingBoxes, add ...

### PR DESCRIPTION
**Pull request by pure-marcmac**
...to index.jelly for Computer.

Placed to float directly to the left of the offline/online node control

### CODE REVIEW

**Comment by daniel-beck** [comment]
@oleg-nenashev Could you elaborate what kind of compatibility loss you expect here?

**Comment by daniel-beck** [comment]
Seems this has been abandoned? @oleg-nenashev @pure-marcmac ?

**Comment by daniel-beck** [comment]
Closing due to lack of response.

**Comment by oleg-nenashev** [comment]
Sorry, missed the original ping 19 days ago.
Not sure what I've meant. After re-review I just have a concern about copy-pasting the compatibility magic from AbstractProject (see the comment in jelly)

**Comment by daniel-beck** [comment]
So whatever we're doing here, we should not just copy the file from somewhere else including the compatibility hacks because that other file was messed up when it was created. This should be done cleanly.

**Comment by daniel-beck** [comment]
PR appears to have been abandoned, closing.

**Pull request closed without merging**
