### PR TITLE
Graphs now scale correctly for high-DPI screens

### PR DESCRIPTION
**Pull request by janfaracik**
### Proposed changelog entries

* Graphs now scale correctly on high resolution screens.

### Comparison (open the images in new tabs to really see the difference)

Before
image

After (on a MacBook Pro)
image

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by res0nance** [comment]
The screenshots look identical to me

**Comment by janfaracik** [comment]
> The screenshots look identical to me

You'll need to open the images in new tabs to really see the difference, the new graph endpoint supports a `scale` parameter which means that devices with high resolution screens can now receive the high res imagery they need to look good :)

**Comment by daniel-beck** [comment]
Looks fine in principle, thanks for taking this on!

I wonder whether this can be accomplished without having to adjust all the callers though. Aren't other plugins, like JUnit, essentially calling the same API, and will need the same adjustments if we go with this approach?

**Review by oleg-nenashev — APPROVED** [review]
Works on my machine, thanks!
Should we consider it as RFE or as a bugfix?

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
>  like JUnit

JUnit uses echarts

Looking at this change it seems callsites need to be updated

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Review by StefanSpieker — APPROVED** [review]

**Pull request merged**
