### PR TITLE
Second backporting for LTS 2.361.1

### PR DESCRIPTION
**Pull request by krisstern**
The below entries are the new ones added in this 2nd backporting. 

```
Fixed
-----

JENKINS-69276           Minor                   2.365
        No focus state on signin page checkbox (regression in 2.361)
        regression
        https://issues.jenkins.io/browse/JENKINS-69276

JENKINS-69250           Minor                   2.366
        JS error during setup wizard because of keyboard shortcuts (regression in 2.361)
        regression
        https://issues.jenkins.io/browse/JENKINS-69250
```

### Desired reviewers

@basil @alecharp @timja @NotMyFault 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7063"></a>

### CODE REVIEW

**Review by basil — APPROVED** [review]

**Review by MarkEWaite — APPROVED** [review]

**Review by timja — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]
https://github.com/jenkinsci/jenkins/pull/7063/commits/30b38a66a51733abc6d33bbec2d45540c6343453 can't be integrated as-is, because of prettier changes.

Probably better to use the post-prettier version, because recent stable branches have been prettier-ized too?

**Comment by krisstern** [comment]
Pretty sure the Jenkins build has not been successful because of some dependencies for `yarn` (`yarn lint`) on project jenkins-war according to the traceback: https://github.com/jenkinsci/jenkins/blob/stable-2.361/war/yarn.lock. Not sure which version to upgrade though.

**Comment by krisstern** [comment]
@NotMyFault How do I do that?

**Comment by krisstern** [comment]
Thanks @NotMyFault!

**Pull request merged**
