### PR TITLE
Remove deprecated and unused jenkins.widgets.HistoryPageFilter.add(java.util.List)

### PR DESCRIPTION
**Pull request by basil**
### Problem

`jenkins.widgets.HistoryPageFilter.add(java.util.List)` was deprecated in favor of `jenkins.widgets.HistoryPageFilter.add(Iterable)` in #2456, but a handful of test callers were never converted.

### Solution

This PR completes the transition by converting all remaining test callers to the new method. With that, the old method is completely unused and can be deleted. I verified this both within this repository (including in Jelly widgets) and by searching for sources and binaries within the broader Jenkins ecosystem.

### Searching for API usages in sources

I verified there were no references to an `add` method in any of these Jelly files:

```
core/src/main/resources/hudson/widgets/BuildHistoryWidget/entries.jelly
core/src/main/resources/hudson/widgets/HistoryWidget/ajaxBuildHistory.jelly
core/src/main/resources/hudson/widgets/HistoryWidget/all.jelly
core/src/main/resources/hudson/widgets/HistoryWidget/entries.jelly
core/src/main/resources/hudson/widgets/HistoryWidget/entry.jelly
core/src/main/resources/hudson/widgets/HistoryWidget/index.jelly
core/src/main/resources/jenkins/widgets/HistoryPageFilter/ajaxBuildHistory.jelly
core/src/main/resources/jenkins/widgets/HistoryPageFilter/entries.jelly
core/src/main/resources/jenkins/widgets/HistoryPageFilter/queue-items.jelly
```

I also ran [this search](https://github.com/search?ref=simplesearch&type=Code&q=user%3Ajenkinsci+%22HistoryPageFilter%22) to verify there were no references to `HistoryPageFilter` anywhere besides Jenkins core.

### Searching for API usages in binaries

Creating `/tmp/additionalClasses` with

```
jenkins/widgets/HistoryPageFilter
```

then using `jenkins-infra/usage-in-plugins` to look for usages in plugins, including those in CloudBees CI, with

```bash
mvn process-classes exec:exec -Dexec.executable=java -Dexec.args='-classpath %classpath org.jenkinsci.deprecatedusage.Main --additionalClasses /tmp/additionalClasses --onlyIncludeSpecified --updateCenter https://jenkins-updates.cloudbees.com/update-center/envelope-core-oc/update-center.json?version=2.263.2.3,https://jenkins-updates.cloudbees.com/update-center/envelope-core-mm/update-center.json?version=2.263.2.3'
```

produced no references.

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by daniel-beck** [comment]
The upside of this change is looks tiny compared to a bad downside, even if unlikely.

**Comment by MarkEWaite** [comment]
I agree with @daniel-beck .  I think the test changes in the pull request are a good thing, but we should not remove the deprecated method because the risk of issues for privately built plugins and plugins whose source is not hosted in the GitHub jenkinsci organization is greater than the benefit of removing the unused method.

**Comment by basil** [comment]
I am not going to take [FUD](https://en.wikipedia.org/wiki/Fear,_uncertainty,_and_doubt) like this seriously. This change is safe. If you don't want it, don't merge it.

**Comment by MarkEWaite** [comment]
> I am not going to take [FUD](https://en.wikipedia.org/wiki/Fear,_uncertainty,_and_doubt) like this seriously. This change is safe. If you don't want it, don't merge it.

I believe that one of the key reasons for the success of Jenkins is that it takes great efforts to retain compatibility from version to version.  User investments are preserved as they upgrade from older versions to later versions.

When an API is removed from Jenkins, any plugin that uses that API will fail to load.  Retaining an unused API seems like a lower risk to Jenkins users than the development benefit of removing that API.

Having said that, it is worth noting the counterpoint.  There are recent and noteworthy exceptions to my view of Jenkins compatibility.  We've intentionally accepted that Jenkins 2.277.1 will use divs for form layout instead of tables.  We've intentionally accepted that 2.277.1 use the Spring Security framework instead of the acegi security framework.  We've intentionally accepted that 2.277.1 will use upstream XStream instead of the XStream fork.  We've intentionally accepted that 2.277.1 will use JQuery 3.5 instead of JQuery 2.1.

**Comment by basil** [comment]
If removing this method causes even a single regression, I'll eat my hat.

**Comment by timja** [comment]
So I guess, who wants to take a chance on seeing @basil eat his hat?

**Comment by daniel-beck** [comment]
I'm not blocking this pull request. As I wrote, it's unlikely. In terms of code search, @basil has done everything that could be expected. I've simply seen too many instances of "nobody would ever think of doing THAT"…

**Comment by MarkEWaite** [comment]
> I'm not blocking this pull request. As I wrote, it's unlikely. In terms of due dilligence, @basil has done everything that could be expected. I've simply seen too many instances of "nobody would ever think of doing THAT"…

No block from me, either, then.  Thanks for the clarification.

**Review by oleg-nenashev — COMMENTED** [review]
No strong opinion. 

This a minor on the peripherals of the codebase. The method does not implement any logic under the hood, it is just a wrapper which does not impact code complexity much. At the same time it is hard to find a use-case for using this API externally, the code is not really designed for extensibility (`addInternal` is private).

**Review by jglick — APPROVED** [review]
If there are no usages in @jenkinsci and it has been deprecated for a while, I think it is fine to remove.

**Review by olamy — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Review by oleg-nenashev — APPROVED** [review]
No objections regarding the merge

**Pull request merged**
