### PR TITLE
Johnbel

### PR DESCRIPTION
**Pull request by JohnbelMDev**
See [JENKINS-XXXXX](https://issues.jenkins.io/browse/JENKINS-XXXXX).

### Proposed changelog entries

- human-readable text

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [x] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [x] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [x] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [x] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [x] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Comment by JohnbelMDev** [comment]
This update includes the latest versions for dependencies and plugins

**Comment by MarkEWaite** [comment]
Closing this pull request.  It does not follow the contributing guidelines and does not complete the pull request template.

**Comment by MarkEWaite** [comment]
@JohnbelMDev if you describe what you were trying to accomplish,  that may help others coach you to create a successful pull request.  The volume of unrelated changes in this pull request was too great for me to spend time trying to extract your original intent from the mix of changes that are included in the pull request.

**Comment by JohnbelMDev** [comment]
The pull request currently lacks a clear focus and appears to contain a
significant number of unrelated changes. To help reviewers understand the
purpose of this pull request and provide constructive feedback, please
clarify the intended goal.

Some helpful information to include:

   - *What specific problem are you trying to solve?* (e.g., bug fix, new
   feature, performance improvement, refactoring)
   - *What are the key changes being made?* (e.g., specific files modified,
   algorithms added or removed, functionality changed)
   - *How do these changes address the identified problem?* (e.g., explain
   the logic behind the modifications, provide examples of how the code
   behaves differently)

By providing this context, you enable reviewers to:

   - *Quickly understand the purpose and scope of the changes.*
   - *Focus their attention on the most relevant parts of the code.*
   - *Offer more targeted and helpful feedback.*

Ultimately, clarifying the intent of this pull request will increase its
chances of being successfully reviewed and merged.

Thank you.


-Johnbel Mahautiere

**Pull request closed without merging**
