### PR TITLE
[FIX JENKINS-27739] Clear cached env vars when node goes online

### PR DESCRIPTION
**Pull request by daniel-beck**
PR #1559 cleared the cached node environment on `connect()`, but that only got called when Jenkins launches the slave itself, resulting in all JNLP slaves never refreshing their node environment. `JnlpSlaveAgentProtocol.Handler.jnlpConnect(Computer)` doesn't work like that.

So I moved the environment cache reset to a new `ComputerListener`'s `onOnline(…)`.

@reviewbybees

### CODE REVIEW

**Comment by olivergondza** [comment]
:+1:

**Comment by daniel-beck** [comment]
Just changed the commit message as the original one was describing an outdated approach.

**Comment by oleg-nenashev** [comment]
:+1:

**Comment by jtnord** [comment]
isn't this a little late in the game?

The listeners are called in a non-deterministic order IIRC and so another listener may have been called first which may do something with the computer that may envolve interacting with the environment>

**Comment by daniel-beck** [comment]
bq. isn't this a little late in the game?

Possibly. Unfortunately there's no better way that I could find. My initial attempt added a `@Restricted(…) void resetCachedEnvironment()` to `Computer` which was called from `SlaveComputer.setChannel()` … which I considered worse than this.

**Comment by daniel-beck** [comment]
Amended PR following @jtnord's comment to ensure the listener runs as early as possible.

**Comment by jtnord** [comment]
:+1:

**Comment by daniel-beck** [comment]
Test failure appears unrelated.

**Pull request merged**
