### PR TITLE
Lessen the severity of the unavailable update message

### PR DESCRIPTION
**Pull request by daniel-beck**
This both makes the "Unavailable" presentation looks less like an error, and adds a note about being unavailable even on the latest release to the (now unfortunately quite wordy) message.

### Before

Screenshot 2021-05-13 at 18 13 21

### After

Screenshot 2021-05-13 at 18 12 37

### Proposed changelog entries

* Explain that some plugin updates can be unavailable even on the latest version of a given release line (i.e. LTS).

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by jvz — APPROVED** [review]

**Comment by timja** [comment]
> I don't have screenshots because I cannot figure out how to make it regenerate CSS from less 😭 Trying with a PR build.

https://github.com/jenkinsci/jenkins/blob/master/CONTRIBUTING.md#building-frontend-assets

**Comment by daniel-beck** [comment]
Figured it out; https://github.com/jenkinsci/jenkins/pull/5051 created the `.less` file but a ton of stuff was just copied from old-school CSS files and left there, which seem to be used preferentially. Why the duplication, I have no idea.

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Review by oleg-nenashev — APPROVED** [review]
no objections, it is definitely an improvement compared to the original message

**Review by StefanSpieker — APPROVED** [review]

**Pull request merged**
