### PR TITLE
Remove the broken packaging testing temporarily

### PR DESCRIPTION
**Pull request by rtyler**
This needs to be reworked a bit to accomodate more modern versions of Jenkins
Pipeline

### CODE REVIEW

**Comment by rtyler** [comment]
@reviewbybees

**Comment by oleg-nenashev** [comment]
Maybe it's better to just comment it out.
But 👍

**Comment by rtyler** [comment]
@oleg-nenashev there are other issues, I need to rework some of the packaging to begin with. I'll tackle that with this PR later this evening

**Comment by KostyaSha** [comment]
Ideally disabling stages would be a right feature.

**Comment by oleg-nenashev** [comment]
> Ideally disabling stages would be a right feature.

I suspect it's a pretty easy feature after change by @svanoort (block-scoped stages)

**Comment by svanoort** [comment]
👎  Fix rather than remove - I can assist with this.   What's wrong with it, specifically?

**Comment by rtyler** [comment]
@svanoort This Jenkinsfile is currently completely broken and has not been actually in-use in our ci.jenkins.io environment until last week.

Because of this crazy tight coupling with stuff in the packaging repository I don't think it's "fixable" so much as "needs rewriting". If you want to get on IRC and work through this, then I'm happy to do that, but the coupling with jenkinsci/packaging makes this nearly impossible to fix inside of just one repository. and one pull request.

I am going to remove everything but the unit tests so we at LEAST have sane pull request validation right now.

**Comment by svanoort** [comment]
> Because of this crazy tight coupling with stuff in the packaging repository I don't think it's "fixable" so much as "needs rewriting".

I'm still unclear about what the concrete problem *is* here -- what do you feel demands a rewrite?  How would you propose to test packaging & environmental behavior without coupling to the packaging repo?  

I would agree that it's worth a refactor and/or probably a bit of work on the packaging side to simplify or harden the test code.  

> I am going to remove everything but the unit tests so we at LEAST have sane pull request validation right now.

My understanding was that packaging tests would not run against PRs, just master branch(es) -- so putting that in place seems reasonable. 

> IRC

Apparently I was kicked off -- I'll hop on and chat a bit so we can discuss an action plan; but to be clear, a unilateral "fix now or I remove" is not readily addressed immediately.  Especially when it's been developed over a while by multiple participants (I think this flavor was @abayer working with feedback from several of us).

**Comment by svanoort** [comment]
To clear: the reason I push for this is that we have had actual problems identified by these tests, and without them, there's nearly zero coverage for SEV-1 issues such as JENKINS-33776 which are linked to platform, packaging, or container.  If anything we should be running them far more rather than making it less likely.

@rtyler Not sure how closely you've looked at the tests in the packaging repo, but they're covering fairly fundamental things ("Can jenkins start?"  and "Does Jenkins respond to HTTP requests?" and "When I run a service command, does Jenkins return the right error code and output?")

If someone can provide a better way of testing those things I'm 100% behind it and will  buy them 🍻 -- but in general failures in the packaging tests are results of real, known issues.

**Comment by rtyler** [comment]
> My understanding was that packaging tests would not run against PRs, just master branch(es) -- so putting that in place seems reasonable.

Yeah, env variables guard against packaging tests during pull request validation but not _packaging_ itself.

[This is broken](https://github.com/jenkinsci/jenkins/blob/master/Jenkinsfile#L83), [this](https://github.com/jenkinsci/jenkins/blob/master/Jenkinsfile#L88-L91) doesn't work in ci.jenkins.io (and is unclear whether it ever worked. [This relies on Copy Artifact plugin](https://github.com/jenkinsci/jenkins/blob/master/Jenkinsfile#L137-L140) which has no reason to be installed in ci.jenkins.io, but seems to exist in the `Jenkinsfile` from a time (long ago, galaxy far away) when stash/unstash wasn't working properly with containers.

[This is an anti-pattern](https://github.com/jenkinsci/jenkins/blob/master/Jenkinsfile#L146-L147) (IMHO) which couples this `Jenkinsfile` immensely close to what's in the packaging repo. [There's a sudo call which concerns me](https://github.com/jenkinsci/packaging/blob/master/workflow/installertest.groovy#L350) hidden away in there too.

If there is a need for sharing this `installertest.groovy` code, and not just sticking it into the `Jenkinsfile` here, then a Shared Library would be a better means of implementing this. But as of right now, there are no public consumers of `installertest.groovy` or any of its functionality so I'm inclined to simply remove what's cruft and move the rest into the `Jenkinsfile` here.


@svanoort The fundamental issue is that *this Jenkinsfile has not been used in any recent history for the project*. So concerns about removal of snippets are not based on the current reality for our ci.jenkins.io environment.

I am trying to get this `Jenkinsfile` into a position where it can sanely run after merge, but nothing has run after merge (ever, as far as I can tell) other than standard Maven targets.

**Comment by abayer** [comment]
I'm a 👍 on this, fwiw.

**Comment by svanoort** [comment]
👍  for now -- I've got WIP in #2560 that *should* work but since docker on the build agents appears unable to pull base images (even by direct shell call, i.e. "docker pull") I am going to go ahead and merge for sanity's sake.

**Pull request merged**
