### PR TITLE
[FIXED JENKINS-45895] - JNLPLauncher config.jelly should not display Work Dir settings when included from other class

### PR DESCRIPTION
**Pull request by oleg-nenashev**
See [JENKINS-45895](https://issues.jenkins-ci.org/browse/JENKINS-45895).

Honestly I think it is a misbehavior of the Docker plugin, which includes the configuration in such improper way: https://github.com/jenkinsci/docker-plugin/blob/master/docker-plugin/src/main/resources/com/nirima/jenkins/plugins/docker/launcher/DockerComputerJNLPLauncher/config.jelly#L8 . But I would prefer to fix it in the core since it hammers community ratings of the weekly and the Docker Plugin is rather dead than alive.

No tests for hacks

### Proposed changelog entries

* Entry 1: JENKINS-45895, Bug - Modify the JNLPLauncher configuration page in order to workaround regression in Docker Plugin (regression in 2.72).
* ...

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@reviewbybees

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Review by ghost — APPROVED** [review]
:bee:

**Comment by oleg-nenashev** [comment]
@reviewbybees done

Need some feedback from @jenkinsci/code-reviewers since it hammers community ratings

**Comment by oleg-nenashev** [comment]
Will merge tomorrow if nobody responds

**Comment by oleg-nenashev** [comment]
Merging it. It is not going to make the things worse at least.

**Pull request merged**
