### PR TITLE
Make changelog URL a build parameter

### PR DESCRIPTION
**Pull request by aldaris**
This is an attempt to resolve [JENKINS-24469](https://issues.jenkins-ci.org/browse/JENKINS-24469) (which is potentially a duplicate of [JENKINS-12429](https://issues.jenkins-ci.org/browse/JENKINS-12429), i.e. display the stable changelog URL in the upgrade available notificiation when stable version of Jenkins is currently being used.
After the patch is applied, LTS releases should be built using the lts-release Maven profile (-Plts-release).

This is a follow-up changeset for #1045 , unfortunately I didn't quite see how the Jenkins.getVersion() could be used to detect if the release is stable (contains two dots??), so this approach is modifying the build process instead.

### CODE REVIEW

**Comment by aldaris** [comment]
I suppose this won't get merged, so I may as well just close this PR for you.

**Comment by jglick** [comment]
I do not see any particular reason for this to be considered invalid, why was it closed?

Please be patient, PRs much older than this one have gotten attention once someone had a few minutes to spare.

**Comment by kohsuke** [comment]
+1 looks good to me

**Comment by aldaris** [comment]
Truth to be told I've made the rookie mistake of creating this PR from my master branch, which then got stuck on a given revision for a good while. Since then I force pushed my master to be up-to-date with the upstream repo, and I pretty much given up on this change.
When I get some time I'll try to apply these changes to the latest master (IIRC after a few months it had merge conflicts...) and open a new PR for it and link it here.

**Comment by daniel-beck** [comment]
@aldaris Awesome, thanks! Ping we specifically when you've done this. I got KK to review this and he's fine with it, and we'll then fix the release scripts accordingly.

**Comment by aldaris** [comment]
@daniel-beck The new PR is ready, see #1812

**Pull request closed without merging**
