### PR TITLE
Fix formatting issues and improve code readability

### PR DESCRIPTION
**Pull request by LakshanSS**
## Purpose 
Improve code readability by fixing formatting issues.

## Changes Done
- Remove unwanted new lines
- Fix lines exceeding max length

### CODE REVIEW

**Comment by pzygielo** [comment]
I see only changes in formatting, so I find commit message misleading.
Could you name refactoring that you applied here?

**Comment by LakshanSS** [comment]
Hi @pzygielo. Thanks for reviewing. I removed unwanted new lines and fixed where line length exceeded max length. These changes will improve code readability.

**Review by varyvol — APPROVED** [review]

**Comment by daniel-beck** [comment]
> exceeded max length

According to whose definition?

**Comment by daniel-beck** [comment]
This does not appear to add sufficient value to outweight the downside of creating merge conflicts between release lines, impacting security fix development and LTS backports, as well as merge conflicts with open PRs.

I recommend this be closed.

**Pull request closed without merging**
