### PR TITLE
[JENKINS-32357 - WiP] Section tabs for job configs - phase 1

### PR DESCRIPTION
**Pull request by tfennelly**
Hoping to make job config navigation a bit easier (not as suckie). See [JENKINS-32357](https://issues.jenkins-ci.org/browse/JENKINS-32357).

screenshot 2016-01-15 14 01 47

We're thinking of this as being "phase 1" i.e. that we think we'll want/need to do another round of improvements after. IOW ... no need for hysteria if it's not "perfect" straight-off :smile: 

**TODO:**
- [x] Basic tabs on jobs, **without** breaking form submission. As expected, issues to resolve, but all seem to be UX glitches i.e. nothing seems "broken".
- [x] Update the "Save" and "Apply" button texts to be more explicit about what will be saved e.g. "Save Job Configuration" or just "Save All". [See comment from @jtnord](https://github.com/jenkinsci/jenkins/pull/1978#issuecomment-171629813).
- [x] Toggle "classic" config view on/off. i.e. allow people to switch back to the old toilet-roll view.
- [x] Fix expanding/collapsing optional subsections. [See this](https://youtu.be/Kup043PhN38?t=115). A bit unsure as to whether we are handling this properly. Added a task to the "Hope TODOs" below.
- [x] Hide the original section titles
- [ ] Add a "filter" option to aid finding relevant config sections i.e. removing section tabs that do not contain what you are looking for etc
- [ ] Lots of JS unit and integration testing. **UPDATE**: More added.

**Hope TODO:**
- [ ] Fix quirky ACE editor rendering bug e.g. create a Worflow job and go to the workflow. The editor doesn't open properly - clicking on it or resizing the page makes it render properly. Changing `config-tabbar.js` to not use the `Behaviour` rule seems to fix it (but breaks other things). Strange one.
- [ ] Expanding/collapsing optional subsections are working better (see TODOs above), but I'm not totally confident we're catching things properly as all of this `row-set-start` and `row-set-end` stuff is really off-the-charts-funky ( :sob: ).

### CODE REVIEW

**Comment by jtnord** [comment]
@tfennelly looks good, however a concern I would have is that it is not obvious that the save/apply applies to the whole job configuration rather than just the active tab.  This is probably obvious to existing Jenkins users, but for those new to Jenkins it is less so.
Also at some point in Jenkins N.0 (n>2) I could see the config submission actually being split up so you could modify the triggers separately from the workflow, or the reporting (so could confuse users again if they get used to this is for the whole form).

**Comment by KostyaSha** [comment]
@jtnord +

**Comment by tfennelly** [comment]
@jtnord @KostyaSha yeah that's a possibility. @daniel-beck made a similar comment.

The only way we can help with that situation that I can see (at the moment) without breaking form submission, is to put some clarification text below the buttons, or to change the button text to be more explicit e.g. "Save Job Configuration".

**Comment by KostyaSha** [comment]
Introduce small icons or text color that will indicate that something edited in each tab.

**Comment by tfennelly** [comment]
@KostyaSha That might be something we could do in a future iteration. Either way (if I understand what you are saying), I don't think that helps clarify (for the user) what will happen on pressing the "Save" button i.e. the user may still have the same "what will be saved" question raised by @jtnord.

**Comment by tfennelly** [comment]
Moved to a new branch ( [tfennelly/jenkins/2.0-with-config-tabs](https://github.com/tfennelly/jenkins/tree/2.0-with-config-tabs) - based off #1995 - uses the same JS build hooks introduced in #1995 ) now. 

Will create a new PR once #1995 is merged.

**Pull request closed without merging**
