### PR TITLE
[FIXED JENKINS-43936] Only migrate legacy users once per restart

### PR DESCRIPTION
**Pull request by fbelzunc**
# Description

See [JENKINS-43936](https://issues.jenkins-ci.org/browse/JENKINS-43936).

I am not sure about how to test here that the new code is not reading from disk multiple times, but only one.

### Changelog entries

Proposed changelog entries:

* Migrate legacy users only once per restart to improve performance of the user retrieval logic

### Submitter checklist

- [x] JIRA issue is well described
- [x] Link to JIRA ticket in description, if appropriate
- [x] Appropriate autotests or explanation to why this change has no tests
- [ ] For new API and extension points: Link to the reference implementation in open-source (or example in Javadoc)

### Desired reviewers

@reviewbybees CC @stephenc @jglick

### CODE REVIEW

**Comment by rsandell** [comment]
:bee:

**Review by jtnord — APPROVED** [review]
:bee:

**Review by oleg-nenashev — APPROVED** [review]
Looks reasonable 🐝 
@reviewbybees done

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers are you fine with the merge towards the weekly?

**Comment by MarkEWaite** [comment]
+1

**Pull request merged**
