### PR TITLE
[JENKINS-51608] - Improve diagnostics of errorneous cases in ClassicPluginStrategy#getShortName()

### PR DESCRIPTION
**Pull request by oleg-nenashev**
See [JENKINS-51608](https://issues.jenkins-ci.org/browse/JENKINS-51608). Just some diagnostics for https://github.com/jenkinsci/configuration-as-code-plugin/issues/242 . Ideally we should generalize Manifest management logic in Jenkins. We already have similar code in CWP, PCT, and Pipeline Utility Steps (CC @raul-arabaolaza @rsandell ), so maybe a lib would be reasonable

### Proposed changelog entries

* RFE: Improve diagnostics of corrupted plugin archives during plugin dynamic loading
* ...

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@reviewbybees @MadsNielsen @ndeloof @ewelinawilkosz

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@MadsNielsen deployed it as WAR `2.126-20180530.122835-1` and Core `2.126-20180530.122814-1`

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers

**Comment by rsandell** [comment]
@oleg-nenashev yes, there already is an API available, it is located in the package `java.util.jar.*` :smirk: :stuck_out_tongue:

**Comment by oleg-nenashev** [comment]
@rsandell  heh. Will create a follow-up ticket

**Comment by oleg-nenashev** [comment]
@reviewbybees and @jenkinsci/configuration-as-code-plugin-developers

**Review by MarkEWaite — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Thanks @MarkEWaite !

**Pull request merged**
