### PR TITLE
[JENKINS-26520] Documentation fix for $BUILD_ID

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-26520](https://issues.jenkins-ci.org/browse/JENKINS-26520)

@reviewbybees

### CODE REVIEW

**Comment by jtnord** [comment]
:+1:

**Comment by jglick** [comment]
Hmm:

    Build timed out (after 180 minutes). Marking the build as aborted.

**Comment by stephenc** [comment]
:+1:

**Comment by oleg-nenashev** [comment]
:+1: Better late than never

**Pull request merged**
