### PR TITLE
[JENKINS-71666] Adapt to Popper deprecation in Jenkins core

### PR DESCRIPTION
**Pull request by debayangg**
See [JENKINS-71666](https://issues.jenkins.io/browse/JENKINS-71666). It removes the deprecated Popper api from war/pom.xml.

### Testing done

Tests passed
Note: Only light-test was performed

### Proposed changelog entries

- Remove deprecated Popper API.

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [x] The Jira issue, if it exists, is well-described.
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [x] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [x] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [x] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [x] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@MarkEWaite @NotMyFault 

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]
Thanks!

**Review by NotMyFault — APPROVED** [review]

**Comment by MarkEWaite** [comment]
This PR is now ready for merge.  We will merge it after approximately 24 hours if there is no negative feedback.

**Comment by basil** [comment]
> **Testing done**
> Tests passed
> Note: Only `light-test` was performed

In general, any changes to the list of detached plugins should be tested as in e.g. #8724:

> Ran `mvn clean verify -Dtest=jenkins.install.LoadDetachedPluginsTest,jenkins.model.StartupTest` (including un-ignored `LoadDetachedPluginsTest#noUpdateSiteWarnings`) locally.

`LoadDetachedPluginsTest#noUpdateSiteWarnings` is an important test for detached plugins, but it is not run as part of normal automation because otherwise new security warnings would fail unrelated builds.

As a one-time courtesy, I have run this test locally and verified that it passed. In the future, please ensure that proper testing is done as part of the review process.

**Comment by MarkEWaite** [comment]
> In the future, please ensure that proper testing is done as part of the review process.

Will do.  Thanks!

**Pull request merged**
