### PR TITLE
[JENKINS-45472] Copy the list in case it's reused elsewhere

### PR DESCRIPTION
**Pull request by daniel-beck**
See [JENKINS-45472](https://issues.jenkins-ci.org/browse/JENKINS-45472).

### Proposed changelog entries

Unclear. For now, this is to get a PR build.

### Submitter checklist

- [ ] Appropriate autotests or explanation to why this change has no tests

### Desired reviewers

@markewaite

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Comment by daniel-beck** [comment]
@mtarnawa Right, there's two bugs due to Git Plugin's reuse of the same list:

* It accumulates all builds' parameters as the list doesn't get cleared between build triggers.
* All builds have the same parameters since the same list is passed through to the build.

Only the second is fixed by this PR, the first is still a bug in Git Plugin.

**Comment by daniel-beck** [comment]
Rebased and added test.

**Comment by oleg-nenashev** [comment]
No feedback from others, the change is safe. Merging

**Pull request merged**
