### PR TITLE
Update login.jelly to avoid autocorrect of username on mobile devices

### PR DESCRIPTION
**Pull request by chris-daw**
Added autocorrect off and autocapitalize off to username input. This switches off functionality on mobile devices which attempts to auto correct text entered into the username field, and removes automatic capitalisation of first word entered.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Seems the pull request has been missed somehow.
:+1: BTW

**Comment by oleg-nenashev** [comment]
A bug in JIRA would be useful

**Comment by olivergondza** [comment]
Pardon my ignorance, but how can one use Jenkins reasonably on a device that does that for all form fields. Or is login special somehow?

**Comment by daniel-beck** [comment]
It's probably the only form in Jenkins you can really use on a mobile device without going completely insane.

**Comment by oleg-nenashev** [comment]
> It's probably the only form in Jenkins you can really use on a mobile device without going completely insane.

Androids and other such stuff work on tablets and laptops, so probably the case is not so horrible.

**Comment by oleg-nenashev** [comment]
re :+1: after the discussion. May be reworked later by @tfennelly and @gusreiber

**Pull request merged**
