### PR TITLE
Adjust  the website timestamp format like "yyyy-MM-dd hh:mm:ss"

### PR DESCRIPTION
**Pull request by gnzhoutian**
Adjust  the website timestamp format like "yyyy-MM-dd hh:mm:ss"

### Desired reviewers

@daniel-beck

### CODE REVIEW

**Review by daniel-beck — CHANGES_REQUESTED** [review]
I do not think that unconditionally overriding the locale-specific date/time format based on the user's Accept-Language is something we should do.

**Comment by gnzhoutian** [comment]
@daniel-beck @fusion27 
 The best approach is to provide an interface for user-defined time formats. But my programming ability is limited, so I can only modify like this. At least, that's the only way I can change the time format for now.
I still think it's user friendly to provide a uniform time format, at least for my company。

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
My suggestion would be to start from creating a JIRA issue and explaining the use-case and expectations. Then we can come up with a better solution. I agree with @daniel-beck that this change cannot be merged as is.

**Comment by gnzhoutian** [comment]
Ok, let me close this pull request. I've come up with a stupid solution here:

**Pull request closed without merging**
