### PR TITLE
[JENKINS-64504] stuck plugin manager buttons

### PR DESCRIPTION
**Pull request by fqueiruga**
See [JENKINS-64504](https://issues.jenkins-ci.org/browse/JENKINS-64504).

Fixing another issue introduced on https://github.com/jenkinsci/jenkins/pull/5051. Plugin manager buttons get stuck on the footer when the search results do not cause the page to scroll. This causes many ATH tests to fail. 

**Technical considerations:**

- Uses the window.requestAnimationFrame to throttle callback calls through the raf polyfill

<details>
<summary>Before</summary>

Captura de pantalla 2020-12-22 a las 11 25 36

</details>

<details>
<summary>After</summary>

Captura de pantalla 2020-12-22 a las 11 30 42

</details>

### Proposed changelog entries

* JENKINS-64504 Fixed an issue that caused the buttons on the plugin manager to get stuck under certain conditions.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@timja 
@oleg-nenashev 
@jtnord 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
LGTM if it solves the issue. No problem with including `raf`

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
Tested via core-pr-tester and seems to work nicely

**Comment by fqueiruga** [comment]
Running this on CI, it seems to be removing over 100 failures on the whole ATH suite

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Review by res0nance — APPROVED** [review]

**Pull request merged**
