### PR TITLE
Refactoring of translation_tool.pl to start using modules

### PR DESCRIPTION
**Pull request by glasswalk3r**
No Jira related issue.

 * This change introduces the Jenkins::i18n Perl distribution to allow to refactor the original program to enable easier maintenance, testing and documentation.

### Proposed changelog entries

* Introduce `Jenkins::i18n` distribution, which is ready to deploy to CPAN if that is the case
* Replace `removeUnusedKeys` with `Jenkins::i18n::remove_unused`
* Rewrite all logic of `removeUnusedKeys` to use external modules that are more stable and have unit testing
* Add documentation, unit tests and validtions to `remove_unused`
* Introduce `Config::Properties`, which includes nice features like proper handling of multi-line property value and wrapping text automatically to fit 80 columns.
* Apply Perl best practices in all changed code.
* Force usage of a minimum Perl version (5.14).
* Change the shebang of `translation-tool.pl` to accept any `perl` that is available in `PATH` environment variable.
* Introduce minor improvements like using `DATA` to read the license (standardized way to do it in Perl) and POD to write documentation (try `perldoc translation-tool.pl` to see the result).

### Proposed upgrade guidelines

N/A since is a separated tool.

But in order to start using `translation_tool.pl`, see `Jenkins-i18n/README.md` for the required steps.

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by basil — COMMENTED** [review]
[-0 vote](https://www.apache.org/foundation/voting.html) from me, for the following reasons:

While I trust that refactoring this script into Perl modules is architecturally correct, it also increases the amount of complexity and the domain-specific knowledge required for users of the localization infrastructure. The existing localization infrastructure, while not ideal from an implementation perspective, can be trivially run by anyone with a modern Linux or macOS system by typing one command without thinking too hard, whether or not the user knows anything about building Perl modules (and the vast majority of us do not, including myself). In my opinion, losing this ability would add additional friction and burden the core developers.

I have opined in the past that the localization infrastructure could use a rewrite. I support any efforts to improve the localization infrastructure, but I am not sure this is our preferred direction. I think this topic could use further discussion on the [`jenkinsci-dev`](https://www.jenkins.io/mailing-lists/) mailing list and possibly a [Jenkins Enhancement Proposal (JEP)](https://github.com/jenkinsci/jep) with more detailed design documentation. I know @NotMyFault has also been examining localization infrastructure and may be interested in contributing to this effort.

Perhaps we could start the broader discussion by explicitly defining the problem(s) in the existing localization infrastructure that we want to solve. In this way, we can evaluate possible solutions based on how they solve the high-level problem(s) before we go down a particular implementation path.

**Comment by NotMyFault** [comment]
I'm with Basil here.
The current setup in core is quite ancient and could indeed get an overhaul, which may not be in Perl or by investing further work in the existing setup, in my opinion.
My work experience with Perl is bar zero, therefore I'd kindly refrain to look over the actual changes proposed.

In the last docs office hours on the tenth of March, we spoke a lot about improving translations, not only in core but in a way individual plugin developers under the jenkinsci organization could benefit from it and work with people who not necessarily need to know anything about git, GitHub or especially Perl, in this case.
Next week, on March the 24th, we're diving deeper and look forward to integrate one of Mark's plugins.
Docs office records are posted as thread on the forums, it would be great to have some feedback or chat about it there.

If the discussed approach from our docs office sessions matures a bit and we manage to integrate one or several plugins, I could look forward to sponsor a JEP.

**Comment by glasswalk3r** [comment]
Even though there is no evidence that I could find of a parallel work effort to improve the translation process in this discussion, I would argue the following:

- there is no change to the current translation infrastructure for an end user, who would only need to download dependencies from CPAN and install them in [a automated fashion](https://perldoc.perl.org/cpan).
- if the project already had a tool written in a JVM based language, this discussion would not make any sense, but there is no such tool AFAIK.
- you're already using a Perl solution for over 10 years, without providing improvements or reviews. This PR, in the other hand, would **improve** any future attempts to do so, since code would be better organized in a logical sense and using unit tests as regression tests as well.
- I'm sure that if anyone tries to install the Perl modules with the documentation provided,all this FUD would go away.

Anyway, I'm this discussion isn't worth the time of anybody, so I'm closing it.
I'll fork this code to a separated project and release it to CPAN. As soon as it ready for end users, I'll send a note to appropriate Google group.

**Comment by glasswalk3r** [comment]
As a reference for those interested about, the fork of `translation-tool.pl` is available at https://github.com/glasswalk3r/jenkins-translation-tool

**Pull request closed without merging**
