### PR TITLE
[FIXED JENKINS-14713] make Cancel independent from Build permission

### PR DESCRIPTION
**Pull request by hangsu-ma**
https://issues.jenkins-ci.org/browse/JENKINS-14713

After this change Buid permission will not grant Cancel permission implicitly.

A script in the confluence page below will make sure configuration is
compatible after this change:
https://wiki.jenkins-ci.org/x/fAAhB

### CODE REVIEW

**Comment by vinnybad** [comment]
I'm having the same issue here.  Any update on this?  It's been open for a while...

**Comment by oleg-nenashev** [comment]
I also think the change is reasonable. :+1: from me

**Comment by hangsu-ma** [comment]
@jglick @kohsuke 
Can we review this PR, it seems there are plenty of interests and user cases that requires cancel permission to be independent from build permission.

@jglick I understand you feel strange when one can not cancel the build one starts. But there seems to be good reasons that many company want this. I think Jenkins should provide the configuration to allow users to implement this policy. And they can always grant use both permission use the migration script i provided: https://wiki.jenkins-ci.org/x/fAAhB
The existence of Cancel permission in Jenkins UI and code means it is suppose to be a separate permission item for it.
For compatibility issue, the PR didn't create new permissions, it only changed impliedBy for same jenkins Cancel permission to a existing Jenkins build in permission. So it's detached from Build permission.
Users with custom made permission matrix shouldn't be impact by this, even they removed the Cancel Permission in jenkins source code and build their jenkins from source(this change will not affect them as they have removed Cancel permission). Please let me know if I missed anything?

**Comment by daniel-beck** [comment]
>  The existence of Cancel permission in Jenkins UI and code means it is suppose to be a separate permission item for it. So I would consider this as a bug fix that will change existing behavior rather than new feature.

This argument is flawed. Some permissions imply others. You wouldn't expect Overall/Administer to not imply everything else, right?

That said, the original case for introduction of the Cancel permission, and the direction the implication was set up is questionable, and probably shouldn't be supported to begin with (a custom external-to-Jenkins dashboard to start builds, but cancel in Jenkins). So I'm still in favor of this new behavior.

A (intentional) side effect of this change however is that for people upgrading who relied on the implication as it's currently defined (deliberately or not), allowing people to start but not abort, will experience this as a change requiring reconfiguration, possibly after not being able to cancel a job they needed to cancel. I'm not sure we're well prepared for that.

**Comment by hangsu-ma** [comment]
Hi @daniel-beck 
I actually have a migration script user can run to grant cancel permission to all users with build permission. This can be run before or after the upgrade.
So jenkins user have effectively same permissions after this upgrade: https://wiki.jenkins-ci.org/x/fAAhB

I see the problem is users are not guaranteed to run this script, is there any upgrade hook/task mechanism in Jenkins? if so, we can have a hook for this upgrade and it will run the migration script automatically when jenkins is upgraded to this version or higher from any lower version but not in the future upgrade again.

Regarding the admin permission, i still think Jenkins should provide user facility to config the suitable permission schema for their own organization, not dictating it. 
There are many valid cases where one organization would not want Jenkins admin to have all permissions, one example would be permission to run production deployment job, or permission to cancel a long running production backup job. These can be limited to a very specific group, not including Jenkins admins.

**Comment by daniel-beck** [comment]
@hangsu-ma There are other popular authorization strategies besides Matrix Auth, such as Role Strategy, as well as possible non-public ones. The script you link to may work on a specific subset of instances, but is nothing that can be rolled out to 150k instances.

**Comment by hangsu-ma** [comment]
Hi @daniel-beck 
you are right, I wrote that in 2013, and only covered GlobalMatrixAuthorizationStrategy, ProjectMatrixAuthorizationStrategy. I can have a look again and cover other strategies.

But for non-public ones, if they are not using Jenkins buildin permissions like Build and Cancel. Then there is no impact. If they are, then there is a behavior change, but Jenkins won't break.

I would also argue users with non-public/private customization/addon for any software can't expect the software updates are always compatible for them for obvious reasons. What do you think?

**Comment by daniel-beck** [comment]
The current behavior remains terrible. We should just bite the bullet and accept a handful of upset users who failed to read the changelog.

**Comment by daniel-beck** [comment]
@jenkinsci/code-reviewers assemble!

**Comment by daniel-beck** [comment]
@oleg-nenashev Given how trivial it is to fix up configurations affected by this change, we can just merge as is. WDYT?

**Review by oleg-nenashev — APPROVED** [review]
Taking the number of JIRA votes into account, I am +1 regarding that as long as it is not backported and correctly mentioned in update guidelines.

We could probably add some migration logic in MatrixAuth/RoleStrategy, but unfortunately I do not have time for that. Should not be a blocker

**Comment by daniel-beck** [comment]
One last chance for @jenkinsci/code-reviewers to stop this from landing 😉

**Review by daniel-beck — APPROVED** [review]

**Comment by hangsu-ma** [comment]
Can't access the Details link above for the failed check continuous-integration/jenkins/pr-head, anyway I can investigate/fix the problem?
Guessing from the name pr-head, it's just building the commit from a 5 years old fork, i can rebase that to a newer branch if that would help? let me know.

**Comment by daniel-beck** [comment]
@hangsu-ma No need, we stopped building pr-head (but I don't think there's a way to clear out old statuses). pr-merge is good enough to confirm this is fine. (And yes, the reason is that this branch is too old to work with the master Jenkinsfile.)

**Comment by oleg-nenashev** [comment]
We have passed the LTS cutoff, so I think it we just merge it since nobody wants again.
Any second thoughts @daniel-beck? It will definitely require mentioning in upgrade guidelines

**Comment by oleg-nenashev** [comment]
https://github.com/jenkinsci/jenkins/pull/3421 passed, merging

**Comment by oleg-nenashev** [comment]
Thanks @hangsu-ma! It is definitely one of the most-long-waiting pull requests in the core, but it's great to get it finally merged. We improved our velocity for new pull requests, and hopefully we will clean up the queue of older ones

**Pull request merged**
