### PR TITLE
Better exception message

### PR DESCRIPTION
**Pull request by cyrille-leclerc**
Better exception message if the SecurityRealm doesn't respect the API contract and return null.

### CODE REVIEW

**Comment by cyrille-leclerc** [comment]
cc @oleg-nenashev

**Comment by oleg-nenashev** [comment]
If it happens, it's a bug in a plugin.
Nonnull API has been defined years ago. Could you please create a JIRA issue and clarify the case? With which plugin does it happen?

**Comment by cyrille-leclerc** [comment]
@oleg-nenashev the problem happened with an "homemade" authentication plugin that made the mistake to return `null` when the API and its javadoc clearly states it should not. I think it's good to help people on error prone APIs.

This proposal is a way to "Be conservative in what you do, be liberal in what you accept from others".

**Comment by oleg-nenashev** [comment]
My recommendation would be to...
1) Add "catch (RuntimeException x)" or "catch (Throwable x)" to the method
2)  Log issue
3) return null from the method.

It's a correct suppression of unexpected issues in plugins, which is being used in many other cases.

**Comment by cyrille-leclerc** [comment]
@oleg-nenashev I don't feel comfortable with returning `null` instead of throwing an Exception. I feel that

1. it's right to either propagate a `NullPointerException` or to an `IllegalStateException`
1. its valuable to provide a clear exception message

**Comment by johnou** [comment]
:+1:

**Comment by oleg-nenashev** [comment]
I'm against throwing undocumented exceptions from the public API, hence 👎 . It may cause undefined behavior un plugins using this API.

The method has a clear Javadoc: "extract user ID from idOrFullName with help from contextual infos. can return <code>null</code> if no user ID matched the input". So IMHO returning null is valid approach in this case.

If you want go forward with exceptions, at least it should be documented in the parent method. But I doubt runtime exception is a right way to go in any case. Better to introduce the new API method then.

**Comment by cyrille-leclerc** [comment]
@oleg-nenashev I changed from `IllegalStateException` to `NullPointerException` so that this change does not change at all the behaviour of the method, it just adds an exception message in the `NullPointerException` that is thrown.

We could have implemented the same behavior with a try/catch.

Do you prefer us to be even more lenient and to return `null` if `SecurityRealm.loadUserByUsername()` makes the mistake to return `null` instead of `UsernameNotFoundException` ?

**Comment by oleg-nenashev** [comment]
With NPE it's better of course. So 🐝 since it does not increase the technical debt. BTW I still think it would be better to have logging in the method and then to return null.

> Do you prefer us to be even more lenient and to return null if SecurityRealm.loadUserByUsername() makes the mistake to return null instead of UsernameNotFoundException ?

I do not see how is it related to this discussion. UsernameNotFoundException is a part of the documented API, everything is fine there.

**Comment by oleg-nenashev** [comment]
Build failed due to the timeout. Retriggering it

**Comment by cyrille-leclerc** [comment]
@oleg-nenashev Thanks. Do you want a Jira issue for this minor exception message enhancement?

**Comment by oleg-nenashev** [comment]
f we consider backporting it, then yes.
If no, then I'm fine with the current state

**Comment by cyrille-leclerc** [comment]
@oleg-nenashev I'm not sure that we need to backport, thanks.

**Comment by oleg-nenashev** [comment]
Then let's go forward with the current PR

**Comment by oleg-nenashev** [comment]
We have two votes, so I'm going to merge it into the next release

**Comment by cyrille-leclerc** [comment]
@oleg-nenashev thanks!

**Pull request merged**
