### PR TITLE
[JENKINS-58836] Wrong spanish argentinian translation for 'logout'

### PR DESCRIPTION
**Pull request by belingueres**
Modificed logout key.

See [JENKINS-58836](https://issues.jenkins-ci.org/browse/JENKINS-58836).

### Proposed changelog entries

* Entry 1: Improved Spanish Argentine translation.

### Submitter checklist

- [x] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### CODE REVIEW

**Review by varyvol — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
Will merge tomorrow if no negative feedback

**Comment by oleg-nenashev** [comment]
retriggering CI

**Comment by belingueres** [comment]
Hi @oleg-nenashev!
Is there any procedure to update the translations?

**Comment by oleg-nenashev** [comment]
Hi @belingueres No special procedure, just submit pull requests and we will get them reviewed :) Thanks for this patch!

If you are asking about your own instance, there are two ways:

* Wait till the release. Note that we do not usually backport translations to LTS
* Use https://github.com/jenkinsci/translation-plugin to override translation on your instance (not really recommended, but works)

There is also https://github.com/jenkinsci/jep/tree/master/jep/216 from @LinuxSuRen for localization plugins which can speedup delivery of patches.

**Review by jeffret-b — APPROVED** [review]

**Pull request merged**
