### PR TITLE
[JENKINS-53823] - Update JTH and commons-io to fix JDK11 compatibility issues

### PR DESCRIPTION
**Pull request by oleg-nenashev**
See [JENKINS-53823](https://issues.jenkins-ci.org/browse/JENKINS-53823). My plan is to pick up https://github.com/jenkinsci/jenkins-test-harness/pull/110 , but effectively it integrates a lot of other changes. I have not tested HTMLUnit from the last release, but should be ok.

### Proposed changelog entries

* RFE, Internal:  Update Jenkins Test Harness from 2.36 to 2.42 to allow running tests with JDK11
  * Changelog: https://github.com/jenkinsci/jenkins-test-harness#changelog
* RFE: Update Apache Commons IO from 2.4 to 2.6
  * Changelog 2.5: https://commons.apache.org/proper/commons-io/upgradeto2_5.html
  * Changelog 2.6: https://commons.apache.org/proper/commons-io/upgradeto2_6.html

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@dwnusbaum @jglick

### CODE REVIEW

**Review by dwnusbaum — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Apache Commons IO 2.6 adds a patch for Java 9+ compatibility: "IO-551: Add Automatic-Module-Name MANIFEST entry for Java 9 compatibility.". So I decided to just update the version to resolve upper bounds

**Comment by dwnusbaum** [comment]
Looks like the HTMLUnit update breaks ZipExtractionInstallerTest.

**Comment by jglick** [comment]
Apparently you need to s/`InteractivePage`/`HtmlPage`/g for whatever reason.

**Comment by oleg-nenashev** [comment]
I believe this is superceded by https://github.com/jenkinsci/jenkins/pull/3872 o

**Pull request closed without merging**
