### PR TITLE
[FIXED JENKINS-26775] Move to Stapler 1.238

### PR DESCRIPTION
**Pull request by abayer**
This gets rid of the duplicate entries in XML Api job listings

And @daniel-beck - this should probably go into 2.0 as well.

cc @reviewbybees

### CODE REVIEW

**Comment by kohsuke** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
:bee: after looking into changes

**Comment by kohsuke** [comment]
In the mean time there's Stapler 1.239 that I need. So I'd rather merge #2059

**Comment by abayer** [comment]
Okiedokie.

**Pull request closed without merging**
