### PR TITLE
Remove .textarea-handle and richtextarea.jelly

### PR DESCRIPTION
**Pull request by janfaracik**
We no longer support IE11 so the `.textarea-handle` resize workaround is no longer needed. 

`richtextarea.jelly` relies on the YUI editor from 10+ years ago and isn't in use on Jenkins or in any plugins (https://github.com/search?p=1&q=org%3Ajenkinsci+%3Arichtextarea&type=Code), the fact that the YUI editor isn't even imported leads me to believe it wouldn't work anyway.

---

### Proposed changelog entries

* N/A

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@jenkinsci/sig-ux 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/6621"></a>

### CODE REVIEW

**Review by basil — COMMENTED** [review]
Nice cleanup! The `richtextarea` changes look good to me. I love the enthusiasm for tackling these long-standing areas of technical debt. And I admire your unique success in doing so. Kudos!

Now this PR does not seem like it completely removes `textarea-handle` as advertised. There is still a reference in https://github.com/janfaracik/jenkins/blob/ad4c757416254440d22a9080230ed9f7e5869ddb/core/src/main/resources/lib/form/textarea.jelly#L105-L106= as well as the `textarea-handle.gif` file mentioned in my other review comment below. While leaving these references behind is harmless, doing so would decrease the impact of this PR (which aims to remove technical debt by removing as much of this dead code as possible). In order to make this PR as logically consistent as possible, I believe the [transitive closure](https://en.wikipedia.org/wiki/Transitive_closure) of references to `textarea-handle` within this repository should be deleted. So I feel relatively strongly that these two references should be deleted in order for this PR to be merged, assuming that this has no other negative side effects.

---

What follows is a combination of optional feedback and some free programming mentorship. As free advice, it is worth exactly as much as you paid for it, and you are free to take it or leave it. But following the principles described below have helped me to become a better programmer over the years. So I will distill this case study into a general software development problem, then describe a general solution to this general problem, then describe how to apply the general solution to this specific problem. You can take the same logical approach to tackle any instance of this problem with blazing efficiency regardless of the particular domain you find yourself in.

Now even if the transitive closure of references to `textarea-handle.gif` in this repository were cleaned up as suggested above, there are still a half-dozen or so references in various plugins as revealed in https://github.com/search?ref=simplesearch&type=Code&q=user%3Ajenkinsci+%22textarea-handle%22. While this core PR does not seem to _break_ any of these plugins, it _does_ leave behind dead code without any clear path toward cleaning it up. This becomes part of the cognitive load and complexity of the software which, over time, creates crippling inertia making future changes more and more difficult. As an active Jenkins frontend developer, I am sure you have experienced this firsthand.

From a software engineering perspective, the `textarea-handle` functionality in core is effectively an [interface](https://en.wikipedia.org/wiki/Interface_(computing)) (a boundary across components in the form of a `div` tag) along with an implementation of that interface (legacy IE11-specific JavaScript logic). With the removal of IE11 support, the implementation is no longer needed. And because the implementation is no longer needed, the interface is no longer needed. But the interface has consumers (plugins). So for logical consistency, the end-of-life of this interface implies that both the producer (core) and consumer (plugins) of the interface should drop all references.

Thinking about this at a high level, the classic solution to this type of problem from a software engineering perspective is [phased obsolescence](https://en.wikipedia.org/wiki/End-of-life_product): an end-of-life announcement (EOLA) for the interface in the form of a deprecation warning, a deprecation period, and an end-of-life (EOL) after which vendor liability ends. For example:

- Retain the interface, but replace the implementation with some sort of warning that the interface is now a [no-op](https://en.wikipedia.org/wiki/NOP_(code)) and that references to the interface should be deleted prior to an agreed-upon date.
- During the deprecation period, encourage consumers to drop their references (e.g. by submitting PRs and hoping that people act on the warnings).
- Once the deprecation period is over, delete the deprecation stubs and declare that any consumers that have not dropped their references are now operating in an undefined state in which the vendor (i.e., the Jenkins project) is not liable.

If all of this sounds laborious, that should be a strong motivation to be _very careful_ when introducing new APIs, either explicit or implicit, because those APIs might survive for decades (as they have in the Jenkins project). [This YouTube video](https://www.youtube.com/watch?v=aAb7hSCtvGw) explains the art of long-term API design. Master the art of deliberate and stable API design, and you can unlock enormous potential implementing far-reaching changes across component boundaries without significant risk of regression.

**Comment by janfaracik** [comment]
Thanks a lot for the comment @basil, I appreciate it.

I've removed the `textarea-handle` element and the `textarea-handle.gif`. Looking through the search filter you provided only [workflow-cps-plugin](https://github.com/jenkinsci/workflow-cps-plugin) directly interacted with the `textarea-handle` element, and all that interaction consisted of was to remove it if the element existed. I've given it a try myself and the plugin seems to work fine/just as before with no console errors.

There does exist another bit of code that interacts with the element in [autocomplete-parameter-plugin](https://github.com/jenkinsci/autocomplete-parameter-plugin), but it looks like this plugin has been [suspended](https://plugins.jenkins.io/autocomplete-parameter/). Even if it wasn't suspended however it still behaved in the same way as `workflow-cps` so all is good there. 

Any plugins that manually create a `textarea-handle` element will have an empty div just as they had before (the element only had styling if the browser was IE11), so nothing changes there for them.

I hope that helps. 

Once again, thanks,

Jan

**Review by basil — APPROVED** [review]
Eliminating the references to `textarea-handle` in core _and_ plugins as described in https://github.com/jenkinsci/jenkins/pull/6621#pullrequestreview-994157784 would be preferable (because it eliminates all of the undesirable cognitive load related to this dead code rather than just some of it), but eliminating the references in core alone should at least discourage the paradigm from spreading further and is therefore good enough.

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Pull request merged**
