### PR TITLE
Remove All localized files of Chinese

### PR DESCRIPTION
**Pull request by LinuxSuRen**
All related plugins are published. Below are PRs:

https://github.com/jenkinsci/localization-zh-cn-plugin/pull/31
https://github.com/jenkinsci/localization-support-plugin/pull/1
https://github.com/jenkinsci/localization-zh-cn-plugin/pull/71

### Proposed changelog entries

* Entry 1: Localization, Remove and migrate all Chinese localization files into localizationi-zh-cn plugin

### Submitter checklist

- [ ] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
Should we go forward with the merge?
CC @daniel-beck who was involved in JEP-216

**Review by fcojfernandez — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Will merge it tomorrow if there is no negative feedback

**Comment by daniel-beck** [comment]
`localization-zh-cn` now depends on the newly released `localization-support` that should add full support for all of this.

Would get confirmation from @LinuxSuRen that the PR build with the plugins installed retain all localizations removed here, and if so, proceed.

**Review by MRamonLeon — APPROVED** [review]
Fine if @LinuxSuRen confirms what @daniel-beck is asking.

**Comment by LinuxSuRen** [comment]
Sorry about the delay. Time difference.
@daniel-beck @MRamonLeon Yes, `localization-zh-cn` already contains those files. Please go ahead.

**Comment by mmh891113** [comment]
@LinuxSuRen 你这个比较坑阿。一不小心升级一下，发现没本地中文翻译了阿。后来查到你这个提交才知道要安装的插件。

**Comment by LinuxSuRen** [comment]
@mmh891113 您好，首先对给您的不方便表示歉意。不过，我们的这次变更是有在社区的邮件列表里讨论过的。另外，在版本发布的变更记录也有说明，同时，也在官方的微信公众号里也有公布。
为了能够避免类似的情况，可以关注我们的官方的媒体渠道。
谢谢您的理解和支持。

**Pull request merged**
