### PR TITLE
[JENKINS-38814] Use GREEDY `RemoteInputStream`s

### PR DESCRIPTION
**Pull request by andresrc**
See [JENKINS-38814](https://issues.jenkins-ci.org/browse/JENKINS-38814), [JENKINS-38640](https://issues.jenkins-ci.org/browse/JENKINS-38640) and https://github.com/jenkinsci/workflow-api-plugin/pull/19

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by daniel-beck** [comment]
@andresrc Do you have a reference for why greedy improves performance?

**Comment by andresrc** [comment]
@daniel-beck Sure, it's in the [remoting javadoc] (https://github.com/jenkinsci/remoting/blob/master/src/main/java/hudson/remoting/RemoteInputStream.java#L191-L222).

**Comment by oleg-nenashev** [comment]
Would be great to see some performance test results. Maybe @svanoort already has some benchmarks for this area.

I think it's a reasonable change, hence a weak 👍

**Comment by andresrc** [comment]
@oleg-nenashev there are some performance results at https://github.com/jenkinsci/workflow-api-plugin/pull/19

**Review by oleg-nenashev — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Since the release train has departed in any case, let's wait a bit for other reviews

**Review by daniel-beck — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Both Builds passed. PR Builder from @kzantow still pollutes the environment

**Pull request merged**
