### PR TITLE
[JENKINS-31395] Footer does not work fine in some situations

### PR DESCRIPTION
**Pull request by recena**
[JENKINS-31395](https://issues.jenkins-ci.org/browse/JENKINS-31395) and [JENKINS-30304](https://issues.jenkins-ci.org/browse/JENKINS-30304)

/cc @csimons @oleg-nenashev

### CODE REVIEW

**Comment by daniel-beck** [comment]
Looks like this means it will not position the footer at the bottom of the page if the page content is not high enough, right?

**Comment by recena** [comment]
@daniel-beck you are right. Looking a better approach....

**Comment by recena** [comment]
@daniel-beck I've addressed your comment.

**Comment by recena** [comment]
@oleg-nenashev @daniel-beck Do you need anything else to review this? I can provide screenshots or a screencast.

**Comment by daniel-beck** [comment]
@recena What about [JENKINS-29771](https://issues.jenkins-ci.org/browse/JENKINS-29771)?

**Comment by uhafner** [comment]
Did you run the test for  JENKINS-30304? (I.e., remove the if in https://github.com/jenkinsci/acceptance-test-harness/blob/master/src/test/java/plugins/AbstractAnalysisTest.java#L173)

**Comment by recena** [comment]
@daniel-beck [JENKINS-29771](https://issues.jenkins-ci.org/browse/JENKINS-29771) is a different problem. In fact, I'm not sure that is a bug. They need to review its CSS.

**Comment by recena** [comment]
@uhafner I'm working on it in this moment.

**Comment by recena** [comment]
@uhafner I wrote a message [here](https://issues.jenkins-ci.org/browse/JENKINS-30304?focusedCommentId=242681&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-242681).

**Comment by recena** [comment]
@uhafner I verified that this PR not solve [JENKINS-30304](https://issues.jenkins-ci.org/browse/JENKINS-30304) but the solution for that issue is not related to the footer. I'd like to make a different proposal.

**Comment by recena** [comment]
Tested on Firefox, Safari and Chrome on Mac. Tested on Internet Explorer 9 on Windows 7.

**Comment by recena** [comment]
@uhafner Finally, I found a solution based on the footer.

**Comment by recena** [comment]
IMO this PR is ready for a final revision. /cc @daniel-beck

**Comment by oleg-nenashev** [comment]
:+1: according to the test results.
@recena Has it been tested on IE11?

**Comment by recena** [comment]
@oleg-nenashev No, I didn't but I can do it.

**Comment by oleg-nenashev** [comment]
Makes sense. At least it's the browser version the fix is intended to fix

**Comment by recena** [comment]
@oleg-nenashev Really the bug was present in other versions and browsers.

**Comment by oleg-nenashev** [comment]
Would be nice to fix the PR title then. From other POVs the PR is ready to go IMHO

**Comment by recena** [comment]
@oleg-nenashev you can find more detailed information in the mentioned JIRA issues.

**Comment by csimons** [comment]
Verified this fixes the footer issue for IE 11 as well (using HEAD 9013b290b75d3638203c3b112b2ef2a2cfb31dc4 on IE 11.0.9600.18059IS).

**Comment by recena** [comment]
@csimons Thanks so much for your feedback.

**Comment by oleg-nenashev** [comment]
Ready to merge as the fix has been confirmed.

**Comment by recena** [comment]
@oleg-nenashev Thanks.

**Pull request merged**
