### PR TITLE
Removed deprecated ApiTokenTestHelper

### PR DESCRIPTION
**Pull request by StefanSpieker**
Removed deprecated `ApiTokenTestHelper` in test module
- replaced with needed config 
- or completely removed unneeded usages

### Testing done

Locally the tests passed.

### Proposed changelog entries

- N/A

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7243"></a>

### CODE REVIEW

**Review by basil — COMMENTED** [review]
> completely removed unneeded usages

How do we know these usages are not needed? Just because tests pass without them does not mean they are not needed: they might be needed, for example, to ensure that both a legacy code path and a non-legacy code path both get tested. While I am not sure that this is the case, I am also not sure that this is _not_ the case either, so I cannot approve this change. Please provide more explicit reasoning about why the deleted usages are no longer needed and can be safely removed without impact to the coverage of each test.

**Review by Wadeck — APPROVED** [review]
@basil Your hypothesis is good in general, in this particular case I can reassure you that I added those calls only to keep those unit test working. They are not testing the API Token but it was just a mean for them to connect the user.

----

The API Token v2 was made in two steps, the first one to add the new format of storage for the token, with the hash approach instead of encryption.
The second step was to add method mechanisms / methods to play with them. 

The test updates were done after first step, without nice method to generate tokens. This led to the need to keep the legacy in the tests. 

The change made in https://github.com/jenkinsci/jenkins-test-harness/commit/291beb19618e93ffae21fb9f156399dcb9a560b5 after a discussion with Jesse was meant to generate tokens on the fly for tests, which allows simpler tests.

----

Without having looked into details of each tests, if they are passing, I am fine with the cleanups/updates.

I just tested some test cases to be sure about my above explanation :)

Thanks @StefanSpieker for the job there! (potentially my explanation will give you more context about why it's working :D)

**Comment by StefanSpieker** [comment]
@Wadeck Thanks for the explanations!

**Review by basil — APPROVED** [review]

**Comment by basil** [comment]
This PR is now ready for merge. We will merge it after approximately 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process. Thanks!

**Review by NotMyFault — APPROVED** [review]

**Pull request merged**
