### PR TITLE
Upgrade stapler version to 1.241.

### PR DESCRIPTION
**Pull request by christ66**
This PR updates the version of stapler to the latest released version (1.241). See [change log](https://github.com/stapler/stapler/compare/stapler-parent-1.239...stapler-parent-1.241) for more information.

@reviewbybees

### CODE REVIEW

**Comment by jtnord** [comment]
:bee: I presume 1.241 fixes the regression that caused 1.240 to be yanked in d63441a8759cf573f909099da4fb41caa30a0297?

**Comment by oleg-nenashev** [comment]
I feel like we are sitting on the bomb if the issue sneaks into Stapler, which has no consistent code reviews.  But :bee: since the changes have been already released there.

I'm against delivering it in 2.0 and probably 2.1

**Comment by christ66** [comment]
@oleg-nenashev I'm ok with holding off on merging this for a while (until after 2.1 release).

**Comment by daniel-beck** [comment]
2.1 will be a pretty heavy release, with ~four weeks of regular changes going in. So I'd rather we hold this off until 2.2(ish).

**Comment by vivek** [comment]
I noticed failing tests, submitted new patch that includes fixes for failing tests as well as Stapler upgrade to 1.241. We should close this PR and evaluate, https://github.com/jenkinsci/jenkins/pull/2298.

**Comment by kohsuke** [comment]
Closing this in favor of #2298.

**Pull request closed without merging**
