### PR TITLE
[JENKINS-56166] Remove hudson.util.ssh.SFTPClient classs from core

### PR DESCRIPTION
**Pull request by kuisathaverat**
See [JENKINS-56166](https://issues.jenkins-ci.org/browse/JENKINS-56166).

In order to remove all dependencies from trilead-ssh2 library from core this deprecated class should be removed, I did not find any reference to hudson.util.ssh.SFTPClient class, is deprecated, and a pretty similar (public methods) class is in the trilead-ssh2 library as com.trilead.ssh2.jenkins.SFTPClient, so I propose to remove it, this will remove more dependencies from the trilead-ssh2 library from core.

The class is nor referenced in core code so a unit test is not needed

### Proposed changelog entries

* hudson.util.ssh.SFTPClient was removed from core, you can still use the compatible class com.trilead.ssh2.jenkins.SFTPClient from trilead-ssh2 library.

### Submitter checklist

- [X] JIRA issue is well described
- [X] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [X] Appropriate autotests or explanation to why this change has no tests
- [X] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@Wadeck @oleg-nenashev @daniel-beck @alecharp 

related to https://github.com/jenkinsci/jenkins/pull/3876

### CODE REVIEW

**Review by Wadeck — APPROVED** [review]
From a search in the whole ecosystem, only `ssh-slave-plugin` is using `SFTPClient`, but actually duplicated the one from core.

FTR, there was a usage of it (as String) in ATH but was removed since.

**Review by oleg-nenashev — APPROVED** [review]
I do not see usages of the class, so I rather +1 removal. But it is a risky change which needs to be explicit in the changelog

**Review by alecharp — APPROVED** [review]
LGTM

**Comment by oleg-nenashev** [comment]
CC @daniel-beck since it removes [unused?] public API

**Review by varyvol — APPROVED** [review]

**Comment by varyvol** [comment]
@daniel-beck could you please review this?

**Review by batmat — APPROVED** [review]
Checked using https://github.com/jenkins-infra/deprecated-usage-in-plugins, and I couldn't find any usage. Neither from manually checking https://github.com/search?q=org%3Ajenkinsci+SFTPClient&type=Code, so LGTM

**Comment by batmat** [comment]
Given the numerous approvals, hence including checking this class does not seem used anywhere publicly. I think this is fine to move forward.

The changelog looks fine too. _Maybe_ we want to make it slightly more outstanding for people to catch it, but well, no actual big deal I guess.

**We will merge this later today or so if nobody objects in the meantime.**

@daniel-beck do you by chance have some remaining concern about this?

**Comment by batmat** [comment]
Got off the band feedback from Daniel that he's fine with this. Let's move on.

**Pull request merged**
