### PR TITLE
Disable the flaky AgentProtocolTest test

### PR DESCRIPTION
**Pull request by oleg-nenashev**
I just want to make CI green again.

### Proposed changelog entries

* N/A

### Desired reviewers

@reviewbybees @jglick

### CODE REVIEW

**Comment by jglick** [comment]
I guess this should have been done as an addition to #3012, where I also mentioned some other problematic related tests: `JenkinsTest` and `SetupWizardTest`.

**Comment by oleg-nenashev** [comment]
@jglick I agree regarding https://issues.jenkins-ci.org/browse/JENKINS-47181 , but I have no time to work on this right now. The test needs creation of a Dummy protocol handler test extension (it was a good idea to create it at very beginning for sure)

**Comment by oleg-nenashev** [comment]
@jenkinsci/hacktoberfest as well

**Comment by jglick** [comment]
Well until you sort all that out could you maybe fold this into #3012 and suppress the other flaking tests too?

**Comment by oleg-nenashev** [comment]
@jglick @jenkinsci/code-reviewers I propose to merge it as is and then handle other tests in #3012 . WDYT?

**Comment by oleg-nenashev** [comment]
Merging as is, will figure out the rest later

**Pull request merged**
