### PR TITLE
[JENKINS-60866] Un-inline setup wizard root URL js

### PR DESCRIPTION
**Pull request by NotMyFault**
See [JENKINS-60866](https://issues.jenkins.io/browse/JENKINS-60866) for the issue that covers the process.  This pull request does not resolve that issue, but it is progress on the goal of that issue.

### Testing done

Testing interactively, I didn't encounter any regressions while walking through the setup wizard until the root URL page.

### Proposed changelog entries

- N/A

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] The Jira issue, if it exists, is well-described.
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [x] There is automated testing or an explanation as to why this change has no tests.
- [x] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [x] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [x] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [x] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [x] For new APIs and extension points, there is a link to at least one consumer.

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [x] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [x] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [x] Proper changelog labels are set so that the changelog can be generated automatically.
- [x] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [x] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]
Code review found no issues.

Interactive testing of the setup wizard root URL field found no issues.  The enter key is ignored if it is pressed inside the field, just as it was ignored previously.

**Comment by MarkEWaite** [comment]
Does it need review from @core-security-review ?

**Comment by NotMyFault** [comment]
> Does it need review from jenkinsci/core-security-review ?

I didn't introduce anything new and stick to what was already in place, although Wadeck advised to use the needs-security-review label if changes involve Jelly or JS changes (as far as I'm aware of) on the mailing list.

**Review by Wadeck — APPROVED** [review]
Added a link to this PR to https://issues.jenkins.io/browse/JENKINS-60866 (generic task for CSP).

When it's just a move, usually you cannot really introduce a vulnerability. It does not require the security audit I would say.

Also keep in mind that if you are "just" moving code, the review is also very straightforward ;)

**Comment by NotMyFault** [comment]
Thanks for checking, clarifying and linking the issue. I wasn't aware we already track this somewhere 👀 

---

/label ready-for-merge

---

This PR is now ready for merge. We will merge it after ~24 hours if there is no negative feedback.
Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process.
Thanks!

**Pull request merged**
