### PR TITLE
Pinning ATH version used in runATH

### PR DESCRIPTION
**Pull request by batmat**
This PR is designed to, hopefully, get the Core build back to green durably. 
Since a few days, we have many if not all PRs and the master branch failing because of ATH tests failures.

So I'm pinning the ATH sha in use for `runATH`. It's going to be much better in terms of stability and control.
We'll want to regularly file PRs to bump ATH SHA to use.

No JIRA. No changelog, purely internal change.

### Submitter checklist

- N/A ~JIRA issue is well described~
- N/A Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- N/A Appropriate autotests or explanation to why this change has no tests
- N/A For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@jenkinsci/java11-support @olivergondza

### CODE REVIEW

**Comment by batmat** [comment]
Examples:

* https://github.com/jenkinsci/jenkins/commit/bcc4e4fe9c3dccc5ca74299d24f8f992c9d5cd71 failed with 
image
* https://github.com/jenkinsci/jenkins/pull/3813 failed with 
image
https://github.com/jenkinsci/jenkins/pull/3814 failed with 
image

**Comment by batmat** [comment]
Fuuuuuuu, now 
image

> Good morning campers!...

**Review by MRamonLeon — APPROVED** [review]
The athRevision could be set in the _essentials.yml_ in a cleaner way, IMO. The right fix, I think is to publish the docker image and align the **athRevision** and **athImage**, as I said in https://github.com/jenkinsci/jenkins/pull/3793#issuecomment-448380551 But as it could last more and there are builds failing right now, these approach is totally reasonable to me.

**Review by oleg-nenashev — APPROVED** [review]

**Comment by batmat** [comment]
Actually, this is wrong. `athRevision` is already set in `essentials.yaml`. Going to file JIRA(s) to make sure we fix all this I think.

https://github.com/jenkinsci/jenkins/pull/3816 is a better version of this PR likely. 

The issue here is that we depend on `runATH` master branch of the pipeline-library, and we have to align everything right away so this works, as Raul explains in https://github.com/jenkinsci/jenkins/pull/3816

**Comment by MRamonLeon** [comment]
> as Raul explains in #3816

*@Batman* you meant Ramon, isn't it :-D :bat:

**Pull request closed without merging**
