### PR TITLE
typofix - https://github.com/vlajos/misspell_fixer

### PR DESCRIPTION
**Pull request by vlajos**
core/src/main/java/hudson/os/solaris/ZFSInstaller.java and core/src/main/java/hudson/os/solaris/ZFSProvisioner.java contain `fs.destory` which are suspicious, but assuming they work as it is.
I reverted them.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
:+1:

**Comment by olivergondza** [comment]
`CHOICES_DELIMETER` fix changes API, though it is not referred to from jenkinsci group. :+1:

**Comment by daniel-beck** [comment]
`CHOICES_DELIMETER` could be referenced in scripts such as `init.groovy.d`. Otherwise :+1:

**Comment by vlajos** [comment]
Should I revert this CHOICES_DELIMETER ?

**Comment by olivergondza** [comment]
@vlajos, please keep the old one as well but `@Deprecated` and initialized with the value of the new field.

**Comment by vlajos** [comment]
Could you please check?

**Comment by olivergondza** [comment]
:+1: on the BC fix.

**Comment by daniel-beck** [comment]
@olivergondza If the old field is no longer used, can't it just be removed? That way it'll be obviously breaking scripts etc. instead of just no longer doing its job.

**Comment by olivergondza** [comment]
@daniel-beck, what do you mean by "... no longer doing its job"? It is read-only field with the same value as before.

**Comment by daniel-beck** [comment]
@olivergondza Thanks for pointing out it's `final`, I missed that.

**Pull request merged**
