### PR TITLE
[FIXED JENKINS-10629] archiving

### PR DESCRIPTION
**Pull request by KostyaSha**
Fixed @oleg-nenashev bug in feature that was reverted after 1.610.

[Review on Reviewable](https://reviewable.io/reviews/jenkinsci/jenkins/1670)

### CODE REVIEW

**Comment by KostyaSha** [comment]
How i like this tests... first fail https://jenkins.ci.cloudbees.com/job/core/job/jenkins-core/2479/

**Comment by oleg-nenashev** [comment]
@KostyaSha 
Thanks for your efforts on the issue troubleshooting and fixing. Probably, a cherry-pick can be preferable in order to have a native reference to a commit you want to restore.

I propose to merge the change to jenkins-1.612, because we're not sure that all regressions have been fixed. I also committed to provide more tests to achieve a better coverage, so it makes sense to wait for a while.

**Comment by KostyaSha** [comment]
Revert of revert is the exact history action, branching commits with cherry-picking is bad idea.

**Comment by oleg-nenashev** [comment]
It's my technical debt to provide unit tests for this change

**Comment by daniel-beck** [comment]
[JENKINS-28124](https://issues.jenkins-ci.org/browse/JENKINS-28124) may be related: another issue with archiving (zip in this case) possibly introduced by the original commons-compress change and fixed by reverting.

**Comment by oleg-nenashev** [comment]
I have not developed the tests yet, but the patch after the @KostyaSha's adjustment works well on my home server for two months. Probably, it's enough to make another attempt.

**Comment by oleg-nenashev** [comment]
@KostyaSha @daniel-beck 
Do you agree with merging this PR without additional tests ? The new change just fixes the flushing and it is confirmed to work on archiving cases, which had a regression in the first fix.

**Comment by KostyaSha** [comment]
@oleg-nenashev of course, but i thought you already has tests that just need to be cherry-picked. Or point me on master-slave example and i will wrote a test case

**Comment by daniel-beck** [comment]
@oleg-nenashev Also not opposed if the tests are too complicated.

**Comment by KostyaSha** [comment]
@daniel-beck i found how simply wrote a test, working on it

**Comment by KostyaSha** [comment]
Can't reproduce issue using jnlp slave, maybe issues tied only to ssh slaves.

**Comment by KostyaSha** [comment]
Reproduced! 1 byte less or more and test wouldn't work, initially tested on top of 1.610 that fails test.

**Comment by KostyaSha** [comment]
```
jenkins.widgets.BuildListTableTest.linksFromFolders

Failing for the past 1 build (Since Unstable#3044 )
Took 9 sec.
Error Message

elementName=[a] attributeName=[<text>] attributeValue=[d » d2 » p]
Stacktrace

com.gargoylesoftware.htmlunit.ElementNotFoundException: elementName=[a] attributeName=[<text>] attributeValue=[d » d2 » p]
	at com.gargoylesoftware.htmlunit.html.HtmlPage.getAnchorByText(HtmlPage.java:569)
	at jenkins.widgets.BuildListTableTest.linksFromFolders(BuildListTableTest.java:60)
```
Unrelated...

**Comment by KostyaSha** [comment]
Fixuped testcase into fix, re-triggering pr.

**Comment by KostyaSha** [comment]
@oleg-nenashev compress-commons 1.10 released ;) Will try update when current build will be green.

**Comment by KostyaSha** [comment]
Done!

**Comment by oleg-nenashev** [comment]
:+1:

**Comment by KostyaSha** [comment]
@oleg-nenashev everybody refuse merging it because you are in assignee.

**Pull request merged**
