### PR TITLE
[JENKINS-68952] Wrong location of email form validation on setup wizard

### PR DESCRIPTION
**Pull request by Langer0416**
See [JENKINS-68952](https://issues.jenkins.io/browse/JENKINS-68952).
**Before**
Before

**After**
After

### Proposed changelog entries

* Let error messages correspond to correct entry.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] (If applicable) Jira issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [X] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")` if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content-Security-Policy directives (see [documentation on jenkins.io](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/6966"></a>

### CODE REVIEW

**Review by NotMyFault — COMMENTED** [review]
Is there a specific reason why you dropped the exclamation mark next to the form validation?

Also, the validation looks weird, because the warnings aren't update if the input has changed.

**Comment by Langer0416** [comment]
> Is there a specific reason why you dropped the exclamation mark next to the form validation?
> 
I found that signup page do not use the exclamation mark, in my humble opinion, i think it's sufficient enough to use red for error message and red border for input field

<h2> Signup page </h2>

Signup

> Also, the validation looks weird, because the warnings aren't update if the input has changed.
> 

https://user-images.githubusercontent.com/71805759/182999542-eea674ed-61b0-484d-ba23-17c5d1483a0d.mp4

In my test, I need to click the "store and continue" button so that the warnings will update

**Comment by daniel-beck** [comment]
The new version looks fairly similar to how the normal Jenkins UI does field validation, while at the same time being quite different (above the field vs. below, same line as the label vs. on a separate line, no icon vs. icon, not updating live). As a user I wonder why these (relatively minor) differences. The existing validation on the other hand is pretty clearly intentionally different. I might still wonder why, but at least it's so massively different that there's less surprise about the differences in behavior.

Additionally, combining error messages and form field labels seems to make it too easy for users to miss the messages. (Who has time to read more than one word of each label? It's just going to explain what a user name is or something equally irrelevant.) The lack of icons and other highlighting (bold text, bold form field outline, or similar) except for a slight text color change makes this worse.

I am confused by the Jira issue description as well. Is it _wrong_ to have a single block of all validation errors on top of the form, as opposed to a design choice? If so, could you provide references to UI design guidelines saying so? Because as the screenshots here show, it's not like the email validation field is an outlier. It behaves consistently with the other field validations.

**Comment by NotMyFault** [comment]
> As a user I wonder why these (relatively minor) differences. The existing validation on the other hand is pretty clearly intentionally different.

I agree.
The existing form validation is correct, syntax wise, the message is just placed in the wrong location, but I don't see a need to change the existing design to something that isn't proper form validation.

> Is it wrong to have a single block of all validation errors on top of the form

It's not wrong, but it doesn't comply with the format form validation is supposed to be used. See https://weekly.ci.jenkins.io/design-library/Validation/ how it should be done, the validation is attached to the input it belongs to, not somewhere else on the page, which is what the issue is about.

**Comment by daniel-beck** [comment]
> See https://weekly.ci.jenkins.io/design-library/Validation/ how it should be done

Ah, good point. That makes sense. Still, the differences with how form validation otherwise works are awkward.

**Review by DuMaM — APPROVED** [review]

**Comment by Langer0416** [comment]
https://user-images.githubusercontent.com/71805759/183412677-0b48571d-3d4f-4c4b-adc8-c40b6552fe68.mp4

I have moved the error message below the input field, but i haven't make it updating live, if neccessary, I'll do it in my spare time, thanks.

**Comment by NotMyFault** [comment]
> I have moved the error message below the input field

That looks much more promising, thanks!

> but i haven't make it updating live

I wouldn't consider that as blocker for this PR, but would be nice to have if you are interested in a follow up PR to this one.

**Review by NotMyFault — APPROVED** [review]

**Review by basil — APPROVED** [review]
This PR is now ready for merge. We will merge it after approximately 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process. Thanks!

**Pull request merged**
