### PR TITLE
Update license year range to 2016

### PR DESCRIPTION
**Pull request by ozcanovunc**

### CODE REVIEW

**Comment by jtnord** [comment]
the file rename breaks the README.md (and possibly other things as well).

**Comment by batmat** [comment]
IANAL for 7cf3620, why not (though we'd have to change it each year)

As for 676d633, without explanation :-1: on renaming things for no clear reason.

**Comment by ozcanovunc** [comment]
LICENSE.txt was the former name so, just fixed that

**Comment by batmat** [comment]
Double-checking, actually that file has already been renamed 4 years ago. So that would mean that PR was based upon a surprisingly old codebase?

**Comment by ozcanovunc** [comment]
@batmat I thought removing the .txt extension was a good idea, but as jtnord said it may break other stuff. So I just renamed it the way it used to be.

**Comment by daniel-beck** [comment]
I'm not sure this is actually useful. As @batmat wrote, we'd need to update this every year…

**Pull request closed without merging**
