### PR TITLE
Remove inline CSS of setup wizard

### PR DESCRIPTION
**Pull request by NotMyFault**
This PR removes the inline CSS of the setup wizard's instance configuration tab.

### Proposed changelog entries

- N/A, skip changelog
- 

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  - Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")` if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content-Security-Policy directives (see [documentation on jenkins.io](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7055"></a>

### CODE REVIEW

**Comment by janfaracik** [comment]
Awesome 🎆 

What would be the easiest way to test this/access the setup screen from a dev version of Jenkins? I've come across those screens before when running Jenkins in `docker` but I'm not sure of how to access them outside of that.

**Comment by NotMyFault** [comment]
> What would be the easiest way to test this/access the setup screen

No idea if that is the easiest way, but I `export JENKINS_HOME` to a different directory, if I just need to access the setup wizard, to remain existing directories untouched.

**Comment by daniel-beck** [comment]
> What would be the easiest way to test this/access the setup screen from a dev version of Jenkins?

For PR testing, there's `docker run --rm -ti -p 8080:8080 -e ID=7055 -e MERGE_WITH=master jenkins/core-pr-tester`

For local development, I'd set `JENKINS_HOME` to an empty dir and run `java -jar war/target/jenkins.war` after building (possibly adding args to allow attaching a debugger).

`war/pom.xml` sets `hudson.Main.development` to `true` for `mvn jetty:run`, so the wizard is skipped there.

**Review by basil — APPROVED** [review]
Very nice! Not only does this make these styles easier to edit by placing them in a dedicated file with the right format, but also it makes them adhere to our standard `stylelint` format, which improves readability.

**Review by timja — APPROVED** [review]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Review by StefanSpieker — APPROVED** [review]

**Pull request merged**
