### PR TITLE
IdleOfflineCause changelogs and @since

### PR DESCRIPTION
**Pull request by varmenise**
@reviewbybees

### CODE REVIEW

**Comment by tfennelly** [comment]
:bee:

**Comment by jtnord** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
:bug: Please reference JIRA issue or pull request in the changelogs.
Also makes sense to add user-oriented changelog. E.g.: "API changes: Add a reusable implementation of <code>IdleOfflineCause</code> class"

**Comment by olivergondza** [comment]
I agree that whatever deserves a changelog line probably deserves JIRA issue as well. I am not sure if it does or not as there was no client code referenced IIRC.

Btw, does changelog/`@since` updates really needs to be reviewed?

**Comment by oleg-nenashev** [comment]
> Btw, does changelog/@since updates really needs to be reviewed?

It makes sense for first contributions of such kind. Just to avoid extra commits. Oh, we still have no agreement on squashing :(

**Comment by varmenise** [comment]
@oleg-nenashev I do not have any JIRA issue to reference...since it was a really small change

**Comment by oleg-nenashev** [comment]
@varmenise But you can reference the pull request. See examples in the changelog

**Comment by vjuranek** [comment]
>  Just to avoid extra commits. Oh, we still have no agreement on squashing :(

@oleg-nenashev maybe start a discussion on the dev-list? While I'd prefer to squash simple changes like this (actually IMHO there's no need for change log record at all in cases like this one), in general I used to do change log record in a separate commit as it makes backporting more easy (well, solve conflicts in change log is pretty trivial, but still quite annoying)

**Comment by oleg-nenashev** [comment]
@vjuranek 
https://groups.google.com/forum/#!searchin/jenkinsci-dev/[DISCUSS]$20Pull$20Request$20merge$20policy$20for$20core/jenkinsci-dev/kqvuDqXwPZw/BfCun-1MCwAJ

**Comment by varmenise** [comment]
@oleg-nenashev is this ready-to-merge with the last fix?

**Comment by oleg-nenashev** [comment]
@varmenise 
I would prefer a link to PR instead of the commit, but it's up to you. :bee: 
Please squash comments and I'll merge the PR then

**Comment by varmenise** [comment]
@oleg-nenashev squashed

**Comment by oleg-nenashev** [comment]
@varmenise Thanks!

**Pull request merged**
