### PR TITLE
[JENKINS-69177] fix: UC check-all active state

### PR DESCRIPTION
**Pull request by NotMyFault**
See [JENKINS-69177](https://issues.jenkins.io/browse/JENKINS-69177)

<details>
<summary>Proposed change</summary>

https://user-images.githubusercontent.com/13383509/181847567-f2aa7965-30f1-4277-be00-abd20625626b.mp4

</details>

<details>
<summary>Current layout</summary>

https://user-images.githubusercontent.com/13383509/181847594-16e15b9c-897e-402a-a01f-d656e405e335.mp4

</details>

I assume this was missed out or wasn't done on purpose @janfaracik, because we don't keep up checkbox states post click anywhere else 👀 

### Proposed changelog entries

* Fix active state of "Check all" checkbox of the update center.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")` if applicable.
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [x] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/6937"></a>

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by daniel-beck** [comment]
Does this still look reasonable when you have the tri-state mode (All, None, Compatible)?

**Comment by NotMyFault** [comment]
> Does this still look reasonable when you have the tri-state mode (All, None, Compatible)?

Yeah, the change proposed solely gets a rid of the state post click. The recently introduced subinterface isn't affected by it.

**Review by timja — CHANGES_REQUESTED** [review]
This breaks keyboard navigation on all checkboxes, (no focus state)

Do we really have to keep messing with the focus states on these inputs? They are fine as-is imo.

**Comment by NotMyFault** [comment]
> Do we really have to keep messing with the focus states on these inputs? They are fine as-is imo.

No, feel free to disregard this PR if we want to keep the current state as-is. If this is needed for keyboard navigation, let's rather not touch it again 👍🏻

**Pull request closed without merging**
