### PR TITLE
[JENKINS-73600] Fix `jetty:run` error when editing build information

### PR DESCRIPTION
**Pull request by ridemountainpig**
## [JENKINS-73600] Fix `jetty:run` error when editing build information

See [JENKINS-73600](https://issues.jenkins.io/browse/JENKINS-73600).

### Testing done

**Before:**

https://github.com/user-attachments/assets/336e2452-ef23-4927-b6c7-03ecd4f10d48

**After:**

https://github.com/user-attachments/assets/afe60ba0-fe42-40db-b8fb-27701fdbdc0c

### Proposed changelog entries

- Change volatile to transient to avoid serialize error.
- Fixed the error encountered when editing build information.
- Fixed the build.xml file generate fail.

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [x] The Jira issue, if it exists, is well-described.
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [x] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Comment by daniel-beck** [comment]
This change is almost certainly not correct. Culprits should be saved. Unfortunately the "before" video does not show enough of the error message to understand what's happening. All Add-Opens should be set correctly. Please update the Jira issue with additional information how you're running Jenkins.

**Comment by ridemountainpig** [comment]
Here is the error message:
CleanShot 2024-08-12 at 21 40 54@2x

**Comment by daniel-beck** [comment]
The original error message claim is about something that https://github.com/jenkinsci/jenkins/blob/121c0aefd6c1b5b895f6c3f18708240a2c24077b/core/pom.xml#L688 and https://github.com/jenkinsci/jenkins/blob/121c0aefd6c1b5b895f6c3f18708240a2c24077b/war/pom.xml#L205 should be taking care of, so the problem is something else specific to your environment. Deleting a feature is not the solution here.

**Review by daniel-beck — COMMENTED** [review]
The reason I didn't submit this as a PR is, per https://issues.jenkins.io/browse/JENKINS-73600?focusedId=448744&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-448744,

> worth reviewing the other locations for cleanup potential when doing this

Did you do that and determine the other locations remain necessary?

**Comment by ridemountainpig** [comment]
> The reason I didn't submit this as a PR is, per https://issues.jenkins.io/browse/JENKINS-73600?focusedId=448744&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-448744,
> 
> > worth reviewing the other locations for cleanup potential when doing this
> 
> Did you do that and determine the other locations remain necessary?

I have cleanup the unnecessary parts.

**Comment by daniel-beck** [comment]
This change is definitely wrong, since it will break `java -jar jenkins.war`.

I would have expected one or both of the other two to be potentially unnecessary.

**Comment by basil** [comment]
I am uncomfortable with applying `--add-opens` to all Maven invocations, as this unnecessarily increases the scope of the workaround. I would rather just documented these options for `jetty:run` as I have done in #9615, as this limits the scope of the workaround to the smallest possible scope (the one where it is needed).

A promising direction for a long-term solution would be to explore switching to forked mode and using `jvmArgs` as explained in https://jetty.org/docs/jetty/12/programming-guide/maven-jetty/jetty-maven-plugin.html#forked in order to set the `--add-opens` options. That is a bit more work though.

**Pull request closed without merging**
