### PR TITLE
[JENKINS-53462] Submit form on Firefox as well

### PR DESCRIPTION
**Pull request by daniel-beck**
See [JENKINS-53462](https://issues.jenkins-ci.org/browse/JENKINS-53462). Alternative to https://github.com/jenkinsci/jenkins/pull/3760 if we don't want to just revert the change in 2.148.

Revert the original fix and instead patch YUI to submit the event on Firefox as well. Should handle JENKINS-54261 and JENKINS-54333 properly. JENKINS-54570 does not seem to be fixed by this.

Minimal testing so far (Chrome with different UAs indicate behavior works now).

Perhaps someone with more JS-fu can sanity check the change to JS based on the annotated 'debug' version of YUI button. In particular, I wonder whether the browser check could be removed from the condition entirely.

### Proposed changelog entries

* Overhaul compatibility fix for future releases of Firefox due to regressions it caused in Firefox and other browsers.

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [n/a] Appropriate autotests or explanation to why this change has no tests
- [n/a] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### CODE REVIEW

**Review by scherler — APPROVED** [review]
Awesome :1st_place_medal:

**Review by fcojfernandez — APPROVED** [review]
UI is not one of my strengths but looks good to me

**Review by oleg-nenashev — APPROVED** [review]
whatever works

**Comment by Wadeck** [comment]
For those who care about the button-min.js, I checked the diff is just:
`if((l.ie||l.webkit)&&o)`
=>
`if((l.ie||l.webkit||l.gecko)&&o)`  IOW there are no hidden change in the minimized version.

Not that I am not trusting Daniel, but just to avoid other to check that themselves ;)

**Comment by daniel-beck** [comment]
> IIUC this amends #3689 so that the aggregate fix is just

That's correct. Two commits here, one to revert the original fix (like #3760), one with that specific change.

**Review by jvz — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Will merge it tomorrow if there is no negative feedback

**Comment by daniel-beck** [comment]
I'd prefer we used #3760 for this week (i.e. reverting the original change only), while we're waiting for more feedback on this one. We can always merge this next week.

**Comment by oleg-nenashev** [comment]
Agreed

**Comment by oleg-nenashev** [comment]
No opinion from me

**Comment by miketaylr** [comment]
> Un-on-holding this, but we haven't received the feedback I was hoping for. We could always yolo merge this, but note that this seems to re-introduce JENKINS-54570 and possibly JENKINS-54318.

Is there any publicly available staging servers to test the changes here (or something similar)?

**Comment by batmat** [comment]
@miketaylr not really. But there's https://hub.docker.com/r/batmat/jenkins-pr-tester/ that might be helpful for testing locally.

For the case here it would be something like:

`docker run --rm -ti -p 8080:8080 -e ID=3761 batmat/jenkins-pr-tester` then open your browser on http://localhost:8080 (or the IP if you're using a non-native Docker installation)

**Comment by daniel-beck** [comment]
@batmat 

> We could always yolo merge this, but note that this seems to re-introduce JENKINS-54570 and possibly JENKINS-54318

**Comment by batmat** [comment]
Let's close this labelled as `stalled` as you did then.

@daniel-beck wdyt?

We'll reopen then once/if there's an intent to finalize it.

**Comment by whimboo** [comment]
If I find the time for testing, what specifically I would have to check for this PR? I assume a regression would only be affecting Firefox, or all browsers?

**Comment by daniel-beck** [comment]
@whimboo All browsers potentially. [JENKINS-54570](https://issues.jenkins-ci.org/browse/JENKINS-54570) and [JENKINS-54318](https://issues.jenkins-ci.org/browse/JENKINS-54318) explain what we expect to go wrong, but potentially any "Submit" button on the (classic) Jenkins UI.

**Comment by daniel-beck** [comment]
> Let's close this labelled as `stalled` as you did then.

What's the purpose of `stalled` if it's just another way to say `proposed-for-close`?

---

I don't think we should close this; it's essentially done but needs confirmation it's not a breaking change.

**Comment by oleg-nenashev** [comment]
> What's the purpose of `stalled` if it's just another way to say `proposed-for-close`?

I have updated the label description to address this question

**Comment by daniel-beck** [comment]
In my testing, the current PR looks good. When switching Chrome to a Firefox user agent, "Submit" buttons in Jenkins 2.164.1 no longer work, but they do with this PR build.

@Wadeck Could you please try to reproduce [JENKINS-54333](https://issues.jenkins-ci.org/browse/JENKINS-54333) in Jenkins 2.150 (not LTS) and IE, and if reproducible, try the same with the PR build for this PR? I don't have Windows to test this, and was unsuccessful in reproducing that issue on 2.150 with Firefox or Chrome.

**Comment by Wadeck** [comment]
### Reproduction

Win10 1803, IE 11.706.17134.0
On 2.150 (not LTS), the build with parameter does not trigger the build twice. But, I wanted to install the `Parameterized trigger` plugin and got twice the number of installation tasks (double submit for sure). Then with the plugin installed, the build is triggered twice. I uninstall the plugin (+restart), build triggered only once. Reinstall (+restart) build triggered twice.

<details>

<summary>Screenshots</summary>

double_install
double_build

</details>

I tried with Firefox, no issue (with/without plugin). Same for Chrome. Even Edge (42.17134.1.0 = without Chromium engine but still using EdgeHTML) is working fine.


### Correction

Using `jenkins-war-2.172-rc28143.6d41e0cd5272.war`, I re-tested with the same protocol for the 4 browsers and it works fine for all of them.

_Note: I tested every configuration at least 3 times to ensure stability of the results._

**Review by Wadeck — APPROVED** [review]
:bee:

**Pull request merged**
