### PR TITLE
use latest kohsuke/access-modifier

### PR DESCRIPTION
**Pull request by ndeloof**

### CODE REVIEW

**Comment by daniel-beck** [comment]
Reviewer diff: https://github.com/kohsuke/access-modifier/compare/access-modifier-1.11...access-modifier-1.12
Real changes included is just one: https://github.com/kohsuke/access-modifier/pull/5

Please include these in such PRs in the future.

**Comment by daniel-beck** [comment]
As per the PR template that you removed, this seems to be lacking:

>  JIRA issue is well described
>  Link to JIRA ticket in description, if appropriate
>  Appropriate autotests or explanation to why this change has no tests

And there's no proposed changelog entry.

**Comment by ndeloof** [comment]
I used `hub` to create this PR so didn't know about required template

There's no JIRA for this, this is just a version bump
IIUC changelog is managed outside PR review, isn't it ?

**Comment by daniel-beck** [comment]
> There's no JIRA for this, this is just a version bump

So what you're saying is that https://github.com/jenkinsci/jenkins/pull/2870 or https://github.com/jenkinsci/jenkins/pull/2715 didn't need Jira entries either?

If this is too irrelevant to have an issue reference, fine. But "version bump" is not a good answer. And this is clearly not motivated by keeping up to date with an externally maintained component, as the library is basically part of Jenkins, it's your change, and the library has no changelog.

>  IIUC changelog is managed outside PR review, isn't it ?

We expect PR authors to propose changelog entries so those of us who maintain the changelog have an explanation to go with the change. In the past, some changes were just too unclear about what they actually do.

This PR lacks everything besides the code change. No explanation, no diff for reviewers, no proposed changelog. Please don't do that again. We have a PR template for a reason (and if your tools don't support PR templates, please consider not using them).

**Pull request closed without merging**
