### PR TITLE
Set httpOnly and secure on cookies to fix spotbugs issue

### PR DESCRIPTION
**Pull request by StefanSpieker**
After a break from Spotbugs, a small one with setting the httpOnly  and secure flags on cookies. 
See [JENKINS-36720](https://issues.jenkins-ci.org/browse/JENKINS-36720).

### Proposed changelog entries

* Set httpOnly header on cookie for iconSize storage

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

### CODE REVIEW

**Comment by fcojfernandez** [comment]
ATH didn't run because an INFRA issue. Closing and reopening the PR to re-launch the CI.

**Review by fcojfernandez — APPROVED** [review]

**Review by res0nance — APPROVED** [review]

**Review by oleg-nenashev — COMMENTED** [review]
Needs reviews from the security team. I believe these flags were reviewed before and considered to not be a problem for the icon size cookie

**Comment by daniel-beck** [comment]
We don't consider their lack to be a problem ( https://jenkins.io/security/reporting/#vulnerability-types ), so we can add it or not 🤷‍♂

**Review by oleg-nenashev — APPROVED** [review]
I would just merge it and forget. Even if it is not a problem, it could reduce number of vulnerability reports to process.

**Review by timja — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
I plan to merge it tomorrow if no negative feedback

**Pull request merged**
