### PR TITLE
Java 11 test failure: no need to log at WARNING

### PR DESCRIPTION
**Pull request by jglick**
```
java.lang.AssertionError: expected:<[]> but was:<[Running Jenkins with Java 11 which is available in the preview mode only. A custom experimental update center will be used: https://updates.jenkins.io/temporary-experimental-java11/]>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at jenkins.model.StartupTest.noWarnings(StartupTest.java:45)
```

Note that this was marked as a flake because Surefire reruns the test (apparently in the same JVM despite `reuse.forks=false`) and the message is printed in a `static` initializer, which gets run just once.

I was actually looking around at other flakes I saw in #3804, one of which I fixed there (https://github.com/jenkinsci/jenkins/pull/3804/commits/08d273f3c6006896490593cb6e018a21d8c89a26) because it happened enough to mark the build unstable. The others I saw were

```
java.lang.AssertionError: expected:<5> but was:<6>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at hudson.slaves.NodeProvisionerTest.loadSpike(NodeProvisionerTest.java:116)
java.lang.AssertionError: expected:<3> but was:<4>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at hudson.slaves.NodeProvisionerTest.baselineSlaveUsage(NodeProvisionerTest.java:134)
```

which are long-known flakes; in #2188 I let them be since `rerunFailingTestsCount` seems to take care of them, but perhaps these tests should just be disabled (if there is no obvious way to fix them).

### CODE REVIEW

**Review by jvz — APPROVED** [review]

**Review by batmat — APPROVED** [review]

**Review by oleg-nenashev — COMMENTED** [review]
-0.5. I think it should be a warning while we are in the preview mode. It kinda duplicates the warning from Extras executable war, but IMHO here you are just adjust the behavior to the test. IMO we should ignore the warning for Java 11 and create a follow-up to remove it along with the experimental UC

**Comment by jglick** [comment]
> I think it should be a warning while we are in the preview mode.

Subjective I guess. To me this feels like an information message. Nothing is necessarily broken.

**Comment by jglick** [comment]
> we should ignore the warning for Java 11

Do you have a specific recommendation? I am loath to hard-code this message into `StartupTest`.

**Comment by oleg-nenashev** [comment]
> Do you have a specific recommendation? 

Hardcoding looks like an acceptable option to me

**Comment by jglick** [comment]
I tend to disagree, and since we are at an impasse, I would rather leave the test broken (but rerun as a flake) for the duration of the preview mode than clutter the test.

**Pull request closed without merging**
