### PR TITLE
Removed LargeText which was moved a long time ago to stapler

### PR DESCRIPTION
**Pull request by StefanSpieker**
Removed `LargeText` which was moved a long time ago to stapler. I did not find any usage:
[jenkins org search](https://github.com/search?p=1&q=org%3Ajenkinsci+LargeText&type=Code)
[deprecated-and-unused.html](https://ci.jenkins.io/job/Infra/job/usage-in-plugins/job/master/lastSuccessfulBuild/artifact/output/deprecated-and-unused.html)

### Proposed changelog entries

N/A

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by basil — APPROVED** [review]
There is a usage in [`mdt-deployment-plugin`](https://github.com/jenkinsci/mdt-deployment-plugin/blob/7f0d5b3ab78dd56bc37a81eba94a8f3917114660/src/main/java/jenkins/plugins/mdtdeploy/MdtBuildAction.java), but I am fine with dropping support for that plugin as long as this is mentioned in the release notes. Ideally a deprecation notice should be added to `mdt-deployment-plugin` in the plugins site as well.

**Comment by StefanSpieker** [comment]
@basil Thanks for checking!
I created a PR there, just in case the maintainer of the mdt-deployment-plugin is still around.

**Comment by daniel-beck** [comment]
> There is a usage in [`mdt-deployment-plugin`](https://github.com/jenkinsci/mdt-deployment-plugin/blob/7f0d5b3ab78dd56bc37a81eba94a8f3917114660/src/main/java/jenkins/plugins/mdtdeploy/MdtBuildAction.java), but I am fine with dropping support for that plugin as long as this is mentioned in the release notes. Ideally a deprecation notice should be added to `mdt-deployment-plugin` in the plugins site as well.

Do unused imports cause problems?

**Review by daniel-beck — APPROVED** [review]

**Comment by StefanSpieker** [comment]
> > There is a usage in [`mdt-deployment-plugin`](https://github.com/jenkinsci/mdt-deployment-plugin/blob/7f0d5b3ab78dd56bc37a81eba94a8f3917114660/src/main/java/jenkins/plugins/mdtdeploy/MdtBuildAction.java), but I am fine with dropping support for that plugin as long as this is mentioned in the release notes. Ideally a deprecation notice should be added to `mdt-deployment-plugin` in the plugins site as well.
> 
> Do unused imports cause problems? If so, that would be a pretty significant gap in `usage-in-plugins`.

The compiler eliminates the imports as far as I know. So there should be no problem at runtime only during compile-time. So the plugin **will still work**, but throws failures during compiling.

**Comment by daniel-beck** [comment]
> throws failures during compiling.

Once (if ever) the baseline is updated. And since there's another `LargeText` provided by Stapler the IDE might even help.

**Comment by timja** [comment]
so we can remove the incompatible with this change? as it's only a compile time thing?

**Comment by basil** [comment]
Oh right, didn't realize the import was unused. That explains why it wasn't showing up in `usage-in-plugins`. Yes of course; I removed the reference to MDT Deployment from the changelog since there is no compatibility issue.

**Pull request merged**
