### PR TITLE
Improve the 'noJob' view immediately after setup

### PR DESCRIPTION
**Pull request by daniel-beck**
The view shown when there are no items in the current container (sometimes it's a folder, but typically a new Jenkins after setup) has been painfully bad for a long time.

This does a few things:

* Rewrite the view in Groovy to get make it easier to improve further, given the high ratio of control flow statements to actual markup content
* Rephrase some existing entries (what is it with logging in to _create_ jobs? There may already be jobs! — legacy authorization strategy leftover would be my guess)
* Add a call-to-action related to distributed builds. This isn't quite enough, but it's a step towards making people aware of the general topic.

While this doesn't move the needle _that_ far, it is, IMO, a definitive improvement over what we have today.

<details>

<summary>Screenshots</summary>

These are in descending order of permissions:

### Create job, agent, or cloud (Administer)

create job agent or cloud

### Create job or agent (Item.Create / Computer.Create)

create job or agent

### Create job (Item.Create)

create job

### Login or signup

login or signup

### Login

login

</details>

### Proposed changelog entries

* Improve the view shown when there are no jobs

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

### CODE REVIEW

**Review by jvz — APPROVED** [review]
Nice improvement!

**Review by res0nance — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
> Create job, agent, or cloud (Administer)

It is probably a nitpicking, but it would be awesome if this view was showing "Configure Security" as a first item when viewed by anonymous with admin permissions (the current screenshot). Does not block this PR anyway, can be a newbie-friendly follow-up ticket

**Review by oleg-nenashev — APPROVED** [review]
It is definitely a net improvement! 

P.S: I am not a big fan of using Groovy views due to the performance overhead being compared to jelly, but it should not be a problem in this case (temporary stub page)

**Review by timja — APPROVED** [review]

**Review by fqueiruga — APPROVED** [review]

**Comment by fqueiruga** [comment]
Thank you Daniel, it's a great change.

While we are probably going to iterate on this empty states in the future, this PR also does a great job to inform us on design and use cases, as well as to surface interesting call-to-actions.

cc @josephbrueggen

**Review by alecharp — APPROVED** [review]
This is great!

**Comment by alecharp** [comment]
I'm adding the `ready-for-merge` label as this PR passes its requirement. It should be merge in 24hrs unless the PR receives any negative feedback.

**Comment by josephbrueggen** [comment]
Thanks Daniel, this is a great change! Looking forward to seeing this merged.

**Pull request merged**
