### PR TITLE
Use the sponsor button to link to our donation page

### PR DESCRIPTION
**Pull request by rtyler**
This will give us a pretty sponsor button that _actually_ does something maybe useful for the project.

### CODE REVIEW

**Comment by daniel-beck** [comment]
Why not add this to https://github.com/jenkinsci/.github instead?

**Comment by rtyler** [comment]
Seemed like it would be better to try out here first :man_shrugging:

**Review by oleg-nenashev — APPROVED** [review]
LGTM assuming the flow there actually works.
Don't forget to add it to the changelog :P

**Comment by daniel-beck** [comment]
I enabled the option to have a sponsor link, otherwise this does nothing.

**Pull request merged**
