### PR TITLE
Adapt to JUnit 4.13's deprecation of org.junit.Assert.assertThat

### PR DESCRIPTION
**Pull request by basil**
### Problem

We recently upgraded to Junit 4.13, which has [deprecated `org.junit.Assert.assertThat` in favor of `org.hamcrest.MatcherAssert.assertThat`](https://junit.org/junit4/javadoc/latest/org/junit/Assert.html#assertThat(java.lang.String,%20T,%20org.hamcrest.Matcher)). However, this repository still imports the older `org.junit.Assert.assertThat`, both directly and through star imports of `org.junit.Assert.*`.

### Solution

It is no longer desirable to import `org.junit.Assert.*` because this results in importing the deprecated `org.junit.Assert.assertThat` and pollutes the namespace, making it impossible to also import `org.hamcrest.MatcherAssert.assertThat`. Therefore, we start by removing all star imports of `org.junit.Assert.*` and instead use explicit imports of the methods we need. With this out of the way, we were able to easily update all usages of the deprecated method by running `sed -i 's/org.junit.Assert.assertThat/org.hamcrest.MatcherAssert.assertThat/g'` across the entire code base.

### Proposed changelog entries

This change is quite trivial, and in my opinion it does not warrant a changelog entry.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

Nobody in particular.

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [x] There are at least 2 approvals for the pull request and no outstanding requests for change
- [x] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [x] Proper changelog labels are set so that the changelog can be generated automatically
- [x] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [x] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]
Good technique described.  Changes only tests and passes the tests.

**Review by res0nance — APPROVED** [review]

**Comment by res0nance** [comment]
Merging in 24h if no negative feedback

**Review by oleg-nenashev — APPROVED** [review]
Thanks for the cleanup!

**Review by daniel-beck — APPROVED** [review]
Looked at the diff and it's all import changes only, plus a single end-of-file newline added, and five code lines changed to benefit from the static import (`Assert.assertThat` → `assertThat`).

**Comment by daniel-beck** [comment]
Would be good if this weren't squash-merged, the commit history is very clean and nicely separates different actions applied to these files.

**Review by StefanSpieker — APPROVED** [review]

**Comment by res0nance** [comment]
@basil looks like there is a compilation failure could you look into it

**Comment by daniel-beck** [comment]
> looks like there is a compilation failure could you look into it

Concurrent change merged. This needs to be fixed up, then merged quickly.

**Comment by basil** [comment]
Build is green now.

**Pull request merged**
