### PR TITLE
Fix ItemGroupMixInTest compilation.

### PR DESCRIPTION
**Pull request by jeffret-b**
Fix build after #4684.

### Proposed changelog entries

* [n/a]

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [n/a] (If applicable) Jira issue is well described
- [n/a] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [n/a] Appropriate autotests or explanation to why this change has no tests
- [n/a] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [x] There are at least 2 approvals for the pull request and no outstanding requests for change
- [x] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by jeffret-b** [comment]
It looks like #4684 broke the build with a missing import in a test class. At least that's what I'm seeing after updating and building on my local machine.

**Comment by MarkEWaite** [comment]
That's also what is showing in the [CI job](https://ci.jenkins.io/job/Core/job/jenkins/job/master/1981/).  Sorry about that!

**Comment by jeffret-b** [comment]
Just trying to get it fixed quickly before more people are impacted.

**Review by MarkEWaite — APPROVED** [review]
Thanks.  I confirmed I see the build break on the master branch before this change and it is resolved with this PR. Confirmed the PR builds as expected on both Java 8 and Java 11.

Not sure how the break reached the master branch, though likely related to the recent instability of ci.jenkins.io agents.

**Review by dwnusbaum — APPROVED** [review]

**Comment by MarkEWaite** [comment]
Merged before the CI build completed so that it would be less disruptive to developers using the master branch.

**Comment by jeffret-b** [comment]
I updated the master branch and compiled locally. It's building fine now.

**Comment by timja** [comment]
The last build of the other PR passed =/

https://ci.jenkins.io/blue/organizations/jenkins/Core%2Fjenkins/detail/PR-4684/18/

**Comment by jeffret-b** [comment]
It's weird. I don't know what happened.

**Comment by timja** [comment]
I assume related to https://github.com/jenkinsci/jenkins/pull/4717 and a build must not have triggered after the merge, possibly ci.jenkins.io was down at the time

**Comment by MarkEWaite** [comment]
> The last build of the other PR passed =/
> 
> https://ci.jenkins.io/blue/organizations/jenkins/Core%2Fjenkins/detail/PR-4684/18/

Yes, I don't understand what happened there.

I'm usually very curious about that type of failure, but considering how rare that type of failure is for Jenkins core, I'm going to continue my focus on preparing for the UI / UX Hackfest and the documentation improvements we hope to make there.

**Comment by daniel-beck** [comment]
IIUC, PR builds after the master branch changes are triggered after branch indexing, which is scheduled daily.

Timeline:
* May 12, 9:50 PM: Last branch indexing of jenkinsci/jenkins
* May 12, 11:50 PM: #4684 built successfully
* May 13, 2:14 AM: #4717 merged
* May 14, 7:36 PM: #4684 merged, breaking master

So this particular case should have been safe, except the May 13 branch indexing didn't happen. I cannot find related log messages.

**Review by oleg-nenashev — COMMENTED** [review]
Belated +1

**Pull request merged**
