### PR TITLE
[JENKINS-60866][JENKINS-71515] Use `JSON#parse` to process `codemirror-config` argument

### PR DESCRIPTION
**Pull request by daniel-beck**
See [JENKINS-60866](https://issues.jenkins.io/browse/JENKINS-60866).

https://github.com/jenkinsci/antisamy-markup-formatter-plugin/pull/91 would be nice to have, but not necessary.

Strictly speaking, this "just" makes the code behave as documented at https://github.com/jenkinsci/jenkins/blob/d977ee8741ed6362dac282e69a317a070ee9d813/core/src/main/resources/lib/form/textarea.jelly#L68-L71 but since [tons of plugins](https://github.com/search?q=org%3Ajenkinsci+codemirror-config&type=code) set this value badly, I added backward compatibility for what appears to be the most common configuration (`mode`).

### Proposed changelog entries

- Require syntactically valid JSON snippet to be returned from `MarkupFormatter#getCodemirrorConfig` / provided to `codemirror-config` in `f:textarea`.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")` if applicable.
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/6867"></a>

### CODE REVIEW

**Comment by daniel-beck** [comment]
I don't really see why I needed https://github.com/jenkinsci/antisamy-markup-formatter-plugin/pull/91 to make the test pass, any ideas?

**Review by basil — APPROVED** [review]

**Comment by basil** [comment]
What are the next steps for this PR? As far as I can tell https://github.com/jenkinsci/antisamy-markup-formatter-plugin/pull/91 needs to be merged and released, then this PR needs to be updated to a non-incremental build of `antisamy-markup-formatter-plugin`. Is there any additional work that needs to be done?

**Comment by daniel-beck** [comment]
> What are the next steps for this PR? As far as I can tell [jenkinsci/antisamy-markup-formatter-plugin#91](https://github.com/jenkinsci/antisamy-markup-formatter-plugin/pull/91) needs to be merged and released, then this PR needs to be updated to a non-incremental build of `antisamy-markup-formatter-plugin`. Is there any additional work that needs to be done?

Ideally I'd find the time to understand why this needs the plugin update despite the attempt at backwards compatibility.

Otherwise this is just waiting for the plugin release, yes.

**Comment by basil** [comment]
With a passing test suite, this is looking close to ready (if not fully ready) from my perspective. Do others feel that the `mode` compatibility path is sufficient, or do others feel that a more systematic search of cases not covered by that compatibility path is needed? My personal opinion is that while the latter could not hurt, I leave that to Daniel's discretion and trust his judgment regarding whether a systematic search is necessary or not.

**Review by NotMyFault — APPROVED** [review]
Looks fine so far, maybe we can get a release of the antisamy-markup plugin soonish, but I wouldn't consider this as blocker, given the antisamy PR is up for review.

**Comment by basil** [comment]
`antisamy-markup-formatter-plugin` is fully covered by the compatibility path, so while that PR is valuable as a code cleanup, there is no need to hold this PR for that one. Whether there are other plugins not covered by the compatibility path that ought to be considered is a bit of an open question, but as I wrote earlier I won't insist on a systematic search.

**Comment by daniel-beck** [comment]
> Whether there are other plugins not covered by the compatibility path that ought to be considered is a bit of an open question

There are some that I managed to miss when I originally authored this. I'm planning to submit PRs for all of them, but this PR should remain at least for a few more weeks until the more notable ones are fixed.

**Comment by daniel-beck** [comment]
Depends on https://github.com/jenkinsci/jenkins/pull/7071 because some plugins use the workaround in the comments of [JENKINS-15604](https://issues.jenkins.io/browse/JENKINS-15604) that requires the JSON object to hold a JS function (`onblur`). This PR effectively drops support for attributes like these (which might be enough to reject it).

**Comment by NotMyFault** [comment]
The antisamy-markup-formatter-plugin PR has been merged and released, @Wadeck do you mind reviewing this PR, to move it forward, please?

**Comment by Wadeck** [comment]
@NotMyFault I will ask someone (else than Daniel) from security team 👍

**Comment by NotMyFault** [comment]
> @NotMyFault I will ask someone (else than Daniel) from security team 👍

Thanks, just mentioned you, because Daniel requested your review initially.

**Comment by Wadeck** [comment]
it was because of CSP topic :) but you did right, thanks 👍

**Comment by daniel-beck** [comment]
Just in case, I don't think this should be merged yet. I haven't done the followup work for https://github.com/jenkinsci/jenkins/pull/6867#issuecomment-1235907502 yet.

**Comment by basil** [comment]
https://github.com/jenkinsci/cloudbees-feature-management-plugin/pull/86 only has 40 installations, and everything else is merged and released, so are we ready to move forward with this?

**Comment by daniel-beck** [comment]
@basil Depends on your threshold for plugin popularity. Based on the notes I took ~2 yrs ago, `templating-engine` is the only one left with >500 known installs that would be incompatible. I suggest a re-review of current plugins for compatibility in case something new popped up since. I'd be happy to share the old notes or to do it myself, but cannot commit to a date right now.

**Comment by basil** [comment]
While I appreciate the desire for perfection here, perhaps we are falling into analysis paralysis and letting "perfect" be the enemy of "good enough." The value of shipping code is far higher than the value of non-shipping code, and the cost of old PRs is high (including the cost of retesting), so I think we should take it out of draft and ship it in weekly (especially since we are early in an LTS cycle). Whatever minor issues remain can be dealt with if and when they come up.

**Comment by basil** [comment]
Passing ATH: https://github.com/jenkinsci/acceptance-test-harness/pull/1748

**Review by timja — APPROVED** [review]

**Comment by basil** [comment]
Passing PCT: https://github.com/jenkinsci/bom/pull/3651

**Review by basil — APPROVED** [review]
This PR is now ready for merge. We will merge it after approximately 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process. Thanks!

**Pull request merged**
