### PR TITLE
[JENKINS-39172] - Add viewport meta tag

### PR DESCRIPTION
**Pull request by leelavery**
Enables better responsiveness on mobile devices

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
CC @jenkinsci/code-reviewers. I'm not a mobile/web developer && I cannot elaborate this fix since there is no justification of the change and proof of it's compatibility with all browsers. Needs more info, ideally in a JIRA ticket

**Comment by leelavery** [comment]
The viewport tag is well documented, some examples below:

http://www.w3schools.com/css/css_rwd_viewport.asp
https://developers.google.com/speed/docs/insights/ConfigureViewport

Where should I add the JIRA ticket?

**Comment by oleg-nenashev** [comment]
Thanks for the examples
* https://wiki.jenkins-ci.org/display/JENKINS/How+to+report+an+issue
* https://issues.jenkins-ci.org

**Comment by leelavery** [comment]
Thanks,

I have created the following JIRA ticket for this fix
https://issues.jenkins-ci.org/browse/JENKINS-39172

**Comment by oleg-nenashev** [comment]
Looks good to me after reading the docs 👍 
@jenkinsci/code-reviewers (esp. @recena @kzantow and @gusreiber) WDYT?

**Comment by daniel-beck** [comment]
So _that's_ what this change does. :+1: from me as well.

**Comment by firebotQL** [comment]
Looks good to me! Approved to merge!

**Comment by willitscale** [comment]
Can confirm, tested on various Android devices.

**Comment by oleg-nenashev** [comment]
Ready to merge. We will merge this change towards the next weekly if nobody else responds negatively.

**Comment by casz** [comment]
👍 for LTS candidate.

**Comment by leelavery** [comment]
Thanks :)

**Comment by recena** [comment]
👍 but the current layout needs deeper changes if we want to achieve a better UX by using different devices and screen sizes.

**Pull request merged**
