### PR TITLE
Backporting for LTS 2.346.3

### PR DESCRIPTION
**Pull request by NotMyFault**
```
Latest core version: jenkins-2.360

Fixed
-----

JENKINS-68417           Major                   2.358
        System log no longer usable as soon as it is full of "<discarded>" messages (regression in 2.325)
        regression
        https://issues.jenkins.io/browse/JENKINS-68417

JENKINS-68906           Minor                   2.358
        Children context menu is broken when view shows items other than children
        https://issues.jenkins.io/browse/JENKINS-68906           

JENKINS-68672           Minor                   2.360
        Total length of progress bar still difficult to see in shaded rows
        https://issues.jenkins.io/browse/JENKINS-68672

JENKINS-68854           Minor                   2.348
        Upgrade Spring core to 5.3.20 or newer
        https://issues.jenkins.io/browse/JENKINS-68854
```

### CODE REVIEW

**Comment by NotMyFault** [comment]
Would someone mind to take a look please? The RC creation is scheduled for tomorrow.

**Review by basil — APPROVED** [review]
Was [JENKINS-68854](https://issues.jenkins.io/browse/JENKINS-68854) considered and rejected, or not yet considered? No strong preference either way on my side - on the one hand (ideally) I do not want to enable the compliance industry's pointless box checking, but on the other hand (practically) I want to lower the barrier to adoption by users. Not sure how other core maintainers feel. As usual, the final decision falls to you and Tim as the Release Lead / Release Officer.

**Comment by NotMyFault** [comment]
> No strong preference either way on my side

I included it this time. No personal preference for this one either, but I'd rather not backport pointless dependency updates for the sole purpose of silencing scanners, if these don't affect the Jenkins project.
Otherwise a security release would take place, if a vulnerability affects the project.

**Comment by basil** [comment]
> I'd rather not backport pointless dependency updates for the sole purpose of silencing scanners, if these don't affect the Jenkins project. Otherwise a security release would take place, if a vulnerability affects the project.

I'm with you 💯%, and I strongly dislike the unjustified burden the compliance industry imposes on developers, especially open-source developers, so I would definitely not want to go out of my way to enable such parties to continue to make such unjustified requests by accommodating them. At the same time I recognize that not everyone who uses Jenkins has the power to resist such a system, and I do not want to punish the powerless by putting obstacles in their way and making it difficult to adopt new releases of Jenkins. It is a complicated topic, and I don't claim to have the final answer. My point in raising the topic was merely to ensure that a decision was made, not to advocate for one decision over another.

**Comment by MarkEWaite** [comment]
> I'd rather not backport pointless dependency updates for the sole purpose of silencing scanners, if these don't affect the Jenkins project. Otherwise a security release would take place, if a vulnerability affects the project.

I'm more in the other direction.  I think that we should generally backport changes that silence scanners when we believe the risk from the backport is low.  In this case, the dependency has been running in Jenkins weekly for over 8 weeks with no reports of issues related to the dependency.  Thanks for including it in the backport.

@kmartens27 we need to be sure the additional item is included in the 2.346.3 changelog.

**Review by MarkEWaite — APPROVED** [review]

**Review by jglick — APPROVED** [review]

**Comment by basil** [comment]
> I'm more in the other direction. I think that we should generally backport changes that silence scanners when we believe the risk from the backport is low.

[…] because `<insert reason here>`.

I don't intend to turn this into a debate in the context of this PR, as I already approved the PR and expressed my lack of strong preference both with regard to this PR and my moderate viewpoint more generally. But in the appropriate forum (which might not be this PR, perhaps the developer list?) I would love to better understand your reasoning, and I think this is an important and recurring topic where it might be good to have a formal policy for the project.

(Is your reasoning similar to mine (i.e., lowering the barrier to adoption)? It very well might be, but I believe it is important to explicitly state such reasoning and also to acknowledge the opposing view: that this enables behavior from the compliance industry that is to a large degree an unjustified burden, especially on members of the open-source community.)

**Comment by timja** [comment]
> an important and recurring topic where it might be good to have a formal policy for the project.

It is formally documented here as a reason to backport:
https://www.jenkins.io/download/lts/#backporting-process

**Comment by basil** [comment]
Ah, good to know - that makes it an easy decision in the future.

**Pull request merged**
