### PR TITLE
[JENKINS-33358] update Groovy to 2.4.8

### PR DESCRIPTION
**Pull request by daspilker**
See [JENKINS-33358](https://issues.jenkins-ci.org/browse/JENKINS-33358).

### CODE REVIEW

**Review by KostyaSha — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
👍 Should be also an LTS candidate taking the impact into account

**Comment by daniel-beck** [comment]
Changelog: http://groovy-lang.org/changelogs/changelog-2.4.8.html

**Review by batmat — APPROVED** [review]
:+1:

**Comment by daniel-beck** [comment]
Has someone tested this with recent Pipeline releases to make sure there are no regressions there? It's popular enough now that breaking those jobs would be bad.

**Comment by KostyaSha** [comment]
> Has someone tested this with recent Pipeline releases to make sure there are no regressions there? It's popular enough now that breaking those jobs would be bad.

Maybe ok for jenkins dev version.

**Comment by daniel-beck** [comment]
> Maybe ok for jenkins dev version.

I'd rather not break the weeklies either if possible.

**Comment by oleg-nenashev** [comment]
So I've deployed this fix on my home instance with several Pipelines and let it run for a while.
It didn't blow up at least

**Comment by oleg-nenashev** [comment]
@daniel-beck Are you fine with the "depth" of "testing" above?

**Comment by daniel-beck** [comment]
@oleg-nenashev Looks reasonable.

**Comment by yetanotherion** [comment]
Hello to all, @oleg-nenashev FYI we observed 
https://issues.jenkins-ci.org/browse/JENKINS-42189
in our production server.

**Comment by oleg-nenashev** [comment]
@yetanotherion Thanks for raising the issue! "It didn't blow up at least" is definitely not the best criteria for the merges. Will follow-up ASAP (likely tomorrow since I'm traveling today)

**Comment by yetanotherion** [comment]
Great, we'll add more information in the jira (if we find any).

**Pull request merged**
