### PR TITLE
Rename API endpoint to avoid URL collisions

### PR DESCRIPTION
**Pull request by fqueiruga**
Tentative fix for https://github.com/jenkinsci/jenkins/pull/5063#issuecomment-747639676

### Proposed changelog entries

* Fix warning caused by an API endpoint conflict.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@jtnord 
@MRamonLeon 
@timja 
@daniel-beck 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by fqueiruga** [comment]
Not sure about the changelog entry, there's probably a better one.

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
> Not sure about the changelog entry, there's probably a better one.

I don't think a changelog is needed, so skipping unless you / others think otherwise

**Review by daniel-beck — APPROVED** [review]
looks reasonable; untested

**Comment by timja** [comment]
Tested

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Review by res0nance — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
whatever works

**Comment by daniel-beck** [comment]
FWIW, a reasonable pattern might be to start using `foo-bar` for URL names instead of camel casing, except for backwards URL compatibility. That's not part of a legal Java identifier. In this case, `administrative-monitors` would have sidestepped any problem nicely.

**Comment by jvz** [comment]
You could use some [regex magic](https://github.com/apache/logging-log4j2/blob/9ca92302a87238d0255db26354e9266d491f8134/log4j-api/src/main/java/org/apache/logging/log4j/util/PropertySource.java#L104) to support all sorts of syntaxes here.

**Comment by timja** [comment]
@fqueiruga do you intend to change to daniel's suggestion?

**Comment by fqueiruga** [comment]
Yes, I'll try to apply them within the morning

**Comment by daniel-beck** [comment]
FTR optional IMO, just something I thought would be useful information for the future.

**Comment by fqueiruga** [comment]
I'm thinking to not change it then. Having the whole route be `/administrative-monitors-api/nonSecurityPopupContent` is a bit strange IMO.

**Comment by timja** [comment]
feel free to change later if you want

**Pull request merged**
