### PR TITLE
[JENKINS-34676] - Update js-buider and js-test libraries to the latest version

### PR DESCRIPTION
**Pull request by oleg-nenashev**
During fixing of JENKINS-34676 I've discovered that Jenkins 2.1 bundles the obsolete version of jenkins-js-builder. The last release version is 0.0.51, but Jenkins core still bundles 0.0.40. It means the core does not get patches like [this one](https://github.com/tfennelly/jenkins-js-modules/commit/dd98ceefcc28861b11272214aeb9bc32a3aaae62). 

@reviewbybees @tfennelly @recena

P.S: jenkins-cd org on NPM seems to be a very bad idea.

### CODE REVIEW

**Comment by recena** [comment]
:bee:

Very confused

**Comment by oleg-nenashev** [comment]
https://www.npmjs.com/package/@jenkins-cd/js-modules have not been loaded as a transitional dependency ...

**Comment by kzantow** [comment]
🐝

**Comment by oleg-nenashev** [comment]
@tfennelly I have no idea what's going on with these templates :( Maybe encoding

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers @reviewbybees I need some help to understand why js-buider fails

**Comment by oleg-nenashev** [comment]
This stuff is working.
🐝 for the code from @kzantow

**Comment by mslusarczyk** [comment]
🐝

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Comment by oleg-nenashev** [comment]
We need to integrate this fix in order to unblock further development of UIs

**Comment by oleg-nenashev** [comment]
Squashed the stuff

**Comment by oleg-nenashev** [comment]
Putting it on hold, because the compatibility status for https://github.com/jenkinsci/jenkins/pull/2281 is unclear

**Comment by kzantow** [comment]
@oleg-nenashev this just needs a fix, compatibility with #2281 is not an issue

**Comment by oleg-nenashev** [comment]
@kzantow Which fix? Mergeability or what?

**Comment by kzantow** [comment]
Yes sorry... merge fix

**Comment by oleg-nenashev** [comment]
After reviewing the changes in the JS modules code, I propose to put it on hold and merge after the LTS baseline

**Comment by recena** [comment]
@oleg-nenashev :+1:

**Comment by oleg-nenashev** [comment]
@kzantow @recena Do we still need this PR. Or should I close it taking recent changes into the account?

**Comment by recena** [comment]
@oleg-nenashev To me, everything related with these third-party components is very confused. My recommendation is to formalize how these components are released (changelog, tags, etc)

**Comment by oleg-nenashev** [comment]
I think it is no longer required

**Pull request closed without merging**
