### PR TITLE
Changed search max results to 100

### PR DESCRIPTION
**Pull request by ssbarnea**
Change-Id: Ie2667a188388a6e83b615471762fda4555aa4b45

See [JENKINS-47020](https://issues.jenkins-ci.org/browse/JENKINS-47020).

### Proposed changelog entries

*JENKINS-47020, Increased max search results from 20 to 100

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### CODE REVIEW

**Comment by daniel-beck** [comment]
Please don't include unrelated whitespace changes.

**Comment by ssbarnea** [comment]
@daniel-beck I will....  Still, can we get someone to fix the indentation on Jenkins codebase which seems to be a mess. My editor automatically fixed those obviously breaches. Is any linting in place?

**Comment by queria** [comment]
Could it be made configurable through system property instead please?

as e.g. System.setProperty("hudson.plugins.tmpcleaner.TmpCleanWork.days", 3)
so maybe something in the style of System.setProperty("hudson.search.Search.ResultsPerPage", 123)

**Comment by mpryc** [comment]
I like the idea and it should be configurable from the:
- system property
- query level (e.g. &max=150)

**Comment by daniel-beck** [comment]
What's the rationale to have this configurable via system property? Other than just being able to?

**Comment by ssbarnea** [comment]
@daniel-beck I can see @mpryc point of view and I already started to implement it when I seen the comment. I imagined that making this configurable and keeping the old value could be less intrusive for the users and would make it easier to get the code merged. 

I am ok with any approach as long we can improve the user experience, meaning be able to get more than 20 results when we search.

**Comment by daniel-beck** [comment]
> could be less intrusive for the users

Unless this incurs a significant drawback in common setups I'm unaware of, what's the downside of this?

I'd strongly prefer to go ahead with this change and adjust as necessary once an actual need for that gets reported.

**Comment by ssbarnea** [comment]
I think that finding the right value can be tricky when you have to recompile the product to change the maxResult. I had something similar in Jira but Jira got it right like 10+ years ago, is configurable as a system property. 

Also this change needs testing on big instance, dev ones with 3 sample jobs are not of much use. I can have patch updated in less than an hour. The big question would be: so we keep the old default or increase it? 

I need bit of time to see what happens with 100 results.

**Comment by oleg-nenashev** [comment]
Are there any other search controls, which could benefit from such shared system property? 

We already have some search-related settings (e.g. case sensitivity + anticipated recursive search support for itemGroups, cc @alexandertaylor). Maybe it makes sense to create a "SearchSettings" `GlobalConfiguration` and start aggregating these options in UI instead of system properties.

**Comment by ssbarnea** [comment]
@oleg-nenashev To be honest I already hate enough how cluttered is the configuration on Jenkins, every time i need to open `/config` I get a headache. Since I discovered the `init.groovy`I prefer to use it to configure Jenkins. At least this file can be SCM controlled.

The problem is that I am still struggling trying to make the Jelly code work well with the system property. I hope I will succeed in the end. 

BTW, Regarding any bigger value for search results: my impression is that this value is also the same as the auto-complete value, which means that I expect some gui surprises when number of rows will not fit current window. 

Ther results page is simple and does scale well to bigger values.

**Comment by daniel-beck** [comment]
@ssbarnea If there are any concerns about the size of this, maybe we should just start with 50?

I would prefer to not have a (admin) UI option for this. And we've been terrible at retiring system property options, so I'm doubtful that's a good idea either.

Is this something for a per-user cookie, like the ball size? Or is that too horrifying to consider?

**Comment by oleg-nenashev** [comment]
@ssbarnea ping

**Comment by ssbarnea** [comment]
@oleg-nenashev Thanks for pinging, I returned from vacation two days ago. I will try to do the 50-100 approach and update the PR this weekend.

**Comment by oleg-nenashev** [comment]
@ssbarnea bump, Happy Christmas! 🎅  :)

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
No need in reviews according to the discussion above. The ball is on @ssbarnea 's side

**Comment by ssbarnea** [comment]
I was quite busy lately with things bit more important than improving search UX. 

I will be away for one week, but after this I will give it a go. Thanks for pinging me.

BTW, If anyone has time to perform the tests and include screenshots, feel free to do it. Be sure you get a screenshot using 1280x800, which happens to be the 13" MBP screensize which, I think is the "minimal" resolution that we need to test with.

**Pull request closed without merging**
