### PR TITLE
Improve test assertion

### PR DESCRIPTION
**Pull request by jvz**
This fixes a test to check an empty map using a proper method rather than relying on its toString representation.

No JIRA nor changelog entry, trivial improvement.

### Submitter checklist

~~- [ ] JIRA issue is well described~~
~~- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)~~
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
~~- [ ] Appropriate autotests or explanation to why this change has no tests~~
~~- [ ] For dependency updates: links to external changelogs and, if possible, full diffs~~

### Desired reviewers

@reviewbybees

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]

**Review by Wadeck — APPROVED** [review]
Code is good
Please adjust the description of the PR by removing the non applicable sections instead of letting the default text (removing everything between See [...] full diffs)

**Comment by batmat** [comment]
FTR, two tests are failing, and unrelated. Known issue that is being fixed in https://github.com/jenkinsci/jenkins/pull/3795.

:+1: @jvz also as Wadeck said, please complete all fields required in the PR template. I agree here no changelog entry at all is perfect.
Also I recommend to either check a checkbox, or ~~cross~~ the whole item (given generally items are not optional, and showing you saw it but that's it's N/A is better for accelerating reviews)

**Review by batmat — APPROVED** [review]

**Comment by batmat** [comment]
Did it myself this time to shorten the cycle. But remember it next time :-).

**Comment by batmat** [comment]
This looks ready.
I think I will merge this later today, if nobody objects or does this before I do.

Thanks Matt!

**Pull request merged**
