### PR TITLE
[JENKINS-52026] - Adding logging of called CLI commands

### PR DESCRIPTION
**Pull request by jonsten**
This will make it easier to monitor and debug the CLI interface.

See [JENKINS-52026](https://issues.jenkins-ci.org/browse/JENKINS-52026).

### Proposed changelog entries

* Improvement, Added optional logging of called CLI commands

### Submitter checklist

- [X] JIRA issue is well described
- [X] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [X] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

No tests added as change only involves addition of log entry.

### Desired reviewers

@jenkinsci/code-reviewers

### CODE REVIEW

**Comment by jonsten** [comment]
Example of how it looks:
image

**Comment by daniel-beck** [comment]
I wonder whether we can distinguish secret arguments from others, and log regular arguments.

**Comment by jonsten** [comment]
That is an good idea, I deliberately avoided outputting the arguments for that reason. Might also be an idea to truncate long arguments...

**Comment by jonsten** [comment]
Did some digging and unfortunately there doesn't seem to be any way for a command to indicate that an argument is sensitive/secret and should be hidden/obfuscated in logs, for example have a look at the documentation for [Argument](http://args4j.kohsuke.org/apidocs/org/kohsuke/args4j/Argument.html), there is the hidden argument, but that does something completely different...
With that said, it would be possible to add filtering of the built in commands, however there would be no way of doing this in a generic way, i.e. there might be third-party commands which handle sensitive information.

**Review by oleg-nenashev — DISMISSED** [review]
The current state is a good start anyway

**Comment by daniel-beck** [comment]
I think the inclusion of an authorization (or potentially even IP address) here would be necessary to make this *really* useful.

**Comment by jonsten** [comment]
It is certainly possible to add the user id to the log message, problem is that the log message have to be moved downwards in the code, which means that it ends up among the pre-flight checks (permission check), and thus isn't always displayed, e.g. if the user doesn't have correct credentials. With that said, I see a benefit in also logging the different exceptions that can occur, as well as the exit code if the command succeed...

Right now I'm opting for adding one log entry right before going into the run() method, one log entry for each catch clause and finally one which logs that the command executed without exception and the return code. One thing that is bothering me though is the wide try-catch clause and that it is really hard to foresee which statements that might cause the different exceptions, so in some situations there will be two entries (most cases, either initial before run and then one after run or in the catch clause), but for some there will only be one entry from the catch clause. Any thoughts on this?

As for IP, anyone who got an idea of how to get hold of it at that point in the code? Can it be retrieved through the channel object?

**Comment by daniel-beck** [comment]
> thus isn't always displayed, e.g. if the user doesn't have correct credentials

Could you clarify? With the current message I'd not expect anything be logged if the user is rejected.

**Review by daniel-beck — DISMISSED** [review]
> the log entry is written at line 260 but access rejection isn't done before line 274

Right, so this logs commands that aren't even getting executed. This seems confusing.

**Review by Wadeck — APPROVED** [review]

**Review by Wadeck — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]

**Comment by daniel-beck** [comment]
Why aren't call catch clauses getting log messages?

**Comment by jonsten** [comment]
Yes, they already have.. And I'm thinking that there might be people relying on the existing format and behaviour of those...

**Review by daniel-beck — APPROVED** [review]

**Pull request merged**
