### PR TITLE
Mark TarOutputStream as restricted

### PR DESCRIPTION
**Pull request by StefanSpieker**
I'm pretty sure that it is not used anymore, because the search just shows no usage at all:
https://github.com/search?q=org%3Ajenkinsci+TarOutputStream&type=Code

### Proposed changelog entries

* Internal: Removed deprecated TarOutputStream

### CODE REVIEW

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
It is being used in of CloudBees proprietary plugins. CC @jtnord @amuniz .
Unfortunately, just searching GitHub is not always enough, because there are hundreds(thousands?) of private-source plugins created by Jenkins user companies and vendors

**Comment by daniel-beck** [comment]
Also, unfortunately we still distribute some plugins outside the jenkinsci org from several years ago.

For those, https://github.com/jenkins-infra/deprecated-usage-in-plugins works better as it downloads all currently distributed plugins and searches for uses of classes from a list of names.

**Comment by oleg-nenashev** [comment]
Putting `@Restricted(DoNotUse.class)` could be a good option once https://github.com/kohsuke/access-modifier/pull/17 is released. `@Restricted(NoExternalUse.class)`  can be used as a workaround to highlight deprecation for plugin maintainers. PCT will not fail, so why not?

**Comment by StefanSpieker** [comment]
Ok, that is a good idea. I also added this annotation to the TarInputStream and already created PRs for plugins which still use this class:
https://github.com/jenkinsci/copy-to-slave-plugin/pull/11
https://github.com/jenkinsci/fstrigger-plugin/pull/4

**Comment by daniel-beck** [comment]
Probably the most pragmatic approach.

`@RestrictedSince` might be helpful too, as would be `@deprecated` in Javadoc with explanation.

**Comment by oleg-nenashev** [comment]
+1 for `@RestrictedSince`. We can safely assume it lands in the next weekly (2.200)

**Comment by StefanSpieker** [comment]
I added the @RestrictedSince("2.200")  as suggested

**Review by oleg-nenashev — APPROVED** [review]
Thanks!

**Review by daniel-beck — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
I plan to merge it tomorrow if no negative feedback

**Review by halkeye — APPROVED** [review]

**Pull request merged**
