### PR TITLE
[JENKINS-54933] Replace ZeroClipboard (Flash) with native JavaScript implementation

### PR DESCRIPTION
**Pull request by NicuPascu**
See [JENKINS-54933](https://issues.jenkins-ci.org/browse/JENKINS-54933)
Removes ZeroClipboard from the copyButton and replaces it with js. The change has been tested on IE9+ browsers.

Also updates the icon with the clipboard icon from material icons.

### Proposed changelog entries

* Replace "copy button" feature initially implemented in Flash with the native JavaScript equivalent

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [n/a] For dependency updates: links to external changelogs and, if possible, full diffs

@imeredith @davidbees

### CODE REVIEW

**Comment by NicuPascu** [comment]
clipboard

**Review by oleg-nenashev — DISMISSED** [review]
Whatever CORE-626 is, there must be a public issue with explanation of the issue

**Comment by NicuPascu** [comment]
@oleg-nenashev I'll get a public issue and link it back here, thanks

**Comment by Wadeck** [comment]
It seems that only the Windows AtomicFile test is failing, but it seems more a flaky issue than a real one introducted by this PR.

**Review by jvz — APPROVED** [review]
LGTM.

**Review by Wadeck — APPROVED** [review]
:bee:

**Review by oleg-nenashev — APPROVED** [review]
Manually tested it in latest versions of Firefox, Chrome, IE and Safari. LGTM

**Comment by oleg-nenashev** [comment]
If somebody is interested, I used https://github.com/batmat/jenkins-pr-tester/pull/3 to simplify the test run

**Pull request merged**
