### PR TITLE
Revert "Jenkins.getInstance() should be non-null"

### PR DESCRIPTION
**Pull request by oleg-nenashev**
This reverts commit bb7c8fcedbcc9b51c5b1bb5b32810af5ac6b1ffb, which has been submitted without a pull request. This is a breaking change, so I propose to revert it. If the submitter feels strongly, he can create a pull request as other Jenkins contributors do.

https://github.com/jenkinsci/jenkins/commit/bb7c8fcedbcc9b51c5b1bb5b32810af5ac6b1ffb
See the discussion there.

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by amuniz** [comment]
:+1: :bee:

**Comment by stephenc** [comment]
:bug: :-1:

**Comment by stephenc** [comment]
To be clear, show a case where this is a breaking change?

Show a case where a plugin can legitimately find `Jenkins.theInstance == null`

**Comment by recena** [comment]
:bee: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by stephenc** [comment]
@oleg-nenashev FTR I will not remove my :bug: unless you can show a case where a plugin can legitimately encounter `Jenkins.theInstance==null`

**Comment by andresrc** [comment]
@stephenc I agree with your reasoning. However, the concern I have is:

- We should aim for all plugins to build cleanly against their baseline version and against the last (or at least last LTS version).
- For all plugins with a baseline between https://github.com/jenkinsci/jenkins/commit/fa496c7bf228ecb243acf0135106f18f27132c6f and https://github.com/jenkinsci/jenkins/commit/bb7c8fcedbcc9b51c5b1bb5b32810af5ac6b1ffb and findbugs enabled (which should be an increasing number) we are going to introduce much boilerplate just to have clean builds in the described scenarios.

Is the change worth it?

**Comment by stephenc** [comment]
@andresrc what boilerplate?

If your baseline is below 1.653 then just call `Jenkins.getActiveInstance()`... you are a plugin, you can do that safely... there is no code path where you could ever have that method explode

When your baseline is above 1.653, replace the call to the deprecated method by `Jenkins.getInstance()` and rejoyce

**Comment by oleg-nenashev** [comment]
@stephenc 

It's breaking change, because you change the **documented** behavior:

```
Gets the {@link Jenkins} singleton.
       * {@link #getActiveInstance()} provides the checked versions of the method.
       * @return The instance. Null if the {@link Jenkins} instance has not been started,
       * or was already shut down
```

I don't even need to provide examples of breaking changes, but below you can find several ones (just first ones I've found). In all cases there is a logic, which explicitly handles the null value in order to do something arbitrary.
* https://github.com/jenkinsci/google-source-plugin/blob/33836a2e9a66c79f4b6ae7a5a51832a4d12381ca/src/main/java/com/google/jenkins/plugins/metadata/scm/JenkinsUtils.java#L39-L54
* https://github.com/jenkinsci/async-http-client-plugin/blob/2b13fa8c148486d29358d68269f43ed9edc98619/src/main/java/jenkins/plugins/asynchttpclient/AHCUtils.java#L34-L56 
* https://github.com/jenkinsci/regression-report-plugin/blob/0e0d127f77e8bb77e96f53e156549c03166e5e99/src/main/java/jp/skypencil/jenkins/regression/UserIdToAddr.java#L24-L32
* https://github.com/jenkinsci/poll-mailbox-trigger-plugin/blob/bfeccd8c3d51d9581a581ed229e8b98f57a36778/src/main/groovy/org/jenkinsci/plugins/pollmailboxtrigger/SafeJenkins.java#L39-L52

I you believe such examples are not enough, I can propose a valid corner-case for Jenkins startup and shutdown logic. There are listeners being invoked at that time, so it's not a big deal to generate a use-case. I'm pretty sure it's possible to find it in existing plugins, but I don't want to spend much time on explaining obvious Javadoc viiolations.

**Comment by andresrc** [comment]
We still have 1.580.x which is a rather important target baseline left in the dust.

**Comment by stephenc** [comment]
The examples you provide are doing redundant null checks.

If you are a plugin, there is no code path where `theInstance == null`

* https://github.com/jenkinsci/google-source-plugin/blob/33836a2e9a66c79f4b6ae7a5a51832a4d12381ca/src/main/java/com/google/jenkins/plugins/metadata/scm/JenkinsUtils.java#L39-L54 show how that method can be called with `theInstance == null`
* https://github.com/jenkinsci/async-http-client-plugin/blob/2b13fa8c148486d29358d68269f43ed9edc98619/src/main/java/jenkins/plugins/asynchttpclient/AHCUtils.java#L34-L56 that method cannot be called during start-up without `theInstance != null` as it is not on any classloader before `theInstance` has been set. The AHC shared singleton is [torn down during termination](https://github.com/jenkinsci/async-http-client-plugin/blob/2b13fa8c148486d29358d68269f43ed9edc98619/src/main/java/jenkins/plugins/asynchttpclient/AHCPlugin.java#L18) so actually that use should throw an exeception if `Jenkins.isTerminating()` 
* https://github.com/jenkinsci/regression-report-plugin/blob/0e0d127f77e8bb77e96f53e156549c03166e5e99/src/main/java/jp/skypencil/jenkins/regression/UserIdToAddr.java#L24-L32 is not used outside of the safe part of the plugin lifecycle
* https://github.com/jenkinsci/poll-mailbox-trigger-plugin/blob/bfeccd8c3d51d9581a581ed229e8b98f57a36778/src/main/groovy/org/jenkinsci/plugins/pollmailboxtrigger/SafeJenkins.java#L39-L52 is a test method helper and could safely be rewritten to just call `getActiveInstance()` (pre 1.653) or `getInstance()` (post 1.653) as it was going to throw an exception if it was null anyway... and that exception can never be null in the plugin classloading lifecycle

**show an example of a valid code path**

:bug:

**Comment by stephenc** [comment]
>  In all cases there is a logic, which explicitly handles the null value in order to do something arbitrary.

In all cases there is a logic *driven by the `@CheckForNull` annotation* where the user has been forced to handle a null check that they **never** will encounter.

Find a **valid** code path where a plugin *could* validly encounter a null Jenkins... here are some hints to help you with your search:

* A plugin adding a shutdown hook via [Runtime.addShutdownHook(java.lang.Thread)](http://docs.oracle.com/javase/7/docs/api/java/lang/Runtime.html#addShutdownHook(java.lang.Thread)) might perhaps be a candidate... :grinning:  though in those cases the plugin is actually implementing a bug because the Jenkins may be shutdown without restarting the servlet container... we should fix those bugs which will likely remove the shutdown hook... if they really need the shutdown hook then they will also have a call to `removeShutdownHook` in a `@Terminator` annotated method and as such we can then assure ourselves that the hook will never be called with a null `Jenkins.theInstance`

* Look for plugins providing servlet filters... :grinning: of course the bug there is that they fail to remove them in a `@Terminator` method or in `Plugin.stop()`

It is up to you to provide a case where any **plugin** is doing the correct thing and could find `Jenkins.theInstance == null`. Core has legitimate code paths where it may be null... fewer than the 65 I left, and there is a PR I am preparing to switch the safe ones to `getInstance()` from `getInstanceOrNull()`

**Comment by stephenc** [comment]
* Plugins that have code that runs on slave^H^H^H^Hagent threads remotely and calls Jenkins.getInstance() to see if they are running on the master or on a slave... :smiley: that is wrong as we should not be pulling the `Jenkins` class over remoting into slaves. The code should be refactored to writeReplace when serialized over a Channel such that the remote safe variant is loaded in a remote JVM

**Comment by oleg-nenashev** [comment]
@stephenc 
Sorry, I'm not going to spend time on my public holiday to just formally confirm the obvious breakage. Maybe I'll find some time to do it tomorrow. BTW I think you just want others to spend more time on this issue.

1. Javadoc describes the behavior of Jenkins.getInstance()
2. The proposed change violates the described behavior
3. The change potentially breaks the things

It's enough IMO

**Comment by jtnord** [comment]
> We still have 1.580.x which is a rather important target baseline left in the dust.

@andersrc Who is we here - as far as I am aware no one is offering support of 1.580.

**Comment by oleg-nenashev** [comment]
@stephenc 
I won't be against changing the methods in 2.0. It is a legitimate way for breaking changes, so I would recommend to propose it there

**Comment by stephenc** [comment]
@oleg-nenashev I repeat, there can be no plugin that uses these methods that will be broken by the change to throw the exception on null.

all plugins pre 1.653 should just do a straight `s/getInstance()/getActiveInstance()/`... in any cases where they are making that call in a class that is invoked in an agent JVM and not on the master JVM... that is a bug in the plugin that they should fix

it is a contract of the `Jenkins` constructor and `Jenkins.cleanUp()` that all plugin code can safely assume when running on the master that `Jenkins.theInstance != null`... any deviation from that contract is a bug in core that we should just fix. (e.g. [JENKINS-33384](https://issues.jenkins-ci.org/browse/JENKINS-33384), [fixed](https://github.com/jenkinsci/jenkins/pull/2093))

Given that 2.0 is making the argument that existing plugins should "just work" punting this change until 2.0 is not a runner IMHO... at best you are saying punt it until 3.0... which is long fingering in the extreme.

The reality is that nobody actually did the correct analysis when the annotation of `@CheckForNull` was being proposed and thus the argument for the `getInstance()` method being `@Nonnull` was incorrectly lost. We want the code to be better, so we should fix the code **now** not next month, not next year

:bug: stands, you have yet to show a valid code path where this revert is necessary

**Comment by stephenc** [comment]
@oleg-nenashev if you want to change this PR to 

```
@@ -719,17 +719,18 @@ public class Jenkins extends AbstractCIBase implements DirectlyModifiableTopLeve
     /**
      * Gets the {@link Jenkins} singleton. In certain rare cases you may have code that is intended to run before
      * Jenkins starts or while Jenkins is being shut-down. For those rare cases use {@link #getInstanceOrNull()}.
+     * In other cases you may have code that might end up running on a remote JVM and not on the Jenkins master,
+     * for those cases you really should rewrite your code so that when the {@link Callable} is sent over the remoting
+     * channel it uses a {@code writeReplace} method or similar to ensure that the {@link Jenkins} class is not being
+     * loaded into the remote class loader
      * @return The instance.
      * @throws IllegalStateException {@link Jenkins} has not been started, or was already shut down
      */
     @CLIResolver
-    @Nonnull
+    @Nullable // TODO replace with non-null once Jenkins 2.0+
     public static Jenkins getInstance() {
-        Jenkins instance = HOLDER.getInstance();
-        if (instance == null) {
-            throw new IllegalStateException("Jenkins has not been started, or was already shut down");
-        }
-        return instance;
+        // TODO throw an IllegalStateException in Jenkins 2.0+
+        return HOLDER.getInstance();
     }
 
     /**
```

I would be fine with that.

**Comment by andresrc** [comment]
@jtnord is not support of the version, I'm talking of plugins which baseline is that version.

**Comment by stephenc** [comment]
@andresrc if their baseline is 1.580.x then they can safely call `getInstance()` because they are a plugin and plugins will never see a `null` instance (if they do see a `null` instance then it is a bug in core, e.g. [JENKINS-33384](https://issues.jenkins-ci.org/browse/JENKINS-33384))

**Comment by stephenc** [comment]
Note that in my alternative diff I use the `@Nullable` annotation because the caller is supposed to know those cases where it could be `null`... i.e. where you are invoking the method from plugin code that is running in a remote JVM

**Comment by oleg-nenashev** [comment]
> I repeat, there can be no plugin that uses these methods that will be broken by the change to throw the exception on null.

Or there may be closed-source plugins using such thing for something. Nobody knows. That's why people write API specifications and follow them

> Given that 2.0 is making the argument that existing plugins should "just work" punting this change until 2.0 is not a runner IMHO... at best you are saying punt it until 3.0... which is long fingering in the extreme.

But putting it into the current release trunk is even worse in such case.

> The reality is that nobody actually did the correct analysis when the annotation of @CheckForNull was being proposed and thus the argument for the getInstance() method being @Nonnull was incorrectly lost. We want the code to be better, so we should fix the code now not next month, not next year

It has been proposed because we had bug reports for startup script hooks. The change has been reviewed and merged. Maybe there is an architecture bug, but it's a topic for the discussion at least.

Nobody in the community is expected to make sole decisions and to push changes without letting the community to review the changes. We have an agreement on this topic within the community (E.g. see [Jan 6 Governance meeting notes](http://meetings.jenkins-ci.org/jenkins-meeting/2016/jenkins-meeting.2016-01-06-19.01.log.html)). It may become a strict policy when @orrc finishes the proposal, but I think it would be good to follow the agreements now even if somebody recommends you to do the other thing.

**Comment by jglick** [comment]
:bee:. I have cases of code written according to the documented contract of `getInstance()` and checking for null which will cause errors if this method throws an `IllegalStateException` (and which I know will encounter this situation because I added the null check in response to actual `NullPointerException`s prior to FindBugs enforcing it). Perhaps those plugins were misusing some other API which resulted in this situation, in which case a legitimate and comprehensive change would include a technique to diagnose such mistakes and a tested solution.

Anyway no one should be obliged to justify themselves on technical grounds in this issue. The onus is on @stephenc to file a PR according to the usual process and convince others of the correctness of his argument. _Deliberately_ unreviewed commits should simply be reverted at once, regardless of the author or content.

**Comment by slide** [comment]
+1

**Comment by stephenc** [comment]
See https://github.com/jenkinsci/jenkins/pull/2094 for my suggested resolution

**Comment by orrc** [comment]
> Nobody in the community is expected to make sole decisions and to push changes without letting the community to review the changes. It may become a strict policy when @orrc finishes the proposal

@oleg-nenashev I fulfilled my action item for that meeting (the proposal wasn't mine to begin with), but it hasn't been followed up so far in a later meeting.
FWIW, I do support what I think is the non-controversial stance of requiring PRs for core code changes.

(Semi on-topic: I have a fairly vague feeling that I was at some point guilty of trying to access `Jenkins.getInstance()` from a `Callable` in a plugin — so I imagine there are instances of that out there)

**Comment by stephenc** [comment]
I did not anticipate this much venom. My original plan was to go with a PR, but I was pursuaded that such a PR would be a nightmare of re-review and inability to progress.

#2094 is the PR to make the bb7c8fc change via a PR

**Pull request closed without merging**
