### PR TITLE
[JENKINS-39414] Stapler 1.247

### PR DESCRIPTION
**Pull request by jglick**
[Changes](https://github.com/stapler/stapler/compare/stapler-parent-1.246...stapler-parent-1.247), most notably https://github.com/stapler/stapler/pull/85

@reviewbybees esp. @oleg-nenashev

### CODE REVIEW

**Comment by abayer** [comment]
:bee:

**Review by andresrc — APPROVED** [review]
:bee:

**Comment by svanoort** [comment]
🐝

**Comment by vivek** [comment]
🐝

**Comment by oleg-nenashev** [comment]
🐝  Ideally we should start maintaining the Stapler changelog like we do in Remoting

**Pull request merged**
