### PR TITLE
Improvements for translation-tool.pl

### PR DESCRIPTION
**Pull request by damianszczepanik**
After several tests of 3bfe97e40f675d9ecd47d120fb9fe3d0576ab5a7 I found that library does not support:
- proper using characters stored as \uXXXX so then translated files have values without \u
- keys with spaces such as `jenkins\ title` is not supported

So then I decided to revert last commit and add a little improvement but still there are problems with
- values which ends with `\` so value is provided as multiline
- lines with more than single `=` character that are already translated

Best example is [SetupWizard](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/jenkins/install/SetupWizard/authenticate-security-token.properties#L3) which has both cases included.

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change).
- [x] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers
@oleg-nenashev

### CODE REVIEW

**Comment by damianszczepanik** [comment]
@oleg-nenashev  looks like there is some problem with Jenkins and I don't have rights to retrigger the build

**Comment by oleg-nenashev** [comment]
Hi Damian, I cannot help with it now. Please see
https://groups.google.com/d/msg/jenkinsci-dev/uc6NsMoCFQI/AIO4WG1UCwAJ .

**Review by oleg-nenashev — APPROVED** [review]
Looks good to me.
@damianszczepanik It may make sense to move the translation tool to a separate repository so that it is possible to have a separate Jenkinsfile, versioning for it and, maybe packaging for CPAN/Docker/whatever. WDYT?

**Comment by damianszczepanik** [comment]
Sounds good except one: looks like there are no many persons who use it so I will be the only maintainer and I don't want to maintain technology which I'm not good at :)

**Comment by oleg-nenashev** [comment]
Maybe Chinese Localization SIG would be interested in extending the localization tooling. CC @LinuxSuRen

**Comment by oleg-nenashev** [comment]
Also, migrating the tool from Perl to Python/Go/Groovy could be an interesting project for GSoC. CC @jenkinsci/sig-gsoc members

**Comment by martinda** [comment]
Interesting, could it be part of the GSoC realted to documentation improvements?

**Comment by LinuxSuRen** [comment]
If we could have a Go version of this, I'd like to maintain it. Agree with that be part of GSoC. I can be the mentor of it.

**Pull request merged**
