### PR TITLE
Update SSHD Module

### PR DESCRIPTION
**Pull request by daniel-beck**
Integrate https://github.com/jenkinsci/sshd-module/pull/35

### Proposed changelog entries

* Update SSHD module from 2.6 to 2.7 which allows configuring disabled key exchange and MAC algorithms through system properties, removing deprecated algorithms by default.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
+1 for merging once released

**Comment by daniel-beck** [comment]
Unsure whether upstream approvals count, but requesting re-reviews anyway 😄

**Review by Wadeck — APPROVED** [review]
:bee:

**Comment by daniel-beck** [comment]
Planning to merge tomorrow.

**Review by jvz — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
@jenkinsci/core Would it make sense to merge this PR early today so that it gets into the upcoming weekly? More soak testing before the next baseline selection would not hurt

**Review by MarkEWaite — APPROVED** [review]

**Comment by MarkEWaite** [comment]
> @jenkinsci/core Would it make sense to merge this PR early today so that it gets into the upcoming weekly? More soak testing before the next baseline selection would not hurt

Yes, that makes sense to me.

**Comment by oleg-nenashev** [comment]
Component changelog has been added by @daniel-beck  https://github.com/jenkinsci/sshd-module/blob/master/CHANGELOG.md#27. IMHO we should also mention the protocol removal in upgrade guidelines. Last time we did that, there were escalations from users.

**Pull request merged**
