### PR TITLE
[JENKINS-37315] Stop A/B testing JNLP3

### PR DESCRIPTION
**Pull request by stephenc**
@jenkinsci/code-reviewers @reviewbybees

See [JENKINS-37315](https://issues.jenkins-ci.org/browse/JENKINS-37315)

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
🐝 and strong 👍 for the LTS line.
Regarding the weekly builds, I think it makes sense as well

**Comment by jglick** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
The PR builder issue seem to be related:

```
12:45:23 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.0:compile (default-compile) on project jenkins-core: Compilation failure
12:45:23 [ERROR] /scratch/jenkins/workspace/core/jenkins-core/core/src/main/java/jenkins/slaves/JnlpSlaveAgentProtocol3.java:[157] error: class, interface, or enum expected
```

**Comment by olivergondza** [comment]
What is the impact of the bug change? As I understand it, the negotiation can fail and then JNLPv2 will be used without users even noticing.

**Comment by oleg-nenashev** [comment]
@olivergondza 
If JNLP3 is not explicitly enabled/disabled, there won't be random enablement of this protocol on the master. Now on default installations Jenkins randomly sets up the support flag on each start, which is... ehm... not an expected behavior for LTS

**Comment by stephenc** [comment]
@olivergondza @oleg-nenashev fixed syntax error... curses upon `vi` for letting me make such a silly error... also upon whoever did an `if` without a `{` o the same line

**Comment by daniel-beck** [comment]
@oleg-nenashev 

> Jenkins randomly sets up the support flag on each start

Isn't `getLegacyInstanceId` constant over time?

**Comment by oleg-nenashev** [comment]
@daniel-beck You're right. So the selection is constant, but it's still something hidden from users

**Comment by samrocketman** [comment]
> If JNLP3 is not explicitly enabled/disabled, there won't be random enablement of this protocol on the master. Now on default installations Jenkins randomly sets up the support flag on each start, which is... ehm... not an expected behavior for LTS

Okay, clarify a bit for me.  It was my understanding that when JNLP3 was merged Jenkins would use that by default.  Now I've been reading in a few issues it sounds like JNLP3 support can have some percentage of errors and be subject to fall back to JNLPv2.  Do I have this right?

**Comment by stephenc** [comment]
Well first off it is a memory hog. Second it is a CPU resource hog for larger installations as it is Thread-per-client rather than NIO in JNLP2. There are other things but this is a public forum.

JNLP4 uses standard TLS encryption and NIO and is ridiculously less pressure on memory (see my Jenkins World talk tomorrow for details) so ultimately we want to ditch all protocols and move to JNLP4... Oleg has some concerns about formal API compatibility... But given that JNLP3 did not honour some of the API contracts in the first place, I argue that ship has sailed... In any case, JNLP4 is merged to master in remoting and we are awaiting a new remoting release to pick it up in Jenkins.

**Pull request merged**
