### PR TITLE
Update to latest version to support M2E

### PR DESCRIPTION
**Pull request by batmat**
See https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jenkinsci-users/FjzMrudsfb0/2oWXs9mZDAAJ
where we see Eclipse import fails.

See https://github.com/mojohaus/build-helper-maven-plugin/issues/43
And https://github.com/mojohaus/build-helper-maven-plugin/commit/f6d1fea90ccf7d9ef03e4587ac440d645f4c9898

No JIRA.

### Proposed changelog entries

* `Internal:` update `build-helper-maven-plugin` from 1.7 to 3.0 to make Jenkins more easily importable in Eclipse IDE.

### Submitter checklist

- ~JIRA issue is well described~
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
LGTM as long as it works

**Review by jglick — APPROVED** [review]
I guess the build would fail if you got it wrong?

**Review by jtnord — COMMENTED** [review]
not tested but seems sane

**Comment by batmat** [comment]
OK, actually I found about https://github.com/jenkinsci/jenkins/commit/0268cc99293ba985fe0a919e8c0633e33174f049 added by @jglick.

The right fix, which I'm going to push right now, is to **delete* the version line.

But Jesse, please tell me if you know/remember why you forced it to 1.7 in https://github.com/jenkinsci/jenkins/commit/0268cc99293ba985fe0a919e8c0633e33174f049

**Comment by batmat** [comment]
OK, override removed. `build-helper-maven-plugin` actually got bumped to 3.0.0 one year ago in https://github.com/jenkinsci/pom/pull/16/files#diff-600376dffeb79835ede4a0b285078036L726

**Review by jtnord — APPROVED** [review]

**Comment by jglick** [comment]
> Jesse, please tell me if you know/remember why you forced it to 1.7 in [0268cc9](https://github.com/jenkinsci/jenkins/commit/0268cc99293ba985fe0a919e8c0633e33174f049)

It was already forced to 1.7 in `pom.xml`. I merely moved the `<version>` down into `core/pom.xml` as that was the last remaining use of the plugin.

**Review by jglick — APPROVED** [review]

**Pull request merged**
