### PR TITLE
Verify that *.properties do not have duplicated keys

### PR DESCRIPTION
**Pull request by jglick**
Noticed some accidental duplications in #1888, corrected here, and introduced automatic test for core and plugins to prevent recurrence, correcting some existing problems.

@reviewbybees

### CODE REVIEW

**Comment by KostyaSha** [comment]
Have you checked that this messages are not using from plugins?

**Comment by jglick** [comment]
> Have you checked that this messages are not used from plugins?

Not quite sure I follow. I am only removing duplicate (thus conflicting) definitions of a property in some translation file. Should have no possible impact on plugins.

(Plugin tests _may_ start failing when they update their core dep and get the new `InjectedTests`—if they had duplicated messages. Which is intentional.)

**Comment by oleg-nenashev** [comment]
Probably a case for automatic autotests for Jenkins core and plugins

**Comment by KostyaSha** [comment]
:+1:

**Comment by oleg-nenashev** [comment]
:bee: from what I see

**Comment by jglick** [comment]
Test failures are the as-yet-undiagnosed

    NoClassDefFoundError: Could not initialize class com.cloudbees.plugins.credentials.SystemCredentialsProvider$ProviderImpl

**Comment by KostyaSha** [comment]
I see this error all time during local development. No idea what messed with descriptors. 
I had similar error only when made live restart of jenkins container it ends in new Descriptors registration and causes absence of Descriptor in ExtensionsList.

**Pull request merged**
