### PR TITLE
[JENKINS-73586] Fix New Item page layout if no icon is defined for an item type

### PR DESCRIPTION
**Pull request by scherler**
https://github.com/jenkinsci/jenkins/pull/9111

introduced a new styling however it broke the styling of the default icon generation in case there is no icon defined. as shown in 1aff74c07aed24815b3b1161cfbe79a9339eab80 

image

After fix 
image

### Testing done

Interactive checks

### Proposed changelog entries

- Fix "New Item" page layout if no icon is defined for an item (regression in 2.453).

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [x] The Jira issue, if it exists, is well-described.
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [x] There is automated testing or an explanation as to why this change has no tests.
- [x] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [x] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [x] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [x] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [x] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Review by janfaracik — APPROVED** [review]

**Comment by janfaracik** [comment]
Thanks!

Out of curiosity, is there a situation where an item type wouldn't provide an icon?

**Comment by mawinter69** [comment]
e.g. the [Coordinator](https://plugins.jenkins.io/coordinator/) plugin implements a new project type but is not providing an icon or image. So it displays wrong:
image

**Comment by janfaracik** [comment]
> e.g. the [Coordinator](https://plugins.jenkins.io/coordinator/) plugin implements a new project type but is not providing an icon or image. So it displays wrong: image

Thanks! 

Any thoughts on this - Depending on how many plugins there are that don't provide an icon, could we instead update the plugins to include an icon rather than maintaining this logic in core?

**Comment by scherler** [comment]
There are some situations in which you cannot provide an icon without a bigger rewrite, IMHO it is there, and removing such functionality is problematic since we have no way of knowing how many plugins depend on this.

**Review by basil — APPROVED** [review]

**Comment by timja** [comment]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by daniel-beck** [comment]
This should have a Jira issue for backporting into LTS.

**Comment by scherler** [comment]
@daniel-beck I created JENKINS-73586

**Pull request merged**
