### PR TITLE
Update login_tr.properties

### PR DESCRIPTION
**Pull request by mcansozeri**
first meaning of "Create" is "oluşturmak" in Turkish, second one is "yaratmak". So "oluşturmak" is better transaction.

Google translate also says the same thing you can check it by clicking following link: 
https://translate.google.com/?sl=en&tl=tr&text=create%20&op=translate

"Oluşturmak" is to create an instance of existing things. "Yaratmak" is to create a thing that does not exist before.

### CODE REVIEW

**Comment by mustafau** [comment]
It is translated as "yaratmak" in the following page too. Can you also update that page?

https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/index_tr.properties

**Comment by mcansozeri** [comment]
It's updated as well. Thank you for message.

**Review by res0nance — APPROVED** [review]

**Review by MarkEWaite — APPROVED** [review]
Approving since two native Turkish speakers are involved in the pull request.

**Comment by MarkEWaite** [comment]
This PR is now ready for merge.  We will merge it after approximately 24 hours if there is no negative feedback.

**Pull request merged**
