### PR TITLE
[JENKINS-59164] - `Functions#toEmailSafeString()` was not really sanitizing the email string

### PR DESCRIPTION
**Pull request by StefanSpieker**
See https://issues.jenkins-ci.org/browse/JENKINS-59164

I wanted to fix a spotbugs issue [UC_USELESS_OBJECT](https://spotbugs.readthedocs.io/en/latest/bugDescriptions.html#uc-useless-object-created-uc-useless-object)
but actually it might be a bug, although it is only used in a deprecated method, I think it can either be removed totally or fixed. I hope it is fixed like the original author has intended to be.

### Proposed changelog entries

* Internal: Minor fix 

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
Looks like a bug. Would be nice to have a JIRA ticket so that we can backport it

**Comment by StefanSpieker** [comment]
I created a Bug report for that:
https://issues.jenkins-ci.org/browse/JENKINS-59164

**Review by Wadeck — APPROVED** [review]
Good job, thank you!
We corrected very recently the A-Z part, without looking at the return value, shame on us ^^

**Review by jvz — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Will merge it tomorrow if no negative feedback

**Comment by oleg-nenashev** [comment]
Thanks a lot @StefanSpieker !

**Pull request merged**
