### PR TITLE
[FIXED JENKINS-33377] Add a check for termination to Functions.isExtensionsAvailable()

### PR DESCRIPTION
**Pull request by stephenc**
@reviewbybees @jenkinsci/code-reviewers

### CODE REVIEW

**Comment by rsandell** [comment]
:bee:

**Comment by imod** [comment]
:+1:

**Comment by jtnord** [comment]
:bee:

**Comment by stephenc** [comment]
@reviewbybees done

**Comment by stephenc** [comment]
and we have a community vote too

**Pull request merged**
