### PR TITLE
[JENKINS-36745] Block single quote in new item name

### PR DESCRIPTION
**Pull request by samatdav**
If job name contains a single quote, Jenkins allows to create it.
However, a user cannot delete such job after. Clicking "Delete Project" throws
`SyntaxError: missing ) after argument list`

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
It would be better to fix the job deletion flow BTW

**Comment by daniel-beck** [comment]
:-1: As I wrote in the issue,

> Looks similar to JENKINS-31871 – the bug in the JS should be fixed rather than prohibit chars.

**Comment by KostyaSha** [comment]
Duplicates #1943 ?

**Comment by oleg-nenashev** [comment]
Yes, it's a duplicate

**Pull request closed without merging**
