### PR TITLE
[JENKINS-31718] Integrated a new version of Remoting

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-31718](https://issues.jenkins-ci.org/browse/JENKINS-31718)

[Changes](https://github.com/jenkinsci/remoting/compare/remoting-2.53...remoting-2.53.1) from https://github.com/jenkinsci/remoting/pull/65

@reviewbybees esp. @stephenc & @kohsuke, also @olivergondza & @akshayabd

### CODE REVIEW

**Comment by jtnord** [comment]
:bee:

**Comment by stephenc** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
And :+1: since it addresses the known serious issue

**Pull request merged**
