### PR TITLE
Fix phrasing error in Polish translation of install wizard

### PR DESCRIPTION
**Pull request by jwojnarowicz**
Update Polish translation for `installWizard_skipFirstUser` to more clear definition of action which states that "skip" means "pomiń[PL]"

Although it is a minor change, it significantly improves context and describes the action that the button takes. The previous one translates into *"Continue as an administrator"* which might suggets continuing as the user that is being created since we create first "admin" user in this wizard.

New translation is more clear as it translates into *"Skip and continue as an administrator"* which **signals the skipping** of first user creation. New translation corresponds directly with English *"Skip and continue as admin"*.

### Proposed changelog entries

- Update Polish translation for install wizard message to skip first user.

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Comment by daniel-beck** [comment]
> Skip and continue as an administrator

FWIW the intention is to refer to the user by the generated default user name `admin`. It's going to be an administrator account (account with Overall/Administer permission) no matter what you call it.

This probably should be improved in the English version to make this clearer, perhaps through formatting similar to the one in the previous paragraph.

**Comment by jwojnarowicz** [comment]
@daniel-beck I agree as in English version it is admin.
My suggested change aimed to introduce clear description of the action, as now it does not inform the user of `skipping`. 

Do you suggest changing it to `admin` as it refers to the name of the user rather than *administrator* which may be mistaken with permissions?

**Comment by daniel-beck** [comment]
> Do you suggest changing it to `admin` as it refers to the name of the user rather than administrator which may be mistaken with permissions?

Yes.

**Comment by jwojnarowicz** [comment]
Changed it to `admin` 😉

**Review by daniel-beck — APPROVED** [review]
Google Translate looks reasonable

**Review by MarkEWaite — APPROVED** [review]
This PR is now ready for merge.  We will merge it after approximately 24 hours if there is no negative feedback.

/label ready-for-merge

**Pull request merged**
