### PR TITLE
Add debug log to track duration of run

### PR DESCRIPTION
**Pull request by sdenel**
Issue: When elapsed time is under the threshold, no message is provided to know that the triggered ran successfully / how much time it took.

### Proposed changelog entries

- Add a FINER log with the time it took to execute the trigger.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7222"></a>

### CODE REVIEW

**Review by NotMyFault — COMMENTED** [review]
How did you test this PR, to ensure it accomplishes the desired outcome, if the change as-is is blocked by Java logic flaws 🤔

**Comment by sdenel** [comment]
Dear @NotMyFault,
Error fixed. I do not have an environment set up to test this PR. A careful review will be muchly appreciated!
BR,
Simon

**Comment by daniel-beck** [comment]
Please test your PR (you can use the PR build for that, or the [core-pr-tester](https://github.com/jenkinsci/core-pr-tester)) and demonstrate what the results look like.

**Comment by sdenel** [comment]
Tested locally, it works as expected.

**Review by basil — COMMENTED** [review]
Could use an automated test based on [`LoggerRule`](https://github.com/search?ref=simplesearch&type=Code&q=user%3Ajenkinsci+LoggerRule).

**Comment by NotMyFault** [comment]
Hey @sdenel,

do you mind addressing Basil's feedback, please? https://github.com/jenkinsci/jenkins/pull/7222#pullrequestreview-1136397018

Thanks!

**Comment by NotMyFault** [comment]
Hey @sdenel,

thanks for your pull request. I'll go ahead and close it for now, until the addition of an automatic test that covers the issue highlighted or some sort of validation to ensure this PR resolves the issue in question.
Your changes aren't lost, you are very welcome to reopen the PR once feedback is addressed and your work is presented in a reviewable state.

Thanks!

**Pull request closed without merging**
