### PR TITLE
[FIXED JENKINS-29507] Make JenkinsRule useable on systems without JNA

### PR DESCRIPTION
**Pull request by vjuranek**
https://issues.jenkins-ci.org/browse/JENKINS-29507

### CODE REVIEW

**Comment by olivergondza** [comment]
@pjanouse?

**Comment by pjanouse** [comment]
This commit isn't enough to solve the issue - status detection whether JNA works or not on target platform because it doesn't cover a MS Windows platform - for similar use-cases as hudson.util.jna.GNUCLIBRARY is used hudson.util.jna.Kernel32 there (because libc doesn't exists on MS Windows, only under Cygwin emulation layer).

This code will disable JNA on MS Windows which isn't desired behavior.

On the other hand MS Windows has to be tested properly before using JNA because for ex. MS Windows on Itanium architecture has an issue in the core currently (see JENKINS-29997).

**Comment by vjuranek** [comment]
@pjanouse could you be more specific where is the problem? If affect only parts of `JenkinsRule` which calls `GNUCLibrary.LIBC`, so if `isJnaSupported()` is able to to load `GNUCLibrary.LIBC`, `JenkinsRule` should be able to do so as well. Or you mean that function name `isJnaSupported` is not accurate?

**Comment by vjuranek** [comment]
`isJnaSupported` is really inaccurate. I renamed it to `isGlibcSupported`

**Comment by pjanouse** [comment]
@vjuranek I think it is worth to know if we can call JNA function in Jenkins/testsuite/wherever and if it works. It looks Jenkins rely on JNA quite heavily but doesn't have fallback properly if something goes wrong (e.g. you can try to run Jenkins on HP-UX or RHEL ppc64 and you can see many exceptions, however it basically 'operates', don't try run it on MS Windows Itanium - you were warned:))

You are right - current impl. references the newly introduced function in JenkinsRule only, so only JenkinsRule is affected. When you renamed the function to more accurate name, I don't have any objection against this commit however I'm still missing more general and robust solution for JNA status detection/retrieving which I can use over Jenkins core later.

**Comment by olivergondza** [comment]
@vjuranek, do you mind moving the method into `JenkinsRule` and making it private so we can merge it right away and provide a better fix eventually without impacting BC?

**Comment by vjuranek** [comment]
@pjanouse agree that better and more compact JNA API would be nice, but it requires much more work and is not subject of this issue.

@olivergondza what's exactly the reason for it? If you re-work JNA one day, you will either break API anyway by removing/changing `GNUCLibrary` (probably making its API private and moving it behind some facade) or keep it and provide alternative approach, but as long as `GNUCLibrary` is public `isGlibcSupported` should be IMHO public as well

**Comment by jglick** [comment]
:+1:

**Comment by vjuranek** [comment]
One month without answering my question - merging myself.

**Pull request closed without merging**
