### PR TITLE
[FIXED JENKINS-53561] HashedToken is not Serializable

### PR DESCRIPTION
**Pull request by jtnord**
See [JENKINS-53561](https://issues.jenkins-ci.org/browse/JENKINS-53561).

### Proposed changelog entries

* Internal: `HashedToken` was not `Serializable`

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@Wadeck @agentgonzo  @jenkinsci/code-reviewers

### CODE REVIEW

**Review by agentgonzo — APPROVED** [review]

**Review by Wadeck — APPROVED** [review]
:bee:

**Review by oleg-nenashev — APPROVED** [review]
ok

**Review by daniel-beck — APPROVED** [review]
🤷‍♂️

**Comment by oleg-nenashev** [comment]
Something is wrong with ATH, I doubt test failures are related

**Comment by jtnord** [comment]
failures are `1) Error in custom provider, org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/usr/bin/firefox) on port 7055; process output follows:`

merging.

**Pull request merged**
