### PR TITLE
sezpoz 1.12

### PR DESCRIPTION
**Pull request by jglick**
@daniel-beck requested some better diagnostics about `META-INF/annotations/hudson.Extension`, which this release provides.

[Upstream changes](https://github.com/jglick/sezpoz/compare/pom-1.11...pom-1.12)

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
Not yet in Central apparently, will need to close & reopen in a few hours. (Would be nice if our CI builders could [pick it up directly](https://oss.sonatype.org/content/repositories/releases/net/java/sezpoz/sezpoz/).)

**Comment by andresrc** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
🐜 From what I see there are binary incompatible changes in the library. I do not see impact on the Jenkins core and OSS plugins, but as always there may be closed-source plugins. Do you see a risk in it?

**Comment by jglick** [comment]
> there are binary incompatible changes in the library

Where?

**Comment by oleg-nenashev** [comment]
@jglick 
Indexer6 to Indexer renaming: https://github.com/jglick/sezpoz/commit/3d864793630bf6385cff1f8a5b7d4f1e5a8959d2

**Comment by oleg-nenashev** [comment]
That issue could be easily fixed by creating deprecated Indexer6 class, which would inherit Indexer

**Comment by jglick** [comment]
> Indexer6 to Indexer renaming

Compatible. This was in an implementation package, since it is used only via service registration, and even then only during compilation not runtime.

**Comment by oleg-nenashev** [comment]
If it's compilation-only, then it's fine
🐝 and @reviewbybees  done

**Review by Thompson1985 — APPROVED** [review]

**Pull request merged**
