### PR TITLE
Adding test coverage for BuildAuthorisationToken

### PR DESCRIPTION
**Pull request by jtnord**
I could not see any test coverage for BuildAuthorisationToken so added
some.

No JIRA - as this is improving test coverage.

### Proposed changelog entries

N/A test code only

### Submitter checklist

- [ ] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### CODE REVIEW

**Review by Wadeck — APPROVED** [review]
Good to see more test 👍

**Comment by oleg-nenashev** [comment]
@jtnord are you still working on it? Or would you be fine with the merge of the current state? Seems fine

**Review by vilacides — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Retriggered the build

**Review by varyvol — APPROVED** [review]

**Review by fcojfernandez — APPROVED** [review]

**Comment by jtnord** [comment]
merging in current state as it is passing and has approvals and woot test coverage :)

**Pull request merged**
