### PR TITLE
[JENKINS-67197] Build project with POST links to blank page

### PR DESCRIPTION
**Pull request by benebsiny**
See [JENKINS-67197](https://issues.jenkins-ci.org/browse/JENKINS-67197).

Since the page redirects to the blank page after "Proceed" button is clicked in the "require POST" page, I make the page reload.

### Proposed changelog entries

* Reload after the "Proceed" button is clicked in the "require POST" page.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] (If applicable) Jira issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
I think this is a valid fix. We do not consider it as an expected call, but still makes sense to improve the UX a bit

**Comment by NotMyFault** [comment]
> I think this is a valid fix. We do not consider it as an expected call, but still makes sense to improve the UX a bit

Wouldn't it make sense to redirect to the job page instead of a reload? The `/build` tab has no indicator wether you have enqueued a job or not, nor is it something you should use to queue up jobs (I guess?).

**Comment by oleg-nenashev** [comment]
@NotMyFault agreed, the job page would be better.

**Comment by benebsiny** [comment]
It seems that this way would be more intuitive, thanks for the suggestion!

**Review by NotMyFault — APPROVED** [review]

**Comment by timja** [comment]
why are you using this page? Just to hack overriding the quiet period?

The page clearly states you shouldn't be using it in its content. 

Bit worried that this has no on failed handling in what it will do, seems weird to submit the form via JavaScript, shouldn't it have a server side redirect (or not be a thing...)

**Comment by MarkEWaite** [comment]
> why are you using this page? Just to hack overriding the quiet period?

That's how I use it.  I believe the schedule build plugin uses the same technique but provides a (weak) UI in addition.

**Review by timja — COMMENTED** [review]
Imo this is not a bug, it's an unsupported feature (which we may accept something like this). 

My review from before is the same, why are we doing this client side?

**Comment by basil** [comment]
Agreed with Tim that the redirect should be done in the backend.

**Comment by basil** [comment]
Hello @benebsiny, would you be able to address Tim's feedback? We haven't heard back from you since this PR was opened 4 months ago, so I am labeling this PR as `stalled`. In the absence of a response I plan to transition it to `proposed-for-close` in approximately one month and close it approximately one week after that.

**Comment by benebsiny** [comment]
@basil  I'm not sure where can I put the code in the backend to redirect the page.😅 It seems that we cannot do the redirection action in `requirePOST.jelly`.

**Comment by basil** [comment]
There are many examples of this. Try running `git grep -i redirect` in `core/src/main/java/`.

**Comment by basil** [comment]
Since the review feedback has not yet been completed and several months have elapsed, including a week with no response after applying the `proposed-for-close` label, I am closing this PR. On behalf of the core team, I would like to thank you for your contribution. Even though this PR did not make it across the finish line, it was a promising start! I continue to encourage you (or anyone else who is interested!) to pick up this effort and drive it to completion. Thanks!

**Pull request closed without merging**
