### PR TITLE
Update french documentation

### PR DESCRIPTION
**Pull request by aureliesalles**
Fix of some mistakes in french help documentation.

### CODE REVIEW

**Comment by batmat** [comment]
:+1: cc @aheritier @alecharp @vlatombe

**Comment by daniel-beck** [comment]
@batmat @aheritier @alecharp @Vlatombe BTW coverage of French `.properties` files is around 55%. You guys could spend an afternoon each to fix that ;-)

**Comment by batmat** [comment]
+1 @daniel-beck I think we could encourage @aureliesalles to keep going on this after this nice first stab :-). 

(She knows Jenkins pretty well and is a Java developer, so has no excuse not to do it ;-)).

**Comment by daniel-beck** [comment]
@batmat @aureliesalles I'd be happy to help – I've gone through the same process for #2777 recently, so the wounds, er, memories are still recent. Just poke me on IRC.

**Comment by aheritier** [comment]
Don't count on me @daniel-beck , I'm never using the FR UI @daniel-beck for Jenkins or anything else in IT.

**Review by aheritier — APPROVED** [review]

**Review by Vlatombe — APPROVED** [review]

**Review by alecharp — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Thanks to @aureliesalles and all the reviewers!

**Pull request merged**
