### PR TITLE
[FIX JENKINS-33767] Only show the upgrade banner when Jenkins is in charge

### PR DESCRIPTION
**Pull request by kohsuke**
@daniel-beck noticed that the banner shouldn't show up while Jenkins is starting

### CODE REVIEW

**Comment by kohsuke** [comment]
@reviewbybees

**Comment by kzantow** [comment]
:bee:

**Comment by daniel-beck** [comment]
:+1:

**Comment by daniel-beck** [comment]
@kohsuke Actual test failures.

**Comment by kohsuke** [comment]
Test failures are the usual flakes.

**Pull request merged**
