### PR TITLE
[JENKINS-71244] Avoid relative link in update center

### PR DESCRIPTION
**Pull request by Bananeweizen**
See [JENKINS-71244](https://issues.jenkins.io/browse/JENKINS-71244).

* convert the relative link to an absolute one, since it might be used in different contexts
* update all message bundles to use the new format argument

Note: To my mind, _all_ relative URLs in properties files are a bad design choice, since the related code may be used from different context URLs. It would probably be rather easy to detect such issues with a regex checkstyle rule looking for `href=".` in properties files. If core maintainers agree, I could raise a separate issue for that.

### Testing done

I've run a developer instance with this change. But I have not been able to force the update center error on my local machine. So Jenkins still runs, but the actual change is untested.

### Proposed changelog entries

- JENKINS-71244: Fix update center proxy configuration hyperlink in error messages

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] The Jira issue, if it exists, is well-described.
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7992"></a>

### CODE REVIEW

**Review by NotMyFault — COMMENTED** [review]
Thanks for the PR! I have tested issue described on the master branch via
```diff
diff --git a/core/src/main/java/hudson/model/UpdateCenter.java b/core/src/main/java/hudson/model/UpdateCenter.java
index b9ca1d2001..7fb5a2ce89 100644
--- a/core/src/main/java/hudson/model/UpdateCenter.java
+++ b/core/src/main/java/hudson/model/UpdateCenter.java
@@ -1680,6 +1680,7 @@ public class UpdateCenter extends AbstractModelObject implements Saveable, OnMas
 
                 connectionStates.put(ConnectionStatus.UPDATE_SITE, ConnectionStatus.CHECKING);
                 statuses.add(Messages.UpdateCenter_Status_CheckingJavaNet());
+                statuses.add(Messages.UpdateCenter_Status_UnknownHostException("yo"));
 
                 config.checkUpdateCenter(this, site.getUrl());
 
```
to replicate the problem the issue linked describes, without messing with networking. 
The URL to the proxy configuration page is resolved properly:
Screenshot 2023-05-26 at 13 58 13
I'm not confident this PR addresses an actual issue, given I can't replicate the issue described.

**Comment by Bananeweizen** [comment]
@NotMyFault I'm not exactly sure, but it looks like you are on the main page of the update center when trying to reproduce, right? If I remember it right from the issue, I was actually installing updates (i.e. my screenshot shows pluginManager/updates). Since that error message can appear on pages with different depth from the root, a fixed relative address (as before the patch) cannot work in all cases.

**Comment by NotMyFault** [comment]
> I was actually installing updates

I see, you were on `/manage/pluginManager/updates/`. On this view, I can replicate the issue with the patch I added above, on the master branch and verify the change proposed working.

I recommend removing the leading slash in the .properties files because `Jenkins.get().getRootUrl()` adds a trailing slash to all URLs creating a double slash: `http://localhost:8085//manage/pluginManager/advanced`

**Comment by Bananeweizen** [comment]
> I recommend removing the leading slash in the .properties files because `Jenkins.get().getRootUrl()` adds a trailing slash to all URLs creating a double slash: `http://localhost:8085//manage/pluginManager/advanced`

Done. I also like it when such things are cleaned up. :) And I'll have to remember your trick of not even fiddling with the network if it's easily possible to just trigger the error condition in (additional) code. Thanks for that.

I didn't rebase, assuming that simplifies your review and you'll probably rebase on submit anyway. Please tell me if that doesn't fit to typical Jenkins project workflows.

**Comment by NotMyFault** [comment]
> I didn't rebase, assuming that simplifies your review and you'll probably rebase on submit anyway. Please tell me if that doesn't fit to typical Jenkins project workflows.

No worries, all good. We don't do that during the review phase, given it detaches code comments, slows the time-to-merge down for no good reason, and generally causes more harm than good.
To maintain a clean history, PRs are squashed, typically.

**Review by NotMyFault — APPROVED** [review]

**Review by timja — APPROVED** [review]
.

**Comment by timja** [comment]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by daniel-beck** [comment]
This breaks links when the UI is not accessed through the configured root URL.

**Comment by NotMyFault** [comment]
> This breaks links when the UI is not accessed through the configured root URL.

Would you recommend a change independent of `#getRootUrl`?

**Comment by daniel-beck** [comment]
> Would you recommend a change independent of `#getRootUrl`?

This should use `Jenkins#getRootUrlFromRequest`, or `StaplerRequest#getContextPath` (like the Jelly variable `rootURL`).

**Comment by daniel-beck** [comment]
> This should use `Jenkins#getRootUrlFromRequest`, or `StaplerRequest#getContextPath` (like the Jelly variable `rootURL`).

FTR doing this would also be incorrect, as the full error message is kinda persisted and not recomputed in every request.

[JENKINS-71905](https://issues.jenkins.io/browse/JENKINS-71905) documents the problem this change causes, but I'm not sure there's a trivial fix.

**Pull request merged**
