### PR TITLE
Fix run generate-weekly-changelog.sh failed

### PR DESCRIPTION
**Pull request by shenxianpeng**
See https://github.com/jenkinsci/core-changelog-generator/issues/37

### Proposed changelog entries

- Fix run generate-weekly-changelog.sh failed

### Proposed upgrade guidelines

N/A

### Desired reviewers

@timja

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Comment by MarkEWaite** [comment]
Thanks!  I've pushed the same change to the fix-changelog-script branch on the repository and am running the changelog drafter action from that branch now.  Results should be visible in https://github.com/jenkinsci/jenkins/actions/runs/11350472763

**Comment by MarkEWaite** [comment]
> Thanks! I've pushed the same change to the fix-changelog-script branch on the repository and am running the changelog drafter action from that branch now. Results should be visible in https://github.com/jenkinsci/jenkins/actions/runs/11350472763

That seemed like a good idea but when the changelog drafter run in that job, it reported a failure inside the Python script.  The failure was related to date parsing an empty return value from `git log`.  I assume that means the virtual environment was created correctly and this can be merged.

**Comment by MarkEWaite** [comment]
Merging immediately because the CI checks are not useful for this pull request

**Comment by MarkEWaite** [comment]
Confirmed that the changelog drafter is running again.  Thanks very much @shenxianpeng !

**Review by timja — COMMENTED** [review]
thanks for moving the change here! +1

**Pull request merged**
