### PR TITLE
Update cvs plugin to 2.16

### PR DESCRIPTION
**Pull request by alxsap**
- CVS plugin [changelog](https://github.com/jenkinsci/cvs-plugin/blob/master/CHANGELOG.md) (2.12 - 2.16)

### Proposed changelog entries

* Update the bundled CVS Plugin from 2.12 to 2.16 - [changelog](https://github.com/jenkinsci/cvs-plugin/blob/master/CHANGELOG.md)

### Proposed upgrade guidelines

N/A

### Submitter checklist

- N/A (If applicable) Jira issue is well described
- N/A Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by daniel-beck — APPROVED** [review]

**Comment by daniel-beck** [comment]
Thanks, looks like an oversight when updating bundled plugins.

**Review by oleg-nenashev — APPROVED** [review]
+1. Would be happy to get rid of this plugin being bundled.

We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Comment by timja** [comment]
Tests are failing:

image

Re-ran multiple times

**Comment by daniel-beck** [comment]
````
 java.io.IOException: Failed to load: Jenkins CVS Plug-in (2.16)
 - Plugin is missing: jsch (0.1.54.2)

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
additional fix is needed as @daniel-beck wrote above

**Comment by varyvol** [comment]
@alxsap did you have the opportunity to review the build failure? It seems like this needs some extra work.

**Comment by Wadeck** [comment]
CVS plugin was removed => closing

**Comment by daniel-beck** [comment]
Specifically in https://github.com/jenkinsci/jenkins/pull/5102 after https://github.com/jenkinsci/jenkins/pull/5096 attempted a simple update, and failed for the same reason as this PR.

**Pull request closed without merging**
