### PR TITLE
Remove hardcode of JKS for use other key stores

### PR DESCRIPTION
**Pull request by gulyaev13**
See thread in Jenkins dev [Jenkins Core and Plugins VS FIPS 140-2](https://groups.google.com/g/jenkinsci-dev/c/YkEG_oSR1mw).

### Proposed changelog entries

* Entry 1: Remove the hardcode with JKS Keystore to allow using other Keystores. For example, BCFKS provided in the FIPS version of Bouncy Castle.
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by jvz** [comment]
Honestly, I'm surprised this wasn't using PKCS11 instead as that's a lot easier to use than Java keystore files.

**Review by jeffret-b — APPROVED** [review]
Makes sense and works fine in my limited testing.

**Review by timja — APPROVED** [review]

**Review by jvz — APPROVED** [review]
Definite improvement over the old value here.

**Comment by daniel-beck** [comment]
There is no concern around backwards compatibility here, correct?

**Comment by jeffret-b** [comment]
I haven't been able to find any issues with backwards compatibility.

**Comment by jvz** [comment]
Old keystore files can be converted with standard java tools.

**Review by oleg-nenashev — APPROVED** [review]
We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Review by res0nance — APPROVED** [review]

**Pull request merged**
