### PR TITLE
[FIXED JENKINS-41182] - Support nodes with 0 executors

### PR DESCRIPTION
**Pull request by ksenia-nenasheva**
Currently Jenkins doesn't support nodes with 0 executors, but it allows creating such nodes. For example see [JENKINS-41182](https://issues.jenkins-ci.org/browse/JENKINS-41182). This pull request adds proper handling of such case, which is useful for FlyWeight tasks.

- allow setting 0 executors in node configuration (fix form validation)
- show computers with 0 executors in Executors widget (see ScreenShot)
- show computers with 0 executors in the Computer list
- allow scheduling FlyWeight tasks to nodes with 0 executors
- prevent error 404 when accessing node pages

### Proposed changelog entries

* Entry 1: TODO
* ...

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### CODE REVIEW

**Comment by daniel-beck** [comment]
@ksenia-nenasheva 

> which is useful for FlyWeight tasks.

Could you explain this? What reason would there be to host flyweight tasks on a non-master agent? It's just more fragile (and AFAICT likely related to a misuse of flyweight executors).

**Comment by ksenia-nenasheva** [comment]
@daniel-beck 
Before my change, FlyWeight tasks were able to run on agents having at least one executor. It is being used in the Multi-configuration job type, which used to be a part of the Jenkins core. So it was a design decision to allow it.

I just made it possible to run such tasks on agents with 0 executors, which seems to be a valid behavior for Flyweight tasks.

**Comment by ksenia-nenasheva** [comment]
@jenkinsci/code-reviewers

**Comment by olivergondza** [comment]
The thing is the flyweight executor is merely a thread in Jenkins master JVM regardless to what node it is scoped to. Creating nodes to host flyweight executors only does not seem to make sense as the tasks can run on different nodes or master without observable difference.

**Comment by oleg-nenashev** [comment]
> The thing is the flyweight executor is merely a thread in Jenkins master JVM regardless to what node it is scoped to. Creating nodes to host flyweight executors only does not seem to make sense as the tasks can run on different nodes or master without observable difference.

I suppose there is a difference between "ideal" flyweight tasks and de-facto Jenkins ones. There are already implementations like Matrix or Pipeline, which are really heavy by design.

**Comment by daniel-beck** [comment]
Still doesn't make an argument for having flyweight-only machines. If they're actually light, master is fine, if they're not, why would there be no "heavy" executors on the same machine?

**Comment by moriarty** [comment]
I have a odd (_legacy_) use case where this pull request would help...

We have a number of Linux Executor nodes, which are setup as standard Jenkins slaves. But some of these also require a paired machine (windows) which isn't a standard node shown in Jenkins (a sort of shadow node), and there is some (_legacy_: https://www.xkcd.com/224/) connection behind the scene... database, simulators, emulators, etc... these shadow nodes are required by our executor nodes for testing, but they're currently outside of Jenkins.

Obviously, we're trying to move everything forward out of this legacy situation, and move towards pipelines and move all the "shadow nodes" into proper executor nodes or better: containers that can be spawned as needed...
The current solution is to set the Label to something which isn't used, and then they have 1 Idle executor,
or just not list them in Jenkins and if errors start occurring then go and check our https://github.com/munin-monitoring/munin monitor page.
It would be useful, to allow 0 executor nodes to check that the nodes are still alive.

The use case I describe might lead to more abuse than its worth... (e.g. adding a slave on a nexus server with zero executors to maintain verify nexus is alive and reachable from jenkins)... but I thought I'd mention it.

A not legacy, but very similar use case (simulating robots: were test execution nodes require a Windows-Linux pair) would be using SIGVerse in Jenkins: http://www.sigverse.org/wiki/en/index.php?Introduction#tebf1688

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers this thread needs more feedback

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers ping

**Comment by batmat** [comment]
I think Daniel has a good point:

> If they're actually light, master is fine, if they're not, why would there be no "heavy" executors on the same machine?

So I'm at least confused as to why we would want to make this possible/encouraged?

@moriarty something like https://xkcd.com/1172/ :stuck_out_tongue:

**Comment by moriarty** [comment]
@batmat I hadn't seen that xkcd yet 👍

**Comment by alexanderrtaylor** [comment]
@ksenia-nenasheva Do you have time to fix the merge issues here? It seems like this would be OK once those are taken care of.

**Comment by daniel-beck** [comment]
@alexanderrtaylor Seems to me the only comment supporting this use case is "odd (*legacy*)", or am I missing something?

**Comment by dwnusbaum** [comment]
This has been superseded by #3141 and #3292, which prevent 0 from being selected as an option for agents, right?

**Comment by ksenia-nenasheva** [comment]
The validation was corrected in #3141 and #3292. Based on them - agents can not have 0 executers. These changes are no longer relevant and I can close this one.

**Pull request closed without merging**
