### PR TITLE
[WiP] switch "Upload Plugin" screen area with "HTTP Proxy Configuration"

### PR DESCRIPTION
**Pull request by qxo**
switch "Upload Plugin" screen area with "HTTP Proxy Configuration"
and move "userName,password,noProxyHost" to advance area ( "HTTP Proxy
Configuration")

so we can upload plugin and  seee all area without scroll screen

### CODE REVIEW

**Comment by daniel-beck** [comment]
Needs 790 pixels height for the upload option to be visible completely, most screens should have that today. OTOH this moves the important proxy configuration (if you need it) below the IMO)rather unusual 'upload plugin' feature (because most plugins will be downloaded from the other tabs). Not sure this is a useful change.

**Comment by KostyaSha** [comment]
Please attach before/after screenshots next time for any UI change.
:-1: at, I see no benefits on putting options under advanced button.

**Comment by oleg-nenashev** [comment]
I don't think it makes much difference.
If you want to optimize layouts, I would propose to move the "Manual Upload" control to a separate tab and to reserve some extra space for advanced features there (e.g. "Upload multiple files").

**Comment by oleg-nenashev** [comment]
Marked as WiP till @qxo processes comments

**Comment by daniel-beck** [comment]
This can probably be considered obsolete after six months.

**Pull request closed without merging**
