### PR TITLE
[JENKINS-32357] Section tabs for job configs - phase 1

### PR DESCRIPTION
**Pull request by tfennelly**
Replacement for #1978.

Hoping to make job config navigation a bit easier (not as suckie). 
- See [JENKINS-32357](https://issues.jenkins-ci.org/browse/JENKINS-32357).
- [Dev list discussion](https://groups.google.com/forum/?hl=en#!topic/jenkinsci-dev/tXursfAKz7M).

[Demo Video](https://youtu.be/uOiclX_W37Q)
[screenshot 2016-01-28 08 39 48](https://youtu.be/uOiclX_W37Q)

We're thinking of this as being "phase 1" i.e. that we think we'll want/need to do another round of improvements after. IOW ... no need for hysteria if it's not "perfect" straight-off :smile: 

**TODO:**
- [x] **Version 1 of a JavaScript API** for config forms that can be used as a foundation on which to build all other config page UX improvements. This will hopefully help compensate for the fact that there is no structure within the markup/DOM. [See config/table-metadata.js](https://github.com/tfennelly/jenkins/blob/2.0-with-config-tabs/war/src/main/js/widgets/config/table-metadata.js).
- [x] **Tabbed sections**. Uses the above config forms API. [See config/tabbar.js](https://github.com/tfennelly/jenkins/blob/2.0-with-config-tabs/war/src/main/js/widgets/config/tabbar.js). Yes, can try other things (accordions etc) in a future iteration.
- [x] **Config finder**. Find text across the different sections, only showing the user those sections that contain the text.
- [x] **Remember last active section**. Remember the last section the user was on when last configuring the Job e.g. if they were on Build Triggers, bring them back there immediately on next configure of that Job.
- [x] **Toggle classic config view on/off**. Allow people to opt-out and revert back to the "classic" configuration view.
- [x] **Section adoption**. Allow one top-level section to "adopt" another top-level section e.g. to move the "Advanced" section inside the "General" section".

[JENKINS-32578](https://issues.jenkins-ci.org/browse/JENKINS-32578) outlines a set of tasks for a possible "phase 2" (and beyond).

### CODE REVIEW

**Comment by tfennelly** [comment]
@jenkinsci/code-reviewers

**Comment by rsandell** [comment]
:+1:

**Comment by jtnord** [comment]
Haven't reviewed - but the screenshot to me shows an issue with the search.
Build is only shown in the "General Tab" - but in reality I would be highly surprised if there was not a mention on the build in the actual "Build Tab" - or the "Triggers tab", or the "Post Build Tab"...
Also - what if the thing you are searching for is hidden via an "Advanced..." section?

Chrome handles advanced for example - if you view its settings and then search - if the result is hidden as it is in advanced - it expands this section (e.g. search for password).

I foresee that searching across tabs will always be difficult to implement correctly without gotchas - and the reason for this search is to help users now find the thing that they are looking for (as it's moved) - but it appears to be failing to do this.

**Comment by tfennelly** [comment]
@jtnord look at the video ... the search removes tabs for sections that do not contain the text being searched for i.e. if the tab is still displayed, then that section has instances of the searched for text. So in the case of the screenshot ... "build" was found in all of those sections where a tab is still displayed.

As for text hidden in "Advanced" sections etc ... yes, we need a nice way of "drawing" people in there, but not sure about auto-expanding coz I think that could be a mess.

**Comment by jtnord** [comment]
@tfennelly sorry I did watch it - I think I must have temporarily zoned out on the subversion part (which was over pretty quick for such a nifty piece of functionality!)

**Comment by tfennelly** [comment]
@jtnord we can't be hanging around here ;)

**Comment by daniel-beck** [comment]
Advanced Project Options, when expanded (*Advanced…* clicked), show up in every tab afterwards.

**Comment by tfennelly** [comment]
@daniel-beck nice one ... thanks for letting me know.

There's going to be some funky little things like that while we get the model right.

**Comment by tfennelly** [comment]
@daniel-beck the advanced options bug is fixed now. On to the next bug :)

**Comment by tfennelly** [comment]
@daniel-beck Would be good to merge this asap and get people using and testing it.

**Pull request merged**
