### PR TITLE
[JENKINS-68578] Test overview bar is out of style with other Jenkins components

### PR DESCRIPTION
**Pull request by ridemountainpig**
See [JENKINS-68578](https://issues.jenkins.io/browse/JENKINS-68578).
image

### Proposed changelog entries

* Use same styling on test overview bar as other Jenkins components.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] New deprecations are annotated with `@Deprecated(since="TODO")` or `@Deprecated(since="TODO", forRemoval=true)` if applicable.
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/6728"></a>

### CODE REVIEW

**Comment by NotMyFault** [comment]
The borders are fine, but the inner parts need some fine tuning:

Bildschirmfoto 2022-07-01 um 11 31 47

**Comment by ridemountainpig** [comment]
image

**Comment by ridemountainpig** [comment]
image

**Review by NotMyFault — APPROVED** [review]

**Review by yaroslavafenkin — APPROVED** [review]

**Comment by uhafner** [comment]
Why is this code part of core? Test results should be part of the JUnit plugin. Has this file been forgotten during the extraction of the JUnit plugin?  

The JUnit plugin has a different color scheme already (green for passed tests). So it would make sense to reuse these values for this bar as well:

Bildschirmfoto 2022-07-01 um 16 57 11

**Comment by NotMyFault** [comment]
> Why is this code part of core? Test results should be part of the JUnit plugin. Has this file been forgotten during the extraction of the JUnit plugin?
> 

The test bar on my screenshot is part of the aggregated test overview of the maven plugin, reusing what core provides. AFAIK, there are bunch of plugins using this logic to generate a test result bar, e.g. the testng plugin, displayed at the test result page for a job.

**Comment by janfaracik** [comment]
Looks fine to me, few things:

* I think it would be better if the stylings were moved to a CSS/LESS file
* Would be great if colors used the vars from https://weekly.ci.jenkins.io/design-library/Colors/ instead
* Is the blue supposed to represent passed tests? If so this would be better as `var(--success-color)` afaik Jenkins has moved on from using blue as a passed build color.

Cheers :)

**Comment by ridemountainpig** [comment]
> I think it would be better if the stylings were moved to a CSS/LESS file
Would be great if colors used the vars from https://weekly.ci.jenkins.io/design-library/Colors/ instead
Is the blue supposed to represent passed tests? If so this would be better as var(--success-color) afaik Jenkins has moved on from using blue as a passed build color.

I think we can open the new issue for those question, in this issue I think just need add the border-radius and over-flow in style let it look round corners.

**Comment by ridemountainpig** [comment]
> I think it would be better if the stylings were moved to a CSS/LESS file
Would be great if colors used the vars from https://weekly.ci.jenkins.io/design-library/Colors/ instead
Is the blue supposed to represent passed tests? If so this would be better as var(--success-color) afaik Jenkins has moved on from using blue as a passed build color.

Sorry, should I solve those question ?
or those question can be another issue, and this PR can be approve ?

Thx~

**Comment by janfaracik** [comment]
> > I think it would be better if the stylings were moved to a CSS/LESS file
> 
> Would be great if colors used the vars from https://weekly.ci.jenkins.io/design-library/Colors/ instead
> 
> Is the blue supposed to represent passed tests? If so this would be better as var(--success-color) afaik Jenkins has moved on from using blue as a passed build color.
> 
> 
> 
> Sorry, should I solve those question ?
> 
> or those question can be another issue, and this PR can be approve ?
> 
> 
> 
> Thx~

You're all good :)

**Review by janfaracik — APPROVED** [review]

**Comment by NotMyFault** [comment]
This PR is now ready for merge. We will merge it after ~24 hours if there is no negative feedback.
Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process.
Thanks!

**Review by basil — APPROVED** [review]
Not a complete solution, but a step in the right direction nevertheless. Incremental progress is how projects like this one succeed. Thanks for the PR!

**Pull request merged**
