### PR TITLE
Add a small gap between build status icon and text

### PR DESCRIPTION
**Pull request by uhafner**
A small followup to https://github.com/jenkinsci/jenkins/pull/5471. Currently the build status icon is too narrow to the text "Console Output". 

**Note:** this does not work for pipelines, seems that that part of the code has been duplicated somewhere in the pipeline modules. 

### Before:

Bildschirmfoto 2021-05-20 um 17 29 32

### After: 

Bildschirmfoto 2021-05-20 um 17 29 38

### Proposed changelog entries

* Entry 1: Enhancement, Improve layout of console output header

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@timja 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by timja — APPROVED** [review]
it'll be whereever WorkflowRun is defined maybe workflow-job

**Comment by daniel-beck** [comment]
Why not change `t:buildCaption` instead? Are Changes, Artifacts, and all the other views using this tag not affected somehow?

**Comment by uhafner** [comment]
The tag itself is broken somehow. The rendering depends on how many spaces are inserted in between. The build page correctly renders the text:

Bildschirmfoto 2021-05-20 um 21 09 54


That is the reason why my general solution in https://github.com/jenkinsci/jenkins/pull/5471 did not work.

**Comment by daniel-beck** [comment]
The difference is the leading whitespace inside the tag (line break + indentation for the text).

Build Log and Changes do not have it (everything on the same line), so there's no gap. Index and Artifacts have it, so there is a gap. A solution requiring a change of the callers isn't a good one IMO.

**Comment by uhafner** [comment]
Yes I have seen that as well. But how can we fix that in the tag if the caller is broken? The caller should not use line breaks before the text. I am not a CSS/HTML specialist, is there a simple solution for this problem?

**Comment by daniel-beck** [comment]
> The caller should not use line breaks before the text.

Good points; I guess in that case we remove the leading/trailing whitespace in the caller, and adapt the tag to look correct when there is none?

**Comment by uhafner** [comment]
Ok, I'll fix the other usages as well. In the meanwhile I marked this PR as draft again.

**Comment by uhafner** [comment]
I think it works now for all usages in Jenkins core. It needs to be adjusted in pipelines (seems that the code has been duplicated there in a plugin).

**Comment by uhafner** [comment]
The tag is used quite often in other plugins. The most important one is https://github.com/jenkinsci/workflow-job-plugin/blob/a8796f0e8a7856e799fa907c80ea8b8c646cf4a3/src/main/resources/org/jenkinsci/plugins/workflow/job/WorkflowRun/index.jelly#L74. With the change here in core there will be an additional space for workflow jobs. This can be adjusted later on. 

In general I don't think that it is a good idea to allow for the content of a `h1` tag contain any kind of HTML. But for this it is too late now. A better approach would be to provide the title as an attribute for `buildCaption.

**Review by oleg-nenashev — APPROVED** [review]
No objections from me.

We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Pull request merged**
