### PR TITLE
Update remoting to 2.60

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Changes summary:

Fixed issues:
- [JENKINS-22722](https://issues.jenkins-ci.org/browse/JENKINS-22722) - 
  Make the channel reader tolerant against Socket timeouts. 
  (https://github.com/jenkinsci/remoting/pull/80)
- [JENKINS-32326](https://issues.jenkins-ci.org/browse/JENKINS-32326) - 
  Support no_proxy environment variable. 
  (https://github.com/jenkinsci/remoting/pull/84)
- [JENKINS-35190](https://issues.jenkins-ci.org/browse/JENKINS-35190)  - 
  Do not invoke PingFailureAnalyzer for agent=>master ping failures. 
  (https://github.com/jenkinsci/remoting/pull/85)
- [JENKINS-31256](https://issues.jenkins-ci.org/browse/JENKINS-31256) - 
  <code>hudson.Remoting.Engine#waitForServerToBack</code> now uses credentials for connection. 
  (https://github.com/jenkinsci/remoting/pull/87)
- [JENKINS-35494](https://issues.jenkins-ci.org/browse/JENKINS-35494) - 
  Fix FindBugs warnings in file management in <code>hudson.remoting.Launcher</code> (main executable class). 
  (https://github.com/jenkinsci/remoting/pull/88)

Enhancements:
- Ensure a message is logged if remoting fails to override the default <code>ClassFilter</code>. 
  (https://github.com/jenkinsci/remoting/pull/80)

@reviewbybees @jenkinsci/code-reviewers

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
CC contributors - @jglick @wiizzard @etiennebec

**Comment by andresrc** [comment]
:bee:

**Comment by jglick** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Comment by batmat** [comment]
FWIW https://github.com/jenkinsci/remoting/compare/remoting-2.59...remoting-2.60

**Comment by batmat** [comment]
:+1:

**Comment by oleg-nenashev** [comment]
@batmat Yes, I should do it next time

Going forward with the merge

**Pull request merged**
