### PR TITLE
Revert switching to array utils

### PR DESCRIPTION
**Pull request by jsoref**
This incorrect change was introduced as part of #3913

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@jvz @proski

### CODE REVIEW

**Comment by proski** [comment]
Looks good to me. I don't have project membership to approve.

**Review by oleg-nenashev — APPROVED** [review]
agreed. Sorry for missing defects during the review

**Comment by oleg-nenashev** [comment]
retriggering the build

**Comment by Wadeck** [comment]
@oleg-nenashev did you forget to re-open the PR after the trigger? :)

**Comment by oleg-nenashev** [comment]
🤦‍♂️

**Comment by oleg-nenashev** [comment]
Sorry, we missed the change and probably caused a regression because of me

**Review by oleg-nenashev — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
JDK8 Linux build failed due to "/home/jenkins/workspace/Core: No space left on device", everything else is green. IMO it is just an infra issue

**Review by varyvol — APPROVED** [review]

**Comment by Wadeck** [comment]
@jsoref as this PR is a regression, a Jira ticket must be created in order to facilitate the management of the backport.

**Comment by jsoref** [comment]
@wadeck: I'm sorry. I've run out of energy for managing Jenkins PRs for the next week, possibly month. Congratulations on pushing me over my limit. If you need an issue to manage this regression, then I suggest you file one.

**Comment by batmat** [comment]
I do not think we actually need a JIRA in this case, and the `regression-fix` label is misplaced, given the issue this PR is fixing was introduced in https://github.com/jenkinsci/jenkins/pull/3913, which got merged in 2.168. 

As the last LTS was 2.164, i.e. **before** the 2.168 where this issue got introduced, there's nothing to backport.

Please correct me if I'm wrong.

**Comment by daniel-beck** [comment]
> there's nothing to backport

That's true, but weeklies are real releases, unlike e.g. Firefox nightlies (are they still around?), so regression fixes should be expedited, and deserve to be mentioned in the changelog.

The case for an issue is overall weaker, true.

**Comment by batmat** [comment]
Makes full sense, thanks for shedding light on this.
So indeed, I was wrong about the "misplaced label" that makes PRs like these stand out so we do NOT have to end up backporting them to new chosen LTS baseline.

Agreed for the JIRA part: weaker indeed. I would say unnecessary generally, but can sometimes draw more attention to some pressing matter.

**Comment by jsoref** [comment]
I'm happy to include a changelog entry if someone provides one, I can't think of a good way to write it "reverting hashcode algorithm" doesn't seem particularly useful to me.

And yes, Firefox has a nightly channel (I'm using it now, it's called "Firefox nightly"). They don't do release notes for nightlies, if people are curious, they can look at the commit history.

**Pull request merged**
