### PR TITLE
JENKINS-38736 Update guice to final 4.0 release.

### PR DESCRIPTION
**Pull request by KostyaSha**
Checking PR build
Diff: https://github.com/google/guice/compare/4.0-beta5...4.0
Previous update attempt https://github.com/jenkinsci/jenkins/pull/1453

---

This change is [Reviewable](https://reviewable.io/reviews/jenkinsci/jenkins/2568)

### CODE REVIEW

**Comment by KostyaSha** [comment]
@jglick was your bug finally fixed?

**Comment by KostyaSha** [comment]
If it pass fine, will open JIRA issue.

**Comment by daniel-beck** [comment]
Why are you linking to the diff from `4.0-beta5` rather than `4.0-beta`, which is the current release?

Unfortunately the `4.0-beta...4.0` diff doesn't load for me, so probably considerably larger.

**Comment by KostyaSha** [comment]
Because beta5 had bug and the question is whether it was fixed.

**Comment by KostyaSha** [comment]
That affects java8 support.

**Comment by oleg-nenashev** [comment]
IMHO it's definitely reasonable to merge it into the Weekly since tests do not fail.
If something blows up in the corner case, we can consider reverting in the worst case

**Review by oleg-nenashev — APPROVED** [review]

**Comment by KostyaSha** [comment]
Created issue in case of regressions https://issues.jenkins-ci.org/browse/JENKINS-38736

**Comment by jglick** [comment]
> was your bug finally fixed?

Which one? At this point I have little recollection of the earlier update.

**Review by jglick — APPROVED** [review]
As @oleg-nenashev said, I think it is reasonable to merge it, and if we find any problems, investigate.

**Comment by KostyaSha** [comment]
@jglick you reverted beta5 to beta in https://github.com/jenkinsci/jenkins/commit/00c858d403ab1f7747de0b9ce80e1eef921c41b3

**Comment by KostyaSha** [comment]
And then you created https://github.com/google/guice/issues/899

**Comment by jglick** [comment]
I have no idea if that bug was fixed or not. Can you please try the test case I mentioned there using the final release?

**Review by jglick — CHANGES_REQUESTED** [review]
Nope, test case still fails I am afraid.

**Comment by jglick** [comment]
Request that https://github.com/jenkinsci/maven-plugin/pull/80 (or its equivalent) be merged and released before this is merged.

**Comment by oleg-nenashev** [comment]
https://github.com/jenkinsci/maven-plugin/pull/80 has been merged, but there is no release by now (CC @aheritier). Without it we cannot integrate this change

**Comment by aheritier** [comment]
@KostyaSha @oleg-nenashev @jglick how is it urgent ? 
If I don't have too much things this week I can try to release it. There is just one or two PR that I would like to process before.

**Comment by oleg-nenashev** [comment]
@aheritier I suppose it's too late for the today's (?) weekly release, but it would be really great if we get it done by the next weekly. Then it will be better soaked before the next LTS baseline, which will likely include the version with updated Guice.

**Comment by aheritier** [comment]
Yes too risky to start a release at midnight :-) Also I have to release [maven-interceptors](https://github.com/jenkinsci/maven-interceptors)
The breakage of maven jobs is bad enough to hold this merge? Even if I release it in few days ?

**Comment by oleg-nenashev** [comment]
> The breakage of maven jobs is bad enough to hold this merge? Even if I release it in few days ?

Even if it is a Weekly release, I would not like to intentionally break the stuff. Especially since there is no need to get it released ASAP.

**Comment by daniel-beck** [comment]
@oleg-nenashev @aheritier We need to point out the potential breakage with old Maven Plugin versions here in the changelog. AFAIU new Jenkins + old Maven plugin = broken. Please correct me if I'm wrong.

Also, we need to think about what to do with the detached Maven Plugin version. We currently include 2.7.1, and it looks like we need to update that, otherwise it'll be broken in case of an upgrade. AFAIR we now enforce upgrades to bundled versions if outdated, so I'd be more comfortable with a 2.7.2.

**Comment by aheritier** [comment]
@daniel-beck yes this is my understanding. In core changelog we should have

JENKINS-38736 Update guice to final 4.0 release => Requires upgrade of maven-plugin to version >= 2.14

> detached Maven Plugin version

Are you talking about these PRs ?

https://github.com/jenkinsci/jenkins/pull/2352
https://github.com/jenkinsci/maven-plugin/pull/72

if ready for these one we'll need to have a maven-plugin 3.0 released with a dependency to maven-builder 1.0 and jenkins 2.x (where the merge is done). This will be another case where the core upgrade will require an upgrade of the maven-plugin ( >= 3.0 in this case). The maven-builder plugin will have to be added in the recommended list of plugins (like gradle, ..) but should be proposed only for this jenkins >= 2.x ( I don't know if it is possible). If installed in oldest versions I think it may not play well together.

**Comment by jglick** [comment]
> otherwise it'll be broken in case of an upgrade

Only in case of someone updating directly to our new core weekly from Hudson 1.295 or earlier. So I am not terribly worried about that.

**Review by jglick — APPROVED** [review]

**Comment by jglick** [comment]
>> detached Maven Plugin version

> Are you talking about these PRs ?

No, I think @daniel-beck was referring to [this](https://github.com/jenkinsci/jenkins/blob/6cad673583d71fb65a76ac7a49307d813f05fa13/core/src/main/java/hudson/ClassicPluginStrategy.java#L407). Whose main purpose at this point is to ensure that plugins with a very old core dependency can still link against `hudson.maven.*` types.

It *also* controls behavior when Jenkins is upgraded from a truly ancient version, but as I said that is a very minor issue compared to the quite probable issue of something upgrading from one weekly to the next and not upgrading the Maven plugin—and there is nothing we can do about that, since the Jenkins plugin manager does not allow us to express the fact that a particular plugin version will not work with a *newer* version of some dependency than what it originally requested: we have no mechanism for marking incompatible changes.

**Comment by daniel-beck** [comment]
@jglick 

Mostly I am referring to https://github.com/jenkinsci/jenkins/blob/6cad673583d71fb65a76ac7a49307d813f05fa13/pom.xml#L95

> Only in case of someone updating directly to our new core weekly from Hudson 1.295 or earlier. So I am not terribly worried about that.

IIRC since 2.0 we're upgrading all plugins unconditionally to the bundled version. So anyone who installed 1.x and kept upgrading will have a broken version installed. At the same time we could use this to take care of this by referencing a version of the maven-plugin that includes the fix.

@aheritier How difficult would it be to create a 2.7.2 with the fix, and bundle that with Jenkins?

**Comment by aheritier** [comment]
@daniel-beck How to discover that there was a 2.7.1 not documented ( https://wiki.jenkins-ci.org/display/JENKINS/Maven+Project+Plugin ) :(

Backporting https://github.com/jenkinsci/maven-plugin/pull/80 in a 2.7.2 seems easy (sisu 0.3.3 is Java 6 compatible) the problem is more with the quality of tests/build that may make it fun.

But I don't get the point, why don't we just bundle in jenkins 2.x a recent version of the maven-plugin ?

**Comment by oleg-nenashev** [comment]
> But I don't get the point, why don't we just bundle in jenkins 2.x a recent version of the maven-plugin ?

I do not see a reason to keep 2.7.x as well. Upgrade to `2.7.1` has been done from `2.5` (https://github.com/jenkinsci/jenkins/commit/2d46bd5b95bc1e695ebd921b83dd7b5302f0bbb4), hence there is no stabilization branch approach. `2.7.1` has been likely released from the security fix branch instead of the master. We just need to ensure that the Security fix is in the master.

@aheritier @daniel-beck @KostyaSha Would be great to accelerate this PR, because there is a new LTS line on the horizon. If the change wants to get there, it needs to be soaked as much as possible. Or we can put the PR on hold and merge it when the new LTS gets selected

**Comment by daniel-beck** [comment]
@oleg-nenashev (and @aheritier )

> I do not see a reason to keep 2.7.x as well. Upgrade to 2.7.1 has been done from 2.5

That was back when pinning of plugins existed. Now, we just force everything to update at least to the bundled release.

Don't let me block you. I expect upset users who get force-fed updates, but maybe that fear is unnecessary.

**Comment by oleg-nenashev** [comment]
> I expect upset users who get force-fed updates, but maybe that fear is unnecessary.

Well, detached plugins are "special". I would definitely expect somebody to perform manual upgradeability tests before going forward. If it can be done in ATH, then it's even better

**Comment by oleg-nenashev** [comment]
Did some manual testing of upgrades for Jenkins instances with Maven Project plugin. Looks good so far

**Comment by aheritier** [comment]
🐝 👍 @oleg-nenashev let's move forward

**Comment by oleg-nenashev** [comment]
@daniel-beck Are you fine with the PR since we've got *some* testing?

**Comment by daniel-beck** [comment]
> Don't let me block you.

**Comment by KostyaSha** [comment]
:shipit:

**Pull request merged**
