### PR TITLE
[JENKINS-52255] Add --xml option to list-plugins command

### PR DESCRIPTION
**Pull request by amuniz**
See [JENKINS-52255](https://issues.jenkins-ci.org/browse/JENKINS-52255).

### Proposed changelog entries

* [JENKINS-52255] `--xml` option in `list-plugins` CLI to generate XML output

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@jenkinsci/code-reviewers

### CODE REVIEW

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
I am against adding such option until there is an XML Specification draft in the Ticket or in jenkins.io pull request.

Usage of XStream hints that it would be an object export, and the format may change over versions (e.g. if we update XStream). IMHO it is not what we want for such generic API offered to CLI users

**Review by daniel-beck — CHANGES_REQUESTED** [review]
This is a great idea, but should be done globally and consistently, not just the single command you specifically care about to have parsable output.

Two years from now, people would ask "Why does only one command have XML output?" and we won't have a good answer.

See recording the creator of agents (and no other object in Jenkins) before this, or how few objects are StaplerOverridable.

**Comment by amuniz** [comment]
@oleg-nenashev 

> I am against adding such option until there is an XML Specification draft in the Ticket or in jenkins.io pull request.

There is no such specification for **any** other command, why is it needed for this?

> Usage of XStream hints that it would be an object export, and the format may change over versions

Yeah, and then all the Jenkins data storage will blow up, so this little CLI issue is going the be the last thing to fix.

@daniel-beck 

> not just the single command you specifically care about to have parsable output.

`get-job`, `get-node` and `get-view` are already outputting XML, so this is not the only one. I'm just modifying this one to be consistent with others and using the `--xml` option to keep backward compatibility on the old plain text output.

> Two years from now, people would ask "Why does only one command have XML output?"

Again, it's not only this one. It is worse actually, people is asking "Why is this command's output plain text when others are XML?", and that's **today**.

**Comment by daniel-beck** [comment]
> `get-job`, `get-node` and `get-view` are already outputting XML, so this is not the only one. I'm just modifying this one to be consistent with others and using the `--xml` option to keep backward compatibility on the old plain text output.

These commands inherently return the native storage format. This one is more akin to other `list-*` commands that don't.

**Comment by oleg-nenashev** [comment]
I would be fine if we had a single command with proper documentation and test automation.
output generation via XStream is also a problem IMHO (they may include class version and other stuff), we should rather generate a plain XML using available XML APIs.

**Comment by amuniz** [comment]
BTW build failed for some unrelated reason.

**Comment by oleg-nenashev** [comment]
> "output generation via XStream is also a problem IMHO" Why?

XStream XML output format may change in Jenkins without preliminary notice. It will be fine for Jenkins itself if it retains compatibility (e.g. XML 1.1 update by @mikecirioli in January), but it may be NOT fine for CLI users relying on the CLI output in their production environments.

**Comment by amuniz** [comment]
> but it may be NOT fine for CLI users relying on the CLI output in their production environments.

Nothing introduced by this PR. As I said before: jobs, nodes and views are already exposing XStream serialization on the CLI.

**Comment by daniel-beck** [comment]
> Nothing introduced by this PR. As I said before: jobs, nodes and views are already exposing XStream serialization on the CLI.

In their native storage format. That is very different from what this PR is doing.

Would there be a reasonable way to do this PR with `--json` option (or even `--csv`) instead? Yes. The same cannot be said for those commands.

**Comment by amuniz** [comment]
Ok.

**Comment by scherler** [comment]
screenshot_2018-07-02_20-29-53

q.e.d

**Pull request closed without merging**
