### PR TITLE
[Java 9] Try BCT with ASM6

### PR DESCRIPTION
**Pull request by batmat**
Downstream to https://github.com/jenkinsci/bytecode-compatibility-transformer/pull/9

* This PR targets the `java9` created to have the necessary time to integrate and test more thoroughly Java 9 related changes without risking for now to impact the `master`'s weeklies

See [JENKINS-46602](https://issues.jenkins-ci.org/browse/JENKINS-46602).

### Proposed changelog entries

* Pick-up `bytecode-compatibility-transformer:2.0-SNAPSHOT` dependency to support Java 9

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@reviewbybees @jenkinsci/code-reviewers

### CODE REVIEW

**Comment by batmat** [comment]
Well, failing but encouraging at the same time, _only_ two tests failing.
image

image

image

**Comment by daniel-beck** [comment]
I think those tests are flaky. @oleg-nenashev ?

**Comment by oleg-nenashev** [comment]
I'd guess so

**Comment by batmat** [comment]
Rebased and force pushed as the PR build builds `pr-head`, so I wanted to see what is the result with latest tip and possibly some fixes since around tests flakiness.

**Comment by daniel-beck** [comment]
@batmat It looks like this PR is messed up. Do you want to keep this around anyway? I think a clean resubmission would be more useful.

**Comment by batmat** [comment]
Yes, agreed.

**Pull request closed without merging**
