### PR TITLE
[JENKINS-31019] Bump BCT to pickup fix.

### PR DESCRIPTION
**Pull request by jtnord**
Update the BCT to pickup the fix for [JENKINS-31019](https://issues.jenkins-ci.org/browse/JENKINS-31019)

[BCT Changes](https://github.com/jenkinsci/bytecode-compatibility-transformer/compare/bytecode-compatibility-transformer-1.7...bytecode-compatibility-transformer-1.8)

@reviewbybees

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
:bee: for the bump, small :ant: for spaces in other line

**Comment by KostyaSha** [comment]
@jtnord crazy work :+1:

**Comment by recena** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
Next release is going to happen on Sunday or Wednesday, so no need to merge immediately. Let's wait a bit to let others to review the change in the lib

**Comment by jglick** [comment]
:bee:

**Pull request merged**
