### PR TITLE
[JENKINS-40435] - Use BulkChange when processing config changes in Job#doConfigSubmit.

### PR DESCRIPTION
**Pull request by oleg-nenashev**
When an empty Freestyle job config gets submitted in the default configuration of Jenkins 2.35, the data is being saved to the disk **8 times**. All of them happen in this code: https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Job.java#L1227-L1246

* setDisplayName
* Project#getBuildWrappersList().rebuild (onModified handler)
* Project#getBuilderList().rebuild (onModified handler)
* Project#getPublisherList().rebuild (onModified handler)
* AbstractProject#makeDisabled
* AbstractProject#setScm
* AbstractProject#triggers.replaceBy
* final save()

There is not so much sense to save partial configurations to the disk due to the risk of data inconsistency there. This change just wraps the config submission section of the job into the BulkChange clause.

https://issues.jenkins-ci.org/browse/JENKINS-40435

@reviewbybees

### CODE REVIEW

**Comment by daniel-beck** [comment]
Real diff: https://github.com/jenkinsci/jenkins/pull/2664/files?w=

**Comment by oleg-nenashev** [comment]
I can confirm it does not blow up for Freestyle and Pipeline. I'm not 100% sure about Matrix projects, but I would rely on JTH and ATH

**Comment by stephenc** [comment]
:bee:

**Review by stephenc — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers looking for some +1s

**Review by daniel-beck — APPROVED** [review]

**Pull request merged**
