### PR TITLE
[JENKINS-34137] setup wizard: better handling of the close button

### PR DESCRIPTION
**Pull request by kzantow**
Fix some issues with the close button: don't allow while plugins installing or in certain other places, close now directs to setup complete panel, with message about skipping admin user creation.

This fixes: https://issues.jenkins-ci.org/browse/JENKINS-34137

@reviewbybees

### CODE REVIEW

**Comment by recena** [comment]
:bee:

**Comment by mslusarczyk** [comment]
:bee:

**Comment by kzantow** [comment]
@reviewbybees done

**Comment by daniel-beck** [comment]
Not sure not allowing this during plugin install is the correct way to go, but seems trivial to adjust afterwards, so I'm going ahead and merge this.

**Pull request merged**
