### PR TITLE
Use Unicode escapes when properties files are both valid UTF-8 and ISO-8859-1

### PR DESCRIPTION
**Pull request by timja**
See https://github.com/jenkinsci/stapler/pull/357
and https://github.com/jenkinsci/jenkins/pull/6546#issuecomment-1120254456

Ran with https://gist.github.com/timja/21d655840f5d617df07a271a7db0a48f

and then paths outputted to a file and `native2ascii` used over top:

```command
cat /tmp/files.txt | xargs -I {} -n 1 bash -c "native2ascii {} > /tmp/ascii.txt && mv /tmp/ascii.txt {}"
```

### Proposed changelog entries

* Correct encoding for several localized strings.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]

**Review by basil — APPROVED** [review]
I just merged a different localization PR so it would be nice to confirm that there are no conflicts.

**Comment by basil** [comment]
This PR is now ready for merge. We will merge it after approximately 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process. Thanks!

**Comment by basil** [comment]
As far as I can tell, this should be labelled `bug` and not `skip-changelog`, because it contains changes to `Messages*.properties`, which are handled by [this code](https://github.com/kohsuke/localizer/blob/fd6c5eff643d7e8cbbdb003810e1af5ebf3c0018/lib/src/main/java/org/jvnet/localizer/ResourceBundleHolder.java#L187-L195=) which is already using `PropertyResourceBundle` (i.e., already showing mojibake when running on Java 9+).

**Comment by basil** [comment]
In fact https://github.com/jenkinsci/jenkins/pull/6382 seems to have been an attempt to address one symptom of this problem, but the fix was incomplete. This PR eradicates the problem.

**Comment by timja** [comment]
> I just merged a different localization PR so it would be nice to confirm that there are no conflicts.

No new issues from merging master locally

**Comment by jglick** [comment]
Worth adding to https://github.com/jenkinsci/jenkins/blob/0f90eba8866c5cd3c9346ca5590ff2982773c32e/test/src/test/java/jenkins/CorePropertiesTest.java#L34 to prevent accidental regression?

**Comment by timja** [comment]
Done: https://github.com/jenkinsci/jenkins-test-harness/pull/433

**Pull request merged**
