### PR TITLE
Cleanup FindBugs in CLI + some refactoring

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Two minor changes: 

* [JENKINS-50064](https://issues.jenkins-ci.org/browse/JENKINS-50064) - FinsBugs CLI is now analyzed with Medium threshold
* Cleanup Core POM as a follow-up to #3308, use newer FindBugs annotations

### Proposed changelog entries

* N/A

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@jenkinsci/code-reviewers

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers ping

**Review by daniel-beck — APPROVED** [review]

**Comment by daniel-beck** [comment]
@oleg-nenashev Do pr-head PR builds mean that any change we merge which changes cli/ might break master once we merge this one? Time for pr-merge? CC @rtyler

**Comment by oleg-nenashev** [comment]
IIUC yes. As designed since we optimize performance, right? Once we reduce the number of open PRs to a rasonable number (40?), we can switch the approach

**Comment by oleg-nenashev** [comment]
Anyway, CLI is not the most active part of the Jenkins codebase

**Pull request merged**
