### PR TITLE
Use standard `doclint`

### PR DESCRIPTION
**Pull request by jglick**
Picking up https://github.com/jenkinsci/pom/pull/270. (actually in #6712)

As of #6366 we were also excluding

> `reference`: Checks for issues relating to the references to Java API elements from Javadoc tags (for example, item not found in `@see`, or a bad name after `@param`).

which seems wrong. Such issues are source code bugs which should be corrected.

### Proposed changelog entries

N/A

### Proposed upgrade guidelines

N/A

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/6710"></a>

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]

**Review by timja — APPROVED** [review]

**Comment by NotMyFault** [comment]
This PR is now ready for merge. We will merge it after ~24 hours if there is no negative feedback.
Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process.
Thanks!

**Review by basil — DISMISSED** [review]
Does not build.

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10:24 min
[INFO] Finished at: 2022-06-28T08:34:01Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.4.0:jar (attach-javadocs) on project jenkins-core: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1 - /home/jenkins/workspace/Core_jenkins_PR-6710/core/src/main/java/hudson/util/ClassLoaderSanityThreadFactory.java:7: error: reference not found
[ERROR]  *  Explicitly sets the {@link Thread#contextClassLoader} for threads it creates to its own classloader.
[ERROR]                                ^
[ERROR] /home/jenkins/workspace/Core_jenkins_PR-6710/core/src/main/java/hudson/util/ClassLoaderSanityThreadFactory.java:9: error: reference not found
[ERROR]  *   in a context where they would receive a customized {@link Thread#contextClassLoader} that was never meant to be used.
[ERROR]                                                                ^
[ERROR] 2 errors
[ERROR] 
[ERROR] Command line was: /opt/java/openjdk/bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/home/jenkins/workspace/Core_jenkins_PR-6710/core/target/apidocs' dir.
[ERROR] -> [Help 1]
```

**Comment by jglick** [comment]
Perfect. I tried to run Javadoc locally and got no errors, but I suspect this is ultimately related to the Debian JDK package messing around with Javadoc settings. Anyway this error is exactly why we do not want `-reference`.

**Comment by jglick** [comment]
BTW I was still unable to reproduce the build error even with

```console
$ docker run -v ~/.m2:/var/maven/.m2 -ti --rm --name mvn -u $(id -u):$(id -g) -e MAVEN_CONFIG=/var/maven/.m2 -v "$PWD":/usr/src/mymaven -w /usr/src/mymaven maven:3-eclipse-temurin-11 mvn -Duser.home=/var/maven -Pquick-build -Dset.changelist -Dignore.dirt install
…
[INFO] --- maven-javadoc-plugin:3.4.0:jar (attach-javadocs) @ jenkins-core ---
[INFO] Configuration changed, re-generating javadoc.
[INFO] Building jar: /usr/src/mymaven/core/target/jenkins-core-2.358-rc32500.63a_77f061c7e-javadoc.jar
…
```

Not sure what I am missing.

**Review by basil — APPROVED** [review]
> Not sure what I am missing.

Missing Java 17.

**Comment by basil** [comment]
[Clean build](https://ci.jenkins.io/job/Core/job/jenkins/job/PR-6710/7/), [no Javadoc warnings](https://ci.jenkins.io/job/Core/job/jenkins/job/PR-6710/7/javadoc-warnings/) :+1:

---

This PR is now ready for merge. We will merge it after approximately 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process. Thanks!

**Pull request merged**
