### PR TITLE
Add the default values for parameters that are not passed in.

### PR DESCRIPTION
**Pull request by cjo9900**
[FIXED JENKINS-13768] Combine all of the ParameterActions into one and add
default values of missing Parameters defined in the job.

Always add missing default parameters.

https://issues.jenkins-ci.org/browse/JENKINS-13768

### CODE REVIEW

**Comment by KostyaSha** [comment]
PR status?

**Comment by oleg-nenashev** [comment]
I would also vote for having it in the core.
There is a new PR from @fbelzunc to git-plugin: https://github.com/jenkinsci/git-plugin/pull/356 . And I was able to find more similar cases with the missing default env vars support.

Needs a fix in any case, probably a topic for Jenkins 2.0

**Comment by daniel-beck** [comment]
This is probably still a good idea, so keeping this open for now.

**Comment by rtyler** [comment]
This has been open for six years, I'm going to close it.

Thank you for proposing this change @cjo9900, I'm sorry it stalled out. :frowning_man:

**Comment by ao-apps** [comment]
Hello from the future.  We're hoping to find a way to have default values always used except when the job is directly triggered by the user.  In our case, we have downstream jobs triggered, and they seem to be getting the parameters from the upstream job instead of their own defaults.

Perhaps this is the wrong place to voice this idea.  I'm still trying to find relevant discussions related to this precise scenario.

**Comment by daniel-beck** [comment]
@ao-apps Decade old pull requests is not the place to have this discussion. Chat or Jenkins users mailing list can help you understand what's going on, since it sounds like a bug to me. Then [report it](https://www.jenkins.io/participate/report-issue/) in the appropriate issue tracker.

**Pull request closed without merging**
