### PR TITLE
English

### PR DESCRIPTION
**Pull request by jsoref**
### Proposed changelog entries

(too minor)

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)

### CODE REVIEW

**Review by daniel-beck — APPROVED** [review]

**Comment by jsoref** [comment]
I just realized I want to change:
> There is no registered token for this user

To:
> There are no registered tokens for this user.

Should I make a new PR or toss that in here?

**Comment by daniel-beck** [comment]
Just add it here.

**Comment by jsoref** [comment]
@daniel-beck: done

**Review by vilacides — APPROVED** [review]

**Review by batmat — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
thanks @jsoref !

**Pull request merged**
