### PR TITLE
Update changelog for the 2.3 release (#2319, #2032, #2003, #1956, #2248, #2327 + edits)

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Integrates changelogs for the merged PRs + some fixes

@daniel-beck @batmat @jenkinsci/code-reviewers

### CODE REVIEW

**Comment by daniel-beck** [comment]
These changelog entries are unusually verbose. Note that if there's an issue or PR reference, users interested in details can always look there.

**Comment by daniel-beck** [comment]
Also, let me just say I love how multiple people start patching the changelog mid-week just before the one release every quarter or so that is guaranteed to not contain one of these changes. 😆

**Comment by daniel-beck** [comment]
Too bad the copy editors are in jenkins-infra.

I'd really like to know which style of changelog is preferred by users, the shorter or the more verbose. WDYT, thread on the users list?

**Comment by oleg-nenashev** [comment]
@daniel-beck +1 for starting a thread (or voting on Twitter, hehe)

**Comment by batmat** [comment]
+1 threads on the users list. +possibly a tweet linking to that thread cc @rtyler ?

**Comment by oleg-nenashev** [comment]
Merged to unblock other changes

**Pull request merged**
