### PR TITLE
Use official version of jbcrypt 0.4 in Hudson Private Security Realm

### PR DESCRIPTION
**Pull request by jglick**
Amends 767a919b5d8b2baaf9e8b42a177e04b8f45680b5 since [this](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.mindrot%22%20AND%20a%3A%22jbcrypt%22) was released subsequently, and the use of Java 8 bytecode is no longer a problem. There is [another version](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22de.svenkubiak%22%20AND%20a%3A%22jBCrypt%22) which [just seems to add OSGi packaging](https://github.com/svenkubiak/jBCrypt/compare/0.4...0.4.1) that I am not bothering with.

### Proposed changelog entries

None needed.

@reviewbybees

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
🐝 though I vote for the changelog entry. 

E.g. "Internal: Hudson Private Security Realm now uses password hashing algorithms from jBCrypt 0.4 instead of 0.2"

**Comment by daniel-beck** [comment]
@oleg-nenashev We were already on 0.4, just bundled as our own class due to the Java requirement of the official release. See the commit linked in the original comment.

**Comment by oleg-nenashev** [comment]
@daniel-beck I know. My changelog proposal is specific to Hudson Private Security realm as I may see.

**Comment by jglick** [comment]
@reviewbybees done

**Comment by jglick** [comment]
FTR the diff from `core/src/main/java/hudson/security/BCrypt.java` to `org/mindrot/jbcrypt/0.4/jbcrypt-0.4-sources.jar!/org/mindrot/jbcrypt/BCrypt.java`:

```diff
15c15
< package hudson.security; // repackaged from http://www.mindrot.org/files/jBCrypt/jBCrypt-0.4.zip (and public modifier removed)
---
> package org.mindrot.jbcrypt;
56c56
<  * The amount of work increases exponentially (2**log_rounds), so
---
>  * The amount of work increases exponentially (2**log_rounds), so 
63c63
< class BCrypt {
---
> public class BCrypt {
```

**Comment by oleg-nenashev** [comment]
Right, it's my bad. I didn't notice 0.4 header and checked the `version 0.2` in Javadoc. Changelog is not required

**Pull request merged**
