### PR TITLE
Update /manage interactive link styles

### PR DESCRIPTION
**Pull request by fqueiruga**
This PR updates the interactive link styles for the management link options on the /manage page. It brings the styles in line with the new look & feel theme.

<details>
<summary>Screenshots</summary>

Hover
Captura de pantalla 2020-06-25 a las 20 55 24

Focus
Captura de pantalla 2020-06-25 a las 20 55 49

Active
Captura de pantalla 2020-06-25 a las 20 59 20

</details>

### Proposed changelog entries

* Entry 1: Updated the styles for the links on the management page

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@timja 
@daniel-beck 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by timja** [comment]
Hover colours aren't as noticeable for me on my monitor after this:

<details>
<summary>Before</summary>

image


</details>

<details>
<summary>After</summary>

image


</details>

**Comment by fqueiruga** [comment]
Interesting let me try to consult with @josephbrueggen to try to come up with something

**Comment by josephbrueggen** [comment]
@timja @varyvol thanks for the feedback! We are looking into how to improve this.

Making the gray darker would reduce text legibility in the 'hover' state, so that likely won't be the fix for this one.

The solution will likely be to re-introduce the border in a manner consistent with other recently adjusted elements.

**Comment by fqueiruga** [comment]
I have added a border to the hyperlinks and updated the screenshots on the description.

**Review by timja — APPROVED** [review]
image

**Review by varyvol — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, we'll merge it in 24 hours if there's no negative feedback

**Comment by timja** [comment]
Seems to have caused the monitoring plugin's UI to break:

image

Pretty sure I saw an issue somewhere for the markup being invalid in this plugin anyway, nested links.

cc @evernat

**Comment by fqueiruga** [comment]
It is probably caused by the fixed link height. I can add a hack to remove it in nested links but I think it should be fixed on the plugin side.

**Comment by evernat** [comment]
@timja @fqueiruga 
html is supposed to be allowed in descriptions of management links: https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/ManagementLink.java#L80
And the secondary link in the description for the monitoring plugin has worked for 10 years: https://github.com/jenkinsci/monitoring-plugin/blob/master/src/main/java/org/jvnet/hudson/plugins/monitoring/PluginManagementLink.java#L53
Now, there is no other way than adding a second ManagementLink next to the first one?

**Comment by daniel-beck** [comment]
The Monitoring Plugin management link has been broken for years, it just wasn't as noticeable: https://issues.jenkins-ci.org/browse/JENKINS-61519

**Comment by fqueiruga** [comment]
Also, nested links are invalid HTML and a use case that I don't think Jenkins should support. That said, the plugin could use some JS code on a span tag styled like a link to emulate an anchor tag. We could add some CSS classes in Jenkins core for that.

**Comment by MikeyCarter** [comment]
Little lost here.  How does one add a new category and get their program to attach to it.

**Pull request merged**
