### PR TITLE
Deprecate FingerprintStorage#getFileFingerprintStorage

### PR DESCRIPTION
**Pull request by daniel-beck**
This utility method is unnecessary, and also brittle, as it relies on the ordering of extensions. Fix it (at least assuming I got the intention correct), and deprecate it, migrating callers to use of `ExtensionList`.

Untested, waiting for PR build.

### Proposed changelog entries

* Deprecate [FingerprintStorage.getFileFingerprintStorage](https://javadoc.jenkins.io/jenkins/fingerprints/FingerprintStorage.html#getFileFingerprintStorage--). Developers should use [FingerprintStorage Extension API](https://www.jenkins.io/doc/developer/extensions/jenkins-core/#fingerprintstorage) instead.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
CC @stellargo

**Review by res0nance — APPROVED** [review]

**Comment by stellargo** [comment]
Plugin developers would be relying on `FingerprintStorage#get()`, so this looks good to me.
@daniel-beck just for my knowledge perspective, would be great if you could help me to understand why you are preferring to deprecate the method, and not just use it after making the changes to using the Extension API

**Comment by daniel-beck** [comment]
> why you are preferring to deprecate the method, and not just use it after making the changes to using the Extension API

I think it's pretty unnecessary because it's not particularly easier than the existing code (especially if, per your comment, legitimate use would likely be only internal). FWIW I was confused about it in #5419 because of the chosen location.

**Review by stellargo — APPROVED** [review]

**Review by basil — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
@daniel-beck ready to go after the merge conflict fix?

**Comment by oleg-nenashev** [comment]
@daniel-beck IMHO it is ready to go

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
@daniel-beck could you please resolve the merge conflict so that we can land it?

**Comment by timja** [comment]
@daniel-beck I've resolved the conflict, is there a reason this is marked as draft?

**Review by basil — APPROVED** [review]

**Comment by basil** [comment]
Not sure why @daniel-beck hasn't replied, but this seems like a reasonable change to me and tests pass, so I've marked it as ready for review and merged with trunk.

---

This PR is now ready for merge. We will merge it after approximately 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process. Thanks!

**Comment by daniel-beck** [comment]
Just E_TOOMANYNOTIFICATIONS, sorry. I don't remember why it was a draft, perhaps because of my uncertainty with

> at least assuming I got the intention correct

**Pull request merged**
