### PR TITLE
Fix NPE on 404 W/O Response Body

### PR DESCRIPTION
**Pull request by pc-cworkman**
I don't have an issue to reference, but I have observed that when a 404 occurs, an NPE will happen like the following:
```
java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:167)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:109)
	at org.apache.commons.io.IOUtils.readLines(IOUtils.java:1944)
	at jenkins.security.ResourceDomainConfiguration.checkUrl(ResourceDomainConfiguration.java:173)
	at jenkins.security.ResourceDomainConfiguration.doCheckUrl(ResourceDomainConfiguration.java:88)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:393)
```

This will no longer dereference the NullPointer when httpURLConnection.getErrorStream() == null.

### Proposed changelog entries

* Entry 1: Fix NPE on 404's without response body, ResourceDomainConfiguration previously expected Http Responses with status 404 to always have an ErrorStream, which is not true. This operation is now null-safe.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

### CODE REVIEW

**Review by NotMyFault — COMMENTED** [review]
This needs a couple of fixes, shifting the import two entries up and handling the IOException introduced properly, before someone could check out the PR.

**Comment by basil** [comment]
Hi @pc-cworkman, thank you for your contribution. Could you please file a Jira ticket with more information about how this stack trace occurs following our [issue reporting](https://www.jenkins.io/participate/report-issue/) documentation, ideally including steps to reproduce the issue from scratch? We need to better understand the scenario in which this problem occurs in order to evaluate the cause of the problem. This PR likely addresses the symptoms of the problem, but a different solution may be needed depending on the cause.

**Comment by pc-cworkman** [comment]
Sorry for the mistakes there @NotMyFault - I hastily pushed this after seeing the problem in a stack trace and neglected to notice the existing exception handling. I have modified this to no longer import new classes and provide the same functionality within the existing try-catch.

@basil Sorry for any mixup - first time contributor here! I read the contribution guide and could have swore it said no Jira tickets were necessary for minor bug fixes, which this seemed to be at the time. Reproduction can be accomplished by returning a 404 without a response body during the identity check referenced in this class.

**Review by basil — CHANGES_REQUESTED** [review]
> I read the contribution guide and could have swore it said no Jira tickets were necessary for minor bug fixes, which this seemed to be at the time.

This is not a minor bug fix. It is a workaround for an issue that lacks the proper context in order for us to be able to evaluate its severity.

> Reproduction can be accomplished by returning a 404 without a response body during the identity check referenced in this class.

And how would such a 404 be returned? I am asking for you to file a Jira with detailed steps to reproduce the issue from scratch on a clean installation of Jenkins without any alterations to the code.

**Pull request closed without merging**
