### PR TITLE
[JENKINS-60907] add Buffered{In,Out}putStream to FilePath.TarCompression.NONE

### PR DESCRIPTION
**Pull request by thomasgl-orange**
See [JENKINS-60907](https://issues.jenkins-ci.org/browse/JENKINS-60907).

Manual tests in my environment show a significant performance improvement (50 secs with defaults settings, 240 secs with compression disabled and no patch, 30 secs with compression disabled and this patch).

### Proposed changelog entries

* Bug: fix poor performance of artifacts archiving when using  `jenkins.model.StandardArtifactManager.disableTrafficCompression=true` ([JENKINS-60907](https://issues.jenkins-ci.org/browse/JENKINS-60907))

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] JIRA issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change
- [ ] Appropriate autotests or explanation to why this change has no tests *=> it should be enough to check that this change does not break existing tests* 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs *=> N/A*

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

### CODE REVIEW

**Review by jvz — APPROVED** [review]
LGTM

**Review by res0nance — APPROVED** [review]
It would be sweet if we could have benchmarks but good sleuthing nonetheless.

**Review by rsandell — APPROVED** [review]

**Review by alecharp — APPROVED** [review]
Thank you for this. It looks good. 

The test failure seems to be related to code that will be removed with https://github.com/jenkinsci/jenkins/pull/4460

**Review by timja — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
I plan to merge it tomorrow if no negative feedback

**Comment by oleg-nenashev** [comment]
no strong opinion whether it should be a bu or RFE.

**Comment by thomasgl-orange** [comment]
Thanks everybody for the reviews, and Oleg for the merge.

> no strong opinion whether it should be a bu or RFE.

I went for bug because, IMHO, `disableTrafficCompression` itself was the new feature, but it has been initialy released with a flaw, which this PR fixes.  Also, time permitting, I would love to see that backported for 2.204.3 (I have yet to search for the LTS guidelines, I've not checked yet how many weeks to wait before marking a Jira as LTS candidate and things like that).  But that's mainly to save me building a patched release for our deployments, not a very strong argument :)
Of course, I won't mind if it is qualified as a simple RFE.

**Pull request merged**
