### PR TITLE
Remove duplicate @Ignore failing the compilation

### PR DESCRIPTION
**Pull request by batmat**
No JIRA. Urgent and internal change. `master` currently is failing for a compilation error.

image

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### CODE REVIEW

**Comment by batmat** [comment]
I think I will watch the build going on and merge this as soon as I see the compilation go successful (i.e. not wait for tests). Given this is going to make all existing PR rebuilds fail, etc.

**Review by vilacides — APPROVED** [review]

**Review by varyvol — APPROVED** [review]

**Review by Wadeck — APPROVED** [review]

**Review by MRamonLeon — APPROVED** [review]

**Comment by Wadeck** [comment]
Due to https://github.com/jenkinsci/jenkins/pull/3799/files#r240538659 😠

**Review by oleg-nenashev — APPROVED** [review]

**Comment by batmat** [comment]
Yup @Wadeck, exactly. Unfortunately, no merge conflict indeed given the lines were not the same.

TBH, retrospectively I think we shouldn't have added that ignore #3721. I think ignoring flakes should be separate and urgent PRs. In such case, it would have been merged, and Matt's PR would have green back also, but master would have been fixed and Jesse wouldn't have added this ignore there.

Anyway, interesting learning :-).

**Comment by batmat** [comment]
OK, compilation phase succeeded, merging:

image

**Pull request merged**
