### PR TITLE
Towards 2.303.2

### PR DESCRIPTION
**Pull request by bmunozm**
LTS candidates:

- https://issues.jenkins.io/browse/JENKINS-66379 (https://github.com/jenkinsci/jenkins/pull/5670)
- https://issues.jenkins.io/browse/JENKINS-66507 (https://github.com/jenkinsci/jenkins/pull/5685)
- https://issues.jenkins.io/browse/JENKINS-66521 (https://github.com/jenkinsci/jenkins/pull/5704) 
- https://issues.jenkins.io/browse/JENKINS-66470 (https://github.com/jenkinsci/jenkins/pull/5723)

### CODE REVIEW

**Comment by bmunozm** [comment]
@daniel-beck @timja  @jtnord @Vlatombe @raul-arabaolaza @imonteroperez @batmat @cathychan @fcojfernandez @MarkEWaite 

I have no permissions to include reviewers or the label `into-lts`

**Comment by jtnord** [comment]
> I have no permissions to include reviewers or the label into-lts

@bmunozm feel free to ask for core committer access (in the mailing list?), given you are driving releases I think you clearly have met the required bar :) )

**Review by jtnord — APPROVED** [review]
checked the community feedback on the changelog, nothing seemed relevant to the included changes.

**Review by imonteroperez — APPROVED** [review]

**Comment by timja** [comment]
Any thoughts on https://github.com/jenkinsci/jenkins/pull/5723 ?

Risk level appears to be 0 and we've had quite a few reports on it

**Comment by basil** [comment]
> Any thoughts on #5723 ?

+1 from me (disclaimer: I exposed the problem and wrote the fix). I did reproduce the problem locally and verify the fix. I would feel slightly better if a real-world user could verify that an incremental build solves the problem for them, but either way this can't really hurt.

**Review by raul-arabaolaza — APPROVED** [review]

**Review by Vlatombe — APPROVED** [review]

**Comment by bmunozm** [comment]
@basil @timja @res0nance https://github.com/jenkinsci/jenkins/pull/5723 included in the PR

**Review by timja — APPROVED** [review]

**Review by res0nance — APPROVED** [review]

**Review by daniel-beck — APPROVED** [review]

**Review by imonteroperez — APPROVED** [review]

**Comment by timja** [comment]
I’ve been trying to this green and no luck so far :( this doesn’t have the full ath suite on it so it should pass

**Review by raul-arabaolaza — APPROVED** [review]

**Comment by timja** [comment]
Yay fixed by increasing CPUs

**Pull request merged**
