### PR TITLE
Use Jenkins modal for 'Apply' button failures

### PR DESCRIPTION
**Pull request by janfaracik**
Previously we'd show a big YUI modal for when the 'Apply' button would fail to save the form. This PR updates that to use a [notification banner](https://weekly.ci.jenkins.io/design-library/Notifications/) and a [Jenkins modal](https://weekly.ci.jenkins.io/design-library/Dialogs/) to display the errors. 

Advantages of this 
- Notifications are consistent with the notification that appears on a successful save
- Notifications and Jenkins modals have better support for theming and are cleaner and more consistent in appearance
- One less reliance on YUI

**Before**
image

image

**After**
image

image

**Before**
image

image

**After**
image

image

### Testing done

* Notifications/modals show as expected for form failures

### Proposed changelog entries

- Use a notification and Jenkins modal for 'Apply' button failures.

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@jenkinsci/sig-ux 

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/8394"></a>

### CODE REVIEW

**Review by timja — APPROVED** [review]
Very nice

**Comment by NotMyFault** [comment]
ATH is not successful.

**Comment by Kevin-CB** [comment]
It looks fine from a security perspective

**Comment by daniel-beck** [comment]
How would you propose that users act on these error messages? The ID is provided so they can ask an admin for help: Users provide the ID, admins can go look through logs for it to understand what went wrong. It's far from convenient, but it doesn't disclose potentially sensitive information to users.

When trying to select the ID from the error popup and releasing the mouse pointer over the popup, it disappears before one can copy the error. That makes the above impossible, unless one tries first to take a screenshot (or like some folks, photo), or it's a repeatable error. That seems like a frustrating experience when using the new UI (even if it's prettier).

(FTR the most straightforward step to reproduce is to check "Poll SCM" and providing an invalid cron pattern. No need to edit the DOM.)

**Comment by lemeurherve** [comment]
> How would you propose that users act on these error messages? The ID is provided so they can ask an admin for help: Users provide the ID, admins can go look through logs for it to understand what went wrong. It's far from convenient, but it doesn't disclose potentially sensitive information to users.
> 
> When trying to select the ID from the error popup and releasing the mouse pointer over the popup, it disappears before one can copy the error. That makes the above impossible, unless one tries first to take a screenshot (or like some folks, photo), or it's a repeatable error. That seems like a frustrating experience when using the new UI (even if it's prettier).
> 
> (FTR the most straightforward step to reproduce is to check "Poll SCM" and providing an invalid cron pattern. No need to edit the DOM.)

Maybe add a "copy to clipboard" button next to the ID?

**Comment by timja** [comment]
> How would you propose that users act on these error messages? The ID is provided so they can ask an admin for help: Users provide the ID, admins can go look through logs for it to understand what went wrong. It's far from convenient, but it doesn't disclose potentially sensitive information to users.

Addressed by switching it to use the same dialog:

image

image

(screenshots updated in the body)

**Comment by timja** [comment]
@jenkinsci/sig-ux ath is now successful in https://github.com/jenkinsci/acceptance-test-harness/pull/1446

**Review by NotMyFault — APPROVED** [review]

**Review by daniel-beck — APPROVED** [review]

**Comment by timja** [comment]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Pull request merged**
