### PR TITLE
Use a destructive button for deleting API tokens

### PR DESCRIPTION
**Pull request by NotMyFault**
The change proposed replaces the tertiary button to purge API tokens with a destructive one (as inteded).

Before:
Screenshot 2022-09-28 at 22 56 21

After:
Screenshot 2022-10-20 at 23 46 45

### Proposed changelog entries

- Entry 1: Issue, Human-readable Text
- ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  - Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")` if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content-Security-Policy directives (see [documentation on jenkins.io](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7184"></a>

### CODE REVIEW

**Comment by timja** [comment]
It looks a bit funny,  button border touching the input and delete button not lined up with the text on the left.
I wonder if it was tertiary to not draw attention to it?

**Comment by NotMyFault** [comment]
> I wonder if it was tertiary to not draw attention to it?

Can't hurt to use the destructive button color for destructive actions, but I agree, the overall alignment of buttons, fields, and tokens is a kinda weird constellation.

**Review by Wadeck — APPROVED** [review]
Good idea to "highlight" the danger aspect 👍

**Comment by NotMyFault** [comment]
Would someone from @jenkinsci/sig-ux mind taking a look please :)

**Comment by timja** [comment]
> Would someone from @jenkinsci/sig-ux mind taking a look please :)

Looks a bit strange with a background when the copy button doesn't have one:

image

**Comment by janfaracik** [comment]
> Looks a bit strange with a background when the copy button doesn't have one

In the same boat here, think it'd look better if they were consistent:

image

**Comment by NotMyFault** [comment]
There we go, I updated the screenshots accordingly 👍🏻

**Review by janfaracik — APPROVED** [review]

**Review by timja — APPROVED** [review]

**Comment by NotMyFault** [comment]
/label ready-for-merge

---

This PR is now ready for merge. We will merge it after ~24 hours if there is no negative feedback.
Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process.
Thanks!

**Pull request merged**
