### PR TITLE
[JENKINS-72744] remove tooltip when widget is refreshed

### PR DESCRIPTION
**Pull request by mawinter69**
Attach the tooltip to the parent element instead of the document body. When a widget is refreshed, the elements are deleted. But the tooltip stays when it is added to the body and thus will never be able to receive an event when the mouse is moved out. Only by clicking somewhere the tooltip disappears
By attaching it to the parent, when the widget is refreshed and the content is removed this will automatically also remove the tooltip html elements.

See [JENKINS-72744](https://issues.jenkins.io/browse/JENKINS-72744).

### Testing done
Manual testing

Start a build and hover over the progress bar in the build history or on the dashboard in the executors widget. After a few seconds you will notice a flicker and the tooltip text is updated. The old tooltip is removed.

### Proposed changelog entries

- JENKINS-72744, remove tooltip when widget is refreshed

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [x] The Jira issue, if it exists, is well-described.
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [x] There is automated testing or an explanation as to why this change has no tests.
- [x] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [x] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [x] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Comment by mawinter69** [comment]
@janfaracik Could this have any side effects when the tooltip is attached to the parent and not the body?
I couldn't find any, but maybe there are in special situations.

**Review by NotMyFault — APPROVED** [review]

**Review by timja — APPROVED** [review]

**Review by daniel-beck — APPROVED** [review]
Seems to work well. Flicker is preferable to stacking IMO.

**Comment by NotMyFault** [comment]
/label ready-for-merge

---

This PR is now ready for merge. We will merge it after ~24 hours if there is no negative feedback.
Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process.
Thanks!

**Comment by mawinter69** [comment]
Caused https://issues.jenkins.io/browse/JENKINS-73158

**Comment by mawinter69** [comment]
fixed with #9263

**Pull request merged**
