### PR TITLE
Second backporting for 2.440.1

### PR DESCRIPTION
**Pull request by NotMyFault**
Latest core version: jenkins-2.445

Fixed
-----

JENKINS-72679           Minor                   2.445
        Admin monitor popup prevents interactions after closing
        https://issues.jenkins.io/browse/JENKINS-72679

---

ref https://github.com/jenkinsci/jenkins/pull/8791#issuecomment-1930076527 and the comment below

### CODE REVIEW

**Review by mawinter69 — APPROVED** [review]

**Comment by daniel-beck** [comment]
Seems a little early. When do you plan to merge this?

**Comment by NotMyFault** [comment]
> Seems a little early. When do you plan to merge this?

The plan was to add update the RC URL in the email thread upon a green PR build waiting for feedback, parallel to people testing it in this weekly.
If nobody objects or reports an issue, I'd merge it next week, thoughts?

**Comment by daniel-beck** [comment]
> parallel to people testing it in this weekly.

It didn't make the weekly.

**Review by imonteroperez — APPROVED** [review]

**Comment by timja** [comment]
If it didn't make the weekly I don't think there's time for it to be validated there, although these do seem low risk, is there a rush or should we push to .2 ?

**Comment by daniel-beck** [comment]
> is there a rush or should we push to .2 ?

Main issue I can see is accidental UI interaction with invisible elements as demonstrated in my video. Some admin monitor buttons can lead to trouble if pressed unintentionally (e.g., the `master`/`built-in` rename). Now how likely that is to happen given the preconditions, no clue.

**Comment by MarkEWaite** [comment]
> is there a rush or should we push to .2 ?

I think we should merge this pull request or we should revert the original pull request and the intervening changes.  

I'd prefer to merge this pull request because I think it is better for the users and better for the project.  However, I acknowledge that is more aggressive than we are usually willing to be for a Jenkins LTS release.  I don't see it as a high risk merge.

If we don't merge this pull request, then I think we should revert original change and the fixes so that we don't risk unexpected interactions with other admin monitors as described by @daniel-beck

**Review by timja — APPROVED** [review]

**Pull request merged**
