### PR TITLE
remove idle executors from widget

### PR DESCRIPTION
**Pull request by mawinter69**
showing idle executors brings no value. They only blow up the widget. Instead the busy/total number of executors are added behind the agent name when the agent is online.
The executor number is removed, to distinguish regular executors from tasks from asynchronous executions (flyweighttask) the latter get a special symbol.

Adds a new icon size class `icon-xs` so the symbols when agents are launching or are offline has better integration into the surrounding brackets and text).

The built-in agent is only shown when it has executors configured or when it is executing an async task that wants to show it's cell

When only a single agent is shown, the busy/total moves to the widget header.

When widget is collapsed, the shown text now distinguishes more different situations.

### Before:
image

#### Dashboard with several agents:
image

#### Dashboard with built-in no executors and one agent:
image
image
collapsed
image

#### Dashboard with built-in no executors and two agents:
collapsed:
image

#### Dashboard with built-in with 2 executors and one agent:
image
collapsed:
image

#### Dashboard with built-in with 2 executors and no agents:
image

collapsed:
image

#### Specific executor
image
collapsed:
image

#### No executors, agents or clouds
image

#### Symbols for offline and launching:
image

### Testing done
manual testing

### Proposed changelog entries

- remove idle executors from widget

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [x] The Jira issue, if it exists, is well-described.
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [x] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Comment by daniel-beck** [comment]
This is pretty nice 👍

One minor issue seems to be that without agents, the widget is empty now, as the header for Built-In Node only shows if you have agents. This may be confusing to (intermediate) users, it looks like nothing can build. (This may even be an opportunity to advertise https://www.jenkins.io/redirect/distributed-builds/ ?)

Another possible issue is that the executor number is shown and if you have several, those numbers appear and it's unclear what they're for or why someone should care. Are they exposed anywhere other than thread dumps? If not, would a symbol, or color, to distinguish between normal/heavyweight and lightweight executors work better?

(Also, [JENKINS-72745](https://issues.jenkins.io/browse/JENKINS-72745) is extremely noticeable now, with a tooltip on the "0/2". Not new here, of course.)

**Comment by mawinter69** [comment]
> This is pretty nice 👍
> 
> One minor issue seems to be that without agents, the widget is empty now, as the header for Built-In Node only shows if you have agents. This may be confusing to (intermediate) users, it looks like nothing can build. (This may even be an opportunity to advertise https://www.jenkins.io/redirect/distributed-builds/ ?)
> 

showing now the same text as when the widget is collapsed, still minor issue that when there are busy executors then the total configured is not shown.

> Another possible issue is that the executor number is shown and if you have several, those numbers appear and it's unclear what they're for or why someone should care. Are they exposed anywhere other than thread dumps? If not, would a symbol, or color, to distinguish between normal/heavyweight and lightweight executors work better?
> 
The executor number is also not really interesting so I changed it that only OneOffExecutors (Flyweighttask) use an icon (with tooltip)

> (Also, [JENKINS-72745](https://issues.jenkins.io/browse/JENKINS-72745) is extremely noticeable now, with a tooltip on the "0/2". Not new here, of course.)

That is probably JENKINS-72744

**Review by timja — APPROVED** [review]
LGTM tested locally

**Review by daniel-beck — APPROVED** [review]

**Comment by timja** [comment]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by timja** [comment]
Likely caused https://github.com/jenkinsci/acceptance-test-harness/issues/1603

**Comment by MarkEWaite** [comment]
I think that this causes a Jelly exception when the docker plugin attempts to edit a cloud definition.  Refer to [JENKINS-73554](https://issues.jenkins.io/browse/JENKINS-73554) for details.

Only visible in weekly releases, not in Jenkins LTS 2.452.3 or Jenkins LTS 2.462.1

**Pull request merged**
