### PR TITLE
Revert "[JENKINS-26445] Build history pagination and search"

### PR DESCRIPTION
**Pull request by tfennelly**
Reverts jenkinsci/jenkins#1641

See [JENKINS-30899](https://issues.jenkins-ci.org/browse/JENKINS-30899)

Really strange. The `queueId` looks to be screwed up on the builds, causing the pagination (which relies on sorting by this `queueId`) to screw up the order in which the builds are displayed. For example, build  num 1 might have a `queueId` of `351` and then build num 2 might have a `queueId` of 60, which seems to make no sense considering that the `queueId` is "supposed" to be incrementing.

### CODE REVIEW

**Comment by tfennelly** [comment]
Possible/probable cause is that the shutdown hook/cleanup (which persists the queueId) is not getting called, resulting in it being reset on next start. @daniel-beck says that, in his experience, the shutdown only works about 30% of the time. That's shocking alright :cry:

**Comment by daniel-beck** [comment]
@oleg-nenashev @jglick @stephenc I'm looking for some input on this.

The problem is that since February, we have persisted `queueId`s, but they aren't reliable enough: #1566 stores these with the `queue.xml` on clean shutdown, which just doesn't happen reliably enough.

As I see it, we have a few options:

1. Merge this revert PR, removing the feature again. Given that it's quite a major RFE, I don't really like removing it again. Also, it's not this part that's the problem, it only surfaces the existing bug.
1. Change this feature to not rely on `queueId`. It *should* work with build numbers for runs and and queue ID for queue items. I'm pretty sure we just need to remove the [few lines here](https://github.com/jenkinsci/jenkins/blob/5c66fcc6b0318ba151ab3a7fcfbd8ec68b5fea42/core/src/main/java/jenkins/widgets/HistoryPageEntry.java#L62...L65) and the inner `else` block that make the backward compatibility code conditional.
1. Fix `queueId` really quickly.

As to the `queueId` issue, we have tons of instances that just don't have consistent `queueIds`. There are essentially three options:

1. Deprecate the entire feature and get rid of it (not an option if we choose to keep the new widget and its reliance on queue ID).
1. Move to a different field name and have XStream deserialize the original field to the legacy value in `readResolve` or something like that.
1. Have a migration script running that fixes queue IDs on startup. Of course there's some difficulty in determining whether a job still needs to be fixed as it'd just change numeric values around, not e.g. change the `builds/` folder content.

Ideally whatever solution we're going with, the builds history should be usable again in 1.634. My favorite is the solution 2 to the widget issue, giving us however long we want to fix the underlying queue ID issue (preferably solution 2 there as well, if possible).

WDYT?

**Comment by KostyaSha** [comment]
Why build queue at all related to build search?

**Comment by daniel-beck** [comment]
#1868 is my proposal to get into 1.634 while we're fixing the `queueId` reliably.

**Comment by daniel-beck** [comment]
Another solution I played around with, which `readResolve()`s `queueId`s to `QUEUE_ID_UNKNOWN`, would not work, as that assumes that all builds are loaded on startup and never discarded from memory. As discarding from memory and build loading can have different reasons it's not correct to assume only the newest N builds will remain in memory. One example is the "Last Failed Build" column that could point to a really obsolete build.

It had the nicer behavior on the UI though without duplication of newly started builds.

**Comment by daniel-beck** [comment]
Obsolete, #1872 has been merged.

**Pull request closed without merging**
