### PR TITLE
Easier to see sections on the configuration pages.

### PR DESCRIPTION
**Pull request by ari**
The current styling doesn't have enough contrast between headings and the body. This commit fixes that problem. I could keep going with other parts of the design, but this seems the most important (and really simple) improvement.

screen shot 2015-06-22 at 10 12 28am

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Cc @gusrieber
AFAIK he is working on the config page layout updates as well

**Comment by daniel-beck** [comment]
For some context: It's JUC Europe week (also: expect low reviewer activity), and this talk is coming up:
https://www.cloudbees.com/jenkins/juc-2015/abstracts/europe/01-02-1400-fennelly-reiber

@gusreiber has proposed some changes to the job config UI before:
https://groups.google.com/d/msg/jenkinsci-dev/6BdWZt35dTQ/T7b0Tn2r2DkJ

Still, if this works well with all the config forms, we should probably include it. Who knows when any proposed larger scale changes actually make it into Jenkins. That said, it looks somewhat out of place in the current Jenkins UI IMO.

**Comment by ari** [comment]
I've added another commit here to ensure the change is more consistent across Jenkins and also to improve consistency of the appearance of links.

The design changes work well on all the pages in Jenkins I can find. In my own installation I've gone a step further to use a more attractive web font from Google, but I thought that that change would not be accepted.

I am sure that Jenkins could do with a more comprehensive makeover, but these minor changes have made a huge improvement to usability for us.

**Comment by Vlatombe** [comment]
Personally, I like the change. I think it improves the form structure readability with a very low cost.

**Comment by daniel-beck** [comment]
> also to improve consistency of the appearance of links.

How well do the changes work for people with (minor) visual impairment? I always thought underlining made it really easy to see what's a link.

**Comment by ari** [comment]
I challenge you to find a mainstream website today which uses underline to denote a link. Which users have managed to download Jenkins from http://jenkins-ci.org/ without the benefit of underlines? Or navigated the left menu? But then are stymied by the job list not having underlines?

Visually impaired users already have a way to cope (perhaps a browser plugin). Many regular users (like me) find underline incredibly hard to read.

**Comment by ari** [comment]
I challenge you to find a mainstream website today which uses underline to denote a link. Which users have managed to download Jenkins from http://jenkins-ci.org/ without the benefit of underlines? Or navigated the left menu? But then are stymied by the job list not having underlines?

Visually impaired users already have a way to cope (perhaps a browser plugin). Many regular users (like me) find underline incredibly hard to read.

**Comment by jtnord** [comment]
gmail underlines links...  I think that's a pretty large site :-)

I like the overall change - not convinced on the removal of the link at the moment (I expect it to be more personal, some people like it some people don't) so perhaps remove that style change and then do a follow up PR that just adds that?

**Comment by ari** [comment]
I don't use gmail, so I'm not overly familiar with it, but I just poked around the settings (like this page https://mail.google.com/mail/u/0/#settings/accounts ) and all the links I could find were blue without underline. I spent only a few minutes poking around other Google properties and couldn't immediately find any underline.

Anyhow, merge my changes if you like them.

**Comment by olivergondza** [comment]
:+1: from me.

**Comment by KostyaSha** [comment]
Please provide before/after screenshots.

**Comment by gusreiber** [comment]
config

As Daniel mentioned, this is an issue that is near and dear to my heart and I think Ari is exactly right, the sections absolutely need better differentiation. I like his solution quite a bit, especially for its immediacy and directness. I have attached a screenshot from the demo I gave at JUCs DC and London, pointing at exactly the same issue.

...so I like what I see of Daniel's change and am inclined to give it a thumbs-up.  I don't see it as being at the exclusion of my ambitions, but rather an affirmation that the issue is a real one.

I am also feeling my way a bit as to what are the best communication venues with the larger community. GitHub PRs are one way to get everyone's attention and share feedback, and a really strong one at that. As Daniel mentioned, I have been using the dev group. I would like to organize and formalize a Jenkins GUI effort. Are there other communication channels that folks are using or would like to be using so we can open the discussion up a bit?

**Comment by KostyaSha** [comment]
@gusreiber unfortunately many business will reply only after changes, because monitoring upstream and devel maillist with many unrelated to productions stuff is very time cost. I can say only that any UI change will break many documentations related to UI. So if you will do infinite UI changes, then you will always break business and real production updates will be more difficult and expensive (also not user friendly).
The same relates to https://github.com/jenkinsci/jenkins/pull/1703

I understand that you like releasing changes every week, but i can propose create some 'ui-changes' branch and work with it. Then merge to dev version after LTS X base will be picked and then get new UI with X+1 lts version.

**Comment by ari** [comment]
Just to be clear to everyone following this. My changes do not look like those posted by @gusreiber Mine look like the screenshot at the top.

I personally don't like the concept of an "accordion" where sections are collapsed. That makes it impossible to see the whole configuration by just scrolling. For quick navigation to sections of a long page, I prefer the scrollspy http://getbootstrap.com/javascript/#scrollspy concept.

I do like @gusreiber design showing the clear nesting of configuration with different background colours (although I would not have picked that strong blue). The levels of nesting are a problem in clarity of the existing conifiguration pages. Despite that, I'd still like my pull request to be accepted since I believe it is a significant step forward with absolutely minimum of disruption to existing users or existing design.

**Comment by olivergondza** [comment]
@KostyaSha, it would be great if we could deliver full UI rework in one thoroughly tested and fully documented changeset. Unfortunately, there is no such thing. Note that this particular PR is not going to make any documentation deprecated. (The fact that screenshots looks differently between versions is something users got used to long ago)

**Comment by daniel-beck** [comment]
I think @gusreiber's unrelated screenshot only confused things here, they are not what this PR is about. I just tried to show @ari what's currently going on in Jenkins UI elsewhere.

Regarding this proposal, I'm still skeptical about the effect on links in inline text. However, taking a look at the current PR build, I cannot find links that aren't underlined. @ari Which links are affected by your change?

**Comment by ari** [comment]
On the home page of my installation I see 

*  left menu (new item, people, etc) as blue/purple with no underline.
* "Build Executor Status" underlined
* list of jobs: underlined
* my name in the top menu: not underlined (but underlined on hover)
* "log out": not underlined
* breadcrumbs (top left menu): not underlined and grey background cell colour on hover
* tabs (for different groups of jobs): not underlined, but grey background on hover

So there really is a combination of all sorts of ideas here. There was a recognition in some places that underlines are unhelpful and hard to read. And in other places, they are used with great enthusiasm.

If you look around the github page you are on right now, you'll find no underline but also no confusion about what is and what isn't clickable through the consistent use of colour. I'd probably enhance my pull request slightly by

    a:visited { color: #204a87; }

That would prevent links being a random mixture of purple and blue based on whether you have clicked on the link before. Jenkins is an application, not an academic paper where you want to know whether you have verified one of the references linked. Consistent blue (like github) might be easier to understand.

**Comment by daniel-beck** [comment]
@ari I was asking about the effect of your change as I did not notice any effective changes. What you describe is both what Jenkins looks like today, and what the build for this PR looks like. And if there really is no difference, why did you include the CSS change to `a:link`?

**Comment by ari** [comment]
@daniel-beck Ah, I misunderstood. I fixed that now since I hadn't properly patched the a:link

Merge this pull request if you like, but even if you all want to want for the next big redesign of Jenkins to land in a year or two, I don't mind. I've got my own patches locally and they look great to me. I've also overridden the font and used one of Google's free fonts to make the text easier to read. However this isn't part of my pull request because I figured people might not like the dependency on a live internet link.

screen shot 2015-07-16 at 6 45 09pm

**Comment by daniel-beck** [comment]
Thanks for the update!

For others' reference, I attached a few screenshots.

Subjectively, I'd have preferred this to be two separate PRs. I like the section headers much more than the changed links.

The links should at least be underlined when hovered to be consistent with the side panel and user/login links, and to make them less ambiguous at least when hovering. This also helps in seeing the extent of a specific link in cases where multiple links appear sequentially in text.

Since some users appear to have difficulties seeing that "Build Executor Status" is an actual link despite color and underline (e.g. JENKINS-29180), this may actually be a step backward in useability. So I'm not sure removing all the underlines is a good idea.

Any other opinions?

configure-new
configure-old
list-new
list-old
manage-new
manage-old
project-configure-new
project-configure-old
project-new
project-old

**Comment by lanwen** [comment]
Please don't add `visited` color on links. I visit all this links hundred times a day. So after a few minutes all links will be another color.

Big headers looks good for me. But It should be underlined too (as in old view)

**Comment by oleg-nenashev** [comment]
I suppose it requires a fix & merge with the master branch

**Comment by ari** [comment]
Is anyone from Jenkins interested in this patch or is any minor UI change just too hard to get through without the sponsorship one of the developers?

Should I just close this and give up on it?

**Comment by ari** [comment]
Unfortunately this simple pull request looks like it will never be merged despite it having a fair bit of interest.

1. Some people decided to hijack the request and turn it into a big discussion about changing the Jenkins UI in a bunch of other ways.

2. Some people believe that unless links are underlined they will be unable to visually locate and identify blue text as a link. I'm not sure how those people manage to use the internet at all today, but I'm not going to argue.

Let's just abandon this and get on with our lives. I'm happy with my local overrides without needing to convince Jenkins developers to adopt them. And I'll submit contributions to https://github.com/jenkins-contrib-themes/jenkins-neo-theme which is dramatically better anyway.

**Comment by gusreiber** [comment]
@ari I just want to apologize for getting myself tangled in your PR. @tfennelly has just submitted a tab divided config page into the v2 branch. I think that can be made more flexible as accordions instead of tabs, and I quite prefer your more open headings to my heavier and blocky approach. Would you object to some of your influences making its way to a 2.0 PR? Is there still some room and chance for collaboration?

**Comment by ari** [comment]
Sure, use any part of this as you need. I personally hate accordions since the assumption that users find it easier to click rather than scroll isn't true in my case. At the very least please store a user preference for whether they should be open or closed by default.

Anyhow, I used to work as a graphic designer and the reason I got out of it was because of the bikeshedding where every customer had a nephew who knew how to design things and I should just listen to this bit of feedback...  :-)  A project has large as Jenkins is going to have a lot of opinions about design, which is probably why it is so hard to get changes agreed on. But hopefully a UX person might step forward and create a unified stylebook... it would be a great step for usability.

Alternatively little projects like https://github.com/jenkins-contrib-themes/jenkins-neo-theme might spring up and one of them could become the new default design. If the core Jenkins had much better semantic html I think that process would happen much faster.

**Pull request closed without merging**
