### PR TITLE
[JENKINS-61467] Do not show disabled, implied permissions in errors

### PR DESCRIPTION
**Pull request by daniel-beck**
See [JENKINS-61467](https://issues.jenkins-ci.org/browse/JENKINS-61467).

### Proposed changelog entries

* Do not show disabled permissions in permission errors when checking for any of several permissions.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [n/a] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Review by res0nance — APPROVED** [review]

**Comment by timja** [comment]
Tests are failing @daniel-beck looks related to the change, permission order isn’t as expected

**Review by fcojfernandez — APPROVED** [review]

**Review by varyvol — APPROVED** [review]

**Comment by fqueiruga** [comment]
This one has been approved for 2 weeks now, can it be merged? @timja

**Comment by fcojfernandez** [comment]
The CI failure seems to be an INFRA issue. Closing and re-opening to re-launch the CI

**Comment by timja** [comment]
Thanks for the PR, let's merge this tomorrow if there's no negative feedback,

the CI build passed yesterday and no changes in between so not too worried about that:
https://ci.jenkins.io/blue/organizations/jenkins/Core%2Fjenkins/detail/PR-4575/18/pipeline

**Pull request merged**
