### PR TITLE
Bulgarian translation

### PR DESCRIPTION
**Pull request by alshopov**

### CODE REVIEW

**Comment by daniel-beck** [comment]
Awesome! 🍻

I don't think we have anyone among regular contributors who speaks Bulgarian (or @oleg-nenashev maybe has hidden talents?), so I'll just give it a quick Google translate check to make sure it looks sane before merging (unfortunately, contributed translations haven't been in the past…).

**Comment by alshopov** [comment]
Hi,

Take your time if you have to - this has been in the works for almost 2 years, will wait a bit more.

What I can do to increase your confidence in merging:

1. I am a long time free and open source software translator - started circa 2000.
2. I do have a lot of Bulgarian translations already done - such as bash, git, GNOME - and many, many others.
3. This is not my first translation for Jenkins - see https://github.com/jenkinsci/jenkins/pull/1913

If you are wondering about the state of the translation - by my standards it is presentable to people.  They will understand it and it can help them. It needs further testing for example some of the properties could be shortened in order to make the interface better looking. Current state also reflects terms in the English original. As they are a bit flaky - for example master/slave terminology is being phased out I will do further work on unification of therms there.

**Comment by daniel-beck** [comment]
In that case I'll save myself the time 👍 Thanks for your contribution.

We'll merge it towards the next weekly release unless something comes up.

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
@alshopov @daniel-beck I can read the most of the text, but I cannot check grammar and typos since the language is quite different from Russian. 

I am fine with merging without a detailed review, but it definitely requires a fix of hyperlinks. The translations have been done 1 year ago, and hence the change doe not reflect the website change to jenkins.io + Wiki redirect links from the main site. But these guys are minor fixes. Thanks for the translation!

**Comment by alshopov** [comment]
Hey Oleg,
Thanx for noticing of links! I thought I eliminated all of these, sadly I missed some. I will coreect.

**Comment by alshopov** [comment]
OK, @oleg-nenashev's request is done.
I have additionally fixed the example in ./core/src/main/resources/hudson/ProxyConfiguration/help-noProxyHost_bg.html:
./core/src/main/resources/hudson/ProxyConfiguration/help-noProxyHost.html mentions "www*.jenkins-ci.org" as a general pattern example. I have translated that to "w*.jenkins.io" which shows you can use "*" for part of name which matches "wiki.jenkins.io".

**Comment by daniel-beck** [comment]
@oleg-nenashev Good find, thanks! Didn't even think of the redirect links. Can we merge this now, WDYT?

**Review by oleg-nenashev — APPROVED** [review]
Fine for merge if it does not collide with the release by @kohsuke

**Comment by daniel-beck** [comment]
Waiting for a good PR build. Seemed random but to be sure.

**Comment by oleg-nenashev** [comment]
"java.lang.AssertionError: expected:<[]> but was:<[This Jenkins instance uses deprecated Remoting protocols: CLI-connect,CLI2-connect,JNLP-connect,JNLP2-connectIt may impact stability of the instance. If newer protocol versions are supported by all system components (agents, CLI and other clients), it is highly recommended to disable the deprecated protocols.]>
"

Maybe I caused it in the last weekly. Restarting the PR

**Comment by oleg-nenashev** [comment]
🚢 🇮🇹

**Pull request merged**
