### PR TITLE
Replace `_()` with `gettext()`

### PR DESCRIPTION
**Pull request by basil**
This PR was automatically generated with a `sed(1)` script. In jenkinsci/stapler#343 we introduced a new `gettext()` method as part of adding support for Java 17, aliasing the old `_()` method to `gettext()` for compatibility purposes. While the `_()` alias works, this PR moves core to use the new `gettext()` function just in case the `_()` alias becomes impractical in some future Java or Groovy update.

### Proposed changelog entries

N/A

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by daniel-beck** [comment]
If this is now the intended way to use this function, a response to

> […] do we expect developers to know about [gettext](https://en.wikipedia.org/wiki/Gettext) to make the mnemonic connection, or would another name be better?

would be nice.

**Comment by basil** [comment]
> a response […] would be nice.

I replied to you in the other thread Daniel.

**Review by jglick — COMMENTED** [review]
-0 I guess; makes source code slightly less legible and there is no particular reason to do this now or perhaps ever. https://github.com/jenkinsci/stapler/pull/343#issuecomment-1076575216

**Comment by basil** [comment]
Let us dispense with this if nobody feels strongly.

**Pull request closed without merging**
