### PR TITLE
Improve button focus states and customizability

### PR DESCRIPTION
**Pull request by fqueiruga**
The changes to the buttons on Jenkins 2.233 (https://github.com/jenkinsci/jenkins/pull/4658) did not include a proper indicator for the focus states. This PR aims to add better focus states for the buttons while taking the chance to enhance the customizability of the buttons.

Summary of the changes:

- Change styling for button focus states. Each button variant has their own outline color (taken inspiration from bootstrap).
- Add extra CSS vars to theme the secondary button.
- Add extra CSS vars to theme button font properties.

Screenshot:
Captura de pantalla 2021-02-16 a las 12 39 56

### Proposed changelog entries

* Improve button focus states.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@timja 
@uhafner 
@halkeye 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by fqueiruga** [comment]
I have also tested it with the dark and solarized themes and it works just fine!

**Review by halkeye — APPROVED** [review]

**Review by timja — APPROVED** [review]
tested on dark and light themes, lgtm

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Review by uhafner — APPROVED** [review]
Nice, thanks!

**Comment by fqueiruga** [comment]
I have pushed 2 commits fixing small issues:

- Focus styles were not properly applied to hyperlinks styled as primary or danger buttons.
- Hover state was not properly being applied on a focused outlined button.

I don't think this warrants a re-review, but I understand if you think one's needed. I have not found any other issue on my extended testing session.

**Pull request merged**
