### PR TITLE
[Fix JENKINS-33245] core asset artifacts bloated due to faulty build assembly step

### PR DESCRIPTION
**Pull request by tfennelly**
See [JENKINS-33245](https://issues.jenkins-ci.org/browse/JENKINS-33245).

### CODE REVIEW

**Comment by tfennelly** [comment]
@jenkinsci/code-reviewers

**Comment by daniel-beck** [comment]
What are the repos for these dependencies?

**Comment by tfennelly** [comment]
@daniel-beck [jenkinsci/js-libs](https://github.com/jenkinsci/js-libs)

**Comment by daniel-beck** [comment]
Underlying fix is https://github.com/jenkinsci/js-libs/commit/f226c00b8b65857d72eaf1f5a0e887cea9100f90

**Pull request merged**
