### PR TITLE
Remove `ui-refresh-overrides.less` and UI refresh toggle

### PR DESCRIPTION
**Pull request by janfaracik**
This removes code to toggle an earlier attempt at a Jenkins UI refresh in order to keep the Jenkins codebase clean.

I've given `jenkinsci` org a search for `isUiRefreshEnabled()` and the only uses were in this repo.

If this is still wanted I'm more than happy to close the PR @fqueiruga :)

### Proposed changelog entries

* Remove experimental header that was never enabled by default

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@jenkinsci/sig-ux @fqueiruga @basil 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by uhafner — APPROVED** [review]
I think we do not need this approach anymore.

**Comment by basil** [comment]
> I've given `jenkinsci` org a search for `isUiRefreshEnabled()` and the only uses were in this repo.

Excellent! I also did a code search for [`ui-refresh`](https://cs.github.com/?scopeName=All+repos&scope=&q=user%3Ajenkinsci+%22ui-refresh%22) and did not find any results. :thumbsup:

I believe there are no usages of this code in the `jenkinsci` GitHub organization. Any potential usages of this code would be in private repositories.

**Review by timja — APPROVED** [review]

**Comment by fqueiruga** [comment]
@janfaracik thank you, please set it on fire lol. I had intented to remove this but I never got around doing it.

**Review by fqueiruga — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]
Looks good, I created a PR on the dark theme plugin to adapt this change.

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Review by basil — APPROVED** [review]
Thanks for confirming @fqueiruga.

**Pull request merged**
