### PR TITLE
Config loading screen style update

### PR DESCRIPTION
**Pull request by jninnes**
Update the style of the "loading" screen when configuring jobs. 
- Uses the "unknown" job progress bar
- Avoids the ugly flash of greyed out content.
- Halved the font size of the "LOADING" text

We could avoid adding additional markup if we used a vector font for the loading progress bar/spinner, but jenkins doesn't use any vector fonts afaik.

Before:
before

After:
after

### CODE REVIEW

**Comment by KostyaSha** [comment]
I like:
- grey background 
- loading with progress
- place loading in the middle of area (horizontally and vertically)

In case of plugin bugs `loading` wouldn't disappear and in place where loaded layout ends will be the root of issue. :-1:  for hiding background lazy loaded rendering.

**Comment by batmat** [comment]
Thanks for the work. Didn't test the PR locally, but IIUC your screenshot, there would not be any progressive rendering. 

I just checked here and I actually think that progressive rendering, though certainly improvable is actually a feature: I often find myself scrolling during the loading to start looking for what I want. Hence unsure this change isn't a bit too "opinionated" (?).

**Comment by olivergondza** [comment]
Agree with Baptiste, I am -1 on this change.

**Comment by daniel-beck** [comment]
:+1: I think this change is a great idea. There's rarely a need to know how the sausage gets made, and the number of people making use of the current broken loading screen is likely very low. OTOH this change makes the loading screen look professional, rather than amateurish and broken like now.

**Comment by jtnord** [comment]
The only thing that concerns me is if Jenkins OOPses whilst getting some plugin details (e.g. a 500); will that leave a page with no feedback seemingly loading forever with no clue as to what has gone wrong?

**Comment by batmat** [comment]
@daniel-beck yeah, after reading your comment, I also agree this screen indeed looks broken. 
+0.9 from me then.

Wondering if the job configuration loading could be optimized. Don't know how much it's specific to our install, but it can takes up to 3-5 seconds here, hence my weird workflow indeed :).

workflow-xkcd

**Comment by daniel-beck** [comment]
@jtnord Looks like you can just open your web developer tools and remove the div from the page. If you're technical enough to gain some insight from where the rendering stopped, you can manage this.

@jninnes What happens when you scroll down? Does this hide the entire config form or only the part "above the fold"?

**Comment by daniel-beck** [comment]
@olivergondza Ping (see previous comments)

@jninnes Ping -- are you still interested in this change?

**Comment by jninnes** [comment]
@daniel-beck  can be closed. Improvements in 2.x override this change.

**Comment by daniel-beck** [comment]
@jninnes Thanks!

**Pull request closed without merging**
