### PR TITLE
Node & package mirroring, yarn

### PR DESCRIPTION
**Pull request by jglick**
# Description

See [INFRA-1139](https://issues.jenkins-ci.org/browse/INFRA-1139).

Akin to https://github.com/jenkinsci/plugin-pom/pull/57 + https://github.com/jenkinsci/plugin-pom/pull/63: we would like to avoid hitting third-party servers (more precisely, anything except github.com + repo.jenkins-ci.org) during builds.

`yarn.lock` created after:

    yarn config set -- --registry https://repo.jenkins-ci.org/api/npm/npm/

Testing:

```bash
rm -rf ~/.m2/repository/com/github/eirslett/{node,npm,yarn}
mvn -f war -DcleanNode clean package
```

and then running `jenkins.war` and confirming:

* setup wizard is OK
* install Blue Ocean, then…
* create Pipeline, **New** dialog OK
* ACE editor works
* Blue Ocean works

### Changelog entries

Proposed changelog entries: N/A

### Desired reviewers

@reviewbybees esp. @cliffmeyers & @daniel-beck & @tfennelly

### CODE REVIEW

**Review by tfennelly — APPROVED** [review]
LGTM 👍

**Comment by jglick** [comment]
@reviewbybees done

**Comment by recena** [comment]
Belated 👍

**Review by oleg-nenashev — APPROVED** [review]
Looks good to me. Had is been documented somewhere in INFRA documentation?

**Comment by jglick** [comment]
Good point; I filed https://github.com/jenkins-infra/documentation/pull/3.

**Pull request merged**
