### PR TITLE
Add undo and redo icon

### PR DESCRIPTION
**Pull request by DuMaM**
Following with suggestion of @NotMyFault i'm adding ionic symbol for undo and redo ([here](https://github.com/jenkinsci/workflow-cps-plugin/pull/559#discussion_r915550215))

It will replace usage of this one: [icon-undo](https://github.com/jenkinsci/jenkins/blob/master/war/src/main/webapp/images/svgs/undo.svg) and [icon-redo](https://github.com/jenkinsci/jenkins/blob/master/war/src/main/webapp/images/svgs/redo.svg)
Those icons was provided from this site: https://ionic.io/ionicons

I did't added any autotest. It's already well tested feature and I only extend it by adding new usage options.

Connected PR's:
https://github.com/jenkinsci/workflow-cps-plugin/pull/559

### Proposed changelog entries

* -

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")` if applicable.
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@NotMyFault @janfaracik 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/6795"></a>

### CODE REVIEW

**Review by NotMyFault — COMMENTED** [review]
That should probably be added to https://github.com/jenkinsci/jenkins/blob/5b1e934544e0dabd5ae4088dba7e97d652e075d7/core/src/main/java/org/jenkins/ui/icon/IconSet.java#L574
to override existing icons too.

Otherwise, LGTM

**Comment by DuMaM** [comment]
> That should probably be added to
> 
> https://github.com/jenkinsci/jenkins/blob/5b1e934544e0dabd5ae4088dba7e97d652e075d7/core/src/main/java/org/jenkins/ui/icon/IconSet.java#L574
> 

I was looking for this for such long time 😄 how does old icons are updated, thanks

**Review by NotMyFault — APPROVED** [review]

**Comment by DuMaM** [comment]
I checked this with Pipeline Plugin on gitpod and it's working fine.

**Review by timja — APPROVED** [review]
untested but looks fine

**Review by janfaracik — APPROVED** [review]

**Comment by DuMaM** [comment]
I'm not sure how to interpret this. Windows build is unstable, where linux one are fine. 
Only one test failed on timeouts. Should i do something about it or it's just flaky test?

**Comment by timja** [comment]
> I'm not sure how to interpret this. Windows build is unstable, where linux one are fine. Only one test failed on timeouts. Should i do something about it or it's just flaky test?

don't worry about it for this

**Comment by DuMaM** [comment]
could we merge it?

**Review by basil — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
