### PR TITLE
Remove unused CSS file

### PR DESCRIPTION
**Pull request by zbynek**
Since styles are now implemented using `less`, this file seems to be needed no more.

### Proposed changelog entries

* Entry 1: Remove unused CSS file

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [n/a] JIRA issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [n/a] Appropriate autotests or explanation to why this change has no tests
- [n/a] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@fqueiruga 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

### CODE REVIEW

**Comment by fqueiruga** [comment]
I'd suggest not doing this, it will break some plugins by @uhafner

**Comment by uhafner** [comment]
I have a switch now in my layout: for Jenkins > 2.222 the following file is used: https://github.com/jenkinsci/bootstrap4-api-plugin/blob/master/src/main/resources/bootstrap/layout-post-2.222.jelly

It seems not to use the style.css anymore.

**Comment by fqueiruga** [comment]
Whatever you consider better. Anyway, if we are removing it we should also remove the `layout-commons.css` file.

**Comment by uhafner** [comment]
From my side it should be save: if someone has an old installation (like our own CI instance at https://ci.jenkins.io 😉) then switching to the new UI header changes will break the layout anyway. As soon as someone has the bootstrap4-api plugin installed it should work...

**Comment by fqueiruga** [comment]
I'll leave it to your criteria then :D

**Review by timja — APPROVED** [review]
it's confusing having it here, +1 to remove

**Review by varyvol — APPROVED** [review]
If @uhafner is fine with it, I agree with the removal to avoid any confusion.

**Review by fcojfernandez — APPROVED** [review]
Since there is an initiative to update the UI, all these changes are an opportunity to improve

**Review by fqueiruga — CHANGES_REQUESTED** [review]
I believe the old layout-commons.css file should also be removed

**Review by fqueiruga — APPROVED** [review]

**Comment by timja** [comment]
Let’s merge it tomorrow if there’s no negative feedback

**Pull request merged**
