### PR TITLE
Upgrade Guice from 4.0 to latest

### PR DESCRIPTION
**Pull request by basil**
### Proposed changelog entries

Upgrade the [Guice](https://github.com/google/guice) library from [4.0](https://github.com/google/guice/releases/tag/4.0) (released on April 28, 2015) to [5.0.1](https://github.com/google/guice/releases/tag/5.0.1) (released on March 2, 2021).

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by jetersen** [comment]
Successfully passes in bom: https://github.com/jenkinsci/bom/pull/694

**Review by timja — APPROVED** [review]

**Comment by jglick** [comment]
Can this be readied for review?

**Comment by timja** [comment]
> Can this be readied for review?

I’m guessing basil wants to separate the release version from guice

**Comment by jglick** [comment]
What about now?

**Review by timja — APPROVED** [review]

**Review by jglick — APPROVED** [review]
Until we can delete it, upgrading it is the next best thing!

**Comment by timja** [comment]
> Until we can delete it, upgrading it is the next best thing!

upgrading this allows Jenkins to start without command line flags on java 17.
(doesn't actually work without the flags, but it's at least nice to start!)

**Review by jetersen — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Review by res0nance — APPROVED** [review]

**Comment by timja** [comment]
caused https://issues.jenkins.io/browse/JENKINS-67174

**Pull request merged**
