### PR TITLE
Reduce usages of com.google.common.base

### PR DESCRIPTION
**Pull request by basil**
Replaces most usages of `com.google.common.base` with native Java or Jenkins functionality. The underlying motivation is to make the code easier to read by using a consistent paradigm as much as possible (namely, JDK classes rather than a mixture of JDK classes and Guava classes).

### CODE REVIEW

**Review by daniel-beck — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Comment by jtnord** [comment]
relation to #5344 ? 

//cc @olamy

**Comment by oleg-nenashev** [comment]
Do we want to changelog it?
Also, maybe you want to consider joining the core team @basil  :) https://groups.google.com/g/jenkinsci-dev/c/1ioTdU4784M/m/7fXzCTIMFgAJ

**Review by jtnord — APPROVED** [review]

**Comment by daniel-beck** [comment]
> Do we want to changelog it?

I don't see why, except _maybe_ if there's enough changes of this type for a general "code cleanup" entry. The audience is users and I doubt they care unless something breaks.

**Review by res0nance — APPROVED** [review]

**Comment by basil** [comment]
I agree with Daniel that this doesn't qualify as a noteworthy change from the end user's point of view. For that matter, neither are the dozens of changelog entries in plugins that say things like "Bump plugin parent POM" and "Bump plugin BOM". 😊

**Comment by timja** [comment]
> I agree with Daniel that this doesn't qualify as a noteworthy change from the end user's point of view. For that matter, neither are the dozens of changelog entries in plugins that say things like "Bump plugin parent POM" and "Bump plugin BOM". 😊

🤷 most plugins have a very clear section right at the bottom that is dependencies, very easy to ignore.

The jenkins 'changelog' layout isn't so nice for that sort of thing. also it's more of release notes than a changelog

**Comment by olamy** [comment]
> relation to #5344 ?
> 
> //cc @olamy

arf I missed this. yup I will close my pr as nobody wants it but do it in separate PRs 🤣

**Pull request merged**
