### PR TITLE
Change to new spelling rules in german

### PR DESCRIPTION
**Pull request by senk**
Changed every occurence of 'muß' to 'muss' and 'daß' to 'dass' because it's no longer
correct.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
CC @daniel-beck @albers

**Comment by albers** [comment]
@senk Good idea, but please also cover encoded occurrances like `\u00df`.
@oleg-nenashev Thanks for the ping.

**Comment by senk** [comment]
@albers Thanks, i will catch up on this!

**Comment by oleg-nenashev** [comment]
@senk Hi. How is it going with this PR?

**Comment by senk** [comment]
I'm in holiday till 20.06 and will definitely catch up afterwards

**Comment by senk** [comment]
changed it @albers @oleg-nenashev @daniel-beck

**Comment by albers** [comment]
Thanks for updating. It's still not complete, though: There are several capitalized occurrances (`\u00DF`) missing.

**Comment by senk** [comment]
now it should be complete

**Comment by albers** [comment]
Yes, it's perfect. Thanks.

**Pull request merged**
