### PR TITLE
Removed unused deprecated Memoizer

### PR DESCRIPTION
**Pull request by StefanSpieker**
Removed unused (and deprecated for a while) class Memoizer.
Nothing found with: 
* [deprecated-and-unused](https://ci.jenkins.io/job/Infra/job/usage-in-plugins/job/master/lastSuccessfulBuild/artifact/output/deprecated-and-unused.html)
* [github search](https://github.com/search?q=org%3Ajenkinsci+Memoizer&type=Code)

### Proposed changelog entries

* Internal: Removed unused internal class Memoizer - use ConcurrentHashMap

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

### CODE REVIEW

**Review by markjacksonfishing — APPROVED** [review]

**Review by timja — APPROVED** [review]
would be good to know when it was deprecated as well, but looks fine

**Review by res0nance — COMMENTED** [review]
Seems to have been deprecated 2 years ago with `jenkins 2.86`

**Review by rsandell — APPROVED** [review]

**Review by MRamonLeon — APPROVED** [review]

**Comment by rsandell** [comment]
Though @oleg-nenashev 's comments in #4468 is probably also food for thought here.

**Review by oleg-nenashev — APPROVED** [review]
Let's merge it after the LTS cutoff

**Review by alecharp — APPROVED** [review]

**Review by fcojfernandez — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
We are beyond the LTS cutoff date. Will merge it tomorrow if no negative feedback

**Comment by daniel-beck** [comment]
Was used until https://github.com/jenkinsci/workflow-cps-plugin/commit/3890d3e34156c5f645bedb4831d5cb5df3d81d1a in `workflow-cps-2.29`. Just FTR. (Upcoming LTS upgrade guide maybe?)

**Pull request merged**
