### PR TITLE
Upgrade to the latest version of commons-beanutils.

### PR DESCRIPTION
**Pull request by jeffret-b**
Pick up the latest improvements and hardenings. Minor update. We don't use the affected features but it would be good to be on the latest version.

I don't think this one warrants a Jira ticket, but I can create one if it helps.

No new tests are needed as there should be no changes. Relying on existing tests and compilation for regression detection. The update from 1.9.3 to 1.9.4 should not have an impact.

See the [commons-beanutils changelog](http://commons.apache.org/proper/commons-beanutils/javadocs/v1.9.4/RELEASE-NOTES.txt) or the [PR](https://github.com/apache/commons-beanutils/pull/7)

### Proposed changelog entries

* Internal: Update commons-beanutils from 1.9.3 to 1.9.4.

### Submitter checklist

- [n/a] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### CODE REVIEW

**Review by jvz — APPROVED** [review]

**Review by res0nance — APPROVED** [review]
LGTM Assuming CI Passes

**Review by Wadeck — APPROVED** [review]
:bee: not tested manually, but read the changelog.

**Comment by jeffret-b** [comment]
Let's try a rebuild and see if we can get a clean one now.

**Comment by jeffret-b** [comment]
Hmm ... I need to investigate the test failures. See if they're because of my change or the Jenkins CI infra.

**Comment by jeffret-b** [comment]
This turned out to be more difficult than originally believed. The changes I proposed are insufficient and not necessarily the way we want to proceed. We should consider the technical debt of our Jelly release before proceeding in that direction.

**Pull request closed without merging**
