### PR TITLE
Check admin permission on asynchPeople link

### PR DESCRIPTION
**Pull request by d3camp0s**
See [JENKINS-65949](https://issues.jenkins-ci.org/browse/JENKINS-65949).

### Proposed changelog entries

* Do not allow unauthenticated users to get information from jenkins users in the 'asynchPeople' section.
* Limit access to the 'asynchPeople' section for admin users only.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@jenkinsci/code-reviewers

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by daniel-beck** [comment]
> Do not allow unauthenticated users to get information from jenkins users in the 'asynchPeople' section.

We don't, you need Overall/Read. We generally recommend not granting anonymous users that level of access for the vast majority of instances.

The linked issue has no information why this would be useful. Please explain your use case. JENKINS-18884 might help (while I still think that justification is flawed, I haven't gotten a real expert in AD to look into it).

**Review by daniel-beck — CHANGES_REQUESTED** [review]
This does not take care of the people API or asyncPeople API.

The sidepanel link is still shown to users without Overall/Administer permission.

(FWIW I am not confident we'd merge it even if this were implemented well.)

**Comment by d3camp0s** [comment]
@daniel-beck 
We are using the Roles plugin (Role based Strategy) and we grant the global read to the anonymous user so that all users have visibility of what the rest of the teams are doing.

But in our organization, obtaining personal information from other users is considered a serious security violation.

they should only have access to see the pipeliens and folders.

**Comment by d3camp0s** [comment]
the change only add this line in the main layout:
 permission="${app.ADMINISTER}"

only admins shouldbe see users on asychPeople link.

**Comment by daniel-beck** [comment]
>  We are using the Roles plugin (Role based Strategy) and we grant the global read to the anonymous user so that all users have visibility of what the rest of the teams are doing.
> 
> But in our organization, obtaining personal information from other users is considered a serious security violation.

Note that users (well, "People") are still referenced in Jenkins as the ones who triggered builds, as the ones who committed to SCM in the integrated changelog, etc.

I don't think it is possible to reconcile these conflicting requirements in current Jenkins.

> only admins shouldbe see users on asychPeople link.

That's not what your PR does. Have you tested it?

**Comment by d3camp0s** [comment]
> That's not what your PR does. Have you tested it?
test? Yes of course!

mr_test_isnot_admin

and cant see the people.

cant_see

**Comment by daniel-beck** [comment]
As you can see in your screenshot, the sidepanel link still exists. That's what I meant by

> The sidepanel link is still shown to users without Overall/Administer permission.

Besides that, `/people/api/` and `/asynchPeople/api/` will still be accessible.

Showing links to inaccessible features is a bad user experience and inconsistent with the rest of Jenkins.

> would have to do it 1 to 1, page by page

This is trivial to automate. Jenkins has an API.

There's also the fact that users are added to search suggestions. `/search/suggest?query=a` etc. can be used to fairly quickly enumerate lots of users (and it's easier the less access the user has, fewer jobs polluting results).

----

This PR doesn't accomplish the stated goal and does so in a flawed manner. I propose this be closed.

**Comment by d3camp0s** [comment]
> This PR doesn't accomplish the stated goal and does so in a flawed manner. I propose this be closed.

Okay, ok, now I understand.  tomorrow i will review the api code and maybe add a validation for admin permissions.  if you want you can close this MR. 
thanks for the explanation

**Comment by jglick** [comment]
While there are likely a number of routes by which “people” can be enumerated when you grant access to projects (`Item.READ`), I think it would make sense to move the **People** functionality to a plugin that could just be disabled as it makes lots of users uncomfortable.

**Comment by MarkEWaite** [comment]
Closing per agreement between @daniel-beck and @d3camp0s .

**Pull request closed without merging**
