### PR TITLE
Pull in new version of Stapler

### PR DESCRIPTION
**Pull request by kohsuke**
Pull in new version of Stapler that has various `@WebMethod` related improvements.

### CODE REVIEW

**Comment by kohsuke** [comment]
@reviewbybees

**Comment by abayer** [comment]
Dupe of https://github.com/jenkinsci/jenkins/pull/2057 =)

**Comment by abayer** [comment]
:bee:

**Comment by kohsuke** [comment]
Validation failed with timeout. Hmm.

**Comment by kohsuke** [comment]
This is getting blocked by a merge problem in the master branch. I'm feeling lucky.

**Pull request merged**
