### PR TITLE
[JENKINS-35906] Ensure that SCMDescriptor.newInstance overrides are honored

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-35906](https://issues.jenkins-ci.org/browse/JENKINS-35906)

Corrects a regression from #2371.

@reviewbybees

### CODE REVIEW

**Comment by kohsuke** [comment]
I feel like we should be killing `Descriptor.newInstance()` and also we do some magic during databinding a tree of JSON objects so that any `Descriptor.newInstance()` overrides are honored, but :bee: to fix regressions

**Comment by kohsuke** [comment]
That magic that I'm referring to is `Descriptor.NewInstanceBindInterceptor`. Why should that not work?

**Comment by kohsuke** [comment]
`Descriptor.NewInstanceBindInterceptor` is the magic I was referring to. I looked at the code and this interceptor only gets installed via Descriptor.newInstance(), which this change ensures we will be using.

**Comment by jglick** [comment]
> this interceptor only gets installed via Descriptor.newInstance()

Right, so it works on *nested* calls, but at top level you still need to ask for `newInstance`.

**Comment by oleg-nenashev** [comment]
🐝 , conflicts with https://github.com/jenkinsci/jenkins/pull/2422

**Comment by oleg-nenashev** [comment]
@reviewbybees done in any case.
@jglick Could you investigate the NPE risk?

**Comment by oleg-nenashev** [comment]
🐛 since <code>newInstanceFromRadioList</code> may return null according to the code. I propose to add annotation to this method and explicitly check null in the code

**Comment by oleg-nenashev** [comment]
🐝

**Pull request merged**
