### PR TITLE
Add Jettison Driver for JSON ORM as dependency

### PR DESCRIPTION
**Pull request by stellargo**
Currently, Jenkins uses a custom version of x-stream for ORM of objects to XML. There is another driver, which is the Jettison driver as mentioned [here](https://x-stream.github.io/json-tutorial.html), which allows mapping to JSON. Adding this dependency would allow plugins to use this driver to get JSON mappings of objects.

Please refer to below comment: 
https://github.com/jenkinsci/jenkins/blob/09b9e96d72fc4932f8ce5338d05cc863f2f9a9a6/core/src/main/java/hudson/util/XStream2.java#L103

### Proposed changelog entries

NA

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by stellargo** [comment]
WIP

**Comment by daniel-beck** [comment]
Adding new dependencies to Jenkins core is just waiting to be a future headache, as plugins start using it and then we'll need to do a major version upgrade and break everything. "API plugins" are generally the preferred approach: https://www.jenkins.io/doc/developer/plugin-development/dependencies-and-class-loading/#using-library-wrapper-plugins

**Comment by stellargo** [comment]
Hi @daniel-beck thank you so much for providing the link to the useful article :) However my use case falls under the last para of https://www.jenkins.io/doc/developer/plugin-development/dependencies-and-class-loading/#initiating-vs-defining-loaders which says: `This means that C cannot provide some class A might need to link against. A needs to be able to “see” any such class on its own. Otherwise you will get a NoClassDefFoundError at runtime.` 

In this case, C is the plugin I am working on, and A is Jenkins core. I would strongly appreciate your guidance :)

**Comment by oleg-nenashev** [comment]
There are ways to add libraries to the custom Jenkins core build, e.g. via Custom WAR Packager. If you need to add a dependency to the Jenkins core itself, I am afraid it requires a serious justification and, ideally, usage inside the core. I would recommend to start from explaining the use-case in the pull request description

**Comment by stellargo** [comment]
@oleg-nenashev I have updated the PR description. If you think the WAR packager route is better, could you please guide me to some example where this has been done?

**Comment by stellargo** [comment]
@oleg-nenashev wouldnt using custom war packager mean that users would not be able to use the plugin on their already running Jenkins instances.

**Comment by oleg-nenashev** [comment]
Yes, custom war packager effectively means a custom Jenkins WAR build. Technically common users should be able to just download the JAR and reference it through classpath. Not an ideal solution either.

Lemme think whether we could have an alternative solution

**Pull request closed without merging**
