### PR TITLE
Create README-TR.md

### PR DESCRIPTION
**Pull request by ghost**
Turkish version of README.md

- [+ ] JIRA issue is well described
- [+ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [+ ] Appropriate autotests or explanation to why this change has no tests
- [ +] For dependency updates: links to external changelogs and, if possible, full diffs

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
TBH I am not sure that we should have localized README versions, because it's hard to maintain them. 

@jenkinsci/code-reviewers WDYT?

**Comment by oleg-nenashev** [comment]
Not sure how we could proceed here. @aytekk have you considered hosting something about Jenkins in Turkish externally (website, etc.)? CC @bitwiseman @tracymiranda who may be interested

**Comment by batmat** [comment]
I do not think either the project's codebase is a place that should be localized. The README is designed for developers instead of end-users, and the lingua franca there is English.

I agree this could be closed. I'll likely do it on next pass if nobody objects.

Oleg and I and not English native speakers, FWIW.

@aytekk thanks a lot for your contribution! Can you please clarify your intention here?

If you wish to contribute, there are certainly many areas where your work would be deeply welcome, for instance look for `.properties` file in the core, these are files that definitely are designed to be translated once per language for instance :-)

**Comment by oleg-nenashev** [comment]
closing according to the feedback and lack of response from @aytekk

**Pull request closed without merging**
