### PR TITLE
[JENKINS-65273] fix SSH CLI authentication

### PR DESCRIPTION
**Pull request by jtnord**
Downgrade apache sshd-core to 2.5.1 to not be affected by
https://issues.apache.org/jira/browse/SSHD-1105

Validated the change with the sshd-plugin CLITest

`>mvn clean test -Djenkins.version=2.294-SNAPSHOT
-Denforcer.skip=true`

See [JENKINS-65273](https://issues.jenkins-ci.org/browse/JENKINS-65273).

### Proposed changelog entries

* [JENKINS-65273]Fix regression in SSH CLI authentication introduced

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Review by batmat — APPROVED** [review]

**Review by res0nance — APPROVED** [review]

**Comment by timja** [comment]
Thoughts on merging when green? Backporting and cutting a new RC? Seems low risk

**Comment by jtnord** [comment]
CloudBees is currently running a regression suite (ATH many plugins etc...) against a build with this cherry-picked into `stable-2.289`  I'm not expecting any regressions but as we are late maybe best to wait (about 4 hours) for this to complete so we do not get suprisies?  (or maybe on the other hand it is good to get an RC into the hands of the people earlier for testing)....

**Review by alecharp — APPROVED** [review]

**Review by kuisathaverat — APPROVED** [review]

**Review by MRamonLeon — APPROVED** [review]

**Review by rsandell — APPROVED** [review]

**Review by jglick — APPROVED** [review]

**Comment by timja** [comment]
@jtnord how're we looking?

**Comment by jtnord** [comment]
@timja 10k/30k tests complete....  so far no regressions

**Comment by jtnord** [comment]
@timja @res0nance tests pass, no regressions found

**Comment by timja** [comment]
Someone able to create a back port pr?

**Pull request merged**
