### PR TITLE
[JENKINS-64775] Restores plugin details in DOM

### PR DESCRIPTION
**Pull request by alecharp**
See [JENKINS-64775](https://issues.jenkins-ci.org/browse/JENKINS-64775).

This is to restore the data we had in `/pluginManager/available` tab, which is also available in `/pluginManager/installed` and `/pluginManager/` tabs.

It would be great if we could have this in the next LTS (backporting this if necessary).

### Proposed changelog entries

* Entry 1: Add 'plugin-id' and 'plugin-version' data attributes back to plugin manager available page 
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@fqueiruga @timja @jenkinsci/code-reviewers 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by jglick** [comment]
Amending #5051?

**Review by timja — COMMENTED** [review]
I have no issues with it, but why?

is there a reason you haven't added it in the same way it is on the other pages?

This line I think?
https://github.com/jenkinsci/jenkins/blob/2c1e8399ca108fcdd089e8c1fa27014750bf4f56/core/src/main/resources/hudson/PluginManager/table.jelly#L98
(jglick: edited to be a permalink as per **Y** key)

**Comment by alecharp** [comment]
@jglick correct, amending #5051.

@timja in the `installed` tab, we have `data-plugin-id`, which is why I went with those attributes.

**Review by timja — APPROVED** [review]

**Review by fqueiruga — APPROVED** [review]

**Comment by alecharp** [comment]
For the record, @timja, I agree that we have some different way to have this, and we shouldn't. At some point, it would be nice to have a common way to display the plugins in the plugin manager, as some details are missing from in the _installed_ or _updates_ tabs but are really nice to have: release date, up for adoption for example.

**Comment by timja** [comment]
> For the record, @timja, I agree that we have some different way to have this, and we shouldn't. At some point, it would be nice to have a common way to display the plugins in the plugin manager, as some details are missing from in the _installed_ or _updates_ tabs but are really nice to have: release date, up for adoption for example.

Ideally we come up with a new design, or implement the plugin site version in here.
The previous PR was just a quick fix to solve the performance issues, it could be adapted to the other pages, the main page is just there's a lot of messages that show up and setting the appropriate one and moving the translations is a pain. 

All do-able though

**Review by MRamonLeon — APPROVED** [review]

**Review by MRamonLeon — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
Looks good, thanks!

We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Pull request merged**
