### PR TITLE
Adding a few nullability annotations

### PR DESCRIPTION
**Pull request by jglick**
Demonstrates that code from #2454 was in fact safe.

@reviewbybees esp. @oleg-nenashev

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Yep, I've checked the code before putting a bee in #2454.
🐝 , but it also makes sense to annotate constructors

**Comment by daniel-beck** [comment]
:+1:

**Comment by jglick** [comment]
> it also makes sense to annotate constructors

Which ones did you have in mind? There is a private one and a data-bound one, neither particularly interesting to annotate, but could if you like.

**Comment by oleg-nenashev** [comment]
NVM. <code> Secret.fromString()</code> is annotated correctly

**Comment by oleg-nenashev** [comment]
Jenkins PR builder has critical days again :(
CC @bwalding

**Pull request merged**
