### PR TITLE
[FIXED JENKINS-37438] - method to run setup wizard after Jenkins is modified

### PR DESCRIPTION
**Pull request by kzantow**
In certain situations, you may need to run the setup wizard after there are some items created. This provides a method by placing an empty `jenkins.install.InstallUtil.lastExecVersion` in `JENKINS_HOME` to force the setup wizard to run.

This should supercede https://github.com/jenkinsci/jenkins/pull/2508

This addresses: [JENKINS-37438](https://issues.jenkins-ci.org/browse/JENKINS-37438)
This also addresses: [JENKINS-34007](https://issues.jenkins-ci.org/browse/JENKINS-34007)

@reviewbybees esp. @Vlatombe @ndeloof

### CODE REVIEW

**Comment by Vlatombe** [comment]
LGTM 🐝

**Comment by oleg-nenashev** [comment]
looks fine (got into this issue as well) 🐝

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Comment by oleg-nenashev** [comment]
@kzantow please document this new property on Wiki

**Pull request merged**
