### PR TITLE
[FIXED JENKINS-36593] - Make ItemCategory#MIN_TOSHOW restricted

### PR DESCRIPTION
**Pull request by oleg-nenashev**
https://issues.jenkins-ci.org/browse/JENKINS-36593

@reviewbybees and esp. @recena

### CODE REVIEW

**Comment by recena** [comment]
🐝 although this field was introduced in middle of a long process and my recommendation today is to remove it. Really, the service consumer (front-end for example) is who should decide the rendering conditions.

**Comment by recena** [comment]
@oleg-nenashev How a user is able to change this static field?

**Comment by recena** [comment]
@oleg-nenashev I'm considering to remove my bee 😄

**Comment by oleg-nenashev** [comment]
@recena Non-final static fields can be easily changed. E.g. by invoking <code>ItemCategory.MIN_TOSHOW = 5</code>

**Comment by recena** [comment]
@oleg-nenashev I don't see the problem in this class. This value is only a default value, as a reference to the developer of `ItemCategory`.

**Comment by oleg-nenashev** [comment]
Just to summarize the problem, public static fields are evil from the API maintenance perspective. Once you introduce and release the field, there is no real way back. For example, you cannot remove this field without a formal binary compatibility breakage in the Jenkins core.

<code>@Restricted</code> at least allows avoiding explicit usages in other plugins.

**Comment by recena** [comment]
@oleg-nenashev I understand what you try to achieve but I hope some day, Jenkins provides a policy to deprecate and remove methods, fields, etc.

**Comment by oleg-nenashev** [comment]
This API deprecation engine originally was in 2.0 scope. I'm not sure if
anybody plans to work on it in short-term. Likely no. But I agree that we
cannot move forward easily without API deprecation

**Comment by oleg-nenashev** [comment]
@recena Are you fine with the explanation?

**Comment by recena** [comment]
@oleg-nenashev Sure.

**Comment by oleg-nenashev** [comment]
@reviewbybees done
Merging it since the author of the original commit is fine with the change

**Pull request merged**
