### PR TITLE
Increase contrast of the disabled plugin uninstall button

### PR DESCRIPTION
**Pull request by benebsiny**
See [JENKINS-63193](https://issues.jenkins-ci.org/browse/JENKINS-63193).

### Proposed changelog entries

* JENKINS-63193, Increase contrast of the disabled plugin uninstall button on the ***/pluginManager/installed*** page

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] (If applicable) Jira issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [X] Appropriate autotests or explanation to why this change has no tests
- [X] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by daniel-beck** [comment]
@benebsiny Thanks for the PR! Could you provide before/after screenshots?

**Comment by benebsiny** [comment]
**Before**
image

**After**
image

**Review by fqueiruga — APPROVED** [review]

**Review by daniel-beck — APPROVED** [review]

**Review by MRamonLeon — APPROVED** [review]

**Comment by MRamonLeon** [comment]
@benebsiny could you please improve the proposed changelog entry to set this PR as ready for merge. It's not clear what is it about, try to give all the context in the sentence to the user reading the release notes.

_Entry 1: Issue, Uninstall plugin button_

For example: _Increase the contrast on the _Uninstall_ button of the Plugin Manager_

Thank you!

**Comment by daniel-beck** [comment]
> could you please improve the proposed changelog entry

@MRamonLeon This PR is labeled `skip-changelog`, so that would be a waste of time.

**Review by StefanSpieker — APPROVED** [review]

**Comment by benebsiny** [comment]
@MRamonLeon I've modified, have a look of it please :)

**Review by res0nance — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Pull request merged**
