### PR TITLE
[JENKINS-69373] Baseline is too long in manage plugins.

### PR DESCRIPTION
**Pull request by frankie139506**
See [JENKINS-69373](https://issues.jenkins.io/browse/JENKINS-69373).

After:
image

### Proposed changelog entries

* Baseline is too long.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] (If applicable) Jira issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [X] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")` if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content-Security-Policy directives (see [documentation on jenkins.io](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7013"></a>

### CODE REVIEW

**Comment by NotMyFault** [comment]
What is the change proposed supposed to address? I see no notable difference to 2.364, nor does the Jira issue outline what's wrong.

**Comment by frankie139506** [comment]
The line is too long compared to other interfaces.
image
I add a css to fix the length of line.
image

**Comment by daniel-beck** [comment]
> What is the change proposed supposed to address? I see no notable difference to 2.364, nor does the Jira issue outline what's wrong.

The separator line (hr?) is too long on the right.

**Comment by NotMyFault** [comment]
> The separator line

Oic. Thanks for the clarification.

> Are there no sane defaults for anything

The default width is fixed at 1800px, which fits for views like `/manage/` but not `/manage/pluginManager/advanced` or others containing elements that don't take up the whole screen space :/

**Comment by daniel-beck** [comment]
> The default width is fixed at 1800px, which fits for views like `/manage/` but not `/manage/pluginManager/advanced` or others containing elements that don't take up the whole screen space :/

So is the real fix to make the other elements wider here?

**Comment by frankie139506** [comment]
> > The default width is fixed at 1800px, which fits for views like `/manage/` but not `/manage/pluginManager/advanced` or others containing elements that don't take up the whole screen space :/
> 
> So is the real fix to make the other elements wider here?

Apologies for my late response, I have made some change, please take a look.

**Comment by frankie139506** [comment]
> > The default width is fixed at 1800px, which fits for views like `/manage/` but not `/manage/pluginManager/advanced` or others containing elements that don't take up the whole screen space :/
> 
> So is the real fix to make the other elements wider here?

Apologize for my late response, I have made some change, please take a look.

**Comment by daniel-beck** [comment]
> Apologize for my late response, I have made some change, please take a look.

Thanks for doing that, but note that I only asked @NotMyFault a question. It's good to be able to see both options though!

**Comment by NotMyFault** [comment]
> So is the real fix to make the other elements wider here?

The input elements use the appropriate width, making the seperator shorter seems fine imo.

However, I'd say that the default seperator width chosen isn't the best, given that 1800px exceed the majority of views, if no per-view scaling is applied.
But this could be changed independently from this PR.

**Comment by frankie139506** [comment]
> > So is the real fix to make the other elements wider here?
> 
> The input elements use the appropriate width, making the seperator shorter seems fine imo.
> 
> However, I'd say that the default seperator width chosen isn't the best, given that 1800px exceed the majority of views, if no per-view scaling is applied. But this could be changed independently from this PR.

So is my original change ok? Or is there something wrong with my changes now?

**Review by timja — APPROVED** [review]
I pushed https://github.com/jenkinsci/jenkins/pull/7013/commits/8b6679ec94fec8fcda410ef4446330a3fe0e4b70 so that there isn't a nested form

**Comment by timja** [comment]
> (I really wonder why so much specific CSS customization is needed all the time for these new UI elements. Are there no sane defaults for anything?)

The page is expected to be wrapped in a form, this is a special page that has multiple forms and the sections were outside of the forms allowing it to go outside the form size.

**Review by NotMyFault — APPROVED** [review]
This PR is now ready for merge. We will merge it after ~24 hours if there is no negative feedback.
Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process.
Thanks!

**Pull request merged**
