### PR TITLE
Plugin manager time machine

### PR DESCRIPTION
**Pull request by tfennelly**
An idea I was experimenting with over xmas break.

Plugin Manager takes plugin "snapshots" and provides a UI to allow rollback.

So it's hoped it helps in those situations where you install a plugin that drags in X other plugins (transitive deps) that cause issues. Same wrt plugin updates.

**Video ....**
[Video](https://youtu.be/bX2Mvpo3IPc)

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@tfennelly The idea looks great to me. If we merge it into the core, do you commit to maintain it and handle the regressions if they happen? I want to avoid unfortunate cases like Build Widget regressions. If you cannot commit to maintain the change, I suggest doing it in a plugin

**Comment by tfennelly** [comment]
@oleg-nenashev ouch ... there was a dig there Oleg 😸 

I can say yes to that but would you believe me? I wasn't aware of it as a policy. I'm not saying it does not make sense, but I think it also suggests that certain people "own" certain parts of the code, which I think is wrong and a bad idea. E.g. I was not ware that I owned Build Widget (you seem to be suggesting that I do).

**Comment by oleg-nenashev** [comment]
> I can say yes to that but would you believe me?

Sure, I would

> I was not aware that I owned Build Widget (you seem to be suggesting that I do).

You are not. But the pagination change there introduced some regressions, and we had difficulties reaching out to you in JIRA (and then you unassigned the issue from yourself). Since we have NO regular core contributors actively working on UI changes, I find it pretty risky if we have a regression which we cannot fix easily.

For the record, I feel it is a very useful change

**Comment by tfennelly** [comment]
> and then you unassigned the issue from yourself

Well sorry, I shouldn't have done that. I totally admit that getting me via JIRA notifications can be troublesome. If I do that, kick me.

**Comment by oleg-nenashev** [comment]
OK, will make sure to ping you. Actually it would be helpful in the case of JEP-200 upgrades as well

Tests fail, because Jenkins rejects to serialize `hudson.util.VersionNumber`. Will create a PR for that

**Comment by jglick** [comment]
An interesting feature to be sure but it seems to be overlapping with `jobConfigHistory`, `thinBackup`, [JEP-201](https://github.com/jenkinsci/jep/blob/master/jep/201/README.adoc), etc. Do we really want to maintain a GUI for snapshotting and restoring just plugin versions (beyond the simplistic rollback function already in core), when we know there is other stuff that would really belong in such a snapshot (and downgrading a plugin can easily result in problems with settings)?

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
JEP-200 thing needs to be fixed

**Comment by tfennelly** [comment]
@oleg-nenashev @jglick Sorry guys, I'm not seeing how JEP-200 and JEP-201 are related to, or blocked by, this.

As far as plugin rollbacks being dangerous (because of job/other config changes that are not compatible with the rollback), I'm not sure I see how this makes things any worse than they are today in that regard i.e. you can uninstall plugins today and mess things up just the same.

**Comment by oleg-nenashev** [comment]
@tfennelly The newly introduced tests fail due to JEP-200, that's what I meant

**Comment by oleg-nenashev** [comment]
@tfennelly any plans to work on it and to get it over the fence?

**Comment by kwhetstone** [comment]
@oleg-nenashev this is something I can fix if we're ok with it going into core.

**Comment by oleg-nenashev** [comment]
@kwhetstone I would not block that from being merged into the core if somebody commits to maintain after the merge.

**Comment by tfennelly** [comment]
@oleg-nenashev I did this as an experiment because it ( not being able to rollback after dodgy plugin installs ) had been a big issue for us on DevOptics. We're now working around that so it's not so big an issue. I don't have the bandwidth to maintain it but @kwhetstone and Vignesh both expressed interest in it. If they are not interested then let's close this PR.

**Pull request closed without merging**
