### PR TITLE
[JENKINS-36441] - Provide a bundling mechanism for plugins being unbundled from the core

### PR DESCRIPTION
**Pull request by oleg-nenashev**
This PR should allow to safely unbundle particular Jenkins core functionality to a plugin and then reference this unbundled plugin from Jenkins WAR (dependency + System Property definition). Otherwise there is no way to safely unbundle something without a new major Jenkins version.
- [x] Support copying of bundled plugins from WAR into Jenkins instance. The engine honors .disabled flags and previous plugin versions (they won't be overriden by default => user can upgrade plugins)
- [x] Allow specifying required and enforced plugin dependencies for plugins bundled into the WAR file
- [x] Allow altering the behavior of PluginManager for bundled, but not required plugins
- [ ] Write tests
- [ ] Provide example (Bouncy castle API plugin?)

https://issues.jenkins-ci.org/browse/JENKINS-36441

@reviewbybees @alobato @andresrc

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@jglick See https://issues.jenkins-ci.org/browse/JENKINS-36441 (ongoing discussion about the feature feasibility)

**Comment by daniel-beck** [comment]
Superseded by #2489?

**Comment by oleg-nenashev** [comment]
Not superseded, but there is some overlap. If #2489 gets merged, this guy will need some adjustment

**Comment by oleg-nenashev** [comment]
As I said in the ticket, I'll follow-up on this PR after my vacation

**Comment by oleg-nenashev** [comment]
I do not longer work on it

**Comment by oleg-nenashev** [comment]
Reopening for further discussion, because there is a use-case for it in `runATH()` / `essentialsTest()`: https://issues.jenkins-ci.org/browse/JENKINS-51306

CC @raul-arabaolaza

**Comment by daniel-beck** [comment]
@oleg-nenashev Did you intend to reopen this?

**Comment by daniel-beck** [comment]
@oleg-nenashev OK, so I did that now. GitHub identified merge conflicts.

**Comment by daniel-beck** [comment]
Closing based on [Jira comment](https://issues.jenkins-ci.org/browse/JENKINS-36441?focusedCommentId=302632&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-302632)

**Pull request closed without merging**
