### PR TITLE
Remove meaningless @since

### PR DESCRIPTION
**Pull request by timja**
See https://github.com/jenkinsci/jenkins/pull/5573#discussion_r651195833

### CODE REVIEW

**Review by basil — COMMENTED** [review]
Suggest adding

```java
@RestrictedSince("TODO")
```

per Daniel's recommendation in a different PR of mine.

**Review by jglick — APPROVED** [review]

**Comment by timja** [comment]
> ```java
> @RestrictedSince("TODO")
> ```

That's only for classes that were public and then restricted

**Review by basil — APPROVED** [review]
Got it. One of these days I'll eventually understand all of these complex and unwritten rules. :-)

**Review by MarkEWaite — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Pull request merged**
