### PR TITLE
pt_BR translation

### PR DESCRIPTION
**Pull request by boaglio**

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
:+1: for merge (even if I don't know the language)

**Comment by KostyaSha** [comment]
We can call for Brazilian people in twitter.

**Comment by daniel-beck** [comment]
@kinow Could you review this?

**Comment by kinow** [comment]
Sure thing @daniel-beck

**Comment by kinow** [comment]
+1 to merge as well

`FullControlOnceLoggedInAuthorizationStrategy.DisplayName` and `AuthorizationStrategy.DisplayName`  had the opposite meaning in Portuguese before. 

Nice catch and kudos for fixing that @boaglio.

**Comment by oleg-nenashev** [comment]
@boaglio 
Thanks for the contribution!

**Comment by boaglio** [comment]
:thumbsup:   :grin:

**Pull request merged**
