### PR TITLE
Replace naming of the term "master" in German translations

### PR DESCRIPTION
**Pull request by uhafner**
Now the non-offending name "Controller" is used everywhere.

See https://github.com/jenkinsci/jep/blob/8f645ce99a9891148cb2398de7c8cfc4d8f645af/jep/16/README.adoc

### Desired reviewers

@daniel-beck @NotMyFault 

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Review by gounthar — APPROVED** [review]

**Review by daniel-beck — CHANGES_REQUESTED** [review]
Most changed terms in `core/src/main/resources/hudson/model/Messages_de.properties` should instead refer to the built-in node for which there is no German term yet according to the JEP.

**Comment by uhafner** [comment]
> Most changed terms in `core/src/main/resources/hudson/model/Messages_de.properties` should instead refer to the built-in node for which there is no German term yet according to the JEP.

Can you please elaborate what you are proposing? I replaced "Master" with "Controller" which I think is a common word for this kind of "thing". Or do we need to make more explicit that we have a controller that might play the role of an agent? This sounds for me too pedantic.

**Comment by daniel-beck** [comment]
> Or do we need to make more explicit that we have a controller that might play the role of an agent? This sounds for me too pedantic.

This is how it's been for several years now in the default locale and how it's specified in the JEP.

**Comment by uhafner** [comment]
Ok, then lets wait for someone finding a proper German name in the JEP.

**Pull request closed without merging**
