### PR TITLE
JENKINS-50361 Return buildId when a job been triggered.

### PR DESCRIPTION
**Pull request by LinuxSuRen**
Details in https://issues.jenkins-ci.org/browse/JENKINS-50361

### CODE REVIEW

**Review by daniel-beck — CHANGES_REQUESTED** [review]
I explain in [this comment to JENKINS-12827](https://issues.jenkins-ci.org/browse/JENKINS-12827?focusedCommentId=201381&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-201381) why this is a bad idea that can be wrong quite often depending on your setup (and provide a solution that's more complex but always correct).

And the comment afterwards points to a bug that only exists because a plugin tried to guess like this, and got it wrong.

**Comment by LinuxSuRen** [comment]
Have any extension point could let me update the http header before it's done?

**Comment by daniel-beck** [comment]
> So, do you have any suggestion? Can I write a plugin to resolve my problem? I just don't want call many times with Jenkins api.

The build ID will only be assigned when the build is started, not when it's put into the queue, and the queue is not strictly in order, so there cannot be a sane way to tell you the build ID before that has happened

**Comment by LinuxSuRen** [comment]
So, what about a callback url? If I put a callback http request into it, when then build has started. I don't whether Jenkins has the extension point.

**Comment by daniel-beck** [comment]
That might work, but will require quite a bit of review and testing to ensure it's not subtly broken.

**Pull request closed without merging**
