### PR TITLE
Stop spamming logs when retrieving AdminWhitelistRule

### PR DESCRIPTION
**Pull request by timja**
see https://github.com/jenkinsci/jenkins/pull/5885#issuecomment-1000271888

Just clicking 'View configuration' with JCasc plugin installed logs a huge stacktrace, there's no way for a user to avoid it, you don't even need to have any config defined

I tried deprecating the getter and setter but it didn't work. Here's a quick patch to see if it's acceptable 😄 

### Proposed changelog entries

* Entry 1: Issue, Human-readable Text
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by daniel-beck** [comment]
Would moving the stack trace into FINE and having a WARNING (or INFO) without (+ hint to increase logging level) be a reasonable compromise?

**Comment by timja** [comment]
> > logs a huge stacktrace
> 
> Would moving the stack trace into FINE and having a WARNING (or INFO) without (+ hint to increase logging level) be a reasonable compromise?

Yeah that would be fine

**Review by jglick — APPROVED** [review]
I do not see much point in the runtime logging here; Java deprecation should suffice.

**Review by oleg-nenashev — APPROVED** [review]
Agreed. It is not really actionable for users

We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Comment by oleg-nenashev** [comment]
@timja should it be considered a UX bug and hence backported?

**Comment by timja** [comment]
> @timja should it be considered a UX bug and hence backported?

probably not worth it, as long as it makes it into the next baseline

**Comment by daniel-beck** [comment]
> Agreed. It is not really actionable for users

It is when called from init.groovy scripts.

**Pull request merged**
