### PR TITLE
[JENKINS-65607] empty StringParameters should be treated as null

### PR DESCRIPTION
**Pull request by jtnord**
https://github.com/jenkinsci/jenkins/pull/5275 changed the meaning of
blank (empty) string parameters to be "" rather than null which causes
them to be injected into pipelines etc rather than not be present, which
causes regressions in several tests.

See [JENKINS-65607](https://issues.jenkins-ci.org/browse/JENKINS-65607).

### Proposed changelog entries

* Entry 1: JENKINS-65607, Fix regression with empty string parameters being injected into pipelines

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by res0nance — APPROVED** [review]

**Review by timja — APPROVED** [review]

**Review by jglick — CHANGES_REQUESTED** [review]
This change was intentional. Are you aware of any actual problem other than test failures, which are already being dealt with (and which would probably be made worse by flipping the behavior again)?

**Comment by jglick** [comment]
> I can see this causing some issue in people builds where they are checking if something is present or not

I doubt this would have actually happened, because prior to my change, at least any GUI configuration of the project would save `""` as the `defaultValue`. So the point of translating `null` to `""` in the `StringParameterValue` was to _counteract_ the effect of now storing `null` rather than `""` in the `StringParameterDefinition`. It is hard to be sure what behaviors people may have relied upon in more scripted scenarios of course (both `null` and `""` were previous tolerated internally), but I am not aware of complaints except functional tests and from some code in `maven-plugin` which I already patched. I recall going through some interactive scenarios with Jenkins with and without my patch and not seeing any behavioral difference in this regard. (There _was_ a surprising behavior involving Declarative Pipeline but this was true before my patch as well.)

**Comment by res0nance** [comment]
We should just decide what the right behaviour should be.

> Another couple things I remembered: GUI uses of `buildWithParameters` would also bind only `""` and never `null`. And typical shell scripts would not notice the difference, unless you took care to `set -u` and so on. So it seemed least confusing to make the behavior consistent in all cases with what had hitherto been the normal case: binding `""`.

Do we know what the behaviour is on Windows?

**Review by MRamonLeon — APPROVED** [review]
The former behavior seems more accurate to our documentation to me.

**Review by jglick — CHANGES_REQUESTED** [review]
No change in my opinion, for reasons explained above. Converting `""` to `null` here would effectively change the behavior for most projects compared to Jenkins 2.280-, and likely for the worse (subtle difference in behavior depending on exactly how you configured & built the project).

**Pull request closed without merging**
