### PR TITLE
Link from cloud configuration to pre-filtered plugin manager

### PR DESCRIPTION
**Pull request by daniel-beck**
Make use of https://github.com/jenkinsci/jenkins/pull/4591 in the UI added by https://github.com/jenkinsci/jenkins/pull/4339.

Screenshot English:

> Screenshot 2020-04-19 at 14 43 09

Screenshot Bulgarian:

> Screenshot 2020-04-19 at 14 42 31

### Proposed changelog entries

(too minor)

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [n/a] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [n/a] Appropriate autotests or explanation to why this change has no tests
- [n/a] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by sladyn98** [comment]
This would then allow users to directly check the cloud configuration in the plugin manager right ?

**Comment by daniel-beck** [comment]
> This would then allow users to directly check the cloud configuration in the plugin manager right ?

Yes, as shown it will display plugins with the `cloud` label. The link is shown on `/configureClouds` if there is no plugin installed that does it. Combined with #4633 you get a reasonable flow (perhaps circuitous, but no dead ends) from fresh install to list of plugins implementing cloud agents.

**Review by res0nance — APPROVED** [review]

**Review by fqueiruga — APPROVED** [review]

**Review by timja — APPROVED** [review]
There's a number of plugins missing in the topic from here, would be good to label them appropriately, in case you're feeling up to it @daniel-beck the list is here:
https://jenkins.io/doc/developer/extensions/jenkins-core/#cloud

**Comment by timja** [comment]
Let's ship in 24 hours if no negative feedback

**Comment by daniel-beck** [comment]
@timja This is maintainers' responsibility.

**Pull request merged**
