### PR TITLE
Upgrade to 3.28 version of Remoting.

### PR DESCRIPTION
**Pull request by jeffret-b**
Upgrade to the 3.28 version of Remoting, which contains a number of minor fixes particularly involving log messages and enhancements to the NO_PROXY environment variable options.

See the [Remoting Changelog](https://github.com/jenkinsci/remoting/blob/master/CHANGELOG.md#328) for the full set of changes included in this dependency update.

### Proposed changelog entries

* Update Remoting from 3.27 to 3.28 to fix some minor issues and enhance NO_PROXY options. (<a href="https://github.com/jenkinsci/remoting/blob/master/CHANGELOG.md#328">Full changelog</a>, <a href="https://issues.jenkins-ci.org/browse/JENKINS-47977">issue 47977</a>, <a href="https://issues.jenkins-ci.org/browse/JENKINS-48778">issue 48778</a>, <a href="https://issues.jenkins-ci.org/browse/JENKINS-49987">issue 49987</a>, <a href="https://issues.jenkins-ci.org/browse/JENKINS-50730">issue 50730</a>, <a href="https://issues.jenkins-ci.org/browse/JENKINS-51108">issue 51108</a>, <a href="https://issues.jenkins-ci.org/browse/JENKINS-54005">issue 54005</a>)

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
      * Tests are included in the changes within the Remoting library, wherever they are meaningful.
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@reviewbybees @jvz

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]

**Review by jvz — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Swarm Plugin has been updated to Remoting 3.28, the agent side looks good according to the tests

**Review by batmat — APPROVED** [review]
LGTM

**Comment by oleg-nenashev** [comment]
Ready to merge IMHO. let's land it into the next weekly if there is no negative feedback

**Comment by jeffret-b** [comment]
I'll plan to merge this in sometime Thursday unless any concerns are raised.

**Pull request merged**
