### PR TITLE
Another random failure

### PR DESCRIPTION
**Pull request by jglick**
[Here](https://ci.jenkins-ci.org/job/jenkins_main_trunk/4349/testReport/junit/hudson.slaves/CommandLauncherTest/commandFails/) for example.

@reviewbybees

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
:bee:

**Comment by kzantow** [comment]
:bee:

**Comment by amuniz** [comment]
:bee: although I don't like this annotation at all and I think we should avoid its use if possible.

**Comment by jglick** [comment]
Well if we know how to fix the test, obviously we will fix the test. This is an escape hatch for the cases where we do not know that.

Better is to set `surefire.rerunFailingTestsCount` on the project, as `workflow-plugin` does. For now I am just trying to deal with a test which is harassing unrelated PRs.

**Pull request merged**
