### PR TITLE
[JENKINS-68805] Demonstrate that IconSet doesn't reset attributes with ampersand

### PR DESCRIPTION
**Pull request by Kevin-CB**
See [JENKINS-68805](https://issues.jenkins.io/browse/JENKINS-68805).

While implementing tests for [SECURITY-2781](https://www.jenkins.io/security/advisory/2022-06-22/#SECURITY-2781), I noticed that the test [getSymbol_notSettingTooltipDoesntAddTooltipAttribute()](https://github.com/jenkinsci-cert/jenkins/blob/04887f08ce06eaae75ef21b6dfd008e38e865d9c/core/src/test/java/org/jenkins/ui/icon/IconSetTest.java#L59) was failing if I created a symbol with an XSS payload before it runs.

And discovered that [icon/IconSet.java#L93)](https://github.com/jenkinsci-cert/jenkins/blob/04887f08ce06eaae75ef21b6dfd008e38e865d9c/core/src/main/java/org/jenkins/ui/icon/IconSet.java#L93) will not remove the tooltip of a symbol already created with the same name if it contains an ampersand symbol (&).

### Proposed changelog entries

* Entry 1: Issue, Human-readable Text
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/6685"></a>

### CODE REVIEW

**Comment by daniel-beck** [comment]
Looks like we don't have labels for PRs not intended for merging, so labeling "on-hold".

**Review by basil — APPROVED** [review]
I moved this test to the main `IconSet` test class and added an `@Disabled` annotation to reflect the fact that the test is failing due to JENKINS-68805 not yet being fixed. When JENKINS-68805 is fixed, the `@Disabled` annotation can be removed.

**Review by timja — APPROVED** [review]

**Comment by basil** [comment]
This PR is now ready for merge. We will merge it after approximately 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process. Thanks!

**Comment by basil** [comment]
Whoops, sorry about that.

**Pull request merged**
