### PR TITLE
Changing helptext fontsize to small

### PR DESCRIPTION
**Pull request by Vishalghyv**
See [JENKINS-62066](https://issues.jenkins-ci.org/browse/JENKINS-62066).

### Proposed changelog entries

* Entry 1: Issue, Human-readable Text
* Changed the size of help text in job config forms to 14 px or 0.875rem.
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by fqueiruga** [comment]
Can we have a screenshot of before and after? Or at least an after

**Review by oleg-nenashev — APPROVED** [review]
`.alert` also uses this style, should be OK

**Comment by Vishalghyv** [comment]
Sorry for the delay, Something has come up, I will update this with images of before and after soon, Probably in one or two days

**Comment by Vishalghyv** [comment]
Before
Screenshot (424)
After
Screenshot (425)

**Review by fqueiruga — APPROVED** [review]

**Comment by Vishalghyv** [comment]
Mostly but the change that I noticed was in `from Credentials...` after the change it also used font size sm
And the whole help text was using font size sm from higher elements i.e html and now used it's own

**Comment by daniel-beck** [comment]
For the element shown in the screenshot:

Before:

> Screenshot 2021-01-14 at 23 20 59

After:

> Screenshot 2021-01-14 at 23 20 56

This change seems to be pointless…?

**Review by daniel-beck — CHANGES_REQUESTED** [review]
No problem with the code, but this PR needs to demonstrate it actually does something.

**Comment by Vishalghyv** [comment]
Right, I will look into it more if there is anywhere change is requried, If not I will close the PR

**Comment by Vishalghyv** [comment]
I was not able to find examples where the changes worked, And it seems that the issue is fixed because all the help text have the same font size i.e. font size sm

**Comment by fqueiruga** [comment]
Thank you for looking into it!

**Pull request closed without merging**
