### PR TITLE
Create README_JPN.md

### PR DESCRIPTION
**Pull request by WillCoHill**
Translation of the README.md file into Japanese

Comment: Translating for access for the Japanese speaking community

### Testing done

Testing done: manually translated md file and verified in .md preview feature on Visual Studio Code. 

### Proposed changelog entries

- human-readable text

 Add README_INT for international README.md files
--> Add README_JPN.md inside the root\README_INT folder

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [ ] The Jira issue, if it exists, is well-described.
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [x] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Comment by WillCoHill** [comment]
To a Japanese audience.
もしミスタイプがあったらよろしければご訂正していただけないでしょうか
どうしても、ご添削お願いいたします！

**Comment by daniel-beck** [comment]
Between the problems we'll have keeping the two documents aligned (and ending up with outdated/conflicting information, for what little there is), and this readme mostly being links elsewhere (and elsewhere being in English), what is the benefit of having this?

It seems that those in the audience who don't understand English would be better served by automatic translation tools.

FWIW we used to have a version of jenkins.io in Chinese, unfortunately that effort stalled, and ended up having to be scrapped.

**Review by NotMyFault — CHANGES_REQUESTED** [review]
This is not needed, commonly, a single README is more than enough.
People who don't speak english, commonly use a translator, instead of maintaining a multitude of different READMEs.

**Comment by MarkEWaite** [comment]
@WillCoHill I agree with @daniel-beck and @NotMyFault that a Japanese language translation of the README is not enough benefit to maintain it.

There are many internationalized messages in Jenkins that would benefit from a Japanese translation.  Are you interested in helping with further Japanese language translations that will help Japanese users directly?

**Comment by MarkEWaite** [comment]
Closing after no response from the submitter.  We'd love to have additional Japanese language translations of the Jenkins messages.  That will help Japanese speaking users.

**Comment by WillCoHill** [comment]
That's a shame. Thank you for your time. I'll try my best to help with any possible future efforts to add Japanese language support

**Pull request closed without merging**
