### PR TITLE
i18n: update the Italian translation

### PR DESCRIPTION
**Pull request by AlessandroMenti**
This PR updates the Italian translation for the Jenkins core.

No additional tests are required as there is no code change.

**Additional remark**: I have redone the translation from scratch to ensure consistency and added a standard MIT license header with me as the copyright holder; if this should be changed, please leave me a remark and I'll be happy to do so.

### Proposed changelog entries

* Update Italian localization.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] ~(If applicable) Jira issue is well described~
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [X] Appropriate autotests or explanation to why this change has no tests
- [ ] ~For dependency updates: links to external changelogs and, if possible, full diffs~

### Desired reviewers

@daniel-beck, @oleg-nenashev

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [x] There are at least 2 approvals for the pull request and no outstanding requests for change
- [x] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [x] Proper changelog labels are set so that the changelog can be generated automatically
- [x] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [x] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
CC @MarkEWaite who could help with a review

**Review by MarkEWaite — APPROVED** [review]
I tested various operations in Italian on Google Chrome with this translation update.  I found no issues.  The translated characters rendered correctly and the pages behaved as expected.

I was a little surprised at the change made two years ago to define "Freestyle project" as "Progetto libero" when the 2011 translation had rendered it as "tipo generico".  However, I'm a native English speaker with only two years of non-technical Italian experience.  My judgment on correct phrasing for the Italian users of Jenkins is not particularly trustworthy.  I'm accustomed to thinking of the word "libero" as meaning "free" rather than "freestyle".  However, the [visual dictionary](https://languagedrops.com/word/en/english/italian/translate/freestyle_stroke/) translates "freestyle stroke" (as in swimming) as "lo stile libero".  That provides at least one source that translates "freestyle" as "libero" (or at least as "stile libero").  

In any  case, the change from "tipo generico" to "libero" was made in 2017 and has generated no bug reports from native Italian users.

I recommend that we merge this in 24 hours.  We could wait for a second approval on the pull request, but I don't expect approvals from others to be any more detailed than the testing already performed by @AlessandroMenti .  More likely, they would perform the type of "smoke testing" that I performed.

**Review by oleg-nenashev — APPROVED** [review]
I agree with merging.
@AlessandroMenti Would it be possible to add the "The MIT License" text to the beginning of all license texts?

**Comment by AlessandroMenti** [comment]
> @AlessandroMenti Would it be possible to add the "The MIT License" text to the beginning of all license texts?

Done!

I have also rebased the branch against the latest `master` and changed the following strings which were introduced/edited in the meantime:

```diff
diff --git a/core/src/main/resources/hudson/logging/LogRecorderManager/feeds_it.properties b/core/src/main/resources/hudson/logging/LogRecorderManager/feeds_it.properties
index d3f1ee1b26..81450aef22 100644
--- a/core/src/main/resources/hudson/logging/LogRecorderManager/feeds_it.properties
+++ b/core/src/main/resources/hudson/logging/LogRecorderManager/feeds_it.properties
@@ -19,6 +19,6 @@
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 # THE SOFTWARE.
 
->\ SEVERE=> TUTTO
->\ WARNING=> AVVERTENZA
+>\ SEVERE=TUTTO
+>\ WARNING=AVVERTENZA
 All=Tutti i livelli
diff --git a/core/src/main/resources/hudson/model/Messages_it.properties b/core/src/main/resources/hudson/model/Messages_it.properties
index e30042fa4c..0287f5378e 100644
--- a/core/src/main/resources/hudson/model/Messages_it.properties
+++ b/core/src/main/resources/hudson/model/Messages_it.properties
@@ -426,6 +426,7 @@ UpdateCenter.PluginCategory.scm-related=Componenti legati alla gestione del \
 UpdateCenter.PluginCategory.security=Sicurezza
 UpdateCenter.PluginCategory.slaves=Avvio e controllo agenti
 UpdateCenter.PluginCategory.test=Test
+UpdateCenter.PluginCategory.theme=Temi interfaccia utente
 UpdateCenter.PluginCategory.trigger=Trigger compilazione
 UpdateCenter.PluginCategory.ui=Interfaccia utente
 UpdateCenter.PluginCategory.unrecognized=Varie ({0})
```

**Comment by timja** [comment]
Hey 👋 there's one conflict would you mind resolving it, then we'll merge ASAP.
(Would do it myself but not confident on it).

**Comment by AlessandroMenti** [comment]
@timja Done (the conflict occurred as, apparently, another commit changed some translation labels as well as a few translations themselves in `core/src/main/resources/hudson/model/Messages_it.properties` - I have fixed this now).

**Pull request merged**
