### PR TITLE
[JENKINS-68390] Fixed build number cutoff in build history widget

### PR DESCRIPTION
**Pull request by Hildebrand-Ritense**
See https://issues.jenkins.io/browse/JENKINS-68390

Fixed build number cutoff in build history widget by increasing the available space for listing the build number.
Gave the build-row cell build name pane 5% more space, taking it from the build-controls pane.

Before:
cut-off-build-numbers

After:
cut-off-build-numbers-fixed

### Proposed changelog entries

* Fix build number cutoff in build history widget.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@jenkins-ci/sig-ux

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/6692"></a>

### CODE REVIEW

**Comment by Hildebrand-Ritense** [comment]
Apologies, I only just now see #6562 and its complexities. Feel free to close this one I guess.
Only thing I'd like to add is that, regardless the possibilities for complex cases as mentioned in #6562, it would be nice if a base install of Jenkins would have this fixed, that might make this PR relevant.

**Comment by basil** [comment]
> Apologies, I only just now see #6562 and its complexities.

Having seen #6562 and its complexities, you are aware of the testing requirements for a change like this.

> Feel free to close this one I guess.

There would only be a reason to close it if you are unable or unwilling to perform the proper testing as in https://github.com/jenkinsci/jenkins/pull/6562#issuecomment-1133778390.

**Comment by basil** [comment]
@Hildebrand-Ritense Are you interested in doing the testing or not?

**Comment by daniel-beck** [comment]
Looks promising so far in limited testing.

> Screenshot 2022-06-28 at 21 17 43

**Comment by Hildebrand-Ritense** [comment]
@basil I'd love to, but I'm not so familiar with the additional build icons, descriptions and so on so I'd really have to invest time to get to know that part of Jenkins and how to set up a number of relevant test cases, spare time that I currently don't have.

**Comment by basil** [comment]
Understood. @daniel-beck do you think this is good enough as-is, or should we close the PR as the author doesn't have the spare time.

**Review by NotMyFault — APPROVED** [review]
Looks fine so far, though more reviews are appreciated.

**Review by daniel-beck — APPROVED** [review]
Looks reasonable in testing and a definitive improvement over the current situation.

**Comment by timja** [comment]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Pull request merged**
