### PR TITLE
Only inspect direct subdirectories for Surefire reports

### PR DESCRIPTION
**Pull request by jglick**
#3165 is not the first to get weird errors like [this](https://ci.jenkins.io/job/Core/job/jenkins/job/PR-3165/1/testReport/junit/org.jvnet.hudson.test/BuildTriggerTest/Windows___Windows_Publishing___testSomething/):

```
junit.framework.AssertionFailedError: test failure
	at junit.framework.Assert.fail(Assert.java:47)
	at org.jvnet.hudson.test.BuildTriggerTest.testSomething(BuildTriggerTest.java:7)
```

This is not an actual test of Jenkins; it is coming from `test/src/test/resources/hudson/tasks/maven-test-failure.zip!/src/test/java/org/jvnet/hudson/test/BuildTriggerTest.java`, which is used by the real `test/src/test/java/hudson/tasks/BuildTriggerTest.java`. Presumably under some conditions (Windows file locks?) the `jenkins-test-harness` fails to properly clean up temporary directories, and then an overzealous `Jenkinsfile` found this report file and thought it indicated a (non-meta) test failure.

@reviewbybees

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
LGTM 🐝

**Comment by jglick** [comment]
From [here](https://ci.jenkins.io/job/Core/job/jenkins/job/master/642/testReport/) to [here](https://ci.jenkins.io/job/Core/job/jenkins/job/PR-3168/1/testReport/) we lose 38 tests, so I am digging into what those were. Unfortunately lack of REST API access makes this a bit manual.

**Comment by jglick** [comment]
There we go, [PR](https://ci.jenkins.io/job/Core/job/jenkins/job/PR-3168/2/testReport/) and [trunk](https://ci.jenkins.io/job/Core/job/jenkins/job/master/644/testReport/) both running 25,654 tests.

**Comment by jglick** [comment]
@reviewbybees done

**Review by batmat — APPROVED** [review]

**Comment by jglick** [comment]
Evidently did not work. Wish I knew how to reproduce this.

**Comment by jglick** [comment]
@daniel-beck says that is because of PRs filed prior to that time, so no worries.

**Pull request merged**
