### PR TITLE
Allow all updates from Dependabot

### PR DESCRIPTION
**Pull request by batmat**
The goal is to see what we get after we merge this, then we add some things into `ignore` as needed. 

https://groups.google.com/g/jenkinsci-dev/c/XMllKuWLO_8/m/jU6CEhiUAAAJ

No Jira, fully dev/internal/build change.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

(Asked them for review)

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by timja — APPROVED** [review]
FTR I did an experiment recently on this and it seemed fine I just hadn't got around to proposing it,

Here's some sample PRs:
https://github.com/timja/jenkins/pulls?q=is%3Apr+sort%3Aupdated-desc+label%3Adependencies+

**Review by res0nance — APPROVED** [review]
I think this is a good experiment to try

**Review by oleg-nenashev — APPROVED** [review]
Fine with me. The list is short enough to be manageable.

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Review by markjacksonfishing — APPROVED** [review]

**Review by amuniz — APPROVED** [review]

**Review by jglick — APPROVED** [review]
Offhand I know Guava and Groovy will need to be excluded.

**Pull request merged**
