### PR TITLE
`TransientActionFactory` cache simplification

### PR DESCRIPTION
**Pull request by jglick**
Amending #2582 as proposed in https://github.com/jenkinsci/jenkins/pull/7932#discussion_r1185766275. New implementation is (IMO) simpler and avoids Guava.

### Testing done

Just ran `TransientActionFactoryTest`.

### Proposed changelog entries

- N/A

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/8048"></a>

### CODE REVIEW

**Review by Vlatombe — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]
/label ready-for-merge

---

This PR is now ready for merge. We will merge it after ~24 hours if there is no negative feedback.
Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process.
Thanks!

**Comment by basil** [comment]
Causes failures in (at least) `hudson.plugins.emailext.plugins.recipients.FailingTestSuspectsRecipientProviderTest`, `hudson.plugins.jacococoveragecolumn.AbstractJaCoCoCoverageColumnTest`, `hudson.plugins.jacococoveragecolumn.BranchCoverageColumnTest`, `hudson.plugins.jacococoveragecolumn.JaCoCoColumnTest`, and `jenkins.scm.api.SCMRevisionActionTest` of the following form:

```
INFO: Expected 1 instance of jenkins.model.TransientActionFactory$Cache but got 0
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.454 s <<< FAILURE! - in hudson.plugins.emailext.plugins.recipients.FailingTestSuspectsRecipientProviderTest
[ERROR] hudson.plugins.emailext.plugins.recipients.FailingTestSuspectsRecipientProviderTest.testAddRecipients  Time elapsed: 1.446 s  <<< ERROR!
java.lang.IllegalStateException: Expected 1 instance of jenkins.model.TransientActionFactory$Cache but got 0
        at hudson.ExtensionList.lookupSingleton(ExtensionList.java:454)
        at jenkins.model.TransientActionFactory.factoriesFor(TransientActionFactory.java:127)
        at hudson.model.Actionable.getAction(Actionable.java:331)
        at hudson.model.Actionable.getAction(Actionable.java:325)
        at hudson.plugins.emailext.plugins.recipients.FailingTestSuspectsRecipientProvider.addRecipients(FailingTestSuspectsRecipientProvider.java:83)
        at hudson.plugins.emailext.plugins.recipients.TestUtilities.checkRecipients(TestUtilities.java:60)
        at hudson.plugins.emailext.plugins.recipients.FailingTestSuspectsRecipientProviderTest.testAddRecipients(FailingTestSuspectsRecipientProviderTest.java:121)
```

The failures all go away when this change is reverted. The failures all look like more cases of commit 1089a22186e924c90738a669260509e5bc4c8074 (i.e., mocks). The tests could be adapted in the same way, or `TransientActionFactory#factoriesFor` loosened to support running in mock context along the lines of e.g.

```java
return ExtensionList.lookup(Cache.class).stream()
        .findFirst()
        .map(Cache::cache)
        .map(classValue -> classValue.get(type))
        .map(classValue -> classValue.get(actionType))
        .orElse(List.of());
```

**Comment by jglick** [comment]
More transparent to fix the mock tests I think. Will propose some corrections soon if no one beats me to it.

**Comment by basil** [comment]
As a courtesy I have released [Email Extension 2.99](https://github.com/jenkinsci/email-ext-plugin/releases/tag/email-ext-2.99).

**Pull request merged**
