### PR TITLE
[FIXED JENKINS-33412] Use Winstone-Jetty 3

### PR DESCRIPTION
**Pull request by daniel-beck**
https://issues.jenkins-ci.org/browse/JENKINS-33412
Also brought up on a mailing list.

Let's see what the PR builds says about this…

### CODE REVIEW

**Comment by daniel-beck** [comment]
Test failure is not real.

**Comment by daniel-beck** [comment]
@olivergondza The bot picks up `FIX` as well, and it's two chars shorter :smile:

**Comment by olivergondza** [comment]
Good to know.

**Comment by daniel-beck** [comment]
End of 1.x line.

**Pull request closed without merging**
