### PR TITLE
Add SortPom to build

### PR DESCRIPTION
**Pull request by basil**
Adds [SortPom](https://github.com/Ekryd/sortpom) to our Spotless configuration to automatically keep our POM files consistently indented and sorted according to the [POM Code Convention](https://maven.apache.org/developers/conventions/code.html#pom-code-convention) that was [voted on by Maven developers in 2008](https://lists.apache.org/thread/h8px5t6f3q59cnkzpj1t02wsoynr3ygk).

### Proposed changelog entries

N/A

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by oleg-nenashev — COMMENTED** [review]
I am +0. While I see some value in keeping the POM formatting standard, enforcing it may complicate contributions. More reviews are needed, I abstain

**Review by timja — APPROVED** [review]
it's automated so 🤷

**Comment by bguerin** [comment]
I am using it for years on all my professional and personal project, it is so magical, it saves time. It has two goals : one to check if POM is well formatted or not (and if not, it will fail the build) and another to do the formatting (thus changing POM content maybe)

You add bits in the POM not worrying about the indent, spaces vs tabs, ..., then compile, it fails => `mvn sortpom:sort` and go on. No much more headache.

**Comment by daniel-beck** [comment]
> You add bits in the POM not worrying about the indent, spaces vs tabs, ..., then compile, it fails => `mvn sortpom:sort` and go on. No much more headache.

Is this obvious from the failure, i.e. friendly to casual contributors who may see this for the first time? I think spotless suggests `spotless:apply`, is there something similar here?

**Comment by timja** [comment]
Spotless is using it so it will be the same clear error message

**Comment by bguerin** [comment]
@daniel-beck 
Verification which fail the build:
```
$ mvn sortpom:verify -Dsort.verifyFail=stop
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< aProject >--------------------
[INFO] Building aProject1.0.0-SNAPSHOT
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- sortpom-maven-plugin:3.0.0:verify (default-cli) @ aProject ---
[INFO] Verifying file /aProject/pom.xml
[ERROR] The xml element <groupId> should be placed before <properties>
[ERROR] The file /aProject/pom.xml is not sorted
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```
Verification which auto format (by default, caution, would require to update SCM), `mvn sortpom:sort` do the same:
```
$ mvn sortpom:verify
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< aProject >--------------------
[INFO] Building aProject1.0.0-SNAPSHOT
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- sortpom-maven-plugin:3.0.0:verify (default-cli) @ aProject ---
[INFO] Verifying file /aProject/pom.xml
[INFO] The xml element <groupId> should be placed before <properties>
[INFO] The file /aProject/pom.xml is not sorted
[INFO] Sorting file /aProject/pom.xml
[INFO] Saved sorted pom file to /aProject/pom.xml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

**Comment by timja** [comment]
In this case we aren't using sortpom directly @bguerin, the error is:

```
[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.18.0:check (default) on project jenkins-war: The following files had format violations:
[ERROR]     pom.xml
[ERROR]         @@ -66,8 +66,8 @@
[ERROR]          ····<dependency>
[ERROR]          ······<groupId>org.jenkins-ci</groupId>
[ERROR]          ······<artifactId>executable-war</artifactId>
[ERROR]         +······<version>2.3</version>
[ERROR]          ······<scope>provided</scope>
[ERROR]         -······<version>2.3</version>
[ERROR]          ····</dependency>
[ERROR]          ····<dependency>
[ERROR]          ······<groupId>org.jenkins-ci.main</groupId>
[ERROR] Run 'mvn spotless:apply' to fix these violations.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :jenkins-war
```

**Comment by basil** [comment]
This PR is now ready for merge. We will merge it after approximately 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process. Thanks!

**Pull request merged**
