### PR TITLE
Add Chinese translation

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Oh,  sp many changes 👍 we could label all your PRs with "hacktoberfest" and then you could get a T-short: https://jenkins.io/blog/2017/10/06/hacktoberfest/

**Comment by oleg-nenashev** [comment]
Test failure does not seem related. Maybe an infra glicth

**Comment by LinuxSuRen** [comment]
@oleg-nenashev  really? It will be my honor.

**Comment by LinuxSuRen** [comment]
@jenkinsci/hacktoberfest

**Review by oleg-nenashev — APPROVED** [review]

**Pull request merged**
