### PR TITLE
Use Java 7 versions of GZIPInputStream and GZIPOutputStream

### PR DESCRIPTION
**Pull request by basil**
See stapler/stapler#203, jenkinsci/workflow-api-plugin#134, jenkinsci/cloudbees-folder-plugin#174, and jenkinsci/docker-build-step-plugin#75. [JZlib](https://github.com/ymnk/jzlib) has not been updated since 2013. Since then, [`GZIPInputStream`](https://docs.oracle.com/javase/8/docs/api/java/util/zip/GZIPInputStream.html) and [`GZIPOutputStream`](https://docs.oracle.com/javase/8/docs/api/java/util/zip/GZIPOutputStream.html) have been added to the Java 7 API, so it seems more prudent to use those implementations.

Note that I have intentionally _not_ removed JZlib from `core/pom.xml` in order to avoid breaking compatibility with `workflow-api-plugin`, `cloudbees-folder-plugin`, and `docker-build-step-plugin` (all of which currently depend on the JZlib provided by Jenkins core pending the merge and release of the abovementioned PRs).

### CODE REVIEW

**Comment by basil** [comment]
Actually looks like these have been part of the Java API since 1.1 (1997). Not sure why we used a third-party library when the corresponding functionality was already available in Java, but in any case the basic point remains the same: Java is still maintained, but JZlib is no longer maintained. So it makes more sense for us to use what is maintained rather than what is not.

**Comment by basil** [comment]
Oh wow, we actually switched from the Java API _to_ JZlib in [JENKINS-14362](https://issues.jenkins.io/browse/JENKINS-14362) for performance reasons. Well never mind, then!

**Comment by MarkEWaite** [comment]
I'm not sure we should surrender that easily.  Current performance on Java 8 and Java 11 and current behavior might be quite different that it was in 2013 when the change had to be made.  It might be a great excuse to learn JMeter and attempt some stress testing to compare the behavior between the JZlib implementation and the Java implementation.

**Comment by basil** [comment]
I doubt it would be possible to verify that we aren't regressing JENKINS-14362 since nobody ever figured out how to reproduce JENKINS-14362. The problem in Java and/or zlib described in JENKINS-14362 may have been resolved in the intervening years, but it may very well still be present. [JDK-8193682](https://bugs.openjdk.java.net/browse/JDK-8193682) (from the 2017/2018 timeframe) describes a very similar issue and doesn't give me confidence. I think the only way to know for sure would be to release the change and see if any users complain about a regression. IMHO the benefit does not seem to be worth the potential inconvenience to users.

**Comment by MarkEWaite** [comment]
That makes sense.  Thanks for the clarification and thanks very much for investigating the dependency so effectively.

**Comment by StefanSpieker** [comment]
If I see this right: https://bugs.openjdk.org/browse/JDK-8193682 the issue is fixed and was backported, so I guess we could try out the java version:


Issue | Fix Version | Assignee | Priority | Status | Resolution | Resolved In Build
-- | -- | -- | -- | -- | -- | --
JDK-8280712 | 17.0.4-oracle | Ravi Reddy | P4 | Resolved | Fixed | b01
JDK-8283522 | 17.0.4 | Jonathan Dowland | P4 | Resolved | Fixed | b01
JDK-8284429 | 15.0.8 | Yuri Nesterenko | P4 | Resolved | Fixed | b01
JDK-8284431 | 13.0.12 | Yuri Nesterenko | P4 | Resolved | Fixed | b01
JDK-8280711 | 11.0.16-oracle | Ravi Reddy | P4 | Resolved | Fixed | b01
JDK-8283329 | 11.0.16 | Goetz Lindenmaier | P4 | Resolved | Fixed | b01
JDK-8281039 | 8u341 | Ravi Reddy | P4 | Resolved | Fixed | b01
JDK-8280781 | 7u351 | Ravi Reddy | P4 | Resolved | Fixed | b01

**Comment by basil** [comment]
Yes we could, but I am still not convinced that the poor performance with regard to CPU that was encountered in JENKINS-14362 won't again become a problem. Maybe it will, maybe it won't, so the change is risky. If someone else wants to take on that risk (and be responsible for dealing with the consequences if a regression occurs), then fine. I am not willing to take on that risk myself.

**Pull request closed without merging**
