### PR TITLE
Improve log record icon

### PR DESCRIPTION
**Pull request by basil**
A full file tray icon is used for build history, as seen [here](https://ci.jenkins.io/job/Core/job/jenkins/). An empty file tray is used for log records. Apart from raising confusing questions about why one tray is empty and the other is full, I do not think it makes sense to use the same icon for both things: one is a historical record of a build, which very much seems like the type of thing you would "file away" for future reference in the physical world, but the system log is a short-term record of events, more analogous to a **journal** in the physical world. Indeed, the logging framework in `systemd` is called `systemd-journald`, and journaling file systems have been around for decades.

#### Before

system-log-before

and

log-records-before

#### After

system-log-after

and

log-records-after

### Proposed changelog entries

- Use a more appropriate icon for log records.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7217"></a>

### CODE REVIEW

**Review by NotMyFault — COMMENTED** [review]
I don't think the backside of a bank card is quite suitable to access Jenkins' logs 🤔

**Comment by basil** [comment]
Good thing, then, that I am _not_ proposing to introduce the back side of a bank card. I am proposing to introduce a **journal**: https://www.amazon.com/Moleskine-Classic-Cover-Notebook-Ruled/dp/8883701127

**Comment by basil** [comment]
Note that ionicons has a _separate_ `card` icon, which does indeed look like the back side of a bank card. I am explicitly _not_ using that icon in this PR, so as far as I can tell the criticism in the preceding review is not valid.

**Comment by timja** [comment]
While it may be called journal it looks a bit strange to me.

Would `reader-outline` be any better?

image

**Comment by basil** [comment]
> While it may be called journal it looks a bit strange to me.

Looks fine to me, and apparently to the ionicon developers as well, because otherwise they would not have created distinct `card` and `journal` icons.

> Would `reader-outline` be any better?

I do not see any reason why it would.

**Comment by basil** [comment]
As far as I can tell there is no objection to the journal concept, just a dislike of the appearance of the `journal` icon in Ionicons. That would be a valid reason to withhold approval of a pull request that proposes to adopt Ionicons as the official icon set of the Jenkins project, but it is not a valid reason to withhold approval of a pull request that applies an appropriate icon from the _already_ officially chosen icon set of the Jenkins project, Ionicons.

**Review by timja — APPROVED** [review]
sure let's try it

**Review by NotMyFault — APPROVED** [review]

**Pull request merged**
