### PR TITLE
Adds Polish translations

### PR DESCRIPTION
**Pull request by damianszczepanik**
No JIRA.

### Proposed changelog entries

* Improvement, provides new translations for Polish language

### Submitter checklist

- ~JIRA issue is well described~ N/A
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- ~Appropriate autotests or explanation to why this change has no tests~
- ~For dependency updates: links to external changelogs and, if possible, full diffs~

### CODE REVIEW

**Comment by batmat** [comment]
Please don't remove parts of the PR template. Filling the changelog is a must have. Thanks!

**Comment by damianszczepanik** [comment]
I have treated this as a template that must be filled and section which are not related should be removed.

Restored anyway.

**Comment by batmat** [comment]
@damianszczepanik removing sections _might_ be fine, but indeed I think crossing the unapplicable out is better for clarity.

But the part that really needs to be (almost) always put is the changelog part.

Can you modify `Entry 1: Issue, Human-readable Text` to make it an actual changelog entry? (look at other PRs to get inspiration for the expected format).

Thank you!

**Comment by damianszczepanik** [comment]
Updated

**Review by daniel-beck — APPROVED** [review]

**Pull request merged**
