### PR TITLE
Do not force the representation

### PR DESCRIPTION
**Pull request by recena**
### Before

before
### After

after

@jenkinsci/code-reviewers 
@reviewbybees

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
👍 I just wonder why you decided to try French Web UI :)

**Comment by recena** [comment]
@oleg-nenashev The reason [JENKINS-36875](https://issues.jenkins-ci.org/browse/JENKINS-36875)

**Comment by recena** [comment]
Are you a bot? 😄

**Comment by recena** [comment]
I assume you are @stephenc. There is no an JIRA issue associated here. I realized while I was working on other issue.

**Comment by oleg-nenashev** [comment]
@recena It was me. Not sure how it happened, likely I've responded from CB email. Sorry abut that

**Comment by oleg-nenashev** [comment]
By the way, another issue is [JENKINS-36690](https://issues.jenkins-ci.org/browse/JENKINS-36690)

**Comment by nicodmf** [comment]
i close issue 36690 in favor of the resolution ticket

**Comment by oleg-nenashev** [comment]
Adjusted the PR title

**Comment by nicodmf** [comment]
link to https://github.com/jenkinsci/external-monitor-job-plugin/pull/14

**Comment by recena** [comment]
This PR is not related with JENKINS-36690 at all.

**Comment by recena** [comment]
This PR is not related with [JENKINS-36690](https://issues.jenkins-ci.org/browse/JENKINS-36690) at all.

**Comment by recena** [comment]
@oleg-nenashev Restoring the PR title, you are confusing the issue.

**Comment by oleg-nenashev** [comment]
@recena If you think this issue is irrelevant, please create a right one and reference it. The PR may need backporting.

**Comment by daniel-beck** [comment]
@oleg-nenashev I don't think removing a few line breaks makes the cut for LTS.

**Comment by recena** [comment]
@oleg-nenashev This is not a bug. It is simplify a way to polish a piece of code.

**Comment by recena** [comment]
@oleg-nenashev I don't have any problem to file a JIRA issue for that, but there are PR (related with translations for example) without a JIRA issue. IMO, this PR is very similar to review a translations or review a text.

**Comment by oleg-nenashev** [comment]
Nope. Translations are not a subject for backporting. If this one hammers
the New Item screen, it needs to be backported. Then it needs an issue.

If backporting is not required, I'm fine with merging it as is

On Jul 25, 2016 16:04, "Manuel Recena" <notifications@github.com> wrote:

@oleg-nenashev <https://github.com/oleg-nenashev> I don't have any problem
to file a JIRA issue for that, but there are PR (related with translations
for example) without a JIRA issue. IMO, this PR is very similar to review a
translations or review a text.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jenkinsci/jenkins/pull/2468#issuecomment-234946966>,
or mute
the thread

**Comment by recena** [comment]
@daniel-beck Thanks.

**Pull request merged**
