### PR TITLE
Update domain for issues.jenkins.io in PR template

### PR DESCRIPTION
**Pull request by timja**
(skip changelog)

### CODE REVIEW

**Review by NotMyFault — APPROVED** [review]

**Review by daniel-beck — APPROVED** [review]
Could you also update the lts-candidate URL in the maintainer checklist?

**Comment by timja** [comment]
> Could you also update the lts-candidate URL in the maintainer checklist?

already uses issues.jenkins.io as far as I can tell

**Comment by timja** [comment]
> It doesn't, which is why I asked for it.

```
 timja in ~/projects/jenkinsci/jenkins on master*
$ rg issues.jenkins-ci.org
```

```
$ rg issues.jenkins.io | wc -l
      40
```

If you can find it then please file a PR to update it, I can't find it

**Comment by basil** [comment]
Tim, it's in `.github/PULL_REQUEST_TEMPLATE.md`:

```
.github/PULL_REQUEST_TEMPLATE.md:- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).
```

You need to run `rg(1)` with `--hidden` to search the `.github` directory.

**Pull request merged**
