### PR TITLE
[FIXED JENKINS-26312] [FIXED JENKINS-26298] Reimpl css based layout changes

### PR DESCRIPTION
**Pull request by tfennelly**
This PR undoes an earlier commit ( 543ea66 ) and reworks it to try get the layouts working better. Earlier commit tried to fix the layout of the left and right panels (side-panel and main-panel) to fixed widths. Didn't work properly so reworking. This commit also relies on javascript to track content resizing in the left and right panels and applying of appropriate styles to make the layout work properly.

Also fixes JENKINS-26306.

[Here's the jenkins.war](https://jenkins.ci.cloudbees.com/job/core/job/jenkins-core/1920/artifact/war/target/jenkins.war) for those that want to test it.

### CODE REVIEW

**Comment by daniel-beck** [comment]
@jglick Does the bot care about PR title?

**Comment by daniel-beck** [comment]
Testing PR build 1920: JENKINS-26298 and JENKINS-26312 seem resolved. Did not experience JENKINS-26306 before. JENKINS-25971 appears to remain resolved.

So, :+1:

**Comment by tfennelly** [comment]
Merged

**Comment by daniel-beck** [comment]
@kohsuke @jglick Could we get this into 1.597? Two reports on the scrolling issue, four reports on the footer issue, and more than a dozen watchers each. Rather bad community ratings in the changelog as well.

**Comment by jglick** [comment]
> Does the bot care about PR title?

Only if you close the PR using a merge commit created by GH, in which case the PR title becomes part of the commit title.

**Comment by jglick** [comment]
> Could we get this into 1.597?

I have not been following this, but if you think it is appropriate to `cherry-pick -x` this into the `rc` branch, go ahead.

**Pull request closed without merging**
