### PR TITLE
[JENKINS-68593] Dropdown chevrons overflow in build queue and executor status

### PR DESCRIPTION
**Pull request by benebsiny**
See [JENKINS-68593](https://issues.jenkins.io/browse/JENKINS-68593)

Screenshot

### Proposed changelog entries

* Place dropdown chevrons at the right of the link in build queue and executor status.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] (If applicable) Jira issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [X] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/6604"></a>

### CODE REVIEW

**Review by NotMyFault — APPROVED** [review]

**Comment by alecharp** [comment]
It seems to be working but I have to note that the build number is on the same vertical alignment as the console progress bar: 
Screen Shot 2022-06-07 at 10 48 54

Also, when you put your pointer over the "left" part of the build number (first few pixels), the animation to display the chevrons start, but then immediately spots and then start again, and on and on and on:

https://user-images.githubusercontent.com/985955/172339987-0f3fc9ac-c52c-45e9-9f02-f2a195ef8e86.mp4

**Comment by NotMyFault** [comment]
> It seems to be working but I have to note that the build number is on the same vertical alignment as the console progress bar:

I'm unable to replicate that on this PR, the build number is perfectly aligned between both for me:

https://user-images.githubusercontent.com/13383509/172812767-0ad14e8f-3ece-4afd-b72e-4178f907a48e.mp4

> Also, when you put your pointer over the "left" part of the build number (first few pixels), the animation to display the chevrons start, but then immediately spots and then start again, and on and on and on:

That is a preexisting issue and tracked in a different Jira ticket.

**Comment by NotMyFault** [comment]
cc @janfaracik mind taking a look?

**Comment by NotMyFault** [comment]
Can I convince someone from @jenkinsci/sig-ux to take a look? Minor issue, but it would be nice to see it resolved before the next LTS baseline selection starts.

**Comment by janfaracik** [comment]
Working well on my end 👍 Some strange menu alignment but that's almost certainly down to YUI

**Review by janfaracik — APPROVED** [review]

**Comment by NotMyFault** [comment]
This PR is now ready for merge. We will merge it after ~24 hours if there is no negative feedback.
Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process.
Thanks!

**Comment by daniel-beck** [comment]
Causes [JENKINS-69116](https://issues.jenkins.io/browse/JENKINS-69116). Reverted by #6919.

I think I mentioned a while back in discussions around testing PRs that sidepanel widgets are regression magnets, and exceptional care needs to be taken with anything involving them. This is what I meant.

**Comment by NotMyFault** [comment]
I've updated the issue with the new information obtained while reviewing this PR, it's a Firefox only issue.

**Comment by daniel-beck** [comment]
Added `skip-changelog` since this was reverted before it made it into a release.

**Pull request merged**
