### PR TITLE
Sort imports

### PR DESCRIPTION
**Pull request by basil**
The imports in this code base are unsorted, making it [harder to read the code](https://github.com/jenkinsci/jenkins/pull/5723#discussion_r709520047) and forcing developers to consciously think about where to place new imports (effort that is largely pointless).

This PR contains two commits. The first commit sorts all imports. The second commit enables enforcement of import order with Spotless to prevent future ordering violations from occurring. Future import ordering problems can be automatically corrected by running `mvn spotless:apply`.

Yes this will cause a lot of merge conflicts. But they can be easily resolved by preferring your own changes (`-X ours`) and then running `mvn spotless:apply`.

### Proposed changelog entries

N/A

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Review by jglick — APPROVED** [review]
Thanks!

**Comment by daniel-beck** [comment]
I expect that this change will make it more difficult for us to safely deliver security fixes, and not just until this commit is on all lines we develop them for, but also to a lesser degree permanently.

The security team is using a script that automatically applies a single security fix to all supported lines (weekly, 1-2 LTS, up to 2 additional LTS for CloudBees). Ideally, that merges cleanly and so the fix only needs to be written once. If the affected code changes once between supported baselines, we may need to write the fix twice (and keep the PRs in sync with any changes in response to feedback) and apply each to whichever baselines are compatible. If affected code changes twice between lines, then write up to three versions of the same security fix. And so on...

The reason it would permanently be a problem: When there are merge conflicts in imports (which seems to be the most common cause for conflicts), I'm sometimes able to deliberately order imports such that the same change merges cleanly into all lines. Downside: Bad import order. Upside: We cannot possibly screw up keeping multiple versions of the same security fix up to date.

On balance, I would rather have bad ordering of entries in the part of the file that the IDE helpfully keeps collapsed, than mess up even a single security fix delivery for some of the releases. We've done that before (although with a different process and cause) and it sucks.

Not blocking this, but I would like to raise this as a risk from this change that most reviewers are probably not aware of.

**Comment by jglick** [comment]
> merge conflicts in imports (which seems to be the most common cause for conflicts)

Though often these are _caused_ by lack of consistent import ordering.

> write the fix twice (and keep the PRs in sync with any changes in response to feedback)

This _used_ to be handled nicely by some heavy-duty Git merge magic, but it turns out humans have an easier time just copying diff hunks around manually. :man_shrugging: 

I think that since merge conflicts in import blocks are so easy to resolve we should not be held back by the possibility of a minor nuisance during security backporting work. Anyone doing such backports already needs to be ready to handle far trickier cases, even if they are less common.

**Comment by Wadeck** [comment]
It seems to be a nice change for the project itself, but not really for the security team. We will have more troubles with our fixes, especially during the next 6-9 months to resolve the conflicts. That's annoying but I would say not sufficiently to block such evolution.
The automatic reformatting has the same kind of problem, we have to work through "once" before being in a better situation.

So (with a tear in the eye) thank you for the job done there, our future ourselves will thank you (perhaps not right now :D)

**Comment by jglick** [comment]
> by running `mvn spotless:apply`

After also applying the `pom.xml` one-line patch here, right?

**Comment by basil** [comment]
> After also applying the `pom.xml` one-line patch here, right?

Yes of course. The point is that sorting the imports is easy and quick, and after that you shouldn't have any problems with backporting.

**Comment by daniel-beck** [comment]
> As far as I can tell, backports shouldn't be a problem as long as you first sort the imports on any branches that are still open for backports. That can be done in 30 seconds by running `mvn spotless:apply`, or with [`google-java-format`](https://github.com/google/google-java-format) by running `git ls-files '*.java' -z | xargs -0 google-java-format -i --fix-imports-only`.

Good idea, that would take care of the most painful parts I expect. Thanks!

**Comment by basil** [comment]
> Good idea, that would take care of the most painful parts I expect. Thanks!

No problem, Daniel. I've done this a few times in large codebases at my current employer, and in each case I followed this strategy successfully without causing too much disruption for my colleagues. If this PR is merged, I'm happy to follow up with a similar PR to the `stable-2.303` branch, which is the only branch I'm aware of that is still open for backporting.

**Comment by jtnord** [comment]
Having a defined sort order and minimising changes from submitters when their IDE re-orders things is great, so thanks for moving this on.
but the Google style guide for imports is in my opinion just awful so I can not consciously say "I approve" here, it is not written to aid humans otherwise not allowing blank lines within a group would not be forbidden (for the same reason we have lines blank after methods etc..), putting static imports at the top (that are more likely to be referenced from the code would not be there). 
I am not going to stand in the way of this - but for me this makes the code much less readable

**Comment by jglick** [comment]
You read `import` statements? For me they just appear in a collapsed block in my editor.

**Comment by basil** [comment]
The lack of a standard import ordering benefits individuals by allowing them to express their subjective preferences but harms the group by slowing down the development process (by forcing developers to unnecessarily think about import order when writing new code or changing existing code) and the review process (by leading to PRs that change both logic and import ordering, with their associated merge conflicts). Just as mutual coöperation in the prisoner's dilemma yields the greatest overall reward, mutual coöperation with regard to import ordering yields the greatest overall benefit to the group, at the slight cost of hindering the ability of individuals to express their subjective preferences.

**Review by jeffret-b — APPROVED** [review]
I'm in favor of this change. The chaotic nature of imports in the Jenkins codebase has long bugged me. It's always difficult to change it in a PR because that just adds more complexity. This looks like an easy way to get it corrected and then keep things moving along well.

As someone who helped prepare security fixes in the past, I agree that this adds some complexity, but I don't see that there's enough of a concern to not do this helpful improvement.

**Comment by timja** [comment]
Thanks all, given this impacts security folks the most and they’ve all weighed in ( and thanks everyone else for their feedback). Let’s go ahead with this

——

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by jglick** [comment]
Oh just one small request: @eecummings should be allowed to write, e.g.

```java
import hudson.
              model /* why wo */.
                    Failure
                           /* uld we fail */;
                            import
                    hudson
                 . // to
              model
           . // finger
       Fingerprint
; // print?
```

**Review by StefanSpieker — APPROVED** [review]

**Comment by timja** [comment]
this sorted my branch nicely:

```
git rebase -Xtheirs master
mvn spotless:apply
```

**Pull request merged**
