### PR TITLE
Upgrade to winstone 5.27 and Jetty 9.4.48.v20220622

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: Olivier Lamy <olamy@apache.org>

### Proposed changelog entries

* Upgrade winstone 5.27 and Jetty 9.4.48.v20220622 (9.4.46.v20220331..9.4.48.v20220622) 
  * https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.47.v20220610
  * https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.48.v20220622

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")` if applicable.
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/6955"></a>

### CODE REVIEW

**Comment by timja** [comment]
Jetty 10 is ready-for-merge so I think we can skip this?

see https://github.com/jenkinsci/jenkins/pull/6801

**Comment by NotMyFault** [comment]
Closing in favor of the PR Tim mentioned, which has been merged and will land in 2.363.

Thanks nevertheless, olamy :)

**Comment by olamy** [comment]
yup but my intention is more to have it in LTS

**Comment by NotMyFault** [comment]
> yup but my intention is more to have it in LTS

In 2.346.3?

**Comment by timja** [comment]
> yup but my intention is more to have it in LTS

Is there an issue it addresses / a need to backport it?

**Comment by olamy** [comment]
9.4.47 and 9.4.48 are including some fixes for CVEs.
We are definitely not affected here.
BUT you know some companies are using some very `smart security scanners` which will detect those versions are not safe!
This may prevent some of those companies to use the LTS.
Strictly we do not have to do it for any **real** security reasons but this could help some users.

**Comment by timja** [comment]
Generally yes that would make sense, but given this won't make it into a weekly line I don't think it will make it into an LTS line.

If this is something you think is important please raise it on the developer mailing list for an exception to the it must be released in the weeklies first rule.

**Pull request closed without merging**
