### PR TITLE
maven-hpi-plugin -> 1.114

### PR DESCRIPTION
**Pull request by KostyaSha**
During build process search found that it not actual.

### CODE REVIEW

**Comment by jglick** [comment]
I can try to release 1.114 if you want to use it.

**Comment by KostyaSha** [comment]
@jglick i see that many plugins updating hpi versions, not sure why, but imho better update it in core periodically to exclude updates in plugins.

**Comment by jglick** [comment]
[JENKINS-30067](https://issues.jenkins-ci.org/browse/JENKINS-30067) is blocking a release (CC @Vlatombe).

**Comment by KostyaSha** [comment]
@Vlatombe @stephenc why are you merging into maven-hpi-plugin master and not doing releases then? Your merges is slow bomb for any dev after you.

@jglick could you try 1.113  as initial PR change or 1.112? Many plugins manually updating to 1.112.

**Comment by jglick** [comment]
JENKINS-30067 claimed to be fixed, will rerun sanity checks and try to do a 1.114 release.

**Comment by jglick** [comment]
Now waiting for https://github.com/jenkinsci/maven-hpi-plugin/pull/22.

**Comment by jglick** [comment]
Alright, 1.114 finally released, give it a shot.

**Comment by KostyaSha** [comment]
I will update PR

**Comment by KostyaSha** [comment]
Updated, let's wait for pr builder.

**Comment by jglick** [comment]
`CommandLauncherTest.commandSuceedsWithoutChannel` needs to be marked `@RandomlyFails` I think.

**Pull request merged**
