### PR TITLE
[JENKINS-29792] Don't run trigger for disabled/copied projects

### PR DESCRIPTION
**Pull request by KostyaSha**
UPD: https://issues.jenkins-ci.org/browse/JENKINS-29792

As part of https://groups.google.com/d/msg/jenkinsci-dev/EyDnytxglxY/1JtweBCxKB8J
round 1

### CODE REVIEW

**Comment by daniel-beck** [comment]
Why? I kind of like the idea of being able to re-enable a project with a special trigger.

This change has no rationale.

**Comment by KostyaSha** [comment]
@daniel-beck and what? Enable it.

**Comment by waynr** [comment]
Re-enabling the job with a special trigger seems counter-intuitive to me--if a job is marked as "disabled" in XML or through the web-ui, what kind of trigger would you expect to bypass this setting?

I guess I can imagine someone wanting to manually trigger a job regardless of its disabled status, but given that this is not the current Jenkins behavior I don't see the benefit of preventing what appears to be a performance improvement from being merged.

**Comment by KostyaSha** [comment]
Jenkins has other Timers: APeriodicWork and etc that are not job related and they will continue to work as expected. For SCMTrigger i want avoid Thread creation, but it need more time for investigation.

**Comment by oleg-nenashev** [comment]
Actually I have a case, which seems to be a valid one:
* We have a monitoring trigger for one of our internal release repositories ("Trigger job on a new release")
* If the job is disabled due to any reason (e.g. policies violation), we generate a special event in our monitoring system + write warnings to Jenkins log 
* Users get the notification and then can re-run jobs when it gets enabled

The proposed change breaks the case.
I definitely vote for the improvement, but IMO it should be configurable somehow.

**Comment by KostyaSha** [comment]
@oleg-nenashev if your job is disabled, why do you expect that it's trigger will be executed? For this weird case you can wrote plugin that will work with PeriodicWork and do this weird things.

Btw, without running triggers for disabled jobs jenkins startup will be faster.

**Comment by oleg-nenashev** [comment]
@KostyaSha 
What about a convenient approach?
* Leave the proposed changes as is
* Add a new <code>onCheckTriggers()</code> method to <code>hudson.model.listeners.ItemListener</code>

**Comment by oleg-nenashev** [comment]
A new hook would also satisfy @daniel-beck's use-case

**Comment by daniel-beck** [comment]
Mine was more hypothetical than anything, so not that important if there are real reasons to implement this. At the time I wrote that, I hadn't seen any. (Still rather questionable, assuming the majority of jobs are enabled if they have an SCM trigger, and you configure an SCM polling thread count limit, but I could live with either.)

A minor upside of this change would be that (SVN) polling wouldn't just write into the polling log that the project is disabled, replacing that it disabled the project because one configured location did no longer exist.

**Comment by KostyaSha** [comment]
@daniel-beck if job is disabled, why do you expected any activities for it? This looks weird.

**Comment by KostyaSha** [comment]
> We need to catch any trigger attempt for a disabled project
@oleg-nenashev Shouldn't this me implemented through listener or via other enabled project?

**Comment by olivergondza** [comment]
I agree with https://github.com/jenkinsci/jenkins/pull/1617#issuecomment-85589642. :+1: on the change. @oleg-nenashev, would that be a problem for you?

**Comment by oleg-nenashev** [comment]
I've fixed the implementation at my previous Jenkins installation when the PR has been created, so it should not be a problem.
:+1: from me

**Comment by KostyaSha** [comment]
Then i must wrote test.
I think core should have somewhere clock settings so it can be tuned for JenkinsRule and test will be possible to implement. Will try...

**Comment by KostyaSha** [comment]
Rebased.
Removed my comment about tests, like other people i'm lazy to do a test case, let's merge?

**Comment by jtnord** [comment]
@daniel-beck you can retrigger builds without spamming people by doing it on the CI server.

**Comment by KostyaSha** [comment]
@jtnord even public ghprb plugin accepts triggering from comments. Maybe time replace CB PR builder?

**Comment by jtnord** [comment]
@KostyaSha lets move that to the mail list if you feel strongly.

**Comment by KostyaSha** [comment]
@jtnord not now

**Comment by KostyaSha** [comment]
PR build is green

**Pull request merged**
