### PR TITLE
Adding translation for New View

### PR DESCRIPTION
**Pull request by jbleduigou**
Signed-off-by: Jean-Baptiste Le Duigou <jb.leduigou@gmail.com>

See [JENKINS-61424](https://issues.jenkins-ci.org/browse/JENKINS-61424).

### CODE REVIEW

**Review by olamy — APPROVED** [review]
LGTM (Me parait bien :) )

**Review by oleg-nenashev — APPROVED** [review]
/CMSC 👍

**Comment by oleg-nenashev** [comment]
I plan to merge it tomorrow if no negative feedback. Thanks @jbleduigou and @olamy !

**Comment by oleg-nenashev** [comment]
Merging it without 24hrs timeout, because it is a minor localization fix

**Comment by oleg-nenashev** [comment]
Thanks for your contribution @jbleduigou! It should land in the next weekly release.

**Pull request merged**
