### PR TITLE
Typo. This list is of JobProperty, not UserProperty.

### PR DESCRIPTION
**Pull request by jglick**
@reviewbybees

### CODE REVIEW

**Comment by recena** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
:bee:, but why not <code>{@link JobProperty}</code>?

**Comment by KostyaSha** [comment]
> :bee:, but why not {@link JobProperty}?

+1

**Comment by jglick** [comment]
> why not `{@link JobProperty}`?

Because the generated Javadoc will already link to that class due to the type of the field.

**Pull request merged**
