### PR TITLE
Make Fingerprint's XSTREAM field public

### PR DESCRIPTION
**Pull request by rsandell**
Some plugins needs to register compatibility alias etc for
their FingerprintFacets.

See for example https://github.com/jenkinsci/dockerhub-notification-plugin/pull/11

@reviewbybees

### CODE REVIEW

**Comment by jtnord** [comment]
:-1: on public static fields.  ad a getter method if you need access to this, or better still add a `registerAlias()` method?

**Comment by rsandell** [comment]
@jtnord I am doing the same as in 'Jenkins.XSTREAM', `Items.XSTREAM` and `Run.XSTREAM`.

**Comment by jtnord** [comment]
yeah - if I could travel back in time I would make those only available via getters too :-)

**Comment by jtnord** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
This is the only right way in this case. BTW migration to a new Xstream version will be a bit more breaking if it happens. I think getXstream() should be annotated with CheckForNull and documented properly in order to support the upgrade in the future. 

So I put :bug: , but just for the public getter method, which should be improved a bit

**Comment by jglick** [comment]
> I think getXstream() should be annotated with CheckForNull

Huh? Why?

:bee:

**Comment by rsandell** [comment]
@oleg-nenashev it will never return null so more likely `@Nonnull` in that case?

**Comment by oleg-nenashev** [comment]
@rsandell @jglick 
If you update Xstream2 to an incompatible Xstream3, you may have to either break the interface or to return null. If we take such risk, I'm OK to keep it as nonnull if it gets documented (@since would be also useful)

**Comment by rsandell** [comment]
Test failures seems unrelated to my changes.

**Comment by oleg-nenashev** [comment]
:bee: after the discussion

**Comment by mslusarczyk** [comment]
:bee:

**Comment by rsandell** [comment]
@reviewbybees done

**Pull request merged**
