### PR TITLE
Replace System.our/err with logger and stack traces

### PR DESCRIPTION
**Pull request by daniel-beck**
**For discussion**: I don't know whether this is remotely a good idea or not. All I know is that seeing https://github.com/jenkinsci/pipeline-model-definition-plugin/blob/pipeline-model-definition-1.3.9/pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy#L683 on ci.jenkins.io while I was investigating stability issues annoyed me and it took me more than an hour (thanks to https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/334 being merged but effectively unreleased) to figure out where this was coming from.

The following would have made it easier to identify where this is coming from

```
2019-10-19 19:36:48.497+0000 [id=100]   INFO    h.WebAppMain$LoggingPrintStream#log: 'GOT CONTEXT FOR lol' was sent to System.err in thread 'Running CpsFlowExecution[Owner[pl/9:pl #9]]'. Increase this logger's logging level to FINE to see the full stack trace.
```

And when increasing the log level as shown in the log recorder UI, it's even better – not _a lot_ better (thanks CPS!), but still:

```
Oct 19, 2019 9:37:19 PM FINE hudson.WebAppMain
GOT CONTEXT FOR lol
java.lang.Exception: The previous log message was sent to System.err in thread 'Running CpsFlowExecution[Owner[pl/10:pl #10]]' through the following stack trace. Plugins should never send log messages to System.err.
	at hudson.WebAppMain$LoggingPrintStream.log(WebAppMain.java:310)
	at hudson.WebAppMain$LoggingPrintStream.println(WebAppMain.java:353)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:47)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:84)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	at sun.reflect.GeneratedMethodAccessor99.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:107)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	at sun.reflect.GeneratedMethodAccessor99.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:87)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	at sun.reflect.GeneratedMethodAccessor99.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:186)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:370)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:93)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:282)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:270)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:66)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Proposed changelog entries

* Intercept calls to `System.out.println` and `System.err.println`, logging them instead.

### Submitter checklist

- [n/a] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

I think @jtnord had an opinion on logging in the past?

### CODE REVIEW

**Comment by slonopotamus** [comment]
I feel infinite recursion nearby if one tries to set up logging to stderr. x_x

**Comment by daniel-beck** [comment]
@slonopotamus Good point. Any good ideas how to prevent that, or is this just dead?

**Comment by slonopotamus** [comment]
This heavily depends on logger implementation, I'm afraid. If it is initialized before you swap stdout/stderr and if it saves a local copy of System.out/System.err, it will be able to log to real stdout/stderr. In all other cases, hello StackOverflowError.

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
It is a valiant goal but a risky implementation from what I see. Jenkins users may enable ConsoleLogger in JUL settings file, and then  you will likely end up in and endless loop. And console logging is quite common for some container types

**Comment by daniel-beck** [comment]
@oleg-nenashev 

> Any good ideas how to prevent that, or is this proposal just dead?

**Comment by oleg-nenashev** [comment]
Prohibit methods in plugin POM so that static analysis tools fail any
attempts to use it by default?

**Comment by daniel-beck** [comment]
Right, which is a totally different, and slow to be integrated way of preventing the undesirable behavior in the first place.

Can we assume the bad behavior is rare enough that we can look at the stack trace to detect recursion, and just print in that case?

**Comment by slonopotamus** [comment]
I actually fail to follow the logic of this PR. It started from that you were reading stderr output to diagnose issues. But after this PR you don't get logs on stderr anymore. Just pretend stderr logs didn't exist in the first place and _don't look at stderr_.

It also makes sense to always look exactly at the same version of code that you're running to avoid such situations - when code you read acts differently from the code you run.

**Comment by daniel-beck** [comment]
@slonopotamus Logger output and stdout/stderr are interleaved in `docker logs` which is how ci.jenkins.io is run.

> It also makes sense to always look exactly at the same version of code

Sure, which is how I ultimately ended up identifying the culprit – GitHub was the "easy" solution that works often enough.

Ultimately, this is just the _motivation_ for me to file this. Whether this change (fixed to address the recursion issue) makes sense or not should be evaluated independently – otherwise, we probably introduce too much code for too narrow use cases.

**Pull request closed without merging**
