### PR TITLE
Slave.JnlpJar.getURL did not work in some modes when core had a snapshot dependency on Remoting

### PR DESCRIPTION
**Pull request by jglick**
When experimenting with `remoting` changes using a snapshot dependency, I found that two kinds of things did not work:

* `JenkinsRule.createSlave` and similar overloads would fail to find `remoting.jar` in the webapp context and fail.
* `mvn -f war hudson-dev:run` would also fail to find `remoting.jar` when creating agents interactively.

Also, lookup of `jenkins-cli.jar` seemed to be fragile at best (sensitive to Maven process CWD).

Changing both to verify what they are returning more carefully. If a true JAR can be found in the webapp context, fine—use it.

Otherwise replace `target/classes/` with the matching `target/whatever.jar` assembly. (This is also more convenient for iteractively testing changes to that component: you can simply `mvn -f ../remoting -DskipTests package` or `mvn -f cli -DskipTests package` to rebuild that JAR, and have it take effect in a functional test or interactive debugging session, without touching `core` or `war` modules.)

And if neither works, fail with a meaningful error, rather than guessing at the process CWD and returning a potentially nonexistent URL.

### Proposed changelog entries

None needed, should not affect production usage.

### Desired reviewers

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
Apparent flake:

```
org.junit.runners.model.TestTimedOutException: test timed out after 180 seconds
	at java.lang.Thread.sleep(Native Method)
	at hudson.model.QueueTest.shouldBeAbleToBlockFlyweightTaskAtTheLastMinute(QueueTest.java:865)
```

Prior to #3055 this would have hung the whole build, I think, so it seems that patch worked.

**Review by oleg-nenashev — APPROVED** [review]
I see nothing wrong with that 🐝

**Comment by jglick** [comment]
@reviewbybees done

**Comment by oleg-nenashev** [comment]
I doubt the test failure is somehow related, retriggering just in case

**Comment by oleg-nenashev** [comment]
retriggering CI

**Comment by oleg-nenashev** [comment]
Issues with Update center appear consistently, but I doubt this PR is a culprit. Will put on-hold for investigation

**Pull request merged**
