### PR TITLE
Initial Bulgarian translation

### PR DESCRIPTION
**Pull request by alshopov**
All Message_bg.properties files done - 654 strings.
Added MIT license to every new file.

Signed-off-by: Alexander Shopov ash@kambanaria.org

Author:    Alexander Shopov ash@kambanaria.org

### CODE REVIEW

**Comment by batmat** [comment]
Don't read bulgarian, but a pity the commit message has a typo :-) "initlial". 
I guess we'll have to find someone who speaks bulgarian to at least make a quick review (?).

**Comment by alshopov** [comment]
Commit message fixed.
I am not so sure about reviewers though - since I am one of the oldest active translators for FOSS in Bulgarian (15 years of GNOME, git, bash, firebug, lots of other projects) - I am accustomed to being the reviewer myself. (https://l10n.gnome.org/teams/bg/, http://translationproject.org/team/bg.html)
I will re-announce the translation in the list to see whether there are other Bulgarian speaking people. Otherwise you need to tell me what kind of reviewers you want.

**Comment by batmat** [comment]
Don't worry, I'm absolutely not saying you're not to be trusted ;-). Just saying that would be better as in general at least that someone can review typos & so on before it gets merged.

**Comment by daniel-beck** [comment]
@alshopov Thanks for taking on this task!

Since you emailed the list I'll give this PR another few days to allow reviews.

**Comment by rtyler** [comment]
I've posted a request from [@jenkinsci](https://twitter.com/jenkinsci), so I hope that helps too!

**Comment by martin-g** [comment]
Any reason why you don't use the XML format for properties files [1] [2]?
It is supported since Java 1.5.

1. http://docs.oracle.com/javase/7/docs/api/java/util/Properties.html#loadFromXML(java.io.InputStream)
2. Examples - http://www.webreference.com/programming/Globalize-Web-Applications15_Java6/index.html

**Comment by alshopov** [comment]
My reasons for staying with the classic properties format is that command line tools in source expect this format and I see no big gain in Bulgarian being the odd translation out.
For Jenkins itself - I suppose it is due to historic reasons as Hudson's first version is just months after the release of Java 1.5. Additionally for many Latin based alphabets - unicode escapes are necessary only for the few (usually) letters outside ASCII range.
Anyway - changing the format of the properties files is definitely not part of this merge.

**Comment by oleg-nenashev** [comment]
I think we're ready to go with this PR since there was no comments regarding the text.
:+1: for the merge

**Pull request merged**
