### PR TITLE
Move period outside parentheses

### PR DESCRIPTION
**Pull request by jsoref**
### Submitter checklist

- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)

### CODE REVIEW

**Comment by daniel-beck** [comment]
So the stupid rule with the period doesn't apply to parentheses, only quotation marks?

**Comment by jsoref** [comment]
It took me a bit to figure out which stupid rule you mean...
I'm pretty sure you mean this one:
http://blog.apastyle.org/apastyle/2011/08/punctuating-around-quotation-marks.html

My favorite part of it is that the Americans and British disagree. 

But, in short, the stupid rule is limited afaik to quotations of things where one would naturally append a period or comma following the quotation. And, it's pretty stupid. I personally don't agree with it in a number of cases, especially when dealing with code where one is trying to quote something that someone might want to copy verbatim.

Anyway, https://english.stackexchange.com/revisions/2127/2 is the applicable rule for commas and parentheticals.

**Review by daniel-beck — APPROVED** [review]

**Comment by jsoref** [comment]
And here's a reference for my exception to the American rule (Technical language, which is often what we're doing): https://www.quickanddirtytips.com/education/grammar/how-to-use-quotation-marks?page=1
The first page explains the history of this feature–the quotation marks were protecting the fragile comma and periods in movable type.

**Comment by daniel-beck** [comment]
Thanks! 😆 Now I have a reference when I claim this is

> stupid

**Review by Wadeck — APPROVED** [review]
Thx for the information 👍

**Pull request merged**
