### PR TITLE
[FIXED JENKINS-27623] Move to JDK7

### PR DESCRIPTION
**Pull request by stephenc**
[JENKINS-27623](https://issues.jenkins-ci.org/browse/JENKINS-27623)

@reviewbybees

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
I suppose JDK7 migration should be discussed and approved on the governance meeting

**Comment by KostyaSha** [comment]
Shouldn't versions be updated in pom project?

**Comment by stephenc** [comment]
@oleg-nenashev which is perfectly fine with me... just that the JDK8 debate, to my mind, misses the point that we shouldn't be running JDK6 as minimum since a good while now anyway... heck (can) does anyone even run the unit tests with Java 6

**Comment by stephenc** [comment]
@KostyaSha meaning? we didn't bump versions when dropping support for Java 5

**Comment by stephenc** [comment]
https://github.com/stephenc/jenkins/commit/e314d90e5c37258cc57782d63af1f51900c62b0b is what we did last time we droppped support for a JDK

**Comment by oleg-nenashev** [comment]
@stephenc 
I still debug the old Perforce plugin with JDK6 (JDK7 is not supported in it due to Hudson dependency). Java dependency won't be a blocker for such case, but I'm not sure about https://github.com/jenkinsci/acceptance-test-harness, which may also include such old plugins

**Comment by stephenc** [comment]
@oleg-nenashev I guess my point is that the unit tests in Jenkins core are not runnable with Java 6 un less you play very fancy dancing games IIRC. I think you need to do something like

```
$ export JAVA_HOME=Path_to_Java_7_or_8
$ export PATH=JAVA_HOME/bin:$PATH
$ mvn clean install -DskipTests
$ export JAVA_HOME=Path_to_Java_6
$ export PATH=JAVA_HOME/bin:$PATH
$ mvn test
```

And fingers crossed that javac does not decide to recompile anything as if it does you will not be able to compile as there are some type inferences that do not compile with Java 6's javac

**Comment by stephenc** [comment]
Another point in favour of this change is Maven 3.3.1.

The "evil" plugin will, at some point in time, want to embed the Maven 3.3.1 jars in order to pick up the latest hooks for pre-parsing the pom. Once it does that it will need Java 7 as a minimum version.

We have no way for a plugin to advertise that it needs a newer JRE. So by picking the battle at the very obvious fast failure of jenkins.war we enable plugins that require Java 7 as a minimum to say they require Jenkins 1.607 (or whenever this lands) as a minimum and thus the update center will prevent a sneak-attack of Java 7 requirements via plugin upgrades

**Comment by jglick** [comment]
I would advise marking this PR `[WiP]` to make it clear that it is exploratory and contingent on broad buy-in.

Beyond simply updating the source level, a PR like this ought to do a sweep of things that can be cleaned up given the new baseline. e314d90e5c37258cc57782d63af1f51900c62b0b was already mentioned, but `log --grep` turns up other related changes such as 9a40874ad3107d0ed8f6b7849787c552105122c9, 15ac490af13f5ac022ce9bd05e4a25bc2094b194, d73ea7ee2e664319611217e78d9fdc19d03e584c, 0a76051a47ce92c935c30445154021ade7b69907, and 253943e13ef16a9e14b71ef07a30e51e6a66e38f. The source base needs to be grepped for `TODO` comments mentioning `Java 6`, `JDK 6`, `JDK6`, `JDK 1.6`, etc., and those places simplified. For example, ed748d4b810ac1dd85e5da7857bc203f5773f329 can be cleaned up (generally, look for mentions of `@IgnoreJRERequirement`). And `-source 7` language constructs should be used wherever appropriate, which is all over the place: NetBeans has a bulk refactoring that introduces `<>`, switches `finally` blocks to `try`-with-resources, and so on, and I presume IDEA has something similar.

Such a massive diff can only be maintained in a short-lived PR, since it will immediately get merge conflicts with pretty much anything else. And since there is not yet consensus on when we should do this change, :-1:

**Comment by stephenc** [comment]
@jglick I was deliberately splitting this into two parts:

1. Move to `-source 7`
2. Tidy up afterwards

This pull request addresses the first part (though there are 24 failing tests that need investigation just for the change to `-source 7`)

A subsequent pull request would cover the second as waiting until all the java 6 todos are tidy in the pull request will be an exercise in tail chasing. I am not expecting this pull request to be merged without the governance meeting saying OK, but I do expect it to be ready and thus not `[WIP]`

**Comment by stephenc** [comment]
@kohsuke you may want to pick up some of this in #1679 but I am closing this in favour of your PR

**Pull request closed without merging**
