### PR TITLE
Fix broken 'download Maven here' link

### PR DESCRIPTION
**Pull request by gnikonorov**
Fix the `download Maven here` link. It looks like the target was removed at some point, so I added it back in.

### Proposed changelog entries

N/A: This is just documentation, so I am not including a changelog entry 

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [x] There are at least 2 approvals for the pull request and no outstanding requests for change
- [x] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [x] Proper changelog labels are set so that the changelog can be generated automatically
- [x] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [x] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]

**Review by MarkEWaite — APPROVED** [review]
Looks good.  Could remove the unreferenced `[download Maven]` that appears earlier in the section of references.

**Comment by MarkEWaite** [comment]
This PR is now ready for merge.  We will merge it after approximately 24 hours if there is no negative feedback.

**Comment by gnikonorov** [comment]
> Looks good. Could remove the unreferenced `[download Maven]` that appears earlier in the section of references.

Of course @MarkEWaite, done. Sorry I missed it earlier

**Review by markjacksonfishing — APPROVED** [review]

**Comment by wangrongding** [comment]
image

why Jenkins_updater be stuck  for two days

**Comment by MarkEWaite** [comment]
@wangrongding asked:

> why Jenkins_updater be stuck for two days

The issue tracker for Jenkins core is https://issues.jenkins.io/ .  Pull requests to Jenkins core are not the place to ask questions or to raise issues that are not related to the pull request.  Your request seems to be a request for help, not related to this pull request.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions.

**Pull request merged**
