### PR TITLE
Added default attribute to enum.jelly

### PR DESCRIPTION
**Pull request by rsandell**
So you can have something different than the first enum value as the default

@reviewbybees

### CODE REVIEW

**Comment by jtnord** [comment]
if you want a default why no set it in the constructor of `it`?

I'm probably against this as it moves the defaults from code to the UI (not that Jenkins doesn;t do this all over the place).

**Comment by oleg-nenashev** [comment]
:+1: since other fields provide a similar default option. A single enum may be used in different forms with different default value, so the approach is perfectly valid IMHO

**Comment by rsandell** [comment]
@jtnord I guess you mean the constructor of instance? That doesn't work since for example selecting a new trigger or adding a new build step in a config form there is no instance until after you submit the form and by then the first element will be set since that was the default in the form.
With this change you can have something different than the first element.

**Comment by jtnord** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
re :bee:

**Comment by rsandell** [comment]
@reviewbybees done

**Pull request merged**
