### PR TITLE
[JENKINS-33467] Do not store duplicate Cause’s

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-33467](https://issues.jenkins-ci.org/browse/JENKINS-33467)

@reviewbybees esp. @christ66

### CODE REVIEW

**Comment by kohsuke** [comment]
:bee:

**Comment by christ66** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
:bee: since we don't store timestamps in User causes.
Otherwise it would be a problem

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Comment by oleg-nenashev** [comment]
It seems somebody needs to release it

**Pull request merged**
