### PR TITLE
[JENKINS-37625] Update Winstone to fix an IllegalStateException

### PR DESCRIPTION
**Pull request by jglick**
Integrates https://github.com/jenkinsci/winstone/pull/31. Manually tested and verified that it prevents the exception.

@reviewbybees

### CODE REVIEW

**Comment by daniel-beck** [comment]
https://github.com/jenkinsci/winstone/compare/winstone-3.2...winstone-3.3

**Review by daniel-beck — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
:bee:

**Comment by jtnord** [comment]
@jglick this was merged with a erroring unit test on Linux.

**Comment by jglick** [comment]
> this was merged with a erroring unit test on Linux

A flake probably—only on one builder. I think the build is gone now, not sure what it was.

**Comment by daniel-beck** [comment]
@jtnord jenkins.ci.c.c was successful, indicating a flaky test. CC @jglick 

Note that ci.j.io is completely useless right now thanks to dozens of Unit test failures and the UI not indicating whether they're Windows-only (which isn't great but often just a matter of not running a Linux-only test on that platform rather than a legitimate failure).

**Pull request merged**
