### PR TITLE
Update the Agent => Master security link to point to a non-Apache redirect

### PR DESCRIPTION
**Pull request by rtyler**
This help text points to a very old redirect which is only editable in our
infrastructure Puppet code (which will at some point in the distant future be
removed).

Changing to jenkins.io/redirect means that the destination of this redirect
is easily modified by pull requests to
https://github.com/jenkins-infra/jenkins.io

See also jenkins-infra/jenkins.io#520

### CODE REVIEW

**Comment by rtyler** [comment]
@daniel-beck [this code isn't being removed](https://github.com/jenkins-infra/jenkins-infra/blob/staging/dist/profile/manifests/catchall.pp#L95-L96) right now.

I don't know when an appropriate time will be to sunset `jenkins-ci.org`, but we're stuck running this "catch-all" apache instance for at least another year. I just want to start moving away things as I see them

**Review by oleg-nenashev — APPROVED** [review]
LGTM 👍

**Comment by oleg-nenashev** [comment]
I doubt we will be ready to deprecate `jenkins-ci.org` within a foreseeable time without a fallout on old instances, but I suppose we will have to do it. Migrating to the new URLs everywhere is a nice thing in any case

**Comment by daniel-beck** [comment]
Wouldn't a redirect URL like `agent-to-master-security` be better than the pretty indecipherable `security-144`?

**Comment by KostyaSha** [comment]
> Wouldn't a redirect URL like agent-to-master-security be better than the pretty indecipherable security-144?

`agent-to-master-security-144`

**Pull request merged**
