### PR TITLE
[JENKINS-55936] suppress exception for nonexistent adminwhitelist rul…

### PR DESCRIPTION
**Pull request by jsoref**
…e files

See [JENKINS-55936](https://issues.jenkins-ci.org/browse/JENKINS-55936).

### Proposed changelog entries

* Improve handling of non-existent admin whitelist rule files for agent-to-master security

### Submitter checklist

- [x] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers

**Review by oleg-nenashev — APPROVED** [review]
Looks OK, but it would be great t get some feedback from the Security team. CC @daniel-beck @Wadeck

**Review by daniel-beck — APPROVED** [review]
This warning has annoyed me for so long. Assuming manually tested, 👍

**Review by Wadeck — APPROVED** [review]
Seems fine!

**Pull request merged**
