### PR TITLE
Enable Windows builds using ACI agents

### PR DESCRIPTION
**Pull request by jglick**
Follows up #4129. Subsumes #4155 and _may_ solve the path length issues there. Complements https://github.com/jenkins-infra/pipeline-library/pull/110.

No changelog needed, purely internal.

### CODE REVIEW

**Review by slide — APPROVED** [review]

**Comment by jglick** [comment]
Current builds are still breaking for mysterious infrastructure reasons.

**Comment by jglick** [comment]
At the moment it seems that Windows ACI agents are not being provisioned at all. CC @slide @olblak

**Comment by jglick** [comment]
Seems that the Windows JDK 11 tests all fail (@slide):

```
java.lang.UnsatisfiedLinkError: C:\openjdk-11\bin\awt.dll: Can't find dependent libraries
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2638)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829)
	at java.base/java.lang.System.loadLibrary(System.java:1867)
	at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1395)
	at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1393)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1392)
	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1425)
	at java.desktop/java.awt.Font.<clinit>(Font.java:260)
	at hudson.model.MultiStageTimeSeries.<clinit>(MultiStageTimeSeries.java:94)
	at hudson.model.LoadStatistics.<init>(LoadStatistics.java:140)
	at hudson.model.OverallLoadStatistics.<init>(OverallLoadStatistics.java:55)
	at jenkins.model.Jenkins.<init>(Jenkins.java:671)
	at …
```

I could just disable that combination. Unfortunately the Windows JDK 8 tests seem to fail too, for a different reason:

```
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at org.junit.internal.runners.statements.FailOnTimeout.evaluate(FailOnTimeout.java:125)
	at org.jvnet.hudson.test.JenkinsRule$2.evaluate(JenkinsRule.java:628)
	at …
```

**Comment by slide** [comment]
I need to update the jdk11 images, see comment https://github.com/jenkinsci/jenkins/pull/4178#issuecomment-525852168

**Comment by jglick** [comment]
OK, that branch is easily enough skipped for now. Any idea what could be causing the `unable to create new native thread`?

**Comment by slide** [comment]
Windows containers can only request 3.5GB of memory with Azure Container Instances, I am wondering if that is just not enough for testing Jenkins?

**Comment by jglick** [comment]
Perhaps, though I thought we had been using Windows ACI agents successfully to run plugin `JenkinsRule` tests, which should be no different in terms of memory requirements.

**Comment by slide** [comment]
That's true, we have definitely done that.

**Comment by jglick** [comment]
Better for a while and then

```
 Cannot contact aci-maven-windows-4vxft: java.io.IOException: Remote call on JNLP4-connect connection from 52.247.3.146/52.247.3.146:24001 failed
```

**Comment by jglick** [comment]
In `DisablePluginCommandTest`, `TemporaryDirectoryAllocator.dispose` is failing with errors such as

```
java.nio.file.FileSystemException: C:\Jenkins\agent\workspace\Core_jenkins_PR-4178\test\target\j h8174339694106520009\plugins\antisamy-markup-formatter\WEB-INF\lib\antisamy-markup-formatter.jar: The process cannot access the file because it is being used by another process.
```

**Comment by jglick** [comment]
Possibly similar issue in `JobQueueTest`; and a crash in `LabelExpressionTest`. Not looking promising. I wonder if I should start with a PR to turn Windows tests back on generally, since the Windows VM agents were only temporarily unavailable, and we could see if some test failures are due to Windows generally.

**Comment by jglick** [comment]
```
 java.lang.AssertionError: 
 failed to connect slave2: $ "C:\openjdk-8\jre/bin/java"  -Djava.awt.headless=true -jar "C:\Jenkins\agent\workspace\Core_jenkins_PR-4178\war\target\jenkins\WEB-INF\lib\remoting-4.0.jar"
 Error occurred during initialization of VM
 Could not reserve enough space for object heap
 
 	at org.jvnet.hudson.test.JenkinsRule.waitOnline(JenkinsRule.java:1065)
 	at org.jvnet.hudson.test.JenkinsRule.createOnlineSlave(JenkinsRule.java:1043)
 	at org.jvnet.hudson.test.JenkinsRule.createOnlineSlave(JenkinsRule.java:1032)
 	at org.jvnet.hudson.test.JenkinsRule.createOnlineSlave(JenkinsRule.java:1024)
 	at hudson.model.NodeTest.testGetAssignedLabelWithBothAndOrExpression(NodeTest.java:398)
```

lends credence to https://github.com/jenkinsci/jenkins/pull/4178#issuecomment-571700895.

**Comment by jglick** [comment]
This one seems hopeless for now. Can revisit if #4447 works out.

**Comment by jtnord** [comment]
no `argLine` is specified for surefire (or the agent) so it will gobble up oodles of ram.  perhaps that should be specified to get consistent results.

**Pull request closed without merging**
