### PR TITLE
[FIXED JENKINS-37440] - Disable FindBugs run when skipTests is true

### PR DESCRIPTION
**Pull request by oleg-nenashev**
@reviewbybees (and CC @jglick who requested it)

https://issues.jenkins-ci.org/browse/JENKINS-37440

### CODE REVIEW

**Comment by jtnord** [comment]
I am :-1: on this - as detailed in the JIRA - it is bad to overload a specific maven plugin flag to do more than what it was designed for.

**Comment by jtnord** [comment]
:bug: findbugs is [bound to verify](https://github.com/oleg-nenashev/jenkins/blob/9805e6ef935e5e17aa13391058cbc00993e45041/pom.xml#L519) - so should not be running at all during install.

**Comment by oleg-nenashev** [comment]
@jtnord 

> I am 👎 on this - as detailed in the JIRA - it is bad to overload a specific maven plugin flag to do more than what it was designed for.

Please also submit a bug to parent POM then

**Comment by oleg-nenashev** [comment]
I'm fine with the current behavior, so I'll let @jglick to justify his PoV

**Comment by KostyaSha** [comment]
👎  skip tests is for skipping tests and not for static analysing

**Comment by jglick** [comment]
:+1:, `-DskipTests` implies that you do not care about tests in the broader sense (any build steps which could only cause a build failure, but would not affect artifact contents if skipped vs. successful).

**Comment by KostyaSha** [comment]
Broader is `maven.test.skip`

**Comment by jtnord** [comment]
@oleg-nenashev raised [JENKINS-37657](https://issues.jenkins-ci.org/browse/JENKINS-37657)

**Comment by stephenc** [comment]
👍 to the principle, :-1: to the property. Should trigger this based on `maven.test.skip`

**Comment by jglick** [comment]
> Should trigger this based on `maven.test.skip`

I would be OK with that, though this property _can_ affect artifacts if you have a `test-jar` execution.

> rather than set the property, instead should force the findbugs plugin to skip without allowing property setting

You mean using a plugin `execution`? What is the advantage?

**Comment by jglick** [comment]
> this property _can_ affect artifacts

An [example](http://stackoverflow.com/q/24727536/12916) of why `maven.test.skip` is not a good choice in general, including for the plugin POM (though it would work in the case of `jenkinsci/jenkins`, after the split of `jenkins-test-harness`).

**Comment by KostyaSha** [comment]
@jglick why you can't create profile in `settings.xml` (or i forgot maven)?

**Comment by stephenc** [comment]
> You mean using a plugin execution? What is the advantage?

No I mean just by using the default `<configuration>`, e.g.

```
   <profile>
       <id>skip-findbugs-with-tests</id>
        <activation>
          <property>
            <name>skipTests</name>
            <value>true</value>
          </property>
        </activation>
        <build>
          <plugins>
            <plugin>
              <groupId>org.codehaus.mojo</groupId>
              <artifactId>findbugs-maven-plugin</artifactId>
              <configuration>
                <skip>true</skip>
              </configuration>
            </plugin>
          </plugins>
        </build>
    </profile>
```

The reason why this is better is that way we ignore any of the properties that are in effect and the heavy handed skip property is properly heavy handed

**Comment by batmat** [comment]
+0. It's become quite a common practice as @jglick says that in general -DskipTests you basically want to build fast.

In my past life, I had set up a `QaD` (_Quick-and-Dirty_) to do that, where I would disable everything possible (tests, static analysis, enforcer...).

**Comment by jglick** [comment]
[Another argument for why using the de facto standard `-DskipTests` is better](https://jitpack.io/docs/BUILDING/#maven-projects)

**Comment by daniel-beck** [comment]
@oleg-nenashev It looks like @stephenc's approach could get consensus here?

**Comment by oleg-nenashev** [comment]
It could, but it requires feedback from @KostyaSha and @jtnord

**Comment by oleg-nenashev** [comment]
@jglick 

> @jglick jglick was unassigned by reviewbybees on Nov 14

WAT?

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers Does anybody care? If not, I am about closing it since I am fine with the current behavior

**Comment by daniel-beck** [comment]
@oleg-nenashev The current state of the discussion is @stephenc 's proposal.

**Comment by oleg-nenashev** [comment]
Maybe. But we still need somebody to implement it :(

**Comment by jglick** [comment]
My current workaround is a local profile:

```xml
<profile>
    <id>skip-findbugs-with-tests</id>
    <activation>
        <property>
            <name>skipTests</name>
            <value>true</value>
        </property>
    </activation>
    <properties>
        <findbugs.skip>true</findbugs.skip>
    </properties>
</profile>
```

**Comment by daniel-beck** [comment]
@jglick Is there a difference to @stephenc 's proposal other than being shorter?

**Comment by jglick** [comment]
@daniel-beck 

> The reason why this is better is that way we ignore any of the properties that are in effect and the heavy handed skip property is properly heavy handed

Whether you consider that a pro or a con, I do not know.

**Comment by oleg-nenashev** [comment]
I have closed the original ticket since we agreed that "-DskipTests" is not a good approach

**Comment by jglick** [comment]
> we agreed that "-DskipTests" is not a good approach

Uh, who agreed to that? Not I.

**Comment by oleg-nenashev** [comment]
@jglick See the votes in the ticket and here. Maybe it is not a joint agreement, but there are definitely more nays that yays.

**Comment by oleg-nenashev** [comment]
Closing it. Whomever is interested in reconsidering it, it should be "fixed" in another place after #3308

**Comment by jglick** [comment]
see https://github.com/jenkinsci/pom/pull/105

**Pull request closed without merging**
