### PR TITLE
[JENKINS-61688] Load build discarder configuration after restart

### PR DESCRIPTION
**Pull request by daniel-beck**
See [JENKINS-61688](https://issues.jenkins-ci.org/browse/JENKINS-61688).

I wish I was joking.

WDYT? 2.222.2?

### Proposed changelog entries

* Actually load a previously saved global build discarder configuration after restart.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [n/a] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [x] There are at least 2 approvals for the pull request and no outstanding requests for change
- [x] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [x] Proper changelog labels are set so that the changelog can be generated automatically
- [x] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [x] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]

**Comment by MarkEWaite** [comment]
I merged the documentation pull request https://github.com/jenkins-infra/jenkins.io/pull/3005 on the assumption that even if it contains errors or flaws, it is better than not have a warning in the online documentation.

**Review by res0nance — APPROVED** [review]

**Comment by res0nance** [comment]
This should definitely be in LTS, we should definitely merge it for the next weekly to give it some time to soak

**Review by MRamonLeon — APPROVED** [review]

**Review by alecharp — APPROVED** [review]

**Review by varyvol — APPROVED** [review]

**Review by olivergondza — APPROVED** [review]

**Review by batmat — APPROVED** [review]
```
$ mvn clean test -Dtest=GlobalBuildDiscarderTest => test success
$ git co HEAD~ core/src/main
$ mvn clean test -Dtest=GlobalBuildDiscarderTest => test failure
```
:+1:

**Review by rsandell — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
I was also hit by this GlobalConfiguration pitfall a few times, our developer API is error prone there. I am not against early 2.222.2. It is not a regression per-se, but it limits functionality of the feature. What about doing so early next week after the regular weekly? If we have a several extra day, we can collect more feedback about .1 and other potential issues there. Groovy Hook is a plausible workaround for now. Or do you want to cut it right away @daniel-beck ?

I suggest to merge it in 24 hours if no negative feedback. I

**Comment by daniel-beck** [comment]
> Or do you want to cut it right away @daniel-beck ?

Unsure. Just putting the idea out there.

Right now it's a feature that doesn't do most of its job after a restart, which is annoying for extra global discarders (but realistically they'll probably run at least once between configuring and restart, i.e. will do the initial cleanup well enough to buy time before the disk runs full again).

The worse problem is the "data loss configuration" situation (people disable the discarder and get builds discarded anyway after a restart), and I just don't know how common that problem is.

Maybe we need to wait for user feedback? Given how we've changelogged it, there's a good chance that most people who would be hurt by this but won't update in the first place.

Side note: I'm really glad we have released 2.204.6, as users concerned about security can use that while they wait for 2.222.x to get better.

**Review by timja — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
test failure is unrelated , https://github.com/jenkinsci/jenkins/pull/4605 fixed it in the master branch

```
[failed-to-read] – TEST-jenkins.agents.WebSocketAgentsTest.xml
<1s
Stacktrace
Failed to read test report file /home/jenkins/workspace/Core_jenkins_PR-4602/test/target/surefire-reports/TEST-jenkins.agents.WebSocketAgentsTest.xml
org.dom4j.DocumentException: Error on line 9474 of document  : Invalid byte 1 of 1-byte UTF-8 sequence.
	at org.dom4j.io.SAXReader.read(SAXReader.java:462)
	at org.dom4j.io.SAXReader.read(SAXReader.java:325)
```

**Comment by oleg-nenashev** [comment]
2.222.1 looks to be stable so far. So I suggest adding Groovy hook samples as a workaround on the top of https://github.com/jenkins-infra/jenkins.io/pull/3005

**Comment by timja** [comment]
> 2.222.1 looks to be stable so far. So I suggest adding Groovy hook samples as a workaround on the top of [jenkins-infra/jenkins.io#3005](https://github.com/jenkins-infra/jenkins.io/pull/3005) . If we need to cut .2 early, we will also backport the fix

jcasc also works fine, which is why I never hit this issue as jcasc runs during boot

```yaml
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
      - "jobBuildDiscarder"
      - simpleBuildDiscarder:
          discarder:
            logRotator:
              artifactDaysToKeepStr: "7"
              artifactNumToKeepStr: "10"
              daysToKeepStr: "7"
              numToKeepStr: "10"
```

**Pull request merged**
