### PR TITLE
Make system info button text selectable in firefox

### PR DESCRIPTION
**Pull request by timja**
See:
https://github.com/jenkinsci/jenkins/pull/6843#issuecomment-1369161015

Found in:
https://stackoverflow.com/questions/34494405/how-to-select-a-text-with-a-cursor-in-a-button-element
and
https://github.com/elastic/eui/pull/2722

### Testing done

Went to system information page, selected a value, copied it, pasted it

### Proposed changelog entries

- Entry 1: Issue, human-readable text
- […]

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7559"></a>

### CODE REVIEW

**Comment by NotMyFault** [comment]
If you don't end the click action on the button itself, copy/pasting works again.
https://user-images.githubusercontent.com/13383509/210277964-5b13d343-2c12-47ee-a755-c3e2e1e1d866.mp4

**Comment by timja** [comment]
Fixed

**Review by NotMyFault — APPROVED** [review]
Thanks!

**Review by daniel-beck — APPROVED** [review]
Appears to work well in (limited) testing. Thanks for the quick reaction.

**Comment by timja** [comment]
Shipping so that the bug doesn't occur in the weekly being released today

**Pull request merged**
