### PR TITLE
Improve the french translation: 'pas bonne' isn't a great wording

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Review by batmat — CHANGES_REQUESTED** [review]

**Comment by sylvestre** [comment]
Oups sorry
I thought I pushed it with the right spelling :p
Now fixed!

**Review by batmat — APPROVED** [review]
\o/

**Review by Wadeck — APPROVED** [review]
LGTM and additionally you remove some quotes that are always problematic 👍

**Review by oleg-nenashev — APPROVED** [review]
LGTM

**Pull request merged**
