### PR TITLE
Deprecating Memoizer as there is a better replacement in Java 8

### PR DESCRIPTION
**Pull request by jglick**
### Proposed changelog entries

None needed I think. Theoretically the replacement could avoid acquiring a lock in some cases, but practically speaking this would only matter during startup.

### Desired reviewers

@reviewbybees

### CODE REVIEW

**Comment by johnou** [comment]
Depending on how often these methods are called you may consider first invoking get and then compute if absent for higher throughput.

**Comment by jglick** [comment]
Well that is what `Memoizer` was doing. I trust that Doug Lea et al. have considered this concept and written an implementation that already performs as well as that would.

**Comment by jglick** [comment]
Test failures seem to have been due to broken update center metadata at the time (CC @daniel-beck). Will trigger a fresh build to be sure.

**Comment by johnou** [comment]
@jglick see https://github.com/orbit/orbit/pull/253#issuecomment-308795229 for detailed information on performance.

**Comment by jglick** [comment]
@johnou so is there some JDK-nnnnnnn tracker issue discussing the performance characteristics? If there is an acknowledged problem and a plan to fix it in Java 8 then we should just use the API as it was designed. If not, then this should just be closed and we will carry on with our weird custom utilities.

**Comment by johnou** [comment]
@jglick no just what Ben mentioned in the other issue, that said I think this change does simplify the code a lot and if the methods are not invoked a great deal there might not even be a notable performance hit. I simply wanted to give a heads up, just in case.

**Comment by daniel-beck** [comment]
Right, while useful context to have if we ever need to investigate a performance problem related to this change, it's not worth worrying about the "what if" here. I think we should just go ahead with what we have here.

**Review by johnou — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
🐝 though I agree that having a micro-benchmark results would be reasonable here

**Review by jglick — COMMENTED** [review]
Sorry, just saw the most recent comments here.

Not sure about the others, but `Jenkins.getExtensionList` _is_ called from performance-sensitive sites, so we could consider adding an optimistic `get` to that one at least, if it is thought to be useful under heavy load conditions.

**Comment by oleg-nenashev** [comment]
@jglick There is an issue report, which points to this PR: https://issues.jenkins-ci.org/browse/JENKINS-48505

**Comment by johnou** [comment]
As I suggested an optimistic get should resolve that issue report.

**Comment by johnou** [comment]
https://github.com/jenkinsci/jenkins/pull/3198

**Comment by johnou** [comment]
for reference, here is the bug report (only fixed in JDK9) JDK-8184907 : ConcurrentHashMap.computeIfAbsent acquires lock even when key present http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8184907

**Pull request merged**
