### PR TITLE
[JENKINS-63855] Support 'min' and 'max' values in the <f:number> tag

### PR DESCRIPTION
**Pull request by benebsiny**
Add the validator for <f:number> whose clazz is 'number', 'number-required', 'non-negative-number-required', 'positive-number', 'positive-number-required'. See demo.

9a59q-vjd1e

See [JENKINS-63855](https://issues.jenkins-ci.org/browse/JENKINS-63855).

### Proposed changelog entries

* Support 'min' and 'max' values in the <f:number> whose clazz is 'number', 'number-required', 'non-negative-number-required', 'positive-number', 'positive-number-required'.
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] (If applicable) Jira issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [X] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
The JavaScript code looks good. `f:number` documentation in https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/lib/form/number.jelly should be also updated so that the new fields are documented.

**Comment by daniel-beck** [comment]
In addition to Oleg's feedback, would it make sense to start transforming such attributes to `data-whatever` attributes on the rendered HTML?

**Comment by daniel-beck** [comment]
If reasonably straightforward, a test for this would be nice as well.

**Comment by benebsiny** [comment]
@oleg-nenashev I've made changes on the document, have a look at it.

**Comment by benebsiny** [comment]
@daniel-beck This may be a good idea. Since 'min' and 'max' are also HTML's <input> attributes, I think we can distinguish the attribute between JavaScript (Jenkins) and HTML that do the validation.

**Comment by benebsiny** [comment]
> If reasonably straightforward, a test for this would be nice as well.

@daniel-beck Yes, let me find out where should the test be.

**Review by oleg-nenashev — APPROVED** [review]

**Comment by benebsiny** [comment]
@daniel-beck  The number test has been done. It look fine in https://ci.jenkins.io/blue/organizations/jenkins/Core%2Fjenkins/detail/PR-5192/38/pipeline/51/ , have a look at it.

**Review by res0nance — APPROVED** [review]
Changes look good, did not test this manually

**Review by olamy — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Comment by daniel-beck** [comment]
@benebsiny Thanks a lot for adding the tests! (I missed some notifications)

**Pull request merged**
