### PR TITLE
[JENKINS-25488] About Jenkins page using one column layout

### PR DESCRIPTION
**Pull request by recena**
[JENKINS-25488](https://issues.jenkins-ci.org/browse/JENKINS-25488)

downstream of https://github.com/jenkinsci/jenkins/pull/2029
### BEFORE

screenshot-localhost 8080 2016-02-12 12-26-26
### AFTER

screenshot-localhost 8080 2016-02-12 12-16-36

@reviewbybees

### CODE REVIEW

**Comment by andresrc** [comment]
:bee:

**Comment by daniel-beck** [comment]
Do we have other views in core we want this behavior for in core?

Why is this a separate CSS file rather than doing this e.g. with classes?

**Comment by recena** [comment]
> Do we have other views in core we want this behavior for in core?

IIRC, there is not other pages (in core) but this can be used by plugins they need it. I'm using this proposal in **Build Pipeline Plugin**.

> Why is this a separate CSS file rather than doing this e.g. with classes?

Because you have to include that CSS file **only** if you want to use one-column layout.

Anyway, the right solution for that (IMO) is to modify `<l:layout>` in order to support several layouts: one-column, two-column, etc..

**Comment by KostyaSha** [comment]
@daniel-beck all full page UI plugins needs full page. AFAIR :atm: they can get only middle layout place. build-pipeline-plugin gets breakages every time as somebody update css/layout in core. I asked @tfennelly to look at it two times (1 year ago), maybe he has ideas.

**Comment by KostyaSha** [comment]
:+1: for full-width UI. 
:-1: as i would like to see more generic API from core for plugins.

**Comment by oleg-nenashev** [comment]
I agree that better info-conftribution API would be useful.
On the other hand it's definitely not a part of JENKINS-25488.
Hence :+1:

**Comment by recena** [comment]
@KostyaSha 

> :-1: as i would like to see more generic API from core for plugins.

As I said before *Anyway, the right solution for that (IMO) is to modify <l:layout> in order to support several layouts: one-column, two-column, etc..*. In fact, I can do that.

**Comment by recena** [comment]
@oleg-nenashev What do you mean with *I agree that better info-conftribution API would be useful*?

**Comment by recena** [comment]
@reviewbybees done

**Comment by daniel-beck** [comment]
> the right solution for that (IMO) is to modify

Which should be implemented now, because if you're going to use this approach in plugins it's going to be impossible to get rid of again.

**Comment by recena** [comment]
@daniel-beck Right. I didn't do that from the beginning because I doubted if it is worth to spend time on jelly.

**Comment by recena** [comment]
I've decided to work on it, for that I've filed this Jira issue [JENKINS-32936](https://issues.jenkins-ci.org/browse/JENKINS-32936). Meantime, this PR should not be merged. /cc @oleg-nenashev

**Comment by recena** [comment]
This https://github.com/jenkinsci/jenkins/pull/2253 supersedes this.

This PR was developed against Jenkins `1.x`.

**Pull request closed without merging**
