### PR TITLE
[WiP] [JENKINS-26544] - Modified edit-select-all icon

### PR DESCRIPTION
**Pull request by chynten-zz**
Modified edit-select-all icon

### CODE REVIEW

**Comment by orrc** [comment]
The GIF looks pretty awful, could you please convert that so it looks the same as the PNG?

It would be nice if the image source (presumably the RRZE image set) could be explicitly mentioned in the commit comment, and if you could squash your branch to a single commit.

**Comment by oleg-nenashev** [comment]
Yes, gif icon is too pixelized.
@elephantem , any plans to adjust it?

> It would be nice if the image source (presumably the RRZE image set) could be explicitly mentioned in the commit comment, and if you could squash your branch to a single commit.

@orrc , I created https://gist.github.com/oleg-nenashev/ec7dea01dcf272e9b891 , so a merger can save some time and just do these things.

**Comment by oleg-nenashev** [comment]
@chynten Any plans to address the comments? If no, I'd consider closing the PR

**Comment by oleg-nenashev** [comment]
Closing since there was no response for a long time

**Comment by oleg-nenashev** [comment]
https://github.com/jenkinsci/matrix-auth-plugin/pull/17 has been integrated

**Pull request closed without merging**
