### PR TITLE
[JENKINS-56659] winstone 5.2 with timestamped version to build on ci

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: olivier lamy <olamy@apache.org>

See [JENKINS-56659](https://issues.jenkins-ci.org/browse/JENKINS-56659).

### Proposed changelog entries

* update Winstone from 5.1 to 5.2

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
It also includes the Jetty upgrade, right?

**Comment by olamy** [comment]
@oleg-nenashev yes if build green I will release winstone then change here to the released version :)

**Comment by olamy** [comment]
@oleg-nenashev ready to merge

**Review by oleg-nenashev — APPROVED** [review]
The PR looks good, but we really need the changelog to be fixed on the Winstone's side and linked from here

**Review by batmat — APPROVED** [review]

**Review by fcojfernandez — APPROVED** [review]

**Review by MRamonLeon — APPROVED** [review]
LGTM, just the changelog question

**Comment by batmat** [comment]
For cross-referencing, this picked up https://github.com/jenkinsci/winstone/pull/60

**Pull request merged**
