### PR TITLE
refactored doIndex

### PR DESCRIPTION
**Pull request by coledodd**
refactored doIndex method in core/src/main/java/jenkins/agents/WebSocketAgents.java : doIndex method of WebSocketAgents class

### Proposed changelog entries

N/A

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] JIRA issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@coledodd Hi! Could you please introduce us to your advisor? We would be happy to discuss how we could coordinate this refactoring work together

**Review by daniel-beck — CHANGES_REQUESTED** [review]
This unnecessarily introduces a bunch of indirection to the code, which actually makes it harder to read.

There's some useful stuff in here, e.g. this can make sense:

https://github.com/jenkinsci/jenkins/blob/59c8d072293775b5a363a1b98a086b2a10281b25/core/src/main/java/jenkins/agents/WebSocketAgents.java#L84-L86

This OTOH seems to overdo it:

https://github.com/jenkinsci/jenkins/blob/59c8d072293775b5a363a1b98a086b2a10281b25/core/src/main/java/jenkins/agents/WebSocketAgents.java#L87-L98

**Comment by varyvol** [comment]
I agree the idea is nice but it seems a bit too excessive.

**Comment by MRamonLeon** [comment]
@coledodd could you please address Daniel's comment and avoid the methods used just once and with one line for logging?

**Comment by fcojfernandez** [comment]
@coledodd are you still interesting in this PR? If so, please address Daniel's comment. Otherwise we can propose it for closing

**Comment by varyvol** [comment]
I'm proposing this for close given there's been no answer or activity for some time now.

**Comment by varyvol** [comment]
Closing given the lack of activity. Please feel free te reopen if you plan to work on this again.

**Pull request closed without merging**
