### PR TITLE
Update the minimum required Remoting version to 3.14

### PR DESCRIPTION
**Pull request by res0nance**
- Fix simple TODO where due to dependencies we could not use functionality from a newer remoting

### Proposed changelog entries

* Update the minimum required Remoting version to `3.14`

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
IIRC it was still a matter of the minimum compatible remoting version, because this code runs on agent.
While we added a lot of checks to advertise usage of newer remoting versions, it might be still a problem for some instances running versions below the minimum one.

But we have to move forward at some point, don't we?

**Review by jglick — APPROVED** [review]

**Review by jeffret-b — APPROVED** [review]
Looks good.

I haven't done any testing, but it should be fine. We do have to move forward.

**Comment by oleg-nenashev** [comment]
I plan to merge it tomorrow if no negative feedback

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
After a deeper look, I request changes here:

* `Channel#currentOrFail()` is available since Remoting 3.14 only. https://javadoc.jenkins.io/component/remoting/hudson/remoting/Channel.html#currentOrFail--
* `remoting.minimum.supported.version` is 3.4 in POM.xml

If we want to update this method, we need to bump `remoting.minimum.supported.version` and to add the change to the changelog

**Comment by oleg-nenashev** [comment]
FTR, it is Jenkins 2.100 when I learned from about Remoting API version concerns and introduced the minimum API version. https://jenkins.io/changelog/#v2.100 . So you can learn on my mistakes here

**Comment by res0nance** [comment]
I bumped the minimum version `3.14` is nearly 2 years old at this point. It feels a little weird to bump it for something so trivial. OTOH we have to move on at some point.

**Review by timja — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
FYI @res0nance @timja we are starting a Core PR Reviewers Team: https://groups.google.com/forum/#!topic/jenkinsci-dev/0sdrcSOQW64 . Please reply in the thread if you would like to join

**Comment by oleg-nenashev** [comment]
FYI @basil @pvtuan10 . I believe the Swarm and Apache Kafka Plugins are ready, but just in case

**Comment by oleg-nenashev** [comment]
I plan to merge it tomorrow if no negative feedback

**Review by oleg-nenashev — APPROVED** [review]

**Review by basil — APPROVED** [review]

**Pull request merged**
