### PR TITLE
Critical favicon change :-)

### PR DESCRIPTION
**Pull request by batmat**
I took a subpart of https://pbs.twimg.com/media/C0dbo7LWIAE3laU.jpg which I think was done by @ksenia-nenasheva so if she does allow it, I guess we're clear from a copyright perspective :-).

cc @kohsuke @oleg-nenashev @daniel-beck :-)

Merry Christmas to all, even if you possibly don't celebrate it! Wish you all the best.

### CODE REVIEW

**Comment by batmat** [comment]
@jenkinsci/code-reviewers critical last minute fix ;-)

**Comment by MarkEWaite** [comment]
Merry Christmas to you as well!

**Review by oleg-nenashev — APPROVED** [review]
Why not? :shipit:

**Review by ksenia-nenasheva — APPROVED** [review]
Fine with me :)
If you want, I could provide the logo without the Christmas Tree.

**Comment by mpailloncy** [comment]
Must probably be backported too ;) 
Merry Christmas to all !

**Comment by batmat** [comment]
Let's do that! :).!

**Comment by batmat** [comment]
@ksenia-nenashev well we could prepare one for next year, but I don't want to ask you do that now ;). Thanks for the proposal :)

**Comment by batmat** [comment]
I'll file the revert PR as soon as the weekly is released

**Comment by oleg-nenashev** [comment]
> I'll file the revert PR as soon as the weekly is released

@batmat Maybe it makes sense to keep it for 2 extra weeks. Some countries celebrate New Year and Orthodox Christmas (Jav 7) instead of the catholic holiday

**Comment by batmat** [comment]
@oleg-nenashev fine by me. I seem to remember anyway Kohsuke saying somewhere we should do that more often :)

**Comment by daniel-beck** [comment]
Someone in this thread other than me gets to update the changelog PR at https://github.com/jenkins-infra/jenkins.io/pull/1295

**Comment by batmat** [comment]
@daniel-beck I actually thought that change could be like a "hidden" one or so? But if you feel this ought to be changeloged I will do it.

**Comment by batmat** [comment]
I.e. like a Easter egg, which one wouldn't release note right?

**Comment by daniel-beck** [comment]
@batmat Why is this still the current favicon?

**Comment by batmat** [comment]
@daniel-beck because my understanding from @oleg-nenashev was that it was still meaningful for Russia, but granted now we can do it indeed. I just approved https://github.com/jenkinsci/jenkins/pull/3222

**Pull request merged**
