### PR TITLE
[JENKINS-62695] - Use daemon threads for SCMTrigger so Jenkins shuts down gracefully.

### PR DESCRIPTION
**Pull request by johnou**
See [JENKINS-62695](https://issues.jenkins-ci.org/browse/JENKINS-62695).

### Proposed changelog entries

* Graceful shutdown when SCM triggers are configured.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by timja — APPROVED** [review]
Seems right to me

**Comment by johnou** [comment]
@timja would you please consider adding the lts-candidate label too? the company I work for uses the lts line and it would be great to finally deploy this fix.

**Comment by timja** [comment]
lts-candidate is a label in jira, anyone can add it

**Comment by johnou** [comment]
ah cheers, added. for some reason I thought it was a github label.

**Comment by johnou** [comment]
@oleg-nenashev thanks for joining the review, in a nutshell I think this solution makes more sense since the trigger functionality may start a new build and the build system is already fully aware of the Jenkins lifecycle, adding in that awareness to SCMTrigger would make things unnecessarily complex.

**Comment by johnou** [comment]
@oleg-nenashev poke

**Review by oleg-nenashev — APPROVED** [review]
It makes sense per se, assuming that the SCM polling operation is always re-enterable in all implementations. I have a bad feeling about Perforce and other similar SCMs after this patch (I forgot a lot of pitfalls there though and may be wrong), but at the same time I believe that this is a right default behavior for Jenkins.

**Comment by oleg-nenashev** [comment]
We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Review by jglick — APPROVED** [review]
Suggest adding a `@Terminator` to call `shutdownNow()` (compare `jenkins.util.Timer`), but may be overkill.

**Review by olivergondza — APPROVED** [review]

**Review by res0nance — APPROVED** [review]

**Comment by johnou** [comment]
@jglick good to know about that annotation but I agree for this use case it would be overkill.

**Comment by jglick** [comment]
@johnou it is not the annotation per se that would matter; it is about whether we care to wait for ongoing trigger tasks to complete naturally before Jenkins finally shuts down. Since triggers are supposed to be read-only, I _think_ it is safe to just let them be killed in the middle like this.

**Comment by johnou** [comment]
@jglick sure, as mentioned in my previous comment I see triggers as a notifying service which queues a job which is then handled correctly by Jenkins if shutdown.

**Comment by johnou** [comment]
That said, I'm happy to revisit this if someone experiences unexpected behaviour / reports a regression.

**Pull request merged**
