### PR TITLE
[FIXED-JENKINS-31916] Slave can't be Serializable

### PR DESCRIPTION
**Pull request by KostyaSha**
RetentionStrategy and ComputerLauncher are not transient or Serializable so the whole class was never Serializable

### CODE REVIEW

**Comment by KostyaSha** [comment]
@stephenc could you look at?

**Comment by stephenc** [comment]
I think this should go the other way and push serializable on those other classes.


All instances are serialised by xstream anyway so I am :-1: on this change as we want to advertise that serialisation (of at least the xstream varietal) is in play

**Comment by stephenc** [comment]
Anything that needs to maintain non-serializable state needs to hook that into the Computer instance ... Not doing that is part cause of other issues

**Comment by KostyaSha** [comment]
@stephenc XStream already serializes everything in jenkins and everything is not Serializable. 
I have no opinion on this part, but current inconsistency fails FindBugs. There is of course fix :scream_cat: 
```
@SuppressFBWarnings(value = "SE_BAD_FIELD",
        justification = "Broken serialization https://issues.jenkins-ci.org/browse/JENKINS-31916") 
``` 
It is also under question how much info should be serialised for slave/:computer: to have restorable slave/computer state after jenkins restart (i.e. store RetentionStrategy with configuration that will be required for termination process).

I tried made Serializable tree, failed because some fields used from core. 
Should all nested tree be `Serializable`?

**Comment by oleg-nenashev** [comment]
> Should all nested tree be Serializable?

You will need to fix much plugins in such case. I would not vote for enforcing it before Jenkins 2.0

**Comment by stephenc** [comment]
They are already being serialised so you effectively have to write them that way anyway already. Show me a concrete case where they are not serializable and I'll show you a bug that needs fixing anyway

**Comment by KostyaSha** [comment]
> You will need to fix much plugins in such case. I would not vote for enforcing it before Jenkins 2.0

@oleg-nenashev How it will reflect on plugins if i make RetentionStrategy Serializable for example? I sure that nobody runs FindBugs to detect such issues.

@stephenc do you mean serialisation done by XStream?

**Comment by stephenc** [comment]
@KostyaSha yep they are being serialized by xstream... and as such you have to write those implementations to be serialization safe anyway... so if there is a `RetentionStrategy` that is not safe to add `implements Serializable` to then that strategy is fundamentally broken anyway.

My vote is to make the two classes `implements Serializable` (please be sure to define the `serialVersionUID` in the base class based on the existing value... CloudBees forces the `RetentionStrategy` and `ComputerLauncher` instances to be serialized over remoting in CJOC - yet more evidence that they are `Serializable` - so if you don't define the correct `serialVersionUID` that could cause issues... also ping me on to review the `serialVersionUID` as I'll want to recheck the calculation to be extra sure)

**Comment by KostyaSha** [comment]
Ok, thanks, will change as soon as i will have free time.

**Comment by daniel-beck** [comment]
@KostyaSha Do you want to keep this PR open?

**Comment by KostyaSha** [comment]
If you want continue - then feel free.

**Comment by KostyaSha** [comment]
@stephenc as usual thanks for your time and review. I have no any mood continue enhancing jenkins.

**Pull request closed without merging**
