### PR TITLE
Merge master into 2.0

### PR DESCRIPTION
**Pull request by daniel-beck**
@jenkinsci/code-reviewers 
@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
Does this even require a PR? My impression was that `2.0` was supposed to be merged with `master` constantly without notice.

**Comment by daniel-beck** [comment]
@jglick I thought so too, until KK opened a master merge PR.

**Comment by daniel-beck** [comment]
Tests probably fail because https://github.com/jenkinsci/jenkins/pull/2100 has been merged into master.

**Comment by daniel-beck** [comment]
Closing because master is broken.

**Pull request closed without merging**
