### PR TITLE
Remove JNR

### PR DESCRIPTION
**Pull request by basil**
Only a handful of plugins use JNR, so it makes more sense as a library plugin than a core dependency. So let's split this out into [`jnr-posix-api-plugin`](https://github.com/jenkinsci/jnr-posix-api-plugin) and remove it from core. I moved [the wrapper class](https://github.com/jenkinsci/jnr-posix-api-plugin/blob/master/src/main/java/hudson/os/PosixAPI.java) there as well as [the sole test](https://github.com/jenkinsci/jnr-posix-api-plugin/blob/master/src/test/java/hudson/os/PosixAPITest.java).

Note that JNR depends on ASM. This PR only removes JNR from the WAR, not ASM. (Removing ASM is more tricky, as core relies on it via Stapler.) Since we weren't declaring an explicit dependency on ASM before, we now declare one in place of a JNR dependency. I verified that this results in the following net change to the WAR:

```
@@ -47,18 +47,11 @@
 WEB-INF/lib/jcommon-1.0.23.jar
 WEB-INF/lib/jenkins-core-2.323-SNAPSHOT.jar
 WEB-INF/lib/jenkins-stapler-support-1.1.jar
-WEB-INF/lib/jffi-1.3.7.jar
-WEB-INF/lib/jffi-1.3.7-native.jar
 WEB-INF/lib/jfreechart-1.0.19.jar
 WEB-INF/lib/j-interop-2.0.8-kohsuke-1.jar
 WEB-INF/lib/j-interopdeps-2.0.8-kohsuke-1.jar
 WEB-INF/lib/jline-2.14.6.jar
 WEB-INF/lib/jna-5.10.0.jar
-WEB-INF/lib/jnr-a64asm-1.0.0.jar
-WEB-INF/lib/jnr-constants-0.10.3.jar
-WEB-INF/lib/jnr-ffi-2.2.9.jar
-WEB-INF/lib/jnr-posix-3.1.12.jar
-WEB-INF/lib/jnr-x86asm-1.0.2.jar
 WEB-INF/lib/json-lib-2.4-jenkins-3.jar
 WEB-INF/lib/jzlib-1.1.3-kohsuke-1.jar
 WEB-INF/lib/kxml2-2.3.0.jar
```

The following plugins are affected:

- [PAM Authentication](https://plugins.jenkins.io/pam-auth/): I opened jenkinsci/pam-auth-plugin#20 to add a dependency on the new `jnr-posix-api-plugin`.
- [CloudBees File Leak Detector](https://plugins.jenkins.io/file-leak-detector/): I opened jenkinsci/file-leak-detector-plugin#10 to add a dependency on the new `jnr-posix-api-plugin`.
- [Maven Repository Scheduled Cleanup](https://plugins.jenkins.io/maven-repo-cleaner/): jenkinsci/maven-repo-cleaner-plugin#4 dropped the dependency on JNR. That PR was merged on June 26, 2018; however, it has not been released.
- [SICCI for Xcode](https://plugins.jenkins.io/sicci_for_xcode/): This plugin is already deprecated and we already dropped support for it in #5560.
- [java.io.tmpdir cleaner](https://plugins.jenkins.io/tmpcleaner/): This plugin is already deprecated and we already dropped support for it in #5560.

The only one of these with significant adoption is PAM Authentication, so from my perspective we can move forward with this PR once jenkinsci/pam-auth-plugin#20 is merged and released.

### Proposed changelog entries

Removed: The [Java Native Runtime (JNR)](https://github.com/jnr) library has been removed from Jenkins core. Users of [PAM Authentication](https://plugins.jenkins.io/pam-auth/), [CloudBees File Leak Detector](https://plugins.jenkins.io/file-leak-detector/), and [Maven Repository Scheduled Cleanup](https://plugins.jenkins.io/maven-repo-cleaner/) must upgrade those plugins to compatible versions.

### Proposed upgrade guidelines

The [Java Native Runtime (JNR)](https://github.com/jnr) library has been removed from Jenkins core. Users of [PAM Authentication](https://plugins.jenkins.io/pam-auth/), [CloudBees File Leak Detector](https://plugins.jenkins.io/file-leak-detector/), and [Maven Repository Scheduled Cleanup](https://plugins.jenkins.io/maven-repo-cleaner/) must upgrade those plugins to compatible versions.

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by daniel-beck** [comment]
To clarify, Wadeck and I are requested as maintainers of `pam-auth`? Otherwise I'm a bit confused :)

This is deliberately not being done as a split/detached plugin, because so few plugins use this dependency in the first place?

**Comment by basil** [comment]
> To clarify, Wadeck and I are requested as maintainers of `pam-auth`?

Yes, exactly. The basic point of this change is moving JNR from core to `pam-auth`.

> This is deliberately not being done as a split/detached plugin, because so few plugins use this dependency in the first place?

Yes, exactly. With only a handful of production consumers of this functionality, it seems wasteful to install this plugin on all Jenkins controllers via the detached plugin mechanism.

**Comment by timja** [comment]
On-hold till https://github.com/jenkinsci/pam-auth-plugin/pull/20 is sorted

**Review by jglick — APPROVED** [review]
OK in principle.

**Comment by timja** [comment]
Ready to continue with this @basil ?

**Comment by basil** [comment]
> Ready to continue with this @basil ?

Yeah, it's the beginning of an LTS cycle and the `pam-auth` change has been released, so this seems like a good time.

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by basil** [comment]
End-to-end testing of this failed, so I am reverting it in #6299 and marking both this PR and #6299 as `skip-changelog`. This regression was never released, so there is no need to mention it in the release notes.

**Comment by basil** [comment]
Once https://github.com/jenkinsci/maven-hpi-plugin/pull/297 has been merged and released, and once `jnr-posix-api` is released with that version of the Maven HPI plugin, then this change can be reintroduced. I plan to propose a new PR at that time to reintroduce the change with thorough end-to-end testing.

**Comment by basil** [comment]
> I plan to propose a new PR at that time to reintroduce the change with thorough end-to-end testing.

Done in #6323.

**Pull request merged**
