### PR TITLE
[JENKINS-61738][2] Session hijacking protection hardening

### PR DESCRIPTION
**Pull request by Wadeck**
See [JENKINS-61738](https://issues.jenkins-ci.org/browse/JENKINS-61738).

_(Companion in jenkins-test-harness: https://github.com/jenkinsci/jenkins-test-harness/pull/205)_

Alternative of https://github.com/jenkinsci/jenkins/pull/4611 with "correct" way to write the test.

The test failure was due to the contextInitialized being called when the context is already started, that is wrong considering the JavaDoc contract.

There is no issue in terms of production code (at least until now), it was just a test design issue.

This PR could be merged after the original proposal as a better way to test the stuff, not needed to wait for this one.

### Proposed changelog entries

* Session hijacking protection hardening

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [n/a] Appropriate autotests or explanation to why this change has no tests
- [n/a] For dependency updates: links to external changelogs and, if possible, full diffs

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [x] There are at least 2 approvals for the pull request and no outstanding requests for change
- [x] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [x] Proper changelog labels are set so that the changelog can be generated automatically
- [n/a] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [n/a] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

### CODE REVIEW

**Review by jeffret-b — COMMENTED** [review]
Looks good. The test configuration is better in this version -- more realistic.

The same comments and changes from the original apply here.

Something is wrong with incrementals.

**Comment by daniel-beck** [comment]
On-holding for upstream release.

**Comment by daniel-beck** [comment]
Lacks changes from review feedback in the other PR.

**Review by daniel-beck — APPROVED** [review]
Looks reasonable. Nicer test adaptation than the other.

**Review by daniel-beck — CHANGES_REQUESTED** [review]
Needs changes from other PR applied.

**Comment by daniel-beck** [comment]
Build failures due to bad incremental?

**Review by daniel-beck — APPROVED** [review]

**Comment by Wadeck** [comment]
> Build failures due to bad incremental?

`Item incrementals:org/jenkins-ci/main/jenkins-test-harness/2.63-rc1318.3ddacb175e4d does not exist` (https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/main/jenkins-test-harness/2.63-rc1318.3ddacb175e4d/)

Seems so. Incremental is currently broken IIRC a message from Jesse recently. Waiting for a new release at this point ;)

**Review by jeffret-b — APPROVED** [review]
Looks good now. This is a better approach.

**Comment by jeffret-b** [comment]
I'm removing the "alternative" label as this one was chosen and the other was closed.

**Comment by jeffret-b** [comment]
I'm marking this as ready-for-merge. It can be merged after the customary 24 hour waiting period if there are no dissents.

**Pull request merged**
