### PR TITLE
Bump antisamy-markup-formatter from 1.0 to 2.1

### PR DESCRIPTION
**Pull request by basil**
Supersedes #5238. Fixes the `RequireUpperBoundDeps` issue and also bumps the detached plugin version to boot.

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by basil** [comment]
Reverted the bump of the detached plugin per recent conversations in other PRs.

**Comment by basil** [comment]
CC @jenkinsci/core-pr-reviewers

**Review by res0nance — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by basil** [comment]
Feel free to squash merge this PR (I can't add the label myself) if desired. In general I would usually prefer for all my PRs to be squash merged (for the reasons given in [this article](https://movementarian.org/blog/posts/github-prs/)), with the exception of those that consist of a well-curated series of commits (which this PR is not). But I know some members of this community feel strongly otherwise, so it doesn't matter either way to me.

**Comment by timja** [comment]
I generally squash merge most PRs here added label anyway

**Review by oleg-nenashev — APPROVED** [review]
Ideally Guava should be ideally fixed on the plugin side.
Not a big deal since it is a test dependency anyway

**Pull request merged**
