### PR TITLE
[JENKINS-63958] use new winstone 5.11.1 with downgraded Jetty version 9.4.30.v20200611

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: olivier lamy <olamy@apache.org>

See [JENKINS-63958](https://issues.jenkins-ci.org/browse/JENKINS-63958).

### Proposed changelog entries

* Downgrade Jetty to 9.4.30.v20200611 to fix the regression with wrong port added to URLs (regression in 2.261)
  * Winstone 5.11.1 changelog: https://github.com/jenkinsci/winstone/releases/tag/winstone-5.11.1
  * Root cause in Jetty: https://github.com/eclipse/jetty.project/issues/5417

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
I prefer to integrate this PR if the build passes

**Review by res0nance — APPROVED** [review]

**Comment by res0nance** [comment]
Favouring this over #5017

**Review by timja — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
I plan to merge it once the CI passes

**Comment by oleg-nenashev** [comment]
Winstone 5.11.1 changelogs have been published: Downgrade Jetty to 9.4.30.v20200611 to fix the regression with wrong port added to URLs  . We are all set here IMHO

**Comment by oleg-nenashev** [comment]
Looks like the PR description modification has retriggered CI... 🤦 this glitch again

image

**Comment by oleg-nenashev** [comment]
As discussed in the chat with @timja , will go ahead and merge it without waiting for the JDK8 CI. The release flow runs the same CI anyway.

image

**Comment by jglick** [comment]
Picking up https://github.com/jenkinsci/winstone/pull/125, fine.

**Comment by jglick** [comment]
If the bug with the port was reproducible somehow, has anyone attempted to cover this with an HtmlUnit regression test?

**Comment by Mike4Online** [comment]
My Jenkins 2.261 system now shows Jenkins 2.263 as an available upgrade, but automatic upgrade fails with the following:

`Upgrade to Jenkins 2.263 failed: Failed to download from https://updates.jenkins.io/download/war/2.263/jenkins.war (redirected to: https://get.jenkins.io/war/2.263/jenkins.war).`

Browsing to the above URL shows that the **2.263** sub-folder is not present.

**Comment by jglick** [comment]
```console
$ curl -IL https://updates.jenkins.io/download/war/2.263/jenkins.war
HTTP/1.1 302 Found
Date: Tue, 20 Oct 2020 16:41:23 GMT
Server: Apache/2.4.29 (Ubuntu)
Location: https://get.jenkins.io/war/2.263/jenkins.war
Content-Type: text/html; charset=iso-8859-1

HTTP/2 404 
server: nginx/1.19.1
date: Tue, 20 Oct 2020 16:41:23 GMT
content-type: text/plain; charset=utf-8
content-length: 10
x-content-type-options: nosniff
strict-transport-security: max-age=15724800; includeSubDomains
```

Might correct itself after something finishes uploading, TBD.

**Comment by Mike4Online** [comment]
Still not working.  I opened [https://github.com/jenkins-infra/jenkins.io/issues/3885](https://github.com/jenkins-infra/jenkins.io/issues/3885)

**Comment by Mike4Online** [comment]
@jglick , in your CURL test, Content-Type text/html is not correct for a .war file. Should be application/octet-stream or some other binary mime type.  And the redirected link [https://get.jenkins.io/war/2.263/jenkins.war](https://get.jenkins.io/war/2.263/jenkins.war) should permit download from a web browser (it gives Not Found instead).

**Pull request merged**
