### PR TITLE
JENKINS-62006 Fix a classloading issue while executing ProcessTree.get()

### PR DESCRIPTION
**Pull request by timja**
See [JENKINS-62006](https://issues.jenkins-ci.org/browse/JENKINS-62006).

I've tested in azure-container-agents plugin and I can now run freestyle builds over remoting where that wasn't possible before, I expect this fixed the slack plugin and digital ocean plugin issue as well, cc @halkeye.

Also tested running a freestyle build on the controller and there were no issues

## Test this pull request

```command
docker run --rm -ti -p 8080:8080 -e ID=5367 -e MERGE_WITH=master jenkins/core-pr-tester
```

### Proposed changelog entries

* Entry 1: JENKINS-62006, Fix a classloading issue while executing ProcessTree.get()
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by Vlatombe — APPROVED** [review]
Ok, so `Jenkins.getInstanceOrNull` was the one pulling `ServletException` which failed on agents. `Channel.current()` being remoting only, should be safe to be called first

**Review by res0nance — APPROVED** [review]
This makes sense

**Review by jglick — COMMENTED** [review]
Probably better to keep the current order of operations and just use the `JenkinsJVM` API which was created for this purpose.

BTW this sounds like a good first project to use `RealJenkinsRule` in core? Assuming the error is reproducible merely by running something in Winstone.

**Comment by timja** [comment]
Right I knew there was something but couldn’t find it...

**Comment by timja** [comment]
> Probably better to keep the current order of operations and just use the `JenkinsJVM` API which was created for this purpose.
> 
> BTW this sounds like a good first project to use `RealJenkinsRule` in core? Assuming the error is reproducible merely by running something in Winstone.

Will take a look

**Comment by halkeye** [comment]
`docker run --rm -ti -p 8080:8080 -e ID=5367 jenkins/core-pr-tester` right? I should get a min to test this weekend

**Comment by timja** [comment]
> `docker run --rm -ti -p 8080:8080 -e ID=5367 jenkins/core-pr-tester` right? I should get a min to test this weekend

yeah it's in the description

**Comment by res0nance** [comment]
> `docker run --rm -ti -p 8080:8080 -e ID=5367 jenkins/core-pr-tester` right? I should get a min to test this weekend

If this works for Gavin as well I feel its worth marking this an lts-candidate so the next LTS release can have this fix

**Comment by halkeye** [comment]
totally fixes my issue on digital ocean plugin

image

**Review by halkeye — APPROVED** [review]

**Comment by timja** [comment]
> BTW this sounds like a good first project to use `RealJenkinsRule` in core? Assuming the error is reproducible merely by running something in Winstone.

Tried reproducing it in https://github.com/jenkinsci/azure-container-agents-plugin/pull/66 and wasn't able to 😢.

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Review by oleg-nenashev — APPROVED** [review]
Should be fine in common scenarios.
I am not sure Jenkins Test Harness would handle it correctly in the combination with common unit tests due to the missing flag reset. But whatever

**Review by basil — APPROVED** [review]

**Review by jglick — APPROVED** [review]
(if it works)

**Comment by jglick** [comment]
JENKINS-26677 would make mistakes like this appear more consistently and with a more easily diagnosed message.

**Pull request merged**
