### PR TITLE
[JENKINS-68129] Fix dropdown chevrons not separating links and overflowing

### PR DESCRIPTION
**Pull request by janfaracik**
See [JENKINS-68129](https://issues.jenkins.io/browse/JENKINS-68129) and [JENKINS-68097](https://issues.jenkins.io/browse/JENKINS-68097)

Required quite a bit of a refactor to do this but it's made the chevron logic a bit simpler which is nice, also managed to remove the "inside" class as part of this without hopefully impacting anything.

I think things could (and will) be simplified in the future in this area, it's quite complex due to all the permutations but this iteration should work better than before.

**Preview**
image

### How to reproduce
* I went to the credentials page, clicked inspect element on the domain link and duplicated it several times. From there you could see that there was no padding initially and links overlapped. With the fix this no longer happens.
* I've also posted a comment below with a short snippet of `jelly` to reproduce most of the common states for a dropdown chevron link

### Proposed changelog entries

* Fix dropdown chevrons not separating links and overflowing

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

### CODE REVIEW

**Comment by janfaracik** [comment]
I've been using this bit of `jelly` to test this, might be helpful for reviewers or for the future:

```
      <div style="display: inline; border: 2px solid black">
        <a class="model-link inside">Hello world</a>
        <a class="model-link inside">Hello world</a>
        <a class="model-link inside">Hello world</a>
      </div>
      <br/>
      <div>
        <a class="model-link ">Hello world</a>
        <a class="model-link ">Hello world</a>
        <a class="model-link ">Hello world</a>
      </div>
      <br/>
      <div>
        <a class="jenkins-table__link model-link ">Hello world</a>
        <a class="jenkins-table__link jenkins-table__badge model-link">Hello world</a>
        <a class="jenkins-table__link model-link ">Hello world</a>
        <a class="jenkins-table__link model-link ">Hello world</a>
        <a class="jenkins-table__link model-link ">Hello world</a>
      </div>
      <br/>
      <div>
        There are many variations of passages of <a href="#" class="model-link model-link--float">Lorem Ipsum</a> available, but the majority have suffered alteration in some form, by injected humour, or randomised words <a href="#" class="model-link model-link--float">which don't look even slightly</a> believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.
      </div>
      <br/>
      <table class="jenkins-table">
        <thead>
          <th>
            hello
          </th>
          <th>
            hello
          </th>
          <th>
            hello
          </th>
        </thead>
        <tbody>
          <tr>
            <td>
              <a class="jenkins-table__link model-link ">Hello world</a>
              <a class="jenkins-table__link jenkins-table__badge model-link">Hello world</a>
              <a class="jenkins-table__link model-link ">Hello world</a>
            </td>
            <td>
              Hello world
              <a class="jenkins-table__link jenkins-table__badge model-link">Hello world</a>
            </td>
            <td>
              <a class="jenkins-table__link model-link ">Hello world</a>
              <a class="jenkins-table__link jenkins-table__badge model-link">Hello world</a>
            </td>
          </tr>
        </tbody>
      </table>
```

Essentially contains all the various ways the chevrons can be displayed, there's quite a few hence the complexity.

**Review by NotMyFault — COMMENTED** [review]
Looks good so far, based on your example provided.
Minor nit with the account dropdown though:

**Review by basil — COMMENTED** [review]
I ran interactive tests with this change and compared Jenkins 2.339 with a build including this pull request. The change looks good. Steps I took to exercise the change:

1. I tested the node labels by editing the built-in node, adding the labels "foo", "bar", and "foobar", and ensuring there was horizontal space between each one, just as in 2.339.
2. I tested the credential domains by running the following in the Script Console:

```groovy
import com.cloudbees.plugins.credentials.CredentialsStore
import com.cloudbees.plugins.credentials.CredentialsProvider
import com.cloudbees.plugins.credentials.domains.Domain
import com.cloudbees.plugins.credentials.domains.HostnameSpecification

Domain domainFoo = new Domain("domainFoo", "Hostname domain", [new HostnameSpecification("foo.com", "")])
Domain domainBar = new Domain("domainBar", "Path domain", [new HostnameSpecification("bar.com", "")])

CredentialsStore store = CredentialsProvider.lookupStores(Jenkins.get())[0]
store.addDomain(domainFoo, [])
store.addDomain(domainBar, [])
```

then going to http://127.0.0.1:8080/credentials/ and verifying that in the "domains" list I could see each domain with horizontal space between each one, just as in 2.339.

My interactive testing indicates that this change fixes the reported problem. I will rely on others to review the implementation.

**Review by timja — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]

**Comment by NotMyFault** [comment]
This PR is now ready for merge. We will merge it after ~24 hours if there is no negative feedback.
Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process.
Thanks!

**Comment by MarkEWaite** [comment]
@janfaracik thanks so much for this fix.  Can you resolve the conflicts so that it can be run through CI in preparation for merge?

**Comment by basil** [comment]
Conflict with #6479.

**Comment by janfaracik** [comment]
Resolved.

**Comment by daniel-beck** [comment]
Causes [JENKINS-68390](https://issues.jenkins.io/browse/JENKINS-68390)

**Comment by daniel-beck** [comment]
Causes [JENKINS-69245](https://issues.jenkins.io/browse/JENKINS-69245)

**Pull request merged**
