### PR TITLE
Fix bug listed as fixed in wrong version

### PR DESCRIPTION
**Pull request by thomassuckow**

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Good catch, thanks for the fix

**Comment by thomassuckow** [comment]
Wait! I may have moved the wrong issue

**Comment by thomassuckow** [comment]
Ok. While I did grab the wrong "Build History" entry than what I meant, both are actually in 1.615. So moving them both now.

**Comment by thomassuckow** [comment]
Closing, fixed in parallel by @daniel-beck

**Comment by daniel-beck** [comment]
Missed this PR, sorry about that!

**Pull request closed without merging**
