### PR TITLE
Rename `base-styles-v2.less` to `styles.less`

### PR DESCRIPTION
**Pull request by janfaracik**
This makes it obvious that this is the main CSS file.

Cheers @basil 👍 

### Proposed changelog entries

* N/A

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@basil @jenkinsci/sig-ux 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by NotMyFault — COMMENTED** [review]
Worth to note that this path has one call in JTH: https://github.com/jenkinsci/jenkins-test-harness/blob/master/src/main/java/org/jvnet/hudson/test/JenkinsRule.java#L2282

**Review by timja — APPROVED** [review]

**Review by basil — COMMENTED** [review]
Very nice! I did a code search for `base-styles-v2` and found no references to this symbol besides the one in `jenkins-test-harness`. So once we take care of the test harness, this should be ready to merge.

Before this PR, I don't get any warnings when running `mvn clean verify -Dtest=lib.form.FormTest#autocompleteOffByDefault`:

```
$ mvn clean verify -Dtest=lib.form.FormTest#autocompleteOffByDefault
[…]
[INFO] Running lib.form.FormTest
=== Starting autocompleteOffByDefault(lib.form.FormTest)
   0.032 [id=17]        INFO    o.jvnet.hudson.test.WarExploder#explode: Using jenkins.war resources from /home/basil/src/jenkinsci/jenkins/war/target/jenkins
   0.162 [id=17]        INFO    o.jvnet.hudson.test.JenkinsRule#createWebServer: Running on http://localhost:38855/jenkins/
   0.351 [id=31]        INFO    jenkins.InitReactorRunner$1#onAttained: Started initialization
   0.352 [id=34]        INFO    jenkins.InitReactorRunner$1#onAttained: Listed all plugins
   0.944 [id=32]        INFO    jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
   0.949 [id=40]        INFO    jenkins.InitReactorRunner$1#onAttained: Started all plugins
   0.951 [id=31]        INFO    jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
   1.437 [id=42]        INFO    jenkins.InitReactorRunner$1#onAttained: System config loaded
   1.438 [id=34]        INFO    jenkins.InitReactorRunner$1#onAttained: System config adapted
   1.438 [id=34]        INFO    jenkins.InitReactorRunner$1#onAttained: Loaded all jobs
   1.439 [id=38]        INFO    jenkins.InitReactorRunner$1#onAttained: Configuration for all jobs updated
   1.547 [id=38]        INFO    jenkins.InitReactorRunner$1#onAttained: Completed initialization
   3.728 [id=17]        INFO    hudson.lifecycle.Lifecycle#onStatusUpdate: Stopping Jenkins
WARN: The method class org.apache.commons.logging.impl.SLF4JLogFactory#release() was invoked.
WARN: Please see http://www.slf4j.org/codes.html#release for an explanation.
   3.857 [id=17]        INFO    hudson.lifecycle.Lifecycle#onStatusUpdate: Jenkins stopped
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.316 s - in lib.form.FormTest
[…]
```

After this PR, I get the following spurious warnings:

```
$ mvn clean verify -Dtest=lib.form.FormTest#autocompleteOffByDefault
[…]
[INFO] Running lib.form.FormTest
=== Starting autocompleteOffByDefault(lib.form.FormTest)
   0.034 [id=17]        INFO    o.jvnet.hudson.test.WarExploder#explode: Using jenkins.war resources from /home/basil/src/jenkinsci/jenkins/war/target/jenkins
   0.164 [id=17]        INFO    o.jvnet.hudson.test.JenkinsRule#createWebServer: Running on http://localhost:39351/jenkins/
   0.356 [id=31]        INFO    jenkins.InitReactorRunner$1#onAttained: Started initialization
   0.360 [id=32]        INFO    jenkins.InitReactorRunner$1#onAttained: Listed all plugins
   0.953 [id=37]        INFO    jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
   0.959 [id=30]        INFO    jenkins.InitReactorRunner$1#onAttained: Started all plugins
   0.962 [id=31]        INFO    jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
   1.379 [id=31]        INFO    jenkins.InitReactorRunner$1#onAttained: System config loaded
   1.380 [id=40]        INFO    jenkins.InitReactorRunner$1#onAttained: System config adapted
   1.380 [id=40]        INFO    jenkins.InitReactorRunner$1#onAttained: Loaded all jobs
   1.381 [id=37]        INFO    jenkins.InitReactorRunner$1#onAttained: Configuration for all jobs updated
   1.490 [id=34]        INFO    jenkins.InitReactorRunner$1#onAttained: Completed initialization
   2.622 [id=17]        WARNING c.g.h.DefaultCssErrorHandler#error: CSS error: 'http://localhost:39351/jenkins/static/34ab9ac8/jsbundles/styles.css' [2873:17] Error in class selector. (Invalid token "only". Was expecting: <IDENT>.)
   2.622 [id=17]        WARNING c.g.h.DefaultCssErrorHandler#warning: CSS warning: 'http://localhost:39351/jenkins/static/34ab9ac8/jsbundles/styles.css' [2873:17] Ignoring the whole rule.
   2.623 [id=17]        WARNING c.g.h.DefaultCssErrorHandler#error: CSS error: 'http://localhost:39351/jenkins/static/34ab9ac8/jsbundles/styles.css' [2892:33] Error in class selector. (Invalid token "only". Was expecting: <IDENT>.)
   2.623 [id=17]        WARNING c.g.h.DefaultCssErrorHandler#warning: CSS warning: 'http://localhost:39351/jenkins/static/34ab9ac8/jsbundles/styles.css' [2892:33] Ignoring the whole rule.
   2.623 [id=17]        WARNING c.g.h.DefaultCssErrorHandler#error: CSS error: 'http://localhost:39351/jenkins/static/34ab9ac8/jsbundles/styles.css' [2911:49] Error in class selector. (Invalid token "only". Was expecting: <IDENT>.)
   2.624 [id=17]        WARNING c.g.h.DefaultCssErrorHandler#warning: CSS warning: 'http://localhost:39351/jenkins/static/34ab9ac8/jsbundles/styles.css' [2911:49] Ignoring the whole rule.
   3.736 [id=17]        INFO    hudson.lifecycle.Lifecycle#onStatusUpdate: Stopping Jenkins
WARN: The method class org.apache.commons.logging.impl.SLF4JLogFactory#release() was invoked.
WARN: Please see http://www.slf4j.org/codes.html#release for an explanation.
   3.901 [id=17]        INFO    hudson.lifecycle.Lifecycle#onStatusUpdate: Jenkins stopped
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.38 s - in lib.form.FormTest
[…]
```

The reason for this is that the workaround in https://github.com/jenkinsci/jenkins-test-harness/blob/c72c458c5103760bb11336369ea7db1267d78af3/src/main/java/org/jvnet/hudson/test/JenkinsRule.java#L2282= no longer applies as of this PR. Hence the original problem is re-exposed, effectively regressing jenkinsci/jenkins-test-harness#275.

To maintain the status quo, we need a PR to `jenkins-test-harness` updating https://github.com/jenkinsci/jenkins-test-harness/blob/c72c458c5103760bb11336369ea7db1267d78af3/src/main/java/org/jvnet/hudson/test/JenkinsRule.java#L2282= to be compatible with this PR. Note that since `jenkins-test-harness` supports core versions 2.204 to weekly, that change will need to be conditional on core version as in https://github.com/jenkinsci/jenkins-test-harness/blob/c72c458c5103760bb11336369ea7db1267d78af3/src/main/java/org/jvnet/hudson/test/JenkinsRule.java#L1115=.

Once an incremental PR build of the test harness change is available and I can confirm that the status quo is maintained, I am ready to approve this PR.

**Comment by timja** [comment]
> The reason for this is that the workaround in [jenkinsci/jenkins-test-harness@c72c458/src/main/java/org/jvnet/hudson/test/JenkinsRule.java#L2282=](https://github.com/jenkinsci/jenkins-test-harness/blob/c72c458c5103760bb11336369ea7db1267d78af3/src/main/java/org/jvnet/hudson/test/JenkinsRule.java#L2282=) no longer applies as of this PR. Hence the original problem is re-exposed, effectively regressing https://github.com/jenkinsci/jenkins-test-harness/pull/275.

I've filed a draft PR to fix those warnings, https://github.com/jenkinsci/jenkins/pull/6471
No time to test right now past the PR build running.

**Review by basil — APPROVED** [review]
This PR is now ready for merge. We will merge it after approximately 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process. Thanks!

**Pull request merged**
