### PR TITLE
[JENKINS-13545] use dialogs to delete computers, views, clouds, users and logrecorders

### PR DESCRIPTION
**Pull request by mawinter69**
Use the confirm dialog approach for computers, views and clouds

See [JENKINS-13545](https://issues.jenkins.io/browse/JENKINS-13545).

### Testing done

Testing was done by manually deleting computers, views and clouds.
Doing so in the default language english and in german to verify translations are applied properly.

### Proposed changelog entries

- Use dialogs to delete computers, views, clouds, users and log recorders instead of dedicated pages.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] The Jira issue, if it exists, is well-described.
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.

### Desired reviewers

N/A

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [x] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [x] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [x] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [x] Proper changelog labels are set so that the changelog can be generated automatically.
- [x] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [x] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

### CODE REVIEW

**Review by uhafner — APPROVED** [review]
LGTM, thanks!

A possible optional improvement: The new code contains a lot of duplications. It would make sense to create a new jelly file responsible for deleting things. Then we can replace (in a followup PR) the ugly browser delete dialog with a native modal dialog using Jenkins styling. Then we need to touch only a single file anymore. Otherwise we need to search again the whole code base for tasks that delete things.

**Comment by mawinter69** [comment]
The task.jelly is already the single place that is used. Only here and in some javascript files changes are required to have native modal dialogs I think as long as the requiresConfirmation option is set.

**Comment by uhafner** [comment]
> The task.jelly is already the single place that is used. Only here and in some javascript files changes are required to have native modal dialogs I think as long as the requiresConfirmation option is set.

`task.jelly` is a good candidate for the God-Class anti pattern. But you are right, UI changes hopefully can be done in the `task.jelly` file only. 

But since you changed more than one file, you simply violated the DRY principle. So rather than always writing
```
<l:task 
        confirmationMessage="${%delete.confirm(it.name)}" 
        href="${rootURL}/${it.url}doDelete" 
        icon="icon-edit-delete icon-md" 
        permission="${it.DELETE}" 
        title="${%Delete Agent}" 
        post="true" 
        requiresConfirmation="true"/>
``` 
a developer would prefer a simpler template like
```
<l:delete 
        message="${%delete.confirm(it.name)}" 
        urlPrefix="${rootURL}/${it.url}" 
        permission="${it.DELETE}" 
        title="${%Delete Agent}"/>
```

But such is change is optional, we have a lot of such DRY examples in Jenkins UI code yet 🙈

**Review by NotMyFault — APPROVED** [review]
Really looking forward to this!

**Comment by mawinter69** [comment]
see #7938 which is on top of this change
It replaces the browser confirm, alert prompt with dialogs

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by MarkEWaite** [comment]
Causes a test failure in the matrix-project plugin as discussed in https://github.com/jenkinsci/bom/pull/2070#issuecomment-1547010232

Reported in Jenkins Jira as [JENKINS-71265](https://issues.jenkins.io/browse/JENKINS-71265)

**Comment by MarkEWaite** [comment]
@mawinter69 this seems to have caused [JENKINS-71429](https://issues.jenkins.io/browse/JENKINS-71429) where attempts to delete a user from the trash can icon of the "Manage Jenkins" ==> "Users" page results in a 404 page not found exception.  Would you be willing to investigate a possible fix for user deletion?

**Comment by mawinter69** [comment]
looking into it

**Comment by MarkEWaite** [comment]
> looking into it

Thanks @mawinter69 for the fix proposed and approved in

* #8131

**Pull request merged**
