### PR TITLE
Move Node monitoring option to app bar

### PR DESCRIPTION
**Pull request by janfaracik**
PR to move the 'Node monitoring' option to the Nodes' app bar from the side panel. Also slight tweaks to the page to remove the sidebar and adds a short description to explain what the pages does.

**Before**

image

**After**

image

**Before**

image

**After**

image

### Testing done

* Node monitoring works as before

### Proposed changelog entries

- Move Node monitoring option to app bar.

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@jenkinsci/sig-ux 

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/8381"></a>

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by daniel-beck** [comment]
What underlying principle motivates this change? It does not seem to be justified by https://weekly.ci.jenkins.io/design-library/AppBar/

**Comment by janfaracik** [comment]
> What underlying principle motivates this change? It does not seem to be justified by https://weekly.ci.jenkins.io/design-library/AppBar/

It'd align more so with https://weekly.ci.jenkins.io/design-library/Layouts/ 'Don't include actions or external pages in your sidebar, these belong in the top app bar'. It'd be consistent with the 'Log Recorders' interface.

**Review by Wadeck — COMMENTED** [review]
Seems to be fine security wise

**Review by NotMyFault — APPROVED** [review]

**Comment by timja** [comment]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by daniel-beck** [comment]
> 'Don't include actions or external pages in your sidebar, these belong in the top app bar'. It'd be consistent with the 'Log Recorders' interface.

This rule basically invalidates every `RootAction`.

**Comment by basil** [comment]
This change broke some core tests due to a markup change, so how do we know that it won't break plugin tests if we haven't run PCT?

**Comment by NotMyFault** [comment]
> This change broke some core tests due to a markup change, so how do we know that it won't break plugin tests if we haven't run PCT?

=> https://github.com/jenkinsci/bom/pull/2432

**Review by basil — APPROVED** [review]
Great!

**Comment by NotMyFault** [comment]
'
/label ready-for-merge

---

This PR is now ready for merge. We will merge it after ~24 hours if there is no negative feedback.
Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process.
Thanks!

**Pull request merged**
