### PR TITLE
[JENKINS-68296] Restore actions icon lookup with size

### PR DESCRIPTION
**Pull request by alecharp**
See [JENKINS-68296](https://issues.jenkins.io/browse/JENKINS-68296).

Prior to Jenkins `2.341` (jenkinsci/jenkins#6395), in the projects' actions sidepanel, the icons for each actions was search with a CSS class suffixed to its name. This value is used in https://github.com/jenkinsci/jenkins/blob/bbd7ca2c4d63067ecc61c4a7840378520b761a41/core/src/main/java/hudson/Functions.java#L2345
passed to https://github.com/jenkinsci/jenkins/blob/bbd7ca2c4d63067ecc61c4a7840378520b761a41/core/src/main/java/hudson/Functions.java#L2290 to https://github.com/jenkinsci/jenkins/blob/bbd7ca2c4d63067ecc61c4a7840378520b761a41/core/src/main/java/org/jenkins/ui/icon/IconSet.java#L203 all the way to https://github.com/jenkinsci/jenkins/blob/bbd7ca2c4d63067ecc61c4a7840378520b761a41/core/src/main/java/org/jenkins/ui/icon/IconSet.java#L175.

When the icons are added in the `IconSet` maps https://github.com/jenkinsci/jenkins/blob/bbd7ca2c4d63067ecc61c4a7840378520b761a41/core/src/main/java/org/jenkins/ui/icon/IconSet.java#L145, they are suffixed with their CSS class size (`icon-md`, `icon-sm`, etc) (because of https://github.com/jenkinsci/jenkins/blob/bbd7ca2c4d63067ecc61c4a7840378520b761a41/core/src/main/java/org/jenkins/ui/icon/Icon.java#L131 and example of usage here: https://github.com/jenkinsci/jenkins/blob/bbd7ca2c4d63067ecc61c4a7840378520b761a41/core/src/main/java/org/jenkins/ui/icon/IconSet.java#L554). This is important because looking in the map, only with the action's `iconClassName`, will never return the correct icon. 

After Jenkins `2.341` (included), the suffix was removed from `actions.jelly` https://github.com/jenkinsci/jenkins/blob/bbd7ca2c4d63067ecc61c4a7840378520b761a41/core/src/main/resources/lib/hudson/actions.jelly#L40. The initial search of the icon was returning `null`. But, a second iteration was done, transforming the icon reference with the prefix `icon-` and adding the size CSS class https://github.com/jenkinsci/jenkins/blob/bbd7ca2c4d63067ecc61c4a7840378520b761a41/core/src/main/java/hudson/Functions.java#L2307. The core icons svg are added using this prefix in `IconSet#initializeSVGs` function https://github.com/jenkinsci/jenkins/blob/bbd7ca2c4d63067ecc61c4a7840378520b761a41/core/src/main/java/org/jenkins/ui/icon/IconSet.java#L554. So, in this second iteration, if the reference of the icon in the jelly file is `redo`, the icon is search with `icon-redo` and then with `.icon-redo.icon-md`. This is working well for core icons, and other plugins that were already naming their icons `icon-XXX` (because the `IconSet#toNormalizedIconNameClass` is only adding `icon-` prefix if it's not present). However, not all plugins are using this prefix and so, their icons were not found. This is the case for the Gitlab Branch Source plugin.

Asking for the action icons with the CSS class for its size is fixing the problem the Gitlab Branch source plugin and with no size effect. 

<details>
<summary>Multibranch Pipeline sidepanel</summary>
Before:

MultiBranch Pipeline sidepanel

After:

MultiBranch Pipeline sidepanel

</details>

<details>
<summary>Branch sidepanel</summary>
Before:

Branch sidepanel

After:

Branch sidepanel

</details>

<details>
<summary>Run sidepanel</summary>
Before:

Run sidepanel

After:

Run sidepanel

</details>

### Proposed changelog entries

* Display icons searched without an icon size CSS value (regression in 2.341).

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@basil @janfaracik @NotMyFault @jenkinsci/sig-ux 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Review by basil — APPROVED** [review]
Very nice! So the root cause was the same as [JENKINS-68270](https://issues.jenkins.io/browse/JENKINS-68270). Since the same original commit introduced two very similar bugs, I went back and audited the original commit to see if it had introduced any similar bugs, but fortunately it looks like it only introduced JENKINS-68270 and this bug.

**Comment by alecharp** [comment]
I think I might have introduce another problem but I cannot reproduce it. This fix the problem in the first lookup of the icon, but when it's not found, the _id_ of the icon is _normalized_ and suffixed with the icon size class: https://github.com/jenkinsci/jenkins/blob/eb997ae74d74bdd93d131b79ed8adfb2b33942f2/core/src/main/java/hudson/Functions.java#L2307

The problem is that, with this fix, the icon size class would be applied twice, `redo icon-md` would be looked up with `redo icon-md` then `.redo.icon-md` and if not found, it would be `icon-redo icon-md icon-md`.

**Comment by alecharp** [comment]
turns out my thought was disproved by tests. I couldn't run the `test` module tests locally, let's see what the CI says.

**Comment by timja** [comment]
> turns out my thought was disproved by tests. I couldn't run the `test` module tests locally, let's see what the CI says.

via IDE or via maven?

IDE doesn't work for me but maven works, occasionally I hit issues with tests not passing on macOS but normally easy enough to fix or ignore them

**Comment by alecharp** [comment]
> via IDE or via maven?

both in fact. But maybe because I tried to run only the failing tests reported here before.

**Comment by timja** [comment]
> > via IDE or via maven?
> 
> both in fact. But maybe because I tried to run only the failing tests reported here before.

I generally do a full compilation and then `cd` to the directory and run the single test I want. Not sure if that's what you're doing.

(not the most efficient but it works)

**Comment by alecharp** [comment]
> I generally do a full compilation and then cd to the directory and run the single test I want. Not sure if that's what you're doing.
> (not the most efficient but it works)

I tried `-pl core,test -am -Dtest=xxx`, I tried a full packaging and use `-pl` again. Didn't try the `cd`. Failure was about the `war/target/classes` being a folder.. 

However, reverting my last commit solved the tests failures.

**Comment by alecharp** [comment]
> Is this still an issue? Shall we go forward with this as a better fix than none?

I don't see any issues anymore. What I thought could be one yesterday was disproved by tests failures here. We are good to go now.

**Pull request merged**
