### PR TITLE
[JENKINS-51684] - XmlFile can now read gzipped files.

### PR DESCRIPTION
**Pull request by tfiskgul**
See [JENKINS-51684](https://issues.jenkins-ci.org/browse/JENKINS-51684).

### Proposed changelog entries

* Internal: Added read only support for gzipped XML files

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### CODE REVIEW

**Review by oleg-nenashev — COMMENTED** [review]
Sounds like a hack TBH. I agree with the idea, but IMHO we should move towards pluggable XmlFile storage.

E.g. what https://github.com/jenkinsci/jenkins/pull/3393 does

**Comment by oleg-nenashev** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-51966

**Comment by tfiskgul** [comment]
@oleg-nenashev thanks for your feedback. Agreed, this is kind of hacky. I experimented with making it transparent (it automatically chose .gz if the file specified was not found, but a file with the same path ending in .gz was present), which was even hackier, but decided not to do it. Pluggable storage sounds nice, but seems to be a big change. I guess pluggable storage could take quite some time for it to be reviewed, accepted and released?

**Comment by daniel-beck** [comment]
This is not unlike the similar "feature" for log files, which needed manual hacking around in JENKINS_HOME to work, or the much later developed https://plugins.jenkins.io/compress-buildlog, to work.

I don't consider hidden features like this a net positive for Jenkins (which already has way too many of these). Not to mention potential bad interactions between this and existing plugins, like Compress Buildlog vs. BFA.

For these reasons, I'd rather not see this merged. -0.5 perhaps?

**Comment by tfiskgul** [comment]
I understand your points and agree, a pluggable extensible XmlFile storage is better. Thanks for your feedback, I'm closing this in favor of #3393.

**Comment by oleg-nenashev** [comment]
@tfiskgul Thanks anyway!

**Pull request closed without merging**
