### PR TITLE
[JENKINS-73539] Disable YUI by default

### PR DESCRIPTION
**Pull request by timja**
See [JENKINS-73539](https://issues.jenkins.io/browse/JENKINS-73539).

This is the culmination of a lot of work over the years to slowly replace existing components that were built with YUI to alternatives.
A few examples:
* https://github.com/jenkinsci/jenkins/pull/6408
* https://github.com/jenkinsci/jenkins/pull/9453
* https://github.com/jenkinsci/jenkins/pull/9395
* https://github.com/jenkinsci/jenkins/pull/6084
* https://github.com/jenkinsci/jenkins/pull/5177

A number of plugins and core changes have been prepared to make this possible.
See the tracking spreadsheet: https://docs.google.com/spreadsheets/d/1UjvtFmNmEdjMN5DUoFxJfBryA8q-E5_HwOzVKbVG9b0/edit?gid=969462704#gid=969462704

We aren't removing YUI at this time as @MarkEWaite requested that we wait till after the next LTS cutoff so-as vendors can change the default back if they still require YUI in their commercial products.

### Testing done

Checked elements in the browser tools, by default no yui is there.

Disabled the flag in user settings and yui appears

Ran `System.setProperty("jenkins.model.experimentalflags.RemoveYuiUserExperimentalFlag.defaultValue", "false")` in the script console and yui appears without having to set a flag.

Clicked around and no issues found.
ATH is successful: https://github.com/jenkinsci/acceptance-test-harness/pull/1861

PCT is successful: https://github.com/jenkinsci/bom/pull/4084.

### Proposed changelog entries

- Disable the Yahoo! User Interface library by default

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [x] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Comment by mawinter69** [comment]
Not sure if this is the right approach. The flag is a user specific thing, so when a plugin is installed that still requires YUI, it means that each and every user of that instance needs to enable it in their personal settings.
I would remove that experimental flag and instead introduce a system property that allows to define if YUI should be enabled or not. That way the admin of an instance can define at startup that YUI is still needed.

**Review by janfaracik — APPROVED** [review]
LGTM <3 Been a long time coming for this one.

**Review by krisstern — APPROVED** [review]

**Comment by timja** [comment]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by mawinter69** [comment]
good enough
Does it need the `upgrade-guide-needed` label?

**Comment by kmartens27** [comment]
Hi @timja, I'm currently putting together the upgrade guide for 2.492.1 and for the YUI disabled entry, I wanted to check and confirm what the process is to re-enable YUI if needed by an admin.

Would it just be a matter of updating `true` to `false` here?:

    public Boolean getDefaultValue() {
        return true;
        return SystemProperties.getBoolean(RemoveYuiUserExperimentalFlag.class.getName() + ".defaultValue", true);

If there are more steps necessary than that, would you be able to share what the exact steps are for re-enabling YUI?

**Comment by timja** [comment]
> Hi @timja, I'm currently putting together the upgrade guide for 2.492.1 and for the YUI disabled entry, I wanted to check and confirm what the process is to re-enable YUI if needed by an admin.
> 
> Would it just be a matter of updating `true` to `false` here?:
> 
> ```
> public Boolean getDefaultValue() {
>     return true;
>     return SystemProperties.getBoolean(RemoveYuiUserExperimentalFlag.class.getName() + ".defaultValue", true);
> ```
> 
> If there are more steps necessary than that, would you be able to share what the exact steps are for re-enabling YUI?

Set this system property:

```
-Djenkins.model.experimentalflags.RemoveYuiUserExperimentalFlag.defaultValue="false"
```

**Comment by kmartens27** [comment]
Thanks very very much!

**Pull request merged**
