### PR TITLE
[JENKINS-68221] Breadcrumbs no longer bold (regression in 2.340)

### PR DESCRIPTION
**Pull request by frankie139506**
See [JENKINS-68221](https://issues.jenkins-ci.org/browse/JENKINS-68221).

Before: font size is 0.85rem and font weight is 500

image
After: font size is 1rem and font weight is bold

image

### Proposed changelog entries
* regression to Jenkins 2.340

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] (If applicable) Jira issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [X] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by timja** [comment]
Unsure if it should be changed, I think it looks fine without the bold.

(When I asked people for feedback on the weekly version that came in on, I did hear that they had noticed this changed but they didn't seem to mind)

cc @janfaracik

**Review by NotMyFault — COMMENTED** [review]
iirc, that was an intentional change, which does still look fine to me nevertheless.
-0 from me for this PR.

**Comment by zbynek** [comment]
@frankie139506 thanks for the PR!

I'm also not sure whether this was intentional change and if it was I'm OK with it. The only reason I brought it up was that the impact is different for different platforms.

**Comment by basil** [comment]
Thanks Zbynek. From my perspective the next step is for a member of UX SIG to confirm that this was intentional, then for this PR and bug to be closed.

**Comment by janfaracik** [comment]
This was an intentional decision during the redesign of the breadcrumbs so not a bug. Thanks.

**Pull request closed without merging**
