### PR TITLE
markdown

### PR DESCRIPTION
**Pull request by jsoref**
### Proposed changelog entries

* Improve markdown files

Note: in general, it is bad form to use `<a href="...">here</a>` or `<a href="...">click me</a>` because screen readers can't help explain to the user what `here` is.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Not sure it is needed, I prefer to have links embedded into the text

**Comment by oleg-nenashev** [comment]
@jsoref WDYT?

**Review by daniel-beck — APPROVED** [review]
I like the removal of all the stupid "here" links 👍 

Not sure about collecting all URLs towards the end. Seems like this makes it easier for the list to get out of sync with actual document contents. Personal preference though.

**Review by batmat — APPROVED** [review]
I like the transformation into more readable text.

I'm much more unconvinced by the separation between the text and the link. I think it makes sense only when used 2+ times, when used once it's actually then even worse than the current state. 

Still approving since this is not such a big deal and a dev-only doc anyway.

**UPDATE: read Daniel's take fully this time. So yes, exact same take for me.**

**Review by oleg-nenashev — APPROVED** [review]
anyway, it is a net-positive change. Since nobody stepped up to revert the links going to the end, I propose to merge it as is

**Pull request merged**
