### PR TITLE
[JENKINS-47127] Downgrade to m-war-p 3.0.0

### PR DESCRIPTION
**Pull request by batmat**
Supersedes https://github.com/jenkinsci/jenkins/pull/3048
I don't think `maven-war-plugin:3.1.1` will be released before the end of this week.
See [MWAR-407](https://issues.apache.org/jira/browse/MWAR-407) to follow the issue fixed in the _svn trunk_.

-----

MWAR-404 introduced the regression in maven-war-plugin 3.1.0that makes
every files be filtered, including binaries.

MWAR-407 has been filed to revert MWAR-404, but that will be only in
m-war-p 3.1.1 or 3.2.0 which are not yet released.

So we downgrade to 3.0.0 for now.

See [JENKINS-47127](https://issues.jenkins-ci.org/browse/JENKINS-47127).

### Proposed changelog entries

* JENKINS-47127: favicon.ico and other binaries were broken, because they were incorrectly filtered.

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@reviewbybees for more eyes

### CODE REVIEW

**Review by daniel-beck — APPROVED** [review]
Assuming this time we're running the wars through a diff tool.

**Comment by batmat** [comment]
That is worrying: missing `JENKINS.SF` and `JENKINS.RSA`

image

**Comment by daniel-beck** [comment]
PR builds aren't signed. Do any PR builds have these?

**Review by oleg-nenashev — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Should it actually be done on the Parent POM side? We may get into this issue with other core components bundling resources, right?

**Comment by daniel-beck** [comment]
This needs to go into the next weekly and I don't really care how.

**Comment by batmat** [comment]
@oleg-nenashev I think it's OK for now here, and I'd rather wait for the fix in m-war-p 3.2 to bump there. I don't expect much people inherit that pom apart from the core anyway (?).

**Comment by daniel-beck** [comment]
Environmental Windows test failure. Linux passed.

**Pull request merged**
