### PR TITLE
[JENKINS-52019] Fix Declarative Pipeline failures on Java 10 with just a little Groovy bump

### PR DESCRIPTION
**Pull request by svanoort**
See [JENKINS-52019](https://issues.jenkins-ci.org/browse/JENKINS-52019).

Tested manually using deployed SNAPSHOT 2.129-20180618.202934-2 and a variety of simpler Declarative builds plus Scripted Pipeline builds and shared libraries.  Not covered by Pipeline unit tests *yet* because of issues with JenkinsRule in Java 10 (another thing to fix).

Groovy Changelog: http://groovy-lang.org/changelogs/changelog-2.4.12.html

### Proposed changelog entries

* Bump Groovy to 2.4.12 to pick up better modules support and fix Declarative Pipeline failures under Java 10

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@oleg-nenashev

### CODE REVIEW

**Comment by svanoort** [comment]
And it seems this manages to introduce a Metaspace leak unless my tests are lying to me.   So it seems this will require downstream fixes to Script Security and workflow-cps plugins.

**Comment by oleg-nenashev** [comment]
@jenkinsci/java10-support

**Comment by oleg-nenashev** [comment]
@svanoort Created https://issues.jenkins-ci.org/browse/JENKINS-52023 for the follow-up memory leak regression. My assumption is that Memory leak is an acceptable cost to get Declarative working in the current state, so I will integrate it.

**Comment by svanoort** [comment]
@oleg-nenashev Yeah, it's a fair tradeoff.  Groovy bumps usually come with memory leak gotchas. :)

**Pull request merged**
