### PR TITLE
kill those pesky hudson temp files

### PR DESCRIPTION
**Pull request by jtnord**
@reviewbybees

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
🐝

**Review by daniel-beck — APPROVED** [review]

**Comment by jtnord** [comment]
@oleg-nenashev @daniel-beck sorry missed one...

**Review by recena — APPROVED** [review]

**Review by batmat — APPROVED** [review]
:bee:

**Review by daniel-beck — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Pull request merged**
