### PR TITLE
[Fix JENKINS-42577] Save jenkins version in Jenkins.save()

### PR DESCRIPTION
**Pull request by liketic**
See [JENKINS-42577](https://issues.jenkins-ci.org/browse/JENKINS-42577).

### Proposed changelog entries

* BUG: Fix persistence of actual Jenkins version in config.xml when saving Jenkins configuration programatically. It solves issues in upgrade logic checks (e.g. Jenkins.isUpgradedFromBefore)
  *  Javadoc link: http://javadoc.jenkins.io/jenkins/model/Jenkins.html#isUpgradedFromBefore-hudson.util.VersionNumber-
* ...

### Desired reviewers

@jglick

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
👍

**Comment by oleg-nenashev** [comment]
Seems the change breaks the tests though:

```
test_getLastExecVersion – jenkins.install.InstallUtilTest
a few seconds
Error
expected:<[9.123]> but was:<[2.78-SNAPSHOT (private-09/09/2017 05:36 GMT-win2012-7f6630$)]>
Stacktrace
org.junit.ComparisonFailure: expected:<[9.123]> but was:<[2.78-SNAPSHOT (private-09/09/2017 05:36 GMT-win2012-7f6630$)]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at jenkins.install.InstallUtilTest.test_getLastExecVersion(InstallUtilTest.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.jvnet.hudson.test.JenkinsRule$2.evaluate(JenkinsRule.java:551)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)

```

**Review by oleg-nenashev — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Thanks @liketic!

**Comment by oleg-nenashev** [comment]
Created the changelog entry. please verify

**Comment by daniel-beck** [comment]
@jglick You requested a PR link in the issue, FYI this got merged into 2.80.

**Comment by jglick** [comment]
Caused [JENKINS-47139](https://issues.jenkins-ci.org/browse/JENKINS-47139).

**Comment by liketic** [comment]
@jglick Apologizes for my bad.

**Comment by oleg-nenashev** [comment]
That's why we have reviews :(
They just cannot replace basic smoke tests. We need to fix that

**Comment by daniel-beck** [comment]
Also caused [JENKINS-47439](https://issues.jenkins-ci.org/browse/JENKINS-47439) not fixed by #3050.

(BTW @liketic don't let any of this discourage you from contributing in the future. Mistakes happen.)

**Comment by liketic** [comment]
@daniel-beck Thanks for your kind. Please feel free to rollback this commit. Jenkins is a great project, I always happy to contribute. However, I'm not a expert on jenkins, for most of opened issues, I cannot figure out the context, so it's really hard to me to contribute to them.  Thanks again.

**Pull request merged**
