### PR TITLE
[JENKINS-39370] - Update Remoting in Jenkins core to 3.10

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Introduces opt-in [Work Directory](https://github.com/jenkinsci/remoting/blob/master/docs/workDir.md) support. I need this change in the core in order to deliver changes in modules like Agent installer and enable work directories by default later.

I also released this version with my own code signing. Will verify it works correctly in Java Web Start with WAR from the CI before merging.

### Changelog entries

* Major RFE: [JENKINS-39370](https://issues.jenkins-ci.org/browse/JENKINS-39370) - Update Remoting from 3.7 to 3.10 in order to introduce the opt-in support of Work Directories in Jenkins agents.
  * Documentation link: https://github.com/jenkinsci/remoting/blob/master/docs/workDir.md
  * Remoting changelog: https://github.com/jenkinsci/remoting/blob/master/CHANGELOG.md#38
* RFE: JENKINS-18578 - Remoting 3.10: If Work directory is enabled, agents will use it to store JAR Cache
* RFE: JENKINS-39369 - Remoting 3.10: If Work directory is enabled, agents will automatically write its logs to the disk
  * Documentation: https://github.com/jenkinsci/remoting/blob/master/docs/logging.md
* RFE: JENKINS-39130 - Remoting 3.10: If Work directory is enabled, agents will automatically check if their Root directory is writable before connecting to the master and accepting tasks
* RFE: JENKINS-39817 - Remoting 3.10: Add support of the `-agentLog` parameter for Java Web Start agents
  * Documentation: https://github.com/jenkinsci/remoting/blob/master/docs/logging.md#default-behavior-without-work-directory-legacy-mode
* RFE: JENKINS-45160 - Allow configuring java.util.logging settings via a property file (-loggingConfig or JUL system property).
  * Documentation: https://github.com/jenkinsci/remoting/blob/master/docs/logging.md

### Submitter checklist

- [x] JIRA issue is well described
- [x] Link to JIRA ticket in description, if appropriate
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For new API and extension points: Link to the reference implementation in open-source (or example in Javadoc)

### Desired reviewers

@mention

@reviewbybees

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
The issue is relevant: 

```
java.lang.AssertionError: Slave failed to go online
	at org.junit.Assert.fail(Assert.java:88)
	at hudson.slaves.JNLPLauncherTest.launchJnlpAndVerify(JNLPLauncherTest.java:124)
	at hudson.slaves.JNLPLauncherTest.testHeadlessLaunch(JNLPLauncherTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.jvnet.hudson.test.JenkinsRule$2.evaluate(JenkinsRule.java:547)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
Standard Output
=== Starting testHeadlessLaunch(hudson.slaves.JNLPLauncherTest)
[.] $ C:\Jenkins\tools\hudson.model.JDK\jdk8\jre\bin\java -jar C:\Jenkins\workspace\Core_jenkins_PR-2886-CGY3RCUBMXOCTVFUB6TLUXNVC6HGTVEY37ZM5TGPDVNBM6XAPBZQ@tmp\m2repo\org\jvnet\hudson\netx\0.5-hudson-2\netx-0.5-hudson-2.jar -headless -basedir C:\Jenkins\workspace\Core_jenkins_PR-2886-CGY3RCUBMXOCTVFUB6TLUXNVC6HGTVEY37ZM5TGPDVNBM6XAPBZQ\test\target\jenkinsTests.tmp\jenkins5645387650790801445test -nosecurity -jnlp http://localhost:53643/jenkins/computer/test/slave-agent.jnlp -arg -headless
May 12, 2017 12:24:40 PM hudson.remoting.jnlp.Main createEngine
INFO: Setting up slave: test
May 12, 2017 12:24:40 PM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
netx: Launch Error: Could not launch JNLP file. (java.lang.reflect.InvocationTargetException null) (java.io.IOException Cannot find the JAR Cache location)
```

**Comment by oleg-nenashev** [comment]
"Should never happen in the current code", lol

https://github.com/jenkinsci/remoting/blob/76c9b8ccf14f7def1141565b0dee2e4d1c5508d4/src/main/java/hudson/remoting/Engine.java#L258-L259

**Comment by oleg-nenashev** [comment]
@abayer so the 3.9 certificate does not pass check on a couple of JVM versions. Something is wrong with the certificate chain :(

**Review by abayer — APPROVED** [review]

**Comment by daniel-beck** [comment]
@abayer @oleg-nenashev So what's with the cert chain Oleg mentions above now?

**Comment by oleg-nenashev** [comment]
@daniel-beck No merge PLS. The code signing result is partially incorrect, working with the Centrum support to get it fixed. Sorry for the delay

**Comment by oleg-nenashev** [comment]
@reviewbybees @abayer back to the review

**Review by abayer — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers are you fine with the upgrade (see the changelog)?

**Comment by oleg-nenashev** [comment]
I assume everybody is fine. Let's see how it flies. The most of the behavior is opt-in anyway

**Pull request merged**
