### PR TITLE
[JENKINS-53239] - Use winstone 5.0

### PR DESCRIPTION
**Pull request by olamy**
[JENKINS-33412] [JENKINS-52804] [JENKINS-51136]

Signed-off-by: olivier lamy <olamy@apache.org>

See [JENKINS-53239](https://issues.jenkins-ci.org/browse/JENKINS-53239).

### Proposed changelog entries

* Major BUG: Update Winstone from 4.4 to 5.0 to fix HTTP/2 support and 
  * Full changelog: https://github.com/jenkinsci/winstone/blob/master/CHANGELOG.md#50
  * Issues: JENKINS-52358, JENKINS-53239, JENKINS-33412, JENKINS-52804, JENKINS-51136 
* ...

### Submitter checklist

- [x] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### CODE REVIEW

**Comment by olamy** [comment]
currently WIP need https://github.com/jenkinsci/winstone/pull/54

**Review by oleg-nenashev — APPROVED** [review]
IMHO ready to go once we agree on the compatibility story

**Comment by olamy** [comment]
related issues:
- https://issues.jenkins-ci.org/browse/JENKINS-33412
- https://issues.jenkins-ci.org/browse/JENKINS-52804
- https://issues.jenkins-ci.org/browse/JENKINS-51136

**Comment by olamy** [comment]
@oleg-nenashev compat issue? If needed I can simply restore the class BoundedExecutorService.java and mark is as @deprecated DO NOT USE :)

**Comment by oleg-nenashev** [comment]
Added changelog and bumped the dependency

CC @dwnusbaum @svanoort

**Review by dwnusbaum — APPROVED** [review]

**Review by svanoort — APPROVED** [review]

**Pull request merged**
