### PR TITLE
Add Chinese localization for scheduler

### PR DESCRIPTION
**Pull request by LinuxSuRen**
### Proposed changelog entries

* Entry 1: Add Chinese localization for scheduler

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@jenkinsci/chinese-localization-sig

### CODE REVIEW

**Comment by daniel-beck** [comment]
I don't understand this PR. Didn't we remove all of this in https://github.com/jenkinsci/jenkins/pull/3667?

**Comment by LinuxSuRen** [comment]
I just migrate all jelly and groovy localization files. Actually I still have no idea how to deal with Java source localization. I'm work on it for a long time. If you have any thought about this, please let me know.

**Comment by daniel-beck** [comment]
So the changelog entry I wrote for #3667 is, in fact, wrong?
https://jenkins.io/changelog/#v2.145

This is why we have a PR template that, among other things, requires you to explain the change to Jenkins users. Please start using it.

**Comment by LinuxSuRen** [comment]
OK

**Review by oleg-nenashev — APPROVED** [review]
Yes, a changelog would be nice

**Comment by oleg-nenashev** [comment]
Apart from the changelog, this PR is ready to go IMHO

**Pull request merged**
