### PR TITLE
Revise curl example for inbound agent

### PR DESCRIPTION
**Pull request by jjasghar**
`curl` in powershell is a `cmd-let` and the `-sO` flags don't working with it. If you change it to `curl.exe` it will work with the flags. 

Reference: https://curl.se/windows/microsoft.html

### Proposed changelog entries

- Changed the hint command for `curl.exe` instead of the `cmd-let` of `curl`

### Submitter checklist

- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [x] There are at least 2 approvals for the pull request and no outstanding requests for change
- [x] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [x] Proper changelog labels are set so that the changelog can be generated automatically
- [x] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [x] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7142"></a>

### CODE REVIEW

**Review by MarkEWaite — CHANGES_REQUESTED** [review]
This change would convert a platform independent page to be specific to Windows users.  The command "curl -sO ..." works on Linux, FreeBSD, OpenBSD, and Windows command prompt with the curl provided in C:\Windows\System32\curl.exe (at least on my computer)

I don't have a suggestion to offer that will fix the insufficient `curl` implementation provided by Windows Powershell.

screencapture-mark-pc2-markwaite-net-8080-computer-jenkins-infra-docker-maven-11-a-2022-09-22-08_34_07-edit

**Comment by jjasghar** [comment]
Maybe add a note about `curl.exe` for windows based environments? From what i can tell from Windows 10 onwards they have `curl.exe` installed via the base install.

**Comment by MarkEWaite** [comment]
> Maybe add a note about `curl.exe` for windows based environments? From what i can tell from Windows 10 onwards they have `curl.exe` installed via the base install.

But it is only need for Powershell environments, not for Windows command processor environments.  If the Windows 10 user runs that command from a `cmd` window, it works as expected.

**Comment by jjasghar** [comment]
How about something like:
> If you are using Powershell to run your remote agent, run `curl.exe` instead of `curl` due to the default `cmd-let` alias

As someone who doesn't use Windows environments very often, searching for this fix took me a good couple of hours; if this was in this copy pasta page it would have saved some significant heart ache. I can imagine it's something other people _will_ hit going forward.

**Comment by MarkEWaite** [comment]
> How about something like:
> 
> > If you are using Powershell to run your remote agent, run `curl.exe` instead of `curl` due to the default `cmd-let` alias
> 
> As someone who doesn't use Windows environments very often, searching for this fix took me a good couple of hours; if this was in this copy pasta page it would have saved some significant heart ache. I can imagine it's something other people _will_ hit going forward.

I like that.  Can you put that into the pull request?  

The quote from the curl documentation page that you linked is especially fun:

> ## A Powershell alias
> 
> The curl tool comes installed in addition to the dreaded [curl alias](https://daniel.haxx.se/blog/2016/08/19/removing-the-powershell-curl-alias/) that plagues Powershell users since it is an alias that runs the invoke-webrequest command and therefore isn't acting much like curl at all.
> 
> A work-around is to invoke curl as "curl.exe" to prevent powershell from treating it as an alias.

**Comment by jjasghar** [comment]
I think I got that right, (I never had to use this formatting), but put it as a "note."

**Review by MarkEWaite — CHANGES_REQUESTED** [review]
That syntax causes a stack trace when I attempt to use it from Jenkins.

You might consider this alternative:

```
diff --git a/core/src/main/resources/hudson/slaves/JNLPLauncher/main.jelly b/core/src/main/resources/hudson/slaves/JNLPLauncher/main.jelly
index 27b734ed99..2504673594 100644
--- a/core/src/main/resources/hudson/slaves/JNLPLauncher/main.jelly
+++ b/core/src/main/resources/hudson/slaves/JNLPLauncher/main.jelly
@@ -57,9 +57,9 @@ curl -sO ${jenkinsURL}jnlpJars/agent.jar
 java -jar <a href="${rootURL}/jnlpJars/agent.jar">agent.jar</a> -jnlpUrl ${jenkinsURL}${it.url}jenkins-agent.jnlp -secret @secret-file ${it.launcher.getWorkDirOptions(it)}</pre>
             </j:otherwise>
           </j:choose>
-               <p>
-                 ${%Please note: if you are using Powershell to run your remote agent, run <pre>curl.exe</pre> instead of <pre>curl</pre> due to the default <pre>cmd-let</pre> alias.:}
-               </p>
+          <p>
+            ${%Please note: Powershell users must use curl.exe instead of curl due to the default Powershell cmd-let alias for curl}
+          </p>
       </j:if>
     </j:when>
     <j:otherwise>
```

The git commit comment that I added in my local exploring was:

>   Remove HTML formatting from internationalized string
>
 >  HTML formatting characters seem to break the internationalized string and
 > cause it to report a stack trace rather than being displayed on the page.
>
>  Remove the trailing ':' from the string since it is not the start of a
>  list or an example.
>
>   Use indentation consistent with the preceding line

With that example, it looks like this:

screencapture-testing-a-markwaite-net-8080-manage-computer-inbound-agent-2022-09-22-10_58_30 (1)

**Comment by jjasghar** [comment]
Fixed per your suggestion. Thanks!

**Review by MarkEWaite — APPROVED** [review]
Confirmed the message is displayed as expected from a Jenkins war compiled with this pull request.

Thanks!

**Review by NotMyFault — APPROVED** [review]
Hey,

welcome to the Jenkins project, and thanks for your PR 🎉 

The change proposed looks good so far!

---

This PR is now ready for merge. We will merge it after ~24 hours if there is no negative feedback.
Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process.
Thanks!

**Review by basil — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
