### PR TITLE
Sleep less in `ViewTest`

### PR DESCRIPTION
**Pull request by basil**
I'm as guilty of working around synchronization problems in tests with sleep statements as the next person (but never in production code!), but this 100-second sleep is just ridiculous. Surely shaving off two 0s and making it a 1-second sleep can't hurt.

### Proposed changelog entries

N/A

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/6701"></a>

### CODE REVIEW

**Review by timja — APPROVED** [review]
Added when the test was originally created in https://github.com/jenkinsci/jenkins/commit/303ddb1a8cdd2983e650fafe3656216a2bc3aab9

Did you check if the sleep is even needed?

Anyway this is now 100x faster

**Comment by basil** [comment]
> Did you check if the sleep is even needed?

It didn't seem to be needed when I removed it. Then again, my personal machine is very fast. :smile: I opted for the "conservative" choice of making the sleep 100 times shorter rather than removing it completely.

**Comment by basil** [comment]
This PR is now ready for merge. We will merge it after approximately 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process. Thanks!

**Comment by basil** [comment]
Invoking the [_de minimis_ clause](https://github.com/jenkinsci/jenkins/blob/c60ea9210cb8db036c2cc1e446e789618b9744f3/docs/MAINTAINERS.adoc?plain=1#L388=).

**Pull request merged**
