### PR TITLE
[JENKINS-66930] remove unsafe classes copied from Apache Ant which have been deprecated in Oct 2019

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: Olivier Lamy <olamy@apache.org>

See [JENKINS-66930](https://issues.jenkins-ci.org/browse/JENKINS-66930).

### Proposed changelog entries

* Remove deprecated, unsafe classes previously copied from Apache Ant. Docker Slaves plugin is incompatible with this change.

### Proposed upgrade guidelines

In case your plugin use those classes, just migrate to the `org.apache.ant` package

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by StefanSpieker** [comment]
I tried to remove that before,a s you can see here: [#4272](https://github.com/jenkinsci/jenkins/pull/4272) There are still two plugins which use it:
jenkinsci/copy-to-slave-plugin#11
jenkinsci/fstrigger-plugin#4

The fstrigger got merged and is already published. We should put this to the upgrade guide. I don't know how often the copy to slave plugin is used.

**Comment by daniel-beck** [comment]
>  jenkinsci/copy-to-slave-plugin#11

Ignore, distribution is suspended (and has been for a long time) so we can pretend it doesn't exist.

**Comment by daniel-beck** [comment]
https://github.com/jenkinsci/docker-slaves-plugin/commit/71ed3c863d2bd04f641d62288b5cf074e5c3ed9a remains unreleased.

> It's now safe to remove them .

Based on what data is this asserted? Please show your work.

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
I am -1 for the change in the current state. `hudson.org.apache.tools.tar.TarInputStream` is used in https://github.com/jenkinsci/copy-to-slave-plugin/blob/c0ea34f47941b1647fd05ea31eb69779ce53fab3/src/main/java/com/michelin/cio/hudson/plugins/copytoslave/MyFilePath.java. Even if the class is deprecated, I believe we need to check and cleanup usages in actively used plugins.

**Review by timja — APPROVED** [review]

**Review by basil — APPROVED** [review]
`hudson.org.apache.tools.tar.TarOutputStream` is still used in the currently released version of [Docker Slaves](https://plugins.jenkins.io/docker-slaves/). I don't feel strongly that this plugin should remain supported, but if we do decide to drop support for it I think this should be mentioned in the release notes and a deprecation notice added to the plugin in the update center.

**Review by StefanSpieker — APPROVED** [review]

**Comment by darxriggs** [comment]
I am not the maintainer of the [docker-slaves-plugin](https://github.com/jenkinsci/docker-slaves-plugin/). Nevertheless, I would also like to see my cleanups of it being released.

**Comment by olamy** [comment]
answer from maintainer: https://github.com/jenkinsci/docker-slaves-plugin/commit/71ed3c863d2bd04f641d62288b5cf074e5c3ed9a#commitcomment-58330874

**Comment by olamy** [comment]
adding `on-hold` to wait for release of the plugin....

**Review by jtnord — APPROVED** [review]
I agree with @daniel-beck the code in `docker-slaves-plugin` has been merged and waiting for release for over 2 years, if that is not long enough what is the expected minimum amount of time?

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by daniel-beck** [comment]
> > is used in https://github.com/jenkinsci/copy-to-slave-plugin/blob/c0ea34f47941b1647fd05ea31eb69779ce53fab3/src/main/java/com/michelin/cio/hudson/plugins/copytoslave/MyFilePath.java
> 
> https://plugins.jenkins.io/copy-to-slave/
> 
> The plugin hasn't been distributed for 3.5 years.

https://groups.google.com/g/jenkinsci-users/c/fVojVq2Mas0/m/tyW76wgoAwAJ 🙃

**Comment by daniel-beck** [comment]
> [daniel-beck](https://github.com/daniel-beck) added a commit that referenced this pull request

Misclick, I have no intention of reverting.

**Pull request merged**
