### PR TITLE
Backporting for LTS 2.222.2

### PR DESCRIPTION
**Pull request by olivergondza**
Backporting has started and the RC is scheduled for 2020-04-08.

This is for the first time we do backporting review in github, partially to see how practical it will be. We are expected to learn and reflect back on the process as we go.

Please have look at the change proposed and rejected so we have a consensus of what goes in by 2020-04-08.

---

- Initially, I propose to backport:

```
JENKINS-61692		Minor     		2.229
	"HTTP Proxy Configuration" -> "Validate Proxy" crashs immediately with NullPointerException
	regression
	https://issues.jenkins-ci.org/browse/JENKINS-61692

JENKINS-61688		Critical  		2.229
	Global build discarders configuration isn't loaded from disk
	https://issues.jenkins-ci.org/browse/JENKINS-61688

JENKINS-61465		Major     		2.226
	Make Functions#checkAnyPermission work on objects that aren't AccessControlled
	https://issues.jenkins-ci.org/browse/JENKINS-61465

JENKINS-60788		Minor     		2.224
	NullPointerException when hitting Check Now against a custom update center
	https://issues.jenkins-ci.org/browse/JENKINS-60788

JENKINS-60454		Major     		2.223
	Jenkins.instance is missing after restart
	https://issues.jenkins-ci.org/browse/JENKINS-60454
```

- What remains to be discussed is the troika of issues introducing and fixing the read only config page. It looks somewhat safe, but given that is a minor improvement that has caused a critical regression, I prefer not to backport JENKINS-61202 and giving it more soak time to 2.222.3.
```
JENKINS-61202		Minor     		2.223
	Read only view of job configuration page
	https://issues.jenkins-ci.org/browse/JENKINS-61202
		Caused https://issues.jenkins-ci.org/browse/JENKINS-61321
		Caused https://issues.jenkins-ci.org/browse/JENKINS-61284

JENKINS-61321		Blocker   		2.224
	Pipeline Job configuration appears read-only for users with project-level permissions after update to Jenkins 2.223
	regression
	https://issues.jenkins-ci.org/browse/JENKINS-61321

JENKINS-61284		Minor     		2.224
	Grey bar below textarea in read only mode looks weird
	https://issues.jenkins-ci.org/browse/JENKINS-61284
```

- [JENKINS-61279: Update version number dependency to 1.7](https://issues.jenkins-ci.org/browse/JENKINS-61279) is being discussed in the issue as something potentially too minor to backport.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
It would be great to get feedback from @timja about backporting read-only UIs for jobs, but I do not think [JENKINS-61202](https://issues.jenkins-ci.org/browse/JENKINS-61202) and JENKINS-61321/JENKINS-61284 should be backported. 61202 is an enhancement, not a bugfix. IMHO it is better to keep it as is until the next baseline

**Comment by daniel-beck** [comment]
> What remains to be discussed is the troika of issues introducing and fixing the read only config page

JENKINS-61284 would apply to all read-only styled config pages, notably system config with SystemRead. It's independent of the two other issues (and one is really only lts-candidate so we don't miss it if we backport the other).

**Review by daniel-beck — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
> JENKINS-61284 would apply to all read-only styled config pages, notably system config with SystemRead.

It is technically correct. But I do not think SystemRead is functional in 2.222.x anyway, we need follow-up PRs to be integrated, and it is only about the next LTS baseline. So I would not worry too much

**Comment by timja** [comment]
not too worried about the system read ones, I think https://issues.jenkins-ci.org/browse/JENKINS-61279 should be backported, replied in the issue

**Comment by jglick** [comment]
I expected to have one PR per distinct backported fix, to make it easier for the author of the original fix to review that the cherry-pick applied cleanly and so on.

**Comment by olivergondza** [comment]
@jglick, I leaned towards this way so we have the perspective of what is all that goes in, and making that decision represented by a single merge. Note the individual backports are represented by a single backported commit most of the time still making it possible to review (branches are safer to backport by their merge commit as that gets squashed).

**Comment by oleg-nenashev** [comment]
@jglick We explicitly agreed to start from a single bulk pull request, please see https://docs.google.com/document/d/1NzR1XtkCfk6MDSD1jRq5H-iPSjqKvP-pfUO0b9lVZ9k/edit#bookmark=id.an8flzvq6hv8

**Review by oleg-nenashev — APPROVED** [review]
The list of backports looks right, +1 for proceeding with that for RC

**Comment by olivergondza** [comment]
Thanks for the review. I have added JENKINS-61279 as simple enough and postponed the rest. Unless there are objections by meeting time tomorrow, we will proceed with merging this as is.

**Review by timja — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
We might want to include a [JENKINS-61823](https://issues.jenkins-ci.org/browse/JENKINS-61823) fix into .2. It would need a new cut of Winstone 5.9.1 with a https://github.com/jenkinsci/winstone/pull/100 backport. I can prepare a version today if other maintainers agree we want to port it into .2

**Comment by olivergondza** [comment]
@oleg-nenashev, yeah, I would be careful around winstone. This is still pretty new and I have advocated for prolonging the soak time for dependencies. So I prefer this in .3.

**Comment by oleg-nenashev** [comment]
> yeah, I would be careful around winstone. This is still pretty new and I have advocated for prolonging the soak time for dependencies. So I prefer this in .3.

Taking the current state of https://github.com/jenkinsci/winstone/pull/100 , I withdraw my proposal to consider it for .2

**Comment by jglick** [comment]
> We might want to include a [JENKINS-61823](https://issues.jenkins-ci.org/browse/JENKINS-61823) fix into .2.

Given that it is a regression in 2.222.1 (IIUC), this makes sense to me.

**Comment by daniel-beck** [comment]
> > We might want to include a [JENKINS-61823](https://issues.jenkins-ci.org/browse/JENKINS-61823) fix into .2.
> 
> Given that it is a regression in 2.222.1 (IIUC), this makes sense to me.

Should be an old-LTS-to-new-LTS regression, yes. OTOH, it's not a popular issue and there's a workaround.

**Comment by olivergondza** [comment]
The backporting window is over. I see the consensus of what goes in in not particularly strong, but we have to move on with the latest agreed on set of backports.

**Pull request merged**
