### PR TITLE
Allow secret to convert to itself

### PR DESCRIPTION
**Pull request by timja**
Reduces warning logs when exporting config via JCasC

Previously there was lots of: 
```
Feb 22, 2020 11:33:40 AM hudson.util.Secret toString
WARNING: Use of toString() on hudson.util.Secret from hudson.util.Secret$1.convert(Secret.java:310). Prefer getPlainText() or getEncryptedValue() depending your needs. see https://jenkins.io/redirect/hudson.util.Secret/
```
Now, there's still some:
```
WARNING: Use of toString() on hudson.util.Secret from org.apache.commons.beanutils.converters.AbstractConverter.convertToString(AbstractConverter.java:195). Prefer getPlainText() or getEncryptedValue() depending your needs. see https://jenkins.io/redirect/hudson.util.Secret/
```
I haven't managed to track down a fix for the above but this improves the current state of log spam

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

### Proposed changelog entries

* Entry 1: Issue, Human-readable Text
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

### CODE REVIEW

**Review by jetersen — APPROVED** [review]
LGTM!

**Review by res0nance — APPROVED** [review]
LGTM

**Review by jvz — APPROVED** [review]
Surprised this wasn't already supported.

**Review by markjacksonfishing — APPROVED** [review]

**Review by fcojfernandez — APPROVED** [review]

**Comment by timja** [comment]
Added ready-for-merge, will merge it tomorrow if no negative feedback.

Thanks for the reviews all

**Review by oleg-nenashev — APPROVED** [review]
IMHo it deserves an rfe or a bug changelog entry. If you would like to backport it, a Jira issue would be great

**Pull request merged**
