### PR TITLE
[JENKINS-27218] expose X-Jenkins-JNLP-Host

### PR DESCRIPTION
**Pull request by ndeloof**
will require remoting released with https://github.com/jenkinsci/remoting/pull/36 to get JENKINS-27218 fixed.

### CODE REVIEW

**Comment by daniel-beck** [comment]
What about https://github.com/jenkinsci/jenkins/blob/master/war/src/main/webapp/help/system-config/master-slave/jnlp-tunnel.html?

**Comment by ndeloof** [comment]
This is another way to get this to work : have reverse proxy route TCP traffic to jenkins master. But I prefer to avoid this when there's no network constraint to prevent direct slave-to-master connection (more rev proxy configuration and traffic required without added value).

This PR is to align JNLP with jenkins CLI support for X-Jenkins-CLI-Host.

**Comment by daniel-beck** [comment]
That's not how this works, since *by default* the JNLP slave will connect to the reverse proxy. Use this option to point it to the real Jenkins server.

https://github.com/jenkinsci/remoting/blob/master/src/main/java/hudson/remoting/jnlp/Main.java#L54
https://github.com/jenkinsci/remoting/blob/master/src/main/java/hudson/remoting/Engine.java#L340

**Comment by ndeloof** [comment]
right.
Issue I'm trying to address is CloudBees H.A. setup where both active and backup nodes share the same configuration, so can't use such an option to route JNLP http to actual host.

**Comment by daniel-beck** [comment]
There's no DNS pointing to the active host you could use for this?

**Comment by ndeloof** [comment]
floating IP is another way to setup HA. I'm considering the use of haproxy frontend here.
CLI works well in this context thanks to X-Jenkins-CLI-Host header support

**Comment by oleg-nenashev** [comment]
cannot be merged anymore

**Comment by ndeloof** [comment]
osbolete since https://github.com/jenkinsci/jenkins/commit/342dc735b0df9e0be0e7e436ccc016bc6515e8e7

**Pull request closed without merging**
