### PR TITLE
[JENKINS-66094]Use Path.startsWith() for subdirectory check when unzipping

### PR DESCRIPTION
**Pull request by trgpa**
See [JENKINS-66094](https://issues.jenkins-ci.org/browse/JENKINS-66094).

### Proposed changelog entries

* Fix an issue unzipping archives in a corner case when entries have the same path prefix as the target location.

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@Wadeck @batmat

### CODE REVIEW

**Comment by Wadeck** [comment]
(Testing still in progress, requires lot of time, but I don't have much 🤷‍♂️)

**Review by Wadeck — APPROVED** [review]
Thank you @trungPa for the PR, I was testing it with tens of different locations and there is no regression, great job!

**Review by basil — APPROVED** [review]

**Comment by basil** [comment]
This PR is now ready for merge. We will merge it after approximately 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process. Thanks!

**Comment by basil** [comment]
@trungPa Could you please update the PR description with an appropriate changelog entry for end users? Something like: "Fix an issue unzipping archives in a corner case when entries have the same path prefix as the target location."

**Pull request merged**
