### PR TITLE
[JENKINS-68103] Fix build progress bar not taking the user to console output

### PR DESCRIPTION
**Pull request by janfaracik**
See [JENKINS-68103](https://issues.jenkins.io/browse/JENKINS-68103)

Essentially the hitbox for the link above the progress bar was too tall, meaning that it was very hard to click the progress bar.

### Testing done

I changed the number of executors on the built-in node from 2 to 3, then I created a Freestyle job with a shell command of `sleep 86400` and checked the "Execute concurrent builds if necessary" option. On Jenkins 2.339, I could see the animated progress bar for all three, and clicking on the progress bar took me to the console as expected. On Jenkins 2.440, I could see the animated progress bar for all three, but hovering over each one made an arrow drop down and made it impossible to click on the progress bar, and clicking on each one took me to the build page rather than the console output. With this PR, the behavior is back to the way it was in 2.339.

### Proposed changelog entries

* Clicking the build progress bar again takes the user to the console output (regression in 2.340).

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@basil

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

### CODE REVIEW

**Review by NotMyFault — COMMENTED** [review]
Clicking does work fine now, but hovering over it makes it invisible, if it's the first build, unless that is a different regression I'm currently not aware of:

https://user-images.githubusercontent.com/13383509/163412124-e6e51a94-6922-4795-ba14-fdaa9ff72ff5.mp4

 Edit: The bar going invisible is introduced in this change, on the current weekly it just blinks:

https://user-images.githubusercontent.com/13383509/163449295-d0067b21-304f-499d-b89e-69e96568f0f8.mp4

**Review by basil — APPROVED** [review]
Many thanks for taking care of this regression. I know that users will appreciate being able to get to the console log in one click. That will save users a lot of time and frustration, especially if they already had to navigate through several clicks from e.g. the GitHub UI.

The main question we have with regard to PRs like this is what testing was done. The PR description is lacking in this regard. As a courtesy, I have taken the liberty to update the PR description with the following text:

> I changed the number of executors on the built-in node from 2 to 3, then I created a Freestyle job with a shell command of `sleep 86400` and checked the "Execute concurrent builds if necessary" option. On Jenkins 2.339, I could see the animated progress bar for all three, and clicking on the progress bar took me to the console as expected. On Jenkins 2.440, I could see the animated progress bar for all three, but hovering over each one made an arrow drop down and made it impossible to click on the progress bar, and clicking on each one took me to the build page rather than the console output. With this PR, the behavior is back to the way it was in 2.339.

Please study the **Testing Done** given above and use this as a model for future PR submissions.

---

This PR is now ready for merge. We will merge it after approximately 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process. Thanks!

**Comment by NotMyFault** [comment]
I've updated my comment accordingly, I'm not against merging this but it basically introduces a new issue, fwiw.

**Comment by basil** [comment]
BTW Alex the animated progress bar becoming invisible when you hover over it is behavior that goes back to at least 2.277 in my testing, so I don't think it is a regression; rather I think it is the expected behavior at this point.

**Review by NotMyFault — APPROVED** [review]
Approving in this case then.

**Pull request merged**
