### PR TITLE
Require @since as part of checkstyle

### PR DESCRIPTION
**Pull request by timja**
See https://github.com/jenkinsci/jenkins/pull/6252#issuecomment-1030700980

Implemented with https://github.com/timja/jenkins-checkstyle-checks, not hosted / pushed to a repo yet, if you want to try it just build it locally.

I looked into suppressing restricted methods / classes, from what I can tell via checkstyle mailing list / issue tracker it should be possible via an xpath suppression but I wasn't able to make it work:

- https://github.com/checkstyle/checkstyle/issues/1340#issuecomment-420835444
- https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.html

This adds suppressions for ~950 files + tests. We can iteratively remove, and in the meantime it will catch new files that are added.

Error messaging: https://github.com/timja/jenkins-checkstyle-checks/blob/9de520d39f8ba4337caeb6dd0fa0839836f49d93/src/main/resources/io/jenkins/libs/checkstyle/messages.properties#L1

This doesn't enforce @since when there's missing JavaDoc, as that seemed the business of another rule to enforce it on public methods and classes.

Thoughts?

### Proposed changelog entries

* Entry 1: Issue, Human-readable Text
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by olamy** [comment]
why not but how do you know in advance the value of the `@since`? 
If I make a PR with a value but it takes 3 weeks to get it merged, the since will be there and even enforced by some checkstyle but with a wrong value.
So it will depend how long it will take to get the pr merged.

**Comment by timja** [comment]
The error message says to add at since TODO. Which will be filled in later once we know the release version

**Comment by daniel-beck** [comment]
> worst a totally useless `@since TODO`

We have a script to fix these periodically: https://github.com/jenkinsci/jenkins/blob/master/update-since-todo.sh

**Comment by daniel-beck** [comment]
> Thoughts?

I really like the idea to have a check for this. Thank you for looking into this!

It's disappointing that `@Restricted` cannot be checked. We've basically mostly treated `@since` and `@Restricted` as alternatives (one for unrestricted, the other for restricted additions). For a check like this, we should make it clear that adding `@Restricted` should be considered for additions, because dealing with accidental API is just unnecessary trouble. The current implementation does not offer `@Restricted` as an alternative in the message (probably because it's not acceptable to the check). That seems to skew it towards unrestricted API in the long term, and does not make it easier for reviewers either: Is something `@since` documented because it's intended as a public API, or because the checker complained and the author just applied the fix?

**Comment by timja** [comment]
> It's disappointing that @Restricted cannot be checked

It likely can be but I wasn't able to get it working and there's an open RFE on checkstyle to make it easier.
Because of the way `TreeWalker` works I wasn't able to figure out a way to handle this in the check itself.

>  For a check like this, we should make it clear that adding @Restricted should be considered for additions, because dealing with accidental API is just unnecessary trouble

Can easily tweak messaging, currently defined in https://github.com/timja/jenkins-checkstyle-checks/blob/9de520d39f8ba4337caeb6dd0fa0839836f49d93/src/main/resources/io/jenkins/libs/checkstyle/messages.properties#L1.

One thing I forgot to mention is that this doesn't enforce `@since` when there's missing JavaDoc, as that seemed the business of another rule to enforce it on public methods and classes.

**Comment by timja** [comment]
I may pick this up again later or anyone else is welcome to

**Pull request closed without merging**
