### PR TITLE
Backporting for LTS 2.289.1

### PR DESCRIPTION
**Pull request by res0nance**
```
Fixed
-----

JENKINS-65605           Blocker                 Sun, 16 May 2021 08:42:32 +0000
        `WithBridgeMethods` annotation no longer working in core
        regression
        https://issues.jenkins.io/browse/JENKINS-65605

JENKINS-65190           Blocker                 2.291
        The build history  layout is out of bounds if set long buildName
        https://issues.jenkins.io/browse/JENKINS-65190

JENKINS-64294           Major                   2.291
        Buffer stdin for WebSocket CLI
        https://issues.jenkins.io/browse/JENKINS-64294

JENKINS-52356           Minor                   2.290
        Support ZIP64 in ZipArchiver
        https://issues.jenkins.io/browse/JENKINS-52356

```

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]

**Review by basil — APPROVED** [review]

**Review by timja — APPROVED** [review]

**Review by jglick — APPROVED** [review]

**Comment by res0nance** [comment]
Will add #5489 once that goes into the master branch

**Review by jtnord — COMMENTED** [review]
I am still unclear what the proposal is for the [Form submission](https://issues.jenkins.io/browse/JENKINS-65585) [regression](#5479).

**Comment by res0nance** [comment]
> I am still unclear what the proposal is for the [Form submission](https://issues.jenkins.io/browse/JENKINS-65585) [regression](#5479).

Thats an open issue that at this point I'm not sure how best to solve.
- Should we simply revert the change?
- Is the change ok but simply HTMLUnit having issues that can be dealt with separately?
- Some other suggestions?

**Review by bmunozm — APPROVED** [review]

**Comment by timja** [comment]
> Should we simply revert the change?

Other option is to revert out of LTS line but keep in weekly?

**Comment by res0nance** [comment]
> > Should we simply revert the change?
> 
> Other option is to revert out of LTS line but keep in weekly?

Thats doable too but do we have concensus for that? We could revert it and reintroduce it when we figure out how to fix the HTMLUnit issues.

**Comment by timja** [comment]
There's a potential fix in https://github.com/jenkinsci/jenkins/pull/5479, probably worth trying the incremental in bom?

**Comment by res0nance** [comment]
Seems to fix the issue the last issue seems to be related to the parameter change

**Comment by MarkEWaite** [comment]
See https://github.com/jenkinsci/jenkins/pull/5405#issuecomment-842713911 for a case where the `requestSubmit` change breaks an interactive save of a matrix job.

**Comment by thomasgl-orange** [comment]
> See [#5405 (comment)](https://github.com/jenkinsci/jenkins/pull/5405#issuecomment-842713911) for a case where the `requestSubmit` change breaks an interactive save of a matrix job.

Copy/pasting my reply from [#5405 (comment)](https://github.com/jenkinsci/jenkins/pull/5405#issuecomment-842977185) here, as an input to the discussion about these form submision regressions:

> I can reproduce what you're describing, and yes, it is indeed a consequence of this 2.289 change. It's not specific to Matrix jobs though.
> 
> What triggers the issue here is the invalid [depth=0](https://github.com/MarkEWaite/docker-lfs/blob/2a32b5804364c8215b21fd1462809b85d64cf109/ref/jobs/Tools/jobs/ant-jdk8-auto-install-check/config.xml#L57) value in your Git `CloneOption`. Because the `shallow` option is off, the field is hidden in the configure page (and the invalid value shouldn't matter in practice), but it still gets somehow validated and blocks submitting the form. And of course the error message is hidden too...
> 
> It is something which could be fixed / worked-around in the Git plugin itself, for this specific case. But similar issues might pop up with other plugins and existing configs, so it's difficult to estimate how "bad" this is.

**Comment by res0nance** [comment]
> See [#5405 (comment)](https://github.com/jenkinsci/jenkins/pull/5405#issuecomment-842713911) for a case where the `requestSubmit` change breaks an interactive save of a matrix job.

I'm going to directly revert it in this 2.289.1 `into-lts` PR if there are no objections. We can fix the change properly and have it included in `.2`. What does everyone think? CC: @jenkinsci/core

**Comment by timja** [comment]
> > See [#5405 (comment)](https://github.com/jenkinsci/jenkins/pull/5405#issuecomment-842713911) for a case where the `requestSubmit` change breaks an interactive save of a matrix job.
> 
> I'm going to directly revert it in this 2.289.1 `into-lts` PR if there are no objections. We can fix the change properly and have it included in `.2`. What does everyone think? CC: @jenkinsci/core

👍

**Comment by jtnord** [comment]
> I'm going to directly revert it in this 2.289.1 into-lts PR if there are no objections.

I was pondering suggesting this earlier.  so 👍 

> we can fix the change properly and have it included in .2

I'm not sure we would want that - rather this is something that we should let bake for a while in the weeklies in case it reveals any more as yet unknown side effects.

**Comment by res0nance** [comment]
> > I'm going to directly revert it in this 2.289.1 into-lts PR if there are no objections.
> 
> I was pondering suggesting this earlier. so 👍
> 
> > we can fix the change properly and have it included in .2
> 
> I'm not sure we would want that - rather this is something that we should let bake for a while in the weeklies in case it reveals any more as yet unknown side effects.

Its more of when we get the right fix in place we can have it included, not necessarily .2. maybe not even .3

**Review by oleg-nenashev — APPROVED** [review]
LGTM, thanks @res0nance !

**Comment by thomasgl-orange** [comment]
> We can fix the change properly and have it included in .2.

The remaining "regression" from #5405 (assuming #5479 was good enough for fixing the few HtmlUnit tests failures) was that HTML forms validation was not bypassed anymore (which was confusing in Mark's example because the invalid input was in an hidden optional block).

To fully restore this behavior with #5405, adding a `novalidate` on affected forms would probably be enough. It sounds like a weird thing to do, but on the other hand this "feature" was weird too.

To get best of both worlds (HTML validation but only for visible inputs), maybe something could be done via `optional-block.jelly` (and `updateOptionalBlock()` in `hudson-behavior.js`), to set `readonly="true"` on the input tags which are in an hidden optional block (this way, values would still be submitted, but not validated). Easier said than done though (for instance, what if some inputs are supposed to stay readonly even when the optional block gets displayed, for whatever reason?).

**Comment by timja** [comment]
> EDIT: rather than novalidate on the form, maybe formnovalidate="formnovalidate" on the submit buttons.

👍

**Comment by thomasgl-orange** [comment]
> To fully restore this behavior with #5405, adding a `novalidate` on affected forms would probably be enough. It sounds like a weird thing to do, but on the other hand this "feature" was weird too.
> 
> **EDIT:** rather than `novalidate` on the form, maybe `formnovalidate="formnovalidate"` on the submit buttons.

Something like that (here on top of #5479): thomasgl-orange/jenkins@90ae5f187c

I've only done a quick test to check it enables saving configuration of Mark's example job (in FF 88).

**Pull request merged**
