### PR TITLE
[FIX JENKINS-33978] Set file permissions on the file before writing the secret

### PR DESCRIPTION
**Pull request by jtnord**
[JENKINS-33978](https://issues.jenkins-ci.org/browse/JENKINS-33978) The file permissions should be set to secure the file before any secret is written to it.

@reviewbybees

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
:bee:

**Comment by daniel-beck** [comment]
:bee:

**Comment by jtnord** [comment]
@reviewbybees done.  @daniel-beck leaving this to you to merge if you feel luck as I have given this zero testing :-)

**Comment by daniel-beck** [comment]
:bug: A funny thing happens when I test this. The file has 644 for me on OS X. beta-1 correctly has 640. Could someone else test this please?

**Comment by kzantow** [comment]
@daniel-beck yes, some issue on OSX with `FilePath.chmod` unrelated to this PR

**Comment by daniel-beck** [comment]
@kzantow How can this be? As I wrote, beta-1 sets permissions correctly.

**Comment by kzantow** [comment]
@daniel-beck @jtnord hm, maybe as it's not an existing file, it does nothing and/or causes said issue?... needs to `iapf.write("", "UTF-8");` first or something? Regardless, it seems the issue is in `chmod`, though.

**Comment by jtnord** [comment]
@kzantow @daniel-beck `touch`ed the file so it should be created now so chmod should work as expected.  Still has the same amount of testing.

**Comment by kzantow** [comment]
> Still has the same amount of testing.

Hahaha. Me gusta.

**Comment by daniel-beck** [comment]
Needs a merge with 2.0.

**Comment by daniel-beck** [comment]
Doesn't work for me. @kzantow Have you tested this?

**Comment by daniel-beck** [comment]
Clearly also needs a test case.

**Comment by kzantow** [comment]
@daniel-beck  PR build for this works for me on OSX:

-rw-r-----  1 kzantow  staff  33 Apr  5 13:45 /Users/kzantow/.jenkins/secrets/initialAdminPassword

**Comment by daniel-beck** [comment]
@kzantow Thanks. I probably did something wrong, as it works for me now as well.

**Comment by daniel-beck** [comment]
:+1: from me, but some more eyes would still be nice.

**Comment by kzantow** [comment]
Right, as it stands, it's a :bee: from me. I'll double check things don't break on Windows 10 & a recent Linux

**Comment by kzantow** [comment]
@daniel-beck I tested this on OSX, Ubuntu Server, Windows 10 and it works fine (Windows doesn't adhere to the permission mask, but that's a known limitation in the chmod method, I'm pretty sure).

**Pull request merged**
