### PR TITLE
Add missing Turkish translations for home page

### PR DESCRIPTION
**Pull request by mustafau**
Here is a screenshot of the home page with Turkish translations.

Screen Shot 2021-04-10 at 05 14 22

### CODE REVIEW

**Comment by MarkEWaite** [comment]
@urklc, @mcansozeri, or @barissimek can you review the translation and confirm it is ready to merge?

**Comment by mcansozeri** [comment]
It's confirmed. Thank you.

**Review by MarkEWaite — APPROVED** [review]
Approving based on review by @mcansozeri

**Review by mcansozeri — APPROVED** [review]
Approved.

**Comment by MarkEWaite** [comment]
This PR is now ready for merge.  We will merge it after approximately 24 hours if there is no negative feedback.

**Review by barissimsek — APPROVED** [review]
Lgtm

**Comment by oleg-nenashev** [comment]
Thanks all for the patch and the reviews!

**Pull request merged**
