### PR TITLE
JENKINS-64252 Fix dragdrop regression

### PR DESCRIPTION
**Pull request by timja**
See [JENKINS-64252](https://issues.jenkins.io/browse/JENKINS-64252).

### Proposed changelog entries

* Entry 1: JENKINS-64252 Fix dragdrop with environment filter (regression in 2.264)
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [x] There are at least 2 approvals for the pull request and no outstanding requests for change
- [x] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [x] Proper changelog labels are set so that the changelog can be generated automatically
- [x] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [x] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by res0nance — APPROVED** [review]

**Review by fqueiruga — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by Wadeck** [comment]
Tested this PR in the scope of another D&D, not solving it, FTR: https://issues.jenkins.io/browse/JENKINS-64291

**Comment by timja** [comment]
Looks like a different issue, this one was caused by prototype not working when it found an SVG.

The other might be in the actual drag and drop implementation (although not looked into it past gifs yet)

**Comment by fqueiruga** [comment]
TBH I think the drag & drop struggles with really tall elements. Elements, especially the ones with nested items, were way shorter before tables-to-divs

**Pull request merged**
