### PR TITLE
Removed unused class stringConverter2

### PR DESCRIPTION
**Pull request by StefanSpieker**
According to [deprecated-and-unused](https://ci.jenkins.io/job/Infra/job/usage-in-plugins/job/master/lastSuccessfulBuild/artifact/output/deprecated-and-unused.html) this small class is not used anywhere and has no test which covers it, I think this might be removed. Especially since it is marked as deprecated since 2009.

### Proposed changelog entries

* Internal: Removed unused class StringConverter2

### Proposed upgrade guidelines

* None

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

### CODE REVIEW

**Review by res0nance — COMMENTED** [review]
A quick search reveals this will break in 2 cases. One is a test which is not an issue but the other is a plugin which seems to have no activity since 2012 https://github.com/search?q=org%3Ajenkinsci+StringConverter2&type=Code

**Comment by StefanSpieker** [comment]
Thanks for pointing that out. I think the plugin is not used anymore, but I added an upgrade line for it.

**Comment by varyvol** [comment]
@StefanSpieker could you please clarify what you mean by adding an upgrade line for it? Maybe raising a PR against the plugin would avoid any issues, but other than that this change looks good.

**Comment by varyvol** [comment]
@StefanSpieker could you please clarify what you mean by adding an upgrade line for it? Maybe raising a PR against the plugin would avoid any issues, but other than that this change looks good.

**Comment by fcojfernandez** [comment]
I'm tempted to approve this PR since the plugin seems more or less abandoned, but I will wait for the answer to @varyvol 's question

**Comment by StefanSpieker** [comment]
@varyvol The mentioned plugin is not build anywhere or listed. The old download URL does not exist either. I guess it would be safe to declare the plugin as dead. Maybe it can be archived somehow? Last update was 2010.

**Review by MarkEWaite — APPROVED** [review]
I think we should approve it based on the ancient date of the last release of that lone plugin that referenced the class.

**Comment by varyvol** [comment]
@StefanSpieker yes, I'm not against this, I just wanted to understand what you meant.

**Review by varyvol — APPROVED** [review]

**Review by fcojfernandez — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
I have no strong opinion here. Such classes indeed cause some maintenance overhead (is it related to the FindBugs cleanup), but public API removal may cause issues in 3rd party plugins we do not know about (proprietary or not). I can confirm that CloudBees does not use this class anywhere, but I am not sure about hundreds of other companies which created their internal plugins and which probably lost expertise/people who can fix them quickly. It is not possible to know full potential impact of breaking changes.

My personal approach is to avoid breaking changes unless they are needed to deliver on the project's goals (security, major features, etc.). I am not blocking this PR, but I ask future maintainers to always keep compatibility in mind. Will add a note to #4472

**Comment by StefanSpieker** [comment]
I'm not sure how to deal with deprecated classes. But if we do not intend to remove some of them, what is the whole point of marking anything as deprecated? I thought that this really old class might be a good start for discussing how to proceed there, especially since it is deprecated for **10 years** now.

**Comment by fcojfernandez** [comment]
@oleg-nenashev both Evaristo and myself approved the PR just after checking the class was deprecated really long time ago and there is no actual use of it. It's true that the only 3rd party we checked was CloudBees plugins since it's the only repo we can check, but with such an elapsed time from the deprecation, we didn't think the policy of retention would be so strict. We take note of that for future reviews and thanks for the guidance

**Comment by oleg-nenashev** [comment]
> But if we do not intend to remove some of them, what is the whole point of marking anything as deprecated?

IMHO it should have been removed in Jenkins 2.0, and it can be easily removed in 3.0. Anything between is a bit more tricky in terms of removals. I am not against removing this particular class if it is an obstacle for any ongoing work, but I am not a big fan of removal just for the sake of removal.

Again, I am not blocking this PR

**Comment by StefanSpieker** [comment]
That would also be a good approach. If we plan to have a version 3.0 in the future - to collect all these unused classes and remove them for version 3.0. Then I would just put exclusions over the classes where I have SpotBugs issues and we somehow mark them for removal for next major release.

**Comment by oleg-nenashev** [comment]
Note that in Jenkins we can also put `@Restricted(DoNotUse.class)` access-modifier annotation which will fail plugin builds against new core versions. It is a more strict addition to the standard `@Deprecated`

**Review by timja — APPROVED** [review]
It's deprecated for 10 years, I vote to remove...

**Comment by oleg-nenashev** [comment]
OK. But let's merge it after the LTS cut-off. We already had enough binary compat issues in the recent months

**Review by MRamonLeon — COMMENTED** [review]
Not sure we can remove it: https://github.com/search?q=org%3Ajenkinsci+stringconverter2&type=Code

It's used by two plugins, not well maintained, for sure, but used. :man_shrugging:

**Review by MRamonLeon — COMMENTED** [review]
Not sure we can remove it: https://github.com/search?q=org%3Ajenkinsci+stringconverter2&type=Code

It's used by two plugins, not well maintained, for sure, but used. :man_shrugging:

**Review by MRamonLeon — APPROVED** [review]
It's a dilemma between keeping compatibility and cleaning the house. I'm for it because of the time the class has been deprecated. Whoever is using it should have changed the code a long time ago

**Review by MRamonLeon — APPROVED** [review]
It's a dilemma between keeping compatibility and cleaning the house. I'm for it because of the time the class has been deprecated. Whoever is using it should have changed the code a long time ago

**Review by MRamonLeon — APPROVED** [review]
It's a dilemma between keeping compatibility and cleaning the house. I'm for it because of the time the class has been deprecated. Whoever is using it should have changed the code a long time ago

**Review by MRamonLeon — APPROVED** [review]
It's a dilemma between keeping compatibility and cleaning the house. I'm for it because of the time the class has been deprecated. Whoever is using it should have changed the code a long time ago

**Review by MRamonLeon — APPROVED** [review]
It's a dilemma between keeping compatibility and cleaning the house. I'm for it because of the time the class has been deprecated. Whoever is using it should have changed the code a long time ago

**Review by MRamonLeon — APPROVED** [review]
It's a dilemma between keeping compatibility and cleaning the house. I'm for it because of the time the class has been deprecated. Whoever is using it should have changed the code a long time ago

**Review by alecharp — APPROVED** [review]

**Review by markjacksonfishing — APPROVED** [review]

**Comment by daniel-beck** [comment]
> IMHO it should have been removed in Jenkins 2.0, and it can be easily removed in 3.0. Anything between is a bit more tricky in terms of removals.

We're not using semver, so this makes no sense at all.

**Review by daniel-beck — APPROVED** [review]

**Comment by daniel-beck** [comment]
> Not sure we can remove it: https://github.com/search?q=org%3Ajenkinsci+stringconverter2&type=Code
> 
> It's used by two plugins, not well maintained, for sure, but used. 🤷‍♂

One is an unused import in a test class. The other is a plugin that was last released in 2008, and hasn't been distributed in 10 years. It has no known installations.

**Comment by daniel-beck** [comment]
> ### Proposed upgrade guidelines
> 
> The serenitec-plugin will not work anymore. It is also not published in Update Center for a couple of years. Try PerfPublisher Plugin instead.

This plugin (see previous comment) is well below the notability threshold for an upgrade guide. I know we're bad at docs, but having a bunch of useless text will just lead to people ignoring what we write.

**Comment by oleg-nenashev** [comment]
We are beyond the LTS cutoff date. Will merge it towards the next weekly if no negative feedback

**Comment by oleg-nenashev** [comment]
@daniel-beck Hm? What is 😕 about? I meant that 2.222 or before are our candidates, but not 2.223 or beyond

**Comment by timja** [comment]
@StefanSpieker WDYT about removing the upgrade guidelines?

**Comment by StefanSpieker** [comment]
@timja : I think they can be removed. I really don't think that there are users affected.

**Pull request merged**
