### PR TITLE
[JENKINS-49401] Move Setup Wizard initialization logic to the init re…

### PR DESCRIPTION
**Pull request by Vlatombe**
…actor.

This way, it is guaranteed the Jenkins version field is not persisted before
the SetupWizard is executed, and computation of the initial Setup Wizard
state will be correct.

Since the SetupWizard is now executed before reaching the COMPLETED
milestone, a Jenkins.save() call has been added in order to persist the current Jenkins version.

See [JENKINS-49401](https://issues.jenkins-ci.org/browse/JENKINS-49401).

### Proposed changelog entries

* Fixed a race condition case that could lead to skip Setup Wizard on the first startup of OEM setups (with groovy scripts or pre-installed plugins).

### Submitter checklist

- [X] JIRA issue is well described
- [X] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@reviewbybees

### CODE REVIEW

**Review by Wadeck — COMMENTED** [review]
> This way, it is guaranteed Jenkins.save() has never been called before
the SetupWizard is executed

FYI the `setSecurityRealm` method at line 3120, 3131 or 3133 will trigger the save before the `SetupWizard`

As I am not an expert in the reactor process, I cannot approve this PR.

**Comment by Vlatombe** [comment]
@Wadeck Any `Jenkins.save()` is a no-op until the InitMilestone.COMPLETED has been reached (see [impl](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/jenkins/model/Jenkins.java#L3161-L3166))

**Comment by jglick** [comment]
> `Jenkins.save()` calls don't update version until the `InitMilestone.COMPLETED` has been reached

…in order to work around some earlier critical bug with the setup wizard, IIRC.

**Review by jglick — COMMENTED** [review]
I have no clue what the impact of this would be. I suppose whatever condition it is fixing is not reproducible enough for a test case.

**Comment by Vlatombe** [comment]
The only way I could reproduce the race condition was by adding a sleep just before the setup wizard initialization.

Then, with a `init.groovy.d` script such as below

```
import jenkins.model.Jenkins
import hudson.init.InitMilestone
import java.util.logging.Logger

Logger logger = Logger.getLogger("save-groovy.groovy")
Thread.start {
    for(int i = 0; i < 100000; i++) {
    if (Jenkins.instance.installState != jenkins.install.InstallState.UNKNOWN) {
      logger.info("Too late")
      break;
    } else if (Jenkins.instance.initLevel == InitMilestone.COMPLETED) {
      Jenkins.instance.save()
      break;
    }
  }
}
```

I could trigger the issue.

I have seen that race condition occur several times on real environment, the competing thread creating cloud instances in Jenkins, causing `save()` to be called in the process.

**Comment by oleg-nenashev** [comment]
Sorry, I do not plan to review this PR anytime soon

**Comment by Vlatombe** [comment]
Unless there are objections, I'll merge this at the end of the week.

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers @reviewbybees  bump

**Pull request merged**
