### PR TITLE
Lithuanian translation update

### PR DESCRIPTION
**Pull request by tomass**

### CODE REVIEW

**Comment by daniel-beck** [comment]
This looks like a work in progress, given the number of English descriptions in the Lithuanian properties file.

**Comment by tomass** [comment]
One of the files does have a lot of still untranslated items (and there are still a lot of other properties files which still have no Lithuanian versions yet). But there are a lot of other translations in this PR which would be nice to see in weekly builds of 2.0. To test/check/validate.
It the PR is "too small", what would be the limit?

**Comment by daniel-beck** [comment]
>  It the PR is "too small", what would be the limit?

Not about it being too small, it's just that having any strings in the localized Messages file will make tools consider them to be already translated. So I recommend you remove untranslated (English) placeholder strings in your Lithuanian resource file.

**Comment by tomass** [comment]
I have finished translating the file in question. Not sure if github will pick it up and merge into the same PR (i'm not an expert in git/github).
If I remove non translated strings then it will be much harder to find untranslated strings later...

**Comment by daniel-beck** [comment]
@tomass The PR is updated. Thank you. I wonder whether someone in the project team speaks Lithuanian… @jenkinsci/code-reviewers any idea?

**Comment by tomass** [comment]
Same question about somebody speaking Lithuanian was asked in my previous PR. Nobody showed up in 3 months:
https://github.com/jenkinsci/jenkins/pull/1990

**Comment by daniel-beck** [comment]
@tomass Good point. In that case, since all strings appear to be translated now, I'll go ahead and merge. Thanks!

**Pull request merged**
