### PR TITLE
[JENKINS-35263] displaying codeMirror as table to fix page sizing

### PR DESCRIPTION
**Pull request by gusreiber**
td.setting-main .CodeMirror {
display: table;
table-layout: fixed;
width: 100%;
}

Setting as suggested by Dmitry Medvedev
https://issues.jenkins-ci.org/browse/JENKINS-27367

Take 2

### CODE REVIEW

**Comment by gusreiber** [comment]
@jenkinsci/code-reviewers @daniel-beck @recena 
Please review.

**Comment by recena** [comment]
👎  there is a isolated CSS file for everything related with the layout `layout-common.css`.

**Comment by recena** [comment]
@gusreiber I don't understand the relation between these changes and the UI issue.

**Comment by daniel-beck** [comment]
@gusreiber There are tons of seemingly unrelated changes (including at least one that appears to roll back specific earlier improvements), were you working off an outdated version and messed up the merge?

**Pull request closed without merging**
