### PR TITLE
Note some nonnull parameters

### PR DESCRIPTION
**Pull request by recampbell**
This will result in NPE if passed as null.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@recampbell 
I would explicitly handle null Strings to workaround JENKINS-26646.
Since we have existing mistakes, IMO there's no need to force the <code>@Nonnull</code> restriction

**Comment by recampbell** [comment]
@oleg-nenashev Well, I think the idea is to force plugins to better handle the consequences of having a null name list.

This would just be a Findbugs error, and wouldn't break any runtime behavior.

**Comment by recampbell** [comment]
I also need to request @reviewbybees as part of an internal cloudbees review process for PR's that I submit.

**Comment by oleg-nenashev** [comment]
In general, I would agree with <code>@Nonnull</code>, but...
* Jenkins plugins won't get an info about contract violations till they update the dependency to the new core version 
* The core will continue failing with NPEs with improper plugins
* The function has no Javadoc documentation, hence the behavior is undefined => an explicit handling seems to be the most compatible resolution

**Comment by jglick** [comment]
I think `@Nonnull` is appropriate here; the function was clearly expected to work with non-null parameters. Any NPEs resulting from plugin bugs should be caught at a higher level (for example by #1550). Of course fuller Javadoc would be a bonus. :+1:

**Comment by stephenc** [comment]
:+1: these methods would throw an NPE if a null was passed anyway, so any existing plugins unaware of the contract would have bugs that findbugs can catch for them more easily with these annotations added

**Pull request merged**
