### PR TITLE
[JENKINS-62332] Remove plugin update GUI “A newer version than being offered for installation exists…”

### PR DESCRIPTION
**Pull request by jglick**
See [JENKINS-62332](https://issues.jenkins.io/browse/JENKINS-62332). Reverts #4742 by @daniel-beck as well as amendments like #5462 and #6656. Would allow https://github.com/jenkins-infra/update-center2/pull/382 to be reverted as well, I suppose (not clear to me whether it imposes a significant performance cost).

While I understand the intention behind the original GUI addition, in practice it is just confusing. Even @lemeurherve working on the Jenkins project’s _own Jenkins server_ was asking (private channel)

> Just noticed these 2 plugins incompatible with ci.jenkins.io Jenkins version…
> Is there something I can do about it? Or does it mean we have to downgrade Jenkins version on ci.jenkins.io?

about `cloudbees-folder` and `jobConfigHistory`. I also saw an earlier conversation between @jtnord and @dduportal wondering why the UC was offering incompatible plugin updates. (It was not.)

If there is even any value in being told that some plugin update _would_ be available if you had a newer core—and generally there is not, unless you are running a pretty old core to begin with—maybe there would be some reasonable way to present that, like in a footnote in the **Updates** tab offering an expandable box with a list of such cases. But unless and until someone steps up to write such a GUI, I think the current alert does more harm than good—especially when we have been picking up the pace of adopting new `jenkins.version`s in plugins when helpful for new APIs, to adapt to frequent GUI tweaks, etc.

### Testing done

Exploring GUI after

```diff
diff --git core/src/main/java/hudson/model/UpdateSite.java core/src/main/java/hudson/model/UpdateSite.java
index 3b0c2af09d..f25374d547 100644
--- core/src/main/java/hudson/model/UpdateSite.java
+++ core/src/main/java/hudson/model/UpdateSite.java
@@ -1236,6 +1236,7 @@ public class UpdateSite {
             this.excerpt = get(o, "excerpt");
             this.compatibleSinceVersion = Util.intern(get(o, "compatibleSinceVersion"));
             this.latest = get(o, "latest");
+            if (name.equals("cloudbees-folder")) latest = "9999";
             this.requiredCore = Util.intern(get(o, "requiredCore"));
             final String releaseTimestamp = get(o, "releaseTimestamp");
             Date date = null;
```

### Proposed changelog entries

- Remove the notice in the plugin manager **Updates** tab about newer plugin versions not compatible with your current core version. Limit the display of updates to plugin versions actually being offered by the update center for your core version.

### Proposed upgrade guidelines

N/A

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7362"></a>

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by dduportal** [comment]
I'm +1 with this change. I won't approve neither refuse because I don't feel legit on the code (or testing the change) but the intent is clearly a good thing.

Adding entries about "new plugin version that can be installed" is really confusing and makes Jenkins administrators asking "what did I do wrong so that I cannot install this new plugin". I consider this a bug as a user.

If I understand correctly, the intent was to fix another case which was: "I see a new version of a plugin in a security advisory and/or in plugins.jenkins but I can"t see this version on the Update center of my Jenkins instance". Which also feels "buggy". By merging this PR, we would switch from 1 behavior to the other.

As proposed by @jglick (at least, and I can't remember where), it could be useful to add (subsequent PR, or here, no opinion) a static message in the update center UI telling the user to update their core version (or wait for the next LTS) so that it would the solve the 2nd behavior. WDYT?

**Comment by jglick** [comment]
> By merging this PR, we would switch from 1 behavior to the other.

Correct.

> it could be useful to add…

Right, something like this is what I referred to in the PR description as

> some reasonable way to present that

**Comment by NotMyFault** [comment]
@daniel-beck You reacted with 👎🏻 on the initial PR body, would you mind clarifying your concerns or worries, please?

**Comment by daniel-beck** [comment]
> would you mind clarifying your concerns or worries

Removing the feature entirely looks certainly easy enough to do, but seems undesirable to me. The original change was implemented for a reason after all.

A good fix would be to adapt the UI to make it clearer these aren't updates available for installation (as mentioned, e.g. listing them elsewhere) to reduce any user confusion without removing potentially useful information.

**Comment by jglick** [comment]
As mentioned in the PR description, of course it would be nice to have a more refined GUI listing these unavailable updates in some clearer way, but this also sounds like some work to do and no one has yet volunteered to do it; and my opinion remains that the current UX is worse than nothing (especially now that the situation has become commonplace in widely-installed plugins due to GUI changes coördinated with core).

**Review by jtnord — APPROVED** [review]
To me the current ui is confusing and worse than no UI.

Could be reverted in the future to provide a better UX

**Review by NotMyFault — APPROVED** [review]

**Comment by timja** [comment]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Pull request merged**
