### PR TITLE
[JENKINS-51062] Extend ClassFilterImpl.isLocationWhitelisted Maven-oriented exclusions to plugin under test during Gradle builds

### PR DESCRIPTION
**Pull request by jglick**
Allows test under discussion in https://github.com/jenkinsci/gradle-plugin/pull/55 by @fcojfernandez to pass. Should not affect production runs, just functional tests.

https://issues.jenkins-ci.org/browse/JENKINS-51062

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
🐝

**Review by fcojfernandez — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
I will merge it, because we may need it to be backported to the next LTS baseline.
Not sure about 2.107.3, likely too late to consider such patch. CC @olivergondza

**Comment by recena** [comment]
Just in case you want to know my opinion, 👎  for backporting.

**Comment by daniel-beck** [comment]
There's a solid chance it'd be missed anyway as we're going to stage the 2.107.3 security update on Monday, and don't plan on running another merge-up before then.

**Comment by recena** [comment]
@daniel-beck I was thinking on it. 👍

**Pull request merged**
