### PR TITLE
[JENKINS-66507] Bump XStream from 1.4.17 to 1.4.18

### PR DESCRIPTION
**Pull request by basil**
Supersedes #5683. Adapts `hudson.util.RobustReflectionConverterTest#ifWorkaroundNeeded` to changes in the XStream framework.

## Proposed changelog entries

* Internal: Upgrade XStream 1.4.17 to 1.4.18
  *  XStream Changelog: http://x-stream.github.io/changes.html

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]

**Review by MarkEWaite — APPROVED** [review]
Reviewed the changes between 1.4.17 and 1.4.18 and they all seem to be related to unitialized security framework conditions.  Jenkins initializes the security framework.

**Comment by MarkEWaite** [comment]
This PR is now ready for merge.  We will merge it after approximately 24 hours if there is no negative feedback.

**Review by Wadeck — APPROVED** [review]
Not manually tested but seems fine. Thanks for the bump @basil 

This will prevent scanners to detect 14 CVEs... :)

**Review by bmunozm — APPROVED** [review]

**Review by daniel-beck — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
Updated the changelog. It is ready to go IMO

**Pull request merged**
