### PR TITLE
[Not Sure I want to merge this] follow-up to #1645 that reduces the number of snapshot updates

### PR DESCRIPTION
**Pull request by stephenc**
@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
Still not quite sure I understand what is going on here, but :+1:

**Comment by stephenc** [comment]
This removes the redundant call to updateSnapshot that the finally block was ensuring. In #1645 I wanted to leave the finally block where it was rather than move it up. I considered the extra snapshot generation worth the simplicity of the patch. This secondary change moves the inner-most finally to the last point of certain change. Now a640438 then adds the required finally that #1645 was using so that if an exception is thrown in the for loop while a task is being assigned to an executor, then at least we exit the maintain method with a valid and correct snapshot...

@jglick I hope the complexity that this adds shows why I went for the simpler duplication of call ;-)

**Comment by jglick** [comment]
My head is spinning but :+1:

**Comment by stephenc** [comment]
@jglick if your head is spinning, my inclination is to stick with the original implementation from #1645 rather than try and optimize away one method call in the finally block (that needs to be there in case an exception is thrown while assigning work to executors)

**Comment by oleg-nenashev** [comment]
:+1: for [Not sure I want to merge this]. We can leave the PR active till somebody performs some benchmarks.

**Comment by stephenc** [comment]
Not worth the extra complexity

**Pull request closed without merging**
