### PR TITLE
Update remoting to 2.62.

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Changes are listed below:

Fixed issues:
- [JENKINS-22853](https://issues.jenkins-ci.org/browse/JENKINS-22853) -
  Be robust against the delayed EOF command when unexporting input and output streams.
  (https://github.com/jenkinsci/remoting/pull/97)
- Fixed ~20 minor issues reported by FindBugs.
  More fixes to be delivered in future versions.
  (https://github.com/jenkinsci/remoting/pull/96)

Enhancements:
- [JENKINS-37218](https://issues.jenkins-ci.org/browse/JENKINS-37218) -
  Performance: <code>ClassFilter</code> does not use Regular Expressions anymore to match <code>String.startsWith</code> patterns.
  (https://github.com/jenkinsci/remoting/pull/92)
- [JENKINS-37031](https://issues.jenkins-ci.org/browse/JENKINS-37031)
  <code>TcpSlaveAgentListener</code> now publishes a list of supported agent protocols to speed up connection setup.
  (https://github.com/jenkinsci/remoting/pull/93)

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
The release is to be done soon from the https://github.com/jenkinsci/remoting/tree/stable-2.x branch

**Comment by oleg-nenashev** [comment]
CC @jenkinsci/code-reviewers @reviewbybees

Are you fine with these changes?

**Comment by daniel-beck** [comment]
@oleg-nenashev So this is what's going in?

https://github.com/jenkinsci/remoting/compare/remoting-2.61...stable-2.x

**Comment by oleg-nenashev** [comment]
@daniel-beck yes

**Comment by oleg-nenashev** [comment]
I'll update Jenkins changelog once @kohsuke finishes the release

**Pull request merged**
