### PR TITLE
[JENKINS-56575] Support REST client for restart

### PR DESCRIPTION
**Pull request by Wadeck**
❗️ Closed in favor of #4030

----

Alternative proposed in #3937 using `Accept` instead of `Referer`.
- The REST clients must use `Accept: application/json` as a distinction factor.
- In addition, multiple tests are provided to cover the existing code and the new one

See [JENKINS-56575](https://issues.jenkins-ci.org/browse/JENKINS-56575).

### Proposed changelog entries

* Improve support for REST clients in the `restart` and `safeRestart` web methods

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [n/a] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@P01son6415

### CODE REVIEW

**Comment by P01son6415** [comment]
> The use of referer header as a distinction factor between regular HTTP client and pure REST client is misleading. You can encounter troubles if a user has privacy oriented configuration, like Firefox [sendRefererHeader](http://kb.mozillazine.org/Network.http.sendRefererHeader).
>
>If you read the linked page you will see that there is a warning that this option can break compatibility with some websites. Generally that's the case when the application is using the referer as the way to counter CSRF (wrong way but that's another topic).
>
>I can only advice you to use Accept header with application/json or an additional parameter in the request to distinguish between regular and rest clients (preference for the accept option).
Both proposals are easy to apply on the rest client, could it be simple curl, Postman or anything else.

Thank you for modifying my PR #3937. I totally agree with you, this is what I did not think of before.

**Comment by LinuxSuRen** [comment]
We might consider this mechanism as a more common way. There're still other places have the same issues.

**Comment by batmat** [comment]
Failure looks infra related... Retriggering.

**Comment by LinuxSuRen** [comment]
> Another option might be to add a custom HTTP header to indicate you're in a REST client or in the UI.

Agree with this idea. We can give a unify custom HTTP header to indicate this. And it's better to put the final solution into a document.

**Comment by Wadeck** [comment]
> [...] custom HTTP header [...]

If I used the `Accept` and `application/json` that are both standard, is to avoid restrictive firewall rules. In some companies, using a custom header could require to create a "change request" and to have good reasons to convince the internal security team. In our case, there is no good reason yet.

> There're still other places [...]

Please provide them to better understand how we could solve it with a common pattern.

**Comment by Wadeck** [comment]
Closed in favor of #4022.

**Comment by Wadeck** [comment]
FTR I reported https://issues.jenkins-ci.org/browse/JENKINS-57464 for the test failure here

**Pull request closed without merging**
