### PR TITLE
[JENKINS-26466] Decouple AbstractProject from DiskSpaceMonitor

### PR DESCRIPTION
**Pull request by batmat**
This modification is one of the preliminary steps to the full plugin extraction later (see JIRA above).
Basically reverts a8c3a031c.

### CODE REVIEW

**Comment by daniel-beck** [comment]
:+1:

**Comment by batmat** [comment]
For reference, I first wrote [another version](https://github.com/batmat/jenkins/commit/9561ae96fe1e29be68f928bc175f30280bd6d521) but as advised by @jglick I finally went on the leaner removal version.

**Comment by oleg-nenashev** [comment]
I have no strong opinion. Are you planning to somehow implement it in the decoupled plugin?
Also CC @ndeloof

**Comment by jtnord** [comment]
:+1:

**Comment by batmat** [comment]
@oleg-nenashev No I didn't plan to currently, but if people think it's useful I can absolutely consider doing so. That may require introducing another new extension point like the one in https://github.com/jenkinsci/jenkins/pull/1985

It would also indeed be useful to have a word of @ndeloof about the use case that led him to add this code at the time. If he still thinks this should be kept at least in the short term, I can file a new JIRA and will consider reintroducing that.

**Comment by olivergondza** [comment]
The use-case, as I understand it, is that some part of core *suspect* the slave can be out of disk space and should have a was to ask monitoring subsystem to have the slave rechecked and turned offline eventualy. There is lot more places like that in core - not to mention this is not specific to diskspace monitoring. For some time I wanted to refactor the code so this will be possible for all the monitors, but never actually had time to.

:+1:

**Comment by oleg-nenashev** [comment]
ready to go, because there was no votes against the change

**Comment by batmat** [comment]
Ping @oleg-nenashev anything still missing?

**Comment by batmat** [comment]
Thanks Oliver.
Le 30 janv. 2016 7:05 AM, "Oliver Gondža" <notifications@github.com> a
écrit :

**Pull request merged**
