### PR TITLE
[WIP] Continue work to restore/fixup packaging tests

### PR DESCRIPTION
**Pull request by svanoort**
What it says on the tin.  

This is intended to replace https://github.com/jenkinsci/jenkins/pull/2553 but include tests back, with some appropriate fixups.

### CODE REVIEW

**Comment by svanoort** [comment]
@rtyler Sticking point appears to be some really quirky behaviors with the docker agents, even with direct 'docker pull' calls.

```
Branch indexing
Connecting to https://api.github.com using jenkinsadmin/****** (GitHub access token for jenkinsadmin)
Fetching changes from 2 remote Git repositories
Checking out Revision 87ae04433e0f4b0a013ff838097399bde67cf6ce (PR-2560)
[Pipeline] properties
[Pipeline] node
Running on kelp in /home/jenkins/agent-workspace/workspace/Core/jenkins/PR-2560
[Pipeline] {
[Pipeline] timestamps
[Pipeline] {
[Pipeline] sh
[PR-2560] Running shell script
+ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
[Pipeline] dir
Running in /home/jenkins/agent-workspace/workspace/Core/jenkins/PR-2560/packaging
[Pipeline] {
[Pipeline] git
Fetching changes from the remote Git repository
Checking out Revision 25aaec9d5f459b2627aaad9808e57993f453ada4 (refs/remotes/origin/master)
[Pipeline] stage
[Pipeline] { (Packaging - Preparation)
[Pipeline] sh
[packaging] Running shell script
+ docker rmi ubuntu:14.04 ubuntu:15.10 centos:6 opensuse:13.2 centos:7
Error response from daemon: could not find image: no such id: ubuntu:14.04
Error response from daemon: could not find image: no such id: ubuntu:15.10
Error response from daemon: could not find image: no such id: centos:6
Error response from daemon: could not find image: no such id: opensuse:13.2
Error response from daemon: could not find image: no such id: centos:7
Error: failed to remove images: [ubuntu:14.04 ubuntu:15.10 centos:6 opensuse:13.2 centos:7]
+ true
[Pipeline] sh
[packaging] Running shell script
+ docker pull ubuntu:14.04
14.04: Pulling from library/ubuntu
ec28102fa49d: Pulling fs layer
b9e69457a8ff: Pulling fs layer
b564cfd8b964: Pulling fs layer
63208b379d15: Pulling fs layer
3abfbfa47972: Pulling fs layer
03d58ee64e1d: Pulling fs layer
3abfbfa47972: Verifying Checksum
3abfbfa47972: Download complete
b9e69457a8ff: Verifying Checksum
b9e69457a8ff: Download complete
03d58ee64e1d: Verifying Checksum
03d58ee64e1d: Download complete
63208b379d15: Verifying Checksum
63208b379d15: Download complete
b564cfd8b964: Verifying Checksum
b564cfd8b964: Download complete
ec28102fa49d: Verifying Checksum
ec28102fa49d: Download complete
ec28102fa49d: Pull complete
b9e69457a8ff: Pull complete
b564cfd8b964: Pull complete
63208b379d15: Pull complete
3abfbfa47972: Pull complete
03d58ee64e1d: Pull complete
Digest: sha256:cefbab7ba48dd9721a183cf9067b94870a56fa9bbb4b70f9d1880f8972b34d7a
Status: Downloaded newer image for ubuntu:14.04
[Pipeline] sh
[packaging] Running shell script
+ docker pull centos:6
6: Pulling from library/centos
c0babb11d964: Pulling fs layer
4663a24f3189: Pulling fs layer
9e3ecb103916: Pulling fs layer
9e3ecb103916: Verifying Checksum
9e3ecb103916: Download complete
c0babb11d964: Verifying Checksum
c0babb11d964: Download complete
c0babb11d964: Pull complete
Pulling repository docker.io/library/centos
Tag 6 not found in repository docker.io/library/centos
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 1
Finished: FAILURE
```

From chatter I've caught it *might* be fixed by upgrading docker (maybe worth trying on a small test node). 

```shell
sh 'docker rmi ubuntu:14.04 ubuntu:15.10 centos:6 opensuse:13.2 centos:7 || true'
 sh 'docker pull ubuntu:14.04 '
sh 'docker pull centos:6'
sh 'docker pull ubuntu:15.10'
 sh 'docker pull debian:wheezy'
sh 'docker pull opensuse:13.2'
```

**Comment by rtyler** [comment]
@svanoort would you mind filing an INFRA ticket to upgrade our Docker version to something that looks more gooder?

I'll try to squeeze that into this week and scheduled a maintenance notice

**Comment by svanoort** [comment]
Reopens due to CI hitting permgen fails :(

**Comment by svanoort** [comment]
Test failure is fairly straightforward to resolve.  On it over the weekend.

**Comment by rtyler** [comment]
```
15:59:51 + find . -iname jenkins.war
15:59:51 ./war/target/jenkins.war
```

found it!

**Comment by svanoort** [comment]
Container install is hosed.  Should be fairly obvious fix?

**Comment by rtyler** [comment]
@svanoort are you asking that rhetorically or are you asking me to jump in.

**Comment by svanoort** [comment]
@rtyler Nono, I'm commenting so you know I'm still hammering out the remaining small issues.

**Comment by oleg-nenashev** [comment]
@rtyler @svanoort Any plans to finish it?

**Comment by svanoort** [comment]
@oleg-nenashev Yes.  I need it to test the work on https://cloudbees.atlassian.net/browse/OSS-1554 so it's being wrapped up as part of that.

**Comment by rtyler** [comment]
*casually points out that @svanoort is linking to CloudBees-internal JIRAs*

**Comment by oleg-nenashev** [comment]
@svanoort any plans to finalize it?

**Comment by svanoort** [comment]
@oleg-nenashev Doubtful - the packaging tests were rather brittle, and now that people are increasingly using Docker packaging they seem less valuable.

**Comment by oleg-nenashev** [comment]
@svanoort I suggest closing it then

**Comment by svanoort** [comment]
Closing with much regret -- I tried but clearly others aren't that interested in ensuring Jenkins starts up successfully.

**Pull request closed without merging**
