### PR TITLE
[JENKINS-49316] Create Item: OK button disabled until TAB pressed

### PR DESCRIPTION
**Pull request by HuangJY777**
change Init CopyFromField function and let the ok button in newJob page be changed when user input words to CopyFromField

See [JENKINS-49316](https://issues.jenkins-ci.org/browse/JENKINS-49316).

### CODE REVIEW

**Review by halkeye — CHANGES_REQUESTED** [review]
Tab should trigger blur (leaving the element). So I'm not sure what this is fixing. On input would be every time a key is pressed, which would mean its hitting the backend for every key press.

I don't think this fixes any issues. And while I don't think most jenkins instances actually gets a ton of traffic, I don't think its the right solution.

**Comment by halkeye** [comment]
You are right that its not working though...

**Comment by halkeye** [comment]
Ah, my bad, I totally misread the bug. Yes this fixes the problem.

I personally think its fine the way it is, but it does fix. Approving.

**Review by halkeye — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Thanks @HuangJY777 @halkeye ! Will get it merged early next week if there is no negative feedback

**Review by Wadeck — APPROVED** [review]

**Pull request merged**
