### PR TITLE
fix letter-spacing

### PR DESCRIPTION
**Pull request by Gadzy**
Negative letter spacing should be avoided. It greatly decreases legibility and accessibility.
See [JENKINS-70209](https://issues.jenkins.io/browse/JENKINS-70209).

### Testing done

Manual testing done. No need for automated testing.

### Proposed changelog entries

- Remove negative letter-spacing to improve legibility in some languages and fonts

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] The Jira issue, if it exists, is well-described.
- [X] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [X] There is automated testing or an explanation as to why this change has no tests.
- [X] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ X New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [X] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [X] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [X] For new APIs and extension points, there is a link to at least one consumer.

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7475"></a>

### CODE REVIEW

**Comment by MarkEWaite** [comment]
Can you provide more details of the interactive testing that you performed?  This seems like a change that will have a wide impact in many places.

**Comment by daniel-beck** [comment]
FTR introduced as an undocumented change in https://github.com/jenkinsci/jenkins/pull/6084, later increased in https://github.com/jenkinsci/jenkins/pull/6614

> for better legibility

**Comment by Gadzy** [comment]
@janfaracik  How can I help with this PR ?

**Comment by timja** [comment]
@janfaracik possible to take a look at this?

**Comment by janfaracik** [comment]
> @janfaracik  How can I help with this PR ?

If the letter spacing is impacting your font/language then absolutely removing it is the right choice 👍

**Review by janfaracik — APPROVED** [review]

**Comment by NotMyFault** [comment]
@Gadzy It would be helpful if you would've included a couple of screenshots of the current behavior vs your change proposed, because applying this PR to weekly.ci.j doesn't change anything for me.

**Review by timja — APPROVED** [review]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Pull request merged**
