### PR TITLE
Use modern icons in workspace view of a job

### PR DESCRIPTION
**Pull request by NotMyFault**
The change proposed utilizes existing SVG icons at the `/ws` view of a job instead of legacy icons.

### Proposed changelog entries

* Use modern icons at the workspace view.

### Proposed upgrade guidelines

The following GIF and PNG icons have been removed in favor of appropriate SVGs:
folder-error -> folder-delete
text-error -> document-delete
text -> document

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
conflicts

**Comment by oleg-nenashev** [comment]
I am pretty sure there external dependencies on these icons...

**Comment by timja** [comment]
> I am pretty sure there external dependencies on these icons...

Looks like a couple:

https://cs.github.com/?q=org%3Ajenkinsci+text.png
https://github.com/search?p=1&q=org%3Ajenkinsci+text.png&type=Code

**Comment by oleg-nenashev** [comment]
Should we just add it to the upgrade guide?

**Comment by NotMyFault** [comment]
> Should we just add it to the upgrade guide?

I've summed the replacement a bit up.

**Comment by timja** [comment]
Change log entry?

**Comment by NotMyFault** [comment]
> Change log entry?

Added

**Comment by daniel-beck** [comment]
Since when did we start to randomly break shit just because it's convenient? There's a very long tail of not very actively maintained plugins, and while it can be annoying to remain compatible, bundling icons is basically free. What am I missing?

**Review by janfaracik — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by daniel-beck** [comment]
Why delete the icons? This was like 1 weekly release after I modernized https://plugins.jenkins.io/cctray-xml/ which uses these same icons.

**Pull request merged**
