### PR TITLE
Rename HudsonIsLoading/Restarting to JenkinsIs...

### PR DESCRIPTION
**Pull request by daniel-beck**
I don't expect there are many callers to these classes (unverified, waiting for PR build) so it should be safe to rename.

Untested

WDYT?

### Proposed changelog entries

* Entry 1: Issue, Human-readable Text
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by basil** [comment]
Seems fine to me. Apparently there's a usage of `hudson.util.HudsonIsRestarting` in [CloudBees License Manager](https://docs.cloudbees.com/plugins/ci/cloudbees-license).

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
I would rather keep the old class tombstone as a Deprecated NoExternalUse one. It can inherit JenkinsIsRestarting, similarly to how Jenkins and Hudson classes exist

**Comment by daniel-beck** [comment]
> I would rather keep the old class tombstone as a Deprecated NoExternalUse one. It can inherit JenkinsIsRestarting, similarly to how Jenkins and Hudson classes exist

Disagree, with a single reference in a proprietary plugin and nothing else there's no need to add complexity to core for compatibility.

**Review by timja — APPROVED** [review]

**Review by basil — APPROVED** [review]

**Review by oleg-nenashev — COMMENTED** [review]
I reviewed it, and I still see no reason to not retain binary compatibility. I was unable to find any usages, hence I do not feel strongly about that. Would be nice to get one more review from @jenkinsci/core

**Review by res0nance — APPROVED** [review]
Since there seems to be only 1 known use this doesn't seem very useful for most so I think its ok to rename

**Review by jglick — CHANGES_REQUESTED** [review]
Besides a known plugin incompatibility, this would break a Groovy script I have used

```groovy
// Similar to Jenkins.restart() but does not include a background thread or a 5s delay.
Jenkins.instance.servletContext.setAttribute('app', new hudson.util.HudsonIsRestarting())
Jenkins.restartableLifecycle().restart()
```

There are tons of code names in core, not to mention package names, referring to Hudson which we cannot possibly expect to rename. I do not see the point of introducing a gratuitous incompatibility.

**Pull request closed without merging**
