### PR TITLE
[JENKINS-41932, JENKINS-42176] - Update libzfs4j from 0.5 to 0.8

### PR DESCRIPTION
**Pull request by oleg-nenashev**
So this PR updates `libzfs` from a 8-year-old release (0.5) to the newest one, which has been updated by @kohsuke and @jimklimov in order to get better support of new forks of Solaris.

Full diff: https://github.com/kohsuke/libzfs4j/compare/libzfs-0.5...libzfs-0.8. Reviews are welcome

## Changelog entry:

* JENKINS-41949, JENKINS-41932 - Update LibZFS from 0.5 to 0.8 to fix compatibility issues with ZFS filesystem and illumos distributions.

CC @jimklimov

### CODE REVIEW

**Comment by jimklimov** [comment]
I believe the source URL may have to be changed somewhere. The original version was on java.net, the new one is on github.

**Comment by oleg-nenashev** [comment]
And.... there is a binary compatibility issue in the lib

**Comment by oleg-nenashev** [comment]
@kohsuke @jimklimov so `allow()` and `unallow()` methods have been removed by @kohsuke in https://github.com/kohsuke/libzfs4j/commit/4b1b412fd74e1da8a79a8e1ca62f516f8293c6d7 . I cannot elaborate the impac, so it is up to you to provide further step guidelines

**Comment by jimklimov** [comment]
I'd vouch for returning the methods, if only to satisfy Jenkins core's desires (and possibly even active usage), perhaps as togglables in the recent fashion (I think we can even auto-detect presence or lack of them in the run-time host ZFS ABI).

I'm not sure what should be done if they are absent (which seems likely on new platforms) - log and/or noop, or some sort of exception to better notice where in Jenkins or other consumers the rotten codepath is called (and if someone does use that - look for modern alternatives to these calls)? In aim for stability, I'd go for log+noop...

**Comment by oleg-nenashev** [comment]
log+noop is fine for me

**Comment by kohsuke** [comment]
I don't recall exactly what test failure I saw that led me to remove it. I need to work on this.

I agree the binary compatibility should be restored somehow.

**Comment by jimklimov** [comment]
I *think* when I made the original fixes a month ago, I looked and could not find the allow routines in current OpenZFS code, so they must have been gone (or perhaps renamed?) a long time ago :) so I did not look closer at "restoring" them back then.

**Comment by jimklimov** [comment]
Posted https://github.com/kohsuke/libzfs4j/pull/6 with my take on this repair.

Looking at code changes, I see that also since libzfs-0.5 the `zfs_send` and `zfs_receive` got commented away in https://github.com/kohsuke/libzfs4j/commit/494c719be432a08a9b04e7fa5186de259bcba458

They might become next nits of the CI tests, or not...

**Comment by jimklimov** [comment]
Also, `zpool_vdev_name` got a new Bool verbose argument in https://github.com/kohsuke/libzfs4j/commit/e9a6178a798447b3b8c40d717b44d23f70158bfb

**Comment by oleg-nenashev** [comment]
@jimklimov Yes, I think we just need to fix the compatibility in the core and then ensure that plugins like https://github.com/jenkinsci/zfs-plugin do not blow up as well. BTW it has been never released from what I see, CC @ndeloof

**Comment by ndeloof** [comment]
@oleg-nenashev I'm not a maintainer on this one, just had wrote a script to update all plugins as jenkins-ci changed maven infra in 2012

**Comment by oleg-nenashev** [comment]
@ndeloof Yeah, sorry. Will ask @kohsuke what is that and how to proceed with that plugin

**Comment by jimklimov** [comment]
So, for now we are waiting for https://github.com/kohsuke/libzfs4j/pull/6 to get reviewed to perfection and ultimately merged, then probably this PR will raise the bar to require `libzfs-0.8.jar`, and rebuild to see if they fit together now :) Right?

**Comment by oleg-nenashev** [comment]
Yep. Once you get a new release, just ping me.
By the way, you can run the Jenkins build locally with a snapshot versions  of the library to test if everything else is fine

**Comment by oleg-nenashev** [comment]
It is good to go, one PR build has passed.
@jenkinsci/code-reviewers any concerns?

**Review by MarkEWaite — APPROVED** [review]
No objection from me.

**Review by oleg-nenashev — COMMENTED** [review]
The latests state is fine for me as well

**Comment by oleg-nenashev** [comment]
@jimklimov I would appreciate if you could help with a proper changelog entry (or entries), which would address ZFS users. If there are existing issues reporting to Jenkins, it would be great to have links as well

**Comment by jimklimov** [comment]
Hi, I am not sure about links... I did post some issues in Jenkins JIRA, some can be pursued later separately from this story (building on it), but can try some log entry to summarize what we ended up with in the end :)

> Subj: Improve portability of Jenkins CI to illumos distros - SunOS descendants based on modern OpenZFS
> Kudos: Kohsuke Kawaguchi, Jim Klimov, Oleg Nenashev, Adam Stevko
> Details: Since the ZFS was introduced in Sun Solaris over a decade ago, the main interaction API was to use command-line tools. Also an OS-internal native library `libzfs.so` was available, interfacing those tools to the OS kernel. In absence of other ABIs, a few projects still risked to link against this "uncommitted" library - including the `libzfs.jar` wrapper employed by Jenkins CI on matching platforms. As time went and Solaris evolved, some function signatures were changed in the library, causing a moderate bit of headache for consumers like this wrapper - but it could be handwaved by requiring an upgrade to the newest release of the single OS. As more time had passed, OpenSolaris and later illumos and numerous open-source distributions had splintered off from Solaris (which went its own proprietary path under Oracle stewardship). Also ZFS was adopted into multiple other operating system kernels (including BSD, Linux and MacOS efforts), cross-pollinating under the foundations of OpenZFS. The `libzfs.so` library is still an "uncommitted implementation detail" of respective distributions, with random ABI changes causing now a much bigger headache due to fragmentation - because there is no single ZFS-wielding OS that you can require an upgrade to, and because there are dozens of combinations of possible function signatures that can be present in a particular OS deployment. The effect for `libzfs.jar` and Jenkins CI was that as the CI server booted up on an OS with incompatible function signatures (and began interacting with ZFS datasets), its Java process just dumped core and died - and with evolution of OpenZFS consuming and contributing operating systems, it became more likely than not to expect a wrong single fixed ABI. The accepted solution for `libzfs.jar` wrapper was to identify which of the wrapped routines have different native ABI signatures "in the wild" and introduce a way to pick and call the correct signature during run-time. While the JAR tries its best to guess the correct set for a given host OS, it includes a way for the end-user (sysadmin) to enforce particular implementation for each such function, using environment variables or java properties. Also this technique is expandable, to uniformly handle more such cases as the future comes down upon us :)

**Comment by jimklimov** [comment]
Googled up some links for "Jenkins" and "SunOS" and "ZFS" :)


* The bolting to "SunOS" (in Jenkins installer - I did not find any such constraints in the JAR itself, except that the paths speak of `solaris`):
** https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/os/solaris/ZFSInstaller.java
** https://groups.google.com/forum/#!topic/jenkinsci-dev/z-t-L0bxQCw

* Previous woes about ABI change between ZFS versions and/or running on Solaris distros without ZFS at all - e.g. older releases:
** https://issues.jenkins-ci.org/browse/JENKINS-5046
** https://issues.jenkins-ci.org/browse/JENKINS-3044
** https://issues.jenkins-ci.org/browse/JENKINS-3052
** https://issues.jenkins-ci.org/browse/JENKINS-3250

* My issues on the matter:
** https://issues.jenkins-ci.org/browse/JENKINS-41949
** https://issues.jenkins-ci.org/browse/JENKINS-41932
** https://issues.jenkins-ci.org/browse/JENKINS-42176

**Comment by oleg-nenashev** [comment]
@jimklimov Changelog entry is commonly about several sentences. Regarding this text, maybe it worth putting it in a blogpost or to README.md of the library (the latter thing would be definitely useful). If there is a CHANGELOG.md file there, it would be also great.

I propose the following Changelog entry:

*  [JENKINS-41949](https://issues.jenkins-ci.org/browse/JENKINS-41949), [JENKINS-41932](https://issues.jenkins-ci.org/browse/JENKINS-41932) - Update [LibZFS](https://github.com/kohsuke/libzfs4j/) from 0.5 to 0.8 to fix compatibility issues with [OpenZFS](http://open-zfs.org/wiki/Main_Page) filesystem and [illumos](https://wiki.illumos.org/display/illumos/illumos+Home) distributions.

WDYT?

**Comment by oleg-nenashev** [comment]
Oh, missed the last comment. Will check how to reference/merge these issues

**Comment by jimklimov** [comment]
Well, in particular JENKINS-41949 is NOT covered by this update (bringing ZFS to other platforms - it is even outside the libzfs.jar codebase). Issues 41932 and 42176 are related to this PR (the JAR improvements and making Jenkins use them).

Otherwise, your short entry seems good... as a nit, I think the "filesystem" part is called still ZFS, and *OpenZFS* is rather an umbrella name for the less tangible entities like the multiple-OS collaboration project and planned legal foundation.

**Comment by oleg-nenashev** [comment]
@jimklimov Thanks, updated the changelog accordingly. Merging

**Pull request merged**
