### PR TITLE
Amending #2055

### PR DESCRIPTION
**Pull request by jglick**
#2055

@reviewbybees esp. @stephenc

### CODE REVIEW

**Comment by stephenc** [comment]
:bug: there is already an example of the `H(x-y)/z` syntax, with this change there would be no example of the `(x-y)/z` syntax

**Comment by jglick** [comment]
> there is already an example of the `H(x-y)/z` syntax

There is, but not showing how to use it productively in multiple fields of one entry, which is what this is showing.

> there would be no example of the `(x-y)/z` syntax

So? I am focusing on providing useful examples of things you might actually want to do (in this case time-balancing a 120m-period task during the workday), not on covering every part of the syntax, which is what the reference above it is for.

**Comment by aheritier** [comment]
@jglick @stephenc it's not clear for me

1/ In `H H(0-7) * * *` the first `H` gives a number between `0` and `59` and the second using the syntax `H(0-7)` gives a number between `0` and `7` instead of `0` and `23`. Thus the build will be triggered every day at the same time between midnight and 8AM (excluded). Right ? Thus `H(0-7)` isn't a range but a random value with restricted boundaries. A range is `0-7`not `H(0-7)` ?

ref 

> The `H` symbol can be thought of as a random value over a range, but it actually is a hash of the job name, not a random function, so that the value remains stable for any given project.

What is misleading is the usage of the word **range** in the sentence

> The `H` symbol can be used with a range. For example, `H H(0-7) * * *` means some time between 12:00 AM (midnight) to 7:59 AM.

2/ You are removing the example `H 9-16/2 * * 1-5` which had the comment 

> once every two hours every weekday (perhaps at 9:38 AM, 11:38 AM, 1:38 PM, 3:38 PM)

I find the "once" erroneous ?
`H` is a value between `0` and `59`
`9-16/2` is every 2 hours between `9` and `16` thus `9`, `11`, `13`, `15` ?

Ref
> `M-N/X` or `*/X` steps by intervals of X through the specified range or whole valid range

Thus the comment should have been 

every two hours between 9AM and 5PM (excluded) every weekday (perhaps at 9:38 AM, 11:38 AM, 1:38 PM, 3:38 PM) ??

3/ But now if you replace the sample by

    # once every two hours every weekday (perhaps at 10:38 AM, 12:38 PM, 2:38 PM, 4:38 PM)
    H H(9-16)/2 * * 1-5

`H(9-16)` is a 'random' value between `9` and `16`, it's not a range thus `H H(9-16)/2` should be every 2 hours after a first launch sometime between 9AM (included) and 5PM (excluded)

Can you clarify please ?

**Comment by jtnord** [comment]
:bug: with @stephenc on this.
9-17/2 is very usefull.  You may not want to wait over 1 hour at the start of the day to do this.
Also backups say rin before developers start so 8-20/4 (which is an actual syntax i have used in the past)

**Comment by jglick** [comment]
> Thus the build will be triggered every day at the same time between midnight and 8AM (excluded). Right ?

Right.

> I find the "once" erroneous?

Correct in English.

> `H H(9-16)/2` should be every 2 hours after a first launch sometime between 9AM (included) and 5PM (excluded)

No, every 2 hours after a first launch sometime between 09:00–10:59.

> You may not want to wait over 1 hour at the start of the day to do this.

Or you may not want more than 1 hour to elapse prior to the _end_ of the day. Or you may simply not care, so long as it happens every two hours, and only during the workday, as in this example. You can feel free to add additional examples with more complex explanations. I am simply trying to correct the syntax to match what I was originally intending to demonstrate when I wrote all this text, in #743.

> backups say rin before developers start

Sorry, what?

**Comment by aheritier** [comment]
H(9-16)/2

> No, every 2 hours after a first launch sometime between 09:00–10:59.

This one is really not clear at all for me. Am I the only why ? 
`/2` is every 2 hours, ok
`H(9-16)` isn't clear for me. Is it a range or a value ? 
For me it was a value ? 
It is range but the start isn't 9 but a hash between 9 and 16 ?

* `3` = Only at the 3 value
* `3/2` = Every 2 *something* after a first iteration at 3 *something*
* `*` = All the values inside the boundaries of the item (0-59 for minutes ...).
* `*/2` = Every 2 *something* The first iteration is *As soon as possible*
* `H` = Only at the *random* (but stable) value inside the boundaries of the item
* `H/2` = Every 2 *something* after a launch at H *something*
* `x-y` = All the values inside the boundaries of the x-y range (thus smaller than the boundaries of the item)
* `x-y/2` = Every 2 *something* inside the boundaries of the x-y range (thus smaller than the boundaries of the item). The first iteration will be at x.
* `H(x-y)` = ???
* `H(x-y)/2` = ???

**Comment by stephenc** [comment]
@aheritier so `H(x-y)` is equivalent to `H(x-y)/1`

When Jenkins is parsing `H(x-y)/z` there is a special case for `z==1`

With `z==1` then there will be one and only one match sometime within the range `(x-y)`... depending on the hash

With `z>1` then the range `(x-y)` is divided into segments `z` long and the has is used to decide the offset into the initial segment. after that the segment length is added each time.

So `H(9-16)/2` means that the hash will be modulo 2 (so either 0 or 1) and then `9 + (hash % 2)` will be the first match and then we keep adding `2` to that until we are `> 16`

`H(9-16)/3` means that the hash would be modulo 3, so outcomes of that could be any of:

* 9, 12, 15
* 10, 13, 16
* 11, 14

whereas `(9-16/3)` will always mean 9, 12, 15

**Comment by aheritier** [comment]
@stephenc ok thus now it is clear for me 
`H(x-y)/z` is a range with a modulo and the first value (H) is computed in the first segment
I think we need to explain this in the doc. It isn't obvious in the current one.

**Comment by amuniz** [comment]
OMG `H(9-16)/3` being `11, 14` is kind of crazy.

**Comment by stephenc** [comment]
:bee:

**Comment by stephenc** [comment]
@reviewbybees done

**Comment by stephenc** [comment]
@jenkinsci/code-reviewers

**Comment by aheritier** [comment]
+1

**Comment by jtnord** [comment]
@stephenc my :bug: still stands so still @reviewbybees

**Comment by jtnord** [comment]
>>  there would be no example of the (x-y)/z syntax

> So? I am focusing on providing useful examples of things you might actually want to do (in this case time-balancing a 120m-period task during the workday), not on covering every part of the syntax, which is what the reference above it is for.

The (x-y)/z syntax **is** useful and **is** used in production. and does have very good meaning.

>> backups say rin before developers start

> Sorry, what?

backups *run* before developers start.
Or another example you need to synchronize your Jenkins backup job which puts a zip on some NFS share which is backed up by IT at 9am, 12pm, 3pm and 6pm or need to be synchronized with external backups.  so you need to run it every 3 hours and with enough time such that the job completes.
e.g. `45 8-16/3 * * *`
using `45 H(8-16)/3 * * *` for this scenariou would be bad as your latest backup on tape would be older than it needed to be if the backups starter at 9:45 or 10:45.

If anything then keep both - but removing valid syntax description which has a use is a clear :bug: for me.

**Comment by jtnord** [comment]
the comment is also wrong as it does not run every two hours every weekday. it runs once every two hours between X and Y...

**Comment by stephenc** [comment]
@jtnord the 1-5 means weekdays so it runs every two hours between X and Y only on weekdays

**Comment by jtnord** [comment]
@stephenc 

```
# once every two hours every weekday (perhaps at 10:38 AM, 12:38 PM, 2:38 PM, 4:38 PM)
 +H H(9-16)/2 * * 1-5
```

But it only runs between **9-17** on a weekday - this is not **every 2 hours on a weekday**!

def: weekday
a day of the week other than Sunday or Saturday.

**Comment by jtnord** [comment]
I have tried to clarify this and keep both usages which I believe are both useful and have their place  in #2342

**Comment by stephenc** [comment]
Closing in favour of #2342

**Pull request closed without merging**
