### PR TITLE
[JENKINS-49588] add readResolve method for 'usages' in Fingerprint.java

### PR DESCRIPTION
**Pull request by mikecirioli**
add readResolve method to ensure that <usages ../> is always initialized properly when deserializing a fingerprint

See [JENKINS-49588](https://issues.jenkins-ci.org/browse/JENKINS-49588).

- It is not clear how this situation (a Fingerprint file without any usages being serialized to disk) is occuring, but this fix will prevent it from blowing up in the event that it does happen.  

### Proposed changelog entries

* Entry 1: `Internal:` Added `readResolve` method to Fingerprint.java to ensure the `usages` field is always initialized

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@reviewbybees @batmat @oleg-nenashev

### CODE REVIEW

**Comment by mikecirioli** [comment]
@oleg-nenashev  - i have a couple of questions about this, i will follow up with you via email or chat.

**Comment by oleg-nenashev** [comment]
@reviewbybees it's on your plate

**Comment by batmat** [comment]
@mikecirioli I think a test (probably using `@LocalData`) is required here for completeness.

**Comment by mikecirioli** [comment]
please remove the `work-in-progress` label, this PR is ready for reiew

**Comment by daniel-beck** [comment]
> It is not clear how this situation (a Fingerprint file without any usages being serialized to disk) is occuring

I'd really like to see more investigation related to this. Either we ship 2.107.1 without this fix, or with it, and neither seems particularly appealing.

**Comment by mikecirioli** [comment]
@daniel-beck I agree, although I am not sure how to go about finding a way to reproduce it.   I searched jira for any possibly related issues but found some issues with fingerprints being truncated due to "&" characters in text strings.  If you have ideas for ways to recreate the root cause I am happy to investigate.

**Review by batmat — APPROVED** [review]
LGTM, cannot see how this could hurt, though agreed it would be better to understand where this comes from, *if possible*.

**Comment by oleg-nenashev** [comment]
@batmat @mikecirioli do you plan to merge it?

**Comment by batmat** [comment]
How about we add a WARNING in the `if`?

That could be useful to know if this a common issue, and in the future (if not everybody upgraded to this in the meantime, granted) this would be sent back through telemetry for _Essentials_.

**Comment by batmat** [comment]
I'll merge later today if nobody objects.

**Comment by mikecirioli** [comment]
another person reported seeing this in JENKINS-49588, are we still planning to merge?

**Comment by daniel-beck** [comment]
Based on recent feedback in JENKINS-49588 it looks to me like we're lacking appropriate diagnostics for malformed fingerprints.

**Comment by oleg-nenashev** [comment]
@mikecirioli could you please respond to the question above?

**Comment by mikecirioli** [comment]
@daniel-beck @oleg-nenashev  - this has dropped off my radar as of late.  As far as I am aware we do not have a better understanding of why this is happening.

**Comment by mikecirioli** [comment]
Can we re-consider merging this PR?  Even if we don't understand what is causing this issue, i am still seeing comments from people who are experiencing it.  This PR should at least soothe some of that pain.

**Review by oleg-nenashev — APPROVED** [review]
I consider this pull request a harmless example of the protective code. It is not clear whether it addresses the reported issue, but it is definitely harmless as is. Since there is no movement expected here, I propose to merge it instead of closing

**Comment by batmat** [comment]
Yes, agree. At least it will help us triage the open JIRA: if the issue keeps coming after this merged, then this will already be an additional data point.

**Comment by oleg-nenashev** [comment]
OK. I will merge it into the next weekly if there is no negative feedback

**Pull request merged**
