### PR TITLE
Migrate into localization-zh-cn-plugin

### PR DESCRIPTION
**Pull request by LinuxSuRen**
See https://github.com/jenkinsci/localization-zh-cn-plugin

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Maybe it makes sense to update Contributing.md to reference this case

**Comment by LinuxSuRen** [comment]
You mean Contributing.md of [Jenkins](https://github.com/jenkinsci/jenkins)

**Review by oleg-nenashev — APPROVED** [review]
Yes. The rest LGTM

**Comment by daniel-beck** [comment]
Per #3691, the changelog entry I've improvised for this is in fact wrong. @oleg-nenashev could we please stop merging PRs that don't follow the template?

**Comment by oleg-nenashev** [comment]
@daniel-beck agreed

**Pull request merged**
