### PR TITLE
[JENKINS-33601] - setup wizard: remove 'skip' user creation, include security config

### PR DESCRIPTION
**Pull request by kzantow**
Removes the 'skip' option when using HudsonPrivateSecurityRealm, adds security config as step in the setup wizard.

Even if it's decided not to include the security config in setup wizard at this point, this PR is probably still beneficial to include, as it has some changes that make it easier to rearrange or add steps to the setup wizard, which will be useful for using it as an upgrade wizard.

Addresses: https://issues.jenkins-ci.org/browse/JENKINS-33601

### CODE REVIEW

**Comment by kzantow** [comment]
@jenkinsci/code-reviewers esp. @daniel-beck

**Comment by daniel-beck** [comment]
@uhafner  Do you like this approach better?

**Comment by daniel-beck** [comment]
FWIW I don't think moving all users through the full security config is a great approach. A selection similar to the initial plugin configuration with "Set up default security config we think is good for you" and "Customize security options to fit your environment" or something like that would be better than this.

That said, I'm not sure how I feel about any of this going into 2.0 (rather than, say, 2.1). It's already a pretty extensive change.

**Comment by daniel-beck** [comment]
Needs 2.0 merge.

**Pull request closed without merging**
