### PR TITLE
Groovy code cleanup

### PR DESCRIPTION
**Pull request by darxriggs**
This is about code formatting to make the Groovy code consistent - mainly:
- no semicolon at EOL
- no trailing whitespaces
- no unrequired access modifiers
- proper spaces around operators, commas and brackets
- proper indentation

Some changes include problems detected by CodeNarc.
Maybe CodeNarc can be included in the future (I have seen FindBugs is already included via the _metrics_ profile).

### CODE REVIEW

**Comment by daniel-beck** [comment]
@olivergondza How will this affect backporting of changes from after this is applied to a release from before this is applied?

**Comment by olivergondza** [comment]
It will be a burden but there is not much to screw up as the whitespace/semicolons have no semantic meaning here.

I do not see much value in such a change in the first place. I am pretty confident such rules, however reasonable they are, will be violated again with next patch unless we start to enforce code style in regular build process. And we do not do this for Java/xml either, btw.

**Comment by daniel-beck** [comment]
I like consistency and agree that the current inconsistencies aren't that nice. However, due to

> It will be a burden

and

> will be violated again with next patch

and the fact that we don't even have a style guide, which this presupposes, I recommend this should be closed.

---

@olivergondza 

> And we do not do this for Java/[…] either

According to [the wiki](https://wiki.jenkins-ci.org/display/JENKINS/contributing) we follow [Oracle Java Code Conventions](http://www.oracle.com/technetwork/java/codeconvtoc-136057.html).

**Comment by olivergondza** [comment]
@daniel-beck, I meant we do not enforce code style automatically.

@darxriggs, if there are other than style related fixes/improvements, please propose them separately.

**Pull request closed without merging**
