### PR TITLE
Remove jQuery from `page-init.js`

### PR DESCRIPTION
**Pull request by janfaracik**
Inspired by the great works by @basil and @timja, this PR removes `page-init.js`' reliance on jQuery.

### Testing done

* Went to a page that uses `<l:js />` (New job), page works as expected and JS loads in 
* Went to a page that uses `<l:css />` (New job), page works as expected and CSS loads in 

### Proposed changelog entries

- N/A

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.

### Desired reviewers

@jenkinsci/sig-ux 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7815"></a>

### CODE REVIEW

**Review by basil — COMMENTED** [review]
[JENKINS-70906](https://issues.jenkins.io/browse/JENKINS-70906) contains a justification for the removal of Prototype. This PR does not contain a justification for the removal of jQuery.

**Comment by janfaracik** [comment]
> [JENKINS-70906](https://issues.jenkins.io/browse/JENKINS-70906) contains a justification for the removal of Prototype. This PR does not contain a justification for the removal of jQuery.

JS is at a place where libraries such as jQuery aren't (as) helpful/necessary anymore and as such should be removed where possible. This would provide a lighter weight + more performant experience and would reduce the amount of libraries Jenkins is dependant on. The GOV.UK blog offers a good insight into how and why they made the change - 

https://insidegovuk.blog.gov.uk/2022/08/11/how-and-why-we-removed-jquery-from-gov-uk/

Obviously not as important as removing the likes of Prototype/YUI/etc but there is still a benefit in doing so.

**Comment by basil** [comment]
`mvn clean verify -Dtest=hudson.model.ManagementLinkTest#links,hudson.PluginManagerCheckUpdateCenterTest,hudson.PluginManagerTest#noInjectionOnAvailablePluginsPage` is failing.

**Comment by basil** [comment]
Note that #7827 obviates the need for this PR by deleting this entire subsystem.

**Comment by janfaracik** [comment]
> Note that #7827 obviates the need for this PR by deleting this entire subsystem.

Wonderful, great job :) I'll close this, thanks for the heads up.

**Comment by basil** [comment]
> Wonderful, great job :) I'll close this, thanks for the heads up.

You are welcome, Jan. Your review of #7827 would be appreciated. In this way, you would not be leaving me holding the bag by myself but rather actively helping to bring a joint effort to closure.

**Pull request closed without merging**
