### PR TITLE
[FIXED JENKINS-28112] JNLP file requests Java 1.5+ despite minimum versi...

### PR DESCRIPTION
**Pull request by stephenc**
@reviewbybees

### CODE REVIEW

**Comment by jtnord** [comment]
We have moved to 1.7+ now.

**Comment by stephenc** [comment]
[have we](https://github.com/jenkinsci/jenkins/blob/master/pom.xml#L104)?

**Comment by jtnord** [comment]
Well I was suprised (didn't see this on the ML).  but [apparently yes](http://jenkins-ci.org/content/good-bye-java6).

**Comment by jtnord** [comment]
Looks like someone forgot to follow through on their promises!

**Comment by stephenc** [comment]
@jtnord yep... @kohsuke FYI you forgot 1.610 is supposed to be java 1.7

**Comment by daniel-beck** [comment]
Please self-assign issues you plan to work on.

**Comment by stephenc** [comment]
Closing in favour of #1679

**Pull request closed without merging**
