### PR TITLE
[JENKINS-68427] When using the groovy code manager.addShortText() in firefox, it will cause page misalignment in the build history list.

### PR DESCRIPTION
**Pull request by frankie139506**
See [JENKINS-68427](https://issues.jenkins.io/browse/JENKINS-68427).

Before
image
After
image

### Proposed changelog entries

* Fix the misalignment in the build history list.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] (If applicable) Jira issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [X] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/6562"></a>

### CODE REVIEW

**Comment by daniel-beck** [comment]
The 'before' screenshot behavior part of deliberate behavior. Given the report is specifically about Groovy Postbuild's badges and empty vertical space, something not demonstrated here, I recommend extensive testing. We've been here before, this widget is a regression magnet.

The build history displays:

* Date and time of the build.
* Optionally, build _names_ can be defined, replacing the build number in the history.
* Build badges like "keep forever", badges from `buildtriggerbadge` plugin, or the referenced Groovy Postbuild custom build badges
* The description of builds

The first three would be shown on one line if they fit, and multiple if not. While it's odd that it breaks despite there being enough space, care needs to be taken to ensure it still breaks when needed in a variety of combinations of content.

**Comment by basil** [comment]
The above review expresses a generally positive assessment of this change, tempered by the cautionary concern that this area has been the source of number of regressions in the past and therefore changes in this area carry a high risk of regression.

This is, of course, a valid concern:

> Have you reviewed and tested your change every way that you know how? **You should not even _contemplate_ pushing until your answer to this is an unequivocal YES.**

– Bryan Cantrill, "[Software: Immaculate, fetid and grimy](http://dtrace.org/blogs/bmc/2015/09/03/software-immaculate-fetid-and-grimy/)", emphasis _not_ mine

However, it is not clear to me from the above review what those past regressions were or what tests are specifically needed to give us confidence in this change.

@frankie139506 It would be helpful if you could do some initial research and propose a set of test scenarios that would give us confidence in this change. Once these test scenarios are proposed and confirmed, the testing could be carried out by you, other volunteers, or a combination of both.

@daniel-beck It would be helpful if you could review such a test plan after it is proposed, or propose your own. If you have some specific test scenarios in mind, it might save everyone time if you could tell us what they are. If you have a specific set of past regressions in mind that demonstrate a general pattern and could help inform a test plan, it would be helpful if you could tell us what they are.

The basic point is that I think we can work together to identify a test plan and execute on it. Let us please do so rather than letting this change stall.

**Comment by daniel-beck** [comment]
> If you have a specific set of past regressions in mind that demonstrate a general pattern and could help inform a test plan, it would be helpful if you could tell us what they are.

Quick search vaguely remembering the folks dealing with it I find:

* https://issues.jenkins.io/browse/JENKINS-33826 / https://github.com/jenkinsci/jenkins/pull/2180
* https://issues.jenkins.io/browse/JENKINS-28455 / https://github.com/jenkinsci/jenkins/pull/1710
* https://github.com/jenkinsci/jenkins/pull/1542
* https://github.com/jenkinsci/jenkins/pull/1872

The screenshots also demonstrate the kind of madness some folks put into their widgets.

There's 4 related values/axes involved, with varying values possible:

* Description: None, Short, medium, ridiculously long (with HTML tables etc., see https://github.com/jenkinsci/jenkins/pull/4209#issuecomment-559002070 and following comments) – I would consider it fairly unlikely that this specifically causes problems since it's never on the same line as the other values.
* Badges: None, 1 symbol, 2 symbols, 1 small text, multiple, ridiculously long
* Dates: These are probably annoying to test unless familiar with date formats, but non-monospaces fonts alone may make it annoying. AFAIUI right now we already have the problem than "wide digits" cause wrap of some but not all history entries.
* Build number/name: Number (no name), short name, medium name, long name

Combinations of these should be checked for reasonable behavior, especially around the various thresholds (e.g. if a wrap at a certain length is implemented, how does it look just below and just above the threshold?).

> generally positive assessment of this change

This PR looks useful, but AFAIUI it does not currently claim to address the Jira issue as I understand it. The wrapping prevented here seems different than the empty vertical space in Jira screenshots.

**Comment by basil** [comment]
> Combinations of these should be checked

Quite a vague statement Daniel. But this is better than nothing I suppose. @frankie139506 Could you select a reasonable subset of the power set of combinations that you think would be appropriate for testing? Once Daniel approves, we can then proceed with finding people to do the testing.

**Comment by frankie139506** [comment]
> > Combinations of these should be checked
> 
> Quite a vague statement Daniel. But this is better than nothing I suppose. @frankie139506 Could you select a reasonable subset of the power set of combinations that you think would be appropriate for testing? Once Daniel approves, we can then proceed with finding people to do the testing.

image
image

 @basil This is my testing.

**Comment by frankie139506** [comment]
> > > Combinations of these should be checked
> > 
> > 
> > Quite a vague statement Daniel. But this is better than nothing I suppose. @frankie139506 Could you select a reasonable subset of the power set of combinations that you think would be appropriate for testing? Once Daniel approves, we can then proceed with finding people to do the testing.
> 
> image image
> 
> @basil  @daniel-beck This is my testing.

**Comment by basil** [comment]
@frankie139506 That isn't a sufficient set of test scenarios to mitigate our concern about possible regressions here.

Daniel listed 4 axes of possible inputs to this code. To fully test this PR and convince ourselves to the highest degree possible that there are no regressions, we would test each value in each axis with each other value in each other axis, both before and after this PR, and make sure there are no regressions. Since the combinatorics of this exercise would take hours or days, and since the Jenkins maintainers are not interested in overly burdening contributors, some combinations can be trimmed from this test matrix. But overall, most of the matrix needs to be tested. That is why I asked you to define a subset of combinations that you feel would be sufficient for testing.

Two screenshots, neither of which contain many of the important test scenarios from Daniel's post (e.g., badges, long descriptions, etc) is clearly insufficient. So I am asking again that we first define the set of test scenarios. You need not test all of them yourself (a community helps each other), but we need to first define what tests we think are important before we can distribute the work. Here is an example:

- Scenario 1: Long description, 2 symbol badge, standard date format, medium length build name
- Scenario 2: Short description, 1 symbol badge, custom date format, no custom build name
- Scenario 3: […]

Let's get consensus on the set of scenarios we feel is important (and sufficient) before we run through each scenario and confirm that the behavior is the same before and after this PR.

**Comment by basil** [comment]
This pull request is off to a promising start but requires additional effort to reach completion: effort that appears to have been abandoned. Since this pull request has remained incomplete with no activity for over a week, I am marking it as `stalled`. If it remains inactive for several weeks, I will label it as `proposed-for-close` in order to maintain an orderly PR queue and close the PR approximately one week after that.

**Comment by daniel-beck** [comment]
> I recommend extensive testing. We've been here before, this widget is a regression magnet.

> Combinations of these should be checked for reasonable behavior

To illustrate, [JENKINS-68390](https://issues.jenkins.io/browse/JENKINS-68390) is a problem that seems to only occur when you have a badge icon, a 2(+?) digit build number, and use Safari.

**Comment by basil** [comment]
> If it remains inactive for several weeks, I will label it as `proposed-for-close` in order to maintain an orderly PR queue and close the PR approximately one week after that.

Closing as promised. On behalf of the core team, I would like to thank you for your contribution. Even though this PR did not make it across the finish line, it was a promising start! I continue to encourage you (or anyone else who is interested!) to pick up this effort and drive it to completion.

**Pull request closed without merging**
