### PR TITLE
[JENKINS-10547, JENKINS-22685] Update windows-slave-installer dependency to 1.5

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Jenkins issues: [JENKINS-10547](https://issues.jenkins-ci.org/browse/JENKINS-10547), [JENKINS-22685](https://issues.jenkins-ci.org/browse/JENKINS-22685)

Changes in winsw:
- https://github.com/kohsuke/winsw/issues?q=milestone%3Awinsw-1.17
- kohsuke/winsw@2bf9e85

Changes in the module:
- https://github.com/jenkinsci/windows-slave-installer-module/commit/a4d2121812fe9fe1b38bbe9d2cb57b9cd5435a0d
- https://github.com/jenkinsci/windows-slave-installer-module/commit/3fbc8434aba05d5d36f52f345d9d0176e98459be

### CODE REVIEW

**Comment by KostyaSha** [comment]
:+1:

**Comment by oleg-nenashev** [comment]
"Could not find artifact org.jenkins-ci.modules:windows-slave-installer:jar:1.5 in central", wow
maven-release-plugin:2.5 also uploaded a snapshot. I'll dig into it later today

**Comment by jtnord** [comment]
@oleg-nenashev make sure you have a recent (1.8+) git client installed and that the maven-scm* is > 1.8

also best to use m-r-p 2.5.2

**Comment by daniel-beck** [comment]
@oleg-nenashev FYI d86a88ab042cc55530d91e745af9e0886e8eeb79 so it would be good if you could do this today.

**Comment by KostyaSha** [comment]
:+1:

**Comment by daniel-beck** [comment]
:+1:

**Comment by jglick** [comment]
:+1:

**Pull request merged**
