### PR TITLE
Bump slf4j from 1.7.25 to 1.7.26

### PR DESCRIPTION
**Pull request by longngn**
GitHub release (commits and diff): https://github.com/qos-ch/slf4j/releases/tag/v_1.7.26
Changelog: https://www.slf4j.org/news.html

### Proposed changelog entries

* Internal: Update slf4j version from 1.7.25 to 1.7.26

### Submitter checklist

- [ ] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Diff: https://github.com/qos-ch/slf4j/compare/v_1.7.25...v_1.7.26

**Review by oleg-nenashev — APPROVED** [review]
LGTM

**Comment by varyvol** [comment]
There are removed classes in the changes...would they affect?

**Review by fcojfernandez — APPROVED** [review]
Reviewing the diff, LGTM

**Comment by longngn** [comment]
Changelog updated

**Comment by oleg-nenashev** [comment]
Will merge tomorrow if no negative feedback

**Pull request merged**
