### PR TITLE
[FIXED JENKINS-34882] Honor non-default update sites in setup wizard

### PR DESCRIPTION
**Pull request by kzantow**
Setup wizard connectivity check would fail and prevent installation when using non-default update sites.

@reviewbybees esp. @andresrc

### CODE REVIEW

**Comment by andresrc** [comment]
:bee:

**Comment by daniel-beck** [comment]
Makes sense :+1:

**Comment by amuniz** [comment]
The build is failing with a related message, :bug: I guess?

**Comment by kzantow** [comment]
@amuniz all fixed up now

**Pull request merged**
