### PR TITLE
[JENKINS-67734] Restore ability to sort plugins by their status

### PR DESCRIPTION
**Pull request by NotMyFault**
Fixes [JENKINS-67734](https://issues.jenkins.io/browse/JENKINS-67734)

The overhaul of the plugin manager (https://github.com/jenkinsci/jenkins/pull/5916) removed the ability to sort plugins by their status, if they are enabled or disabled.
Unless I missed something, I can't think of a reason why this ability has been removed, especially for admins, because you can't view the plugin manager without overall/administer anyway 🤔 

cc @janfaracik mind taking a look?

### Proposed changelog entries

* Restore ability to sort plugins by their status.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by janfaracik** [comment]
Not sure if I'm doing something wrong but this doesn't seem to work for me? Clicking the 'Enabled' cell but it isn't changing the sorting.

**Comment by daniel-beck** [comment]
This is `false` for SystemRead permission (https://github.com/jenkinsci/jep/blob/master/jep/224/README.adoc). The idea is to only have the enable/disable buttons for admins.

**Comment by NotMyFault** [comment]
> This is `false` for SystemRead permission (https://github.com/jenkinsci/jep/blob/master/jep/224/README.adoc). The idea is to only show the enable/disable buttons for people who can use them.

Thanks for the clarification! Though it looks like I had a bad testing day today, because what I called a regression above works as intended on my other instances 🥴

**Comment by daniel-beck** [comment]
Seems like the TH should remain but just not flagged as unsortable?

**Review by janfaracik — APPROVED** [review]

**Review by timja — CHANGES_REQUESTED** [review]
From my testing this column isn't the enable / disable it's the downgrade a plugin column which I'm not sure if  it needs sorting, and it needs a label on the column if so.

It's just a random arrow that only appears when you click currently
image


I can sort enabled/ disabled just fine on released versions

**Comment by NotMyFault** [comment]
> I can sort enabled/ disabled just fine on released versions

Yeah, works flawless on 2.336 for me. Maybe some weird hiccup I experienced while doing something, but I'd be in favor of closing this PR, considering it works well out of the box without my change.

**Pull request closed without merging**
