### PR TITLE
Restore mis-remove localization files

### PR DESCRIPTION
**Pull request by LinuxSuRen**
* Localization for install wizard should be kept

 See also #3667

* BUG, Restore Chinese localization for the Installation Wizard
* ...

- [ ] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

@mention

### CODE REVIEW

**Comment by batmat** [comment]
Retriggering now #3818 got merged, this should remove ATH failures and get a green build here.

**Comment by LinuxSuRen** [comment]
The build error should be unrelated to this pr.

**Review by oleg-nenashev — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
PR builder is sick, but this PR does not make it worse

**Comment by oleg-nenashev** [comment]
@LinuxSuRen if you want it to be backported to the previous LTS baseline, please create a JIRA ticket and reference it here

**Comment by LinuxSuRen** [comment]
@oleg-nenashev Yes

**Comment by LinuxSuRen** [comment]
Here is the JIRA ticket https://issues.jenkins-ci.org/browse/JENKINS-55791

**Pull request merged**
