### PR TITLE
[FIXED JENKINS-30721] Use case insensitive FileSets on Windows

### PR DESCRIPTION
**Pull request by vvv444**
[FIXED JENKINS-30721]

### CODE REVIEW

**Comment by jtnord** [comment]
:-1: - case sensitivity depends on the FileSystem.  Windows can have case sensitive file systems (and not just case preserving file systems)

**Comment by vvv444** [comment]
Well, maybe theoretically it can... But practically, as far as I know, most of the tools on Windows do not support it and that's definitely not what Windows user expects.

**Comment by jtnord** [comment]
most tools do support it actually - as they will use what is provided and returned and don't upper/lowercase (by virtue of the default file system being case preserving).

**Comment by vvv444** [comment]
Examples:
1. Command line command "copy Foo Bar" will work in any case, no matter if the file on the file-system is called "Foo", "foo" or "FoO".
2. Same for "mspaint foo.bmp", no matter what is the actual case of file name on disk.

This is the consistent behaviour for all tools on Windows. I don't remember any tool that would not work this way. Jenkins is the only exception I ever seen.

**Comment by oleg-nenashev** [comment]
I agree with @jtnord . At one of my previous companies we used the case-sensitive NFS mapping on Windows in production. This approach may break such installations.

@vvv444 
If you want to introduce this feature, make it configurable && disabled by default. E.g. you could use System properties. https://wiki.jenkins-ci.org/display/JENKINS/Features+controlled+by+system+properties

**Comment by Vlatombe** [comment]
#1429 provides a better solution I believe.

**Comment by oleg-nenashev** [comment]
@Vlatombe 
They are ortogonal a bit, but may address the same case

**Comment by vvv444** [comment]
Ok, I agree with @Vlatombe. The other is a better solution.

**Pull request closed without merging**
