### PR TITLE
Fix missing space in log message

### PR DESCRIPTION
**Pull request by aheritier**

### CODE REVIEW

**Comment by aheritier** [comment]
@reviewbybees please. It is a so big fix :-)

**Comment by aheritier** [comment]
For reference it gives this without the fix : https://speakerdeck.com/aheritier/jenkins-2-dot-0-at-breizhcamp

**Comment by christ66** [comment]
:bee:

**Comment by batmat** [comment]
+0.5 :smirk:

**Comment by batmat** [comment]
Naaah, kidding. :+1:

**Pull request merged**
