### PR TITLE
Set ATH mvn run: set batch mode, and show versions

### PR DESCRIPTION
**Pull request by batmat**
No JIRA, small and internal change.

### Proposed changelog entries

* `Internal:` nothing visible to end users

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@reviewbybees esp. @raul-arabaolaza

### CODE REVIEW

**Review by raul-arabaolaza — APPROVED** [review]
LGTM

**Comment by batmat** [comment]
Will wait at least for a successful PR build before merging.

**Review by daniel-beck — APPROVED** [review]

**Comment by batmat** [comment]
One test failure. I cannot see how this could be related
image

**Comment by daniel-beck** [comment]
FYI @oleg-nenashev seems we have a flaky test from #3357.

**Pull request merged**
