### PR TITLE
Typo in Polish translation

### PR DESCRIPTION
**Pull request by wojciechk**

### CODE REVIEW

**Comment by daniel-beck** [comment]
Are you sure this shouldn't be `Zachowaj`? I mean I'm only going by Google Translate here, but *hide* seems wrong, while *keep* would be the original meaning.

**Comment by daniel-beck** [comment]
@damianszczepanik PTAL

**Comment by wojciechk** [comment]
OK, you're right, that should be _Zachowaj_ if the meaning is _keep_.

**Comment by damianszczepanik** [comment]
+1

**Comment by daniel-beck** [comment]
@damianszczepanik This is about a build, not a job.

**Comment by damianszczepanik** [comment]
Zachowaj to budowanie

**Comment by wojciechk** [comment]
I see that both _Budowanie_ and _Wykonanie_ are used in Polish translations.
It would be better to be consistent and decide which one to use in the first place.  My original commit concerned obvious spelling error.

**Comment by daniel-beck** [comment]
@wojciechk @damianszczepanik https://wiki.jenkins-ci.org/display/JENKINS/Internationalization has child pages for specific translations -- maybe you two could collaborate on a Polish version that prescribes the canonical translations for specific terms in Jenkins, then change the resources accordingly?

**Comment by damianszczepanik** [comment]
I see that each child has specified content, hierarchy etc so what is the goal of this page? Also I believe there are many files which may not be updated according to the terms/translations we use for Polish language. I'm doing my best with each commit but I don't want to translate the label which I cannot see so the context is not clear to me...

**Comment by daniel-beck** [comment]
@damianszczepanik I'm only suggesting you create a wiki page with agreed upon standard translations of terms into Polish, or whatever else may be needed, like the table on https://wiki.jenkins-ci.org/display/JENKINS/Spanish+Translation

It's also possible I don't understand the problem in this case, neither word means anything to me :-)

**Comment by damianszczepanik** [comment]
There is no problem, rather question :)

Will take a look at this.

**Pull request closed without merging**
