### PR TITLE
Bump ATH revision once more

### PR DESCRIPTION
**Pull request by olivergondza**
Integrating https://github.com/jenkinsci/acceptance-test-harness/pull/469 to get a clean build.

### Proposed changelog entries

None

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@MRamonLeon @batmat

### CODE REVIEW

**Comment by batmat** [comment]
BTW, FTR the random failures we were seeing in https://github.com/jenkinsci/jenkins/pull/3816 didn't happen on the build of the merge on the `master` branch. 

So, adding this PR, we should hopefully get back to a stabler green build on the `master` branch :fireworks: 

image

**Review by batmat — APPROVED** [review]

**Review by MRamonLeon — APPROVED** [review]
go ahead

**Comment by MRamonLeon** [comment]
:crossed_fingers:

**Review by oleg-nenashev — APPROVED** [review]

**Comment by batmat** [comment]
New failures with different cause:

image

All tests are failing again for apparently a same underlying cause:

```
Error
Failed to decode response from marionette
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'a86c9162562e', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1035-azure', java.version: '1.8.0_171'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 60.4.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:geckodriverVersion: 0.22.0, moz:headless: false, moz:processID: 1734, moz:profile: /tmp/rust_mozprofile.Bm1LyU..., moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 4.15.0-1035-azure, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: 15737e87-da5c-4686-b23b-5288dec318ce
Stacktrace
org.openqa.selenium.WebDriverException:
Failed to decode response from marionette
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'a86c9162562e', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1035-azure', java.version: '1.8.0_171'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 60.4.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:geckodriverVersion: 0.22.0, moz:headless: false, moz:processID: 1734, moz:profile: /tmp/rust_mozprofile.Bm1LyU..., moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 4.15.0-1035-azure, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: 15737e87-da5c-4686-b23b-5288dec318ce
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:605)
at org.openqa.selenium.remote.RemoteWebDriver.getPageSource(RemoteWebDriver.java:434)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.openqa.selenium.support.events.EventFiringWebDriver.lambda$new$1(EventFiringWebDriver.java:105)
at com.sun.proxy.$Proxy43.getPageSource(Unknown Source)
at org.jenkinsci.test.acceptance.selenium.SanityChecker.isFastPath(SanityChecker.java:83)
at org.jenkinsci.test.acceptance.selenium.SanityChecker.checkSanity(SanityChecker.java:60)
at org.jenkinsci.test.acceptance.selenium.SanityChecker.afterNavigateTo(SanityChecker.java:46)
at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.openqa.selenium.support.events.EventFiringWebDriver.lambda$new$0(EventFiringWebDriver.java:84)
at com.sun.proxy.$Proxy42.afterNavigateTo(Unknown Source)
at org.openqa.selenium.support.events.EventFiringWebDriver.get(EventFiringWebDriver.java:166)
at org.jenkinsci.test.acceptance.po.CapybaraPortingLayerImpl.visit(CapybaraPortingLayerImpl.java:89)
at org.jenkinsci.test.acceptance.po.ConfigurablePageObject.configure(ConfigurablePageObject.java:106)
at core.FreestyleJobTest.doNotDiscardSuccessfulBuilds(FreestyleJobTest.java:215)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
at org.jenkinsci.test.acceptance.junit.JenkinsAcceptanceTestRule$1$2$1.evaluate(JenkinsAcceptanceTestRule.java:168)
at org.jenkinsci.test.acceptance.junit.FilterRule$1.evaluate(FilterRule.java:63)
at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
at org.jenkinsci.test.acceptance.junit.JenkinsAcceptanceTestRule$1.evaluate(JenkinsAcceptanceTestRule.java:58)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
at org.junit.runners.Suite.runChild(Suite.java:127)
at org.junit.runners.Suite.runChild(Suite.java:26)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Standard Output
=== Starting test doNotDiscardSuccessfulBuilds(core.FreestyleJobTest): 11:10:52
No pooled jenkins controller listening on socket /home/ath-user/jenkins.sock
master56186|Running from: /mnt/agent-workspace/workspace/Core_jenkins_PR-3818-4HVOVA52SFMYKUXIYFGIEYJ43AP6UJGPYYJER3IQ3ANJHD4MNTNQ/ath/categoriesfirefoxjdk8/jenkins.war
master56186|webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
master56186|Dec 20, 2018 11:10:55 AM org.eclipse.jetty.util.log.Log initialized
master56186|INFO: Logging initialized @171ms to org.eclipse.jetty.util.log.JavaUtilLog
master56186|Dec 20, 2018 11:10:56 AM winstone.Logger logInternal
master56186|INFO: Beginning extraction from war file
master56186|Dec 20, 2018 11:10:56 AM org.eclipse.jetty.server.handler.ContextHandler setContextPath
master56186|WARNING: Empty contextPath
master56186|Dec 20, 2018 11:10:56 AM org.eclipse.jetty.server.Server doStart
master56186|INFO: jetty-9.4.z-SNAPSHOT; built: 2018-08-30T13:59:14.071Z; git: 27208684755d94a92186989f695db2d7b21ebc51; jvm 1.8.0_171-8u171-b11-2-b11
master56186|Dec 20, 2018 11:10:56 AM org.eclipse.jetty.webapp.StandardDescriptorProcessor visitServlet
master56186|INFO: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
master56186|Dec 20, 2018 11:10:57 AM org.eclipse.jetty.server.session.DefaultSessionIdManager doStart
master56186|INFO: DefaultSessionIdManager workerName=node0
master56186|Dec 20, 2018 11:10:57 AM org.eclipse.jetty.server.session.DefaultSessionIdManager doStart
master56186|INFO: No SessionScavenger set, using defaults
master56186|Dec 20, 2018 11:10:57 AM org.eclipse.jetty.server.session.HouseKeeper startScavenging
master56186|INFO: node0 Scavenging every 660000ms
master56186|Jenkins home directory: /mnt/agent-workspace/workspace/Core_jenkins_PR-3818-4HVOVA52SFMYKUXIYFGIEYJ43AP6UJGPYYJER3IQ3ANJHD4MNTNQ/ath/categoriesfirefoxjdk8/target/jenkins7899022467093773892home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
master56186|Dec 20, 2018 11:10:57 AM org.eclipse.jetty.server.handler.ContextHandler doStart
master56186|INFO: Started w.@4da855dd{Jenkins v2.157-SNAPSHOT,/,file:///mnt/agent-workspace/workspace/Core_jenkins_PR-3818-4HVOVA52SFMYKUXIYFGIEYJ43AP6UJGPYYJER3IQ3ANJHD4MNTNQ/ath/categoriesfirefoxjdk8/target/jenkins7899022467093773892home/war/,AVAILABLE}{/mnt/agent-workspace/workspace/Core_jenkins_PR-3818-4HVOVA52SFMYKUXIYFGIEYJ43AP6UJGPYYJER3IQ3ANJHD4MNTNQ/ath/categoriesfirefoxjdk8/target/jenkins7899022467093773892home/war}
master56186|Dec 20, 2018 11:10:57 AM org.eclipse.jetty.server.AbstractConnector doStart
master56186|INFO: Started ServerConnector@61edc883{HTTP/1.1,[http/1.1]}{0.0.0.0:56186}
master56186|Dec 20, 2018 11:10:57 AM org.eclipse.jetty.server.Server doStart
master56186|INFO: Started @1696ms
master56186|Dec 20, 2018 11:10:57 AM winstone.Logger logInternal
master56186|INFO: Winstone Servlet Engine v4.0 running: controlPort=disabled
master56186|Dec 20, 2018 11:10:58 AM jenkins.InitReactorRunner$1 onAttained
master56186|INFO: Started initialization
master56186|Dec 20, 2018 11:10:58 AM jenkins.InitReactorRunner$1 onAttained
master56186|INFO: Listed all plugins
master56186|Dec 20, 2018 11:10:59 AM jenkins.InitReactorRunner$1 onAttained
master56186|INFO: Prepared all plugins
master56186|Dec 20, 2018 11:10:59 AM jenkins.InitReactorRunner$1 onAttained
master56186|INFO: Started all plugins
master56186|Dec 20, 2018 11:10:59 AM jenkins.InitReactorRunner$1 onAttained
master56186|INFO: Augmented all extensions
master56186|Dec 20, 2018 11:11:00 AM jenkins.InitReactorRunner$1 onAttained
master56186|INFO: Loaded all jobs
master56186|Dec 20, 2018 11:11:00 AM hudson.model.AsyncPeriodicWork$1 run
master56186|INFO: Started Download metadata
master56186|Dec 20, 2018 11:11:00 AM hudson.util.Retrier start
master56186|INFO: Attempt #1 to do the action check updates server
master56186|Dec 20, 2018 11:11:00 AM jenkins.InitReactorRunner$1 onAttained
master56186|INFO: Completed initialization
master56186|Dec 20, 2018 11:11:00 AM hudson.WebAppMain$3 run
master56186|INFO: Jenkins is fully up and running
master56186|Dec 20, 2018 11:11:04 AM hudson.model.UpdateSite updateData
master56186|INFO: Obtained the latest update center data file for UpdateSource default
master56186|Dec 20, 2018 11:11:04 AM hudson.model.DownloadService$Downloadable load
master56186|INFO: Obtained the updated data file for hudson.tasks.Maven.MavenInstaller
master56186|Dec 20, 2018 11:11:04 AM hudson.util.Retrier start
master56186|INFO: Performed the action check updates server successfully at the attempt #1
master56186|Dec 20, 2018 11:11:04 AM hudson.model.AsyncPeriodicWork$1 run
master56186|INFO: Finished Download metadata. 3,655 ms
master56186|Dec 20, 2018 11:11:12 AM hudson.model.Run execute
master56186|INFO: clear_profession #1 main build action completed: SUCCESS
[[ATTACHMENT|/mnt/agent-workspace/workspace/Core_jenkins_PR-3818-4HVOVA52SFMYKUXIYFGIEYJ43AP6UJGPYYJER3IQ3ANJHD4MNTNQ/ath/categoriesfirefoxjdk8/target/diagnostics/doNotDiscardSuccessfulBuilds(core.FreestyleJobTest)/ui-recording.mov]]
Standard Error
Dec 20, 2018 11:10:52 AM org.jenkinsci.test.acceptance.controller.LocalController postConstruct
INFO: Running with given plugins: []
1545304252707	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.Bm1LyUsahXYo"
Dec 20, 2018 11:10:53 AM org.jenkinsci.test.acceptance.log.LogReader run
INFO: Jenkins is stopped
1545304255522	Marionette	INFO	Listening on port 41027
1545304255618	Marionette	WARN	TLS certificate errors will be ignored for this session
Dec 20, 2018 11:10:55 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Dec 20, 2018 11:10:55 AM org.jenkinsci.test.acceptance.controller.WinstoneController startProcess
INFO: Starting Jenkins: JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre JENKINS_HOME=/mnt/agent-workspace/workspace/Core_jenkins_PR-3818-4HVOVA52SFMYKUXIYFGIEYJ43AP6UJGPYYJER3IQ3ANJHD4MNTNQ/ath/categoriesfirefoxjdk8/target/jenkins7899022467093773892home jenkins.install.state=TEST /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Duser.language=en -jar ./jenkins.war --ajp13Port=-1 --httpPort=56186
Dec 20, 2018 11:10:55 AM org.jenkinsci.test.acceptance.controller.LocalController startNow
INFO: Waiting for Jenkins to become running in http://127.0.0.1:56186/
Dec 20, 2018 11:11:00 AM org.jenkinsci.test.acceptance.controller.LocalController startNow
INFO: Jenkins is running in http://127.0.0.1:56186/
[Parent 1734, Gecko_IOThread] WARNING: pipe error (65): Connection reset by peer: file /build/firefox-esr-4oYyar/firefox-esr-60.4.0esr/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
###!!! [Parent][MessageChannel] Error: (msgtype=0x160080,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv
A content process crashed and MOZ_CRASHREPORTER_SHUTDOWN is set, shutting down
console.log: Accessibility service init or shutdown observer does not exist.
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
Browser died already
org.openqa.selenium.NoSuchSessionException: Tried to run command without establishing a connection
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'a86c9162562e', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1035-azure', java.version: '1.8.0_171'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 60.4.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:geckodriverVersion: 0.22.0, moz:headless: false, moz:processID: 1734, moz:profile: /tmp/rust_mozprofile.Bm1LyU..., moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 4.15.0-1035-azure, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: 15737e87-da5c-4686-b23b-5288dec318ce
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:605)
at org.openqa.selenium.remote.RemoteWebDriver.getPageSource(RemoteWebDriver.java:434)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.openqa.selenium.support.events.EventFiringWebDriver.lambda$new$1(EventFiringWebDriver.java:105)
at com.sun.proxy.$Proxy43.getPageSource(Unknown Source)
at org.jenkinsci.test.acceptance.selenium.SanityChecker.isFastPath(SanityChecker.java:83)
at org.jenkinsci.test.acceptance.selenium.SanityChecker.checkSanity(SanityChecker.java:60)
at org.jenkinsci.test.acceptance.selenium.SanityChecker.beforeNavigateTo(SanityChecker.java:51)
at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.openqa.selenium.support.events.EventFiringWebDriver.lambda$new$0(EventFiringWebDriver.java:84)
at com.sun.proxy.$Proxy42.beforeNavigateTo(Unknown Source)
at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringNavigation.to(EventFiringWebDriver.java:567)
at org.jenkinsci.test.acceptance.FallbackConfig$1.evaluate(FallbackConfig.java:228)
at org.jenkinsci.test.acceptance.guice.Cleaner.performCleanUp(Cleaner.java:54)
at org.jenkinsci.test.acceptance.guice.TestCleaner.performCleanUp(TestCleaner.java:19)
at org.jenkinsci.test.acceptance.guice.World.endTestScope(World.java:66)
at org.jenkinsci.test.acceptance.junit.JenkinsAcceptanceTestRule$1.evaluate(JenkinsAcceptanceTestRule.java:64)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
at org.junit.runners.Suite.runChild(Suite.java:127)
at org.junit.runners.Suite.runChild(Suite.java:26)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by batmat** [comment]
O.M.G.

image

What a time to be alive! :stuck_out_tongue_closed_eyes:

**Comment by olivergondza** [comment]
Nah, that can't be real...

**Comment by batmat** [comment]
What a suspense
image

**Comment by batmat** [comment]
Green build! Let's merge! I believe I'll do that in one hour or so if you don't do that before @olivergondza :)

**Comment by olivergondza** [comment]
@batmat, @MRamonLeon, thank you guys!

**Pull request merged**
