### PR TITLE
[JENKINS-51205] Improve performance of /pluginManager/available service

### PR DESCRIPTION
**Pull request by jglick**
See [JENKINS-51205](https://issues.jenkins-ci.org/browse/JENKINS-51205). Seems to reduce `curl` time for this page from 8.1s → 4.7s, and seems to reduce overhead more inside the ATH Docker container, but measurements need to be confirmed.

### Proposed changelog entries

* Faster rendering of **Plugin Manager » Available**.

### Desired reviewers

@raul-arabaolaza

### CODE REVIEW

**Comment by raul-arabaolaza** [comment]
I am going to perform some tests with this, and update here the results

**Comment by raul-arabaolaza** [comment]
Unfortunately, I am not observing big improvements with this change (in the order of seconds), although that may be related to my custom docker configuration and some network issues may be happening as I have experimented some incoherent results depending if I have already initialized the list of plugins before the test or not. I assume there is some caching done by Jenkins. I am continuing investigating

**Comment by raul-arabaolaza** [comment]
Even if this does not entirely solve JENKINS-50790 [git#589](https://github.com/jenkinsci/git-plugin/pull/589) will say I believe is worth it, so approving

**Review by raul-arabaolaza — APPROVED** [review]

**Comment by jglick** [comment]
I definitely _did_ see lots of CPU being consumed by the thread rendering `table.jelly` and I think this reduces that overhead significantly. OTOH there is also plenty of overhead on the browser side rendering this gigantic table. While it makes sense to show a simple list like this in **Updates** or **Installed**, for **Available** we would be better served by a different UI. Maybe it would help to just hide everything by default until you type something in the search field (ideally using JS to avoid loading content from the server until you have a filter); of course that would certainly mandate changes to ATH.

**Comment by jglick** [comment]
FWIW https://github.com/jenkinsci/git-plugin/pull/589 is stable, compared to [trunk builds](https://ci.jenkins.io/job/Plugins/job/git-plugin/job/master/221/testReport/) which generally time out

	at org.jenkinsci.test.acceptance.po.PluginManager.installPlugins(PluginManager.java:235)

I suggest we merge this as a stopgap to stabilize ATH but also reconsider the UI.

**Comment by jglick** [comment]
@jenkinsci/code-reviewers

**Review by MarkEWaite — APPROVED** [review]
I didn't see any user-perceived difference between the "before" and the "after" case when loading the "Available" page from my Windows-based Google Chrome browser.

I was using a Debian 9 server with a locally attached SSD drive.  It may be that the locally attached SSD drive makes the frequent reads fast enough that no change is seen in the web browser.

The change seems reasonable to me, even without perceiving a performance difference in my use from a web browser.

**Comment by jglick** [comment]
OK, merging given that it seems to help at least the CI system running ATH, and might help people using HDDs.

**Pull request merged**
