### PR TITLE
Avoid archiving any test-related artifacts

### PR DESCRIPTION
**Pull request by jglick**
Amends #3759 (pending #3838) in case that solves [INFRA-1964](https://issues.jenkins-ci.org/browse/INFRA-1964). @olblak information as to the root cause of the Incrementals deployment errors would be appreciated, as this is purely speculative.

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Even if it is speculative, it definitely makes sense

**Review by jvz — APPROVED** [review]

**Review by batmat — APPROVED** [review]

**Comment by jglick** [comment]
Still waiting for build results of course.

**Comment by oleg-nenashev** [comment]
I will merge it right now, because there is a pretty high traffic in Jenkins core PRs nowadays

**Comment by batmat** [comment]
So it's an improvement but unfortunately did not solve the Incrementals ongoing failure.

**Comment by batmat** [comment]
Though `Skipping deployment as no artifacts were found with the expected path, typically due to a PR merge build not up to date with its base branch: https://ci.jenkins.io/job/Core/job/jenkins/job/PR-3870/1/artifact/**/*-rc*.bb7ba911d8fe/*-rc*.bb7ba911d8fe*/*zip*/archive.zip` might hint that the issue was a more usual one. Latest builds on `master` are still ongoing, we'll see what it gives there.

**Comment by batmat** [comment]
:fireworks: 
image

**Pull request merged**
