### PR TITLE
[JENKINS-66749] Missing spaces in upstream/downstream project view

### PR DESCRIPTION
**Pull request by jamesD33064**
# Missing spaces in upstream/downstream project view

截圖 2021-10-24 下午6 08 46

See [JENKINS-66749](https://issues.jenkins-ci.org/browse/JENKINS-66749).

### Proposed changelog entries

*  Add space between icon and project name in upstream & downstream section in project page.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by timja — DISMISSED** [review]

**Review by uhafner — CHANGES_REQUESTED** [review]

**Comment by jamesD33064** [comment]
截圖 2021-10-31 下午2 56 21

**Review by timja — APPROVED** [review]
The link also needed a margin, based on the fix in https://github.com/jenkinsci/jenkins/pull/5507 (I've pushed a commit to get this over the line)

I also created a css class for it, not the best naming but wasn't sure what do call it.

Tested this and it works

**Review by uhafner — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by uhafner** [comment]
I think a similar fix is required for `buildLink.jelly`. I'm currently trying to refactor my `summary.jelly` file with the new icons and here the gap is also missing. 

Additionally, the icon seems to render not correctly aligned vertically. Any idea what needs to be fixed in the CSS here? The first pixel seems to be aligned with the top of the text, it would look better if it is vertically centered?

Bildschirmfoto 2021-11-01 um 15 21 27

**Comment by timja** [comment]
Will try take a look later on

**Comment by uhafner** [comment]
I played around a little bit and it actually seems that our vertical alignment is broken somehow for the build status. Even on the same page I get different offsets for the alignment of text and SVG icon:

Bildschirmfoto 2021-11-01 um 15 51 47

Here the icon for the Java and Error Prone warnings are 4 pixels above the text. For the same icon for the Checkstyle and SpotBugs summary the icon starts just 1 pixel above the text. I have no idea what causes this misalignment?

(Sorry this is unrelated to this PR, simply an observation while trying to use the icon in my `summary.jelly`)

**Comment by uhafner** [comment]
> Will try take a look later on

Hmm, this is not yet solved? I think this problem occurs in several (all?) places where we use the icon.

**Comment by timja** [comment]
> > Will try take a look later on
> 
> Hmm, this is not yet solved? I think this problem occurs in several (all?) places where we use the icon.

Haven't had a chance, but this fixes this specific instance no reason to hold it back, we can iterate on improvements

**Comment by uhafner** [comment]
Ok, this just needs additional and duplicate work, I created a followup: #5887.

**Comment by timja** [comment]
Thanks for sorting it

**Pull request merged**
