### PR TITLE
Test plugin wrapper

### PR DESCRIPTION
**Pull request by olivergondza**
Add tests for plugin dependency resolution and tweak the message a bit as it was confusing.

(If we fail to install `foo` v5 that depends on `bar` v3+ because `bar` v4 (latest in UC) installation failed, it should refer to `bar`'s version we tried to install not the one `foo` wanted. This is especially confusing if there is more *foos* that depend on different `bar` versions - Jenkins will claim it failed to install multiple `bar` versions and none of them needs to be the one it really tried)

### CODE REVIEW

**Comment by olivergondza** [comment]
@jenkinsci/code-reviewers

**Comment by oleg-nenashev** [comment]
👍

**Review by oleg-nenashev — APPROVED** [review]
Maybe makes sense to changelog the message bit, but not sure

**Review by daniel-beck — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Merging without squash since the changes are independent

**Pull request merged**
