### PR TITLE
[JENKINS-61806] Remove the timestamp from the footer

### PR DESCRIPTION
**Pull request by fqueiruga**
See [JENKINS-61806](https://issues.jenkins-ci.org/browse/JENKINS-61806).

### Proposed changelog entries

* Entry 1: Removed the page generation timestamp from the footer.
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] JIRA issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@timja

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by daniel-beck** [comment]
Previously:

* https://github.com/jenkinsci/jenkins/pull/4599#issuecomment-603820574
* https://github.com/jenkinsci/jenkins/pull/4599#issuecomment-604929503
* https://github.com/jenkinsci/jenkins/pull/4599#issuecomment-604969580

@fqueiruga You wrote:

> I'll start a thread on the UX SIG chat to discuss the timestamp removal. Please consider meanwhile if the PR can go ahead as it is or if it can be rolled back on a future PR.

Can you provide a reference there? I would expect my feedback was discussed there, because I got no further responses in the original PR.

**Comment by fqueiruga** [comment]
@daniel-beck here's the thread from last week https://gitter.im/jenkinsci/ux-sig?at=5e7e0910284f2a59a9c92b41

**Review by oleg-nenashev — COMMENTED** [review]
It does not look like there is a consensus in the referenced Gitter thread. I do not have strong opinion, but I think that more feedback is needed.

It might be also possible to just hide the span in the new experimental UI layout (e.g. disable via CSS)

**Comment by Wadeck** [comment]
If we have the choice, -1 for the removal :)

**Comment by timja** [comment]
> If we have the choice, -1 for the removal :)

Is it -1 for removal in general, or with some tweaks to the implementation it would be okay?

Looking through Daniel's feedback, a couple of places the time could be added which may satisfy some of the use cases:

1. On the user profile page when setting a timezone display the system clock and adjusted time zone time?
2. Possibly add the current system time to the systemInfo page, so there's always a place to see it.

Wadeck's feedback:
> Concerning the removal of the timestamp, at this point I am not sure it's a good idea. I got some bug/vulnerability reports where the Jenkins version was not set. I imagine it's a bug under certain conditions in development mode

appears to have been marked as not an issue?

https://github.com/jenkinsci/jenkins/pull/4599#issuecomment-604266825

We can discuss this more on gitter, there was a thread there but not much engagement...

**Comment by Wadeck** [comment]
> Is it -1 for removal in general, or with some tweaks to the implementation it would be okay?

As I replied in the thread, I don't understand why we are trying to mix CSS change with "breaking" change.
If you tweak the stuff to be displayed somewhere else, why not. Pure removal seems wrong.

**Comment by fqueiruga** [comment]
The reason I created this as a separate PR was precisely to avoid mixing it with the CSS improvements efforts.

**Comment by fqueiruga** [comment]
If feedback is negative I can leave the ticket open for comments and withdraw this PR.

**Comment by MRamonLeon** [comment]
It seems people in general wants to keep it. Is it feasible to have a link or whatever to show it for some people, while keeping it hidden for users in general @fqueiruga ?

**Review by rsandell — COMMENTED** [review]
What motivation is there for removing it?
The issue description doesn't say anything more than to do it. We can't all hang out in Gitter and follow along on all discussions to magically know the background for a change like this.

**Comment by fqueiruga** [comment]
The motivation was that many people considered it superficial. I'm closing it because it has become stale anyway.

**Pull request closed without merging**
