### PR TITLE
JENKINS-60513: Added transient to SCMDescriptor#generation AtomicInteger to fix warnings

### PR DESCRIPTION
**Pull request by StefanSpieker**
This was reported and I think adding the class to the whitelist seems fine.

See [JENKINS-60513](https://issues.jenkins-ci.org/browse/JENKINS-60513).

### Proposed changelog entries

* Regression-Fix: Resolve warnings from AtomicInteger and class-filter

### Submitter checklist

- [x] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
AtomicInteger primitive may differ across JVMs, and serialization may fail. On the case of this issue it might make more sense to rename the field and make it transient. Transient and restricted int field could be also introduced to avoid Old data monitor warnings

**Comment by StefanSpieker** [comment]
I thought, since the AtomicBoolean was also part of the list, this would be safe. And if I read the documentation right, they are both serialized to an Integer: https://docs.oracle.com/javase/8/docs/api/serialized-form.html#java.util.concurrent.atomic.AtomicInteger

**Comment by StefanSpieker** [comment]
@oleg-nenashev: I added the transient to the field and reverted the whitelist change. Since it is private field it should not be necessary to add an Restricted to it, right?

**Review by fcojfernandez — APPROVED** [review]

**Review by varyvol — APPROVED** [review]

**Comment by fcojfernandez** [comment]
@oleg-nenashev we think this PR can be marked as ready-for-merge. WDYT?

**Review by res0nance — APPROVED** [review]
This looks ok, if this value isn't serialized does it create issues? It seems to come from some deprecated code but it might have an effect on anything that relies on this value.

**Review by oleg-nenashev — APPROVED** [review]
It will do the job for this error, but it will still impact deserialization of old values. Might be better to rename the field

**Comment by StefanSpieker** [comment]
@oleg-nenashev: I changed the name.

**Comment by oleg-nenashev** [comment]
I plan to merge it tomorrow if no negative feedback

**Comment by daniel-beck** [comment]
This should be mentioned in the upgrade guide because it causes unloadable data warnings.

Screenshot 2020-03-25 at 20 49 45

**Pull request merged**
