### PR TITLE
[JENKINS-67885] update the bundled `display-url-api` plugin

### PR DESCRIPTION
**Pull request by jtnord**
the bundled mailer plugin was DOA as it failed to start because the
bundled display-url-plugin was too old

Updates the disaplay-url plugin to 2.3.5 to fix the issue

See [JENKINS-67885](https://issues.jenkins-ci.org/browse/JENKINS-67885).

### Proposed changelog entries

* Update bundled display-url-plugin to prevent issues starting the mailer plugin for offline installations.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@Wadeck 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [x] There are at least 2 approvals for the pull request and no outstanding requests for change
- [x] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [x] Proper changelog labels are set so that the changelog can be generated automatically
- [x] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [x] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by jtnord** [comment]
ammends https://github.com/jenkinsci/jenkins/pull/6180

**Review by jglick — COMMENTED** [review]
OK but is there no automated test which should have caught this?

**Comment by timja** [comment]
Possible to fix it so the test fails?

ref. https://github.com/jenkinsci/jenkins/pull/6180#discussion_r784174935

**Comment by jglick** [comment]
Also https://github.com/jenkinsci/jenkins/blob/89c59b479b58fc6dcc31157ec5f6aa5d747e0b6c/core/src/main/resources/jenkins/split-plugins.txt#L17 maybe time to remove some of these extremely old splits?

**Review by MarkEWaite — APPROVED** [review]

**Comment by daniel-beck** [comment]
This looks like a late LTS inclusion candidate. Thoughts @timja @cathychan ?

**Comment by daniel-beck** [comment]
Choosing an older version in https://github.com/jenkinsci/jenkins/blob/89c59b479b58fc6dcc31157ec5f6aa5d747e0b6c/test/src/test/java/jenkins/install/LoadDetachedPluginsTest.java#L73 should demonstrate a test failure without this fix, WDYT about adding this?

**Comment by timja** [comment]
+1 for backporting it

**Comment by MarkEWaite** [comment]
+1 for backporting it

**Comment by jtnord** [comment]
> Choosing an older version in
> 
> https://github.com/jenkinsci/jenkins/blob/89c59b479b58fc6dcc31157ec5f6aa5d747e0b6c/test/src/test/java/jenkins/install/LoadDetachedPluginsTest.java#L73
> 
> should demonstrate a test failure without this fix, WDYT about adding this?

using `1.490` works.  need to pick a number that is old enough for the lowest detached plugin that we bundle but older than a detached plugin that is no longer bundled...

```
   3.099 [id=63]        SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Jenkins Mailer Plugin v408.vd726a_1130320 (mailer)
java.io.IOException: Failed to load: Jenkins Mailer Plugin (mailer 408.vd726a_1130320)
 - Update required: Display URL API (display-url-api 2.3.4) to be updated to 2.3.5 or higher
        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:1018)
        at hudson.PluginManager$2$1$1.run(PluginManager.java:542)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:175)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:305)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1156)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:222)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:121)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
   4.268 [id=63]        INFO    jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
   4.276 [id=65]        INFO    jenkins.InitReactorRunner$1#onAttained: Started all plugins
   4.277 [id=48]        INFO    jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
   4.332 [id=48]        INFO    jenkins.model.Jenkins#setBuildsAndWorkspacesDir: Using non default workspaces directories: ${JENKINS_HOME}/workspace/${ITEM_FULLNAME}.
   4.764 [id=48]        INFO    jenkins.InitReactorRunner$1#onAttained: System config loaded
   4.764 [id=57]        INFO    jenkins.InitReactorRunner$1#onAttained: System config adapted
   4.765 [id=64]        INFO    jenkins.InitReactorRunner$1#onAttained: Loaded all jobs
   4.767 [id=47]        INFO    jenkins.InitReactorRunner$1#onAttained: Configuration for all jobs updated
   4.781 [id=52]        INFO    hudson.model.AllView#migrateLegacyPrimaryAllViewLocalizedName: JENKINS-38606 detected for AllView in hudson.model.Hudson@74a94b2a; renaming view from All to all
   4.923 [id=45]        INFO    jenkins.InitReactorRunner$1#onAttained: Completed initialization
   5.013 [id=23]        INFO    hudson.lifecycle.Lifecycle#onStatusUpdate: Stopping Jenkins
   5.180 [id=23]        INFO    hudson.lifecycle.Lifecycle#onStatusUpdate: Jenkins stopped
```

**Comment by daniel-beck** [comment]
Since https://github.com/jenkinsci/jenkins/pull/5445 in 2.292, this is the oldest version (range) that works for this, anything older is no longer bundled.

**Comment by jtnord** [comment]
https://github.com/jenkinsci/jenkins/pull/6306  the version needs to be newer than things which are split but no longer bundled and older than something we want to test.

**Comment by jtnord** [comment]
I have updated the Fix so it builds on the failing test to show that the test passes (well it should - just need the build to finish!)

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Pull request merged**
