### PR TITLE
JENKINS-68302 Use `mvnw` to specify Maven v3.8.4 as v3.8.5 fails

### PR DESCRIPTION
**Pull request by cyrille-leclerc**
Fix [JENKINS-68302 - Building Jenkins with Maven 3.8.5 fails on maven-shade-plugin:shade](https://issues.jenkins.io/browse/JENKINS-68302)

Use `mvnw` to specify Maven v3.8.4 as v3.8.5 fails
Maven v3.8.4 fails with: "Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.3.0:shade (default) on project cli: Error creating shaded jar: duplicate entry: META-INF/services/io.jenkins.cli.shaded.jakarta.websocket.ContainerProvider"

Problem discussed on https://groups.google.com/g/jenkinsci-dev/c/q4Lz3flJXI0

### Proposed changelog entries

* Add Maven Wrapper (`mvnw`) to specify the version of Maven to use to build Jenkins as there are problems with Maven 3.8.5

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@MarkEWaite @jglick 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

### CODE REVIEW

**Review by timja — COMMENTED** [review]
see https://github.com/jenkinsci/jenkins/pull/4736

**Comment by basil** [comment]
Right, we think this is a great idea, but like https://github.com/jenkinsci/jenkins/pull/4736, it needs corresponding changes to our Pipeline jobs to invoke `./mvnw` rather than `mvn`.

**Comment by cyrille-leclerc** [comment]
> Right, we think this is a great idea, but like #4736, it needs corresponding changes to our Pipeline jobs to invoke `./mvnw` rather than `mvn`.

Thanks @basil , I'm wondering if the introduction of `mvnw` is primarily aimed at helping the onboarding of community members who want to contribute to Jenkins Core.
I don't think that having the CI pipeline using `mvnw` is a requirement for this goal of simplifying community onboarding.


is IMO to help community members to contribute to Jenkins.

**Review by basil — CHANGES_REQUESTED** [review]
True, the introduction of Maven Wrapper assists in the onboarding of new contributors. Yet also, it carries an associated maintenance burden for the core maintainers in that the wrapper needs to be kept up-to-date somehow. When CI builds are using the wrapper, updating the wrapper to the latest version of Maven (which can be automated) suffices. When CI builds are not using the wrapper, updates to the wrapper must be coordinated in lockstep with updates to the version of Maven used in CI builds (which is a manual process). This increases the maintenance burden for the core maintainers, and I am not willing to take on this additional burden.

In the long term, updating the CI builds to use Maven Wrapper alongside its introduction provides the benefits of a smoother onboarding experience for new contributors without the associated maintenance cost of keeping the wrapper synchronized with updates to the version of Maven used in CI builds.

**Comment by basil** [comment]
This pull request is off to a promising start but requires additional effort to reach completion: effort that appears to have been abandoned. Since this pull request has remained incomplete with no activity for over a month, I am marking it as `stalled`. If it remains inactive for several more weeks, I will label it as `proposed-for-close` in order to maintain an orderly PR queue and close the PR approximately one week after that.

**Comment by jglick** [comment]
Maven 3.8.6 has been released which I think fixes the regression so this is no longer an urgent concern?

**Comment by NotMyFault** [comment]
> Maven 3.8.6 has been released which I think fixes the regression so this is no longer an urgent concern?

ci.jenkins uses 3.8.6 by now and builds without issue, seems so, if there is still interest in using and maintaining the wrapper 🤔

**Comment by jglick** [comment]
Pinning versions of tools used during the build makes sense, but `mvnw` seems like an outdated way of doing that—forces the build to download the tool at runtime (or use some complicated cache). If we are using container agents, then perhaps the infra team could specify tool versions in label variants so projects could pick the desired version, rather than always getting “latest”. https://github.com/jenkinsci/jenkins/blob/b95e3e6e28b7bce0efb07db2ca1ec01d6a5dc784/Jenkinsfile#L27-L32

**Comment by basil** [comment]
> If it remains inactive for several more weeks, I will label it as `proposed-for-close` in order to maintain an orderly PR queue and close the PR approximately one week after that.

Due to inactivity, I am closing this PR. On behalf of the core team, I would like to thank you for your contribution. Even though this PR did not make it across the finish line, it was a promising start! I continue to encourage you (or anyone else who is interested!) to pick up this PR and drive it to completion. Thanks!

**Pull request closed without merging**
