### PR TITLE
[FIX JENKINS-35263] displaying codeMirror as table to fix page sizing

### PR DESCRIPTION
**Pull request by gusreiber**
td.setting-main .CodeMirror {
display: table;
table-layout: fixed;
width: 100%;
}

Setting as suggested by Dmitry Medvedev
https://issues.jenkins-ci.org/browse/JENKINS-27367

@jenkinsci/code-reviewers @daniel-beck @recena

### CODE REVIEW

**Comment by recena** [comment]
@gusreiber Let me take a look in my local environment...

**Comment by daniel-beck** [comment]
Anyone wondering how this could work? The answer is the `lib.form.textarea.textarea` adjunct included in `/lib/form/textarea.jelly`, so far only used for JavaScript. This adds the sibling CSS file.

**Review by daniel-beck — APPROVED** [review]
Seems to work. The initial form starts with a pixel or two of horizontal scrolling, but compared to the other mess, this is a huge improvement.

Thanks for taking care of this @gusreiber :+1:

**Comment by daniel-beck** [comment]
FTR before:

> before

After (OS X hides scroll bars unless scrolling): 

> after

**Comment by oleg-nenashev** [comment]
LGTM 👍

**Comment by kwaping** [comment]
LGTM 👍 also, much better than my solution. Good work. (Tested only in Firefox 49.0.1)

**Comment by oleg-nenashev** [comment]
Merging according to the feedback. 2.26 is a target release

**Comment by dblanchette** [comment]
This still seems to be a problem today. I was able to circumvent it by injecting the same CSS but without the CodeMirror class:

```css
td.setting-main {
    display: table;
    table-layout: fixed;
    width: 100%;
}
```

Is this known?

**Pull request merged**
