### PR TITLE
Remove extraneous whitespace below title on Job pg

### PR DESCRIPTION
**Pull request by kevinburke**
There's extra whitespace caused by the description/Disable Project fields
floating all the way across the page. This change floats those boxes to the
right, which allows the Workspace/Recent Changes boxes to come up the page and
allows more page content to fit onscreen.

Abbreviated screenshot:

### CODE REVIEW

**Comment by jglick** [comment]
Status?

**Comment by oleg-nenashev** [comment]
@kevinburke 
Is this PR alive?

**Comment by kevinburke** [comment]
Hey - I haven't had a chance to test this change against the latest master, and I doubt I will, sorry :(

You should be able to verify it by building this branch and checking that the UI matches the view in the screenshot.

**Comment by batmat** [comment]
Just added the `needs-fix` label since https://github.com/jenkinsci/jenkins/pull/1329#issuecomment-50603424 does not appear to have been processed.

**Comment by daniel-beck** [comment]
@batmat Good find, thanks.

**Comment by daniel-beck** [comment]
PR appears to have been abandoned, closing.

**Pull request closed without merging**
