### PR TITLE
Allow rows to be clicked for selecting plugins in the Plugin Manager

### PR DESCRIPTION
**Pull request by rtyler**
This allows users to simply click the entire table row in the Plugin Manager, rather than needing to click the 15x15 pixel checkbox to select a plugin

There were a few JavaScript errors I ended up correcting while I was in here.

Whitespace ignoring diff: https://github.com/jenkinsci/jenkins/pull/3544/files?w=1

### Proposed changelog entries

* Plugins can be selected by clicking rows in the plugin manager rather than strictly clicking the checkbox

### CODE REVIEW

**Comment by slide** [comment]
:+1:

**Review by daniel-beck — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Nice idea! IIUC some test failures are related

**Comment by rtyler** [comment]
I have a sneaking suspicion that these test failures are due to htmlunit being stupid and not understanding [let](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let) or anything resembling contemporary JavaScript :frowning_man:

**Comment by rtyler** [comment]
Confirmed, we're apparently using an htmlunit that's old AF. (2.16, released in 2015) through [jenkins-test-harness-htmlunit](https://github.com/jenkinsci/jenkins-test-harness-htmlunit) which is consumed by [jenkins-test-harness](https://github.com/jenkinsci/jenkins-test-harness)

**Review by Wadeck — APPROVED** [review]
:bee:

**Comment by oleg-nenashev** [comment]
Well, the test failure does really look related and important:

```
Linux / Linux Publishing / hudson.PluginManagerInstalledGUITest – hudson.PluginManagerInstalledGUITest<1s
Error
Java heap space
Stacktrace
java.lang.OutOfMemoryError: Java heap space
at java.util.Arrays.copyOf(Arrays.java:3332)
at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:649)
at java.lang.StringBuilder.append(StringBuilder.java:202)
at org.apache.maven.surefire.util.internal.StringUtils.escapeToPrintable(StringUtils.java:186)
at org.apache.maven.surefire.booter.ForkingRunListener.nullableEncoding(ForkingRunListener.java:364)
at org.apache.maven.surefire.booter.ForkingRunListener.encode(ForkingRunListener.java:388)
at org.apache.maven.surefire.booter.ForkingRunListener.encode(ForkingRunListener.java:370)
at org.apache.maven.surefire.booter.ForkingRunListener.toString(ForkingRunListener.java:316)
at org.apache.maven.surefire.booter.ForkingRunListener.testError(ForkingRunListener.java:161)
```

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
test needs to be fixed or investigated.
Seems the Jelly patch triggers some weird behavior

**Comment by rtyler** [comment]
No idea why this fails, I give up.

**Pull request closed without merging**
