### PR TITLE
[INFRA-1032] ${user.name} might contain metacharacters

### PR DESCRIPTION
**Pull request by jglick**
Replaces #2716 with the same fix as in https://github.com/jenkinsci/remoting/pull/173.

@reviewbybees

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
🐝

**Comment by jglick** [comment]
[Working so far](https://ci.jenkins.io/job/Core/job/jenkins/job/PR-2929/1/execution/node/28/log/?consoleFull):

    [INFO] Setting property 'build.version' to '2.68-SNAPSHOT (private-06/26/2017 19:29 GMT-win2012-b5ff00$)'.

**Comment by rtyler** [comment]
@jglick Just thinking aloud here, but is there a reason that regex-property stuff shouldn't go into the parent pom?

**Comment by jglick** [comment]
Parent POM as in `jenkins/pom`? It could I guess, though for plugins we already have [this code](https://github.com/jenkinsci/maven-hpi-plugin/blob/78627204f82009367dd554b4b3732cf9f4970d84/src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java#L939-L944) which is better as it includes a Git commit hash as well as the `user.name`. So since `jenkins` and `remoting` both handle build numbers, pulling it up into the parent would only benefit other non-plugin/module components TBD which opted in to the feature.

**Comment by rtyler** [comment]
@jglick Understood, just curious.

**Comment by jglick** [comment]
@reviewbybees done

**Pull request merged**
