### PR TITLE
Remove Turkish localization

### PR DESCRIPTION
**Pull request by mustafau**
All Turkish localization files have been moved to the [Turkish Localization Plugin](https://github.com/jenkinsci/localization-tr-plugin). That plugin is ready to be released. 

See [JEP-216](https://github.com/jenkinsci/jep/blob/master/jep/216/README.adoc)

### Proposed changelog entries

* Localization: Migrated Turkish localization files into Turkish Localization Plugin

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### CODE REVIEW

**Comment by daniel-beck** [comment]
The reason that dedicated localization plugins exist is that it's easier for translators to contribute to them and don't need to have changes reviewed and accepted by developers who do not speak the language anyway. Ultimately this benefits users through more and better localized content.

However, before a large-scale change like this, I'd really like to see some effort around the actual _translating_. So far you've submitted a single one-line translation fix to core in #4056 (and we're actually pretty good at accepting translations, unlike many plugins). It doesn't look like you have submitted any PR to plugins contributing translations, and https://github.com/jenkinsci/localization-tr-plugin hasn't been updated in months and looks like it contains no new translations over what is being removed here from core. 

So far, I see no benefit to users here. How do you envision this going forward? Is there a community of Turkish-speaking Jenkins users who've committed to contribute translations? Why haven't you, or they, contributed any translations through the existing model of translations bundled with the components they appear in? I mean, even if any PRs remained unmerged, the content could be ported to the dedicated localization plugin, after all.

**Comment by oleg-nenashev** [comment]
I think we could bring it up in the user or development mailing list.
The change itself is useful IMHO, especially if there is an intention to keep extending the translations

**Comment by mustafau** [comment]
My intention here is to release the plugin as-is and make further contributions there. However, I have no objection to start contributing in the core. We can move to the localization plugin when the community see fit. 

I personally do not know anybody who is willing to contribute Turkish translations. I will see if I can bring anyone in.

**Comment by alecharp** [comment]
For the moment, the Turkish Translation plugin is not ready to be released (one test in error) so we should wait for the first release of the plugin before merging this IMO.

**Comment by MRamonLeon** [comment]
Adding on-hold label until an agreement is reached in the mail list or the plugin is released.

**Comment by oleg-nenashev** [comment]
Hi @mustafau . Are you still interested in it? There was no discussion in the developer mailing list as I suggested on Oct 21, and I am not sure whether you plan to proceed with it or suggest another way. If there is no plan to continue here, I suggest closing the pull request

**Comment by fcojfernandez** [comment]
I agree with Oleg this PR can be closed, so I'm proceeding. @mustafau if you plan to continue working on it, please reopen it

**Pull request closed without merging**
