### PR TITLE
Unbundle Maven Plugin and Subversion Plugin

### PR DESCRIPTION
**Pull request by daniel-beck**
Stop bundling Maven and Subversion Plugins in the Jenkins war.

There are no plugins for installation in `update-center.json` that have a core dependency older than 1.323. Since maven-plugin got split from core in 1.296 and subversion in 1.310, they are no longer being installed in any realistic situation.

Manually tested by putting one of the plugins depending on core 1.323 in `$JENKINS_HOME/plugins` and starting Jenkins. There's no `maven-plugin` or `subversion` being extracted.

Keep the maven-plugin dependency for the tests, as there are quite a few depending on it.

Requesting @jglick for review as IIRC he recently proposed removing `maven-plugin` somewhere.

Supersedes #4146.

### Proposed changelog entries

* Stop bundling Maven Plugin and Subversion Plugin with Jenkins. In very rare cases, this could result in problems when attempting to install plugins compatible with Jenkins before 1.310. The Jenkins project is currently not publishing any such plugins.

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### CODE REVIEW

**Comment by daniel-beck** [comment]
If you like this PR, check out https://github.com/jenkinsci/jenkins/pull/4040! 😁

**Comment by jglick** [comment]
> We are no longer offering plugins for installation in `update-center.json` that have a core dependency older than 1.323.

Oh? Why?

**Review by jglick — COMMENTED** [review]
Should it not then be removed from `split-plugins.txt` & `split-plugin-cycles.txt`? And if your cutoff is 1.323, then why would you not also remove `subversion`, split at 1.310?

**Comment by daniel-beck** [comment]
@jglick 

> Oh? Why?

No reason, it just happened. In theory, someone could lower a core dependency sufficiently to break this, but I consider this unlikely.

> Should it not then be removed from `split-plugins.txt` & `split-plugin-cycles.txt`?

Unsure. It still exists and was detached -- we just don't need to bundle it in practice.

> And if your cutoff is 1.323, then why would you not also remove `subversion`, split at 1.310?

I thought about it, but decided to submit without. That said, both plugins suffer from being severely outdated and not being able to be easily updated.

**Comment by jglick** [comment]
> it just happened

You mean, all plugins which happened to have an older dependency were either updated, or removed for various reasons such as security advisories? Not that there was some change to the update center which specifically set this cutoff and blocked plugins using an older dep.

**Comment by jglick** [comment]
> It still exists and was detached -- we just don't need to bundle it

Just in case there is some plugin with an older dep still installed, even though there is an update for this plugin available, or it has been taken off the UC altogether? OK, harmless I suppose.

**Review by jglick — APPROVED** [review]
I actually think we should more aggressively stop bundling any plugins older than some reasonable distance in the past (two years?), and stop claiming to support direct upgrades from such old versions, but that would be a bigger discussion, maybe a JEP. This seems safe.

**Comment by daniel-beck** [comment]
> direct upgrades from such old versions

Quick reminder that you did #4000 and that would break again badly if we did.

**Comment by daniel-beck** [comment]
> You mean, all plugins which happened to have an older dependency were either updated, or removed for various reasons such as security advisories? Not that there was some change to the update center which specifically set this cutoff and blocked plugins using an older dep.

That is my assumption, yes. I have not investigated further, just looked at the JSON. Could dig deeper, but is it really worth the time?

> Just in case there is some plugin with an older dep still installed, even though there is an update for this plugin available, or it has been taken off the UC altogether? OK, harmless I suppose.

That, or private source plugins.

**Review by oleg-nenashev — APPROVED** [review]
LGTM, but IMHO it will require a mention in the upgrade guide for LTS

**Review by timja — APPROVED** [review]

**Review by fcojfernandez — APPROVED** [review]

**Review by varyvol — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
I plan to merge it tomorrow if no negative feedback

**Comment by daniel-beck** [comment]
Build passed but it failed at the notification at the end.

**Comment by daniel-beck** [comment]
Merged master after #4040 to resolve conflict.

**Review by timja — APPROVED** [review]

**Pull request merged**
