### PR TITLE
JENKINS-64040 JENKINS-64136 Fix hidden page elements from radio blocks showing up when they shouldn't

### PR DESCRIPTION
**Pull request by timja**
See [JENKINS-64136](https://issues.jenkins-ci.org/browse/JENKINS-64136).
See [JENKINS-64040](https://issues.jenkins-ci.org/browse/JENKINS-64040).

Reverts https://github.com/jenkinsci/jenkins/pull/4936

image

Certain properties could be made visible as a child of radioBlock and made to float on the page, the hidden selector didn't override more specific ones

It appears the original bug is fixed by tables to div fixes so reverting the fix

Reproduction steps:
1. Start Jenkins with git plugin installed
2. Create a freestyle job
3. See floating add repository and add branch buttons

### Proposed changelog entries

* Entry 1: JENKINS-64136 and JENKINS-64040, Fix hidden page elements from radio blocks showing up when they shouldn't
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [x] There are at least 2 approvals for the pull request and no outstanding requests for change
- [x] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [x] Proper changelog labels are set so that the changelog can be generated automatically
- [x] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [x] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by fqueiruga** [comment]
I would vote to just revert the whole thing. 
The `position: absolute;` is unreliable, as wrong parent with a `position: relative;` may break the whole thing. In addition, `visibility: hidden;` still blocks pointer events. All in all, IMO, any solution should involve `display: none;` in order to be reliable.

**Comment by timja** [comment]
> I would vote to just revert the whole thing.
> The `position: absolute;` is unreliable, as wrong parent with a `position: relative;` may break the whole thing. In addition, `visibility: hidden;` still blocks pointer events. All in all, IMO, any solution should involve `display: none;` in order to be reliable.

the problem with `display: none` is that it affects layout hence the original bug.

`visibility:hidden` preserves layout.

can you test it on the cloudbees internal plugin to see if it fixes it?

**Comment by fqueiruga** [comment]
Does the old bug also happen with the tables-to-divs changes?? 

At the very least I would suggest putting a 0px or 1px height. The fact that `visibility:hidden;` preserves layout is the reason why it overlaps over other elements. I would say that it may be better to have another look at the `radioBlock` markup rather than introducing this item.

**Comment by fqueiruga** [comment]
We are not yet able to test it on our proprietary plugin as it hasn't been updated to be tables-to-divs compatible.

**Comment by timja** [comment]
> Does the old bug also happen with the tables-to-divs changes??

I can't reproduce it after the tables to divs fixes

cc @benebsiny

**Comment by fqueiruga** [comment]
We'll report back once we fix our plugin, we will test it against 2.265 and see if it still fails. 

Still, I think reverting is the right choice. We have found issues in 2 plugins, we don't know how many more there can be.

**Comment by timja** [comment]
> We'll report back once we fix our plugin, we will test it against 2.265 and see if it still fails.
> 
> Still, I think reverting is the right choice. We have found issues in 2 plugins, we don't know how many more there can be.

well given I can't reproduce the previous bug any more after reverting the change I don't have an issue with it...

**Review by fqueiruga — APPROVED** [review]

**Review by MarkEWaite — APPROVED** [review]
I built the pull request and confirmed that the change prevents the "Add repository" button from appearing with git plugin 4.4.5.  Thanks for the fix!

**Comment by MarkEWaite** [comment]
This PR is now ready for merge.  We will merge it after approximately 24 hours if there is no negative feedback.

**Review by daniel-beck — APPROVED** [review]

**Review by res0nance — APPROVED** [review]

**Review by jglick — APPROVED** [review]

**Pull request merged**
