### PR TITLE
update workspace permission zh description

### PR DESCRIPTION
**Pull request by runzexia**

### CODE REVIEW

**Comment by runzexia** [comment]
@LinuxSuRen

**Review by LinuxSuRen — CHANGES_REQUESTED** [review]

**Comment by LinuxSuRen** [comment]
LGTM

**Comment by runzexia** [comment]
rebase

**Review by oleg-nenashev — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Meanwhile we can squash PRs during the merge. No need to spend extra time on rebasing

**Pull request merged**
