### PR TITLE
[JENKINS-47127] - Update maven-war-plugin from 3.0.0 to 3.2.3

### PR DESCRIPTION
**Pull request by based2**
https://maven.apache.org/plugins/maven-war-plugin/

# Proposed changelog entries

 * Internal: update maven-war-plugin from 3.0.0 to 3.2.3

Submitter checklist

JIRA issue is well described
Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). Examples
* Use the Internal: prefix if the change has no user-visible impact (API, test frameworks, etc.)
Appropriate autotests or explanation to why this change has no tests

    For dependency updates: links to external changelogs and, if possible, full diffs

Desired reviewers

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
CC @batmat who was working on https://issues.jenkins-ci.org/browse/JENKINS-47127 . I doubt we have much test coverage in this area

**Comment by batmat** [comment]
@based2 can you please confirm you see the favicon in a correct state after building Jenkins? Thanks

**Comment by based2** [comment]
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 55.682 s - in jenkins.scm.SCMCheckoutStrategyTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR] hudson.UDPBroadcastThreadTest.legacy(hudson.UDPBroadcastThreadTest)
[ERROR]   Run 1: UDPBroadcastThreadTest.legacy:36->receiveAndVerify:87 » SocketTimeout Receive ...
[ERROR]   Run 2: UDPBroadcastThreadTest.legacy:36->receiveAndVerify:87 » SocketTimeout Receive ...
[ERROR]   Run 3: UDPBroadcastThreadTest.legacy:36->receiveAndVerify:87 » SocketTimeout Receive ...
[ERROR]   Run 4: UDPBroadcastThreadTest.legacy:36->receiveAndVerify:87 » SocketTimeout Receive ...
[ERROR]   Run 5: UDPBroadcastThreadTest.legacy:36->receiveAndVerify:87 » SocketTimeout Receive ...
[INFO] 
[ERROR] hudson.UDPBroadcastThreadTest.multicast(hudson.UDPBroadcastThreadTest)
[ERROR]   Run 1: UDPBroadcastThreadTest.multicast:63->receiveAndVerify:87 » SocketTimeout Recei...
[ERROR]   Run 2: UDPBroadcastThreadTest.multicast:63->receiveAndVerify:87 » SocketTimeout Recei...
[ERROR]   Run 3: UDPBroadcastThreadTest.multicast:63->receiveAndVerify:87 » SocketTimeout Recei...
[ERROR]   Run 4: UDPBroadcastThreadTest.multicast:63->receiveAndVerify:87 » SocketTimeout Recei...
[ERROR]   Run 5: UDPBroadcastThreadTest.multicast:63->receiveAndVerify:87 » SocketTimeout Recei...
[INFO] 
[INFO] 
[ERROR] Tests run: 9369, Failures: 0, Errors: 2, Skipped: 40
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Jenkins main module 2.180-SNAPSHOT:
[INFO] 
[INFO] Jenkins main module ................................ SUCCESS [ 57.406 s]
[INFO] Jenkins cli ........................................ SUCCESS [ 12.732 s]
[INFO] Jenkins core ....................................... SUCCESS [02:50 min]
[INFO] Jenkins war ........................................ SUCCESS [ 17.423 s]
[INFO] Jenkins core tests POM ............................. SUCCESS [  5.437 s]
[INFO] Tests for Jenkins core ............................. FAILURE [  01:07 h]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:12 h
[INFO] Finished at: 2019-06-08T12:40:04+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20:test (default-test) on project jenkins-test: There are test failures.

**Comment by based2** [comment]
[ERROR] Tests run: 10, Failures: 0, Errors: 10, Skipped: 0, Time elapsed: 162.269 s <<< FAILURE! - in hudson.UDPBroadcastThreadTest
[ERROR] multicast(hudson.UDPBroadcastThreadTest)  Time elapsed: 21.2 s  <<< ERROR!
java.net.SocketTimeoutException: Receive timed out
	at java.base/java.net.PlainDatagramSocketImpl.receive0(Native Method)
	at java.base/java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:181)
	at java.base/java.net.DatagramSocket.receive(DatagramSocket.java:814)
	at hudson.UDPBroadcastThreadTest.receiveAndVerify(UDPBroadcastThreadTest.java:87)
	at hudson.UDPBroadcastThreadTest.multicast(UDPBroadcastThreadTest.java:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:556)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by based2** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-8702

**Comment by based2** [comment]
Context: MacOS Mojave - Java11 - FR - Firefox 67.0.1
java -jar MYPATH/jenkins/war/target/jenkins.war
http://localhost:8080/ -> Jenkins 2.180-SNAPSHOT

Note: SetupWizard / UI issue text header overlap on: "Créer le 1er utilisateurs Administrateur"
the "Administrateur" is over the "Créer le 1er utilisateurs" text. Favicon is not visible at this step.

Using Jenkins, show the favicion.ico load in the firefox dev network tool: 
http://localhost:8080/static/f5860b6b/favicon.ico Status: 200
Now, as changing to Github tab, the Jenkins icon is visible in the Firefox Jenkins tab.

**Comment by based2** [comment]
French translation is lacking, ex:
 Nouveau Item -> Nouvel élément
 Lockable Resources -> Ressources blocables
 New View -> Nouvelle vue
 Configure Credentials -> Configurer les identifiants, mots de passes et clés
 Logs systèmes -> Journaux systèmes

 Utilisateurs : Inclus tout les utilisateurs connus> Inclus tous les utilisateurs connus

A good helper for translations: https://www.deepl.com/

**Comment by batmat** [comment]
Just noticed also the PR template was blanked out. Please restore it and check and fill the right fields.

**Comment by based2** [comment]
done

**Review by batmat — APPROVED** [review]
Given the upstream bug is deemed fixed, and submitter says the favicon is still visible, LGTM

**Review by oleg-nenashev — APPROVED** [review]
Should be fine

**Comment by oleg-nenashev** [comment]
Will merge on Wednesday if no negative feedback

**Pull request merged**
