### PR TITLE
[JENKINS-25953] Tabs in job view are mis-aligned

### PR DESCRIPTION
**Pull request by baskaran-md**
Before: 
beforefix_jenkins-25953

After (Chrome):
afterfix_jenkins-25953_chrome

After (Firefox):
afterfix_jenkins-25953_firefox

### CODE REVIEW

**Comment by baskaran-md** [comment]
This is forked from https://github.com/jenkinsci/jenkins/pull/1483, as it didn't address all the issues.

**Comment by daniel-beck** [comment]
Why did you leave the border definition in?

**Comment by baskaran-md** [comment]
Thanks @daniel-beck. Removed it.

**Comment by pwielgolaski** [comment]
could you post screenshot after final chances when border is set for none?

**Comment by baskaran-md** [comment]
Updated my first comment - https://github.com/jenkinsci/jenkins/pull/1544#issue-55430728 with new screenshots. Thank you, @pwielgolaski.

**Comment by daniel-beck** [comment]
Was the gap below the highlighted element there before?

**Comment by baskaran-md** [comment]
I am not sure which Gap you're talking about. I upgraded from Jenkins Ver-1.570 to Ver-1.597. 

Gap-1 (red) is unmodified before and after fix. Current fix is to address Gap-2 (blue) only.

gaps_before_jenkins-25953_chrome

**Comment by baskaran-md** [comment]
@daniel-beck  Is it ready for the merge, or needs any improvement?

**Comment by daniel-beck** [comment]
In the new version, compared to other tabs, the selected tab appears to have 1 px less height. There is a gap between it and the top of the tabs on the second row.

**Comment by baskaran-md** [comment]
@daniel-beck Agreed. After hours of debugging, I found that its https://github.com/kevinburke/doony theme, which is causing the issue. 

Initial fix by @pwielgolaski itself is working fine. Apologize for the confusion.

Closing this Pull Request.

**Pull request closed without merging**
