### PR TITLE
 [JENKINS-28553] - Stable workaround for adding PluginServletFilter

### PR DESCRIPTION
**Pull request by ManuelB**
https://marvelution.atlassian.net/browse/JJI-188

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
I would recommend...
* Create an issue on Jenkins JIRA with a reference to the issue on your bugtracker
* Document the behavior in Javadoc of <code>getInstance</code>
* Add <code>@CheckForNull</code> annotation there
* Call <code>getInstance()</code> only once to make the static analysis happy

**Comment by ManuelB** [comment]
Thanks. I will try to integrate the feedback in the next few days.

/Manuel

**Comment by ManuelB** [comment]
JIRA Issue in Jenkins Tracker: https://issues.jenkins-ci.org/browse/JENKINS-28553

**Comment by oleg-nenashev** [comment]
Marked as WiP, because the comments have not been addressed yet.
BTW :+1:  for merging the change when it gets adjusted

**Comment by ManuelB** [comment]
Hi Oleg,
I added the Feedback to the code.

/Manuel

**Comment by ManuelB** [comment]
Hi @oleg-nenashev ,
anything else what you need for merging this request?

/Manuel

**Comment by daniel-beck** [comment]
Looks good to me as well and you addressed @oleg-nenashev's concerns. Thanks for the fix!

**Pull request merged**
