### PR TITLE
Revert "Disable Windows builds and ATH to mitigate the ongoing INFRA issue"

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Reverts jenkinsci/jenkins#4153 . See https://groups.google.com/forum/#!topic/jenkinsci-dev/v9d-XosOp2s

### CODE REVIEW

**Review by olblak — APPROVED** [review]

**Review by jetersen — APPROVED** [review]

**Review by dwnusbaum — APPROVED** [review]

**Review by jglick — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
CC @AbhyudayaSharma @olblak FYI benchmark tests are unstable on windows agents. Could we change the defaul file lenght limitations for them?

```
... 27 more
Suppressed: java.io.IOException: Cannot run program "C:\Jenkins\tools\hudson.model.JDK\jdk11\jdk-11.0.3+7\bin\java.exe": CreateProcess error=206, The filename or extension is too long
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
at org.openjdk.jmh.runner.Runner.doFork(Runner.java:724)
... 29 more
Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long
at java.base/java.lang.ProcessImpl.create(Native Method)
at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:420)
at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:151)
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
... 31 more
Standard Output
```

**Comment by AbhyudayaSharma** [comment]
Windows allows long file path names https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#enable-long-paths-in-windows-10-version-1607-and-later

I don't know if this is compatible with Windows Server 2012 that the agents use right now.

**Review by fcojfernandez — APPROVED** [review]

**Comment by slonopotamus** [comment]
Is there something that prevents this from merge?

**Comment by oleg-nenashev** [comment]
I was waiting for Windows ACI to close it once and for all, but indeed it makes sense to restore the previous status quo

**Comment by oleg-nenashev** [comment]
`There are no nodes with the label ‘docker&&highmem&&Linux’`
Looks like we should fix it on the CI side @olblak

**Comment by oleg-nenashev** [comment]
Created https://issues.jenkins-ci.org/browse/INFRA-2284 for the labeling, will revert the label tweak for now

**Comment by timja** [comment]
Tests are failing on windows:
```
<failed to invoke the VM, caught IOException: Cannot run program "C:\Jenkins\tools\hudson.model.JDK\jdk8\jre\bin\java.exe": CreateProcess error=206, The filename or extension is too long>
```

image

**Comment by timja** [comment]
Closing and re-opening doesn't seem to re-trigger since it's a direct PR to the repo and not a fork

**Comment by olblak** [comment]
> `There are no nodes with the label ‘docker&&highmem&&Linux’`
> Looks like we should fix it on the CI side @olblak

no but "docker&&highmem&&linux" yes

Current Label configuration : `highmem highram docker linux`

**Comment by slonopotamus** [comment]
Could someone please retrigger CI for this PR?

**Comment by timja** [comment]
> Could someone please retrigger CI for this PR?

Can't actually retrigger this as it's a direct branch not a forked PR 😢 
@oleg-nenashev probably needs to push a change, or resubmit as a forked PR...

**Comment by slonopotamus** [comment]
@batmat: that doesn't work, like @timja said a little bit earlier.

Offtop: to be honest, I don't understand why PR reopening is supposed to retrigger CI at all. That's not how other CI systems (Travis, AppVeyor, CircleCI, GitHub Actions, etc) work. Jenkins is the only exception I've heard of. And even if it works this way, why PRs created from different repos behave differently from PRs created from the same repo... And why you can't simply click a "rerun" button on ci.jenkins
org... This doesn't make any sense.

**Comment by oleg-nenashev** [comment]
I plan to work on adding support of "/jenkins rebuild" to ci.jenkins.io, it
is just not a top priority taking the current CI state :(

**Comment by oleg-nenashev** [comment]
It is passing now, so I will integrate it to unblock other changes. The infra is still unstable, and this change will likely cause more outages until Windows ACI is fully available (Cc @olblak @slide ). But we really need windows CI

**Comment by slide** [comment]
I'd love to remove the win2012 agents and move to the win2019 agents, not sure what we need to do there. It should fix the long file path issue

**Comment by jglick** [comment]
@oleg-nenashev

> It is passing now

[Not really](https://ci.jenkins.io/job/Core/job/jenkins/job/master/1609/testReport/), it just looked that way because you filed this from an origin branch which was not being merged with subsequent `master` changes, including some tests that apparently fail consistently on Windows.

**Comment by daniel-beck** [comment]
> origin branch

😫

**Pull request merged**
