### PR TITLE
Remove editorconfig

### PR DESCRIPTION
**Pull request by KostyaSha**
It doesn't support strip trailing space with "modified lines". That ends with many whitespace changes in old code changes.

[Review on Reviewable](https://reviewable.io/reviews/jenkinsci/jenkins/1619)

### CODE REVIEW

**Comment by jglick** [comment]
:+1:, seems pretty useless anyway. (I for one use 4-space indent on all new `*.jelly`, for example.)

**Comment by KostyaSha** [comment]
Idea of this file is good, but it has no many options that maybe enforced for everybody.

**Comment by oleg-nenashev** [comment]
AFAIK we have a coding style for Java only. It makes sense to start from Coding Style guidelines and accept the standard on the governance meeting. 

After that it will be possible to refer a document at least. We can also train Jenkins Pull Request Builder to validate coding styles.

**Comment by oleg-nenashev** [comment]
:+1: for the merge in any case

**Comment by tfennelly** [comment]
:-1: As far as I can remember, you don't need to use this file if you don't want to; just don't configure it in your IDE. Is something forcing you to use it?

Different Jenkins modules are using different indents for different file formats (.jelly, .jsp etc). It's a PITA reconfiguring your IDEA for each in order to be consistent with what's there already. Please don't remove it unless you are somehow being forced to use this file in your IDE.

**Comment by tfennelly** [comment]
@KostyaSha so are you saying that after removing the `trim_trailing_whitespace` setting from `.editorconfig` it still strips the trailing whitespace, but if you remove the file completely it doesn't remove it and everything works fine?

**Comment by KostyaSha** [comment]
@tfennelly you enforcing coding styles that has no agreement and already created issues for people. You shouldn't do such merges without public discussion.

**Comment by KostyaSha** [comment]
Also IDEA works fine with all mentioned formats by default, problems introduced only because of this .editorconfig that has no real good configuration options and support. Feel free to keep this file only for you.

**Comment by tfennelly** [comment]
@KostyaSha That file is not enforcing anything. It only takes effect if you install the plugin in their editor. It may be that that one setting should not be in there, in which case just remove it. This PR is throwing out the baby with the bath water.

IDEA does work fine by default if all modules are using the same indent etc, but they're not, in which case the default settings are a PITA.

**Comment by KostyaSha** [comment]
IDEA works fine with mixed coding style. It supports editorconfig by default, but it wrong to use such configurations for project like jenkins that has mixed coding style. Even any your PRs will have messed space changes.

**Comment by jtnord** [comment]
@oleg-nenashev I don't think we do have a coding style at all (not one that is worth reading) and -1k on enforcing this in the PR builder (there is not one tool that works consistently across all IDEs and produces code that actually looks good to humans in all cases)

What was [documented](https://wiki.jenkins-ci.org/display/JENKINS/contributing#contributing-CodeStyle)  (and even then for core only) was that we "loosley match" an out-of-date standard that has not been updated since 1999 and as such is woefully inadequate when it comes to new features/syntax and what is possible in new IDEs.

:+1: on the merge.

If @tfennelly feels this is a pain then individual formats (that do not reformat unchanged code) can be exported form the IDEs in a way that they can be imported and not reformat unchanged code.

**Comment by tfennelly** [comment]
If the newer versions of IntelliJ have it on by default then I agree that it's not a good idea to have it there anymore. I'm fairly sure that when I added this (nearly 9 months ago), IntelliJ didn't bundle the EditorConfig plugin by default (fairly sure I had to install it - I still use IntelliJ12).

So :+1: 

Sorry for the confusion.

**Comment by KostyaSha** [comment]
Build is broken because i pushed commit into wrong branch and removed it.

**Comment by KostyaSha** [comment]
Merge or we should wait reviewbycloudbees? @stephenc will this work for your whitespace issues?

**Comment by stephenc** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jenkinsci/jenkins/1619)

Reviewed files:
- .editorconfig @ r1

---

:+1:

---

**Comment by KostyaSha** [comment]
https://reviewable.io/reviews/jenkinsci/jenkins/1619 Wow, something new. @stephenc is it used personally by you or it something useful for everybody?

**Comment by stephenc** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jenkinsci/jenkins/1619)



---

It seems free for open source repos... just playing with it for now... seems better at showing the diff since last view though

---

**Pull request merged**
