### PR TITLE
[JENKINS-51603] The proper way to make a parameter optional is to use @DataBoundSetter

### PR DESCRIPTION
**Pull request by jglick**
Amends #2945 and then #3463.

### CODE REVIEW

**Review by ndeloof — APPROVED** [review]
I'm 👍  with this approach but I'm not sure this is an established consensus. I wonder it would make sense to make this explicit with a dedicated JEP on UI DataBinding

**Comment by daniel-beck** [comment]
>  I'm not sure this is an established consensus.

Plenty of prior art in pipeline steps.

**Review by oleg-nenashev — COMMENTED** [review]
It undermines the original approach IMHO. The field has been **intentionally** added to the constructor, because it should not be modified after the object creation. The field should be final ideally, but it was not final due to lack of `readResolve()` there.

@jglick made the thing working well for Databinding, but on the other hand he introduced undocumented setter method which changes the object state without reconfiguring connected agents. So it creates new API, and this API may confuse plugin developers and users.

I am against of using `@DataBoundSetter` APIs for just for UI binding, and I totally do not think we have a consensus on this topic

P.S: Next time please give me a chance to comment in PR before it's merged

**Comment by jglick** [comment]
> it should not be modified after the object creation

So who is going to modify it? Not JEP-201, not the UI.

> changes the object state without reconfiguring connected agents

A launcher just launches an agent. It is not responsible for changing anything about a connected agent. If you want to reconfigure a `Node` you save a change to it, which involves creating a fresh `ComputerLauncher`. In fact it requires creating a fresh `Node`! See for example `Slave.setNumExecutors`. This is a setter for databinding. It is meaningless and illegal to call it on an agent already attached via `Jenkins.addNode`; doing so will not update the actual `Executor` count on the corresponding `Computer`. You need to start from the top level. See the Javadoc on `Computer.setNumExecutors` for details.

> it creates new API, and this API may confuse plugin developers

What is confusing about it? Plenty of classes have `@DataBoundSetter`s. From Java code they are to be used, if at all, immediately after calling the `@DataBoundConstructor`. That is a general rule.

> I am against using `@DataBoundSetter` APIs just for UI binding

Then you need to introduce a new API in Stapler to allow use of a builder pattern or something like that, and update `structs`, `configuration-as-code`, etc. accordingly, plus of course integration tests in `workflow-cps` etc.

> Next time please give me a chance to comment in PR before it's merged

Yes this should not have been merged before giving @oleg-nenashev a chance to comment.

**Comment by jglick** [comment]
> immediately after calling the `@DataBoundConstructor`

(With the exception of `@DataBoundSetter`s directly on top-level objects such as `GlobalConfiguration` or `Item`, which of course would not have a `@DataBoundConstructor`.)

**Comment by ndeloof** [comment]
`DataBoundSetter`s indeed don't enforce at bytecode level that such a method is never invoked _after_ describable object has been created, but stapler databinding does. Just like it does for `@PostConstruct` init methods.

Based on this I only can imagine some hack-ish groovy script to run on master and invoke such a setter by mistake, which sounds like a very hypothetic corner case.

**Pull request merged**
