### PR TITLE
Bump to more recent tip of ATH

### PR DESCRIPTION
**Pull request by batmat**
No JIRA. Internal and test only change.

Going to propose a few successive bumps to try and update to latest `master` (will update the diff link below as I go):
* https://github.com/jenkinsci/acceptance-test-harness/compare/8c3126005c0d5394ed225a5c9f3eab99ab385afe...32a57d160bc4d8b44929ed17e6af013c9da28b1b?expand=1

### Proposed changelog entries

_N/A_

### Submitter checklist

- [ ] ~JIRA issue is well described~
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@olivergondza @jenkinsci/java11-support

### CODE REVIEW

**Comment by batmat** [comment]
I'm almost surprised it stayed green for every builds, too good to be true?  :thinking:

**Review by MRamonLeon — APPROVED** [review]

**Review by alecharp — APPROVED** [review]
looks like the real sha1 so :+1:

**Comment by raul-arabaolaza** [comment]
> I'm almost surprised it stayed green for every builds, too good to be true?  
> 
> **UPDATE: After a double-check, confirming there was an actual test run. I suppose the fact the SmokeTest category has been carefully chosen to not include flaky tests played a role in this. So rather  **

Yeah, quality over quantity was the choice, only reviewed tests that never ever failed in the ATH were added to the core build, that is the reason it has been green. :)

For what I see those tests are still working fine in the ATH builds, even with Java 11 so I am ok with it. Although I have no vote here!

**Comment by batmat** [comment]
Everybody has a _vote_ Raul, so thanks for the feedback and you're definitely entitled to approve or request change on this :).

**Review by raul-arabaolaza — APPROVED** [review]

**Comment by raul-arabaolaza** [comment]
I forgot to approve after my previous comment... :man_facepalming:

**Comment by olivergondza** [comment]
Sorry to be late to the party, just noting ATH has a released containers paired with maven releases that are consumed by other downstream projects that might be a good candidates to be used by core as well.

**Pull request merged**
