### PR TITLE
Test stapler PropertyResourceBundle change

### PR DESCRIPTION
**Pull request by timja**
Just running core tests https://github.com/jenkinsci/stapler/pull/357

### CODE REVIEW

**Comment by basil** [comment]
Note that I only scanned plugins and not core (and core components) in the other PR, so I think we also need to check whether any `.properties` files in core (and core components) are both valid UTF-8 and valid ISO-8859-1, and convert them to using escape sequences if any are found.

**Comment by timja** [comment]
What command / tool did you use to check it?

**Comment by basil** [comment]
```java
@@ -45,6 +47,29 @@ public class DeprecatedUsage {
     }
 
     public void analyze(File pluginFile) throws IOException {
+        try (WarReader warReader = new WarReader(pluginFile, false)) {
+            String fileName = warReader.nextClass();
+            while (fileName != null) {
+                if (fileName.endsWith(".properties")) {
+                    System.err.println();
+                    byte[] contents = IOUtils.toByteArray(warReader.getInputStream());
+                    if (!isEncoded(contents, StandardCharsets.US_ASCII)) {
+                        boolean isUtf8 = isEncoded(contents, StandardCharsets.UTF_8);
+                        boolean isIso88591 = isEncoded(contents, StandardCharsets.ISO_8859_1);
+                        if (isUtf8 && isIso88591) {
+                            System.err.println("Case 1: " + fileName + " is valid UTF-8 and valid ISO-8859-1");
+                        } else if (isUtf8) {
+                            System.err.println("Case 2: " + fileName + " is valid UTF-8 but not valid ISO-8859-1");
+                        } else if (isIso88591) {
+                            System.err.println("Case 3: " + fileName + " is not valid UTF-8 but is valid ISO-8859-1");
+                        } else {
+                            System.err.println("Case 4: " + fileName + " is neither valid ASCII nor valid UTF-8 nor valid ISO-8859-1");
+                        }
+                    }
+                }
+                fileName = warReader.nextClass();
+            }
+        }
         if (IGNORED_PLUGINS.contains(pluginFile.getName())) {
             return;
         }
@@ -52,6 +77,22 @@ public class DeprecatedUsage {
         analyzeWithClassVisitor(pluginFile, classVisitor);
     }
 
+    private static boolean isEncoded(byte[] bytes, Charset charset) {
+        CharsetDecoder decoder = charset.newDecoder();
+        decoder.onMalformedInput(CodingErrorAction.REPORT);
+        decoder.onUnmappableCharacter(CodingErrorAction.REPORT);
+        ByteBuffer buffer = ByteBuffer.wrap(bytes);
+
+        try {
+            decoder.decode(buffer);
+            return true;
+        } catch (CharacterCodingException e) {
+            if (charset.equals(StandardCharsets.US_ASCII)) {
+                Object foo = "bar";
+            }
+            return false;
+        }
+    }
```

**Comment by timja** [comment]
19 files in core.

```
Case 1: core/src/main/resources/hudson/util/NoTempDir/index_nl.properties is valid UTF-8 and valid ISO-8859-1
Case 1: core/src/main/resources/hudson/lifecycle/Messages_it.properties is valid UTF-8 and valid ISO-8859-1
Case 1: core/src/main/resources/hudson/fsp/Messages_de.properties is valid UTF-8 and valid ISO-8859-1
Case 1: core/src/main/resources/hudson/Messages_es.properties is valid UTF-8 and valid ISO-8859-1
Case 1: core/src/main/resources/hudson/model/Messages_de.properties is valid UTF-8 and valid ISO-8859-1
Case 1: core/src/main/resources/hudson/model/AllView/noJob_it.properties is valid UTF-8 and valid ISO-8859-1
Case 1: core/src/main/resources/hudson/model/BooleanParameterDefinition/config_it.properties is valid UTF-8 and valid ISO-8859-1
Case 1: core/src/main/resources/hudson/slaves/DumbSlave/configure-entries_fr.properties is valid UTF-8 and valid ISO-8859-1
Case 1: core/src/main/resources/lib/layout/layout_it.properties is valid UTF-8 and valid ISO-8859-1
Case 1: core/src/main/resources/jenkins/tasks/filters/impl/Messages_pt_BR.properties is valid UTF-8 and valid ISO-8859-1
Case 1: core/src/main/resources/jenkins/security/UpdateSiteWarningsMonitor/message_es.properties is valid UTF-8 and valid ISO-8859-1
Case 1: core/src/main/resources/jenkins/security/apitoken/LegacyApiTokenAdministrativeMonitor/manage_pt_BR.properties is valid UTF-8 and valid ISO-8859-1
Case 1: core/src/main/resources/jenkins/security/s2m/MasterKillSwitchWarning/description_pt_BR.properties is valid UTF-8 and valid ISO-8859-1
Case 1: core/src/main/resources/jenkins/model/RenameAction/action_fr.properties is valid UTF-8 and valid ISO-8859-1
Case 1: core/src/main/resources/jenkins/model/MasterBuildConfiguration/config_fr.properties is valid UTF-8 and valid ISO-8859-1
Case 1: core/src/main/resources/jenkins/model/DefaultSimplePageDecorator/simple-header_fr.properties is valid UTF-8 and valid ISO-8859-1
Case 1: core/src/main/resources/jenkins/slaves/Messages_pt_BR.properties is valid UTF-8 and valid ISO-8859-1
Case 1: core/src/main/resources/jenkins/slaves/systemInfo/Messages_fr.properties is valid UTF-8 and valid ISO-8859-1
Case 1: core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol4/description_pt_BR.properties is valid UTF-8 and valid ISO-8859-1
```

I used: https://gist.github.com/timja/21d655840f5d617df07a271a7db0a48f

**Comment by basil** [comment]
I think they can all be converted to ASCII with `translation-tool.pl`.

**Comment by timja** [comment]
Closing in favour of https://github.com/jenkinsci/jenkins/pull/6553

**Pull request closed without merging**
