### PR TITLE
[JENKINS-40470] - Revert "[FIXED JENKINS-37559] - Fix ProcessTree.java on Solaris with 64-bit JVM"

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Reverts jenkinsci/jenkins#2507 . It is a follow-up to the issue reported by @gozdal. https://issues.jenkins-ci.org/browse/JENKINS-40470.

I am not sure reverting is a right approach. Maybe @csiden could follow-up on the issue and figure out a better fix together with @gozdal

### CODE REVIEW

**Comment by csiden** [comment]
@oleg-nenashev I won't be able to look at the reported issue until the first week of Jan (inconsistent internet on vacation), but I'll check it out as soon as I get back.

**Comment by gozdal** [comment]
@csiden Would be great. I can reproduce it on Solaris 11 Intel every time so I guess it's something easy.

**Comment by tarzanek** [comment]
I can reproduce too and I'd be really happy if LTS would get a fix for this as soon as possible, please please guys ;)

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers WDYT?

**Comment by MarkEWaite** [comment]
If the revert returns it to better behavior for @gozdal, @tarzanek, and @csiden, then the revert seems reasonable to me.

**Comment by csiden** [comment]
I was able to reproduce the issue and #2701 should fix it (issue described in that PR).

**Comment by oleg-nenashev** [comment]
There is a confirmation from a user regarding the fix in #2701, so I think it's better to merge that PR

**Comment by oleg-nenashev** [comment]
Closing since another fix has been integrated towards 2.40

**Pull request closed without merging**
