### PR TITLE
Fix Spanish (es) link translation

### PR DESCRIPTION
**Pull request by MarcoAurelioWM**
Typo/gramar fix.

### CODE REVIEW

**Comment by daniel-beck** [comment]
@recena PTAL

**Review by recena — APPROVED** [review]

**Review by recena — COMMENTED** [review]
Should we escape the special character?

**Comment by daniel-beck** [comment]
@recena Other files in `_es` don't either, such as https://raw.githubusercontent.com/jenkinsci/jenkins/master/core/src/main/resources/lib/hudson/queue_es.properties -- assuming this actually works, no opinion.

**Comment by recena** [comment]
@daniel-beck This was my assumption.

**Comment by recena** [comment]
Go ahead!

**Comment by MarcoAurelioWM** [comment]
FWIW I am a native Spanish speaker and I'm willing to contribute fixing
other translations in Spanish which are wrong, or adding missing ones.
Regards.
-- 
M. A.

**Comment by oleg-nenashev** [comment]
Any translations will be appreciated

**Comment by daniel-beck** [comment]
@MarcoAurelioWM More translation contributions would be great. https://wiki.jenkins.io/display/JENKINS/Internationalization#Internationalization-Whattranslatorsneedtoknow/do should get you started.

**Pull request merged**
