### PR TITLE
Try to avoid test hangs

### PR DESCRIPTION
**Pull request by jglick**
Observed a couple CI builds of older core branches hanging in this test for hours, I suspect because the test was failing to find the expected task but it was doing so in an endless loop that could not respond to `Thread.interrupt` despite the standard 3m timeout in `JenkinsRule`.

Possible that https://github.com/jenkinsci/jenkins-test-harness/pull/67 (integrated in #2959) would have helped.

@reviewbybees

### CODE REVIEW

**Comment by Jimilian** [comment]
Maybe it will be better to directly call `maintenance` method of `Queue` two times? If everything is correct it should move the task to `buildable`, no?

**Comment by jglick** [comment]
Maybe. @varmenise’s code; I am not too interested in editing it heavily, I just want it to stop causing CI outages.

**Comment by jglick** [comment]
CI failure looks random:

    Connect to repo.azure.jenkins.io:443 [repo.azure.jenkins.io/13.68.19.38] failed: Connection refused

**Comment by daniel-beck** [comment]
Windows build passed, but I triggered it again anyway.

**Comment by jglick** [comment]
I am not sure what [this](https://ci.jenkins.io/job/Core/job/jenkins/job/PR-3055/2/testReport/org.jvnet.hudson.test/BuildTriggerTest/testSomething/)

```
junit.framework.AssertionFailedError: test failure
	at junit.framework.Assert.fail(Assert.java:47)
	at org.jvnet.hudson.test.BuildTriggerTest.testSomething(BuildTriggerTest.java:7)
```

is about. There is no such test class or test method that I can see, in this repo or anywhere else. I do not have workspace view permission even if the workspace still exists.

**Comment by jglick** [comment]
`AgentProtocolTest.testShouldNotDisableProtocolsForMigratedInstances` failure, unrelated (#3012).

**Review by oleg-nenashev — APPROVED** [review]
🐝 whatever works

**Comment by jglick** [comment]
> There is no such test class or test method that I can see, in this repo or anywhere else.

FTR this was `src/test/java/org/jvnet/hudson/test/BuildTriggerTest.java` in `test/src/test/resources/hudson/tasks/maven-test-failure.zip`. How it “escaped” to the project test results, I am not sure…

**Comment by jglick** [comment]
Ah, perhaps because we are archiving `**/target/surefire-reports/*.xml` when we should be doing only `*/target/surefire-reports/*.xml`.

**Pull request merged**
