### PR TITLE
[WiP][JENKINS-19154] Publish test results in real time

### PR DESCRIPTION
**Pull request by olivergondza**
[JENKINS-19154](https://issues.jenkins-ci.org/browse/JENKINS-19154)
A draft to support discussion at [dev-list](https://groups.google.com/forum/?fromgroups#!msg/jenkinsci-dev/M9pt1vvdrCo/aFPQkMj2KIUJ)

### CODE REVIEW

**Comment by firsthour** [comment]
Have there been any further updates on this?

**Comment by olivergondza** [comment]
@firsthour, I am afraid not.

**Comment by jglick** [comment]
Superseded by https://wiki.jenkins.io/display/JENKINS/JUnit+Realtime+Test+Reporter+Plugin I suppose.

**Comment by oleg-nenashev** [comment]
@olivergondza I want to remove the branch. Are you fine with it?

**Pull request closed without merging**
