### PR TITLE
JENKINS-29059: Display cron run times after warnings if warnings occur.

### PR DESCRIPTION
**Pull request by ChrisCanCompute**
If there is a warning for cron timings, display the warning, then ";" then the message that would have turned up.
Allows users to ignore the warnings if they want (but still get the help).

### CODE REVIEW

**Comment by olivergondza** [comment]
There already is a way to display multiple validations at once: `FormValidation#aggregate`.

**Comment by ChrisA89** [comment]
That's much nicer. I've updated to use that method. Thanks!

**Comment by olivergondza** [comment]
:+1:

**Comment by oleg-nenashev** [comment]
:bee:

**Pull request merged**
