### PR TITLE
[JENKINS-59684] Support "alert-info" for admin monitor in popup

### PR DESCRIPTION
**Pull request by Wadeck**
- Add support for `alert-info` and `alert-danger` also in the popup for admin monitor.
- Also support the `p` tags in the message, discovered with the CSRF monitor message being only "half-styled".

<details>

<summary>Screenshots</summary>

#### Full page mode (ok before and after)
full_page_ok

#### Before
popup_ko

#### After
Screenshot_2019-10-07_114211_001

#### Before
Screenshot_2019-10-07_114815_001

#### After
Screenshot_2019-10-07_114758_001

#### Before
Screenshot_2019-10-07_121622_001
#### After
Screenshot_2019-10-07_121609_001

</details>

See [JENKINS-59684](https://issues.jenkins-ci.org/browse/JENKINS-59684).

### Proposed changelog entries

* Administrative monitors providing information message are now correctly styled in the popup mode

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [n/a] Appropriate autotests or explanation to why this change has no tests
- [n/a] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@recena @daniel-beck

### CODE REVIEW

**Review by res0nance — APPROVED** [review]

**Review by jvz — APPROVED** [review]
Thanks for fixing this!

**Comment by daniel-beck** [comment]
Why does this edit `style.css` when #2857 worked on `bootstrap.css` etc.?

**Comment by Wadeck** [comment]
The `alert-warning` that was applied before comes from #1847.

The `bootstrap.css` is applied only to `manage.jelly`, don't ask me why. https://github.com/Wadeck/jenkins/blob/4d65572c6db9099ebcf8d2222159c069996670f9/core/src/main/resources/jenkins/model/Jenkins/manage.jelly#L33 and #2857

**Review by oleg-nenashev — APPROVED** [review]
💯 , thanks!
I was thinking about delivering upgrade guide heads-up through update centers, and this is a great foundation improvement for it

I plan to merge it tomorrow if no negative feedback

**Review by daniel-beck — APPROVED** [review]

**Pull request merged**
