### PR TITLE
Migrate some tests from `HudsonTestCase` to `JenkinsRule`

### PR DESCRIPTION
**Pull request by basil**
`HudsonTestCase` was deprecated in favor of `JenkinsRule` on June 12, 2013, yet 21 tests in this repository continue to use it. This PR does not migrate all of them, but it does take care of 12 pieces of low-hanging fruit.

### CODE REVIEW

**Review by jvz — APPROVED** [review]
Very nice! Was sort of annoyed by all the legacy tests, so thanks 😊

**Comment by basil** [comment]
I needed a new PR build anyway, so I added a trivial fix to `HelpLinkTest`. It's not related to this PR, but I didn't think it was worth its own PR either.

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Review by oleg-nenashev — APPROVED** [review]
Thanks for the cleanup!

**Review by StefanSpieker — APPROVED** [review]

**Pull request merged**
