### PR TITLE
[JENKINS-6798] Redirect on HTTP 502, 503, 504

### PR DESCRIPTION
**Pull request by Vlatombe**
See [JENKINS-6798](https://issues.jenkins-ci.org/browse/JENKINS-6798).

### Proposed changelog entries

* Do not reload too early when Jenkins is behind a reverse proxy and is restarting.

### Submitter checklist

- [X] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### CODE REVIEW

**Review by jglick — APPROVED** [review]
Looks right. Did you manage to test it, for example against a `StatefulSet` + nginx-ingress?

**Comment by Vlatombe** [comment]
Yes, I checked the behaviour with the jenkins helm chart + nginx-ingress controller

**Review by res0nance — APPROVED** [review]

**Review by timja — APPROVED** [review]

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
Would it be safer to also set the upper bound for the range?

**Comment by Vlatombe** [comment]
@oleg-nenashev added upper bounds

**Review by oleg-nenashev — APPROVED** [review]
I plan to merge it tomorrow if no negative feedback

**Pull request merged**
