### PR TITLE
Adds support of sessionId for External-Job-Monitor

### PR DESCRIPTION
**Pull request by Abhishekkr3003**
I was using the External-Job-Monitor plugin and following this [Doc](https://plugins.jenkins.io/external-monitor-job/#plugin-content-monitoring-an-execution), but I was getting 403 responses like this:

Screenshot 2024-01-03 at 10 07 05 PM

On looking into the code, found a bug:
GET request to fetch `crumb` before POST request for `postBuildResult` has an extra `'`, due to which GET request was giving a non-2XX response, and crumb fields were not getting enriched.

Furthermore, I was still getting 403 responses, and then I found this [change](https://www.jenkins.io/doc/upgrade-guide/2.176/#SECURITY-626). which mentioned:
```
CSRF tokens (crumbs) are now only valid for the web session
```
So, to make things work, I added the support for `sessionId` returned in the GET call (to fetch crumb) to be sent in the POST call for `postBuildResult`.

And then getting the expected results:

image

image

To summarize, this PR has the following two changes:
1. Fixes bug in GET call of crumb
2. Adds sessionId support

### Testing done

Testing is done as mentioned above.

### Proposed changelog entries

- Support Session ID for External Job Monitor to prevent HTTP 503 response.

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Comment by mawinter69** [comment]
According to https://issues.jenkins.io/browse/JENKINS-70684 this class is probably obsolete. Maybe the documentation needs to be updated in the plugin to no longer point to using things from core

**Comment by Abhishekkr3003** [comment]
@mawinter69 I think SetExternalBuildResultCommand requires us to store the logs and send them via SSH to the Jenkins Host as mentioned in the [doc](https://plugins.jenkins.io/external-monitor-job/#plugin-content-submit-a-run-per-cli). But Hudon Main wraps our command, keeps the log, and sends via HTTP to Jenkins, which gives quite a bit of flexibility while using the External-Job-Monitor plugin. So, keeping this class or at least this functionality is better.

**Review by Kevin-CB — APPROVED** [review]
I tested your PR locally, it looks fine from a security perspective!

**Review by NotMyFault — APPROVED** [review]

**Comment by NotMyFault** [comment]
/label ready-for-merge

---

This PR is now ready for merge. We will merge it after ~24 hours if there is no negative feedback.
Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process.
Thanks!

**Comment by jglick** [comment]
> Hudon Main wraps our command, keeps the log, and sends via HTTP to Jenkins

Fine but as mentioned in Jira please instead move all of this functionality into some utility in the plugin, so we can delete the class from core. It does not belong here and should not be touched.

**Comment by daniel-beck** [comment]
@jglick It looks like you may have an opinion on https://github.com/jenkinsci/jenkins/pull/9023

**Comment by jglick** [comment]
Indeed. BTW I think all the logic here to retrieve a crumb ought to be deleted anyway, as it should only be needed if you are using a password rather than an API token.

**Pull request merged**
