### PR TITLE
[FIX JENKINS-34093] Make logger field private

### PR DESCRIPTION
**Pull request by daniel-beck**

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
:+1:

**Comment by batmat** [comment]
I was going to say this might be slightly problematic if it was used by plugins, but after looking at `git blame` as it was only introduced by @recena in https://github.com/jenkinsci/jenkins/commit/eb78face60e2dc76c9beafeeb6f846341843409c less than a month ago I'm also :+1:

**Comment by recena** [comment]
👍

**Comment by daniel-beck** [comment]
@batmat Also, not public.

**Comment by daniel-beck** [comment]
@oleg-nenashev Why did you label this 2.0? I filed this against master.

**Pull request merged**
