### PR TITLE
Merged security test back to test class

### PR DESCRIPTION
**Pull request by StefanSpieker**
Merged security test back to test class

### Proposed changelog entries

* Internal: N/A

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by daniel-beck** [comment]
Thanks for taking this on!

Is this deliberately just one of the many such tests? Or perhaps you could look at the other `WhateverSEC12345Test` classes and try merging them back into `WhateverTest`?

I wonder whether we should make this a regular post-release cleanup task. Pinging @Wadeck for his thoughts.

**Review by timja — APPROVED** [review]

**Comment by StefanSpieker** [comment]
I just wanted to be sure that this is really intended, before creating a big MR which is not in the interest of the team. I guess I will create another one to merge the rest.

**Comment by daniel-beck** [comment]
> I just wanted to be sure that this is really intended, before creating a big MR which is not in the interest of the team.

I'm definitely in favor of this being done, thanks for getting this started!

For context, these separate classes are mostly an artifact of how we develop security fixes; it's definitely desired for these tests to end up migrated into the regular tests. I expect you'll find TODO comments like https://github.com/jenkinsci/jenkins/blob/a2332a6f1e720e1c41ef101a2e35bc24dac5294f/test/src/test/java/jenkins/model/JenkinsLocationConfigurationSEC1471Test.java#L32 in most or even all such classes.

**Comment by Wadeck** [comment]
> I wonder whether we should make this a regular post-release cleanup task

Totally, 👍

**Comment by jglick** [comment]
> an artifact of how we develop security fixes

Briefly: we want to avoid merge conflicts from unrelated changes to the same test class (such as `import`s). A new file is easy to merge.

**Review by oleg-nenashev — APPROVED** [review]
LGTM. There is no particular value in keeping tests separate after a security release. Personally I have no strong opinion about moving tests, IMHO time could be better spent on increasing test coverage and fixing known defects and production code quality, but I am perfectly fine if someone is willing to contribute to the test suite housekeeping,

Thanks a lot @StefanSpieker !

**Comment by oleg-nenashev** [comment]
We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Pull request merged**
