### PR TITLE
[FIXED JENKINS-44764, JENKINS-44894] - Update Extras Executable War from 1.34 to 1.35.1

### PR DESCRIPTION
**Pull request by oleg-nenashev**
# Description

* [JENKINS-44764](https://issues.jenkins-ci.org/browse/JENKINS-44764) - Executable WAR now checks for Java 8 instead of Java 7 before starting Jenkins ([PR #8](https://github.com/jenkinsci/extras-executable-war/pull/8)).
* [JENKINS-44894](https://issues.jenkins-ci.org/browse/JENKINS-44894) - Add system properties for managing the Jetty Session ID cookie name ([PR #9](https://github.com/jenkinsci/extras-executable-war/pull/9)).
  * Now it is possible to disable random cookie name generation or to specify a custom one
  * These options can be used to workaround issues like [JENKINS-25046](https://issues.jenkins-ci.org/browse/JENKINS-25046)
  * The options are documented [here](https://github.com/jenkinsci/extras-executable-war#jetty-session-ids)

### Changelog entries

Proposed changelog entries:

* Entry 1: Bug, JENKINS-44764, Executable WAR now checks for Java 8 instead of Java 7 before starting Jenkins
* Entry 2: RFE (or bug?), JENKINS-44894, Add system properties for managing the Jetty Session ID cookie name
  * Link 1: Workaround for JENKINS-25046, https://issues.jenkins-ci.org/browse/JENKINS-25046
  * Link 2: Usage guide, https://github.com/jenkinsci/extras-executable-war#jetty-session-ids
* ...

### Submitter checklist

- [x] JIRA issue is well described
- [x] Link to JIRA ticket in description, if appropriate
- [x] Appropriate autotests or explanation to why this change has no tests

### Desired reviewers

@daniel-beck @reviewbybees

### CODE REVIEW

**Comment by daniel-beck** [comment]
Would have been nice to have a backportable `executable-war` just for the Java 8 message.

**Comment by daniel-beck** [comment]
Reviewer diff: https://github.com/jenkinsci/extras-executable-war/compare/executable-war-1.34...executable-war-1.35?w=1

**Comment by daniel-beck** [comment]
Typo in `disableCustomSeesionIdCookieName` should probably not make it into Jenkins.

**Comment by oleg-nenashev** [comment]
Yes, I need to fix it and re-release. 
Code reviews cannot catch all my typos :(

**Comment by oleg-nenashev** [comment]
Ne full diff: https://github.com/jenkinsci/extras-executable-war/compare/executable-war-1.34...executable-war-1.35.1?w=1

@daniel-beck 

> Would have been nice to have a backportable executable-war just for the Java 8 message.

It is backportable. In such case we would add new system properties to the LTS baseline, but the documentation explicitly says that all properties are "experimental" and may change

**Comment by daniel-beck** [comment]
Diff from previous diff: https://github.com/jenkinsci/extras-executable-war/compare/executable-war-1.35...executable-war-1.35.1?w=1

It's really just the typo fix.

**Review by daniel-beck — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
@reviewbybees done since @daniel-beck works for CloudBees. I also got non-CloudBees votes in the downstream PRs, so I am going to merge it towards the next weekly

**Pull request merged**
