### PR TITLE
[JENKINS-68380] Make CodeMirror textareas resizable

### PR DESCRIPTION
**Pull request by janfaracik**
See [JENKINS-68380](https://issues.jenkins.io/browse/JENKINS-68380)

--

image

This wasn't _fun_. Essentially CodeMirror doesn't behave particularly nicely with the browser native `resize` CSS attribute, it works in Safari but not in Chrome etc. The solution that I've got is to create a small resizer element that looks very similar to the native browser one and hook that up with CodeMirror's resize events.

--

**How to reproduce**

- Go to Manage Jenkins -> Script console
- You can now resize the console ✨ 

--

### Proposed changelog entries

* Script console is now resizable again

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@NotMyFault @alecharp 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/6620"></a>

### CODE REVIEW

**Review by alecharp — APPROVED** [review]
just tested with `$JENKINS_URL/script` and it's working properly now. Thanks!

**Review by basil — COMMENTED** [review]
> This wasn't _fun_.

Diving into decade-old technical debt rarely is. But hopefully the satisfaction of adoption by a large user base helps to offset the emotional burden. It does for me.

> Essentially CodeMirror doesn't behave particularly nicely with the browser native resize CSS attribute, it works in Safari but not in Chrome etc.

The [Five Whys](https://en.wikipedia.org/wiki/Five_whys) iterative interrogative technique is drilled into me at this point, so my first question when reading the above is: "Why?" That is also my second, third, fourth, and fifth question. :smile:

> The solution that I've got is to create a small resizer element that looks very similar to the native browser one and hook that up with CodeMirror's resize events.

But is this the ideal long-term solution or a short-term workaround? Without an evaluation of the root cause of the problem, it is difficult for me to determine whether this solution addresses the root cause of the problem or just the symptoms. But my gut feeling is that it merely addresses the symptoms and that it introduces some additional long-term burden in the form of maintaining a custom widget that "looks very similar to the native browser one".

(Warning: Another software engineering mini-lecture here.) Are workarounds sometimes justified? Sure! I introduced several workarounds into Jenkins core and plugins myself recently, along with corresponding justifications. This is a reality in both proprietary and open-source software. Are workarounds always justified? No, and in many cases they cause debilitating technical debt in the long term. So how does one strike the optimal balance? Here is the best strategy I have found to date.

- Determine the root cause of the problem with Five Whys.
- Sketch out the design of an ideal long-term solution, but do not implement it.
- Implement a short-term workaround.
- Find the midpoint between the short-term workaround and the long-term solution that gives the best bang for the buck: something more robust than the short-term workaround, but not as expensive as the ideal long-term solution.
- Implement the midpoint.

The above strategy usually takes slightly more time than just implementing the short-term workaround, but it usually pays dividends in the long term by not precluding (or precluding less) the implementation of the long-term solution. Critically, I find that I rarely discover the midpoint until (ironically) _after_ I have designed the long-term solution. To be fully transparent, I am trying to push to you discover and implement the midpoint in this PR. I do not know what it is, but I promise to help you get there if you are willing to go through the Five Whys root-cause analysis exercise together.

**Comment by timja** [comment]
Upstream issue: https://github.com/codemirror/CodeMirror/issues/850

there’s a library you can add to do it as well, any thoughts on which solution is better @janfaracik ?

**Comment by timja** [comment]
and see https://github.com/codemirror/codemirror5/pull/6280/

**Comment by janfaracik** [comment]
Hey. Cheers for the comments @basil and @timja. 

Ideally we’d just use the native `resize: vertical;` CSS attribute to enable the CodeMirror textarea to be resizable, this is what we do for other textareas on Jenkins and is what I’d class as the ideal/best solution. 

This unfortunately doesn’t work due to how CodeMirror handles resizing, and [the developers don’t appear to want to change that](https://github.com/codemirror/codemirror5/pull/6280). This might change in a future release of CodeMirror (it’s currently [undergoing a complete rewrite](https://codemirror.net/)) but that’d require updating our already very old instance of CodeMirror which would be a pain.

Initials thoughts for a workaround to this would be to apply the attribute to an outer container for the `textarea`, track the size changed event for that and then apply that new size to its internal CodeMirror element. Suitable candidates would be the containers `.CodeMirror` and `.CodeMirror-scroll`, however this doesn’t work due to browser differences, e.g. one container resize might work in Chrome but it doesn’t work in Safari, and vice versa.

As Tim mentioned there exists [an NPM package](https://github.com/Sphinxxxx/cm-resize) that can add resizing support but IMO the code required to set up the resizing would equal the existing solution in length, and we’d then have an additional package we’d have to use from NPM which I’ve been trying to avoid adding to.

The solution in place in this PR is rather minimal and from a user’s perspective behaves as expected/consistently with other areas of Jenkins, although happy to go with the package route if that’s preferred.

---

Off topic, I do think it’d be worth looking at the new version of CodeMirror (6) and seeing how easy it’d be to implement in Jenkins as it brings a slurry of new enhancements which would be beneficial, e.g. being more accessible and having touchscreen support.

**Review by timja — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]

**Comment by janfaracik** [comment]
> > This unfortunately doesn’t work due to how CodeMirror handles resizing, and [the developers don’t appear to want to change that](https://github.com/codemirror/codemirror5/pull/6280).
> 
> That is a strong argument for why the fix should be in Jenkins rather than upstream.
> 
> > As Tim mentioned there exists [an NPM package](https://github.com/Sphinxxxx/cm-resize) that can add resizing support but IMO the code required to set up the resizing would equal the existing solution in length, and we’d then have an additional package we’d have to use from NPM which I’ve been trying to avoid adding to.
> 
> Not only that, but that package also hasn't been updated since 2018, so introducing a new dependency on it seems like more of a liability than a net benefit.
> 
> I noticed that you commented negatively only on the fact that https://github.com/Sphinxxxx/cm-resize is a third-party package without commenting on the advantages or disadvantages of its design and implementation. I can't understand, let alone judge the merits of, the design and implementation of https://github.com/Sphinxxxx/cm-resize/blob/7777d8e7bbf8842acf5a69bfc893c3806d76f682/src/cm-resize.js vs the design and implementation of this PR. If we think the approach taken in https://github.com/Sphinxxxx/cm-resize/blob/7777d8e7bbf8842acf5a69bfc893c3806d76f682/src/cm-resize.js is more maintainable in the long term, perhaps we could incorporate elements of its implementation into the implementation in this PR. If we think the approach taken in this PR is more maintainable in the long term, then great! If the two differ in implementation but are equivalent in maintainability, I see no need to make any further changes to this PR.

👍 

Had a read through their (`cm-resize`) implementation and I think the main benefit to our implementation is that it isn't reliant on any other libraries. They're using the `drag-tracker` library to handle dragging whereas we're just using plain ordinary JS, if we went for their approach it'd be another dependency we'd have to import and rely on.

**Comment by basil** [comment]
I concur. https://github.com/Sphinxxxx/drag-tracker hasn't been updated since 2018 and therefore fails one of my tests ("is it actively maintained?") when considering whether to introduce a new dependency.

**Review by basil — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by daniel-beck** [comment]
Caused [JENKINS-69320](https://issues.jenkins.io/browse/JENKINS-69320).

**Pull request merged**
