### PR TITLE
[JENKINS-69637] Fix ClassCastException when param list is empty

### PR DESCRIPTION
**Pull request by loganmzz**
See [JENKINS-69637](https://issues.jenkins.io/browse/JENKINS-69637).

Not sure if empty list should be considered as non-parameterized. Most code seems to handle null or empty list but there are exceptions:

* `jenkins.model.ParameterizedJobMixIn#doBuild`
* `jenkins.model.ParameterizedJobMixIn#doBuildWithParameters`
* `jenkins.model.ParameterizedJobMixIn#isParameterized`

### Proposed changelog entries

Fix ClassCastException when trying to build a Job whose parameter list is empty

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  - Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate.
- [x] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")` if applicable.
- [x] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content-Security-Policy directives (see [documentation on jenkins.io](https://www.jenkins.io/doc/developer/security/csp/)).
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@basil 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7140"></a>

### CODE REVIEW

**Comment by loganmzz** [comment]
Windows build has failed, but I dont know why. It lasted for 6 hours !

**Comment by timja** [comment]
> Windows build has failed, but I dont know why. It lasted for 6 hours !

Our windows builds are less reliable than linux, although some work is going on to stabilise the whole test suite. I've merged in master which will re-trigger it for you

**Comment by loganmzz** [comment]
No one to review ? :(

**Review by NotMyFault — APPROVED** [review]

**Review by timja — APPROVED** [review]
Thanks! Apologies for the delay

**Comment by loganmzz** [comment]
> Thanks! Apologies for the delay

Don't worry, it happpens. I just wanna be sure it won't be forgotten.

**Review by basil — COMMENTED** [review]
Have you tested this PR in production and verified it resolves the error you were experiencing in [JENKINS-69637](https://issues.jenkins.io/browse/JENKINS-69637)? I don't see how this fix could be effective, because the problem in JENKINS-69637 was on line 151 of `ParametersDefinitionProperty`, when casting the `Object` to `JsonObject`. In the reported bug, the `Object` was actually a `JSONNull` and could not be cast to `JsonObject`. Your PR does nothing to address this.

**Comment by loganmzz** [comment]
> Have you tested this PR in production and verified it resolves the error you were experiencing in [JENKINS-69637](https://issues.jenkins.io/browse/JENKINS-69637)? I don't see how this fix could be effective, because the problem in JENKINS-69637 was on line 151 of `ParametersDefinitionProperty`, when casting the `Object` to `JsonObject`. In the reported bug, the `Object` was actually a `JSONNull` and could not be cast to `JsonObject`. Your PR does nothing to address this.

1. I haven't tested this in real world because:
   1. I don't even know how to do it (if you have some process to easily test it without waiting for 3 hours build, I will be happy to do it !)
   2. I relied on test framework which at least from developer perspective it acts as a web client (and from my memory was producing same effects before my fix).
1. I suspect `JSONArray.fromObject(null)` to return a singleton list containing a `JSONNull`, which is causes the observed behavior.

Note: I will check points `1.ii` and `2`. And waiting for instructions about `1.i`

**Comment by basil** [comment]
To test the change, just build the WAR file with `mvn clean verify -DskipTests` (or download the incremental build from the CI job in this PR) and then run `java -jar jenkins.war`. And yes I also suspect `JSONArray.fromObject(null)` is returning a singleton list containing a `JSONNull`. The problem is that the existing code tries to unconditionally cast that type to `JsonObject`. I would have expected your fix to do an `instanceof` check and skip the cast if the object is of type `JSONNull`.

**Comment by basil** [comment]
I think I understand your earlier comment now: by not passing `null` to `JSONArray#fromObject`, we avoid the problematic situation to begin with. I ran the test from your latest revision without the changes to `core/src/main`, and it reproduced the exact stack trace from the bug, and the test passes with the changes to `core/src/main`, so there is no need for additional testing. From my perspective this is ready for merge.

**Pull request merged**
