### PR TITLE
[JENKINS-72189] fix drag&drop handle for existing repeatables

### PR DESCRIPTION
**Pull request by mawinter69**
The drag&drop handle for `<f:repeatable header="Header">` is missing for existing entries when opening a configure page and the styling of the header is wrong.
Newly added entries do have the handle and can be moved.

Before:
image

After:
image

See [JENKINS-72189](https://issues.jenkins.io/browse/JENKINS-72189).

### Testing done
Manual testing as described in the Jira

### Proposed changelog entries

- JENKINS-72189, fix drag&drop handle for existing repeatables

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [x] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Comment by NotMyFault** [comment]
ATH failed in https://github.com/jenkinsci/acceptance-test-harness/pull/1393

**Comment by mawinter69** [comment]
The test failures don't seem to be related to this change. They look more as being caused by the new version of the folder plugin

**Review by NotMyFault — APPROVED** [review]
Thanks!

**Comment by mawinter69** [comment]
Would it be possible to get this in the next LTS @MarkEWaite

**Comment by MarkEWaite** [comment]
> Would it be possible to get this in the next LTS @MarkEWaite

Thanks for asking @mawinter69 .  It becomes eligible for backporting after it has been included in a weekly release.  If it can be included in the 2.430 release on Tuesday, 31 Oct 2023, then it could be included in the 2.426.1 release candidate that will be made available Wednesday, 1 Nov 2023.

**Review by timja — APPROVED** [review]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Pull request merged**
