### PR TITLE
remove restriction to be able to override the method in subclasses

### PR DESCRIPTION
**Pull request by varmenise**
Removing the restriction otherwise https://issues.jenkins-ci.org/browse/JENKINS-36537 fix it's unusable

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
<code>@since</code> needs to be adjusted then

**Comment by oleg-nenashev** [comment]
🐝

**Comment by amuniz** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Pull request merged**
