### PR TITLE
[JENKINS-65928-2] Job trend page use previous icon color for trend graph

### PR DESCRIPTION
**Pull request by benebsiny**
See [JENKINS-65928](https://issues.jenkins-ci.org/browse/JENKINS-65928).

This issue is reopen because the colors in trend graph were not changed to the new colors which match the svg icons.

I add new enum items in the color palette for the color shown in the trend graph. The original colors defined in the enum were not  modified because other components might also use those colors.

Screenshot_20211025_193054

### Proposed changelog entries

* Use new color in trend graph.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by oleg-nenashev — COMMENTED** [review]
Needs more feedback from UX SIG, especially @uhafner @timja @fqueiruga. New colors seem to be very contrast for a chart, but at the same time it is a new palette indeed

**Review by uhafner — CHANGES_REQUESTED** [review]
I am fine with changing the colors to make them the same as the build icon colors, this will be a quick win solution.

I think a more general solution would make more sense though (out of scope for this PR). Additionally, the build trend chart should be replaced by a modern ECharts chart in the future (out of scope for this PR).

**Comment by alecharp** [comment]
@oleg-nenashev you requested your self to review this PR, do you still have the time for it? 
my opinion on this is that it would be nice to have the same colors used on all graphs. Until we change the way we generate those, this seems good enough in accept this PR.

**Comment by timja** [comment]
can you fix the conflicts please

**Review by uhafner — APPROVED** [review]

**Comment by uhafner** [comment]
Seems there is a meaningless test around that checks the color by value: 
https://github.com/jenkinsci/jenkins/blob/e3f8bc052d6065d3fcf6430f4c7c029c1fd25e54/core/src/test/java/hudson/model/BallColorTest.java#L12-L15

This test can be deleted, it does not test anything.

**Review by NotMyFault — APPROVED** [review]
Looks nice to have the trend graph colors aligned with the build status colors.

**Comment by benebsiny** [comment]
@uhafner The test is removed.

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Pull request merged**
