### PR TITLE
Save after calling setSecurityRealm or setAuthorizationStrategy

### PR DESCRIPTION
**Pull request by jglick**
Very confusing to have a `RestartableJenkinsRule` test which sets up security, only to see no trace of that in the next session, because you forgot to `rr.j.jenkins.save()`.

`GlobalSecurityConfiguration.doConfigure` of course already `save`s, in a `BulkChange`, so it should be unaffected; this is for isolated API calls.

@reviewbybees

### CODE REVIEW

**Review by oleg-nenashev — COMMENTED** [review]
Generally it is preferable, but the original behavior is a common approach in Jenkins.

I think we need to ensure that all `BulkOperation`s are in place at least, just to prevent double save operations

**Comment by jglick** [comment]
> I think we need to ensure that all `BulkOperation`s are in place

`BulkChange` you mean? As noted in the PR description, `GlobalSecurityConfiguration.doConfigure` does this already.

**Comment by jglick** [comment]
Test failures indicate tests which try to set a non-`Serializable` object, typically an inner class. Those need to be fixed.

**Review by daniel-beck — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
I would prefer explicit failure instead of `saveQuietly()`, but generally LGTM 🐝

**Comment by jglick** [comment]
> I would prefer explicit failure instead of `saveQuietly()`

Too late—the setters do not throw `IOException`.

**Comment by jglick** [comment]
Hmm, CI builders failed with

```
java.lang.AssertionError: 

Expected: <true>
     but: was <false>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at hudson.cli.ConnectNodeCommandTest.connectNodeShouldSucceedWithForce(ConnectNodeCommandTest.java:114)
```

though I cannot reproduce that locally or find any explanation related to this PR.

(There was one case where `CLICommandInvoker.authorizedTo` caused problems, but only because it was overwriting `$JENKINS_HOME/config.xml`, which AFAICT should not matter here.)

**Comment by jglick** [comment]
Wait, it fails if you run the whole test suite, but not if you run just this test case. Looking…

**Comment by oleg-nenashev** [comment]
:bee:

**Comment by jglick** [comment]
Presumably

```
java.lang.AssertionError: deletion stopped
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at hudson.UtilTest.testDeleteRecursive_onWindows(UtilTest.java:453)
```

is not related.

**Pull request merged**
