### PR TITLE
Bump to latest 1.50 parent pom release

### PR DESCRIPTION
**Pull request by batmat**
As 1.51 is upcoming (esp. to include the bump to extra-enforcer-rules to support JDK 11), the main goal here is to get an intermediate release with 1.50.
This way in case something goes wrong, it will be hopefully easier and quicker to figure where this comes from.

No JIRA, small enough.
Diff is https://github.com/jenkinsci/pom/compare/jenkins-1.49...jenkins-1.50 (contains only the SUREFIRE-1588 workaround)

### Proposed changelog entries

* `Internal:` update to 1.50 parent pom to get the SUREFIRE-1588 workaround.

### Submitter checklist

~~- [ ] JIRA issue is well described~~
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@jglick given changes in 1.50 all come from him.

### CODE REVIEW

**Comment by batmat** [comment]
@daniel-beck @oleg-nenashev when/if the PR build is successful, I think it would be good to merge this before Monday so it gets in the next release.

I'm aware it's very late, so I'm fine if you think this is too dangerous. 

I explained in the description that my intent here would be to get an intermediate release before we bum to upcoming 1.51, which I think would be better in case we have issues to diagnose.

Thanks a lot

**Review by jglick — APPROVED** [review]

**Comment by batmat** [comment]
Tests failures look unrelated and also happened on random PRs
image

On `master`:
image

`poorManPerformanceTestBed` I've no idea why it could fail because of this update. I assume this is unrelated. 

Did someone see these failing elsewhere recently maybe?

**Comment by jglick** [comment]
`testDeleteRecursive_onWindows` does in fact flake frequently. I would suggest `@Ignore`ing it. `poorManPerformanceTestBed` does not ring a bell, but just from the name I would also suggest `@Ignore`ing it.

**Comment by batmat** [comment]
BTW, last PR rebuild only fails on the `testDeleteRecursive_onWindows`, which I'm proposing to ignore in #3787

image

**Comment by batmat** [comment]
Facepalm, now the unrelated failure comes from a new test added for security-904 iiuc. 

Groundhog day

**Comment by batmat** [comment]
FTR 
screenshot_20181206-000529__01

**Comment by batmat** [comment]
Unrelated test failures are a mess. I triple-checked and last rebuild failed also on 
image

Exact same failure as on `master` currently, so I'm going to go ahead and merge this later today I think if nobody objects.

Got approval from Jesse (wouldn't obviously merge with 0 approval), and the upstream change is pretty limited anyway. I'll handle fallout if I missed something obvious even if seeming unlikely.

**Pull request merged**
