### PR TITLE
[JENKINS-53462] Stop using deprecated submit events

### PR DESCRIPTION
**Pull request by daniel-beck**
See [JENKINS-53462](https://issues.jenkins-ci.org/browse/JENKINS-53462).

Previously: #4246 #3761 #3760 #3689

In some limited manual testing in Firefox and Chrome, this seems to work.

### Proposed changelog entries

* Stop using deprecated untrusted submit events on modern browsers for compatibility with future Firefox releases.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@thomasgl-orange @halkeye 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
Tested it with Jenkins PR tester on Chrome and Edge. Seems to be working fine.

We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Review by thomasgl-orange — APPROVED** [review]
Tested with:
- FF 87.0 with `dom.forms.submit.trusted_event_only=false`
- FF 87.0 with `dom.forms.submit.trusted_event_only=true`
- FF 66.0.3

It looks good, forms are always submitted once and only once (with some usecases involving files parameters, some none).

Whereas plain 2.288 without this PR is very broken on FF 87.0 with `dom.forms.submit.trusted_event_only=true`, most forms are then impossible to submit.

PS: now also tested a bit from some Windows 10 navigators (IE 11.1790.17763.0 and Edge 44.17763.831.0), all good.

**Comment by timja** [comment]
_May have caused a regression in pipeline input step_ (or at least in the tests)

See https://github.com/jenkinsci/bom/pull/511#issuecomment-835843160, picked up in PCT testing

**Comment by halkeye** [comment]
if its breaking tests, what version of a browser engine are the tests using? I know we had issues in ... that repo that generates all the install lists that jenkins uses (like groovy or perl or whatever). The browser engine was so old it didn't support any of the basic javascript on some sites.

**Comment by res0nance** [comment]
> _May have caused a regression in pipeline input step_ (or at least in the tests)
> 
> See [jenkinsci/bom#511 (comment)](https://github.com/jenkinsci/bom/pull/511#issuecomment-835843160), picked up in PCT testing

Its also breaking `ssh-slaves`.
I tested pipeline-input-step manually and it seems to work on `2.289` so I think its just the tests.

**Comment by daniel-beck** [comment]
> The browser engine was so old it didn't support any of the basic javascript on some sites.

Also https://groups.google.com/g/jenkinsci-dev/c/Wj3YHoKRDSM/m/r6NbQG8oAgAJ as another indicator that we're either on an outdated HTMLUnit, or that there's just no support for modern web stuff.

Although my change here should be backward compatible with old browsers; assuming HTMLUnit is just an "old browser" I would expect it to continue working. Perhaps there's a legitimate problem here?

**Comment by jtnord** [comment]
https://issues.jenkins.io/browse/JENKINS-65585

**Comment by MarkEWaite** [comment]
I'm seeing an unexpected failure during interactive use that seems to be caused by this change.  I've not been able to duplicate it in a simplified case yet, but I can see it consistently with this change included and it is resolved when this change is removed.

When I attempt to configure a [matrix job](https://github.com/MarkEWaite/docker-lfs/blob/weekly-with-plugins/ref/jobs/Tools/jobs/ant-jdk8-auto-install-check/config.xml) in Jenkins 2.288 I am able to save the configuration.  

When I attempt to save the [same job](https://github.com/MarkEWaite/docker-lfs/blob/weekly-with-plugins/ref/jobs/Tools/jobs/ant-jdk8-auto-install-check/config.xml) with Jenkins 2.289, the page does not return.  

When I save the [same job](https://github.com/MarkEWaite/docker-lfs/blob/weekly-with-plugins/ref/jobs/Tools/jobs/ant-jdk8-auto-install-check/config.xml) with a custom build of Jenkins 2.289 with this change reverted, it saves as expected.

**Comment by thomasgl-orange** [comment]
@MarkEWaite: I can reproduce what you're describing, and yes, it is indeed a consequence of this 2.289 change. It's not specific to Matrix jobs though.

What triggers the issue here is the invalid [depth=0](https://github.com/MarkEWaite/docker-lfs/blob/2a32b5804364c8215b21fd1462809b85d64cf109/ref/jobs/Tools/jobs/ant-jdk8-auto-install-check/config.xml#L57) value in your Git `CloneOption`. Because the `shallow` option is off, the field is hidden in the configure page (and the invalid value shouldn't matter in practice), but it still gets somehow validated and blocks submitting the form. And of course the error message is hidden too...

It is something which could be fixed / worked-around in the Git plugin itself, for this specific case. But similar issues might pop up with other plugins and existing configs, so it's difficult to estimate how "bad" this is.

**Pull request merged**
