### PR TITLE
[JENKINS-24452] Don't export arbitrary unexportable exceptions

### PR DESCRIPTION
**Pull request by daniel-beck**
[JENKINS-24452](https://issues.jenkins-ci.org/browse/JENKINS-24452)

### CODE REVIEW

**Comment by xiaoxuetu** [comment]
I  meet this problem in Jenkins version 2.46.2

**Comment by oleg-nenashev** [comment]
Yes, it still worth fixing it

**Comment by xiaoxuetu** [comment]
Which version will fix this problem?

**Comment by oleg-nenashev** [comment]
Once it is integrated into the master branch, it will appear in the weekly release line within one week (yeah, Mr. Obvious). Regarding the LTS, it will be determined by the release team. I am not sure the fix is backportable in the current state

**Review by oleg-nenashev — DISMISSED** [review]
This fix potentially breaks the valid use-cases.

I propose another fix:
1) Move exported to a getter like @jglick proposes
2) In getter call the export logic and try/catch the 'NotExportableException'
3) If the exception happens, return am artificial cause type, which would include some serializable bits like the stacktrace

**Comment by daniel-beck** [comment]
> This fix potentially breaks the valid use-cases.

Seems like a lot of work for basically nothing. I will not implement that approach, so if you 👎 anything less, please let me know so we can close this.

**Review by jglick — APPROVED** [review]
Looks fine to me, no need to do anything more.

**Comment by jglick** [comment]
> This fix potentially breaks the valid use-cases.

It does not break anything. It only fixes something which was always broken. Exporting detailed information from `ChannelTermination` (if anyone ever actually cared) would be an RFE.

**Comment by jglick** [comment]
And yes I retract my suggestion for `getStack`.

A test here _would_ be nice. After all, the original code could never have worked, which @kohsuke would have seen had d652291815c2c4d4424e0b704f8c64fc1ad74abe included any test coverage.

**Comment by oleg-nenashev** [comment]
> It does not break anything. It only fixes something which was always broken. 

Well, the case should have been working for exceptions with `@ExportedBean`, right?
`Channel#terminate(Exception cause)` is a part of the public API, so there is a technically valid case of passing information through the exception. So it breaks the following case:

```
@ExportedBean
class MyOfflineCause extends Exception {
  ..
}

and then

channel.terminate(new MyOfflineCause(...))
```

But yes, I agree that API access will blow up in any other case. My proposal of a correct bugfix would be to check if the exception has `@ExportedBean` annotation and to return null otherwise.

If @jenkinsci/code-reviewers are fine with the minor breakage risk, I am fine as well. I will remove my "Request changes" though I am not ready to approve the pull request in the current state.

**Comment by daniel-beck** [comment]
PR predates `Jenkinsfile`, so didn't get a PR build on PR reopen. Rebased.

**Comment by oleg-nenashev** [comment]
Test failure is unrelated

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers ping

**Review by MarkEWaite — APPROVED** [review]

**Comment by daniel-beck** [comment]
Rebased onto master.

**Comment by oleg-nenashev** [comment]
I have created https://issues.jenkins-ci.org/browse/JENKINS-49217 for a better implementation in a follow-up. Let's merge it as is for now

**Pull request merged**
