### PR TITLE
[JENKINS-63342] Fix JavaScript errors in Script Console on Mac

### PR DESCRIPTION
**Pull request by francoiscampbell**
Fixes errors related to keyevent handling in the script console when using a browser on a Mac introduced in 2.248 (specifically https://github.com/jenkinsci/jenkins/pull/4818/files#diff-da911448bbb85d374f604da9c1e00136R941)

See [JENKINS-63342](https://issues.jenkins-ci.org/browse/JENKINS-63342).

### Proposed changelog entries

* Bug: Fix Cmd + Enter not running the script in the Script Console on a Mac
* Bug: Fix backspace key sometimes not deleting text from the Script Console on a Mac

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by daniel-beck** [comment]
What's the error that this is fixing?

**Comment by francoiscampbell** [comment]
Here's the error you see today in the script console: 
Screen Shot 2020-08-07 at 11 13 59 AM

Upon fixing the scoping of `cmdKeyDown` (https://github.com/jenkinsci/jenkins/pull/4901/commits/6db83ae3eda60104ca4bb41196a705ec6d865185), I got a similar error related to the scope of the `e` and `editor` variables, so I figured the simplest solution was to just partially revert the commit that changed the scope of all those variables.

**Comment by francoiscampbell** [comment]
I also just created https://issues.jenkins-ci.org/browse/JENKINS-63342 which explains the bug in more detail.

**Comment by daniel-beck** [comment]
Apparently a regression in 2.244 from https://github.com/jenkinsci/jenkins/pull/4818

**Review by daniel-beck — APPROVED** [review]
I was able to reproduce the described problems on 2.251 on Firefox 79 / Mac OS 10.15.5 and can confirm this PR solves both.

I have not reviewed the code in detail, at a glance it looks reasonable.

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
This PR is ready for merge and may be merged after 24 hours if there's no negative feedback

**Review by oleg-nenashev — APPROVED** [review]
Thanks for the patch!

**Pull request merged**
