### PR TITLE
Adding id-card icon as a symbol, to be used in credentials plugin

### PR DESCRIPTION
**Pull request by raunak111**
See [JENKINS-69775](https://issues.jenkins.io/browse/JENKINS-69775).

### Proposed changelog entries

- Entry 1: The credential and credentials provider options have the same icon which is confusing/misleading

### Proposed upgrade guidelines

By adding the id-card icon, it can be used in the credentials providers option, as currently, it has a redundant icon 

### Submitter checklist

- [x] The Jira issue, if it exists, is well-described.
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [x] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7443"></a>

### CODE REVIEW

**Comment by NotMyFault** [comment]
Hey,

thanks for the PR.

> Testing is not required as only an entry is added to the symbols map

Testing is much needed, because this proposal doesn't address the issue at all, and doesn't impact the credentials-plugin.

I'd recommend you submit your contribution towards the [credentials-plugin](https://github.com/jenkinsci/credentials-plugin), and change the `symbol-key` there, that is where the icons are coming from.

Thanks!

**Comment by raunak111** [comment]
Hey,

thanks for your response.

> I'd recommend you submit your contribution towards the [credentials-plugin](https://github.com/jenkinsci/credentials-plugin), and change the `symbol-key` there, that is where the icons are coming from.

Someone tried changing the `symbol-key` to `symbol-wallet` in the [Jira issue](https://issues.jenkins.io/browse/JENKINS-69775) comments and it didn't work. Probably because it was not part of the ICON_TO_SYMBOL_TRANSLATIONS map?

If this PR is merged, I can then further contribute to the [credentials-plugin](https://github.com/jenkinsci/credentials-plugin) and change the icon there.

Please correct me if my approach is wrong as I'm a new contributor

**Comment by NotMyFault** [comment]
> Someone tried changing the `symbol-key` to `symbol-wallet` in the [Jira issue](https://issues.jenkins.io/browse/JENKINS-69775) comments and it didn't work. Probably because it was not part of the ICON_TO_SYMBOL_TRANSLATIONS map?

No, the map overrides tango icons with ionicons. Plugin authors don't need to see their icon added there, they can rely on the ionicons API plugin https://weekly.ci.jenkins.io/design-library/Symbols/, as it's already done widely in plugins.

**Comment by raunak111** [comment]
Thank you for guiding me in the right direction. Will do that 💯

**Pull request closed without merging**
