### PR TITLE
Log if no class paths was found for plugin

### PR DESCRIPTION
**Pull request by jonsten**
We ran into a situation where one of the plugin jpi archives was incorrect and didn't contain any valid classpaths. It took us a while to figure out that the classes from the jpi wasn't added to the class path. The log entry added in this change would have helped us a lot to spot the error quicker, and I believe that others in similar situations would benefit from it as well.

No JIRA issue available for this minor logging improvement.

### Proposed changelog entries

N/A

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by daniel-beck** [comment]
This is a legitimate use case, e.g. aggregator plugins.

**Comment by jonsten** [comment]
Doh, that was what I was worried about, just couldn't think of any valid case.

As for aggregator plugins, just had a look at Blue Ocean plugin (only aggregator plugin that seems to exist at this point), and it still contain a jar in WEB-INF/lib (see https://updates.jenkins-ci.org/download/plugins/blueocean/1.24.3/blueocean.hpi), so at least for that plugin, no warnings will be logged. I guess all plugins which are built using standard pom and release procedures will contain an (almost) empty jar fil, even if it doesn't have any classes defined.

With that said, I'm fine with abandoning this PR considering the new insight that there might be other legitim cases

**Comment by daniel-beck** [comment]
> and it still contain a jar in WEB-INF/lib

Good point. Any plugin built using modern tooling would have such a jar IIUC.

Would be interesting to see whether we're currently publishing plugins that would have a problem here.

FWIW `INFO` seems plenty for the use case? Visible but not inherently a problem?

**Comment by jonsten** [comment]
> FWIW `INFO` seems plenty for the use case? Visible but not inherently a problem?
Logging to Info should be sufficient as it makes it to show up in the logs, I've updated the PS

**Review by StefanSpieker — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
> Would be interesting to see whether we're currently publishing plugins that would have a problem here.

I doubt there are such plugins. Plugin manager is quite verbose on the FINE level anyway, so it should not be a big problem even we start excluding useless JARs from all aggregator plugins at some point

**Comment by oleg-nenashev** [comment]
We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Review by basil — APPROVED** [review]

**Pull request merged**
