### PR TITLE
[JENKINS-49112] Include the filename of the unreadable file in the exception message

### PR DESCRIPTION
**Pull request by ghost**
See [JENKINS-49112](https://issues.jenkins-ci.org/browse/JENKINS-49112).

### Proposed Changelog

* RFE - JENKINS-49112 -: Improve error messages in `TextFile#read()` to help diagnosing issues like JENKINS-49060

### Desired reviewers

@oleg-nenashev 
@daniel-beck

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
👍

**Comment by oleg-nenashev** [comment]
@dtrebbien I added the proposed changelog entry. PTAL

**Comment by oleg-nenashev** [comment]
Probably the changelog should reference JENKINS-49112. It seems that JENKINS-49112 and JENKINS-49060 PRs link wrong issues...

**Comment by dtrebbien** [comment]
The changelog entry looks good to me. Referencing both issues would be good.

**Pull request merged**
