### PR TITLE
chore: backporting 2.440.3

### PR DESCRIPTION
**Pull request by krisstern**
```shell
Latest core version: jenkins-2.448

Postponed
---------

JENKINS-68631           Minor                   2.446
        Hovering over stuck builds hides the progress bar (regression in 2.21)
        regression
        https://issues.jenkins.io/browse/JENKINS-68631

Fixed
-----

JENKINS-72954           Minor                   2.452, 2.440.3
        Update Mina SSH to 2.12.1 in Jenkins CLI
        https://issues.jenkins.io/browse/JENKINS-72954

JENKINS-72900           Minor                   2.450, 2.440.3
        Update Spring Security to 5.8.11 and Spring Framework to 5.3.33
        https://issues.jenkins.io/browse/JENKINS-72900

JENKINS-72856           Minor                   2.449, 2.440.3
        Update bundled trilead-api to 2.84.86.vf9c960e9b_458
        https://issues.jenkins.io/browse/JENKINS-72856

JENKINS-72799           Minor                   2.448, 2.440.3
        ConsoleLogFilter is not applied to all SlaveComputer logging
        https://issues.jenkins.io/browse/JENKINS-72799

JENKINS-72796           Minor                   2.449, 2.440.3
        Computer.threadPoolForRemoting can be poisoned by bad code
        https://issues.jenkins.io/browse/JENKINS-72796

```

```[tasklist]
### Submitter checklist
- [x] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Comment by basil** [comment]
I think it will be important to backport the Mina SSHD detached plugin changes to make the scanners happy. Rather than try to figure out how to do a minimal backport, I would recommend simply backporting all bundled plugin updates from trunk. While this includes more than just security fixes, it is tested in the latest weekly and should be safer than an untested surgical/minimal backport in my opinion.

**Comment by timja** [comment]
> [JENKINS-69113](https://issues.jenkins.io/browse/JENKINS-69113) / [47ac4a9](https://github.com/jenkinsci/jenkins/commit/47ac4a9b264fa2c15655a04b72f10a09403d3268) seems a bit much as a backport. While it fixes a regression it's not a recent one and not the core purpose of the change, so IMO we can live without it for another month. Thoughts?

I agree I think this can be dropped unless anyone has strong opinions on it.

**Comment by krisstern** [comment]
No problem, just dropped [JENKINS-69113](https://issues.jenkins.io/browse/JENKINS-69113) / [47ac4a9](https://github.com/jenkinsci/jenkins/commit/47ac4a9b264fa2c15655a04b72f10a09403d3268) from the LTS

**Review by basil — APPROVED** [review]
Since both @krisstern and @NotMyFault reacted with a thumbs up emoji to https://github.com/jenkinsci/jenkins/pull/9113#issuecomment-2032996170, and nobody had any feedback against it, I have implemented this in commit 387f5a600bee5cae72cb95a6a1cf59bc8da14255, tested the same way as #9091. With that having been addressed, the scanners should be happy with everything we are bundling and therefore I am approving this PR.

**Pull request merged**
