### PR TITLE
[FIXED JENKINS-37616] Make Cloud.PROVISION independent from Jenkins.ADMINISTER

### PR DESCRIPTION
**Pull request by olivergondza**
[JENKINS-37616](https://issues.jenkins-ci.org/browse/JENKINS-37616)

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Or maybe just Computer.CREATE?

**Comment by olivergondza** [comment]
Computer.CREATE allows you to create something new and configure it, while this just execute admin provided configuration.

**Comment by oleg-nenashev** [comment]
👍 anyway

**Comment by vjuranek** [comment]
:+1:  to @olivergondza to have different permission for creating ordinary slave and slave from cloud. Another reason is that while when creating ordinary slave you already have to have the resource (computer) and Jenkins has nothing to do with its allocation, in case of cloud its creation is requested by Jenkins and it can cost money, thus it would make sense to have more restrictive access to creating cloud base slaves than to ordinary slaves.

**Pull request merged**
