### PR TITLE
Upgrade to stapler version 1.246

### PR DESCRIPTION
**Pull request by vivek**
Fixed regressions reported in https://github.com/jenkinsci/jenkins/pull/2415 and other enhancements.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Seems the issue with release availability has not been resolved yet.

According to the code changes, I do not believe that it's only one change in *three* Stapler releases. Please provide a full changelog (ideally with JIRA references if available)

**Comment by vivek** [comment]
@oleg-nenashev Yeah not sure what the problem is, hopefully they will appear eventually in the repo.

In terms of changes, here are the Stapler PRs (no JIRA ticket though) that got merged post 1.244:

- https://github.com/stapler/stapler/pull/78
- https://github.com/stapler/stapler/pull/79
- https://github.com/stapler/stapler/pull/80

**Comment by vivek** [comment]
@oleg-nenashev Who would know why is Stapler artifacts are not resolved yet? 

`10:45:26 [ERROR] Failed to execute goal on project jenkins-core: Could not resolve dependencies for project org.jenkins-ci.main:jenkins-core:jar:2.26-SNAPSHOT: The following artifacts could not be resolved: org.kohsuke.stapler:stapler-groovy:jar:1.246, org.kohsuke.stapler:stapler-jrebel:jar:1.246: Could not find artifact org.kohsuke.stapler:stapler-groovy:jar:1.246 in central `

**Comment by oleg-nenashev** [comment]
@vivek 
Likely because it has not been actually uploaded to Maven Central. 
See https://mvnrepository.com/artifact/org.kohsuke.stapler/stapler

**Comment by vivek** [comment]
@oleg-nenashev Right and its not even at http://repo.jenkins-ci.org/public/org/kohsuke/stapler/stapler/. Maybe the repo has moved. @kohsuke Do you know if release went well or it was released to some other repo?

**Comment by daniel-beck** [comment]
@oleg-nenashev Actually, only the repository changing commit in https://github.com/stapler/stapler/compare/stapler-parent-1.244...stapler-parent-1.246 was without PR.

And in https://github.com/stapler/stapler/compare/stapler-parent-1.243...stapler-parent-1.244 only https://github.com/stapler/stapler/commit/94113342cf42c2b0e8a732613fc392f82d17f985 was outside a PR.

Still, @vivek's list of PRs is misleading, as this updates from 1.243 to 1.246, not from 1.244. Full list:

https://github.com/stapler/stapler/pull/73
https://github.com/stapler/stapler/pull/75
https://github.com/stapler/stapler/pull/77
https://github.com/stapler/stapler/pull/78
https://github.com/stapler/stapler/pull/79
https://github.com/stapler/stapler/pull/80

**Comment by vivek** [comment]
@daniel-beck Thanks, yeah I mistook the from version number, your list is good that is from 1.243. So what happens next to get stapler 1.246 to land in central? It's already released.

**Comment by oleg-nenashev** [comment]
@vivek You should contact @kohsuke . Likely he did not completely perform the release process. Maybe the release is staged on Nexus, but requires a manual action.

**Comment by vivek** [comment]
@daniel-beck @oleg-nenashev: Stapler 1.246 was released to maven central but was not visible, @kohsuke fixed it. Its visible now. Can Jenkins build be triggered for this PR manually?

**Comment by vivek** [comment]
@daniel-beck There is one failure but this has been failing since https://jenkins.ci.cloudbees.com/job/core/job/jenkins-core/6375/ and is unrelated. How do we move forward?

**Comment by daniel-beck** [comment]
@vivek There's a successful PR build, so no problem there from build success POV. Now this needs reviews.

@jenkinsci/code-reviewers assemble!

**Comment by vivek** [comment]
@daniel-beck How long do you stage it for review? Didn't see any comments so far.

**Comment by oleg-nenashev** [comment]
Review is still in my TODO list.
I'll do it with a high priority since it may worth having new Stapler in LTS

**Comment by oleg-nenashev** [comment]
There are some compatibility changes in PRs like https://github.com/stapler/stapler/pull/77 (public classes => final, and several other changes). Putting back on-hold since I'm not comfortable about merging before a wider research

**Comment by oleg-nenashev** [comment]
I would rather 🐛 this PR till Stapler has public CI builds.
The component is critical  to Jenkins stability, hence we should invest into it.

@vivek Is it critical to get it available in the next LTS line? What's the impact if it does not get there?

**Comment by vivek** [comment]
@oleg-nenashev It is critical as some of the changes/fixes are needed by blueocean. So its really important it gets in to this LTS. 

Just so that I understand, your objection is for process or there is technical reason you are objecting to? In terms of review, each Stapler PR goes thru review process and has been reviewed/approved. 

Anyways, all of those PR are already in stapler released version. So if you think there is PR or change that is an issue or can cause instability in Jenkins then we can fix that otherwise I think we should not hold this PR for process reasons unless it violates any Jenkins guidelines.

**Comment by oleg-nenashev** [comment]
@vivek Binary compatibility is one of Jenkins requirements. Since there are binary compatibility changes, Stapler maintainers should proof that they do not impact at least OSS plugins.

I do not want to block the update since I understand value of BO to the community, but compatibility of existing plugins IMHO is a mandatory requirement unless there is a decision made after the discussion in the ML.

**Comment by vivek** [comment]
@oleg-nenashev Fair point. Happy to help here. All tests are passing. If there is more testing or review needed, lets get thru that. Its just that the PR is sitting idle so was making sure the concern gets addressed and integration happens if all looks good:)

**Comment by oleg-nenashev** [comment]
So there are following issues I see:
* No CI for Stapler itself. Not sure we want to merge a lib, which didn't pass tests on the generic environment. But I'm sure @kohsuke has performed tests locally as a part of the release
* `java.org.kohsuke.stapler.lang.Klass` has been converted from `public` to `public final`. It is a binary compatibility breakage
 * Investigation results: No usages in the Jenkins project
* The changes slightly increase the technical debt (missing API docs), but it's a kind of the maintainer decision

So I do not see anything critical in the changes (though I didn't investigate logic much), but I would like to get signoff of other @jenkinsci/code-reviewers since the changes do not qualify as a "safe change" for me.

If somebody fixes the binary compatibility issue and creates a working PR builder, you will have my +1

**Comment by batmat** [comment]
+1 on the "safe change" comment. There's still quite a few changes there… Normally there would still be time for the next .1 LTS to let it soak anyway, only if the selected base includes it...

**Comment by oleg-nenashev** [comment]
@batmat I'm not sure. Do you approve the change in the current state or not? I read "no" from your comment, but I'm not 100% sure

@vivek Actually I've expected a response from you yesterday. Is there a chance you spin a new Stapler release with compatibility change revert in time? In such case it would be convenient.

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers @reviewbybees Any other feedback?

**Comment by ndeloof** [comment]
LGTM 🐝   👍  and all that sort of things.

stapler imo is part of jenkins-core API (who else is using it?) and should be developed in sync. Getting 3 releases without being used by jenkins-core doesn't make sense to me. I wish stapler CI build would build latest tag from jenkins + stapler version patch to detect potential regressions.

**Comment by oleg-nenashev** [comment]
There was np technical reason in the release delay. The release process was
somehow screwed up, and @kohsuke was not responding to pings (see the PR
referenced in the summary). Hence the stapler upgrades were hanging.

I do not consider Stapler as a part of the Jenkins project, because the
project is not accessible to jenkinsci/admins && the review process is
being held outside differently. There are also usages outside.Jenkins IIRC.
But I agree we should pick the new version to the Jenkins core as early as
we can.

**Comment by stephenc** [comment]
FTR I have reviewed the changes to stapler and I do not view them as high or medium risk. I cannot see any use case for extending `Klass`.

**Comment by ndeloof** [comment]
The way stapler is managed and hosted outside jenkins project doesn't make me feel it's not part of jenkins project (I agree it would make sense project is managed the same way). And I can't find any usage outside jenkins and KK's own projects :P

**Comment by batmat** [comment]
@oleg-nenashev, let's say weak :+1: :bee: but I'll trust more knowledgeable persons here. 
I've had a look at the GitHub code search yesterday, and in addition to Stephen's comment about any "use case for extending Klass", I couldn't find any plugin under https://github.com/jenkinsci that was actually doing it.

**Comment by oleg-nenashev** [comment]
Thanks for the feedback.
I'm merging this PR and taking responsibility to work on any kind of regressions it causes.

**Comment by oleg-nenashev** [comment]
@vivek Please provide a human-readable changelog (maybe in Stapler's repo)

**Comment by batmat** [comment]
@oleg-nenashev this is a team's decision. You don't have to take that burden alone if it happens to be necessary. Many people here have expressed their approval, so it's OK to merge IMO. Thanks for moving that forward and so many other things in that project Oleg.

**Comment by daniel-beck** [comment]
@vivek So what does this actually do? The changelog for this change in 2.28 is still useless. See @oleg-nenashev's question above.

**Comment by vivek** [comment]
@daniel-beck @oleg-nenashev 
Allows 'parallel request routing', this will allow BlueOcean or any Jenkins plugin to serve request routes that otherwise be served by jelly views as JSON response. Relevant PR is: https://github.com/stapler/stapler/pull/77.

**Comment by oleg-nenashev** [comment]
@vivek 
So could you add the changelog to Stapler?
Example: https://github.com/jenkinsci/remoting/blob/master/CHANGELOG.md

**Comment by vivek** [comment]
@oleg-nenashev sure, I can do that. I will send a PR with this change added to a CHANGELOG.md in stapler.

**Comment by vivek** [comment]
@oleg-nenashev @daniel-beck https://github.com/stapler/stapler/pull/95.

**Pull request merged**
