### PR TITLE
[FIXED JENKINS-32478] Use released version of test harness

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-32478](https://issues.jenkins-ci.org/browse/JENKINS-32478)

Follows up #1977 to actually use the released binary artifacts now that sources have been physically extracted.

@reviewbybees

### CODE REVIEW

**Comment by jtnord** [comment]
:bee:

**Comment by recena** [comment]
:bee:

**Comment by kwhetstone** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
:+1: 
Maybe it breaks some incoming pull requests, but the change definitely worth it.
Retriggering the build to see if it is an unstable test or code migration issue

**Comment by jglick** [comment]
I forgot to update `plugins/pom.xml`, will do that as soon as I can.

**Comment by oleg-nenashev** [comment]
:bee:

**Comment by tfennelly** [comment]
:bee:

**Comment by rsandell** [comment]
:bee:

**Comment by jglick** [comment]
Still trying to track down

```
org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyTestSuite(org.jvnet.hudson.test.junit.FailedTest)  Time elapsed: 0.016 sec  <<< ERROR!
java.lang.IncompatibleClassChangeError: Implementing class
	at …
	at org.eclipse.sisu.plexus.binders.PlexusAnnotatedBeanModule$PlexusSpaceModule.visitor(PlexusAnnotatedBeanModule.java:101)
	at org.eclipse.sisu.binders.SpaceModule.configure(SpaceModule.java:92)
	at org.eclipse.sisu.plexus.binders.PlexusAnnotatedBeanModule.configure(PlexusAnnotatedBeanModule.java:81)
	at org.eclipse.sisu.plexus.binders.PlexusBindingModule.configure(PlexusBindingModule.java:65)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:230)
	at com.google.inject.spi.Elements.getElements(Elements.java:103)
	at com.google.inject.spi.Elements.getElements(Elements.java:80)
	at org.eclipse.sisu.binders.WireModule.configure(WireModule.java:60)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:230)
	at com.google.inject.spi.Elements.getElements(Elements.java:103)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:136)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at org.codehaus.plexus.DefaultPlexusContainer.addPlexusInjector(DefaultPlexusContainer.java:476)
	at org.codehaus.plexus.DefaultPlexusContainer.<init>(DefaultPlexusContainer.java:202)
	at org.codehaus.plexus.DefaultPlexusContainer.<init>(DefaultPlexusContainer.java:166)
	at hudson.maven.MavenEmbedderUtils.buildPlexusContainer(MavenEmbedderUtils.java:166)
	at hudson.maven.MavenEmbedderUtils.buildPlexusContainer(MavenEmbedderUtils.java:159)
	at hudson.maven.MavenEmbedder.<init>(MavenEmbedder.java:109)
	at hudson.maven.MavenEmbedder.<init>(MavenEmbedder.java:136)
	at org.jvnet.hudson.test.HudsonTestCase$7.decorateHome(HudsonTestCase.java:1326)
	at org.jvnet.hudson.test.HudsonTestCase.newHudson(HudsonTestCase.java:486)
	at org.jvnet.hudson.test.HudsonTestCase.setUp(HudsonTestCase.java:318)
	at …
```

**Comment by jglick** [comment]
Only observed in `cloudbees-folder-plugin`; other simpler plugins pass the injected test. Maybe something to do with that plugin’s dependencies. Anyway is not looking like a blocker.

**Comment by jglick** [comment]
Seems `org.eclipse.sisu.scanners.EmptyClassVisitor`, pulled in from `lib-jenkins-maven-embedder` via the harness, uses ASM 3.x while Jenkins core uses 4.x (via `jnr-posix`); and `org.objectweb.asm.ClassVisitor` changed from an interface to an abstract class. Seems like a problem of a very old version of Sisu Inject coming from the Maven embedder. Not sure why only some plugins are affected. Anyway, another reason to try to refactor `JenkinsRule` (well, `HudsonTestCase` in this case—`InjectedTest` cannot be trivially moved to JUnit 4.x) to expect `*.hpi` test dependencies in the test classpath rather than doing runtime artifact resolution.

**Pull request merged**
