### PR TITLE
 [JENKINS-34751] use patched version of Groovy 2.4.6

### PR DESCRIPTION
**Pull request by daspilker**
contains fixes for [GROOVY-7761](https://issues.apache.org/jira/browse/GROOVY-7761) and [GROOVY-7826](https://issues.apache.org/jira/browse/GROOVY-7826), see https://github.com/jenkinsci/groovy/compare/GROOVY_2_4_6...GROOVY_2_4_6-jenkins-1

dev list thread:
https://groups.google.com/forum/?fromgroups#!topic/jenkinsci-dev/KPagVUko3hg

[JENKINS-34751](https://issues.jenkins-ci.org/browse/JENKINS-34751)

### CODE REVIEW

**Comment by slide** [comment]
Even if this fixes issues, I've seen these type of patched versions stay around for too long and sometimes even cause issues on upgrade. :-1:

**Comment by daspilker** [comment]
I would have preferred to use an official release, but it will take at least a few days to get a new release. We may not get an official release until the the first 2.x LTS baseline is chosen. To get the fixes into to the first 2.x LTS release, we should use a patched Groovy for a very limited time. It would be a bummer to ship the first 2.x LTS release with a regression in advanced Groovy scripting.

Both changes already landed in Groovy master (2.5) and have been backported to 2.4, so they will be in the next Groovy releases:

GROOVY-7826: https://github.com/apache/groovy/commit/de30aed50902fb8483824d0e484f7c769b5636a4
GROOVY-7761: https://github.com/apache/groovy/commit/7c78768f7ec7267f94755661ccfe0889802fa7da

There should be no reason to use the patched version longer than necessary, which is until 2.4.7 has been released.

**Comment by oleg-nenashev** [comment]
@daspilker If it's a question of several days, I would wait till the official release since the next weekly release ETA is Sunday.

I definitely agree that the LTS should contain a fix. For Jenkins 2 LTS backporting window the release on Sunday should be fine as well even if the previous version gets selected. Technically we just need to integrate the fix till the middle of June in order to get it in Jenkins 2 LTS RC

**Comment by daspilker** [comment]
[quoting](https://issues.jenkins-ci.org/browse/JENKINS-34751?focusedCommentId=258208&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-258208) @daniel-beck:

> While we release 2.x.1 LTS on July 6, we decide the baseline on June 8 and the version we choose is typically 3-4 weeks old. I.e. now.

> If this is supposed to be fixed for 2.x.1 LTS in July, we need to go the patched Groovy route again, and quickly.

We don't know if Groovy 2.4.7 will be released in time for the next LTS. I think it's a good idea to have the patch on master for a few weeks before backporting it into the LTS. If Groovy 2.4.7 is released, we can jump to the official version ASAP.

**Comment by oleg-nenashev** [comment]
👍 for merging it if there is no official release till Friday EoD

**Comment by daniel-beck** [comment]
@slide 

> Even if this fixes issues, I've seen these type of patched versions stay around for too long and sometimes even cause issues on upgrade.

Note that the fixes are scheduled for upcoming Groovy releases and were backported by @daspilker. While this remains a patched version, it's as close to being safe as possible.

Maybe @daspilker can commit to track upstream development, and remove this patched dependency as soon as there's a new 2.4.x?

**Comment by daspilker** [comment]
Yes, I'm tracking Groovy development and will open a new PR if Groovy 2.4.7 has been released.

**Comment by slide** [comment]
Ok, in that case :+1:

**Comment by KostyaSha** [comment]
👍 :shipit:

**Comment by daniel-beck** [comment]
👍 FTR

**Comment by jglick** [comment]
:+1:

**Comment by jglick** [comment]
Tried

    mvn -DskipTests clean install && mvn -f ../workflow-cps-plugin -Djenkins.version=2.7-SNAPSHOT clean test

with only failures in `CpsFlowExecutionTest.loaderReleased` and `SerializationTest.listIterator` which were known from Jenkins 2.0 and not related to this change.

**Comment by batmat** [comment]
:+1:

**Comment by oleg-nenashev** [comment]
Groovy 2.4.7 has not been released yet. Merging

**Pull request merged**
