### PR TITLE
[FIX JENKINS-32938] Usage Statistics needs a section otherwise it can be kind of hard to find

### PR DESCRIPTION
**Pull request by stephenc**
@reviewbybees

http://issues.jenkins-ci.org/browse/JENKINS-32938

### CODE REVIEW

**Comment by HRMPW** [comment]
:bee:  This should help distinguish this from "Custom Update Center" settings

**Comment by stephenc** [comment]
@HRMPW it really depends what plugins you have installed, e.g. on one of my systems it is attached to Literate multibranch!
 
screen shot 2017-02-10 at 15 56 13

**Comment by HRMPW** [comment]
one of three installs!

**Review by daniel-beck — APPROVED** [review]

**Comment by stephenc** [comment]
@reviewbybees done

**Pull request merged**
