### PR TITLE
Drop the version from libraries packaged under `WEB-INF/lib`

### PR DESCRIPTION
**Pull request by Vlatombe**
The default mapping requires `mvn clean`ing every time whenever a library is updated, otherwise it ends up being packaged twice. It also eases deep war comparison.

Con is that it is slightly more difficult to determine library version, since you need to look into `lib.jar/META-INF/MANIFEST.MF` rather than look at the file name itself.

### Testing done

* Checked startup is successful
* Checked that `/jnlpJars/agent.jar` is reachable

### Proposed changelog entries

N/A

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [x] The Jira issue, if it exists, is well-described.
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [x] There is automated testing or an explanation as to why this change has no tests.
- [x] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [x] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [x] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [x] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [x] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Comment by Vlatombe** [comment]
```
java.io.FileNotFoundException: lib/remoting-3206.vb_15dcf73f6a_9.jar
	at hudson.model.Slave$JnlpJar.getURL(Slave.java:470)
```
Some tests look broken, back to draft.

**Review by basil — COMMENTED** [review]
-0 from me. I don't feel strongly enough to block the change, but I somewhat like the status quo, as it improves observability (e.g. when listing open file descriptors with `pfiles` or `ls -lah /proc/$PID/fd`). Admittedly, I only ever run `mvn clean verify` (never `mvn verify`, for exactly this reason), but my experience is that the former is good enough. I have a natural bias for observability over performance, and I recognize that others have different priorities, which is why I am not blocking this PR, but I would prefer to keep this as-is and to close this PR.

**Review by jglick — APPROVED** [review]
I have a preference (+0) for stability in the list of ZIP entries.

Regarding version lookups, `jenkins.war!/META-INF/maven/org.jenkins-ci.main/jenkins-war/pom.xml` and `jenkins.war!/WEB-INF/lib/jenkins-core.jar!/META-INF/maven/org.jenkins-ci.main/jenkins-core/pom.xml` contain resolved version numbers.

**Comment by jglick** [comment]
> For what reason do you have this preference?

Same as in PR description. Also easier to maintain scripts which pick out a member by name. No strong feeling, but have generally encountered fewer problems with Maven projects configured to suppress the default behavior of injecting `-${project.version}` into artifact filenames.

**Comment by basil** [comment]
> Also easier to maintain scripts which pick out a member by name.

That seems like a pretty contrived use case to me—better to construct the WAR file as desired rather than pick out a member in a script after the fact.

> No strong feeling, but have generally encountered fewer problems with Maven projects configured to suppress the default behavior of injecting `-${project.version}` into artifact filenames.

No strong feeling either, but from the other perpsective one could also make the argument that deviating from the default behavior for any reason is an increase in code that has to be maintained (even a small one).

**Comment by Vlatombe** [comment]
Talking about technical debt, I had issues in the past with a setup relying on a custom `jenkinsWarId` provided to `maven-hpi-plugin`, that was embedding a different version of `remoting` than the version that was ending up in maven classpath. 

Could be qualified as an exotic use case, but that still exists in real life.

This was leading to test errors like `java.io.FileNotFoundException: lib/remoting-XXXX.jar` for tests relying on `JenkinsRule#createOnlineSlave` that were difficult to diagnose.

Dropping the version from packaging would have avoided that kind of issue.

**Comment by Vlatombe** [comment]
> deviating from the default behavior

Maven defaults are not always sane TBH.

**Review by timja — APPROVED** [review]

**Comment by daniel-beck** [comment]
> Dropping the version from packaging would have avoided that kind of issue.

That case looks more like a reason to keep the version, seems like the error was fairly explicit, and resulting behavior discrepancies between jars would be far more difficult to diagnose?

**Comment by Vlatombe** [comment]
> the error was fairly explicit

Actually not so much, added clarification in 
https://github.com/jenkinsci/jenkins/commit/fdae43cdb1e4da22582485b87b91c8d37817521d#diff-fd90f3c68e090dc7d978216f27bab3655ba35a72127f46d0ccd983a14cf2b97bR476

One more protection that could be added would be for `maven-hpi-plugin` to validate that the jenkins core version in classpath is the same as the core version provided part of the custom `jenkinsWarId`.

**Review by NotMyFault — APPROVED** [review]

**Comment by jtnord** [comment]
Not that we have hit the issue and not that we want to add yet more to core but this impacts a collision in aArtifactIds but different groupIds and versions (`foo.bar:utils:1.0` and `whizz.bang:utils:3.2` would not be possible to use both.)

Mostly -0.  Benefit I can see is that scanners would not see different paths for libraries with CVE that causes "new" findings (like spring causes on every bump)

**Comment by Vlatombe** [comment]
Closing as there doesn't seem a strong enough consensus on this topic.

**Comment by jglick** [comment]
If reconsidering, beware that some parts of PCT-related tooling apparently make assumptions about WAR entry name formats rather than inspecting the nested manifest as they probably should: https://github.com/jenkinsci/maven-hpi-plugin/blob/0a49814328a9e6be94aa6bc3569905e83f178900/src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java#L93

**Comment by maxi-bee** [comment]
This would be extremely useful for vulnerability management of anyone using Jenkins/CBCI. Currently most scanners will detect every version having the same vulnerability as different ones. Having the consistency on the path (via stripping this versioning of the `jar` name). Note also that we don't see this issue for any of the other products we scan (so I suppose they either don't include the versioning on the file name or they are always vulnerability free until now :) ). I officially support this change!

**Pull request closed without merging**
