### PR TITLE
[FIXED JENKINS-49319] Upgrade to PrototypeJS 1.7.3

### PR DESCRIPTION
**Pull request by uhafner**
See [JENKINS-49319](https://issues.jenkins-ci.org/browse/JENKINS-49319).

The [diff](https://github.com/sstephenson/prototype/compare/1.7...1.7.3) is quite large. Changelogs:
- http://prototypejs.org/2015/09/24/prototype-1-7-3/
- http://prototypejs.org/2014/04/18/prototype-1-7-2/
- http://prototypejs.org/2012/08/08/prototype-1-7-1/

Since no new feature is added, just a new release the existing ATH should be sufficient as a regression test.
 

### Proposed changelog entries

* Internal: Upgrade to PrototypeJS 1.7.3

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@tfennelly

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers

**Comment by oleg-nenashev** [comment]
something went wrong :(

**Comment by uhafner** [comment]
Good too see that an upgrade from 1.7 to 1.7.3 did not change the number of failed tests. Seems that someone patched the original version inside this sealed library (rather than providing a patch that is applied in the build process). Is this a common praxis in core? It makes upgrading to newer releases a pain...

**Comment by oleg-nenashev** [comment]
> Seems that someone patched the original version inside this sealed library (rather than providing a patch that is applied in the build process). Is this a common praxis in core? It makes upgrading to newer releases a pain...

It is a bad practice for sure. I wonder why we keep this code in the core at all.
IIUC Jenkins JS Bundler allows to keep it in external repository with independent versioning. WDYT @uhafner @tfennelly @daniel-beck?

**Review by oleg-nenashev — APPROVED** [review]
IMHO this codebase shouldbe removed from the core somehow. OTOH the PR does not make the things worse, so I am fine with merging if it passes ATH.

**Comment by recena** [comment]
@uhafner Do we solve something with this upgrade? A particular bugfix? any improvement?

**Comment by uhafner** [comment]
I provided some links in JENKINS-49319: here you see the stack trace when I try to use a bar graph in my plug-in. With 1.7.3 the bar graph is correctly rendered. Without the graph is broken.

**Comment by recena** [comment]
@uhafner My apologies, I did not see the content of the JIRA issue. I'll do it.

**Comment by oleg-nenashev** [comment]
We have selected 2.107.x for the LTS baseline. Probably we could ship it now

**Comment by oleg-nenashev** [comment]
On hold for this weekly, I want to get more feedback from @jenkinsci/code-reviewers

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers ping

**Comment by oleg-nenashev** [comment]
@recena WDYT?

**Comment by oleg-nenashev** [comment]
YOLO mode: I am going to merge it into the next weekly unless nobody votes against.

**Comment by oleg-nenashev** [comment]
Merge with squash would be preferable from what I see

**Comment by daniel-beck** [comment]
@oleg-nenashev AFAIUI this history it pretty much deliberate, with the changes over time compared to upstream having been reapplied.

**Comment by oleg-nenashev** [comment]
Yeah, maybe. 
I will merge it as is then, but generally it should be moved outside of the Jenkins repo if we need such change again

**Comment by jglick** [comment]
Evidently caused a serious regression: [JENKINS-49968](https://issues.jenkins-ci.org/browse/JENKINS-49968). CC @daniel-beck @oleg-nenashev

**Pull request merged**
