### PR TITLE
UI Improvements / refreshing

### PR DESCRIPTION
**Pull request by lrobertson39**
- Update all drop down boxes within job configuration and main configuration pages to match new styling where class .setting-input has not been defined
- Add padding to labels to provide middle vertical alignment to single-line input fields while not causing regression in JENKINS-10253
- Always vertically align input fields to middle

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@tfennelly 
Is this PR alive?

**Comment by daniel-beck** [comment]
@tfennelly @gusreiber Is there something here we can salvage for 2.x? Or is it maybe obsolete with new config style?

**Comment by oleg-nenashev** [comment]
These guys rarely respond to GitHub pings :(

**Comment by batmat** [comment]
@lrobertson39 hi! If it's not too much work, could you possibly consider rebasing it onto master? That would help check it still makes sense with Jenkins 2.x (which had a lot of UI changes)?
Thanks a lot.

**Comment by daniel-beck** [comment]
This appears to have been abandoned years ago. Will probably need to be updated for 2.x anyway, so closing for now.

**Pull request closed without merging**
