### PR TITLE
Stylelint fixes

### PR DESCRIPTION
**Pull request by StefanSpieker**
I fixed a couple of stylelint warnings to reduce the amount of warnings.
* merged duplicate selectors
* Added a couple of newlines because of rule `selector-list-comma-newline-after`

### Proposed changelog entries

* Internal: N/A

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
conflicts

**Comment by StefanSpieker** [comment]
Merged with master, there are currently failing frontend tests in master:

```
[INFO] Test Suites: 1 failed, 2 passed, 3 total
[INFO] Tests:       6 failed, 14 passed, 20 total
```

**Comment by timja** [comment]
> Merged with master, there are currently failing frontend tests in master:
> 
> ```
> [INFO] Test Suites: 1 failed, 2 passed, 3 total
> [INFO] Tests:       6 failed, 14 passed, 20 total
> ```

weird, this seems to fix it: https://github.com/jenkinsci/jenkins/pull/5031
but not sure what caused it and for it not to be picked up in CI

**Review by res0nance — APPROVED** [review]
Nice when I look at the logs i see almost a third of it is just stylelint warnings. Hopefully we can have that cleaned up

**Comment by StefanSpieker** [comment]
The plan is definitly to get rid of all these. I just wanted to keep the changes "reviewable"

**Comment by timja** [comment]
Looks like a flakey test:
image

**Pull request merged**
