### PR TITLE
[JENKINS-49331] Handle exceptions when rebuilding with invalid choice parameter

### PR DESCRIPTION
**Pull request by Fredrik93**
See [JENKINS-49331](https://issues.jenkins.io/browse/JENKINS-49331).

### Testing done
Testing done by compiling the project and running the light-test profile provided  

### Proposed changelog entries

- JENKINS-49331, human-readable text

<!-- Comment:
The changelog entry should be in the imperative mood; e.g., write "do this"/"return that" rather than "does this"/"returns that".
For examples, see: https://www.jenkins.io/changelog/

You may add multiple changelog entries if applicable by adding a new entry to the list, e.g.
- JENKINS-49331 Add exception handling

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [ X] The Jira issue, if it exists, is well-described.
- [ X] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [X] There is automated testing or an explanation as to why this change has no tests.
- [X] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [X] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [X] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [X] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [X] For new APIs and extension points, there is a link to at least one consumer.
```

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Review by MarkEWaite — CHANGES_REQUESTED** [review]
Thanks for the pull request!

The proposed change doesn't seem to change the behavior much from the existing behavior.  An "Oops" page is shown to the user when they enter an invalid value for a choice parameter with this change, just as an "Oops" page was shown to the user before this change.

The "Oops" page that I see looks like this:

screencapture-rhel-8-a-markwaite-net-8080-jenkins-job-choice-param-lastCompletedBuild-rebuild-configSubmit-2024-03-09-05_58_02-edit

Thanks for completing the "Testing done" entry.   

Please provide a proposed changelog entry that more completely describes the change in terms that a user will understand.

Please also reinsert the rest of the pull request template and complete the checkboxes.  It helps you as a submitter and it helps maintainers as reviewers.

**Comment by MarkEWaite** [comment]
I tested this interactively by performing the following steps:

1. Compile with `mvn -am -pl war,bom -Pquick-build clean install`
2. Run with `mvn -pl war jetty:run`
3. Install the rebuilder plugin (required to duplicate the issue)
4. Restart Jenkins
5. Create a freestyle project that takes a choice parameter "CHOSEN_LETTER" with several single letter choices ("A", "B", ...)
6. Run the freestyle project, choosing various parameters and confirm they succeed
7. Click the "Rebuild last" link on the job page, and enter an invalid value in the CHOSEN_LETTER field
8. Click the button to run the job

That results in the "Oops" page that is mentioned in https://github.com/jenkinsci/jenkins/pull/9027#pullrequestreview-1926192620

Without this change, the "Oops" page looks like this:

screencapture-rhel-8-a-markwaite-net-8080-jenkins-job-choice-param-lastCompletedBuild-rebuild-configSubmit-2024-03-09-06_15_40-edit

**Comment by MarkEWaite** [comment]
I'm not sure what the user will expect when they rebuild with an invalid value for a choice parameter.

The `checkValue` method can either throw an unchecked exception (like `IllegalArgumentException` in the current code and in this pull request) or its callers can be modified to accept a `StringParameterValue` return value and then they return that result.  If the returned `StringParameterValue` is returned as `null` for invalid parameter values, then the "Oops" page is not shown to the user, but the rebuild then proceeds and uses the default value of the parameter, instead of using the invalid value that was entered by the user.

I don't think that changing the signature of `checkValue` to throw a checked exception (like `IOException`) will help because the callers inside the `ChoiceParameterDefinition` class will need to catch that exception and do something with it.  As far as I can tell, the only alternatives are to return the `StringParameterValue` or to return `null` and neither of those alternatives will stop the job from being executed.

**Comment by Fredrik93** [comment]
Hi Mark, i really appreciate your comments, theyre really helpful to me. im trying to reproduce the issue the way that you described, i also agree with your last comment and ill try to make the correct adjustments.

**Comment by MarkEWaite** [comment]
> Hi Mark, i really appreciate your comments, theyre really helpful to me. im trying to reproduce the issue the way that you described, i also agree with your last comment and ill try to make the correct adjustments.

Thanks again for the pull request.  Unfortunately, my comments only highlight the problem and don't really offer a solution.  I don't understand how to solve the problem without wider changes than I think would be appropriate for this case.

**Comment by Fredrik93** [comment]
oh, i see. I might have underestimated the issue. I picked an issue from the newbie-friendly issues. What are your thoughts on this, do you reckon that i should abandon this task and try my hand at something else, more simple? I understand thats it of course based on my skills and its hard for you to know, but just changing method took me a while, so fiddling with anything more complex would probably be too much for me

**Comment by MarkEWaite** [comment]
> oh, i see. I might have underestimated the issue. I picked an issue from the newbie-friendly issues. What are your thoughts on this, do you reckon that i should abandon this task and try my hand at something else, more simple? I understand thats it of course based on my skills and its hard for you to know, but just changing method took me a while, so fiddling with anything more complex would probably be too much for me

I think that this issue is incorrectly labeled as "newbie-friendly".  I think you are wise to choose another issue.  If you choose to work on another issue, you can close this pull request.

**Pull request closed without merging**
