### PR TITLE
Update access-modifier to allow plugins to use suppressions

### PR DESCRIPTION
**Pull request by jtnord**
### Proposed changelog entries

* Updated Access Modifier to `1.16`

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] JIRA issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

### CODE REVIEW

**Review by jvz — APPROVED** [review]
I wondered why this feature never worked before...

**Comment by jtnord** [comment]
> I wondered why this feature never worked before...

it works - you just need to specify `1.16` in your plugin, and then ignore the upper-bounds error.

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
Would be good to link to a changelog / release notes when upgrading the dependency...

**Comment by jtnord** [comment]
> Would be good to link to a changelog / release notes when upgrading the dependency...

it would and I went looking and there wasn't any as far as I could tell.  Best there is is https://github.com/kohsuke/access-modifier/commits/access-modifier-1.16  (basically ignore synthetic methods, and allow code to suppress the check via an annotation)

**Review by oleg-nenashev — APPROVED** [review]
+1 for merging, changelogs is a known issue

**Review by res0nance — APPROVED** [review]

**Pull request merged**
