### PR TITLE
[JENKINS-61458] Allow Jenkins.MANAGE user to access "Reload Configuration From Disk"

### PR DESCRIPTION
**Pull request by escoem**
See [JENKINS-61458](https://issues.jenkins-ci.org/browse/JENKINS-61458).

### Proposed changelog entries

*  Allow users with Jenkins.MANAGE permissions access to configuration reload

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [x] There are at least 2 approvals for the pull request and no outstanding requests for change
- [x] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [x] Proper changelog labels are set so that the changelog can be generated automatically
- [x] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [x] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by amuniz — APPROVED** [review]

**Review by EstherAF — APPROVED** [review]
Looks good to me!

**Comment by res0nance** [comment]
Merging in 24h if no negative feedback

**Review by varyvol — APPROVED** [review]

**Review by MRamonLeon — APPROVED** [review]

**Comment by MRamonLeon** [comment]
The proposed change log is not clear to me. This change allow administers to reload the configuration from disk, either via UI or CLI. I would suggest a bit of polishment to the changelog entry @escoem

**Comment by escoem** [comment]
> The proposed change log is not clear to me. This change allow administers to reload the configuration from disk, either via UI or CLI. I would suggest a bit of polishment to the changelog entry @escoem

@MRamonLeon _Reload Configuration from Disk_ is the name of the Management Link.

**Comment by MRamonLeon** [comment]
What I mean is that this change also adds MANAGE users to reload from CLI, so something like:

`Allow users with MANAGE permission to reload the configuration from disk.`

is better IMO, because it includes both, from UI or CLI. But it's approved from my side, anyway.

**Pull request merged**
