### PR TITLE
Recover views after error in `Jenkins.load`

### PR DESCRIPTION
**Pull request by jglick**
I had occasionally seen mysterious errors in CloudBees CI which I finally tracked down by observing that they came after a warning about reloading `$JENKINS_HOME/config.xml` from disk. #8413 made this somewhat safer but not enough.

([CloudBees-internal reference](https://cloudbees.atlassian.net/browse/BEE-53211))

### Testing done

Without the fix, the assertions about `.primaryView` and `.views` fail. More interestingly, while browsing the dashboard (`goTo("")`) simply fails with a 404 (Stapler trace is pretty obvious: looking up the primary view fails since it is null), browsing some other pages produces two `StackOverflowError`s from Stapler/Jelly:

```
…
	at org.kohsuke.stapler.jelly.JellyViewScript.run(JellyViewScript.java:98)
	at org.kohsuke.stapler.jelly.IncludeTag.doTag(IncludeTag.java:174)
	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:271)
	at org.kohsuke.stapler.jelly.JellyViewScript.run(JellyViewScript.java:98)
…
```

and

```
…
	at org.apache.commons.jelly.JellyContext.getVariableWithDefaultValue(JellyContext.java:260)
	at org.apache.commons.jelly.JellyContext.getVariableWithDefaultValue(JellyContext.java:260)
…
```

which seems to be caused by an unfortunate default logic in `IncludeTag` resulting in an infinite recursion when `it=null`.

### Proposed changelog entries

- Restore the list of views after a failed attempt to reload global configuration, to avoid further rendering errors.

### Proposed upgrade guidelines

N/A

### Desired reviewers

@Vlatombe

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Comment by jglick** [comment]
https://github.com/jenkinsci/jenkins/blob/c1a356b11a111f4dff30bfc47788c83601d48b0f/core/src/main/resources/jenkins/model/Jenkins/sidepanel.jelly#L26 :eyes:

**Review by Vlatombe — APPROVED** [review]

**Review by dwnusbaum — APPROVED** [review]
FWIW, there was a similar issue with views in folders caused by HashiCorp Vault plugin, fixed by https://github.com/jenkinsci/hashicorp-vault-plugin/pull/336 and made more robust in core by https://github.com/jenkinsci/jenkins/pull/9653, leading to the same recursion as in https://github.com/jenkinsci/cloudbees-folder-plugin/pull/447.

Do you have an `OldDataMonitor` warning for an observed loading failure? I wonder if any other XStream robustness improvements are possible here.

**Comment by jglick** [comment]
> Do you have an `OldDataMonitor` warning for an observed loading failure?

No, `OldDataMonitor` is only triggered when XStream unmarshalling completed with some recoverable issues of known categories, like missing fields. The situation here is not necessarily about XStream; I used invalid XML for the test case but I think I saw the bug in response to some transient `IOException` loading `config.xml`.

**Comment by timja** [comment]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Pull request merged**
