### PR TITLE
github-organization-folder is deprecated

### PR DESCRIPTION
**Pull request by jglick**
# Description

Follows up https://github.com/jenkinsci/github-organization-folder-plugin/pull/39.

### Changelog entries

None required I think.

### Desired reviewers

@reviewbybees

By the way @i386 you probably want to recommend `blueocean` on new installs now, right?

### CODE REVIEW

**Comment by i386** [comment]
@jglick do you mean update it in the aggregator?

**Comment by daniel-beck** [comment]
Related: https://github.com/jenkins-infra/jenkins.io/pull/807

**Comment by oleg-nenashev** [comment]
I m fine with this change.
Regarding BlueOcean, IMHO it requires voting in the Developer Mailing list or at the governance meeting. AFAIK we used this process to approve the initial list. @daniel-beck please correct me if I am wrong

**Comment by jglick** [comment]
> do you mean update it in the aggregator?

@i386 no, I mean edit the same file I am editing in this PR.

**Comment by oleg-nenashev** [comment]
🐝 and @reviewbybees done.
Passing to @jenkinsci/code-reviewers since it is a global change in Installation Wizard

**Comment by daniel-beck** [comment]
Seems like a straightforward adaptation after a plugin restructuring with no effective functional difference, therefore should not need extended review and discussion.

**Review by daniel-beck — APPROVED** [review]

**Comment by jglick** [comment]
> a straightforward adaptation after a plugin restructuring with no effective functional difference

Exactly.

**Pull request merged**
