### PR TITLE
[JENKINS-49543] Old versions of Tomcat also failed to serialize classes from Jenkins modules

### PR DESCRIPTION
**Pull request by jglick**
See [JENKINS-49543](https://issues.jenkins-ci.org/browse/JENKINS-49543). Amends #3264.

### Proposed changelog entries

* JENKINS-49543: fix for JEP-200 issues in old versions of Tomcat was not complete; known to cause errors at least when saving user configurations.

### Desired reviewers

@reviewbybees @jenkinsci/code-reviewers

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
🐝 makes sense though "update tomcat" should be generally enough

**Review by daniel-beck — APPROVED** [review]

**Comment by jglick** [comment]
@reviewbybees done

**Comment by oleg-nenashev** [comment]
Test failure is unrelated && fixed in https://github.com/jenkinsci/jenkins/pull/3310

**Comment by oleg-nenashev** [comment]
Raised a question about backporting to 2.107.1 in the JIRA ticket

**Pull request merged**
