### PR TITLE
Translations: Update the Mandarin localization

### PR DESCRIPTION
**Pull request by lilyJi**
Translate few HTML resources to Mandarin

### CODE REVIEW

**Comment by daniel-beck** [comment]
Is there a reason you're going with the HTML entities instead of UTF-8 characters?

**Comment by lilyJi** [comment]
Hi Daniel,
All my translation files are encoded in UTF-8, which is a requirement of translating static HTML resources. I think I didn't use HTML entities. This is my first small commit, just want to make sure I'm doing the right thing. So if there is any adjustment I need to make, please tell me. Thank you so much!

**Comment by oleg-nenashev** [comment]
AFAIK we do not have active contributors speaking Chinese, so I am not sure how do we proceed here after the formal check.

**Comment by fengxx** [comment]
It is very hard to view the char encoded in html entity, such as 
{code}
&#x542F;&#x7528;&#x9009;&#x9879;&#x540E;&#xFF0C;Jenkins&#x4F1A;&#x963B;&#x6B62;&#x8BE5;&#x9879;&#x76EE;&#x7684;&#x5EFA;&#x7ACB;&#x5982;&#x679C;&#x8BE5;&#x9879;&#x76EE;&#x7684;&#x5B50;&#x9879;&#x76EE;&#x5728;&#x961F;&#x5217;&#x4E2D;&#x6216;&#x6B63;&#x5728;&#x6784;&#x5EFA;&#x3002;
{code}

It will be better if using 简体中文。

**Comment by daniel-beck** [comment]
@lilyJi See @fengxx's response, that was what I was trying to point out.

**Comment by daniel-beck** [comment]
Superseded by #2865.

**Pull request closed without merging**
