### PR TITLE
[JENKINS-54136] Use per-trial correlation IDs

### PR DESCRIPTION
**Pull request by daniel-beck**
See [JENKINS-54136](https://issues.jenkins-ci.org/browse/JENKINS-54136).

### Proposed changelog entries

* JENKINS-54136: Use per-trial correlation IDs

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [n/a] For dependency updates: links to external changelogs and, if possible, full diffs

### CODE REVIEW

**Review by jvz — APPROVED** [review]
LGTM. Are these correlation ids available for logging in general? Could be useful when debugging from a log file where multiple users are online concurrently.

**Comment by rtyler** [comment]
This corresponds to jenkins-infra/uplink#19

**Comment by daniel-beck** [comment]
On-holding this until https://github.com/jenkins-infra/uplink/issues/15#issuecomment-432892749 is acknowledged by @rtyler

**Review by rtyler — APPROVED** [review]
The generated correlation IDs match what we're capable of generating in uplink

**Comment by daniel-beck** [comment]
To be merged only once the PR build passes.

**Pull request merged**
