### PR TITLE
[JENKINS-46282] - Update WinSW from 2.1.0 to 2.1.2

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Fixes [JENKINS-46282](https://issues.jenkins-ci.org/browse/JENKINS-46282), which impacts the default installation.
Also updates Parent POM in the module

Full list of fixes:

Downstream of https://github.com/jenkinsci/windows-slave-installer-module/pull/16

Full Diffs: 
* https://github.com/kohsuke/winsw/compare/winsw-v2.1.0...winsw-v2.1.2
* https://github.com/jenkinsci/windows-slave-installer-module/compare/windows-slave-installer-1.9...windows-slave-installer-1.9.1

### Proposed changelog entries

3 Bugs:

* JENKINS-46282 - Update Windows service wrapper from 2.1.0 to 2.1.2: `stopTimeoutMs` in Runaway Process Killer extension was ignored, default configuration of the Master service was impacted.
  * WinSW changelog: https://github.com/kohsuke/winsw/blob/master/CHANGELOG.md
  * Module changelog: https://github.com/jenkinsci/windows-slave-installer-module/blob/master/CHANGELOG.md
* Windows service wrapper 2.1.2: Prevent printing of log entries in the `status` command
  * WinSW Issue 206 - https://github.com/kohsuke/winsw/issues/206)
* Windows service wrapper 2.1.2: Prevent hanging of the stop executable when its logs are not being drained do the parent process
  * WinSW Issue 218 - https://github.com/kohsuke/winsw/issues/218

No tests in the Jenkins core, it is covered by WinSW autotests.

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@reviewbybees

### CODE REVIEW

**Review by alexanderrtaylor — APPROVED** [review]
LGTM with a successful build
🐝

**Comment by oleg-nenashev** [comment]
@reviewbybees done since there was no changes in the released version

**Comment by oleg-nenashev** [comment]
@olblak @rtyler This is due to that Jenkins restart, right?

**Comment by oleg-nenashev** [comment]
restarting CI, it may help

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers @daniel-beck WDYT though? 2.1.2 has been released in early July, no regressions reported by WinSW users.

**Comment by MarkEWaite** [comment]
Does [issue 237](https://github.com/kohsuke/winsw/issues/237) affect this code?  

If so, does this change make it any worse?

**Comment by oleg-nenashev** [comment]
@MarkEWaite If that issue it real, it affects Jenkins as well (starting from 2.50). But I have been unable to reproduce it so far. It may be something specific to the .NET version. This change does not make it worse anyway

**Review by MarkEWaite — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Test is successful, 🚢 🇮🇹

**Pull request merged**
