### PR TITLE
Update notifying badges in dropdowns

### PR DESCRIPTION
**Pull request by SomasekharSunkari**
See [JENKINS-71326](https://issues.jenkins.io/browse/JENKINS-71326).

### Testing done
Screenshot 2023-12-21 145143

Screenshot 2023-12-21 150118

### Proposed changelog entries

- JENKINS-71326, human-readable text

#If any changes need to made tell me ! if it was not enough ! Thank You !

### CODE REVIEW

**Review by mawinter69 — CHANGES_REQUESTED** [review]
I think it needs more than just changing the color to orange. The badges can have different colors, that correspond to the severity of the badge (danger=red, warning=orange, info=blue). And this should be also visible in the dropdowns accordingly.

**Comment by daniel-beck** [comment]
Also needs to consider theme support (e.g. https://plugins.jenkins.io/dark-theme/ )

**Comment by SomasekharSunkari** [comment]
Ok I will update this thing . Thank you!

**Comment by SomasekharSunkari** [comment]
can any of you please tell me how to add class names to html elements in the codebase ?

**Comment by mawinter69** [comment]
while working on badges, `<l:task` in sidepanels also supports badges. Those should also get coloured.
image

**Comment by SomasekharSunkari** [comment]
how to fix codeing styles with prettier ? can anyone guide.

**Comment by krisstern** [comment]
Hi @SomasekharSunkari,
Maybe try setting up `prettier` for Java: https://github.com/jhipster/prettier-java? You will need to define some rules though to begin with.

**Comment by SomasekharSunkari** [comment]
Can you tell me the rules to define with it ?

**Comment by mawinter69** [comment]
This PR is obsolete, we already have another PR #8853 that is basically ready

**Comment by krisstern** [comment]
Cool 👍🏼

**Comment by SomasekharSunkari** [comment]
Ok I will move to another !

**Pull request closed without merging**
