### PR TITLE
[JENKINS-46652] Check Computer.BUILD permission only on heavyweight tasks

### PR DESCRIPTION
**Pull request by jglick**
See [JENKINS-46652](https://issues.jenkins-ci.org/browse/JENKINS-46652). Integration tests will be downstream.

### Proposed changelog entries

* Pipeline builds could not be started if the Authorize Project plugin was configured to associate the build with a user to whom the authorization strategy was configured to deny **Agent/Build** permission on the master node.

### Desired reviewers

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by daniel-beck** [comment]
Similar domain as #3242 (flyweight task handling on master).

**Comment by oleg-nenashev** [comment]
I want to review it, but most likely I will have no time for that this week.

**Comment by oleg-nenashev** [comment]
I would feel much more comfortable about that if MatrixProject was a heavy task

**Comment by daniel-beck** [comment]
@oleg-nenashev  The parent doesn't do anything, does it? Except checkout but that's not really a permissions issue.

**Comment by jglick** [comment]
Exactly—the matrix parent flyweight task just does a checkout, which should not require any special permission.

**Comment by oleg-nenashev** [comment]
@jglick @daniel-beck Also Matrix Aggregators. Including these ones... https://github.com/jenkinsci/postbuildscript-plugin/blob/ed3415b53c1fbd1e60592d2957904fbabbacde88/src/main/java/org/jenkinsci/plugins/postbuildscript/ConfigurableMatrixAggregator.java

**Comment by oleg-nenashev** [comment]
Please do not merge it this week. I want to do a careful review of this PR

**Comment by jglick** [comment]
That one should be using https://github.com/jenkinsci/postbuildscript-plugin/pull/15.

**Comment by oleg-nenashev** [comment]
As discussed with @daniel-beck, the proposal is to implement a system property, which at least allows to opt-out to the original behavior

**Review by oleg-nenashev — APPROVED** [review]
🐝 and @reviewbybees done

**Comment by oleg-nenashev** [comment]
Not sure what's up with the test, but it's definitely unrelated to this PR. Some tests would be cool tho

screen shot 2018-02-23 at 20 32 26

**Comment by jglick** [comment]
> Some tests would be cool

There are two downstream PRs which each independently verify the effectiveness of the change (as can be seen by setting the default to `false`). It would be possible to write some sort of mock test in this repository if it is considered necessary.

**Comment by oleg-nenashev** [comment]
Any core team member is welcome to merge it. I am not fully comfortable with the change though I approved it after the opt-out option (@jglick knows my concerns). I am not ready to take responsibility for the merge as a sole approver.

**Review by svanoort — APPROVED** [review]
Looks OK to me

**Review by daniel-beck — COMMENTED** [review]
Belated +1

**Comment by oleg-nenashev** [comment]
Thanks @daniel-beck @svanoort! I will work a bit on the contributing guidelines to clarify how the merge process works. I would guess there was a mis-expectation that I merge it after approval, and I apologize for an extra delay caused by that.

**Pull request merged**
