### PR TITLE
[JENKINS-62599] Remove the Italian resources from core

### PR DESCRIPTION
**Pull request by AlessandroMenti**
Remove the Italian resources from core Jenkins as this localization is going to be managed by the Italian localization plugin.

No tests are included because there is no code change.

This PR depends on [HOSTING-980](https://issues.jenkins-ci.org/browse/HOSTING-980).

See [JENKINS-62599](https://issues.jenkins-ci.org/browse/JENKINS-62599).

### Proposed changelog entries

* Italian localization removed from Jenkins core and moved to the [Italian localization plugin](https://github.com/jenkinsci/localization-it-plugin).

### Proposed upgrade guidelines

==== Install the Italian localization plugin if needed
https://issues.jenkins-ci.org/browse/JENKINS-62599[JENKINS-62599]

The Italian localization has been moved from Jenkins core to the [Italian localization plugin](https://github.com/jenkinsci/localization-it-plugin) in order for it to be updated more frequently. You will have to install that plugin if you used Jenkins in Italian and would like to continue showing its interface in that language.

### Submitter checklist

- [X] (If applicable) Jira issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [X] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

None.

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by daniel-beck** [comment]
I previously left a comment in https://github.com/jenkinsci/jenkins/pull/4306 that I think largely applies here too.

Of course the situation here is different: You have two previous contributions to Jenkins core in this space (https://github.com/jenkinsci/jenkins/pull/3075, https://github.com/jenkinsci/jenkins/pull/3232) and both fairly substantial improvements to the Italian localization.

On the other hand, they're both several years old, and were accepted into core with only slight delays. These also look like your only (pull request) contributions to Jenkins so far. It's not clear to me that the primary reason to move translations out of core and components -- streamlining otherwise blocked contributions -- really applies here, as it was the case with the Chinese translations that ultimately led to the creation of the JEP.

There's a risk that we move translations out, and that the localization plugin withers if you lose interest or simply don't have the time to maintain it, making the situation worse than it is now: Any prospective contributor would need to deal not just with the localization tooling, but possibly also the plugin release processes and project governance.

What are your thoughts about this?

**Comment by AlessandroMenti** [comment]
Hi @daniel-beck, thanks for your comment - given that I haven't fullowed much the project lately, I assumed (perhaps mistakenly...) that splitting the localization files into a separate plugin was the preferred choice.

I fully agree with you about the risk of moving the localization files out of core, especially given that - as far as I know - there are no other users who have recently contributed to the Italian localization, or a community (as is the case with the Chinese SIG) who is willing to maintain it as a team in case I will be unable to do so in the future.

The only argument in favor of a separate plugin, at this point, would be that - in my opinion - it would be easier for me to translate plugin resources only in one place instead of potentially opening multiple pull requests in the corresponding repositories.

In any way, I'll be fine with both choices (keeping translations in core vs. moving them), just let me know how I should proceed.

**Comment by daniel-beck** [comment]
Thanks for your response!

> I assumed (perhaps mistakenly...) that splitting the localization files into a separate plugin was the preferred choice.

Maybe? It's not a superior approach in all cases, perhaps not even in most cases. There's trade-offs involved. If there's an active community (or perhaps just one really active, regular contributor, as it was with Chinese) for a localization, it can make sense to move to the localization plugin model. This has many benefits:

* No more waiting for reviews by potentially unresponsive maintainers who don't know the language in the first place
* No more waiting for plugin releases with the new translations
* Easier to incrementally improve translations over time
* Easier to make large scale terminology cleanups across components
* Gathering a language community in one spot to facilitate collaboration
* Backfilling translations for older releases is possible.

I already listed drawbacks above.

---

I think Italian, like Turkish before, isn't in a situation where it makes sense to _move_ to a localization plugin. Just the migration to the localization plugin can be a lot of work that doesn't directly benefit users (and in some cases can even be sort of a regression).

And even when some of the problems solved by such a plugin crop up, it could make sense to put just _new translations_ into the plugin (e.g. translating a new plugin, put those into `localization-it` instead of the plugin directly), while, at least for a time, keeping already translated components as is.

So, personally, right now, I don't think this particular change is beneficial, and I'm unsure that the Italian Localization Plugin is a good idea (assuming you have no co-contributors in that space). That said, I can easily see it working out in the future, if you can get a few co-contributors to work with you on improving the Italian localization. That would be great and I'd be happy to see another plugin in that space appear and thrive.

FWIW the good thing about how the localization and `localization-support` is structured is that you can always start with the localization plugin by grabbing files added or changed in unmerged PRs and just put them into the same top-level directory. IOW, you can contribute as you always have, and only when you encounter problems would you start a localization plugin, and no work will have been lost.

Obviously, this is only one person's opinion. Let's keep this PR around for a while to see what others thing.

**Comment by oleg-nenashev** [comment]
If somebody is willing to maintain the localization plugin, I do not mid if we introduce it. But it is a significant effort to get it running and to gradually move localizations from plugins.

**Comment by AlessandroMenti** [comment]
I guess we can go with the following solution: for the time being, I will just update the resources in Jenkins core, as well as the ones of the plugins I am going to translate. Should the number of translated plugins become too high, we can move the translations to a separate plugin. Does that sound good for you?

**Comment by daniel-beck** [comment]
@AlessandroMenti That seems like a pragmatic approach (note the problem is less the number of plugins with translations, but rather unmerged/unreleased pull requests).

**Comment by AlessandroMenti** [comment]
OK, I'll close this PR and the associated Jira requests then and I'll open a new one to integrate the updated Italian resources. Thanks!

**Comment by AlessandroMenti** [comment]
See https://github.com/jenkinsci/jenkins/pull/4810 for the integration of the new Italian translation into core.

**Pull request closed without merging**
