### PR TITLE
[JENKINS-58736] Correction of /assets throwing 500

### PR DESCRIPTION
**Pull request by Wadeck**
See [JENKINS-58736](https://issues.jenkins-ci.org/browse/JENKINS-58736).

### Proposed changelog entries

* Internal: prevent an exception to be thrown when requesting empty asset name

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [n/a] For dependency updates: links to external changelogs and, if possible, full diffs

### CODE REVIEW

**Review by jvz — APPROVED** [review]
LGTM. No manual testing performed.

**Comment by alecharp** [comment]
I'm wondering how this changeset (which seems good) is making another test failing, only on Java 8 build. 
@Wadeck could you close and re-open your PR to see if the test is flaky or not?

**Comment by Wadeck** [comment]
@alecharp thx for the ping!

`Linux-jdk8 / Linux Publishing / hudson.slaves.PingThreadTest.failedPingThreadResetsComputerChannel`
failing with:
```
   9.934 [id=14]	INFO	hudson.slaves.ChannelPinger$1#onDead: Ping failed. Terminating the channel slave0.
java.util.concurrent.TimeoutException: No ping
	at hudson.slaves.PingThreadTest.failedPingThreadResetsComputerChannel(PingThreadTest.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:556)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Build restarted.

**Comment by Wadeck** [comment]
Second attempt: the ATH failed to compile but all the tests passed.
Build re-re-started.

**Review by oleg-nenashev — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Will merge tomorrow if no negative feedback

**Comment by Vikas92155** [comment]
Hello
Can i disclose it

Thanks
Vikas

**Comment by Wadeck** [comment]
@Vikas92155 As it was not considered as a vulnerability, there is no "embargo" there.

**Pull request merged**
