### PR TITLE
Add marker iterface for an Item to indicate no disk syncing

### PR DESCRIPTION
**Pull request by suryagaddipati**
This is a fix for  trying to load an item from database instead of disk during my plugin's startup , but jenkins seems to assuming that everything is being loaded from the disk and removing my dynamically loaded items.

### CODE REVIEW

**Comment by KostyaSha** [comment]
I will prefer to see annotation or field rather then marker interface.

**Comment by oleg-nenashev** [comment]
If we add such annotation, it should be taken into the account in many methods operating with the disk. Before this update the implementation may confuse API users.

Probably, <code>Saveable</code> could address your case

**Comment by suryagaddipati** [comment]
@oleg-nenashev Despite the javadoc comments in `Savable`, it doesn't look like it has anything to do with xml file on the disk. I am using the `save()` method to save stuff to the database.

**Comment by daniel-beck** [comment]
> I will prefer to see annotation or field rather then marker interface (if it possible).

@KostyaSha Could you elaborate what the effective differences between marker interface and annotation are and why you prefer one over the other?

**Comment by KostyaSha** [comment]
@daniel-beck i have bad example - EphemeralNode

**Comment by vjuranek** [comment]
Instead of adding some markers (i.e. workarounds), I'd prefer to implement regular extension point which would allow to load jobs from various sources, XML files on disk being on of possible sources, so that any markers won't be needed and all jobs are treated equally.

**Comment by suryagaddipati** [comment]
@vjuranek Jenkins code currently doesn't treat non-xml jobs any differently. 
The issue here is fix for this behavior. 

https://github.com/suryagaddipati/jenkins/blob/master/core/src/main/java/jenkins/model/Jenkins.java#L2673...LL2686

I am unclear why that syncing is happening , Ideally I would want to remove the code above but I am not sure what the implications of that would be.

**Comment by vjuranek** [comment]
> Jenkins code currently doesn't treat non-xml jobs any differently. 

obviously it does, otherwise you didn't issue this PR :-)

I'm not sure how you currently the jobs from DB, but Jenkins should be aware about it and it should IMHO be reflected also in the code you are referring to. Adding some ad hoc marker interfaces will make it IMHO even worse (in sense that it adds some jobs categories, so that if we want to allow more job sources in the future, we will have to deal with these categories and possible special behavior for each this category)

**Comment by suryagaddipati** [comment]
> I'm not sure how you currently the jobs from DB,

I load them up  on plugin load and do `Jenkins.getInstance().addItem` 

>Adding some ad hoc marker interfaces will make it IMHO even worse (in sense that it adds some jobs categories, so that if we want to allow more job sources in the future, we will have to deal with these categories and possible special behavior for each this category)

 I am open to other suggestions and I can work on it over the weekend. This is a real blocker for my plugin.

**Comment by jglick** [comment]
Agreed with @vjuranek that this looks like a hack in search of a proper extension point.

**Comment by suryagaddipati** [comment]
Agree that this looks like a hack. 

For me to comeup with a proper solution, I need to know why this disk syncing is there in the first place. 

What happens if  disk syncing code is deleted? 

Ideally I would like to delete the disk syncing code, but I am not sure what the consequences of that would be,.

@jglick @KostyaSha @kohsuke @vjuranek @oleg-nenashev

**Comment by KostyaSha** [comment]
See comment before this block :)

**Comment by suryagaddipati** [comment]
@KostyaSha how embarrassing :) . 

Ok so this functionality exists for "Reloading Items from Disk" .

So I am guessing a good solution would be 

1. Change the wording in manage page and remove the word "Disk" 
2. Invert the responsibility of checking to see if something needs to be deleted to item. 

I am closing this PR for now. Will propose the change described above in a different pr.

**Pull request closed without merging**
