### PR TITLE
Backporting for LTS 2.375.2

### PR DESCRIPTION
**Pull request by krisstern**
```shell
Latest core version: jenkins-2.382

Fixed
-----

JENKINS-70199           Minor                   2.382
        Distributed builds telemetry
        https://issues.jenkins.io/browse/JENKINS-70199

JENKINS-70105           Major                   2.379
        Slow down re-connects when using websockets
        https://issues.jenkins.io/browse/JENKINS-70105

JENKINS-70103           Major                   2.379
        Agent websocket sessions not cleared up on connection close
        https://issues.jenkins.io/browse/JENKINS-70103

JENKINS-70083           Minor                   2.379
        Update bundled script-security and junit plugins
        https://issues.jenkins.io/browse/JENKINS-70083

JENKINS-69587           Minor                   2.378
        Pipeline console live viewing is bouncing (regression in 2.359)
        regression
        https://issues.jenkins.io/browse/JENKINS-69587

```

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7517"></a>

### CODE REVIEW

**Comment by NotMyFault** [comment]
Including 1b0eef58dee95a7b15d25ecaaa65b3daaf7424f0 requires a bunch of more plugin updates, to satisfy enforcer.
While evaluating the backports for .1, I left this commit out intentionally, given the amount of needed updates, I couldn't ensure stability is warranted without introducing undiscovered regressions, based on the short timeframe this set was tested on.

**Comment by MarkEWaite** [comment]
> Including [1b0eef5](https://github.com/jenkinsci/jenkins/commit/1b0eef58dee95a7b15d25ecaaa65b3daaf7424f0) requires a bunch of more plugin updates, to satisfy enforcer. While evaluating the backports for .1, I left this commit out intentionally, given the amount of needed updates, I couldn't ensure stability is warranted without introducing undiscovered regressions, based on the short timeframe this set was tested on.

I thought that we needed to include that change because the older versions of those plugins have known security vulnerabilities.  The 2.375.2 release is scheduled for Jan 11, 2023.  I think that we'll have enough time to test that change.

**Comment by NotMyFault** [comment]
A working sample is available at https://github.com/jenkinsci/jenkins/pull/7392

> The 2.375.2 release is scheduled for Jan 11, 2023. I think that we'll have enough time to test that change.

Agreed. There are no open regressions from past weeklys related to this item, I'm aware of.

**Comment by krisstern** [comment]
I see

**Review by basil — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]

**Pull request merged**
