### PR TITLE
[JENKINS-36908] Make sure that the All view is created

### PR DESCRIPTION
**Pull request by alvarolobato**
[JENKINS-36908](https://issues.jenkins-ci.org/browse/JENKINS-36908)
@reviewbybees

### CODE REVIEW

**Comment by jtnord** [comment]
:bee: do we know why @kohsuke  changed this in a seemingly unrelated PR to begin with?

**Comment by alvarolobato** [comment]
@jtnord no, I pinged him asking.

**Comment by amuniz** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
IMHO 🐛 . From what I see this change impacts the old-old feature (hack?) allowing replacing or even deleting All views: https://wiki.jenkins-ci.org/display/JENKINS/Editing+or+Replacing+the+All+View. Smells like a breaking change for instances having an altered All view, because Jenkins will attempt to add another AllView now.

I think the check against <code>AllView</code> class is errorneous.

**Comment by daniel-beck** [comment]
Why not just restore what @kohsuke removed?

**Comment by daniel-beck** [comment]
:bug: No way. The *All* view is the first thing I usually get rid of. We even document how to remove or change it:
https://wiki.jenkins-ci.org/display/JENKINS/Editing+or+Replacing+the+All+View

> Needs a more intelligent behavior (e.g. check against view name)

Could you elaborate? I frequently have a view named `All` that contains projects matching `.*` so I can customize views.

**Comment by alvarolobato** [comment]
@jtnord @oleg-nenashev @daniel-beck I've changed the behaviour to how it was before: if you have a primary view it won't create the All view.

**Comment by daniel-beck** [comment]
LGTM :+1: (to be merged with squash)

**Comment by alvarolobato** [comment]
@daniel-beck can I get a bee to remove the bug?

**Comment by jtnord** [comment]
:bee:

**Comment by daniel-beck** [comment]
:bee: it is.

**Comment by alvarolobato** [comment]
@oleg-nenashev can you reconsider removing the bug?

**Comment by oleg-nenashev** [comment]
🐝 for the current implementation.
A test would be nice :P

**Comment by alvarolobato** [comment]
@oleg-nenashev tests added

**Comment by oleg-nenashev** [comment]
👍

**Comment by alvarolobato** [comment]
@reviewbybees done

**Comment by alvarolobato** [comment]
@oleg-nenashev  or @daniel-beck  could you merge this please?

**Comment by amuniz** [comment]
@daniel-beck It would be great to see this backported in the next LTS

**Comment by daniel-beck** [comment]
@amuniz Up to @olivergondza

**Pull request merged**
