### PR TITLE
JENKINS-61398 Fix empty SCM block after submit

### PR DESCRIPTION
**Pull request by timja**
See [JENKINS-61398](https://issues.jenkins-ci.org/browse/JENKINS-61398).

### Proposed changelog entries

* Entry 1: JENKINS-61398, Fixed SCM configuration via UI
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

### CODE REVIEW

**Comment by daniel-beck** [comment]
This indicates we might have similar problems in other forms as well, potentially in plugins?

**Comment by timja** [comment]
> This indicates we might have similar problems in other forms as well, potentially in plugins?

Possibly, I've searched core and wasn't able to find anymore issues,
I've checked the first page of results and didn't find an issue but there certainly could be more

https://github.com/search?q=org%3Ajenkinsci+radioBlock&type=Code

It depends on whether we want to rollback, or fix the current implementation and see if there's more issues.

I would like to actually find an issue rather than block on a potential issue that could exist.

**Review by jglick — CHANGES_REQUESTED** [review]
As per

> This indicates we might have similar problems in other forms as well, potentially in plugins?

I would prefer #4559 until the problem is better studied.

**Comment by timja** [comment]
Ok, closing this then, I don't have time to look at it was just seeing if there was a quick fix that could be applied on top, so the feature doesn't need reverting, posted my investigation on the ticket anyway

**Comment by oleg-nenashev** [comment]
A safe way could be introduce a new set of filtered controls and to gradually adopt them. I agree with @jglick that #4559 is likely preferable for now, because otherwise we are likely to have whack-a-mole in open-source and 3rd party proprietary plugins

**Comment by oleg-nenashev** [comment]
Lemme keep it open for a while for investigation

**Comment by rsandell** [comment]
OK leaving this to @oleg-nenashev

**Comment by daniel-beck** [comment]
Removing the regression-fix label as the regression has been resolved differently.

**Comment by MRamonLeon** [comment]
@oleg-nenashev I propose for close this PR because there is no movement for a while

**Comment by timja** [comment]
FWIW, 3 plugins in jenkinsci org are using this patten:

- https://github.com/jenkinsci/vectorcast-execution-plugin/
- https://github.com/jenkinsci/kubernetes-cd-plugin/
- https://github.com/jenkinsci/hockeyapp-plugin/

**Pull request closed without merging**
