### PR TITLE
Backporting for LTS 2.319.1

### PR DESCRIPTION
**Pull request by cathychan**
Prep work for https://github.com/jenkins-infra/release/issues/191

```
Fixed
-----

JENKINS-67063		Blocker   		2.320
	Unstash with symlinks fails
	regression
	https://issues.jenkins.io/browse/JENKINS-67063

JENKINS-67061		Minor     		2.320
	ConfigDirectory overloads the wrong load (should be load2)
	regression
	https://issues.jenkins.io/browse/JENKINS-67061

JENKINS-67028		Minor     		2.320
	2.318 build history is missing a hyperlink
	regression
	https://issues.jenkins.io/browse/JENKINS-67028

JENKINS-67002		Minor     		2.320
	if an Exception is thrown in a RestartListener Jenkins is left in a zombie state
	https://issues.jenkins.io/browse/JENKINS-67002

JENKINS-66993		Major     		2.320
	java.lang.LinkageError: loader jenkins.util.AntClassLoader attempted duplicate abstract class definition
	regression
	https://issues.jenkins.io/browse/JENKINS-66993

JENKINS-66969		Minor     		2.321
	Ongoing first build disappears from build history
	regression
	https://issues.jenkins.io/browse/JENKINS-66969
```

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

### Proposed changelog entries

* Entry 1: Issue, Human-readable Text
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by cathychan** [comment]
@timja Please add `into-lts` label.

**Comment by timja** [comment]
Looking at the comments in https://issues.jenkins.io/browse/JENKINS-66947 seems to be recommended to not include it?

cc @jtnord / @jglick / @daniel-beck

**Comment by timja** [comment]
@jtnord what's the reason for including https://issues.jenkins.io/browse/JENKINS-66930 ?

**Comment by jtnord** [comment]
> Looking at the comments in https://issues.jenkins.io/browse/JENKINS-66947 seems to be recommended to not include it?
> 
> cc @jtnord / @jglick / @daniel-beck

it is in there if we like it or not..
https://github.com/jenkinsci/jenkins/commit/e7d52169dca11007f6acb058f233d6bcb3f8ba2f
image

SO this seems like maybe the PR here is not correct (or that the reporting is not correct) (have not checked)

**Comment by jtnord** [comment]
> @jtnord what's the reason for including https://issues.jenkins.io/browse/JENKINS-66930 ?

Same again - that ship has sailed.    https://github.com/jenkinsci/jenkins/commit/9cf91882de07be5f6890ff2b6acf0c1a05435bc6

At this point I think the report is incorrect?

**Comment by timja** [comment]
Ah sure all fine then

**Comment by jtnord** [comment]
the [commits](https://github.com/jenkinsci/jenkins/pull/5920/commits) in GitHub show 6 commits which differs from the summary here?

image

**Comment by cathychan** [comment]
It turns out some of the issues had the `lts-candidate` label in Jira, but were actually already released before 2.319.
I'll remove the labels from those tickets and generate the summary again. There is no change to the content of this PR.

**Comment by cathychan** [comment]
Updated the summary.
Sorry for the confusions!

**Review by timja — APPROVED** [review]

**Review by jglick — APPROVED** [review]
Java changes look reasonable. I am not familiar with the GUI changes.

**Comment by cathychan** [comment]
@timja or anyone else, can you restart the build? Looks like a network issue.

**Comment by timja** [comment]
Done yeah it’s been unstable the last few days

**Comment by timja** [comment]
RC is https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/main/jenkins-war/2.319.1-rc31657.35d85d1fdb91/jenkins-war-2.319.1-rc31657.35d85d1fdb91.war

**Pull request merged**
