### PR TITLE
Revert "[JENKINS-62446] adding CasC compatibility to Global tool > Gl…

### PR DESCRIPTION
**Pull request by daniel-beck**
…oba Maven"

This reverts commit 618ccc39c1b0a313cabdf0544eb8f3861a836b7c.

Per https://github.com/jenkinsci/jenkins/pull/5008#pullrequestreview-527164239

### Proposed changelog entries

* Revert improper fix for JENKINS-62446 in 2.266

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by jglick — APPROVED** [review]
At least until there is some analysis for why JCasC is running into trouble.

**Review by MarkEWaite — APPROVED** [review]

**Review by res0nance — APPROVED** [review]

**Comment by timja** [comment]
I'll try have a look this week, don't rush to merge this please

**Comment by res0nance** [comment]
> I'll try have a look this week, don't rush to merge this please

The weekly is already out so I'll mark this `On Hold` until you get back on this

**Comment by timja** [comment]
So the reason for this is both `MavenGlobalConfig` and `MavenInstallation` are in the `Tool` category and have the same symbol for a describe-able

https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/jenkins/mvn/GlobalMavenConfig.java#L19-L22

and they have the same symbol which just isn't going to work in JCasC.

See the test in jcasc https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/integrations/src/test/resources/io/jenkins/plugins/casc/GlobalToolGlobalMavenTest.yaml for the yaml setup.

-1 for this change unless anyone has better ideas

the symbols could be renamed to `mavenConfiguration` and `mavenTool` to make their use clearer?

**Review by timja — COMMENTED** [review]
reviewed

**Comment by jglick** [comment]
> the `Tool` category

So a bug in `configuration-as-code`: it should be using separate subsections for `ToolInstallation`s vs. `GlobalConfiguration`s to avoid ambiguity and conflicts.

**Comment by jglick** [comment]
> the symbols could be renamed to `mavenConfiguration` and `mavenTool`

https://github.com/jenkinsci/structs-plugin/blob/745286d2d7a362a6b39579073fb2f01bb0f5c3b8/annotation/src/main/java/org/jenkinsci/Symbol.java#L21-L23

**Comment by timja** [comment]
> > the `Tool` category
> 
> So a bug in `configuration-as-code`: it should be using separate subsections for `ToolInstallation`s vs. `GlobalConfiguration`s to avoid ambiguity and conflicts.

@oleg-nenashev any thoughts here?

the UX of that doesn't sounds great.

This is the only case I've seen this issue in

**Comment by jglick** [comment]
Whether it is _fixable_ in `configuration-as-code` without making a bigger mess, I have no idea, just describing the intended design of `@Symbol`.

**Comment by daniel-beck** [comment]
The sample config shows how the `maven` installer is fine, only `maven` global configuration and `maven` tool definition clash. This seems to be all on JCasC and while we could keep the workaround, I would consider it likely to happen again – basically, IIUC, for any tool that is both a "real" tool (`ToolInstallation`) and has a global configuration. JCasC ignored the potential for otherwise legal name clashes in its config file format, so it should be changed to address this.

**Comment by daniel-beck** [comment]
> unless anyone is willing to suggest a fix which actually adds supports for the use-case

👎 That is externalization of costs for fixing a bad plugin design.

**Comment by daniel-beck** [comment]
It's not necessarily just core either — https://github.com/daniel-beck/git-plugin/commit/f38ff7fb48e80fa67e68f3e19819ce80826c7f51 is a reasonable change that is effectively blocked by the design of JCasC.

https://groups.google.com/g/jenkinsci-dev/c/nnfreZqwIJ4/m/osaWsPuOBgAJ looks like Jesse saw this coming.

**Comment by jglick** [comment]
https://github.com/daniel-beck/git-plugin/commit/f38ff7fb48e80fa67e68f3e19819ce80826c7f51 is tricky BTW because of metasteps: [JENKINS-37227](https://issues.jenkins.io/browse/JENKINS-37227)

**Review by MRamonLeon — APPROVED** [review]

**Comment by daniel-beck** [comment]
This got several approvals and no rejections, so I plan to merge it in the next day or so.

Filed https://issues.jenkins.io/browse/JENKINS-64979 for the backport to keep LTS behavior stable.

**Comment by oleg-nenashev** [comment]
Stable behavior in LTS would mean having a defect in JCasC without resolution for users.
I agree that JCasC needs to be patched for the best possible fix. That might not be possible to implemente until the 2.277.1 release though

**Comment by daniel-beck** [comment]
Well, yeah, it's a trade-off. The original workaround PR should never have been merged, or this one more quickly. Neither happened. My expectation is that this change will be merged at some point, so it's best IMO to do so now so we can get it into 2.277.x.

**Pull request closed without merging**
