### PR TITLE
[WiP] [FIXED JENKINS-28401] Move disable/enable button to sidepanel

### PR DESCRIPTION
**Pull request by olivergondza**
Small step to remove the clutter on the right side of the screen.

Before:
before

After:
after

### CODE REVIEW

**Comment by jtnord** [comment]
While I am neither +1 nor -1 on the change as a whole (there are likely other ways to make the existing UI better) I do think the choice of the padlock icon infers the wrong context to the user.  To me it implies something is secure or insecure and to me in the context of jenkins would imply the configuration is locked or security is disabled (ie allow anonynous access to the job).  
IMO it should also change depending on if the link is to enable or disable the project.

**Comment by olivergondza** [comment]
@jtnord, I guess you are right. The best fit for disable (though not enable) would be what we currently use for delete. Not sure such icon shuffling is worth the confusion. Any suggestions?

**Comment by oleg-nenashev** [comment]
Play/pause icons could work if we make the "play" icon visually different from the "Build" action icon

**Comment by uhafner** [comment]
Another simper option would be to use a link rather than the button right after the text. 

If the action is moved to the left then we should use the same label style for delete and enable. I prefer the short form "Enable Project" and "Delete Project" rather than the currently used value "Delete Maven project". (Or even better "Delete" and "Enable"?).

**Comment by olivergondza** [comment]
My general idea to avoid controls that are placed on page rather randomly and concentrate it on one place, the sidepanel.

@oleg-nenashev, I like the play/pause idea.

@uhafner, I find current *Delete X Project* pattern more confusing than helpful as well, though someone bothered to put the complexity in place presumably for a reason. I do not object against doing the same once we agree that moving controls to sidepanel is a good thing.

**Comment by oleg-nenashev** [comment]
@olivergondza 
I've found several icon sets, which seem to be non-confusing. We could also use something like roadsigns if we replace "delete" icon for something like trashbin

Semaphore:
* https://www.iconfinder.com/icons/64900/green_lights_traffic_icon#size=32
* https://www.iconfinder.com/icons/64901/lights_red_traffic_icon#size=32
* // we also could use some additional light combinations, for other purposes (e.g. yellow for a non-parallel build, which is being build)

Standalone circles:
* https://www.iconfinder.com/icons/34214/circle_green_icon#size=64
* https://www.iconfinder.com/icons/34211/green_icon#size=128

**Comment by KostyaSha** [comment]
Why not just remove this button? In comparison to other SW, settings usually available in "Settings", but in jenkins for job it's called "configure" and disable/enable already exist under "settings".

**Comment by olivergondza** [comment]
@KostyaSha, I am afraid people will miss the convenient way of disabling jobs. Though, I definitely agree that there is no reason to introduce such duality in the future.

Aside from that, feature like 'keep this build forever', 'mark slave temporarily offline' or 'launch slave agent' do not have an alternative and I would like to move them to sidepanel as well.

**Comment by jtnord** [comment]
@gusreiber sometimes has some good ideas

**Comment by tfennelly** [comment]
Right, @gusreiber is very good at these kinds of thing.

**Comment by KostyaSha** [comment]
> @KostyaSha, I am afraid people will miss the convenient way of disabling jobs.

Disabling/enabling is not something that frequently used. Or it mean that you do something wrong.
In github it at all hidden for example.

Right now my leftside panel is already overloaded with many buttons from different plugins. 
:-1: for moving existed stuff until the whole design and plan for enhancement will be created (comparison with other automation tools, other tools, what form controls can be used/added for doing better UI).
I will even prefer some additional page that will have all this icons (like Desktop with icons on PC). Or maybe some collapsableю

**Comment by olivergondza** [comment]
I can imagine that one day we split sidepanel tasks into *informative*, *possibly-destructive* or even more categories to look visually different and perhaps even collocated. Having *seldom-used* category to be collapsed by default should help as well.

**Comment by KostyaSha** [comment]
> I can imagine that one day

UI changes will cause questions and usability problem for users. Also will broke any documentation (even Jenkins o'reilly book?). Moving buttons on page without knowing final design :-1: The same problem is overloaded history widget.

**Comment by olivergondza** [comment]
@KostyaSha, in what way is reordering controls or changing their color/background going to brake documentation? All your suggestions was more invasive than that...

Lets move this to dev-list so we will hopefully come up with more general plan.

**Comment by olivergondza** [comment]
https://groups.google.com/forum/#!topic/jenkinsci-dev/1o_txF9mKcM

**Comment by slide** [comment]
@olivergondza @KostyaSha I use the convenient Enable/Disable buttons all the time, I would definitely miss it.

**Comment by KostyaSha** [comment]
@slide could you describe how you configured your jenkins/job that you are constantly using this buttons? :laughing:

**Comment by jglick** [comment]
> Another simper option would be to use a link rather than the button right after the text.

Or just a labelled checkbox, with an immediate AJAX save when checked/unchecked? Though that suffers a bit since we do not want to show this text at all in the initial page load in the normal case that the project is enabled.

> I prefer the short form "Enable Project" and "Delete Project" rather than the currently used value "Delete Maven project".

FYI, this pronoun is under the control of the project type plugin. [Reference](https://github.com/jenkinsci/maven-plugin/blob/f32d1924477e9a5eb34b013d6a9815f4a53d0e0b/src/main/java/hudson/maven/MavenModuleSet.java#L456)

> Or even better "Delete" and "Enable"?

Agreed, I see no reason for the pronoun to be included here. The _Configure_ link does not include it, and no seems to be confused about what they are configuring.

**Comment by daniel-beck** [comment]
@slide @KostyaSha I also use enable/disable a lot (for good reasons I won't go into).

FWIW I don't like the inline buttons at all, especially since model-links (popup menus) were added, because these are missing for no real reason other than UI position. (Although one could imagine extending the model-links to cover these, but easier and more consistent would be to move most of them to the main sidepanel).

> Agreed, I see no reason for the pronoun to be included here. The *Configure* link does not include it, and no seems to be confused about what they are configuring.

Some users mentioned that 'Delete Build' and 'Delete Project' are already too similar and cause accidental deletions (I did point out that the confirmation dialog looks and works completely differently, didn't help). 'Configure' OTOH only really applies to projects, and isn't destructive.

**Comment by oleg-nenashev** [comment]
Does Jenkins 2 UI solve it in a better way?

**Comment by uhafner** [comment]
It is still on the right side of the panel, or am I missing something? (On the right side means on my screen: 30cm of empty space after the job information, then the disable button suddenly appears...).

**Comment by olivergondza** [comment]
Abandoning

**Pull request closed without merging**
