### PR TITLE
[JENKINS-33809] Don't reuse forks

### PR DESCRIPTION
**Pull request by daniel-beck**
As recommended by @teilo, in an attempt to cut down the OOME during test (rather than increasing memory).

@reviewbybees @jenkinsci/code-reviewers

### CODE REVIEW

**Comment by jtnord** [comment]
:bee:

**Comment by mslusarczyk** [comment]
:bee:

**Comment by batmat** [comment]
What we may want to do also is to pass something like `-Xloggc:gc${surefire.forkNumber}.log` to surefire fork and be able to batch-analyze afterwards which tests consumed the most memory.

**Comment by amuniz** [comment]
If this does not suffice, maybe merging [this](https://github.com/jenkinsci/jenkins/pull/2220) could help to diagnose.

**Pull request merged**
