### PR TITLE
[JENKINS-53401] Tie nodeProperties to the current node for save purpose

### PR DESCRIPTION
**Pull request by Vlatombe**
See [JENKINS-53401](https://issues.jenkins-ci.org/browse/JENKINS-53401).

### Proposed changelog entries

* Fixed a thread safety issue when creating several nodes in parallel.

### Submitter checklist

- [X] JIRA issue is well described
- [X] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Wrong JIRA issue is referenced in the commit body. AFAICT you mean https://issues.jenkins-ci.org/browse/JENKINS-53401

**Comment by Vlatombe** [comment]
Good catch @oleg-nenashev, fixed.

**Comment by daniel-beck** [comment]
Is there a way to test this somewhat reliably with enough threads saving nodes?

**Comment by Vlatombe** [comment]
@daniel-beck added a test

**Review by daniel-beck — APPROVED** [review]

**Review by KostyaSha — APPROVED** [review]

**Review by daniel-beck — APPROVED** [review]

**Pull request merged**
