### PR TITLE
[JENKINS-47324] Use NIO in FilePath#isDirectory

### PR DESCRIPTION
**Pull request by dwnusbaum**
See [JENKINS-47324](https://issues.jenkins-ci.org/browse/JENKINS-47324). 

This came up as a possible improvement to help diagnose [JENKINS-55356](https://issues.jenkins-ci.org/browse/JENKINS-55356). Needs a test case at the least, and some investigation to understand the cases that previously would have returned false that would now throw exceptions to understand the risk of the change.

From the [`File#isDirectory` Javadoc](https://docs.oracle.com/javase/7/docs/api/java/io/File.html#isDirectory()):

> Where it is required to distinguish an I/O exception from the case that the file is not a directory, or where several attributes of the same file are required at the same time, then the Files.readAttributes method may be used.

Known cases where the behavior changes between the old and new implementations:

* If the file does not exist, the new code throws `NoSuchFileException` instead of returning `false`
  * This change seems likely to affect existing callers, maybe we handle it specially?

### Proposed changelog entries

* Internal: Allow callers of `FilePath#isDirectory` to differentiate between failures and non-directories by throwing exceptions in the case of failure.

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@reviewbybees

### CODE REVIEW

**Review by jvz — APPROVED** [review]
Makes sense to me. I'd suggest Mockito for any tests here. :)

**Comment by dwnusbaum** [comment]
Tests failures such as `jenkins.util.VirtualFileTest#readLink` are definitely caused by the change, maybe we just need  `LinkOption.NOFOLLOW_LINKS`, but needs to be investigated.

**Comment by jvz** [comment]
After playing with that API a lot, if you do NOFOLLOW_LINKS to check if something is a directory, then you won't be able to visit symlinks to directories. At least that was my understanding.

**Comment by dwnusbaum** [comment]
Yeah after investigating it just looks like some VirtualFile methods need to be updated.

**Comment by dwnusbaum** [comment]
I'm going to close this for now until I have more time to look into `File#isDirectory` to understand what failure cases this could surface.

**Pull request closed without merging**
