### PR TITLE
[FIX JENKINS-41264] Add javadoc workflow explanation

### PR DESCRIPTION
**Pull request by varmenise**

### CODE REVIEW

**Comment by amuniz** [comment]
:+1:

**Comment by oleg-nenashev** [comment]
Methods should be marked by the "code" tag or by a link annotation. The text itself looks good to me

**Comment by daniel-beck** [comment]
@oleg-nenashev Do you require this change?

**Comment by oleg-nenashev** [comment]
We do not hurry with the merge right now (weekly is pretty far), so I would rather prefer to see a small fix from @varmenise

**Comment by oleg-nenashev** [comment]
I will fix it later since I have an action item to review/update remoting-related Javadocs and annotations

**Comment by oleg-nenashev** [comment]
@varmenise Please do not dissapear after creating pull requests

**Comment by oleg-nenashev** [comment]
changelogs are not required

**Comment by varmenise** [comment]
@oleg-nenashev I planned to fix it , was in my backlog but I got caught up in higher priorities things

**Pull request merged**
