### PR TITLE
[JENKINS-34226] No "pressed" style for OK button on Create Item

### PR DESCRIPTION
**Pull request by 97gushan**
See [JENKINS-34226](https://issues.jenkins-ci.org/browse/JENKINS-34226).

<details> <summary> Before</summary>

before

</details>

<details> <summary> After</summary>

after

</details>

<details> <summary> Comparison with other button</summary>

compare

</details>

Tested on 

- Firefox Version 69.0.1
- Chrome Version 77.0.3865.75
- Safari Version 13.0.1

### Proposed changelog entries

* Adding a "pressed" style for the Create Item button

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [n/a] Appropriate autotests or explanation to why this change has no tests
- [n/a] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### CODE REVIEW

**Comment by MRamonLeon** [comment]
Could you please add some screenshots before and after?
Have you tested it on several browsers? 

Closing to retrigger the UI

**Comment by 97gushan** [comment]
Updated description with images and browser information

**Review by MRamonLeon — APPROVED** [review]
I guess the hack proposed is outdated, the page was last updated in 2011. The property should work on every modern browser: https://www.w3schools.com/cssref/css3_pr_box-shadow.asp

So approving. Thanks @97gushan BTW you have tools to test on Internet Explorer or Edge even local web pages, for example https://www.browserstack.com/list-of-browsers-and-platforms/live

**Review by oleg-nenashev — APPROVED** [review]
Fine with me, thanks!

**Comment by oleg-nenashev** [comment]
I plan to merge it tomorrow if no negative feedback

**Comment by oleg-nenashev** [comment]
@97gushan  Is it a Hacktoberfest pull request just in case? Just to label it properly on our side. See [Hacktoberfest in Jenkins](https://jenkins.io/events/hacktoberfest). If you do not participate in it, please consider doing so. Your pull requests are much appreciated 👍

**Comment by 97gushan** [comment]
No I did not know of Hacktoberfest but will check it out

**Review by daniel-beck — APPROVED** [review]
Manually tested, seems fine.

Looks a bit weird specifically on the _New Item_ screen when moving the pointer outside the button while keeping pressed, as the dark shadow and lighter background don't match up well, but this is a clear 99% improvement (an argument can be made that the background shouldn't change anyway).

**Comment by oleg-nenashev** [comment]
Thanks for the patch!

**Pull request merged**
