### PR TITLE
Upgrade winstone 5.11 to introduce Jetty LowResourceMonitor

### PR DESCRIPTION
**Pull request by olamy**
See [JENKINS-63713](https://issues.jenkins-ci.org/browse/JENKINS-63713).

Signed-off-by: olivier lamy <olamy@apache.org>

### Proposed changelog entries

* Winstone 5.11 introduce LowResourceMonitor from Jetty
* Bump jetty.version from 9.4.30.v20200611 to 9.4.32.v20200930

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by res0nance — APPROVED** [review]
Linking changelog https://github.com/jenkinsci/winstone/releases/tag/winstone-5.11

**Review by oleg-nenashev — APPROVED** [review]
There are other changes in https://github.com/jenkinsci/winstone/releases/tag/winstone-5.11 which are not mentioned (e.g. Jetty upgrade). Changelog entries and the PR title should be updated accordingly before the merge

**Review by MRamonLeon — APPROVED** [review]

**Comment by MRamonLeon** [comment]
Set on-hold until the changelog entries are fixed.

**Comment by olamy** [comment]
jetty version bump entry added

**Review by oleg-nenashev — APPROVED** [review]
We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

@jenkinsci/core would we want to expedite the process a bit and to merge it into the tomorrow's weekly?

**Comment by MarkEWaite** [comment]
@MRamonLeon I updated the proposed changelog entry to show jetty version 9.4.32.v20200930 rather than jetty version 9.4.31.v20200723 since that seems to be the version included with Winstone 5.11.  I also included JENKINS-63713 as the referenced issue in hopes it helps with clarity.  

If either of those were incorrect changes, could you let me know so that I can correct my mistake before the Jenkins 2.261 changelog is created?

**Pull request merged**
