### PR TITLE
[JENKINS-71406] Flake in `ExecutorTest.apiPermissions` caused by builds left running

### PR DESCRIPTION
**Pull request by jglick**
See [JENKINS-71406](https://issues.jenkins.io/browse/JENKINS-71406). Similar to #8115.

### Testing done

Ran locally, confirmed that it was aborting a few builds.

### Proposed changelog entries

- N/A

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/8157"></a>

### CODE REVIEW

**Review by basil — COMMENTED** [review]
Are we confident that `ExecutorTest` is the only case of this problem?

**Comment by jglick** [comment]
It was the only such failure I could see in the [currently available history](https://ci.jenkins.io/job/Core/job/jenkins/job/master/). If other buggy test cases are subsequently discovered, they can be fixed as well.

**Review by basil — CHANGES_REQUESTED** [review]
Not the right fix I think. Fails to diagnose the essential problem: that `ExecutorTest#startBlockingBuild` (which is invoked not just from `ExecutorTest`) returns a build for whose completion consumers are obligated to wait.

**Review by basil — CHANGES_REQUESTED** [review]
More transparent (and consistent with existing tests) to stop the builds in the same scope as they were started.

**Comment by basil** [comment]
This is still inconsistent with the pattern used in existing tests in core and plugins that simply stop any running builds that are in scope at the end of the test (not in a finally block and not by iterating over all builds). An approach that is consistent with the pattern used in existing tests is https://github.com/jenkinsci/jenkins/pull/8158.

I am not necessarily against switching to a new approach, but I think any possible new approach should be done consistently throughout this test suite at least, while also allowing plugin tests to use the same approach. I think that would likely take the form of opting in (or opting out?) of generic cleanup logic in the Jenkins test harness (JTH) rather than writing a `stopRunningBuilds()` method in every repository that contains tests.

**Comment by jglick** [comment]
Did not see #8158; that seems more straightforward.

**Pull request closed without merging**
