### PR TITLE
Remove fontawesome from setup wizard

### PR DESCRIPTION
**Pull request by janfaracik**
Fontawesome is only used for the setup wizard, this PR replaces those icons with icons from Ionicons for consistency/one less dependency. From a user's perspective the changes are very minimal.

**Before**
image

image

**After**
image

image

Removes copy-plugin as there are no longer any fonts in the fonts folder.

### Testing done

Setup wizard works as before, just with slight icon changes.

### Proposed changelog entries

- N/A

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.

### Desired reviewers

@jenkinsci/sig-ux 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7960"></a>

### CODE REVIEW

**Comment by timja** [comment]
I just seem to be getting spinning squares not ticks, is that right?
image

**Comment by janfaracik** [comment]
> I just seem to be getting spinning squares not ticks, is that right?
> 
> I'm using the core-pr-tester and I've hard reloaded cache
> 
> image

Good spot, should be fixed now.

**Review by timja — COMMENTED** [review]
LGTM

**Review by NotMyFault — APPROVED** [review]

**Review by timja — APPROVED** [review]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by NotMyFault** [comment]
@janfaracik There are a couple (?) of lint issues left to address alongside
> 20:44:32  [INFO] ERROR in unable to locate '/home/jenkins/agent/workspace/Core_jenkins_PR-7960/war/src/main/fonts/**/*' glob

**Pull request merged**
