### PR TITLE
Bump `junit` from 1.51 to 1.52

### PR DESCRIPTION
**Pull request by basil**
Fixes the `RequireUpperBoundDeps` error that was blocking #5657.

### Proposed changelog entries

N/A

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
The test error seems to be related

**Comment by timja** [comment]
> The test error seems to be related

I can't see related ones?

**Comment by Wadeck** [comment]
<details>

<summary>FTR Error from the first PR (from dependabot)</summary>

```
[2021-08-16T06:07:22.947Z] Failed while enforcing RequireUpperBoundDeps. The error(s) are [
[2021-08-16T06:07:22.947Z] Require upper bound dependencies error for org.jenkins-ci.plugins:display-url-api:2.3.4 paths to dependency are:
[2021-08-16T06:07:22.947Z] +-org.jenkins-ci.main:jenkins-test:2.307-rc31419.e84257757bd5
[2021-08-16T06:07:22.947Z]   +-org.jenkins-ci.plugins:mailer:1.34
[2021-08-16T06:07:22.948Z]     +-org.jenkins-ci.plugins:display-url-api:2.3.4
[2021-08-16T06:07:22.948Z] and
[2021-08-16T06:07:22.948Z] +-org.jenkins-ci.main:jenkins-test:2.307-rc31419.e84257757bd5
[2021-08-16T06:07:22.948Z]   +-org.jenkins-ci.plugins:junit:1.52
[2021-08-16T06:07:22.948Z]     +-org.jenkins-ci.plugins:display-url-api:2.3.5
[2021-08-16T06:07:22.948Z] and
[2021-08-16T06:07:22.948Z] +-org.jenkins-ci.main:jenkins-test:2.307-rc31419.e84257757bd5
[2021-08-16T06:07:22.948Z]   +-org.jenkins-ci.plugins:junit:1.52
[2021-08-16T06:07:22.948Z]     +-io.jenkins.plugins:checks-api:1.7.2
[2021-08-16T06:07:22.948Z]       +-org.jenkins-ci.plugins:display-url-api:2.3.5
[2021-08-16T06:07:22.948Z] ]
```


</details>

In this commit, there are some failure (build still running). I compared them with latest commit build on master.

Also failing in latest core commit

- hudson.slaves.SlaveComputerTest

Was **not** failing in latest core commit

- hudson.model.UsageStatisticsTest

```
09:01:13  [ERROR] Tests run: 5, Failures: 1, Errors: 4, Skipped: 0, Time elapsed: 33.093 s <<< FAILURE! - in hudson.model.UsageStatisticsTest
09:01:13  [ERROR] roundtrip(hudson.model.UsageStatisticsTest)  Time elapsed: 24.361 s  <<< FAILURE!
09:01:13  org.junit.ComparisonFailure: expected:<...yleProject":0,"org-j[enkinsci-plugins-workflow-job-WorkflowJob":0,"org-j]vnet-hudson-test-Moc...> but was:<...yleProject":0,"org-j[]vnet-hudson-test-Moc...>
09:01:13  	at org.junit.Assert.assertEquals(Assert.java:117)
09:01:13  	at org.junit.Assert.assertEquals(Assert.java:146)
09:01:13  	at hudson.model.UsageStatisticsTest.compareWithFile(UsageStatisticsTest.java:174)
09:01:13  	at hudson.model.UsageStatisticsTest.roundtrip(UsageStatisticsTest.java:125)
```

Seems some naming change, not investigated deeper

**Comment by timja** [comment]
@dependabot rebase

**Comment by Wadeck** [comment]
After having ran the test locally on master and on this PR, the failure in UsageStatisticsTest:
The `org-jenkinsci-plugins-workflow-job-WorkflowJob` is no long present in the JSON entry "jobs" from the `getStatData`, and this leading to the comparison failure.

**Comment by Wadeck** [comment]
If you do not want the jobs.json adjustment please revert the commit :) I expect the PR to pass the tests now.

**Review by timja — APPROVED** [review]
> If you do not want the jobs.json adjustment please revert the commit :) I expect the PR to pass the tests now.

FTR: https://github.com/jenkinsci/checks-api-plugin/pull/94

**Review by oleg-nenashev — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Pull request merged**
