### PR TITLE
BallColor: Add back grey icon to be compatible with

### PR DESCRIPTION
**Pull request by panicking**
The BallCalor api is broken for missing icon gray color. There were removed without inform plugins that this interface was supposed to be deprecated

### CODE REVIEW

**Comment by jonesbusy** [comment]
Jenkins doesn't use balls anymore and plugins like https://plugins.jenkins.io/greenballs/ were deprecated

If you found a plugin not using symbol they must be fixed on the plugin side not adding gifs on core.

Similar issue https://issues.jenkins.io/browse/JENKINS-71919

**Comment by panicking** [comment]
@NotMyFault so the class should be removed from Jenkins core. Am I right?

**Comment by MarkEWaite** [comment]
> @NotMyFault so the class should be removed from Jenkins core. Am I right? You can say that core does not use it but it expose a class that instantiate them and export this api

No, we generally do not remove API's from Jenkins core without a significant effort to remove all the callers.

**Comment by panicking** [comment]
@MarkEWaite Sorry but I have some problems here:

- Result.java that should use the same class for result color and get:
 public static final @NonNull Result SUCCESS = new Result("SUCCESS", BallColor.BLUE, 0, true);
    /**
     * The build had some errors but they were not fatal.
     * For example, some tests failed.
     */
    public static final @NonNull Result UNSTABLE = new Result("UNSTABLE", BallColor.YELLOW, 1, true);
    /**
     * The build had a fatal error.
     */
    public static final @NonNull Result FAILURE = new Result("FAILURE", BallColor.RED, 2, true);
    /**

Then it's not clear how to convert jelly file to get the right one. If I want to get the path and not the class from the new icon how should I read some documentation or example?

**Comment by panicking** [comment]
@MarkEWaite Found out how, 
https://github.com/jenkinsci/gerrit-trigger-plugin/pull/501

**Pull request closed without merging**
