### PR TITLE
[JENKINS-71578] allow making sidepanel sticky

### PR DESCRIPTION
**Pull request by mawinter69**
Having a sticky sidepanel allows pages with only few links but longer content easier navigation.

Apply stickiness to PluginManager.

After:
image

See [JENKINS-71578](https://issues.jenkins.io/browse/JENKINS-71578).

### Testing done

Manually visit PluginManager
Sidepanel sticks when scrolling down so all links stay accessible all the time.
Configure a job -> sidepanel is still sticky

### Proposed changelog entries

- Allow to make side panel sticky

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/8269"></a>

### CODE REVIEW

**Review by daniel-beck — CHANGES_REQUESTED** [review]
Needs to be accompanied by (plugin) developer guidance when to use this to prevent a mess of arbitrary choices.

Should not be used on extensible pages like for `User`, otherwise scrolling makes later entries inaccessible. (It's fairly unlikely to matter for `User`, but it's an extensible sidepanel nonetheless.)

**Comment by mawinter69** [comment]
The non scrolling is already a problem now. Just go to configure job and make the browser window very small and the lower links are gone.
So maybe we should add some css to allow it to scroll if required

**Comment by daniel-beck** [comment]
> already a problem now

While small windows will hide sidepanel entries for config forms, it's the same 5 or so entries every time, and they're only for navigation inside the same page (something you can also accomplish by scrolling), not to go somewhere else. `User` and everything `Actionable` has an unbounded number of sidepanel entries, and those links go elsewhere with usually no alternative.

**Comment by mawinter69** [comment]
tested this on a job. When adding a overflow: auto and a scrollbar is shown, the widget fills up to the scrollbar and then when hovering the navigation arrows are missing. Can be overcome by adding padding to the sidepanel but this will increase the gap between side and main panel. And scrollbar-gutter is not supported on Safari 😞

**Review by janfaracik — APPROVED** [review]

**Comment by janfaracik** [comment]
Would it be possible to move `<div id="side-panel" class="app-page-body__sidebar">` from `layout.jelly` into `side-panel.jelly` and that way we could do away with the JS?

**Comment by mawinter69** [comment]
> Would it be possible to move `<div id="side-panel" class="app-page-body__sidebar">` from `layout.jelly` into `side-panel.jelly` and that way we could do away with the JS?

done

**Review by timja — APPROVED** [review]
LGTM

**Comment by timja** [comment]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Pull request merged**
