### PR TITLE
Update WinSW to 2.1.0 and Windows Agent Installer to 1.9

### PR DESCRIPTION
**Pull request by oleg-nenashev**
See the changelog: https://github.com/jenkinsci/windows-slave-installer-module/blob/master/CHANGELOG.md . Notable changes are listed below.

Full diffs:
* WinSW: https://github.com/kohsuke/winsw/compare/winsw-2.0.3...winsw-2.1.0
* Windows Agent Installer: https://github.com/jenkinsci/windows-slave-installer-module/compare/windows-slave-installer-1.8...windows-slave-installer-1.9

### Changelog entries

Proposed changelog entries:

* [JENKINS-43737](https://issues.jenkins-ci.org/browse/JENKINS-43737) - Update to [Windows Service Wrapper 2.1.0](https://github.com/kohsuke/winsw/blob/master/CHANGELOG.md#210) to support new features: `<download>` command with authentication, flag for startup failure on `<download>` error, _Delayed Automatic Start_ mode.
* [JENKINS-43603](https://issues.jenkins-ci.org/browse/JENKINS-43603) - Windows services: Add System Property, which allows disabling WinSW automatic upgrade on agents. [More info](https://github.com/jenkinsci/windows-slave-installer-module#disabling-automatic-upgrade).
* [JENKINS-42745](https://issues.jenkins-ci.org/browse/JENKINS-42745) - Windows services: Restore compatibility of the `WindowsSlaveInstaller#generateSlaveXml()` method. (API regression in 2.50, no known external usages).
* [JENKINS-43930](https://issues.jenkins-ci.org/browse/JENKINS-43930) - Windows services: Prevent fatal file descriptor leak when agent service installer fails to read data from the service `startup.log`.

### Submitter checklist

- [x] JIRA issue is well described
- [x] Link to JIRA ticket in description, if appropriate
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For new API and extension points: Link to the reference implementation in open-source (or example in Javadoc)

### Desired reviewers

@reviewbybees @jglick @stephenc  @nightman68

### CODE REVIEW

**Review by jglick — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers Would you be fine with merging towards the next weekly?

**Comment by daniel-beck** [comment]
@oleg-nenashev Given that 2.58 is pretty terrible, how confident are you that this won't result in new regressions for Windows users?

**Comment by oleg-nenashev** [comment]
@daniel-beck I am pretty confident about it. Hence there is a 60% probability :(
I am personally fine if it gets postponed, but it would be great to have it in the LTS.  I would definitely want to have download with auth in at least. And I commit to handle the fallout of course

We have SSHD Core, Groovy and Jetty updates pending. Probably it is better to do everything as a big bang after LTS line selection if we do not want to stick to 2.57 as a Plan B

**Comment by oleg-nenashev** [comment]
@daniel-beck So what is your decision about merging?

**Comment by oleg-nenashev** [comment]
As per discussion with @daniel-beck, he didn't actually block this PR. Taking the good community rating of 2.59 and the LTS process, I am going to merge this change now. P.S: I made several attempts to confirm it in IRC

**Pull request merged**
