### PR TITLE
[JENKINS-63699] Rename "Manage Jenkins" to avoid name redundancy

### PR DESCRIPTION
**Pull request by janfaracik**
See [JENKINS-63699](https://issues.jenkins.io/browse/JENKINS-63699).

Rename "Manage Jenkins" to 'Settings'.

image

### Testing done

* Task in sidebar is correctly named 'Settings'
* Navigated to Settings, title + app bar is set correctly
* Navigated to individual pages, e.g. System, 'Settings' is visible in the breadcrumbs bar

### Proposed changelog entries

- Rename "Manage Jenkins" to 'Settings'

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.

### Desired reviewers

@jenkinsci/sig-ux 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7741"></a>

### CODE REVIEW

**Comment by daniel-beck** [comment]
Did you consider alternatives to _Settings_, and if so, what were the pros/cons? E.g., the Jira issue proposes "Manage" (which on its own is probably odd but that's just IMO), and I would expect some form of or term involving "Administration" to make sense, given the permission name that mostly/by default governs access.

Otherwise, as before, needs a corresponding docs update, and perhaps even batch PRs to GH repos given how common it is to mention this label.

Given the potential confusion for users and how much documentation, including where we don't directly control it, refers to the old label, I'm not even sure that this point that any new label is a net positive change.

**Comment by janfaracik** [comment]
> Did you consider alternatives to _Settings_, and if so, what were the pros/cons? E.g., the Jira issue proposes "Manage" (which on its own is probably odd but that's just IMO), and I would expect some form of or term involving "Administration" to make sense, given the permission name that mostly/by default governs access.

I only considered 'Settings', it's near universally used nowadays on almost every service/application/operating system - I think it'd be a mistake to go for something else.

> Otherwise, as before, needs a corresponding docs update, and perhaps even batch PRs to GH repos given how common it is to mention this label.
> 
> Given the potential confusion for users and how much documentation, including where we don't directly control it, refers to the old label, I'm not even sure that this point that any new label is a net positive change.

I'm happy to make the changes, I understand it's a hefty change for minimal reward but I think as part of refreshing/modernising the Jenkins user experience we need to take a good look at its content too.

**Comment by daniel-beck** [comment]
> it's near universally used nowadays on almost every service/application/operating system - I think it'd be a mistake to go for something else.

It is probably a good term in isolation. Note that I mention Overall/Administer for the relation to an existing other term. These changes do not happen in isolation.

Since Mac OS uses "Preferences" for per-app settings, and "System Preferences" for the global ones, applying that logic to Jenkins would result in the pair of "Configure" and "Configure System/Jenkins" or a similar variant of the term, basically pulling the former "System" term up one level.

(Besides, Mac OS has had System Preferences for a long time. Does Windows no longer use Control Panel?)

**Comment by janfaracik** [comment]
> > it's near universally used nowadays on almost every service/application/operating system - I think it'd be a mistake to go for something else.
> 
> Since Mac OS uses "Preferences" for per-app settings, and "System Preferences" for the global ones, applying that logic to Jenkins would result in the pair of "Configure" and "Configure System/Jenkins" or a similar variant of the term, basically pulling the former "System" term up one level.
> 
> (Besides, Mac OS has had System Preferences for a long time. Does Windows no longer use Control Panel?)

Windows has used 'Settings' since Windows 8 from what I can remember. macOS has adopted 'Settings/System Settings' now as part of macOS Ventura (I imagine they'd have dropped the 'System' for alignment with iOS had it not been part of macOS' identity since forever).

image

The advantage of just 'Settings' for me is that it's near-universal now, and it's short and snappy.

**Comment by daniel-beck** [comment]
To clarify, you see no potential confusion with "Settings" being global, and "Configuration" being for specific jobs etc.?

**Comment by timja** [comment]
> FWIW [JEP-223](https://github.com/jenkinsci/jep/tree/master/jep/223?rgh-link-date=2023-03-20T10%3A14%3A02Z) might also be a consideration here, AFAICT Overall/Manage got its name from the menu item.

It doesn't read that way to me.

> This type of permission is a form of "Management" capability, a term used to describe permissions that can be used to delegate the ability to manage specific aspects of an instance without granting an overall administrative permission.

It got it from 'management' vs 'administration'.

not from a page being called 'Manage Jenkins', otherwise you would just get permission to all the pages under there?

**Comment by daniel-beck** [comment]
There's still a natural match between the terms. Overall/Manage grants access to (parts of) Manage Jenkins.

As I acknowledge above, "Settings" is a good term in isolation. Jenkins has a lot of baggage though and therefore I don't think this is a good choice.

**Comment by nitish799** [comment]
i would like to contribute to this issue.

**Review by timja — APPROVED** [review]
+1

**Comment by jglick** [comment]
What the screenshot in the PR description does not show is all of the other stuff in `/manage/` which does not look like “settings” to me: **System Log**, **Load Statistics**, **Jenkins CLI**, etc.

**Comment by janfaracik** [comment]
> What the screenshot in the PR description does not show is all of the other stuff in `/manage/` which does not look like “settings” to me: **System Log**, **Load Statistics**, **Jenkins CLI**, etc.

That is a good point. I would say that 'Settings' has become somewhat of a catch-all term, often including stats/graphs (e.g. battery, disk management) or information (e.g. About, machine info).

**Comment by alecharp** [comment]
@janfaracik is this something you want to address or should we close this pull request for now?

**Comment by janfaracik** [comment]
> @janfaracik is this something you want to address or should we close this pull request for now?

Think it'd be sensible to close - can always discuss it at the next UX sig/online.

**Pull request closed without merging**
