### PR TITLE
[JENKINS-69791] Improve "View as plain text" UX flow

### PR DESCRIPTION
**Pull request by Langer0416**
See [JENKINS-69791](https://issues.jenkins.io/browse/JENKINS-69791).

### Before
Before

### After
After

### Proposed changelog entries

Move the "View as plain text" sidebar out of "Console output"

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] The Jira issue, if it exists, is well-described.
- [X] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [X] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7225"></a>

### CODE REVIEW

**Comment by MarkEWaite** [comment]
Thanks for the pull request.  Good to have a conversation about the contents of the sidepanel for the build page.

I find the new layout more confusing than the old layout.  The old layout provided a visual cue that the console output is what is being viewed as plain text.  The new layout makes me think that I'll see the build page as text, when what I will see is the console log as text.

Would it be clearer if the label changed to "Console output as text" rather than "View as text"?

I rarely use the "View as text" button.  For my use, I think it is less desirable to add a rarely used button to a panel that already has too many entries for me.  I may not be a typical user and am interested in experience from other users if they perceive the importance of the "View as text" button differently than I do.

**Comment by NotMyFault** [comment]
> a panel that already has too many entries

A great point to pick up, which I do agree with.
A simple job with a few test integrations and code analysis tools do create sidepanels with 20, ungrouped and unnested, items at a minimum (!!).
Unnesting sidepanel items is no real improvement in terms of usability, considering it lengthens the jam full sidepanel by more entries, inevitably making stuff even harder to locate, unless you know what you are looking for.

**Review by NotMyFault — COMMENTED** [review]
> It currently has 7-8 without plugins. How could that be too much?

Given, this statement doesn't consider the vast broad of Jenkins capabilities, ranging from many job types over different integrations, as they are commonly used in real world scenarios, I'd like to neglect this point.

Therefore, I'm voting [-0](https://www.apache.org/foundation/voting.html#expressing-votes-1-0-1-and-fractions) on the proposed change, for the reasons stated above.

**Comment by Sweepi** [comment]
> Given, this statement doesn't consider the vast broad of Jenkins capabilities, ranging from many job types over different integrations, as they are commonly used in real world scenarios, I'd like to neglect this point.

Are these capabilities brought by Jenkins or by plugins?
Afaik "View as plain text" is Jenkins core.

**Comment by MarkEWaite** [comment]
> Are these capabilities brought by Jenkins or by plugins?
> Afaik "View as plain text" is Jenkins core.

They are most commonly capabilities brought by plugins, but that does not change the user experience.  Every addition to the side panel from Jenkins core or a Jenkins plugin stretches the length of the side panel for all users.  If those users do not use that button, the change risks pushing other more frequently used side panel buttons below the bottom of the browser so that the user must scroll in order to click the button.  I'm already experiencing that with ci.jenkins.io job pages.

I am "-1" for this change though willing to be persuaded otherwise if multiple users confirm that they frequently access the "View console as text" button.

**Comment by Sweepi** [comment]
Thanks for the clarification about pipeline jobs, i could was not able to figure that out.

**Review by Wadeck — COMMENTED** [review]
Thanks for the screenshots.

Not a big fan of the change, `-0` as well.

**Pull request closed without merging**
