### PR TITLE
JENKINS-22028 - update label to reflect actual behavior

### PR DESCRIPTION
**Pull request by rantoniuk**
Per suggestion in JENKINS-22028 .

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Should be "Plain text" IMO. I'd also propose to drop translations to other languages

**Comment by warden** [comment]
I didn't like the look of "Plain text" and capitalization for me is less relevant than the meaning :)
I can change to capitalized version of Plain text or Plain Text if you prefer though.
Dropping support of other languages is not part of this issue.

**Comment by daniel-beck** [comment]
*Plain text* would be consistent with the rest of Jenkins AFAICT.

**Comment by warden** [comment]
Here you go!

**Comment by daniel-beck** [comment]
@warden Thanks!

**Pull request merged**
