### PR TITLE
expose build parameters as REST API

### PR DESCRIPTION
**Pull request by ndeloof**

### CODE REVIEW

**Comment by ndeloof** [comment]
@reviewbybees

**Comment by jglick** [comment]
:bug: seems suspect since `getActions()` should already be `@Exported`. I would want to see a functional test with `WebClient` demonstrating the expected URL and content which you cannot get without this patch.

**Comment by ndeloof** [comment]
@jglick getActions is indeed Exported but then you have can't determine which action is ParameterAction. If you want to retrieve the build parameters by REST API you have no way.

**Comment by jglick** [comment]
> determine which action is ParameterAction

Well, the one with a `parameters` property.

The more general question of identifying elements of a polymorphic list is already filed as https://github.com/stapler/stapler/pull/51.

**Comment by ndeloof** [comment]
there's many Actions to have `parameters` attributes.

**Comment by jglick** [comment]
Hence the more general PR I linked to.

**Pull request closed without merging**
