### PR TITLE
Backporting for 2.332.1

### PR DESCRIPTION
**Pull request by cathychan**
Prework for https://github.com/jenkins-infra/release/issues/223

```
Fixed
-----

JENKINS-67767		Blocker   		2.334 / 2.319.3
	Backporting reminder: security fixes in 2.334 to 2.332.1
	https://issues.jenkins.io/browse/JENKINS-67767

JENKINS-67753		Minor     		Wed, 16 Feb 2022 14:13:14 +0000
	Missing icon on empty organization folder
	regression
	https://issues.jenkins.io/browse/JENKINS-67753

JENKINS-67722		Minor     		Sun, 13 Feb 2022 15:54:03 +0000
	The configure link for custom log recorders links to the wrong "configure" location
	regression
	https://issues.jenkins.io/browse/JENKINS-67722

JENKINS-67702		Minor     		2.319.3
	Backport XStream 1.4.19 to LTS
	https://issues.jenkins.io/browse/JENKINS-67702

JENKINS-67689		Minor     		Sun, 13 Feb 2022 15:54:03 +0000
	Can't cancel build on run page with build name of certain length, x hidden
	regression
	https://issues.jenkins.io/browse/JENKINS-67689

JENKINS-67674		Minor     		2.333
	Update bundled plugins after 2022-01-12 advisory
	https://issues.jenkins.io/browse/JENKINS-67674

JENKINS-67662		Minor     		2.333
	Tooltips show wrong feature name on checkboxes
	regression
	https://issues.jenkins.io/browse/JENKINS-67662

JENKINS-67635		Major     		2.333
	Using "||" in pipeline targeting cloud labels cause multiple agents to be spun incessantly
	regression
	https://issues.jenkins.io/browse/JENKINS-67635

JENKINS-67627		Minor     		2.333
	Expandable text areas strip spaces
	regression
	https://issues.jenkins.io/browse/JENKINS-67627

JENKINS-67609		Minor     		Sun, 13 Feb 2022 15:54:03 +0000
	Help buttons show twice on different themes
	regression
	https://issues.jenkins.io/browse/JENKINS-67609

JENKINS-67496		Major     		2.333
	Drag & drop is messed up, drag placeholders always have tiny size
	regression
	https://issues.jenkins.io/browse/JENKINS-67496

JENKINS-67000		Major     		Tue, 15 Feb 2022 18:54:51 +0000
	JavaWebStart agents cannot connect due to AccessControlException
	regression
	https://issues.jenkins.io/browse/JENKINS-67000
```

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by timja** [comment]
Can we add all those candidates please?

**Comment by cathychan** [comment]
@timja I added the four remaining items that are `FIXED BUT UNRELEASED`.

**Review by timja — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]
Candidate selection looks fine, though I'd vouch for updating the security advisory of SECURITY-2602, otherwise Jenkins warns you about it, even if the fix is integrated.

**Comment by jtnord** [comment]
what about https://issues.jenkins.io/browse/JENKINS-67753 ?

**Comment by timja** [comment]
Yeah sounds good

**Comment by cathychan** [comment]
I know we still have much time before finalizing the RC, but can we still move forward and merge this? We can always add more backports if necessary, right?

**Comment by timja** [comment]
yes you're fine to merge this

**Pull request merged**
