### PR TITLE
CI: Let java figure out memory ergonomics

### PR DESCRIPTION
**Pull request by timja**
https://github.com/jenkinsci/jenkins/pull/5843#discussion_r734358513

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
No objections for this one

**Comment by jtnord** [comment]
> A little worried about setting that affecting jetty:run.

it does - but at the same time, giving min 512MB / max 1.5g to maven for a build that does not need it makes it a memory hog, with less RAM actually available for surefire and other things. 

for those that want `jetty:run` and `hpi:run` they can always override the memory on the CLI. Whilst the values from `.mvn/jvm.config` are applied before `MAVEN_OPTS`  the JVM (at least openJDK and derivatives) take the last provided value as the one to use...

```
>java -Xmx1 -version
Error occurred during initialization of VM
Too small initial heap

>java -Xmx1 -Xmx1M -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.265-b01, mixed mode)
```

**Comment by alecharp** [comment]
@basil @dduportal do you think, with the merge conflicts resolved, we should integrate this PR?

**Comment by basil** [comment]
I do not understand the impact, before and after, on each JVM involved (primary Remoting JVM, Maven JVM, Surefire JVM, test agent JVMs) across all agent templates, so I cannot properly review this change.

**Review by dduportal — APPROVED** [review]
Fine for me, thanks for solving conflicst.

We'll have to minotir the build executions when running on "highmem" instrances to see if it uses most of the provided memory.

**Comment by basil** [comment]
I guess I should just be explicit. -0 from me because I do not think we have a complete understanding of the effects of this change. These builds are not very stable as it is (I often have to re-run them 2-3 times to get a passing result), and I fear we may destabilize them further. Unfortunately reasoning about JVM memory usage, especially when so many JVMs are involved, is not a trivial matter.

**Pull request closed without merging**
