### PR TITLE
[JENKINS-30374] Update obsolete help message

### PR DESCRIPTION
**Pull request by swashbuck1r**
Remove obsolete reference to "location you configured above" since the location is now determined automatically rather than explicitly configured.

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
:bee:

**Comment by recena** [comment]
:bee:

**Comment by daniel-beck** [comment]
@swashbuck1r IIRC when you specify the TOOL_HOME first, you can still select to have it be installed there.

**Comment by jglick** [comment]
Possibly true, but the text field does get hidden, so I am not sure whether this is a real feature we care to support.

**Pull request merged**
