### PR TITLE
[JENKINS-73907] Fix double-escaped tooltips in "Help for feature"

### PR DESCRIPTION
**Pull request by ridemountainpig**
See [JENKINS-73907](https://issues.jenkins.io/browse/JENKINS-73907).

### Testing done
CleanShot 2024-11-21 at 11 14 20

### Proposed changelog entries

- Fix double-escaped tooltips in "Help for feature".

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [x] The Jira issue, if it exists, is well-described.
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [x] There is automated testing or an explanation as to why this change has no tests.
```

### Desired reviewers

N/A

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Comment by daniel-beck** [comment]
#10000 🎉

**Review by MarkEWaite — APPROVED** [review]

**Review by daniel-beck — APPROVED** [review]

**Comment by daniel-beck** [comment]
I confirmed the expected outcome manually in `Security2779Test`.

**Review by MarkEWaite — COMMENTED** [review]
This PR is now ready for merge. We will merge it after the next weekly release if there is no negative feedback.

/label ready-for-merge

**Comment by jglick** [comment]
Anyway `'` should generally be avoided in GUI labels. Use `Don’t` or `Do not`

**Pull request merged**
