### PR TITLE
Document that Jenkins.getPluginManager() is not nullable

### PR DESCRIPTION
**Pull request by batmat**
No JIRA, internal and very small.
I have checked the code, and given the attribute is `final` and is initialized on L807 if passed null anyway.

### Proposed changelog entries

* Internal: Add `@Nonnull` to `Jenkins.getPluginManager()`

### Submitter checklist

~~- [ ] JIRA issue is well described~~
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
~~- [ ] For dependency updates: links to external changelogs and, if possible, full diffs~~

### CODE REVIEW

**Review by varyvol — APPROVED** [review]

**Review by Wadeck — APPROVED** [review]
:bee:

**Review by fcojfernandez — APPROVED** [review]

**Review by jvz — APPROVED** [review]
Sooner or later, someone will probably try converting the codebase to Kotlin, and all these annotations will certainly be useful there. ;)

**Comment by Wadeck** [comment]
@jvz they are already used by IntelliJ even in Java :) And then you have FireBugs that can tell you when you are doing some crazy stuff

**Comment by jvz** [comment]
I know the annotations are already used. If you use IntelliJ to convert the Java code to Kotlin, then it will use those nullable annotations to determine the nullability of the equivalent Kotlin types. For example, if my method has the signature `public @Nonnull String getFoo()`, then the Kotlin one will be `fun getFoo(): String`, whereas the signature `public @CheckForNull String getBar()` will be converted to `fun getBar(): String?`.

**Review by oleg-nenashev — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
It's totally OK according to https://github.com/jenkinsci/jenkins/search?q=getPluginManager&unscoped_q=getPluginManager . Will merge it in few days

**Pull request merged**
