### PR TITLE
Removing `SubClassGenerator`

### PR DESCRIPTION
**Pull request by basil**
According to `usage-in-plugins`, [this class is deprecated and unused](https://ci.jenkins.io/job/Infra/job/usage-in-plugins/job/master/lastSuccessfulBuild/artifact/output/deprecated-and-unused.html). (I also checked against CloudBees proprietary plugins.) So let's restrict it so that nobody starts using this. We don't want anyone to use it, because it ends up pulling in ASM.

~If @daniel-beck asked me to delete this class and the corresponding test rather than marking it with `@Restricted(DoNotUse.class)`, I would do so happily.~ Consensus seems to be that we're OK with removing this class.

### Proposed changelog entries

Developer: The `hudson.util.SubClassGenerator` class has been removed without replacement.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@jtnord @daniel-beck 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by daniel-beck — COMMENTED** [review]
Do you know whether this was ever used for anything? Probably too annoying to find out now?

**Comment by basil** [comment]
> Do you know whether this was ever used for anything? Probably too annoying to find out now?

I can't see any evidence that it was ever used for anything in core at least. `git log -S SubClassGenerator` has exactly one commit: the commit that introduced `SubClassGenerator` in 2010.

**Review by daniel-beck — APPROVED** [review]
LGTM, wouldn't fight a full `rm` either.

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by res0nance** [comment]
> LGTM, wouldn't fight a full `rm` either.

Should we just delete it then?

**Comment by basil** [comment]
> Should we just delete it then?

That is my preference, and it sounds like Daniel is OK with it, so I'll upgrade this PR to a deletion.

**Review by res0nance — APPROVED** [review]

**Review by timja — APPROVED** [review]

**Comment by basil** [comment]
Can this get the `ready-for-merge` label?

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Pull request merged**
