### PR TITLE
stapler/stapler #76

### PR DESCRIPTION
**Pull request by kohsuke**
This brings in https://github.com/stapler/stapler/issues/76

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Stapler package was not available at that point, retriggering the build

**Comment by oleg-nenashev** [comment]
I'm not against the upgrade, but it would be useful to have more info about impact on Jenkins

**Comment by oleg-nenashev** [comment]
@kohsuke 
>  The following artifacts could not be resolved: org.kohsuke.stapler:stapler-groovy:jar:1.244, org.kohsuke.stapler:stapler-jrebel:jar:1.244:

Stapler 1.244 is not available after 10 hours. Something went wrong
http://repo.cloudbees.com/content/repositories/central/org/kohsuke/stapler/stapler/

**Comment by kohsuke** [comment]
Oppsy

**Comment by kohsuke** [comment]
I think the failure is a flaky test `hudson.slaves.ComputerConnectorTest.testConfigRoundtrip`

**Comment by oleg-nenashev** [comment]
@kohsuke 
I'm not 100% sure, because Test says:
```
<h1>404 Not Found</h1>
<p>Stapler processed this HTTP request as follows, but couldn't find the resource to consume the request
```

**Comment by oleg-nenashev** [comment]
Retriggering the build just in case @kohsuke fixed something

**Comment by oleg-nenashev** [comment]
AFAIK it no works in @kzantow's PR

**Comment by kzantow** [comment]
Yeah, I have the same failure in my PR https://github.com/jenkinsci/jenkins/pull/2268 i spent some time debugging it, but couldn't figure it out after a short time, doesn't seem related to the changes in mine, but I did upgrade Stapler to 1.244.

**Comment by KostyaSha** [comment]
> but it would be useful to have more info about impact on Jenkins

Still no replies.

 As usual stapler will broke something and JIRA issue should be filled to have ability cross link issues. 

👎

**Comment by oleg-nenashev** [comment]
We will have to integrate newer Stapler at some point in any case.
But the current stapler master branch is a barely reviewable sequence of short changes. So we definitely need comments from the code developer before merging the stuff.

@kohsuke Any plans to respond to this PR?

**Comment by oleg-nenashev** [comment]
Just another build attempt

**Comment by michaelneale** [comment]
ping @vivek @kohsuke is this required?

**Comment by oleg-nenashev** [comment]
Closing since there is no response && stapler has fixes on the top of it. CC @jglick

**Pull request closed without merging**
