### PR TITLE
Stop supporting .NET Framework 2.0 + Update Windows Service Wrapper from 2.3.0 to 2.9.0

### PR DESCRIPTION
**Pull request by nxtn**
See [JENKINS-60005](https://issues.jenkins-ci.org/browse/JENKINS-60005), [JENKINS-61862](https://issues.jenkins-ci.org/browse/JENKINS-61862), jenkinsci/windows-slave-installer-module#42, jenkinsci/windows-slave-installer-module#43, jenkinsci/windows-slave-installer-module#52...

This change has no tests because CI runs on Linux.

### Questions

- I didn't see the `WindowsInstallerLink` class referenced anywhere.
- I didn't see the `WindowsSlaveInstaller` messages referenced anywhere.
- Why are there duplicated codes?

### Proposed changelog entries

(copied from jenkinsci/windows-slave-installer-module#43)

* major rfe - JENKINS-60005, JENKINS-61862 - Stop supporting .NET Framework 2.0 for launching Jenkins server and agents as a Windows service. .NET Framework 4.0 or above is now required.
  * Windows support policy: https://www.jenkins.io/doc/administration/requirements/windows/
* major rfe - Update Windows Service Wrapper from 2.3.0 to 2.9.0. It includes numerous improvements and bugfixes. Most notably, the service installer will now ask for permission elevation if the required permissions are missing
  * Windows Service Wrapper changelog - https://github.com/winsw/winsw/releases
  * Windows Agent Installer 2.0 Changelog - https://github.com/jenkinsci/windows-slave-installer-module/releases/tag/windows-slave-installer-2.0
* internal - Use built-in WinSW features for permission elevation ans strong cryptography
  * Windows Agent Installer 2.0 Changelog - https://github.com/jenkinsci/windows-slave-installer-module/releases/tag/windows-slave-installer-2.0

### Proposed upgrade guidelines

* Use-cases affected by .NET Framework 2.0 support removal - https://www.jenkins.io/blog/2020/07/23/windows-support-updates/#use-cases-affected-by-net-framework-2-0-support-removal
* Upgrade Guidelines - https://www.jenkins.io/blog/2020/07/23/windows-support-updates/#upgrade-guidelines

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

/cc @oleg-nenashev 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Thanks! Let's coordinate it with Windows Agent Installer so that we drop
.NET Framework 2.0 support in the core in a single release. I plan to
finish the module release by the end of the next week

**Comment by oleg-nenashev** [comment]
@jenkinsci/core @jenkinsci/sig-platform This pull request is now ready for review

**Review by oleg-nenashev — APPROVED** [review]
Ready to go from my PoV. Manual tests work for both master and agent installation

**Review by timja — APPROVED** [review]
Looks sane, not a windows user though

**Review by MarkEWaite — APPROVED** [review]
Looks good to me.  Thanks for this effort!

**Review by slide — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Comment by oleg-nenashev** [comment]
This change will require upgrade guidelines. I have created some here: https://www.jenkins.io/blog/2020/07/23/windows-support-updates/#use-cases-affected-by-net-framework-2-0-support-removal

**Pull request merged**
