### PR TITLE
link from update center to changelog

### PR DESCRIPTION
**Pull request by jhonDoe15**
See [JENKINS-69682](https://issues.jenkins.io/browse/JENKINS-69682).

image

(had a bit of a snafu in the commits but all changes in the final stage are meant to be there)

### Proposed changelog entries

- Entry 1: added changelog link/button in the plugin manager page

### Submitter checklist

- [x] The Jira issue, if it exists, is well-described.
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7237"></a>

### CODE REVIEW

**Comment by NotMyFault** [comment]
> (had a bit of a snafu in the commits but all changes in the final stage are meant to be there)

Creating a dedicated branch to propose a PR from is recommended, see [the contributing guidelines](https://github.com/jenkinsci/jenkins/blob/master/CONTRIBUTING.md#proposing-changes) for more information.

**Comment by jhonDoe15** [comment]
> > (had a bit of a snafu in the commits but all changes in the final stage are meant to be there)
> 
> Creating a dedicated branch to propose a PR from is recommended, see [the contributing guidelines](https://github.com/jenkinsci/jenkins/blob/master/CONTRIBUTING.md#proposing-changes) for more information.

thanks for the good advice @NotMyFault, this is exactly what I realized after this mess, and this is what I plan to do next.
for this time I'm afraid its a bit more problematic since the changes were published already to the master branch in my forked repo

**Comment by daniel-beck** [comment]
Currently the changelog of Jenkins (core) is linked from the administrative monitor informing admins about new releases. I can see why it would be useful to be able to navigate there even when on the current version of Jenkins. That said, the plugin manager is for, well, plugins, so I don't understand why the link would be there. Perhaps it can be integrated into the About Jenkins page somehow?

**Comment by jhonDoe15** [comment]
Hallo @daniel-beck , while I agree the bar informing administrators of a new release is a nice UX touch, it doesn't serve the purpose of this enhancement. 
because Jenkins in its essence is made of plugins and any conflicts or updates on such are displayed and explained in the [change log](https://www.jenkins.io/changelog/), it helps and provides easy access to the page detailing recent changes, to major plugins or Jenkins itself.
if you brought it up, it can also help, though not as much to add it to the bottom app bar for reference just like the version and docs already there. either way it's not right for this PR or issue but can be connected to provide context.

**Comment by jhonDoe15** [comment]
some flick happened to the ci, could you retry it?

**Comment by jhonDoe15** [comment]
I updated according to jenkins origin/master

**Comment by daniel-beck** [comment]
> it doesn't serve the purpose of this enhancement.

The PR doesn't state what the purpose of the change is, so I had to guess 😉 

> because Jenkins in its essence is made of plugins and any conflicts or updates on such are displayed and explained

Do you have examples for the changelog entries you're thinking of here? Occasionally we mention when Jenkins updates will be incompatible with some plugins, and we mention updates to bundled plugins, which affect basically nobody (it's only relevant when manually installing plugins, offline), but otherwise I cannot think of anything that would make sense here.

> bottom app bar for reference just like the version and docs already there

Oh, good point: the version number in the footer could link to the changelog. Would that work? Unsure whether it works UX wise, but might be an option. A potential problem might be that users overriding `hudson.footerURL` would not benefit from that enhancement, but I would guess those are  typically larger corporate, perhaps even centrally managed instances.

**Comment by jhonDoe15** [comment]
>The PR doesn't state what the purpose of the change is, so I had to guess 😉

I'm assuming usage of the issue for such decisions and details. would you recommend adding things like so in the PR? (I'm here to learn)

> Do you have examples for the changelog entries you're thinking of here? Occasionally we mention when Jenkins updates will be incompatible with some plugins, and we mention updates to bundled plugins, which affect basically nobody (it's only relevant when manually installing plugins, offline), but otherwise, I cannot think of anything that would make sense here.

I see what you mean, (personally, I work offline but then it wouldn't help anyway to link to the change log 😅 unless we'd save some of them to the war file) but I believe someone having issues might want to take a look while updating and installing as a first step
 
> Oh, good point: the version number in the footer could link to the changelog. Would that work? Unsure whether it works UX wise, but might be an option. A potential problem might be that users overriding `hudson.footerURL` would not benefit from that enhancement, but I would guess those are typically larger corporate, perhaps even centrally managed instances.

I wouldn't add personally to the version link but as a second link specifically for it (s separate link for the change log as reference like the API docs) though if someone built it themselves they might overwrite the existing link

**Comment by timja** [comment]
I don't see the value in adding it to the plugin manager / update center.

We are reducing side bar links not adding random ones especially not ones outside of Jenkins.

Linking to it from the footer from the existing version link would be fine as long as it's configurable in some way

**Comment by NotMyFault** [comment]
> We are reducing side bar links not adding random ones especially not ones outside of Jenkins.

I do agree with Tim's concern, and therefore vote [-0](https://www.apache.org/foundation/voting.html#expressing-votes-1-0-1-and-fractions) on this proposal as-is.

> Linking to it from the footer from the existing version link would be fine as long as it's configurable in some way

Sounds like something we could positively look forward to.

**Comment by jhonDoe15** [comment]
In that case I'll start getting on this if that's okay.
Could you help though pointing me in the direction regarding an issue? 
All the proposed changes for this PR I did through my fork's master branch, how can I take the origin back to drop all recent commits?

**Comment by timja** [comment]
`git reset --hard origin/master` should do it assuming origin is jenkinsci/jenkins or possible `git reset --hard upstream/master` depending on how you have it named

**Comment by daniel-beck** [comment]
>  All the proposed changes for this PR I did through my fork's master branch, how can I take the origin back to drop all recent commits?

Assuming you can use HTTPS URLs and not just SSH URLs:

```
git clone https://github.com/jenkinsci/jenkins
cd jenkins
git push -f https://github.com/jhonDoe15/jenkins master
```

(Then delete the temporary clone)

**Comment by NotMyFault** [comment]
@jhonDoe15 are you still interested in delivering this change? Above, you have a few samples of how to address your concern.

**Comment by jhonDoe15** [comment]
I was but the jira ticket for the issue didn't have complete support after I tried going after it and clarifying matters

**Comment by NotMyFault** [comment]
> I was but the jira ticket for the issue didn't have complete support after I tried going after it and clarifying matters

Above, you can find two comments by Daniel and Tim how to rebase your branch.

**Comment by timja** [comment]
Hi @jhonDoe15 are you still interesting in this pull request?

In order to progress this it would need to move to a link in the footer, see https://github.com/jenkinsci/jenkins/pull/7989 which introduced support for multiple links

**Comment by NotMyFault** [comment]
I'll go ahead and close the PR due to lack of response.
@jhonDoe15 you are much welcome to re-open it, once the feedback requested has been addressed.

Thanks!

**Pull request closed without merging**
