### PR TITLE
Revert [JENKINS-24513] Add access control for builds admin monitor

### PR DESCRIPTION
**Pull request by timja**
Given the plugin it recommends to use it not maintained, does not support jcasc or pipeline builds should we really be recommending it?

context:
https://groups.google.com/g/jenkinsci-dev/c/c1z4C3mQ2-k/m/h23s7oZUBgAJ

this is for discussion

originally added in https://github.com/jenkinsci/jenkins/pull/3919

### Proposed changelog entries

* Remove warning that recommends use of the Authorize project plugin.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by daniel-beck** [comment]
> Given the plugin it recommends to use it not maintained, does not support jcasc or pipeline builds should we really be recommending it?

The message could be changed to de-emphasize / no longer mention the plugin, but the problem is still one that administrators should be aware of. We should figure out a solution to this, of course, but pretending there's nothing here isn't it.

**Review by jglick — APPROVED** [review]
> The message could be changed to de-emphasize / no longer mention the plugin, but the problem is still one that administrators should be aware of.

True, but I do not think that is an argument against merging this PR as is. The existing monitor specifically checks whether you have a QIA. There is only one (known) implementation, in an abandoned plugin, so prompting an admin to install it makes no sense. Conversely, just because they are _not_ using a QIA does not necessarily mean they are vulnerable to something—depends heavily on their usage pattern, such as JCasC vs. GUI, and authorization strategy configuration, or for that matter if they use CloudBees CI and its trigger restrictions system—so it is misleading to ask them to dismiss a security warning. Better to hold off on designing some new notification unless and until we have a coherent answer as to what the admin should do instead (or at least some way of reliably detecting that what they are doing now is unsafe).

**Comment by basil** [comment]
For what it's worth, jenkinsci/authorize-project-plugin#44 is a relatively complete PR to add JCasC support to Authorize Project.

**Review by oleg-nenashev — COMMENTED** [review]
I would rather vote for fixing JCasC support. Built authorization is important feature for enterprise environments. There was a pull request for that if I recall correctly

**Comment by timja** [comment]
> I would rather vote for fixing JCasC support. Built authorization is important feature for enterprise environments. There was a pull request for that if I recall correctly

The PR was last touched over 2 years ago and the author has said he won't work on it any more and the plugin is un-maintained 🤷

**Comment by jglick** [comment]
Anyway IIRC JCasC support was less of a problem than multibranch Pipeline integration: JCasC bundles are implicitly trusted to come from an administrator, whereas there is no clear trust model to apply for `build` triggers defined in a `Jenkinsfile`. In other words, there is no safe and complete system for handling this issue currently, so pestering an administrator to install an incomplete system (with no maintainer) seems inappropriate.

**Comment by timja** [comment]
Bump

There is no maintainer for the recommended plugin and no seems interested.

This is also very much a freestyle build feature and pipeline is more popular, from my understanding.

This does not touch the feature at all, it just stops throwing warnings in users faces when there's not a good solution

**Review by basil — APPROVED** [review]
Completing the effort would be ideal, but better not to say anything at all than to describe an incomplete effort.

**Comment by basil** [comment]
This PR is now ready for merge. We will merge it after approximately 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process. Thanks!

**Pull request merged**
