### PR TITLE
[JENKINS-69276] No focus state on checkboxes

### PR DESCRIPTION
**Pull request by frankie139506**
See [JENKINS-69276](https://issues.jenkins.io/browse/JENKINS-69276).

gif2

### Proposed changelog entries

* Restore focus state for checkboxes (regression in 2.361)

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] (If applicable) Jira issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [X] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")` if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content-Security-Policy directives (see [documentation on jenkins.io](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/6976"></a>

### CODE REVIEW

**Comment by timja** [comment]
Do you know what caused it to lose this and is this undo-ing / affecting another change?

**Comment by frankie139506** [comment]
> Do you know what caused it to lose this and is this undo-ing / affecting another change?

I found it relate to [JENKINS-68788](https://github.com/jenkinsci/jenkins/pull/6680), I think this PR only need to remove the canceled focus state, but In `JENKINS-68788` it remove all the focus state this is very odd.

**Review by NotMyFault — COMMENTED** [review]
Tim, do I understand your issue correctly that there's no post-click focus state on the checkbox, but you want one here?
That's what the PR adds, but this is not what we do for checkboxes in general.

**Comment by timja** [comment]
> Tim, do I understand your issue correctly that there's no post-click focus state on the checkbox, but you want one here? That's what the PR adds, but this is not what we do for checkboxes in general.

No, the issue is when you tab across it its invisible you do not know it's selected

**Comment by NotMyFault** [comment]
> No, the issue is when you tab across it its invisible you do not know it's selected

Oic, thanks for the clarification. My former question turns into an issue then.

**Comment by frankie139506** [comment]
> > Tim, do I understand your issue correctly that there's no post-click focus state on the checkbox, but you want one here? That's what the PR adds, but this is not what we do for checkboxes in general.
> 
> No, the issue is when you tab across it its invisible you do not know it's selected

Apologize, I can't understand what should I do.

**Comment by frankie139506** [comment]
> > > Tim, do I understand your issue correctly that there's no post-click focus state on the checkbox, but you want one here? That's what the PR adds, but this is not what we do for checkboxes in general.
> > 
> > 
> > No, the issue is when you tab across it its invisible you do not know it's selected
> 
> Apologize, I can't understand what you mean.

**Comment by frankie139506** [comment]
Apologize, I can't understand what you mean.

**Review by timja — CHANGES_REQUESTED** [review]
This doesn't seem to be working for me, your video show clicking but the issue is about when tabbing through elements.

i.e. click username, see focus state:
image

Then press tab twice and you can't tell the checkbox is selected.

(apologies if the issue wasn't clear enough)

**Comment by frankie139506** [comment]
> This doesn't seem to be working for me, your video show clicking but the issue is about when tabbing through elements.
> 
> i.e. click username, see focus state: image
> 
> Then press tab twice and you can't tell the checkbox is selected.
> 
> (apologies if the issue wasn't clear enough)

Thanks for explaining.Don't we need a focus state when click the checkbox?

**Comment by timja** [comment]
> Thanks for explaining. Don't we need a focus state when click the checkbox?

Yes there should be some, looking closer I see you've fixed one half of this.

If it's selected it now works properly, i.e. if you click keep me signed in and then tab off it and back to it it's correctly got a focus state.

but the unchecked state is not working.

(so currently this is better than currently released version but would be good to fix the default state)

**Comment by frankie139506** [comment]
> > Thanks for explaining. Don't we need a focus state when click the checkbox?
> 
> Yes there should be some, looking closer I see you've fixed one half of this.
> 
> If it's selected it now works properly, i.e. if you click keep me signed in and then tab off it and back to it it's correctly got a focus state.
> 
> but the unchecked state is not working.
> 
> (so currently this is better than currently released version but would be good to fix the default state)

I have made some change, please take a look.

**Review by timja — APPROVED** [review]
LGTM thanks

**Review by basil — APPROVED** [review]
This PR is now ready for merge. We will merge it after approximately 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process. Thanks!

**Comment by NotMyFault** [comment]
> > No, the issue is when you tab across it its invisible you do not know it's selected
> 
> Oic, thanks for the clarification. My former question turns into an issue then.

Keep in mind that my issue outlined previously remained unaddressed and introduces a future regression, if that is a considerable merge blocker:

https://user-images.githubusercontent.com/13383509/184725774-0be7b5d4-5765-45a5-9119-58ca43d98cb8.mp4

**Comment by frankie139506** [comment]
> outlined

@NotMyFault It seems to me that if I click the checkbox, we get the focus state, that's why when you uncheck the checkbox, they still have the focus state. This is my humble opinion.

**Comment by timja** [comment]
@NotMyFault I see no issue there, when you uncheck it your focus state is on the checkbox. it should be highlighted

**Comment by NotMyFault** [comment]
> @NotMyFault I see no issue there, when you uncheck it your focus state is on the checkbox. it should be highlighted

If this is intended, it's incosistent with the overall checkbox design, see https://weekly.ci.jenkins.io/design-library/Checkboxes/ for example.

**Comment by timja** [comment]
> > @NotMyFault I see no issue there, when you uncheck it your focus state is on the checkbox. it should be highlighted
> 
> If this is intended, it's incosistent with the overall checkbox design, see [weekly.ci.jenkins.io/design-library/Checkboxes](https://weekly.ci.jenkins.io/design-library/Checkboxes/) for example.

It's not inconsistent, it's a bug this PR is fixing.
Which is why I updated the title and the changelog entry.

Try tabbing across the job configure page its impossible right now to know where you are -.-

**Comment by NotMyFault** [comment]
> Which is why I updated the title and the changelog entry.

Oic, I didn't notice this one, let's disregard my concern 👍🏻

**Pull request merged**
