### PR TITLE
JENKINS-65574 Reverse direction of build-progress animation

### PR DESCRIPTION
**Pull request by uhafner**
As discussed in the UX SIG channel, the build status animation of the new SVG icons should use the same direction as our other spinner animations. So I changed the animation from counter-clockwise to clockwise. Additionally, I added some pixels of space between the icon and the "Console Output" text. 

## Before

see our Jenkins CI

## After
 
https://user-images.githubusercontent.com/503338/117545161-e60f3680-b024-11eb-93dd-2f10fb96935c.mov

### Proposed changelog entries

* Entry 1: Enhancement, Improve build status progress animation
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@timja @fqueiruga 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
this could probably be backported to either .1 or .2 of LTS, so I created a jira issue for it

**Review by res0nance — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by uhafner** [comment]
I have just seen, that I the fix is not correct, sorry. Seems that the class `build-status-icon__wrapper` is also used on the build page. Here we now have too much margin. Should I simply revert https://github.com/jenkinsci/jenkins/pull/5471/commits/ef08fe97f49b129a063b05153919a84550702493?

**Comment by timja** [comment]
Yeah may as well

**Review by StefanSpieker — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]

**Pull request merged**
