### PR TITLE
Refresh the style of alerts

### PR DESCRIPTION
**Pull request by janfaracik**
Small pull request to refresh the style of alerts. Some minor tweaks to colours, border radius and weights to bring alerts more inline with the rest of Jenkins.

**Before**
image

**After**
image

I'll open a pull request for the dark theme plugin to match.

### Testing done

* Modified the Manage Jenkins screen to display all monitors to test a variety of styles, works as expected

### Proposed changelog entries

- Refresh the style of alerts.

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [x] The Jira issue, if it exists, is well-described.
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [x] There is automated testing or an explanation as to why this change has no tests.
- [x] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [x] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [x] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [x] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [x] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@jenkinsci/sig-ux 

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Review by timja — COMMENTED** [review]
Can you show all colours please?

success,info,danger,warning.

Even if its just in the browser changing classes

----

needs a dark theme PR

**Comment by janfaracik** [comment]
> Can you show all colours please?
> 
> success,info,danger,warning.
> 
> Even if its just in the browser changing classes
> 
> needs a dark theme PR

Opened a Design Library PR - https://github.com/jenkinsci/design-library-plugin/pull/318 - will update OP

**Review by timja — APPROVED** [review]
Screenshots with more detail:

<details>
<summary>Before</summary>

image


</details>


<details>
<summary>After</summary>

image


</details>

Main difference is the text is easier to read, looks nice to me

**Comment by janfaracik** [comment]
Thanks! Appreciate it.

With dark theme:

image

**Review by NotMyFault — APPROVED** [review]

**Review by StefanSpieker — APPROVED** [review]

**Comment by timja** [comment]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by janfaracik** [comment]
> I think this caused a regression for badges on manage Jenkins and other places where badges are used.
> 
> image
> 
> image
> 
> The badges make use of  the classes `alert-warning`, `alert-danger` and `alert-info`
> 
> 

Thanks, I'll take a look

**Pull request merged**
