### PR TITLE
[JENKINS-57922] - Ability to specify target directory for translation-tool.pl

### PR DESCRIPTION
**Pull request by mustafau**
See [JENKINS-57922](https://issues.jenkins-ci.org/browse/JENKINS-57922)
Also [JEP-216](https://github.com/jenkinsci/jep/tree/master/jep/216)

### Proposed changelog entries

* Added ability to specify target directory for translation-tool.pl

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
Looks good to me, but I am not sure whether we want to keep this tool in this repository at all. Maybe it is better to have a separate one with separate release cycle and CPAN deployments if needed

**Comment by mustafau** [comment]
Thanks @oleg-nenashev 

I have added another commit fixing an existing bug in the tool. There is also another bug I am investigating. The tool should make sure that there is a new line character at the end of an existing file before writing anything at all.

**Comment by oleg-nenashev** [comment]
I am going to merge it today. It is not a part of the production codebase, so I do not see need to wait for more reviews

**Comment by oleg-nenashev** [comment]
Thanks @mustafau !

**Pull request merged**
