### PR TITLE
[WiP] [FIXED JENKINS-23273] /etc/sysconfig option to skip (off default) long c...

### PR DESCRIPTION
**Pull request by jieryn**
...hown

### CODE REVIEW

**Comment by daniel-beck** [comment]
I don't think this needs to be an option. The suggested default behavior is simply broken.

**Comment by jieryn** [comment]
It's generally wrong to muck around with the existing and long time default behavior. There are still people on jenkins-user list emailing about upgrading from Hudson, literally Hudson. This served a purpose for a while, it should just remain in there..

**Comment by oleg-nenashev** [comment]
Cannot be merged

**Comment by jieryn** [comment]
https://github.com/jenkinsci/packaging/pull/2

**Pull request closed without merging**
