### PR TITLE
[JENKINS-28781] update the bct library to 1.6.2.

### PR DESCRIPTION
**Pull request by jtnord**
Pickup the changes in the bytecode-compatibility-transformer for
[JENKINS-28781](https://issues.jenkins-ci.org/browse/JENKINS-28781)

### CODE REVIEW

**Comment by jtnord** [comment]
@reviewbybees

**Comment by stephenc** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
:bee:

**Comment by jtnord** [comment]
@reviewbybees done

**Comment by KostyaSha** [comment]
Why not wait for PR builder results?!

**Comment by jtnord** [comment]
@KostyaSha because I forgot.  If they break I will look at them and revert if needed.

**Comment by oleg-nenashev** [comment]
@jtnord 
Yes, :-1: for immediate merging. We need to wait for the community feedback in any case. The next release ETA is October 12th, tho there is no hurry in any case

**Comment by KostyaSha** [comment]
This is called "insta-merge" :D

**Comment by jtnord** [comment]
@oleg-nenashev any community feedback on this should have happened in the PR for the BCT library itself.  I fail to see how anyone could vote -1 for this trivial change after the change in BCT was open for review for so long.

**Comment by oleg-nenashev** [comment]
@jtnord Not everybody is aware about libraries and monitors them. Particular libs like Stapler, winp, winsw, etc. are even located in other GitHub orgs. This PR should give such users a chance to shout about the issue before it gets merged.

**Comment by KostyaSha** [comment]
https://github.com/jenkinsci/bytecode-compatibility-transformer/commits/master was released few minutes ago, people has no time even to review released in `upstream` version.

**Comment by jtnord** [comment]
@KostyaSha [this](https://github.com/jenkinsci/bytecode-compatibility-transformer/pull/2) is the change and it was open for > 3 weeks for community review.
the other changes where trivial changes needed to release the plugin (m-r-p git bugs releasing a snapshot)

**Comment by jtnord** [comment]
@oleg-nenashev @KostyaSha I dropped the ball here, however I don't feel like this is contentious enough to revert just so we can get some feedback *if* the tests pass.

**Comment by KostyaSha** [comment]
@jtnord i.e. i usually reviewing what changes was done in release and not monitoring PRs in all libraries, because I can't be sure in master state as it can get more changes. So release is final thing that makes sense for reviewing. 

Issue with dependency update can be very difference, even java version mismatches and etc

**Comment by oleg-nenashev** [comment]
Yes, I think we can go forward and fix something in master if the tests fail

**Comment by KostyaSha** [comment]
@jtnord no need revert, but in future please at least wait for PR builder.

**Comment by jtnord** [comment]
@KostyaSha will do.

**Comment by jtnord** [comment]
[build](https://jenkins.ci.cloudbees.com/job/core/job/jenkins-core/3294/) passed.

**Comment by KostyaSha** [comment]
:+1:

**Comment by olivergondza** [comment]
@jtnord, looking at stacktraces this seems to be the cause of https://jenkins.ci.cloudbees.com/job/core/job/acceptance-test-harness/1251/testReport/plugins/BatchTaskPluginTest/do_not_trigger_for_failed_build/ and the rest of failures in BatchTaskPluginTest.

**Comment by jtnord** [comment]
@olivergonza looking at it.

**Comment by jtnord** [comment]
@olivergondza tracked as [JENKINS-30820](https://issues.jenkins-ci.org/browse/JENKINS-30820)

**Pull request merged**
