### PR TITLE
[JENKINS-68194] Delete `.disabled` file when uninstalling a plugin

### PR DESCRIPTION
**Pull request by benebsiny**
See [JENKINS-68194](https://issues.jenkins.io/browse/JENKINS-68194).

Delete the `.disabled` files when uninstalling the plugin, so the disabled status will be cleared.

### Proposed changelog entries

- Delete `.disabled` files when uninstalling a plugin

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] (If applicable) Jira issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  - Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")` if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content-Security-Policy directives (see [documentation on jenkins.io](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7042"></a>

### CODE REVIEW

**Comment by basil** [comment]
Did you try writing a test for this?

**Comment by benebsiny** [comment]
@basil Not yet. That's a great idea. I'll try it.

**Comment by daniel-beck** [comment]
Unsure this makes sense to implement while [JENKINS-69487](https://issues.jenkins.io/browse/JENKINS-69487) is open. At least currently, implied dependencies that are unexpectedly forcibly restored will not be enabled for no reason.

**Comment by benebsiny** [comment]
@basil Testcase added.

**Comment by benebsiny** [comment]
@daniel-beck I am unable to reproduce the [JENKINS-69487](https://issues.jenkins.io/browse/JENKINS-69487), but I though this PR could solve the problem you described in the `Notes` section

**Comment by daniel-beck** [comment]
@benebsiny Right, but disabling (with or without automatically being reinstalled) is currently the only way to prevent these plugins from being loaded again. Not a big deal if they just provide a library, but can be a problem if there's behavior associated with them: Since configuration files remain, any optional enabled features will reappear. At the moment, if someone first disables, then uninstalls, this change would cause undesirable behavior changes in Jenkins from re-installed, re-enabled plugins.

**Comment by daniel-beck** [comment]
> What is the path forward here?

I don't think this fix should be merged while we don't have a fix for [JENKINS-69487](https://issues.jenkins.io/browse/JENKINS-69487), as behavior will become worse for what I think is a fairly common case (disable first, then uninstall). Do not consider this blocking feedback, but I'm -1 on this PR.

**Comment by basil** [comment]
> Do not consider this blocking feedback, but I'm -1 on this PR.

I must not be understanding your definition of -1, because based on the [Apache definition](https://www.apache.org/foundation/voting.html) a -1 is both negative and blocking, unlike a -0 which is negative and non-blocking:

> A -1 vote by a qualified voter stops a code-modification proposal in its tracks. This constitutes a veto, and it cannot be overruled nor overridden by anyone. Vetoes stand until and unless the individual withdraws their veto.

---

I marked [JENKINS-68194](https://issues.jenkins.io/browse/JENKINS-68194) as depending on [JENKINS-69487](https://issues.jenkins.io/browse/JENKINS-69487) in Jira and am labeling this `on-hold` pending the fix for JENKINS-69487.

**Comment by daniel-beck** [comment]
When I provided the feedback above, I was thinking of a recent experience around implied dependencies. While that's annoying, it seems much less of a problem than plugins newly adding dependencies on previously disabled, then uninstalled, plugins being unable to start.

As far as I'm concerned, this can proceed.

CC @basil in case you'd like to have this remain `on-hold` anyway.

> a -1 is both negative and blocking, unlike a -0 which is negative and non-blocking

Interesting, thanks for that reference. I don't think we've used it as such, or if we did I was unaware. In project meetings, we (used to) add up individual votes and the decision is made according to the sign of the sum.

**Review by basil — APPROVED** [review]
> As far as I'm concerned, this can proceed.

Great! I downgraded the Jira relationship between the two issues from "depends on" to "relates to".

**Review by timja — APPROVED** [review]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Pull request merged**
