### PR TITLE
[JENKINS-39972] export fullName and fullDisplayName

### PR DESCRIPTION
**Pull request by mawinter69**
export fullName and fullDisplayName

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
I'm fine with fullName. Full display name is a bit debatable since the output may vary depending on the user. But IMHO fine as well. 👍

**Comment by daniel-beck** [comment]
Could there be encoding issues with `getFullDisplayName`? Has this been tested?

**Comment by mawinter69** [comment]
fullDisplayName is just a concatenation of the displayNames which is also exported, so if there is an encoding issue it would be also there

**Comment by daniel-beck** [comment]
@mawinter69 

> fullDisplayName is just a concatenation of the displayNames which is also exported

Well, except for the concatenating `»`.

**Comment by mawinter69** [comment]
`»` is a valid UTF-8 character. I tested that locally and it causes no problems. Anyway if this would be a problem this is something that would need to be fixed in stapler.

**Review by oleg-nenashev — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
@daniel-beck Are you fine with the explanation?

**Comment by daniel-beck** [comment]
@oleg-nenashev Works for me.

Not sure this should be visible out of the box, but not strongly opposed either.

**Comment by oleg-nenashev** [comment]
Maybe it's too late for merge into this weekly. Likely the release is in the progress.

**Pull request merged**
