### PR TITLE
[JENKINS-51965] - Added JAXB plugin as a split dependency

### PR DESCRIPTION
**Pull request by kohsuke**
See [JENKINS-51965](https://issues.jenkins-ci.org/browse/JENKINS-51965).

As a part of Java 9 support, we need to explicit carry around JAXB plug

https://github.com/jenkinsci/jaxb-plugin
https://github.com/jenkinsci/instance-identity-module/pull/11

### Proposed changelog entries
none
### Submitter checklist

- [x] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@oleg-nenashev

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@kohsuke IIUC your plan is to create another PR, right?

**Comment by kohsuke** [comment]
@oleg-nenashev and I talked and we decided to take a different more dumber approach. This PR now reflects that change

**Comment by oleg-nenashev** [comment]
I would like to do some testing before the merge, but looks good taking that we tried better options without success. The research is described in https://issues.jenkins-ci.org/browse/JENKINS-51965

**Comment by oleg-nenashev** [comment]
I tested it locally, and it looks good. But maybe it makes sense to review comments from @jglick in the ticket

**Comment by qq97241481** [comment]
yeap

**Comment by daniel-beck** [comment]
@oleg-nenashev  What is the status of this PR?

**Comment by oleg-nenashev** [comment]
The plan is to investigate it next month

**Comment by oleg-nenashev** [comment]
Closing in favor of #3865 by @batmat

**Pull request closed without merging**
