### PR TITLE
[JENKINS-55081] SEC-904 related test failing on java 11

### PR DESCRIPTION
**Pull request by Wadeck**
- just running the tests for the moment

See [JENKINS-55081](https://issues.jenkins-ci.org/browse/JENKINS-55081).

### Proposed changelog entries

* Internal: correct test failing with Java 11: `FilePathSEC904Test.isDescendant_regularFiles`

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [n/a] For dependency updates: links to external changelogs and, if possible, full diffs

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
LGTM as a test fix, but probably we need a user-facing changelog entry

**Comment by batmat** [comment]
I have checked the commits, and bear with me, I might have missed something. So IIUC, both tests and main code need to be changed because of the upstream `relativize` change in behavior.

To assess things stay fixed in Java 8, I think we should have the following:
1. first commit only changes src/main/java code, not touching src/test/java yet 
    * => we expect a PR build success on Java 8 (still ignore for now the failures with JDK11, given that's we're fixing)
2. Once this shows we are still green on !Java-11, we also change the test so we remove failures from JDK11.

This way we do know that the code on Java 8 was still checked to work with the original tests it was written with.

WDYT?

**Comment by Wadeck** [comment]
@batmat I did not change the failing tests. I just added new ones.

**Comment by batmat** [comment]
Right indeed, I don't know why I thought I had seen replacements.

**Review by batmat — APPROVED** [review]

**Comment by batmat** [comment]
Ping @jenkinsci/java11-support BTW given this does relate to an issue only surfacing with Java 11.

**Review by MRamonLeon — APPROVED** [review]

**Comment by Wadeck** [comment]
Tests failing due to:
- `hudson.model.QueueTest.testBlockBuildWhenUpstreamBuildingLock` <= flaky / time-dependent test
  - `new SleepBuilder(5000), [...] new SleepBuilder(10000)`
- `hudson.util.AtomicFileWriterPerfTest.poorManPerformanceTestBed` <= Baptiste is already on it

**Review by jvz — APPROVED** [review]

**Comment by batmat** [comment]
I'm seeing only the latter failing:

image

Which indeed I am still analyzing in #3788 

Let's merge this.

**Comment by batmat** [comment]
Filed as https://github.com/jenkinsci/jenkins/pull/3797

**Pull request merged**
