### PR TITLE
[JENKINS-67372] Restore support for symbolic links in the Jenkins home directory

### PR DESCRIPTION
**Pull request by basil**
See [JENKINS-67372](https://issues.jenkins.io/browse/JENKINS-67372). Fixes a regression introduced in #6025 when the Jenkins home directory is a symbolic link.

### Proposed changelog entries

- Restore support for symbolic links in the Jenkins home directory (regression in 2.325).

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by basil** [comment]
Leaving this as draft because I plan to write some tests for this. In the meantime I tested the fix interactively and I believe it is correct, so might as well get an incremental build to provide relief for any affected user(s).

**Comment by basil** [comment]
The new test passes on [Java 8](https://ci.jenkins.io/job/Core/job/jenkins/job/PR-6059/7/testReport/hudson/UtilTest/Linux_jdk8___Linux_Publishing___createDirectories/) and [Java 11](https://ci.jenkins.io/job/Core/job/jenkins/job/PR-6059/7/testReport/hudson/UtilTest/Linux_jdk11___Linux_Publishing___createDirectories/). A user has [manually tested the fix](https://issues.jenkins.io/browse/JENKINS-67372?focusedCommentId=417098&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-417098) successfully.

**Review by timja — APPROVED** [review]

**Comment by basil** [comment]
Would be nice to get this merged toward the next weekly to provide relief to the affected users. [Two](https://issues.jenkins.io/browse/JENKINS-67372?focusedCommentId=417098&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-417098) [users](https://issues.jenkins.io/browse/JENKINS-67372?focusedCommentId=417102&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-417102) have confirmed that the incremental build from this PR resolve the issue for them.

**Review by oleg-nenashev — APPROVED** [review]
+1 for releasing it in the next weekly

We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Pull request merged**
