### PR TITLE
[JENKINS-33546] [JENKINS-33605] Back to Stapler 1.239

### PR DESCRIPTION
**Pull request by daniel-beck**
[JENKINS-33546](https://issues.jenkins-ci.org/browse/JENKINS-33546)
[JENKINS-33605](https://issues.jenkins-ci.org/browse/JENKINS-33605)

While Stapler is being fixed, let's make sure there's not another Jenkins release with these regressions in it.

@reviewbybees

CC @vivek @kohsuke

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
:+1: . 

P.S: The initial commit message was bad. The revert commit message makes me crying :(

**Comment by batmat** [comment]
:+1: and +1 with @oleg-nenashev for the commit message [could have been more explicit](https://github.com/jenkinsci/jenkins/pull/2076#issuecomment-192178072)...

**Comment by jglick** [comment]
:bee:

**Comment by jglick** [comment]
(_but_ this would be a perfect opportunity to introduce a regression test)

**Comment by daniel-beck** [comment]
@jglick I signed @vivek up for that.

**Pull request merged**
