### PR TITLE
[FIX JENKINS-33127] BootFailures send HTTP 500

### PR DESCRIPTION
**Pull request by daniel-beck**
HTTP 500 is used for `oops.jelly`, so it seemed the most appropriate for the various `BootFailure`s as well.

Untested, which in the case of `JenkinsReloadFailed/index.groovy` could be a problem (nowhere to copy&paste from). If someone knows how to trigger this one, please let me know.

@reviewbybees

### CODE REVIEW

**Comment by KostyaSha** [comment]
:+1:

**Comment by aheritier** [comment]
:bee: the build error isn't related to your PR, master is also broken : https://jenkins.ci.cloudbees.com/job/core/job/jenkins-core/4026/console

**Comment by jglick** [comment]
Please merge with `master`.

**Comment by jglick** [comment]
I think `BootFailure` should get a default `index.jelly` which includes a `details.jelly` view, the default version of which would simply `${h.printThrowable(it.cause)}`. Then we would not need to have so much duplicated boilerplate.

**Comment by jglick** [comment]
Anyway, :bee:

**Comment by aheritier** [comment]
@jglick I imagine that the best to do for @daniel-beck is to rebase it on top of the current master to have the build fixed ? Is it what you mean by merge with master ?

**Comment by jglick** [comment]
Rebasing is evil. `git merge master` suffices.

**Comment by daniel-beck** [comment]
@jglick @aheritier Merged master.

**Comment by jglick** [comment]
:bee:

**Pull request merged**
