### PR TITLE
Make changelog URL a build parameter

### PR DESCRIPTION
**Pull request by aldaris**
This is my latest attempt to resolve JENKINS-24469 (which is potentially a duplicate of JENKINS-12429, i.e. display the stable changelog URL in the upgrade available notification when stable version of Jenkins is currently being used.
After the patch is applied, LTS releases should be built using the lts-release Maven profile (-Plts-release).

This is a follow-up changeset for #1045 , unfortunately I didn't quite see how the Jenkins.getVersion() could be used to detect if the release is stable (contains two dots??), so this approach is modifying the build process instead.

### CODE REVIEW

**Comment by KostyaSha** [comment]
> detect if the release is stable (contains two dots??)

:atm: - yes

**Comment by daniel-beck** [comment]
Given how https://github.com/jenkinsci/packaging works, I expect the URL to just get passed as argument in all productive cases anyway.

**Comment by jtnord** [comment]
@daniel-beck huh?  packaging doesn't build the war only the native installers and push bits around.

**Comment by daniel-beck** [comment]
@jtnord Right, sorry about that. I blame jet lag.

**Comment by daniel-beck** [comment]
I think we can merge this as is :+1:

**Comment by jtnord** [comment]
the code looks fine.  Selfishly I would prefer that none of this was in multiple resource files - and that all callers passed in the url which was obtained from a single place...  
But I'll take my day job hat off and say :+1:

**Pull request merged**
