### PR TITLE
[JENKINS-32493] Remove plugin parent POM from core project.

### PR DESCRIPTION
**Pull request by andresrc**
[JENKINS-32493](https://issues.jenkins-ci.org/browse/JENKINS-32493)

As part of the process of getting a [new plugin parent POM](https://github.com/jenkinsci/plugin-pom) decoupled from the core project the plugin module is removed.

@reviewbybees

### CODE REVIEW

**Comment by batmat** [comment]
:+1:

**Comment by olivergondza** [comment]
Does it makes sense to preserve the commit history in the new repo? Or it was rewritten from scratch?

**Comment by andresrc** [comment]
As @stephenc commented on the mailing list, it has evolved partly from a parent pom used internally at CloudBees, not from the existing one.

**Comment by jtnord** [comment]
:bee:

**Comment by jglick** [comment]
:bee:

**Comment by andresrc** [comment]
@reviewbybees done

**Comment by oleg-nenashev** [comment]
Nice achievement for the 2000th pull request :)

**Comment by andresrc** [comment]
:smile:

**Pull request merged**
