### PR TITLE
Translate into Simplified Chinese with creating new properties file

### PR DESCRIPTION
**Pull request by node**
This is an i18n pr with only one  message properties file creating . It's better to request an Chinese speaking reviewer to review.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
CC  @LinuxSuRen

**Comment by LinuxSuRen** [comment]
ok, i will review this later

**Comment by node** [comment]
Here is a easy to read link https://www.zybuluo.com/node/note/966000

**Comment by LinuxSuRen** [comment]
@oleg-nenashev already review, it is very well.

**Comment by daniel-beck** [comment]
Thanks @node and @LinuxSuRen

**Pull request merged**
