### PR TITLE
fixup search and filter case sensitive issue in PluginManager

### PR DESCRIPTION
**Pull request by mamh2021**
fixup '%search' and '%filter' case sensitive in src/main/resources/hudson/PluginManager
in table_xxx.properties and installed_xxx.properties files I found the "filter" startswith a capital letter,
so I choose to the upper case. the "search" is not in any properties files, both upper and lower case are OK,
in order to keep the style same I choose the upper case too.

this PR is fixup for https://github.com/jenkinsci/jenkins/pull/4580

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

### Proposed changelog entries

* Entry 1: Issue, Human-readable Text
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by mmh891113** [comment]
hi @daniel-beck ,
I create one PR try to fixup this issue. the ${%Filter} for localizer is not available in PluginManager UI.
Can you help me review it , thank you very much.

see https://github.com/jenkinsci/jenkins/pull/4580

**Comment by daniel-beck** [comment]
It is unclear why this should result in the English localization being changed from lowercase to uppercase. Could you explain?

**Comment by mmh891113** [comment]
QQ拼音截图20201015080424

Before this PR https://github.com/jenkinsci/jenkins/pull/4580 , the filter was uppercase.

If not change to uppercase other language localization would not work well.Or we can modify  table_xxx.properties and installed_xxx.properties files,But that would be a lot of work.

**Comment by daniel-beck** [comment]
@mmh891113 Another option would be to provide an English override in `installed.properties` etc. that maps `Filter=filter`.

Also, search and replace of one line in ~10 files is not a lot of work.

**Comment by varyvol** [comment]
@daniel-beck I'm not sure I get your point. Changing the jelly file allows for 27 properties files to work correctly. Why should those be changed instead?

**Review by alecharp — APPROVED** [review]
I feel like it's easier to revert the jelly file than changing *all* the `installed*.properties` to match the `filter` syntax. Also because, even those without any translation will have to be updated to use `Filter` in the UI.

**Review by MRamonLeon — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
Looks good to me. Since @daniel-beck did not request changes in the review, I suggest going forward. Thanks for your contribution @mageSFC2020 !

We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

P.S: If this is a Hacktoberfest pull request, please let us know so that we can label it properly and facilitate reviews. Check out [this page](https://www.jenkins.io/events/hacktoberfest/) for more information about Jenkins in Hacktoberfest: guidelines, featured projects, etc. 

[image](https://www.jenkins.io/events/hacktoberfest/)

**Review by daniel-beck — CHANGES_REQUESTED** [review]
The change to the English UI is unintentional and unnecessary. This PR should provide a lowercase English localization.

**Comment by oleg-nenashev** [comment]
@mageSFC2020 hi. Are you interested in finalizing the pull request?

**Comment by alecharp** [comment]
@mamh2021 could you look into the comment from Daniel and fix localization? In the meantime, I'm adding the `proposed-for-close` label. Thanks.

**Comment by basil** [comment]
To summarize:

- @daniel-beck created #4580, which was merged and released.
- @mamh2021 created this PR as a fixup to #4580.
- @daniel-beck (the original author of #4580) requested changes on this PR.
- A year and a half later, this request for change has not been accommodated.

Due to inactivity, I am closing this PR. On behalf of the core team, I would like to thank you for your contribution. Even though this PR did not make it across the finish line, it was a promising start! I continue to encourage you (or anyone else who is interested!) to pick up this PR and drive it to completion. Thanks!

**Pull request closed without merging**
