### PR TITLE
[JENKINS-45892] Enhanced diagnostics

### PR DESCRIPTION
**Pull request by jglick**
Improves upon #2957.

@reviewbybees

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]

**Comment by jglick** [comment]
@reviewbybees done

**Review by daniel-beck — APPROVED** [review]

**Comment by rtyler** [comment]
Currently building a master image now, will be rolling out for testing shortly

**Comment by rtyler** [comment]
Rebuilding a master image with the latest set of changes, should be rolled out and running within an hour.

**Comment by daniel-beck** [comment]
@rtyler commented on IRC that this seems to work now.

**Comment by oleg-nenashev** [comment]
🚢 🇮🇹

**Pull request merged**
