### PR TITLE
JENKINS-33930 focus color for delete

### PR DESCRIPTION
**Pull request by gusreiber**
@reviewbybees

OLD | NEW :
image

### CODE REVIEW

**Comment by gusreiber** [comment]
css change for focus button only.

**Comment by daniel-beck** [comment]
@gusreiber Could you attach screenshots for before/after comparison?

**Comment by daniel-beck** [comment]
Tested it, looks fine. Despite the name, the dark one is the focus color.

Unfocused:

> screen shot

Focused:

> screen shot

**Comment by jglick** [comment]
:bee: without testing

**Comment by kzantow** [comment]
:bee: though, I still have concerns about the accessibility of it all. guidelines / certain requirements need more than color changes. anyway, it's an improvement, as it stands and this is a drop in the bucket of an overall review of accessibility.

**Comment by recena** [comment]
@kzantow Count with me for that task.

**Comment by batmat** [comment]
:+1:

**Pull request merged**
