### PR TITLE
[FIXED JENKINS-29790] Protect from race condition in TimerTrigger

### PR DESCRIPTION
**Pull request by KostyaSha**
https://issues.jenkins-ci.org/browse/JENKINS-29790

### CODE REVIEW

**Comment by KostyaSha** [comment]
@jglick you are welcome

**Comment by oleg-nenashev** [comment]
@KostyaSha 
You should assign the <code>job</code> to a temporary variable and then use it in order to be 100% sure that the value does not changes to null after the check

**Comment by KostyaSha** [comment]
@oleg-nenashev ??

**Comment by Vlatombe** [comment]
oleg is right, if you don't use a local variable the code isn't thread-safe, even if the risk is indeed very low.

**Comment by KostyaSha** [comment]
This check only skips unstarted run, if you want fix in other way then you are welcome.

**Comment by KostyaSha** [comment]
If you see "race condition" words that doesn't mean that it's thread issue. This object is single threaded.

**Comment by jglick** [comment]
The `job` variable is set to non-null in `start`. It is not set back to `null` in `stop`. So it suffices to do a nullness check on the instance variable without a local copy. :+1:

**Comment by KostyaSha** [comment]
cc @olivergondza this probably could be useful for LTS, but i don't know whether root change is in LTS.

**Comment by olivergondza** [comment]
@KostyaSha, 1.609.3 will not receive any more backports and new line was not picked yet. Please, make sure `lts-candidate` is tracked in JIRA.

**Comment by KostyaSha** [comment]
@olivergondza checked, change appeared only in 1.621, so no problems for current lts

**Comment by KostyaSha** [comment]
Rebased, squashed, added tests and license markers that so likes everybody.

**Comment by jglick** [comment]
:+1:

**Comment by lanwen** [comment]
:+1:

**Comment by jglick** [comment]
Need a fix for `hashCode` too, apparently: [JENKINS-29945](https://issues.jenkins-ci.org/browse/JENKINS-29945)

**Comment by jglick** [comment]
:+1:

**Comment by lanwen** [comment]
:+1:

**Comment by oleg-nenashev** [comment]
:+1:

**Pull request merged**
