### PR TITLE
Minor improvements to JSON signature validation

### PR DESCRIPTION
**Pull request by daniel-beck**
- Complete checksum validity check before starting signature
- Print both provided and computed digests if they mismatch
- Log the canonical JSON rather than prettyprinted, but only on FINE

----

Minimal testing, just some stuff I did locally trying to understand a checksum problem earlier ([with an entirely different cause](https://github.com/jenkins-infra/update-center2/pull/365/commits/b166adf91339b76758158fe8bb42bf9e9c0eeb5e)).

### Proposed changelog entries

Unsure. Too minor?

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Review by jvz — APPROVED** [review]
Looks fine to me. I can't pass an opportunity to shill for AES/GCM which automatically signs everything it encrypts.

**Comment by daniel-beck** [comment]
> I can't pass an opportunity

You should at least try though. Plus we're not encrypting anything here.

**Comment by jvz** [comment]
> > I can't pass an opportunity
> 
> You should at least try though. Plus we're not encrypting anything here.

image

**Review by fcojfernandez — APPROVED** [review]

**Review by alecharp — APPROVED** [review]
Looks good to me. Thanks!

**Comment by daniel-beck** [comment]
Thanks for the reviews, I prefer to give this some additional testing to ensure I'm not accidentally introducing a security issue. Once done, I will restore ready-for-merge.

**Review by varyvol — APPROVED** [review]

**Review by MRamonLeon — APPROVED** [review]

**Comment by varyvol** [comment]
@daniel-beck were you able to perform some additional testing on this? Or is there something else pending?

**Comment by alecharp** [comment]
@daniel-beck were you able to get back on this PR?

**Pull request closed without merging**
