### PR TITLE
Jenkins CLI now connect to existing SSH agent for authentication

### PR DESCRIPTION
**Pull request by rborer**
If an existing SSH agent is detected, the CLI will try to use its known identities to authenticate towards Jenkins. This allow the CLI to not ask the SSH key passphrase at each command.

Agent communication is done through project jsch-agent-proxy (https://github.com/ymnk/jsch-agent-proxy), this new dependency increase the jar size from 2.5 to 3.9 mb.

This has been successfully tested both on OSX (with the OpenSSH agent) and on Windows 8 with Pageant.

### CODE REVIEW

**Comment by jontro** [comment]
Could the jars be repackaged otherwise using the http://sonatype.github.io/jarjar-maven-plugin/ ?

**Comment by daniel-beck** [comment]
@rborer The reason this was delayed no longer applies (CC @jglick). Are you interested in updating this PR (or maybe resubmitting a new one)?

**Comment by daniel-beck** [comment]
Not sure whether this still is useful in the current CLI state, but the PR hasn't been updated in years and has merge conflicts, so closing for now. Please rebase onto current Jenkins and submit a new PR if you're still interested in this.

**Comment by rborer** [comment]
@daniel-beck sorry, your previous message from May 2016 slipped through my inbox! 

Unfortunately I don't have access to the underlying Jenkins instance anymore so it'll be hard for me to work on it...

**Pull request closed without merging**
