### PR TITLE
Choose more mnemonic artifactId’s for modules not consumed externally

### PR DESCRIPTION
**Pull request by jglick**
No issue, no changelog needed. Just trying to make `artifactId`s be more consistent and independently meaningful.

In particular, `test` was weird. As of the creation of an independent `jenkins-test-harness`, this artifact is no longer consumed externally (it is not even `deploy`ed), so we can choose the name freely. The name of the parent POM is also of no consequence to outside consumers. It would be nice to rename `cli` to `jenkins-cli` but I fear that might break some external build (hard to say what exactly).

@reviewbybees @jenkinsci/code-reviewers

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
It may collide with https://github.com/jenkinsci/pom/blob/master/pom.xml , but that guy also needs sosme cleanup in terms of naming. So 🐝

**Comment by jglick** [comment]
I do not think it should “collide” in any way—what are you thinking of?

**Comment by oleg-nenashev** [comment]
I mean we have a naming overlap.
Anyway, @reviewbybees done

**Comment by jglick** [comment]
> we have a naming overlap

How so? That is `org.jenkins-ci:jenkins`. This proposes `org.jenkins-ci.main:jenkins-parent`.

**Review by daniel-beck — APPROVED** [review]
Couldn't find affected infra, so seems reasonable.

**Comment by oleg-nenashev** [comment]
merge conflict

**Pull request merged**
