### PR TITLE
[FIXED JENKINS-28425] Fix build history styling badness

### PR DESCRIPTION
**Pull request by thomassuckow**
Pics: https://issues.jenkins-ci.org/browse/JENKINS-28425

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
:+1:

**Comment by KostyaSha** [comment]
:+1:

**Comment by tfennelly** [comment]
@thomassuckow Thanks, thanks for looking to fix this.

Did you test your changes with a variety of builds - longer names, descriptions etc? I will get the CI war and test it. Thanks again.

**Comment by tfennelly** [comment]
@thomassuckow Looks good. Thanks again.

I did notice one other issue (not a regression of this PR) when using the [Groovy Postbuild Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Groovy+Postbuild+Plugin) attaching lots of labels. The labels have no space between them, so when there are lots of them, they run out across the page (instead of wrapping).

Adding the following CSS at line 1044 fixes that. I will do a followup PR for that issue.

```css
.build-row-cell .build-badge span:after {
    content: " ";
    font-size: 0%;
}
```

**Comment by thomassuckow** [comment]
@tfennelly I did not test with longer names, though the change should be low risk. The biggest risk is the margin->padding change as the element is now narrower.

**Pull request merged**
