### PR TITLE
[FIXED JENKINS-19634] Fix sorting percentages

### PR DESCRIPTION
**Pull request by smccarthy**
This fixes the sorting of percentages.

### CODE REVIEW

**Comment by smccarthy** [comment]
Notice the Success Percentage column. 

Broken : broken screenshot

Fixed : 
fixed screenshot

**Comment by daniel-beck** [comment]
Do you think it's feasible to order `<100%` and `>0%` just before/after `100%`/`0%`?

**Comment by smccarthy** [comment]
@daniel-beck I can look at that today. I think it would probably be possible.

**Comment by smccarthy** [comment]
I have no more commits for this PR. Please let me know if anything else is required.

Thank you!

**Comment by smccarthy** [comment]
@daniel-beck Hi Daniel, Do you know when this PR will get looked at and merged? Sorry if you are the wrong person to contact. I don't know who else to contact, and you were the only one who commented on this PR.

Thanks !

**Comment by daniel-beck** [comment]
@smccarthy Thanks for pinging me, and sorry about the delay! I generally like to see a second opinion first, but as none is forthcoming, I'm merging this. It looks safe enough.

**Comment by smccarthy** [comment]
Thanks @daniel-beck  !

**Pull request merged**
