### PR TITLE
SCM._for is actually @CheckForNull.

### PR DESCRIPTION
**Pull request by jglick**
Correcting minor annotation mistake introduced in 1.568. @reviewbybees

### CODE REVIEW

**Comment by jtnord** [comment]
+1

**Comment by daniel-beck** [comment]
@reviewbybees Consider mentioning who you are when reviewing on the phone.

**Comment by oleg-nenashev** [comment]
I would also document the behavior in <code>@return</code>

**Comment by jglick** [comment]
> Consider mentioning who you are when reviewing on the phone.

Seconded. I think that would be @stephenc.

Also I will try to CC @cloudbees/jenkins-enterprise which GitHub claims works!

**Comment by stephenc** [comment]
:+1:

**Comment by tfennelly** [comment]
:+1:

**Pull request merged**
