### PR TITLE
Remove checkUpdates dead code

### PR DESCRIPTION
**Pull request by timja**
See https://github.com/jenkinsci/jenkins/pull/4518#pullrequestreview-384264849,
@daniel-beck found this was dead, I've searched the code and explored the UI without it and all seems fine

### Proposed changelog entries

* Entry 1: Not worth it imo
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

### CODE REVIEW

**Comment by daniel-beck** [comment]
Amends https://github.com/jenkinsci/jenkins/pull/4613.

**Review by daniel-beck — APPROVED** [review]
Thanks!

**Comment by timja** [comment]
merging as trivial

**Comment by jglick** [comment]
> merging as trivial

https://www.reddit.com/r/math/comments/5kjjfb/the_story_of_the_professor_who_said_it_was_trivial/dbojmgh/

**Pull request merged**
