### PR TITLE
Upgrade groovy to 3.x

### PR DESCRIPTION
**Pull request by timja**
See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

So far basic sanity tests seem to work

All illegal reflective access warnings from groovy disappeared

Script console works

Running a pipeline works

### Proposed changelog entries

* Entry 1: Groovy upgraded to 3.0.7
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by daniel-beck** [comment]
Previously: https://github.com/jenkinsci/jenkins/pull/3719 https://github.com/jenkinsci/jenkins/pull/3605

> Running a pipeline works

I'm very surprised.

@jglick @abayer @dwnusbaum ?

**Comment by oleg-nenashev** [comment]
> I'm very surprised.

Depends on the Pipeline complexity. When we were doing Java 11 compatibility, simple Pipelines also worked out of the box on Groovy 3. Real Pipelines - not so much. Also, we need to keep in mind new memory leaks and sandbox escapes

**Review by jglick — CHANGES_REQUESTED** [review]
We do not want the version used by `script-security` changed, it is too risky.

**Comment by timja** [comment]
> We do not want the version used by `script-security` changed, it is too risky.

Can you expand on this?
Don’t we have to update it at some point?

p.s this is an experiment right now to see what breaks, no merge expectations at all

**Comment by jglick** [comment]
> Can you expand on this?

Basically every Groovy language feature is associated with one or more critical security vulnerabilities we had to patch in `groovy-sandbox` (plus, often, matching changes in `groovy-cps`). Groovy 3.x adds a bunch of features, thus is almost certain to introduce vulnerabilities. It is basically @dwnusbaum alone doing this work and I doubt he can spare extra time, nor can others help without years of experience with these issues (they are very hard to reason about and debug). If you want to take over this area on the CERT team for a while and then do some weeks (?) of research on 3.x and commit to rapid responses to new vulnerabilities as they are reported (this is a favorite area for “independent security researchers” for obvious reasons), then we can discuss.

> Don’t we have to update it at some point?

Do we?

To be clear, I do not care if the version used for `/script` and other non-sandboxed raw-Groovy applications changes. Non-sandboxed Pipelines…well, if a new version of Groovy passes all known automated tests, then probably most users will be unaffected by functional regressions—some weird idioms will break in some users’ scripts, and actually attempting to _use_ the new Groovy features in CPS-transformed scripts will very likely not work and may break in creative and opaque ways, and we may see novel memory leaks that are also tricky to track down. The blocker for me is sandboxed usage (anything using the `script-security` plugin).

https://github.com/jenkinsci/jenkins/pull/3605#issuecomment-465557917 basically still applies.

**Comment by timja** [comment]
> Do we?

Well if we ever want to fix the IllegalReflectiveAccess warnings then we need to, they were fixed in 3.x.

> To be clear, I do not care if the version used for /script and other non-sandboxed raw-Groovy applications changes. Non-sandboxed Pipelines…well, if a new version of Groovy passes all known automated tests, then probably most users will be unaffected by functional regressions

I assume that's not possible right now without some form of relocation in core / hiding the classes from plugins as core provides groovy for everyone?

**Comment by jglick** [comment]
> …as core provides groovy for everyone?

Correct. Anyway I am not sure we would really want to be bundling _two_ versions of Groovy, and that would not help with the Java 9+ warnings either right?

**Comment by daniel-beck** [comment]
@timja Can we close this PR?

**Comment by timja** [comment]
sure not really looking at this one atm

**Pull request closed without merging**
