### PR TITLE
Update to animal-sniffer 1.16

### PR DESCRIPTION
**Pull request by batmat**
Let's upgrade to last release. No specific reason/issue for this, just trying to keep things up-to-date.

See the announcement: https://groups.google.com/forum/#!msg/mojohaus-dev/1X3FFgNYB98/NWwm56D9AAAJ

I had [tested it when staged, no issue found](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/mojohaus-dev/U54UXKYt8p8/7ItZA1wRCAAJ).

### Proposed changelog entries

* Internal: Update to [animal-sniffer 1.16 release](https://groups.google.com/forum/#!msg/mojohaus-dev/1X3FFgNYB98/NWwm56D9AAAJ)
### Submitter checklist

- ~~[ ] JIRA issue is well described~~
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@reviewbybees esp @jglick because https://github.com/mojohaus/animal-sniffer/issues?utf8=%E2%9C%93&q=milestone%3A1.16%20is%3Aclosed%20author%3Ajglick

### CODE REVIEW

**Comment by batmat** [comment]
Finally done "upstream" in https://github.com/jenkinsci/pom/pull/15, waiting for it.

**Comment by batmat** [comment]
Ready to review, bumped to release version.

**Review by jglick — APPROVED** [review]
Sounds fine to me.

**Comment by batmat** [comment]
Waiting until next release ~Monday and possibly more reviews and will merge if nobody objects in the meantime.

@reviewbybees done

**Review by oleg-nenashev — APPROVED** [review]
🚢 🇮🇹

**Pull request merged**
