### PR TITLE
[JENKINS-53710] Fix signature check on Java 11

### PR DESCRIPTION
**Pull request by daniel-beck**
See [JENKINS-53710](https://issues.jenkins-ci.org/browse/JENKINS-53710).

### Proposed changelog entries

* Fix update center signature check on Java 11

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [n/a] Appropriate autotests or explanation to why this change has no tests
- [n/a] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@oleg-nenashev @bitwiseman @svanoort

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
Would be nice to have a comment describing the behavior and risks

**Comment by svanoort** [comment]
For understanding of those who won't follow:

* According to daniel, signature verification mangles internal checksums (state gets mutated)
* So, we need to avoid running verify if the data is not valid
* Signature might be hex or base64
* First we check if it can decode as hex (and if so, welp we compare, but if it won't accept the format, it  will throw an exception rather than mutating the signature)
* Then we check as Base64
* Note that it's POSSIBLE to have Base64 that can be decoded as HEX,  but the odds are `(16/64) ^ n` where n is the number of characters

**Comment by daniel-beck** [comment]
Just in case: This should not be merged as is. I just thought the bug and fix was entertaining enough to post.

<details>
<summary>Spoiler here</summary>

My current understanding of the problem and this fix:

The problem is that the call to `signature.verify` resets the internal state of the message digest, and a subsequent call without going through the `DigestOutputStream` updating the digest will result in a wrong checksum. For unknown reason this is only a problem for SHA-512 and Java 11.

This fix works by putting the format that is less likely to be successfully parsed as the other format first: Any hexadecimal string can be interpreted as a valid base64 string (especially if we ignore the `=` padding, but the opposite is _vastly_ less likely (as in, somewhere between 4E-60 and 8E-78).

Since a non-hexadecimal base64 string will now result in an exception, there will only be one invocation of `verify`, with the expected argument.
</details>

**Review by svanoort — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
I confirm that this fix works well with Plugin and Tool installation logic on JDK11.
#3652 integrated the fix towards the Java 11 support branch

**Comment by daniel-beck** [comment]
So… maybe we should merge it as is after all? I added a lengthy comment why it works.

**Review by oleg-nenashev — APPROVED** [review]
I agree with the approach, let's merge it

**Pull request merged**
