### PR TITLE
[JENKINS-69543] Fix thread safety in websockets handling.

### PR DESCRIPTION
**Pull request by Vlatombe**
Follow-up of #6780, #6801

Session-holding maps are accessed by multiple threads.

Even though some concurrent access version of this would perform better it should be safe to access sessions in a synchronized way.

`org.springframework.util.ConcurrentReferenceHashMap` could be an alternative if synchronized access is too slow.

See [JENKINS-69543](https://issues.jenkins.io/browse/JENKINS-69543).

### Proposed changelog entries

- Fix thread safety in websockets handling.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] (If applicable) Jira issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  - Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")` if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content-Security-Policy directives (see [documentation on jenkins.io](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7076"></a>

### CODE REVIEW

**Comment by krisstern** [comment]
Should I backport this ASAP for the LTS 2.361.1 release?

**Comment by timja** [comment]
> Should I backport this ASAP for the LTS 2.361.1 release?

Generally no it needs real world testing via the weekly line.

Unless others have evidence that this is a critical issue for the release and needs to go in ASAP

**Comment by NotMyFault** [comment]
Is this intended to be a TODO for today's LTS release @Vlatombe? The release took already place, and backporting outside from weekly's aren't eligible.

**Review by jglick — APPROVED** [review]
Good catch!

**Review by basil — APPROVED** [review]
Very nice! Too bad this did not make it into 2.361.1 LTS, as there is no workaround on the client side. I suppose the best we can do is get this into 2.361.2 LTS. Thanks for the PR!

**Comment by basil** [comment]
This PR is now ready for merge. We will merge it after approximately 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process. Thanks!

**Pull request merged**
