### PR TITLE
Update Mockito from 2.22.0 to 3.0.0

### PR DESCRIPTION
**Pull request by sullis**
See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

### Proposed changelog entries

* Entry 1: Issue, Human-readable Text
* ...

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### CODE REVIEW

**Comment by jvz** [comment]
What's new in 3.0? Any compatibility issues we should be concerned about?

**Comment by sullis** [comment]
image

**Comment by sullis** [comment]
Mockito 3.x is compiled for Java 8.  (earlier versions of Java are not supported)

**Comment by jvz** [comment]
Oh, that's good news!

**Comment by oleg-nenashev** [comment]
Same as https://github.com/jenkinsci/plugin-pom/pull/217 for plugins

**Review by oleg-nenashev — APPROVED** [review]
I am fine with the update as long as CI passes

**Review by MRamonLeon — APPROVED** [review]

**Review by fcojfernandez — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
will merge tomorrow if no negative feedback

**Review by res0nance — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Thanks a lot for your contribution @sullis !

**Pull request merged**
