### PR TITLE
[JENKINS-68801] - Fix for Functions#extractPluginNameFromIconSrc

### PR DESCRIPTION
**Pull request by bzzitsme**
See [JENKINS-68801](https://issues.jenkins.io/browse/JENKINS-68801).

If our plugin's artifactId will contain "plugin-", then it will replace all "plugin-" occurences instead of first one.
Then it won't be able to correctly extract plugin name

### Proposed changelog

* Use correct icon lookup even when plugin ID includes more than one occurrence of "plugin".

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")` if applicable.
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@timja @janfaracik 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/6902"></a>

### CODE REVIEW

**Comment by bzzitsme** [comment]
Hi @janfaracik @timja
Could you take a look at this PR?

**Comment by timja** [comment]
Is this a theoretical issue or do you have a plugin which includes the text `plugin-` in it?

**Comment by bzzitsme** [comment]
> Is this a theoretical issue or do you have a plugin which includes the text `plugin-` in it?

We have plugin named cloudbees-plugin-usage-plugin which has artifactId "cloudbees-plugin-usage"

**Comment by daniel-beck** [comment]
There's also https://plugins.jenkins.io/plugin-util-api/ https://plugins.jenkins.io/plugin-usage-plugin/ https://plugins.jenkins.io/cloudbees-plugin-gateway/ https://plugins.jenkins.io/icn-plugin-loader/ which might hit this.

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
(untested, but I assume you have)

**Review by NotMyFault — APPROVED** [review]

**Comment by timja** [comment]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by bzzitsme** [comment]
> (untested, but I assume you have)

I have tested it and it works fine

**Review by yaroslavafenkin — APPROVED** [review]
Looks reasonable to me. 
Do we maybe want to add a tiny unit test for this? E.g.  [FunctionsTest.java#L398](https://github.com/jenkinsci/jenkins/blob/6d179998e18adfbaa4e443c7e837135bf36c53d7/core/src/test/java/hudson/FunctionsTest.java#L398)

**Comment by bzzitsme** [comment]
> Do we maybe want to add a tiny unit test for this? E.g. [FunctionsTest.java#L398](https://github.com/jenkinsci/jenkins/blob/6d179998e18adfbaa4e443c7e837135bf36c53d7/core/src/test/java/hudson/FunctionsTest.java#L398)

Added test for new functionality

**Comment by NotMyFault** [comment]
/label ready-for-merge

---

This PR is now ready for merge. We will merge it after ~24 hours if there is no negative feedback.
Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process.
Thanks!

**Comment by timja** [comment]
(labelling with other text is currently broken, it will work on it's own)

**Review by basil — APPROVED** [review]

**Pull request merged**
