### PR TITLE
[JENKINS-69517] Make 'focus-visible' frame less excessive

### PR DESCRIPTION
**Pull request by NotMyFault**
See [JENKINS-69517](https://issues.jenkins.io/browse/JENKINS-69517).

### Testing done

I launched up a Jenkins instance to provide the screenshots below and noticed no visible regressions in relation to focus-states.

**Before**:

Screenshot 2022-11-09 at 11 11 45

**After**:

Screenshot 2022-11-09 at 11 11 34

### Proposed changelog entries

- Reduce size of the focus state (regression from 2.366).

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7346"></a>

### CODE REVIEW

**Comment by timja** [comment]
Still doesn't look like what I would expect.

something like the regular focus state on buttons:

image

**Comment by NotMyFault** [comment]
> something like the regular focus state on buttons:

I wouldn't consider that as regular state, it's only present on YUI buttons. All `jenkins-button`s use this focus frame:

Screenshot 2022-11-09 at 11 45 45

**Comment by janfaracik** [comment]
The fields/buttons should only use that heavy focus state when navigating via keyboard, otherwise it's a fairly lightweight focus state like so:

image

The reason the keyboard focus is so heavy is solely to draw attention to it - happy for that to be changed though if it's causing issues.

**Comment by NotMyFault** [comment]
> when navigating via keyboard

Yeah, that's what the PR addresses and issue mentions, I didn't touch the active/hover state.

> happy for that to be changed though if it's causing issues.

Just made it a _little_ thinner, but still heavily enough imo.

**Review by timja — APPROVED** [review]
thanks!

**Review by janfaracik — APPROVED** [review]

**Comment by NotMyFault** [comment]
/label ready-for-merge

---

This PR is now ready for merge. We will merge it after ~24 hours if there is no negative feedback.
Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process.
Thanks!

**Pull request merged**
