### PR TITLE
[JENKINS-55070] Correction of the symptom, not the root cause

### PR DESCRIPTION
**Pull request by Wadeck**
Please note this will correct the symptom only. Why that happened is another story. Normally at that point the instance should be non-null.

See [JENKINS-55070](https://issues.jenkins-ci.org/browse/JENKINS-55070).

### Proposed changelog entries

* Correction of the rare `java.lang.NullPointerException` exception on startup

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [n/a] Appropriate autotests or explanation to why this change has no tests
- [n/a] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@oleg-nenashev @daniel-beck

### CODE REVIEW

**Review by daniel-beck — APPROVED** [review]

**Review by jvz — APPROVED** [review]

**Comment by Wadeck** [comment]
This PR is not meant to be merged if it is not proven that this is the cause.

**Review by jeffret-b — COMMENTED** [review]
It is questionable whether this fix changes anything significantly regarding the referenced issue. If so it doesn't seem to help or clarify anything. I agree that further evaluation is needed before proceeding.

**Review by oleg-nenashev — APPROVED** [review]
Same as in #3806 , I second what @jeffret-b says. Let's create separate tickets so that we do not confuse users and backport symptom fixes properly

**Comment by oleg-nenashev** [comment]
On hold according to the conversation with @Wadeck

**Pull request closed without merging**
