### PR TITLE
Simplify Jenkins.installState serial form to avoid relying on readResolve

### PR DESCRIPTION
**Pull request by jglick**
Follows up #3325. After that was merged I had on occasion noticed warnings from `readResolve` that `valueOf` failed to find a state by name, which I am presuming was caused by the extension list not being ready at the time of deserialization. I am not sure how to reproduce those problems, but switching the serialized field to a plain `String` and then looking up the live `InstallState` object lazily once the system is in a readier state seems safer, and also simplifies the `$JENKINS_HOME/config.xml` form to just, e.g.,

```xml
<installStateName>RUNNING</installStateName>
```

Proposed changelog entry: further simplify storage of the Jenkins setup wizard’s installation state.

@jenkinsci/code-reviewers

### CODE REVIEW

**Comment by Vlatombe** [comment]
Will break the proprietary [RegistrationState](https://github.com/cloudbees/cloudbees-license-plugin/blob/master/src/main/java/hudson/license/RegistrationState.java).

**Comment by jglick** [comment]
@Vlatombe IIUC there is a subclass overriding `readResolve` and including state. It should not be doing so—install states are intended to be singletons, as documented in the super `readResolve`. Instead, if there is any interesting state, this may be kept in a separate `GlobalConfiguration`.

**Review by Vlatombe — APPROVED** [review]
lgtm

**Review by Vlatombe — APPROVED** [review]
lgtm

**Pull request merged**
