### PR TITLE
[JENKINS-60822] - Fix localized versions to no longer report argument parsing errors: changelog.url (regression in 2.214)

### PR DESCRIPTION
**Pull request by jonbrohauge**
See [JENKINS-60822](https://issues.jenkins-ci.org/browse/JENKINS-60822).

### Proposed changelog entries

* Fix localized versions to no longer report `can't parse argument number: changelog.url` (regression in 2.214)

### Submitter checklist

- [X] JIRA issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [X] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

The JIRA issue describes how to get resolved.
Did not add tests, as this is a change to update language specific message.properties to match the default message.properties

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [x] There are at least 2 approvals for the pull request and no outstanding requests for change
- [x] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [x] Proper changelog labels are set so that the changelog can be generated automatically
- [x] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [x] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

### CODE REVIEW

**Review by jglick — APPROVED** [review]
Amends #4412.

**Comment by jglick** [comment]
Reproduced and verified in a backdated (`2.215-SNAPSHOT`) development build using

```bash
curl -u admin:$(cat $JENKINS_HOME/secrets/initialAdminPassword) -H 'Accept-Language: cs' http://localhost:8080/manage
```

Before:

```html
org.apache.commons.jelly.JellyTagException: jar:file:…/war/WEB-INF/lib/jenkins-core-2.215-SNAPSHOT.jar!/hudson/model/UpdateCenter/CoreUpdateMonitor/message.jelly:53:20: &lt;j:otherwise> can't parse argument number: changelog.url
```

After:

```html
Nová verze Jenkins-u (2.215) je k dispozici <a href="http://updates.jenkins-ci.org/download/war/2.215/jenkins.war">ke stažení</a> (<a href="https://jenkins.io/changelog">changelog</a>).
```

**Review by MarkEWaite — APPROVED** [review]

**Comment by MarkEWaite** [comment]
I will this tomorrow unless objections are raised.

**Review by oleg-nenashev — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Thanks @jonbrohauge !

**Pull request merged**
