### PR TITLE
Add a default implementation for SecurityListener

### PR DESCRIPTION
**Pull request by Wadeck**
Proposition to add a default implementation on the SecurityListener class that is currently abstract by simply removing the abstract modifiers on the methods.
Two other possibilities could have been chosen:
1) using an interface instead of an abstract class, but this implies two things, first we cannot have private static method (the all() method) but it's not really important since other extensions have set their own "all" to public ; the second is that the binary compatibility could be broken due to the change from class to interface.
2) adding a layer like that was done for Swing, you have the simili interface SecurityListener that stays abstract with abstract method and a new abstract class that implements (empty body) each mandatory methods to let them becomes optional.

Could simplify a bit the [#3074](https://github.com/jenkinsci/jenkins/pull/3074) like proposed on [this comment](https://github.com/jenkinsci/jenkins/pull/3074/files/b2c068e1d77eb49da1850d019d12dd8559db187b#r144217367)

No tests added since it's a modification that do not change behaviors, existing tests suffice to check non-regression.

### Submitter checklist
- [x] Appropriate autotests or explanation to why this change has no tests

### Desired reviewers

@reviewbybees

### CODE REVIEW

**Review by oleg-nenashev — COMMENTED** [review]
Looks reasonable to me. Even in the core there are examples where the calls are being implemented just to ignore them: https://github.com/jenkinsci/jenkins/blob/08def67a18eee51de9f3f99bc2a792fee1c160e0/core/src/main/java/jenkins/security/LastGrantedAuthoritiesProperty.java#L92-L150 . It would be great to validate and cleanup such code as a part of the pull request.

**Comment by Wadeck** [comment]
I also modify the inner class like requested @oleg-nenashev, just letting in place the empty method full of comment.

**Review by oleg-nenashev — APPROVED** [review]
🐝

**Review by daniel-beck — APPROVED** [review]

**Review by jglick — APPROVED** [review]
Yep, follows our usual policy for listeners.

_Newly written_ listeners can be `interface`s, since in Java 8 these can have `default` and `static` methods.

**Comment by oleg-nenashev** [comment]
@Wadeck thanks!

**Pull request merged**
