### PR TITLE
Bump Mina to 2.12.1 in the CLI

### PR DESCRIPTION
**Pull request by daniel-beck**
Upstream release notes: https://github.com/apache/mina-sshd/releases

Explanation why this is filed manually: https://github.com/jenkins-infra/helpdesk/issues/3919#issuecomment-2023726186

### Testing done

None, pretend I am Dependabot (just without as many links).

### Proposed changelog entries

- Update Apache Mina in the CLI from 2.11.0 to 2.12.1.

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Review by yaroslavafenkin — COMMENTED** [review]
Do we care about these?
https://github.com/jenkinsci/jenkins/blob/9970349ab1a70ace79abce0f76d3cbe9034aeaf9/war/pom.xml#L522-L535

**Comment by MarkEWaite** [comment]
The API plugin has been released with 2.12.1.  Pull request:

* https://github.com/jenkinsci/mina-sshd-api-plugin/pull/92

[API release 2.12.1-101.v85b_e08b_780dd](https://github.com/jenkinsci/mina-sshd-api-plugin/releases/tag/2.12.1-101.v85b_e08b_780dd)

**Comment by daniel-beck** [comment]
> Do we care about these?

These are bundled as a dependency of the split `sshd` plugin. It's fairly rare for these bundled plugins to be used, most scenarios install whatever is latest from update sites. So we do care, just not as much. Plus, Dependabot knows how to update these.

**Comment by MarkEWaite** [comment]
Tested by building Jenkins core with pull requests #9093, #9097. and #9089 then removed the `Ignore` annotation from `LoadDetachedPluginsTest.noUpdateSiteWarnings()` and ran that test with:

```
mvn clean verify -Dtest=jenkins.install.LoadDetachedPluginsTest,jenkins.model.StartupTest
```

Tested by including Apache Mina sshd common 2.12.1-101.v85b_e08b_780dd and Apache Mina sshd core 2.12.1-101.v85b_e08b_780dd releases in the [plugins.txt file](https://github.com/MarkEWaite/docker-lfs/blob/f8fa10fce9a654df313572c69ecd6be0a1172cf7/plugins.txt#L99) of my Jenkins controller and running that controller with agents connected through ssh to Debian 10, Debian 11, Debian 12, Debian testing, Debian unstable, FreeBSD 13.1, Red Hat Enterprise Linux 8, Rocky Linux 9, Ubuntu 20.04, Ubuntu 22.04, and Windows 11, 

Tested by running Jenkins with those pull requests and connecting to the command line interface with an RSA ssh private key with the ssh server plugin.  After registering my RSA public key with my account on the Jenkins controller, I was able to perform a `quiet-down` command over ssh with the command:

```
ssh -i ~/.ssh/id_rsa -p 44022 test-host quiet-down
```

**Review by MarkEWaite — APPROVED** [review]
Thanks!

**Pull request merged**
