### PR TITLE
[JENKINS-27845] use latest Ant version in core

### PR DESCRIPTION
**Pull request by ndeloof**

### CODE REVIEW

**Comment by ndeloof** [comment]
@reviewbybees

**Comment by KostyaSha** [comment]
:-1: Such change already contains in #1670 that is blocked by @oleg-nenashev

**Comment by KostyaSha** [comment]
Please make ant update in separate commit

**Comment by ndeloof** [comment]
@KostyaSha what do you mean by "separate commit" ? This PR only contain ant version upgrade + required code change (due to jenkins badly hacking internal structure)

**Comment by ndeloof** [comment]
Change proposed on #1670 is to rely on commons-compress and change `readFromTar` implementation, while this one is _only_ about updating ant dependency, which actually did include commons-compress Tar code, so is eventually a very comparable change, but with less visible impact on jenkins codebase.

**Comment by KostyaSha** [comment]
This PR broke more difficult PR #1670, just because @oleg-nenashev can't end some his tests. So -1 until biggest PR will be merged. If you want just update ant dep, then i'm ok and remove tar changes.

**Comment by oleg-nenashev** [comment]
I think we should go forward and merge #1670

**Comment by oleg-nenashev** [comment]
#1670 has been merged. Closing this PR

**Comment by KostyaSha** [comment]
@oleg-nenashev #1670 has no ant dep update

**Comment by oleg-nenashev** [comment]
Sorry, my bad. BTW the PR should be remerged

**Comment by KostyaSha** [comment]
And we back to what i firstly said:

> Please make ant update in separate commit

**Comment by oleg-nenashev** [comment]
The issue is still actual

**Comment by daniel-beck** [comment]
@ndeloof Do you plan to finish this?

**Comment by oleg-nenashev** [comment]
I'd guess no
@ndeloof please feel free to reopen it if you want to finish it

**Pull request closed without merging**
