### PR TITLE
Remove sites.jelly (dead code)

### PR DESCRIPTION
**Pull request by timja**
The page appears to have been added in 2009 but the only link to it was commented out from the beginning https://github.com/jenkinsci/jenkins/commit/720be7d7a12facd3543c0ffa2d2757ef76b9c06a#diff-7f2984f6889d7bdb822d04143bfa6d90R33

### Proposed changelog entries

* N/A internal
* ...

### Submitter checklist

- [na] JIRA issue is well described
- [na] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [na] Appropriate autotests or explanation to why this change has no tests
- [na] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@daniel-beck (mentioned this was unused as part of https://github.com/jenkinsci/jenkins/pull/4149#discussion_r316210420)

@jenkinsci/core-pr-reviewers

### CODE REVIEW

**Review by halkeye — APPROVED** [review]
I just tested it locally, the page is empty anyways, not just hidden 👍

**Review by res0nance — APPROVED** [review]

**Review by oleg-nenashev — COMMENTED** [review]
Would it make sense to recover it instead? It looks to be helpful for some cases when there are multiple sources configured via external plugins of config-as-code?

**Review by oleg-nenashev — APPROVED** [review]
Approving it based on testing by @halkeye 

> I just tested it locally, the page is empty anyways, not just hidden 


CC @ikedam who might have an opinion based on https://plugins.jenkins.io/update-sites-manager

**Comment by ikedam** [comment]
No problem to remove that. Anyway, it doesn’t show anything as pointed, and the expected feature is provided (and extended) by update-sites-manager.

**Pull request merged**
