### PR TITLE
Update commons-beanutils to latest version

### PR DESCRIPTION
**Pull request by jvz**
[Release notes](https://commons.apache.org/proper/commons-beanutils/javadocs/v1.9.3/RELEASE-NOTES.txt). Note that one big change from 1.8 to 1.9 is that they added (backward compatible) generic signatures to the API (about time!). While this is unlikely to cause any issues, this does require a passing CI build first.

### Proposed changelog entries

* Internal: Update commons-beanutils to 1.9.3

### Submitter checklist

- ~~[ ] JIRA issue is well described~~
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@reviewbybees @madchap @batmat @varyvol

### CODE REVIEW

**Review by varyvol — APPROVED** [review]

**Comment by batmat** [comment]
@jvz given how Jenkins core dependencies are usable and used in plugins, can you please assess the compatibility in a few key plugins that would be known to use commons-beanutils, by using either a timestamped SNAPSHOT for the Core, or Incrementals (though then I think consumers would require to be Incrementalified).

**Review by batmat — CHANGES_REQUESTED** [review]
clarifying that my last comment is actually a "change request", because I'd like to see 2 or 3 downstream PRs on key plugins showing this won't obviously break them.

**Comment by jvz** [comment]
Yeah, I can make some incrementals PRs to check it out. I'll link to them here.

**Comment by jvz** [comment]
I took some of the most installed plugins and ran their builds and tests with my changes:

* credentials
* ssh-credentials
* junit
* ldap

**Comment by batmat** [comment]
You mean you ran them locally? If so I would expect more like a linked PR on the said plugins.

**Comment by jvz** [comment]
> You mean you ran them locally? If so I would expect more like a linked PR on the said plugins.

Yes. I could try to track down which plugins are directly using it and do manual upgrades there first if that's what you're suggesting.

**Comment by jvz** [comment]
Linked are several PRs I opened to show CI passing for plugins that directly use beanutils in some way that are also still being developed.

**Comment by batmat** [comment]
This is not exactly what I was asking for, but I think this will do for this case. I was asking to file such PRs, but with a bump to the current Incremental version of the Core for this PR.

(Need to write up an explanation somewhere about "downstream PRs" on the Jenkinsci org.)

**Review by batmat — APPROVED** [review]

**Comment by jvz** [comment]
Ah, ok. I was thinking of doing that at first, but the incrementals release didn't make it due to being out of date with master at the time.

**Comment by batmat** [comment]
Yeah, but then you could just have deployed a SNAPSHOT of the Core using like `mvn clean deploy -DskipTests`, then use the timestamped version for downstream PRs.
*Any* Jenkins developer can deploy _any_ plugin or resources as SNAPSHOT.

**Comment by jvz** [comment]
Ah, I forgot about deploying snapshots since I tend to avoid using them for repeatable builds.

**Review by fcojfernandez — APPROVED** [review]

**Review by Wadeck — APPROVED** [review]
:bee:

**Comment by batmat** [comment]
I believe enough downstream testing assessment here has been done, though I'm still not 100% comfortable with going with this. I'm going to wait for another review or two from core maintainers, and I think we should be good to go.

**Comment by jglick** [comment]
There is a filed RFE to make downstream builds automatically wait for an upstream incremental deployment.

**Review by jglick — APPROVED** [review]
What could possibly go wrong?

**Review by daniel-beck — APPROVED** [review]
````
$ java -jar japicmp-0.13.1-jar-with-dependencies.jar --old commons-beanutils-1.8.3.jar --new commons-beanutils-1.9.3.jar --ignore-missing-classes --only-incompatible
Comparing binary compatibility of /Users/danielbeck/Downloads/commons-beanutils-1.9.3.jar against /Users/danielbeck/Downloads/commons-beanutils-1.8.3.jar
WARNING: You are using the option '--ignore-missing-classes', i.e. superclasses and interfaces that could not be found on the classpath are ignored. Hence changes caused by these superclasses and interfaces are not reflected in the output.
===  UNCHANGED CLASS: PUBLIC org.apache.commons.beanutils.BasicDynaBean  (default serialVersionUID changed)
	***! CLASS FILE FORMAT VERSION: 50.0 <- 47.0
===  UNCHANGED CLASS: PUBLIC org.apache.commons.beanutils.BasicDynaClass  (default serialVersionUID changed)
	***! CLASS FILE FORMAT VERSION: 50.0 <- 47.0
===  UNCHANGED CLASS: PUBLIC org.apache.commons.beanutils.BeanComparator  (default serialVersionUID changed)
	***! CLASS FILE FORMAT VERSION: 50.0 <- 47.0
===  UNCHANGED CLASS: PUBLIC org.apache.commons.beanutils.DynaProperty  (default serialVersionUID changed)
	***! CLASS FILE FORMAT VERSION: 50.0 <- 47.0
===  UNCHANGED CLASS: PUBLIC org.apache.commons.beanutils.LazyDynaBean  (default serialVersionUID changed)
	***! CLASS FILE FORMAT VERSION: 50.0 <- 47.0
===  UNCHANGED CLASS: PUBLIC org.apache.commons.beanutils.LazyDynaClass  (default serialVersionUID changed)
	***! CLASS FILE FORMAT VERSION: 50.0 <- 47.0
===  UNCHANGED CLASS: PUBLIC org.apache.commons.beanutils.LazyDynaList  (default serialVersionUID changed)
	***! CLASS FILE FORMAT VERSION: 50.0 <- 47.0
***  MODIFIED CLASS: PUBLIC org.apache.commons.beanutils.ResultSetDynaClass  (default serialVersionUID changed)
	***! CLASS FILE FORMAT VERSION: 50.0 <- 47.0
***  MODIFIED CLASS: PUBLIC org.apache.commons.beanutils.RowSetDynaClass  (default serialVersionUID changed)
	***! CLASS FILE FORMAT VERSION: 50.0 <- 47.0
***  MODIFIED CLASS: PUBLIC org.apache.commons.beanutils.WrapDynaBean  (default serialVersionUID changed)
	***! CLASS FILE FORMAT VERSION: 50.0 <- 47.0
---! REMOVED CLASS: PUBLIC(-) org.apache.commons.collections.ArrayStack  (class removed)
	---  CLASS FILE FORMAT VERSION: n.a. <- 47.0
	---! REMOVED INTERFACE: java.util.RandomAccess
	---! REMOVED INTERFACE: java.util.List
	---! REMOVED INTERFACE: java.lang.Cloneable
	---! REMOVED INTERFACE: java.util.Collection
	---! REMOVED INTERFACE: org.apache.commons.collections.Buffer
	---! REMOVED INTERFACE: java.lang.Iterable
	---! REMOVED INTERFACE: java.io.Serializable
	---! REMOVED CONSTRUCTOR: PUBLIC(-) ArrayStack()
	---! REMOVED CONSTRUCTOR: PUBLIC(-) ArrayStack(int)
	---! REMOVED METHOD: PUBLIC(-) boolean empty()
	---! REMOVED METHOD: PUBLIC(-) java.lang.Object peek()
		---  REMOVED EXCEPTION: java.util.EmptyStackException
	---! REMOVED METHOD: PUBLIC(-) java.lang.Object peek(int)
		---  REMOVED EXCEPTION: java.util.EmptyStackException
	---! REMOVED METHOD: PUBLIC(-) java.lang.Object pop()
		---  REMOVED EXCEPTION: java.util.EmptyStackException
	---! REMOVED METHOD: PUBLIC(-) java.lang.Object push(java.lang.Object)
	---! REMOVED METHOD: PUBLIC(-) int search(java.lang.Object)
---! REMOVED INTERFACE: PUBLIC(-) ABSTRACT(-) org.apache.commons.collections.Buffer  (not serializable)
	---  CLASS FILE FORMAT VERSION: n.a. <- 47.0
	---! REMOVED INTERFACE: java.util.Collection
	---! REMOVED INTERFACE: java.lang.Iterable
	---! REMOVED METHOD: PUBLIC(-) ABSTRACT(-) java.lang.Object get()
	---! REMOVED METHOD: PUBLIC(-) ABSTRACT(-) java.lang.Object remove()
---! REMOVED CLASS: PUBLIC(-) org.apache.commons.collections.BufferUnderflowException  (class removed)
	---  CLASS FILE FORMAT VERSION: n.a. <- 47.0
	---! REMOVED INTERFACE: java.io.Serializable
	---! REMOVED CONSTRUCTOR: PUBLIC(-) BufferUnderflowException()
	---! REMOVED CONSTRUCTOR: PUBLIC(-) BufferUnderflowException(java.lang.String)
	---! REMOVED CONSTRUCTOR: PUBLIC(-) BufferUnderflowException(java.lang.String, java.lang.Throwable)
	---! REMOVED METHOD: PUBLIC(-) FINAL(-) java.lang.Throwable getCause()
---! REMOVED CLASS: PUBLIC(-) org.apache.commons.collections.FastHashMap  (class removed)
	---  CLASS FILE FORMAT VERSION: n.a. <- 47.0
	---! REMOVED INTERFACE: java.lang.Cloneable
	---! REMOVED INTERFACE: java.util.Map
	---! REMOVED INTERFACE: java.io.Serializable
	---! REMOVED FIELD: PROTECTED(-) boolean fast
	---! REMOVED FIELD: PROTECTED(-) java.util.HashMap map
	---! REMOVED CONSTRUCTOR: PUBLIC(-) FastHashMap(java.util.Map)
	---! REMOVED CONSTRUCTOR: PUBLIC(-) FastHashMap(int, float)
	---! REMOVED CONSTRUCTOR: PUBLIC(-) FastHashMap(int)
	---! REMOVED CONSTRUCTOR: PUBLIC(-) FastHashMap()
	---! REMOVED METHOD: PUBLIC(-) void clear()
	---! REMOVED METHOD: PUBLIC(-) java.lang.Object clone()
	---! REMOVED METHOD: PUBLIC(-) boolean containsKey(java.lang.Object)
	---! REMOVED METHOD: PUBLIC(-) boolean containsValue(java.lang.Object)
	---! REMOVED METHOD: PUBLIC(-) java.util.Set entrySet()
	---! REMOVED METHOD: PUBLIC(-) boolean equals(java.lang.Object)
	---! REMOVED METHOD: PUBLIC(-) java.lang.Object get(java.lang.Object)
	---! REMOVED METHOD: PUBLIC(-) boolean getFast()
	---! REMOVED METHOD: PUBLIC(-) int hashCode()
	---! REMOVED METHOD: PUBLIC(-) boolean isEmpty()
	---! REMOVED METHOD: PUBLIC(-) java.util.Set keySet()
	---! REMOVED METHOD: PUBLIC(-) java.lang.Object put(java.lang.Object, java.lang.Object)
	---! REMOVED METHOD: PUBLIC(-) void putAll(java.util.Map)
	---! REMOVED METHOD: PUBLIC(-) java.lang.Object remove(java.lang.Object)
	---! REMOVED METHOD: PUBLIC(-) void setFast(boolean)
	---! REMOVED METHOD: PUBLIC(-) int size()
	---! REMOVED METHOD: PUBLIC(-) java.util.Collection values()
````

**Comment by batmat** [comment]
So this is ready for merge. Let's merge this later today or tomorrow if nobody objects in the meantime.

Thank you everyone for the eyes!

**Comment by Wadeck** [comment]
The message from Daniel does indicate some breaking change :| After a quick search, it seems the removed classes are not used in the ecosystem.

**Comment by daniel-beck** [comment]
@Wadeck 

> The message from Daniel does indicate some breaking change

Read the changelog, you must:

> Older versions of BeanUtils contained some classes that were copied from Commons Collections. These classes have now been removed, and a dependency to Commons Collections has been added; the collections jar now has to be contained in the classpath, too.

**Comment by jvz** [comment]
Now I'm not super involved at Apache Commons, but that project specifically takes backward compatibility extremely seriously. Any removed APIs causes a major version number bump.

**Comment by casz** [comment]
Love how this minor version bump has a breaking change. The `Converter` no longer accepts lambda:
```
Stapler.CONVERT_UTILS.register((type, value) -> Version.of(value.toString()), Version.class);
```

```
Stapler.CONVERT_UTILS.register(new Converter() {
            @Override
            public <T> T convert(Class<T> type, Object value) {
                return (T) Version.of(value.toString());
            }
        }, Version.class);
```

**Comment by casz** [comment]
Where to report this, and how do we get this fixed before next LTS?

**Comment by batmat** [comment]
@casz please file an issue in the Jenkins tracker first, given this is an issue for our ecosystem.
I believe we want to backport a revert. 

Can you possibly look for other cases where this method would be called? Thanks

(https://issues.jenkins-ci.org/browse/INFRA-2110 would help for precise method calls, but it would be hard to detect everything **before** we know something is breaking).

**Comment by jvz** [comment]
This sounds like it should also be reported as an API breakage at https://issues.apache.org/jira/browse/BEANUTILS

**Comment by casz** [comment]
The damage is done, I'll write code that handles both cases :cry:

**Comment by casz** [comment]
Reported as: https://issues.apache.org/jira/browse/BEANUTILS-521

**Comment by casz** [comment]
Fixed in: https://github.com/jenkinsci/configuration-as-code-plugin/pull/889

**Pull request merged**
