### PR TITLE
Remove KXML2 library

### PR DESCRIPTION
**Pull request by basil**
This PR removes the following JAR from the WAR:

- `kxml2-2.3.0.jar`

Core stopped depending on it in #7778. In that PR, I wrote:

> I am not yet removing the `kxml2` JAR file from the Jenkins WAR in this PR because I have not done the research to determine whether doing so would affect any plugins. If, once this change has been tested in several weekly releases and proven to be stable, there is a desire to remove this no-longer-needed JAR file, the removal can be explored at that time.

The above change has been shipping for a while now and we have not had a need to return to using KXML2 in core, so I am proceeding with the removal of this library from core. As you will see below, nothing of any relevance in the ecosystem is still using this functionality, and any stragglers are better off carrying this component themselves rather than relying on core for it.

I scanned the update centers for Jenkins and CloudBees and while I found some stuff using XPP3, I found nothing directly using KXML2.

### Testing done

The PR build and update center scan should be sufficient. I also did a BOM run with this PR with no issues.

### Proposed changelog entries

- Stop shipping `net.sf.kxml:kxml2` because Jenkins no longer depends on it.

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/8503"></a>

### CODE REVIEW

**Comment by basil** [comment]
This change seems to break `new XStream()`, which uses the default driver (still XML Pull Parser v3), but not `new XStream2()`, which uses the StaX driver. In most cases we're already using (or should be using) `new XStream2()`, but there are still a handful of cases (mostly in tests) where we still need to use `new XStream()`. To get those uses to work with the removal of all three JARs mentioned above, they need to be changed to `new XStream(XStream2.getDefaultDriver())`. I'll explore how much work is needed to adapt the ecosystem to this change, and either do that work or reduce this scope of this PR by retaining at least one of the three JARs.

**Comment by basil** [comment]
While attempting to remove all three libraries (kxml2-2.3.0.jar, mxparser-1.2.2.jar, and xpp3-1.1.4c.jar) did lead me to file a few clean up PRs in various repository to make plugin code more consistent with core (which was a nice benefit), I ended up giving up on removing `mxparser` after finding that it broke `new XStream()`, which would break third-party library code that happens to use XStream (independent of Jenkins plugins or Jenkins core itself) and I ended up giving up on removing `xpp3` after finding some proprietary plugins that directly imported `XppDriver`. So the scope of this PR is now just removing `kxml2` which should be completely safe to do today. Therefore I am removing the `on-hold` label.

**Comment by amuniz** [comment]
> ended up giving up on removing xpp3 after finding some proprietary plugins that directly imported XppDriver

I think its usage in that particular propritary plugin (`operations-center-context`) can be just removed (as long as there is an `XStream` constructor not requiring an instance of it).

**Comment by basil** [comment]
> I think its usage in that particular proprietary plugin […] can be just removed

I am sure that it can be. But the fact that it has not been is the reason that I have given up on this removal and reduced the scope of this PR.

**Review by NotMyFault — APPROVED** [review]

**Review by res0nance — APPROVED** [review]

**Comment by NotMyFault** [comment]
/label ready-for-merge

---

This PR is now ready for merge. We will merge it after ~24 hours if there is no negative feedback.
Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process.
Thanks!

**Pull request merged**
