### PR TITLE
[JENKINS-36387] Catch exception when scm retry count field is empty.

### PR DESCRIPTION
**Pull request by godfath3r**
Related to JENKINS-36387

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
retriggering after https://github.com/jenkinsci/jenkins/pull/2435

**Comment by oleg-nenashev** [comment]
Infra issue. retriggering again

**Comment by oleg-nenashev** [comment]
👍

**Comment by oleg-nenashev** [comment]
The test causes compilation failure :(

> /scratch/jenkins/workspace/core/jenkins-core/core/src/test/java/jenkins/model/GlobalSCMRetryCountConfigurationTest.java:[34,28] error: cannot find symbol

**Comment by godfath3r** [comment]
Retriggering tests, as all are passed locally.

**Comment by oleg-nenashev** [comment]
I do not feel the test really validates the change. JSONException is being caused by the access to the non-existent field in json.getInt(0) accordig to http://json-lib.sourceforge.net/apidocs/jdk15/net/sf/json/JSONObject.html#getInt(java.lang.String).

I would recommend to retrieve the configuration instance from Jenkins and to explicitly call configure() with empty <code>json</code> parameter

**Comment by godfath3r** [comment]
@oleg-nenashev Don't you think this test case is enough? Please comment if there is anything more to add in this PR.

**Comment by oleg-nenashev** [comment]
LGTM (excepting particular possible improvements we've discussed in IRC)

**Pull request merged**
