### PR TITLE
[JENKINS-71937] Fix deprecated `Slave` constructor

### PR DESCRIPTION
**Pull request by Vlatombe**
Got broken in https://github.com/jenkinsci/jenkins/pull/8395

See [JENKINS-71937](https://issues.jenkins.io/browse/JENKINS-71937).

### Testing done
Issue reporter has [confirmed](https://github.com/jenkinsci/jenkins/pull/8564#issuecomment-1747720859) that this fixes the issue that was experienced since Jenkins 2.421.

### Proposed changelog entries

- Fix agent allocation due to label issue detected by vSphere Cloud plugin (regression in 2.421).

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [X] The Jira issue, if it exists, is well-described.
- [X] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Review by jglick — APPROVED** [review]

**Review by MarkEWaite — APPROVED** [review]

**Comment by MarkEWaite** [comment]
This PR is now ready for merge.  We will merge it after approximately 24 hours if there is no negative feedback.

/label ready-for-merge

**Comment by basil** [comment]
Incremental build 2.427-rc34267.67cf93d3772c is available for testing. The incremental build is available from: https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/main/jenkins-war/2.427-rc34267.67cf93d3772c/

@quacktacular Can you please test the incremental build and confirm the issue is resolved?

**Comment by quacktacular** [comment]
@basil yes I'll take look shortly

**Review by NotMyFault — APPROVED** [review]

**Comment by quacktacular** [comment]
Looks good on my test env!

**Review by basil — APPROVED** [review]
The **Testing Done** section of the PR is blank, but a user has confirmed this PR resolves the issue.

**Comment by bboehmke** [comment]
This also fixes the issue in my test environment!

**Pull request merged**
