### PR TITLE
Remove unused material-icons

### PR DESCRIPTION
**Pull request by NotMyFault**
The change proposed removes the unused material-icons in favor of our standard ionicons used. There is no plugin with functional code left relying on the material-icons: https://github.com/search?q=org%3Ajenkinsci+NOT+repo%3Ajenkinsci%2Fjenkins+%22%2Fmaterial-icons%2F%22&type=code

### Testing done

Jenkins and plugins function as-is, given the icons are unused.

### Proposed changelog entries

- Remove unused material icons.

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Review by timja — DISMISSED** [review]

**Comment by daniel-beck** [comment]
> in core

It's not in core though, it's a test? Doesn't this just reduce test coverage for something that still exists?

**Comment by NotMyFault** [comment]
> Are there no plugins using these icons?

The test case operates independently of the icon you reference. `l:svgIcon` is not reserved for material icons only, you can load any SVG you like, which is valid and intended.
The change proposed just changes which icon is used in the test, moving to our standard icon set, but that has no impact on coverage, given the `l:svgIcon` is still the same as before, just with a different symbol now.

**Review by timja — APPROVED** [review]

**Comment by MarkEWaite** [comment]
I see references to material-icons in the [blue ocean plugin repository](https://github.com/search?q=repo%3Ajenkinsci%2Fblueocean-plugin%20material-icons&type=code), but I'm not confident those are references to icons provided by core.  Most of the references in that plugin seem to be to "blueocean-material-icons".

**Comment by NotMyFault** [comment]
> I see references to material-icons in the [blue ocean plugin repository](https://github.com/search?q=repo%3Ajenkinsci%2Fblueocean-plugin%20material-icons&type=code), but I'm not confident those are references to icons provided by core. Most of the references in that plugin seem to be to "blueocean-material-icons".

Indeed, they aren't shipped or referenced from core. BlueOcean has its own submodule containing the icons it needs.

At the time the material icons were added to core, no API was added to load them dynamically as you do it with symbols (`<l:icon src="symbol-symbolName-outline plugin-ionicons-api" />` e.g.), but load them from a static path.
Plugins shipping their own icon set of material icons are unaffected by this change.

**Pull request merged**
