### PR TITLE
BulkChange auto-close

### PR DESCRIPTION
**Pull request by kohsuke**
Code simplification.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
I'm not sure that it's a good approach to perform BulkChange commits on exceptions. But it's not related to the change since it's just a refactoring.

👍

**Comment by KostyaSha** [comment]
>Code simplification.

### BEFORE
https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/BulkChange.java#L89-L99

```

    /**
     * Saves the accumulated changes.
     */
    public void commit() throws IOException {
        if(completed)   return;
        completed = true;

        // move this object out of the scope first before save, or otherwise the save() method will do nothing.
        pop();
        saveable.save();
    }
```

### Now
```
    /**
     * Saves the accumulated changes.
     */
    public void commit() throws IOException {
        if(completed)   return;
        completed = true;

        // move this object out of the scope first before save, or otherwise the save() method will do nothing.
        pop();
        saveable.save();
    }
```

NOW

https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/BulkChange.java#L109-L124

```
    /**
     * Exits the scope of {@link BulkChange} without saving the changes.
     *
     * <p>
     * This can be used when a bulk change fails in the middle.
     * Note that unlike a real transaction, this will not roll back the state of the object.
     *
     * <p>
     * The abort method can be called after the commit method, in which case this method does nothing.
     * This is so that {@link BulkChange} can be used naturally in the try/finally block.
     */
    public void abort() {
        if(completed)   return;
        completed = true;
        pop();
    }
```

**Comment by KostyaSha** [comment]
@kohsuke could you not push your single user branches into upstream and clean-up tones of staled branches?

**Comment by oleg-nenashev** [comment]
Yes, in this case @KostyaSha is right. Thanks for catching!

**Comment by kohsuke** [comment]
Corrected

**Comment by KostyaSha** [comment]
And now if error will happen before commit changes will be lost, because commit was in finally before. 
👎

**Comment by KostyaSha** [comment]
@reviewbybees !

**Comment by KostyaSha** [comment]
@stephenc @jtnord

**Comment by oleg-nenashev** [comment]
So it needs fix...

**Comment by KostyaSha** [comment]
No replies -> close

**Comment by oleg-nenashev** [comment]
@KostyaSha proposed to close this PR. Since there is no response from @kohsuke , it's reasonable

**Pull request closed without merging**
