### PR TITLE
ExtractResourceWithChangesSCM now needs to have a descriptor

### PR DESCRIPTION
**Pull request by jglick**
@reviewbybees

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Probably it makes sense to implement a fair descriptor with <code>@TestExtension</code>

**Comment by jglick** [comment]
`@TestExtension` can only be used inside a single test. You can use `@Extension` inside `src/test/java/`, but then the SCM is registered for example in the UI during `mvn hpi:run` of a plugin, which I did not want.

**Comment by olivergondza** [comment]
:+1:

**Comment by oleg-nenashev** [comment]
:+1:

**Pull request merged**
