### PR TITLE
Backporting for LTS 2.387.2

### PR DESCRIPTION
**Pull request by krisstern**
```shell
Latest core version: jenkins-2.395

Postponed
---------

JENKINS-70820           Minor                   2.396
        "New Node" button missing in Web UI
        regression
        https://issues.jenkins.io/browse/JENKINS-70820

Fixed
-----

JENKINS-70626           Minor                   2.392
        Backport bundled plugin updates to 2.387.1
        https://issues.jenkins.io/browse/JENKINS-70626

JENKINS-70599           Minor                   2.393
        installNecessaryPlugins API redirects to a non-existent page, returns 404
        regression
        https://issues.jenkins.io/browse/JENKINS-70599

JENKINS-69955           Blocker                 2.395
        WebSocketTimeoutException: Connection Idle Timeout
        https://issues.jenkins.io/browse/JENKINS-69955
```

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7759"></a>

### CODE REVIEW

**Comment by NotMyFault** [comment]
https://github.com/jenkinsci/jenkins/pull/7759/commits/e7e32e2c4ccee10d981d825f129a6c86b6a30fe3 is not yet released. 2.396 releases tomorrow.

**Comment by krisstern** [comment]
Is the timeline too tight to include https://github.com/jenkinsci/jenkins/commit/e7e32e2c4ccee10d981d825f129a6c86b6a30fe3, or should we leave the pull request as is?

**Comment by NotMyFault** [comment]
> Is the timeline too tight to include [e7e32e2](https://github.com/jenkinsci/jenkins/commit/e7e32e2c4ccee10d981d825f129a6c86b6a30fe3), or should we leave the pull request as is?

We typically backport changes from weekly releases only, to ensure changes have been tested in the field.

https://github.com/jenkinsci/jenkins/pull/7700 needs to be included too, to pass the tests.

**Comment by krisstern** [comment]
Thanks! I have undone https://github.com/jenkinsci/jenkins/commit/e7e32e2c4ccee10d981d825f129a6c86b6a30fe3 via a git rebase and have included https://github.com/jenkinsci/jenkins/commit/9d979384e757161a9c6854ef4da16938238e46e0 in this pull request to pass the checks.

**Review by NotMyFault — APPROVED** [review]

**Review by timja — APPROVED** [review]

**Pull request merged**
