### PR TITLE
[JENKINS-34065] Deleting obsolete pinning UI

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-34065](https://issues.jenkins-ci.org/browse/JENKINS-34065)

@reviewbybees

### CODE REVIEW

**Review by daniel-beck — APPROVED** [review]

**Review by recena — APPROVED** [review]

**Review by batmat — APPROVED** [review]
LGTM :+1: Played with the modified version through 
`docker run -ti -p 8080:8080 -e ID=2728 batmat/jenkins-pr-tester`
and also grepped the code for left pinning related occurrences

**Comment by rsandell** [comment]
:bee:

**Comment by jglick** [comment]
Test failures seem unrelated.

**Comment by jglick** [comment]
@reviewbybees done

**Comment by daniel-beck** [comment]
No overlap in failing tests between the two instances, so this should be fine.

**Pull request merged**
