### PR TITLE
[JENKINS-48922] - Whitelist StringBuilder and StringBuffer for serialization

### PR DESCRIPTION
**Pull request by oleg-nenashev**
It has been catched by @MarkEWaite in Grooby PostBuild Plugin, see [JENKINS-48992](https://issues.jenkins-ci.org/browse/JENKINS-48992). I think this is generally a bad idea to serialize this classes, but I see no security concerns in it.

Searches like [this](https://github.com/search?l=Java&q=org%3Ajenkinsci+%22private+StringBuilder%22&type=Code) and [this](https://github.com/search?utf8=%E2%9C%93&q=org%3Ajenkinsci+%22private+StringBuffer%22&type=Code) reveal other  potential usages, so I decided to add the classes to the global whitelist

The fix has been verified in https://github.com/jenkinsci/groovy-postbuild-plugin/pull/29

### Proposed changelog entries

* Not required

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@reviewbybees @jglick

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Test failure is related

**Review by jglick — APPROVED** [review]
Weird but harmless.

**Comment by oleg-nenashev** [comment]
On Monday I will try to go through other types in `java.lang.*` just in case we missed something being used actively (e.g. `Date` and so on)

**Comment by oleg-nenashev** [comment]
Tests passed

**Comment by vkotovv** [comment]
@oleg-nenashev I think you've linked wrong issue in your original message, right one will be https://issues.jenkins-ci.org/browse/JENKINS-48922. Just a typo.

**Comment by oleg-nenashev** [comment]
@vkotovv my bad, sorry about the inconvenience it caused

**Comment by vkotovv** [comment]
@oleg-nenashev can you edit your message at the top?

**Comment by oleg-nenashev** [comment]
Changelog has not been affected, it landed along with JEP-200 and didn't need extra entries

**Pull request merged**
