### PR TITLE
More concise welcome text for Jenkins 2

### PR DESCRIPTION
**Pull request by batmat**
As discussed in https://issues.jenkins-ci.org/browse/JENKINS-33557?focusedCommentId=251588&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-251588

ping @daniel-beck @recena @kzantow

### CODE REVIEW

**Comment by daniel-beck** [comment]
:+1:

**Comment by oleg-nenashev** [comment]
:+1:

**Comment by kzantow** [comment]
:+1:

**Comment by recena** [comment]
Betaled but :+1:

**Pull request merged**
