### PR TITLE
Update detached plugin versions after security release

### PR DESCRIPTION
**Pull request by Wadeck**
Update detached plugin versions after security release: matrix-auth and matrix-project

- JUnit and structs also due to requireUpperBoundDeps

See [advisory/2020-07-15](https://www.jenkins.io/security/advisory/2020-07-15/).

### CODE REVIEW

**Review by jvz — APPROVED** [review]

**Review by daniel-beck — APPROVED** [review]

**Review by timja — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
LGTM as code. @Wadeck please restore the pull request temlate so that changelogs could be generated normally

**Comment by oleg-nenashev** [comment]
We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Comment by timja** [comment]
FTR this has never had a green build, I triggered one earlier in case the first was a blip.

**Review by timja — CHANGES_REQUESTED** [review]
Failing tests

```
Caused by: java.io.IOException: Failed to load: Matrix Project Plugin (1.17)
 - Update required: JUnit Plugin (1.26.1) to be updated to 1.29 or higher
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:952)
	at hudson.PluginManager.dynamicLoad(PluginManager.java:932)
	... 16 more
```

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
Thanks for the fix

**Pull request merged**
