### PR TITLE
[JENKINS-56934] fix the 'new view' link to correctly work with folders

### PR DESCRIPTION
**Pull request by jtnord**
See [JENKINS-56934](https://issues.jenkins-ci.org/browse/JENKINS-56934).

the new view link was always pointing to the root newView and so could not create new views in folders.

### Proposed changelog entries

* "New View" link takes into account the current folder when creating new views

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [x] There are at least 2 approvals for the pull request and no outstanding requests for change
- [x] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [x] Proper changelog labels are set so that the changelog can be generated automatically
- [x] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [x] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by daniel-beck** [comment]
Honestly it's probably better if we just remove this, it's just been a neverending cycle of fixes causing regressions.

**Review by jtnord — COMMENTED** [review]
> It's probably better if we just remove this, it seems to be a never-ending cycle of fixes causing regressions.
> 
> How does this handle nested views?

Tell me how to create one and I will test it manually and write a unit test 🙂

**Comment by jvz** [comment]
What's a nested view? I can't include a view inside a view (or at least not via the list view mechanism).

**Comment by jtnord** [comment]
@daniel-beck are you referring to https://plugins.jenkins.io/nested-view/ ?

**Comment by daniel-beck** [comment]
> @daniel-beck are you referring to https://plugins.jenkins.io/nested-view/ ?

Yes. I remember that being more popular and more active, so perhaps not a big deal…

Also [`TreeView`s](https://www.jenkins.io/doc/book/managing/system-properties/#hudson-treeview) might be interesting to try, don't remember what their gimmick was (time to delete maybe?)

**Comment by jtnord** [comment]
`nestedView` kindof works - the plugin is broken as a `NestedView` is not a `ModifiableViewGroup` so this action will not appear (bug in nested view).
on the root page the nested view also injects its own action (which is the wrong page - it should do it when inside the nested view but it does it on the outer page - leading to 2 "New View" actions) - one to create a new view in the nested view, and one to create one in the normal view.  this is wrong as you can have 2 nested views in the the same `ViewGroup` and then all bets are off as to which action targets which (without looking maybe at the URLs).
This plugin is up for adoption and so as no PR would be merged I will decline to create a PR for it.

as for the Jenkins inbuilt `TreeView` I tested this - and you end up with 2 new Views again.  but this is experimental feature and it is buggy and does not work correctly when I tested.  it adds drop down `ModelObject` arrows that does nothing.  Not attempting to fix the experimental feature in this PR - we probably just want to delete it separately

**Review by rsandell — APPROVED** [review]

**Comment by judovana** [comment]
Hi!
I had just adopted nested view plugin, so do not expect educated conclusion. Sorry.
I personally consider nested views as a bit of useful legacy - so no pipelines, no folders... Once folders or pipelines are around.. yo are on your own.

**Review by res0nance — APPROVED** [review]
Fix looks reasonable but the test seems to fail, I think its due to the view returning a viewgroup instead of a modifiableviewgroup

**Review by oleg-nenashev — APPROVED** [review]
LGTM.

We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Pull request merged**
