### PR TITLE
Replace EOL actions/upload-release-asset with softprops/action-gh-release

### PR DESCRIPTION
**Pull request by afzal442**
Signed-off-by: afzal442 <afzal442@gmail.com>

See [JENKINS-69867](https://issues.jenkins.io/browse/JENKINS-69867) and https://github.com/jenkins-infra/helpdesk/issues/3176

### Proposed changelog entries

- Entry 1: Issue, github action release workflow
- […]

Ref: https://github.com/softprops/action-gh-release
### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.

### Desired reviewers

@NotMyFault 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7285"></a>

### CODE REVIEW

**Review by NotMyFault — COMMENTED** [review]
Hey,

thanks for the PR. A few things I'd like to highlight:
- Why was the name and id changed and removed from a few steps? Both are fine as-is and can stay.

**Comment by afzal442** [comment]
Thanks @NotMyFault for reviewing this. 
> Why was the name and id changed and removed from a few steps? Both are fine as-is and can stay.

I made this changes at some places as to check if it works or not. 😄

**Comment by NotMyFault** [comment]
Looks fine so far, but is there a particular reason, why you didn't choose https://github.com/actions/upload-artifact?
Based on a quick read, it should do fine what the archived action does, we are using at the moment.

**Comment by afzal442** [comment]
hmm! that's interesting. The reason why I choose this is because it allows customisation with outputs like we have this at the moment. 🏷️

**Comment by afzal442** [comment]
LMK if you have anything else to suggest here. Thanks.

**Comment by NotMyFault** [comment]
I'm inclined to prefer the GH action, because it's not subject to various recent action deprecations, like Node 12 -> 16 or `set-output`.
This one is affected by both, hence there's no real net benefit in switching to the softprops action, given addressing both deprecations is the motivation behind the issue.

**Comment by NotMyFault** [comment]
Hey @afzal442,

are you interested in looking into my recommendation to move this PR forward?

**Comment by afzal442** [comment]
hmm! yes I'm. But need more time. :)

**Review by NotMyFault — APPROVED** [review]
I resolved the outstanding issues myself and verified these by re-releasing 2.385 in my fork.

**Pull request merged**
