### PR TITLE
[FIXED JENKINS-36043] - Fixed NPE when no "scm" JSON object is null

### PR DESCRIPTION
**Pull request by mohamed-el-habib**
https://issues.jenkins-ci.org/browse/JENKINS-36043

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
👍

**Comment by oleg-nenashev** [comment]
Would be better to check property availability before binding BTW

**Comment by oleg-nenashev** [comment]
Maybe #2426 fixes it in a better way

**Comment by jglick** [comment]
:-1:, this seems to be fixing a symptom rather than actually correcting anything. Whether #2426 will fix JENKINS-36043 is another question; `AbstractMultiBranchProject` has a rather strange implementation that might need special care.

**Comment by oleg-nenashev** [comment]
I see no problem with fixing symptom, but ideally @jglick should polish his PR a bit

**Comment by mohamed-el-habib** [comment]
I don't understood how #2426 fix the NPE. into AbstractMultiBranchProject field that contains scm information is 'scmSource' and not 'scm', so we will get NPE at line [60](https://github.com/jenkinsci/jenkins/pull/2426/files#diff-d376d6548897110deaa2e9a5f82b5ca0R60)

**Comment by jglick** [comment]
Subsumed by #2426.

**Pull request closed without merging**
