### PR TITLE
[JENKINS-27058] Enforce absolute paths for Slave.remoteFS

### PR DESCRIPTION
**Pull request by recampbell**
@reviewbybees

### CODE REVIEW

**Comment by olivergondza** [comment]
`File#isAbsolute()` is platform dependent. Does it accept windows paths on unix master and vice-versa?

**Comment by jglick** [comment]
Exactly, I think this cannot work as written if the slave is a different OS than the master.

**Comment by recampbell** [comment]
@olivergondza @jglick OK, I'm reusing the existing validation approach now.

**Comment by recampbell** [comment]
@stephenc , they can be relative when entered into the UI, but must be absolute by the time they are passed to the Slave constructor, at least according to the contract of Slave.remoteFS.

**Comment by stephenc** [comment]
To give an example, I regularly use `./jenkins-slave` as a remoteFS path for even normal slaves as that allows me to jump around different slave IPs running different OSes or jump around the user without having to reconfigure the slave and have different workspaces resolved depending on the host:user pair

The constructor cannot be given an absolute path for this use case as the path cannot be made absolute without a connection to the slave

**Comment by daniel-beck** [comment]
@reviewbybees Please sign your responses when using this address.

**Comment by olivergondza** [comment]
FWIW, I come across a situation when relative path caused problems to maven tool installer https://github.com/openshift/jenkins-cloud-plugin/pull/18. Anyway, if there are valid usecases then at least javadoc has to be corrected.

**Comment by recampbell** [comment]
Yes, relative paths will break workflow, too.

**Comment by stephenc** [comment]
Well we may need to look into that. I suspect a different tack is what's needed. The path can be absolute when connected, but there is a need for relative paths for Slave's persisted state

**Comment by jglick** [comment]
I am fine with the persisted `remoteFS` being a relative path for some weird use cases, so long as the actual path passed around once the connection is made is absolute. That would perhaps mean relaxing `Node.createPath` to accept relative paths and call `absolutize` at the end.

**Comment by jglick** [comment]
In that case, some other uses of `getRemoteFS()` would probably need to be adjusted. In particular, `CommandLauncher` should be setting `WORKSPACE` to an absolute path (perhaps just by using `node.getRootPath().getRemote()` in place of `node.getRemoteFS()`). `SlaveComputer` also would have to absolutize `root`.

My concern is that there are plugins floating around which believe the current Javadoc and assume that `getRemoteFS()` is an absolute path; if @stephenc has a use case which requires it to sometimes be relative, that is not technically supported by the current API, so we have a compatibility issue.

**Comment by stephenc** [comment]
I am recommending closing this in favour of https://github.com/jenkinsci/jenkins/pull/1606

**Comment by recampbell** [comment]
Made obsolete by #1606

**Pull request closed without merging**
