### PR TITLE
Expose fingerprint methods for plugins

### PR DESCRIPTION
**Pull request by stellargo**
### Proposed changelog entries

* Developer: Expose fingerprint range set serialization methods for plugins

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by stellargo** [comment]
WIP

**Review by afalko — APPROVED** [review]

**Review by afalko — COMMENTED** [review]
Why not remove the line vs. comment?

**Comment by stellargo** [comment]
@afalko This PR is in draft state because there might be other changes that are required in downstream PR. These are ad-hoc changes which I'll clean once the downstream PR is ready for merge :)

**Comment by stellargo** [comment]
CC @oleg-nenashev @afalko @mikecirioli

**Comment by stellargo** [comment]
Downstream plugin: https://github.com/jenkinsci/postgresql-fingerprint-storage-plugin

**Comment by afalko** [comment]
Don't you still want to just remove the line rather than leaving it commented?

**Comment by stellargo** [comment]
@afalko I undid that comment. Could you please check you aren't by default viewing an old commit

**Review by afalko — APPROVED** [review]

**Comment by afalko** [comment]
> @afalko I undid that comment. Could you please check you aren't by default viewing an old commit

Ahh, that was the problem; I wish it would auto-refresh :).

**Review by oleg-nenashev — APPROVED** [review]
I am not against this pull request, it looks solid on its own. Just keep in mind that it likely exposes a potential issue with other converters. PostgreSQL Fingerprint storage may not work if Fingerprint Facets declare their own converters and register it in the Jenkins core XSTREAM instance only

**Comment by stellargo** [comment]
@oleg-nenashev shouldn't be a problem, the Postgres plugin defines it's own instance. I feel that the converter is good to have in the api, else all the plugins would basically keep re-implementing it.

**Review by res0nance — APPROVED** [review]
Looks alright, should be squash merged, the commit history seems like a mess for such a small change

**Comment by oleg-nenashev** [comment]
We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Pull request merged**
