### PR TITLE
[Fix JENKINS-46161] Make ReverseBuildTrigger#getUpstreamProjects null…

### PR DESCRIPTION
**Pull request by liketic**
…-safe

See [JENKINS-46161](https://issues.jenkins-ci.org/browse/JENKINS-46161).

### Proposed changelog entries

* Entry 1: Issue, Human-readable Text
* ...

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@oleg-nenashev

### CODE REVIEW

**Review by oleg-nenashev — COMMENTED** [review]
I would rather keep the method nullable and add proper annotations if it was a new method. But this option is safer since there may be other external usages. 

In any case, I suggest adding the `@CheckForNull` annotation to the `upstreamProjects` field and to add Javadoc to `getUpstreamProjects()` in order to describe the behavior of the method

**Comment by liketic** [comment]
@oleg-nenashev Thanks for your reply. I updated the PR. I'm OK to close this if you thought the fix is deprecated. Thanks.

**Review by oleg-nenashev — APPROVED** [review]
👍

**Comment by oleg-nenashev** [comment]
No votes against. Merging without squash, commits are self-consistent

**Comment by daniel-beck** [comment]
No proposed changelog and the issue description is complete 💩 as well 😢

**Comment by oleg-nenashev** [comment]
@daniel-beck my bad, I should have modified the changelog proposal before merging. I've forgotten about it in this ticket. Will follow-up in jenkins.io PR

**Pull request merged**
