### PR TITLE
[JENKINS-69341] Text and logo exceed sidepanel in "About Jenkins" view

### PR DESCRIPTION
**Pull request by frankie139506**
See [JENKINS-69341](https://issues.jenkins.io/browse/JENKINS-69341).

### Proposed changelog entries

* Too minor.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] (If applicable) Jira issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [X] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")` if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content-Security-Policy directives (see [documentation on jenkins.io](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/6994"></a>

### CODE REVIEW

**Review by NotMyFault — DISMISSED** [review]
Thanks for addressing, looks much better:

Screenshot 2022-08-15 at 10 59 35

**Review by daniel-beck — CHANGES_REQUESTED** [review]
I don't think changing the sidepanel width for all pages in Jenkins is an appropriate solution when one page in Jenkins with a completely custom layout looks slightly awkward in incremental builds only.

If the sidepanel should be made wider to accommodate a real need of wider labels, that's fine. But this isn't it.

Notably, the About page layout is broken at window widths of 970-1165 px anyway, so it's not even that that particular page's layout is fine otherwise.

<details>

Screenshot 2022-08-15 at 12 25 43

</details>

**Comment by frankie139506** [comment]
> I don't think changing the sidepanel width for all pages in Jenkins is an appropriate solution when one page in Jenkins with a completely custom layout looks slightly awkward in incremental builds only.
> 
> If the sidepanel should be made wider to accommodate a real need of wider labels, that's fine. But this isn't it.
> 
> Notably, the About page layout is broken at window widths of 970-1165 px anyway, so it's not even that that particular page's layout is fine otherwise.

@daniel-beck Do you mean that I need an underlaying fix?

**Comment by daniel-beck** [comment]
> Do you mean that I need an underlaying fix?

No, I mean that this fix changes too much (every page in Jenkins) for a very narrow bug (incremental version numbers are larger than the sidepanel on the About Jenkins page).

Perhaps look into whether the About Jenkins sidepanel can be set up to wrap overflowing text?

**Comment by frankie139506** [comment]
> > Do you mean that I need an underlaying fix?
> 
> No, I mean that this fix changes too much (every page in Jenkins) for a very narrow bug (incremental version numbers are larger than the sidepanel on the About Jenkins page).
> 
> Perhaps look into whether the About Jenkins sidepanel can be set up to wrap overflowing text?

I have made some change. Please take a look.

**Comment by daniel-beck** [comment]
Looks reasonable now (screenshot with patched DOM):
Screenshot 2022-08-15 at 16 14 39
Screenshot 2022-08-15 at 16 14 26

**Comment by frankie139506** [comment]
> Looks reasonable now (screenshot with patched DOM): Screenshot 2022-08-15 at 16 14 39 Screenshot 2022-08-15 at 16 14 26

Thanks. If have any problem plz tell me.

**Review by daniel-beck — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]
Thanks for addressing the outstanding concerns!

---

This PR is now ready for merge. We will merge it after ~24 hours if there is no negative feedback.
Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process.
Thanks!

**Pull request merged**
