### PR TITLE
[JENKINS-72944] reduce spacing in buildhistory widget

### PR DESCRIPTION
**Pull request by mawinter69**
the logic when name, details and badges arrangement is changed so that the available space is better used.
The stop action is no longer treated as separate thing, instead it is just like all other badges. The stop button will always be in the far right. The width calculation now considers the actual width of the content and not of the element they are in. When name and badges fit in one row they will be joined.
badges are using a flex layout that should allow for better alignement and will automatically wrap the elements though this only happen now when the badges are in their own row and still to large

Add a resize handler so when the sidepanel switch to/from tablet mode or size is changed in tablet mode then the table layout is recalculated.

The pictures show builds with many badges (gerrit, build trigger badge, keep build forever, job config change, disk usage)

<details>
  <summary>Screenshots before</summary>
Full width window:

- line break inside the disk usage badge 
- no space between badges
- bad alignement (see build 11530)

image

~850px width window
image

min-width window (483px)
image

Running build
image

after going to full-screen from min-width window
image

</details>

<details>
  <summary>Screenshots after</summary>

Full width window with running build
image

~850px width window
image

min-width window (483px)
image

</details>

See [JENKINS-72944](https://issues.jenkins.io/browse/JENKINS-72944).

### Testing done
Manual testing

### Proposed changelog entries

- JENKINS-72944, reduce spacing in buildhistory widget

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [x] The Jira issue, if it exists, is well-described.
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [x] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Review by timja — APPROVED** [review]
I haven't closed inspected the JavaScript, its quite complex. Something like handlebars would likely clean the code up a lot but may be complicated by the fact the badges are loaded in via jelly

----

Screenshots and testing looks good to me

**Review by Kevin-CB — COMMENTED** [review]
I tested your PR locally, it looks fine security wise.

However, I've noticed minor bugs. 
When I build an empty freestyle project and add a build description, the ordering gets messed up, placing the description first and the left bar in the middle of the character. Note that this seems to only happen on the last build.
image

Also, when there are no badges on my build, I encounter some errors.
image

**Comment by mawinter69** [comment]
> 
> However, I've noticed minor bugs. When I build an empty freestyle project and add a build description, the ordering gets messed up, placing the description first and the left bar in the middle of the character. Note that this seems to only happen on the last build. image
> 

Fixed

> Also, when there are no badges on my build, I encounter some errors. image

fixed

**Review by NotMyFault — APPROVED** [review]

**Comment by mawinter69** [comment]
given ongoing work by @janfaracik in #9148 to rewrite the build history widget does it make sense to merge this?

**Comment by timja** [comment]
Let's mark as on-hold, we can always pick it back up later if needed.

/label on-hold

**Comment by mawinter69** [comment]
close in favor of #9148

**Pull request closed without merging**
