### PR TITLE
[JENKINS-32978] support latest source version to avoid compile time warnings with JDK7

### PR DESCRIPTION
**Pull request by daspilker**
see http://stackoverflow.com/questions/8185331/forward-compatible-java-6-annotation-processor-and-supportedsourceversion

### CODE REVIEW

**Comment by daspilker** [comment]
This has already been fixed in stapler (https://github.com/stapler/stapler/pull/58) and windows-packer-checker (https://github.com/kohsuke/windows-package-checker/pull/1). Can we please fix this in core as well to get rid of the compile time warnings?

**Comment by oleg-nenashev** [comment]
👍 
CC @jenkinsci/code-reviewers

**Comment by daniel-beck** [comment]
:+1:

**Comment by daspilker** [comment]
Cool thanks! Can we also get this issue solved for lib-annotation-indexer (https://github.com/jenkinsci/lib-annotation-indexer/pull/3) and sezpoz (https://github.com/jglick/sezpoz/pull/11)?

**Comment by oleg-nenashev** [comment]
sezpos needs an action from @jglick 
lib-annotation-indexer should be released manually. I'll do it

**Pull request merged**
