### PR TITLE
Update buttons to use new classes on the dashboard

### PR DESCRIPTION
**Pull request by janfaracik**
Small PR to update the design of the `.jenkins-button` classes as well as to use the classes on the dashboard. This is the first part of several PRs to update buttons across Jenkins (see the closed #5897 for a rough end goal).

**Before**
image

**After**
image

It's rather hard to tell any major differences here (apart from color), the key differences are the hover/focus states:

**Before**

https://user-images.githubusercontent.com/43062514/177791395-6c2bb1f9-6c12-49f6-bd10-912bdb936c28.mov

**After**

https://user-images.githubusercontent.com/43062514/177791859-6277f2be-f726-4af9-b679-921af07cddfa.mov

**New keyboard focus state**
Screenshot 2022-07-07 at 14 59 35

**What else?**
* Slight change to `.jenkins-button` appearance (slightly more rounded/padded, icons are larger)
* Semantic modifiers have been removed (e.g. `.jenkins-button--destructive`), you can now use semantic and palette classes to the same thing (e.g. `.jenkins-button .jenkins-!-destructive-color`)
* `.jenkins-button--transparent` has been renamed to `.jenkins-button--tertiary`

Seeing as `.jenkins-button` isn't used anywhere apart from Jenkins/Design Library it should be fine to make these breaking changes without backwards compatibility. I'll update Design Library to support these changes.

### Proposed changelog entries

* Update design of buttons on the dashboard 

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")` if applicable.
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@jenkinsci/sig-ux 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/6799"></a>

### CODE REVIEW

**Review by yaroslavafenkin — APPROVED** [review]
Looks ok to me from security standpoint. Done superficial manual testing, haven't found anything broken in the UI.

**Review by NotMyFault — APPROVED** [review]
Looks nice 👏🏻

**Review by timja — COMMENTED** [review]
Likely intentional but I wanted to check before approving.

----

The icon size buttons don't match the screenshots you've provided.

image

the active one is faded out while the others show as more button like.

is it meant to be like that?

**Comment by janfaracik** [comment]
> Likely intentional but I wanted to check before approving.
> 
> The icon size buttons don't match the screenshots you've provided.
> 
> image
> 
> the active one is faded out while the others show as more button like.
> 
> is it meant to be like that?

Not intentional - Might need to clear cache there, your screenshot is showing the old style buttons. I've just reran it again on my end and it produces what's seen in the screenshot -

Screenshot 2022-07-14 at 09 49 48

**Comment by timja** [comment]
Ok clearing cache worked, for me clicking the button size changes doesn't seem to work.

it worked for one click on S but then I couldn't get back to L, when I cleared by cookies I can't change the size any more

**Comment by janfaracik** [comment]
> Ok clearing cache worked, for me clicking the button size changes doesn't seem to work.
> 
> it worked for one click on S but then I couldn't get back to L, when I cleared by cookies I can't change the size any more

Can't seem to reproduce that in Safari or Chrome.

https://user-images.githubusercontent.com/43062514/179045902-b161609f-9c5f-4e82-8f29-029bf1386085.mov

**Comment by timja** [comment]
> Can't seem to reproduce that in Safari or Chrome.

How are you testing? I'm using `mvn jetty:run` from https://github.com/jenkinsci/jenkins/blob/master/CONTRIBUTING.md#building-and-debugging

If I request the URL http://localhost:8080/jenkins/iconSize?24x24 and I have a breakpoint at
https://github.com/jenkinsci/jenkins/blob/a990ebcda49cf6aa457acfa03dd91adced26504e/core/src/main/java/jenkins/model/Jenkins.java#L4771 the breakpoint is never called.

If I add a trailing slash then it's correctly invoked:
http://localhost:8080/jenkins/iconSize/?24x24

----

This seems to be a pre-existing issue and I can reproduce it on master, would be good to hear someone else can as well though.

**Comment by timja** [comment]
> I'm doing the same but can't seem to reproduce it on master either. Do you have any projects/folders in the table when it isn't working?

A bunch, including some with strange names for CSRF, I'll try from a clean one later on

**Comment by janfaracik** [comment]
> > I'm doing the same but can't seem to reproduce it on master either. Do you have any projects/folders in the table when it isn't working?
> 
> A bunch, including some with strange names for CSRF, I'll try from a clean one later on

Is this PR good to move forward without that?

**Comment by timja** [comment]
Yes

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by ViliusS** [comment]
Please stop taking out color out of design elements. These buttons were blue to indicate that they are clickable. What's separating them now from the rest of the text?

**Comment by daniel-beck** [comment]
Probably causes [JENKINS-70247](https://issues.jenkins.io/browse/JENKINS-70247).

**Comment by basil** [comment]
> Probably causes [JENKINS-70247](https://issues.jenkins.io/browse/JENKINS-70247).

Confirmed through bisection.

**Pull request merged**
