### PR TITLE
LTS 2.263.2

### PR DESCRIPTION
**Pull request by timja**
```
Fixed
-----

JENKINS-64393		Critical  		Thu, 10 Dec 2020 21:11:24 +0000
	junit4 tests are no longer run in the core build
	https://issues.jenkins.io/browse/JENKINS-64393

JENKINS-64373		Minor     		Thu, 10 Dec 2020 21:12:00 +0000
	github-branch-source help icon doesn't expand on recent core
	https://issues.jenkins.io/browse/JENKINS-64373

JENKINS-64330		Trivial   		Thu, 10 Dec 2020 21:12:40 +0000
	Wrong unicode codes in spanish translation and small improvements
	https://issues.jenkins.io/browse/JENKINS-64330

JENKINS-64125		Critical  		Thu, 10 Dec 2020 21:12:44 +0000
	Select inside invisibleEntry is not being populated by the backend
	https://issues.jenkins.io/browse/JENKINS-64125

JENKINS-64071		Minor     		Thu, 10 Dec 2020 21:12:05 +0000
	f:select not populated by doFill method
	regression
	https://issues.jenkins.io/browse/JENKINS-64071

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
Fine with me, thanks @timja! IIUC we have some tome for additional backports if something pops up

**Review by res0nance — APPROVED** [review]

**Comment by timja** [comment]
LDAP plugin ATH errors because the test is loading a newer ldap version than works with core if anyone has time to look, I've had a brief look and update center metadata looks right, https://updates.jenkins.io/update-center.actual.json?version=2.263.2 does get me redirected to the right update center =/.

```
master60577|2020-12-11 03:30:05.366+0000 [id=111]	WARNING	hudson.PluginWrapper#versionDependencyError: Suppressing dependency error in LDAP Plugin v2.2: Jenkins (2.266) or higher required
master60577|2020-12-11 03:30:05.366+0000 [id=111]	INFO	h.model.UpdateCenter$DownloadJob#run: Installation successful: ldap
master60577|2020-12-11 03:30:05.366+0000 [id=111]	INFO	h.m.UpdateCenter$CompleteBatchJob#run: Completing installing of plugin batch?
Plugins to be updated: []
master60577|2020-12-11 03:30:05.440+0000 [id=111]	WARNING	h.ExtensionFinder$GuiceFinder$SezpozModule#configure: Failed to load hudson.security.LDAPSecurityRealm$DescriptorImpl
master60577|java.lang.ClassNotFoundException: org.springframework.security.core.AuthenticationException
master60577|	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1387)
master60577|	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1342)
master60577|	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1089)
master60577|	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
master60577|Caused: java.lang.NoClassDefFoundError: org/springframework/security/core/AuthenticationException
master60577|	at java.lang.Class.getDeclaredConstructors0(Native Method)
master60577|	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
master60577|	at java.lang.Class.getDeclaredConstructors(Class.java:2020)
master60577|	at hudson.ExtensionFinder$GuiceFinder$SezpozModule.resolve(ExtensionFinder.java:501)
master60577|	at hudson.ExtensionFinder$GuiceFinder$SezpozModule.resolve(ExtensionFinder.java:482)
master60577|	at hudson.ExtensionFinder$GuiceFinder$SezpozModule.configure(ExtensionFinder.java:531)
master60577|	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
master60577|	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
master60577|	at com.google.inject.spi.Elements.getElements(Elements.java:110)
master60577|	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
master60577|	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
master60577|	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:226)
master60577|	at hudson.ExtensionFinder$GuiceFinder.refresh(ExtensionFinder.java:347)
master60577|	at jenkins.model.Jenkins.refreshExtensions(Jenkins.java:2742)
master60577|	at hudson.PluginManager.start(PluginManager.java:978)
master60577|	at hudson.model.UpdateCenter$CompleteBatchJob.run(UpdateCenter.java:2288)
master60577|	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
master60577|	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
master60577|	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:118)
master60577|	at java.lang.Thread.run(Thread.java:748)
```

**Review by fqueiruga — APPROVED** [review]

**Review by jtnord — APPROVED** [review]
> https://updates.jenkins.io/update-center.actual.json?version=2.263.2 does get me redirected to the right update center

What about https://updates.jenkins.io/update-center.actual.json?version=2.263.2-SNAPSHOT though

**Comment by timja** [comment]
> > [updates.jenkins.io/update-center.actual.json?version=2.263.2](https://updates.jenkins.io/update-center.actual.json?version=2.263.2) does get me redirected to the right update center
> 
> What about [updates.jenkins.io/update-center.actual.json?version=2.263.2-SNAPSHOT](https://updates.jenkins.io/update-center.actual.json?version=2.263.2-SNAPSHOT) though

yeah that's it

any thoughts @daniel-beck?

**Comment by daniel-beck** [comment]
https://github.com/jenkins-infra/update-center2/pull/476

**Comment by timja** [comment]
> Fine with me, thanks @timja! IIUC we have some tome for additional backports if something pops up

I did a comb through jira and recent merges for this, there was only one there initially.
But yeah there's time if anyone wants to propose others / anything urgent.

Plan is to deliver RC next week as I don't want to commit to anything over the Xmas period

**Comment by timja** [comment]
Last build of ATH looks pretty good, couple of plugin's need updates, and a few flakes I think

**Pull request merged**
