### PR TITLE
[JENKINS-31753] Fields are aligned at the bottom

### PR DESCRIPTION
**Pull request by fbonerandi**
before :
before_modif
after : 
after_modif2

### CODE REVIEW

**Comment by batmat** [comment]
:+1: 
Btw you could have force pushed the previous PR if you wanted to.

So you wanna close #1980 right?

**Comment by daniel-beck** [comment]
LGTM. @jtnord @oleg-nenashev since you commented on the previous one, WDYT?

**Comment by jtnord** [comment]
LGTM :+1:

**Comment by fbonerandi** [comment]
Could you add to next LTS version

**Comment by olivergondza** [comment]
@fbonerandi, the issue is flagged lts-candidate already.

**Pull request merged**
