### PR TITLE
Make compilable with JDK 9 javac

### PR DESCRIPTION
**Pull request by jglick**
Amends #2603.

@reviewbybees

### CODE REVIEW

**Comment by daniel-beck** [comment]
Is this real or just a bug in the compiler?

**Comment by jglick** [comment]
> Is this real or just a bug in the compiler?

Apparently JDK 9 fixed a corner case in interpretation of the spec. IOW the code was wrong and earlier versions of `javac` mistakenly permitted it.

**Comment by jglick** [comment]
@reviewbybees done

**Comment by stephenc** [comment]
I thought it was explicitly for the case of construction of objects that the diamond operator was introduced. Have you a link to the javac bug?

**Comment by johnou** [comment]
I agree with Stephen, in my opinion the code should compile as it was with the diamond operator with jdk 7 and above.

**Comment by jglick** [comment]
> it was explicitly for the case of construction of objects that the diamond operator was introduced

Yes, and the diamond operator still works in most cases. This is a special case where the inferred type uses a wildcard but the assigned type does not (IIUC).

> Have you a link to the javac bug?

[JDK-8075793](https://bugs.openjdk.java.net/browse/JDK-8075793). Apparently they are now going back to accepting broken source code when using `java.level=7`, so this patch would not be strictly required now (if using a sufficiently new JDK 9 build), but we would need it anyway when moving the Jenkins source level forward.

**Comment by johnou** [comment]
@jglick nice catch.

**Review by johnou — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
Does not hurt anyway. 🚢 🇮🇹

**Comment by daniel-beck** [comment]
@jglick 

From the linked report:

> It also compiles with Java 9 when passing the -source/target 1.8 or 1.9.

Does that not contradict the foillowing?

> we would need it anyway when moving the Jenkins source level forward

**Comment by recampbell** [comment]
@reviewbybees done

**Comment by oleg-nenashev** [comment]
@recampbell From what I see it is not done since there is an outstanding question from @daniel-beck

**Comment by jglick** [comment]
@daniel-beck possibly true; I have not checked that yet. At any rate, being explicit about the type is not going to hurt anything. At worst we have another possible use of type diamond after switching to `-source 8`.

**Review by daniel-beck — COMMENTED** [review]
No opinion. I don't think this is a relevant case to address, OTOH it's a trivial change.

**Comment by jglick** [comment]
> I don't think this is a relevant case to address

Well it is relevant to me because without it I cannot work on Jenkins core sources.

**Comment by daniel-beck** [comment]
@jglick Don't use pre-release software then? :wink:

**Comment by batmat** [comment]
Makes me think we should add this combinatorials to Jenkinfile then and check it too continuously as we now do for Windows.

**Comment by johnou** [comment]
@batmat or just setup CI for Jenkins w/ JDK9?

**Comment by daniel-beck** [comment]
@johnou I think that's what @batmat is proposing.

**Comment by batmat** [comment]
Filed https://issues.jenkins-ci.org/browse/INFRA-1101 for adding a JDK9 on ci.j.i

**Pull request merged**
