### PR TITLE
Remove `msie.js`, `svgxuse.min.js` and CSS custom properties polyfill

### PR DESCRIPTION
**Pull request by janfaracik**
We no longer support Internet Explorer 11, so there is no longer a need for the polyfill or custom JavaScript.

### Testing done

We verified that `git grep -i ismsie` returned no results and that code searches for [`msie.js`](https://cs.github.com/?scopeName=All+repos&scope=&q=user%3Ajenkinsci+%22msie.js%22) and [`svgxuse.min.js`](https://cs.github.com/?scopeName=All+repos&scope=&q=user%3Ajenkinsci+%22svgxuse.min.js%22) returned no results. Additionally, we verified that the only remaining results for `git grep -i msie` in Jenkins core were in third-party YUI code.

### Proposed changelog entries

* N/A

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@jenkinsci/sig-ux @basil 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by NotMyFault — APPROVED** [review]

**Review by timja — APPROVED** [review]
There’s probably a whole bunch of manually done CSS variables fallbacks for adjuncts that postcss wasn’t processing if you’re interested in going further

**Review by timja — APPROVED** [review]

**Review by basil — APPROVED** [review]
The Git branch is named `ie-deprecation`, but typically to deprecate something means to discourage its use (while still supporting it). Support for IE 11 isn't just deprecated: it no longer exists. So this Git branch could be more accurately named `ie-removal`.

As in the other PR, the main question we have with regard to PRs like this is whether the PR will break any existing consumers. The PR description is lacking reasoning in this regard. As a courtesy, I have taken the liberty to update the PR description with the following text:

> We verified that `git grep -i ismsie` returned no results and that code searches for [`msie.js`](https://cs.github.com/?scopeName=All+repos&scope=&q=user%3Ajenkinsci+%22msie.js%22) and [`svgxuse.min.js`](https://cs.github.com/?scopeName=All+repos&scope=&q=user%3Ajenkinsci+%22svgxuse.min.js%22) returned no results. Additionally, we verified that the only remaining results for `git grep -i msie` in Jenkins core were in third-party YUI code.

Given the lack of consumers from the code search, I am approving this PR. Please study the reasoning given above and use this as a model for future PR submissions.

---

This PR is now ready for merge. We will merge it after approximately 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process. Thanks!

**Comment by basil** [comment]
CI builds are consistently failing. This will need to be addressed prior to integration.

**Comment by basil** [comment]
> CI builds are consistently failing. This will need to be addressed prior to integration.

As a courtesy, I have taken the liberty of checking in the changes to `war/yarn.lock` in commit 63c94169b3.

**Pull request merged**
