### PR TITLE
[JENKINS-63232] Build Time Trend Page fails to Display Build Time History

### PR DESCRIPTION
**Pull request by Wadeck**
See [JENKINS-63232](https://issues.jenkins-ci.org/browse/JENKINS-63232).

When the job is not an AbstractBuild and there are some agents on the system, the "builtOnStr" was `undefined`.

### Proposed changelog entries

* JENKINS-63232, Fix a regression in Build Time Trend Page

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [n/a] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@daniel-beck 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Review by daniel-beck — APPROVED** [review]

**Review by fqueiruga — APPROVED** [review]

**Comment by timja** [comment]
Shipping to weekly as discussed on #jenkins-release in IRC

**Comment by amai2012** [comment]
Will it be backported to LTS? See bug report

**Comment by timja** [comment]
Hi yes it’s marked as an LTS candidate so it should get backported

**Comment by daniel-beck** [comment]
It's too late for 2.235.x though as that line has basically ended. Expect this to be in 2.249.1.

**Pull request merged**
