### PR TITLE
Add Jenkins modules to the Core Bill of Materials

### PR DESCRIPTION
**Pull request by oleg-nenashev**
It looks like [JENKINS-55582  - Convert modules to plugins](https://issues.jenkins-ci.org/browse/JENKINS-55582) is not active at the moment (@jglick please correct me if I am wrong). Based on that, I would like to proceed and add the modules to BOM to minimize risks of using wrong module versions in plugins. Once modules are detached as plugins, we can always remove them from BOM, there are no compatibility guarantees for it.

### Proposed changelog entries

* Add Jenkins modules to the Core Bill of Materials
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Review by jtnord — COMMENTED** [review]
code looks ok, seems reasonable enough.

**Review by amuniz — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Review by res0nance — APPROVED** [review]

**Comment by jglick** [comment]
#3988 for reference

**Review by jglick — APPROVED** [review]
Yes this should ameliorate the problems associated with use of modules, especially for the ones that often find their way into plugin classpaths: `instance-identity` and `sshd`.

**Comment by oleg-nenashev** [comment]
@jenkinsci/core I suggest merging it tomorrow on the morning so that it has higher chance of getting into the next LTS release. There is no functional changes in this PR

**Pull request merged**
