### PR TITLE
[JENKINS-33192] Allow the 'groovy' CLI command to return exit codes

### PR DESCRIPTION
**Pull request by jmurphyau**
Added support for groovy scripts to return an exit code

https://issues.jenkins-ci.org/browse/JENKINS-33192

### CODE REVIEW

**Comment by olivergondza** [comment]
This looks good to me,

**Comment by jmurphyau** [comment]
I did this start on a base of the 2.0 branch - is there anything I need to do to make this change available for 2.0 and the master branch at the same time? Or is that something that's handled at merge/later?

In regards to needs-testcase: I'll get right onto that. Theres currently (that I can see) no test on the `groovy` command.. Is there anything in addition to this change that I should test while I'm in there?

Are these comments best placed in Jira or here in Github?

**Comment by olivergondza** [comment]
It is ok to discuss the implementation on github. You are right there are no tests for `groovy` command but those for `groovysh`[1] should be a good starting point.

Ad 2.0: If I am not mistaken, changes from master will be merged into 2.0 once it is ready for release, so I would say everything should go to master unless it is 2.0 material. This PR is not.

[1] https://github.com/jenkinsci/jenkins/blob/master/test/src/test/java/hudson/cli/GroovyshCommandTest.java

**Comment by daniel-beck** [comment]
Closing this PR as it was based on the wrong branch to prevent accidental merges. Please resubmit towards `master`.

**Pull request closed without merging**
