### PR TITLE
upgrade to winstone 5.3 (Jetty 9.4.18.v20190429)

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: olivier lamy <olamy@apache.org>

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

### Proposed changelog entries

* RFE, Winstone 5.3: Upgrade to Jetty 9.4.18.v20190429
  * Winstone changelog: https://github.com/jenkinsci/winstone/blob/master/CHANGELOG.md#53
  * Jetty 9.4.18: https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.18.v20190429
  * Jetty 9.4.17: https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.17.v20190418
  * Jetty 9.4.16: https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.16.v20190411
* ...

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### CODE REVIEW

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
Please provide clarification what changes there (links to upstream changelogs, JIRA issues, etc.) so that we can evaluate the change

**Comment by olamy** [comment]
at this stage it's WIP as I was expecting some CI build to validate the change....

**Review by oleg-nenashev — APPROVED** [review]
That's why we have a PR template 🤷‍♂

**Comment by batmat** [comment]
For cross-reference this picked up https://github.com/jenkinsci/winstone/pull/63 which is said to have caused https://issues.jenkins-ci.org/browse/JENKINS-57888

**Pull request merged**
