### PR TITLE
2.277.2 backporting

### PR DESCRIPTION
**Pull request by MarkEWaite**
## 2.277.2 backporting

```
Fixed
-----

JENKINS-62006 - Major - 2.285
        Fix NoClassDefFoundError exception while executing ProcessTree.get()
        https://issues.jenkins.io/browse/JENKINS-62006

JENKINS-64931 - Major - 2.283
        Prevent Jenkins queue deadlock when cancelling tasks under certain conditions
        https://issues.jenkins.io/browse/JENKINS-64931

JENKINS-64972 - Minor - 2.283
        Fix help buttons in the draggable section
        https://issues.jenkins.io/browse/JENKINS-64972

JENKINS-65186 - Minor - 2.278
        Reduce logging of renamed API endpoint
        https://issues.jenkins.io/browse/JENKINS-65186
```

### CODE REVIEW

**Review by res0nance — APPROVED** [review]

**Review by timja — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]

**Review by markjacksonfishing — APPROVED** [review]

**Comment by MarkEWaite** [comment]
28 failing acceptance test harness tests are failing.  The 2.277.1 backporting pull request had 30 failing ATH tests.  Assumed that the failures are comparable.

**Comment by timja** [comment]
> 28 failing acceptance test harness tests are failing. The 2.277.1 backporting pull request had 30 failing ATH tests. Assumed that the failures are comparable.

Updating ATH version should fix at least one test

**Comment by MarkEWaite** [comment]
> Updating ATH version should fix at least one test

Pushed a67c09ce3faef036106854c63608cbe8ce217c14 with the most recent ATH version.

**Comment by daniel-beck** [comment]
Haven't we done `cherry-pick -x` in the past?

**Review by markjacksonfishing — APPROVED** [review]

**Comment by MarkEWaite** [comment]
> Haven't we done `cherry-pick -x` in the past?

Yes.  Missed that option in the cherry-pick while I was evaluating pull requests.  I can redo the commits so that we are consistent with previous backports.

**Comment by MarkEWaite** [comment]
> > Haven't we done `cherry-pick -x` in the past?
> 
> Yes. Missed that option in the cherry-pick while I was evaluating pull requests. I can redo the commits so that we are consistent with previous backports.

**Review by daniel-beck — APPROVED** [review]
Backports look correct. The issues seem relevant and worth backporting based on the issue descriptions.

**Pull request merged**
