### PR TITLE
XMLUtils should parse via InputStream not Reader

### PR DESCRIPTION
**Pull request by jglick**
Parsing an XML file using `Reader` renders any encoding declaration ineffective, so this should be avoided.

### Proposed changelog entries

* Added better parsing overloads to `XMLUtils`.

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by jglick** [comment]
I presume the `FunctionsTest.printThrowable` failure is a flake.

**Review by res0nance — APPROVED** [review]
If the `Reader` version is undesirable should we deprecate it?

**Comment by jglick** [comment]
> If the `Reader` version is undesirable should we deprecate it?

Well, maybe, but you might be stuck with a `Reader` for reasons outside your control. In this case it is assumed that the encoding is not an issue. I did deprecate the `(File, String)` overload which was clearly wrong.

**Review by oleg-nenashev — APPROVED** [review]
LGTM.

We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Pull request merged**
