### PR TITLE
Correct self label check

### PR DESCRIPTION
**Pull request by res0nance**
See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

I was reading the code around label and noticed this bug.
Corrected its behaviour to match its documentation and wrote the appropriate test

### Proposed changelog entries

* Entry 1: Too minor
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by MRamonLeon — APPROVED** [review]

**Review by rsandell — APPROVED** [review]

**Review by Wadeck — APPROVED** [review]
(unit) tested with and without the update, the test covers the change.

Not sure if this bug could be effectively impacting user experience or not, but seems interesting to be corrected 👍

**Comment by daniel-beck** [comment]
> Not sure if this bug could be effectively impacting user experience or not

That's my main question here. Does this fix a bug? I've always thought self-labels worked, but how, given this? Is it perhaps even deliberate?

**Comment by Wadeck** [comment]
@daniel-beck When someone requests a label in Jenkins, the default behavior is to look for it in a map, meaning it's the same reference. The unit test covers a case that could potentially happen in reality but is perhaps only happening in programmatic context.

Just to be clear, I have **not** manually tested the bug _(outside the unit tests, previous comment updated for clarity)_.

**Comment by res0nance** [comment]
> > Not sure if this bug could be effectively impacting user experience or not
> 
> That's my main question here. Does this fix a bug? I've always thought self-labels worked, but how, given this? Is it perhaps even deliberate?

It does work except in this case where a programmer creates another label atom and calls `isSelfLabel` I'd assume most programmer's would obtain the label via `Jenkins.getLabel()` which would avoid this issue entirely.

I'd say this is a bug as semantically one would define equality as whatever `equals` defines.

The javadoc as well supports the idea of equality of name being what defines equality and not equality of reference
```
Returns true if this label is a "self label",
which means the label is the name of a {@link Node}.
```

**Review by oleg-nenashev — APPROVED** [review]
Looks good to me taking the analysis above. Should be no user-facing defect indeed.

We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Pull request merged**
