### PR TITLE
In testParse_with_XXE(), use more temporary variables

### PR DESCRIPTION
**Pull request by rodrigc**
This will help isolate the source of exceptions
thrown in this test.

### CODE REVIEW

**Comment by jtnord** [comment]
:+1:

**Comment by jtnord** [comment]
@rodrigc where do you see the failures?
[jenkins.ci.c.c](https://jenkins.ci.cloudbees.com/job/core/job/jenkins-core/lastCompletedBuild/testReport/jenkins.xml/XMLUtilsTest/history/) and [ci.j.o](https://ci.jenkins-ci.org/job/jenkins_pipeline/branch/master/lastBuild/testReport/jenkins.xml/XMLUtilsTest/history/)  don;t show the test as failing.

**Comment by daniel-beck** [comment]
@jtnord https://ci.jenkins-ci.org/job/jenkins_main_trunk/4560/testReport/

Reference: https://groups.google.com/d/msg/jenkinsci-dev/hWoJiYQjGUo/2_OHSP6xBQAJ

**Comment by jtnord** [comment]
@daniel-beck may as well just merge this then?

**Comment by rodrigc** [comment]
See this thread: https://groups.google.com/forum/#!topic/jenkinsci-dev/hWoJiYQjGUo

**Comment by amuniz** [comment]
:+1: (weird NPE)

**Comment by rodrigc** [comment]
OK, now the test is failing here: https://ci.jenkins-ci.org/job/jenkins_main_trunk/4564/consoleText

``
in jenkins.xml.XMLUtilsTest
testParse_with_XXE(jenkins.xml.XMLUtilsTest)  Time elapsed: 0.052 sec  <<< ERROR!
java.lang.NullPointerException
	at jenkins.xml.XMLUtilsTest.testParse_with_XXE(XMLUtilsTest.java:130)
``

If I look at https://github.com/jenkinsci/jenkins/blob/master/core/src/test/java/jenkins/xml/XMLUtilsTest.java#L130

the only things that can be null are **stringReader** or **XMLUtils**.
I can't figure out which of those things could be null.

**Comment by slide** [comment]
Couldn't it be something inside of XMLUtils.parse? I've seen a method left
out of the stacktrace before.

**Comment by rodrigc** [comment]
@slide: Could be.  How would I find out?  I can't reproduce this test failure on my laptop.  It only fails 
             on the Jenkins host which is running the tests.  This makes things hard to isolate.

**Comment by slide** [comment]
Are you building on Windows or Linux? I think the build hosts are Linux, so
if you are building on Windows, maybe try in a VM or something?

**Comment by rodrigc** [comment]
I'm on Linux.

**Comment by jtnord** [comment]
And it is only failing in one of the builds... it is fine on jenkins.ci.cloudbees.com (oracle JDK7) and the pipeline build on ci.jenkins.org (some jdk8?) (link in above comment).

I'm tempted to say this is a bug in the JDK that is on ci.j.o - If XMLUtils could not be loaded cinit'ed it should throw a `ClassNotFoundException` not a `NullPointerException` - and all the tests in `XMLUtilsTest` should fail not just this one...
Could it really be this is running with the initial 1.7.0 JDK?

jenkins.ci.c.c (passing)
```
Java version: 1.7.0_79, vendor: Oracle Corporation
Java home: /opt/java/sdk/Oracle/x86_64/jdk1.7.0_79/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-71-generic", arch: "amd64", family: "unix"
```

ci.j.o (passing)
```
Java version: 1.8.0_51, vendor: Oracle Corporation
Java home: /home/jenkins/slave/tools/hudson.model.JDK/jdk8_51/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-77-generic", arch: "amd64", family: "unix"
```

ci.j.o (failing)
```
Java version: 1.7.0, vendor: Oracle Corporation
Java home: /home/jenkins/slave/tools/hudson.model.JDK/jdk7/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-77-generic", arch: "amd64", family: "unix"
```

**Comment by daniel-beck** [comment]
Reconfigured the job to build on 7u80.

**Comment by jtnord** [comment]
Thanks - seems to be fixed now.

**Comment by rodrigc** [comment]
@daniel-beck Thanks for upgrading the build host.

I'm still getting emails about a failing build: https://ci.jenkins-ci.org/job/jenkins_main_trunk/4566/console

```
10:15:34 [ERROR] npm WARN package.json jenkins-ui@1.0.0 No repository field.
10:15:34 [ERROR] npm WARN package.json jenkins-ui@1.0.0 No README data
```

Anyou ideas?  Thanks.

**Comment by jtnord** [comment]
The build is just timing out, the above error (although needing a fix) is not the cause of the failure AFAICT...

```
11:04:25 Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.39 sec - in jenkins.model.MasterBuildConfigurationTest
11:04:25 Running jenkins.model.JenkinsLocationConfigurationTest
11:04:38 Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.472 sec - in jenkins.model.JenkinsLocationConfigurationTest
13:14:08 Build timed out (after 180 minutes). Marking the build as failed.
```

So after a unit test finished - it was waiting for another 2hrs 10 minutes...
Given this is running with `concurrency=1` this looks like either surefire fails to start another test, or that it doesn't realize that all the tests have finished.  Given we have created a lot of processes I wonder if something is just a little tight on the end machine (OOM killing a process as soon as it starts, or failing to fork and surefire not picking this up).

What I could really do with is if the BuildTimeoutPlugin could send a kill -3 to any existing java processes (all surefire and the main maven java process) before it kills them to get a stack trace...  We are using the latest surefire plugin at least, but not the latest Maven...

Now on jenkins.ci.cb.com the VM is being yanked - and DEV@cloud has memory limits on processes so it could be that something in 2.0 is causing a higher than normal memory leak, or starting a non deamon thread that prevents surefire from exiting correctly, and consumes memory leading to the process being killed on DEV@cLoud and a build timeout on cucumber.  
@daniel-beck this really does concern me - as I don't believe that the jump in memory for the 2.0 branch was ever fully understood.

**Comment by amuniz** [comment]
>  this really does concern me - as I don't believe that the jump in memory for the 2.0 branch was ever fully understood.

@teilo there is no such memory jump as far as I can tell. I've run several times the full test suite locally (tried in both Linux and OSX) and monitored it during the run, it has never requested more than 500MB. I think there is some issue in ci.jenkins-ci.org infra, which I've not been able to diagnose.

**Pull request merged**
