### PR TITLE
Format POM files

### PR DESCRIPTION
**Pull request by basil**
A trivial change that simplify adjusts the whitespace in the POM files to use consistent indentation. The inconsistent indentation was driving me nuts every time I tried to edit these files, particularly when things were indented with an odd number of spaces. I suggest reviewing this with "Hide whitespace changes" enabled.

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]
Changes look good.

**Comment by daniel-beck** [comment]
Not sure about this one, the benefits are minimal, so even the minor downsides (polluting `git blame`) will not be insignificant in comparison.

Could we at least do something with checkstyle or something similar to prevent this problem in the future?

**Comment by basil** [comment]
`git blame -w` works just fine even with whitespace changes (which is really all this PR contains). I'm sure [Spotless](https://github.com/diffplug/spotless) can enforce things like this but I've never tried to set it up for Maven XML files.

**Comment by daniel-beck** [comment]
@basil Thanks, I was unaware that flag existed!

**Review by daniel-beck — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
There might be merge conflicts, but I am not aware about any pending PR which would be affected significantly.

We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Review by res0nance — APPROVED** [review]

**Pull request merged**
