### PR TITLE
[JENKINS-45438] Add Jetty HTTP/2 connector

### PR DESCRIPTION
**Pull request by olamy**
# Changelog 

* [JENKINS-45438] - Winstone 4.1: Add HTTP/2 Support
* [PR 2937] Winstone 4.1: Add HTTP/2 Jetty connector

### CODE REVIEW

**Comment by olamy** [comment]
need https://github.com/jenkinsci/extras-executable-war/pull/11 and https://github.com/jenkinsci/winstone/pull/39

**Comment by oleg-nenashev** [comment]
@olamy Could you please add a JIRA ticket for HTTP2 support?

**Comment by daniel-beck** [comment]
Better to use dated snapshot versions, everyone can upload these. Unlikely to happen and cause trouble, but still.

**Comment by olamy** [comment]
@oleg-nenashev I changed the description with a link to the jira issue. I'm not sure about the formatting.

**Comment by daniel-beck** [comment]
@olamy Thanks, we'll reformat as needed when copying over to the changelog.

**Comment by oleg-nenashev** [comment]
Executable War has been released: https://github.com/jenkinsci/extras-executable-war/blob/master/CHANGELOG.md#136

**Comment by olamy** [comment]
winstone 4.1 released.

**Review by oleg-nenashev — APPROVED** [review]
👍

**Pull request merged**
