### PR TITLE
Change icon for 'People' task on user profiles

### PR DESCRIPTION
**Pull request by janfaracik**
**Before**
image

**After**
Screenshot 2022-08-17 at 21 25 26

(ignore the hover highlight)

### Proposed changelog entries

* N/A (too small a change)

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")` if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content-Security-Policy directives (see [documentation on jenkins.io](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@jenkinsci/sig-ux 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7006"></a>

### CODE REVIEW

**Comment by timja** [comment]
> There's also a similar link on the user error page, although I'm unsure of how to access this page in a browser so I've left it just in case it's the only way to exit the page - any guidance on this would be grand.

Try change your password on the user configure screen but only fill one input

You get a page with a broken breadcrumb so that would need fixing before removing the sidepanel link I think

image

**Review by timja — APPROVED** [review]
Hmm so I think this is fine to remove as there's not much point in navigating to the people page from here and the people should likely not even be on the main sidebar.

I expect the majority of view of this page is from someone viewing their own profile.

it's a bit weird to click a user from the people page but not have people included in the breadcrumb.

**Review by NotMyFault — APPROVED** [review]

**Comment by NotMyFault** [comment]
The sidepanel on `error.jelly` is the only way to return to the previous page, the breadcrumb is just the generic top level one.
We should keep the reference there, for now.

**Review by daniel-beck — DISMISSED** [review]
"People" isn't a breadcrumb on the user page, so this is akin to #6907 without #6126.

Use a different icon (e.g. the basic "People" icon) instead of the up arrow, and it's a regular navigation item?

**Comment by janfaracik** [comment]
> "People" isn't a breadcrumb on the user page, so this is akin to #6907 without #6126.
> 
> Use a different icon (e.g. the basic "People" icon) instead of the up arrow, and it's a regular navigation item?

I've updated it, thanks for spotting 👍

**Comment by timja** [comment]
Could you update screenshots?

**Comment by janfaracik** [comment]
> Could you update screenshots?

Oops I had them the wrong way around.

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Pull request merged**
