### PR TITLE
Register help icon again

### PR DESCRIPTION
**Pull request by NotMyFault**
The proposed change addresses a regression from the ionicon support PR: https://github.com/jenkinsci/jenkins/pull/6186/files#diff-f58b5cf9ae51828d19d0b7d299430741ba3ee9d4679d6213da61aaea0b3d1540L520-L521

A bunch of plugins actually rely on it, and it used to be a registered icon before.

I've chosen the help outline ionicon, I guess that fits the best, instead of reverting to material icons.

### Proposed changelog entries

* Restore missing help icon (regression in 2.335).

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by timja — APPROVED** [review]
nice

**Comment by MarkEWaite** [comment]
I've confirmed that this fixes the Pipeline syntax image on the sidebar of Pipeline jobs.  Thanks!

## Before (2.335)

screencapture-rhel-8-a-markwaite-net-8080-job-Bugs-Pipeline-Checks-job-bin-bitbucket-job-master-2022-02-17-12_42_24-edit

## After (build of this PR)

screencapture-testing-a-markwaite-net-8080-job-pipeline-2022-02-17-12_43_41-edit

# Other help icons with issues

I was hoping that this change would also resolve the issue I see with the help icon for the Bitbucket Branch Source plugin.  It changes the behavior but does not fully resolve the issue.  Would you prefer a separate issue for this one or should it be considered in the context of this pull request?

## Before (2.335)

before-Screenshot 2022-02-17 124736

## After (build of this PR)

after-Screenshot 2022-02-17 124858

**Review by MarkEWaite — APPROVED** [review]

**Comment by NotMyFault** [comment]
> I was hoping that this change would also resolve the issue I see with the help icon for the Bitbucket Branch Source plugin

Other help icons of the bitbucket plugins look fine, I guess there's somewhere a left reference to the image path in the bitbucket plugin.

**Comment by MarkEWaite** [comment]
This PR is now ready for merge.  We will merge it after approximately 24 hours if there is no negative feedback.

**Comment by NotMyFault** [comment]
One zipgrep later and I found your missing icon, Mark ^^
PR is linked above.

**Pull request merged**
