### PR TITLE
Remove `java.util.concurrent` from `--add-opens` list

### PR DESCRIPTION
**Pull request by basil**
I am not sure why we originally added `--add-opens java.base/java.util.concurrent=ALL-UNNAMED` to the Java 17 preview, but it seems unnecessary in principle (why would we be persisting a concurrent data structure?), and I seem to be able to run a Pipeline job just fine without it locally. So let us see if we can remove this custom directive without any negative side effects.

This PR is in draft state for now as I am not entirely sure this is doable. If the core tests and the plugin BOM tests pass with it removed, then I will mark this as ready for review.

If this PR is successful, I plan to repeat similar exercises for the other `--add-opens` directives until we arrive at the minimal set needed for XStream in the context of Jenkins.

### Proposed changelog entries

N/A

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by basil** [comment]
Core tests passed with the removal of `java.util.concurrent`, and all plugin BOM tests passed except for `workflow-cps-plugin`. I proposed jenkinsci/workflow-cps-plugin#518 to see if we might be able to change that.

**Comment by basil** [comment]
[Successful Java 17 BOM run](https://ci.jenkins.io/job/Tools/job/bom/job/PR-935/21/) with the latest incremental from this PR and the latest incremental from jenkinsci/workflow-cps-plugin#518. I believe this PR is ready for review. It will be ready for merge once jenkinsci/workflow-cps-plugin#518 is merged and released.

**Review by timja — APPROVED** [review]

**Comment by basil** [comment]
https://github.com/jenkinsci/workflow-cps-plugin/pull/518 was released in [2683.vd0a_8f6a_1c263](https://github.com/jenkinsci/workflow-cps-plugin/releases/tag/2683.vd0a_8f6a_1c263), so I am moving this PR out of draft state.

**Comment by basil** [comment]
This PR is now ready for merge. We will merge it after approximately 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process. Thanks!

**Pull request merged**
