### PR TITLE
CLI: Only load a private key if using SSH mode

### PR DESCRIPTION
**Pull request by jeffret-b**
In the CLI library, there are different modes. These days they are SSH and HTTP. Unless the "-noAuthKey" parameter is passed, the CLI program loads a private key if it can. This private key is only useful if the mode is SSH, but it still loads it for HTTP without the extra parameter. This changes it to only load the key for SSH mode.

The current behavior had me really confused recently when using the CLI client. HTTP mode is supposed to be the default but it was asking to load the private key. It appeared that it was always using SSH when it wasn't.

### Proposed changelog entries

* CLI library now only loads a private key if using SSH mode.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [n/a?] JIRA issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
It's difficult to test this change. It's hard to test at this level to begin with and the behavior can be system or user dependent. With the improvement, it would mostly be testing for the nonexistence of something.
- [n/a] For dependency updates: links to external changelogs and, if possible, full diffs

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

### CODE REVIEW

**Comment by alecharp** [comment]
Closing to re-trigger the build.

**Review by fcojfernandez — APPROVED** [review]

**Review by timja — APPROVED** [review]

**Comment by jeffret-b** [comment]
The build failure doesn't seem to be related but I'll trying kicking it again.

**Review by MRamonLeon — APPROVED** [review]

**Comment by timja** [comment]
```

Project ID: org.apache.maven.plugins:maven-clean-plugin
Reason: POM 'org.apache.maven.plugins:maven-clean-plugin' not found in repository: Unable to download the artifact from any repository
  org.apache.maven.plugins:maven-clean-plugin:pom:2.2
from the specified remote repositories:
  central (http://repo1.maven.org/maven2)
```

isn't maven central https only now?

**Comment by timja** [comment]
https://github.com/jenkinsci/jenkins/pull/4435

**Review by res0nance — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
I plan to merge it tomorrow if no negative feedback

**Comment by oleg-nenashev** [comment]
@jeffret-b  if you want to get it backported to LTS, please create a Jenkins Jira ticket

**Comment by oleg-nenashev** [comment]
Also, now er have a merge conflict

**Comment by jeffret-b** [comment]
Jesse did the same thing with a slightly different implementation in the WebSockets change. No reason for this PR now.

**Pull request closed without merging**
