### PR TITLE
Remove unused imports

### PR DESCRIPTION
**Pull request by StefanSpieker**
I noticed that there are a lot of unused imports, especially in the tests and I thought removing them would help a bit. If you think that this just puts noise in the repository you can close the PR.

### Proposed changelog entries

* no changelog entry needed

### CODE REVIEW

**Review by res0nance — APPROVED** [review]
LGTM 👍

**Review by oleg-nenashev — APPROVED** [review]
It might cause some issues with backports, but we should really clean it up at some point. So it is fine to do it now IMHO

**Review by timja — APPROVED** [review]
Should probably look at adding checkstyle to prevent this re-occurring?

**Comment by oleg-nenashev** [comment]
I plan to merge it tomorrow if no negative feedback

**Pull request merged**
