### PR TITLE
Remove unused jenkins-slave.xml file from the Core

### PR DESCRIPTION
**Pull request by tsparber**
The `jenkins-slave.xml` file has been copied to the windows-slave-installer-module,
but a unused (as far as my research goes) (old) copy is still present in the jenkins core.

New file location: [jenkinsci/windows-slave-installer-module: src/main/resources/org/jenkinsci/modules/windows_slave_installer/jenkins-slave.xml](https://github.com/jenkinsci/windows-slave-installer-module/blob/master/src/main/resources/org/jenkinsci/modules/windows_slave_installer/jenkins-slave.xml)

We wanted to modify the default deployed `jenkins-slave.xml` file, but ended up changing the wrong file.

### Proposed changelog entries

* Internal: Remove unused `jenkins-slave.xml` file template from core. This change requires at least version 1.3.1 of the [WMI Windows Agents](https://plugins.jenkins.io/windows-slaves) plugin (Released Mar 14 2017).

### Submitter checklist

- [ ] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
The file is not referenced anywhere in the core source.
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@oleg-nenashev

### CODE REVIEW

**Review by lsarkar — APPROVED** [review]
better to use 'unused' instead of 'unneeded' in the commit message?

**Comment by tsparber** [comment]
> 
> 
> better to use 'unused' instead of 'unneeded' in the commit message?

I've updated the commit message accordingly.

**Comment by oleg-nenashev** [comment]
IIRC old versions of WNI Windows Agents plugin still rely on it. Last time I tried deleting the file, it caused regression reports. But it was about 2 years ago

**Review by timja — APPROVED** [review]

**Comment by StefanSpieker** [comment]
Then it might be a good idea to add the minimum version to the changelog. If I am right, you should have at least Version 1.3.1 of the plugin https://wiki.jenkins.io/display/JENKINS/Windows+Slaves+Plugin

**Review by StefanSpieker — APPROVED** [review]

**Comment by tsparber** [comment]
> Then it might be a good idea to add the minimum version to the changelog. If I am right, you should have at least Version 1.3.1 of the plugin https://wiki.jenkins.io/display/JENKINS/Windows+Slaves+Plugin

I've updated the proposed changelog entry.

**Review by oleg-nenashev — APPROVED** [review]
I am fine with going ahead with this change, the plugin was around for long enough.
It will require mentioning in the upgrade guidelines

**Comment by oleg-nenashev** [comment]
I plan to merge it tomorrow if no negative feedback

**Comment by oleg-nenashev** [comment]
@MarkEWaite @daniel-beck Maybe it is time to introduce a `chore` label for such changes. Changed to `rfe` for now

**Pull request merged**
