### PR TITLE
Remove deprecated `DIR_SEPARATOR` and `LINE_SEPARATOR`

### PR DESCRIPTION
**Pull request by StefanSpieker**
Remove deprecated separator from `IOUtils` which are long available in `org.apache.commons.io.IOUtils`
These fields are unused according to:
* [deprecated-and-unused](https://ci.jenkins.io/job/Reporting/job/deprecated-usage-in-plugins/lastSuccessfulBuild/artifact/output/deprecated-and-unused.html) for `hudson/util/IOUtils#DIR_SEPARATOR_UNIX` and `hudson/util/IOUtils#DIR_SEPARATOR_WINDOWS`
* [usage-by-api](https://ci.jenkins.io/job/Reporting/job/deprecated-usage-in-plugins/lastSuccessfulBuild/artifact/output/usage-by-api.html) for `hudson/util/IOUtils#DIR_SEPARATOR`, `hudson/util/IOUtils#LINE_SEPARATOR`, `hudson/util/IOUtils#LINE_SEPARATOR_UNIX`, `hudson/util/IOUtils#LINE_SEPARATOR_WINDOWS` which is just used by [synopsys-detect-plugin](https://github.com/jenkinsci/synopsys-detect-plugin) and a search in this repo does not find usages.
* The search for whole Jenkins org does not find usages:
   1. [DIR_SEPARATOR](https://github.com/search?q=org%3Ajenkinsci+DIR_SEPARATOR&type=code)
   2. [DIR_SEPARATOR_UNIX](https://github.com/search?q=org%3Ajenkinsci+DIR_SEPARATOR_UNIX&type=code)
   3. [DIR_SEPARATOR_WINDOWS](https://github.com/search?q=org%3Ajenkinsci+DIR_SEPARATOR_WINDOWS&type=code)
   4. [LINE_SEPARATOR_UNIX](https://github.com/search?q=org%3Ajenkinsci+LINE_SEPARATOR_UNIX&type=code)
   5. [LINE_SEPARATOR_WINDOWS](https://github.com/search?q=org%3Ajenkinsci+LINE_SEPARATOR_WINDOWS&type=code)
   6. a little harder to search for [LINE_SEPARATOR](https://github.com/search?q=org%3Ajenkinsci+LINE_SEPARATOR&type=code)

Should I also remove these from the [IOUtils.hint](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/META-INF/upgrade/IOUtils.hint)?

### Testing done

A lot of searching on GitHub

### Proposed changelog entries

- Removed long deprecated `hudson.util.IOUtils#DIR_SEPARATOR`, `hudson.util.IOUtils#DIR_SEPARATOR_WINDOWS`, `hudson.util.IOUtils#DIR_SEPARATOR_UNIX`, `hudson.util.IOUtils#LINE_SEPARATOR`, `hudson.util.IOUtils#LINE_SEPARATOR_WINDOWS` and `hudson.util.IOUtils#LINE_SEPARATOR_UNIX` which are available from `org.apache.commons.io.IOUtils`

### Proposed upgrade guidelines

- Update [Synopsys Detect plugin](https://plugins.jenkins.io/blackduck-detect/) before updating Jenkins

### Submitter checklist

- [x] The Jira issue, if it exists, is well-described.
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7641"></a>

### CODE REVIEW

**Review by NotMyFault — APPROVED** [review]
Thanks!

> Should I also remove these from the [IOUtils.hint](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/META-INF/upgrade/IOUtils.hint)?

I think these should stick around, pointing to the methods to use.

**Review by julien-demaziere — APPROVED** [review]
LGTM

Found no usage of this `IOUtils.LINE_SEPARATOR` according to https://github.com/search?q=org%3Ajenkinsci+IOUtils.LINE_SEPARATOR&type=code

**Comment by basil** [comment]
> I think these should stick around, pointing to the methods to use.

What would be the purpose of retaining these if nothing is consuming them?

**Comment by NotMyFault** [comment]
> > I think these should stick around, pointing to the methods to use.
> 
> What would be the purpose of retaining these if nothing is consuming them?

Can also remove them then @StefanSpieker

**Comment by NotMyFault** [comment]
@StefanSpieker could you remove the leftover hints from https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/META-INF/upgrade/IOUtils.hint, as recommended, please?

**Review by basil — APPROVED** [review]

**Comment by NotMyFault** [comment]
/label ready-for-merge

---

This PR is now ready for merge. We will merge it after ~24 hours if there is no negative feedback.
Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process.
Thanks!

**Pull request merged**
