### PR TITLE
Allow customising call to action color

### PR DESCRIPTION
**Pull request by timja**
See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

The text color on the dark theme has insufficient contrast without allowing to customise it in the call to action, https://github.com/jenkinsci/dark-theme/issues/31

Before:

image

After:

image

### Proposed changelog entries

None, minor follow-up to the css variables PR
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by res0nance — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
I plan to merge it in 24 hours if no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information

**Comment by fqueiruga** [comment]
I have one comment though. Empty state will change in the future, so for now I wouldn't create a new variable just for this, as it will probably be removed on the following months

**Comment by timja** [comment]
> I have one comment though. Empty state will change in the future, so for now I wouldn't create a new variable just for this, as it will probably be removed on the following months

It needs a different variable though as by default it uses 'inherit' which uses `text-color` which doesn't have sufficient contrast on the dark theme against the blue background

Unless you have any other suggestions?

**Comment by fqueiruga** [comment]
We could try setting the same background color as an info alert, or a success banner.

**Comment by timja** [comment]
image

image

See https://github.com/jenkinsci/jenkins/pull/4761/commits/b9620a56aaa2600d7acea0b6f25dcf2baaa11140

**Review by fqueiruga — APPROVED** [review]

**Pull request merged**
