### PR TITLE
Stable 1.651

### PR DESCRIPTION
**Pull request by ge-vi**
Translations mainly for not administrative users.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@ge-vi You should create it against the master branch. There is no plan to release a new 1.651.x LTS, 2.7.1 is a next baseline

**Comment by ge-vi** [comment]
@oleg-nenashev 
I see. So it is best way to "transfer" changes thru patch export?
p.s. I used to work with another SCM so git is kind a new thing...

**Comment by oleg-nenashev** [comment]
@ge-vi Patch export it the most simple way if you don't want to study Git features.
Ib general cherry pick or rebase are preferable.

**Comment by ge-vi** [comment]
@oleg-nenashev thanks for info

**Pull request closed without merging**
