### PR TITLE
Use a jenkins-button at project creation page

### PR DESCRIPTION
**Pull request by NotMyFault**
The title says all; we're on a good way to reduce the overall appearance of standalone yui buttons 🤞🏻 

Before:

Screenshot 2022-09-29 at 23 13 48

Screenshot 2022-09-29 at 23 13 58

After:

Screenshot 2022-09-30 at 00 59 22

Screenshot 2022-09-30 at 00 59 45

### Proposed changelog entries

- Entry 1: Issue, Human-readable Text
- ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  - Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")` if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content-Security-Policy directives (see [documentation on jenkins.io](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7191"></a>

### CODE REVIEW

**Comment by janfaracik** [comment]
Looking good! <3 

Only concern is the button is a bit small, couple of ways to fix it could be -

* Rename the button to 'Create' or something along those lines
* Or - I've added a class in a WIP branch (https://github.com/jenkinsci/jenkins/compare/master...janfaracik:jenkins:new-buttons-2-bottom-bar?expand=1) called `.jenkins-buttons-row--equal-width` which sets a min width on buttons inside of it, could copy the code for that

**Comment by NotMyFault** [comment]
Thanks for the feedback! I went with the first option for now. 'Create' makes more sense, context wise, than the 'OK' surface, given the button actually creates a new project.

**Comment by NotMyFault** [comment]
Thanks for the feedback! I went with option two, looks a lot better, indeed.

**Comment by timja** [comment]
> Rename the button to 'Create' or something along those lines

This is still correct to do but not required in this PR 😄

**Review by timja — APPROVED** [review]
LGTM, tested

**Review by janfaracik — APPROVED** [review]

**Review by yaroslavafenkin — APPROVED** [review]
Tested, LGTM

**Comment by NotMyFault** [comment]
This PR is now ready for merge. We will merge it after ~24 hours if there is no negative feedback.
Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process.
Thanks!

**Comment by NotMyFault** [comment]
> What do you think about using button bar here?

This PR is not about the overall design of an existing component, but rather adapting what is already in place.

**Pull request merged**
