### PR TITLE
Fixed encoding in German translation (log recorder levels)

### PR DESCRIPTION
**Pull request by Jochen-A-Fuerbacher**
This pull request fixes some encoding issues in the German translation of the log recorder.

### Proposed changelog entries

* Fixed encoding in German translation

### CODE REVIEW

**Comment by daniel-beck** [comment]
Caused by https://github.com/jenkinsci/jenkins/commit/ed8d905c2c3cdf8e68b3100c9521891761ef359e by @LinuxSuRen two months ago.

Possible further regressions:
https://github.com/jenkinsci/jenkins/commit/ed8d905c2c3cdf8e68b3100c9521891761ef359e#diff-23aff0cec966ec8a194fa73d98e9108bR25
https://github.com/jenkinsci/jenkins/commit/ed8d905c2c3cdf8e68b3100c9521891761ef359e#diff-23aff0cec966ec8a194fa73d98e9108bR28
https://github.com/jenkinsci/jenkins/commit/ed8d905c2c3cdf8e68b3100c9521891761ef359e#diff-a33f9b534fc3bbddcf319f95f6cb1a01R7

**Comment by daniel-beck** [comment]
Beyond these, only some old pt_BR translations contain U+FFFD, or �, which should probably not be a legal character in properties files to begin with.

**Comment by daniel-beck** [comment]
@Jochen-A-Fuerbacher While you're at it, could you address the other regressions I linked to above?

**Comment by LinuxSuRen** [comment]
@Jochen-A-Fuerbacher Please let me know if something is wrong because of my modified.

**Comment by daniel-beck** [comment]
@Jochen-A-Fuerbacher Thanks 🎉

**Review by daniel-beck — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
@Jochen-A-Fuerbacher thanks a lot!
@LinuxSuRen no worries, it happens sometimes.

**Pull request merged**
