### PR TITLE
[JENKINS-55292] Remove MailCommand localization from core

### PR DESCRIPTION
**Pull request by daniel-beck**
See [JENKINS-55292](https://issues.jenkins-ci.org/browse/JENKINS-55292).

Supersedes https://github.com/jenkinsci/jenkins/pull/3819

### Proposed changelog entries

* Bug: Remove Mailer related localized strings from core. Make sure you use Mailer Plugin 1.23 or newer.

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [n/a] Appropriate autotests or explanation to why this change has no tests
- [n/a] For dependency updates: links to external changelogs and, if possible, full diffs

### CODE REVIEW

**Review by batmat — APPROVED** [review]
`git grep MailCommand` on the tip of this PR yields nothing anymore, so OK I guess?

**Review by batmat — APPROVED** [review]
LGTM provided build goes green?

**Review by MRamonLeon — APPROVED** [review]
A bit of cleaning up is always welcome :heart_eyes:

**Review by Wadeck — APPROVED** [review]

**Comment by daniel-beck** [comment]
I wonder whether this would justify an upgrade of the bundled plugin version for detachment when upgrading from before 1.493, since users might have a bit of a bad time until explicitly upgrading otherwise (e.g. CLI help command will fail).

**Review by alecharp — APPROVED** [review]

**Comment by batmat** [comment]
Are you saying you're concerned by users upgrading from Jenkins < 1.493?

If so, I guess a changelog entry is enough, as they're likely anyway to have other more pressing issues than that, and I wouldn't over-complicate here for instances that didn't update for so long?

**Comment by daniel-beck** [comment]
@batmat 

> Are you saying you're concerned by users upgrading from Jenkins < 1.493?

Sort of. Not as much as I'd be concerned introducing other problems on more relevant configurations by just increasing the bundled version. Still something we should explicitly be OK with.

**Comment by batmat** [comment]
Now I _think_ I understand your concern. Well anyway an instance upgrading from very old baseline like 1.4xx (or even 1.5xx) I would expect to go steps by steps, and also switch to using LTSes, so I wouldn't worry about these really.

**Pull request merged**
