### PR TITLE
[WiP] First draft of providing categorisation of Item types in Jenkins

### PR DESCRIPTION
**Pull request by rsandell**

### CODE REVIEW

**Comment by rsandell** [comment]
@jenkinsci/code-reviewers @reviewbybees @recena @amuniz

**Comment by rsandell** [comment]
I realized today that it's probably the ItemDescriptors that are the interesting thing to ask the category about, not an instance of Item, since it's primary intended for the new item screen.

**Comment by recena** [comment]
@rsandell Right, I'll send a PR today. I was talking about it (`ItemDescriptors`) with other teammates.

**Comment by rsandell** [comment]
Continued on another fork by @recena

**Pull request closed without merging**
