### PR TITLE
Add getter for temp offline cause of nodes for plugins

### PR DESCRIPTION
**Pull request by tploss**
See [JENKINS-67964](https://issues.jenkins-ci.org/browse/JENKINS-67964).

No tests for this since it is a one line getter.

### Proposed changelog entries

N/A

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade -> none of the mentioned in this PR
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [x] For dependency updates: links to external changelogs and, if possible, full diffs -> N/A

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by tploss** [comment]
This PR is similar to https://github.com/jenkinsci/jenkins/pull/6152 (from a topic perspective) but may present less opportunities for controversy since it is much smaller and makes zero changes to the current API.

**Review by timja — APPROVED** [review]

**Review by basil — COMMENTED** [review]
I think our usual policy for API additions (and a sound policy for API additions in general) is to review both the proposed new API and the proposed consumer of the new API together.

The reason for this is that the foundation of good API design is covering both current and future use cases (see slide 7 of Joshua Bloch's "[How to Design a Good API and Why it Matters](http://www.cs.bc.edu/~muller/teaching/cs102/s06/lib/pdf/api-design)"). Without seeing a consumer, it is difficult to evaluate how well a proposed new API satisfies even current use cases, let alone future ones. With a consumer in mind, one can evaluate how the proposed new API satisfies existing use cases with an eye toward future use cases.

The motivation for the new API is explained in [JENKINS-67964](https://issues.jenkins.io/browse/JENKINS-67964):

> When creating plugins that handle node availability it is necessary to access a node's [`temporaryOfflineCause`](https://issues.jenkins.io/browse/JENKINS-67964#L268) so that it can be examined (e.g. to find out which user set it etc.). This can be easily done if the node is still connected (== still has a channel) but if another `OfflineCause` is set (e.g. because of a connection termination) it is impossible to retrieve the `temporaryOfflineCause` set previously using a `Computer`'s [`getOfflineCause`](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Computer.java#L360) method which is the only method available to retrieve `OfflineCause`s.

This is certainly helpful context, but I think even more helpful would be a PR that demonstrates how this new API would be consumed. That way, reviewers could see the end result and judge how well the proposed API solves the problem at hand with an eye toward future use cases as well.

**Comment by tploss** [comment]
I fully agree that it is good practice to keep the consumer of the API in mind. 👍 
Since the plugin for which this functionality is necessary is closed source within my company I sadly cannot share any snippets from there directly but I can definitely explain the usage a bit better:

Scenario
1. We have a Jenkins system with multiple nodes connected to it
2. We have colleagues that are mainly responsible for these nodes. This also means investigating any issues that come up. 
3. We have a plugin that automatically manages when nodes should be online or temp offline since they aren't completely ready yet

Problem
1. Node admin wants to investigate an issue on a node.
2. Node admin sets node temp offline with some message
3. Node connection breaks, resulting in an error + new offlinecause for the node
4. At some random time: Our plugin kicks in and checks whether the node is "ready" to be set online (based on some web services etc.)
5. Since the plugin cannot access the temp offline message it is impossible to find out whether this node was set temp offline by a node admin and should therefore not be brought online.

Solution
1. Node offers public getter for temp offline cause
2. Plugin gets temp offline cause and performs its own checks on whether this can be overwritten or not


I hope this helps in understanding the use of this new public method.

**Comment by alecharp** [comment]
@tploss could it be possible that an OSS plugin have a use for this new API as well? I'm sure your need is not unique and could benefit another plugin. I understand we are asking to do an extra mile here, on something you and your company might not benefit directly, but the community might. Your use case is really interesting.

**Comment by tploss** [comment]
@alecharp, I don't think I fully understand what you want me to do here. Could you please rephrase if there is something you would want me to do to improve this PR?

**Comment by tploss** [comment]
@basil Anything still standing in the way of approval?

**Review by basil — APPROVED** [review]

**Comment by alecharp** [comment]
@tploss sorry, it's me that didn't understand enough your explanation.

**Pull request merged**
