### PR TITLE
[FIXED JENKINS-12379] Allow specifying a context for archiving

### PR DESCRIPTION
**Pull request by daniel-beck**
**Please provide feedback**: What's a user-friendly name for this new option? _Search Context_ seems weird but I cannot think of anything better.

---

Possible unexpected side effect is that the fingerprinted path to files is also relative to the search context. I think it makes sense to have it mirror the structure of the archived artifacts.

---

Screenshots of the new option and form validation below. Note that some minor wording changes have occurred since these screenshots were taken.

**Trying to escape the workspace**:

> screen shot 2014-12-20 at 17 32 25

---

**Workspace exists, but specified context does not**:

> screen shot 2014-12-20 at 17 31 42

---

**Existing validation for artifact pattern (and suggestion) recognizes current value of context**:

> screen shot 2014-12-20 at 17 31 24

---

**Input can be validated based on workspace contents**:

> screen shot 2014-12-20 at 17 31 34

### CODE REVIEW

**Comment by daniel-beck** [comment]
The interest in this feature (and the presence in Teamcity according to the issue description) indicates this is something users want to have.

I'd like to have it myself to not have to add silly batch/shell build steps for copying files around (very basic operations), increasing the complexity of my job configurations disproportionally. In the case of jobs that may roam between Windows and Linux nodes (e.g. Ant or Gradle plugin based builds), this isn't that straightforward to add either.

**Comment by jglick** [comment]
But again it could be handled in the Copy Artifacts plugin without patching core; just an alternative to the “flatten” mode.

**Comment by daniel-beck** [comment]
@jglick Any changes in Copy Artifact will only affect access from that build step. Users as well as automated agents accessing build artifacts directly will not benefit from that.

The issue this is attempting to resolve clearly shows user demand for this feature:
https://issues.jenkins-ci.org/browse/JENKINS-12379

**Comment by ericLemanissier** [comment]
+1 for this feature. It's a very common case to have compiled binaries in a subfolder of the workspace (build, bin, whatever the name). It makes no sense to archive the folder itself.
Implementing this in Copy Artifact pluggin is not an option, as user may want to download the artifact archive.

**Comment by Marqo09** [comment]
I'd also +1 this feature specifically for the purpose of creating more concise build artifacts. Modifying the Copy Artifact would not satisfy my needs as these artifacts are directly used for easy distribution of beta releases.

As for @daniel-beck's implementation, I'd be interested to see how it handles archiving multiple "Files to archive" when a "Search Context" is specified. E.g.,

Files to archive: jenkins.war, **/jenkins.zip, **/jenkins.jar
Search Context: target
Directory Structure:
    target/jenkins.war
    target/dist/jenkins.zip
    foo/bar/jenkins.jar

I imagine I'd probably end up with an archive that contains jenkins.war, dist/jenkins.zip, and would not include jenkins.jar (assuming this change simply modifies the archive working directory to the specified "target" directory).

Although I'd love to have a feature capable of generating a single archive with just the jenkins.war, jenkins.zip, and jenkins.jar files give the above setup, I'd still be quite content with the fantastic work done by @daniel-beck. 

As a final note, if the magic under the hood is only fixing up the current working directory of where to perform the search from, I'd like to suggest the name "Archive Working Directory" over "Search Context".

Thank you again for this great feature and I look forward to seeing this pull request make it into the core.

**Comment by jzee** [comment]
+1 - this is so very crucial! Thanks for making it happen!

**Comment by kodayashi** [comment]
+1 as well! As for naming, I've seen the term "Base Path" used before (NuGet I believe), where this simply means "the base path specified will be the root of the archive."

**Comment by oleg-nenashev** [comment]
:+1: 
@daniel-beck , what's the status of this PR? It also needs a merge with amaster

**Comment by daniel-beck** [comment]
@oleg-nenashev Thanks for the reminder. I'll try to fix it up this week.

**Comment by daniel-beck** [comment]
Superseded by #1878.

**Pull request closed without merging**
