### PR TITLE
small fixes

### PR DESCRIPTION
**Pull request by jhonDoe15**
### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7198"></a>

### CODE REVIEW

**Review by NotMyFault — COMMENTED** [review]
Hey,

thanks for the PR. I'd recommend to stick to "grammar fixes", as your commit message implies, and revert the other stuff.
The try to try-with-resource cleanup and the other code changes don't really fit into that category.

**Comment by jhonDoe15** [comment]
Hi!
thanks for the feedback, I'd really like to keep that even with a separate commit given its such a shame to keep that troublesome code smell

**Comment by jhonDoe15** [comment]
all fixed!

**Comment by jhonDoe15** [comment]
I'd love some advice @NotMyFault . I've seen some notab;e usage of spotBugs NonNull annotation preceded with a nullity check (usually for method parameters), could lombok NonNull or a custom annotation to preform the nullity check be a better and more concise solution in your opinion?
this is an example from the source for reference
```
    protected ParameterDefinition(@NonNull String name) {
        if (name == null) {
            throw new IllegalArgumentException("Parameter name must be non-null");
        }
        this.name = name;
    }
```

**Review by NotMyFault — CHANGES_REQUESTED** [review]
As much as I appreciate any kinds of contribution, I don't think the changes presented get us anywhere.
What you label as 'code smell' is our checkstyle, and I'd recommend to not change it, nor is there a net benefit in renaming random variables.

Generally, we try to keep PRs focused on a specific topic, to facilitate an easy and fast review process, rather than throwing a bunch of random changes in a single PR.

**Comment by jhonDoe15** [comment]
I see, how'd you seperate this pr? didn't want to flud with unnecessary PR's is why I did it as such

**Comment by NotMyFault** [comment]
I'd recommend picking a specific topic you want to focus on. For example, if you want to address a few typos, the PR should only be about that.

Code changes typically require some technically debt and justification.

**Comment by jhonDoe15** [comment]
even if one would refactor the code to make it simpler and less proun to bugs (like when using try with resources)?

**Comment by jhonDoe15** [comment]
I'm closing this PR as it has come not relevant as before and opening a different one just for the agreed language fixes.

I would like however to get an answer to the previous comment to make better PR next time, thanks again

**Comment by MarkEWaite** [comment]
> > Code changes typically require some technically debt and justification.
>
> even if one would refactor the code to make it simpler and less proun to bugs (like when using try with resources)?

Pull requests are welcomed that make the code simpler and less prone to bugs, specifically using try with resources.  Some previous examples include:

* #6765 
* #5680
* #5568
* #4361

I'm less confident in changes that rename arguments in methods because I'm not sure if that will affect references to that method that may exist in jelly files.

**Pull request closed without merging**
