### PR TITLE
Add snakeyaml to war dependencies

### PR DESCRIPTION
**Pull request by almariah**
### Proposed changelog entries

* add snakeyaml to WAR dependencies to allow parsing YAML files in groovy scripts and pipeline scripts.

### Submitter checklist

- [ ] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@jenkinsci/code-reviewers

### CODE REVIEW

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
@almariah It has to be done via a plugin if it is needed.
The request seems to be a version of https://issues.jenkins-ci.org/browse/JENKINS-19401 IIUC

**Comment by oleg-nenashev** [comment]
Examples of such API plugins:

* https://github.com/jenkinsci/apache-httpcomponents-client-4-api-plugin/
* https://github.com/jenkinsci/jquery-plugin
* https://github.com/jenkinsci/bouncycastle-api-plugin
* etc.

**Comment by oleg-nenashev** [comment]
Another approach would be to install a plugin which already bundles this library: https://github.com/search?l=Maven+POM&q=org%3Ajenkinsci+snakeyaml&type=Code . In such case you won't need to write/modify any code

**Comment by almariah** [comment]
@oleg-nenashev Hi,
Thanks for you suggestions. It is nice to have a support for YAML files for many reasons. One of them to be able to configure jenkins using init.groovy script before even installation of any plugin or using it for installation a list of plugins in YMAL files. The YAML file is modern way for doing that. Usage of `garp` does't work for missing plugins dependencies.

**Comment by oleg-nenashev** [comment]
@almariah I think you may be interested to take a look at https://github.com/jenkinsci/configuration-as-code-plugin (has not been released yet). It uses YAML for configuration, and yes, it bundles Snake YAML.

Actually `init.groovy` scripts run when the plugins are already loaded, so it will have YAML if a plugin bundles it

**Review by svanoort — CHANGES_REQUESTED** [review]
I second closing this -- dependencies should only be added to core when new functionality can't be accomplished by plugins.  Otherwise it's too easy to creep into a dependency mess or end up with conflicting versions causing issues.

**Comment by oleg-nenashev** [comment]
Closing this PR according to the discussion.
@almariah if you are not satisfied by the responses, let us know

**Pull request closed without merging**
