### PR TITLE
Add a disabled status to the REST API for AbstractProject job types

### PR DESCRIPTION
**Pull request by daniel-beck**
### Proposed changelog entries

* Add the boolean `disabled` flag to applicable jobs' REST API output for classic project types like Freestyle, Maven, or Multi-configuration (Matrix).

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] JIRA issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
It looks good to me, but should it be done on the `Job` level instead? I know that the disabled API has not been fully generalized yet, but maybe it's time to do so. No problem if we keep it oit of the scope

**Review by Wadeck — APPROVED** [review]
Not manually tested but seems fine.

**Review by oleg-nenashev — APPROVED** [review]
I added an Explicit AbstractProject reference to the suggested changelog, and I believe it can be integrated in the current state. I plan to merge it tomorrow if no negative feedback

**Comment by daniel-beck** [comment]
> AbstractProject reference to the suggested changelog

The changelog is for Jenkins users, not Jenkins developers. I suggest you find a different way to describe this.

**Comment by oleg-nenashev** [comment]
@daniel-beck I am open to your suggestions. We have never had a good user-friendly term for AbstractProject

**Comment by daniel-beck** [comment]
"classic project types like Freestyle, Maven, or Multi-configuration (Matrix)."

**Comment by oleg-nenashev** [comment]
I plan to merge it tomorrow if no negative feedback

**Comment by oleg-nenashev** [comment]
Will merge, because it is a trivial change

**Pull request merged**
