### PR TITLE
Now that packaging is in https://github.com/jenkinsci/packaging and give...

### PR DESCRIPTION
**Pull request by stephenc**
...n that the ips packaging is stale, we should just drop this

@reviewbybees

### CODE REVIEW

**Comment by jtnord** [comment]
:+1:  it's not offered as a package on http://jenkins-ci.org and no-one has volunteered to update it.

**Comment by jglick** [comment]
I thought I had already asked @kohsuke to move `ips/` to `jenkinsci/packaging` and he had acknowledged. Maybe he forgot?

**Comment by daniel-beck** [comment]
We decided to stop providing Solaris packages, so what's the point?

**Comment by stephenc** [comment]
Exactly. It's not like we are purging this code from the git repo and rewriting the entire history to ensure it is purged. People can easily go back to a tag if someone steps up to take ownership... and anyway they would want to move it over to the `packaging` repo if they were picking up support for this

**Comment by jtnord** [comment]
This is missing changes to [war/pom.xml](https://github.com/jenkinsci/jenkins/blob/master/war/pom.xml#L518-L542) to remove the ips profile

**Comment by stephenc** [comment]
@jtnord not any more ;-)

**Comment by jtnord** [comment]
:+1:

**Comment by oleg-nenashev** [comment]
:+1: 
Noting is required IMO

**Comment by KostyaSha** [comment]
Finally repo will have clean structure :+1:

**Comment by kohsuke** [comment]
Note that it's not the packaging that's stale, it's the infra that serves the packages that are currently dropped.

I've imporeted the history into the packaging repository.

**Pull request merged**
