### PR TITLE
[JENKINS-59964] redirect to setOfflineCause

### PR DESCRIPTION
**Pull request by mawinter69**
in case an agent is already temporarily offline redirect to the
page that updates the offline reason when going to ../<computer>/markOffline

See [JENKINS-59964](https://issues.jenkins-ci.org/browse/JENKINS-59964).

### Proposed changelog entries

* Redirect agent's `mark offline` dialog to updating the offline reason when the agent is already offline

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
"and actually trigger it back online when hitting the "Mark offline" submit button." from the issue description likely depends on the agent implementation. I would consider it a separate defect.

Nevertheless, it looks like a nice UX enhancement, regardless of the underlying bug

**Comment by mawinter69** [comment]
It fixes the described issue for agent implementations in core. If it doesn't work for other agents implemented in plugins then this must be fixed in those plugins I think.

**Review by NotMyFault — APPROVED** [review]
Works well, though I'm not sure when this is actually needed unless you access the page via the URL.

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Pull request merged**
