### PR TITLE
[FIXED JENKINS-28086][FIXED JENKINS-28289] Update remoting version to 2.55

### PR DESCRIPTION
**Pull request by olivergondza**
[JENKINS-28289](https://issues.jenkins-ci.org/browse/JENKINS-28289)
[JENKINS-28086](https://issues.jenkins-ci.org/browse/JENKINS-28086)

### CODE REVIEW

**Comment by batmat** [comment]
:+1:

**Comment by olivergondza** [comment]
There are tests failures that needs to be looked at

**Comment by oleg-nenashev** [comment]
Yes, the test failures are related

**Comment by kohsuke** [comment]
See https://github.com/jenkinsci/remoting/pull/78 where the further fix is being worked on.

I suggest we close this in favor of #2010

**Comment by olivergondza** [comment]
Ack

**Pull request closed without merging**
