### PR TITLE
[JENKINS-73744] npm scripts `lint:fix` do not work

### PR DESCRIPTION
**Pull request by scherler**
See [JENKINS-73744](https://issues.jenkins.io/browse/JENKINS-73744).

### Proposed changelog entries

- human-readable text

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Review by basil — CHANGES_REQUESTED** [review]
Previously: [JENKINS-71021](https://issues.jenkins.io/browse/JENKINS-71021), #9615.

Fails interactive testing. Steps to reproduce are as follows: intentionally introduce a violation to `core/src/main/resources/lib/form/password/password.js`, then run `mvn clean verify -DskipTests`.

```javascript
diff --git a/core/src/main/resources/lib/form/password/password.js b/core/src/main/resources/lib/form/password/password.js
index 4cd33dbfc6..70d24f77db 100644
--- a/core/src/main/resources/lib/form/password/password.js
+++ b/core/src/main/resources/lib/form/password/password.js
@@ -28,9 +28,8 @@ Behaviour.specify(
   0,
   function (e) {
     var secretUpdateBtn = e.querySelector(".hidden-password-update-btn");
-    if (secretUpdateBtn === null) {
+    if (secretUpdateBtn === null)
       return;
-    }
 
     secretUpdateBtn.onclick = function () {
       e.querySelector(".hidden-password-field").setAttribute(
```

Before this PR, the `yarn lint:ci` portion of the Maven build fails, and running `yarn lint` as documented in `CONTRIBUTING.md` fails with

```
core/src/main/resources/lib/form/password/password.js
  32:7  error  Expected { after 'if' condition  curly

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

After this PR, the `yarn lint:ci` portion of the Maven build (erroneously!) succeeds, and running `yarn lint` as documented in `CONTRIBUTING.md` (erroneously!) passes. This is a regression.

**Comment by timja** [comment]
FWIW the instructions in https://github.com/jenkinsci/jenkins/pull/9615 do work but something is wrong as the local project yarn should be picked up, I'm not sure why the PATH workaround is needed.

**Comment by scherler** [comment]
@basil thanks for pointing out, lemme investigate how https://github.com/jenkinsci/jenkins/pull/9615/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R58 could be prevented since that is not something you want to have to do working with `yarn` I wonder whether it makes sense to move the whole npm to the root folder since it has to cover 2 subfolder but maybe there is a reason not to do so. Further I wonder why `js` is kept in `core` and not in `war` which would be another possible solution.

**Comment by scherler** [comment]
BTW I tried the workaround 
image
...but that did not work

**Comment by scherler** [comment]
@basil @timja https://github.com/jenkinsci/jenkins/pull/9718 one thing I am unsure is to use `env.CI` to use `lint:fix` and if not set `lint` so we get back the stack trace

**Comment by basil** [comment]
> use `env.CI` to use `lint:fix` and if not set `lint` so we get back the stack trace

As suggestged in https://github.com/jenkinsci/jenkins/pull/6948#issuecomment-1201565247.

**Pull request closed without merging**
