### PR TITLE
Serbian [sr] translation of properties files

### PR DESCRIPTION
**Pull request by ghost**
Jelly view files to follow.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers I doubt we have people, who can review this change.
@rtyler Maybe the call on Twitter / dev/user ML?

**Comment by imod** [comment]
I doubt anyone will care to validate translations done with cyrillic unicode codes...

**Comment by oleg-nenashev** [comment]
@imod As a happy Cyrillic language speaker, I commonly checkout Russian translation PRs and then review them in an editor, which shows such properties properly.

**Comment by imod** [comment]
@oleg-nenashev I guess I just did not know that there is an easy way to do it :)

**Comment by daniel-beck** [comment]
@lksndr To clarify, do you plan to amend this PR, or is it mergeable as-is and you will file further PRs?

**Comment by lksndr** [comment]
@daniel-beck It's mergeable; additional work would be in a subsequent PR.
@imod This functionality is available in IDEA under File->Settings->Editor->File Encodings->Transparent native-to-ascii conversion, and I'm sure in other editors as well.

**Comment by daniel-beck** [comment]
:+1: A superficial check of the translations back to English indicates sane translations, except some domain specific terms Google has a problem with. I think that's all we can do here.

**Comment by imod** [comment]
👍  @lksndr, cool I did not know about it

**Comment by oleg-nenashev** [comment]
Retriggering the PR build, but 👍 from me.

**Pull request merged**
