### PR TITLE
Add Chinese translation

### PR DESCRIPTION
**Pull request by LinuxSuRen**
About view, job and user ... Chinese translation

### CODE REVIEW

**Review by daniel-beck — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers just in case somebody speaks Chinese

**Comment by oleg-nenashev** [comment]
@LinuxSuRen are you still working on the changes? If yes, please let us know when it's ready.

**Comment by LinuxSuRen** [comment]
it is already done

**Comment by oleg-nenashev** [comment]
Ack, ready to merge then

**Pull request merged**
