### PR TITLE
Use different job status balls for disabled and never built jobs

### PR DESCRIPTION
**Pull request by Ka-Wing**
See [JENKINS-22931](https://issues.jenkins-ci.org/browse/JENKINS-22931).

### Proposed changelog entries

* Entry 1: Disabled builds icon changed from gray to orange.

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### CODE REVIEW

**Comment by daniel-beck** [comment]
I mean, sure, it looks different now from 'not built', so technically achieves the stated goal, but what's 'disabled' about the color orange?

Grey before was useful because it's frequently used for disabled UI. Unfortunately, we overload it to mean 'indeterminate' (i.e. not built) as well.

But orange?

**Review by daniel-beck — CHANGES_REQUESTED** [review]
This does not change the other icon sizes, so is incomplete (beyond concerns about color choice).

**Comment by daniel-beck** [comment]
Regarding color blindness compatibility, this doesn't seem to exactly improve the situation. Particularly not for users of Green Balls Plugin (assuming there's no special icons for disabled/not built/aborted.

screen shot

**Comment by ashes999** [comment]
I wrote the initial Jenkins request for this. As I recommended, why not use something simple, light a light grey and a (very) dark grey? Why do we need to introduce another colour (especially if colour blindness is an issue we need to work around)?

**Comment by fedefiorini** [comment]
Okay, thanks for feedback! We thought that orange for "disabled" would have meant that it has been disabled for a reason similar to bugs or whatever, we didn't consider color blindness and we are now aware of it. 

We're going to fix it using a different grey tone.

**Comment by ashes999** [comment]
@fedefiorini I'm not an expert on usability, but I can suggest one thing: there are tools out there to measure contrast (as well as tools to simulate colour blindness). I would suggest trying these to make sure that the two colours look distinct enough without users, say, squinting at the screen.

Either that, or you could add some sort of additional icon or something (eg. an X) for the disabled jobs. But that would break consistency with all the other icons...

**Comment by oleg-nenashev** [comment]
The proposed color says nothing to me. If we really want to help color-blind people, why do we stick to empty balls at all? Maybe we could put some ~partyparrots~ graphics there. E.g. here are quick prototypes for the disabled button:

disabled 2
disabled

**Comment by daniel-beck** [comment]
Agree, we're at the limit of what colors can do. A question mark perhaps for 'not build', an 'X' for aborted?

**Comment by Ka-Wing** [comment]
There is an exlamation mark inside the gray orb. Would this be a good idea? For which status would this be useful? 

grey

**Comment by oleg-nenashev** [comment]
Among available options I would prefer the "pause" symbol (see above)

**Comment by daniel-beck** [comment]
@Ka-Wing 

> There is an exlamation mark inside the gray orb. Would this be a good idea? For which status would this be useful?

If you have to ask this question, it's probably not a good symbol.

**Comment by recena** [comment]
In case that my opinion is considered, I don't like this proposal. I don't see the benefit.

**Comment by Ka-Wing** [comment]
@recena Of course your opinion matters. Can you eleborate why you don't see the benefit and what should be done instead in your opinion?

**Comment by oleg-nenashev** [comment]
Just for the record, I totally support making the change to allow distinguishing 2 states. It is a small improvement, but why not?

**Comment by itsjohno** [comment]
This has been a relatively large pain point for me recently when migrating from one Jenkins box to another, and running a Groovy script to disable all jobs. I'd really like to see a way to distinguish between "not built" and "disabled".

I think I'm in agreement with @oleg-nenashev, the pause symbol on the grey orb for disabled builds strikes me as the best solution here and doesn't muddy the water by adding another colour.

**Comment by recena** [comment]
I don't have strong opinion +0

**Comment by oleg-nenashev** [comment]
> I think I'm in agreement with @oleg-nenashev, the pause symbol on the grey orb for disabled builds strikes me as the best solution here and doesn't muddy the water by adding another colour.

It may become tricky if Jenkins Pipeline adds support of "Pause" at some point (there are such requests in JIRA). But we will be able to change symbols later if it's needed, because Pause in Pipeline will require adding such job state in the core.

If somebody proposes a PR with animated icons for "pause", I think we will be able to get it merged

**Comment by daniel-beck** [comment]
@Ka-Wing Do you have plans to finish this?

**Comment by Ka-Wing** [comment]
Yes, I'll try to finish this soon.

**Comment by oleg-nenashev** [comment]
@Ka-Wing OK, we are waiting for the update here

**Comment by daniel-beck** [comment]
I have to go back a bit on what I wrote here last year.

> Agree, we're at the limit of what colors can do.

While it seems tempting to go for the easy fix here, we should consider the overall presentation of all the build status icons in Jenkins. Adding symbols to some but not all of the icons seems to be a hack solution.

Instead, I would like to put forward another suggestion:

We're currently overloading "grey" with two meanings: Disabled, and never built.

Can we go with a (possibly darker) grey for disabled, and a very light grey / white(ish) for 'never built'? The orbs seem to have a darker border, so it hopefully wouldn't look "just" white.

Unfortunately I lack the skills to implement this myself to see how it looks, so there's a high likelihood this proposal will turn out terribly.

I look forward to seeing a good solution here, even if it ends up being different from what I suggest here.

**Comment by JeanChristopheMorinPerso** [comment]
And what about a gray ball with three dots in it when it's never built (so pending) and the same grey when it's disabled? I am myself a color blind and adding other colors would make things slightly more difficult. Sometimes the difference between two grey can become quite small.

I Like what @oleg-nenashev came up with in https://github.com/jenkinsci/jenkins/pull/3320#issuecomment-369871869, though I wouldn't use the pause symbol for not yet built jobs (I would keep it for a really paused job).

Something like:
pending or pending_dark for the pending ones. What do you guys think?

**Comment by daniel-beck** [comment]
I was thinking something along these lines:

Aborted:
aborted

Never built:
new
or perhaps even
new2

The brightness difference alone should (hopefully) make this accessible. Some concern with the very bright one might be that it could be difficult to tell building/animated from not building/static.

**Comment by daniel-beck** [comment]
I would also like to note that the https://ci.jenkins.io/legend page will need updating in this PR: It would no longer show an identical looking icon for both _disabled_ and _new_ projects.

**Comment by daniel-beck** [comment]
I was looking into this some more in an attempt to provide an alternative proposal as outlined in https://github.com/jenkinsci/jenkins/pull/3320#issuecomment-480643744.

Looking through our resources I noticed we ship different sizes (unsurprising, corresponding to list view icon sizes) and discovered that this PR in its current form only changes the specific 32x32 size.

Beyond that, I would ask that any modifications would be done to the original SVG source files in https://github.com/jenkinsci/jenkins/tree/master/war/images and/or the conversion scripts, to allow us to e.g. scale them up in the future.

I created https://github.com/jenkinsci/jenkins/pull/3997 as an alternative, implementing my suggestion from https://github.com/jenkinsci/jenkins/pull/3320#issuecomment-480643744. It's a bit different since there's actually three states (new, aborted, and disabled) currently appearing grey, not just two as discussed here.

**Comment by daniel-beck** [comment]
No matter where this proposal is going (i.e. which variant ultimately makes it), this PR needs a lot of work. There hasn't been a response from @Ka-Wing in more than three months, so I'm closing this for general housekeeping. This isn't a rejection, I welcome you to submit a new PR addressing some or the recent review comments here.

It might perhaps be best to base a future re-submission off #3996 (which has a fixed `legend` view and a few other internal changes), and just replace all the assets.

**Pull request closed without merging**
