### PR TITLE
[JENKINS-67846] Icon alignment of build status is wrong

### PR DESCRIPTION
**Pull request by frankie139506**
See [JENKINS-67846](https://issues.jenkins.io/browse/JENKINS-67846).
Before
image

After
image

### Proposed changelog entries

* Fix build status position.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] (If applicable) Jira issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [X] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

### CODE REVIEW

**Review by alecharp — COMMENTED** [review]
Tested locally with `core-pr-tester` and building github.com/alecharp/simple-app with `mvn verify -Dmaven.test.skip checkstyle:checkstyle`. I used Warnings-ng to display checkstyle results. 

It's solving the problem (vertical aligment) but I find the icon and the text to be too close. Some spacing could be added. This is highly personal, I do not want to block this pull request for this.

**Comment by frankie139506** [comment]
> Tested locally with `core-pr-tester` and building github.com/alecharp/simple-app with `mvn verify -Dmaven.test.skip checkstyle:checkstyle`. I used Warnings-ng to display checkstyle results.
> 
> It's solving the problem (vertical aligment) but I find the icon and the text to be too close. Some spacing could be added. This is highly personal, I do not want to block this pull request for this.

I have already fixed it. Please take a look at it.
image

**Review by alecharp — APPROVED** [review]
Thank you @frankie139506. This looks great. I couldn't not find any regression with this in my test.

**Review by basil — COMMENTED** [review]
This PR does not contain an evaluation of the cause of the problem. Without an evaluation of the cause of the problem, we cannot determine whether the proposed solution addresses the cause of the problem or merely one of its symptoms. What caused this regression, and what makes us confident such a regression will not occur again in the future?

**Comment by alecharp** [comment]
I found out this was introduced by https://issues.jenkins.io/browse/JENKINS-67515 and [jenkinsci/jenkins#6162](https://github.com/jenkinsci/jenkins/pull/6162). It's present since 2.329.

**Comment by alecharp** [comment]
@frankie139506 could you please address Basil comments on this pull request? Thank you.

**Comment by alecharp** [comment]
I checked https://issues.jenkins.io/browse/JENKINS-68356 (as caused by https://issues.jenkins.io/browse/JENKINS-67515) and this pull request doesn't break its fix.

**Review by basil — APPROVED** [review]
@frankie139506 After some consideration, I decided to accept this PR as-is, but in the future I will insist on a written evaluation of the root cause of the problem and an explanation of how the proposed PR addressed the root cause.

--

This PR is now ready for merge. We will merge it after approximately 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process. Thanks!

**Pull request merged**
