### PR TITLE
Use the scalable SVG logo over the PNG

### PR DESCRIPTION
**Pull request by janfaracik**
Use the SVG version of the Jenkins text logo instead of the PNG, removes the PNG file from the codebase

### Screenshots

**Old**
image

**New**
image

### Proposed changelog entries

* Use the SVG version of the Jenkins text logo instead of the PNG

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
- [ ] Appropriate autotests or explanation to why this change has no tests

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
I am definitely +1 for that. Not sure what was the reason to NOT reference SVG. Is it browser compatibility @fqueiruga @timja ?

Maybe we should also check references to the logo. It was publicly exposed as HTTP resource, so just removing it may have side effects.

**Review by fqueiruga — APPROVED** [review]
Can't remember why it's still like this. My only suggestion is to verify that it does indeed work in IE11. Cheers!

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
> Maybe we should also check references to the logo. It was publicly exposed as HTTP resource, so just removing it may have side effects.

better that people use other sources if so, quite unlikely they would use this anyway

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Review by res0nance — APPROVED** [review]
Tested on IE11 Seems to work fine
image

**Pull request merged**
