### PR TITLE
Call hpi:record-core-location

### PR DESCRIPTION
**Pull request by jglick**
Downstream change matching https://github.com/jenkinsci/maven-hpi-plugin/pull/25.

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
May take a different approach in the upstream PR.

**Comment by kohsuke** [comment]
Trivially :bee:

**Comment by oleg-nenashev** [comment]
https://github.com/jenkinsci/maven-hpi-plugin/pull/25 has not been integrated yet

**Comment by jglick** [comment]
@kohsuke also requests this be documented [here](https://wiki.jenkins-ci.org/display/JENKINS/Extend+Jenkins) or similar.

**Comment by jglick** [comment]
```
java.net.SocketException: Broken pipe
	at jenkins.security.Security232Test.commonsCollections1(Security232Test.java:85)
```

looks like a flake.

**Review by KostyaSha — APPROVED** [review]

**Comment by abayer** [comment]
:bee:

**Pull request merged**
