### PR TITLE
Center textbox names vertically

### PR DESCRIPTION
**Pull request by Carbenium**
This PR replaces #1871

### CODE REVIEW

**Comment by recena** [comment]
@Carbenium Please, fill a JIRA issue to describe what do you want to do, to resolve, to improve...

**Comment by recena** [comment]
@Carbenium Please, provide a screenshot with before/after result.

**Comment by Carbenium** [comment]
Before | After
---------------------|-----------------------
 |

**Comment by recena** [comment]
@Carbenium What web browser did you use to take this screenshot?

**Comment by Carbenium** [comment]
@recent The screenshot was taken with Firefox 42.0

**Comment by recena** [comment]
@Carbenium I'll try it with different environments (browsers + O.S.9

**Comment by jtnord** [comment]
FWICT this also changes labels applied to TextAreas which makes this change a little ugly IMO.

**Comment by recena** [comment]
@jtnord Exactly. For that, I want to try it and find possible solutions. I don't know why Jenkins UI doesn't use YUI Form components in a right way.

**Comment by daniel-beck** [comment]
If this centers the label for text areas, it would introduce an undesirable behavior there for a minor visual gain on single-line text boxes.

**Comment by oleg-nenashev** [comment]
@daniel-beck @recena 
Seems it makes sense to close it if @Carbenium does not plan to finalize it

**Comment by daniel-beck** [comment]
Agreed.

@Carbenium If you're still interested in making this happen, please file a new PR on top of the current 2.x master, and demonstrate that multiline text areas aren't negatively affected.

**Comment by recena** [comment]
Agreed.

**Pull request closed without merging**
