### PR TITLE
[Jenkins-16750] Update build status icon

### PR DESCRIPTION
**Pull request by zbynek**
See [JENKINS-16750](https://issues.jenkins-ci.org/browse/JENKINS-16750).

### Proposed changelog entries

* Update status icon of a build when the build is finished

### Submitter checklist

- [x ] JIRA issue is well described
- [x ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [n/a ] Appropriate autotests or explanation to why this change has no tests
- [n/a ] For dependency updates: links to external changelogs and, if possible, full diffs

### CODE REVIEW

**Review by varyvol — APPROVED** [review]

**Comment by zbynek** [comment]
There is a little screen recording (using the green balls plugin, the patch itself does not affect color)
jenkins-icon
I would like to ask for some feedback: is there some interest in getting this merged? If yes, how can I help?

**Comment by daniel-beck** [comment]
> is there some interest in getting this merged?

@zbynek Speaking for myself, absolutely! This particular behavior has been bugging me for a long time. It's just in an area I don't have a lot of experience with (JS) so review is a lot more effort.

**Review by halkeye — COMMENTED** [review]
Is document.querySelector used in other places? I'm not sure off hand of its safe to use compatibility wise. Wouldn't the $$ function be safer?

**Comment by jvz** [comment]
> Is document.querySelector used in other places? I'm not sure off hand of its safe to use compatibility wise. Wouldn't the $$ function be safer?

https://caniuse.com/#search=queryselector

Works in damn near everything. I've used it in some other JS code in Jenkins and plugins.

**Review by halkeye — APPROVED** [review]
:+1: i just wasn't sure where jenkins drew the line between newness and supporting extreme old

**Review by oleg-nenashev — APPROVED** [review]
Thanks @zbynek ! I do not see anything wrong in the implementation though I am not a JavaScript developer. Assuming that @halkeye 's 👍 means "approved", I am fine with merging it

**Comment by oleg-nenashev** [comment]
Will land it in the weekly if there is no negative feedback

**Review by halkeye — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Ignoring CI failure, because it is caused by external INFRA issue. See https://issues.jenkins-ci.org/browse/INFRA-2086

**Pull request merged**
