### PR TITLE
Merge 2.319 security fixes back into master

### PR DESCRIPTION
**Pull request by daniel-beck**
Trial PR to see whether this builds on CI. If it does, I'll push to `master` directly.

Meanwhile, 2.319 is at https://github.com/jenkinsci/jenkins/releases/tag/jenkins-2.319

### CODE REVIEW

**Review by jglick — APPROVED** [review]

**Comment by jglick** [comment]
> I'll push to `master` directly.

Why not simply merge this PR?

**Comment by daniel-beck** [comment]
Passed enough (some sort of ATH infra failure?)

**Comment by timja** [comment]
> Passed enough (some sort of ATH infra failure?)

Not infra, can be reproduced locally, appears to be security regression: https://issues.jenkins.io/browse/JENKINS-67063?focusedCommentId=415616&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-415616

**Comment by jglick** [comment]
I think a `deleteDir()` before https://github.com/jenkins-infra/pipeline-library/blob/4fd036d1da36d5dc9313d6f048b1f67f82cb0a3b/vars/runATH.groovy#L97 may solve it. Something weird with symlinks.

**Comment by timja** [comment]
gets past it locally for me

**Comment by jglick** [comment]
https://github.com/jenkinsci/jenkins/blob/d563512c97a471396fdbe3d8958ff9fcf3bcbec1/core/src/main/java/hudson/FilePath.java#L2840 is wrong I think. Trying to figure out how this should work instead.

**Comment by timja** [comment]
the `deleteDir` has unblocked ATH

**Comment by jglick** [comment]
check #5886

**Pull request merged**
