### PR TITLE
Removed superflous throws

### PR DESCRIPTION
**Pull request by StefanSpieker**
Removed superflous throws. Just limited on hudson test namespace to somehow limit the scope.

### Proposed changelog entries

* N/A

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by Wadeck — APPROVED** [review]
@StefanSpieker Thanks for the contribution 🚀  (it will count for Hacktoberfest ^^)

Could you tell me how do you find some of the unnecessary throws? I tried with IntelliJ to find CustomPluginManagerTest the useless throws but it was happy with it. And removing it does not trigger compiler error neither.
Perhaps you are using another IDE (I saw https://youtrack.jetbrains.com/issue/IDEA-76934)

I didn't check every method but as it's mainly about tests, if they are still passing, that's a sufficient signal 👍

**Comment by Wadeck** [comment]
:x: Errors due to new import enforcer rule.

<details>

<pre>
[2021-10-01T13:30:05.031Z] Caused by: org.apache.maven.plugin.MojoExecutionException: The following files had format violations:
[2021-10-01T13:30:05.031Z]     src/test/java/hudson/slaves/NodePropertyTest.java
[2021-10-01T13:30:05.031Z]         @@ -10,7 +10,6 @@
[2021-10-01T13:30:05.031Z]          import·com.gargoylesoftware.htmlunit.html.HtmlForm;
[2021-10-01T13:30:05.031Z]          import·com.gargoylesoftware.htmlunit.html.HtmlLabel;
[2021-10-01T13:30:05.031Z]          import·hudson.model.Descriptor;
[2021-10-01T13:30:05.031Z]         -import·hudson.model.Descriptor.FormException;
[2021-10-01T13:30:05.031Z]          import·hudson.model.Slave;
[2021-10-01T13:30:05.031Z]          import·java.util.logging.Level;
[2021-10-01T13:30:05.031Z]          import·net.sf.json.JSONObject;
[2021-10-01T13:30:05.031Z]     src/test/java/hudson/model/queue/BuildKeepsRunningWhenFaultySubTasksTest.java
[2021-10-01T13:30:05.031Z]         @@ -10,7 +10,6 @@
[2021-10-01T13:30:05.031Z]          import·hudson.model.Node;
[2021-10-01T13:30:05.031Z]          import·hudson.model.Queue;
[2021-10-01T13:30:05.031Z]          import·hudson.model.ResourceList;
[2021-10-01T13:30:05.031Z]         -import·java.io.IOException;
[2021-10-01T13:30:05.031Z]          import·java.util.Collection;
[2021-10-01T13:30:05.031Z]          import·java.util.Collections;
[2021-10-01T13:30:05.031Z]          import·java.util.concurrent.TimeUnit;
[2021-10-01T13:30:05.031Z]     src/test/java/hudson/model/DescriptorTest.java
[2021-10-01T13:30:05.031Z]         @@ -36,7 +36,6 @@
[2021-10-01T13:30:05.031Z]          import·hudson.tasks.BuildStepDescriptor
[2021-10-01T13:30:05.031Z]          import·hudson.tasks.Builder;
[2021-10-01T13:30:05.031Z]          import·hudson.tasks.Shell;
[2021-10-01T13:30:05.031Z]         -import·java.io.IOException;
[2021-10-01T13:30:05.031Z]          import·java.util.Arrays;
[2021-10-01T13:30:05.031Z]          import·java.util.List;
[2021-10-01T13:30:05.031Z]          import·java.util.concurrent.Callable;
[2021-10-01T13:30:05.031Z]     src/test/java/hudson/model/labels/LabelExpressionTest.java
[2021-10-01T13:30:05.031Z]         @@ -43,7 +43,6 @@
[2021-10-01T13:30:05.031Z]          import·hudson.model.Node.Mode;
[2021-10-01T13:30:05.031Z]          import·hudson.slaves.DumbSlave;
[2021-10-01T13:30:05.031Z]          import·hudson.slaves.RetentionStrategy;
[2021-10-01T13:30:05.031Z]         -import·java.io.IOException;
[2021-10-01T13:30:05.031Z]          import·java.lang.reflect.Field;
[2021-10-01T13:30:05.031Z]          import·java.util.Collections;
[2021-10-01T13:30:05.031Z]          import·java.util.Set;
[2021-10-01T13:30:05.031Z]     src/test/java/hudson/model/UserIdMigratorTest.java
[2021-10-01T13:30:05.031Z]         @@ -26,10 +26,8 @@
[2021-10-01T13:30:05.031Z]          import·static·org.hamcrest.CoreMatchers.is;
[2021-10-01T13:30:05.031Z]          import·static·org.hamcrest.MatcherAssert.assertThat;
[2021-10-01T13:30:05.031Z]          
[2021-10-01T13:30:05.031Z]         -import·java.io.IOException;
[2021-10-01T13:30:05.031Z]          import·org.junit.Rule;
[2021-10-01T13:30:05.031Z]          import·org.junit.Test;
[2021-10-01T13:30:05.031Z]         -import·org.jvnet.hudson.reactor.ReactorException;
[2021-10-01T13:30:05.031Z]          import·org.jvnet.hudson.test.JenkinsRule;
[2021-10-01T13:30:05.031Z]          import·org.jvnet.hudson.test.recipes.LocalData;
[2021-10-01T13:30:05.031Z]          
[2021-10-01T13:30:05.031Z]     src/test/java/hudson/model/UpdateSiteTest.java
[2021-10-01T13:30:05.031Z]         @@ -46,7 +46,6 @@
[2021-10-01T13:30:05.031Z]          import·java.util.List;
[2021-10-01T13:30:05.031Z]          import·java.util.jar.Attributes;
[2021-10-01T13:30:05.031Z]     ... (5 more lines that didn't fit)
[2021-10-01T13:30:05.031Z] Violations also present in 13 other files.
[2021-10-01T13:30:05.031Z] Run 'mvn spotless:apply' to fix these violations.
</pre>

</details>

**Comment by StefanSpieker** [comment]
@Wadeck I'm using IntelliJ for that, you can just use this analyzer. right-click on the project you want to scan, than inspect code and edit the project default inspection profile. There you can search for _redundant throws_
grafik
If you deselct everything but this, it will be quite fast. In the problems window just mark all issues and apply the refactoring.

And then don't forget to run `spotless:apply` ... thanks for pointing that out.

**Comment by Wadeck** [comment]
@StefanSpieker thanks for the confirmation.
I didn't expect to have to run manually the analysis to get this result. Some other inspections are done automatically, hence my confusion. Compared to other inspections, it does not seem to run automatically in background, I think the linked ticket from previous comment is the reason.

**Review by basil — APPROVED** [review]
This PR is now ready for merge. We will merge it after approximately 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process. Thanks!

**Pull request merged**
