### PR TITLE
[JENKINS-60857] - Update Winstone to 5.8 in the 2.204.x baseline

### PR DESCRIPTION
**Pull request by oleg-nenashev**
See [JENKINS-60857](https://issues.jenkins-ci.org/browse/JENKINS-60857). We missed this regression during the LTS backporting and verification.

### Proposed changelog entries

* * Fix a _KeyStores with multiple certificates are not supported_ error from Jetty when passing certain kinds of certificates, such as domain wildcards (regression in 2.217)
  * Changelog: https://github.com/jenkinsci/winstone/releases/tag/winstone-5.8

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [x] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [x] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [x] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by olivergondza** [comment]
Did we managed to verify this is fixing the issue?

**Comment by timja** [comment]
Yes - https://issues.jenkins-ci.org/browse/JENKINS-60857?focusedCommentId=383816&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-383816

**Comment by oleg-nenashev** [comment]
@olivergondza Yes. We had exactly the same issue in the Weekly 🤦‍♂

**Review by raul-arabaolaza — APPROVED** [review]

**Review by olivergondza — APPROVED** [review]
I approve these changes and I also agree with out-of-cycle .4 to get this out

**Comment by oleg-nenashev** [comment]
I will contact @kohsuke to get a release today if the build passes

**Comment by sfransen** [comment]
is this fixed in the release that was today as my jenkins is dead and will not launch in the 2.204.3 LTS

`$ cat failed-boot-attempts.txt
Mon Mar 02 08:01:43 PST 2020
Mon Mar 02 08:08:07 PST 2020
Mon Mar 02 08:08:54 PST 2020
Mon Mar 02 08:35:52 PST 2020
Mon Mar 02 08:37:10 PST 2020
Mon Mar 02 08:40:31 PST 2020
Mon Mar 02 08:42:34 PST 2020
Mon Mar 02 08:44:01 PST 2020
Mon Mar 02 08:46:54 PST 2020
Mon Mar 02 08:47:53 PST 2020
Mon Mar 02 08:56:15 PST 2020


[08:58:31] root@mtjenkins01/var/lib/jenkins
$ cat /var/log/jenkins/jenkins.log
Running from: /usr/lib/jenkins/jenkins.war
2020-03-02 16:56:15.111+0000 [id=1] WARNING winstone.Logger#logInternal: Parameter handlerCountMax is now deprecated
2020-03-02 16:56:15.127+0000 [id=1] WARNING winstone.Logger#logInternal: Parameter handlerCountMaxIdle is now deprecated
2020-03-02 16:56:15.132+0000 [id=1] INFO   org.eclipse.jetty.util.log.Log#initialized: Logging initialized @498ms to org.eclipse.jetty.util.log.JavaUtilLog
2020-03-02 16:56:15.179+0000 [id=1] INFO   winstone.Logger#logInternal: Beginning extraction from war file
2020-03-02 16:56:15.207+0000 [id=1] WARNING o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath
2020-03-02 16:56:15.412+0000 [id=1] INFO   winstone.Logger#logInternal: Exclude Ciphers [^.*_(MD5|SHA|SHA1)$, ^TLS_RSA_.*$, ^SSL_.*$, ^.*_NULL_.*$, ^.*_anon_.*$]
2020-03-02 16:56:15.438+0000 [id=1] INFO   org.eclipse.jetty.server.Server#doStart: jetty-9.4.25.v20191220; built: 2019-12-20T17:00:00.294Z; git: a9729c7e7f33a459d2616a8f9e9ba8a90f432e95; jvm 1.8.0_222-b10
2020-03-02 16:56:15.645+0000 [id=1] INFO   o.e.j.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2020-03-02 16:56:15.679+0000 [id=1] INFO   o.e.j.s.s.DefaultSessionIdManager#doStart: DefaultSessionIdManager workerName=node0
2020-03-02 16:56:15.679+0000 [id=1] INFO   o.e.j.s.s.DefaultSessionIdManager#doStart: No SessionScavenger set, using defaults
2020-03-02 16:56:15.681+0000 [id=1] INFO   o.e.j.server.session.HouseKeeper#startScavenging: node0 Scavenging every 660000ms
2020-03-02 16:56:15.967+0000 [id=1] INFO   hudson.WebAppMain#contextInitialized: Jenkins home directory: /var/lib/jenkins found at: SystemProperties.getProperty("JENKINS_HOME")
2020-03-02 16:56:16.038+0000 [id=1] INFO   o.e.j.s.handler.ContextHandler#doStart: Started w.@2a7ed1f{Jenkins v2.204.3,/,file:///var/cache/jenkins/war/,AVAILABLE}{/var/cache/jenkins/war}
2020-03-02 16:56:16.084+0000 [id=1] INFO   o.e.j.util.ssl.SslContextFactory#load: x509=X509@463fd068(mtcoveritydb01,h=[],w=[]) for SslContextFactory@895e367[provider=null,keyStore=null,trustStore=null]
2020-03-02 16:56:16.084+0000 [id=1] INFO   o.e.j.util.ssl.SslContextFactory#load: x509=X509@1b266842(starfieldclass2ca,h=[],w=[]) for SslContextFactory@895e367[provider=null,keyStore=null,trustStore=null]
2020-03-02 16:56:16.085+0000 [id=1] INFO   o.e.j.util.ssl.SslContextFactory#load: x509=X509@7a3793c7(taiwangrca,h=[],w=[]) for SslContextFactory@895e367[provider=null,keyStore=null,trustStore=null]
2020-03-02 16:56:16.085+0000 [id=1] INFO   o.e.j.util.ssl.SslContextFactory#load: x509=X509@42b3b079(itservices.def.com,h=[gaalpa2adssrv53.itservices.def.com, itservices.def.com, gaalpa2adssrv53, itservices, its-ad-ldap.it.xxx.com, its-ad-ldap.lrns.def.com, its-ad-ldap.cci.xxx.com],w=[]) for SslContextFactory@895e367[provider=null,keyStore=null,trustStore=null]
2020-03-02 16:56:16.086+0000 [id=1] INFO   o.e.j.util.ssl.SslContextFactory#load: x509=X509@651aed93(geotrustglobalca,h=[],w=[]) for SslContextFactory@895e367[provider=null,keyStore=null,trustStore=null]
2020-03-02 16:56:16.086+0000 [id=1] INFO   o.e.j.util.ssl.SslContextFactory#load: x509=X509@4dd6fd0a(1,h=[mtjenkins01.quantum.xxx.com],w=[]) for SslContextFactory@895e367[provider=null,keyStore=null,trustStore=null]
2020-03-02 16:56:16.087+0000 [id=1] INFO   o.e.j.util.ssl.SslContextFactory#load: x509=X509@bb9e6dc(verisignclass3publicprimarycertificationauthority-g3,h=[],w=[]) for SslContextFactory@895e367[provider=null,keyStore=null,trustStore=null]
2020-03-02 16:56:16.087+0000 [id=1] INFO   o.e.j.util.ssl.SslContextFactory#load: x509=X509@5456afaa(godaddyclass2ca,h=[],w=[]) for SslContextFactory@895e367[provider=null,keyStore=null,trustStore=null]
2020-03-02 16:56:16.088+0000 [id=1] INFO   o.e.j.util.ssl.SslContextFactory#load: x509=X509@6692b6c6(trustisfpsrootca,h=[],w=[]) for SslContextFactory@895e367[provider=null,keyStore=null,trustStore=null]
2020-03-02 16:56:16.088+0000 [id=1] INFO   o.e.j.util.ssl.SslContextFactory#load: x509=X509@1cd629b3(epkirootcertificationauthority,h=[],w=[]) for SslContextFactory@895e367[provider=null,keyStore=null,trustStore=null]
2020-03-02 16:56:16.092+0000 [id=1] INFO   o.e.j.server.AbstractConnector#doStop: Stopped ServerConnector@5702b3b1{SSL,[ssl, http/1.1]}{0.0.0.0:8443}
2020-03-02 16:56:16.092+0000 [id=1] INFO   o.e.j.server.session.HouseKeeper#stopScavenging: node0 Stopped scavenging
2020-03-02 16:56:16.094+0000 [id=1] INFO   hudson.WebAppMain#contextDestroyed: Shutting down a Jenkins instance that was still starting up
java.lang.Throwable: reason
       at hudson.WebAppMain.contextDestroyed(WebAppMain.java:388)
       at org.eclipse.jetty.server.handler.ContextHandler.callContextDestroyed(ContextHandler.java:937)
       at org.eclipse.jetty.servlet.ServletContextHandler.callContextDestroyed(ServletContextHandler.java:565)
       at org.eclipse.jetty.server.handler.ContextHandler.stopContext(ContextHandler.java:905)
       at org.eclipse.jetty.servlet.ServletContextHandler.stopContext(ServletContextHandler.java:367)
       at org.eclipse.jetty.webapp.WebAppContext.stopWebapp(WebAppContext.java:1450)
       at org.eclipse.jetty.webapp.WebAppContext.stopContext(WebAppContext.java:1415)
       at org.eclipse.jetty.server.handler.ContextHandler.doStop(ContextHandler.java:980)
       at org.eclipse.jetty.servlet.ServletContextHandler.doStop(ServletContextHandler.java:284)
       at org.eclipse.jetty.webapp.WebAppContext.doStop(WebAppContext.java:547)
       at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:93)
       at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:180)
       at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:201)
       at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:111)
       at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:93)
       at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:180)
       at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:201)
       at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:111)
       at org.eclipse.jetty.server.Server.doStop(Server.java:454)
       at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:93)
       at winstone.Launcher.shutdown(Launcher.java:311)
       at winstone.Launcher.<init>(Launcher.java:202)
       at winstone.Launcher.main(Launcher.java:362)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:498)
       at Main._main(Main.java:375)
       at Main.main(Main.java:151)
2020-03-02 16:56:16.097+0000 [id=1] INFO   o.e.j.s.handler.ContextHandler#doStop: Stopped w.@2a7ed1f{Jenkins v2.204.3,/,null,UNAVAILABLE}{/var/cache/jenkins/war}
Exception in thread "Jenkins initialization thread" java.lang.NoClassDefFoundError: hudson/util/HudsonFailedToLoad
       at hudson.WebAppMain$3.run(WebAppMain.java:247)
Caused by: java.lang.ClassNotFoundException: hudson.util.HudsonFailedToLoad
       at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
       at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:543)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
       ... 1 more
2020-03-02 16:56:16.097+0000 [id=1] INFO   winstone.Logger#logInternal: Jetty shutdown successfully
java.io.IOException: Failed to start Jetty
       at winstone.Launcher.<init>(Launcher.java:191)
       at winstone.Launcher.main(Launcher.java:362)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:498)
       at Main._main(Main.java:375)
       at Main.main(Main.java:151)
Caused by: java.lang.IllegalStateException: KeyStores with multiple certificates are not supported on the base class org.eclipse.jetty.util.ssl.SslContextFactory. (Use org.eclipse.jetty.util.ssl.SslContextFactory$Server or org.eclipse.jetty.util.ssl.SslContextFactory$Client instead)
       at org.eclipse.jetty.util.ssl.SslContextFactory.newSniX509ExtendedKeyManager(SslContextFactory.java:1275)
       at org.eclipse.jetty.util.ssl.SslContextFactory.getKeyManagers(SslContextFactory.java:1256)
       at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:374)
       at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:245)
       at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
       at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
       at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
       at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:92)
       at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
       at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
       at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
       at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:320)
       at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
       at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:231)
       at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
       at org.eclipse.jetty.server.Server.doStart(Server.java:385)
       at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
       at winstone.Launcher.<init>(Launcher.java:189)
       ... 7 more
2020-03-02 16:56:16.098+0000 [id=1] SEVERE winstone.Logger#logInternal: Container startup failed
java.lang.IllegalStateException: KeyStores with multiple certificates are not supported on the base class org.eclipse.jetty.util.ssl.SslContextFactory. (Use org.eclipse.jetty.util.ssl.SslContextFactory$Server or org.eclipse.jetty.util.ssl.SslContextFactory$Client instead)
       at org.eclipse.jetty.util.ssl.SslContextFactory.newSniX509ExtendedKeyManager(SslContextFactory.java:1275)
       at org.eclipse.jetty.util.ssl.SslContextFactory.getKeyManagers(SslContextFactory.java:1256)
       at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:374)
       at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:245)
       at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
       at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
       at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
       at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:92)
       at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
       at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
       at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
       at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:320)
       at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
       at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:231)
       at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
       at org.eclipse.jetty.server.Server.doStart(Server.java:385)
       at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
       at winstone.Launcher.<init>(Launcher.java:189)
Caused: java.io.IOException: Failed to start Jetty
       at winstone.Launcher.<init>(Launcher.java:191)
       at winstone.Launcher.main(Launcher.java:362)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:498)
       at Main._main(Main.java:375)
       at Main.main(Main.java:151)
[08:58:55] root@mtjenkins01/var/lib/jenkins

 `

**Comment by timja** [comment]
not released yet afaik https://updates.jenkins.io/stable-2.204/latestCore.txt

**Comment by itzikbekel** [comment]
same here, still not working on 2.204.3

**Comment by itzikbekel** [comment]
> not released yet afaik https://updates.jenkins.io/stable-2.204/latestCore.txt

it means we can use this until it released? because I downloaded the jenkins.war from this link, execute it and got the same issue.

**Comment by timja** [comment]
You need 2.204.4, which isn't released yet, that link will be updated when it has been

**Comment by MarkEWaite** [comment]
Or you can use 2.204.2.

**Pull request merged**
