### PR TITLE
[CID-1251490] Using invalid iterator (INVALIDATE_ITERATOR)

### PR DESCRIPTION
**Pull request by KostyaSha**
invalid_loop: Attempting to obtain another element from items.keySet() after it's been modified.

Reviewing analysing reports. Does such fix valid?

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
No, the fix does not resolve the problem. In this code Jenkins splits items cleanup into a separate thread, so the issue may appear during the concurrent modification in this thread and on a new Executable.

The spawned thread should be synchronized with Jenkins instance to resolve the issue

**Comment by jtnord** [comment]
@oleg-nenashev I'm failing to see how the original code ever worked correctly unless we only ever removed the last item from the keySet. (what happens when you remove an item from a set and are itterating is non-deterministic and could cause items to be skipped etc..)
Hence the code change looks good to me - however I have not jumped into the code of CopyOnWriteMap

**Comment by KostyaSha** [comment]
There are some other places where iteration+remove is done in such way. I looked at CopyOnWriteMap but it ends in generic interfaces. 

@jtnord could you look at CopyOnWriteMap?

**Comment by KostyaSha** [comment]
Wrote a test case and `CopyOnWriteMap.Tree` works without error. 

Closing.

**Pull request closed without merging**
