### PR TITLE
[FIXED JENKINS-31219] A CloudProvisioningListener can prevent provisi…

### PR DESCRIPTION
**Pull request by stephenc**
…oning of all clouds instead of just the targeted cloud

See [JENKINS-31219](https://issues.jenkins-ci.org/browse/JENKINS-31219)

@reviewbybees

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
:bee:

**Comment by KostyaSha** [comment]
:+1: Test case of course will be welcome >_<

**Comment by jglick** [comment]
:bee: though I would love to see a test.

**Comment by stephenc** [comment]
@reviewbybees done (testing this is hard)

**Comment by KostyaSha** [comment]
@stephenc create 2 test clouds + test listener that will touch some file, run and verify?

**Comment by stephenc** [comment]
@KostyaSha not quite, you have to set up a listener that will refuse provisioning from the first cloud and permit provisioning from the second and then verify that a node gets provisioned from the second cloud while ensuring that the listener is only objecting to the first cloud... writing a test that actually is not going to give false positives for a 1 line change that is correct on code inspection seems like a large amount of overkill... if people really feel strongly about it then fair enough, but so far I've only seen "nice to have"

**Comment by KostyaSha** [comment]
If second cloud receive this job, then it works :) At least this case will be covered. Better to have 1 test rather than nothing. No need in running the whole slave, should be enough to mark with files. 
Without tests jenkins will never end fighting with bugs imho.

**Comment by oleg-nenashev** [comment]
Retriggering CI

**Pull request merged**
