### PR TITLE
Update the design of the copy button

### PR DESCRIPTION
**Pull request by janfaracik**
**Before**
image

**After**

https://user-images.githubusercontent.com/43062514/175719843-b92a46c2-3b0e-4bb5-beee-e874158e20e8.mov

**What's changed**
* Uses the `.jenkins-button` class instead of `YUI`
* Uses a new `ionicon` inspired icon with an animation
* Component attributes tidied
  * `message` is no longer required, sensible values are set for `message` and `tooltip` by default
  * `style` attribute removed, inline styles are not recommended/shouldn't be encouraged
*  Revoke API token button uses a `trash` icon - this looked out of place without updating this as well

<details>
<summary>Revoke API token</summary>

Before

After
image

</details>

### Proposed changelog entries

* Copy button design updated

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@jenkinsci/sig-ux 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/6698"></a>

### CODE REVIEW

**Review by NotMyFault — COMMENTED** [review]
Any specific reason why we don't use a more clipboard looking-like icon? I feel that would be more suitable than two squares, no? 🤔

**Comment by timja** [comment]
> Any specific reason why we don't use a more clipboard looking-like icon? I feel that would be more suitable than two squares, no? 🤔

https://graphicdesign.stackexchange.com/questions/132106/what-is-the-most-intuitive-and-obvious-copy-link-icon

and from a google images search looking at what others do:

image

I think it works but it does make the API token generator look wrong as the revoke token icon is out of place:

image

**Comment by NotMyFault** [comment]
> > Any specific reason why we don't use a more clipboard looking-like icon? I feel that would be more suitable than two squares, no? 🤔
> 
> https://graphicdesign.stackexchange.com/questions/132106/what-is-the-most-intuitive-and-obvious-copy-link-icon
> 
> and from a google images search looking at what others do:
> 
> image
> 

Right, I was thinking of the existing clipboard icon in place. Felt that was more intuitive to get used to.

**Comment by janfaracik** [comment]
> Any specific reason why we don't use a more clipboard looking-like icon? I feel that would be more suitable than two squares, no? 🤔

I was just following the ionicons copy icon. I've updated it a touch now to look more like a file and less of a square - 

image

> I think it works but it does make the API token generator look wrong as the revoke token icon is out of place:
> 
> image

I'll take a look into that.

**Comment by NotMyFault** [comment]
> I was just following the ionicons copy icon. I've updated it a touch now to look more like a file and less of a square -

Thanks a bunch. UI wise does my button look a bit different from yours on your screenshot, the outline is cut off:

https://user-images.githubusercontent.com/13383509/176019237-4ce77b05-6544-4934-9f28-76bc2566ae17.mp4

Currently testing on Chrome 103 on MacOS, Safari is fine 🥴

**Comment by janfaracik** [comment]
> > I was just following the ionicons copy icon. I've updated it a touch now to look more like a file and less of a square -
> 
> Thanks a bunch. UI wise does my button look a bit different from yours on your screenshot, the outline is cut off:
> 
>  Kapture.2022-06-27.at.21.19.56.mp4 
> 
> Currently testing on Chrome 103 on MacOS, Safari is fine 🥴

I can't seem to reproduce that :/ Running Chrome 103 on macOS on a 13 inch MacBook Pro at standard res. Are your scaling settings non-default by any chance?

image

**Comment by NotMyFault** [comment]
> I can't seem to reproduce that :/ Running Chrome 103 on macOS on a 13 inch MacBook Pro at standard res. Are your scaling settings non-default by any chance?

Oddly enough, I can't seem to replicate that anymore and I don't recall changing anything, seems to be all good now.

**Review by NotMyFault — APPROVED** [review]

**Review by timja — APPROVED** [review]

**Review by daniel-beck — COMMENTED** [review]
Half of the PR seems unrelated to the stated purpose?

**Comment by daniel-beck** [comment]
Having two tooltips like in the video looks really weird.

**Comment by daniel-beck** [comment]
Ah OK, the initial PR comment is outdated then. I was confused when reviewing the code. Might not be worth adding a changelog entry though.

**Comment by timja** [comment]
> the initial PR comment is outdated then

Updated, I've left the changelog entry alone.

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Comment by jglick** [comment]
This PR completely broke the copy button for me in Firefox 109.0 on Linux. (I verified that it is broken in the PR merge commit, and working in the parent. Had to backport https://github.com/jenkinsci/jenkins/pull/5824#discussion_r730301674 to be able to build old versions with current Yarn.)

* The icon does not select when the mouse is directly over the icon. Can be worked around by moving to the very top of the icon.
* But then even when I do manage to click it, it just throws an error (and does not copy anything):
```
Uncaught TypeError: navigator.clipboard is undefined
    <anonymous> …/jenkins/adjuncts/…/lib/layout/copyButton/copyButton.js:18
```

Same problems on Chromium 109.0.5414.74 except the stack trace reporting is slightly different:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
    at HTMLButtonElement.<anonymous> (copyButton.js:18:25)
```

https://user-images.githubusercontent.com/154109/213590341-c61ed5ec-bac3-4839-90e0-bd2812fa6265.mp4

**Pull request merged**
