### PR TITLE
[JENKINS-36282] Add support to cc.xml for exporting jobs in folders recursively

### PR DESCRIPTION
**Pull request by dwnusbaum**
See [JENKINS-36282](https://issues.jenkins-ci.org/browse/JENKINS-36282).

This duplicates jenkinsci/cctray-xml-plugin#1 so that the fix can be made without waiting on cc.xml to be split from core.

The recursive behavior only activates if you access cc.xml with a query parameter named `recursive`, in case anyone relies on the current behavior. If that seems unlikely, I can make the recursive behavior the default.

### Proposed changelog entries

* Enable cc.xml to export jobs in folders recursively when accessed with a query parameter named <code>recursive</code>.

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@reviewbybees

### CODE REVIEW

**Review by daniel-beck — COMMENTED** [review]
This should just be converted into a Groovy view.

**Comment by dwnusbaum** [comment]
I've converted it into a Groovy view, but I'm not clear on how to get Stapler to map it correctly. Right now it has to be accessed by going to `http://host/jenkins/cc.xml.groovy`. I'll look through the [Stapler docs](http://stapler.kohsuke.org/reference.html) more to figure out how to fix it, but if anyone has a quick pointer to fix it please let me know.

**Comment by dwnusbaum** [comment]
@daniel-beck It looks like a groovy view with a '.' in the name has to be accessed at 'foo.bar.groovy'. A workaround would be to do what cctray-xml-plugin does and add an `Action` so that the view is in `index.groovy`, but then it seems like it would make sense to add the complex logic to the `Action` and keep the same jelly view.

For now I moved the logic into a function in `hudson.Functions` so that cc.xml.jelly stays simple and we don't have to add an `Action` and `TransientViewActionFactory` to core. Is that ok?

**Comment by daniel-beck** [comment]
Seems reasonable to me.

**Review by oleg-nenashev — APPROVED** [review]
:bee:

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Comment by oleg-nenashev** [comment]
@daniel-beck wdyt?

**Comment by daniel-beck** [comment]
Seems reasonable. Haven't looked into it, but for detaching the feature, it's fine. If I have to rework things, that's my problem for not getting it done.

**Comment by oleg-nenashev** [comment]
Merging then. Thanks @daniel-beck !

**Comment by oleg-nenashev** [comment]
@dwnusbaum please follow the PR template and write the changelog entry

**Comment by dwnusbaum** [comment]
@oleg-nenashev I've updated the original comment to follow the template and added a changelog entry.

**Comment by daniel-beck** [comment]
@dwnusbaum https://wiki.jenkins.io/display/JENKINS/Monitoring+Jenkins and other locations that describe this feature should be updated accordingly.

Also, why not add a second link to `builds.jelly` that passes that parameter?

**Comment by dwnusbaum** [comment]
@daniel-beck I'll update that page and anything else that references cc.xml. Good idea, I'll submit a PR to add a second link so the new behavior is discoverable.

**Pull request merged**
