### PR TITLE
[JENKINS-55738] Correct out of disk space message

### PR DESCRIPTION
**Pull request by nisarg1499**
See [JENKINS-55738](https://issues.jenkins-ci.org/browse/JENKINS-55738).

### Proposed changelog entries

* `Internal: ` NodeMonitor out of disk space wrong message. The message has null value when master goes out of disk space. And it is due to returning of an empty nodeName(string) by c.getName().
* And so replacing c.getName() with c.getDisplayName() as it is overriden and so it will solve this issue. And this change has not been tested due to out of disk space constraint. 

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests

### Desired reviewers

@mention

### CODE REVIEW

**Review by jglick — APPROVED** [review]
Looks right; were you able to confirm whether it fixes the issue?

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
@nisarg1499 Thanks for the pull request

https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Computer.java#L769-L772 returns `nodeName`, but `getName()` returns the same field just without nulness check: https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Computer.java#L565 

So the message will contain `null` instead of empty string after the change. It unlikely improves the situation, "master" will not be returned. Please correct me if I am wrong

**Comment by nisarg1499** [comment]
> Looks right; were you able to confirm whether it fixes the issue?

Actually I don't know how to test it on local and create an out of disk space event so I didn't confirmed it. Can you just give me the command of testing this on local. I will just test this and let you know.

**Comment by nisarg1499** [comment]
> @nisarg1499 Thanks for the pull request
> 
> https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Computer.java#L769-L772 returns `nodeName`, but `getName()` returns the same field just without nulness check: https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Computer.java#L565
> 
> So the message will contain `null` instead of empty string after the change. It unlikely improves the situation, "master" will not be returned. Please correct me if I am wrong

@oleg-nenashev  Yes you are right that both the methods are actually returning `nodeName` and I thought of this earlier. But as `getDisplayName()` was getting overriden so I thought that it would give the required string.  So as i mentioned in the above comment I want to know the way of testing this on local so that I can check whether the behaviour is perfect or not.

I have one idea that if we pass "Putting back online as there is enough disk space again" in `Logger.info()` then would it be a better behaviour and would it work? As if we change `getName()` method of Computer class than it would create a problem as this method is used in many places.

**Comment by nisarg1499** [comment]
> @nisarg1499 Thanks for the pull request
> 
> https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Computer.java#L769-L772 returns `nodeName`, but `getName()` returns the same field just without nulness check: https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Computer.java#L565
> 
> So the message will contain `null` instead of empty string after the change. It unlikely improves the situation, "master" will not be returned. Please correct me if I am wrong

@oleg-nenashev  Can you please guide me in reviewing the fix which had been done. Which test are necessary and how can I do it on local by manually creating an out of disk event.

And as you said that this changes won't work than can you suggest me how should I proceed to fix this?

**Comment by oleg-nenashev** [comment]
@nisarg1499 please use separate pull requests for unrelated changes. It will help us to review and deliver them separately without blocking on each other

**Comment by nisarg1499** [comment]
> @nisarg1499 please use separate pull requests for unrelated changes. It will help us to review and deliver them separately without blocking on each other

@oleg-nenashev 
Yes I know but due to some issues the new commit got merged into previous PR. I am closing this pull request and I will do two different PR of two different issues. Sorry for the inconvenience

**Pull request closed without merging**
