### PR TITLE
[JENKINS-19445, JENKINS-34213, JENKINS-34808, JENKINS-34121] Bump remoting to 2.59.

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Changes:

2.58:
- [JENKINS-34213](https://issues.jenkins-ci.org/browse/JENKINS-34213) - Ensure that the unexporter cleans up whatever it can each sweep (https://github.com/jenkinsci/remoting/pull/81)
- [JENKINS-19445](https://issues.jenkins-ci.org/browse/JENKINS-19445) Force class load on UserRequest in order to prevent deadlock on windows nodes when using JNA and Subversion (https://github.com/jenkinsci/remoting/pull/82)
- [JENKINS-34808](https://issues.jenkins-ci.org/browse/JENKINS-34808) - Allow user to adjust socket timeout (https://github.com/jenkinsci/remoting/pull/68)

2.59:
- [JENKINS-34819](https://issues.jenkins-ci.org/browse/JENKINS-34819) - Allow disabling the remoting protocols individually. Works around issues like [JENKINS-34121](https://issues.jenkins-ci.org/browse/JENKINS-34121) (https://github.com/jenkinsci/remoting/pull/83)

@reviewbybees @jenkinsci/code-reviewers

### CODE REVIEW

**Comment by andresrc** [comment]
:bee:

**Comment by rsandell** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Comment by stephenc** [comment]
:bee: 👍

**Comment by christ66** [comment]
Should the remoting version be bumped up to 2.29 as @kohsuke just released a new version: https://github.com/jenkinsci/remoting/commit/ab984a09b687fe8b376193f18f4c611d1d91dd96?

**Comment by oleg-nenashev** [comment]
@christ66 sure

**Comment by oleg-nenashev** [comment]
Seems to be an INFRA issue, restarting the build

**Comment by jglick** [comment]
https://github.com/jenkinsci/remoting/pull/82 is still open, yet it is listed in the changelog here…?

**Comment by oleg-nenashev** [comment]
Actually it takes some time to get remoting in Maven central. Just stay tuned

**Comment by jglick** [comment]
:bee: but needs to wait for Central sync.

**Pull request merged**
