### PR TITLE
Update eslint

### PR DESCRIPTION
**Pull request by timja**
not sure exactly what caused it but possibly batch merging of PR introduced a dep update.

Untested

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/6816"></a>

### CODE REVIEW

**Comment by NotMyFault** [comment]
Where/how did you discover that? The latest master revision has no eslint failures according to https://ci.jenkins.io/job/Core/job/jenkins/job/master/3821/consoleFull

**Comment by timja** [comment]
discovered in https://github.com/jenkinsci/jenkins/pull/6806

and reproduced on master branch

**Comment by NotMyFault** [comment]
Oic. Jan updated ESLint in https://github.com/jenkinsci/jenkins/pull/6806/files#diff-98e6e30c7f0019b490c85520fd4e7fdb64fc5f07348c35ddc84624ccfb97af47R32 which is not present on master (yet).

If I do that on the current master revision, I observe the same couple of failures like on his PR, but if I run it with 7.1.0 I'm fine, like the CI is.
I'd take a guess and assume this is a fix for a change in ESLint we need in the future (on his PR) if we update and you were subject to caching of node/node_modules?

**Comment by timja** [comment]
Closing in favour of https://github.com/jenkinsci/jenkins/pull/6813

**Pull request closed without merging**
