### PR TITLE
JENKINS-63308 Fix regexp validator UI location

### PR DESCRIPTION
**Pull request by timja**
See [JENKINS-63308](https://issues.jenkins-ci.org/browse/JENKINS-63308).

<details>
<summary>Before</summary>

image

</details>

<details>
<summary>After</summary>

image

</details>

### Proposed changelog entries

* Entry 1: Issue, Human-readable Text
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by StefanSpieker — APPROVED** [review]

**Review by fqueiruga — APPROVED** [review]

**Comment by fqueiruga** [comment]
Amazing and really fast fix thanks @timja !

**Comment by MarkEWaite** [comment]
Has it been confirmed that the field does not perform variable expansion?  If it performs variable expansion, then the new validator will likely block all use of variables in that field.

**Comment by timja** [comment]
> Has it been confirmed that the field does not perform variable expansion? If it performs variable expansion, then the new validator will likely block all use of variables in that field.

not sure what you mean? this is basically a revert to what the previous code did before the regression.

**Comment by MarkEWaite** [comment]
> > Has it been confirmed that the field does not perform variable expansion? If it performs variable expansion, then the new validator will likely block all use of variables in that field.
> 
> not sure what you mean? this is basically a revert to what the previous code did before the regression.

Ah, ok.  In the git plugin, there are fields where a user may enter a number or they may enter a symbolic value that is expanded at job run time.  For example, ${DEPTH} may be a parameter value to the job and might also be inserted as the value of the shallow clone depth field.  If the shallow clone depth field allows only integer values, it may warn about the variable value.

If this is restoring a behavior that existed before, then the previous behavior must not have included variable expansion.  Safe to ignore my comment.

**Comment by timja** [comment]
there's only 3 regexp validators in Jenkins core afaik.

number, positive number and required.

👍

**Comment by timja** [comment]
This PR is now ready for merge, it'll be merged after 24 hours if there's no negative feedback.

**Pull request merged**
