### PR TITLE
[JENKINS-69116] When the build queue has long words, it will cause it to cover other places.

### PR DESCRIPTION
**Pull request by frankie139506**
See [JENKINS-69116](https://issues.jenkins.io/browse/JENKINS-69116).

Before:
image

After:
image

### Proposed changelog entries

* Don't block other interface.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] (If applicable) Jira issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [X] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")` if applicable.
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/6919"></a>

### CODE REVIEW

**Comment by daniel-beck** [comment]
> Don't block other interface.

If you were a Jenkins user with no knowledge of pull requests coming in, would this help you understand what was changed?

**Comment by frankie139506** [comment]
> > Don't block other interface.
> 
> If you were a Jenkins user with no knowledge of pull requests coming in, would this help you understand what was changed?

I have added a picture to complement this sentence. Please take a look.

**Comment by daniel-beck** [comment]
> I have added a picture to complement this sentence. Please take a look.

Thanks. The "Proposed changelog entry" is what you recommend we add to https://www.jenkins.io/changelog/ to describe the change to other Jenkins users. We don't put pictures there.

Since this seems to fix an unreleased regression from #6604, there will be no need to document this in the changelog if we merge this today. But if there were, normal users would not understand what was changed.

**Review by daniel-beck — APPROVED** [review]

**Comment by daniel-beck** [comment]
If this is merged before the weekly release, whoever merges should add `skip-changelog` both here and on #6604.

**Comment by NotMyFault** [comment]
Checking out ee9d350913c4b663d78229bc51e219ecd03255b5 as latest revision, I'm not able to replicate the issue, assuming I understood it correct?
Screenshot 2022-07-25 at 09 36 06
What did you do to experience that @frankie139506 ?

**Comment by daniel-beck** [comment]
@NotMyFault use `_` instead of spaces to not have trivial word breaks.

**Comment by NotMyFault** [comment]
> @NotMyFault use `_` instead of spaces to not have trivial word breaks.

Same outcome:
Screenshot 2022-07-25 at 09 43 16

**Comment by frankie139506** [comment]
> > @NotMyFault use `_` instead of spaces to not have trivial word breaks.
> 
> Same outcome: Screenshot 2022-07-25 at 09 44 35

gif1

**Comment by NotMyFault** [comment]
Oic, based on your GIF provided, that seems to be a browser dedicated issue:
Screenshot 2022-07-25 at 10 02 26
Chrome and Safari warrant the current design fine, where Firefox is the odd one.

**Comment by frankie139506** [comment]
> Oic, based on your GIF provided, that seems to be a browser dedicated issue:
> Screenshot 2022-07-25 at 10 02 26
> Chrome and Safari warrant the current design fine, where Firefox is the odd one.

Sorry I didn't say which browser I was use.

**Comment by daniel-beck** [comment]
>  Preferably, this should be addressed for Firefox only, considering it's the only one affected, I guess?

To prevent introduction of a new regression, IMO this reversal PR should be merged now, and then the original change can be done more compatibly.

**Review by NotMyFault — APPROVED** [review]

**Comment by NotMyFault** [comment]
> To prevent introduction of a new regression, IMO this reversal PR should be merged now, and then the original change can be done more compatibly.

Agree, unfortuntate to see it reverted, but trading one regression for another isn't great either.

**Comment by timja** [comment]
Given it's a one line change only introduced yesterday and release is coming out tomorrow, expedited 😄

**Pull request merged**
