### PR TITLE
[FIX JENKINS-33705] Use platform line endings

### PR DESCRIPTION
**Pull request by daniel-beck**
[JENKINS-33705](https://issues.jenkins-ci.org/browse/JENKINS-33705)

### CODE REVIEW

**Comment by batmat** [comment]
:+1:

**Comment by oleg-nenashev** [comment]
:+1:

**Comment by jtnord** [comment]
personally I am massively against multi line logs like this as it screws up machine parsing and these should really be multiple log entries...
Many parsers have special cases for exceptions (aka stack traces) - but this is IMO pure evilness...

But whatevers - better than it was.

**Comment by daniel-beck** [comment]
@jtnord This is mostly the use case for temporarily instances run interactively, where it's easier to check the log than to look on the FS. Do you have an alternative suggestion to this approach? I think highlighting like this is necessary to ensure the password is not overlooked.

**Comment by jtnord** [comment]
@daniel-beck - thanks for waiting for my response :-)

Yes - the alternative is to 
```
LOGGER.info("***************************************************************************");
LOGGER.info("***************************************************************************");
LOGGER.info("**                                                                       **");
LOGGER.info("** Jenkins initial setup is required. An admin user has been created and **")
LOGGER.info("** a password generated.                                                 **")
LOGGER.info("** Please use the following password to proceed to installation:         **")
LOGGER.info("**                                                                       **");
// TODO pad this with the correct number of spaces
LOGGER.info("** " + setupKey +   "                                                    **");
LOGGER.info("**                                                                       **");
LOGGER.info("**                                                                       **");
// TODO pad this with the correct number of spaces
LOGGER.info("** This may also be found at: " + iapf.getRemote()    + "                **")
LOGGER.info("**                                                                       **");
LOGGER.info("***************************************************************************");
LOGGER.info("***************************************************************************");
```

**Comment by daniel-beck** [comment]
@teilo Would padding it to the left be acceptable, so the actual message starts in column ~60?

    Mrz 24, 2016 4:10:56 PM jenkins.install.SetupWizard <init>
    INFO:                                                       *************************************************************
    Mrz 24, 2016 4:10:56 PM jenkins.install.SetupWizard <init>
    INFO:                                                       *************************************************************
    Mrz 24, 2016 4:10:56 PM jenkins.install.SetupWizard <init>
    INFO:                                                       *************************************************************
    Mrz 24, 2016 4:10:56 PM jenkins.install.SetupWizard <init>
    INFO:                                                       Created admin user for first launch setup.
    Mrz 24, 2016 4:10:56 PM jenkins.install.SetupWizard <init>
    INFO:                                                       Please use the following password to proceed to installation:
    Mrz 24, 2016 4:10:56 PM jenkins.install.SetupWizard <init>
    INFO:                                                       444a3adab53543e386a21a0e81b0242c
    Mrz 24, 2016 4:10:56 PM jenkins.install.SetupWizard <init>
    INFO:                                                       This may also be found at:
    Mrz 24, 2016 4:10:56 PM jenkins.install.SetupWizard <init>
    INFO:                                                       /var/lib/jenkins/secrets/initialAdminPassword
    Mrz 24, 2016 4:10:56 PM jenkins.install.SetupWizard <init>
    INFO:                                                       *************************************************************
    Mrz 24, 2016 4:10:56 PM jenkins.install.SetupWizard <init>
    INFO:                                                       *************************************************************
    Mrz 24, 2016 4:10:56 PM jenkins.install.SetupWizard <init>
    INFO:                                                       *************************************************************

My main concern here is that the message should be easy to find and I'm not sure it would be in your approach.

**Comment by jtnord** [comment]
> Would padding it to the left be acceptable

No, you are not in control of the logger format - some formatters put the timestamp and message on a single line.
Other formatters abbreviate the classname (j.i.SetupWizard) - so you can't count on 60 to be correct (and others would have a different date format)

**Pull request merged**
