### PR TITLE
Update sidepanel_sl.properties

### PR DESCRIPTION
**Pull request by matejzero**
Fixed wrong translations.

### CODE REVIEW

**Comment by batmat** [comment]
Wow, thanks.

Those translations were contributed by an automated system and merged globally.

So, could you possibly also review https://github.com/jenkinsci/jenkins/commit/362b04eb3caacc1d3fbdd569d7ce22bc8b99b946 and https://github.com/jenkinsci/jenkins/commit/60d8abc254cf57c102f83edcc7ba9cdfae43336d to see if nothing bad like that slipped in in `_sl` translations?

Thanks for your help!

**Comment by batmat** [comment]
To be ported to `master` too BTW. 

Not sure I should have merged it on 1.x now I think of it. Reading the original translation made me act possibly a bit quicker than I should...

@daniel-beck do you plan to merge 1.x changes into master/2.1 again like you did previously, or should the changes be cherry_picked? I can file the associated PR if so.

**Comment by daniel-beck** [comment]
@batmat Why are we merging random PRs into `1.x`? AFAIK this is the branch KK created for the 1.x infra test releases…

**Comment by matejzero** [comment]
Doing a quick check, there is no translations bad as the one I fixed. You can see it's been auto translated, but you can, most of the time, see what the text is talking about.

I might go over the and retranslate them, but I don't have time right now (will put it on my todo). I also have to note, I don't use Jenkins, so some translations are hard to make right, since I can't put them to the right context.

**Comment by batmat** [comment]
@daniel-beck mostly because, my bad, I went a bit too fast. 

I checked the content with google translate, and when I saw `With my ass` in the original text I thought I would be good indeed that it gets merged asap. Only to realize afterwards it wasn't actually targetting `master`... :disappointed: 

@matejzero could you please refile the same PR against the `master` branch? If not, I can do it.

**Pull request merged**
