### PR TITLE
JENKINS-37282 allow user to be created (e.g. in anonymous user case)

### PR DESCRIPTION
**Pull request by pjfanning**
Allow anonymous user to be created if it doesn't already exist

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
I'm honestly 👎 regarding such approach. We should avoid creating users where it is possible in the Getter logic. IMHO the plugins should perform CheckForNull as it is stated in the annotation.

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
Not a fix OR violated annotation specification if somebody considers it as a valid fix

**Comment by oleg-nenashev** [comment]
@pjfanning Just in case, do you agree or not? In Jenkins project we have no veto right, any -1 can be outvoted, hence please feel free to reopen the ticket if you want to get a wider discussion

**Comment by pjfanning** [comment]
@oleg-nenashev I see your point about not creating users in the User.getUser calls. Do you have any suggestions as to how to handle the 'anonymous' user? The automatic abort for long running jobs is useful but it feels like this action shouldn't be associated with an actual user but with the 'anonymous' user.

**Pull request closed without merging**
