### PR TITLE
Hacktoberfest: Performance issue, string concatenation in  loop

### PR DESCRIPTION
**Pull request by Sangaibisi**
See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

### Proposed changelog entries

String concantenatin might cause to performance issue if we don't care string pool. Also, more readable code.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
This one looks like a valid PR. Why did you close it @Sangaibisi ?

**Comment by Sangaibisi** [comment]
> This one looks like a valid PR. Why did you close it @Sangaibisi ?
As far as I remember linux tests were unsuccessful. I do not know why it happened.

**Comment by daniel-beck** [comment]
We're having infra trouble at the moment, so this is likely unrelated to this PR.

**Comment by oleg-nenashev** [comment]
I would recommend to reopen it to see whether the change passes CI. Code-wise it looks fine

**Comment by oleg-nenashev** [comment]
Marked as `spam` to clean up the Hacktoberfest queries. I do not consider the change itself as a spam, and I will be happy to mark the recovered pull request as a valid one.

**Pull request closed without merging**
