### PR TITLE
Update ExtensionList#load to not log unnecessary stacktrace

### PR DESCRIPTION
**Pull request by sghill**
Also uses the Java8 syntax for only building a message when the log level is enabled.

Most logging in Jenkins is not covered by tests, so I didn't add them here. Let me know if that'd be preferred.

See [JENKINS-56494](https://issues.jenkins-ci.org/browse/JENKINS-56494).

### Proposed changelog entries

* Update Jenkins initialization logging on FINE level to not log stack trace per extension

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### CODE REVIEW

**Comment by daniel-beck** [comment]
The motivation here is unclear. https://github.com/jenkinsci/jenkins/commit/b075de5f02b7a45a12bf11aef86d5332a8d74c7d indicates this exists for a reason.

**Comment by sghill** [comment]
@daniel-beck thanks for the feedback!

The motivation is simplifying root cause analysis when problems arise in running Jenkins controllers. Today we can turn the logs up to FINE, but we end up with many red herrings.

Downloading the most recent LTS (2.150.3) and enabling FINE logging results in a startup with 19 stacktraces. Jenkins of course starts up OK and the extensions are all working. The stacktraces all have a `null` cause:
```
23:15:27.375 [pool-7-thread-9] DEBUG hudson.ExtensionList - Loading ExtensionList: class hudson.ExtensionFinder23:15:27.375 [pool-7-thread-9] DEBUG hudson.ExtensionList - Loading ExtensionList: class hudson.ExtensionFinder
java.lang.Throwable: null
    at hudson.ExtensionList.load(ExtensionList.java:378) ~[?:?]
```

Definitely open to the idea these are being resolved too early, but representing that as a `new Throwable()` that is never actually thrown is confusing. In this case as an operator I'd much rather see a warning along the lines of "Extension x.y.z was resolved too early - this causes ..." than a stacktrace.

Since it's not clear what impact this has, I opted to remove the Throwable as it does not seem to have any consequence and the FINE log level is hidden from users by default anyway. Happy to change to a warning that is more clear if you'd prefer that.

**Comment by daniel-beck** [comment]
> Since it's not clear what impact this has, I opted to remove the Throwable as it does not seem to have any consequence and the FINE log level is hidden from users by default anyway. Happy to change to a warning that is more clear if you'd prefer that.

The idea seems to be to allow investigating possible extension loading problems resulting from previously successfully performed extension loading. So there's no actual problem here.

Distinguish FINE and FINEST perhaps? One with, one without stack trace?

**Comment by sghill** [comment]
I can do that, but do you have a preference for what the cause should be (if we agree it should not be `null`)? My first thought would be to introduce a `MaybeResolvedTooEarlyException`.

I'd also really like to better understand who is getting value from this stacktrace and what should be done about it. To that end if there are docs on how you could remediate this situation? It'd be excellent to link to them from this message. Or if there is a deterministic way we can tell that an extension was loaded too soon that'd be very helpful.

A more meta question - I'd like to help out in improving the logging situation for Jenkins. Are there guidelines on the logging philosophy in Jenkins? I found [this](https://wiki.jenkins.io/display/JENKINS/Logging) but it doesn't really cover from an developer's perspective what should be logged or from an operator's perspective what we should expect to see.

Thanks for the quick responses!

**Comment by daniel-beck** [comment]
> I'd also really like to better understand who is getting value from this stacktrace and what should be done about it. To that end do you know if there are docs on how you could remediate this situation?

I don't _know_ the specific motivation, but in troubleshooting (and cranking up the log level) the stack trace would explain what caused a specific extension to load. A not-actually-exception is a convenient way to get that as part of log output.

> A more meta question - I'd like to help out in improving the logging situation for Jenkins. Are there guidelines on the logging philosophy in Jenkins?

Unsure. Probably just, if something looks potentially useful in determining what's going on, or troubleshooting, log it. For a larger discussion around this, I recommend the jenkinsci-dev mailing list.

**Comment by sghill** [comment]
> Distinguish FINE and FINEST perhaps? One with, one without stack trace?

Thanks for the suggestion. I went for FINE (log4j2: debug) and FINER (log4j2: trace), which seems to map well to the intent you described as well.

Here's the FINE:
```
13:58:40.667 [UpdateCenter.init] DEBUG hudson.ExtensionList - Loading ExtensionList 'hudson.diagnosis.OldDataMonitor'
13:58:40.672 [Finalizing set up] DEBUG hudson.ExtensionList - Loading ExtensionList 'hudson.model.LabelFinder'
13:58:40.676 [Download metadata thread] DEBUG hudson.ExtensionList - Loading ExtensionList 'hudson.model.DownloadService$Downloadable'
```

Here's the FINER with a more descriptive cause -- I think this would've prevented my question in the first place:
```
14:00:35.264 [Jenkins initialization thread] DEBUG hudson.ExtensionList - Loading ExtensionList 'hudson.model.listeners.ItemListener'
14:00:35.264 [Jenkins initialization thread] TRACE hudson.ExtensionList - Loading ExtensionList 'hudson.model.listeners.ItemListener' from
java.lang.Throwable: Only present for stacktrace information
	at hudson.ExtensionList.load(ExtensionList.java:378) ~[?:?]
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:317) ~[?:?]
	at hudson.ExtensionList.iterator(ExtensionList.java:172) ~[?:?]
	at jenkins.model.Jenkins.<init>(Jenkins.java:997) ~[?:?]
	at hudson.model.Hudson.<init>(Hudson.java:85) ~[?:?]
	at hudson.model.Hudson.<init>(Hudson.java:81) ~[?:?]
	at hudson.WebAppMain$3.run(WebAppMain.java:233) ~[?:?]
```

**Comment by daniel-beck** [comment]
@sghill Why did you close this? https://github.com/jenkinsci/jenkins/commit/7bf6156a6e577753dab1e590ec2beafd1036566e looked reasonable.

**Comment by sghill** [comment]
Happy to rebase and reopen if you'd like, just preferred to close it with the possibility of reopening instead of leaving it open and possibly getting stale

**Comment by daniel-beck** [comment]
@sghill Please do, this looked reasonable. We're currently working hard to prevent PRs from stalling so I'm optimistic 😃

**Review by daniel-beck — APPROVED** [review]

**Review by batmat — APPROVED** [review]

**Pull request merged**
