### PR TITLE
FIXED JENKINS-36282 - "Export as plain XML" option doesn´t export jobs inside folders

### PR DESCRIPTION
**Pull request by dariver**
Adding a new method to obtain all items in `hudson.model.AllView.java` and using it in `cc.xml.jelly`

More info in [JENKINS-36282](https://issues.jenkins-ci.org/browse/JENKINS-36282)

@reviewbybees

### CODE REVIEW

**Comment by alvarolobato** [comment]
@reviewbybees

**Comment by daniel-beck** [comment]
This appears to be wrong, as it assumes the definition of recursion for `View.getAllItems()` is the same as recursion for `Jenkins.getAllItems()` – which by my reading of https://github.com/jenkinsci/jenkins/pull/793 it is not: It recurses *views*, not *item groups*.

This also appears to only address the specific case of the `AllView`, ignoring all other core-provided view types in redefining that `View.getAllItems()` means, introducing inconsistency.

So, :-1:

CC @olivergondza Could you as author of `View.getAllItems()` clarify?

**Comment by jglick** [comment]
Please include a meaningful summary of your changes in both commit comments, and the PR title. Hundreds of PRs are opened for review. I can only even look at a handful. If yours has no summary, I am not about to look at it.

**Comment by daniel-beck** [comment]
Closing after no response to review comments for a few months.

**Pull request closed without merging**
