### PR TITLE
Update SezPoz to 1.11

### PR DESCRIPTION
**Pull request by jglick**
Picks up [these changes](https://github.com/jglick/sezpoz/compare/pom-1.9...pom-1.11), especially https://github.com/jglick/sezpoz/pull/11, as requested in #2329 by @daspilker and @oleg-nenashev.

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
Need to wait a few hours for Central synch, apparently.

**Comment by varmenise** [comment]
🐝

**Comment by oleg-nenashev** [comment]
The changes in the lib are barely reviewable.
I'd rely on the CI results

**Comment by daspilker** [comment]
:+1:

The release is now available in Maven Central: https://repo1.maven.org/maven2/net/java/sezpoz/sezpoz/1.11/

Can someone restart the CI?

**Comment by oleg-nenashev** [comment]
it works

**Comment by oleg-nenashev** [comment]
👍 from me

**Pull request merged**
