### PR TITLE
Updated Swedish translation

### PR DESCRIPTION
**Pull request by Regnander**
In this PR, I added new and updated existing properties/HTML files. There are some more HTML files to be translated, which I will take care of in a future PR.

No JIRA ticket. Since the majority of the most recent translation PRs lacked one, I figured this wasn't needed.

### Testing done

Testing was done by browsing the various menus and settings to get proper context.

### Proposed changelog entries

- Major overhaul of the entire Swedish translation.

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Comment by Regnander** [comment]
I have no idea on how to solve the build errors, so any help would be appreciated.

**Comment by StefanSpieker** [comment]
I think it is complaining about the HTML files. 

> Code style issues found in 84 files. Run Prettier to fix.

You can build it on your machine and check that you are seeing the same error. You can fix it with `prettier`. In the ci process you can change the [Line 799 in pom.xml](https://github.com/jenkinsci/jenkins/blob/master/war/pom.xml#L799) to `lint:fix`, which should fix all problems, remember to revert the changes before committing the changes.

**Comment by Regnander** [comment]
My local repo is currently broken, so I manually formatted the affected HTML files. However, I still get the same lint error.

**Comment by NotMyFault** [comment]
> My local repo is currently broken, so I manually formatted the affected HTML files. However, I still get the same lint error.

The correct way to fix prettier issues is by running `yarn run lint:fix` followed by `lint:ci` to ensure locally, that your PR passes CI checks.

**Comment by Regnander** [comment]
> The correct way to fix prettier issues is by running `yarn run lint:fix` followed by `lint:ci` to ensure locally, that your PR passes CI checks.

That fixed the lint errors. Thanks!

However, this time the logs say "`hudson.PluginManagerTest.updateSiteURLCheckValidation` failed". Is there something I can do about this?

**Review by MarkEWaite — APPROVED** [review]
Thanks very much for the pull request.

I resolved the conflict and merged the latest changes from the master branch so that a new CI build would evaluate the pull request again.

I've run the Jenkins controller with locale set to "sv_SE" using the Jenkins locale plugin and was able to see the Swedish translations from my Google Chrome browser.  I checked a few of the translations with Google translate and confirmed that Google translate agrees with the translated strings.

I don't speak Swedish, but I believe that @rsandell does.  I've approved this pull request based on my testing and my use of google translate to confirm the few strings I checked agreed with Google translate.

**Comment by MarkEWaite** [comment]
> @MarkEWaite Thanks for merging again. Is there anything I should do once the build is finished?

No, I think that the preferred next step is a review by another Swedish speaker.  If that doesn't happen within a week, I will ask for a review by someone who is not a Swedish speaker so that it can be merged.

**Pull request merged**
