### PR TITLE
Remove not existed build variable

### PR DESCRIPTION
**Pull request by KostyaSha**
Referenced link also has this variable https://wiki.jenkins-ci.org/display/JENKINS/Building+Jenkins#other+tips

@daniel-beck ?

---
This change is [Reviewable](https://reviewable.io/reviews/jenkinsci/jenkins/2708)

### CODE REVIEW

**Comment by daniel-beck** [comment]
@KostyaSha Not sure what you're asking of me. I didn't write this.

**Review by oleg-nenashev — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Merging since the variable does not really exist within the jenkinsci organization

**Comment by oleg-nenashev** [comment]
Oh, not merging since there is only one +1 CC @jenkinsci/code-reviewers

**Comment by KostyaSha** [comment]
> Oh, not merging since there is only one +1 CC @jenkinsci/code-reviewers

ORLY?

**Comment by KostyaSha** [comment]
> @KostyaSha Not sure what you're asking of me. I didn't write this.

People started referencing to you saying that you will soon fix/made docs. I did the same. Or you plan make developer documentation and keep such wrong info like this?

**Review by abayer — APPROVED** [review]

**Pull request merged**
