### PR TITLE
jenkins-dropdown background is transparent when the browser does not support backdrop-filter

### PR DESCRIPTION
**Pull request by lgf10**
See [JENKINS-72430](https://issues.jenkins.io/browse/JENKINS-72430).

### Proposed changelog entries

- JENKINS-72430, fix dropdowns having a transparent background in certain circumstances

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

### CODE REVIEW

**Comment by MarkEWaite** [comment]
Thanks for the pull request.  Please describe the testing that you performed to confirm that the change is well behaved.  Changes to the cascading style sheets can have a very wide impact.

Please provide "before" and "after" screenshots that show how the change has affected the user interface.

**Comment by lgf10** [comment]
Before:
grafik
grafik

After:
grafik
grafik

**Comment by lgf10** [comment]
As discussed in https://issues.jenkins.io/browse/JENKINS-72430, the issue stems from [backdrop-filter](https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter) not working.
Setting layout.css.backdrop-filter.force-enabled results in the correct behaviour.

**Review by NotMyFault — CHANGES_REQUESTED** [review]
I'm unable to replicate the issue on
- MacOS 14.1.2 (23B92):
	- Firefox 120.0.1
	- Chrome 119.0.6045.105
	- Safari 17.1.2 (19616.2.9.11.12)
- Windows 11 23H2 (22631):
	- Firefox 120.0.1
	- Chrome 119.0.6045.105
	- Edge 105
- Windows 10 (10.0.19045.3324):
	- Firefox 120.0.1
	- Chrome 119.0.6045.105
	- Edge 105

I'm not confident the change proposed has an impact on the scenario described, nor am I confident the issue reported is valid, given several people cannot replicate it.

> fix dropdowns having a transparent background in certain circumstances

Additionally, I'm not confident that - unspecified - "certain circumstances" provide any net worth for maintainers attempting to reproduce the issue.

I recommend providing a compelling list of modifications made to set up an environment as similar as yours, evidently the issue cannot be reproduced in plain Firefox on a new OS installation.

**Comment by lgf10** [comment]
The circumstances under which the issue appears have only been solved mere minutes ago (-> JIRA discussion)
Allthough I'm not sure of the cause, I do have a solution. Should I close this issue? Is it relevant to other people?

**Comment by lgf10** [comment]
I have not previously touched any of the mentioned properties.
layout.css.backdrop-filter.enabled already was true for me
gfx.webrender.all had a default of false (atleast for me)
and the layout.css.backdrop-filter.force-enabled (which fixed the issue when set to true) also had a default of false

I get that this is probably a rare Firefox oddity caused by some hardware or software configuration of the underlying system, but calling this a "user-specific configuration mistake" seems somewhat harsh.

Since I now have a working solution, I will close the issue.

**Pull request closed without merging**
