### PR TITLE
Added new API to create a file in jenkins server.

### PR DESCRIPTION
**Pull request by msdinesh07**
We have added a new API to create the mentioned file name with path and file contents as parameter to the API on the Jenkins server.

### CODE REVIEW

**Comment by daniel-beck** [comment]
Please explain what this is actually needed for. Code mentions `config.xml`, but there's plenty of APIs for job configurations etc. There's also general-purpose scripting APIs for specialized use cases. Without justification, I just see no need for this change.

:-1: for the obvious security vulnerability introduced here, as this allows anyone with Jenkins read access to override any file on the Jenkins master that the Jenkins process has write access to, inside or outside `JENKINS_HOME`.

Please keep to the same coding style as the rest of the source file you're editing. I know it's not all consistent in Jenkins, but that's no reason to not try.

**Comment by kohsuke** [comment]
I think this is best done as a plugin. You can implement a `RootAction` that has this exact method.

**Comment by msdinesh07** [comment]
Hi Daniel,

This API is not to update the config.xml in JENKINS_HOME. We have an use-case where we need to write a file with the configuration variables under group_vars & host_vars where Ansible make use of this variable files in JSON format. We couldn't find any existing API to solve our use-case. So, we thought of writing a new API where we could create new file in jenkins server. For the security vulnerability, may be we could allow only to write files outside of JENKINS_HOME.

Kohsuke,
Could you please provide more information on the plugin and I couldn't find any method which performs the same action.

Regards,
Dinesh

**Comment by olivergondza** [comment]
@msdinesh07, In case you need this for a handful of files, adding support to core or creating a plugin is a huge overkill. Take advantage of the [Script Console](https://wiki.jenkins-ci.org/display/JENKINS/Jenkins+Script+Console) ('s remote access capabilities) and do any changes you need to. Custom groovy scripting required.

**Comment by msdinesh07** [comment]
We will write less than 10 files only. I'm new to Jenkins development. So I need to explore more on script console.

**Comment by daniel-beck** [comment]
@msdinesh07 Please ask on the jenkinsci-users mailing list for advice on how to achieve what you want. I don't think we will accept anything resembling this pull request into Jenkins due to lack of a use case.

**Comment by msdinesh07** [comment]
Thanks @daniel-beck. I have solved my problem with the help of jenkins ansible plugin to pass the dynamic host and group vars.  Thanks all for your support.

**Pull request closed without merging**
