### PR TITLE
add compilerArg `-Xpkginfo:always` for useIncrementalCompilation which make build fast

### PR DESCRIPTION
**Pull request by qxo**
useIncrementalCompilation will not work for some java not compiled (package-info.java)

try `mvn package -X ` will find thest files:
ie:
```
[DEBUG] useIncrementalCompilation enabled
[DEBUG] Stale source detected: I:\github\jenkins\core\src\main\java\hudson\cli\package-info.java
[DEBUG] Stale source detected: I:\github\jenkins\core\src\main\java\hudson\os\solaris\package-info.java
[DEBUG] Stale source detected: I:\github\jenkins\core\src\main\java\hudson\cli\handlers\package-info.java
[DEBUG] Stale source detected: I:\github\jenkins\core\src\main\java\jenkins\security\s2m\package-info.java
[DEBUG] Stale source detected: I:\github\jenkins\core\src\main\java\hudson\init\package-info.java
[DEBUG] Stale source detected: I:\github\jenkins\core\src\main\java\hudson\model\labels\package-info.java
[DEBUG] Stale source detected: I:\github\jenkins\core\src\main\java\hudson\cli\declarative\package-info.java
[DEBUG] Stale source detected: I:\github\jenkins\core\src\main\java\hudson\console\package-info.java
[DEBUG] Stale source detected: I:\github\jenkins\core\src\main\java\hudson\util\jna\package-info.java
[INFO] Changes detected - recompiling the module!
```

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

### Proposed changelog entries

* Entry 1: Issue, Human-readable Text
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by varyvol** [comment]
@qxo have you checked whether it makes sense to change the annotations in those specific 'package-info' files, instead of modifying how the project is built?

**Comment by qxo** [comment]
> @qxo have you checked whether it makes sense to change the annotations in those specific 'package-info' files, instead of modifying how the project is built?

It should be work, but do not have time for this

And then compilerArg `-Xpkginfo:always` wil make it easy for fixup

**Comment by varyvol** [comment]
@qxo my concern is that I don't really know (maybe I'm lacking some knowledge here) why the issue is happening. Is it because those package-info files should have another content? Is it because there's something else on another files? Is it because of a Maven bug? If you can provide further details, it would certainly help with the review.

**Comment by qxo** [comment]
> package-info
maven will not compile package-info.java  without any annotation with Retention=RUNTIME 

ref: https://stackoverflow.com/questions/6770455/maven-compiling-package-info-java-to-package-info-class

**Review by MRamonLeon — APPROVED** [review]
IIUC the compilation of Jenkins core takes longer than needed because the packages-info are not compiled to .class because they don't have at least one annotation persisting in RUNTIME. The compiler detects some java files without class files and recompile everything. With this change we always compile package-info to class and then the compiler doesn't detect changes so it's faster. Is this right?

A reference: https://stackoverflow.com/questions/17944108/maven-compiler-plugin-always-detecting-a-set-of-sources-as-stale

**Review by timja — APPROVED** [review]
seems fine

**Comment by timja** [comment]
I think we're fine to go ahead with this, easy to back out if it introduces an issue,

We'll merge this after 24 hours if there's no negative feedback

**Review by oleg-nenashev — APPROVED** [review]
I agree with the merge

**Pull request merged**
