### PR TITLE
Do not use null value for aria-hidden HTML attribute

### PR DESCRIPTION
**Pull request by directhex**
'' is not a valid value for the `aria-hidden` attribute.

Ref: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-hidden_attribute

Ref: https://dequeuniversity.com/rules/axe/3.5/aria-valid-attr-value?application=axe-puppeteer

Minor fix with no config or user changes, does not meet the bar for JIRA ticket or changelog inclusion

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

### Proposed changelog entries

* Entry 1: Issue, Human-readable Text
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by daniel-beck** [comment]
IIRC if the attribute value is `null` (no quotes) rather than `''` it will not be emitted at all. Worth a try perhaps?

**Review by MRamonLeon — APPROVED** [review]
Per https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-hidden_attribute and https://www.w3.org/TR/wai-aria-1.1/#typemapping the allowed values are _true_, _false_ and _undefined_ so I'm fine with this PR.

**Review by timja — APPROVED** [review]
seems fine

**Comment by timja** [comment]
@directhex can you restore the PR template please for changelog generation

**Comment by directhex** [comment]
@timja I've put the template back in, though I'm not sure how to phrase a changelog entry for this

**Review by fqueiruga — APPROVED** [review]

**Comment by daniel-beck** [comment]
> changelog generation

I recommend we `skip-changelog` this one, seems a bit too minor. Different of course if screen readers etc. seriously fail here, but then a changelog entry should be straightforward, describing the impact.

**Review by res0nance — APPROVED** [review]
I'm with @daniel-beck we probably should skip the changelog as there doesn't seem to be any impact that we have noticed to warrant a changelog

**Comment by zbynek** [comment]
@directhex did you use any tool to confirm your fix? I'm using Chrome's builtin Lighthouse audit and it complains about
`<div aria-hidden="undefined"></div>` too. Maybe the only correct way to have it undefined is just to omit it.
* in Jelly returning `null` instead of `''` should do the trick, as per @daniel-beck 's suggestion
* in the `.js` file you can just delete it or change it to `aria-hidden="true"` -- not sure which one was author's intention (it's not very useful to make an image visible to screen reader if it has no `aria-label` / `title`).

**Comment by directhex** [comment]
@zbynek I didn't run it through a tool, the report came from some inscrutable internal service which scans sites in production

If we want to go the "just omit the tag" route, I can send that instead

**Comment by alecharp** [comment]
@directhex from @zbynek's last comment, I feel like omitting the attribute would be better. The improvement would be to see lighthouse (or any other tool) stop complaining about it. Can you look into this and rework your PR? Thanks!

**Comment by varyvol** [comment]
@directhex did you have the opportunity to review @alecharp and @zbynek  suggestion?

**Comment by directhex** [comment]
Sorry, been busy. Let's give it a shot.

**Review by zbynek — APPROVED** [review]
All 4 ARIA attribute issues reported by Lighthouse on Jenkins Dashboard are gone now 🎉

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Pull request merged**
