### PR TITLE
[JENKINS-60678] Fix java checking on ComputerLauncher for AdoptOpenJDK 11

### PR DESCRIPTION
**Pull request by MRamonLeon**
See [JENKINS-60678](https://issues.jenkins-ci.org/browse/JENKINS-60678).

The date behind the version was avoiding the match.

### Proposed changelog entries

* Bug: Fix check of java version on ComputerLauncher for AdoptOpenJDK 11 

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [N/A] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@jenkinsci/core-pr-reviewers 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
@MRamonLeon this seems more like a bug rather than an internal change as detailed in your proposed changelog entry

**Review by oleg-nenashev — APPROVED** [review]
Thanks @MRamonLeon !

**Comment by oleg-nenashev** [comment]
I plan to merge it tomorrow if no negative feedback and if the CI passes

**Comment by MRamonLeon** [comment]
Awesome @timja 

> @MRamonLeon this seems more like a bug rather than an internal change as detailed in your proposed changelog entry

You're right, I didn't ponder the implications, thanks.

**Review by MarkEWaite — APPROVED** [review]
I would very much like it if the added tests would also include tests for the following data that I've extracted from various other interesting Java distributions:

### Amazon Corretto

```
openjdk version "11.0.6" 2020-01-14 LTS
OpenJDK Runtime Environment Corretto-11.0.6.10.1 (build 11.0.6+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.6.10.1 (build 11.0.6+10-LTS, mixed mode)
```

### OpenJDK 11.0.6
```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment 18.9 (build 11.0.6+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.6+10, mixed mode)
```

### Azul Zulu OpenJDK 11

```
openjdk version "11.0.5" 2019-10-15 LTS
OpenJDK Runtime Environment Zulu11.35+15-CA (build 11.0.5+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.35+15-CA (build 11.0.5+10-LTS, mixed mode)
```

**Review by alecharp — APPROVED** [review]

**Review by res0nance — APPROVED** [review]
LGTM, bonus points if you include @MarkEWaite suggestion on other distributions

**Comment by oleg-nenashev** [comment]
CI failed, so it is not ready to merge. Retriggering CI

**Comment by MRamonLeon** [comment]
The test failures are showing up on all PRs:

```
Could not transfer artifact org.apache.maven.plugins:maven-clean-plugin:jar:2.4.1 from/to central (http://repo1.maven.org/maven2): Error transferring file: Server returned HTTP response code: 501 for URL: http://repo1.maven.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.4.1/maven-clean-plugin-2.4.1.jar -> [Help 1]
```
I guess, it's not related to the changes, but infra problems

I will add the tests @MarkEWaite suggested

**Comment by timja** [comment]
> The test failures are showing up on all PRs:
> 
> ```
> Could not transfer artifact org.apache.maven.plugins:maven-clean-plugin:jar:2.4.1 from/to central (http://repo1.maven.org/maven2): Error transferring file: Server returned HTTP response code: 501 for URL: http://repo1.maven.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.4.1/maven-clean-plugin-2.4.1.jar -> [Help 1]
> ```
> 
> I guess, it's not related to the changes, but infra problems
> 
> I will add the tests @MarkEWaite suggested

It's not infra, it's tests,
FTR https://github.com/jenkinsci/jenkins/pull/4435

**Comment by MRamonLeon** [comment]
Then, I guess, all PRs are pending on https://github.com/jenkinsci/jenkins/pull/4435

**Review by varyvol — APPROVED** [review]

**Pull request merged**
