### PR TITLE
Code readability improvement

### PR DESCRIPTION
**Pull request by RaRe2604**
Adding few changes to make the code readable.

Code readability : If-else changed to Ternary operator
Code Readability and Performance : Used isEmpty() than equals
Code Readability : For loop to Streams

### CODE REVIEW

**Comment by RaRe2604** [comment]
@res0nance Can you please review this PR

**Review by sladyn98 — APPROVED** [review]
The code changes look good to me

**Comment by RaRe2604** [comment]
@jenkinsci/core-pr-reviewers Please review this PR

**Comment by Wadeck** [comment]
Not convinced such changes are really improving readability. It's more about IntelliJ-like complaints / information / advice that are applied automatically.

So +0 for me.

**Review by res0nance — COMMENTED** [review]
The usages of stream did not make the code any easier to read, in some instances it made it harder to read so -1

**Comment by daniel-beck** [comment]
> The usages of stream did not make the code any easier to read, in some instances it made it harder to read so -1

An argument could be made that it's easier to confirm the code works as expected, so I like it for new code. The benefit in rewriting existing code isn't really there though.

-0 from me for the merge conflict potential with LTS backports and security fix merges alone.

**Pull request closed without merging**
