### PR TITLE
Add periods to sentences

### PR DESCRIPTION
**Pull request by jsoref**
### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests

### Desired reviewers

### CODE REVIEW

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
This entry is a localization key, which is used in translations: https://github.com/jenkinsci/jenkins/blob/9ae584277fbcffc4045f67ad22d0ad6ee0821260/core/src/main/resources/jenkins/model/Jenkins/projectRelationship-help_da.properties

If you want  to add a dot, it's preferable to override the value in `projectRelationship.properties` for the default localization

**Comment by jsoref** [comment]
The localization key is used to hint "you need to update your translation".

The original text is wrong, in that it doesn't have a period, the translations are also wrong in that they too don't have periods.

I'm more than happy to update all the keys and translations to add periods if someone is comfortable w/ that.

But just adding a period to the english translation doesn't do anyone any favors -- it leaves all the other translations broken w/o a hint that they should do something.

**Review by batmat — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
@jsoref 
> I checked, and afaict no one has translated this string, which means my fix is the right thing to do today.

https://github.com/search?q=org%3Ajenkinsci+%22The+downstream+project+records+the+fingerprints+of+the+upstream+files+it+uses%22&type=Code

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
requesting changes according to the comment above

**Review by culmat — APPROVED** [review]

**Comment by jsoref** [comment]
Arg. The `\\` escaping keeps tripping me up.

Replacing the localization key is the right thing to do, otherwise some other localizer will incorrectly assume that they shouldn't have a `.`.

**Review by vilacides — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
ok. IMHO it is a bit overkill, but yes we can merge it now

**Comment by oleg-nenashev** [comment]
Will ship it to the next weekly if there is no negative feedback

**Review by batmat — APPROVED** [review]

**Comment by batmat** [comment]
:shipit:

**Review by varyvol — APPROVED** [review]

**Pull request merged**
