### PR TITLE
JENKINS-70169 Restore link to last breadcrumb

### PR DESCRIPTION
**Pull request by timja**
See [JENKINS-70169](https://issues.jenkins.io/browse/JENKINS-70169).

Alternative to https://github.com/jenkinsci/jenkins/pull/7525

### Testing done

Clicked the breadcrumb on the console log page.
Checked around a number of other pages like Plugin Manager, new item page etc

### Proposed changelog entries

- JENKINS-70169 Restore link to last breadcrumb

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

<a href="https://gitpod.io/#https://github.com/jenkinsci/jenkins/pull/7539"></a>

### CODE REVIEW

**Review by NotMyFault — APPROVED** [review]

**Comment by lemeurherve** [comment]
@timja here is the corresponding PR with this same fix included: https://github.com/jenkinsci/jenkins/pull/7491

I suppose you prefer to include only this fix?

**Comment by timja** [comment]
I am confident in the fix. I don't see any attempts by that pull request to get merged by 2.383, none of the people involved in the original pull request per requested for review or notified.

It's the Christmas period so I will not commit to anything but I am -1 for a revert of the original PR.

**Comment by basil** [comment]
The fact that https://github.com/jenkinsci/jenkins/pull/6912#issuecomment-1345193180 and #7525 remain unacknowledged for approximately one week does not give me confidence that others are actively paying attention to the content of weekly releases. The veto of #7525 in https://github.com/jenkinsci/jenkins/pull/7539#issuecomment-1359612272 does not contain a technical justification for why #7525 is bad, so by [Apache rules](https://www.apache.org/foundation/voting.html#Veto) it is invalid and has no weight. It also remains unclear to me whether https://github.com/jenkinsci/design-library-plugin/issues/182 was a preëxisting issue exposed by #6912 (and therefore hidden again by this PR) or an API change introduced by #6912 (and therefore still unsolved by this PR).

**Comment by NotMyFault** [comment]
> I am confident in the fix. 

I gave it a practical test earlier, and it does restore breadcrumbs missing breadcrumbs indeed, like outlined on the issue.

**Comment by timja** [comment]
> remain unacknowledged for approximately one week

> none of the people involved in the original pull request were requested for review or notified.


> so by [Apache rules](https://www.apache.org/foundation/voting.html#Veto) it is invalid and has no weight

This is the Jenkins project. Not the Apache project. 

https://github.com/jenkinsci/design-library-plugin/issues/182 was pre-existing and is an enhancement request not a blocker for anything.

**Comment by janfaracik** [comment]
Thanks for the fix @timja. I've just moved house in the last week (plus the joy of no internet) so I've had little time to spend on Jenkins.

**Review by janfaracik — APPROVED** [review]

**Comment by timja** [comment]
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Pull request merged**
