### PR TITLE
JENKINS-1962: Support rendering local time based on browser's formatting

### PR DESCRIPTION
**Pull request by rahulsom**
The earlier implementation relied on the server timezone. While this works for colocated teams, this is not great for distributed teams.

This change relies on passing milliseconds since epoch as an attribute to a HTML tag, and then using javascript on page load to set the body of the tag to a correctly formatted timestamp.

I'm very new to this part of Jenkins' code. I'm guessing there's a better place to place the javascript code. Please advise me on it, and I'll fix it.

See [JENKINS-1962](https://issues.jenkins-ci.org/browse/JENKINS-1962).

### Proposed changelog entries

* Timestamps rendered by Jenkins now depend on the browser timezone.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@Wadeck @jglick @daniel-beck @tfennelly 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by daniel-beck** [comment]
How does this relate to https://github.com/jenkinsci/jenkins/pull/4760?

**Comment by rahulsom** [comment]
> How does this relate to #4760?

@daniel-beck That expects the user to set it. To set it, the user needs to know about it. Even then, it stays pinned for users who travel. This lets the browser figure out what time it to display based on what the OS tells the browser its timezone is.

**Comment by daniel-beck** [comment]
This is convenient, but in my experience people use date/time to refer to builds, if everyone has different effective time zones, that makes it impossible. There also doesn't seem to be an opt-out for that.

Ideally there'd be a way to report into the session what the browser's time zone is, and otherwise integrate dynamic TZ into the existing feature (where people could enable/disable this).

**Comment by jglick** [comment]
FWIW the `timestamper` plugin lets you select server or browser timezones for absolute time display, as well as options irrelevant here (none, or relative to build start).

**Comment by rahulsom** [comment]
>  in my experience people use date/time to refer to builds,

I'll close this PR. Thanks!

**Pull request closed without merging**
