### PR TITLE
Lithuanian translation update

### PR DESCRIPTION
**Pull request by tomass**

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@rtyler @daniel-beck  Could you tweet about the desired review of this change?

**Comment by tomass** [comment]
Sorry, but what exactly do you mean by "tweet"? I have made some initial translations to check if this way of submitting translations is ok. If it is ok, I will continue with further translations.

**Comment by batmat** [comment]
Hi Tomas,
I think Oleg just means that we should use the @jenkinsci account to try
and find translation reviewers in many languages.

To Oleg: we've had a discussion about that a few days ago on IRC. In
summary Tyler is waiting for a blog entry to refer to it. I said I would
look into it soon, but if you can do it before no problem for me.
Le 8 févr. 2016 8:26 AM, "Tomas Straupis" <notifications@github.com> a
écrit :

**Comment by rtyler** [comment]
[shazam](https://twitter.com/jenkinsci/status/697810685737046016)

**Comment by tomass** [comment]
Is there any movement on this or is it stuck for some reason?

**Comment by batmat** [comment]
Hi @tomass we were actually just missing a review from someone speaking lithuanian.
I just went ahead and merged after I randomly checked some of your translations on google translate :-).

Thanks!

**Comment by batmat** [comment]
Btw, I also squashed your 4 commits into one as they seemed to me to be one logical change (and the exact same message for each commit kind of went in this direction).

**Comment by tomass** [comment]
Brilliant. Thank you.
My translations as such should be ok as I'm familiar with translation as such and Lithuanian terms. The only thing to be checked is java property file syntax - I have never done translations in such a way.

**Pull request merged**
