### PR TITLE
[JENKINS-33772] ID was not sufficiently unique for SezpozModule

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-33772](https://issues.jenkins-ci.org/browse/JENKINS-33772)

@reviewbybees esp. @kohsuke

### CODE REVIEW

**Comment by daniel-beck** [comment]
Tentative +.5 as the reported issue does not appear in the PR build.

**Comment by kzantow** [comment]
:bee: @jglick assuming plugin updates won't cause issues with duplicates

**Comment by jglick** [comment]
> assuming plugin updates won't cause issues with duplicates

Updates always force a restart, so I doubt that is a risk.

**Comment by kohsuke** [comment]
:bee:

**Pull request merged**
