### PR TITLE
Reduce heading for repeatable

### PR DESCRIPTION
**Pull request by jsoref**
See https://reports.jenkins.io/core-taglib/jelly-taglib-ref.html (n.b. the page doesn't seem to have been updated in over a year, but ... it's still a representative sample)

image

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Comment by daniel-beck** [comment]
Even h3 still seems a bit much, that's the size used for tags.

**Comment by jsoref** [comment]
h4? h5? I'm definitely open to suggestions.

**Comment by daniel-beck** [comment]
h3 seems appropriate 👍 Thanks for considering.

**Comment by jsoref** [comment]
Please add the squash me label :-)

**Review by daniel-beck — APPROVED** [review]

**Review by res0nance — APPROVED** [review]

**Comment by res0nance** [comment]
Merging in 24h if no negative feedback

**Review by oleg-nenashev — APPROVED** [review]
thanks for the fix!

**Pull request merged**
