### PR TITLE
Tests did not match naming pattern so were never being executed

### PR DESCRIPTION
**Pull request by stephenc**
Just a straightforward rename to a name that matches the inclusion rules

@jenkinsci/code-reviewers @reviewbybees @oleg-nenashev

### CODE REVIEW

**Comment by jtnord** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
They were working on my machine (c).

But 🐝

**Comment by stephenc** [comment]
@oleg-nenashev well they were not failing (because they were not being run)... works from an IDE with the old name... works from `mvn test -Dtest=SlaveTest2 -DfailIfNoTests=false` but will not be run otherwise...

**Comment by oleg-nenashev** [comment]
Please wait till the PR builder finishes next time.  just in case

**Pull request merged**
