### PR TITLE
@Ignore AtomicFileWriterPerfTest

### PR DESCRIPTION
**Pull request by batmat**
No JIRA nor changelog, trivial change. Causing recent build flakiness for no obvious reason (this test was added 1+ year ago).

### Submitter checklist

~~- [ ] JIRA issue is well described~~
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
~~- [ ] Appropriate autotests or explanation to why this change has no tests~~
~~- [ ] For dependency updates: links to external changelogs and, if possible, full diffs~~

### CODE REVIEW

**Review by jvz — APPROVED** [review]

**Review by Wadeck — COMMENTED** [review]
Not sure such approach is really good for the long run.

**Review by jtnord — APPROVED** [review]

**Comment by batmat** [comment]
I agree. I guess I _could_ just delete the test. I wanted to avoid this, but given the perf of the storage, there's probably no good way out. Or at some point introduce a profile for such flakes/things that require some normal environment. (if you check the comment around the test, you'll see that these perfs are absolutely horrible, it's like 3 times slower than an old 5400 RPM hard-disk)....

**Review by jglick — COMMENTED** [review]
Please just `@Ignore` this test so we are not bothered with it in CI.

**Review by varyvol — APPROVED** [review]

**Comment by batmat** [comment]
Right, so given @Wadeck and @jglick feedback, I've finally gone the `@Ignore` path, though I generally prefer to just delete tests in such case, but well. This test could be useful in the future for testing if someone changes AtomicFileWriter or so I suppose.

**Review by MRamonLeon — APPROVED** [review]

**Review by Wadeck — APPROVED** [review]

**Comment by batmat** [comment]
Given the implicit approval of @jglick (because he added that `@Ignore` too himself in https://github.com/jenkinsci/jenkins/pull/3799), and approvals from Ramon and Wadeck, I will likely merge this later today once the PR build is successful and if nobody objects in the meantime.

**Review by jglick — APPROVED** [review]

**Comment by batmat** [comment]
Superseded by https://github.com/jenkinsci/jenkins/pull/3799

**Pull request closed without merging**
