### PR TITLE
Stable 2.235.1

### PR DESCRIPTION
**Pull request by olivergondza**
Backporting has started and the RC is scheduled for 2020-06-03.

Please have look at the changes proposed ~and rejected~ so we have a consensus of what goes in by 2020-06-03.

Fixed
-----

JENKINS-62163   Major         2.236
- 'Available' plugin manager tab keeps showing "Plugin list is loading..." in IE11
- regression
- https://issues.jenkins-ci.org/browse/JENKINS-62163

JENKINS-61920   Major         2.237
- java.lang.ClassNotFoundException: javax.annotation.CheckForNull
- regression
- https://issues.jenkins-ci.org/browse/JENKINS-61920
  - Caused https://issues.jenkins-ci.org/browse/JENKINS-61926

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Review by MRamonLeon — APPROVED** [review]

**Review by bmunozm — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
These backports looks good, thanks!
I will check the changelog and check whether anything important is missing

**Comment by oleg-nenashev** [comment]
I would suggest to consider the following issues:

* [JENKINS-62181](https://issues.jenkins-ci.org/browse/JENKINS-62181) -  Fix a deadlock involving custom loggers during agent startup (regression in 2.231). https://github.com/jenkinsci/jenkins/pull/4714 from 2.238
** Why? regression which may impact many users
* Part of the [JENKINS-62231](https://issues.jenkins-ci.org/browse/JENKINS-62231) fix - Prevent Old Data Monitor from failing plugin loading in the case of class field unmarshalling issues. https://github.com/jenkinsci/jenkins/pull/4718 from 2.237
** Why? EC2 plugin downgrade had a nasty user experience. It would be great to improve the Jenkins core robustness, just in case a similar issue happens again

Maybe:

*  Ensure that job/folder creation routines properly check the requested name for invalid characters.  https://github.com/jenkinsci/jenkins/pull/4684 from 2.237
** Why? It is a relatively minor fix which was in the Jenkins core for 2+ weeks. I have no strong opinion about it, can be postponed until .2

**Comment by olivergondza** [comment]
Any other input on Oleg's suggestions?

**Comment by timja** [comment]
Agree with deadlock, unmarshalling would be nice, not sure if other is needed

**Comment by MarkEWaite** [comment]
On Wed, Jun 3, 2020 at 5:48 AM Oleg Nenashev <notifications@github.com>
wrote:

> I would suggest to consider the following issues:
>
>    - JENKINS-62181 <https://issues.jenkins-ci.org/browse/JENKINS-62181> -
>    Fix a deadlock involving custom loggers during agent startup (regression in
>    2.231). #4714 <https://github.com/jenkinsci/jenkins/pull/4714> from
>    2.238
>    ** Why? regression which may impact many users
>
> I agree this should be included

>
>    - Part of the JENKINS-62231
>    <https://issues.jenkins-ci.org/browse/JENKINS-62231> fix - Prevent Old
>    Data Monitor from failing plugin loading in the case of class field
>    unmarshalling issues. #4718
>    <https://github.com/jenkinsci/jenkins/pull/4718> from 2.237
>    ** Why? EC2 plugin downgrade had a nasty user experience. It would be
>    great to improve the Jenkins core robustness, just in case a similar issue
>    happens again
>
>
I agree this should be included

>
>
> Maybe:
>
>    - Ensure that job/folder creation routines properly check the
>    requested name for invalid characters. #4684
>    <https://github.com/jenkinsci/jenkins/pull/4684> from 2.237
>    ** Why? It is a relatively minor fix which was in the Jenkins core for
>    2+ weeks. I have no strong opinion about it, can be postponed until .2
>
>
I think this should wait for .2 because it is a relatively minor fix.

**Comment by olivergondza** [comment]
Thanks for the quick vote, I have backported https://issues.jenkins-ci.org/browse/JENKINS-62231 and https://issues.jenkins-ci.org/browse/JENKINS-62181.

**Review by res0nance — APPROVED** [review]

**Review by timja — APPROVED** [review]

**Pull request merged**
