### PR TITLE
[JENKINS-64931] no need to synchronize on Queue as queue is using a Lock and this under certain conditions can generate a deadlock. look at the dump attached to the issue JENKINS-64931

### PR DESCRIPTION
**Pull request by olamy**
See [JENKINS-64931](https://issues.jenkins-ci.org/browse/JENKINS-64931).

### Proposed changelog entries

* Prevent Jenkins queue deadlock when cancelling tasks under certain conditions .

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [x] There are at least 2 approvals for the pull request and no outstanding requests for change
- [x] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [x] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
Should be safe enough. The downside is that there might be new tasks allocated to executors in parallel with the cycle, but I assume it is "okay" taking the "may" in the argument

**Comment by daniel-beck** [comment]
> Fix possible deadlock when using FutureImpl#cancel (see attached dump JENKINS-64931)

Is that useful to anyone who isn't an experienced Java developer?

**Review by sladyn98 — APPROVED** [review]
If the queue has a lock, this change should be safe.

**Comment by olamy** [comment]
> > Fix possible deadlock when using FutureImpl#cancel (see attached dump JENKINS-64931)
> 
> Is that useful to anyone who isn't an experienced Java developer?

just to prove this issue can happen :) as  FutureImpl#cancel  is not used in jenkins core

**Review by MRamonLeon — APPROVED** [review]

**Comment by daniel-beck** [comment]
> just to prove this issue can happen :) as FutureImpl#cancel is not used in jenkins core

What I mean is, the changelog is for users/administrators, not developers.

Something like

> Fix a [potential / rare] deadlock involving the queue.

would be better for that audience IMO.

**Comment by oleg-nenashev** [comment]
Updated the changelog suggestion. I think we can move ahead with merging the fix.

We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

**Comment by timja** [comment]
This may have caused https://issues.jenkins.io/browse/JENKINS-65262, we started noticing it after upgrading to that version

**Comment by olamy** [comment]
for the record it's not related. (cc @timja)

**Pull request merged**
