### PR TITLE
[FIXED JENKINS-33037] Fixed malformed ranges in RangeSet.fromString()

### PR DESCRIPTION
**Pull request by pjanouse**
Fix for rejecting malformed ranges in
hudson.model.Fingerprint.RangeSet.fromString(...)

### CODE REVIEW

**Comment by olivergondza** [comment]
With unittest, I am +1 on merging this.

**Comment by batmat** [comment]
@olivergondza +1, add the `needs-testcase` label?

**Comment by pjanouse** [comment]
Actually, I've been working on that due to test coverage of CLI, I'll add TC soon here.

**Comment by pjanouse** [comment]
After all, the work was more complex. 

As mentioned in the JIRA, function is used directly for user input processing, so we have to be very strict and rigid during checking and validating. I hope, I've covered all possible options what the user can specify with all basic variants of invalid input.

**Pull request merged**
