### PR TITLE
Remove Java 11 `ClassNotFoundException` telemetry

### PR DESCRIPTION
**Pull request by basil**
See [#5656 (comment)](https://github.com/jenkinsci/jenkins/pull/5656#issuecomment-898226063). The Java 11 `ClassNotFoundException` telemetry added in #4003 stopped earlier this year. As a result, this is dead code. It has already caused problems once in #5398. More recently, I have been trying to unfork `AntClassLoader`, and I have discovered that the Java 11 `ClassNotFoundException` telemetry code in `AntClassLoader` is custom to our fork of `AntClassLoader` and cannot be upstreamed. This is an obstacle to unforking `AntClassLoader`. Whereas if this dead code is removed, then the obstacle no longer exists. So this PR is simply reverting #4003.

I suggest using the "Hide whitespace changes" feature when reviewing the changes to `AntClassLoader`.

### Proposed changelog entries

N/A

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] (If applicable) Jira issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

### CODE REVIEW

**Review by oleg-nenashev — COMMENTED** [review]
The main question to us is whether we will benefit from this code when working on Java 17 support. I would say that yes, it could be useful. If there is a way to reuse it for the ongoing experiments, I would rather vote for keeping it. CC @timja and @MarkEWaite 

AntClassLoader is a kernel of Jenkins classloading. TBH I do not see much need in unforking it, there are many performance and diagnosability improvements we could achieve by keeping it a part of the core. For example, #4957 . I think we could rename the class so the 'Ant' part is not confusing. WDYT @basil @jglick @jtnord ?

**Review by jtnord — APPROVED** [review]
`AntClassloader` upstream is pretty old and missing several modern features.  I want add support to our implementation to support parallel class loading when I get time, I think keeping our fork (SIC} is better for the project.

I have never looked at the java 11 telemetry, but have not been involved in any java 11 work. Talking about  Java 17 seems premature to me and if needed we can always revert this change later.

If you rename the `AntClassloader` you will break the Bouncy castle API plugin.

**Review by timja — APPROVED** [review]
> AntClassLoader is a kernel of Jenkins classloading. TBH I do not see much need in unforking it, there are many performance and diagnosability improvements we could achieve by keeping it a part of the core

I expect we will still have it in core, but only override any very specific changes we need for Jenkins

> The main question to us is whether we will benefit from this code when working on Java 17 support

I wouldn't have thought so and we can always re-add if required

**Comment by basil** [comment]
The plan, as described previously in #5656, is to make `jenkins.util.AntClassLoader` of `org.apache.tools.ant.AntClassLoader`. This allows us to maintain our own customizations without the maintenance burden of having to keep the whole class synchronized with upstream. This PR is the second to last part of that journey, not the first. I have previously filed #5617, #5635, #5650, and #5656 (as well as apache/ant#150 and apache/ant#151), for those who have not been following along.

> `AntClassloader` upstream is pretty old and missing several modern features. I want add support to our implementation to support parallel class loading when I get time

The last upstream change that has not yet been backported to our fork is [commit d37df73a8](https://github.com/apache/ant/commit/d37df73a8) from September 21, 2016, which adds parallel class loading support to `AntClassLoader`. Once this PR and #5656 are merged, I plan to backport that commit to our fork. That will bring our fork as close to the upstream main branch as is possible. Then, when upstream does a new release with apache/ant#150 and apache/ant#151 and Jenkins upgrades to it, I will remove the code duplication by implementing the subclassing described above.

Ironically, had my approach been taken from the very beginning, Jenkins would have had parallel class loading support since the release of Ant 1.10.0 on December 27, 2016. The only reason that we don't have it today is that we maintain our own fork of the class and nobody has backported upstream fixes (until my recent effort began).

> I think keeping our fork (SIC} is better for the project.

According to Wikipedia, "_sic_ may also be inserted derisively or sarcastically, to call attention to the original writer's spelling mistakes or erroneous logic, or to show general disapproval or dislike of the material." Not very nice, James. But if you're going to use _sic_, do it right: it's spelled in lowercase and takes square brackets rather than a parenthesis and a curly brace. Even better: if there is a flaw in my reasoning, then make a compelling argument rather than using derisive words like this.

**Comment by timja** [comment]
I don’t think it’s derisive or sarcastic (sic) according to my understanding but I don’t know why it was added, https://www.google.com/amp/s/www.urbandictionary.com/define.php%3Fterm%3D*sic*%26amp%3Dtrue

**Comment by basil** [comment]
> I don’t think it’s derisive or sarcastic […] according to my understanding but I don’t know why it was added

At minimum, it's an implication that the original post contained a mistake in spelling, punctuation, grammar, or logical reasoning. I don't appreciate that. Obviously my spelling and grammar are correct, in contrast to the incorrectly capitalized and punctuated "(SIC}". The point about wanting parallel classloading ironically supports the direction I am taking rather than maintaining a fork without the upstream change to enable parallel classloading. Cleaning up 17-year-old technical debt like this is emotionally draining enough without also dealing with the constant stream of negativity and nit-picking in code reviews. To quote Kohsuke from another PR: "I appreciate your code review, but let's focus on important things here." I have even loftier goals, like eventually moving away from `AntClassLoader` to a subclassed `URLClassLoader`. Let's get these PRs approved and merged with a minimum amount of fuss so that I can move forward with this effort and reduce our maintenance burden going forward.

**Comment by jtnord** [comment]
> The plan, as described previously in #5656, is to make jenkins.util.AntClassLoader a subclass of org.apache.tools.ant.AntClassLoader.

Where best to have this discussion? Currently the class loader details are internal to Jenkins (with the exception of bouncy castle API plugin which ignores the restriction) As the class loader from upstream is not Restricted it then becomes exposed and part of an API.  We should be trying to remove things from Jenkins not add more IMO.
There has been investigation to not expose Jenkins library classes to plugins that works well at runtime, but not at development time 😕

As is, and to restate my approval from above,  I am ok with this pr.

**Comment by timja** [comment]
> Where best to have this discussion?

dev Mailing list?

**Review by jglick — APPROVED** [review]
> whether we will benefit from this code when working on Java 17 support. I would say that yes, it could be useful.

YAGNI. If and when we want to reinject similar telemetry, there is always Git history.

**Comment by oleg-nenashev** [comment]
I need to think more about this PR before approving it. I am not blocking it, and personally I ask folks to be kind to each other. All of us want to improve Jenkins and to cleanup technical debt.

I just ask other core maintainers to give @MRamonLeon some time to respond. He is currently on vacation, I will discuss this PR with him on Wednesday.

**Comment by timja** [comment]
> I just ask other core maintainers to give @MRamonLeon some time to respond. He is currently on vacation, I will discuss this PR with him on Wednesday.

@MRamonLeon / @batmat waiting for you atm, any thoughts please?

**Review by MRamonLeon — APPROVED** [review]

**Comment by timja** [comment]
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

**Pull request merged**
