### PR TITLE
[FIXED JENKINS-25234] Improve readability of the 'schedule build' toolti...

### PR DESCRIPTION
**Pull request by petermarcoen**
As suggested in https://issues.jenkins-ci.org/browse/JENKINS-25234 
This avoids confusion as to which job will be build.

### CODE REVIEW

**Comment by daniel-beck** [comment]
Not localizable. Should be `${%Schedule_a_build(job.fullDisplayName)}` or something like that, with corresponding changes to localized texts.

**Comment by petermarcoen** [comment]
Thanks for the feedback Daniel.

For the localization, I made the modifications you suggested. I also updated all the locale files. 
I tried my best to find a correct translation for "for {jobname}", when in doubt I used ": {jobname}" instead, I hope that's allright.

I'm not sure about the relative display name, after putting a job in a folder job.fullDisplayName shows the folder name already. The documentation seems to comfirm this:

getFullDisplayName: Works like getDisplayName() but return the full path that includes all the display names of the ancestors. (http://javadoc.jenkins-ci.org/hudson/model/Item.html#getFullDisplayName())

Please take a look at the following print screens:

http://imgur.com/9ooB9vk,jsXYfOD#0 (English)
http://imgur.com/9ooB9vk,jsXYfOD#1 (Dutch, my mother tongue)

**Comment by daniel-beck** [comment]
> I'm not sure about the relative display name, after putting a job in a folder job.fullDisplayName shows the folder name already.

That's my point. If you're in a folder (Cloudbees Folder Plugin) named *Foo*, the job *Bar*, whose full name is then *Foo/Bar*, will be shown as *Bar* in the job name column, but yours shows *Foo » Bar* instead. I think that it should not, for consistency.

**Comment by petermarcoen** [comment]
Ow okay, I thought you meant the other way around.
I changed this now so that it uses the same name as in the Job column: h.getRelativeDisplayNameFrom(job, itemGroup))

Example: http://i.imgur.com/rev8qQO.png

**Comment by daniel-beck** [comment]
Looks good. I wonder whether it should be *for* or *of*, but that's minor enough.

Anyone else have an opinion on this PR?

**Comment by olivergondza** [comment]
LGTM

**Pull request merged**
